### ISSUE TITLE
[Feature]: Configurable colors highlight

### ISSUE THREAD

**Issue by deryrahman** [LunarVim/LunarVim#1062]
### Feature motivation

If we want to override the default colors highlight, we need to create some additional config on `lv-config.lua`. But somehow, it would make `lv-config.lua` looks ugly. The feature is quite general I think. I see so many people prefer to change the colors to match their preferences. So, it would be great if we can easily override colors highlight directly from lunarvim config.

### Describe the expected solution

Additional config

```lua
-- ...
O.colors_highlight = {
    Visual = { bg="#222222" },
    VimWikiHeader1 = {  fg="#dddddd", bg="#111111" },
},
-- ...
```

Make sure this color's config is called after plugins and colorschema are fully loaded.

### Describe the alternatives you've considered

First I've already implemented the solution inside `lv-config.lua`. It's quite obvious and easy.

```lua
-- Colors
local highlights = {
	Visual = { bg = "#858585" },
}

function highlight(group, properties)
    local bg = properties.bg == nil and "" or "guibg=" .. properties.bg
    local fg = properties.fg == nil and "" or "guifg=" .. properties.fg
    local style = properties.style == nil and "" or "gui=" .. properties.style

    local cmd = table.concat({
        "highlight", group, bg, fg, style
    }, " ")

    vim.api.nvim_command(cmd)
end

for group, properties in pairs(highlights) do
    highlight(group, properties)
end
```

But it didn't work when the first time lv opened. Once I triggered the config save, it works. After some research, I found that the `colors` folder is loaded after `lv-config.lua`.  Thus, the colors highlight I've been set before are not applied.

I also did some refactor to make that function called after colorschema has loaded. But, end up messing up the nvim's runtime order. Trying to simply put colorschema set before the `lv-config.lua` set in `init.lua` also didn't work. The `colors` folder is called somewhere

**Comment by sa-mendez** [comment]
I think working your solution into lunar vim would be good.

In the short term, you can get the highlighting to work using auto-commands.  Here is what I did in my lv-config:

```lua
-- Autocommands (https://neovim.io/doc/user/autocmd.html)
O.user_autocommands = {
  { "ColorScheme", "*", "hi CursorLine guibg=#2c200d" },
  { "ColorScheme", "*", "hi Search guibg=#aa6a2c guifg=wheat" },
}
```

Come to think of it, you can probably just update your highlight function to just use auto commands instead, and it should work to provide the functionality generically like you want.

**Comment by ChristianChiarulli** [comment]
colorscheme is in lua, require it and change the values, should work in theory right?

**Comment by sa-mendez** [comment]
Yes, that would be the most direct approach.  But the moment you switch your colorscheme, you would have to go back and edit it.  Using the auto commands allows you to treat your highlight choices as overrides independent of the chosen color scheme.

**Comment by deryrahman** [comment]
Great @sa-mendez , I have tried it, and it works! I made a pull request for that https://github.com/ChristianChiarulli/LunarVim/pull/1065. Any feedbacks are welcome.

I also tried to refactor the colors folder, so any lvim colorscheme would be more manageable, please take a look @ChristianChiarulli

**Comment by abzcoding** [comment]
the colorscheme has changed a lot, not sure if this is applicable anymore or not, feel free to reopen it

**Comment by dgmora** [comment]
@abzcoding So is there a "right way" to do this, aside from autocommands? Overriding certain highlights from the configuration sounds like something normal and that should be possible

**Comment by abzcoding** [comment]
not sure if this would be the right way or not, but besides autocmds you can create a file under `~/.config/lvim/after/plugin`
and do your highlights there, for example
https://github.com/abzcoding/lvim/blob/main/after/plugin/symbols-outline.vim

**Comment by sbzi1020** [comment]
Hi, I just fixed this issue, I hope this can help :-)
```
vim.api.nvim_create_autocmd("FileType", {
    pattern = "*",
    callback = function()
        print ">>> Set my custom cursor line color:)"
        vim.cmd 'hi CursorLine guifg=NONE guibg=#424141 ctermbg=NONE gui=NONE cterm=NONE'
    end,
})
```
