### ISSUE TITLE
[Feature]: Support clangd switch_source_header command

### ISSUE THREAD

**Issue by gikari** [LunarVim/LunarVim#1063]
### Feature motivation

Clangd LSP [supports](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#clangd) `switch_source_header` command. It would be nice to support this with a keybinding (for example `<leader>l<h>`), but only for C++ LSP.

**Comment by kylo252** [comment]
Hey this is provided by default by [lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/clangd.lua). The command is `:ClangdSwitchSourceHeader` which you can just map directly.

**Comment by gikari** [comment]
> Hey this is provided by default by [lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/clangd.lua). The command is `:ClangdSwitchSourceHeader` which you can just map directly.

Thanks, didn't know that, but how do I do that for only C++ files, where clangd loads, and keep it NOP for everything else? Does the lsp mappings behave similarly? Seems nontrivial.

**Comment by kylo252** [comment]
You would ideally have it in the `on_attach` callback. Sadly we only have the API for the `common_on_attach`. So you need to manually change it for clangd specifically.

**Comment by gikari** [comment]
> You would ideally have it in the `on_attach` callback. Sadly we only have the API for the `common_on_attach`. So you need to manually change it for clangd specifically.

Sadly, I do not understand how to do that 😢. Seems like it is a good reason to include this snippet in the config as a comment or provide the entire feature for clangd out of the box.

**Comment by abzcoding** [comment]
@gikari can you test adding this to your `~/.config/lvim/lv-config.lua`:
```lua
lvim.autocommands.custom_groups = {
  { "Filetype", "cpp", "nnoremap <leader>lh <Cmd>ClangdSwitchSourceHeader<CR>"},
}
```

**Comment by gikari** [comment]
@abzcoding it does work, however: it becomes enabled when I navigate to cpp file, but stays available even if I navigate to a file with a different file type (e.g. lua). Also, this approach does not allow a nice message in WhichKey (Btw, it would be nice to have a feature to make WhichKey bindings for a particular filetype too).

**Comment by rebuilt** [comment]
You have to add the keybinding to the local buffer only.

**Comment by rebuilt** [comment]
```
"map <buffer> <leader>lh <Cmd>ClangdSwitchSourceHeader<CR>"
```

**Comment by gikari** [comment]
> ```
> "nmap <buffer> <leader>lh <Cmd>ClangdSwitchSourceHeader<CR>"
> ```

That works, thanks. Still no custom WhichKey message, though.

**Comment by rebuilt** [comment]
I think whichkey registers leader bindings before that autocommand has a chance to run.

**Comment by rebuilt** [comment]
We are going to walk on the wild side here.  This is going to be super experimental.   

Place this in your `lv-config.lua`
```
lvim.autocommands.custom_groups = {
	{ "Filetype", "lua", "lua require('lv-user').bind_cpp_keys()" },
}

```

Create the following file `~/.local/share/lunarvim/lvim/lv-user/init.lua`
And place this code inside

```
local M = {}
M.bind_cpp_keys = function()
  vim.cmd "nnoremap <buffer> <leader>lh <Cmd>ClangdSwitchSourceHeader<CR>"
  lvim.builtin.which_key.mappings["l"] = {
    name = "LSP",
    a = { "<cmd>lua vim.lsp.buf.code_action()<cr>", "Code Action" },
    d = {
      "<cmd>Telescope lsp_document_diagnostics<cr>",
      "Document Diagnostics",
    },
    w = {
      "<cmd>Telescope lsp_workspace_diagnostics<cr>",
      "Workspace Diagnostics",
    },
    -- f = { "<cmd>silent FormatWrite<cr>", "Format" },
    f = { "<cmd>lua vim.lsp.buf.formatting()<cr>", "Format" },
    i = { "<cmd>LspInfo<cr>", "Info" },
    j = {
      "<cmd>lua vim.lsp.diagnostic.goto_next({popup_opts = {border = lvim.lsp.popup_border}})<cr>",
      "Next Diagnostic",
    },
    k = {
      "<cmd>lua vim.lsp.diagnostic.goto_prev({popup_opts = {border = lvim.lsp.popup_border}})<cr>",
      "Prev Diagnostic",
    },
    l = { "<cmd>silent lua require('lint').try_lint()<cr>", "Lint" },
    q = { "<cmd>Telescope quickfix<cr>", "Quickfix" },
    r = { "<cmd>lua vim.lsp.buf.rename()<cr>", "Rename" },
    s = { "<cmd>Telescope lsp_document_symbols<cr>", "Document Symbols" },
    S = {
      "<cmd>Telescope lsp_dynamic_workspace_symbols<cr>",
      "Workspace Symbols",
    },
    h = { "<Cmd>ClangdSwitchSourceHeader<CR>", "Clangd Switch Source Header" },
  }
end

return M


```
@abzcoding

**Comment by kylo252** [comment]
Try this 

```lua
lvim.builtin.which_key.mappings["lh"] = {
  function()
    local buf = vim.api.nvim_get_current_buf()
    local ft = vim.api.nvim_buf_get_option(buf, "filetype")
    if ft == "c" or ft == "cpp" then
      vim.cmd [[ClangdSwitchSourceHeader]]
    end
  end,
  "Go To Header",
}
```

Reference https://github.com/folke/which-key.nvim/issues/135#issuecomment-883158839

**Comment by rebuilt** [comment]
@kylo252 

Oh that's much better

**Comment by gikari** [comment]
> Try this
> 
> ```lua
> lvim.builtin.which_key.mappings["lh"] = {
>   function()
>     local buf = vim.api.nvim_get_current_buf()
>     local ft = vim.api.nvim_buf_get_option(buf, "filetype")
>     if ft == "c" or ft == "cpp" then
>       vim.cmd [[ClangdSwitchSourceHeader]]
>     end
>   end,
>   "Go To Header",
> }
> ```
> 
> Reference [folke/which-key.nvim#135 (comment)](https://github.com/folke/which-key.nvim/issues/135#issuecomment-883158839)

Nah. This does not work as expected. It shows the legend "Go To Header" in any buffer, no matter CPP or not.


> We are going to walk on the wild side here. This is going to be super experimental.
> 
> Place this in your `lv-config.lua`
> 
> ```lua
> lvim.autocommands.custom_groups = {
> 	{ "Filetype", "lua", "lua require('lv-user').bind_cpp_keys()" },
> }
> ```
> 
> Create the following file `~/.local/share/lunarvim/lvim/lv-user/init.lua`
> And place this code inside
> 
> ```lua
> local M = {}
> M.bind_cpp_keys = function()
>   vim.cmd "nnoremap <buffer> <leader>lh <Cmd>ClangdSwitchSourceHeader<CR>"
>   lvim.builtin.which_key.mappings["lh"] = {
>     "<Cmd>ClangdSwitchSourceHeader<CR>",
>     "Clangd Switch Source Header",
>   }
> end
> 
> return M
> ```
> 
> @abzcoding

This does not work at all. If I keep the "lua" extension in the autocommands, it shows the following on lua file loading:
```
Error detected while processing FileType Autocommands for "lua":
E5108: Error executing lua [string ":lua"]:1: module 'lv-user' not found:
        no field package.preload['lv-user']
        no file './lv-user.lua'
        no file '/usr/share/luajit-2.0.5/lv-user.lua'
        no file '/usr/local/share/lua/5.1/lv-user.lua'
        no file '/usr/local/share/lua/5.1/lv-user/init.lua'
        no file '/usr/share/lua/5.1/lv-user.lua'
        no file '/usr/share/lua/5.1/lv-user/init.lua'
        no file '/home/gikari/.cache/nvim/packer_hererocks/2.0.5/share/lua/5.1/lv-user.lua'
        no file '/home/gikari/.cache/nvim/packer_hererocks/2.0.5/share/lua/5.1/lv-user/init.lua'
        no file '/home/gikari/.cache/nvim/packer_hererocks/2.0.5/lib/luarocks/rocks-5.1/lv-user.lua'
        no file '/home/gikari/.cache/nvim/packer_hererocks/2.0.5/lib/luarocks/rocks-5.1/lv-user/init.lua'
        no file './lv-user.so'
        no file '/usr/local/lib/lua/5.1/lv-user.so'
        no file '/usr/lib/lua/5.1/lv-user.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/gikari/.cache/nvim/packer_hererocks/2.0.5/lib/lua/5.1/lv-user.so'
```
 If I change it to cpp:
```lua
> lvim.autocommands.custom_groups = {
> 	{ "Filetype", "cpp", "lua require('lv-user').bind_cpp_keys()" },
> }
```

Clangd breaks (It is not listed in the ```:LspInfo``` at all) and no error message is printed.

**Comment by kylo252** [comment]
> Nah. This does not work as expected. It shows the legend "Go To Header" in any buffer, no matter CPP or not.

This honestly feels like a which-key issue/bug/limitation. I'm not sure how else to solve this while still showing a dynamic entry for it in which-key. I'm sure it's nice to have a super neat keymap list but we, and everyone else basically, have the same issue where some mappings are shown out of context. 

BTW, you can should now be able to override `on_attach` for `clangd`, but I think there's something weird happening there that we need to investigate.

**Comment by rebuilt** [comment]
It seems to work.  

![conditional mappings](https://user-images.githubusercontent.com/16025007/127353863-0eccec9f-1e84-4a53-8ac7-f91ab56b15b4.gif)

**Comment by rebuilt** [comment]
I can't actually test the cpp action.  I don't develop in cpp.  But conditionally adding a mapping is there.   I've contained the files to just my own lvim folder.  I put it in this branch https://github.com/rebuilt/lvim/tree/conditional-whichkey

**Comment by rebuilt** [comment]
It should work without mucking about in lv-user.  I'd forgotten that's still a gitignored folder.

**Comment by Rido-o** [comment]
I don't use lunar vim and am not entirely sure how it works but would something along these lines work?
https://github.com/folke/which-key.nvim/issues/135#issuecomment-897595196

**Comment by Rido-o** [comment]
After a bit more tinkering I managed to come up with this that should fix the problem of keybinds following you into new buffers
```lua
local wk = require('which-key')
local bufNo = vim.api.nvim_buf_get_number("%")

vim.cmd('autocmd FileType cpp lua WhichKeyCpp(' .. bufNo .. ')')
function WhichKeyCpp(bufNumber)
    wk.register({
        ['<leader>lh'] = {'<Cmd>ClangdSwitchSourceHeader<CR>', 'Clangd Switch Source Header'}
    }, { buffer = bufNumber })
end
```
Theres probably a more elegant way of doing it, but hopefully this helps to address your problem

**Comment by Garzet** [comment]
Anyone managed to make a file open in a split or another tab?

**Comment by abzcoding** [comment]
you might use `nvim_get_current_buf()` or maybe `vim.uri_to_bufnr(uri)`
