### ISSUE TITLE
[Feature]: Create `:LvimLspInfo`

### ISSUE THREAD

**Issue by kylo252** [LunarVim/LunarVim#1187]
# Description

It would be nice to create a custom `LspInfo` like `LspInfoExtended` or `LvimLspInfo` or something. It would show what we should have setup in case there's a problem. This can also show and some other internal info about the config parameters that were sent to the language server.

After merging #1086 we would be to retrieves a list of the currently used null-ls providers by filetype.

## Some Ideas of what such a function could include

@rebuilt 
> - Which formatter/linter is actually being used
> - Formatter/linter options for that specified filetype
> - Attached lsp servers.
> - The output of :messages.
> - The output of grep ERROR ~/.cache/nvim/lsp.log  and also maybe the other log files (dap.log, packer.nvim.log)  
> - The output of :checkhealth 
> - lspconfig The output of :checkhealth treesitter
> - The important bits from nvim -v
> - Missing default plugins.

**Comment by rebuilt** [comment]
Maybe also the git commit id.

**Comment by rebuilt** [comment]
Anything in here useful?  https://github.com/nvim-lua/lsp-status.nvim
