### ISSUE TITLE
[Bug]:   Can't jump to prev/next snippet's placeholder using <(s-)tab>

### ISSUE THREAD

**Issue by mbalazy** [LunarVim/LunarVim#1228]
### Problem description

1. Open some file (example: MyComponent.tsx)
2. Invoke :VsnipOpen 
3. Edit or create new snippet **with tabstops**. For eg:
`    "import": {
        "body": [
            "import $1 from '$2'"
        ],
        "description": "imoprt component",
        "prefix": [
            "imi"
        ]
    }`
4. Reopen MyComponent.tsx
5. Type `imi`
6. Select new created snippet from compe
7. Pres `<tab>`
8. Cursor don't jump to next step, behaves like like space.

### LunarVim version

rolling 7cd03f

### Neovim version (>= 0.5)

0.6

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by daniel-vera-g** [comment]
I am testing lunarvim on master and can observe something similar.
Using snippets in `ts` files works as expected with `<tab>`. On Markdown files,`<tab>` behaves like a space. F.ex with the `link` snippet.

**Comment by mbalazy** [comment]
In my case I have no problem with snippets in `.tsx` files on master. 
I just checked past commits on rolling:

213e39 - no problem with tabstops in snippets
d7595f - from this commit tabstops are broken.

**Comment by ChristianChiarulli** [comment]
3da49e4be455d72d2a69fb76472c1f022815681b fixes this
