### ISSUE TITLE
[Bug]: Rolling and master install failing

### ISSUE THREAD

**Issue by alechp** [LunarVim/LunarVim#1235]
### Problem description

- As recent as 2 weeks ago I had to do a fresh LunarVim install and it worked. Ran into some issues, but got it working
- Initially had lspinstall issues, vim.uri module not found and other issues

NOTE: Still debugging this. Will update this issue with my findings. Might be user error, but figured best to record since the fix isn't super intuitive 

### Steps to reproduce:
1. Download and compile latest neovim version
2. Remove existing lunarvim (also tried with/without manually archiving nvim dir)
3. Try one line install
4. Fail, uninstall
5. Try manual master clone install
6. Fail, uninstall
7. Try rolling clone install
8. Fail, uninstall
9. Try manual for Mac (lua, node, [...], treesitter, neovim, neovim-remix, [...], clone plugins, clone lunarvim , create config file

Currently investigating possible issue with neovim in healthchecks. Going to open this issue now though to document my progress

### LunarVim version

stable

### Neovim version (>= 0.5)

0.6

### Screenshots
<details>
<summary>Details</summary>

1. The cp instruction re: "config.example.lua" in install docs is outdated. Shows "lv-config.example.lua" after install:

![Screen Shot 2021-08-03 at 4 35 04 PM-1](https://user-images.githubusercontent.com/3058939/128240991-3c71d236-2121-4ee0-a1ac-8e52fcc47c3b.png)

1.5. The --branch flag is wrong in docs (probably encoding issue with someone's file editor that caused initial problem, but should be --branch instead of -branch 

2. After running lvim, I've tried both PackerSync and PackerInstall... both fail. Exits lvim and terminal starts acting weird. Have replicated this exact effect through multiple installs... Doesn't like Packer
![image](https://user-images.githubusercontent.com/3058939/128241135-6d4f7305-cf6e-4395-b2af-66c40581e1e1.png)

![image](https://user-images.githubusercontent.com/3058939/128241314-c0ba0609-37ec-4f32-a3c2-572581a43e06.png)

3. Originally had neovim 0.5. Tried updating to 0.6. No dice
<img width="169" alt="Screen Shot 2021-08-04 at 12 16 02 PM" src="https://user-images.githubusercontent.com/3058939/128241436-910dee7a-3514-477e-8bbe-8b6e55ba16d0.png">

4. Tried manually removing the plugin directory, like mentioned here: https://github.com/ChristianChiarulli/LunarVim/issues/1180#issuecomment-890207674
![image](https://user-images.githubusercontent.com/3058939/128241674-c5b75aa6-605a-485f-a49d-088ede368eba.png)

</details>

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
can you test running this
```shell
curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh | LVBRANCH=rolling bash -s -- --overwrite
```

**Comment by alechp** [comment]
What I see when running stable install (first all-in-one shell script):
```
/dev/fd/11: line 102: 33811 Abort trap: 6           nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim" --headless +'autocmd User PackerComplete sleep 100m | qall' +PackerInstall
```


<img width="832" alt="Screen Shot 2021-08-04 at 12 31 37 PM" src="https://user-images.githubusercontent.com/3058939/128243454-6ab01a06-1dab-4a6a-97d5-b21521fca8be.png">

<img width="788" alt="Screen Shot 2021-08-04 at 12 32 08 PM" src="https://user-images.githubusercontent.com/3058939/128243513-eeb5dd8b-834f-4cd4-8cea-02743f6bf777.png">

**Comment by abzcoding** [comment]
> can you try running this
> 
> ```shell
> curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh | LVBRANCH=rolling bash -s -- --overwrite
> ```
@alechp 
can you run this one as well, and take screenshots, so we can get to the bottom of this
**WARNING: backup your ~/.config/nvim folder if you need it**

**Comment by alechp** [comment]
:checkhealth showing python module missing. I already ran the pip install from manual install, but doing that again

<img width="832" alt="Screen Shot 2021-08-04 at 12 35 14 PM" src="https://user-images.githubusercontent.com/3058939/128243914-1f4f228c-f00b-4013-9a02-b74cb5ea22a6.png">

<img width="832" alt="Screen Shot 2021-08-04 at 12 35 50 PM" src="https://user-images.githubusercontent.com/3058939/128243968-8de22a85-cb94-451b-bab5-45efd77b4fd5.png">

Uninstalled lunarvim again

Manually installing mac
<img width="798" alt="Screen Shot 2021-08-04 at 12 37 11 PM" src="https://user-images.githubusercontent.com/3058939/128244157-5bb1e165-ea5e-4472-8691-f2681b7e00a1.png">

<img width="832" alt="Screen Shot 2021-08-04 at 12 36 46 PM" src="https://user-images.githubusercontent.com/3058939/128244107-15ed2423-0305-457d-8901-d8b89c574681.png">

Looks like ueberzerg is throwing, trying again without ueberzerg (since on Mac) to double check other deps
<img width="1552" alt="Screen Shot 2021-08-04 at 12 38 25 PM" src="https://user-images.githubusercontent.com/3058939/128244298-34727405-182a-4f67-8c16-63fab950d14b.png">

Yes removing ueberzug fixes issue
 <img width="1552" alt="Screen Shot 2021-08-04 at 12 39 11 PM" src="https://user-images.githubusercontent.com/3058939/128244397-25ddb87d-8574-4cd3-9eb4-e20297167627.png">

Cloning plugs
<img width="1552" alt="Screen Shot 2021-08-04 at 12 40 09 PM" src="https://user-images.githubusercontent.com/3058939/128244485-6e1b3554-6109-4207-a1a7-4a9715123fd4.png">

**Comment by alechp** [comment]
When I run `lvim` checkhealth warns me about init.vim missing in .config/nvim even though init.lua is present

<img width="1552" alt="Screen Shot 2021-08-04 at 12 50 22 PM" src="https://user-images.githubusercontent.com/3058939/128245805-a21d31e6-1ee4-480c-86e0-1351fd758a7c.png">

<img width="1552" alt="Screen Shot 2021-08-04 at 12 49 47 PM" src="https://user-images.githubusercontent.com/3058939/128245699-9d2d15ea-66c9-495d-a311-a0494d106d79.png">


When I try removing plugin dir and running PackerSync, still get weird packer error (ie. closes out of lvim)
<img width="399" alt="Screen Shot 2021-08-04 at 12 57 17 PM" src="https://user-images.githubusercontent.com/3058939/128246499-c19e57dc-af7f-4581-84b7-287aa06a6263.png">

<img width="1552" alt="Screen Shot 2021-08-04 at 12 57 09 PM" src="https://user-images.githubusercontent.com/3058939/128246551-d165997b-31d3-4ec1-8443-07561f6658dd.png">

**Comment by rebuilt** [comment]
Can you try running with and without the `exec` at the front of this:

```
exec nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim" "$@"

```
We added `exec` to the start of the executable since this pull request.  https://github.com/LunarVim/LunarVim/pull/1203

**Comment by kylo252** [comment]
In addition to what's been said, I have a few suggestions but I need to clear up some suspicions first. Can you run:

```shell
where nvim
which nvim
```

I want to make sure you don't have two separate binaries. I would also like to see the output of

```shell
ls -la /bin/sh
```

**Comment by alechp** [comment]
> Can you try running with and without the `exec` at the front of this:
> 
> ```
> exec nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim" "$@"
> ```
> 
> We added `exec` to the start of the executable since this pull request. #1203

Tried this with rolling and stable (uninstalling between runs) and neither worked. When I tried running PackerSync, instead of terminal spazzing out/distorting characters, it just closed the terminal outright

<img width="1552" alt="Screen Shot 2021-08-04 at 1 07 21 PM" src="https://user-images.githubusercontent.com/3058939/128247900-ade05ed5-1632-40a2-9f84-f3ff8ba105c6.png">

This popped up when I ran. Made me think it could be a chmod/sudo issue, but when I look, file simply isn't there:
<img width="1552" alt="Screen Shot 2021-08-04 at 1 10 13 PM" src="https://user-images.githubusercontent.com/3058939/128248130-885b6217-90ef-4f93-9511-5856916858d7.png">

For good measure, tried uninstall land reinstalling; this time with rolling (since PR was merged 3 days ago, not sure if in stable yet). This is what I see on :checkhealth
<img width="1552" alt="Screen Shot 2021-08-04 at 1 12 02 PM" src="https://user-images.githubusercontent.com/3058939/128248300-d7a249b9-a318-4d5e-ae0c-96f5185c0d0d.png">

> In addition to what's been said, I have a few suggestions but I need to clear up some suspicions first. Can you run:
> 
> ```shell
> where nvim
> which nvim
> ```
> 
> I want to make sure you don't have two separate binaries. I would also like to see the output of
> 
> ```shell
> ls -la /bin/sh
> ```

<img width="832" alt="Screen Shot 2021-08-04 at 1 06 35 PM" src="https://user-images.githubusercontent.com/3058939/128248144-8b2f773d-7589-49e3-8fa6-bafb22d7e721.png">

**Comment by kylo252** [comment]
So what I think the problem is that we need to clean Packer's environment. You **need** to make sure you've deleted all of these folders (feel free to back them up): 

```shell
rm -rf ~/.local/share/lunarvim/site
rm -rf ~/.config/lvim/plugin
rm -rf ~/.cache/nvim
rm -rf ~/.local/share/nvim/shada
```

Now when you start `lvim` again, you should see that `Packer` will try to clone itself first, after that you can do either `:PackerInstall` or `:PackerSync` followed by `:PackerCompile` and then restart `lvim`

Some stuff are a bit too complicated due to Packer's lazy-loading workflow. Sorry about that.

**Comment by alechp** [comment]
It does trigger Packer lazyload after I remove those 4 dirs. 
<img width="832" alt="Screen Shot 2021-08-04 at 3 01 50 PM" src="https://user-images.githubusercontent.com/3058939/128261099-c929dad3-c62d-4103-b229-d864772b2e2f.png">


But I can't run PackerInstall or PackerSync without terminal spazzing

<img width="832" alt="Screen Shot 2021-08-04 at 3 01 57 PM" src="https://user-images.githubusercontent.com/3058939/128261120-8e311365-eec2-414f-a988-657ec426fcea.png">


<img width="832" alt="Screen Shot 2021-08-04 at 3 02 24 PM" src="https://user-images.githubusercontent.com/3058939/128261231-f0f8563f-c681-4b81-8260-01651cfbc977.png">


Can't imagine this matters, but this is my terminal version:
<img width="391" alt="Screen Shot 2021-08-04 at 3 03 47 PM" src="https://user-images.githubusercontent.com/3058939/128261264-9f5e9294-a467-4f47-89b1-ecb21eecf178.png">


macOS v11.2.3

**Comment by kylo252** [comment]
I want to isolate the issue, can you try the steps included in [neovim/nvim-lspconfig#debugging](https://github.com/neovim/nvim-lspconfig#debugging): 
> If you have an issue with lspconfig, the first step is to reproduce with a minimal configuration.
> ...

It will verify that a minimal configuration for both packer and lspconfig works as expected.

**Comment by abzcoding** [comment]
closed due to inactivity, feel free to reopen this issue if it still exists ( also please respond to what kylo252 said 😢 )

**Comment by alechp** [comment]
### On current (failing) version of LunarVim (trying to install on laptop):
- Retried with rolling install version on 0.6 neovim and still failing
- nvim directory not being generated (idk if that matters or not in newest version of LunarVim)
- bunch of module installs fail 
- no LSP client
- macOS v11.5.1

### On previous (working) version (currently using on desktop):
- nvim directory exists
- No lvim directory
- LSP works, modules found, etc 
- macOS v10.15.7

### Screenshots
<img width="1552" alt="Screen Shot 2021-08-23 at 5 50 07 AM" src="https://user-images.githubusercontent.com/3058939/130451456-d1a10710-923b-416a-84eb-f93a57a6f956.png">
<img width="1552" alt="Screen Shot 2021-08-23 at 5 56 23 AM" src="https://user-images.githubusercontent.com/3058939/130451465-bcdff0d8-bad1-49c0-8f11-be7f9cc70ef8.png">
<img width="1552" alt="Screen Shot 2021-08-23 at 5 57 48 AM" src="https://user-images.githubusercontent.com/3058939/130451472-2ee1e2dc-8f01-4936-a260-ae9152eb224d.png">
. Ran through 
<img width="1552" alt="Screen Shot 2021-08-23 at 5 50 02 AM" src="https://user-images.githubusercontent.com/3058939/130451445-48d85427-2e8d-4b94-a500-fb461413ae6a.png">

**Comment by kylo252** [comment]
Did you try my suggestion about using a minimal config? Use this as your `init.lua`

https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua

> It will verify that a minimal configuration for both packer and lspconfig works as expected.

**Comment by alechp** [comment]
> Did you try my suggestion about using a minimal config? Use this as your `init.lua`
> 
> [https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua](https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua?rgh-link-date=2021-08-23T14%3A14%3A45Z)
> 
> > It will verify that a minimal configuration for both packer and lspconfig works as expected.

Yes. Just tried with fresh un/reinstall. When I start lvim, same issue from before (eg. if I try running a PackerInstall or PackerSync command, terminal closes immediately)

**Comment by kylo252** [comment]
> Yes. Just tried with fresh un/reinstall. When I start lvim, same issue from before (eg. if I try running a PackerInstall or PackerSync command, terminal closes immediately)

Something is off with Packer on your system. Your next step is to check if there are similar issues on their tracker https://github.com/wbthomason/packer.nvim/issues, you can also see if you missed any steps from https://github.com/wbthomason/packer.nvim#debugging

**Comment by alechp** [comment]
No idea what the source of the bug is then

Looks like I'm back to using VSCode on my laptop for the foreseeable future. RIP
