### ISSUE TITLE
[Bug]: smart quit that doesn't discard unwritten changes

### ISSUE THREAD

**Issue by gnmearacaun** [LunarVim/LunarVim#1239]
### Problem description

`<leader>c` and `<leader>q` exit without a warning. There may be unsaved changes, thereby work can be lost unexpectedly.

I have the following script in my init.vim that handles buffers and windows in a sane way. I intend to convert it to lua eventually (my lua skills are novice level atm). Here's the script in case anyone else wants to take a crack at it:
```

function! SmartQuit()
    let num_buffers = len(getbufinfo({'buflisted':1}))
    if num_buffers == 1
      try
        execute ":silent quit"
      catch /E37:/
        " Unwritten changes
        echo "E37: Discard changes?  y = yes, n = no, w = write and quit: "
        let ans = nr2char(getchar())
        if ans == "y" 
          execute "quit!"
        elseif  ans == "w" 
          execute "write"
          execute "quit"
        else
          call feedkeys('\<ESC>')
        endif
      endtry
    else
      try
        execute "bd"
      catch /E89:/
        " Unwritten changes
        echo "E89: Discard changes?  y = yes, n = no, w = write and quit: "
        let ans = nr2char(getchar())
        if ans == "y" 
          execute "bd!"
        elseif  ans == "w" 
          execute "write"
          execute "bd"
        else
          call feedkeys('\<ESC>')
        endif
      endtry
    endif
endfunction
```

### LunarVim version

rolling

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+5-g05330ba50

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
I like the idea generally. I haven't noticed it before since I have remaped those anyway, but Isn't it better to remove the force quit in the first place?

**Comment by gnmearacaun** [comment]
Idk, I generally use `q` for quitting. The behaviour of that script is exactly what I want. Quits each buffer one at a time, offers to write out and quit with a single keystroke. `Force quit` shuts all tabs down at once, okay, but not without prompting to write changes. I'm in favor of getting rid of it.
