### ISSUE TITLE
[Feature]: Add builtin-lsp quickfix list

### ISSUE THREAD

**Issue by ashincoder** [LunarVim/LunarVim#1242]
### Feature motivation

So there is a keybinding of `<leader>ql` which calls the quick fix. But the following does nothing for me. The video shown will show the difference

https://user-images.githubusercontent.com/83629316/128374702-d6a44a48-0129-4195-a54a-a88c24b7e03f.mp4

### Describe the expected solution

I thought calling QuickFix() will bring a list of errors. 

### Describe the alternatives you've considered

using the following function will be much better. 
lua`lua vim.lsp.diagnostic.set_loclist()` will show a list of errors

**Comment by ChristianChiarulli** [comment]
fixed on rolling

**Comment by ashincoder** [comment]
Oh ok great
