### ISSUE TITLE
[Doc Improvement] Add disabling of barbar

### ISSUE THREAD

**Issue by benvds** [LunarVim/LunarVim#1246]
### Feature motivation

Please add to docs.

Discussion:
https://discord.com/channels/701530051140780102/704077577920446636/872932402022985788

Barbar cannot be disabled by setting:
`lvim.builtin.barbar.active = false`

But needs to be done using:
`lvim.builtin.bufferline.active = false`

I think this is an important plugin to mention for disabling as barbar breaks conventional vim tab/window usage.

**Comment by ChristianChiarulli** [comment]
documented here: https://www.lunarvim.org/plugins/, thank you
