### ISSUE TITLE
[Feature]: Fuzzy grep

### ISSUE THREAD

**Issue by marcusbuffett** [LunarVim/LunarVim#1253]
### Feature motivation

It would be great if there were a default keybind for fuzzy searching for text. Easy enough to set up yourself, but I think it’s common enough to warrant inclusion as a default mapping. Maybe \<leader\>sf ? f for fuzzy?

**Comment by kylo252** [comment]
Have you tried `<leader>st` ? It's bound to `:Telescope live_grep`.

**Comment by marcusbuffett** [comment]
Right, I know about that one, but it’s not fuzzy. Searching for fbar won’t match occurrences of “foobar”. Related is this issue in the telescope repo: https://github.com/nvim-telescope/telescope.nvim/issues/564

**Comment by Uzaaft** [comment]
@kylo252 What do you think? Is this something you think we should add to `lvim`?

**Comment by kylo252** [comment]
> @kylo252 What do you think? Is this something you think we should add to `lvim`?

@Uzaaft, I have a function that does a somewhat similar job to this request, but I hadn't been able to merge upstream due to the awkward API it needs. Take a look here https://github.com/kylo252/lvim/blob/77b3b53582437cc7e39d4c942523488b335a8351/lua/user/telescope/custom-finders.lua#L209-L239

**Comment by abzcoding** [comment]
`<leader>sf` for fuzzy finding files
`<leader>st` for fuzzy finding strings
