### ISSUE TITLE
[Bug]: Can't jump to prev/next snippet's placeholder

### ISSUE THREAD

**Issue by angryheng** [LunarVim/LunarVim#1255]
### Problem description

When I press Tab or S-Tab, Can't jump to prev/next snippet's placeholder

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6.0

### Screenshots

![tab](https://user-images.githubusercontent.com/28853495/128583861-68588224-a818-433e-8e9d-31a9b1250af7.gif)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
fixed on latest rolling 3da49e4be455d72d2a69fb76472c1f022815681b
