### ISSUE TITLE
[Bug]: Text out of sync in insert mode

### ISSUE THREAD

**Issue by ahmedkhalf** [LunarVim/LunarVim#1258]
### Problem description

https://user-images.githubusercontent.com/36672196/128601182-80546cba-82d9-46b9-9601-3cb9f5e0e1ad.mp4

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/nvim/ftplugin/)
- [X] I checked the options (~/.config/nvim/lv-config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

Lunarvim Master Branch, Latest commit

### Neovim version (>= 0.5)

v0.6.0-dev+108-g5130bc071

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Does this also happen when you use an empty config.lua?

**Comment by ahmedkhalf** [comment]
Somehow, the issue is now gone when I updated to rolling... I will let you know if it occurs again, but for now, I will close the issue.
