### ISSUE TITLE
[Bug]: gitsigns fails to update

### ISSUE THREAD

**Issue by ashincoder** [LunarVim/LunarVim#1260]
### Problem description

Open lvim:
1 PackerSync
2 Shows gitsigns failed to update

### LunarVim version

rolling branch only

### Neovim version (>= 0.5)

NVIM v0.5.0 Build type: Release LuaJIT 2.0.5

### Relevant log output

```shell
nothing relevent to gitsigns.
```

### Screenshots

[![asciicast](https://asciinema.org/a/OJChoInyu15nYkRm98D5V2G8L.svg)](https://asciinema.org/a/OJChoInyu15nYkRm98D5V2G8L)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
```shell
cd ~/.local/share/lunarvim/site/pack/packer/opt/gitsigns.nvim/
git reset --hard
git pull
```

i think this is more of a `gitsigns` issue, cause i got it with my own separate neovim config as well

**Comment by marcusbuffett** [comment]
In case anyone else finds this, I had to do the above but `git reset --hard origin/main` instead, to get the pull to work
