### ISSUE TITLE
[Bug]: format on save doesn't work if i want to save the file right after change!

### ISSUE THREAD

**Issue by ahhshm** [LunarVim/LunarVim#1263]
### Problem description

The only reason that I installed lunarvim is that LSP settings are tricky for me. one of the most important things that I expect from lunarvim is format on save. apparently, this doesn't work most of the time! 

if I want to save the file right after a change, the format on save doesn't work. I have to wait maybe 10 seconds and then try to save the file so the format on save works. maybe it's because of the tree-sitter that sometimes is slow and my computer is also very slow.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

I don't know. I installed it yesterday

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Have you explicitly set a fornatter or are you using the language server for formatting?   Does it lag after the first format or just on the first format?

**Comment by ahhshm** [comment]
<b>Have you explicitly set a formatter or are you using the language server for formatting?</b>
No. I haven't set a formatted and everything is the default.

<b>Does it lag after the first format or just on the first format?</b>
It lags after every save, But if I had changed the file recently nothing happens.

**Comment by rebuilt** [comment]
Which language server is it?

**Comment by ahhshm** [comment]
typescript

**Comment by ChristianChiarulli** [comment]
you likely have to wait for the lang server to startup, lunarvim can't speed that up.

**Comment by ahhshm** [comment]
Ok. Thanks for the quick reply. I haven't expected that. 
LunarVim is still awesome.
