### ISSUE TITLE
Develop Pinning strategy

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#1265]
We need to pin our core plugins to specific commits for reproducibility and stability.

- how often should they be updated? 
  - weekly? 
  - monthly? 
  - never? 
  - when we feel like it?

**Comment by abzcoding** [comment]
weeky

**Comment by ahmedkhalf** [comment]
I personally want it 8 days instead of one week.

**Comment by dhollinger** [comment]
What about specific versions of neovim. Unless you're using an appimage or pinning brew/apt/dnf packages that will get updated on a regular schedule. Is there a plan to bundle neovim with the pinned versions? Does pinning Neovim even need to be done?
