### ISSUE TITLE
[Feature]: Disable Tabs (barbar)

### ISSUE THREAD

**Issue by hector-sab** [LunarVim/LunarVim#1272]
### Feature motivation

I am always frustrated that each buffer opens a tab and that gets in the way of my workflow.

### Describe the expected solution

A way to turn on/off barbar.nvim and anything else that keeps adding a tab even when the plugin is deactivated OR some guidance so I can do it myself. I am pretty new to lvim and looking forward to using it and contributing (but the tabs are in the way of me using it).

### Describe the alternatives you've considered

I tried disabling the plugin from `~/.local/share/lunarvim/lvim/lua/core/bufferline.lua` and that seems to deactivate the plugin. But there's still something creating a tab that I cannot remove.

### Additional context

I come from using fzf.nvim and `Buffers`, thus I want something resembling that.

**Comment by abzcoding** [comment]
can you test adding this to your `config.lua`
```lua
lvim.builtin.bufferline.active = false
```

**Comment by ChristianChiarulli** [comment]
I think theres also another vim builtin option that hides the tabline all together that he would need @abzcoding

**Comment by abzcoding** [comment]
> I think theres also another vim builtin option that hides the tabline all together that he would need @abzcoding

like this?
```lua
vim.cmd [[ set showtabline=0 ]]

**Comment by hector-sab** [comment]
Thanks @abzcoding  @ChristianChiarulli , that worked.

**Comment by hector-sab** [comment]
For future references, a better option is to `set showtabline=1`. This way it still shows up when there are two or more tabs.
