### ISSUE TITLE
[Feature]: Can we talk about the change from ["<C-j>"] = actions.move_selection_next, to ["<C-j>"] = actions.cycle_history_next,

### ISSUE THREAD

**Issue by afridley** [LunarVim/LunarVim#1274]
### Feature motivation

I would like to change 
         ``` ["<C-j>"] = actions.cycle_history_next,```
          ```["<C-k>"] = actions.cycle_history_prev,```
back to
          ```["<C-j>"] = actions.move_selection_next,```
         ``` ["<C-k>"] = actions.move_selection_previous,```
and have
          ```["<C-n>"] = actions.cycle_history_next,```
          ```["<C-p>"] = actions.cycle_history_prev,```

To me being able to hold control and move up and down telescopes search is more useful then cycling the history.
It also matches my expectation with being able to hold ctrl j,k to move up and down lsp menus.

I would also be fine if there was just a config option that would switch it.

But maybe I'm missing something as to why it was changed

**Comment by abzcoding** [comment]
you can change them to whatever you want
```lua
lvim.keys.normal_mode["<C-j>"] = "whatever"
lvim.keys.normal_mode["<C-n>"] = "whatever"
-- ...
```

**Comment by afridley** [comment]
@abzcoding This is great as far as a config solution.

I still wonder if the default shouldn't be the other way around though to match the existing navigation for qflist and lsp menus. Since in both those you can use some form of j and k

**Comment by afridley** [comment]
@abzcoding @ChristianChiarulli Also it looks like they are still j and k in normal mode just not insert mode so we should probably make those consistent.

      mappings = {
        i = {
          ["<C-n>"] = actions.move_selection_next,
          ["<C-p>"] = actions.move_selection_previous,
          ["<C-c>"] = actions.close,
          ["<C-j>"] = actions.cycle_history_next,
          ["<C-k>"] = actions.cycle_history_prev,
          ["<C-q>"] = actions.smart_send_to_qflist + actions.open_qflist,
          ["<CR>"] = actions.select_default + actions.center,
          -- To disable a keymap, put [map] = false
          -- So, to not map "<C-n>", just put
          -- ["<c-t>"] = trouble.open_with_trouble,
          -- ["<c-x>"] = false,
          -- ["<esc>"] = actions.close,
          -- Otherwise, just set the mapping to the function that you want it to be.
          -- ["<C-i>"] = actions.select_horizontal,
          -- Add up multiple actions
          -- You can perform as many actions in a row as you like
          -- ["<CR>"] = actions.select_default + actions.center + my_cool_custom_action,
        },
        n = {
          ["<C-j>"] = actions.move_selection_next,
          ["<C-k>"] = actions.move_selection_previous,
          ["<C-q>"] = actions.smart_send_to_qflist + actions.open_qflist,
          -- ["<c-t>"] = trouble.open_with_trouble,
          -- ["<C-i>"] = my_cool_custom_action,
        },
      },
    },

**Comment by afridley** [comment]
@abzcoding Actually I cant seem to get this to work
at first I thought because the example was in normal mode but even with this im not seeing a change

```lua
lvim.keys.insert_mode["<C-j>"] = "actions.move_selection_next"
lvim.keys.insert_mode["<C-k>"] = "actions.move_selection_previous,"
lvim.keys.insert_mode["<C-n>"] = "actions.cycle_history_next,"
lvim.keys.insert_mode["<C-p>"] = "actions.cycle_history_prev"
```
tried with normal_mode as well

Is it possible its not making it to telescope.js or that telescope doesnt care about these bindings
