### ISSUE TITLE
[Bug]: Regression - no efm ... null-ls? errors for eslint and prettier

### ISSUE THREAD

**Issue by afridley** [LunarVim/LunarVim#1275]
### Problem description

Open a project with eslint after installing needed Lsp's(javascript or typescript) and efm. notice that there are no lsp errors for eslint. 

This is also true for prettier

I know that we are still configuring efm. But just wanted to get this logged as a use case.

I wonder if null-ls can accomplish the same and show eslint and prettier diagnostics .

I can get eslint errors back by pasting
```lua
local tsserver_args = {prettier, eslint}
require"lspconfig".efm.setup {
    -- init_options = {initializationOptions},
    cmd = {DATA_PATH .. "/lspinstall/efm/efm-langserver"},
    init_options = {documentFormatting = true, codeAction = false},
    filetypes = {"lua", "python", "javascriptreact", "javascript", "typescript", "typescriptreact", "sh", "html", "css", "json", "yaml", "markdown"},
    settings = {
        rootMarkers = {".git/"},
        languages = {
            python = python_arguments,
            lua = lua_arguments,
            sh = sh_arguments,
            javascript = tsserver_args,
            javascriptreact = tsserver_args,
            html = {prettier},
            css = {prettier},
            json = {prettier},
            yaml = {prettier},
            markdown = {markdownPandocFormat},
            typescript = tsserver_args,
            typescriptreact = tsserver_args
            -- javascriptreact = {prettier, eslint},
            -- javascript = {prettier, eslint},
            -- markdown = {markdownPandocFormat, markdownlint},
        }
    }
}

```
into the init.lua
but then im asked whenever saving whether id rather use efm or null-ls to format and efm doesn't do anything format wise anymore.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

5.1 rolling 8/10/2020

### Neovim version (>= 0.5)

.5

### Screenshots

![oldnvim](https://user-images.githubusercontent.com/34749972/128812210-962ddcf4-894e-44a3-875f-0fbe8047167a.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
yes you can
```lua
-- use prettier for formatting and eslint for fixing
lvim.lang.typescript.formatters = { { exe = "prettier" } }
lvim.lang.typescriptreact.formatters = lvim.lang.typescript.formatters
lvim.lang.javascript.formatters = lvim.lang.typescript.formatters
lvim.lang.javascriptreact.formatters = lvim.lang.typescript.formatters

lvim.lang.typescript.linters = { { exe = "eslint_d" } }
lvim.lang.typescriptreact.linters = lvim.lang.typescript.linters
lvim.lang.javascript.linters = lvim.lang.typescript.linters
lvim.lang.javascriptreact.linters = lvim.lang.typescript.linters
```

**Comment by afridley** [comment]
@abzcoding thank you this works perfectly.
