### ISSUE TITLE
[Feature]: Include dotfiiles in Telescope results

### ISSUE THREAD

**Issue by gikari** [LunarVim/LunarVim#1286]
### Feature motivation

Currently, telescope functions like `find_files` do not include hidden files in the results. These include like files from GNU stow repos (`.config`, `.zshrc` etc) and files from various programming projects like `.clang-format` and `.dockerignore`. Not including these in search results is kinda strange.

### Describe the expected solution

Pass `hidden=true` for all the find_files commands, that are bind to mappings and menu entries in Dashboad.

Adjust documentation for [Telescope Project](https://www.lunarvim.org/plugins/02-extra-plugins.html#telescope-project) plugin:
```lua
	{
		"nvim-telescope/telescope-project.nvim",
		event = "BufWinEnter",
		setup = function()
			vim.cmd([[packadd telescope.nvim]])
		end,
		config = function()
			require("telescope").setup({
				extensions = {
					project = {
						hidden_files = true, -- default: false
					},
				},
			})
		end,
	},

```

### Describe the alternatives you've considered

Use `git_files` instead of `find_files` and fallback to `find_files` if we are not in a repo. However, in this case, I am not sure whose responsibility to implement that - Telescope or Lunarvim's.

**Comment by kylo252** [comment]
Fixed in #1702.
