### ISSUE TITLE
[Bug]: LvimInfo not listing eslint_d as supported linter for JavaScript family.

### ISSUE THREAD

**Issue by PasiBergman** [LunarVim/LunarVim#1295]
### Problem description

LvimInfo not listing eslint_d as supported linter for JavaScript family. Reason is, that there is no specific config for eslint_d linter, but elint config is used with cmd = eslint_d. LvimInfo should add eslint_d as supported linter when eslint is detected.

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Tastyep** [comment]
Should be fixed once [this](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/105#issuecomment-898279573) is implemented
