### ISSUE TITLE
[Feature]: Install without sudo permissions. Install in user directory.

### ISSUE THREAD

**Issue by sperezconesa** [LunarVim/LunarVim#1297]
### Feature motivation

I work with several HPC clusters and other computers I can't use sudo on, so I can't install lunar vim with the easy install scripts... I can do this for plain neovim so I guess this can be done for lunar vim too!

### Describe the expected solution

Have a script just like the ones provided but without having to sudo.

### Describe the alternatives you've considered

Doing the manual installation, unfortunatelly the link where it is explained is broken!
https://www.lunarvim.org/01-installing.html#manual-install

**Comment by kylo252** [comment]
There's been some delays but please do take a look at https://github.com/LunarVim/LunarVim/pull/1052.
I would appreciate any help and/or feedback regarding the new script.

**Comment by sperezconesa** [comment]
I'm sorry, I didn't see that!
I'll try to help you out!
