### ISSUE TITLE
[Feature]: Add Puppet LSP support

### ISSUE THREAD

**Issue by dhollinger** [LunarVim/LunarVim#1305]
### Feature motivation

I prefer to work in Neovim/LunarVim for code, but I also write automation code in the Puppet DSL. LunarVim doesn't appear to have default support for the Puppet Language Server and setting it up can be complicated to say the least.

### Describe the expected solution

[nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md) already supports the puppet language server and [nvim-lspinstall](https://github.com/kabouzeid/nvim-lspinstall) has a [Pull Request](https://github.com/kabouzeid/nvim-lspinstall/pull/121) to add install support for the LSP. I have ported this PR into my local install of LunarVim's lsp-install and it works well.

As for [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim), LSPConfig directly configures the linter within the Language Server configuration and as such it is not needed in null-ls.

Syntax highlighting is handled by [puppet-vim](https://github.com/rodjek/vim-puppet). I'd love Treesitter syntax, but that is probably more work than I have time to add and Puppet-Vim is maintained by a Puppet employee.

### Describe the alternatives you've considered

Puppet currently doesn't provide much alternative support for LSP outside of their langserver. There are some older tagfiles, but they seem to be out of date as the LSP is now the preferred and recommended development tool

### Additional context

![Peek 2021-08-12 10-44](https://user-images.githubusercontent.com/2914211/129227156-e4fe5bc1-0c79-404e-8c4b-76b58a958965.gif)

**Comment by abzcoding** [comment]
@dhollinger can you confirm that #1322 fixes your issue?

**Comment by dhollinger** [comment]
@abzcoding It does appear to fix the issue. I should note that `.epp` files are also puppet files. They are puppet templates. Not sure if that should be this issue or a new one.

**Comment by abzcoding** [comment]
> @abzcoding It does appear to fix the issue. I should note that `.epp` files are also puppet files. They are puppet templates. Not sure if that should be this issue or a new one.

let me add the support for `.epp` files as well in that PR
