### ISSUE TITLE
[Bug]: Comments dosen't work in Elixir

### ISSUE THREAD

**Issue by torepettersen** [LunarVim/LunarVim#1308]
### Problem description

Using gcc in Elixir files adds a `/* .. */` around the line.

The expected comment would be `##` in the beginning of the line.

### LunarVim version

Latest master (e7b6d3b)

### Neovim version (>= 0.5)

v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
@torepettersen can you confirm #1321 fixes your issue or not?

**Comment by torepettersen** [comment]
Thanks, @abzcoding, that works.
