### ISSUE TITLE
[Bug]: No delegateCommandHandler for java.apply.workspaceEdit

### ISSUE THREAD

**Issue by Asocia** [LunarVim/LunarVim#1314]
### Problem description

Whenever I apply a code action in a java project, I get the following message on my status line:
```
RPC[Error] code_name = MethodNotFound, message = "No delegateCommandHandler for java.apply.workspaceEdit"
```

The code action works but it produces above error message which is annoying. What should I change in order to prevent this? I'm using a clean install of LunarVim.
```
LVBRANCH=master bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
# and then launch LunarVim with `lvim`.
```

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [ ] The programs specified by the config are installed

### LunarVim version

latest

### Neovim version (>= 0.5)

NVIM v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
i don't think this has anything to do with LunarVim, it might be related to this [issue](https://github.com/eclipse/eclipse.jdt.ls/issues/376) in `eclipse.jdt.ls`
