### ISSUE TITLE
[Bug]: can not install with command

### ISSUE THREAD

**Issue by arywz** [LunarVim/LunarVim#1325]
### Problem description

remote: Enumerating objects: 2547, done.
remote: Counting objects: 100% (851/851), done.
remote: Compressing objects: 100% (295/295), done.
remote: Total 2547 (delta 636), reused 707 (delta 544), pack-reused 1696
Receiving objects: 100% (2547/2547), 800.00 KiB | 939.00 KiB/s, done.
Resolving deltas: 100% (1435/1435), done.
Cloning LunarVim configuration
Cloning into '/Users/ary/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 9570, done.
remote: Counting objects: 100% (228/228), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 9570 (delta 130), reused 169 (delta 103), pack-reused 9342
Receiving objects: 100% (9570/9570), 10.71 MiB | 6.11 MiB/s, done.
Resolving deltas: 100% (5786/5786), done.
chmod: /usr/local/bin/lvim: Not a directory

### LunarVim version

master

### Neovim version (>= 0.5)

→ nvim --version NVIM v0.5.0 Build type: Release LuaJIT 2.1.0-beta3

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by arywz** [comment]
install command does not work in macos

**Comment by daiyanze** [comment]
Same thing happened here. I'm using Mac Big Sur (Apple m1).
It seems the folder `/usr/local/bin/` did not exist. Had to create that folder manually...

**Comment by frontendwizard** [comment]
I can confirm it's not working on M1 macbooks. The `/usr/local/bin` is not a directory in my case
