### ISSUE TITLE
[Bug]: Extreme lag and CPU usage (git branch -a --no-abbrev --contains) in Linux kernel git repo

### ISSUE THREAD

**Issue by nift4** [LunarVim/LunarVim#1337]
### Problem description

1. Clone linux kernel
2. Edit an file (example: any defconfig)
3. Watch git eating up half your cpu and lvim becoming unusable
P.S.: running the command standalone, it takes 8 seconds, so the bug here is that it is getting spammed

### LunarVim version

e7b6d3b6f5982ea1042ffd499a7b85c18f0b782e

### Neovim version (>= 0.5)

0.6.0-dev

### Screenshots
CPU MEM TIME NAME
![Bildschirmfoto von 2021-08-17 08-27-45](https://user-images.githubusercontent.com/36458596/129674774-1a7e5585-171b-407b-b9ab-807fdcd477d0.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Tastyep** [comment]
If it spams the command, its likely because of `galaxyline`, I noticed it refreshes unconditionally at least every second.
Maybe #1329 will solve that

**Comment by abzcoding** [comment]
@nift4 can you pull the latest changes and test it again?

**Comment by nift4** [comment]
seems to be fixed, thanks
