### ISSUE TITLE
[Bug]: No syntax highlighting for nix

### ISSUE THREAD

**Issue by ashincoder** [LunarVim/LunarVim#1345]
### Problem description

1. Open a nix file
2. No syntax highlighting

### LunarVim version

rolling branch latest

### Neovim version (>= 0.5)

NVIM v0.5.0 Build type: Release LuaJIT 2.0.5

### Relevant log output

```shell
Nothing relevant
```

### Screenshots

![2021-08-18-193705_1366x768_scrot](https://user-images.githubusercontent.com/83629316/129913390-a45d185b-008b-4794-82f2-112ae9747e8d.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ashincoder** [comment]
I have also installed nix treesitter package

**Comment by abzcoding** [comment]
@ashincoder can you test if #1347 fixes your issue or not 🥺

**Comment by ashincoder** [comment]
Ok can I test this tomorrow as my laptop with nix is not being used right now.

**Comment by ashincoder** [comment]
Yeah it works :smile:

**Comment by ashincoder** [comment]
you can close this after u merge the PR #1437
