### ISSUE TITLE
[Bug]: Telescope package is missing

### ISSUE THREAD

**Issue by vlcinsky** [LunarVim/LunarVim#1348]
### Problem description

1. Using lunarvim rolling for a while
2. after some update today, Telescope is not installed
3. tried to reinstall LunarVim comletely
4. Command `:Telescope` is unknown
5. following packages are reported for `:PackerStatus`:
 • null-ls.nvim
 • vim-vsnip (not loaded)
 • nvim-compe (not loaded)
 • nvim-comment
 • nvim-lspconfig
 • nvim-lspinstall
 • barbar.nvim
 • which-key.nvim
 • nvim-toggleterm.lua
 • project.nvim
 • dashboard-nvim
 • nvim-tree.lua
 • popup.nvim
 • friendly-snippets (not loaded)
 • nvim-treesitter
 • galaxyline.nvim
 • nvim-autopairs (not loaded)
 • nvim-web-devicons
 • gitsigns.nvim
 • plenary.nvim
 • packer.nvim
 • nlsp-settings.nvim

### LunarVim version

a190306e: [Feature]: LSP Fortran (#1342)

### Neovim version (>= 0.5)

v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
can you remove `~/.config/lvim/plugin`
and do a `:PackerSync` afterwards

**Comment by vlcinsky** [comment]
@abzcoding I followed the instructions from README and during my reinstallation I removed or renamed all following directories:
- `~/.cache/nvim`
- `~/.config/nvim #Removed only on Master Branch`
- `~/.local/share/nvim/site/pack/packer #Removed only on Master Branch`
- `~/.local/share/lunarvim #Removed only on Rolling Branch`
- `~/.config/lvim #Removed only on Rolling Branch`

and then reinstalled lunarvim. It did not help that time.

Anyway, I fixed the issue somehow:

# Cause - `lvim.builtins.telescope.active` was nil

I have found, that `lvim.builtins.telescope.active` was nil. I have no idea, how that was possible, I had never before problems with that.

The steps which helped me to fix the issue:
- add `lvim.builtins.telescope.active=true` and `lvim.builtins.project.active=true` to my config
- restart lvim, PackerSync etc.
- checked, that it works
- restored my older customized lunarvim configuration (not touching the lunarvim files)
- restart lvim, PackerSync etc.
- all works

What is strange is that my personal customized `config.lua` does not contain the line `lvim.builtins.telescope.active=true` (but does the `lvim.builtins.project.active=true`).

I suspect that the value of `lvim.builtins.telescope.active` was somewhere cached, then it went broken and got cached with empty content. I had some error messages from packer so it is one of suspects, but I have no idea how to prove who is guilty.

Now it works for me.

**Comment by daniel-vera-g** [comment]
I had the same behavior, where telescope was not available as plugin.
I was on the `rolling` version and switched over to `master`, did a `:PackerSync` and Telescope was back as PlugIn.
Maybe it got disabled, removed, commented out or alike in `rolling`?

**Comment by shivahnshankar** [comment]
Same problem...clean install of rolling release does not activate Telescope. I know this is a rolling release and this is a community led effort but there have been many such regressions and maybe people are better of using the stable release for now.

**Comment by abzcoding** [comment]
@kylo252 after https://github.com/LunarVim/LunarVim/commit/335e707b2aae38c0cd5d0d962b27038ab1117aa6, sometimes the value of  `lvim.builtin.telescope.active` is `nil` which causes `Packer` to remove telescope because of `disable = not lvim.builtin.telescope.active,`
do you have any ideas why this would happen?

**Comment by kylo252** [comment]
Can you guys try #1354? Let's see if that fixes things and then we can try other forceful measures.

**Comment by vlcinsky** [comment]
Searching the code for lines, which could mess up with `lvim.builtin.telescope` I was expecting something like:
```lua
lvim.builtin.telescope = {color_devicons = false}
```
what would leave all the remaining `lvim.builtin.telescope` values empty.

But I have fond another situation, where thing could go wrong, see https://github.com/lunarvim/lunarvim/blob/1f45d1531d3636102f8971f8b2103b5302f48b68/lua/core/telescope.lua#L2-L6
```lua
local M = {}
function M.config()
  local status_ok, actions = pcall(require, "telescope.actions")
  if not status_ok then
    return
  end

  lvim.builtin.telescope = {
    ---@usage disable telescope completely [not recommeded]
    active = true,
    defaults = {
```

As you see, if `require("telescope.actions") ` fails, the `lvim.builtin.telescope = {...` does not happen.

So a bug in telescope.actions module could break the things.

I would propose to do some debug logging after `pcall(require, "some.module")` fails. This way we could detect such issues much simpler.

**Comment by abzcoding** [comment]
cc: @Tastyep

**Comment by vlcinsky** [comment]
The PR #1354 seems ready for use (reviewed, fixed, reviewed). Consider merging it as it could prevent some messy scenarios resulting from having nvim paths in rtp and packpath.

**Comment by chase** [comment]
After applying the fix of setting telescope to active, this line doesn't work in a new config on a new install:
https://github.com/LunarVim/LunarVim/blob/ae1dea8b6499afbc35d3386654f9d0d8d208d342/utils/installer/config.example.lua#L40

**Comment by vlcinsky** [comment]
@chase make sure what is value of `lvim.builtin.project.active`

It should be true to allow Project things to work.

In my case when fighting with missing telescope I had to add to my personal config.lua a line:
```lua
lvim.builtin.project.active = true
```
and it started working.

It was enough to have that line there temporarily, after things got fixed, the line could be removed.

**Comment by chase** [comment]
@vlcinsky That's the first thing I tried, it's not that Project things don't work. In fact, Recent Projects from the dashboard works just fine.

This is the error when using `leader,P` after that line is enabled in my config:
```
E5108: Error executing lua .../start/telescope.nvim/lua/telescope/_extensions/init.lua:11: This extension doesn't exist or is not installed: project                                                                                                                                                                                                                                                                                                                                           
module 'telescope._extensions.project' not found:                                                                                                                                                                                                                                                                                                                                                                                                                                              
        no field package.preload['telescope._extensions.project']                                                                                                                                                                                                                                                                                                                                                                                                                              
        no file './telescope/_extensions/project.lua'                                                                                                                                                                                                                                                                                                                                                                                                                                          
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/telescope/_extensions/project.lua' 
```

**Comment by vlcinsky** [comment]
@chase good you asked. I had exactly the same problem and in my personal config.lua I see these lines:
```lua
-- lvim.builtin.which_key.mappings["P"] = { "<cmd>lua require'telescope'.extensions.project.project{}<CR>", "Projects" }
lvim.builtin.which_key.mappings["P"] = { "<cmd>Telescope projects<CR>", "Projects" }
```

**Comment by vlcinsky** [comment]
@chase try to pull the latest changes, commit https://github.com/LunarVim/LunarVim/commit/d85584d09f9028fa4202cea473f7f0ae3c531aef might fix these things.

**Comment by chase** [comment]
@vlcinsky The original line still doesn't seem to work, maybe the config should just use the Telescope command instead?

**Comment by vlcinsky** [comment]
@chase yes, that is what worked for me. But I do not understand, why it is not working when calling the telescope project view via lua.
