### ISSUE TITLE
[Feature]: Allow to autodetect or select python virtualenv

### ISSUE THREAD

**Issue by vlcinsky** [LunarVim/LunarVim#1357]
### Feature motivation

Having bunch of python projects, all using virtualenv. Most of them are having single vitualenv named `.venv` located within the project folder, some are having multiple virtual envs (typically some python libraries tested using `tox` with virtualevs in `.tox/py36`, `.tox/py37` etc.).

When I cd into given folder, activate the virtualenv and start `lvim`, things are working well.

With new [project](https://github.com/ahmedkhalf/project.nvim) feature it is so easy to cd into another project folder. It woudl be great, if LSP for python would work there (semi) automatically.

### Describe the expected solution

Open `lvim` in any directory.

Use project and jump to a file in another project directory, where is python app.

LSP would deal with virtualenvs as follows:
- detect all relevant virtualenvs within given project folder
- if only one, automatically use it
- if more, pick one

If there are more virtualenvs, allow to change to another one.

This behaviour should be available for other means of changing directory (such as `:cd ../some/other/project`).

### Describe the alternatives you've considered

Tried https://github.com/HallerPatrick/py_lsp.nvim but it conflicts with LunarVim LSP initialization.

I was searching for configuration options to reconfigure pyright LSP to use another virtual env but I got lost.

### Additional context

It would be great to have such feature available as standard part of LunarVim, but if I would have a chance to set it up only as part of my personal configuration, I wold be happy too.

Note, that there could be other LSP servers for other languages which could benefit from controlling their environments.

**Comment by kylo252** [comment]
You can turn off the default `pyright` setup like this:

```lua
lvim.lang.python.lsp.provider = nil
```
now you can manually set any other provider you like 😃

**Comment by kylo252** [comment]
Are you still having problems with this after the recent updates?
It's now possible to setup `pylsp` directly, and you can further override any of its configuration.

**Comment by kobzar** [comment]
I think we can close it
