### ISSUE TITLE
[Bug]: Installation isuue on Ubuntu (neovim 0.6 ppa)

### ISSUE THREAD

**Issue by maroozm** [LunarVim/LunarVim#1358]
### Problem description

packer.nvim: Error running config for telescope.nvim: attempt to call a nil value
packer.nvim: Error running config for nvim-tree.lua: attempt to call a nil value

It gives this error and then asks to press ENTER, after which nothing happens. I have tried a couple of times but same issue. I mean lvim still works but with errors on telescope and tree

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.6

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Can you try to run `:PackerSync` please

**Comment by maroozm** [comment]
did that, still doesn't work. maybe the issue is with rolling branch?
