### ISSUE TITLE
[Bug]: Diagnostic messages are not readable

### ISSUE THREAD

**Issue by kbrah** [LunarVim/LunarVim#1360]
### Problem description

I get diagnostics messages like this. I cannot read the message since it goes out of the screen.

![2021-08-20-120026_970x26_scrot](https://user-images.githubusercontent.com/10815813/130209039-43f03e36-7f52-4e23-84dc-3ed79416c08e.png)

When I move into the error with `space + l + j` The message displays nicely like this.
![2021-08-20-120425_822x61_scrot](https://user-images.githubusercontent.com/10815813/130209304-53af1772-136d-4c8f-a917-18b070700d0f.png)

### LunarVim version

rolling 

### Neovim version (>= 0.5)

0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
This is a virtual-text limitation, related to https://github.com/neovim/neovim/issues/13860

In the meanwhile, have you tried using a popup instead? 
```lua
lvim.lsp.diagnostics.virtual_text = false
```

**Comment by kbrah** [comment]
By popup do you mean the one that is displayed when using space + l + j? Is there any other way to display it? By disabling virtual text it only hides the diagnostic message. I would like to be able to display it in a similar way as "K" for hover doc.

**Comment by kbrah** [comment]
I found g + l will display line diagnostics. I think that is good enough for me :)

**Comment by kbrah** [comment]
Is there a way to show the popup automatically on hover?

**Comment by leopepe** [comment]
> Is there a way to show the popup automatically on hover?

@kbrah It is possible to do this by using autocmd on CursorHover events. vimr shared a solution in this [thread](https://neovim.discourse.group/t/how-to-show-diagnostics-on-hover/3830/4).

```
vim.api.nvim_create_autocmd({ "CursorHold" }, {
    pattern = "*",
    callback = function()
        for _, winid in pairs(vim.api.nvim_tabpage_list_wins(0)) do
            if vim.api.nvim_win_get_config(winid).zindex then
                return
            end
        end
        vim.diagnostic.open_float({
            scope = "cursor",
            focusable = false,
            close_events = {
                "CursorMoved",
                "CursorMovedI",
                "BufHidden",
                "InsertCharPre",
                "WinLeave",
            },
        })
    end
})
```
The callback checks if there are any other popup windows already in display, if not calls `vim.diagnostic.open_float`
