### ISSUE TITLE
[Feature]: Mapping to view git diff of current file

### ISSUE THREAD

**Issue by marcusbuffett** [LunarVim/LunarVim#1363]
### Feature motivation

This is something I do a lot and was surprised to find it wasn't in the built in mappings provided for git operations.

### Describe the expected solution

A mapping like \<Leader\>gd to open a diff view between the current file and the file at HEAD

### Describe the alternatives you've considered

Could just leave it up to each user to configure this, maybe I'm overestimating how common this need is.

**Comment by kylo252** [comment]
Good idea! The closest I could find to the desired effect is using `:Gitsigns diffthis HEAD` 

Could you try it and share your thoughts?

**Comment by marcusbuffett** [comment]
Yeah that's exactly what I'm looking for, good find. I wouldn't have thought Gitsigns would have that functionality. I've added that mapping to my config. I'll let others decide whether a built-in mapping makes sense, but it's still got my vote, particularly given that it's already included in an existing built-in plugin.
