### ISSUE TITLE
[Bug]: Clean install craches

### ISSUE THREAD

**Issue by torepettersen** [LunarVim/LunarVim#1368]
### Problem description

I got some problems with LunarVim saying: module 'core.lualine' not found. I then tried to do a clean install, but the installation then crashed with the same error:

![2021-08-21_11-09](https://user-images.githubusercontent.com/17319716/130316954-42bcde2d-5499-4ad6-9a02-8768944858fd.png)

### LunarVim version

Latest master

### Neovim version (>= 0.5)

v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
lualine is only available in the `rolling` branch, can you install using
```sh
LVBRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)
```
and then do a `:PackerSync`

**Comment by torepettersen** [comment]
Seems like that at least solves the installation problem, but after installation, it seems like not all packages are installed. Isn't Telescope supposed to be there by default?

![2021-08-21_12-52](https://user-images.githubusercontent.com/17319716/130319518-fed8a5fd-8e4c-499b-b31e-648d7a1ed5b7.png)
![2021-08-21_12-53](https://user-images.githubusercontent.com/17319716/130319526-66e6ba0e-0b3e-4c58-8c69-2f453105d152.png)

**Comment by abzcoding** [comment]
that is related to #1348
you can add this to your config for now
```lua
lvim.builtin.telescope.active=true
```
