### ISSUE TITLE
[Bug]:  Markdown snippets not expanding properly

### ISSUE THREAD

**Issue by daniel-vera-g** [LunarVim/LunarVim#1371]
### Problem description

When trying to use snippets in markdown, it just jumps to the next line and the completion window stays open.

As I understood it, the workflow to use a snippet is:

1. Select snippet in completion window with `<CR>`
2. Cycle through snippet with `<(S)-Tab>` and `<C-e>`

This works for most languages I tested, except markdown.

---

As a workaround I either:

1. Added:  `  ["<C-Space>"] = { "compe#confirm('CR')", { silent = true, noremap = true, expr = true } },` after: https://github.com/hrsh7th/nvim-compe/issues/99
2. Or used an expansion Keymap for vsnips: 

```lua
-- Expand or jump
vim.api.nvim_set_keymap('i', '<C-l>', "vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'", {expr = true})
vim.api.nvim_set_keymap('s', '<C-l>', "vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'", {expr = true})
```

Nevertheless, I would assume that it should work without this workaround.

If possible I would propose to add something like the first workaround to the compe config. I couldn't get it working with `<CR>`. Only with `<C-Space>`. Maybe someone knows better :smile:  

### LunarVim version

rolling commit: 33640834e4b07a8e9c5a6707ec0eadd863011ac0

### Neovim version (>= 0.5)

v0.5.0

### Screenshots

[![asciicast](https://asciinema.org/a/rQB2qtkEF4wvGR14qmATB5dB3.svg)](https://asciinema.org/a/rQB2qtkEF4wvGR14qmATB5dB3)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Markdown snippets work for me.  But I press `tab` to highlight the snippet I'd like to use.  And then `enter` to transform the snippet.

![markdown_snippets](https://user-images.githubusercontent.com/16025007/130698896-d5105d36-a57b-4721-9246-47809aa965a5.gif)

**Comment by daniel-vera-g** [comment]
> Markdown snippets work for me. But I press `tab` to highlight the snippet I'd like to use. And then `enter` to transform the snippet.
> 
> ![markdown_snippets](https://user-images.githubusercontent.com/16025007/130698896-d5105d36-a57b-4721-9246-47809aa965a5.gif)

Thanks for testing it. I use a Plugin(`bullets.vim`) to insert bullets, numbering,... It seems, that it maps `<CR>` to insert a mapping and breaks the transforming behavior...
I'm sorry, should have tested it better. Closing it.
