### ISSUE TITLE
[Bug]: lvim.keys.normal_mode makes navigation impossible

### ISSUE THREAD

**Issue by premell** [LunarVim/LunarVim#1374]
### Problem description

When using  lvim.keys.normal_mode to add keybindings, it makes you unable to use <C-h> and <C-l> to navigate to the nvimtree. Also you can not use H and L to use the buffers. There are probably way more stuff not working, but these are some of the most obvious ones. 

To reproduce, simply create an empty config.lua file and add 
```
 lvim.keys.normal_mode = {
      ["[d"] = "<PageUp>",
 }
```
to it. The bug appears even if the brackets are empty
```
 lvim.keys.normal_mode = {
 }
```
 I am not sure if lvim.keys.normal_mode depricated, but it is still on lunarvim.org keybindings section. 

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
this will remove all the LunarVim keybindings, hence everything not working
```lua
 lvim.keys.normal_mode = {
      ["[d"] = "<PageUp>",
 }
 -- or even this lvim.keys.normal_mode = {}
 ```
 if you want to add a keybinding you can use
 ```lua
  lvim.keys.normal_mode["[d"]="<PageUp>"
 ```

**Comment by premell** [comment]
oh okay, then I'll make a PR to lunarvim. This is the current explanation there 
![image](https://user-images.githubusercontent.com/65544203/130407591-0882be5c-d418-4385-9257-bebfd1201af7.png)
