### ISSUE TITLE
[Bug]: Installing proccess done correctly but config wont start

### ISSUE THREAD

**Issue by dessasin** [LunarVim/LunarVim#1378]
### Problem description

The installation steps are completed without any problems, but the customization settings are not activated after the installation. I thing installer wont create init.vim file at ~/.config/nvim path.

### LunarVim version

LunarVim 0.5.1

### Neovim version (>= 0.5)

v0.5.0

### Relevant log output

```shell
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Screenshots

I recorded installation proccess to video.
https://streamable.com/l7up74

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
bcz config is created in `~/.config/lvim` and you can use lunarvim using `lvim` command and not `nvim`

**Comment by dessasin** [comment]
O ok I didnt know that

**Comment by abzcoding** [comment]
> O ok I didnt know that

no worries mate 😄
