### ISSUE TITLE
Does anyone know how do I switch Tokyo night theme storm to night in lvim

### ISSUE THREAD

**Issue by lakshyarao22** [LunarVim/LunarVim#1379]
### Problem description

Just want to switch from Tokyo night storm to Tokyo night -night in lunarvim

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
add this to your config.lua
```lua
vim.g.tokyonight_style = "night"
```
