### ISSUE TITLE
[Bug]: Duplicate files and directories in Nvimtree

### ISSUE THREAD

**Issue by williamgoulois** [LunarVim/LunarVim#1382]
### Problem description

1. Open LunarVim
2. Immediatly after pressing enter, try to open nvimtree (with <leader>e for example).
3. See that folders are duplicated

I don't know if this issue is coming from LunarVim or directly NvimTree. I have run :PackerSync to have latest version of nvimtree.

### LunarVim version

rollling 33640834e4b07a8e9c5a6707ec0eadd863011ac0

### Neovim version (>= 0.5)

nightly 0.6

### Screenshots

<img width="199" alt="Screenshot 2021-08-23 at 16 14 23" src="https://user-images.githubusercontent.com/37271970/130462607-0ed34abb-2a25-4a86-bbd7-9b2a6a2165fa.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
cc @ahmedkhalf

**Comment by ahmedkhalf** [comment]
Thx for the issue! This is actually a problem with nvim-tree and I managed to do a minimal reproduction: [NvimTree Issue #586](https://github.com/kyazdani42/nvim-tree.lua/issues/586)

**Comment by ahmedkhalf** [comment]
Problem fixed from nvim-tree
