### ISSUE TITLE
Emmet Support?

### ISSUE THREAD

**Issue by norquisd** [LunarVim/LunarVim#1386]
Is there any way to use emmet in LV? Rather, is it supported with the built-in LSP at all? I can see some mentions of emmet in LV's config (specifically `lvim.lang.emmet.active`), but I'm not sure if it is meant to be up and running.

**Comment by rebuilt** [comment]
Add the emmet plugin to your plugins list.  

```lua
{
			"aca/emmet-ls",
			config = function()
				local lspconfig = require("lspconfig")
				local configs = require("lspconfig/configs")

				local capabilities = vim.lsp.protocol.make_client_capabilities()
				capabilities.textDocument.completion.completionItem.snippetSupport = true
				capabilities.textDocument.completion.completionItem.resolveSupport = {
					properties = {
						"documentation",
						"detail",
						"additionalTextEdits",
					},
				}

				if not lspconfig.emmet_ls then
					configs.emmet_ls = {
						default_config = {
							cmd = { "emmet-ls", "--stdio" },
							filetypes = {
								"html",
								"css",
								"javascript",
								"typescript",
								"eruby",
								"typescriptreact",
								"javascriptreact",
								"svelte",
								"vue",
							},
							root_dir = function(fname)
								return vim.loop.cwd()
							end,
							settings = {},
						},
					}
				end
				lspconfig.emmet_ls.setup({ capabilities = capabilities })
			end,
		},
```

**Comment by norquisd** [comment]
Cool, this works. Thanks!

**Comment by lavixta** [comment]
Is currently emmet-ls does not support for jsx and tsx i could only use emmet with html and css files

**Comment by rebuilt** [comment]
Correct.  It's not officially supported for those file types.  There's an open issue requesting support. 
 https://github.com/aca/emmet-ls/issues/10

**Comment by rebuilt** [comment]
Another option is this plugin.  But you'll need to trigger it manually with control+y then comma. 
 https://github.com/mattn/emmet-vim

**Comment by lavixta** [comment]
À thanks a lot cuz i saw in filetypes of the codes above has jsx but when i try it is not working with jsx

**Comment by oussamachah2020** [comment]
i added the code to my plugin, but it does't work !! how can i make it work is there a keys or something??

**Comment by olrtg** [comment]
@oussamachah2020 you can checkout my config here:
https://github.com/olrtg/dotfiles/blob/master/lvim/lua/olrtg/lsp/emmet.lua

Cheers!

**Comment by betogrun** [comment]
@oussamachah2020 I also need to run `npm install -g emmet-ls` to install the emmet language server in order to make it work.

**Comment by rodude123** [comment]
If you use emmet-ls how do you expand it?

**Comment by olrtg** [comment]
> If you use emmet-ls how do you expand a expression

When you write a expression in a supported filetype the cmp will tell you to if you can make the expansion.

**Comment by olrtg** [comment]
Also the defaults for emmet_ls are now very good so you can setup emmet like this:

```
MasonInstall emmet-ls
```

And then in your `config.lua`:

```
require("lvim.lsp.manager").setup("emmet_ls")
```

**Comment by QuentinGibson** [comment]
How would someone pass in a custom config using @olrtg method of installing emmet_ls

**Comment by brneor** [comment]
@QuentinGibson like this:

```lua
local emmet_options = {
  cmd = { vim.fn.stdpath "data" .. "/lsp_servers/emmet_ls/node_modules/.bin/emmet-ls", "--stdio" },
  capabilities = capabilities,
  filetypes = {
    "html",
    "typescript",
    "javascript",
    "javascriptreact",
    "xml",
  },
  root_dir = function ()
    return vim.loop.cwd()
  end
}
require("lvim.lsp.manager").setup("emmet_ls", emmet_options)

```
