### ISSUE TITLE
[Bug]: Vimtex plugin doesn't work

### ISSUE THREAD

**Issue by argapost** [LunarVim/LunarVim#1388]
### Problem description

Hi everyone I have a problem with the vimtex plugin.

1. I install vimtex by putting into my config:
  {
  "lervag/vimtex",
  },

2. The plugin is installed correctly I can see it in site/packer/start/vimtex
3. When I open a .tex file and try to find the vimtex commands by using ":Vimtex..." there are no commands from the plugin

Thank you in advance for your help!

### LunarVim version

Rolling

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+164-g50b30de20

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Can you try adding the latex plugin with this config:

```lua
		{
			"lervag/vimtex",
			config = function()
				vim.cmd("call vimtex#init()")
			end,
		},

```

**Comment by argapost** [comment]
Yeah perfect it works! thank you!
