### ISSUE TITLE
Install : Error installing Lunarvim on Ubuntu (attempt to index a nil value)

### ISSUE THREAD

**Issue by Israr** [LunarVim/LunarVim#1389]
I encountered following error during install (on ubuntu 20.04)

`
Resolving deltas: 100% (5920/5920), done.
packer.nvim: Error running config for telescope.nvim: .../ikhan/.local/share/lunarvim/lvim/lua/core/telescope.lua:83: attempt to index a nil value
packer.nvim: Error running config for nvim-treesitter: ...ikhan/.local/share/lunarvim/lvim/lua/core/treesitter.lua:68: attempt to index a nil value
Press ENTER or type command to continue
`

**Comment by frontendwizard** [comment]
I'm also facing this on MacOS

**Comment by Tastyep** [comment]
@kylo252 

Can you enter lvim at this point and run `:PackerSync` ?

**Comment by ekans** [comment]
I have the same problem.
After `:PackerSync` it seems to work. At least the error (linkg plenary.log) is gone.

**Comment by kylo252** [comment]
@ekans, Is this on a fresh-install?

**Comment by kylo252** [comment]
can you guys test to see if #1390 solves this?

**Comment by ekans** [comment]
I got this error now:
```
Installing LunarVim shim
Preparing Packer setup
packer.nvim: Error running config for vim-rooter: [string "..."]:0: module 'core.rooter' not found:
^Ino field package.preload['core.rooter']
^Ino file './core/rooter.lua'
```
FYI, before executing `instal.sh` I just moved `~/.local/share/lunarvim`

**Comment by ekans** [comment]
Forget my previous message! (I cleanup other lvim stuff before re-rerun `install.sh`)
It works fine now! :+1:

**Comment by Israr** [comment]
> It worked this time (on a Mac). I will try on ubuntu later.

Worked on ubuntu too.
