### ISSUE TITLE
[Bug]: Remove nlsp-settings from LunarVim

### ISSUE THREAD

**Issue by dhollinger** [LunarVim/LunarVim#1392]
### Feature motivation

After spending some time digging through the lua code in https://github.com/tamago324/nlsp-settings.nvim, I've found that the plugin makes some assumptions about Language Servers and generates configuration for many Language Servers from the VSCode extension `package.json` for a language server.

The problem with this is that many language servers are also maintained as standalone projects separate from the VSCode extension that implements it. This means the settings generated and used in nlsp-settings doesn't actually translate to the language server itself.

Additionally, it assumes that all settings are passed into the settings array within the config[server_name] table... which in standalone uses of the language servers is not appropriate. In fact, in some cases, such as `puppet` and `solargraph` some (or most) settings are passed in as options in the `cmd` and the `settings` array doesn't affect the launch of the LSP.

It may be easier to implement a separate plugin or LunarVim specific way of handling LSP config or simply go back to overriding the defaults from `lspconfig`.

### Describe the expected solution

Find a LSP settings solution that is easy for the user AND actually applies settings to each language server supported.

### Describe the alternatives you've considered

`nlsp-settings` isn't 100% functional even for all the language servers that are supported and the maintainer seems slow to review PRs and issues.

Some alternatives include:

- Creating a standalone plugin for all Neovim users
- Create a LunarVim-specific solution for simplifying LSP configuration overrides
- Simply go back to using normal lspconfig overrides in the config.lua file

**Comment by nahojer** [comment]
You have this very nice `on_config_done` function when customizing which-key. However, it serves no purpose when trying to configure your own LSP mappings. (Also, I want to remove the ["\<leader\>gg"] mapping because I don't use Lazygit and I find that it bloats my which-key "popup.") Can I suggest moving below code from the setup function of the which-key config (`lua/core/which-key.lua`) to `lua/core/builtins/init.lua`?

```lua
if lvim.builtin.which_key.on_config_done then
    lvim.builtin.which_key.on_config_done(which_key)
end
```

`lua/core/builtins/init.lua` could then look something like this:

```lua
local M = {}

local builtins = {
  "keymappings",
  "core.which-key",
  "core.gitsigns",
  "core.compe",
  "core.dashboard",
  "core.dap",
  "core.terminal",
  "core.telescope",
  "core.treesitter",
  "core.nvimtree",
  "core.project",
  "core.bufferline",
  "core.autopairs",
  "core.comment",
  "core.lspinstall",
  "core.lualine",
}

function M.config(config)
  for _, builtin_path in ipairs(builtins) do
    local builtin = require(builtin_path)
    builtin.config(config)
  end

  if lvim.builtin.which_key.on_config_done then
      lvim.builtin.which_key.on_config_done(which_key)
  end
end

return M
```

What do you think? Am I missing something that prevents us from doing this?

**Comment by abzcoding** [comment]
closed due to inactivity, feel free to reopen this
