### ISSUE TITLE
[Feature]: compe is deprecated use nvim-cmp

### ISSUE THREAD

**Issue by ashincoder** [LunarVim/LunarVim#1395]
### Feature motivation

No type of frustration. As stated compe was deprecated and nvim-cmp is improved I guess. 
https://github.com/hrsh7th/nvim-cmp

### Describe the expected solution

Move to nvim-cmp

### Describe the alternatives you've considered

https://github.com/hrsh7th/nvim-cmp

### Additional context

Nothing relevant --

**Comment by bobek** [comment]
Came across https://github.com/ms-jpq/coq_nvim recently. Seems to be an interesting alternative.

**Comment by ahmedkhalf** [comment]
no

**Comment by abzcoding** [comment]
done
