### ISSUE TITLE
Disable lunar vim based on certain condition

### ISSUE THREAD

**Issue by adarshchbs** [LunarVim/LunarVim#1404]
I want to use lunar vim but also want to use nvim inside vscode. Now I am trying to disable loading lunar vim using following command.

`
if not vim.g.vscode then  
    ''' body of lunar vim init.lua '''
end
`
but it still try to load packages using packer. Which lead to error in vscode.
Please let me know how to solve this issue.

**Comment by abzcoding** [comment]
closed due to inactivity, feel free to reopen
