### ISSUE TITLE
[Bug]: Telescope no result total num

### ISSUE THREAD

**Issue by nzlov** [LunarVim/LunarVim#1416]
### Problem description

`search text`

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5

### Screenshots

![image](https://user-images.githubusercontent.com/2859981/131210189-a10574a6-a42c-4367-b015-5e17dff8ace9.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

Default theme causes problems...

**Comment by abzcoding** [comment]
can you elaborate?

**Comment by abzcoding** [comment]
is this what you referring to?
<img width="705" alt="Screen Shot 2021-08-28 at 1 17 34 PM" src="https://user-images.githubusercontent.com/10992695/131212154-73f224b0-1ef8-458e-a025-c43446cea2bf.png">
cause we are changing the default theme pretty soon

**Comment by abzcoding** [comment]
cc: @ChristianChiarulli

**Comment by ChristianChiarulli** [comment]
what is the highlight group for this?

**Comment by abzcoding** [comment]
maybe this 
https://github.com/nvim-telescope/telescope.nvim/blob/50e5e86ac37ee3989a0015d3934c5a961012990a/lua/telescope/previewers/buffer_previewer.lua#L768
