### ISSUE TITLE
[Documentation]: neovim installer error

### ISSUE THREAD

**Issue by lapingenieur** [LunarVim/LunarVim#1417]
### Problem description

On Lunarvim's [website, part install/rolling](https://www.lunarvim.org/01-installing.html#rolling), this command errors:

```bash
bash <(curl -s https://raw.githubusercontent.com/lunarvim/LunarVim/rolling/utils/bin/install-latest-neovim)
```

The `install-latest-neovim` file only exists on the `master` branch (at least doesn't on the `rolling` branch)

* wrong link: [`https://raw.githubusercontent.com/lunarvim/LunarVim/rolling/utils/bin/install-latest-neovim`](https://raw.githubusercontent.com/lunarvim/LunarVim/rolling/utils/bin/install-latest-neovim)
* same on branch `master`: [`https://raw.githubusercontent.com/lunarvim/LunarVim/master/utils/bin/install-latest-neovim`](https://raw.githubusercontent.com/lunarvim/LunarVim/master/utils/bin/install-latest-neovim)

;)

### LunarVim version

rolling (documentation)

### Neovim version (>= 0.5)

all

### I have

- [x] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
https://github.com/LunarVim/lunarvim.org/commit/0903e7d4ae0ca369d8092f148737909583535f13
