### ISSUE TITLE
[Feature]: Select sources for compe

### ISSUE THREAD

**Issue by OliverNChalk** [LunarVim/LunarVim#1420]
### Feature motivation

Currently, it looks like the sources for compe are hardcoded / there is no way to disable sources? I don't find the Spell source particularly useful as it just clutters the autocomplete box, so I was looking if there was a way to disable it. I checked where compe was setup and you can see that it looks like there is not hook or config variables that would allow a user to disable a particular source: 

https://github.com/LunarVim/LunarVim/blob/d85584d09f9028fa4202cea473f7f0ae3c531aef/lua/core/compe.lua#L27-L42

### Describe the expected solution

Ideally, the user would be able to define an array of sources if they wish to override the default. Or more conveniently, there would be a sources object that would map `source -> boolean`, allowing the user to easily disable a single source (in my case, I would simply set the Spell source to false).

### Describe the alternatives you've considered

Forking lunarvim, seems counter to the current direction the team is trying to go with the centralized and more expressive config file.

**Comment by abzcoding** [comment]
can you test
```lua
lvim.builtin.compe.source.spell = false
```

**Comment by OliverNChalk** [comment]
I was prepared for some mind-bending voodoo to cause that to work, however, it doesn't seem to. I'm still getting Spell suggestions

**Comment by abzcoding** [comment]
> I was prepared for some mind-bending voodoo to cause that to work, however, it doesn't seem to. I'm still getting Spell suggestions

quick question do you get ` (Spell)` in the autocompletion menu?

**Comment by abzcoding** [comment]
like instead of `LSP` do you get `Spell` ?
<img width="375" alt="Screen Shot 2021-08-30 at 10 51 58 AM" src="https://user-images.githubusercontent.com/10992695/131294367-898e85c1-29f9-4911-a9f4-21fad8054be7.png">

**Comment by OliverNChalk** [comment]
It shows up as `(Text) [LSP]`:
![image](https://user-images.githubusercontent.com/11343499/131303000-fd46c12f-57c9-496d-bcb0-c802dd119318.png)

**Comment by abzcoding** [comment]
ok so those come from the language server not the spelling

**Comment by abzcoding** [comment]
normal neovim even with `nvim-cmp` has the same issue
<img width="951" alt="Screen Shot 2021-08-30 at 12 19 25 PM" src="https://user-images.githubusercontent.com/10992695/131304897-c323b0fd-fba4-4d80-b83f-907f436084bc.png">
