### ISSUE TITLE
[Bug]: term_mode mapping ending in <Esc> doesn't work

### ISSUE THREAD

**Issue by gmunguia** [LunarVim/LunarVim#1421]
First, thanks for LunarVim 🤗!

#### Steps to reproduce

On a fresh LunarVim install, add the mappings:

```lua
lvim.keys.term_mode = {
  ["<Leader><Esc>"] = "<C-\\><C-N>",
  ["b<Esc>"] = "<C-\\><C-N>",
  ["<Esc><Esc>"] = "<C-\\><C-N>",
  ["foo"] = "<C-\\><C-N>",
  ["ee"] = "<C-\\><C-N>",
}
```

Open a new terminal (`:terminal`) and try any of the mappings.

#### Things I've tried

These mappings work:

```lua
lvim.keys.term_mode = {
  ["<Leader>e"] = "<C-\\><C-N>",
  ["n"] = "<C-\\><C-N>",
  ["ba"] = "<C-\\><C-N>",
  ["<Esc>"] = "<C-\\><C-N>",
}
```

I've tried disabling built-in plugins and removing `noremap`.

Happy to collaborate on figuring this out, but I'm lost 😕.

### LunarVim version

Tried on latest stable (https://github.com/LunarVim/LunarVim/commit/e7b6d3b6f5982ea1042ffd499a7b85c18f0b782e) and rolling (https://github.com/LunarVim/LunarVim/commit/5ede0c906ab174678e39237fe55f24bc5ae99348).

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by qvieth** [comment]
try `vim.o.timeoutlen = 500`

**Comment by gmunguia** [comment]
That worked, thanks 🙌. In case this helps others, I added a pair of autocmds so increasing `timeoutlen` doesn't interfere with other things (e.g. which-key):

```lue
lvim.autocommands.custom_groups = {
  { "TermEnter", "*", "set timeoutlen=500" },
  { "TermLeave", "*", "set timeoutlen=100" },
}
```

**Comment by qvieth** [comment]
The main purpose of LunarVim default's `timeoutlen=100` is to make Whichkey responsive. This sometimes interferes with some users' key sequence. In case you have keybindings that don't work in normal mode, you can try increasing `timeoutlen` value to above 100 to see which value works(`timeoutlen=170` works for me without slowing Whichkey down too much).

**Comment by qvieth** [comment]
https://github.com/LunarVim/LunarVim/pull/1094
