### ISSUE TITLE
[Bug]: Terraform language server doesn't work anymore on the rolling branch

### ISSUE THREAD

**Issue by soerenmartius** [LunarVim/LunarVim#1423]
### Problem description

In the latest version of the rolling branch, the `terraform-ls` doesn't send any feedback to nvim anymore. All other language servers are working as expected. The 0.5.1 version seems to be fine.

1. Run `LspInstall terraform`
2. Open any Terraform file, insert broken code -> no feedback given by LSP

### LunarVim version

Latest Rolling

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+b35de6c52

### Screenshots

<img width="326" alt="Screenshot 2021-08-30 at 09 31 52" src="https://user-images.githubusercontent.com/930643/131295603-55fe776d-97e6-494d-87d8-9be04c12d439.png">
<img width="644" alt="Screenshot 2021-08-30 at 09 31 40" src="https://user-images.githubusercontent.com/930643/131295609-57c36590-6380-414a-809e-e9f0f1bd1600.png">
<img width="2048" alt="Screenshot 2021-08-30 at 09 26 22" src="https://user-images.githubusercontent.com/930643/131295615-bf53e831-c654-41b3-8c7f-8936fad0d9e1.png">
<img width="2048" alt="Screenshot 2021-08-30 at 09 26 11" src="https://user-images.githubusercontent.com/930643/131295631-3e4c5b3d-721b-44ff-9d62-39b4d8016e5e.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/131409671-4ce246e7-5195-4038-a408-8c937dd887da.png)

This is the latest rolling and the latest version of terraform ls, so I can't reproduce.

**Comment by soerenmartius** [comment]
> ![image](https://user-images.githubusercontent.com/29136904/131409671-4ce246e7-5195-4038-a408-8c937dd887da.png)
> 
> This is the latest rolling and the latest version of terraform ls, so I can't reproduce.

maybe that's one that occurs on OSX only? Will investigate a bit further tomorrow

**Comment by soerenmartius** [comment]
it seems to be an issue with the recent version of terraform-ls, sorry for the noise!
