### ISSUE TITLE
[Bug]:  Why do onedarker string and comment use the same color?

### ISSUE THREAD

**Issue by qvieth** [LunarVim/LunarVim#1425]
### Problem description

Green color for comment is weird.

### LunarVim version

rolling 5ede0c9

### Neovim version (>= 0.5)

0.5.0

### Screenshots

![image](https://user-images.githubusercontent.com/71810726/131330607-5741e026-9110-42cf-a56c-dba3a048273f.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
cc: @ChristianChiarulli

**Comment by chase** [comment]
I think this was an accident:
https://github.com/LunarVim/Colorschemes/blob/master/templates/onedarker.yml#L64

Treesitter-based comment highlighting is gray:
https://github.com/LunarVim/Colorschemes/blob/master/templates/onedarker.yml#L148

**Comment by ChristianChiarulli** [comment]
I'll fix this at some point today.

**Comment by ChristianChiarulli** [comment]
but also you should `:TSInstall lua`

**Comment by luxus** [comment]
should be fixed with this commit https://github.com/LunarVim/LunarVim/commit/dc1151a90aa68f4f8d5350e40daa67034241c0e9
