### ISSUE TITLE
[Bug]: Links in the README are broken

### ISSUE THREAD

**Issue by davibarreira** [LunarVim/LunarVim#1429]
### Problem description

Links such as the "For the julia language server look here" are broken in the README.

### LunarVim version

Master/Rolling

### Neovim version (>= 0.5)

Y

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
Thank you for mentioning this. I just updated all of those links in `rolling`.
gonna merge `rolling` into `master` pretty soon as well
