### ISSUE TITLE
[Feature]: Some small improvements for default Lunarvim colorscheme would be awesome

### ISSUE THREAD

**Issue by qvieth** [LunarVim/LunarVim#1431]
### Feature motivation

![image](https://user-images.githubusercontent.com/71810726/131436089-d191115f-ac65-4d19-bc09-94e01aafb989.png)

It seems like the default Lunarvim colorscheme onedarker is taken from LunarVim/Colorschemes, so I think mentioning all the relevant issues at once would be helpful.

Compare onedarker to onedark from [ChristianChiarulli/nvcode-color-schemes](https://github.com/ChristianChiarulli/nvcode-color-schemes.vim) :
- Markdown headers from [ChristianChiarulli/nvcode-color-schemes](https://github.com/ChristianChiarulli/nvcode-color-schemes.vim) colorschemes have different color while onedarker(and all colorschemes in [Lunarvim/Colorschemes](https://github.com/LunarVim/Colorschemes)) does not.
- Also codemonkey(and some other colorschemes) have this same issue with https://github.com/LunarVim/LunarVim/issues/1425 .
- Another also gruvbox and nord(and maybe all the others) from nvcode-colorscheme is really good please consider porting them to Lunarvim/Colorschemes.

**Comment by abzcoding** [comment]
cc: @ChristianChiarulli
