### ISSUE TITLE
[Bug]: `K` doesn't show hover correctly if used alongside flutter-tools.nvim

### ISSUE THREAD

**Issue by shivahnshankar** [LunarVim/LunarVim#1433]
### Problem description

In lua/keymappings.lua
`["K"] = ":move '<-2<CR>gv-gv",`
and in lua/lsp/init.lua
`["K"] = { "<cmd>lua vim.lsp.buf.hover()<CR>", "Show hover" },`
`:verbose map K` shows the first mapping is active.

Hence doHover is not working on lsp.

### LunarVim version

latest rolling

### Neovim version (>= 0.5)

NVIM v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by shivahnshankar** [comment]
Hmm..maybe this is related to the `flutter-tools.nvim` plugin for dart/flutter I am using. This plugin conflicts with the nvim-lspconfig and I have to explicitly disable the builtin dart lsp by using:
`lvim.lang.dart.lsp.provider = ""`
Maybe this is not creating the keymappings?

**Comment by abzcoding** [comment]
the first `K` is for `visual mode` and the second one is for `normal_mode` so that is not the issue

**Comment by shivahnshankar** [comment]
Right...but hover is still not working with the flutter-tools.nvim plugin. I am able to do the following though:
`:lua vim.lsp.buf.hover()`
and get the hover functionality working.

**Comment by abzcoding** [comment]
> Right...but hover is still not working with the flutter-tools.nvim plugin. I am able to do the following though:
> `:lua vim.lsp.buf.hover()`
> and get the hover functionality working.

can you do 
```vim
:verbose map K
:verbose noremap K
:verbose nnoremap K
```
to make sure nothing else conflicts

**Comment by shivahnshankar** [comment]
Well i am sure that flutter-tools.nvim and the requirement to not setup LSP is messing with the keybindings.
So lets say i have config.lua open in a buffer. I try:
`:verbose map K`
and i get
<pre>
n  K           *@<Cmd>lua vim.lsp.buf.hover()<CR>
x  K           * :move '<-2<CR>gv-gv
Last set from ~/.local/share/lunarvim/lvim/init.lua
</pre>
However, if i open a flutter/dart file, and i try:
`:verbose map K`
i get
<pre>
x  K           * :move '<-2<CR>gv-gv/lunarvim/lvim/init.lua
        Last set from ~/.local/share/lunarvim/lvim/init.lua
</pre>
Note that flutter-tools.nvim requires nvim-lspconfig lsp config to be disabled. Is the keybind linked to the lsp setup function and hence never gets called?

**Comment by abzcoding** [comment]
yes that is exactly the issue
```lua
local function add_lsp_buffer_keybindings(bufnr)
  local status_ok, wk = pcall(require, "which-key")
  if not status_ok then
    return
  end

  local keys = {
    ["K"] = { "<cmd>lua vim.lsp.buf.hover()<CR>", "Show hover" },
    ["gd"] = { "<cmd>lua vim.lsp.buf.definition()<CR>", "Goto Definition" },
    ["gD"] = { "<cmd>lua vim.lsp.buf.declaration()<CR>", "Goto declaration" },
    ["gr"] = { "<cmd>lua vim.lsp.buf.references()<CR>", "Goto references" },
    ["gI"] = { "<cmd>lua vim.lsp.buf.implementation()<CR>", "Goto Implementation" },
    ["gs"] = { "<cmd>lua vim.lsp.buf.signature_help()<CR>", "show signature help" },
    ["gp"] = { "<cmd>lua require'lsp.peek'.Peek('definition')<CR>", "Peek definition" },
    ["gl"] = {
      "<cmd>lua vim.lsp.diagnostic.show_line_diagnostics({ show_header = false, border = 'single' })<CR>",
      "Show line diagnostics",
    },
  }
  wk.register(keys, { mode = "n", buffer = bufnr })
end
function M.common_on_attach(client, bufnr)
  if lvim.lsp.on_attach_callback then
    lvim.lsp.on_attach_callback(client, bufnr)
    Log:debug "Called lsp.on_init_callback"
  end
  lsp_highlight_document(client)
  add_lsp_buffer_keybindings(bufnr)
  require("lsp.null-ls").setup(vim.bo.filetype)
end

```

**Comment by abzcoding** [comment]
if you want to disable the lsp, just map that key yourself 😅

**Comment by abzcoding** [comment]
here is how you can do it, add this to your `config.lua`
```lua
lvim.builtin.which_key.mappings["K"] = { "<cmd>lua vim.lsp.buf.hover()<CR>", "Show hover" }
```

**Comment by shivahnshankar** [comment]
Thanks..that works for me.
