### ISSUE TITLE
for some reasons when i try to install the tsserver it gives me error 

### ISSUE THREAD

**Issue by imSafdarAwan** [LunarVim/LunarVim#1439]
### Problem description

I just installed the linux and i tried to run the 

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

letest

### Neovim version (>= 0.5)

nightly

### Relevant log output

```shell
:LspInstall typescript
```

### Screenshots

![image](https://user-images.githubusercontent.com/87114084/131623242-34b55397-82c2-4ee6-a77c-d69c75b23e53.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by imSafdarAwan** [comment]
i think npm is giving me this error can anybody solve this prob
![image](https://user-images.githubusercontent.com/87114084/131656906-69c74f54-8f00-4ce0-8865-cb036a58d39d.png)

**Comment by abzcoding** [comment]
unrelated to lunarvim
