### ISSUE TITLE
[Bug]: Runtimepath not set correctly, some user plugins are not loaded

### ISSUE THREAD

**Issue by aaronsms** [LunarVim/LunarVim#1442]
### Problem description

After #1354, the order of the runtimepath is not set correctly anymore. The */after paths are expected to come at the end. But _~/.local/share/lunarvim/site_ instead comes after _~/.config/lvim/after_, which causes some users plugins to be not loaded correctly.

### LunarVim version

rolling

### Neovim version (>= 0.5)

v0.6.0

### Relevant log output

```shell
packpath=/etc/xdg/xdg-ubuntu/nvim,/etc/xdg/nvim,/usr/share/ubuntu/nvim/site,/usr/loc
al/share/nvim/site,/usr/share/nvim/site,/var/lib/snapd/desktop/nvim/site,/usr/local/sh
are/nvim/runtime,/usr/local/lib/nvim,/var/lib/snapd/desktop/nvim/site/after,/usr/share
/nvim/site/after,/usr/local/share/nvim/site/after,/usr/share/ubuntu/nvim/site/after,/e
tc/xdg/nvim/after,/etc/xdg/xdg-ubuntu/nvim/after,~/.local/share/lunarvim/lvim,~/.confi
g/lvim,~/.config/lvim/after,~/.local/share/lunarvim/site,~/.local/share/lunarvim/site/
after
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
cc: @kylo252
