### ISSUE TITLE
[Bug]: Wordlist download throws an error

### ISSUE THREAD

**Issue by bob3000** [LunarVim/LunarVim#1445]
### Problem description

There is a problem with the download of word lists when setting `spelllang` to a value other then `en`.

Steps to reproduce:
1. Open a random file in lvim
2. `:set spelllang=de_de`
3. `set spell`

causes

```
spellfile#LoadFile(): No (writable) spell directory found.
Failed to create: /home/bob/.local/share/nvim/site/spell
Warning: Cannot find word list "de.utf-8.spl" or "de.ascii.spl"
```

The worst is that the error message is completely misleading because in my case the directory indicated was existing and writable.

**The solution** is simple but because of the misleading error message it might take a minute to get there

```
mkdir ~/.local/share/lunarvim/site/spell
```

After the directory is created the downloading of missing word lists is offered as usual. 
Since I already got the solution I actually wanted to open a PR but  I wasn't sure what would be the best way to fix the issue? Should the directory simply be created during installation? That would however not fix existing installations. Maybe any other suggestions?

### LunarVim version

rolling

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+206-g284199bc4

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
I mentioned in another PR that I'm not sure if this variable is set correctly. Do you have any suggestions on how it should look like?

**Comment by bob3000** [comment]
@kylo252 From what I understand so far the `spellfile` setting should not be directly related to this one issue. It might even be a neovim bug (at least the error message) since for some reason neovim seems to create the `spell` directory under `~/.local/share/nvim/site/spell` and then tries to download the word list to `~/.local/share/lunarvim/site/spell` where no `spell` directory was created.

Nevertheless the `spellfile` setting could be a possible solution for this one issue because if it would be set to `~/.local/share/lunarvim/site/spell/en.utf-8.add`. Then nvim should actually create the missing `spell` directory (according to `:help spellfile`) and therefore solve the problem. Best would be if there was a setting to explicitly set a directory for wordlists downloads. Couldn't find one though.

**Comment by bob3000** [comment]
I just stumbled upon the `SpellFileMissing` event which would allow to create the directory in an auto command like

```
{ "SpellFileMissing", "*", ":!mkdir -p ~/.local/share/lunarvim/site/spell" },
```

It sovles the problem but it requires to restart nvim after the aucmd created the directory which is a bit ugly. Thereafter the wordlist will be downloaded as it is supposed to be. Maybe this approach could be further improved to avoid the restart.

**Comment by abzcoding** [comment]
feel free to reopen this issue if it persists

**Comment by omalaspinas** [comment]
Hello,

I think I have a somewhat similar issue. I don't know if it is exactly the same though.

After being offered with downloading the spell file I get an error message which does not make sense to me (running neovim 0.6.1). Any ideas?

```bash
No spell file for "de" in utf-8
Download it?

Downloading de.utf-8.spl...
Error detected while processing function spellfile#LoadFile[67]..spellfile#Nread:
line   13:
E117: Unknown function: netrw#NetRead
Could not find it, trying de.ascii.spl...
Error detected while processing function spellfile#LoadFile[92]..spellfile#Nread:
line   13:
E117: Unknown function: netrw#NetRead
Download failed
Warning: Cannot find word list "de.utf-8.spl" or "de.ascii.spl"
```

**Comment by bob3000** [comment]
@omalaspinas This issue is caused by the fact that netrw was disabled which seems to be required to download the spell files.
It's technically a setting but since it breaks basic neovim functionality it could also be consider this a bug.

Here is a workaround for the moment:
Edit `.local/share/lunarvim/lvim/lua/lvim/core/nvimtree.lua` and change the setting `disable_netrw` to false. Restart lvim and the spell files should download correctly.

**Comment by abzcoding** [comment]
please do not edit that file directly
just add this to your config
```lua
lvim.builtin.nvimtree.setup.disable_netrw = false
```

**Comment by omalaspinas** [comment]
thanks!
