### ISSUE TITLE
[Bug]: LspInstall yaml not working

### ISSUE THREAD

**Issue by davibarreira** [LunarVim/LunarVim#1448]
### Problem description

When I run the ``:LspInstall yaml`` I get an error saying 
```
bash: line 2: yarn: command not found
bash: line 3: yarn: command not found
```
By the way, I'm running Pop_os 21.04.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [ ] The programs specified by the config are installed

### LunarVim version

Master

### Neovim version (>= 0.5)

Yes

### Relevant log output

```shell
bash: line 2: yarn: command not found
bash: line 3: yarn: command not found
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
This isn't really a lunarvim issue.  Install yarn first then try `:LspInstall yaml` again.
