### ISSUE TITLE
[Bug]:  <M-h> bindings not working on mac

### ISSUE THREAD

**Issue by John15321** [LunarVim/LunarVim#1452]
### Problem description

Hi, Im new to vim. Im following your youtube tutorial, Im on episode 3, and it looks like meta keybindings don't work on mac for me. I was hoping you could help me with that

### LunarVim version

none

### Neovim version (>= 0.5)

0.6.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Xuanluo-Qiu** [comment]
Hey, I have the same's error, How can I fix this?
