### ISSUE TITLE
[Bug]: Hover and GoTo definition not working on Rust filetypes

### ISSUE THREAD

**Issue by sanevillain** [LunarVim/LunarVim#1456]
### Problem description

Hover and GoTo definition not working on Rust filetypes. 
Might be an issue on my local machine or something to do with rust-analyzer but wanted to post in case someone else currently has, or has had the same issue before. 

### LunarVim version

0.5

### Neovim version (>= 0.5)

0.5

### Screenshots

![Screenshot 2021-09-03 at 11 47 51](https://user-images.githubusercontent.com/43202006/131986351-f78de59b-2b18-4b57-a381-ce16d5e6f844.png)

This is the output that I get when I try to peek into the definition of a library function

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Tastyep** [comment]
Did you try visiting the page ?

**Comment by sanevillain** [comment]
> Did you try visiting the page ?

Do you mean the rust-analyzer page ?
