### ISSUE TITLE
[Bug]: Error setting theme on new installation using old config.lua

### ISSUE THREAD

**Issue by kabessao** [LunarVim/LunarVim#1460]
### Problem description

Because I use multiple computers I've decided to make my config.lua fail proof for new installations without having to edit it, and everything works fine, except theme.

I use tokyonight, and on new installations it always fails when setting it as the theme before downloading it.

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.5.0

### Screenshots

![image](https://user-images.githubusercontent.com/22626848/132066312-008f9d31-0b4a-4eac-b1f5-aec7bfad78fc.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
When you say `I use tokyonight, and on new installations it always fails when setting it as the theme before downloading it.`

Does it work after a `:PackerSync`?   

There is no way for the theme to work before downloading it.

**Comment by kabessao** [comment]
Yes, I forgot to address the rest, my bad.

What I would want is to lvim to keep the default theme if it fails, like in this case, or check if the theme is present before setting it.

For new installation using ```PackerSync``` or ```PackerUpdate``` is not a problem for me, it is just the error that bothers me a little.

**Comment by abzcoding** [comment]
i guess you can have sth like this in your config
```lua
  local status_ok, tk = pcall(require, "tokyonight")
  if status_ok then
    -- set tokyonight theme 
  else
     -- or download tokyonight
    -- set normal theme
  end
```

**Comment by kabessao** [comment]
Yep, that does solve this, I was using the vimscript version of tokyonight, thank you for showing me that there is a lua version of it, i didn't knew about it.
