### ISSUE TITLE
[Feature]: Return to last edit position when opening files

### ISSUE THREAD

**Issue by simonfontana** [LunarVim/LunarVim#1461]
### Feature motivation

Keep the position between sessions. It's a common feature in most IDEs. 

I've added a possible solution to my fork: https://github.com/simonfontana/LunarVim/commit/029ef74e49ff0a6170ad320a532d35792ef01b76

However it is in vimscript and I don't know how to do it in Lua. Maybe someone can help?

**Comment by abzcoding** [comment]
```lua
vim.cmd [[
  autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | execute "normal! g`\"" | endif
]]
```
or maybe this
```lua
  lvim.autocommands.custom_groups = {
  lvim.autocommands.custom_groups = {
    {"BufReadPost", "*", 'if line("\'\\"") > 1 && line("\'\\"") <= line("$") | execute "normal! g`\\"" | endif'},
  }
```

**Comment by abzcoding** [comment]
@simonfontana i'm closing this bcz of no response, feel free to reopen it if those commands didn't help you
