### ISSUE TITLE
[Feature]: Documentation generation snippets (JSDoc, etc...)

### ISSUE THREAD

**Issue by gikari** [LunarVim/LunarVim#1466]
### Feature motivation

VSCode has the nice feature, when writing TypeScript files: JSDoc snippet.
You type `/**` on the line above of the function definition, then press enter...

![Screenshot_20210904_135234](https://user-images.githubusercontent.com/14205339/132092039-b4097cb7-28bb-4989-bdd1-f21e0324546b.png)

...and it automatically generates appropriate documentation boilerplate code to then fill it in.

![Screenshot_20210904_135253](https://user-images.githubusercontent.com/14205339/132092046-240cde20-1de9-4e0f-9663-17ee220849a6.png)

Typing these comments by hand is a chore, and the above described feature is a very nice addition to productivity.

### Describe the expected solution

Add snippets for documentation comments for various languages (Java, TypeScript, C++ etc).

**Comment by abzcoding** [comment]
we can maybe use https://github.com/danymat/neogen or sth

**Comment by Uzaaft** [comment]
@gikari  Have you done anything special with your tsserver? My vscode does not do that...

**Comment by Uzaaft** [comment]
A quick look at the tsserver log in vscode, and this **seem** to be somethign baked into tsserver.
Would be ideal to do this without adding another library. Perhaps this can be added to the snippets library we use instead.

**Comment by kylo252** [comment]
I think this has been fixed in later cmp updates, please let me know if you're still having problems with this.
