### ISSUE TITLE
[Bug]: Bashls changes root of the project

### ISSUE THREAD

**Issue by gikari** [LunarVim/LunarVim#1467]
### Steps to reproduce:

1. Create git repo
2. Create any file (sample.js or something, it does no matter) and open it
3. Create a directory with bash script file in it. The project structure would be:
![Screenshot_20210904_191421](https://user-images.githubusercontent.com/14205339/132101255-27c79a49-7901-4af3-9663-b7b8c1e1cc63.png)

4. Open bash script, e.g. from nvim-tree

### Observed behavior:

Project root changes, therefore nvim-tree jumps to new root
![Screenshot_20210904_191402](https://user-images.githubusercontent.com/14205339/132101230-91482ac2-5cc2-4795-884c-f69dca226f50.png)

### Expected behavior

Project root does not change and stays where .git directory is.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5

### Relevant log output

```shell
LspInfo:

Configured servers: cmake, null-ls, typescript, tsserver, dockerfile, yaml, json, bashls, python, lua, rust, bash, cpp, efm
Neovim logs at: /home/gikari/.cache/nvim/lsp.log

1 client(s) attached to this buffer: bashls

  Client: bashls (id: 4 pid: 544367)
  	root:      /home/gikari/temporal/scripts
  	filetypes: sh
  	cmd:       /home/gikari/.local/share/nvim/lspinstall/bash/node_modules/.bin/bash-language-server start
  	autostart: True

2 active client(s): 

  Client: bashls (id: 4 pid: 544367)
  	root:      /home/gikari/temporal/scripts
  	filetypes: sh
  	cmd:       /home/gikari/.local/share/nvim/lspinstall/bash/node_modules/.bin/bash-language-server start
  	autostart: True

  Client: tsserver (id: 3 pid: 544267)
  	root:      /home/gikari/temporal
  	filetypes: javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
  	cmd:       /home/gikari/.local/share/nvim/lspinstall/typescript/node_modules/.bin/typescript-language-server --stdio
  	autostart: True
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
that is the default behavior from `https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#bashls`
you can change that by setting `lvim.lang.sh.lsp.setup.root_dir`

**Comment by gikari** [comment]
That's bad default behavior. Why would you want to change the directory, when **editing** a script file, which is part of the large project?

**Comment by abzcoding** [comment]
well you can do a PR to `nvim-lspconfig` and fix that i guess

**Comment by mjlbach** [comment]
fyi lspconfig does not change cwd, that's probably your project rooter in lunarvim. root detection in lspconfig is entirely internal

**Comment by abzcoding** [comment]
> fyi lspconfig does not change cwd, that's probably your project rooter in lunarvim. root detection in lspconfig is entirely internal

cc: @ahmedkhalf

**Comment by abzcoding** [comment]
@mjlbach this commit fixed issue https://github.com/neovim/nvim-lspconfig/commit/2f026f2177bff7c9599d8dc561a4bdb30626ad9c

**Comment by ahmedkhalf** [comment]
For future reference, another way this can be solved is by changing the order of the detection_methods.
```lua
lvim.builtin.project.detection_methods = { "pattern", "lsp" }
```
