### ISSUE TITLE
[Bug]: Permission denied to install node modules with npm

### ISSUE THREAD

**Issue by rpm89** [LunarVim/LunarVim#1468]
Hi, I'm trying to install the rolling release following the steps presented in https://www.lunarvim.org/01-installing.html#rolling 

But I get the following error when executing the `LVBRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)` command:

Would you like to install lunarvim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
Installing node modules with npm..
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/lib/node_modules/tree-sitter-cli
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/tree-sitter-cli'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/tree-sitter-cli'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/lib/node_modules/tree-sitter-cli'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

I see its a permission related issue, but I don't know how to avoid it. When or how should I give it sudo privileges?

**Comment by abzcoding** [comment]
you can follow this to make sure you wouldn't need sudo to use `-g`
`https://github.com/sindresorhus/guides/blob/main/npm-global-without-sudo.md`
or install the dependency yourself and respond `n` in there
```sh
npm install -g neovim
npm install -g tree-sitter-cli
```

**Comment by rpm89** [comment]
Hi. Thank you. 
I've installed the dependencies the way you'd said and tried to install the lunarvim again.
But now I'm having another problem. After installing the rust dependencies, I get:

packer.nvim: Error running config for nvim-treesitter: ...meira/.local/share/lunarvim/lvim/lua/core/treesitter.lua:70: attempt to call method 'get_default' (a nil value)
Press ENTER or type command to continue

**Comment by Mat-moran** [comment]
I am in the same step and I am also facing problems with Rust dependencies if you click yes.

```
Would you like to check lunarvim's Rust dependencies?
[y]es or [n]o (default: no) : y
Installing missing Rust dependency with cargo
/proc/self/fd/11: line 191: cargo: command not found
```

Thanks in advance.

**Comment by abzcoding** [comment]
> Hi. Thank you.
> I've installed the dependencies the way you'd said and tried to install the lunarvim again.
> But now I'm having another problem. After installing the rust dependencies, I get:
> 
> packer.nvim: Error running config for nvim-treesitter: ...meira/.local/share/lunarvim/lvim/lua/core/treesitter.lua:70: attempt to call method 'get_default' (a nil value)
> Press ENTER or type command to continue

just run `:PackerSync` inside lvim after installation, and that error goes away

**Comment by abzcoding** [comment]
> I am in the same step and I am also facing problems with Rust dependencies if you click yes.
> 
> ```
> Would you like to check lunarvim's Rust dependencies?
> [y]es or [n]o (default: no) : y
> Installing missing Rust dependency with cargo
> /proc/self/fd/11: line 191: cargo: command not found
> ```
> 
> Thanks in advance.

you can either install `cargo` or install `ripgrep` and `fd-find` yourself

**Comment by abzcoding** [comment]
btw guys i would suggest joining our discord, you can find the solution to your issues and also chat with other users
to get suggestions for cool plugins and stuff

`#AD` 😅

**Comment by Mat-moran** [comment]
Ouu Thanks @abzcoding I will do definitely!!

**Comment by rpm89** [comment]
> > Hi. Thank you.
> > I've installed the dependencies the way you'd said and tried to install the lunarvim again.
> > But now I'm having another problem. After installing the rust dependencies, I get:
> > packer.nvim: Error running config for nvim-treesitter: ...meira/.local/share/lunarvim/lvim/lua/core/treesitter.lua:70: attempt to call method 'get_default' (a nil value)
> > Press ENTER or type command to continue
> 
> just run `:PackerSync` inside lvim after installation, and that error goes away

I can't even start lvim to run that command. When I finish the installation with that error and try to open lvim I get:

fish: Unknown command: lvim

I tried to unistall and install again, but I get this:

rm: cannot remove '/usr/local/bin/lvim': No such file or directory

The other 2 commands on the unninstall part of the site goes well:

rm -rf ~/.local/share/lunarvim
rm -rf ~/.local/share/applications/lvim.desktop

I don't think the installation is getting complete

**Comment by abzcoding** [comment]
lunarvim will install in `~/.local/bin/lvim`

**Comment by jayedeem** [comment]
I ran into the same problem, i deleted ~/.config/lvim and all the other folders ran the install script again and it worked.

**Comment by rpm89** [comment]
> lunarvim will install in `~/.local/bin/lvim`

That wasn't o my fish PATH. I put it now.
And now I could finally open LunarVim. I ran the `:PackerSync` and it worked. Everything is working properly now.
Thank you so much for the help!
