### ISSUE TITLE
[Bug]: Which key is hard to read due to transparency

### ISSUE THREAD

**Issue by kingedward35** [LunarVim/LunarVim#1469]
### Problem description

I updated my plugins and noticed that the background for which key and other popups (the ones that shows after installing or updating plugins) is now transparent and is hard to read. I am wondering if there is some way to turn off transparency for all LVIM popup windows? I also tried reinstalling LunarVim, but I still get the same issue.

### LunarVim version

Rolling

### Neovim version (>= 0.5)

0.5

### Screenshots

![image](https://user-images.githubusercontent.com/12418717/132102355-3283677b-9ab7-485d-bef4-bcdc1ebcb4ea.png)
![image](https://user-images.githubusercontent.com/12418717/132102399-fd95342e-8551-4087-a9de-ffcdda0cfcc7.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
that is not our theme though 😢

**Comment by abzcoding** [comment]
this is what default lunarvim looks like
<img width="1447" alt="Screen Shot 2021-09-04 at 9 29 02 PM" src="https://user-images.githubusercontent.com/10992695/132102557-cd291742-b636-4ebe-b529-9163c4e3d048.png">

**Comment by kingedward35** [comment]
I understand that is not your theme, but I have been running the same theme for the last 3 weeks and only recently does which key and the other pop ups begin to look like this. Previously, they looked similar to your screenshot, but they had the same theme as mine. The only difference was that it didn't have transparency. I was wondering if that might have been added during a recent LunarVim update?

**Comment by abzcoding** [comment]
from what i recall transparency is off by default and can only be enabled if you have this in your `config.lua`
```lua
lvim.transparent_window = true
```

**Comment by abzcoding** [comment]
also you can check the configurations for your theme to see if they have any transparency-related configuration or not

**Comment by kingedward35** [comment]
I can definitely tell you that I do not have transparency turned on. (I hate transparency).

**Comment by abzcoding** [comment]
then i would suggest checking the repo for your theme to see their configurations, cause we have not changed anything related to transparency in the recent month

**Comment by kingedward35** [comment]
The repo for my theme should not have changed. I forked the repo for the `zephyr` theme and haven't updated it in close to a month.

**Comment by abzcoding** [comment]
this is the only part regarding transparency in our code, so not sure what to tell you
```lua
  if lvim.transparent_window then
    cmd "au ColorScheme * hi Normal ctermbg=none guibg=none"
    cmd "au ColorScheme * hi SignColumn ctermbg=none guibg=none"
    cmd "au ColorScheme * hi NormalNC ctermbg=none guibg=none"
    cmd "au ColorScheme * hi MsgArea ctermbg=none guibg=none"
    cmd "au ColorScheme * hi TelescopeBorder ctermbg=none guibg=none"
    cmd "au ColorScheme * hi NvimTreeNormal ctermbg=none guibg=none"
    cmd "let &fcs='eob: '"
  end
```

**Comment by kingedward35** [comment]
Thanks.

**Comment by kingedward35** [comment]
Looks like the issue was with another plugin: `auto-session`. Removing this plugin fixes the issue. I know this thread is closed and I appreciated your help, but would you happen to know another plugin or another way to restore and save LunarVim sessions?

**Comment by abzcoding** [comment]
i would highly recommend https://github.com/folke/persistence.nvim

**Comment by kingedward35** [comment]
Thanks alot.
