### ISSUE TITLE
[Bug]: Plugins don't auto-install if plugins listed in another file

### ISSUE THREAD

**Issue by LandonSchropp** [LunarVim/LunarVim#1475]
### Problem description

I have quite a few plugins in my NeoVim configuration, as well as many other settings. In order to keep my configuration clean, I've split it into several different Lua files.

`config.lua`:

``` lua
require("settings")
require("keys")
require("plugins")
```

`lua/plugins.lua`:

```
lvim.plugins = {
  {"folke/tokyonight.nvim"},
  {"folke/trouble.nvim"},
  {'airblade/vim-rooter'}
}
```

This works great for most of my settings, but doesn't seem to be working for the plugin installer.

If I save the configuration file, none of my plugins are installed. I also don't see anything if I run `:PackerInstall`, or if I restart LunarVim.

However, as soon as I move my plugins to `config.lua`, everything works perfectly.

### LunarVim version

Latest (as of today)

### Neovim version (>= 0.5)

v0.5.0

### Relevant log output

```shell
N/A
```

### Screenshots

N/A

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by LandonSchropp** [comment]
The problem here was in my config.

**Comment by nix-universe** [comment]
@LandonSchropp, could you please explain what exactly the problem was?

**Comment by LandonSchropp** [comment]
@nix-universe It’s been quite a while, but I believe the problem was a simple Lua syntax error.

**Comment by nix-universe** [comment]
@LandonSchropp Thanks for your reply! In the meantime, an update from nvim 0.10.3(?) to 0.10.4 fixed the issue for me.
