### ISSUE TITLE
[Bug]: .config/lvim/config.lua:16: attempt to index field 'diagnostics' (a nil value)

### ISSUE THREAD

**Issue by John15321** [LunarVim/LunarVim#1478]
### Problem description

(Im on MacOS btw, Intel)

I have been trying to follow your setup videos, but it looks like my IntelliSense is in some weird way restricted. I don't get any [LSP] autocompletion, and now that I'm trying to disable virtual text like you did Im getting this error?

```
.config/lvim/config.lua:16: attempt to index field 'diagnostics' (a nil value)
```

![image](https://user-images.githubusercontent.com/56229312/132134281-57f43066-76a8-426f-a8dc-8bff6c83915a.png)

### LunarVim version

I just

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+210-g6751d6254

### Relevant log output

```shell
NVIM v0.6.0-dev+210-g6751d6254
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by jbron@WRO-JBRON-MB-01

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-6751d62/share/nvim"

Run :checkhealth for more info
```

### Screenshots

Additionally, that's what it looks like when I try to write

```python
import numpy as np
```

It warps the text in a weird way, when I go to a different line it seems fine, I don't get any autosuggestion

![image](https://user-images.githubusercontent.com/56229312/132134337-e6e24f04-99c3-4a59-88cc-5ab4d8c0f79b.png)

![image](https://user-images.githubusercontent.com/56229312/132134374-0b8a2b88-cbec-4ae5-942e-7de35c74a475.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
```lua
lvim.lsp.diagnostics.virtual_text = false
```

**Comment by John15321** [comment]
> ```lua
> ```lua
> lvim.lsp.diagnostics.virtual_text = false
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
>       
> ```

Thanks that worked but Im still not getting IntelliSense so Im gonna make another Issue about that I guess. I did LspInstall python and I did `y` for checking my python dependencies during the install

**Comment by abzcoding** [comment]
hop on discord it would be easier to fix and you would get to know the community

**Comment by John15321** [comment]
> hop on discord it would be easier to fix and you would get to know the community

Thats a good idea! Sure give me a second
