### ISSUE TITLE
[Bug]: Avoiding naming collisions with LunarVim Lua files

### ISSUE THREAD

**Issue by LandonSchropp** [LunarVim/LunarVim#1479]
### Problem description

I recently ran into an issue that took me quite a while to figure out.

The configuration I'm importing from NeoVim is somewhat large, and I've always liked to split it into several files. Here's what my `config.lua` file looked like:

``` lua
require("settings")
require("keys")
require("plugins")
```

What I didn't realize the time was that there's already a `plugins.lua` file present in LunarVim. When I tried loading LunarVim, I'd get an obscure error because my `plugins.lua` file was earlier in the `runtimepath`. This would cause LunarVim to load the wrong file and fail.

For now, I renamed my plugins file to `local_plugins.lua` to avoid the problem.

Is there any way to avoid this type of naming collision? I understand this is likely a larger problem with NeoVim's Lua imports, but I'm wondering if there's a pragmatic solution. Would it make sense for LunarVim to namespace its files to avoid collisions?

### LunarVim version

Latest

### Neovim version (>= 0.5)

v0.5.0

### Relevant log output

```shell
N/A
```

### Screenshots

N/A

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
You can put those files inside `~/.config/lvim/lua/user` and then require them with `require('user.plugins')`  

For an example configuration look here:  https://github.com/abzcoding/lvim

@Tastyep   You were right.  It happened.

**Comment by LandonSchropp** [comment]
Yep, that makes sense and it's how I'll solve this problem. I just wanted to bring up the issue since it took a while to figure out what was going on.

I opened up neovim/neovim#15574 to hopefully spur discussion around an alternative long-term solution in NeoVim.

**Comment by LandonSchropp** [comment]
Would it make sense for LunarVim to namespace its as well to avoid collisions? Something like `lunarvim/plugins.lua` and `require("lunarvim.plugins")`? I realize that's probably a big PITA for you guys, but I thought I'd ask in case another NeoVim Lua novice like myself runs into the same issue.

**Comment by rebuilt** [comment]
Yes.  That's the solution Tasty proposed.

**Comment by LandonSchropp** [comment]
I check with the NeoVim folks in neovim/neovim#15574, and this is what @gpanders said:

> Collisions are avoided by plugins properly namespacing their modules. Not doing so is an anti-pattern and is not something Neovim is likely to support. Besides, the ability for a user to override what module gets loaded upon `require()` is a feature, not a bug.

So it seems like they're encouraging plugin authors to namespace their modules.

**Comment by LandonSchropp** [comment]
Thank you!
