### ISSUE TITLE
[Feature]: Auto Import All Missing Dependencies in files

### ISSUE THREAD

**Issue by LandonSchropp** [LunarVim/LunarVim#1481]
### Feature motivation

I'm a big fan of the [vim-import-js](https://github.com/Galooshi/vim-import-js) and its ability to automatically import dependencies.  Some language servers also support the ability to auto-import symbols on completion, which is really cool. However, the downside to this is I don't always want to autocomplete a function to import it. For example, if I spell it wrong and then fix the spelling, I wouldn't trigger the completion auto-import. Or if I copy code from one file to another, I'd like to be able to quickly import all of the missing dependencies in the file.

### Describe the expected solution

I'd love a keyboard shortcut such as `<leader>lm` to automatically import all missing dependencies in the current file. I imagine that this would identify any undefined symbol, and attempt to import it.

### Describe the alternatives you've considered

I'll continue to use vim-import-js for JavaScript projects, and to use the auto-import features of language servers on completion.

### Additional context

N/A

**Comment by chase** [comment]
The implementation of this varies vastly among language servers, so I don't think this is reasonable

**Comment by yassinebridi** [comment]
This should be implemented by the typescript language server, this is the LSP that Lunarvim uses:

https://github.com/typescript-language-server/typescript-language-server/issues/235

**Comment by LandonSchropp** [comment]
@chase I thought I'd throw it out there, since it'd be a cool feature, but I understand if it's not feasible to implement.

@yassinebridi 👍

**Comment by marwan38** [comment]
@LandonSchropp Check out https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils, it does what you want.

**Comment by LandonSchropp** [comment]
@marwan38 Thanks for the suggestion! I'll incorporate that today.

**Comment by kamalkech** [comment]
@marwan38 archived !
