### ISSUE TITLE
[Bug]: Vue Template Random lines

### ISSUE THREAD

**Issue by RizaHKhan** [LunarVim/LunarVim#1482]
### Problem description

On random lines, these lines appear:

I don't think they mean anything and cannot be turned off.

### LunarVim version

Bleeding Edge

### Neovim version (>= 0.5)

0.5

### Screenshots

![2021-09-05_21-34-48](https://user-images.githubusercontent.com/51720003/132148600-5d15a8fa-65ec-4cd0-8e37-a9758e04a8b6.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Does it clear up if you write the file?  Do you have the  indentblankline plugin installed?

Can you provide a sample vue file to test.  This is what I see when I open my sample vue file.  But I don't work with vue at all.  

![image](https://user-images.githubusercontent.com/16025007/132223568-d92e893f-1e2c-476b-af6d-9136e3181131.png)

**Comment by RizaHKhan** [comment]
@rebuilt That plugin(indentblankline) seems to have done the trick. I no longer see those lines. 

Thank you,
