### ISSUE TITLE
[Bug]: When using emmet the output includes extra characters

### ISSUE THREAD

**Issue by RizaHKhan** [LunarVim/LunarVim#1483]
### Problem description

Say you type in a HMLT (Vue template in my case)

`div.myclassname` and press tab, it outputs the correct HTML tag but also includes appends extra characters (see screenshot).

### LunarVim version

Bleeding Edge

### Neovim version (>= 0.5)

0.5

### Screenshots

![2021-09-05_14-10-48](https://user-images.githubusercontent.com/51720003/132148695-96b5df21-0f3b-4771-b9ef-d28c543f7186.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Which emmet are you using?  If it's this one `https://github.com/aca/emmet-ls`.  It doesn't actually support vue.  The only officially supported filetypes are html and css.  File an issue on that project with your problem

This one should work for any filetype but you'll need to manually trigger the text transformation with `<C-y>,`
https://github.com/mattn/emmet-vim
