### ISSUE TITLE
[Bug]: Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/uri.lua:117: attempt to index local 'uri' (a nil va lue)

### ISSUE THREAD

**Issue by nzlov** [LunarVim/LunarVim#1484]
### Problem description

1. lspinstall go
2. open *.go file

Maybe lsp client sort?

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [ ] The programs specified by the config are installed

### LunarVim version

rolling

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+218-g3f526feeb

### Relevant log output

```shell
Language client log: /Users/nzlov/.cache/nvim/lsp.log
 Detected filetype:   go
 
 2 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, pid: 5001, bufnr: [13, 13])
 	filetypes:       
 	autostart:       false
 	root directory:  /Users/nzlov/workspaces/x/x
 	cmd:             nvim
 
 Client: gopls (id: 3, pid: 58600, bufnr: [13, 13, 13, 13])
 	filetypes:       go, gomod
 	autostart:       true
 	root directory:  /Users/nzlov/workspaces/x/x
 	cmd:             /Users/nzlov/.local/share/nvim/lspinstall/go/gopls
 
 Other clients that match the filetype: go
 
 Config: null-ls
 	filetypes:         go
 	root directory:    /Users/nzlov/workspaces/x/x
 	cmd:               nvim
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: gopls, graphql, null-ls, json, go
```

### Screenshots

![image](https://user-images.githubusercontent.com/2859981/132148735-74ec8413-3be5-4767-b24c-43b5ead89f95.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by andoni0305** [comment]
Same issue here

**Comment by mjlbach** [comment]
A plugin you are using has not adapted the handler call style to https://github.com/neovim/neovim/pull/15504

**Comment by LoganAMorrison** [comment]
@nzlov I had the same issue. Downgrading to neovim 0.5 seems to fix the issue.

**Comment by angryheng** [comment]
Same issue here

**Comment by angryheng** [comment]
> @nzlov I had the same issue. Downgrading to neovim 0.5 seems to fix the issue.

how to downgrading to neovim 0.5

**Comment by angryheng** [comment]
@LoganAMorrison how to Downgrading to neovim 0.5

**Comment by LoganAMorrison** [comment]
> @LoganAMorrison how to Downgrading to neovim 0.5

Just install the 0.5 [release](https://github.com/neovim/neovim/releases)

**Comment by angryheng** [comment]
@LoganAMorrison  Thanks

**Comment by abzcoding** [comment]
you are getting this error because we are using `nvim-compe` and that is not compatible with the latest neovim changes
install `noevim 0.5.0` for now, chris is planning to stream the migration to `nvim-cmp` but it might take a bit

**Comment by patlux** [comment]
```
~ ❯❯❯ nvim --version
NVIM v0.7.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by _nixbld1

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/ym92ijzgzvyivprdvl91grrjg5nr1yqv-neovim-unwrapped-master/share/nvim
"

Run :checkhealth for more info
```

works
