### ISSUE TITLE
[Bug]: Theme coloring failure when opening new files

### ISSUE THREAD

**Issue by angryheng** [LunarVim/LunarVim#1485]
### Problem description

Theme coloring failure when opening new files

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6.0

### Screenshots

![bug](https://user-images.githubusercontent.com/28853495/132154048-4e64b6d7-6b3d-4ef0-a2d3-5854a538d3b0.gif)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Minhvu1981** [comment]
https://user-images.githubusercontent.com/28853495/132154048-4e64b6d7-6b3d-4ef0-a2d3-5854a538d3b0.gif

**Comment by Minhvu1981** [comment]
https://user-images.githubusercontent.com/28853495/132154048-4e64b6d7-6b3d-4ef0-a2d3-5854a538d3b0.gif

**Comment by abzcoding** [comment]
you need treesitter for those colors
you can either install treesitter support for vim files using `:TSInstall vim`
or just install most of them using `:TSInstall maintained`

**Comment by angryheng** [comment]
@abzcoding Thanks
