### ISSUE TITLE
[Feature]: Recognise common variations of dockerfiles 

### ISSUE THREAD

**Issue by nahojer** [LunarVim/LunarVim#1491]
### Feature motivation

Dockerfiles are typically named in various ways. Here are some examples:

* Dockerfile
* dockerfile
* dev.dockerfile

### Describe the expected solution

Expect that these are recognised correctly. In my config.lua I've added

```lua
lvim.autocommands.custom_groups = {
  -- Recognize dockerfile correctly.
  { "BufWinEnter", "*[Dd]ockerfile", "setlocal filetype=dockerfile" },
  { "BufRead", "*[Dd]ockerfile", "setlocal filetype=dockerfile" },
  { "BufNewFile", "*[Dd]ockerfile", "setlocal filetype=dockerfile" },
}
```

but I imagine more people want this and that it might be a nice default. If you disagree, please close this issue.

**Comment by abzcoding** [comment]
can you remove those custom_groups and try again?
it should be a bit better after the last commit

**Comment by nahojer** [comment]
I see that you work fast 😎 Unfortunately I run LunarVim on master. Need that stability because I use it for work... But i checked the last commit in rolling and if that solves my problem it's a lot cleaner

**Comment by abzcoding** [comment]
gonna merge it pretty soon, so i'm gonna close this if that is ok with you 😅
