### ISSUE TITLE
[Feature]: motion support for code comments

### ISSUE THREAD

**Issue by baocang** [LunarVim/LunarVim#1493]
### Feature motivation

such as:
`2gcc` to comment two lines
`gcj` to comment current & next lines
`gciw` to comment current word 
`gci(`, `gci{` ...

### Describe the alternatives you've considered

disable vim-comment, use vim-commentary instead
switch to visual studio code + VSCodeVIM

**Comment by rebuilt** [comment]
Disabling vim-comment and using vim-commentary is what I do in my own config.
