### ISSUE TITLE
No longer letting me install

### ISSUE THREAD

**Issue by JoshTRN** [LunarVim/LunarVim#1495]
I had an installation from a few months back. I saw that some work had been done so I went to download the rolling branch and I can't install it at all. It's not writing a lunarvim configuration in the `.local/share` folder. I get this error upon opening:

`E282: Cannot read from "/home/joshua/.local/share/lunarvim/lvim/init.lua"`

OS: Garuda Linux
Host: XPS 13 9310
Kernel: 5.13.13-zen1-1-zen
Uptime: 2 days, 1 hour, 31 mins
Packages: 1716 (pacman)
Shell: fish
DE: Plasma 5.22.5
WM: KWin
WM Theme: Sweet-Dark
Terminal: konsole
CPU: 11th Gen Intel i7-1185G7 (8) @ 4.8GHz
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics]
Memory: 9.42GiB / 15.36GiB

When I install it, I first `sudo -s` to get super user privileges, then I run `bash` to get into a bash shell, then I run the rolling release installation command.

When I run lvim, I get that error. I'm not sure what the issue is as I've said previously, I had it installed previously. 

If anyone has some insights as to why it might not be creating the directory, it would be really helpful. Thanks.

**Comment by rebuilt** [comment]
You don't need sudo to install it anymore.  

You may need to delete the old launcher.  The old launcher used to be placed in `/usr/local/bin` which may take priority over where we place it now `~/.local/bin`  
run `which lvim`.   Remove the one you have installed.  Example  `sudo rm /usr/local/bin/lvim`

```bash
rm -rf ~/.local/share/lunarvim
sudo rm /usr/local/bin/lvim
rm ~/.local/bin/lvim
rm -rf ~/.cache/nvim
```

Your old config files will probably need to be updated if they're super old.  We've changed some of the options.  Is your config file named lv-config.lua or config.lua?

**Comment by JoshTRN** [comment]
It's config.lua

**Comment by abzcoding** [comment]
can you remove your previous installation and install lunarvim again without using sudo?

**Comment by kylo252** [comment]
Feel free to open a new ticket if you're still having issues.
