### ISSUE TITLE
[Bug]: Python slow to quit

### ISSUE THREAD

**Issue by argapost** [LunarVim/LunarVim#1504]
### Problem description

When I quit a python file it takes 1 second compared to other filetypes where the exit is instant (with lvim.format_on_save = false)

I know there was this issue https://github.com/LunarVim/LunarVim/issues/411 but it seems that the problem was the efm-langserver since there is no efm in the newest versions of lvim I thought to open a new issue.

Does anyone else experience the same type of lag?

### LunarVim version

Rolling

### Neovim version (>= 0.5)

NVIM v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rafamadriz** [comment]
I don't think that this is necessarily  because of lunarvim but maybe some plugin that is included by default, I have the same problem in my config and I don't use lunarvim. I have tried disabling tressitter and other things but can't find the reason for this.

**Comment by abzcoding** [comment]
@argapost can you try commenting your added plugins, then doing a `:PackerSync` to remove those plugins and testing it again?

**Comment by argapost** [comment]
Yes, I did and it remains laggy when I try to quit even on an empty test.py file.  

I LspUninstall python and it seems to solve the issue so the pyright language server seems to be the problem for me. 

Any ideas?

**Comment by abzcoding** [comment]
you can search their repo for a potential issue that got fixed
