### ISSUE TITLE
[Bug]: Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by ivano9** [LunarVim/LunarVim#1505]
### Problem description

1. Open the configuration of lvim
2. Show the error in the print screen

Also saw that sometimes when open another file open it uncolorized text

I tested it on master and rolling branch both same behaviour

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+27-g27118c6eb

### Screenshots

![image](https://user-images.githubusercontent.com/43305758/132518692-cb85f7ba-2615-4088-b137-cfed1167dd1c.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
plz update to the latest `rolling`, it should be fixed in there
or you can downgrade your neovim to `0.5 release`
this happened bcz of a breaking change in neovim head and the changes that plugins did in their code
