### ISSUE TITLE
Has any one package lunarvim for Nixos

### ISSUE THREAD

**Issue by Dulanjala007** [LunarVim/LunarVim#1507]
### Feature motivation

i would like to know if anyone had packaged lunarvim for nixos...
how to handle the directories/paths and plugins..

**Comment by Vanderscycle** [comment]
I have been also trying to install lunar vim on nixos but I get snap on npm install "tree-sitter-cli" globally which nixos can't find. no issues npm -g neovim globally however.

**Comment by Dulanjala007** [comment]
@Vanderscycle i could install the "tree-sitter-cli" globally with npm (npm global package handling enabled, without nix store)
but the lvim tree-sitter parser compilation fails...

first by missing "gcc" once you install that system wide or for user or for neovim only (via home-manager neovim module's extraPackages option, I used this)..

then you get another error on tree-sitter-cli execution, caused by the linux tree-sitter executable not recognized as executable by nixos... that's the correct result, because of how different the runtime of nixos is... so we can't use the embedded tree-sitter executable in the tree-sitter-cli node_module... 

so we replace that with the one from the nixpkgs, with home-manger i did it like this.

first delete the existing 'tree-sitter' file at `tree_sitter_bin="<global_node_moduels_path>/lib/node_modules/tree-sitter-cli/"`
then added this to my home-manager config
`  home.file.${tree_sitter_bin}.source = "${pkgs.tree-sitter}/bin/tree-sitter";`
then tree-sitter-cli starts working correctly
and all the parser for languages installed without errors...

as for language lsp installs, all the ones from npm installed fine..
but lua language server did work since it also uses generic linux executable which doesn't work on nixos
so you can install 'sumneko-lua-language-server' from nixpkgs and update your lvim config to have 
`lvim.lang.lua.lsp.setup.cmd = { "lua-language-server" }
lvim.lang.rust.lsp.setup.cmd = { "rust-analyze" } 
`
same for rust-analyzer

then eveything works fine...

my home-manager module for neovim is this

```
{ pkgs, globalPkgDir, ... }:

let
  node_dir = builtins.replaceStrings [ "$HOME/" "~/" ] [ "" "" ] globalPkgDir;
  tree_sitter_bin = "${node_dir}/lib/node_modules/tree-sitter-cli/tree-sitter";
in
{

  home.file.${tree_sitter_bin}.source = "${pkgs.tree-sitter}/bin/tree-sitter";

  programs.neovim = {
    enable = true;
    withNodeJs = true;
    withPython3 = true;
    extraPackages = with pkgs; [ gcc rnix-lsp sumneko-lua-language-server ];
    package = pkgs.neovim-nightly;
    vimAlias = true;
  };


}
```

**Comment by Vanderscycle** [comment]
@Dulanjala007 Thank you so much for the detailed answer. I'm relatively new to nixos and I am both stumped and pleasantly surprised at times by nix way of doing Linux.
I'll try on my end when I have time and report back.

**Comment by V1RE** [comment]
I'm probably doing it all wrong, but here's my [attempt](https://github.com/V1RE/nixpkgs/blob/75198a323d6cdf86838755421c60cfea124ea3ad/pkgs/applications/editors/lunarvim/default.nix).

Would love some feedback/help!

**Comment by Dulanjala007** [comment]
@V1RE you're doing it the correct nixos way... i didn't, i made it work out side of nix store, since the lunarvim still changing i didn't want to everything to be pinned to a version yet..

but your way is the correct way..! Good Luck..

**Comment by morphykuffour** [comment]
Personally I think the NixOS store way of installing LunarVim will be a pain in the ass because of the development velocity of LunarVim. I installed neovim-unwrapped and simply placed my nvim config in `.config` with stow. Here's the link [neovim-unwrapped](https://search.nixos.org/packages?channel=22.05&show=neovim-unwrapped&from=0&size=50&sort=relevance&type=packages&query=neovim). 
Install the unwrapped version which is currently 0.7.0. You can then `rm -rf ~/.config/nvim` then stow your nvim config. I think this is the easiest way to setup lunarvim on nixos with low overhead.
```bash
nix-env -iA nixos.neovim-unwrapped
```

**Comment by tuxflo** [comment]
Not stale

**Comment by niksingh710** [comment]
Any updates?

**Comment by Redyf** [comment]
I've been looking for a way to make LunarVim work on NixOS for almost 2 weeks, but yesterday a friend of mine (Alpha.) told me about a way to make $HOME/.local/bin work on Nix by writing this line of code in your ~/.config/nixpkgs/home.nix (if you have <a href="https://github.com/nix-community/home-manager">Home-manager</a> installed): 

```
#Add support for ./local/bin
home.sessionPath = [
"$HOME/.local/bin"
];
```
After writing that in your home.nix file, do **home-manager switch** in your terminal to apply the changes and follow the instructions on <a href="https://www.lunarvim.org">LunarVim</a> Official website to install it in your system :)

**Comment by Redyf** [comment]
> Any updates?
https://github.com/LunarVim/LunarVim/issues/1507#issuecomment-1328247475

**Comment by tuxflo** [comment]
Not stale, just didn't found the time to try it...

**Comment by ProminentRetail** [comment]
This is being addressed by NixOS/nixpkgs#257063.

**Comment by ProminentRetail** [comment]
And it's been merged! :D

**Comment by tuxflo** [comment]
This is great! Thanks to all people involved in getting this done.
I think this issue could be closed then.
