### ISSUE TITLE
[Feature]: A modular config file

### ISSUE THREAD

**Issue by yassinebridi** [LunarVim/LunarVim#1508]
### Feature motivation

I used to make a config file for each feature: Keymaps, Plugins, Macros, etc..
as I add more config to the `config.lua`, it becomes quite overwhelming to edit.

### Describe the expected solution

The ability to modularize the config file, and source the other config files in the main `config.lua`

**Comment by abzcoding** [comment]
you can do that already
take a look at my config for example
https://github.com/abzcoding/lvim

**Comment by yassinebridi** [comment]
Thank you @abzcoding i have been trying to import directly from the current folder instead of a lua folder.

**Comment by abzcoding** [comment]
@yassinebridi 
btw i really suggest creating a `user` folder inside of that `lua` folder to avoid
namespace clash with other plugins and lunarvim itself

**Comment by yassinebridi** [comment]
Oh, you are righti will change that, many thanks.
