### ISSUE TITLE
[Feature]: Add support for prisma lsp using :LspInstall

### ISSUE THREAD

**Issue by yassinebridi** [LunarVim/LunarVim#1510]
### Feature motivation

nvim-lspconfig already support prisma lsp here:
https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#prismals

It would be cool to install Prisma LSP using nvim-lspconfig

**Comment by abzcoding** [comment]
we are using https://github.com/kabouzeid/nvim-lspinstall as our lsp installer, plz create the issue there
