### ISSUE TITLE
[Feature]: Appimage Prebuild package

### ISSUE THREAD

**Issue by Burnsedia** [LunarVim/LunarVim#1511]
### Feature motivation

I want a appimage that is prebuild with LunarVim, and is has arm and x64 support

### Describe the expected solution

prebuild arm and x64 appimage

**Comment by x86dev** [comment]
+1 here, would be cool to have!

**Comment by Burnsedia** [comment]
thanks guys,

I have lots of free time now, I am going to work on this until I get another job.
I am also going to work on my games/apps.

I use this LunarVim to my apps developments.

**Comment by tuxflo** [comment]
Hi @Burnsedia did you ever managed to build a lunarvim appimage (with the plugins)?
I need this too.

**Comment by Burnsedia** [comment]
No, work has been getting in the way, there is a way to pack a app image with configuration files but no dice so far

**Comment by tuxflo** [comment]
Nope, not stale

**Comment by LostNeophyte** [comment]
okay so no promises, it may be abandoned in the future

can you check if [this (lunarvim master)](https://mega.nz/file/eeoFERpA#g_QxruVufYUDYU66jBN27vrcEKzlkwrOQDRRGWQGUQQ) appimage works? if you don't have lunarvim already installed on your machine, you'll need to run :PackerSync on the first run. In the appimage everything (except updating lvim core) should work, this includes adding user plugins, removing core plugins and updating plugins. the appimage assumes that neovim is executable using nvim, so if you have a neovim appimage make sure you can execute it with bash -c "exec nvim"

**Comment by LostNeophyte** [comment]
can you check if [the appimage from here](https://github.com/LostNeophyte/LunarVim/releases) works? if you don't have lunarvim already installed on your machine, you'll need to run :PackerSync on the first run. In the appimage everything (except updating lvim core) should work, this includes adding user plugins, removing core plugins and updating plugins. this appimage includes lunarvim and neovim

**Comment by LostNeophyte** [comment]
[I think it's done](https://github.com/LunarVim/LunarVim-mono/releases/tag/nightly), please do report any issues you find :)

**Comment by Burnsedia** [comment]
Ok

**Comment by Burnsedia** [comment]
@LostNeophyte I am going to give Packaging as an AppImage a shot again.

**Comment by LostNeophyte** [comment]
I did it, it's in the lunarvim-mono repo

**Comment by Burnsedia** [comment]
@LostNeophyte Thanks; need help maintaining it?

**Comment by LostNeophyte** [comment]
https://github.com/LunarVim/LunarVim-mono/releases

**Comment by LumenYoung** [comment]
> https://github.com/LunarVim/LunarVim-mono/releases

Hi, @LostNeophyte, Thank you for the effort. Do you see any difficulty to have such mono appimage for arm64 architecture as well? It would be appreciated if we can have that on single board computer (like Raspberry Pi) as well.

**Comment by LostNeophyte** [comment]
> > https://github.com/LunarVim/LunarVim-mono/releases
> 
> Hi, @LostNeophyte, Thank you for the effort. Do you see any difficulty to have such mono appimage for arm64 architecture as well? It would be appreciated if we can have that on single board computer (like Raspberry Pi) as well.

if the normal lunarvim install works there then it should be easy to do

**Comment by LumenYoung** [comment]
> > > https://github.com/LunarVim/LunarVim-mono/releases
> > 
> > 
> > Hi, @LostNeophyte, Thank you for the effort. Do you see any difficulty to have such mono appimage for arm64 architecture as well? It would be appreciated if we can have that on single board computer (like Raspberry Pi) as well.
> 
> if the normal lunarvim install works there then it should be easy to do

As I can see from now, the neovim doesn't provide pre-built for arm64. Manual effort is needed for that.

**Comment by LostNeophyte** [comment]
in that case it will be harder, maybe i'll do that in the future

**Comment by LumenYoung** [comment]
> in that case it will be harder, maybe i'll do that in the future

Cool, I would like to help if you have time to list what is needed for it to work.

**Comment by LostNeophyte** [comment]
thanks, i'll get back to this issue in a month or so, I'm currently in the middle of merging the mono repo into the main one (and it looks like that might fail)
