### ISSUE TITLE
[Bug]: phpcbf not formatting

### ISSUE THREAD

**Issue by marwan38** [LunarVim/LunarVim#1514]
### Problem description

1. Create a php file with messy formatting
2. Format using `<leader>lf`
3. Nothing changes
4. Run command: `:! phpcbf %`
5. File is formatted correctly

I'm not sure if this is an upstream issue (null-ls itself) or not. I do know that it's activated because the statusbar does say `php, phpcbf`

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
it seems like if your code has linting issues, it doesn't format them, make sure to test it on a simple php file

**Comment by marwan38** [comment]
@abzcoding ironically, if the linter was on, the diagnostics would be complaining that its not formatted (indented) correctly. But, there is no linter.

Thing is, with null-ls, there's no diagnostics for php (yet), so how would it know? Also, calling the formatter cli command directly works just fine.

**Comment by abzcoding** [comment]
@marwan38 oh what i meant was to simply test it on a 3 line php file to see if it works at all or not, then we can proceed to the next step 😅

**Comment by abzcoding** [comment]
btw we support linters for php as well
<img width="786" alt="Screen Shot 2021-09-09 at 6 13 51 PM" src="https://user-images.githubusercontent.com/10992695/132697166-4d4d6f31-0a8b-4903-a1d2-9ebfab9852fd.png">

**Comment by marwan38** [comment]
@abzcoding I tested it on a minimal file

1. Create test.php
2. Make the most simple class possible
3. Format
4. No work
5. Format using direct command `:! phpcbf %`
6. Works

And yeah, I've seen those linters working for php. We just don't use them at work and use `phpcs`. I've contacted null-ls directly and they were kind enough to offer to put up the phpcs linter as well :).

**Comment by marwan38** [comment]
php-cs-fixer is not working either, I tried it with a barebones config, works just fine.

**Comment by marwan38** [comment]
This is an upstream issue that is caused by an unhandled edge case. Closing.

https://github.com/jose-elias-alvarez/null-ls.nvim/pull/185#issuecomment-917629535
