### ISSUE TITLE
[Feature]:  Easymotion plugin

### ISSUE THREAD

**Issue by carloseguevara** [LunarVim/LunarVim#1517]
### Problem description

The easymotion is a very popular plugin to improve the process to move across the current file. I try to add this plugin but I don't be able to map the easymotion commands:
map  / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)

Could you help to understand how map this types of plugins? Others plugins still use this type of map, and I don't understand how to adapt to lunarvim.

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

v0.6.0-dev+8-g75f758b99

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
It would help to know what you've tried so far.  

It looks like easymotion accepts leader bindings.  To set leader bindings use whichkey.  https://www.lunarvim.org/configuration/02-keybindings.html#whichkey-bindings

**Comment by carloseguevara** [comment]
Thanks! That's work, only add: 
lvim.builtin.which_key.mappings["n"] = {
  "<Plug>(easymotion-overwin-f)", "Projects"
}
