### ISSUE TITLE
[Bug]: Persistence plugin no longer works.

### ISSUE THREAD

**Issue by kingedward35** [LunarVim/LunarVim#1519]
### Problem description

After updating to the newest rolling release, the [persistence](https://github.com/folke/persistence.nvim) plugin no longer works. If you quit LunarVim and then apply the `<cmd>lua require('persistence').load()<cr>` command, the previous session does not start up.

### LunarVim version

Rolling

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
i'm using the same plugin with lunarvim and it works fine for me,
can you try disabling the dashboard session management?
add this to your `~/.config/lvim/config.lua`
```lua
vim.g.dashboard_enable_session = 0
```

**Comment by kingedward35** [comment]
That worked. Thanks.
