### ISSUE TITLE
[Feature]: Roll back nvim-tree commits

### ISSUE THREAD

**Issue by BlueDruddigon** [LunarVim/LunarVim#1521]
### Feature motivation

At previous version of nvim-tree.lua, i can close unused buffer to open file.

### Describe the expected solution

Can you roll back nvim-tree.lua version to this commit: "c75e4a63b73f223a80835ab3b75f602dc3e60e66"
This will fix the config of nvim_tree_respect_buf_cwd for my convenient used :(
Or add a property like that for nvimtree.lua.
Thanks.

**Comment by rebuilt** [comment]
Go to the nvim-tree.lua folder and run 
```bash
git pull --unshallow
git checkout c75e4a63b73f223a80835ab3b75f602dc3e60e66
```

That will put you on that commit immediately.   

That commit you're asking for is three weeks old and sets nvim-tree to a pre 1.0 release.  I'm not sure we want to do that.

**Comment by rebuilt** [comment]
Running a `:PackerSync` will update files in that folder so you might want to test and see if making that folder read-only prevents packer from updating it.  I'm not sure.  I haven't tested that out.

**Comment by abzcoding** [comment]
do the thing that rebuilt said
