### ISSUE TITLE
How to disable nvim-cmp

### ISSUE THREAD

**Issue by BlueDruddigon** [LunarVim/LunarVim#1522]
I cannot find a way to disable nvim-cmp, which is mentioned in https://github.com/hrsh7th/nvim-cmp#i-dislike-auto-completion. So, how do I disable it?

**Comment by BlueDruddigon** [comment]
> Have you tried
> 
> ```lua
> local cmp = require'cmp'
> cmp.setup {
>   completion = {
>     autocomplete = false,
>   },
> }
> ```

How do I configure in my config.lua? I'm newbie sorry

**Comment by rebuilt** [comment]
You might want to consult the documentation.   https://www.lunarvim.org/configuration/

**Comment by BlueDruddigon** [comment]
> You might want to consult the documentation. https://www.lunarvim.org/configuration/

Oh, I'm sorry :v: I should question this: How I disable the nvim-cmp for only a python file?

**Comment by BlueDruddigon** [comment]
> You might want to consult the documentation. https://www.lunarvim.org/configuration/

Oh, I'm sorry :v: I should question this: How I disable the nvim-cmp for only a python file?

**Comment by rebuilt** [comment]
I haven't tested this code but it should be something like
```lua
local filetype = vim.bo.filetype

if (filetype == "python") then
local cmp = require'cmp'
cmp.setup {
  completion = {
    autocomplete = false,
  },
}
end
```

The first file you open will set the autocomplete option.  For more complex behavior, where it changes each time you open a new file, you'll need to create an autocommand on the FILETYPE event that runs a function you create.   

Read about https://www.lunarvim.org/configuration/05-autocommands.html

**Comment by rebuilt** [comment]
Example autocommands here:  https://github.com/LunarVim/LunarVim/blob/rolling/lua/core/autocmds.lua

**Comment by BlueDruddigon** [comment]
> I haven't tested this code but it should be something like
> 
> ```lua
> local filetype = vim.bo.filetype
> 
> if (filetype == "python") then
> local cmp = require'cmp'
> cmp.setup {
>   completion = {
>     autocomplete = false,
>   },
> }
> end
> ```
> 
> The first file you open will set the autocomplete option. For more complex behavior, where it changes each time you open a new file, you'll need to create an auto command on the FILETYPE event that runs a function you create.
> 
> Read about https://www.lunarvim.org/configuration/05-autocommands.html

![image](https://user-images.githubusercontent.com/39997524/132837353-db794a29-1cf0-490f-bb09-a6a43dce43d2.png)

Cannot use that tho!

**Comment by BlueDruddigon** [comment]
> Example autocommands here: https://github.com/LunarVim/LunarVim/blob/rolling/lua/core/autocmds.lua

![image](https://user-images.githubusercontent.com/39997524/132837808-9ed186b2-0db1-4133-af8c-8dcc73ab4494.png)
my other try! But it doesn't work

**Comment by rebuilt** [comment]
~/.config/lvim/lua/user/autocommands.lua

```lua
local M = {}

M.setup = function()
	lvim.autocommands.custom_groups = {
		{ "Filetype", "*", "lua require('user.autocommands').disable_python_autocomplete()" },
	}
end

M.disable_python_autocomplete = function()
	local filetype = vim.bo.filetype

	if filetype == "python" then
		require("cmp").setup({ completion = { autocomplete = false } })
	end
end

return M

```

config.lua
```lua
require("user.autocommands").setup()

```

**Comment by BlueDruddigon** [comment]
> ```lua
> local M = {}
> 
> M.setup = function()
> 	lvim.autocommands.custom_groups = {
> 		{ "Filetype", "*", "lua require('user.autocommands').toggle_autocomplete()" },
> 	}
> end
> 
> M.toggle_autocomplete = function()
> 	local filetype = vim.bo.filetype
> 
> 	local enable_autocomplete = true
> 	if filetype == "python" then
> 		enable_autocomplete = false
> 	end
> 
> 	require("cmp").setup({ completion = { autocomplete = enable_autocomplete } })
> end
> 
> 
> return M
> ```

Can't help -.-

**Comment by rebuilt** [comment]
No.  Don't change anything in the `~/.local/share/lunarvim/lvim` folder.  

If you've already modified files there reset your changes `git reset --hard HEAD`

Then read about how to configure lunarvim.  https://www.lunarvim.org/configuration/  You're really not going to make progress until you figure out what file to edit.  

This issue isn't really an issue with lunarvim so I'm closing.

**Comment by rebuilt** [comment]
Here is an example config to follow.   https://github.com/abzcoding/lvim

**Comment by BlueDruddigon** [comment]
```
This issue isn't really an issue with lunarvim so I'm closing.
```

So you mean that this issue belongs to nvim-cmp plugin ?

**Comment by rebuilt** [comment]
Writing custom code for each user on demand is out of scope.  

But I didn't want to close without being completely unhelpful.   So I've linked to the relevant documentation.  I've provided example code.  I linked an example repository that you can use to learn how to configure lunarvim.  

I'm not sure how to help you further.  Your responses have been  'Cannot use that tho!` and `Can't help -.-`.  What plan of action can I possibly form from those responses?  

You can try on the discord channel to see if someone will help you write the code you want.

**Comment by mayankdutta** [comment]
since we are on `cmp`, could u help me how to add custom snippets with `cmp`, earlier I just to add snippets in the file after typing `:VsnipOpen`

**Comment by BlueDruddigon** [comment]
> Writing custom code for each user on demand is out of scope.
> 
> But I didn't want to close without being completely unhelpful. So I've linked to the relevant documentation. I've provided example code. I linked an example repository that you can use to learn how to configure lunarvim.
> 
> I'm not sure how to help you further. Your responses have been `Cannot use that tho!` and `Can't help -.-`. What plan of action can I possibly form from those responses?
> 
> You can try on the discord channel to see if someone will help you write the code you want.

Sorry about my useless responses. All things that i want to describe with you is how to disable ``nvim-cmp`` for python rather than leave it as default. That's so unconvenient for me because i'm using a autocomplete call Kite engine, it's an AI based autocomplete tool. Leave the plugin setup by default make kite complete menu doesn't show up. The other way is use kite-lsp for neovim but as the information mentioned here https://github.com/kiteco/vim-plugin/blob/master/LSP.md#kite-lsp, the kite-lsp doesn't well-supported via LSP. My personal problem is i don't know how to config the `nvim-cmp` plugin as my wishing. About my poor English, i don't know ways to describe it for you. 

As i knows, the way you've done above is disable by filetype. But i don't know why it's doesn't work for me! I'm trying to learn more about lua language and learn how to customize by myself.

I'm very appreciate your helps.

**Comment by rebuilt** [comment]
Maybe the filetype detection is different on your machine.  

You can add some print statements after `local filetype = vim.bo.filetype` to see the value of `filetype`.  Maybe it's not exactly 'python'  
`print(filetype)`

Also run `set filetype?`  To see what filetype is detected.

**Comment by BlueDruddigon** [comment]
> Maybe the filetype detection is different on your machine.
> 
> You can add some print statements after `local filetype = vim.bo.filetype` to see the value of `filetype`. Maybe it's not exactly 'python'
> `print(filetype)`
> 
> Also run `:set filetype?` To see what filetype is detected.

i'm using `:set filetype?` and this is result
![image](https://user-images.githubusercontent.com/39997524/132919026-612860ae-b70f-4fb1-a373-f27268c053c7.png)

![image](https://user-images.githubusercontent.com/39997524/132919083-970f1104-a454-4044-95db-b02e393c65e1.png)

The filetype exactly python

**Comment by rebuilt** [comment]
When you added the print statement after `local filetype = vim.bo.filetype`, was that also `python`?

**Comment by BlueDruddigon** [comment]
> When you added the print statement after `local filetype = vim.bo.filetype`, was that also `python`?

I tried but it doesn't print anything.

I've found this from configuration on `lunarvim.org`
https://tech.saigonist.com/b/code/list-all-vim-script-events.html

And it's maybe `FileType` but `Filetype`?



> This code goes in this file:
> ~/.config/lvim/lua/user/autocommands.lua
> 
> ```lua
> local M = {}
> 
> M.setup = function()
> 	lvim.autocommands.custom_groups = {
> 		{ "Filetype", "*", "lua require('user.autocommands').toggle_autocomplete()" },
> 	}
> end
> 
> M.toggle_autocomplete = function()
> 	local filetype = vim.bo.filetype
> 
> 	local enable_autocomplete = true
> 	if filetype == "python" then
> 		enable_autocomplete = false
> 	end
> 
> 	require("cmp").setup({ completion = { autocomplete = enable_autocomplete } })
> end
> 
> 
> return M
> ```
> 
> This code goes in your config.lua
> 
> ```lua
> require("user.autocommands").setup()
> ```

Your code here you calls `Filetype` and that's maybe the reason why the `print` statement doesn't show up anything ?

**Comment by BlueDruddigon** [comment]
i've created structure like `~/.config/lvim/lua/user/autocommands.lua` like you mentioned. And i added this to config.lua file `require('user.autocommands').setup()`

Here is the picture

![image](https://user-images.githubusercontent.com/39997524/132920383-463374dc-a18d-44ed-8b62-2e8acc92cee0.png)

I don't know why this doesn't work. And the result in a python file

![image](https://user-images.githubusercontent.com/39997524/132920456-78e96f35-e313-46e8-9c83-9c3ecb882d1a.png)

**Comment by rebuilt** [comment]
> Is the setup.buffer of nvim-tree is equals to setup function you've edited above ?

Looks like you can apply a setting to a single buffer by using `setup.buffer`.   That's interesting.  I didn't know that.  Without `buffer` it will apply to all files you open.

**Comment by rebuilt** [comment]
```lua
	lvim.autocommands.custom_groups = {
		{ "Filetype", "python", "lua require('cmp').setup.buffer({completion = {autocomplete = false}})" },
	}
```

**Comment by BlueDruddigon** [comment]
> ```lua
> 	lvim.autocommands.custom_groups = {
> 		{ "Filetype", "python", "lua require('cmp').setup.buffer({completion = {autocomplete = false}})" },
> 	}
> ```

I've tried this code. But it acts abnormally. The buffer reloads every single character i've entered so the autocomplete menu didn't show!

maybe it's a bug ?
