### ISSUE TITLE
[Bug]: Settings non-deterministically applied

### ISSUE THREAD

**Issue by LandonSchropp** [LunarVim/LunarVim#1525]
### Problem description

This is a really weird bug, and I'm not quite sure how to reproduce it. Some of my settings seem to be non-deterministically applied. Here's a good example:

https://user-images.githubusercontent.com/361591/132933007-13a72922-e908-43a8-940a-f994fa123e2b.mp4

In this example, the numbers randomly appear on the side. It's hard for me to pin down, but I swear this happens with other settings as well, especially with key mappings. For example, I'm using the built-in tabline instead of bufferline, so I remapped `H` and `L` to the following:

``` lua
lvim.keys.normal_mode["H"] = "gT"
lvim.keys.normal_mode["L"] = "gt"
```

Sometimes when I run `lvim`, the keymaps work fine. Other times, one of them will work and the other will give an error like this (indicating the map isn't applied):

```
E492: Not an editor command: BufferNext
```

I'm not quite sure what's needed to debug this, so please let me know if there's anything I can provide.

### LunarVim version

Latest (as of today)

### Neovim version (>= 0.5)

v0.5.0

### Relevant log output

```shell
N/A
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by LandonSchropp** [comment]
This is happening with other lvim settings besides these two as well.

**Comment by rebuilt** [comment]
Can you try setting the keys like this:

```lua
lvim.keys.normal_mode["<S-h>"] = "gT"
lvim.keys.normal_mode["<S-l>"] = "gt"
```

How are you setting line numbers?  Or are you using the defaults?

**Comment by LandonSchropp** [comment]
The tab keybindings suggestion you made seems to have fixed things. Any thoughts on why that would make a difference? It would expect my previous settings to either work or not work, rather than working 50% of the time.

Another setting that seems to occasionally not work when restarting LunarVim is this one:

``` lua
lvim.builtin.telescope.on_config_done = function()
  lvim.builtin.telescope.defaults.mappings.i["<cr>"] = actions.file_tab
end
```

Yet another issue with key bindings seems to be related to `vim-surround`. I have this plugin installed via `lvim.plugins`.

``` lua
lvim.plugins = {
  ...
  { "tpope/vim-surround" },
  ...
}
```

But none of the key bindings from the plugin are working.
---

In terms of settings line numbers, I normally do this:

``` lua
auto_command("InsertEnter * :set number norelativenumber")
auto_command("InsertLeave * :set relativenumber")
```

However, I thought this might be the issue, so I commented out these lines, and I'm still running into the same issue.

If it's helpful, all of my LunarVim config is contained in my [dotfiles](https://github.com/LandonSchropp/dotfiles/tree/lunarvim/config/lvim).

**Comment by rebuilt** [comment]
I have no idea why the keybinding only works half the time.  

You'll need to increase the timeoutlen value for the surround plugin to work correctly.  LunarVim sets a very low timeoutlen value for perceived responsiveness in whichkey.  
I don't ever want to see whichkey unless I forget my keybindings so I've set
`vim.opt.timeoutlen = 1000`


Try changing your autocommands to this format:
https://www.lunarvim.org/configuration/05-autocommands.html

**Comment by rebuilt** [comment]
You might need to require `actions` for this to work correctly.  It's defined in the `config` function but the callback is called in the `setup` function.  At that point `actions` does not exist

```lua
lvim.builtin.telescope.on_config_done = function()
  local actions = require("telescope.actions")
  lvim.builtin.telescope.defaults.mappings.i["<cr>"] = actions.file_tab
end
```

**Comment by LandonSchropp** [comment]
Ah, setting `timeoutlen` to a longer interval makes perfect sense. That fixed my issue with vim-surround.

I left out the line above, but I did require actions at the top of the file:

```
local actions = require("telescope.actions")
```

That key binding does work, but like many of the other settings, it only seems to apply about 50% percent of the time.

Is it possible there's a race condition somewhere in the LunarVim codebase that could be causing these issues? Is there anything asynchronous happening on startup with config load? Any startup optimizations I could disable that might be causing issues?

The only other thing I can think of is that my config is split up into multiple files. Here's what my `config.lua` file looks like:

``` lua
require("user.settings")
require("user.keys")
require("user.plugins")
require("user.theme")
require("user.syntax")
require("user.language")
require("user.which_key")
```

I wouldn't think that would affect anything, but I thought I'd mention it in case I'm wrong.

Thanks for your patience with all of this. I appreciate all the help.

**Comment by rebuilt** [comment]
If there is a race condition, it's unknown to us.  

Can you add this to your config to rule out `impatient.nvim` as the source of the problem.  This destroys the cache so lunarvim must load from disk and not a cached instance.  

```lua
_G.PLENARY_DEBUG = true -- Plenary destroys cache with this undocumented flag set to true by default
```

**Comment by rag-hav** [comment]
Getting something similar too. Auto pairs is working sporadically.

```lvim.builtin.autopairs.active = true```

I tried adding this to my config too.

**Comment by rebuilt** [comment]
> Getting something similar too. Auto pairs is working sporadically.
> 
> `lvim.builtin.autopairs.active = true`
> 
> I tried adding this to my config too.

Make sure you manually delete the packer_compiled folder and then `:PackerSync` again
`rm -rf ~/.config/.lvim/plugin`

If that doesn't work remove the `after` attribute from the autopairs declaration in `~/.local/share/lunarvim/lvim/lua/plugins.lua`.  And then run `:PackerSync`

``` lua
  {
    "windwp/nvim-autopairs",
    -- event = "InsertEnter",
    -- after = "nvim-cmp",
    config = function()
      require("core.autopairs").setup()
    end,
    disable = not lvim.builtin.autopairs.active,
  },

```

**Comment by LandonSchropp** [comment]
@rebuilt I tried setting that flag, but I can still repro my line numbers problem, so I'm assuming that isn't it.

**Comment by LandonSchropp** [comment]
I also tried commenting out the `setup` function in `impatient.lua`, but that doesn't seem to have helped either.

**Comment by LandonSchropp** [comment]
In order to try and pin down some of my issues, I've been selectively commenting out parts of my config. The line numbers issue seems to be caused by this section:

``` lua
-- Configure the status line.
lvim.builtin.lualine.options.icons_enabled = true
lvim.builtin.lualine.options.section_separators = { "", "" }
lvim.builtin.lualine.options.component_separators = { "", "" }

local function location()
  return vim.fn.line(".") .. "/" .. vim.fn.line("$")
end

lvim.builtin.lualine.sections.lualine_a = { "mode" }
lvim.builtin.lualine.sections.lualine_b = { components.branch }
lvim.builtin.lualine.sections.lualine_c = { components.filename }
lvim.builtin.lualine.sections.lualine_x = {
  components.diagnostics,
  components.diff,
  separator = " ",
}
lvim.builtin.lualine.sections.lualine_y = { components.filetype }
lvim.builtin.lualine.sections.lualine_z = { location }
```

Any idea why modifying lualine would cause this?

I still haven't pinned down the root cause of the keyboard shortcuts issue, but maybe that's a separate problem.

**Comment by LandonSchropp** [comment]
I've finally identified the root cause of my keymapping woes! I opened up #1548, as well as #1549 for the Lualine issue. Thanks!
