### ISSUE TITLE
[Feature]: Install without root permission

### ISSUE THREAD

**Issue by Moelf** [LunarVim/LunarVim#1526]
### Feature motivation

sometimes on HPC set-up users have to install `neovim` by downloading binary themselves, in this case, the LunarVim installation script would fail since it couldn't find `neovim` from package manager.

**Comment by kylo252** [comment]
The installer does not require `sudo`. Even the CI workflow doesn't use `sudo` because the `nvim` binary is downloaded manually into `~/.local/bin`.

If you're having trouble with the installer, then you need to check that `nvim` is executable and found on your `$PATH`.
