### ISSUE TITLE
[Bug]: Installing node modules with npm.. Failes

### ISSUE THREAD

**Issue by John15321** [LunarVim/LunarVim#1528]
### Problem description

When installing the rolling release ( I haven't tried for the stable).
While checking the npm dependencies this error occurs (I checked on Ubuntu, macOS, and Manjaro, all the same).
The error is for this command:

```bash
LVBRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)
```

The solution I recommend is to either add a section in the documentation that describes how to deal with that or maybe write down some prerequisites or simply fix it in the installer. From what I have heard its due to some npm permissions (I'm not very familiar with node javascript etc so idk)

### LunarVim version

none

### Neovim version (>= 0.5)

0.5.0

### Relevant log output

```shell
88\                                                   88\               
      88 |                                                  \__|              
      88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\  
      88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\ 
      88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
      88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
      88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
      \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|

--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install lunarvim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
Installing node modules with npm..
npm notice 
npm notice New minor version of npm available! 7.21.1 -> 7.23.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.23.0
npm notice Run npm install -g npm@7.23.0 to update!
npm notice 
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/lib/node_modules/neovim
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/neovim'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/neovim'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/lib/node_modules/neovim'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/john/.npm/_logs/2021-09-11T17_07_43_884Z-debug.log
```

### Screenshots

![image](https://user-images.githubusercontent.com/56229312/132955757-84e3b333-f475-476d-be35-7cb26550139d.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by rebuilt** [comment]
I added the link for resolving eaccess errors to the lunarvim documentation
https://www.lunarvim.org/01-installing.html#troubleshooting-installation-problems

**Comment by John15321** [comment]
> I added the link for resolving eaccess errors to the lunarvim documentation
> https://www.lunarvim.org/01-installing.html#troubleshooting-installation-problems

To be honest I would be more verbose about error descriptions. `EACCESS` error means nothing to most people, especially if the error output u got I like 30 lines long and you are not familiar with node. Additionally, I would suggest some sort of a prerequisites paragraph.
I can do that myself, I will post an issue on the docs and try to do it myself and do a pull rqst from a fork so if you could take a look in a while
