### ISSUE TITLE
[Feature]: Support Terraform/HCL

### ISSUE THREAD

**Issue by Jberlinsky** [LunarVim/LunarVim#1530]
### Feature motivation

**As an** infrastructure engineer and vim user
**I want** LunarVim to support Terraform configuration in HCL (HCL is the language -- the two are often interchanged)
**So that** I can use LunarVim for day-to-day engineering work

### Additional context

LunarVim's [Language Overview](https://www.lunarvim.org/languages/) states that if `lspconfig`, `null-ls` and `treesitter` all have support for a language, an Issue should be filed. Terraform/HCL meets these criterion as follows:

- **`lspconfig`**: https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#terraformls
- **`null-ls`**: https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#terraform_fmt
- **`treesitter`**: https://github.com/MichaHoffmann/tree-sitter-hcl

**Comment by Jberlinsky** [comment]
It appears that support is present when the following configuration is given:

```
lvim.lang.terraform.formatters = { { exe = 'terraform_fmt' } }
```

It might be good to document this.

**Comment by rebuilt** [comment]
@kylo252 The suggestion from `:LvimInfo` lists the exe as just `terraform`

![terraform](https://user-images.githubusercontent.com/16025007/132978348-12be6ef5-63da-4de2-a674-4d53421fffb6.png)

**Comment by kylo252** [comment]
> @kylo252 The suggestion from `:LvimInfo` lists the exe as just `terraform`

This value is managed internally by `null_ls` https://github.com/jose-elias-alvarez/null-ls.nvim/blob/da8bb757c630b96fd26030df56fd3a070fbf16a1/lua/null-ls/builtins/formatting.lua#L585-L597

So if the the command name is wrong, then I suggest opening a ticket there as well, @Jberlinsky.

**Comment by clementnuss** [comment]
@Jberlinsky thanks for reporting this issue, I'm in the exact same position :)
I wondered whether you found a way to install [MichaHoffman's tree-sitter syntax ](https://github.com/MichaHoffmann/tree-sitter-hcl)? I could find a way to install non-supported grammars

**Comment by clementnuss** [comment]
> @Jberlinsky thanks for reporting this issue, I'm in the exact same position :) I wondered whether you found a way to install [MichaHoffman's tree-sitter syntax ](https://github.com/MichaHoffmann/tree-sitter-hcl)? I could find a way to install non-supported grammars

actually it's already available and can simply be installed with: `TSInstall hcl` (the tree-sitter is named hcl)
if you want it to be active for `.tf` files as well, just add this to your `config.lua`:
```
parser_configs.hcl = {
  filetype = "hcl", "terraform",
}
```
and enjoy TS and syntax highlighting :)

**Comment by Uzaaft** [comment]
Writing a PR to lunarvim.org 
Sorry about the dumb question, but should this be under hcl or terraform in the languages sector? @rebuilt  @kylo252

**Comment by Uzaaft** [comment]
![image](https://user-images.githubusercontent.com/48220549/145103288-6b68af6c-a9bb-4b1c-b9c2-2744bd797caf.png)
WIP.
@Jberlinsky  @clementnuss  Anything more you guys think a Terraform user would need?
I might have forgot something in my eagerness.

**Comment by Uzaaft** [comment]
Draft PR:
https://github.com/LunarVim/lunarvim.org/pull/148

**Comment by clementnuss** [comment]
Thanks for the prompt PR!
I would change 2 things: for the language name I would put: **HCL (Terraform)**
and for the `parser_configs` variable, I had put it in my local config scope as it was not there by default. maybe there is another way to do it but I did:
```lua
local parser_configs = require("nvim-treesitter.parsers").get_parser_configs()
parser_configs.hcl = { ...}
```

**Comment by Uzaaft** [comment]
![image](https://user-images.githubusercontent.com/48220549/145173245-a11419fb-ba81-475c-b2ed-7803f2b1af54.png)
@clementnuss Anything else?

**Comment by Uzaaft** [comment]
Sorry about that ghost text in the screenshot. Running ML on my computer, so the rendering is glitchy in Arch. xD

**Comment by kylo252** [comment]
Do we need to add anything regarding filetype detection? I tried opening a `test.hcl` and the lsp-installer didn't detect a matching server out-of-the-box.

**Comment by Uzaaft** [comment]
@kylo252 It detects a matching server for `test.tf`
Which kind of makes sense. The Terraform lsp would only detect Terraform files, no?

**Comment by clementnuss** [comment]
not sure regarding `.hcl` files with `terraform-lsp`, but for the Treesitter config it's fine on my side

**Comment by Uzaaft** [comment]
I think adding lsp settings for .hcl files would be needed for this to be merged, considering that the section is all about hcl. 
@kylo252  You are the guru here. How do I add filetype detection? xD

**Comment by kylo252** [comment]
I tried forcing `terraform-ls` to attach to `*.hcl` files by modifying the setup opts, but this doesn't seem supported just yet :sweat_smile: 

![image](https://user-images.githubusercontent.com/59826753/145183846-4af8de24-af9a-4200-902f-ce12e9f2e572.png)

---

However, I did find some relevant issues that should be considered:

- add more filetypes: https://github.com/neovim/nvim-lspconfig/pull/1328
> Neither Vim nor Neovim supports Terraform out of the box. The tf filetype is completely unrelated (see TinyFugue).

- terraform-ls doesn't work: https://github.com/neovim/nvim-lspconfig/issues/380

I have no experience whatsoever with terraform, so I can't really say if there's anything more to be done or not. Maybe @ChristianChiarulli has some answers.

**Comment by Uzaaft** [comment]
Terraform LSP worked for me with a `test.tf` file and the following code: 
```Terraform
resource "null_resource" "void" {
  provisioner "local-exec" {
    command = "echo Hello World > success.txt"
  }
}

bogus should upset LSP...
```
It reports the following: 
```
HCL: Invalid block definition: Either a quoted string block label or an opening brance ("{") is expected here.
```
Although I have no experience with terraform either. Nor do I have any spesific terraform plugins. 
`:set filetype` returns `filetype=terraform`

**Comment by Uzaaft** [comment]
@kylo252  Seems like Chris can't be reached.
Should I just go ahead and add a note that HCL support is a WIP, and that the current config works on terraform files?

**Comment by ChristianChiarulli** [comment]
I remember some controversy with the filetypes for this, not sure I remember where tho...

**Comment by ChristianChiarulli** [comment]
https://github.com/neovim/nvim-lspconfig/pull/1008

**Comment by ChristianChiarulli** [comment]
All of the terraform I write usually uses the `.tf` extension

**Comment by kylo252** [comment]
@ChristianChiarulli, I guess you can just copy (any) config you have here, and we'll call it WIP?

**Comment by Uzaaft** [comment]
I second @kylo252 idea.
I think it also would be wise to remove the HCL part of the title, considering the issue Chris linked to.

**Comment by kylo252** [comment]
Fixed for now with https://github.com/LunarVim/lunarvim.org/pull/148

Please let me know if there's anything else that can be added.
