### ISSUE TITLE
[Bug]: Error while calling lua chunk

### ISSUE THREAD

**Issue by devrrior** [LunarVim/LunarVim#1533]
### Problem description

Steps to produce the behavior:
1. Try to install install lunarvim rolling version
2. Fail, uninstall
3. Try to install again lunarvim but this time stable version
4. Fail again

### LunarVim version

Rolling

### Neovim version (>= 0.5)

0.5.0

### Relevant log output

```shell
Cloning LunarVim configuration
Cloning into '/Users/fernando/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 201, done.
remote: Counting objects: 100% (201/201), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 201 (delta 2), reused 136 (delta 0), pack-reused 0
Receiving objects: 100% (201/201), 981.55 KiB | 2.45 MiB/s, done.
Resolving deltas: 100% (2/2), done.
Installing LunarVim shim
Preparing Packer setup
Error detected while processing /Users/fernando/.config/lvim/plugin/packer_compiled.lua:
E5113: Error while calling lua chunk: /Users/fernando/.config/lvim/plugin/packer_compiled.lua:341: Vim(echomsg):E121: Undefined variable: packPress ENTER or type command to continue
```

### Screenshots

![image](https://user-images.githubusercontent.com/69869135/132992482-75fafb38-678d-461b-8185-5be7120d3175.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Remove the packer_compiled folder and run the installer again

`rm -rf ~/.config/lvim/plugin`

**Comment by devrrior** [comment]
Yes, it works., thanks I had uninstalled lvim, I used these commands:
![image](https://user-images.githubusercontent.com/69869135/132996052-521aa9ed-aa99-4e1a-80b2-b440ab63227a.png)

So I don't know if you should add this command in the documentation for uninstalling lvim.

**Comment by rebuilt** [comment]
Added the suggested step to lunarvim.org
