### ISSUE TITLE
[Bug]: How do I tell null-ls to start on .scss files

### ISSUE THREAD

**Issue by afridley** [LunarVim/LunarVim#1536]
### Problem description

null-ls does not load on scss files even if I have added prettier to the css lang with

```lua
lvim.lang.css.formatters = {
  {
    exe = "prettier", -- can be prettierd eslint, or eslint_d as well
    args = {},
  },
}
```

If I open a css file it will activate null-ls and I can then get prettier to work in the scss files. But that can be a pain for projects with scss modules

The weird thing is that null-ls lists scss as a lang in the list once it is activated. but doesnt actually activate on that filetype. 
```
Client: null-ls (id: 2 pid: 5001)
  	root:      ...
  	filetypes: javascript, javascriptreact, typescript, typescriptreact, vue, svelte, css, scss, html, json, yaml, markdown
  	cmd:       nvim
  	autostart: True
```

null-ls should activate when a scss file is opened

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

latest rolling 9/13/2021

### Neovim version (>= 0.5)

0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by vuki656** [comment]
You should be able to pass 
`filetypes = { "javascript", "javascriptreact", "typescript", "typescriptreact", "vue", "svelte", "css", "scss", "html", "json", "yaml", "markdown" }` below the `exe`.

You just need to add `scss` to the list.

**Comment by afridley** [comment]
@vuki656 The thing is that the scss filetype is already being assigned to null-ls. null-ls still wont start on scss even though its in the filetypes. So whether I add it explicitly or not LspInfo shows scss as a filetype.

Thats why I thought it was weird.

Im wondering if it has to do with https://github.com/LunarVim/LunarVim/blob/rolling/lua/lsp/null-ls/formatters.lua#L70
@Tastyep

**Comment by vuki656** [comment]
Oh, interesting.

The only other thing I can recommend is to try and enable [debug mode](https://github.com/jose-elias-alvarez/null-ls.nvim#how-to-enable-and-use-debug-mode) and see if it spits out any errors.

**Comment by afridley** [comment]
I had some time to dig into it.

The problem stems from this line https://github.com/LunarVim/LunarVim/blob/bb130d669b60d0fd4d1a8867387f180d994968c9/lua/lsp/null-ls/linters.lua#L65-L72
```
function M.setup(filetype, options)
  if not lvim.lang[filetype] or (linters_by_ft[filetype] and not options.force_reload) then
    return
  end


  linters_by_ft[filetype] = M.list_configured(lvim.lang[filetype].linters)
  null_ls.register { sources = linters_by_ft[filetype].supported }
end
```

Since scss is not listed in the file that command references
https://github.com/LunarVim/LunarVim/blob/rolling/lua/config/defaults.lua

null-ls will not start.
adding scss with the same settings as css 
```
  scss = {
    formatters = {
      -- {
      --   exe = "prettier",
      --   args = {},
      -- },
      -- {
      --   exe = "prettierd",
      --   args = {},
      -- },
    },
    linters = {},
    lsp = {
      provider = "cssls",
      setup = {
        cmd = {
          "node",
          DATA_PATH .. "/lspinstall/css/vscode-css/css-language-features/server/dist/node/cssServerMain.js",
          "--stdio",
        },
      },
    },
  },
```
Allows null-ls to run but an error is thrown and although LspInfo and NullLsInfo show that prettier is loaded and null-ls autoformat does not work

Im wondering why we dont cascade
So if scss does not exist but cssls has scss as a filetype then null-ls would receive it and start.

Though im still not sure why just plain adding scss with the same settings doesn't work since that looks like whats being done for less

**Comment by kylo252** [comment]
> I had some time to dig into it.
> 
> The problem stems from this line
> 
> https://github.com/LunarVim/LunarVim/blob/bb130d669b60d0fd4d1a8867387f180d994968c9/lua/lsp/null-ls/linters.lua#L65-L72
> 
> Since scss is not listed in the file that command references
> [https://github.com/LunarVim/LunarVim/blob/rolling/lua/config/defaults.lua](https://github.com/LunarVim/LunarVim/blob/rolling/lua/config/defaults.lua?rgh-link-date=2021-09-13T15%3A23%3A47Z)

That's why there's a symlink to from `ftplugin/scss.lua` to `ftplugin/css.lua`. It was done assuming they're using the same tools.

> Im wondering why we dont cascade
> So if scss does not exist but cssls has scss as a filetype then null-ls would receive it and start.
> 
> Though im still not sure why just plain adding scss with the same settings doesn't work since that looks like whats being done for less

I need to clarify that `null-ls` actually need `cssls` to start. This is mainly done to be able to turn-off auto-formatting in the language-server if a formatter was specified.

**Comment by afridley** [comment]
@kylo252 
Is the symlink supposed to prevent the need to add
```
scss = {
    formatters = {
       {
         exe = "prettier",
         args = {},
       },
      -- {
      --   exe = "prettierd",
      --   args = {},
      -- },
    },
    linters = {},
    lsp = {
      provider = "cssls",
      setup = {
        cmd = {
          "node",
          DATA_PATH .. "/lspinstall/css/vscode-css/css-language-features/server/dist/node/cssServerMain.js",
          "--stdio",
        },
      },
    },
  },
```
to defaults.lua because right now im adding the above to defaults directly but would love to be able to enable it via the config. Is there another way to tell null-ls to start on scss files

ive tried lvim.lang.scss.formaters and adding prettier there but that just gives an error.
Or should I put in a pull to add scss to defaults with the same settings as less?

**Comment by kylo252** [comment]
> Or should I put in a pull to add scss to defaults with the same settings as less?

Exactly! Well except that it should be `css`. You can see which one has a symlink to see they share the same entry: https://github.com/LunarVim/LunarVim/blob/87d36102919df97ec15af4c916e37888cee279cd/ftplugin/scss.lua

Let me know if that solves your problem.

**Comment by kylo252** [comment]
This now works out-of-the-box after #1584. 

You can set it explicitly: 

```lua
lvim.lang.scss.formatters = { { exe = "prettier" } }
```
