### ISSUE TITLE
[Bug]: Regression? from #1462 virtual text has lost its source

### ISSUE THREAD

**Issue by afridley** [LunarVim/LunarVim#1538]
### Problem description

virtual text has gone from

> Pyright: "re" is not accessed
> to
> "re" is not accessed

Pyright does show with gl.

It would be nice to have the option to show pyright in the virtual text as well though I could see others opting not to have it.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

latest rolling 9/13/2021

### Neovim version (>= 0.5)

0.6.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
they cause unexpected side effects, for example, code actions didn't work properly in clang, so instead of  messing with diagnostics, we've created that `gl` thingy
