### ISSUE TITLE
[Feature]: actually use neovim-remote 

### ISSUE THREAD

**Issue by snoblenet** [LunarVim/LunarVim#1539]
### Feature motivation

LunarVim is actually installing [neovim-remote](https://github.com/LunarVim/LunarVim/commit/ba4a959b906c6aadd953626c13845dc6d1a97978), but not currently using it as far as I can tell.

Neovim-remote can be used to tell an existing instance of Neovim to open a file, instead of opening a new instance each time. (Amongst other things.)

This is how I use it in my `~/.zshenv`. (Minus some unreliable logic that attempts to handle line numbers in filenames and some logic that finds the relevant Tmux tab.) Could LunarVim do something similar?

```
function neovim() {
  export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket

  server="$(nvr --serverlist)"

  if [[ -z "$server" ]]; then # neovim remote server not found
    eval "NVIM_LISTEN_ADDRESS=/tmp/nvimsocket command nvim ${@:-.}"
  else
    eval "nvr -O ${@:-.}"
  fi
}

```

### Describe the expected solution

If the user so chooses, LunarVim can always open new files in an existing instance of the app.

**Comment by lytex** [comment]
It seems the nvr command is not working properly with the LSP. I get a `Client 2 exit with code 127 and signal 0` each time and no linting at all when opening a python file with nvr from within a lunarvim terminal, using `lvim --noplugins`
