### ISSUE TITLE
[Bug]: My config.lua was replaced on fresh install

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#1541]
### Problem description

My config.lua was replaced on fresh install

It should preserve pre-existing config.lua

### LunarVim version

rolling

### Neovim version (>= 0.5)

.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by afridley** [comment]
Looks like #1381 change the config directory to .config/nvim rather then .config/lvim

**Comment by kylo252** [comment]
The user files are always backed-up during the installation very early on.

It should also be fixed by updating any outdated `lvim` binary that you have, see https://github.com/LunarVim/LunarVim/blob/rolling/README.md#known-issues
