### ISSUE TITLE
[Bug]: Install Error

### ISSUE THREAD

**Issue by Gabriel-JM** [LunarVim/LunarVim#1542]
### Problem description

Get this error when after LunarVim cloning, when preparing Packer setup:
```bash
Preparing Packer setup
Error detected while processing /home/gabriel/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: /home/gabriel/.local/share/lunarvim/lvim/init.lua:6: module 'bootstrap' not found:
	no field package.preload['bootstrap']
	no file './bootstrap.lua'
	no file '/usr/share/luajit-2.1.0-beta3/bootstrap.lua'
	no file '/usr/local/share/lua/5.1/bootstrap.lua'
	no file '/usr/local/share/lua/5.1/bootstrap/init.lua'
	no file '/usr/share/lua/5.1/bootstrap.lua'
	no file '/usr/share/lua/5.1/bootstrap/init.lua'
	no file './bootstrap.so'
	no file '/usr/local/lib/lua/5.1/bootstrap.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/bootstrap.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'Error detected while processing command line:
E492: Not an editor command: PackerSync
Press ENTER or type command to continuenvim: /build/neovim-CyuPli/neovim-0.6.0~ubuntu1+git202109101209-185ed18e6-adeb5640f/src/nvim/message.c:2292: msg_scroll_flush: Assertion `to_scroll >= 0' failed.
/proc/self/fd/11: line 264: 95282 Aborted                 (core dumped) nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
```

### LunarVim version

Stable

### Neovim version (>= 0.5)

v0.6.0-dev

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Gabriel-JM** [comment]
It was working correctly and then i reinstall it and always get this error

**Comment by afridley** [comment]
I had the same issue 

had to clone manually and rollback to a previous commit then I was able to PackerInstall

**Comment by whitehat33** [comment]
I have the same problem.

**Comment by nzlov** [comment]
wbthomason/packer.nvim#502 (comment)
```
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
```

**Comment by nzlov** [comment]
Fix:

wbthomason/packer.nvim#502 (comment)

```
lvim  -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
```

**Comment by Mate2xo** [comment]
Same here, on the Stable branch. Installed it on one computer this weekend and was working fine ; installed it yesterday on another, and it failed on this error (both are Ubuntu-base OS). Since the stable branch has not changed these last 2 days, I guess the problem could lie somewhere else


> Fix:
> 
> [wbthomason/packer.nvim#502](https://github.com/wbthomason/packer.nvim/issues/502) (comment)
> 
> ```
> lvim  -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
> ```

@nzlov this line is actually what is launched by the install script, and what makes the script fail. Launching it manually afterwards doesn't cause any failure though, and I could also just launch `Packer` commands from lvim. So maybe this could be some kind of timing issue causing the 'bootstrap' module to not be loaded yet when launched by the script. My two systems are pretty similar (LinuxMint and Budgie), so I cannot think of something else

**Comment by Groving** [comment]
I install lua51. Pacman -S lua51. It decide my problem

**Comment by pr3c0g** [comment]
I also have that problem when installing, but opening lvim and running `:PackerSync` works fine.

In case someone faces the same issue that I had, I had to remove the old bin at `/usr/local/bin/lvim` from previous versions (the new one is `~/.local/bin/lvim`)

Thanks to @rebuilt for the help on that one

**Comment by whitehat33** [comment]
> I also have that problem when installing, but opening lvim and running `:PackerSync` works fine.
> 
> In case someone faces the same issue that I had, I had to remove the old bin at `/usr/local/bin/lvim` from previous versions (the new one is `~/.local/bin/lvim`)
> 
> Thanks to @rebuilt for the help on that one

Thanks @pr3c0g, this has fixed the problem.

**Comment by smikeya** [comment]
to fix error roll back to commit 009f004 
rm -rf ~/.local/share/lunarvim/lvim
git clone git clone https://github.com/LunarVim/LunarVim.git ~/.local/share/lunarvim/lvim
cd ~/.local/share/lunarvim/lvim
git checkout 009f004
and voila
lvim +PackerSync
should be OK
P.S. till error will be fixed

**Comment by Gabriel-JM** [comment]
> I also have that problem when installing, but opening lvim and running `:PackerSync` works fine.
> 
> In case someone faces the same issue that I had, I had to remove the old bin at `/usr/local/bin/lvim` from previous versions (the new one is `~/.local/bin/lvim`)
> 
> Thanks to @rebuilt for the help on that one

Yes i tested it yesterday and worked too. When launching lunarvim it was opening only the neovim, and after running `:PackerSync` it seems like it loads everything and boom, it worked.

**Comment by smikeya** [comment]
Strange because of this error: E492: Not an editor command: PackerSync 
I removed completely and reinstalled  and :Packer is not a command i.e. in's not loaded
Smth is wrong with bootstrap and rintime paths

**Comment by reynerdev** [comment]
I have the same problem. Delete everything by following the instruction from the website and everything remains the same. I

![image](https://user-images.githubusercontent.com/58928047/133351321-9b84b410-41ce-4a11-8a29-3205e71b73cc.png)

**Comment by smikeya** [comment]
#1156 doesn't fix. Your last changes in decoupling is wrong/ I have TrueZen nvim in ~/.local/share/nvim/pack/packer/opt/ dir/ and lvim give error in lualine table. In LunarVim TueZen is not installed. So, cleaning cache is not a solution.

**Comment by rebuilt** [comment]
> I have the same problem. Delete everything by following the instruction from the website and everything remains the same. I
> 
> ![image](https://user-images.githubusercontent.com/58928047/133351321-9b84b410-41ce-4a11-8a29-3205e71b73cc.png)


Can you try the instructions from the known issues section please.
https://github.com/LunarVim/LunarVim

**Comment by smikeya** [comment]
> > I have the same problem. Delete everything by following the instruction from the website and everything remains the same. I
> > ![image](https://user-images.githubusercontent.com/58928047/133351321-9b84b410-41ce-4a11-8a29-3205e71b73cc.png)
> 
> Can you try the instructions from the known issues section please.
> https://github.com/LunarVim/LunarVim

It seems to me that it depends on which distrib you use. I have 2 MXLinux  - it give error and Arch I didn't try.
