### ISSUE TITLE
[Bug]: Can't map <C-i>

### ISSUE THREAD

**Issue by ThangEthan** [LunarVim/LunarVim#1543]
### Problem description

```
lvim.keys.insert_mode = {
  ["<C-i>"] = "<Esc>I",
}

```
This mapping doesn't work, it will insert a Tab character. In :imap I found 
`<Tab>       * <Esc>I
`

### LunarVim version

latest

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Pressing `<C-i>` sends the same terminal keycode as pressing `Tab`.  The only way to get around that fact is to change what keycode your terminal sends.  You can change this in your terminal itself or you can follow the suggestion here:

https://vi.stackexchange.com/questions/16161/how-to-map-c-i-separate-from-tab

**Comment by rebuilt** [comment]
This isn't really a bug with Lunarvim so I'm closing.
