### ISSUE TITLE
[Bug]: Modifying Lualine Config Causes Dashboard to Randomly Display Numbers

### ISSUE THREAD

**Issue by LandonSchropp** [LunarVim/LunarVim#1549]
### Problem description

This is a follow-up to #1525. That issue actually turned out to be *two* issues, so I'm splitting it into more specific issues.

When I modify the Lualine config, the Dashboard randomly displays numbers about 50% of the time.

https://user-images.githubusercontent.com/361591/132933007-13a72922-e908-43a8-940a-f994fa123e2b.mp4

Here's the portion of my config that seems to be the culprit:

``` lua
local components = require("core.lualine.components")

-- Configure the status line.
lvim.builtin.lualine.options.icons_enabled = true
lvim.builtin.lualine.options.section_separators = { "", "" }
lvim.builtin.lualine.options.component_separators = { "", "" }

local function location()
  return vim.fn.line(".") .. "/" .. vim.fn.line("$")
end

lvim.builtin.lualine.sections.lualine_a = { "mode" }
lvim.builtin.lualine.sections.lualine_b = { components.branch }
lvim.builtin.lualine.sections.lualine_c = { components.filename }
lvim.builtin.lualine.sections.lualine_x = {
  components.diagnostics,
  components.diff,
  separator = " ",
}
lvim.builtin.lualine.sections.lualine_y = { components.filetype }
lvim.builtin.lualine.sections.lualine_z = { location }
```

I don't know why this would be affecting the numbers in the dashboard. However, since I *think* this config should be valid, I thought I'd open it up as a bug.

### LunarVim version

Latest

### Neovim version (>= 0.5)

v0.5.0

### Relevant log output

```shell
N/A
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ssbanerje** [comment]
I am not sure if this is related, but running `:PackerSync` causes the Dashboard to have line numbers and cursor line.

**Comment by abzcoding** [comment]
dashboard is about to be replaced with alpha.nvim, so this shouldn't be an issue anymore
