### ISSUE TITLE
[Bug]: Neovide Not Loading LunarVim Config

### ISSUE THREAD

**Issue by MarkJamesXL** [LunarVim/LunarVim#1553]
### Problem description

I'm running LunarVim with neovide gui using this command:

`neovide -- -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim"`

Which used to work just fine until last night where an update of neovim broke neovide and started rendering only background colors, according to this: https://github.com/neovide/neovide/issues/954#issuecomment-918394524 
The issue was patched this morning and neovide is working with .vimrc config (everything is rendering correctly), but it wouldn't use the LunarVim config, and when I run the specified command neovide runs with .vimrc config. 

### LunarVim version

version 0.5.1, and a git pull of the rolling release shows that I'm up to date

### Neovim version (>= 0.5)

NVIM v0.5.0 Build type: Release LuaJIT 2.0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Are you on the latest rolling? can you please test it without modifying the `&rtp`: 
`neovide -- -u ~/.local/share/lunarvim/lvim/init.lua`

**Comment by MarkJamesXL** [comment]
Thanks for your help, yes I'm on the latest rolling release, and launching it without modifying the `&rtp` also doesn't launch Neovide with the LunarVim config or plugins.

**Comment by kylo252** [comment]
Oh I just realized what happened. This is most probably related to #1381. 
I had made it so that you can start neovim with lunarvim config from the default config directory `$XDG_CONFIG_HOME/nvim`. So then you can launch any GUI without needing to mess with the `&rtp`. 

But if you'd like to still keep `lvim` separate, then you need to set some environment variables. I had been planning to introduce this binary, but I needed someone to test it. 

```bash
#!/bin/sh

export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-$HOME/.config/lvim}"
export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-$HOME/.local/share/lunarvim}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-$HOME/.cache/lvim}"

exec neovide -- -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
```

You can test it from the terminal and add it somewhere on your path and see if it works: 

```bash
touch lvim-gui #or neovide-lv or something
# paste the snippet above
chmod +x lvim-gui
mv lvim-gui ~/.local/bin/.
```

**Comment by MarkJamesXL** [comment]
Thanks it works out great, Neovide is launching with the lunar config. 
As a side note, when you launch the lvim-gui, neovide starts with a blackscreen for a second then it loads the config and works out as intended, and this is nitpicking but since you are testing I figure you might want to know the how its working and the output, I don't care about it tbh.
Gonna close it since I believe the issue is solved.

**Comment by akiranguyenvni** [comment]
Hi guys, thank you all for sharing~
Based on what I learnt from you and other kind guys on internet, I figured out an awesome way to use Lunarvide, hence I would like to share you guys to.
Hope it's useful to you too.

The way is pretty simple, only `1` line of code.

I edit my `~/.zshrc`,
adding this line: `alias lunarvide="NVIM_APPNAME=neovim/LunarVim neovide"`
`source ~/.zshrc`
Voila! I can now open Lunarvide anywhere from console by `cd to/path && lunarvide .`

Here it is my all config:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/105026206/235603665-f99bce73-58b4-4f3f-8110-56089e564f67.png">

**Comment by revelationnow** [comment]
Is there a way to launch neovide with lunarvim config by default? I want to be able to right click on files in the windows explorer and open with neovide with lunarvim config. Right now it only allows me to open in vanilla neovide.
