### ISSUE TITLE
[Bug]: Can't set markdown linters

### ISSUE THREAD

**Issue by LandonSchropp** [LunarVim/LunarVim#1554]
### Problem description

I'm trying to configure my markdown linters.

``` lua
lvim.lang.markdown.linters = { { exe = "markdownlint" }, { exe = "write_good" } }
```

However, this produces an error:

```
Vim(luafile):E5113: Error while calling lua chunk: /Users/landon/.config/lvim/lua/user/language.lua:13: attempt to index field 'markdown'
(a nil value)
```

### LunarVim version

Latest

### Neovim version (>= 0.5)

v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by LandonSchropp** [comment]
As a side note, I think this configuration is kind of clunky compared to null_ls's default configuration. Specifically, I don't like that I have to specify the configuration for each file type instead of just being able to specify each linter individually.

``` lua
-- Enable formatting.
lvim.format_on_save = true

local sources = {

  -- Formatters
  null_ls.builtins.formatting.eslint_d,
  null_ls.builtins.formatting.fixjson,
  null_ls.builtins.formatting.mix,
  null_ls.builtins.formatting.stylua,

  -- Linters
  null_ls.builtins.diagnostics.eslint_d,
  null_ls.builtins.diagnostics.rubocop,
  null_ls.builtins.diagnostics.shellcheck,
  null_ls.builtins.diagnostics.markdownlint,
  null_ls.builtins.diagnostics.write_good,
}

-- Enable the formatters and linters.
null_ls.register({ sources = sources })
```

The main reason I'm not using this is because it causes some other issues with LunarVim.

**Comment by afridley** [comment]
Im wondering if null-ls is even started. if you do LspInfo does null ls even start

I ran into an issue recently #1536 that makes me think Null-ls only looks at this file and wont start unless the language is there which markdown isnt.
https://github.com/LunarVim/LunarVim/blob/rolling/lua/config/defaults.lua

It seems weird that null-ls doesn't start based on the language server being used filetypes if the lang server has a specified linter / formater. But maybe thats to expensive performance wise to figure out.

**Comment by LandonSchropp** [comment]
@afridley Thanks for the reply! I think this error is happening before we even get to markdown. The error message I posted seems to indicate that I'm trying to set the `linters` property of `markdown`, but `markdown` isn't a table.

My other linters and formatters work fine with null_ls.

**Comment by abzcoding** [comment]
you can set this in your config.lua, till we fix it upstream
```lua
lvim.lang.markdown = {}
lvim.builtin.lspinstall.on_config_done = function()
  lvim.lang.tailwindcss.lsp.setup.filetypes = { "markdown" }
  lvim.lang.tailwindcss.lsp.active = true
  require("lsp").setup "tailwindcss"
end
```
and then set linters/formatters after it or in the proper ftplugin file

**Comment by LandonSchropp** [comment]
Thanks! I'll do that.

Should some of this code make it into the main repo?

**Comment by abzcoding** [comment]
> Thanks! I'll do that.
> 
> Should some of this code make it into the main repo?

it might 😅

**Comment by younger-1** [comment]
> 
> 
> you can set this in your config.lua, till we fix it upstream
> 
> ```lua
> lvim.lang.markdown = {}
> lvim.builtin.lspinstall.on_config_done = function()
>   lvim.lang.tailwindcss.lsp.setup.filetypes = { "markdown" }
>   lvim.lang.tailwindcss.lsp.active = true
>   require("lsp").setup "tailwindcss"
> end
> ```
> 
> and then set linters/formatters after it or in the proper ftplugin file

I think this is not bad choice to using `markdown` linters or formatters:

After install `prettier` and `markdownlint-cli`, adding a ftplugin lua file to `lunarvim` config dir, like this `~/.config/lvim/ftplugin/markdown.lua`

```lua
require("lsp.null-ls").setup "markdown"
lvim.lang.markdown = {
  formatters = {
    {
      exe = "prettier",
    },
  },
  linters = {
    {
      exe = "markdownlint",
    },
  },
}
```

**Comment by younger-1** [comment]
> I think this is not bad choice to using `markdown` linters or formatters:
> 
> After install `prettier` and `markdownlint-cli`, adding a ftplugin lua file to `lunarvim` config dir, like this `~/.config/lvim/ftplugin/markdown.lua`
> 
> ```lua
> require("lsp.null-ls").setup "markdown"
> lvim.lang.markdown = {
>   formatters = {
>     {
>       exe = "prettier",
>     },
>   },
>   linters = {
>     {
>       exe = "markdownlint",
>     },
>   },
> }
> ```

There is still a problem. When use above workarounds, the buffer-keymappings which will be added by lunarvim's [lsp-mudule](https://github.com/LunarVim/LunarVim/blob/rolling/lua/lsp/init.lua#L32) only when LS attach to a buffer is not defined. May there is a better way to add some meaningful keymappings through a unifed way to avoid the boilerplate code.

```lua
  local keys = {
    ["K"] = { "<cmd>lua vim.lsp.buf.hover()<CR>", "Show hover" },
    ["gd"] = { "<cmd>lua vim.lsp.buf.definition()<CR>", "Goto Definition" },
    ["gD"] = { "<cmd>lua vim.lsp.buf.declaration()<CR>", "Goto declaration" },
    ["gr"] = { "<cmd>lua vim.lsp.buf.references()<CR>", "Goto references" },
    ["gI"] = { "<cmd>lua vim.lsp.buf.implementation()<CR>", "Goto Implementation" },
    ["gs"] = { "<cmd>lua vim.lsp.buf.signature_help()<CR>", "show signature help" },
    ["gp"] = { "<cmd>lua require'lsp.peek'.Peek('definition')<CR>", "Peek definition" },
    ["gl"] = {
      "<cmd>lua require'lsp.handlers'.show_line_diagnostics()<CR>",
      "Show line diagnostics",
    },
  }
```

**Comment by kylo252** [comment]
> There is still a problem. When use above workarounds, the buffer-keymappings which will be added by lunarvim's [lsp-mudule](https://github.com/LunarVim/LunarVim/blob/rolling/lua/lsp/init.lua?rgh-link-date=2021-09-25T16%3A09%3A48Z#L32) only when LS attach to a buffer is not defined. May there is a better way to add some meaningful keymappings(`gl`, `gr` for example) through a unifed way to avoid the boilerplate code.

That was done intentionally since null-ls doesn't support nearly any of those capabilities, except for the `gl` command. You can still bind any of them manually if you want to try.

**Comment by kylo252** [comment]
This now works out-of-the-box after #1584. 

You can set it explicitly: 

```lua
lvim.lang.markdown.formatters = { { exe = "prettier" } }
```

**Comment by LandonSchropp** [comment]
Thanks!
