### ISSUE TITLE
[Bug]: If you press "j" and "k" quickly in insert mode, it switches to visual mode

### ISSUE THREAD

**Issue by lnwor** [LunarVim/LunarVim#1560]
### Problem description

1. Open lvim
2. Switch to insert mode
3. Press quickly "j" and "k"
4. Notice it switches to visual mode

Besides, when I'm pressing j and k lunarvim has some sort of delay in the cursor, while it doesn't happen with other  keys

### LunarVim version

Up to date with commit edcf15ba672986cb90358e739d801919f4cf91e0

### Neovim version (>= 0.5)

0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
believe it or not, that is a feature, which you can disable 😅 
it would go to `normal_mode` though

```lua
lvim.keys.insert_mode["jk"]=nil
```
<img width="526" alt="Screen Shot 2021-09-15 at 11 21 44 PM" src="https://user-images.githubusercontent.com/10992695/133492321-23373253-a9bc-489b-a88f-81f71ad3748b.png">

**Comment by lnwor** [comment]
Oh. I never would have thought that it was a feature 😅. Thank you for showing me how to disable it
