### ISSUE TITLE
[Feature]: Disable format_on_save for specific file types

### ISSUE THREAD

**Issue by reykjalin** [LunarVim/LunarVim#1561]
### Feature motivation

I use Intelephense for PHP development and by default it's set to format on save. I confirmed this by disabling any other PHP linters and formatters and enabled only Intelephense. When I save the file it's automatically formatted.

The easiest solution seems to be to allow people to disable autoformat for specific file types, e.g. via a `lvim.lang.php.format_on_save = false`.

I still want format on save enabled for other languages, e.g. JS/TS, so disabling `format_on_save` for the every type of file is a bit too excessive.

It's also a bit counter-intuitive to have no formatters configured in `lvim.lang.php.formatters` and my php files are still formatted on save.

### Describe the expected solution

Allow me to disable `format_on_save` for specific file types.

### Manually configure the language server

I tried changing the settings by adding this in my `.config/lvim/config.lua`:

```lua
lvim.lang.php.lsp.settings = {
  intelephense = {
    format = {
      enable = false,
    },
  },
}
```

But that didn't work. I tried other variations of this, e.g. `lvim.lang.php.lsp.settings.intelephense.format.enable = false`, but that didn't work either.

**Comment by sagikazarmark** [comment]
It took me a while to figure this out, but you can disable formatting in intelephense using the following snippet:

```lua
vim.list_extend(lvim.lsp.override, { "intelephense" })

require("lvim.lsp.manager").setup("intelephense", {
  settings = {
    intelephense = {
      format = {
        enable = false
      }
    }
  }
})
```

**Comment by sagikazarmark** [comment]
Scratch that, I thought it works, but it doesn't. :\

I've spent quite a bit of time on this as well, it's a shame it's this hard to disable.

**Comment by sagikazarmark** [comment]
I did some debugging and I'm not entirely convinced this is a lunarvim/nvim-lspconfig issue.

I opened a new issue here: bmewburn/vscode-intelephense#2003
