### ISSUE TITLE
[Bug]: Completion is inserting non-selected item from menu

### ISSUE THREAD

**Issue by windowsrefund** [LunarVim/LunarVim#1563]
### Problem description

Create a new python file
```
touch foo.py
````
Edit the file
```
lvim foo.py
```
Enter the following line but do not press Enter after the last character
```
foo.py
```
On my system, I see a single option of 'property' appear in the autocomplete menu. This appears to be a snippet. This single option is not selected so I press Enter with the expectation of being dropped to the next line while remaining in Insert mode.

However, the 'property' snippet ends up being used and I end up with an unintended mess
```
foo.def foo():
    doc = "The foo property."
    def fget(self):
        return self._foo
    def fset(self, value):
        self._foo = value
    def fdel(self):
        del self._foo
    return locals()
foo = property(**foo())
```
I attempted to overcome this by ensuring completeopt is set to not select by default

```
:set completeopt?
completeopt=menuone,noinsert,noselect
```

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
can you confirm if #1523 fixes anything for you or not?

**Comment by windowsrefund** [comment]
I updated my rolling release and added the line but am still seeing the same behavior
```
lvm.builtin.cmp.confirm_opts.select = false

**Comment by abzcoding** [comment]
that is not yet merged with rolling
you can test it using
```sh
cd ~/.local/share/lunarvim/lvim
git checkout -b chase-improve_cmp_complete_mapping rolling
git pull https://github.com/chase/LunarVim.git improve_cmp_complete_mapping
```
to test it
and use
```sh
cd ~/.local/share/lunarvim/lvim
git checkout rolling
```
to get back to `rolling`

**Comment by windowsrefund** [comment]
Thank you. It does work as expected. In fact, I was even able to remove change I had mentioned regarding _completeopt_ and still have it work.

**Comment by abzcoding** [comment]
> Thank you. It does work as expected. In fact, I was even able to remove change I had mentioned regarding _completeopt_ and still have it work.

cc: @chase
