### ISSUE TITLE
[Bug]: Lunar Crashes when installing Java Lsp

### ISSUE THREAD

**Issue by MarkJamesXL** [LunarVim/LunarVim#1567]
### Problem description

Using `LspInstall java` spites out `java.lang=ALL-UNNAMED \\^@  -jar \$(echo "\$JAR") \\^@  -configuration "\$CONFIG" \\^@  -data "\$WORKSPACE"^@EOF^@    chmod +x jdtls.sh^@` before crashing LunarVim. Its an old issue though.

### LunarVim version

Latest Rolling Release

### Neovim version (>= 0.5)

0.5.0 

### Relevant log output

```shell
`checkhealth` gives out:
`Error detected while processing function health#check:                                                                                               
line   16:                                                                                                                                           
E5108: Error executing lua ...pack/packer/start/lualine.nvim/lua/lualine/component.lua:75: bad argument #2 to 'rep' (number expected, got table)`
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by antonio-hickey** [comment]
Having this same problem

**Comment by kylo252** [comment]
That's why there's a bundled https://github.com/LunarVim/LunarVim/blob/65392c553ea6a69053a99fea57c3dee6c48afa75/utils/bin/jdtls

**Comment by MarkJamesXL** [comment]
> That's why there's a bundled https://github.com/LunarVim/LunarVim/blob/65392c553ea6a69053a99fea57c3dee6c48afa75/utils/bin/jdtls

Trying to use the sh file file gives out ```Error: Unable to access jarfile /home/mark/.local/share/nvim/lspinstall/java/plugins/org.eclipse.equinox.launcher_*.jar```

**Comment by ChristianChiarulli** [comment]
It's weird because I installed java like a few days ago with `:LspInstall`

**Comment by MarkJamesXL** [comment]
@ChristianChiarulli It's an old issue I remember encoutering it more than two weeks back when I first installed lunar back then, never reported because I hadn't any use for Java, but now I have a college course in java and not reporting it came to bite me back 🌚

**Comment by williamgoulois** [comment]
I have this issue but in all filetypes/projets it triggers when i open a file (not in dashboard)

https://user-images.githubusercontent.com/37271970/133942900-5445e0c9-a287-46d8-a198-3c690c0dc960.mov

**Comment by williamgoulois** [comment]
Looks like it has a link with cache ! I managed to remove the issue with `:LvimCacheReset` !

**Comment by foodornt** [comment]
Same issue, crashes with an error saying: `stack smashing`

**Comment by antonio-hickey** [comment]
After a fresh reinstall of lvim i was able to install java lsp, i was running rolling before and still running rolling now not sure what the reasoning of this is, but for anyone having trouble with this try a fresh reinstall. Back up your config before and check out the the doc's https://www.lunarvim.org/01-installing.html#uninstall before uninstalling.

**Comment by MarkJamesXL** [comment]
No need to do a fresh install its working fine now without one, just tried it, I don't know if its related but maybe deleting the nvim cache folder in ~/.cache and the  ~/.local/share/nvim fixed it for me. Gonna close since I believe the issue is fixed.
