### ISSUE TITLE
[Bug]: When pressing j or k cursor flickers

### ISSUE THREAD

**Issue by Balrrach** [LunarVim/LunarVim#1571]
### Problem description

Steps to reproduce:
1. Enter insert format at any level
2. Press j or k
3. Watch the cursor flicker back and forth

### LunarVim version

Last one I believe

### Neovim version (>= 0.5)

0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by xeluxee** [comment]
That isn't an issue, that behaviour is caused by some mappings to exit from insert mode without pressing esc.
Press `jj`, `jk` or `kj` in insert mode to exit to normal mode.
See #1560 if you want to disable.

**Comment by Balrrach** [comment]
Fixed! Thanks a lot
