### ISSUE TITLE
[Bug]: some plugins won't load immediately after calling lv-reload-config()

### ISSUE THREAD

**Issue by kylo252** [LunarVim/LunarVim#1574]
# Description

Saving `config.lua` or triggering the reload function will not reload any lazy-loaded plugins.

## How to reproduce

- open a buffer and enter insert mode, then call `:PackerStatus` to check the active plugins. 
- save `config.lua` or use `<leader>Lr`
- check `:PackerStatus` again and you'll see that some plugins won't load again, e.g. `autopairs`

**Comment by kylo252** [comment]
Probably related to #1556.

**Comment by rag-hav** [comment]
after saving the ~/.config/lvim/config.lua the newly generated plugins/packer_compiled.lua has autopairs turned off. But using <Leader>Lr to reset always generates the correct one.

Curiously, commenting out line 97 of utils/init.lua `  plugin_loader:cache_reset()
` makes it so, that a single save makes correct packer_compiled, but now <Leader>Lr also works only once. After which doing either results in a bad packer_compiled.lua

**Comment by kylo252** [comment]
Switching to `BufWinEnter` instead of `BufRead` seems to work fine on my side, except for some problem with `cmp` and/or `autopairs`.

**Comment by abzcoding** [comment]
should be fixed now :)
