### ISSUE TITLE
[Bug]: Diff colors are VERY hard to see in onedarker

### ISSUE THREAD

**Issue by ssbanerje** [LunarVim/LunarVim#1576]
### Problem
I am not sure if this is bug report or feature request.

The colors from the `Diff*` highlight group are very hard to see. 

I don't think these colors are set anywhere in the default `onedarker` theme. As a result they are quite difficult to look at on the darker background. It would be better to have higher contrast like those used with TreeSitter.

AFAIK here is the group:
```
DiffAdd        xxx ctermbg=4 guifg=#282c34 guibg=#587c0c
DiffChange     xxx ctermbg=5 gui=underline guifg=#282c34 guibg=#0c7d9d
DiffDelete     xxx ctermfg=12 ctermbg=6 gui=bold guifg=#282c34 guibg=#94151b
DiffText       xxx cterm=bold ctermbg=9 gui=bold guibg=Red
DiffviewVertSplit xxx guibg=#1f2227
DiffviewFilePanelDeletion xxx guifg=#94151b
DiffviewFilePanelInsertion xxx guifg=#587c0c
DiffviewStatusDeleted xxx guifg=#94151b
DiffviewStatusRenamed xxx guifg=#0c7d9d
DiffviewStatusModified xxx guifg=#0c7d9d
DiffviewStatusAdded xxx guifg=#587c0c
DiffViewNormal xxx guifg=#5c6370 guibg=#282c34
```

### Steps to reproduce
```
lvim -d <file1> <file2>
```

### Solution
It seems that other "onedark" implementations have already have these settings. Maybe these could be added into the lvim ondarker implementation.

https://github.com/navarasu/onedark.nvim/blob/35119a8b264fe9b06ec4245601b7722debb0dd0b/lua/onedark/highlights.lua#L57-L64

https://github.com/navarasu/onedark.nvim/blob/35119a8b264fe9b06ec4245601b7722debb0dd0b/lua/onedark/highlights.lua#L239-L264

### LunarVim version

rolling @ 87d3610

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
a PR would be appreciated 🥺
