### ISSUE TITLE
[Bug]: Line diagnostic (gl) message not readable, overflows out of screen

### ISSUE THREAD

**Issue by lallenfrancisl** [LunarVim/LunarVim#1587]
### Problem description

1. Go to a line having a diagnostic message
2. hit `gl`
3. If the diagnostic message is long enough it will overflow

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5.0

### Screenshots

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/21018348/134042451-af684bfc-22ce-4b6a-873c-7a3c1aa66b27.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
i actually wanted to fix this, what is an acceptable width for it? 120?

**Comment by Jacob87** [comment]
I have the same problem
I also want to mention that when we hit `gl` 2x times, it no longer focuses the diagnostic window. (Like we were able to do before).


It looks like these issues happened since this merge:
* #1487

**Comment by abzcoding** [comment]
@Jacob87 i added another commit in #1588, you should be able to change focus as well

**Comment by Jacob87** [comment]
@abzcoding Unfortunately it doesn't seem to work 🤔. It only gets focused when I manually click it with my mouse and when  focused it doesn't close when I press Q also (exactly when you hover something with shfit-K ^^'
I also tried this patch: [abzcoding@2054ebc](https://github.com/abzcoding/LunarVim/commit/2054ebc0f3f984caf30fabfe9685931dc76047b5)

**Comment by abzcoding** [comment]
the issue is that i have set to style to minimal which causes this, but the upside is not showing a big ass border and number stuff 🤷

**Comment by abzcoding** [comment]
i can set the cursor to the start of the floating window though if that seems better 🤔
