### ISSUE TITLE
[Bug]: bootstrap.lua not found

### ISSUE THREAD

**Issue by tabot-kevin** [LunarVim/LunarVim#1590]
### Problem description

Try to install the latest master, by copying the link and pasting on the terminal to install.
`bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

> 0.5

### Screenshots

<img width="1016" alt="Screen Shot 2021-09-21 at 1 16 48 AM" src="https://user-images.githubusercontent.com/81575086/134093561-1e34430f-75f6-4304-b44e-191b54f24f6f.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Open lvim and run :PackerSync to install your plugins

**Comment by abzcoding** [comment]
<img width="909" alt="Screen Shot 2021-09-21 at 12 39 48 PM" src="https://user-images.githubusercontent.com/10992695/134135495-1370d9b0-91a8-4ca1-b2a8-21c6d6f86a4a.png">
