### ISSUE TITLE
[Feature]: change font on install, also set the example configuration as default

### ISSUE THREAD

**Issue by eleijonmarck** [LunarVim/LunarVim#1596]
### Feature motivation

This is a exceptional step to making vim "just work".

What would make lunarvim even more exceptional:
- example configuration set on installation
- install and set a nerd font on installation

This way "everything" seem to just work out of the box after installation.

The thing we should strive for is no configuration needed for everything to work.

Hopefully this makes sense

### Describe the expected solution
- example configuration set on installation
- install and set a nerd font on installation

**Comment by abzcoding** [comment]
installing and setting a nerd font is not an easy task
it also requires sudo privileges and touching your terminal configurations
all of which should not be done by your editor
but for the example part, we are proving a sample configuration in `~/.config/lvim//config.lua`, which comes from 
https://github.com/LunarVim/LunarVim/blob/rolling/utils/installer/config.example.lua

but we want to keep it as minimal as possible and instead encourage people to tune the config to their liking and also to check out https://www.lunarvim.org/community/faq.html#where-can-i-find-some-example-configs

**Comment by eleijonmarck** [comment]
@abzcoding gotcha!

it's funny how setting a font is hard to get really. Otherwise you would have to embed it and such.

thanks for all the clarifications and all your help :+1:
