### ISSUE TITLE
[Bug]: can't get `gd` to work properly in lua projects

### ISSUE THREAD

**Issue by younger-1** [LunarVim/LunarVim#1603]
### Problem description

I used `LunarVim` for a mouth and I am really suprised by it's amazing customizability and user-friendly. I have solved many little stuff in my daily usage of lunarvim by searching for the project's issues or reading the source code most of time. But I stilll confused by this problem and can't solve it from the first time when I used lunarvim.

This problem is that `gd` can't take me to tables and functions that need `require`, though they are defined in current lua project. It only take me to tables and functions defined in current buffer as well as builtin types and functions.

Take lunarvim source as an example. The situation that `gd` doesn't work:

```lua
-- https://github.com/LunarVim/LunarVim/blob/rolling/init.lua#L6
require("bootstrap"):init() -- Here I can't go to definition of module `bootstrap` or function `init`

-- https://github.com/LunarVim/LunarVim/blob/rolling/lua/bootstrap.lua#L49
self.runtime_dir = get_runtime_dir() -- Here I can go to function `get_runtime_dir`, it is defined is this file
```

This problem only happened in lua project with lua-lsp `sumneko_lua` installed. And I had test some other language (python, c++, go, rust) with lsp installed and `gd` worked properly.

I reinstalled `sumneko_lua` many times and try in another computer but the problem is still there.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [x] The programs specified by the config are installed

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.5.0

### Relevant log output

```shell
Language client log: /home/xavier/.cache/nvim/lsp.log
 Detected filetype:   lua
 
 2 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, pid: 5001, bufnr: [3, 3, 21, 24, 8])
 	filetypes:       lua
 	autostart:       false
 	root directory:  /home/xavier/.config/lvim
 	cmd:             nvim
 
 Client: sumneko_lua (id: 2, pid: 14911, bufnr: [3, 21, 21, 24, 24, 8, 8])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /home/xavier/.config/lvim
 	cmd:             /home/xavier/.local/share/nvim/lspinstall/lua/sumneko-lua-language-server -E /home/xavier/.local/share/nvim/lspinstall/lua/main.lua
 
 Configured servers list: lua, null-ls, python, go, sumneko_lua, rust, cpp
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
sadly this is a limitation of `sumneko_lua` language server as far as i know 😞

**Comment by younger-1** [comment]
> 
> 
> sadly this is a limitation of `sumneko_lua` language server as far as i know 😞

Surely not! Though I thought is the problem of lua-lsp in the beginning, but `sumneko_lua` has the ability to do it and more much better that it.  

Take lunarvim source as an example.

Here is the `gd` working properly with `sumneko_lua` in vscode:
![lunarvim-vscode](https://user-images.githubusercontent.com/45989017/134505701-4f6ed20c-48f6-433e-ab10-de8cdb5583f8.gif)

[sumneko_lua repo](https://github.com/sumneko/lua-language-server) shows what it can do and it's power is not restricted to vscode.

Here is the `gd` working properly with `sumneko_lua` in nvim config [nvchad](https://github.com/NvChad/NvChad):
![b](https://user-images.githubusercontent.com/45989017/134506984-551edaaf-ee09-4d9b-bb41-97852f5d2259.gif)

Here is the `gd` working properly with `sumneko_lua` in nvim config [doom](https://github.com/NTBBloodbath/doom-nvim):
![c](https://user-images.githubusercontent.com/45989017/134507733-6d3e8f73-522a-498e-a4fd-e0f19dac2062.gif)


I roughly look through their source code and their config have nothing 
Here is [lunarvim's](https://github.com/LunarVim/LunarVim/blob/rolling/lua/config/defaults.lua#L638) `sumneko_lua` config

Here is [nvchad's](https://github.com/NvChad/NvChad/blob/19e17eac58/lua/plugins/configs/lspconfig.lua#L83) `sumneko_lua` config which is almost the same as `lunarvim`

Here is [doom-nvim's](https://github.com/NTBBloodbath/doom-nvim/blob/1acb6e2834/lua/doom/modules/config/doom-lspinstall.lua#L22) `sumneko_lua` config which is managed by [](https://github.com/folke/lua-dev.nvim) to provide help for nvim builtin lua API and it's "go to definition" is still provided by `sumneko_lua`

So I really wonder what's mess up inside lunarvim and how to pick up the missing function.

**Comment by abzcoding** [comment]
have you found any neovim configuration that supports that? (not vscode)
if yes, then we can take a look and see what are we missing

**Comment by abzcoding** [comment]
based on the doom-nvim sample, the issue might be that without `lua-dev` plugin, the workspace doesn't contain `~/.local/share/lunarvim/lvim`

**Comment by abzcoding** [comment]
not sure though, we can ask @NTBBloodbath for help 🥺

**Comment by abzcoding** [comment]
@kylo252 do you have any idea why this wouldn't work in LV but works in all other configurations ?

**Comment by abzcoding** [comment]
@younger-1 i think i found the issue
can you comment these lines and check on your side?
<img width="1037" alt="Screen Shot 2021-09-23 at 5 00 47 PM" src="https://user-images.githubusercontent.com/10992695/134516043-ca7a8eb4-c5ea-41e7-b95a-12c1601d8283.png">

**Comment by younger-1** [comment]
@abzcoding  I am trying now!

**Comment by younger-1** [comment]
> 
> 
> @younger-1 i think i found the issue
> can you comment these lines and check on your side? (inside `lua/config/defaults.lua`)
> <img alt="Screen Shot 2021-09-23 at 5 00 47 PM" width="1037" src="https://user-images.githubusercontent.com/10992695/134516043-ca7a8eb4-c5ea-41e7-b95a-12c1601d8283.png">

@abzcoding  It works!! wowwww!!

**Comment by abzcoding** [comment]
ok let me make a PR
