### ISSUE TITLE
[Feature]: Specify guifont in config

### ISSUE THREAD

**Issue by jeffrey-l-turner** [LunarVim/LunarVim#1608]
### Feature motivation

I'm using Neovide on a Mac and the default guifont doesn't display properly. I've forked the report with a nerd font so that it displays properly. My changes can be found here: https://github.com/jeffrey-l-turner/LunarVim/blob/wcolor-rolling/lua/config/settings.lua#L14

### Describe the expected solution

Set a global variable allowing users to specify a nerd font so that Lunar Vim use a better nerd font.

**Comment by abzcoding** [comment]
basically the normal neovim way
```lua
vim.opt.guifont = "FiraCode Nerd Font:h13"
```
