### ISSUE TITLE
[Bug]: Insert mode view wrong/jump when there is an diagnostic in LSP (happened all the time)

### ISSUE THREAD

**Issue by haininhhoang94** [LunarVim/LunarVim#1609]
### Problem description

Steps to reproduce:
1. Open a random file (in this case quick-scope.lua)
2. The file need to have some error or warning
3. Whenever I edit the error line with insert mode, the view of the text is wrong but after return to Normal Mode, it is okay

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6

### Screenshots

![output](https://user-images.githubusercontent.com/34930708/134621817-ca4c4809-59ca-4891-93b6-8b7613bfb163.gif)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by angryheng** [comment]
same issue

**Comment by abzcoding** [comment]
till this issue is fixed can you guys at this to your `~/.config/lvim/config.lua` and use `gl` or `<leader>lj` and `<leader>lk` to view the diagnostics
```lua
lvim.lsp.diagnostics.virtual_text = false
```

**Comment by haininhhoang94** [comment]
> till this issue is fixed can you guys add this to your `~/.config/lvim/config.lua` and
> use `gl` or `<leader>lj` and `<leader>lk` to view the diagnostics
> 
> ```lua
> lvim.lsp.diagnostics.virtual_text = false
> ```

I confirm that this is working for now! 
Thanks!

But we still looking for the solution 😃

One thing that I have noticed that when using Neovim with Coc (forked from the previous release of LunarVim before LSP) is virtual text such as codi.vim didn't give this problem. Maybe some issues related to how LSP handle virtual text?

**Comment by youdaniel** [comment]
It seems to have something to do with the prefix character. When I do 
`lvim.lsp.diagnostics.virtual_text = true`
everything works fine.

**Comment by chase** [comment]
I wonder if it has to do with double-width characters in Nerdfonts. I've disabled it myself because I encountered the same problem.

**Comment by haininhhoang94** [comment]
> I wonder if it has to do with double-width characters in Nerdfonts. I've disabled it myself because I encountered the same problem.

How did you disable it?

> It seems to have something to do with the prefix character. When I do 
> 
> `lvim.lsp.diagnostics.virtual_text = true`
> 
> everything works fine.

Which font did you use? I use Hack Nerd Font

**Comment by youdaniel** [comment]
> Which font did you use? I use Hack Nerd Font

I use Iosevka Nerd Font.

You can disable it by setting `lvim.lsp.diagnostics.virtual_text` to false. If you still want to see the virtual text you can set it to true (this just overrides LunarVim's setting so the default character is used).

**Comment by kylo252** [comment]
I'm pretty sure this is related to the custom handlers.
cc @abzcoding

**Comment by abzcoding** [comment]
> I'm pretty sure this is related to the custom handlers.
> cc @abzcoding

no it's not, as mentioned above this is related the the icon that we are setting and also not using debounce
