### ISSUE TITLE
[Bug]: can't not use `nvim-telescope/telescope-packer.nvim`

### ISSUE THREAD

**Issue by younger-1** [LunarVim/LunarVim#1610]
### Problem description

`LunarVim` is not compatible with [telescope-packer.nvim](https://github.com/nvim-telescope/telescope-packer.nvim)

Step to reproduce:
1. add the plugin
```lua
lvim.plugins = {
  {
    "nvim-telescope/telescope-packer.nvim",
    after = "telescope.nvim", -- or module = "telescope.nvim" or without lazyload all will casue problem
    config = function()
      require("telescope").load_extension "packer"
    end,
  },
}
```

2. update lunarvim throuth `lvim +LvimCacheReset +PackerUpdate`

Once I have this plugin installed, no matter how I adjusted my `config.lua` and clear cache many times, somethings must be wrong with one of this commands: `PackerClean`, `PackerCompile`, `PackerUpdate`, `LvimCacheReset`

After restart nvim, all the plugin will not be loaded beacause packer-compiled file `~/.config/lvim/plugin/packer_compiled.lua` is changed(in my case, the file only contains 80 line)

If runnig `:PackerClean` is ok for you, try `:LvimCacheReset` (or `:PackerCompile`) and it's the begin of the really bad thing.
If plugin is all loaded, try to write something and save it to lunarvim config file (`~/.config/lvim/config.lua`), and it will cause error with the error message showed in following log 2:

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.5

### Relevant log output

Other bad things will be:
```log
1. PackerClean:
It will prompt to remove all the plugins installed both in vim's start and opt pack path. (Yes, I do input `y` deliberately and found all they gone)

2. LvimCacheReset or save the lunarvim config file:
Error detected while processing BufWritePost Autocommands for "/home/xavier/.config/lvim/config.lua":
E5108: Error executing lua /home/xavier/.local/share/lunarvim/lvim/lua/utils/init.lua:99: Vim(lua):E5108: Error executing lua /home/xavier/.config/lvim/plugin/packer_compiled.lua:657: atte
mpt to index a nil value
Error detected while processing BufWritePost Autocommands for "*":
E5108: Error executing lua /home/xavier/.config/lvim/plugin/packer_compiled.lua:657: attempt to index a nil value
``` 

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Tastyep** [comment]
Can you try to:
1. remove "nvim-telescope/telescope-packer.nvim" from your plugins
2. run `:LvimCacheReset`
3. `:PackerSync`
4. Add back "nvim-telescope/telescope-packer.nvim"
5. `:PackerInstall`

The `after` attribute from Packer is buggy, that could be the cause

**Comment by younger-1** [comment]
> 
> 
> Can you try to:
> 
>     1. remove "nvim-telescope/telescope-packer.nvim" from your plugins
> 
>     2. run `:LvimCacheReset`
> 
>     3. `:PackerSync`
> 
>     4. Add back "nvim-telescope/telescope-packer.nvim"
> 
>     5. `:PackerInstall`
> 
> 
> The `after` attribute from Packer is buggy, that could be the cause

Ok, I will try

**Comment by younger-1** [comment]
> 
> 
> Can you try to:
> 
>     1. remove "nvim-telescope/telescope-packer.nvim" from your plugins
> 
>     2. run `:LvimCacheReset`
> 
>     3. `:PackerSync`
> 
>     4. Add back "nvim-telescope/telescope-packer.nvim"
> 
>     5. `:PackerInstall`
> 
> 
> The `after` attribute from Packer is buggy, that could be the cause

@Tastyep  I am sorry. I try so many times. It is still buggy with behavier I have mentioned above... 😭

**Comment by Tastyep** [comment]
Can you confirm that the nil value is `require("telescope")` ?

**Comment by younger-1** [comment]
> 
> 
> Can you confirm that the nil value is `require("telescope")` ?

@Tastyep This is one of the outputs of `:lua print(vim.inspect(require("telescope")))` with `nvim-telescope/telescope-packer.nvim` enabled(the bad thing of the situation is none of the plugin loaded),  the another output of `:lua print(vim.inspect(require("telescope")))` is the same of that without `nvim-telescope/telescope-packer.nvim` enabled (the bad thing of this situation is that `Relevant log output` above has mentioned.
```log
{
  __format_setup_keys = <function 1>,
  extensions = {
    <metatable> = {
      __index = <function 2>
    }
  },
  load_extension = <function 3>,
  register_extension = <function 4>,
  setup = <function 5>
}
````

**Comment by Tastyep** [comment]
I tried installing it, it works. The plugin in itself doesn't seem to work, but that's not my problem.
Are you based on master or rolling ?

**Comment by younger-1** [comment]
> 
> 
> I tried installing it, it works. The plugin in itself doesn't seem to work, but that's not my problem.
> Are you based on master or rolling ?

I am in latest rolling branch.

**Comment by younger-1** [comment]
After doing `:LvimCacheClear`, does `:PackerClean` behave normally for you ? Are editing and saving `config.lua` behaving normally?

**Comment by Tastyep** [comment]
Can you try removing the `after` parameter ? As far as I know, it doesn't even work correctly.
Then try again [this](https://github.com/LunarVim/LunarVim/issues/1610#issuecomment-927089399)

**Comment by younger-1** [comment]
I'm sure `after` is not there.

**Comment by Tastyep** [comment]
> I'm sure `after` is not there.

This line ?
after = "telescope.nvim", -- or module = "telescope.nvim" or without lazyload all will casue problem

**Comment by younger-1** [comment]
Yes, without this line.

**Comment by younger-1** [comment]
Solved!

This is caused by `telescope-packer` and the problem can be fixed through this [pull request](https://github.com/nvim-telescope/telescope-packer.nvim/pull/7) which simply remove [this buggy line](https://github.com/nvim-telescope/telescope-packer.nvim/blob/9d5f488ee196fc6cbe08f17a357148a13805ea90/lua/telescope/_extensions/packer/plugin_list.lua#L6).

As the code hasn't be merged yet, if someone want to use the `telescope-packer`, you can have a look at [my branch](https://github.com/younger-1/telescope-packer.nvim) which merged `open_readme_on_enter` pull request from [@ikerurda](https://github.com/nvim-telescope/telescope-packer.nvim/pull/6)

**Comment by redigaffi** [comment]
same for me @aadityasinha-dotcom

**Comment by brneor** [comment]
@aadityasinha-dotcom @redigaffi depending on your version of Lunarvim, Packer is not used anymore.
