### ISSUE TITLE
[Bug]: "Not an editor command: NvimTreeToggle"

### ISSUE THREAD

**Issue by schwartx** [LunarVim/LunarVim#1618]
### Problem description

Not an editor command: NvimTreeToggle

https://github.com/kyazdani42/nvim-tree.lua/commit/a864b80bafeba6ea17d1a55e4c6f5e73f189f6bb
kyazdani42/nvim-tree.lua lastest commit

i have to run "require'nvim-tree'.setup()" to fix it

### LunarVim version

latest rolling

### Neovim version (>= 0.5)

NVIM v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
just fixed it

**Comment by likern** [comment]
@abzcoding I see this error again with `:PackerSync`

**Comment by likern** [comment]
May be LunarVim will support official versions of plugins (fixed latest versions), so no accident breaking changes will happen. Or at least have a list of versions which are expected to work?

**Comment by abzcoding** [comment]
> May be LunarVim will support official versions of plugins (fixed latest versions), so no accident breaking changes will happen. Or at least have a list of versions which are expected to work?

LunarVim is supporting the latest versions of the plugins, also if it still occurs please do a `:LvimCacheReset` to make sure nothing is cached

**Comment by abzcoding** [comment]
> @abzcoding Doesn't work after `:PackerSync` and `:LvimCacheReset`
> 
> ![Снимок экрана от 2021-09-30 18-03-16](https://user-images.githubusercontent.com/842306/135481113-8ba763c2-0967-41f2-9dd8-effb911de9a0.png)

are you on `rolling` or `master` branch?
```sh
git -C ~/.local/share/lunarvim/lvim status
```

**Comment by abzcoding** [comment]
as you can see it works just fine in the latest lunarvim and `nvimtree`
<img width="722" alt="Screen Shot 2021-09-30 at 6 37 03 PM" src="https://user-images.githubusercontent.com/10992695/135481606-c37e09ca-9b91-46a6-892c-e5094b87d55e.png">
<img width="861" alt="Screen Shot 2021-09-30 at 6 36 06 PM" src="https://user-images.githubusercontent.com/10992695/135481411-7bf81d61-9f57-4c2d-9f4c-4d9baa6faf77.png">

**Comment by likern** [comment]
@abzcoding Thank you. After updating `LunarVim` it started working without problems.

**Comment by eo1989** [comment]
Nope, still has issues. Even after updating to Nvim 0.7-dev, after packer sync, lvimcachereset, lvimupdate, lvimreload. -_-.
