### ISSUE TITLE
[Bug]: FloatBoder typo

### ISSUE THREAD

**Issue by chase** [LunarVim/LunarVim#1622]
### Problem description

https://github.com/LunarVim/LunarVim/blob/rolling/lua/onedarker/highlights.lua#L20

Should be `FloatBorder` not `FloatBoder`

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
https://github.com/LunarVim/LunarVim/commit/464f092ada7b6e54f5ad65aea0ae3c1b55f618f4
