### ISSUE TITLE
[Bug]: Instalation error even with all the  Prerequisites stated in the docs

### ISSUE THREAD

**Issue by mrHola21** [LunarVim/LunarVim#1633]
### Problem description

Shell  = fish 
Terminal = alacritty
OS = Arch Linux 
Kernel Type = Mainline kernel 
Kernel Version = 5.14.7-arch1-1
Window Manager = Openbox

As I use fish I typed (notice the `| psub` at the end) `bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh | psub)`  and it gave the same error as bash.

To switch to bash I typed `bash` in the fish shell and ran `bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`

### LunarVim version

I am trying to install the latest stable release

### Neovim version (>= 0.5)

`NVIM v0.5.0` `Build type: Release` `LuaJIT 2.0.5`

### Relevant log output

```shell
into '/home/gautam/.local/share/lunarvim/site/pack/packer/start/packer.nvim'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 45 (delta 1), reused 27 (delta 1), pack-reused 0
Receiving objects: 100% (45/45), 71.16 KiB | 137.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
--------------------------------------------------------------------------------
Cloning LunarVim configuration
Cloning into '/home/gautam/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 206, done.
remote: Counting objects: 100% (206/206), done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 206 (delta 2), reused 127 (delta 0), pack-reused 0
Receiving objects: 100% (206/206), 1.63 MiB | 2.12 MiB/s, done.
Resolving deltas: 100% (2/2), done.
Installing LunarVim shim
Preparing Packer setup
Error detected while processing /home/gautam/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: /home/gautam/.local/share/lunarvim/lvim/init.lua:6: module 'bootstrap' not found:
	no field package.preload['bootstrap']
	no file './bootstrap.lua'
	no file '/usr/share/luajit-2.0.5/bootstrap.lua'
	no file '/usr/local/share/lua/5.1/bootstrap.lua'
	no file '/usr/local/share/lua/5.1/bootstrap/init.lua'
	no file '/usr/share/lua/5.1/bootstrap.lua'
	no file '/usr/share/lua/5.1/bootstrap/init.lua'
	no file './bootstrap.so'
	no file '/usr/local/lib/lua/5.1/bootstrap.so'
	no file '/usr/lib/lua/5.1/bootstrap.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'Error detected while processing command line:
E492: Not an editor command: PackerSync
Press ENTER or type command to continue
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Can you try the steps listed under known issues please:  https://github.com/LunarVim/LunarVim#known-issues

**Comment by mrHola21** [comment]
I did  
for this command `lvim +LvimCacheReset` it just said `Unknown command: lvim` (as lunar vim could not be installed)
`LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-$HOME/.local/share/lunarvim}"` this ran succesfully
and `bash "$LUNARVIM_RUNTIME_DIR/utils/installer/install_bin.sh"` gave an error `bash: /utils/installer/install_bin.sh: No such file or directory`

**Comment by BrightXiaoHan** [comment]
I encountered the same issue

**Comment by mrHola21** [comment]
@rebuilt I cloned the repo in the same location as u said using https .  And it says `E282: Cannot read from "/home/gautam/.local/share/lunarvim/lvim/init.lua"` . 

I don't think the error is because of permissions as I have the appropriate permissions. 
![ScreenShot](https://user-images.githubusercontent.com/66013271/135049736-2a3c9832-beda-4c73-9ffa-1311211c2586.png)

**Comment by rebuilt** [comment]
Does that file exist on your system?   If it does exist, what are the permissions on that file?

If it doesn't exist it means the installer did not reach the stage of cloning the lunarvim repo

**Comment by mrHola21** [comment]
Yeah my bad . so how do I get that file in my system ? As the install.sh was also not installing it , I tried it after installing packer . Or should I build from source ?
![ScreenShot](https://user-images.githubusercontent.com/66013271/135063159-ade2db3c-7b89-41f3-a87a-af5747b109a4.png)
.

**Comment by rebuilt** [comment]
Try cloning it manually `git clone https://github.com/LunarVim/LunarVim.git ~/.local/share/lunarvim/lvim`

This should have been done by the installer.  I'm not sure why it didn't clone the repo. From your installer outpu, it looks like the installer didn't throw any errors when cloning the repo.  
```
Cloning LunarVim configuration
Cloning into '/home/gautam/.local/share/lunarvim/lvim'...
```

**Comment by mrHola21** [comment]
Yeah Manually cloning Packer and lunarvim did the trick .
