### ISSUE TITLE
[Bug]: LspInstall bug

### ISSUE THREAD

**Issue by angryheng** [LunarVim/LunarVim#1636]
### Problem description

LspInstall lua or css or html error

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6.0

### Screenshots

![bug](https://user-images.githubusercontent.com/28853495/135013785-d39bcf34-f538-4675-be86-64f5d06c4d46.gif)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
can you share contents of `:messages`
and also your nvim version using `nvim -vv`
and if there are any errors in `~/.cache/nvim/lsp.log`
<img width="827" alt="Screen Shot 2021-09-28 at 7 04 39 PM" src="https://user-images.githubusercontent.com/10992695/135119010-3c4d41ca-5a93-4c00-8570-eaee9d2ce105.png">

**Comment by afridley** [comment]
@abzcoding seems like something with barbar I wonder if you update if you will get it too here is a screenshot of the full error. Maybe something with a recent update of barbar 
<img width="1440" alt="Screen Shot 2021-09-28 at 2 09 43 PM" src="https://user-images.githubusercontent.com/34749972/135150680-10386fc2-0f53-4840-81cf-4fd919b00937.png">

**Comment by abzcoding** [comment]
it might be, bcz i'm not using barbar https://github.com/abzcoding/lvim/blob/5717af1b67fac9400270bafe84b260f28e79e23c/lua/user/builtin.lua#L6

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by abzcoding** [comment]
can you guys test if pinning barbar to any if these commits fixes the issue or not
<img width="1335" alt="Screen Shot 2021-09-28 at 11 17 51 PM" src="https://user-images.githubusercontent.com/10992695/135155733-60f7c212-71fd-46e9-ae98-02a477c54f7e.png">

**Comment by forestofrain** [comment]
I modified [plugins.lua](https://github.com/LunarVim/LunarVim/blob/rolling/lua/plugins.lua#L141) and had to pin to the Aug 16 commit. It appears that commit [d5f3b2d](https://github.com/romgrk/barbar.nvim/commit/d5f3b2dd27d20f74a7dfd4f602afac59310b2c94) causes this issue. If you don't kill the process quickly, you may find your RAM usage as gone through the roof. 

Not being familiar with Lua or this project, is there a local `config.lua` way to pin the built in packages or override?

**Comment by abzcoding** [comment]
> I modified [plugins.lua](https://github.com/LunarVim/LunarVim/blob/rolling/lua/plugins.lua#L141) and had to pin to the Aug 16 commit. It appears that commit [d5f3b2d](https://github.com/romgrk/barbar.nvim/commit/d5f3b2dd27d20f74a7dfd4f602afac59310b2c94) causes this issue. If you don't kill the process quickly, you may find your RAM usage as gone through the roof.
> 
> Not being familiar with Lua or this project, is there a local `config.lua` way to pin the built in packages or override?

thank you for testing it, yes i'm about to pin it right now

**Comment by abzcoding** [comment]
i just pinned the barbar version to a previous one, please do a `:PackerSync` to install the older version
and just to be sure run `:LvimCacheReset` afterwards

**Comment by chase** [comment]
@abzcoding Made a PR to fix this upstream, that should prevent this from occurring

**Comment by abzcoding** [comment]
@chase thank you
