### ISSUE TITLE
[Bug]: can't setup `json` language server for `jsonc` filetype

### ISSUE THREAD

**Issue by younger-1** [LunarVim/LunarVim#1639]
### Problem description

I creat a `ftplugin` lua file in `~/.config/lvim/ftplugin/jsonc.lua` with the following content:

```lua
require("lsp").setup "json"
```

But `jsonls` is not activated after opening a `jsonc` file.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
by default jsonls works only on json files, you can either change that or create a ftdetect and make it think json=jsonc

```lua
lvim.lang.json.lsp.setup.filetypes = { "json", "jsonc" }
``
<img width="652" alt="Screen Shot 2021-09-29 at 9 33 47 AM" src="https://user-images.githubusercontent.com/10992695/135211979-13cd759a-a446-457c-8d6d-7d318ff813bc.png">

**Comment by younger-1** [comment]
Thanks for your reply!
