### ISSUE TITLE
[Bug]: LspInstall bug

### ISSUE THREAD

**Issue by angryheng** [LunarVim/LunarVim#1640]
### Problem description

I have installed HTML services through LSPinstall HTML, but still prompts LS Inactive

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6.0

### Screenshots

<img width="1063" alt="bug" src="https://user-images.githubusercontent.com/28853495/135198059-eb1602ce-d870-4497-9ea8-e291811e3aa9.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
can you run `:LvimInfo` on that file?

**Comment by angryheng** [comment]
@abzcodin
<img width="1051" alt="bug" src="https://user-images.githubusercontent.com/28853495/135242265-86dfd22c-5a4a-4ee7-8406-634d7112cf02.png">
g

**Comment by angryheng** [comment]
@abzcoding 

<img width="1051" alt="bug" src="https://user-images.githubusercontent.com/28853495/135246807-b015875c-1984-41ef-981e-3a3c4e8f4f6f.png">

**Comment by abzcoding** [comment]
also please check. ~/.cache/nvim/lsp.log for errors

**Comment by abzcoding** [comment]
btw can you test what happens if you open an html file in a git managed folder?

**Comment by abzcoding** [comment]
we just completely changed the lang server stuff using https://github.com/williamboman/nvim-lsp-installer
feel free to reopen this if the issues still persist
