### ISSUE TITLE
[Keymap]:selecting a column in lvim.

### ISSUE THREAD

**Issue by maroozm** [LunarVim/LunarVim#1641]
### Problem description

 I cannot figure out the keybinding for selecting a column in lvim. This might be not a good place to ask but i don't see another way. Thanks

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.6.0-dev

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
> CTRL-V enters block selection mode (allowing you to select rectangular blocks of text).

if you want to select a whole column :
1. you can hit `gg` to get to the first line
2. move around to the column you like
3. then you can hit `ctrl-v` to enter block selection mode
4. and at last pressing `G` to select that whole column

basically exactly the same as a normal neovim/vim
