### ISSUE TITLE
[Bug]: LspInstall json

### ISSUE THREAD

**Issue by likern** [LunarVim/LunarVim#1643]
### Problem description

1. Run `:LspInstall json` fails

![Снимок экрана от 2021-09-29 19-23-57](https://user-images.githubusercontent.com/842306/135309962-e391bdc3-7b1b-4f99-b116-ef1e00e345d3.png)

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [ ] The programs specified by the config are installed

### LunarVim version

rolling

### Neovim version (>= 0.5)

v0.6.0-dev+357-g96614f84a

### Relevant log output

```shell
[ERROR][2021-09-29 19:29:02] .../vim/lsp/rpc.lua:459	"rpc"	"node"	"stderr"	"/home/me/.local/share/nvim/lspinstall/json/vscode-json/json-language-features/server/dist/node/jsonServerMain.js:1\n(()=>{var e={2775:(e,t,n)=>{(()=>{var e={46:e=>{\"use strict\";function t(){}function n(e,t){const r=n.spread(e,t),o=r.then((e=>e[0]));return o.cancel=r.cancel,o}!function(e){e.spread=function(e,n){let r=null;const o=new Promise(((i,s)=>{function a(){e.removeListener(n,c),e.removeListener(\"error\",u),o.cancel=t}function c(...e){a(),i(e)}function u(e){a(),s(e)}r=a,e.on(n,c),e.on(\"error\",u)}));if(!r)throw new TypeError(\"Could not get `cancel()` function\");return o.cancel=r,o}}(n||(n={})),e.exports=n},54:function(e,t,n){\"use strict\";var r=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};const o=n(614),i=r(n(374)),s=r(n(304)),a=i.default(\"agent-base\");function c(){const{stack:e}=new Error;return\"string\"==typeof e&&e.split(\"\\n\").some((e=>-1!==e.indexOf(\"(https.js:\")||-1!==e.indexOf(\"node:https:\")))}function u(e,t){return new u.Agent(e,t)}!function(e){class t extends o.Event\n\nSyntaxError: Unexpected token '.'\n    at Module._compile (internal/modules/cjs/loader.js:891:18)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)\n    at Module.load (internal/modules/cjs/loader.js:811:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:723:14)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)\n    at internal/main/run_main_module.js:17:11\n"
```

### Screenshots

![Снимок экрана от 2021-09-29 19-23-57](https://user-images.githubusercontent.com/842306/135310060-13ea2089-6745-4e4a-8b29-d827345da3b4.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
there was a bug with barbar that got fixed, can you do a `:PackerSync` and try again?

**Comment by chase** [comment]
This doesn't seem to be related, I'm not sure what `vim.lua` is actually

**Comment by likern** [comment]
I think I mixed two related errors. `:PackerSync` did really help with installation. `json` successfully was installed.
![Снимок экрана от 2021-09-29 23-13-44](https://user-images.githubusercontent.com/842306/135342212-5e49283b-8d3e-474c-94bb-a0c115a61213.png)

**Comment by abzcoding** [comment]
glad it worked

**Comment by likern** [comment]
However it didn't help making `json` working. When I open simple `package.json` I see this error.
![Снимок экрана от 2021-09-29 23-16-34](https://user-images.githubusercontent.com/842306/135342345-a7c3944b-c2dd-47eb-bf0e-2c4ae189500b.png)

And in `~/.cache/nvim/lsp.log`

```bash
[ERROR][2021-09-29 23:16:30] .../vim/lsp/rpc.lua:459	"rpc"	"node"	"stderr"	"/home/me/.local/share/nvim/lspinstall/json/vscode-json/json-language-features/server/dist/node/jsonServerMain.js:1\n(()=>{var e={2775:(e,t,n)=>{(()=>{var e={46:e=>{\"use strict\";function t(){}function n(e,t){const r=n.spread(e,t),o=r.then((e=>e[0]));return o.cancel=r.cancel,o}!function(e){e.spread=function(e,n){let r=null;const o=new Promise(((i,s)=>{function a(){e.removeListener(n,c),e.removeListener(\"error\",u),o.cancel=t}function c(...e){a(),i(e)}function u(e){a(),s(e)}r=a,e.on(n,c),e.on(\"error\",u)}));if(!r)throw new TypeError(\"Could not get `cancel()` function\");return o.cancel=r,o}}(n||(n={})),e.exports=n},54:function(e,t,n){\"use strict\";var r=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};const o=n(614),i=r(n(374)),s=r(n(304)),a=i.default(\"agent-base\");function c(){const{stack:e}=new Error;return\"string\"==typeof e&&e.split(\"\\n\").some((e=>-1!==e.indexOf(\"(https.js:\")||-1!==e.indexOf(\"node:https:\")))}function u(e,t){return new u.Agent(e,t)}!function(e){class t extends o.Event\n\nSyntaxError: Unexpected token '.'\n    at Module._compile (internal/modules/cjs/loader.js:891:18)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)\n    at Module.load (internal/modules/cjs/loader.js:811:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:723:14)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)\n    at internal/main/run_main_module.js:17:11\n"
```
![Снимок экрана от 2021-09-29 23-16-48](https://user-images.githubusercontent.com/842306/135342502-3a8a0190-698e-4d07-8d57-83075af79701.png)

**Comment by abzcoding** [comment]
make sure your node version is greater than 14

**Comment by likern** [comment]
@abzcoding Have I missed this requirement in documentation? My version is indeed `12.15.0`. I'll check with newer versions.

**Comment by abzcoding** [comment]
> @abzcoding Have I missed this requirement in documentation? My version is indeed `12.15.0`. I'll check with newer versions.

oh someone else had the same issue on discord, so I thought it might help you as well, I don't think its part of our dependencies but rather the lang server's dependency

**Comment by likern** [comment]
I can confirm that upgrading to latest Node.js version `16.10.0` indeed **solved the problem**. I think this needs to be mentioned in documentation.

While VS Code worked with old node.js version, I think they package their own version into VS Code.

**Comment by likern** [comment]
@abzcoding A little bit outside question. Could you clarify the relation between LSP and `nvim-ls` in terms of json formatting.

Is this LSP json gives formatting which gives VS Code *by default*? How is this related to my config option
```js
lvim.lang.json.formatters = { { exe = "prettier" } }

```
I thought that json formatting should work without LSP, but it didn't.

**Comment by abzcoding** [comment]
sure thing basically some language servers don't have builtin formatting which you can check by running `:LvimInfo` command. 
so we use `null-ls` which uses Neovim as a language server to inject LSP diagnostics, code actions, and more via Lua.
<img width="882" alt="Screen Shot 2021-09-30 at 12 24 58 AM" src="https://user-images.githubusercontent.com/10992695/135347119-3f86a025-af03-4b16-8353-470c1f782c67.png">

**Comment by abzcoding** [comment]
clang for example does support native formatting, so you won't need an external one
<img width="859" alt="Screen Shot 2021-09-30 at 12 25 46 AM" src="https://user-images.githubusercontent.com/10992695/135347180-88bf40ed-3440-4ffe-99ea-89d3fefd6074.png">

**Comment by likern** [comment]
But if `null-ls` is it's own LSP and I configured `prettier` to format json files, why _it didn't work untill I installed `jsonls` LSP server_? I thought they are not coupled, as I understand this.

And only after installing `jsonls` I see `prettier` in list. Before it showed nothing.
![Снимок экрана от 2021-09-30 00-17-27](https://user-images.githubusercontent.com/842306/135349794-037374e3-bb01-4461-965c-283a2e342cb8.png)

**Comment by abzcoding** [comment]
`null-ls` is not a lang server, Neovim doesn't provide a way for non-LSP sources to hook into its LSP client. null-ls is an attempt to bridge that gap
