### ISSUE TITLE
[Bug]: /usr/share/nvim/runtime/lua/vim/uri.lua:116: attempt to index local 'uri' (a nil value)

### ISSUE THREAD

**Issue by Sabitra** [LunarVim/LunarVim#1646]
### Problem description

When in insert mode, and typing, this message keeps popping up hindering typing. 
I got rid of it by commenting out the uri_to_bufnr function call in handler.lua and the uri.lua file. 

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5

### Relevant log output

```shell
OK to all
```

### Screenshots

No screenshots as I first sorted it out then felt relevant to report as bug.  To reproduce the issue I can un-comment the 3 lines.

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Make sure you've installed a release from this page:  https://github.com/neovim/neovim/releases

Known working versions are the a5ac2f4 build and neovim HEAD if you're compiling.  There are some issues with versions in between.

https://github.com/LunarVim/LunarVim/issues/1575
https://github.com/LunarVim/LunarVim/issues/1562
https://github.com/LunarVim/LunarVim/issues/1516
https://github.com/LunarVim/LunarVim/issues/1499
https://github.com/LunarVim/LunarVim/issues/1484
https://github.com/LunarVim/LunarVim/issues/1484

**Comment by Sabitra** [comment]
thanks man. that helped me. However just commenting out the function call in config files worked better.
