### ISSUE TITLE
[Feature]: Unbind which-key

### ISSUE THREAD

**Issue by haininhhoang94** [LunarVim/LunarVim#1650]
### Feature motivation

When I tried to overwrite default which-key in lunarvim it is not working (by using config.lua)
![image](https://user-images.githubusercontent.com/34930708/135569883-ec7f0b55-15bb-4abd-8b94-ea7398498a40.png)

### Describe the expected solution

overwrite default which-key in config.lua

### Describe the alternatives you've considered

edit the lunarvim built in config help, but it may make it difficult to update in the future

**Comment by rebuilt** [comment]
Did you close and reopen neovim after making changes?

**Comment by abzcoding** [comment]
instead of `mappings["ld"]` can you test `mappings["l"]["d"]` ?

**Comment by haininhhoang94** [comment]
nevermind it seems that i need to completely reopen neovim (i kept one or 2 instance in another tmux window).
closed!
