### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rlopeznegrete** [LunarVim/LunarVim#1654]
### Problem description

Hi all,

I'm either not setting up the lang.c.formatter correctly or it is not configured properly... I'm trying to reformat some c code using '=G' as per usual, but the indentation and location of curly brackets after is not correct. Please verify if this is not a bug, or correct my settings...

original code (note indentation of `#ifdef` and location of curly brackets in the if
![image](https://user-images.githubusercontent.com/1289343/135642654-e8e15717-58bc-411c-be68-b47344ebf396.png)

expected indentation
![image](https://user-images.githubusercontent.com/1289343/135642563-25bac906-084c-4fc1-9dea-a242793ddade.png)

result from =G. Again notice the curly brackets did not move, and that the `#ifdef`, `#endif` macro section all got justified...
![image](https://user-images.githubusercontent.com/1289343/135642715-de90125c-df52-4cbf-a815-546298578dd9.png)

my current settings are in config.lua
![image](https://user-images.githubusercontent.com/1289343/135642788-bcdc20cf-92e8-4b3e-93f0-41b235124dd7.png)

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6-dev

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Uzaaft** [comment]
Do you have clang_format in your path? 
If so, can you run the formatter directly on the file from your command line?

**Comment by Uzaaft** [comment]
Also, have you run `:PackerCompile` after adding the formatter?

**Comment by rlopeznegrete** [comment]
Hi Uzaaft,

Yes, I do have clangd and clang-format in my path. I had not run `:PackerCompile` before, but even after doing that it still formats the code incorrectly. Question: to execute the formatting via `clangd` do I need to use =G or some other command?

Thank you,
 Rodrigo

**Comment by abzcoding** [comment]
> > Also, have you run `:PackerCompile` after adding the formatter?
> 
> Hi Uzaaft,
> 
> Yes, I do have `clangd` and `clang-format` in my path. I had not run `:PackerCompile` before, but even after doing that it still formats the code incorrectly. Question: to execute the formatting via `clangd` do I need to use =G or some other command?
> 
> Thank you, Rodrigo

to format using the language server, first you need to install it using `:LspInstall cpp` and then use `<leader>lf` for formatting or add this to your config.lua to format automatically on save
```lua
lvim.format_on_save = true
```

**Comment by abzcoding** [comment]
also use `:LvimInfo` when in doubt

**Comment by rlopeznegrete** [comment]
Hi,
I know there's an issue with my lack of understanding on how lunarvim works. However, I did follow all the steps described in the comments above, and still I don't see the text getting properly formatted. Is there a way for me to log the outputs from clang? or a different way to debug the issue?

thank you

**Comment by abzcoding** [comment]
> Hi, I know there's an issue with my lack of understanding on how lunarvim works. However, I did follow all the steps described in the comments above, and still I don't see the text getting properly formatted. Is there a way for me to log the outputs from clang? or a different way to debug the issue?
> 
> thank you

you can check `~/.cache/nvim/lsp.log` for possible error logs

**Comment by rlopeznegrete** [comment]
one last question, how do I change the formatting style for the formatter? I am using clang, and prefer the 'gnu' style for coding.

**Comment by abzcoding** [comment]
> one last question, how do I change the formatting style for the formatter? I am using clang, and prefer the 'gnu' style for coding.

using `.clang-format` file https://clang.llvm.org/docs/ClangFormatStyleOptions.html
for example https://github.com/gcc-mirror/gcc/blob/master/contrib/clang-format

**Comment by rlopeznegrete** [comment]
> > one last question, how do I change the formatting style for the formatter? I am using clang, and prefer the 'gnu' style for coding.
> 
> using `.clang-format` file in the root of your project https://clang.llvm.org/docs/ClangFormatStyleOptions.html for example https://github.com/gcc-mirror/gcc/blob/master/contrib/clang-format

Awesome! Thanks that cleared my questions and fixed the issue!
