### ISSUE TITLE
[Feature]: Add default plugin on/off switch to main config

### ISSUE THREAD

**Issue by signed-log** [LunarVim/LunarVim#1658]
### Feature motivation

Snippets are a pain when coding `python` (at the end of each line, it proposes to create a new function, which easily creates a huge mess if you're doing `Enter` without doing right arrow).  
I identified (thanks to the Discord), that the plugin responsible for that mess is `friendly-snippets`, but, contrary to core plugins, it's impossible to disable default plugins without digging in low-level config and manually setting that plugin off  
There is a switch to disable `cope` plugin, which is the variable that also control `friendly-snippets`, but I don't want to give the whole completion stack up

### Describe the expected solution

Add config variables for every default plugin, like for core ones, something like like `lunarvim.default.<plugin name>.disable`, to selectively disable default those

### Describe the alternatives you've considered

Make a system of drop-in for low-level config that would be outside of the main git repo so that it isn't overriden by updates, however idk if that's a thing possible in lua

**Comment by abzcoding** [comment]
to be clear, most of them have this already, but not friendly-snippets 😅 

for example:
```lua
lvim.builtin.project.active = false -- will disable the project.nvim plugin
```
<img width="420" alt="Screen Shot 2021-10-02 at 11 59 37 AM" src="https://user-images.githubusercontent.com/10992695/135709312-576b6de2-667e-4abd-8e47-a332758fc471.png">

**Comment by Stig124** [comment]
PR is underway

**Comment by Stig124** [comment]
I see all points, but having a kill-switch for every plugin is better IMO

**Comment by Stig124** [comment]
Sure, there is plugins that are needed

**Comment by abzcoding** [comment]
should be fixed via https://github.com/LunarVim/LunarVim/pull/2546
