### ISSUE TITLE
[Bug]: [NvimTree] following options are now set in the setup 

### ISSUE THREAD

**Issue by Moelf** [LunarVim/LunarVim#1661]
### Problem description

after the latest update of LvimUpdate:
```
[NvimTree] following options are now set in the setup (:help nvim-tree.setup): nvim_tree_disable_netrw | nvim_tree_hijack_netrw | nv
im_tree_auto_open | nvim_tree_auto_close | nvim_tree_tab_open | nvim_tree_update_cwd | nvim_tree_follow | nvim_tree_lsp_diagnostics 
| nvim_tree_bindings
```

### LunarVim version

git

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+198-g81f4de08b

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
these options have been migrated already, can you run a `:PackerSync`?
<img width="258" alt="Screen Shot 2021-10-03 at 3 15 24 AM" src="https://user-images.githubusercontent.com/10992695/135734590-22e8298c-c535-4d78-ba17-3d3cd7e70376.png">
also make sure you are on `rolling` branch
