### ISSUE TITLE
[Bug]: Running `nvim` on Windows after installing LunarVim adds a `~/` directory in the current path

### ISSUE THREAD

**Issue by Antyos** [LunarVim/LunarVim#1664]
### Problem description

I don't know if this is intended behavior or not, but the issue is as the title describes: after running the new LunarVim PowerShell installation script and getting `lvim` working, running the regular `nvim` command in the terminal will create a `~/` folder in the directory `nvim` was started from.

Running `nvim` from my user directory will create the following folder structure:

```
C:\USERS\ANDREW\~
└───.local
    └───share
        └───lunarvim
            └───site
                └───pack
                    └───packer
                        └───start
                            └───packer.nvim
                                ├───.github
                                │   ├───ISSUE_TEMPLATE
                                │   └───workflows
                                ├───doc
                                ├───lua
                                │   └───packer
                                │       └───plugin_types
                                └───tests
```

> Note that this does not occur when running `lvim`.

I suspect this is related to the default `init.lua` located in my `\AppData\Local\nvim\` folder which loads a handful of Packer plugins of its own. If I remove the default `init.lua`, this issue does not occur.

#### Other things of note

- I don't know if it assumed that there should never be a need to call `nvim` after getting LunarVim installed. The reason I have other programs that still use NeoVim's executable without running through LunarVim. This problem effects them specifically because those other programs start adding `~\` folders in their installation directories.

- The file `C:\Users\Andrew\AppData\Local\nvim\lua\plugin-loader.lua` has nothing to do with LunarVim's `plugin-loader.lua`. I structured my `nvim\lua\` directory similarly to LunarVim's because I really like how it does things. Please don't be confused by this.

### LunarVim version

Commit: f61c4ac (Latest from lang-refactor branch)

### Neovim version (>= 0.5)

v0.5.0

### Relevant log output

```shell
Error detected while processing C:\Users\Andrew\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: C:\Users\Andrew\AppData\Local\nvim\lua\plugin-loader.lua:7: Vim(packadd):E919: Directory not found in 'packpath': "pack/*/opt/packer.nvim"
Error detected while processing C:\Users\Andrew\AppData\Local\nvim\plugin\packer_compiled.lua:
E5113: Error while calling lua chunk: ...ers\Andrew\AppData\Local\nvim\plugin\packer_compiled.lua:8: Vim(packadd):E919:
Directory not found in 'packpath': "pack/*/opt/packer.nvim"
Press ENTER or type command to continue
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
That's definitely not intentional 😄 

Can you pull the updates, now on rolling, and test again? You can also do a complete re-install if you'd like.

**Comment by Antyos** [comment]
I tried running `:LvimUpdate` but it failed and said to look at the log, but I couldn't find the log. I opted to just delete all the LunarVim files on my computer and reinstall with the updated PowerShell script. I figure any issues I was having are likely related to the recent addition of Windows compatibility and would be resolved with a clean install.

I had some issues with things not automatically installing, but I think that's more related to #1663.

Even after updating to `rolling`, I'm still getting the `~\` issue.

**Comment by kylo252** [comment]
> I tried running `:LvimUpdate` but it failed and said to look at the log, but I couldn't find the log. I opted to just delete all the LunarVim files on my computer and reinstall with the updated PowerShell script. I figure any issues I was having are likely related to the recent addition of Windows compatibility and would be resolved with a clean install.

I'm guessing it's because you had manually modified the repo, since I specifically made it so that `:LvimUpdate` will only perform a `git pull` if it's safe to do so. 

> I had some issues with things not automatically installing, but I think that's more related to #1663.

Yeah I also have some problems with a few parsers here and there.

> Even after updating to `rolling`, I'm still getting the `~\` issue.

I know it's annoying, but we need to try narrowing down when this is exactly happening. One thing that comes to mind is your `lvim.ps1` command might be outdated, so make sure its content matches with what we have here: https://github.com/LunarVim/LunarVim/blob/rolling/utils/bin/lvim.ps1

**Comment by Antyos** [comment]
The contents of my `lvim.ps1` match the one you linked.

Just because I'm not completely sure, are LunarVim's Packer plugins installed in a location that is isolated from vanilla NeoVim's installation? I figured they were, but I think (at least) one of them is being called by NeoVim's packer and assumes environment variables have been overridden by `lvim.ps1`.

**Comment by kylo252** [comment]
> Just because I'm not completely sure, are LunarVim's Packer plugins installed in a location that is isolated from vanilla NeoVim's installation? I figured they were, but I think (at least) one of them is being called by NeoVim's packer and assumes environment variables have been overridden by `lvim.ps1`.

It should be isolated see:
https://github.com/LunarVim/LunarVim/blob/5fe7b7ad4d6fa699ca9cc306a788d6485fc0ba8d/lua/plugin-loader.lua#L11-L12

which is passed from here:
https://github.com/LunarVim/LunarVim/blob/5fe7b7ad4d6fa699ca9cc306a788d6485fc0ba8d/lua/bootstrap.lua#L105-L107

One protentional issue is that if environment variables aren't really compatible with `os.getenv` for whatever reason. You can easily verify that though by printing their values.

**Comment by Antyos** [comment]
I figured out the issue and I'm dumb.

Remember how I said "Ignore the file `C:\Users\Andrew\AppData\Local\nvim\lua\plugin-loader.lua` because it has nothing to do with LunarVim"? Well it turns out that my `plugin-loader.lua`, which was based on an older version of LunarVim, was creating those strange directories. Oops!
