### ISSUE TITLE
Formatters/linters in .config/lvim/ftplugin not recognized

### ISSUE THREAD

**Issue by argapost** [LunarVim/LunarVim#1667]
### Problem description

I had my formatters/linters for each language inside .config/lvim/ftplugin/[language].lua, but after the refactor they are not recognized is this intended? should I move them in the config.lua?

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

Rolling

### Neovim version (>= 0.5)

NVIM v0.6.0-dev

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Can you share one of them?

**Comment by argapost** [comment]
.config/lvim/ftplugin/lua.lua
``` lua
lvim.lang.lua.linters = {
	{
		exe = "luacheck",
		args = {"--ignore", "112"},
	},
}

```

**Comment by abzcoding** [comment]
you can move them all in one place till the issue gets fixed, and explicitly require it
```lua
require("user.external_helpers").formatters()
require("user.external_helpers").linters()
```
<img width="821" alt="Screen Shot 2021-10-03 at 10 04 06 PM" src="https://user-images.githubusercontent.com/10992695/135766937-317c31f4-9790-489f-bce3-2a3f9b24a50b.png">

**Comment by argapost** [comment]
ok thanks!

**Comment by abzcoding** [comment]
> ok thanks!

you can use this syntax as well
```lua

local nls = require("null-ls")
nls.config {
    debounce = 150,
    save_after_format = false,
    sources = {
      nls.builtins.formatting.prettierd,
      nls.builtins.formatting.stylua,
      nls.builtins.formatting.goimports,
      nls.builtins.formatting.shfmt.with { extra_args = { "-i", "2", "-ci" } },
      nls.builtins.diagnostics.eslint_d,
      nls.builtins.diagnostics.shellcheck,
      nls.builtins.diagnostics.luacheck,
    },
}
```
