### ISSUE TITLE
Pyright server using a lot of resources 

### ISSUE THREAD

**Issue by Jasylum** [LunarVim/LunarVim#1668]
### Problem description

Opening a python file uses a lot of resources due to the node running in the background

![1633274789](https://user-images.githubusercontent.com/52153618/135761032-d6df3a0d-98f5-4d5f-a327-ba8ed9663ef4.png)

I have seen a pylsp.lua file inside the .local/share/lunarvim/site/pack/packer/start/nvim-lspconfig/lua/lspconfig folder. How can I use pylsp as the default language server instead of pyright for python?

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

NVIM v0.5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Are you on the latest rolling?

**Comment by Jasylum** [comment]
Yes I am

**Comment by kylo252** [comment]
You should check `lsp.log` to see what's going on. You can also access all the other logs by `<Leader>Ll`.

**Comment by Jasylum** [comment]
No I my question was whether I can use pylsp as a default language server for python in lunar vim or not. Using pyright just spikes up my cpu and it's kind of laggy using pyright. So using another lsp would be a better option.

**Comment by abzcoding** [comment]
> No I my question was whether I can use pylsp as a default language server for python in lunar vim or not. Using pyright just spikes up my cpu and it's kind of laggy using pyright. So using another lsp would be a better option.

as a temp solution to test it out, edit this file
```sh
~/.local/share/lunarvim/site/after/ftplugin/python.lua
```
and replace 
```lua
require("lsp.manager").setup("pyright")
```
with
```lua
require("lsp.manager").setup("pylsp")
```
then do `:LspInstall pylsp`
and see if that lang server is any better
