### ISSUE TITLE
[Feature]: Option to set formatting timeout duration

### ISSUE THREAD

**Issue by nalbury** [LunarVim/LunarVim#1684]
### Feature motivation

The terraform-ls language server has a built in formatter but its so slow that it times out on most files.

The null-ls formatter works, but forces the user to choose which formatter to use on each save if its used alongside the language server.

Using the language server's formatter by itself fails silently, but I noticed it logs:
```
[ ERROR ] 2021-10-04T06:11:47-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/Users/nalbury/.local/share/nvim/lsp_servers/terraform/terraform-ls/terraform-ls"	"stderr"	'2021/10/04 06:11:47 rpc_logger.go:45: Error for "textDocument/formatting" (ID 3): [-32800] error code -32800: Execution of "Format" canceled\n'
[ ERROR ] 2021-10-04T06:11:47-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/Users/nalbury/.local/share/nvim/lsp_servers/terraform/terraform-ls/terraform-ls"	"stderr"	"2021/10/04 06:11:47 server.go:248: Completed 1 requests [1.205960166s elapsed]\n"
```
This seems somewhat benign but I noticed the duration time (1.2s) and I believe the underlying function being called defaults to 1s(1000ms). 

I looked at the source [here](https://github.com/LunarVim/LunarVim/blob/d01ba08eaec1640ac2d038893525b3ba0af25813/lua/utils/init.lua#L61) and then tried disabling the auto format option, and manually configured a `BufWritePre` with much longer timeout:
```
lvim.autocommands.custom_groups = {
  { "BufWritePre", "*.tf", "lua vim.lsp.buf.formatting_sync(nil, 6000)" },
}
```
Which worked beautifully, but it looks like it would require a configuration for each filetype I want auto formatting on(?), so I was hoping for a way to set that globally.

### Describe the expected solution

Something like `lvim.format_on_save_timeout = 6000` would be sufficient for me. But I also would be happy with being able to enable the global option and override the BufWritePre cmd on a case by case basis ([at the moment they're only used if format on save is disabled](https://github.com/LunarVim/LunarVim/blob/d01ba08eaec1640ac2d038893525b3ba0af25813/lua/utils/init.lua#L76)). 

### Describe the alternatives you've considered

See above

### Additional context

Happy to try and figure this out and submit a MR, but I am admittedly only familiar with Lua by working with it in my various neovim configs. I'm also curious if you even think this is the right solution?

**Comment by abzcoding** [comment]
for the moment you can disable format_on_save and define it yourself anyway you want
```lua
    require("core.autocmds").define_augroups {
      autoformat = {
        {
          "BufWritePre",
          "*",
          ":silent lua vim.lsp.buf.formatting_sync()", -- change this
        },
      },
    }
```

**Comment by radeksimko** [comment]
Not to derail your original intention/topic about making timeout configurable - which seems like a good idea regardless.

For context - I am one of the maintainers of Terraform LS.

> The terraform-ls language server has a built in formatter but its so slow that it times out on most files.

Do you by any chance use tfenv to manage Terraform versions? There is a known issue delaying execution, see https://github.com/tfutils/tfenv/issues/196 If you use Terraform directly the formatting should be relatively quick.

If you use "standard" setup with "plain" Terraform and formatting is still slow, I would be very interested in some details such as size of the file being formatted and time it took: https://github.com/hashicorp/terraform-ls/issues/new

Naturally there will be a limit and I don't know of hand how big file would you need to cross the 1 sec timeout, but it certainly shouldn't be most files.
