### ISSUE TITLE
[Bug]: lsp get_namespace error after lunarvim is loaded and everytime i type

### ISSUE THREAD

**Issue by alexzanderr** [LunarVim/LunarVim#1688]
### Problem description

after opening lunarvim with a file i instantly get this error in vim command line:
```error
Error executing vim.schedule lua callback: ...exzander/.local/share/lunarvim/lvim/lua/l
sp/handlers.lua:33: attempt to call field 'get_namespace' (a nil value)
```
lsp is working, sometimes its not.
i just modified `config.lua` a little bit, added 2 external plugins, but i removed them. the syntax of the file is correct.
neovim version is downgraded.
this error occures everytime i use lsp: autocomplete, autopairs, typing (actions that require lsp)

checkhealth output is fine.

i tested in a not-git folder and in a git folder. same error.
lunarvim is updated. packer is synced to the max possible.

>  I restarted Neovim after running :LspInstall *

i have all the language server installed, so the above actions is redundant

> :messages

after running this, the above error is printed "1 million" times on the screen.

lsp info is just fine. like i said sometimes it isnt attached to the buffer (that error still occurs), sometimes its attached to the buffer (error still occurs)

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

NVIM v0.5.2-dev+15-g71950115e

### Neovim version (>= 0.5)

NVIM v0.5.2-dev+15-g71950115e

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
can you downgrade to `0.5.1 or 0.5.0 release` or upgrade to `0.6 head` ?

**Comment by alexzanderr** [comment]
it was `0.6` head, some days ago and i had similar issues with lunarvim.

i guess the solution is to go to `0.5.1` or `0.5`.

**Comment by abzcoding** [comment]
i'm on neovim 0.6 head without any issues
<img width="961" alt="Screen Shot 2021-10-05 at 3 56 56 PM" src="https://user-images.githubusercontent.com/10992695/136022195-8212274f-e8d3-4184-9ea8-a5ed2a92fbca.png">

**Comment by abzcoding** [comment]
> it was `0.6` head, some days ago and i had similar issues with lunarvim.
> 
> i guess the solution is to go to `0.5.1` or `0.5`.
> 
> i will try and let you know the results.
> 
> but, honestly, how do i get `0.5.1` or `0.5.0` ? because on neovim's github there are a few releases and the `release-0.5`, which i downloaded and compiled yesterday, is actually `0.5.2` not `0.5.0`
> 
> ![image](https://user-images.githubusercontent.com/54772464/136022331-2bfa896e-f996-4cb9-9a67-401cc84a71a6.png)

you can use our script probably https://github.com/LunarVim/LunarVim/blob/rolling/utils/installer/install-neovim-from-release
and change the `RELEASE_VER` variable

**Comment by alexzanderr** [comment]
okey i tested with `0.5.1` and with `v0.6.0-dev+402-g655e489e9` and its working, i can type with no problems and everything its working. but my LSP is inactive, only sumneko lua its working. but any other lsp is inactive, i tried installing them, but nothing happened.

![image](https://user-images.githubusercontent.com/54772464/136025676-3a06a5a6-24de-422c-ac19-372cbd4cffd2.png)


![image](https://user-images.githubusercontent.com/54772464/136025814-cc0bdb8a-3cf7-4e21-bab2-c2514da857cb.png)


i tried to manually setup the server inside neovim
![image](https://user-images.githubusercontent.com/54772464/136026031-f94eeed2-fc47-4658-b0b4-c139857072a2.png)


and its not attached to the current buffer
![image](https://user-images.githubusercontent.com/54772464/136026073-acd71d64-794b-420a-9b65-86c6dfa63528.png)


it just doesnt want to attach..

what's wrong?

**Comment by abzcoding** [comment]
you need to run `:LvimUpdate` so that lunarvim generates ftplugin files under 
`~/.local/share/lunarvim/site/after/ftplugin/`

**Comment by alexzanderr** [comment]
all the servers should be configured by default and automatically attached to the coresponding buffers.
thats how i see it with lunarvim project. everything should work out of the box. ( the only struggle would be which version of neovim you need, but anything else should work)

**Comment by abzcoding** [comment]
<img width="868" alt="Screen Shot 2021-10-05 at 4 24 03 PM" src="https://user-images.githubusercontent.com/10992695/136026547-241b50de-369c-408c-aeeb-a96823fef002.png">

**Comment by abzcoding** [comment]
> all the servers should be configured by default and automatically attached to the coresponding buffers.
> thats how i see it with lunarvim project. everything should work out of the box. ( the only struggle would be which version of neovim you need, but anything else should work)

yes that should be the case if you ran `:LvimUpdate` feel free to open a new issue if that doesn't properly work

**Comment by abzcoding** [comment]
do you these kinds of files?
<img width="520" alt="Screen Shot 2021-10-05 at 4 25 59 PM" src="https://user-images.githubusercontent.com/10992695/136026882-e57e014d-64e3-4b9a-87d6-3d5ec59beb61.png">

**Comment by abzcoding** [comment]
they should be automatically created if you've used `:LvimUpdate`

**Comment by alexzanderr** [comment]
> do you these kinds of files? <img alt="Screen Shot 2021-10-05 at 4 25 59 PM" width="520" src="https://user-images.githubusercontent.com/10992695/136026882-e57e014d-64e3-4b9a-87d6-3d5ec59beb61.png">

![image](https://user-images.githubusercontent.com/54772464/136027080-bb3a73de-7290-40b8-bf37-b8877d82a38f.png)

**Comment by abzcoding** [comment]
well then the lang servers should attach and work? are they not working?

**Comment by alexzanderr** [comment]
look ... only `lua ls` is working
![image](https://user-images.githubusercontent.com/54772464/136027172-d13aa772-400f-446f-a229-0a7edb665e80.png)

![image](https://user-images.githubusercontent.com/54772464/136027195-4dddcd45-8115-43ca-9840-0ca0ce289c5c.png)

**Comment by abzcoding** [comment]
are sure you are on a project folder?
for example for python server to be activated you need to have these files in the root of your project folder
https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#pyright
or it needs to be git managed
<img width="769" alt="Screen Shot 2021-10-05 at 4 29 21 PM" src="https://user-images.githubusercontent.com/10992695/136027518-d3345c56-abcd-4a1a-a136-b272605e2481.png">

**Comment by abzcoding** [comment]
also please run `:LvimInfo` in a python file

**Comment by alexzanderr** [comment]
apparently, `jsonls`, `sumneko_lua` are working, but `pyright`, `cpp`,  are not.

`c` language server its working, weird, but the same `clangd` its not working for `cpp` filetype.

**Comment by abzcoding** [comment]
can you check `~/.cache/nvim/lsp.log` for possible issues, also please run `:LvimInfo` in a `python` or `cpp` file

**Comment by alexzanderr** [comment]
wtf.
now its working
![image](https://user-images.githubusercontent.com/54772464/136027859-f26f0a0d-4f96-4330-9c8b-74b5970211cc.png)


![image](https://user-images.githubusercontent.com/54772464/136027894-7aa0a5c0-7a62-4b60-ae21-7d1d558fac19.png)

**Comment by alexzanderr** [comment]
> are sure

i am in a git managed folder.

**Comment by abzcoding** [comment]
you might need to reopen it after update, that might be the reason 🤷

**Comment by abzcoding** [comment]
also we are using an implementation of `impatient.nvim` to cache stuff, that might be the culprit
run `:LuaCacheProfile` to check it

**Comment by alexzanderr** [comment]
well, in `~/.cache/nvim/lsp.log`, there are `80000` lines of logs. i cant show all of them.

also result of `LvimInfo` in `cpp`, i see its working now..
![image](https://user-images.githubusercontent.com/54772464/136028307-5fdfe777-44f1-42c2-82b7-8afc65a9822e.png)


> also we are using an implementation of `impatient.nvim` to cache stuff, that might be the culprit run `:LuaCacheProfile` to check it

![image](https://user-images.githubusercontent.com/54772464/136028477-29fa1335-c28b-4bcd-bd67-e41cc747d6b8.png)

**Comment by abzcoding** [comment]
its all good no need to show anything else 😅

**Comment by alexzanderr** [comment]
so i guess the solution to most errors of lunar vim is:
- to install neovim `0.5.1` or `0.6`
- to run `PackerSync`
- to run `LvimUpdate`
- restart lunar vim
- install any absent language server (if you dont have them)
- install tree sitter parsers (if you dont have them)
and i think thats it.

am i correct?

**Comment by abzcoding** [comment]
atm yes, but most of it gonna be automated in our `1.0` release

**Comment by alexzanderr** [comment]
cool. thanks a lot for support and help.

**Comment by alexzanderr** [comment]
what versions of neovim should i ignore?
because i saw that with neovim `0.6.2` i had problems in lunarvim

**Comment by abzcoding** [comment]
> what versions of neovim should i ignore? because i saw that with neovim `0.6.2` i had problems in lunarvim
> 
> can you make a list, please?

there is no `0.6.2` version as far as i know
but `0.5` `0.5.1` and `0.6 head` should be working fine

**Comment by alexzanderr** [comment]
> but 0.5 0.5.1 and 0.6 head should be working fine, i'm on 0.6 head and i'm updating my neovim on a daily basis to make sure it stays functional in neovim head

cool. thanks a lot.

**Comment by abzcoding** [comment]
are you sure that wasn't `0.5.2` ?
cause this is the latest nightly version on their reop
<img width="691" alt="Screen Shot 2021-10-05 at 4 45 06 PM" src="https://user-images.githubusercontent.com/10992695/136030192-312dec04-3c0c-46b4-87c9-55a099b4581c.png">

**Comment by abzcoding** [comment]
also this is the latest version on aur
<img width="616" alt="Screen Shot 2021-10-05 at 4 46 19 PM" src="https://user-images.githubusercontent.com/10992695/136030381-6068e741-50d9-4131-a1ac-9f3316e85418.png">

**Comment by alexzanderr** [comment]
> are you sure that wasn't 0.5.2 ?

very sure. well. if you say so. i dont really know. i remember that i once built neovim on my machine manully and got `0.6.2`

**Comment by alexzanderr** [comment]
> are you sure that wasn't 0.5.2 ?
very sure. well. if you say so. i dont really know. i remember that i once built neovim on my machine manully and got `0.6.2`

**Comment by alexzanderr** [comment]
wanna talk on discord?

**Comment by abzcoding** [comment]
> > are you sure that wasn't 0.5.2 ?
> 
> very sure. well. if you say so. i dont really know. i remember that i once built neovim on my machine manully and got `0.6.2`

that might be a non-release version then

**Comment by abzcoding** [comment]
> wanna talk on discord?

sadly i don't have time for it 😭 , but hopefully i'll be active next week 🤞

**Comment by abzcoding** [comment]
> wanna talk on discord?
> i want to contribute to this project and i need to know the standards.

https://github.com/LunarVim/LunarVim/blob/rolling/CONTRIBUTING.md

**Comment by alexzanderr** [comment]
i dont mean to talk right now. just to conversate when you have time.

**Comment by alexzanderr** [comment]
add me and we will see. `alexzander#5442`

**Comment by abzcoding** [comment]
> i dont mean to talk right now. just to conversate when you have time.

for sure mate, you can hop on our server and talk in #lunarvim channel with other devs as well
https://discord.gg/7kuuVdNG

**Comment by alexzanderr** [comment]
i already am and i already talked there.
