### ISSUE TITLE
[Bug]: `LspInstall` shouldn't be the only way to use language servers

### ISSUE THREAD

**Issue by xeluxee** [LunarVim/LunarVim#1691]
### Problem description

Currently the only way to use language severs is `:LspInstall`.
But I'd prefer to use language servers installed system-wide.

After the last update the below code doesn't work anymore:
```
lvim.lang.c.lsp.setup.cmd[1] = "clangd"
```
It tells me to look at Breaking Changes in README.md, but I can't figure out how to change LS path with Nlsp, especially with c family languages that currently aren't supported by that plugin.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

8fb404f

### Neovim version (>= 0.5)

0.5

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Dulanjala007** [comment]
yeah! i faced this too.. 
I am on nixos, where no generic linux executable works, must be complied on system or from nixos binary servers.
with introduction of "nvim-lsp-installer", my lvim setup completely broken..

checking and merging provider config from a provider dir from user config dir would be a solution...

**Comment by abzcoding** [comment]
you can use user provider and override all of the lang servers, you can find examples in my configuration reop
https://github.com/abzcoding/lvim/blob/8cb8e7e2bb3d2f65c8b6e6bcff24eb35ae993711/config.lua#L47
https://github.com/abzcoding/lvim/tree/main/lua/user/providers

**Comment by Dulanjala007** [comment]
@abzcoding Thanks for the info...
but it would be nice if lvim automaitcally load and merge user config without all these code in user config for all the lang servers.
just my opinion...

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by abzcoding** [comment]
i'm closing this in favor of #1697
