### ISSUE TITLE
[Bug]: LunarVim does not start when the nvim/lvim command is run

### ISSUE THREAD

**Issue by jrafaaael** [LunarVim/LunarVim#1693]
### Problem description

After installing Lunarvim, I want to run it and to do this I run the command `nvim` in the terminal, which launch neovim (I mean without any configuration), but not LunarVim...

When I run the command `lvim` I get `Command 'lvim' not found, but there are 25 similar ones.`

Only when I run the command `~/.local/bin/lvim` (https://www.lunarvim.org/01-installing.html#troubleshooting-installation-problems) launch LunarVim.

### Neovim version (>= 0.5)

0.5

### Relevant log output

```shell
when run :checkhealt in nvim (not lunarvim)

## Configuration
  - WARNING: Missing user config file: /home/jrafael/.config/nvim/init.vim
    - ADVICE:
      - :help init.vim

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6003'
  - INFO: $COLORTERM='truecolor'

health#provider#check
```

### Screenshots

![running nvim](https://user-images.githubusercontent.com/70046023/135936678-11066af0-18c0-42fb-99cd-a9ffab879b3c.png)
![launch nvim](https://user-images.githubusercontent.com/70046023/135936687-f65f919e-24fa-48e6-80ff-000e04be6d1a.png)
![running these command from https://www.lunarvim.org/01-installing.html#troubleshooting-installation-problems](https://user-images.githubusercontent.com/70046023/135936691-cc081b5e-245b-4e79-8656-b09bfbbbcf1e.png)
![launch lunarvim](https://user-images.githubusercontent.com/70046023/135936701-6f076006-cb9c-44c1-9dec-9ed6242f7c30.png)
![Screenshot at 2021-10-04 19-18-51](https://user-images.githubusercontent.com/70046023/135937117-fa8e95f6-4000-4657-a930-b57aa543f549.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by adamklo** [comment]
Add `$HOME/.local/bin` to your $PATH

**Comment by abzcoding** [comment]
https://www.lunarvim.org/02-after-install.html#add-lvim-to-path
