### ISSUE TITLE
[Bug]: Formatting with prettier asks to select a language server

### ISSUE THREAD

**Issue by kbrah** [LunarVim/LunarVim#1705]
### Problem description

When formatting a typescript file with prettier_d_slim set as formatter, lvim asks to select a language server
![image](https://user-images.githubusercontent.com/10815813/136363784-d790ded3-f374-4157-b49f-728be0ce35ee.png)
If I select null-ls, prettier does the formatting but not with tsserver.

This is the only thing I added to my config:
```
lvim.lang.typescript.formatters = { { exe = "prettier_d_slim" } }
lvim.lang.typescriptreact.formatters = lvim.lang.typescript.formatters
```

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5.1

### Relevant log output

```shell
Language client log: /home/xx/.cache/nvim/lsp.log
 Detected filetype:   typescript
 
 3 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, pid: 5001, bufnr: [11])
 	filetypes:       javascript, javascriptreact, typescript, typescriptreact, vue, svelte
 	autostart:       false
 	root directory:  /home/xx/Code/xx/xx
 	cmd:             nvim
 
 Client: tsserver (id: 2, pid: 173051, bufnr: [11])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /home/xx/Code/xx/xx
 	cmd:             /home/xx/.local/share/nvim/lsp_servers/tsserver/node_modules/.bin/typescript-language-server --stdio
 
 Client: tailwindcss (id: 3, pid: 173052, bufnr: [11])
 	filetypes:       aspnetcorerazor, astro, astro-markdown, blade, django-html, edge, eelixir, ejs, erb, eruby, gohtml, haml, handlebars, hbs, html, html-eex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte
 	autostart:       true
 	root directory:  /home/xx/Code/xx/xx
 	cmd:             /home/xx/.local/share/nvim/lsp_servers/tailwindcss_npm/node_modules/.bin/tailwindcss-language-server --stdio
 
 Configured servers list: tsserver, tailwindcss, null-ls
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
that might be because tsserver supports native formatting, and by default you have
```lua
lvim.format_on_save = true
```
so neovim wants to know which formatter to use 
1. the native tsserver formatter
2. or the null-ls prettier formatter

**Comment by kylo252** [comment]
when was the last time you updated? this shouldn't happen on rolling.

**Comment by gfsd3v** [comment]
@kylo252 I'm using the most recently rolling version and I'm having the same behavior

![image](https://user-images.githubusercontent.com/36668882/136454761-51432315-2dea-481d-ad9f-e0fc937e9b6c.png)

**Comment by marcomayer** [comment]
I have the same issues with .json files.

**Comment by kbrah** [comment]
@kylo252 I was using the latest version. I just updated to the latest again. Now on typescriptreact files format_on_save does not work at all but in typescript files it still asks for the language server. If I manually format space + l + f on typescriptreact file, it does not ask for the language server but uses the tsserver native formatting.

**Comment by kbrah** [comment]
Oh sorry I missed that one.

This seems to work correctly
```
local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup({{exe = "prettier_d_slim", filetypes = {"typescript", "typescriptreact", "javascript"} }})

lvim.lsp.on_attach_callback = function(client, _)
    if client.name == "tsserver" or client.name == "jsonls" then
      client.resolved_capabilities.document_formatting = false
      client.resolved_capabilities.document_range_formatting = false
    end
  end

```

However still having issues if I use this
```
lvim.lang.typescript.formatters = { { exe = "prettier_d_slim" } }
lvim.lang.typescriptreact.formatters = lvim.lang.typescript.formatters

lvim.lsp.on_attach_callback = function(client, _)
    if client.name == "tsserver" or client.name == "jsonls" then
      client.resolved_capabilities.document_formatting = false
      client.resolved_capabilities.document_range_formatting = false
    end
  end

```

**Comment by abzcoding** [comment]
@kbrah no worries, yeah as mentioned -> https://www.lunarvim.org/languages/#multi-languages-per-formatter
your first syntax should be better ( not reusing the same formatter twice )
<img width="773" alt="Screen Shot 2021-10-15 at 10 51 04 AM" src="https://user-images.githubusercontent.com/10992695/137448081-0c3e753f-3ce4-43ac-bff0-f7470bde1725.png">
