### ISSUE TITLE
[Feature]:  Show line diagnostics only for line during CursorHold

### ISSUE THREAD

**Issue by casonadams** [LunarVim/LunarVim#1712]
### Feature motivation

I think having virtual text on is awesome!  However, it is super noisy.  Would be nice to have an option that allow it to be toggled to show only the line on CursorHold

### Describe the expected solution

Here is what I have working.  It is kind of dirty.  I would like some guidance on where I should put this code to make it a reality

```
function PrintDiagnostics(opts, bufnr, line_nr, client_id)
  opts = opts or {}
  bufnr = bufnr or 0
  line_nr = line_nr or (vim.api.nvim_win_get_cursor(0)[1] - 1)

  local line_diagnostics = vim.lsp.diagnostic.get_line_diagnostics(bufnr, line_nr, opts, client_id)
  if vim.tbl_isempty(line_diagnostics) then return end

  local diagnostic_message = ""
  for i, diagnostic in ipairs(line_diagnostics) do
    diagnostic_message = diagnostic_message .. string.format("%s ", diagnostic.message or "")
  end
  -- print(diagnostic_message) -- on comment to print to MsgArea
  vim.api.nvim_buf_set_virtual_text(bufnr, 1, line_nr , {{diagnostic_message, "LspDiagnosticsDefaultError"}}, {})
end

function Clear(_, bufnr, _, _)
-- print("      ") -- on comment to print to MsgArea
  vim.api.nvim_buf_clear_namespace(bufnr, 1, 0, -1)
end

vim.cmd [[ autocmd CursorHold * lua PrintDiagnostics() ]]
vim.cmd [[ autocmd CursorMoved * lua Clear() ]]
```

**Comment by abzcoding** [comment]
in that case, you can literally disable the virtual text using `lvim.lsp.diagnostics.virtual_text = false`
and then put your all of your code in `~/.config/lvim/config.lua`
<img width="1599" alt="Screen Shot 2021-10-08 at 11 07 26 PM" src="https://user-images.githubusercontent.com/10992695/136616023-21116264-a4ed-4078-910d-47b9d7bf6155.png">

**Comment by casonadams** [comment]
I was wondering if this was something that would be considered to be added to lvim?

So that some quick mock up would look like this.
```
lvim.lsp.diagnostics.virtual_text = {
  enabled = true,
  display = "line || all"
}
```

**Comment by kylo252** [comment]
Last time I tried this it ended up being a bit buggy, so I'm not really sure that I recommend making this a default behavior even on your own configuration.

**Comment by kraxli** [comment]
@casonadams I would love to have such a behaviour! Would you mind to share your setup?

The following is not working. However I am wondering if something in the direction of the below code-snip could work?
```
lvim.autocommands.custom_groups = {
  { "CursorHold", "*", "lua vim.diagnostic.get(nil, { virtual_text = true, underline = false })" },
}
```

**Comment by kraxli** [comment]
@abzcoding how would your solution 
```
lvim.lsp.diagnostics.virtual_text = false
lvim.autocommands.custom_groups = {
  { "CursorHold", "*", "lua vim.lsp.diagnostic.show_line_diagnostics({ show_header = false, border = 'single' })" },
}
```
in `neovim >= 0.6` work?

**Comment by abzcoding** [comment]
@kraxli just change the lua thingy part to
```lua
lua vim.diagnostic.open_float(0,{scope='line'})
```

**Comment by casonadams** [comment]
> ### Feature motivation
> 
> I think having virtual text on is awesome! However, it is super noisy. Would be nice to have an option that allow it to be toggled to show only the line on CursorHold
> ### Describe the expected solution
> 
> Here is what I have working. It is kind of dirty. I would like some guidance on where I should put this code to make it a reality
> 
> ```
> function PrintDiagnostics(opts, bufnr, line_nr, client_id)
>   opts = opts or {}
>   bufnr = bufnr or 0
>   line_nr = line_nr or (vim.api.nvim_win_get_cursor(0)[1] - 1)
> 
>   local line_diagnostics = vim.lsp.diagnostic.get_line_diagnostics(bufnr, line_nr, opts, client_id)
>   if vim.tbl_isempty(line_diagnostics) then return end
> 
>   local diagnostic_message = ""
>   for i, diagnostic in ipairs(line_diagnostics) do
>     diagnostic_message = diagnostic_message .. string.format("%s ", diagnostic.message or "")
>   end
>   -- print(diagnostic_message) -- on comment to print to MsgArea
>   vim.api.nvim_buf_set_virtual_text(bufnr, 1, line_nr , {{diagnostic_message, "LspDiagnosticsDefaultError"}}, {})
> end
> 
> function Clear(_, bufnr, _, _)
> -- print("      ") -- on comment to print to MsgArea
>   vim.api.nvim_buf_clear_namespace(bufnr, 1, 0, -1)
> end
> 
> vim.cmd [[ autocmd CursorHold * lua PrintDiagnostics() ]]
> vim.cmd [[ autocmd CursorMoved * lua Clear() ]]
> ```
> 
> ### Describe the alternatives you've considered
> 
> _No response_
> ### Additional context
> 
> _No response_

@kraxli ^^

**Comment by kraxli** [comment]
@abzcoding many thanks! works charmingly :-)

would there something similar be for virtual text. E.g. leveraging   `vim.lsp.diagnostics.show`?

**Comment by abzcoding** [comment]
@kraxli not sure tbh, but you can check out [lsp_lines.nvim](https://git.sr.ht/~whynothugo/lsp_lines.nvim)

**Comment by kraxli** [comment]
@abzcoding thanks a lot! I am going with the solution you have posted:
```lua vim.diagnostic.open_float(0,{scope='line'})```

**Comment by dgmora** [comment]
Hi, I got this working, however it would be really nice if this would be one of the default supported options. Virtual text can be very obtrusive in some files.
A third option that I liked is getting them in the status line when hovering (with [Ale](https://github.com/dense-analysis/ale))

For  others getting here, seems `custom_groups` is deprecated. This works:

```
lvim.autocommands = {
  { "CursorHold", "*", "lua vim.lsp.diagnostic.show_line_diagnostics({ show_header = false, border = 'single' })" }
}
```

**Comment by jorgsk** [comment]
I'd love to see this functionality working. I tried the approach from @dgmora but the config is not accepted:
![autocmd_error](https://user-images.githubusercontent.com/761677/187451801-4f6ca21a-a03d-4f4f-932c-527773e0f6d9.png)

**Comment by casonadams** [comment]
I created this plugin [simple-diagnostics](https://github.com/casonadams/simple-diagnostics.nvim) that helps with this.  Have a look.

**Comment by jorgsk** [comment]
Thanks @casonadams, your plugin does the job!
