### ISSUE TITLE
[Bug]: Code actions doesn't work in `javascript` files using `tsserver`

### ISSUE THREAD

**Issue by angryheng** [LunarVim/LunarVim#1713]
### Problem description

Code actions dont work at all

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6.0

### Screenshots

![bug](https://user-images.githubusercontent.com/28853495/136526822-4b5f5d48-8c11-420b-8f12-0acfba4c23b4.gif)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
@carvhal @jakubreron that is probably a separate issue
cc: @kylo252

**Comment by chase** [comment]
The rename action in `lua` for `sumneko` doesn't work anymore either

**Comment by abzcoding** [comment]
> The rename action in `lua` for `sumneko` doesn't work anymore either
it seems to be working 🤔 , what version of neovim are you using?
<img width="1307" alt="Screen Shot 2021-10-09 at 11 18 12 AM" src="https://user-images.githubusercontent.com/10992695/136649422-e6ed6cd8-36dd-4c7a-a305-248c0fbccb36.png">

**Comment by abzcoding** [comment]
it might be that tbh, although i'm on neovim 0.6 head

**Comment by abzcoding** [comment]
> > it might be that tbh, although i'm on neovim 0.6 head
> 
> To clarify, I'm triggering it using `vim.lsp.buf.rename()`, what are you using to trigger the rename? (I've also never had it open the buffers it updates, so something might be weird on my end)

`<leader>lr` which i think is bound to the same thing

**Comment by chase** [comment]
> > > it might be that tbh,

Is there any way for you to easily check which version of sumneko you're using?

**Comment by chase** [comment]
@abzcoding Figured out the issue.
This PR broke my config: https://github.com/LunarVim/LunarVim/pull/1584
It broke lua-dev, silently:
```
{
    "folke/lua-dev.nvim",
    config = function()
      local luadev = require("lua-dev").setup({
        lspconfig = lvim.lang.lua.lsp.setup
      })
      lvim.lang.lua.lsp.setup = luadev
    end,
    ft = "lua"
  },
```

**Comment by abzcoding** [comment]
> @abzcoding Figured out the issue. This PR broke my config: #1584 It broke lua-dev, silently:
> 
> ```lua
> {
>     "folke/lua-dev.nvim",
>     config = function()
>       local luadev = require("lua-dev").setup({
>         lspconfig = lvim.lang.lua.lsp.setup
>       })
>       lvim.lang.lua.lsp.setup = luadev
>     end,
>     ft = "lua"
>   },
> ```
i'm using lua-dev as well in case you wanted to use it https://github.com/abzcoding/lvim/blob/main/lua/user/providers/sumneko_lua.lua

**Comment by kylo252** [comment]
> The rename action in `lua` for `sumneko` doesn't work anymore either

It has _always_ been very finicky for me, but it seemed like I was always the only one with that problem :(

**Comment by abzcoding** [comment]
this should be fixed
