### ISSUE TITLE
[Bug]: Internal Telescope man_pages slugish

### ISSUE THREAD

**Issue by Xyhlon** [LunarVim/LunarVim#1721]
### Problem description

Enter lvim
Search the Man Pages Type <leader>sM 
Search for pthreads or pthread_create
It will take for ever and won't find the correct result

### LunarVim version

rolling 

### Neovim version (>= 0.5)

0.5-release

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
<img width="884" alt="Screen Shot 2021-10-09 at 11 35 23 AM" src="https://user-images.githubusercontent.com/10992695/136649935-b91560b1-8c89-40e8-abff-02623625d0c2.png">

**Comment by Xyhlon** [comment]
for the common ones like cat printf it works however I need to work with the POSIXs standard and need to find and use pthreads however it doesn`t find it. I installed fzf via apt and changed the config.lua to import telescope nvim fzf plugin, packer compiled, restarted lvim and still it doesn't find the POSIXs pthreads man page
![image](https://user-images.githubusercontent.com/26318103/136650265-04792017-f5c1-4b64-ba70-a09adae18a10.png)

**Comment by abzcoding** [comment]
ok you might wanna create an issue in the telescope.nvim repo for that, cause we are just calling 
```lua
        M = { "<cmd>Telescope man_pages<cr>", "Man Pages" },
```

**Comment by Xyhlon** [comment]
config.lua
lvim.builtin.which_key.mappings.s.M = { "<cmd>Telescope man_pages sections=1,2,3,4,7,<cr>", "Man Pages" }
after changing this mapping i can find the man pages but browsing and opening man pages using K is still really slow i thing man_pages doesn't use ripgrep or fzf or fd

**Comment by rebuilt** [comment]
The colorizer plugin slows down telescope searches.  Related issue: https://github.com/LunarVim/LunarVim/issues/2718.  

It's possible other plugins can similarly slow down searches.  The only way to know is to turn off your other plugins to see if search speeds up.
