### ISSUE TITLE
[Feature]: Sections in Man Page search

### ISSUE THREAD

**Issue by Xyhlon** [LunarVim/LunarVim#1723]
### Feature motivation

There is no option to search specific section of the man_pages it only searches the first section however this is inconvenient.
https://github.com/nvim-telescope/telescope.nvim/issues/1321
also SEE Issue #1721 

### Describe the expected solution

It should either search all of the man_pages or  a option in the command should be given
like 
\<leader\>s<section_numbers>M
which should execute 
in which-key.lua
        M = { "<cmd>Telescope man_pages sections=<section_numbers_seperated_by_commas_with_trailing_comma><cr>", "Man Pages" },

**Comment by abzcoding** [comment]
or do you prefer making the section part configurable,
with the default being only the first section
 and search all sections at once?

**Comment by major0** [comment]
I personally think the default should have been changed to `sections="ALL"`.

**Comment by abzcoding** [comment]
> I personally think the default should have been changed to `sections="ALL"`.

you can change it in your config if you like

```lua
lvim.builtin.which_key.mappings["sM"] = { "<cmd>Telescope man_pages sections=ALL<cr>", "Man Pages" }
```
