### ISSUE TITLE
[Bug]: autopairs plugin isn't loaded

### ISSUE THREAD

**Issue by xeluxee** [LunarVim/LunarVim#1727]
### Problem description

When I go to insert mode autopairs ins't loaded.
I can see it even from `:PackerStatus`
In `lua/plugins.lua` line 53 loads autopairs after `nvim-cmp`, but even if cmp is loaded autopairs isn't loaded (see `:PackerStatus`)
Removing line 53 makes it work
Anyone experiencing this issue?

### LunarVim version

596db66

### Neovim version (>= 0.5)

0.5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Yes,  I believe it's related to this packer issue https://github.com/wbthomason/packer.nvim/issues/435

Here is more context on why this might happen:  https://github.com/wbthomason/packer.nvim/issues/272#issuecomment-811254292
