### ISSUE TITLE
lsp failing - Expected table, got nil

### ISSUE THREAD

**Issue by andoni0305** [LunarVim/LunarVim#1730]
### Problem description

Getting the following error when lauching lvim 
```
Error detected while processing /Users/user.name/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: vim/shared.lua:235: Expected table, got nil
```
The result is not getting any lsp, virtual text or icons, etc...

Steps to reproduce:

1. Launch lvim 
2. Open any lua file
3. No lsp

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [ ] The programs specified by the config are installed

### LunarVim version

rolling - latest

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+447-g5940a3415

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by andoni0305** [comment]
formatters are not attaching either
maybe null-ls being affected

**Comment by andoni0305** [comment]
Seems to have been an issue in my config :|

**Comment by thiagodebastos** [comment]
> 
> 
> Seems to have been an issue in my config :|

I'm now getting this issue after updating lvim, may I ask how you fixed it?

**Comment by thiagodebastos** [comment]
That's really strange, your config worked for me too. I don't have much time to investigate further right now, but this is what I had, which worked before the update:

```lua
lvim.lang.javascript.formatters = { { exe = "prettier" }, { exe = "eslint" } }
lvim.lang.javascriptreact.formatters = { { exe = "prettier" }, { exe = "eslint" } }

lvim.lang.typescript.formatters = { { exe = "eslint_d" } }
lvim.lang.typescriptreact.formatters = lvim.lang.typescript.formatters

-- set an additional linter
lvim.lang.javascript.linters = { { exe = "eslint_d" } }
lvim.lang.javascriptreact.linters = { { exe = "eslint_d" } }

lvim.lang.typescript.linters = { { exe = "eslint_d" } }
lvim.lang.typescriptreact.linters = lvim.lang.typescript.linter

```
