### ISSUE TITLE
[Feature]: filetype.nvim plugin for faster startup times

### ISSUE THREAD

**Issue by argapost** [LunarVim/LunarVim#1735]
### Feature motivation

In the chase of 0ms startup times maybe this plugin https://github.com/nathom/filetype.nvim can be added to the core plugins of lvim?

**Comment by abzcoding** [comment]
[this](https://www.reddit.com/r/neovim/comments/rvwsl3/introducing_filetypelua_and_a_call_for_help/) has been added upstream
