### ISSUE TITLE
[Bug]: C/CPP Formatter stopped working.

### ISSUE THREAD

**Issue by jameswalmsley** [LunarVim/LunarVim#1750]
### Problem description

1. Open a C file.
2. Attempt for format

File does not format

clang-format was working with null-ls recently, and I'm not sure whats stopped working.
I've enabled the null-ls log, and if I configure my formatter to uncrustify I get a log file..

However with clang-format I'm not getting anything.

My config is:

```
lvim.lang.c.formatters = {{ exe = 'clang-format' }}
```

J

### LunarVim version

origin/rolling

### Neovim version (>= 0.5)

0.5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Why not use `clangd` for this?

**Comment by kylo252** [comment]
If you set an external formatter then it will disable the formatting capability for the language server by default. We've had that behavior pretty much since the beginning.

If it's something specifically with `clangd` then check if you need to set: `--fallback-style`
