### ISSUE TITLE
[Bug]: Formatting and custom configuration lost after editing configuration files

### ISSUE THREAD

**Issue by dumrich** [LunarVim/LunarVim#1758]
### Problem description

1. Edit the config file by adding a keybinding
2. Save changes and go to another file
3. See bufferline, lualine, and fonts go away. Also keybindings don't work

I was able to counter the bufflerline/lualine issue by running LvimUpdate and PackerCompile, but this overrides my config

### LunarVim version

Stable

### Neovim version (>= 0.5)

0.5

### Screenshots

![image](https://user-images.githubusercontent.com/40397381/137035238-16f0561e-c194-4ef3-94dd-ed403cf0a022.png)
After running LvimUpdate and PackerUpdate (custom keybindings still lost):
![image](https://user-images.githubusercontent.com/40397381/137035305-9df86945-c16f-4eac-9c0a-7db45fb0687b.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
> This also happen on rolling, the step are same, change whatever on config file, save it, quit and run `lvim` you will get default neovim screen, and must run `:PackerCompile`. If it ot happen on your config try [mine](https://gist.github.com/mandaputtra/11277ecae23975a64ba15c31139d9a89)

can you comment this part of your config?
```lua
lvim.lsp.override = { 'typescript', 'typescriptreact', 'javascript', 'javascriptreact' }

lvim.lang.typescript.formatters = { { exe = "prettierd" } }
lvim.lang.typescriptreact.formatters = lvim.lang.typescript.formatters
lvim.lang.javascript.formatters = lvim.lang.typescript.formatters
lvim.lang.javascriptreact.formatters = lvim.lang.typescript.formatters

lvim.lang.typescript.linters = { { exe = "eslint_d" } }
lvim.lang.typescriptreact.linters = lvim.lang.typescript.linters
lvim.lang.javascript.linters = lvim.lang.typescript.linters
lvim.lang.javascriptreact.linters = lvim.lang.typescript.linters
```
also do a `:LvimUpdate`

**Comment by mandaputtra** [comment]
Can you share your config?

**Comment by kylo252** [comment]
I'm not sure about the other issues with barbar, because I can't really tell what's wrong. But for the key mappings that are using by lunarvim, you need to use the same syntax to override them because it's not quite that easy to detect that a user has set a keybind otherwise.

```lua
lvim.builtin.which_key.mappings["f"] = {
	f = { "<cmd>Telescope find_files<CR>", "Find Files" },
	g = { "<cmd>Telescope live_grep<CR>", "Live grep" },
}
```

see https://www.lunarvim.org/configuration/02-keybindings.html#lunarvim-keybindings
