### ISSUE TITLE
[Bug]: Treesitter for erlang not working?

### ISSUE THREAD

**Issue by ivano9** [LunarVim/LunarVim#1759]
### Problem description

I installed the tree-sitter for erlang by doing via command `:TSInstall erlang` but not show the icon of tree-sitter in the status bar, also when I do :TSModuleInfo show:

![image](https://user-images.githubusercontent.com/43305758/137148968-c228dcf8-2320-4d7b-95d4-b62707776f27.png)

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5

### Screenshots
health#treesitter#check

![image](https://user-images.githubusercontent.com/43305758/137057904-36c1e6c9-2655-4f77-80fb-ea8660fb4152.png)

health#nvim_treesitter#check

![image](https://user-images.githubusercontent.com/43305758/137057998-6aa07eb6-a308-4a44-aaf4-269f8febcc78.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
from your TSModuleInfo `erlang` is a different entity from `elixir` so you might need to update the picture

**Comment by ivano9** [comment]
> https://github.com/LunarVim/LunarVim/blob/9e18c16b2b378792c689591190774786fd5da04c/lua/lvim/plugins.lua#L61-L63

yes im using the same

**Comment by kylo252** [comment]
Keep in mind that this might be related to #1362
