### ISSUE TITLE
[Feature]: hi CursorColumn 

### ISSUE THREAD

**Issue by phamlehuy53** [LunarVim/LunarVim#1771]
### Feature motivation

In lvim, i can't highlight CursorColumn  

### Describe the expected solution

Be able to customize CursorColumn and CursorLine

**Comment by abzcoding** [comment]
by default, we are highlighting the current line as you can see here
https://github.com/LunarVim/LunarVim/blob/daa0b24a501939f9af7d37af12066d31f78f2df1/lua/lvim/config/settings.lua#L38

you can disable it by adding this to your config
```lua
vim.opt.cursorline = false
-- vim.opt.cursorcolumn = false
```
or even use autocommands
```lua
lvim.autocommands.custom_groups = {
    { "WinLeave", "*", "set nocursorline nocursorcolumn" },
    { "WinEnter", "*", "set cursorline cursorcolumn" },
}
```

as for changing the hi color of CursorColumn and CursorLine
these are the default for `onedarker` theme of lunarvim
https://github.com/LunarVim/LunarVim/blob/daa0b24a501939f9af7d37af12066d31f78f2df1/lua/onedarker/highlights.lua#L23-L24
which you can change either by using a different theme or by setting them directly
```lua
vim.cmd [[
    hi CursorColumn cterm=bold ctermbg=red guibg=#464646
]]
```

**Comment by ashnur** [comment]
While the vim.cmd does change the color, something still overwrites it later, so it doesn't stick.

**Comment by abzcoding** [comment]
> While the vim.cmd does change the color, something still overwrites it later, so it doesn't stick.

you can create a file called `~/.config/lvim/after/plugin/highlights.vim`
and put this or anything else inside it, that should run after everything else
```lua
hi CursorColumn cterm=bold ctermbg=red guibg=#464646
```
if that didn't help either, you are better off using another colorscheme or forking https://github.com/LunarVim/onedarker.nvim and changing it to your liking

**Comment by aemonge** [comment]
Did any of both solutions worked?  On my case, I'm using `lvim.colorscheme = "gruvbox-material"` from **sainnhe/gruvbox-material** and I'm wanting to do the following, but It isnt' working either direclty at `~/.lvim/config.lua`:

```
vim.cmd [[
  hi clear SpellBad
  hi clear SpellCap
  hi SpellBad     gui=underline cterm=underline
  hi SpellCap     gui=underline cterm=underline
  hi CursorLine   gui=bold      cterm=bold
  hi CursorColumn gui=bold      cterm=bold
  hi SignColumn   gui=bold      cterm=bold
  hi NonText      ctermbg=none
  hi Terminal     ctermbg=none
  hi Normal       ctermbg=none
  hi Folded       ctermbg=none
  hi CursorLine   ctermbg=none
  hi CursorColumn ctermbg=none
  hi SignColumn   ctermbg=none
]]
```

Nor saving it in `~/.config/lvim/after/plugin/gruvbox-materia.vim`
```
hi clear SpellBad
hi clear SpellCap
hi SpellBad     gui=underline cterm=underline
hi SpellCap     gui=underline cterm=underline
hi CursorLine   gui=bold      cterm=bold
hi CursorColumn gui=bold      cterm=bold
hi SignColumn   gui=bold      cterm=bold
hi NonText      ctermbg=none
hi Terminal     ctermbg=none
hi Normal       ctermbg=none
hi Folded       ctermbg=none
hi CursorLine   ctermbg=none
hi CursorColumn ctermbg=none
" let g:gruvbox_color_column=none
hi SignColumn   ctermbg=none

```
