### ISSUE TITLE
[Bug]: module 'lsp.manager' not found

### ISSUE THREAD

**Issue by ahmedkhalf** [LunarVim/LunarVim#1799]
### Problem description

When I open my config file I get this error:
```
Error while processing file: /home/ahmedk/.local/share/lunarvim/site/after/ftplugin/lua.lua
...ahmedk/.local/share/lunarvim/site/after/ftplugin/lua.lua:1: module 'lsp.manager' not found
```
and LSP is inactive.

When I open a random .py file, there are no errors but LSP is still inactive.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

latest rolling

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+418-gacd5e831b

### Relevant log output

```shell
No errors apart from one documented above, also no lsps are active.
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ahmedkhalf** [comment]
Thx lvimupdate fixed it

**Comment by kylo252** [comment]
> The same message appears if I require _lsp.manager_ from config. **Release type**: rolling

Make sure you run `LvimUpdate` and `LvimCacheReset`.
