### ISSUE TITLE
Global install script.

### ISSUE THREAD

**Issue by jameswalmsley** [LunarVim/LunarVim#180]
I'd like to be able to install nvcode system-wide to sit alongside vim and neovim.

Running nv should run the global configuration.. unless there is a local configuration found.

**Comment by ChristianChiarulli** [comment]
I would like this as well, however, everytime I've tried I have failed at creating a good self contained installed script. If anyone would like to create this I would appreciate it.

**Comment by jameswalmsley** [comment]
I did a proto-type of a config that can be global, and alternatively fallback to the users local config..
#190

**Comment by Khwarazmi** [comment]
Thanks james for your efforts, here is what i did ( i use arch )

- deleted everything related to nvim from .conf .local
- reinstalled it with pacman -S neovim
- git clone https://github.com/jameswalmsley/nvcode.git -b global-install nvcode.global
- cd nvcode.global/utils/bin
- sudo ./nvcode-upgrade.sh -g

![Screenshot from 2021-04-01 18 23 26](https://user-images.githubusercontent.com/73063566/113324514-7caa5280-9317-11eb-8bfb-09fbbcca49ac.png)

**Comment by jameswalmsley** [comment]
Try running without the sudo:

```
,/nvcode-upgrade.sh -g
```

The script internally uses sudo just for cloning the nvcode configuration into /usr/local/share/nvcode and copying the nv script to /usr/local/bin

Also do you have an alias for `nv`? If you have an older version it might not be setting the environment correctly..

**Comment by Khwarazmi** [comment]
i do have an alias, and unfortunately same error

**Comment by jameswalmsley** [comment]
Does pacman install the latest neovim from the master branch?

You can also run the install-latest-neovim.sh script to build and install it.

What does your nv alias do? Probably that shouldn't affect the script.

I'll run it on arch myself.. not sure what's happening here.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Khwarazmi** [comment]
Thanks a lot James, i fixed it
instead of install with pacman i installed with yay to get the latest version 
yay -S neovim-git and i ran it without sudo 

thank you so much for your efforts and time to help, i really appreciate that
![Screenshot from 2021-04-01 19 47 05](https://user-images.githubusercontent.com/73063566/113333796-2f33e280-9323-11eb-9cee-bdc929dbfe97.png)

**Comment by jameswalmsley** [comment]
Awesome :)
No problem.
