### ISSUE TITLE
[Bug] This extension doesn't exist or is not installed: fzf

### ISSUE THREAD

**Issue by kylo252** [LunarVim/LunarVim#1804]
> LunarVim is complaining about Telescope not having `fzf` installed. I went ahead and installed it through Chocolatey, but I'm still getting the following error:

```log
[lunarvim] [WARN  22:38:14] 
packer.nvim: Error running config for telescope.nvim: ...\start\telescope.nvim\lua\telescope\_extensions\init.lua:12: This extension doesn't exist or is not installed: fzf
...k\packer\start\telescope-fzf-native.nvim\lua\fzf_lib.lua:11: cannot load module 'C:\Users\Andrew\AppData\Roaming\lunarvim\site\pack\packer\start\telescope-fzf-native.nvim\lua\../build/libfzf.dll': The specified module could not be found.^M

packer.compile: Complete
packer.nvim: Error running config for telescope.nvim: ...\start\telescope.nvim\lua\telescope\_extensions\init.lua:12: This extension doesn't exist or is not installed: fzf
loop or previous error loading module 'telescope._extensions.fzf'

E117: Unknown function: exec
E15: Invalid expression: exec('messages')
E117: Unknown function: exe
E15: Invalid expression: exe('messages')
```

_Originally posted by @Antyos in https://github.com/LunarVim/LunarVim/issues/1671#issuecomment-945045035_

---

Edit: to clarify, this has nothing to do with having the `fzf` binary installed or not, it's about https://github.com/nvim-telescope/telescope-fzf-native.nvim. For anyone facing this issue, please try: 

```shell
:! make -C $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim
```

You can also do `make clean`  just to be sure

```shell
:! cd $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim && make clean && make
```

**Comment by Uzaaft** [comment]
@Antyos 
Do you have the Chocolatey install location in your PATH?(Should be `C:\ProgramData\chocolatey` by default, was `C:\Chocolatey`  previously )

**Comment by Antyos** [comment]
> @Antyos Do you have the Chocolatey install location in your PATH?(Should be `C:\ProgramData\chocolatey` by default, was `C:\Chocolatey` previously )

I believe so. This is in my path: `C:\ProgramData\chocolatey\bin`. Running `fzf --version` in PowerShell gives `0.27.2 (e086f0b)`. Additionall, running `:!fzf --version` in LunarVim gives the same result.

**Comment by Antyos** [comment]
> You should change it to `lvim.core.lualine.components`.

Ah, that would fix many things 😅 Thanks!

**Comment by alexzaizar09** [comment]
I'm in a mac with a clean install of neovim and all the requirements and I'm getting the same error. Any suggestions?

**Comment by gaetgu** [comment]
> I'm in a mac with a clean install of neovim and all the requirements and I'm getting the same error. Any suggestions?

@alexzaizar09 I am also running into the same issue. I am on an Apple Silicon mac, which seems to be causing the issues. This is the issue I get when I start lvim:

```console
packer.nvim: Error running config for telescope.nvim: .../start/telescope.nvim/lua/telescope/_extensions/init.lua:12: This extension doesn't exist or is not installed: fzf
...k/packer/start/telescope-fzf-native.nvim/lua/fzf_lib.lua:11: dlopen(/Users/gabriel/.local/share/lunarvim/site/pack/packer/start/telescope-fzf-native.nvim/lua/../build/libfzf.so, 5): no suitable i
mage found.  Did find:
^I/Users/gabriel/.local/share/lunarvim/site/pack/packer/start/telescope-fzf-native.nvim/lua/../build/libfzf.so: mach-o, but wrong architecture
```

I ran `file $(which fzf)`, which returns `/opt/homebrew/bin//fzf: Mach-O 64-bit executable arm64`, but `file [...]/build/libfzf.so` returns `Mach-O 64-bit dynamically linked shared library x86_64`.

That seems to show that the issue (at least for me, on an M1 chip) was to rebuild telescope-fzf-native.nvim as described in https://github.com/nvim-telescope/telescope-fzf-native.nvim/issues/23. Not sure what the problem on Windows could be though.

**Comment by filipesilva-l** [comment]
I'm in Ubuntu 20.04.03 with a clean install of neovim (0.6) and I'm getting the same error. Any suggestions?

**Comment by Antyos** [comment]
So ironically, with all this new talk of `fzf` not working on other systems, mine is actually working fine now! I did have to do a clean install of Windows though (for other reasons), so that may not be the best solution.

**Comment by Uzaaft** [comment]
@filipesilva-l  What does `which fzf` show you?
@abzcoding Perhaps we should add a template(if we dont have one) regarding dependencies issues, and what one should check/provide in the issue ?

**Comment by alexzaizar09** [comment]
@Uzaaft it shows `fzf not found` and in response to @gaetgu I am not in an M1 mac. And actually, I have my own neovim config with fzf working.

**Comment by Uzaaft** [comment]
@alexzaizar09 I guess you need to install fzf, and add it to your PATH. A quick google search gave me this guide: https://zwbetz.com/how-to-add-a-binary-to-your-path-on-macos-linux-windows/#windows-gui

**Comment by filipesilva-l** [comment]
@Uzaaft It shows the following:
![image](https://user-images.githubusercontent.com/30537113/140430775-c020abc1-81b3-451a-b19e-dbfada512cdd.png)

**Comment by alexzaizar09** [comment]
@Uzaaft install `fzf` with brew makes no change, during the installation script of lunarvim is still unable to find it. And it is in the PATH, and as I've said I do have the extension running with my own neovim config

**Comment by Uzaaft** [comment]
@abzcoding You know the codebase better than me. Is there a variable in the config for setting the fzf path?

Just for  the sake of doing it, could you guys do the following:
`:PackerSync`-> `:UpdateRemotePlugins` ->  `:LvimUpdate` -> `:LvimCacheReset` -> `:PackerCompile`
Also, could you guys test the following command from within LunarVim:
`:!fzf --version`

**Comment by abzcoding** [comment]
> @abzcoding You know the codebase better than me. Is there a variable in the config for setting the fzf path?
> 
> Just for the sake of doing it, could you guys do the following: `:PackerSync`-> `:UpdateRemotePlugins` -> `:LvimUpdate` -> `:LvimCacheReset` -> `:PackerCompile` Also, could you guys test the following command from within LunarVim: `:!fzf --version`

as far as i know, this is the only thing we do about fzf
https://github.com/LunarVim/LunarVim/blob/6b3e0574a3d2577f8c0558144202ba12f3978cae/lua/lvim/plugins.lua#L27-L31

**Comment by Uzaaft** [comment]
Wait...Doesn`t that mean that the manual installation of fzf is not needed, since fzf is a dependency of LunarVim?

**Comment by abzcoding** [comment]
> Wait...Doesn`t that mean that the manual installation of fzf is not needed, since fzf is a dependency of LunarVim?

yes, it was added a while back

**Comment by alexzaizar09** [comment]
> > @abzcoding You know the codebase better than me. Is there a variable in the config for setting the fzf path?
> > Just for the sake of doing it, could you guys do the following: `:PackerSync`-> `:UpdateRemotePlugins` -> `:LvimUpdate` -> `:LvimCacheReset` -> `:PackerCompile` Also, could you guys test the following command from within LunarVim: `:!fzf --version`
> 
> as far as i know, this is the only thing we do about fzf
> 
> https://github.com/LunarVim/LunarVim/blob/6b3e0574a3d2577f8c0558144202ba12f3978cae/lua/lvim/plugins.lua#L27-L31

all this suggestion get in a loop trying to load fzf which throws the same error that the extension is not installed. Nevertheless, when I run `:!fzf --version` it throws this `:!fzf --version
0.28.0 (brew)` so it is there

**Comment by kylo252** [comment]
## Again, this has nothing to do with having the `fzf` binary installed or not, it's about https://github.com/nvim-telescope/telescope-fzf-native.nvim

Try this please: 

```shell
:! make -C $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim
```

You can also do `make clean`  just to be sure

```shell
:! cd $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim && make clean && make
```

**Comment by alexzaizar09** [comment]
> ## Again, this has nothing to do with having the `fzf` binary installed or not, it's about https://github.com/nvim-telescope/telescope-fzf-native.nvim
> Try this please:
> 
> ```shell
> :! make -C $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim
> ```
> 
> You can also do `make clean` just to be sure
> 
> ```shell
> :! cd $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim && make clean && make
> ```

thanks

**Comment by kylo252** [comment]
For those of you on Windows, could you try setting up MSYS2 with this script? https://gist.github.com/kylo252/a0e799c9bf269093d715b5dec3e37eb4

**Comment by DerrikMilligan** [comment]
For me, I needed to make sure that I had the `make` and `mingw` tools installed and then ran the `install.ps1` script again and was able to get it working.

**Comment by dimitarvdimitrov** [comment]
> ## Again, this has nothing to do with having the `fzf` binary installed or not, it's about https://github.com/nvim-telescope/telescope-fzf-native.nvim
> Try this please:
> 
> ```shell
> :! make -C $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim
> ```
> 
> You can also do `make clean` just to be sure
> 
> ```shell
> :! cd $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim && make clean && make
> ```

Thanks for the workaround. I had to modify it slightly for my M1

```shell
arch -arm64 make -C $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim
```

**Comment by kylo252** [comment]
> Thanks for the workaround. I had to modify it slightly for my M1
> 
> ```shell
> arch -arm64 make -C $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim
> ```

It's a good idea to upstream the fix if it's needed. The Makefile should pick the correct compiler out of the box.

**Comment by younger-1** [comment]
@kylo252 Could you try [this plugin](https://github.com/natecraddock/telescope-zf-native.nvim) instead of `telescope-fzf-native`?
It worked out of box because it shift compiled sorters for linux/windows/macOS written by `zig`

**Comment by dietrich** [comment]
On windows 10 issue is the missing libfzf.dll file:
1) from lvim :echo $LUNARVIM_RUNTIME_DIR finds the runtime directory (if you don't know where it is)
2)cd $LUNARVIM_RUNTIME_DIR\site\pack\packer\start\telescope-fzf-native.nvim
3) mkdir build (if it doesn't exisit)

3) gcc -O3 -Wall -Werror -fpic -shared src/fzf.c -o build/libfzf.dll

**Comment by kylo252** [comment]
> @kylo252 Could you try [this plugin](https://github.com/natecraddock/telescope-zf-native.nvim) instead of `telescope-fzf-native`? It worked out of box because it shift compiled sorters for linux/windows/macOS written by `zig`

Isn't it a completely different plugin tho? It seems that you still need a compiler either way, `zig` in this case.

**Comment by younger-1** [comment]
> Isn't it a completely different plugin tho? It seems that you still need a compiler either way, `zig` in this case.

It is an alternative to `telescope-fzf-native`.  As https://github.com/natecraddock/telescope-zf-native.nvim mentioned in project's readme: "Pre-compiled libzf binaries are included.", so you don't need a zig compiler. It include a submodule of https://github.com/natecraddock/zf

**Comment by Sparkenstein** [comment]
as mentioned above as well as in [this comment](https://github.com/nvim-telescope/telescope-fzf-native.nvim/issues/43#issuecomment-1020653830) running `make` solves the problem even on windows. 

I just ran `choco install make` and ran `make` in the directory where `telescope-fzf-native` plugin is. solved the issue for me.
100% not lunarvim issue!

**Comment by abzcoding** [comment]
should be fixed via #2330

**Comment by MostHated** [comment]
> That seems to show that the issue (at least for me, on an M1 chip) was to rebuild telescope-fzf-native.nvim as described in [nvim-telescope/telescope-fzf-native.nvim#23](https://github.com/nvim-telescope/telescope-fzf-native.nvim/issues/23). Not sure what the problem on Windows could be though.

Following the steps here fixed it for me in a Win10 VM. TL;DR go to nvim package install dir, (Ex: AppData\Local\nvim-data\site\pack\packer\start\telescope-fzf-native.nvim\) and run `make clean` followed by `make` and was good to go. :+1:

**Comment by koslak** [comment]
Hi, for those who are facing this issue on Windows, what is happening is that the _telescope-fzf-native.nvim_ plugin is not being built. You can check this by doing this:

1. Open a CMD window and go to the plugin's folder:

`> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim`

2. Go to the `build` folder and then you will see that is empty. 

**The following are the steps that I did to make it work:** 

1. Open a CMD window and go to the plugin's folder:

`> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim`

2. Run the following command (make sure you have the dependencies installed (like cmake) to build this plugin):

`> cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build`

**Note:** The instruction above is from the Github repository: [telescope-fzf-native.nvim github](https://github.com/nvim-telescope/telescope-fzf-native.nvim#cmake-windows-linux-macos).

3. Make sure the plugin was built. Go to the folder:

`> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim\build\Release`
`> dir`

and now you should see the following files: 

```
24-Feb-23  11:27 PM    <DIR>          .
24-Feb-23  11:27 PM    <DIR>          ..
24-Feb-23  11:27 PM             2,796 fzf.exp
24-Feb-23  11:27 PM             4,620 fzf.lib
24-Feb-23  11:27 PM            22,016 libfzf.dll
               3 File(s)         29,432 bytes
```

4. Now open Nvim and run the command `:PackerSync`

**Comment by Weizhe-Chen** [comment]
> ## Again, this has nothing to do with having the `fzf` binary installed or not, it's about https://github.com/nvim-telescope/telescope-fzf-native.nvim
> Try this please:
> 
> ```shell
> :! make -C $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim
> ```
> 
> You can also do `make clean` just to be sure
> 
> ```shell
> :! cd $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim && make clean && make
> ```

On MacBook Pro M1 Ventura, I encountered the following error using `make` or `arch -arm64 make`:
mkdir -p build
/opt/homebrew/bin/gcc-11 -O3 -Wall -Werror -fpic -std=gnu99 -shared src/fzf.c -o build/libfzf.so
make: /opt/homebrew/bin/gcc-11: No such file or directory
make: *** [build/libfzf.so] Error 1

I have to set the CC variable in Makefile to gcc:

```make
CFLAGS += -Wall -Werror -fpic -std=gnu99

ifeq ($(OS),Windows_NT)
    CC = gcc
    TARGET := libfzf.dll
ifeq (,$(findstring MSYS,$(MSYSTEM)))
	# On Windows, but NOT msys
    MKD = cmd /C mkdir
    RM = cmd /C rmdir /Q /S
else
    MKD = mkdir -p
    RM = rm -rf
endif
else
    MKD = mkdir -p
    RM = rm -rf
    TARGET := libfzf.so
endif

# I added the following line
CC = gcc

```

**Comment by Omixxx** [comment]
For nvchad users, you have to run `cd ~/.local/share/nvim/lazy/telescope-fzf-native.nvim && make` and you're should be good to go ✨

**Comment by HermesSantos** [comment]
For windows users, there is a problem with the gcc compiler and fzf, what solved my problem:
I used a specific branch for the fzf, this one "2330a7eac13f9147d6fe9ce955cb99b6c1a0face". You can use like this:
{ "nvim-telescope/telescope-fzf-native.nvim", commit = "2330a7eac13f9147d6fe9ce955cb99b6c1a0face", optional = true} (adapt it to your packer manager).
I found this solutions here https://github.com/nvim-telescope/telescope-fzf-native.nvim/issues/43#issuecomment-1126993613

**Comment by sanzhang007** [comment]
我系统是windows amd64
我遇到的是这种情况 MINGW64中gcc 编译 后
 'C:/Users/zs/AppData/Local/nvim-data/lazy/telescope-fzf-native.nvim/lua/../build/libfzf.dll': %1 不是有效的 Win32 应用程序。
然后我用scoop 下载gcc 用下载后的gcc编译，就ok啦

**Comment by lamteteeow** [comment]
> Hi, for those who are facing this issue on Windows, what is happening is that the _telescope-fzf-native.nvim_ plugin is not being built. You can check this by doing this:
> 
> 1. Open a CMD window and go to the plugin's folder:
> 
> `> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim`
> 
> 2. Go to the `build` folder and then you will see that is empty.
> 
> **The following are the steps that I did to make it work:**
> 
> 1. Open a CMD window and go to the plugin's folder:
> 
> `> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim`
> 
> 2. Run the following command (make sure you have the dependencies installed (like cmake) to build this plugin):
> 
> `> cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build`
> 
> **Note:** The instruction above is from the Github repository: [telescope-fzf-native.nvim github](https://github.com/nvim-telescope/telescope-fzf-native.nvim#cmake-windows-linux-macos).
> 
> 3. Make sure the plugin was built. Go to the folder:
> 
> `> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim\build\Release` `> dir`
> 
> and now you should see the following files:
> 
> ```
> 24-Feb-23  11:27 PM    <DIR>          .
> 24-Feb-23  11:27 PM    <DIR>          ..
> 24-Feb-23  11:27 PM             2,796 fzf.exp
> 24-Feb-23  11:27 PM             4,620 fzf.lib
> 24-Feb-23  11:27 PM            22,016 libfzf.dll
>                3 File(s)         29,432 bytes
> ```
> 
> 4. Now open Nvim and run the command `:PackerSync`

amazing! Thank you so much. Works like a charm.

**Comment by p6laris** [comment]
> Hi, for those who are facing this issue on Windows, what is happening is that the _telescope-fzf-native.nvim_ plugin is not being built. You can check this by doing this:
> 
> 1. Open a CMD window and go to the plugin's folder:
> 
> `> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim`
> 
> 2. Go to the `build` folder and then you will see that is empty.
> 
> **The following are the steps that I did to make it work:**
> 
> 1. Open a CMD window and go to the plugin's folder:
> 
> `> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim`
> 
> 2. Run the following command (make sure you have the dependencies installed (like cmake) to build this plugin):
> 
> `> cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build`
> 
> **Note:** The instruction above is from the Github repository: [telescope-fzf-native.nvim github](https://github.com/nvim-telescope/telescope-fzf-native.nvim#cmake-windows-linux-macos).
> 
> 3. Make sure the plugin was built. Go to the folder:
> 
> `> cd %AppData%\..\Local\nvim-data\site\pack\packer\opt\telescope-fzf-native.nvim\build\Release` `> dir`
> 
> and now you should see the following files:
> 
> ```
> 24-Feb-23  11:27 PM    <DIR>          .
> 24-Feb-23  11:27 PM    <DIR>          ..
> 24-Feb-23  11:27 PM             2,796 fzf.exp
> 24-Feb-23  11:27 PM             4,620 fzf.lib
> 24-Feb-23  11:27 PM            22,016 libfzf.dll
>                3 File(s)         29,432 bytes
> ```
> 
> 4. Now open Nvim and run the command `:PackerSync`

Thanks

**Comment by whj768702** [comment]
> ## Again, this has nothing to do with having the `fzf` binary installed or not, it's about https://github.com/nvim-telescope/telescope-fzf-native.nvim
> Try this please:
> 
> ```shell
> :! make -C $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim
> ```
> 
> You can also do `make clean` just to be sure↳
> 
> ```shell
> :! cd $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim && make clean && make
> ```

it really helped.

**Comment by Barmaley0** [comment]
> > Кажется, это показывает, что проблема (по крайней мере, для меня, на чипе M1) заключалась в пересборке Telescope-fzf-native.nvim, как описано в [nvim-telescope/telescope-fzf-native.nvim#23](https://github.com/nvim-telescope/telescope-fzf-native.nvim/issues/23) . Не уверен, в чем может быть проблема в Windows.
> 
> Выполнение описанных здесь шагов исправило это для меня на виртуальной машине Win10. TL;DR перейдите в каталог установки пакета nvim (например: AppData\Local\nvim-data\site\pack\packer\start\telescope-fzf-native.nvim) и запустите, а `make clean`затем `make`все готово. 👍

GOOOD! it works!!!!

**Comment by MrShortcut** [comment]
Delete in the AppData/Local/ folder NVIM-DATA and INSTALL Dependenncies

scoop install gcc
scoop install fd
scoop install make
scoop install cmake

Open Neovim Enjoy!
