### ISSUE TITLE
[Bug] eslint_d not working as a formatter

### ISSUE THREAD

**Issue by kylo252** [LunarVim/LunarVim#1808]
> This is what I see using my config:

LvimInfo Output:
![image](https://user-images.githubusercontent.com/11343499/137938199-108381ad-2072-4587-8d03-b16156833576.png)

Linting suggestions work:
![image](https://user-images.githubusercontent.com/11343499/137939353-f587a68f-e687-400b-bbea-60cf011ad2c7.png)

> However, autofix does not work, which is in-line with what `LvimInfo` is saying about `eslint_d` not being a supported formatter. Does `eslint_d` work as a formatter for you?

_Originally posted by @OliverNChalk in https://github.com/LunarVim/LunarVim/issues/1706#issuecomment-946825630_

**Comment by OliverNChalk** [comment]
c4a85b32752e1ca41c6d9a2613b9d2e75dbf463d - i'm on this commit now and `eslint_d` works for me

**Comment by kingedward35** [comment]
Getting the same behavior. Eslint_d also doesn't work as a linter at the same time. I basically had to uninstall my lunarvim, but now I can't seem to get it to work at all. Does anyone know how to install an earlier version of Lunarvim? I tried to download the v0.5.1 source code and build from that, but I can't seem to find instructions for it. As of now I don't have a working version of Lunarvim so I would like to get one going ASAP. Without the eslint support, I effectively can't use this.

**Comment by kingedward35** [comment]
Somehow got this working today by manually updating my config with the latest config settings.
