### ISSUE TITLE
[Bug]: restore support for julials

### ISSUE THREAD

**Issue by 00sapo** [LunarVim/LunarVim#1853]
### Problem description

1. julials doesn't start automatically
2. pylsp and jedi_language_server try to start automatically, even if no executable is available

I can't disbale the second, while I can change the first by calling `require'lspconfig'.julials.setup{})`

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

f07ab6a

### Neovim version (>= 0.5)

0.5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by mjlbach** [comment]
That script is out of date, you should prefer the one upstream in lspconfig already https://github.com/neovim/nvim-lspconfig/blob/08a698d652f3d1fc6195b4efd9d23ecaced2c879/lua/lspconfig/julials.lua#L10-L40

**Comment by eo1989** [comment]
> That script is out of date, you should prefer the one upstream in lspconfig already https://github.com/neovim/nvim-lspconfig/blob/08a698d652f3d1fc6195b4efd9d23ecaced2c879/lua/lspconfig/julials.lua#L10-L40

Is this still valid? Just checked lspconfig's branches and it looks like they've all been pruned.

**Comment by mjlbach** [comment]
It's an lspconfig built-in, you don't need to do anything manually to use it. The server configurations were all moved to lspconfig/server_configurations

**Comment by kylo252** [comment]
Fixed in https://github.com/LunarVim/lunarvim.org/pull/153
