### ISSUE TITLE
[Feature]: Automatically update git file status and nvim-tree after lazygit window is closed

### ISSUE THREAD

**Issue by gikari** [LunarVim/LunarVim#1854]
### Feature motivation

When working with Lazygit, quite frequently files are updated. However, the new files' status are not shown after I close a lazygit window after commit or branch change. To fix this I need to manually press R to reload a tree.

### Describe the expected solution

LunarVim automatically updates the nvim-tree and hunks inside an opened file, once the lazygit window is closed.

### Additional context

Maybe it's also useful for general floating terminal windows, since in them anything could be changed, so it's useful to reload the files and tree, that could be affected.

**Comment by abzcoding** [comment]
Basically, we are at the mercy of nvim-tree.lua here, so i'm closing this since there is not much we can do unless it is fixed upstream
