### ISSUE TITLE
[Feature]: GitHub Copilot

### ISSUE THREAD

**Issue by Moelf** [LunarVim/LunarVim#1856]
### Feature motivation

https://github.com/github/copilot.vim#getting-started

**Comment by abzcoding** [comment]
just in case, here is how i use it in my own config
https://github.com/abzcoding/lvim/blob/377f7ee64bd483f33ac724eba91b581b4d18fba1/lua/user/builtin.lua#L49

**Comment by gelfand** [comment]
It's fine with `cmp-copilot`.
```lua
lvim.builtin.sell_soul_to_devel = true

lvim.plugins = {
	{
		"github/copilot.vim",
		disable = not lvim.builtin.sell_soul_to_devel,
		config = function ()
			-- copilot assume mapped
			vim.g.copilot_assume_mapped = true
		end
	},
	{
		"hrsh7th/cmp-copilot",
		disable = not lvim.builtin.sell_soul_to_devel,
		config = function ()
			lvim.builtin.cmp.formatting.source_names["copilot"] = "(Cop)"
			table.insert(lvim.builtin.cmp.sources, {name = "copilot"})
		end
	},
}
```
But to make Copilot's virtual text not collide with cmp's ghost text, I had to remove [these](https://github.com/gelfand/copilot.vim/commit/099387d6a67a5943065613f6f6a1da9f3b116610) three lines.

**Comment by gonzaloserrano** [comment]
thx a ton @gelfand! That fixed issues I had with prev solutions where snippets navigation was not working.

**Comment by yueyingjuesha** [comment]
I don't have copilot installed but I still got this wired <Plug>(cmp.u.k.recursive:
) innserted
