### ISSUE TITLE
Autopairs error??? 

### ISSUE THREAD

**Issue by codewizkid** [LunarVim/LunarVim#1861]
After updating all the packages, I'm getting a weird error about "running config nvim-autopairs". It says the problem is located at packer_complied.lua on line 63. When I go to that file, theirs an LSP error on line 60 with this code block `  local success, result = pcall(loadstring(s))` stating that `loadstring` is deprecated. I have ZERO idea how to fix this issue...

**Comment by codewizkid** [comment]
That worked, but now it says function nvim-autopairs.completion.cmp setup is deprecated. remove this function and use require ("cmp").setup to add <cr> mapping. How do i do this? Sorry for noob questions...

**Comment by abzcoding** [comment]
> That worked, but now it says function nvim-autopairs.completion.cmp setup is deprecated. remove this function and use require ("cmp").setup to add mapping. How do i do this? Sorry for noob questions...

no worries 😄 

```sh
# check your branch (it should be rolling)
git -C ~/.local/share/lunarvim/lvim status

# check latest commit ( it should be 891cf9944a9f18badffec0c32442610d91f0e96b )
git -C ~/.local/share/lunarvim/lvim rev-parse HEAD
```

**Comment by abzcoding** [comment]
<img width="465" alt="Screen Shot 2021-10-29 at 9 34 00 PM" src="https://user-images.githubusercontent.com/10992695/139481828-ebe0ee80-438f-44db-bc7c-730df3e0a505.png">

**Comment by abzcoding** [comment]
basically the fixed got merged in the `rolling` branch, and if you are on that you should not see the error anymore

**Comment by codewizkid** [comment]
I'm on the master branch. How do i get back to rolling?

**Comment by abzcoding** [comment]
> I'm on the master branch. How do i get back to rolling?
can you try this?
```sh
# to get all remotes
git -C ~/.local/share/lunarvim/lvim fetch --all
# to switch to rolling
git -C ~/.local/share/lunarvim/lvim checkout rolling
```

**Comment by codewizkid** [comment]
Got it back to rolling! Do i just repeat the pull command? It says I'm uptodate but that new error is still there...

**Comment by abzcoding** [comment]
> Got it back to rolling! Do i just repeat the pull command? It says I'm uptodate but that new error is still there...

yeah make sure you are on this
```lua
# check latest commit ( it should be 891cf9944a9f18badffec0c32442610d91f0e96b )
git -C ~/.local/share/lunarvim/lvim rev-parse HEAD
```

**Comment by codewizkid** [comment]
Odd, last commit for me is 1f2167df0ea3f837c9c78a0137a888ca05e5e83a

**Comment by abzcoding** [comment]
> Odd, last commit for me is [1f2167d](https://github.com/LunarVim/LunarVim/commit/1f2167df0ea3f837c9c78a0137a888ca05e5e83a)

so you are still on master branch 😢

**Comment by codewizkid** [comment]
whats odd is that when i use the git -C ~/.local/share/lunarvim/lvim status command it says i'm on the branch rolling...

**Comment by abzcoding** [comment]
> whats odd is that when i use the git -C ~/.local/share/lunarvim/lvim status command it says i'm on the branch rolling...


fuck maybe you need 
```sh
cd  ~/.local/share/lunarvim/lvim
git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin
git checkout origin/rolling
git pull
```

**Comment by codewizkid** [comment]
IT WORKED!!!!! Thank you SOOOOOO much for your help man!

**Comment by kylo252** [comment]
For future reference, you can do <leader>LI to see the changelog. We should probably create some kind of `LvimChangeLog`
