### ISSUE TITLE
[Bug]: Autoindent not working with python

### ISSUE THREAD

**Issue by ayush-1506** [LunarVim/LunarVim#1867]
### Problem description

asciinema recording here: https://asciinema.org/a/HatGuP7ARTYUKTJId1H3IYZhp . scroll jumps to start of newline rather than the expected indent position

using nvim v0.5.1.

I believe this used to work until a few days back. Reinstalling nvim, lunarvim doesn't help. Pyright also seems active.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ayush-1506** [comment]
Thanks, that seems to work. Maybe this should be a default setting in `.config/lvim/config.lua` ?

**Comment by abzcoding** [comment]
> Thanks, that seems to work. Maybe this should be a default setting in `.config/lvim/config.lua` ?

hopefully it gets fixed in the upstream treesitter in the newer version, we are waiting for that tbh ( currently we are on the "0.5-compat" branch)
https://github.com/LunarVim/LunarVim/blob/891cf9944a9f18badffec0c32442610d91f0e96b/lua/lvim/plugins.lua#L70-L74

**Comment by FinallyFinancialFreedom** [comment]
> can you try adding this to your config?
> 
> ```lua
> -- treesitter is buggy :(
> lvim.builtin.treesitter.indent = { enable = true, disable = { "python" } }
> ```

treesitter indent messes up python all the time even now , disable it forever.
