### ISSUE TITLE
help me remove vim.opt.clipboard

### ISSUE THREAD

**Issue by Leiyi548** [LunarVim/LunarVim#1871]
I don't know how to cancel this setting in lunarvim
![image](https://user-images.githubusercontent.com/76139422/139524405-c5520ba0-9397-420a-8043-626c3ad8fc41.png)

**Comment by abzcoding** [comment]
for future references, you can override those using the normal neovim way
```lua
vim.opt.clipboard = "whatever you want"
```

**Comment by Leiyi548** [comment]
@abzcoding  Thankyou!  I set vim.opt.clipboard = ""
