### ISSUE TITLE
Help me add vscode snippets to luasnip🙏🏻🙏🏻

### ISSUE THREAD

**Issue by Leiyi548** [LunarVim/LunarVim#1872]
![image](https://user-images.githubusercontent.com/76139422/139526537-4f521a7a-0d0f-43e3-bebb-b309efd5bbbf.png)
This is my snippet directory.
![image](https://user-images.githubusercontent.com/76139422/139526551-e8df1916-7684-4f4f-8b5e-23dd2140692f.png)
I add snippets but not working.
How to set luasnip to work?

**Comment by abzcoding** [comment]
first create the `vscodesnips` folder and the package.json inside it
```sh
mkdir ~/.config/lvim/vscodesnips
touch ~/.config/lvim/vscodesnips/package.json
touch ~/.config/lvim/vscodesnips/lua.json
```
fill package.json with sth like this
```json
{
  "name": "nvim-snippets",
  "author": "abzcoding",
  "engines": {
    "vscode": "^1.11.0"
  },
  "contributes": {
    "snippets": [
      {
        "language": "lua",
        "path": "./lua.json"
      }
    ]
  }
}
```
then you can create your snippets inside the lua.json file for example
```json
{
  "it": {
    "prefix": "it",
    "body": ["it('should ${1:do something}', function()", "\t${2}", "end)"]
  },
  "describe": {
    "prefix": "describe",
    "body": ["describe('${1:Title}', function()", "\t${2}", "end)"]
  },
  "doc": {
    "prefix": "doc",
    "body": [
      "-----------------------------------------------------------------------------//",
      "-- ${0:document}",
      "-----------------------------------------------------------------------------//"
    ]
  },
}
```
and enjoy using them

**Comment by Leiyi548** [comment]
@abzcoding Thank you very much. I successfully customized the code fragment

**Comment by hawkinchina** [comment]
how to  add snippets from a framework to a filetype with 
[friendly-snippets](https://github.com/rafamadriz/friendly-snippets) ?

------------------config of friendly-snippets--------
require'luasnip'.filetype_extend("ruby", {"rails"}) 
require'luasnip'.filetype_extend("typescript", {"angular"}) 
require'luasnip'.filetype_extend("typescript", {"nestjs"}) 
-------------------------------------------------
add this config directly to. ~/.config/lvim/config.lua ??

**Comment by abzcoding** [comment]
> @abzcoding how to add snippets from a framework to a filetype with [friendly-snippets](https://github.com/rafamadriz/friendly-snippets) ?
> 
> * config of friendly-snippets:
> 
> ```
> require'luasnip'.filetype_extend("ruby", {"rails"}) 
> require'luasnip'.filetype_extend("typescript", {"angular"}) 
> require'luasnip'.filetype_extend("typescript", {"nestjs"}) 
> ```
> 
> add this config directly to. ~/.config/lvim/config.lua ?

yes

**Comment by hawkinchina** [comment]
thanks a lot.
