### ISSUE TITLE
The functions of the language server are unresponsive,

### ISSUE THREAD

**Issue by ztby74** [LunarVim/LunarVim#1877]
### Problem description

It is difficult for unfamiliar users to understand your documents,
The language server is installed, but the function is not reflected
What should I do?
Your document says server configuration reference   https://github.com/tamago324/nlsp-settings.nvim,   only lua , No more cases were given,
I feel like I'm in a bottomless pit

### LunarVim version

current version

### Neovim version (>= 0.5)

5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ujjwal3067** [comment]
You have no screenshots and no relevant log output. Please update your description before anyone can help you.

**Comment by abzcoding** [comment]
i didn't fully understand the issue but here are some resources on the matter ( from [lunarvim.org](https://www.lunarvim.org/languages/#server-configuration) )

1. if you want to customize some stuff that are support by [nlsp-settings](https://github.com/tamago324/nlsp-settings.nvim):
<img width="833" alt="Screen Shot 2021-10-31 at 7 28 18 PM" src="https://user-images.githubusercontent.com/10992695/139592011-a349ca47-e6cf-4bf0-bab8-2de3e2189087.png">

2. if you want to change other stuff or use language specific plugins
<img width="814" alt="Screen Shot 2021-10-31 at 7 29 04 PM" src="https://user-images.githubusercontent.com/10992695/139592058-91d1052a-6252-48b6-b0b9-5e760f3e229c.png">
