### ISSUE TITLE
[Bug]: "lvim" won't start LunarVim

### ISSUE THREAD

**Issue by TheAwesomeGuy47** [LunarVim/LunarVim#1878]
### Problem description

I have tried editing the `.bashrc` in my `/home/theawesomeguy47/` directory with the following:

`export PATH="/home/theawesomeguy47/.local/bin/lvim:$PATH"`

And when I type `lvim` in my terminal (I am using KDE Plasma on Arch Linux so my terminal is Konsole) it just says `bsah: lvim: command not found`

Thanks!

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.5.1

### Screenshots

![image](https://user-images.githubusercontent.com/77284265/139553732-b7fe139e-5490-49f9-a3b5-8bb385fb35dc.png)
![image](https://user-images.githubusercontent.com/77284265/139553743-f8a0b82c-262d-4a3f-a3ae-46fc913a38b2.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Use `ls /home/theawesomeguy47/.local/bin` to make sure there's actually something in that folder.  
Use `echo $PATH` to print out the contents of the path environmental variable.  

If you haven't already restarted your terminal, make sure to do so.  Or manually  `source ~/.bashrc`.  That file gets read when you start a new terminal session.

**Comment by TheAwesomeGuy47** [comment]
Will try that. I did restart my terminal, although I didn't try `source ./bashrc`

**Comment by ujjwal3067** [comment]
> Will try that. I did restart my terminal, although I didn't try `source ~./bashrc`

you have to source or it won't work unless you restart your terminal

**Comment by TheAwesomeGuy47** [comment]
My distribution for Linux is now Manjaro and it automatically created the `lvim` command.

Thanks for helping though, @rebuilt and @ujjwal3067!

**Comment by Alban-Kaperi** [comment]
> export PATH="/home/theawesomeguy47/.local/bin/lvim:$PATH"

You are doing it wrong, replace it with the line below.
**export PATH="/home/theawesomeguy47/.local/bin:$PATH"**

**Comment by TheAwesomeGuy47** [comment]
I also recently discovered that.

**Comment by Soetch** [comment]
> Use `ls /home/theawesomeguy47/.local/bin` to make sure there's actually something in that folder. Use `echo $PATH` to print out the contents of the path environmental variable.
> 
> If you haven't already restarted your terminal, make sure to do so. Or manually `source ~/.bashrc`. That file gets read when you start a new terminal session.

God, this saved me an entire afternoon. Thanks man !

**Comment by r3d-b0y** [comment]
![Create Path](https://user-images.githubusercontent.com/63814819/208306113-deea9786-6718-4338-92b5-78cc52128ef9.png)
![Load the Path](https://user-images.githubusercontent.com/63814819/208306119-f4aa29e1-fff6-4826-a72c-90649387a4dd.png)
 
i got same issue with trying create PATH, reaload and reopen my terminal but still not working :)

**Comment by daveinwords** [comment]
> > export PATH="/home/theawesomeguy47/.local/bin/lvim:$PATH"
> 
> You are doing it wrong, don't include lvim in the path, replace it with the line below. **export PATH="/home/theawesomeguy47/.local/bin:$PATH"**

This is actually the best fix. Thanks.

**Comment by Kh1ng** [comment]
This fix worked for me temporarily. However, npm freaks out when .local is on the path, leading to issues later. I spent a while tracking it down and had to uninstall npm, angular, and some other nonsense, delete the path entry, then some node modules, and reinstall.

Error message I was getting was:
The relative path ‘~/.local/bin/’ is included in the PATH environment variable, which is insecure in combination with the -execdir action of find.  Please remove that entry from $PATH

After we were back to square one, I ended up making an alias:
#lvim
alias lvim='~/.local/bin/lvim'

and it seems to make everyone happy for now. Hopefully, this can save someone else a headache in the future.

**Comment by hernandezluise** [comment]
> For me, a Mac user, I tried putting this everywhere and found that:
> 
> **THESE DID NOT WORK**
> 
> * Putting it in `/home/`
> * Putting it in `.bash_profile` or `.bashrc`
> 
> **THIS WORKED ON _MAC M2_ **
> 
> * Putting it in `/Users/_user_/.local/bin`
> 
> As a step by step that I did to make it work for me and assuming the user is called johnwick:
> 
> 1. open terminal
> 2. type in `nvim ~/.zshrc`
>    
>    1. use whatever editor, but assuming you have vim installed as this is LunarVim...
> 3. put `export PATH="/Users/johnwick/.local/bin:$PATH"`
> 4. save the file
> 
> ... 5. try to exit Vim 6. shut down your computer because you can't close out of vim 7. install Notepad++

This actually work for me on mac with zsh

**Comment by esslamben** [comment]
You can just update the first line in your .zshrc to 
```
# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.local/bin:$HOME/bin:/usr/local/bin:$PATH
```

I've added the extra `$HOME/.local/bin`which is where the lvim bin is stored. You technically only need that bit to get this working.

**Comment by lognorman20** [comment]
> For me, a Mac user, I tried putting this everywhere and found that:
> 
> **THESE DID NOT WORK**
> 
> * Putting it in `/home/`
> * Putting it in `.bash_profile` or `.bashrc`
> 
> **THIS WORKED ON _MAC M2_ **
> 
> * Putting it in `/Users/_user_/.local/bin`
> 
> As a step by step that I did to make it work for me and assuming the user is called johnwick:
> 
> 1. open terminal
> 2. type in `nvim ~/.zshrc`
>    
>    1. use whatever editor, but assuming you have vim installed as this is LunarVim...
> 3. put `export PATH="/Users/johnwick/.local/bin:$PATH"`
> 4. save the file
> 
> ... 5. try to exit Vim 6. shut down your computer because you can't close out of vim 7. install Notepad++

worked for me as well!

**Comment by Aman2233** [comment]
so I had the same exact problem with people following steps and not working, when I got oh-my-zsh I had ended up getting the .zshrc file, when I took a look at the top comment " If you come from bash you might have to change your $PATH.
# export PATH=/Users/amanueal/.local/bin:$PATH" it was uncommented and even after copying the same exact comment it didn't work so if you have .zshrc and .zshenv like myself try commenting off .zshrc, that worked for me

**Comment by sardine-bro** [comment]
> You can just update the first line in your .zshrc to
> 
> ```
> # If you come from bash you might have to change your $PATH.
> export PATH=$HOME/.local/bin:$HOME/bin:/usr/local/bin:$PATH
> ```
> 
> I've added the extra `$HOME/.local/bin`which is where the lvim bin is stored. You technically only need that bit to get this working.

This worked for my M1 Macbook using zshrc
- just add it to the top of your .zshrc config

**Comment by tahajalili** [comment]
> For me, a Mac user, I tried putting this everywhere and found that:
> 
> **THESE DID NOT WORK**
> 
> * Putting it in `/home/`
> * Putting it in `.bash_profile` or `.bashrc`
> 
> **THIS WORKED ON _MAC M2_ **
> 
> * Putting it in `/Users/_user_/.local/bin`
> 
> As a step by step that I did to make it work for me and assuming the user is called johnwick:
> 
> 1. open terminal
> 2. type in `nvim ~/.zshrc`
>    
>    1. use whatever editor, but assuming you have vim installed as this is LunarVim...
> 3. put `export PATH="/Users/johnwick/.local/bin:$PATH"`
> 4. save the file
> 
> ... 5. try to exit Vim 6. shut down your computer because you can't close out of vim 7. install Notepad++

You're a lifesaver!
