### ISSUE TITLE
[Bug]: "go to definition" doesn't work for `vim.cmd` in autocmds.lua

### ISSUE THREAD

**Issue by Dieterbe** [LunarVim/LunarVim#1884]
### Problem description

i have installed 'lua' support.
When looking at the lunarvim source code, in particular the below section in autocmds.lua, when I hit `gd` with cursor on `pairs()`, it takes me to the declaration of the pairs function, but doing the same with the cursor on `vim.cmd` does nothing.
i would expect to navigate to where `vim.cmd` is set.

thank you.

```
function M.define_augroups(definitions) -- {{{1
  -- Create autocommand groups based on the passed definitions
  --
  -- The key will be the name of the group, and each definition
  -- within the group should have:
  --    1. Trigger
  --    2. Pattern
  --    3. Text
  -- just like how they would normally be defined from Vim itself
  for group_name, definition in pairs(definitions) do
    vim.cmd("augroup " .. group_name)
    vim.cmd "autocmd!"

    for _, def in pairs(definition) do
      local command = table.concat(vim.tbl_flatten { "autocmd", def }, " ")
      vim.cmd(command)
    end

    vim.cmd "augroup END"
  end
end

```

### LunarVim version

95d8127f319d135001eb3fd07b30db3fd43d7ee4

### Neovim version (>= 0.5)

0.5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
`gd` basically runs 
```vim
:lua vim.lsp.buf.definition()
```
are you able to goto definition of that in a normal neovim ( outside of lunarvim) ?

**Comment by Dieterbe** [comment]
Hi Abouzar,
I don't have a normal neovim with lsp set up at this time, although at some point I will try that out.
For now, just wanted to confirm that, in lunarvim...
```
vim.cmd
 ^ cursor here -> go to definition works, via `gd` and also via `:lua vim.lsp.buf.definition()`
vim.cmd
     ^ cursor here -> go to definition does not work, via `gd` and neither via `:lua vim.lsp.buf.definition()`
```

**Comment by abzcoding** [comment]
if you want a working and minimal neovim config to test it out
use this https://github.com/mjlbach/defaults.nvim
and clone it to your `~/.config/nvim`
to check if the same happens in that as well or not

**Comment by Dieterbe** [comment]
Thanks. the kickstart.nvim config has the exact same problem as described above.

**Comment by abzcoding** [comment]
> Thanks. the kickstart.nvim config has the exact same problem as described above.


it might be because the `cmd` part is implemented in c and has no source code in lua, i have no idea though

so i think we can close this issue, since it seems like an issue in sumneko_lua lang server or nvim-lspconfig and not specific to lunarvim

**Comment by Dieterbe** [comment]
thanks @abzcoding for your help. have a nice day!
