### ISSUE TITLE
[Bug]: SegFault using file explorer

### ISSUE THREAD

**Issue by mandaputtra** [LunarVim/LunarVim#1888]
### Problem description

1. Find project with lots of file, I suggest vscode repository https://github.com/microsoft/vscode
2. Use CTRL + F
3. find some files and then LunarVim stopped working, 

![Screenshot from 2021-11-01 15-44-03](https://user-images.githubusercontent.com/23342943/139645899-0229e216-7c04-48af-ae7f-f4c187f8a432.png)

### LunarVim version

rolling

### Neovim version (>= 0.5)

NVIM v0.5.0-dev+1455-gf83c25942

### Relevant log output

```shell
Please tell me how to get the log from segfault error messages, I will edit or add more detail.
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Are you on Windows? Does the same issue occur if you disable fzf-native?

```lua
lvim.builtin.telescope.extensions.fzf = nil
```

**Comment by mandaputtra** [comment]
On linux, let me see

**Comment by mandaputtra** [comment]
Fixed! with the options enabled

**Comment by kylo252** [comment]
@mandaputtra, I think it would be good to follow up on this issue on https://github.com/nvim-telescope/telescope-fzf-native.nvim, even if it's just a bug report to let the developers know about it.
