### ISSUE TITLE
[Bug]: All LSP servers starting for javascript filetypes

### ISSUE THREAD

**Issue by andreicorpo** [LunarVim/LunarVim#1889]
### Problem description

When I enter a javascript file, a lot of lsps start:
- tsserver
- ember
- denols
- eslint
- stylelint_lsp
- tailwindcss

Even though I changed the file from `lunarvim/after/ftplugin/javascript.lua` to only have this line:
``` lua
require("lvim.lsp.manager").setup("tsserver")
```

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [x] The programs specified by the config are installed

### LunarVim version

rolling - commit `e8693406q

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+nightly-840-g1ced6cf08

### Screenshots

- `LvimInfo`
![LvimInfo](https://user-images.githubusercontent.com/12585256/139647064-95a23f83-daf7-440c-b2ad-0c303b63120d.png)
- `LspInfo`
![LspInfo](https://user-images.githubusercontent.com/12585256/139647242-3cd848e4-f78f-460e-bc77-0452a3002962.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by andreicorpo** [comment]
It seems like I had two folders which set up LSPs. `lunarvim/after/ftplugin/` and `lunarvim/site/after/ftplugin` and I had to remove the servers setups from both folders. 
Then I noticed that if I remove the `lunarvim/site/after/ftplugin`, the LSPs were not set up at all even tho I have this line in my config:
``` lua
lvim.lsp.templates_dir = join_paths(get_runtime_dir(), "after", "ftplugin")
```
I changed it to:
```lua 
lvim.lsp.templates_dir = join_paths(get_runtime_dir(), "site", "after", "ftplugin")
```
and removed the unwanted servers from `lunarvim/site/after/ftplugin/javascript.lua` and now everything seems fine.

**Comment by kylo252** [comment]
> Then I noticed that if I remove the `lunarvim/site/after/ftplugin`, the LSPs were not set up at all even tho I have this line in my config:

You need to run `:LvimCacheReset` to re-generate these files. 

The bootstrap checks if the folder got deleted, but it doesn't check if it's empty or not. Because I don't want it to block for too long at startup, and it's easy to run the command manually instead.

**Comment by aaronclimbs** [comment]
I'm also having this issue - was curious if it was due to some conflicts with VS Code LSP installs.

**Comment by kylo252** [comment]
Please take a look at the updated docs https://www.lunarvim.org/troubleshooting/#too-many-language-servers-are-starting-at-once

**Comment by LandonSchropp** [comment]
@kylo252 I'm a bit confused from that link you posted. AFAIK, I don't have any overrides to the LSP servers, and many of these servers still seem to be enabled by default for me.

@ mjlbach mentioned that these rules are configurable, but the current default experience seems broken for JS devs. Would it be reasonable to turn off some of these? Or maybe they should all be turned off and enabled like linters and formatters?

**Comment by kylo252** [comment]
Do you mean that you actually _emptied_ the override list? Because any server that's not in the list is "allowed" to start automatically, Compare the result of 

```lua
:lua print(vim.inspect("lvim.lsp.override"))
```
with the defaults at: https://github.com/LunarVim/LunarVim/blob/044b53a6fed7ed2c477870883857a9742a2e1b98/lua/lvim/lsp/config.lua#L45-L66

**Comment by LandonSchropp** [comment]
@kylo252 Ah, I completely missed that `override` displays the servers that are *not* enabled by default. Now that I realize that, I see it in the documentation. Thanks for the clarification!

As a small suggestion, I feel like a variable name such as `lvim.lsp.disabled_language_servers` would be a little more self-documenting. To me, the name `lvim.lsp.override` implies that I'm overriding the defaults by enabling additional servers. But maybe that's just me?

**Comment by kylo252** [comment]
> As a small suggestion, I feel like a variable name such as `lvim.lsp.disabled_language_servers` would be a little more self-documenting. To me, the name `lvim.lsp.override` implies that I'm overriding the defaults by enabling additional servers. But maybe that's just me?

I agree with the sentiment, but there are two problems that involves changing the name: 
- this is a legacy variable that was used from nearly the beginning.
- the word "disabled" could also imply that this server will never actually run, not even manually.

**Comment by kylo252** [comment]
I'll close the issue since this seems resolved. Please let me know if you're still having troubles.
