### ISSUE TITLE
Formatter arguments

### ISSUE THREAD

**Issue by RobertoGoAm** [LunarVim/LunarVim#1891]
Is there a way I can pass arguments to a formatter? Where I work at we use a non-convetional eslint config file and its not being picked up by eslint, usually, appending -c eslintrc.json to the command is enough for it to work, but haven't found any info on it being possible with LunarVim and I'm not well versed on Nvim to patch something up.

Can anybody give me a hand?

**Comment by RobertoGoAm** [comment]
Nevermind, just found some docs on the subject which I didnt see before 🤦‍♂️ . Closing

**Comment by Almo7aya** [comment]
@RobertoGoAm can u send me a link or something please?, I can't find this in the docs

**Comment by RobertoGoAm** [comment]
Don't recall at the momment, however, have this example from my config:

```lua
local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup {
  {
    exe = "eslint_d",
    args = {"-c", "eslintrc.json" },
    filetypes = {"javascript", "typescript", "vue"}
  },
  {
    exe = "stylelint",
    args = {"--config", "stylelint.json"},
    filetypes = {"scss"}
  },
}
```
