### ISSUE TITLE
[Bug]: Multiple errors when starting lunarvim with a javascript file

### ISSUE THREAD

**Issue by andreicorpo** [LunarVim/LunarVim#1892]
### Problem description

When I start `lvim` with a javascript file I get a lot of error messages - some lsp related and other stuff.

### LunarVim version

rolling - commit `e8693406`

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+nightly-927-ged2573b7e

### Relevant log output

```shell
E576: Error while reading ShaDa file: there is an item at position 101212 that must not be there: Missing items are for internal uses only
E576: Error while reading ShaDa file: there is an item at position 101212 that must not be there: Missing items are for internal uses only
Error executing vim.schedule lua callback: ...AD-ed2573b/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:150: attempt to index local 'client' (a nil value)
Error executing vim.schedule lua callback: ...AD-ed2573b/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:150: attempt to index local 'client' (a nil value)
Error executing vim.schedule lua callback: ...AD-ed2573b/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:150: attempt to index local 'client' (a nil value)
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: cannot resume dead coroutine
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: cannot resume dead coroutine
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: cannot resume dead coroutine
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: cannot resume dead coroutine
```
```


### Screenshots

![image](https://user-images.githubusercontent.com/12585256/139847986-44275dda-b71b-4f7f-bf0e-b02126ed5a16.png)


### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Can you share the output of both `LvimInfo` and `LspInfo`?

**Comment by kylo252** [comment]
Sorry for the late reply, can you see if you're still getting this issue on rolling? I think it should be resolved after the latest null-ls updates.

**Comment by andreicorpo** [comment]
Somehow after the latest updates I can't get the linters and formatters to work anymore even tho they seem to be active.

![image](https://user-images.githubusercontent.com/12585256/142896834-e140324a-ea7a-4fed-847e-2767026f8d66.png)


![image](https://user-images.githubusercontent.com/12585256/142896874-32be02af-21c5-464d-b79f-9f4ddfcbf8a0.png)


I also updated neovim, so I'm not sure it this is a lunarvim issues or neovim issue.

**Comment by kylo252** [comment]
Make sure you can run either of them directly, for example: `:! prettierd %`. If that works, then you should enable debug-mode for `null-ls`, see https://github.com/jose-elias-alvarez/null-ls.nvim#faq
```lua
lvim.lsp.null_ls.config = {
   debug = true,
}
```
