### ISSUE TITLE
[Feature]: create a better example configuration for Windows

### ISSUE THREAD

**Issue by kylo252** [LunarVim/LunarVim#1902]
### Feature motivation

There are certain things that just work differently on Windows, one of many are are C compilers availability. This would break extensions that require runtime libraries to work. Specific examples are Treesitter: https://github.com/LunarVim/LunarVim/issues/1663 and Telescope-fzf-native: https://github.com/LunarVim/LunarVim/issues/1804. 

Some other useful features might also be good to have, like making `powershell` the default shell. 
From `:h powershell`
```powershell
To use PowerShell:
		let &shell = has('win32') ? 'powershell' : 'pwsh'
		let &shellcmdflag = '-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;'
		let &shellredir = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
		let &shellpipe = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
		set shellquote= shellxquote=
```

**Comment by abzcoding** [comment]
should be fixed via #2330
