### ISSUE TITLE
[Bug]: LSP rename with pyright hangs

### ISSUE THREAD

**Issue by kimusan** [LunarVim/LunarVim#1903]
### Problem description

I do the following: space ->  l -> r (for LSP rename). At this point it should show the renaming prompt but nothing happens. 
pressing space again just moves the cursor one to the right. 

I then wanted to exit so <esc>:q<cr> but here it just hangs. Presing ctrl-c to try and interrupt gives the following errors in a constant loop: 

`Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/dianostic.lua:621: Keyboard interrupt`
Here it actually shows the rename prompt but it does not seem to take input at all. 

Then the following errors start to appear:
`Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:44: attempt to index local 'client' (a nil value).`

Sometimes the following is also shown:
`LSP[id=1]  client has shut down after sending command` (not exact wording as it disappears to fast to get it exactly right)

This is not an extremely huge python project but it does have a few hundred py files across many folders. 

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.6-dev

### Relevant log output

```shell
from lsp.log (not sure this is related):
[WARN][2021-11-04 12:31:41] ...lsp/handlers.lua:401     "Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js"
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Do you have LunarVim and all the core plugins updated? are you running any formatters or linters?

**Comment by kylo252** [comment]
Is this still an issue? It might've gotten better after single-file support has been added.

**Comment by kimusan** [comment]
Actually seems to work ok now. thanks
