### ISSUE TITLE
[Bug]: Telescope find_file picker does not find dotfiles

### ISSUE THREAD

**Issue by Gael101** [LunarVim/LunarVim#1905]
### Problem description

It seems that when I open the file finder (pressing <leader> f or <leader>sf) does not look for hidden files. 
I already tried to override the config by adding : 
`lvim.builtin.telescope.defaults.pickers.find_files.find_command = { "fd", "--type=file", "--hidden", "--smart-case", "" }
` to my config.lua but it does not work.
My workaround solution is to override the <leader>f which-key command by : 
`lvim.builtin.which_key.mappings["f"]= { "<cmd>Telescope find_files hidden=true<cr>" , "Find Files" }
`
but it's not very convenient. 
It seems that this already has been addressed, but it's not working 

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by sa-mendez** [comment]
Try the following:

```lua
-- show hidden files when running a find command in telescope
lvim.builtin.telescope.pickers = { find_files = { hidden = true } }
```

It works for me.

**Comment by dycw** [comment]
Hi @sa-mendez , I believe I have a related problem. On one of my stations I don't have access to `fd`, and I think that's the reason why my `find_files` returns nothing.

I do have access to `rg`, however, so I assumed an adaption of @Gael101 's line above would work for me:

```lua
lvim.builtin.telescope.defaults.pickers.find_files.find_command = { "rg", "--files", "--follow", "--hidden" }
```

as this definitely works in the terminal. (Also to check, `live_grep` is working.)

Could you help please?

P.S. Thanks in advance!

**Comment by sa-mendez** [comment]
Hi @dycw 

Use the following, and it will work as you intend:

```lua
lvim.builtin.telescope.pickers = { find_files = {find_command = { "rg", "--files", "--follow", "--hidden" }}}
```
I tested this and it works, but beware, the fact that you are using the ``--follow`` flag, it will make the searches very unresponsive in certain directories with symbolic links.

Hope this helps.

**Comment by sa-mendez** [comment]
In my system, I also do not have the fd command and do have rg installed.

You can also just use my original suggestion:
```lua
lvim.builtin.telescope.pickers = { find_files = { hidden = true } }
```
without having to override the find command as you are trying to do.  The only reason you may want to override the find command as you are doing is to enable the ``--follow`` flag, as you can enable the search of hidden files and folders with my original suggestion.

**Comment by kylo252** [comment]
@Gael101, please install `fd`, or at least `rg` and then change the command as suggested in the earlier comments.

**Comment by dycw** [comment]
Hi @sa-mendez , you've helped me configure telescope so it works on the aforementioned machine. Thanks for your help!
