### ISSUE TITLE
[Bug]: neovim0.6 HEAD

### ISSUE THREAD

**Issue by Leiyi548** [LunarVim/LunarVim#1907]
### Problem description

Today, I started neovim treesitter and asked me to update to a version above 0.51. I updated to 0.6. This problem occurred
Error executing vim.schedule lua callback: ...AD-3ba800f/share/nvim/runtime/lua/vim/lsp/diagn
ostic.lua:150: attempt to index local 'client' (a nil value)
Error executing vim.schedule lua callback: ...AD-3ba800f/share/nvim/runtime/lua/vim/lsp/diagn
ostic.lua:150: attempt to index local 'client' (a nil value)

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

relase

### Neovim version (>= 0.5)

0.6.0

### Screenshots

![Uploading image.png…]()

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Leiyi548** [comment]
I back neovim0.51 solve this problem!

**Comment by xobtoor** [comment]
I have the same issue (with lunarvim and with my own config) if i switch to neovim nightly (v0.6.0-dev+558-g3ba800f15)

Use case to switch for me to nightly was access to github copilot.

**Comment by Leiyi548** [comment]
@xobtoor  I can't solve your problem eithoit using coplot,You can open a issue

**Comment by xobtoor** [comment]
@Leiyi548 No the issue has nothing to do with copilot, it was just the trigger for me to do the switch to the nightly.

The error itself is exactly the same like yours (from my pov)
