### ISSUE TITLE
[Bug]: VSCode with embedded neovim

### ISSUE THREAD

**Issue by ARN1SH** [LunarVim/LunarVim#1908]
### Problem description

I was trying to set up VSCode with embedded neovim as Chris shows in this video (https://www.youtube.com/watch?v=g4dXZ0RQWdw) . I downloaded the settings.json, keybindings.json (https://github.com/LunarVim/LunarVim/tree/rolling/utils/vscode_config) and init.vim (https://github.com/LunarVim/LunarVim/tree/rolling/utils/lv-vscode).

VSCode-Neovim:
line   34:
E1208: -complete used without -nargs
line   10:
E1208: -complete used without -nargs
Error detected while processing VimEnter Autocommands for "*":
Feline needs 'termguicolors' to be enabled to work properly
Please do `:help 'termguicolors'` in Neovim for more information

I tried `set termguicolors` in init.vim, both didn't seem to work.
I googled the other error messages but I didn't understood how to solve it since I am a beginner.
It would be a great help if you can tell me what dumb mistakes I am making.

### LunarVim version

None

### Neovim version (>= 0.5)

0.6.0-dev

### Screenshots

![image](https://user-images.githubusercontent.com/53369760/140515550-33a29665-8ef8-408b-b1a8-9e696978ae4e.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ARN1SH** [comment]
Found this issue on the extension github https://github.com/asvetliakov/vscode-neovim/issues/724 for E1208: -complete used without -nargs
But what to do with 
1 Error detected while processing VimEnter Autocommands for "*":
2 Feline needs 'termguicolors' to be enabled to work properly

**Comment by heresy0-0y** [comment]
that vid is very old, and im pretty sure Chris has moved away from vscode integration.
I have lunar vim installed using current install instructions, and all i had to do to get vscode neovim working was add the executable path and init path (on macos 11/12, that’s /Users/{user}/.local/bin/lvim and /Users/{user}/.config/lvim/config.lua respectively)

I am using vscodium in lieu of vscode but that shouldn’t change anything in this context.
and dont forget to open your vsc from your terminal.

you may need to go through the initial lvim setup to get it working too. but if you are tied to vscode id say all of this is definitely worth the effort for the nvim integration.
all the best
hera c sey

**Comment by ARN1SH** [comment]
I already have lunarvim installed but when I set the executable path to lvim and init path to config.lua, it shows the following error
`2021-11-06T04:50:32.152Z MainController: Neovim exited with code: -2`
`2021-11-06T04:50:32.151Z MainController: Neovim was disconnected`
`2021-11-06T04:50:32.114Z MainController: Neovim spawn error: spawn /usr/bin/lvim ENOENT`
![image](https://user-images.githubusercontent.com/53369760/140598454-9cd051de-df07-4d36-a8c7-a455656c703a.png)

when I set the executable path to nvim and init path to config.lua, it shows the same error as before
![image](https://user-images.githubusercontent.com/53369760/140598536-b3a59d5d-3889-45b1-b499-f1bebe63785c.png)
Its definitely worth the effort for the nvim integration but I still couldn't get it working properly.

@ChristianChiarulli Please help

**Comment by kylo252** [comment]
This integration should honestly be removed from this repo. One of the first things they recommend is to disable all the plugins and basically only use keymaps: https://github.com/asvetliakov/vscode-neovim#performance-problems.

We can still keep it under the LunarVim org.

**Comment by ARN1SH** [comment]
Downgrading to nvim 0.5.1 fixed it !
