### ISSUE TITLE
[Bug]: Clangd doesn't attach to c file or h file

### ISSUE THREAD

**Issue by Xyhlon** [LunarVim/LunarVim#1911]
### Problem description

open a c or h file

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

latest 

### Neovim version (>= 0.5)

0.5.1

### Relevant log output
:LspInfo 
 Language client log: /home/bob/.cache/nvim/lsp.log
 Detected filetype:   c
 
 0 client(s) attached to this buffer: 
 
 1 active client(s) not attached to this buffer: 
 
 Client: null-ls (id: 1, pid: 5001, bufnr: [])
 	filetypes:       lua, python
 	autostart:       false
 	root directory:  /home/bob/.config/lvim
 	cmd:             nvim
 
 Configured servers list: null-ls

grep ERROR stuff:
entHighlight(13) 605 ms\nI[15:18:40.998] Failed to find compilation database for /home/bob/Programming/slpw21g229/A3/q2.c\nI[15:18:40.998] ASTWorker building file /home/bob/Programm
ing/slpw21g229/A3/q2.c version 8 with command clangd fallback\n[/home/bob/Programming/slpw21g229/A3]\n/usr/bin/clang -resource-dir=/home/bob/.local/share/nvim/lsp_servers/clangd/cla
ngd_13.0.0/lib/clang/13.0.0 -- /home/bob/Programming/slpw21g229/A3/q2.c\n"
[ERROR][2021-10-29 15:18:42] .../vim/lsp/rpc.lua:462    "rpc"   "/home/bob/.local/share/nvim/lsp_servers/clangd/clangd" "stderr"        "I[15:18:42.782] <-- textDocument/documentHig
hlight(15)\nI[15:18:42.782] --> reply:textDocument/documentHighlight(15) 0 ms\n"
[ERROR][2021-10-29 15:18:42] .../vim/lsp/rpc.lua:462    "rpc"   "/home/bob/.local/share/nvim/lsp_servers/clangd/clangd" "stderr"        "I[15:18:42.973] <-- textDocument/didChange\n
"
[ERROR][2021-10-29 15:18:43] .../vim/lsp/rpc.lua:462    "rpc"   "/home/bob/.local/share/nvim/lsp_servers/clangd/clangd" "stderr"        "I[15:18:43.270] <-- textDocument/documentHig
hlight(16)\nI[15:18:43.271] Failed to find compilation database for /home/bob/Programming/slpw21g229/A3/q2.c\n"
[ERROR][2021-10-29 15:18:43] .../vim/lsp/rpc.lua:462    "rpc"   "/home/bob/.local/share/nvim/lsp_servers/clangd/clangd" "stderr"        "I[15:18:43.275] ASTWorker building file /hom
e/bob/Programming/slpw21g229/A3/q2.c version 10 with command clangd fallback\n[/home/bob/Programming/slpw21g229/A3]\n/usr/bin/clang -resource-dir=/home/bob/.local/share/nvim/lsp_ser
vers/clangd/clangd_13.0.0/lib/clang/13.0.0 -- /home/bob/Programming/slpw21g229/A3/q2.c\n"
[ERROR][2021-10-29 15:18:43] .../vim/lsp/rpc.lua:462    "rpc"   "/home/bob/.local/share/nvim/lsp_servers/clangd/clangd" "stderr"        "I[15:18:43.279] --> reply:textDocument/docum
entHighlight(16) 8 ms\nI[15:18:43.279] Skipping rebuild of the AST for /home/bob/Programming/slpw21g229/A3/q2.c, inputs are the same.\n"
[ERROR][2021-10-29 15:18:43] .../vim/lsp/rpc.lua:462    "rpc"   "/home/bob/.local/share/nvim/lsp_servers/clangd/clangd" "stderr"        "I[15:18:43.279] --> textDocument/publishDiag
nostics\n"
[ERROR][2021-10-29 15:18:43] .../vim/lsp/rpc.lua:462    "rpc"   "/home/bob/.local/share/nvim/lsp_servers/clangd/clangd" "stderr"        "I[15:18:43.594] <-- textDocument/formatting(
17)\n"
[ERROR][2021-10-29 15:18:43] .../vim/lsp/rpc.lua:462    "rpc"   "/home/bob/.local/share/nvim/lsp_servers/clangd/clangd" "stderr"        "I[15:18:43.595] --> reply:textDocument/forma
tting(17) 1 ms\n"
[ERROR][2021-10-29 15:18:43] .../vim/lsp/rpc.lua:462    "rpc"   "/home/bob/.local/share/nvim/lsp_servers/clangd/clangd" "stderr"        "I[15:18:43.622] <-- textDocument/didSave\nI[
15:18:43.622] File version went from 10 to 10\n"
[ERROR][2021-10-29 15:18:44] .../vim/lsp/rpc.lua:462    "rpc"   "/home/bob/.local/share/nvim/lsp_servers/clangd/clangd" "stderr"        "I[15:18:44.122] Failed to find compilation d
atabase for /home/bob/Programming/slpw21g229/A3/q2.c\nI[15:18:44.122] ASTWorker building file /home/bob/Programming/slpw21g229/A3/q2.c version 10 with command clangd fallback\n[/hom
e/bob/Programming/slpw21g229/A3]\n/usr/bin/clang -resource-dir=/home/bob/.local/share/nvim/lsp_servers/clangd/clangd_13.0.0/lib/clang/13.0.0 -- /home/bob/Programming/slpw21g229/A3/q
2.c\n"
[ERROR][2021-10-29 15:21:08] .../vim/lsp/rpc.lua:462    "rpc"   "/home/bob/.local/share/nvim/lsp_servers/clangd/clangd" "stderr"        "I[15:21:08.813] <-- textDocument/documentHig
hlight(18)\nI[15:21:08.813] --> reply:textDocument/documentHighlight(18) 0 ms\n"
[ERROR][2021-10-29 15:44:31] .../vim/lsp/rpc.lua:462    "rpc"   "/home/bob/.local/share/nvim/lsp_servers/clangd/clangd" "stderr"        "I[15:44:31.606] <-- shutdown(19)\nI[15:44:31
.606] --> reply:shutdown(19) 0 ms\n"
[ERROR][2021-10-29 15:44:31] .../vim/lsp/rpc.lua:462    "rpc"   "/home/bob/.local/share/nvim/lsp_servers/clangd/clangd" "stderr"        "I[15:44:31.607] <-- exit\nI[15:44:31.607] LS
P finished, exiting with status 0\n"

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Xyhlon** [comment]
I had to add 
vim.list_extend(lvim.lsp.override, { "clangd" })
to the lunarvim config
but my question is why I did need to change any settings?

**Comment by kylo252** [comment]
Do you mean that you need to provide custom configuration for it to work? if so, what are you using?
Can you also provide the full logfile?

**Comment by Xyhlon** [comment]
I didn't have to set any custom configuration I only had to add the aforementioned line to the lunarvim config file. I attached the complete log file  but I think it might be a bit large.
[lsp.log](https://github.com/LunarVim/LunarVim/files/7490847/lsp.log)

**Comment by kylo252** [comment]
The server is attaching just based on the amount of data in the logs. I think you mean that it's not working as expected, e.g. "go-to definition" not doing anything or something. That could be related to the fact that you don't have a `compile_commands.json`, please refer to the official guide for more information: https://clangd.llvm.org/troubleshooting

**Comment by Xyhlon** [comment]
After the newest update broke aforementioned short time fix and I can ensure you the clangd lsp doens't attach
 
 Language client log: /home/bob/.cache/nvim/lsp.log
 Detected filetype:   c
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: null-ls

**Comment by kylo252** [comment]
You probably didn't call `LvimCacheReset` after you've added it to `lvim.lsp.override`, and that's why it looked like it was working. Please take a look here for a full example: https://www.lunarvim.org/languages/c_cpp.html#lsp-settings
