### ISSUE TITLE
[Bug]: lvim.builtin.autopairs.active = false does not disable autopairs

### ISSUE THREAD

**Issue by ElPiloto** [LunarVim/LunarVim#1919]
### Problem description

1. put `lvim.builtin.autopairs.active = false` in `~/.config/lvim/config.lua`
2. Open new buffer and in insert mode type a `"`
3. Observe that the second quote is automatically entered for you, even though autopairs should be disabled.

This also happens with other paired characters such as `(` or `{` which will automatically insert `)` and `}` respectively.

### LunarVim version

commit 294ed3684a76af1c3d983ebc8bfe62ef90f4f632 

### Neovim version (>= 0.5)

0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by edward-mb** [comment]
Try something like
```lua
lvim.builtin.autopairs.on_config_done = {
	active = false,
}

```

**Comment by abzcoding** [comment]
@ElPiloto  please run `:LvimCacheReset` after adding this to your config.lua
```lua
lvim.builtin.autopairs.active = false
```

**Comment by ElPiloto** [comment]
@abzcoding : `:LvimCacheReset` isn't defined in my version of LunarVim (from August 31).

@edward-mb : that worked for me.  Thank you!

Can someone explain to me why my original attempt to disable autopairs failed?  Is this a bug or did I do something wrong? Should I update my mental model of how to disable lunarvim builtins?

**Comment by abzcoding** [comment]
> @abzcoding : `:LvimCacheReset` isn't defined in my version of LunarVim (from August 31).
> 
> @edward-mb : that worked for me. Thank you!
> 
> Can someone explain to me why my original attempt to disable autopairs failed? Is this a bug or did I do something wrong? Should I update my mental model of how to disable lunarvim builtins?

i would suggest updating, cause that might've been a bug that was fixed
