### ISSUE TITLE
[Feature]: Enable preview whilst searching with telescope

### ISSUE THREAD

**Issue by dycw** [LunarVim/LunarVim#1921]
### Feature motivation

As a user of [fzf.vim](https://github.com/junegunn/fzf.vim), followed by [fzf-preview](https://github.com/yuki-yano/fzf-preview.vim) and [fzf-lua](https://github.com/ibhagwan/fzf-lua), I've always had out-of-the-box support for previews, whether it be files, marks, etc.

I can't figure out how to activate this, whether with standalone telescope or with LunarVim.

### Describe the expected solution

![Screenshot from 2021-11-07 09-20-43](https://user-images.githubusercontent.com/10572122/140628802-d300540a-7493-4b7a-bc65-b4764b5165f3.png)

### Describe the alternatives you've considered

As mentioned, there have been [fzf.vim](https://github.com/junegunn/fzf.vim), [fzf-preview](https://github.com/yuki-yano/fzf-preview.vim) and [fzf-lua](https://github.com/ibhagwan/fzf-lua).

There's been a nvim-telescope/telescope.nvim#643 and nvim-telescope/telescope.nvim#605, none of which I can seem to replicate.

### Additional context

Currently, I'm just stuck with

![Screenshot from 2021-11-07 09-20-10](https://user-images.githubusercontent.com/10572122/140628792-97530779-816b-49e6-920a-06f73e0b71b4.png)

**Comment by edward-mb** [comment]
I guess that If the window is not wide enough, the preview is hidden.

Search for the telescope config and take a look
`<leader> Lf telescope`

then on your config.lua do something like
```
lvim.builtin.telescope.defaults.layout_config.width = 0.98
lvim.builtin.telescope.defaults.layout_config.preview_cutoff = 40

```
and play with vertical options
```
      layout_strategy = "horizontal",
      layout_config = {
        width = 0.75,
        preview_cutoff = 120,
        horizontal = { mirror = false },
        vertical = { mirror = false },
      },

```

**Comment by dycw** [comment]
Thank you, I will check this out.

Strangely I've never considered this to be a reason!

**Comment by dycw** [comment]
Thank you @edward-mb , this solved it.

For anyone else who may see this, the relevant parts of the source that was shown to me are [here](https://github.com/LunarVim/LunarVim/blob/6b3e0574a3d2577f8c0558144202ba12f3978cae/lua/lvim/core/telescope.lua#L25-L30).
