### ISSUE TITLE
[Bug]: When entering any character triggers autocomplete, the entry that is not the first prompt is automatically selected

### ISSUE THREAD

**Issue by SDGLBL** [LunarVim/LunarVim#1928]
### Problem description

1. Edit a go file. As the below pic shows,it select the 6th entry automaticly
![image](https://user-images.githubusercontent.com/41188874/140709152-260acf55-e906-4d4c-96aa-694df3cb9024.png)
2.When in other lang files. The Lua file, for example, seems to work normally.
![image](https://user-images.githubusercontent.com/41188874/140709859-2a7f567c-1c3e-42a2-86cc-64153d1bad03.png)

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [ ] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

v0.6.1

### Neovim version (>= 0.5)

v0.5.1

### Relevant log output

```shell
None
```

### Screenshots

![image](https://user-images.githubusercontent.com/41188874/140709152-260acf55-e906-4d4c-96aa-694df3cb9024.png)

![image](https://user-images.githubusercontent.com/41188874/140709859-2a7f567c-1c3e-42a2-86cc-64153d1bad03.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Can this be related to the type of the completion? it seems to be preferring `modules` over other types. Can you please try to verify that?

**Comment by SDGLBL** [comment]
> Can this be related to the type of the completion? it seems to be preferring `modules` over other types. Can you please try to verify that?

Yes, it does seem that way
