### ISSUE TITLE
[Feature]: Example of regestiering a custom null-ls linter

### ISSUE THREAD

**Issue by zalegrala** [LunarVim/LunarVim#1932]
### Feature motivation

Null-ls doesn't support a linter that I would like to use, and are unlikely to merge a contribution at this time for reasons.

I would like to see an example of how to use lunarvim to register a linter as described in the null-ls examples.

https://github.com/jose-elias-alvarez/null-ls.nvim#examples

Specifically, I don't see how to call `null_ls.register(linter)` 

### Describe the expected solution

Some docs exist with an example on how to do this in the most Lunarvim way.

**Comment by kylo252** [comment]
There's no wrapper for this currently, and unlikely will ever be. 

You should just use the native null-ls calls directly, it will also make debugging easier.

**Comment by zalegrala** [comment]
When I call `register` from the native null-ls, that registration doesn't seem to affect what I can load into lvim.  For example, here is a linter that I want to use, but can't get lvim to recognize it.  Do you have ideas on how to connect those dots?

```lua
-- add golangci-lint until https://github.com/jose-elias-alvarez/null-ls.nvim/pull/318
local null_ls = require("null-ls")

local golangci_lint = {
    method = null_ls.methods.DIAGNOSTICS,
    filetypes = { "go" },
    generator = null_ls.generator({
        command = "golangci-lint",
        to_stdin = true,
        from_stderr = false,
        args = {
            "run",
            "--out-format",
            "json",
            "$DIRNAME",
            "--path-prefix",
            "$ROOT",
        },
        format = "json",
        check_exit_code = function(code)
            return code <= 2
        end,
        on_output = function(params)
            local diags = {}
            for _, d in ipairs(params.output.Issues) do
                if d.Pos.Filename == params.bufname then
                    table.insert(diags, {
                        row = d.Pos.Line,
                        col = d.Pos.Column,
                        message = d.Text,
                    })
                end
            end
            return diags
        end,
    }),
}
-- add to other sources or register individually
null_ls.register(golangci_lint)

local linters = require "lvim.lsp.null-ls.linters"
linters.setup {
  { exe = "golangci_lint", filetypes = { "go" }, },
}
```

**Comment by kylo252** [comment]
@zalegrala, where are you adding this call?

**Comment by chase** [comment]
> When I call `register` from the native null-ls, that registration doesn't seem to affect what I can load into lvim. For example, here is a linter that I want to use, but can't get lvim to recognize it. Do you have ideas on how to connect those dots?
> 
> ```lua
> -- add to other sources or register individually
> null_ls.register(golangci_lint)
...
> ```

@zalegrala 

I believe this is due to an error in your configuration: https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/MAIN.md#registration

Even for a single source, it must be in a list-like table like: `null_ls.register({golangci_lint})`

**Comment by chase** [comment]
Another user needed to setup null_ls for use with yarn PnP, which requires rather specific customization, but I think it's a good example:
https://github.com/LunarVim/LunarVim/issues/1938#issuecomment-968550356

**Comment by rckgomz** [comment]
@zalegrala did this worked for you? I'm trying to do the same and I'm getting 
`21:13:09 [ERROR] lvim: "Not a valid linter: golangci_lint" file="linters.lua", line=36`

Also, `null_ls` now support `golangci_lint` in their [builtins](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#about-94) linters.

**Comment by kylo252** [comment]
@rckgomz, that's already available on rolling. You can also wait for a new release that's hopefully coming either today or tomorrow.

**Comment by zalegrala** [comment]
@rckgomz I've been waiting for the update in lvim, so haven't been using it so not sure if it worked or not.  Somewhat of a slow process between putting up the PR in `null_ls` to seeing the results, but I think it might get faster since I think lvim used to have a null_ls fork?  I remember seeing a PR a while ago.

**Comment by dawilliams** [comment]
Has this been resolved or what is the recommended work around? Thanks!

**Comment by durandj** [comment]
I added the following to my `config.lua` to get`golangci-lint` working without much fuss.

```lua
linters.setup {
  -- Snip...
  {
    command = "golangci-lint",
    filetypes = { "go" },
  },
  -- Snip...
}
```
