### ISSUE TITLE
[Bug]: save and quit very slow on a large project

### ISSUE THREAD

**Issue by rebebop** [LunarVim/LunarVim#1954]
### Problem description

Hi, I have a largish ruby on rails project. Have the default configuration for lunarvim. I installed `tsserver` and `solargraph` for code completion etc. Now whenever I save any file `:w` or `:q` it takes lunarvim a full second or more to save or quit the file. Not sure what's going on here. I tried it with my own nvim configuration and there it's completely fine.

Any ideas how to debug this?

### LunarVim version

rolling release

### Neovim version (>= 0.5)

v0.5.1

### Relevant log output

```shell
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/build/config -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/src -I/opt/homebrew/include -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/build/include
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.5.1_1/share/nvim"

Run :checkhealth for more info
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Should be solved with #1937

**Comment by rebebop** [comment]
@kylo252 Confirmed, I turned off auto format on save and the lag is gone.

**Comment by EsmaeelEmadi** [comment]
I turned off auto-format on saving and it is still slow. TBH I saw no difference at all.

**Comment by kylo252** [comment]
@EsmaeelEmadi, which system are you using?
