### ISSUE TITLE
[Feature]: (Minor) use SchemaStore.nvim for jsonls

### ISSUE THREAD

**Issue by real-99** [LunarVim/LunarVim#1957]
### Feature motivation

I think one of the features I enjoy in IDE such as vs-code is the whole compatibility with schemas file (package.json, angular.config.json, etc...).

As of right now, I am seeing that LunarVim does not support all the those

### Describe the expected solution

My solution to this problem is using the [SchemaStore.nvim](https://github.com/b0o/schemastore.nvim) plugin which let jsonls access the whole [schemastore](http://schemastore.org) catalog. 

### Describe the alternatives you've considered

I don't think there's other applicable solutions except taking all the schemas by hand.

### Additional context

Nothing to note.

**Comment by chase** [comment]
@real-svg I personally use this and I believe so does @abzcoding

I'll bring it up with the rest of the maintainers :+1:
