### ISSUE TITLE
[Bug]: All LSP Clients Loaded by Default (Even When They're Not Applicable)

### ISSUE THREAD

**Issue by LandonSchropp** [LunarVim/LunarVim#1958]
### Problem description

I think this issue is easy to notice with the Deno LSP, but it applies to other LSPs as well.

Open up a JavaScript file contained in a Node.js and run `:LspInfo`. You'll see the Deno LSP running, even though it's not an LSP project.

The Deno LSP flags errors that are simply not relevant for a normal Node.js project. Here's a few examples from one of my files.

```
 │     Relative import path "node-fetch" not prefixed with / or ./ or ../ from "... deno(import-prefix-missing) [2, 19]
 │     Relative import path "lodash" not prefixed with / or ./ or ../ from "... deno(import-prefix-missing) [3, 15]
 │     Relative import path "date-fns" not prefixed with / or ./ or ../ from "... deno(import-prefix-missing) [4, 47]
```

Since I updated to the most recently version of Node.js, I've noticed that several language servers are now running by default in my JavaScript ile:

* `eslint`
* `null-ls`
* `tsserver`
* `stylelint_lsp`
* `tailwindcss`
* `ember`
* `denols`
* `rome`

My project only uses `eslint`, `null-ls` and `ts-server`. None of the rest of these LSPs are relevant.

Ideally, these language servers would only be loaded when they're relevant to the project. As more of these tools get added to LunarVim, would it make sense for the LSP detection to become more sophisticated than just the file type? For example, maybe the `ember` language sever should only get loaded by default if there's a `package.json` file contains the `ember` package.

I don't know if this solution works for every language server. Is there an easy way to distinguish a Deno project from a Node.js project? A Node.js project may contain a `package.json` file, but it doesn't have to.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

Latest

### Neovim version (>= 0.5)

v0.5.1

### Relevant log output

```shell
N/A
```

### Screenshots

N/A

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by LandonSchropp** [comment]
I forgot to mention that this is my current LSP configuration:

```
local formatters = require("lvim.lsp.null-ls.formatters")
local linters = require("lvim.lsp.null-ls.linters")

-- Formatters
formatters.setup({
  { exe = "mix" },
  { exe = "eslint_d" },
  { exe = "fixjson" },
  { exe = "stylua" },
})

-- Linters
linters.setup({
  { exe = "eslint_d" },
  { exe = "rubocop" },
  { exe = "shellcheck" },
  { exe = "markdownlint" },
  { exe = "write_good" },
})
```

**Comment by mjlbach** [comment]
AFAIK lunarvim isn't special-casing deno, so you're just relying on the lspconfig rules for identifying projects. 


> Ideally, these language servers would only be loaded when they're relevant to the project. As more of these tools get added to LunarVim, would it make sense for the LSP detection to become more sophisticated than just the file type? 

It is more sophisticated than just matching on filetype, as it examines project structure.

https://github.com/neovim/nvim-lspconfig/blob/82ca244c9f9db65779790f7d51f39acb9b9e0528/lua/lspconfig/denols.lua#L119

https://github.com/neovim/nvim-lspconfig/blob/82ca244c9f9db65779790f7d51f39acb9b9e0528/lua/lspconfig/tsserver.lua#L22-L25

Note, there is overlap. For these cases, I recommend you override deno/tsserver's root pattern in your setup call to remove commonalities. In lspconfig2 (name TBD) there will be project local configuration.

These can be more complicated/robust, here's the one for rust which parses cargo metadata:

https://github.com/neovim/nvim-lspconfig/blob/38e489a12e991e0dd762de1adac976920fb438b5/lua/lspconfig/rust_analyzer.lua#L18-L56

No one has bothered to update the rules for the JS ecosystem, they are all community contributed so feel free to PR.

**Comment by LandonSchropp** [comment]
Ah, I completely missed that issue. Your explanation of this also makes complete sense. Thanks!
