### ISSUE TITLE
[Bug]: lvim.leader doesn't work with non english character 

### ISSUE THREAD

**Issue by Nojipiz** [LunarVim/LunarVim#1961]
### Problem description

1) Go to your config.lua file 
2) Change lvim.leader = "space"  to lvim.leader = "ñ"
3) Reload

Help i really want to use Lvim but doesn't work with non english key

### LunarVim version

v 0.6.1

### Neovim version (>= 0.5)

0.5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by chase** [comment]
@Nojipiz This is likely a limitation of Neovim, not LunarVim.

If you do `:let mapleader="ñ"`, does it function?

**Comment by Nojipiz** [comment]
@chase Sorry, my bad it doesn't work
