### ISSUE TITLE
[Bug]: can not update lunavim

### ISSUE THREAD

**Issue by angryheng** [LunarVim/LunarVim#1963]
### Problem description

The project root, running git pull, always show already up to date

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
You might be on master and expecting to see updates from rolling.

**Comment by angryheng** [comment]
@kylo252  thanks resolved
