### ISSUE TITLE
[Bug]: python go to definition doesn't work

### ISSUE THREAD

**Issue by seik** [LunarVim/LunarVim#1964]
### Problem description

Steps to reproduce:

1. Open a python file.
2. Attempt to use go to definition (g+d).

Error message:

`E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:458: bad argument #2 to 'format' (number expected, got nil)`

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

5a310a2

### Neovim version (>= 0.5)

0.5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Weird, I would advise updating to neovim-nightly either way.
