### ISSUE TITLE
[Bug]: Can't use same `exe` for formatter and linter

### ISSUE THREAD

**Issue by andoni0305** [LunarVim/LunarVim#1966]
### Problem description

Maybe there's a new way to specify linters that i missed from the updates but i am not getting virtual text from the configured linters. In this case `eslint_d`.

1. Open js project file on `lvim` commit [ffcaae6](https://github.com/LunarVim/LunarVim/commit/ffcaae6c32fb10c7716dde2593e30bdf044719db) and i get virtual text
2. Open js project file on `lvim` commit [da7ff0a](https://github.com/LunarVim/LunarVim/commit/da7ff0a87aec87592a9ef2905eea60fddcf2d2fb) and no linter error or virtual text. Just tsserver.

Linter config
```lua
local linters = require("lvim.lsp.null-ls.linters")
linters.setup({
	{
		exe = "eslint_d",
		filetypes = {
			"javascript",
			"javascriptreact",
			"typescript",
			"typescriptreact",
		},
	},
})
`````

It might be an omission on my part but couldn't figure it out

Thanks!

### LunarVim version

rolling@latest

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+566-g4174244d8

### commit `ffcaae6`
![image](https://user-images.githubusercontent.com/19435653/142287006-8925947e-281f-4f5e-b1e7-9ee41296668a.png)
![image](https://user-images.githubusercontent.com/19435653/142287029-7df9527f-f9d9-4a07-8a20-aa7de07c8059.png)

### commit `da7ff0a`

![image](https://user-images.githubusercontent.com/19435653/142287525-665a1093-7666-4595-9d26-d3821677bc79.png)

![image](https://user-images.githubusercontent.com/19435653/142287687-c6e76682-05c2-485d-b9ed-b305c92539d1.png)

![image](https://user-images.githubusercontent.com/19435653/142287735-b7d99832-2db8-403c-9bb4-eab4cc73e1c2.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by andoni0305** [comment]
I think the issues was that i had `eslint_d` as `linter` and as `formatter`

Will do some tweaks to see how to allow that again

Updating issues title

**Comment by andoni0305** [comment]
Is there a way to do this without removing [`elseif` lines](https://github.com/LunarVim/LunarVim/blob/c26ac5364f2bb04b7428105db39c12c6549d5dfb/lua/lvim/lsp/null-ls/linters.lua#L41)? 

Thanks in advance!

**Comment by kylo252** [comment]
> Is there a way to do this without removing [`elseif` lines](https://github.com/LunarVim/LunarVim/blob/c26ac5364f2bb04b7428105db39c12c6549d5dfb/lua/lvim/lsp/null-ls/linters.lua#L41)?
> 
> Thanks in advance!

I had to add this because null-ls kept registering sources after the recent refactors to be able to call the setup function from an `ftplugin` file, otherwise it will keep registering new instances every time you enter a matching buffer.

Can you see if the linked PR fixes the issue? I'm not really all that familiar with `eslint` 😄

**Comment by andoni0305** [comment]
@kylo252 it works perfectly 👍 !
Should i close this?

Thanks!
