### ISSUE TITLE
Lualine will not change according to the theme color

### ISSUE THREAD

**Issue by Leiyi548** [LunarVim/LunarVim#1971]
before:
![image](https://user-images.githubusercontent.com/76139422/142632420-1e148953-9d12-4ffa-89c9-d4ed23947a60.png)
after:
![image](https://user-images.githubusercontent.com/76139422/142632482-a1bb7655-6659-4401-8b3d-36ea95334e93.png)
It used to be useful. This problem occurred when I updated the lunarvim of the latest master branch

**Comment by ittisafur** [comment]
you need to set the lualine color 
`lvim.builtin.lualine.options.theme= "tokyonight"`
Reference:
[Lunarvim Theme](https://www.lunarvim.org/configuration/06-statusline.html#theme)

**Comment by Leiyi548** [comment]
@ittisafur  
![image](https://user-images.githubusercontent.com/76139422/142714806-f20833a6-9233-45b0-86c4-b9824f47eef9.png)
In the past, I could automatically switch my lualine according to the theme, but now I can't

**Comment by Leiyi548** [comment]
@ittisafur  I found a solution to modify the lvim.builtin.lualine.option.theme= "auto"
