### ISSUE TITLE
Give ability to use external lsp server via just config override (ex: "cmd") without the server from Lsp-installer

### ISSUE THREAD

**Issue by Dulanjala007** [LunarVim/LunarVim#1972]
### Problem description

if you don't have the server installed via lsp-installer then you can't override the config, but we are using a external server via the modified config

I know we can directly config servers without using `lvim.lsp.manager`
but if someone tried this way i thought it would work, they would be just stuck.

if we config it like..
```
lvim.lsp.automatic_servers_installation = false
vim.list_extend(lvim.lsp.override, { "sumneko_lua", "tsserver" })
```
add config override to -> `lua/lvim/lsp/providers/sumneko_lua.lua`

run `:LvimCacheReset`

what's happening in these conditions is it ends up here 
`Log:debug(requested_server.name...` 

> https://github.com/LunarVim/LunarVim/blob/fe99ee6e42ddec225c46a9d1fcda5c5d76396601/lua/lvim/lsp/manager.lua#L62-L85

,where there's nothing being done to config the server
since we aren't using auto installer, 
but it just wait until the requested server is ready, which is never going to happen since we aren't installing it

So Docs should include that if you aren't using lsp-installer then only use 
`require("lspconfig")["pyright"].setup(opts)` type of manual setup calls..

Hope this help someone save their time...

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6 dev

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
I'm not really sure that I get the point here. 

_Any server in `lvim.lsp.override` needs an explicit setup call somewhere in your `config.lua`_. 

Then you are free to use the `lvim.lsp.manager` API, or `lspconfig` or anything else for that matter. See https://www.lunarvim.org/languages/#overriding-the-default-setup-options. The only thing that people seem to miss is that you _must_ execute `:LvimCacheReset` to remove the generated `ftplugin` file that had the original setup call.

**Comment by Dulanjala007** [comment]
think of this example..
you need to use the external `sumneko_lua` version that's in the system path..
and you want it to be setup only on access using the ftplugin (not putting the config in the config.lua)
then calling the lsp.manager with the custom config in the ftplugin's lua.lua file
then it should work right?
Important :-  we disable auto lsp install, since we already have the server in the system

**Comment by kylo252** [comment]
You can already do this, see this full example for `clangd`: https://www.lunarvim.org/languages/c_cpp.html#lsp-settings

**Comment by Dulanjala007** [comment]
yes there's the possibility, but there are few bugs...

1. either lsp server is not available in the lsp-installer or you installed it via the installer  
   ONLY then you can use the lsp.manager to override the config...

2. if you have a provider added (lua/lsp/providers/*), like sumneko_lua 
    then even if you override the server, it will always create the ftplugin for lua...

current solution is to just add the server directly using lspconfig[server].setup()

**Comment by kylo252** [comment]
Are you specifically talking about the lua-server? because `clangd` is installed locally as I've shown in example.

**Comment by Dulanjala007** [comment]
please check the linked code part in the issue...
if the server is available through the lsp-installer, 
then you need to install it via the installer to make the config activate, 
you won't notice it easily because by default we have auto install lsp servers enabled, 
so it will automatically install the lsp, and then initialize the config, 
even if our config uses an externally installed lsp server..
if you disable the auto install lsp server via the lsp-installer then the code in the example won't work..

I spent so much time on this trying to setup lua lsp server, debug the whole lsp manager code section..
since my machine runs NixOS and i have to use custom built executables for everything.

![Screenshot from 2021-11-21 01-37-46](https://user-images.githubusercontent.com/16051361/142739618-3d2bde7c-41f5-4356-a9a9-89b600e2854c.png)

these are one of the cause of the problem with ftplugin file creation...

**Comment by Dulanjala007** [comment]
you missed the issue with the template generator, 
when provider for a server exists, then it creates the ftplugin file for that lang even if that server is overrided.. 

Ex: since sumneko_lua.lua exists in providers, even when override sumneko_lua server, it still create lua.lua in ftplugin dir
