### ISSUE TITLE
Unable to understand the docs/breaking change

### ISSUE THREAD

**Issue by gonzaloserrano** [LunarVim/LunarVim#1973]
### Problem description

So there is this breaking change:

![CleanShot 2021-11-19 at 18 47 35](https://user-images.githubusercontent.com/349328/142668132-f142c8f6-6f35-4202-9189-e4ba9dc8f8c1.png)

Which prints `18:47:46 [WARN ] lvim: "Deprecation notice: [lvim.lang.go] setting is no longer supported. See https://github.com/LunarVim/LunarVim#breaking-changes" file="init.lua", line=59` in my installation.

I checked https://www.lunarvim.org/languages/go.html but I don't really know what to do?

Thanks

### LunarVim version

rolling, since I needed https://github.com/LunarVim/LunarVim/commit/c26ac5364f2bb04b7428105db39c12c6549d5dfb

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+589-gc0efe49e7

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by PBird** [comment]
remove lvim.lang.go  in `~/.config/lvim/config.lua`. Then you should to do the new way that described in [example config](https://github.com/LunarVim/LunarVim/blob/rolling/utils/installer/config.example.lua)

example :
`
local formatters = require "lvim.lsp.null-ls.formatters"  `
`formatters.setup { 
  { exe = "gofmt" }
}
`

**Comment by gonzaloserrano** [comment]
Thanks, that works. 

Side-comment: should the docs page reflect that? E.g in https://github.com/LunarVim/lunarvim.org/edit/master/docs/languages/go.md there is no mention on how to do that.

**Comment by kylo252** [comment]
> Side-comment: should the docs page reflect that? E.g in [LunarVim/lunarvim.org/edit/master/docs/languages/go.md](https://github.com/LunarVim/lunarvim.org/edit/master/docs/languages/go.md) there is no mention of how to do that.

I'm still not sure how the information should be structured in those pages. I had to update a lot of deprecated info on my own and opted for the auto-generated template that you see. Basically, I had figured that this is better than repeating the same info that exists in https://github.com/LunarVim/lunarvim.org/tree/master/docs/languages#formatting. 

That said, please do open a PR if you have some ideas to improve it. I would really appreciate it!
