### ISSUE TITLE
Help me test the startup time of lunarvim🙏🏻🙏🏻🙏🏻

### ISSUE THREAD

**Issue by Leiyi548** [LunarVim/LunarVim#1975]
![image](https://user-images.githubusercontent.com/76139422/142731717-0b5a7bb2-41ad-4d7d-8268-6644a9a0dbaf.png)

I use: startuptime to test the startup time. I found that this test is the startup time of nvim, not the startup time of lunarvim. How can I test the startup time of lunarvim?

**Comment by kylo252** [comment]
Some like to benchmark using `--startuptime`

```shell
lvim --startuptime s.log
```

**Comment by Leiyi548** [comment]
@kylo252  
![image](https://user-images.githubusercontent.com/76139422/142735561-891a7886-5355-43fb-908e-9a00661c0b02.png)
Is this last line my startup time?

**Comment by kylo252** [comment]
>  Is this last line my startup time?

Yup, and the number next to each command is how much that one took.
