### ISSUE TITLE
Failed to change LSP prefix...Please help me.

### ISSUE THREAD

**Issue by Leiyi548** [LunarVim/LunarVim#1976]
![image](https://user-images.githubusercontent.com/76139422/142733565-2e1065bc-71b8-439b-9a59-4ba3db922046.png)
![image](https://user-images.githubusercontent.com/76139422/142733577-c7962c03-aa54-48e1-9845-080c2a541647.png)
not working?

**Comment by kylo252** [comment]
It might because the handlers are always loaded after the user-config. The easiest way would be to update to neovim-nightly and then use:

```lua
vim.diagnostic.config {
  virtual_text = {
    prefix = "",
  },
}
```
![image](https://user-images.githubusercontent.com/59826753/142734691-8e877160-a883-44d3-824c-53cb373858d4.png)

**Comment by Leiyi548** [comment]
@kylo252 
![image](https://user-images.githubusercontent.com/76139422/142750098-74b4158e-6fdb-4289-a124-d7583f34388c.png)
I updated to neovim 0.6, and then I had this problem. Please help me how to solve this problem

**Comment by Leiyi548** [comment]
@kylo252 I solved this problem. I used lvimCacheReset to solove this problem .

**Comment by Leiyi548** [comment]
@kylo252  Thank you for your help. I have successfully changed. Thank you very much
