### ISSUE TITLE
[Bug]: Setting up pylsp via lvim.lsp.manager has no effect, lspconfig.pylsp.setup does

### ISSUE THREAD

**Issue by fnune** [LunarVim/LunarVim#1978]
### Problem description

Set up `pylsp` with some settings using the built-in `lvim.lsp.manager`:

```lua
local opts = {
  settings = {
    pylsp = {
      plugins = {
        pylsp_mypy = { enabled = true },
      }
    },
  }
}
require("lvim.lsp.manager").setup("pylsp", opts)
```

Observe how this has no effect:
![image](https://user-images.githubusercontent.com/16181067/142739258-7b099f66-2715-4e92-b57f-e13252873131.png)

Change the `lvim.lsp.manager` line to this:

```lua
-- require("lvim.lsp.manager").setup("pylsp", opts)
require("lspconfig")["pylsp"].setup(opts)
```

Observe how this now works:
![image](https://user-images.githubusercontent.com/16181067/142739274-aa66896e-dc0e-4b0f-894e-c0b5aae52b51.png)

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

I don't know where to find this

### Neovim version (>= 0.5)

v0.5.1

### Relevant log output

```shell
:echo &ft
python

---

:LspInfo
 Language client log: /home/fausto/.cache/nvim/lsp.log
 Detected filetype:   python
 
 2 client(s) attached to this buffer: 
 
 Client: pylsp (id: 1, pid: 113343, bufnr: [16])
 	filetypes:       python
 	autostart:       true
 	root directory:  /home/fausto/Development/project
 	cmd:             pylsp
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [16])
 	filetypes:       javascript, javascriptreact, typescript, typescriptreact, vue, css, scss, less, html, json, yaml, markdown, graphql, python
 	autostart:       false
 	root directory:  /home/fausto/Development/project
 	cmd:             nvim
 
 Configured servers list: pylsp, null-ls

---

:LspStart pylsp
(no output, seems to succeed)

---

grep ERROR ~/.cache/nvim/lsp.log
(no results, contents of file follow)

[START][2021-11-20 21:01:22] LSP logging initiated
[START][2021-11-20 20:58:15] LSP logging initiated
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
did you add it to override_list?
<img width="842" alt="Screen Shot 2021-11-21 at 12 04 06 PM" src="https://user-images.githubusercontent.com/10992695/142755298-8f48df71-ecd5-4451-8308-284ca8e8f2d9.png">

**Comment by fnune** [comment]
https://github.com/fnune/dotfiles/blob/1b2af1307a94dfbfbc2b09b302683c898e1a7d24/lvim/.config/lvim/config.lua#L49

Yup. You can see the rest of my config there.

**Comment by fnune** [comment]
After tinkering for a bit I'm thinking that it may be something else:

Using the built-in manager does have an effect and works, but it's picking its own installation o the LSP, which doesn't have the mypy or black plugins, so those don't work.

If I use lspconfig to set up pylsp, it picks my own installation of it, where everything works.

So presumably this isn't a setup issue but the manager preferring its own install.

The docs made it seem like the change (built-in manager vs lspconfig API) was syntactic sugar, which probably confused me.

How can I use the manager but still choose my own pylsp installation?

**Comment by abzcoding** [comment]
i've been away from the project for a bit, so i'm not sure, maybe @kylo252 can help you there
but this is how i change the options ( without using the override thingy)
https://github.com/abzcoding/lvim/tree/main/lua/lvim/lsp/providers

**Comment by kylo252** [comment]
This is probably related to #1981

@fnune, can you please test to see if it solves your problem?

**Comment by fnune** [comment]
Looks like that might be the fix. I'll come back to this once it's released, since the fix has already been merged.

**Comment by kylo252** [comment]
You can switch to the rolling branch instead :)

**Comment by fnune** [comment]
Looks like it's still picking `~/.local/share/nvim/lsp_servers/pylsp/venv/bin/pylsp` instead of my own installation.

If I add `lvim.lsp.automatic_servers_installation = false`:

```lua
lvim.lsp.automatic_servers_installation = false
vim.list_extend(lvim.lsp.override, { "pyright", "pylsp" })

local opts = {
  settings = {
    pylsp = {
      plugins = {
        pylsp_mypy = { enabled = true },
        pylsp_black = { enabled = true },
      }
    },
  }
}
require("lvim.lsp.manager").setup("pylsp", opts)
```

...when I open `lvim`, its own version of `pylsp` is still installed. So I run `LspUninstall pylsp`, `LvimResetCache` and restart `lvim`.

When I open it again, `pylsp` isn't activated at all and it doesn't show up under `LspInfo`.

**Comment by fnune** [comment]
For the record: I ran this to switch to the rolling channel.

```bash
LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)
```

**Comment by kylo252** [comment]
> When I open it again, `pylsp` isn't activated at all and it doesn't show up under `LspInfo`.

Yup, this is to be expected. Now you need to manage the installation yourself. Make sure that `:! which pylsp` is successful. 

To clarify, this :
```lua
local opts = {}
require("lvim.lsp.manager").setup("pylsp", opts)
```

is just a shorthand for 

```lua
local opts = {}
local default_opts = { -- these are used as base in `resolve_config`
  on_attach = require("lvim.lsp").common_on_attach,
  on_init = require("lvim.lsp").common_on_init,
  capabilities = require("lvim.lsp").common_capabilities(),
}
local config = vim.tbl_deep_extend("force", default_opts, opts)
require("lspconfig")["pylsp"].setup(config)
```

So feel free to use `lspconfig` directly.

**Comment by fnune** [comment]
> > When I open it again, `pylsp` isn't activated at all and it doesn't show up under `LspInfo`.
> 
> Yup, this is to be expected. Now you need to manage the installation yourself. Make sure that `:! which pylsp` is successful.

I would argue that it's not what's expected in my case, since I do have `pylsp` installed and working. With this in mind:

```lua
lvim.lsp.automatic_servers_installation = false
vim.list_extend(lvim.lsp.override, { "pyright", "pylsp" })

local opts = {
  settings = {
    pylsp = {
      plugins = {
        pylsp_mypy = { enabled = true },
        pylsp_black = { enabled = true },
      }
    },
  }
}
require("lvim.lsp.manager").setup("pylsp", opts)
```

I would expect to work as long as my local `pylsp` is correctly installed and working (as it is).

**Comment by kylo252** [comment]
We had that discussion and came to the conclusion that on average, the reason you most likely would want to override a server is to change the `cmd` parameters. Since most servers that actually offer `settings` can already be configured with https://github.com/tamago324/nlsp-settings.nvim

**Comment by kylo252** [comment]
I added a notice regarding this in https://github.com/LunarVim/lunarvim.org/pull/146

**Comment by fnune** [comment]
Sweet, thank you! <3
