### ISSUE TITLE
[Feature]: LunarVim.desktop

### ISSUE THREAD

**Issue by ALipAkrohk** [LunarVim/LunarVim#1982]
### Feature motivation

Hi
LunarVim can now be installed on Arch via [AUR](https://aur.archlinux.org/packages/lunarvim-git/), but it is a bit difficult to package.
1- After installing the package, due to access problems, the software update feature will have problems.
2 - LunarVim requires a` LunarVim.desktop` file in `/usr/share/applications/` 
I sent a request to add a LunarVim icon to PapirusDevelopmentTeam, I hope you find it useful.

### Describe the expected solution

Create a LunarVim.Desktop file in the specified path for easier access to LunarVim.
Change the installation location of software configurations in aur and route it to `$HOME/.config/lvim`

### Additional context

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2882
[ArchAUR_LunarVim](https://aur.archlinux.org/packages/lunarvim-git/)
[ chaotic-aur  LunarVim](https://github.com/chaotic-aur/packages/commit/38061337cc5c600c2a0efff365ecf5fc691e0f2a)

**Comment by chase** [comment]
We've already got a desktop file, but it might need some love. Feel free to submit a PR!

https://github.com/LunarVim/LunarVim/blob/rolling/utils/desktop/lvim.desktop

**Comment by ALipAkrohk** [comment]
> We've already got a desktop file, but it might need some love. Feel free to submit a PR!
> 
> https://github.com/LunarVim/LunarVim/blob/rolling/utils/desktop/lvim.desktop

So now you just have to change the name of your icon, because you have a custom icon and you do not need to use the NeoVim icon.
