### ISSUE TITLE
Failed to cancel jk jj kj mapping[Bug]: 

### ISSUE THREAD

**Issue by Leiyi548** [LunarVim/LunarVim#1983]
### Problem description

   lvim.keys.insert_mode["jk"] = nil
   lvim.keys.insert_mode["kj"] = nil
   lvim.keys.insert_mode["jj"] = nil

I set it up, but it didn't work.

https://user-images.githubusercontent.com/76139422/142827599-13110098-cd03-4536-9e68-2dfa885524cb.mov

### LunarVim version

relase

### Neovim version (>= 0.5)

0.6.0 HEAD

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by fnune** [comment]
Just submitted this https://github.com/LunarVim/LunarVim/issues/1984

Probably related.

**Comment by abzcoding** [comment]
instead of nil can you set them to false?

**Comment by fnune** [comment]
Setting them to `false` worked. In my case:

```lua
lvim.keys.visual_block_mode.J = false
lvim.keys.visual_block_mode.K = false
```

`<leader>Lk`

```lua
  visual_block_mode = {
    ["<A-j>"] = ":m '>+1<CR>gv-gv",
    ["<A-k>"] = ":m '<-2<CR>gv-gv",
    J = false,
    K = false,
    <metatable> = <table 1>
  },
```

**Comment by Leiyi548** [comment]
@fnune @abzcoding Thankyou!!!
