### ISSUE TITLE
[Bug]: Overriding lvim.keys.visual_block_mode has no effect

### ISSUE THREAD

**Issue by fnune** [LunarVim/LunarVim#1984]
### Problem description

I'm trying to override `J` and `K` in `visual_block_mode`. I basically want `J` to do a visual block join instead of `:move`.

1. Confirm that currently `J` and `K` and mapped to `:move`:

```lua
-- Partial output of <leader>Lk
  visual_block_mode = {
    ["<A-j>"] = ":m '>+1<CR>gv-gv",
    ["<A-k>"] = ":m '<-2<CR>gv-gv",
    J = ":move '>+1<CR>gv-gv",
    K = ":move '<-2<CR>gv-gv",
    <metatable> = <table 1>
  },
```

2. Attempt several ways to override `J` following [the docs](https://www.lunarvim.org/configuration/02-keybindings.html#lunarvim-keybindings):

```lua
lvim.keys.visual_block_mode.J = nil
lvim.keys.visual_block_mode["J"] = nil
lvim.keys.visual_block_mode["<S-j>"] = nil
```

3. Confirm that there's no change (output is the same as above for `<leader>Lk`.
4. Try out blowing out the whole keybindings table:

```lua
lvim.keys.visual_block_mode = {}
```

5. Confirm that there's a change but the keybindings are still there:
```lua
  visual_block_mode = {
    ["<A-j>"] = ":m '>+1<CR>gv-gv",
    ["<A-k>"] = ":m '<-2<CR>gv-gv",
    J = ":move '>+1<CR>gv-gv",
    K = ":move '<-2<CR>gv-gv"
  },
```
Notice how it no longer says `<metatable> = <table 1>`

(5) hints to me that there's a change but it's not the intended change.

### LunarVim version

I don't know where to find this

### Neovim version (>= 0.5)

0.5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by fnune** [comment]
https://github.com/LunarVim/LunarVim/issues/1983#issuecomment-975436177

Solved: set them to `false` instead of `nil`.

Leaving the ticket open because the docs say `nil`.

**Comment by abzcoding** [comment]
thank you for mentioning it, updated the docs accordingly https://github.com/LunarVim/lunarvim.org/commit/afa073305fa2524bf5961c307fd39c26edfc98a8

**Comment by fnune** [comment]
https://github.com/LunarVim/lunarvim.org/commit/afa073305fa2524bf5961c307fd39c26edfc98a8

Thanks @abzcoding !
