### ISSUE TITLE
[Feature]: Telescope support for lsp_references and code actions

### ISSUE THREAD

**Issue by dlvhdr** [LunarVim/LunarVim#1985]
### Feature motivation

In my nvim configuration I added a custom keybinding ("gr") that will open up telescope with the references of the symbol under the cursor.
I find this a lot better than the split opening at the bottom.

This is what I added:
```lua
function M.lsp_references()
  require("telescope.builtin").lsp_references {
    layout_strategy = "horizontal",
    layout_config = {
      width = 0.6,
      height = 0.5,
      prompt_position = "top",
    },
    sorting_strategy = "ascending",
    ignore_filename = false,
  }
end
```

I did the same thing for code actions.

### Describe the alternatives you've considered

This is a potential bug...
I tried to replicate this behavior in lvim, but my remapping didn't work.
Remapping "gr" to my custom command simply appended my mapping but didn't override lvim's one.
```lua
lvim.keys.normal_mode["gr"] = "<cmd>lua require('dlvhdr/telescope').lsp_references()<cr>"
```

Running `:verbose map gr` shows:
```
n  gr          *@<Cmd>lua vim.lsp.buf.references()<CR>
n  g           * <Cmd>lua require("which-key").show("g", {mode = "n", auto = true})<CR>
x  g           * <Cmd>lua require("which-key").show("g", {mode = "v", auto = true})<CR>
        Last set from anonymous :source
n  gr          * <Cmd>lua require('dlvhdr/telescope').lsp_references()<CR>
        Last set from anonymous :source
```

**Comment by abzcoding** [comment]
can you try this instead?
```lua
lvim.lsp.buffer_mappings.normal_mode["gr"] = { "<cmd>lua require('dlvhdr/telescope').lsp_references()<cr>", "References" }
```
i think `gr` might be an special case because of this

https://github.com/LunarVim/LunarVim/blob/044b53a6fed7ed2c477870883857a9742a2e1b98/lua/lvim/lsp/config.lua#L24-L37

**Comment by dlvhdr** [comment]
Thanks @abzcoding, this works!
I guess it's worth adding to the docs how one can override these.
I also guess I should have looked at the lua code first, seems pretty straight forward :)
Thanks again!

**Comment by abzcoding** [comment]
no worries mate, sorry for the inconvenience 😅 
yeah we should either converge those or write it down somewhere in the docs

**Comment by elazarl** [comment]
Do we want to add a shortcut to show references in Telescope?
Say, `Leader-l-R`?

**Comment by abzcoding** [comment]
> Do we want to add a shortcut to show references in Telescope?
> Say, `Leader-l-R`?

you can add it yourself
```lua
lvim.builtin.which_key.mappings["l"]["R"] = { "<cmd>Telescope lsp_references()<cr>", "Telescope references" }
```

**Comment by elazarl** [comment]
@abzcoding I can add the entire lvim configuration myself ;-),

But the point of lvim is to provide good default key binding, and I think this is a very common action that could benefit most users.

Don't you think?

**Comment by abzcoding** [comment]
> @abzcoding I can add the entire lvim configuration myself ;-),
> 
> But the point of lvim is to provide good default key binding, and I think this is a very common action that could benefit most users.
> 
> Don't you think?

no i don't think that it is necessary since we already have `gr` keybinding for references

**Comment by elazarl** [comment]
Then maybe just a keybinding for `Telescope quickfix`, which would effectively allow any `g*` keybinding to be opened in Telescope?

**Comment by abzcoding** [comment]
> Then maybe just a keybinding for `Telescope quickfix`, which would effectively allow any `g*` keybinding to be opened in Telescope?

sure a PR would be appreciated

**Comment by abzcoding** [comment]
you can add it around here, or even replace the `<leader>lq`
https://github.com/LunarVim/LunarVim/blob/3c152cb1cf768e3111543d3070e6efd6cfacbb1c/lua/lvim/core/which-key.lua#L163-L165
