### ISSUE TITLE
[Bug]: Website is displaying each page twice

### ISSUE THREAD

**Issue by yatesco** [LunarVim/LunarVim#1986]
### Problem description

Go to the docs site https://www.lunarvim.org/. Each page is rendered twice. This occurs on the latest firefox, Safari, and Chrome on the latest macos. On firefox you need to scroll down, on Safari and Chrome you need to scroll up.

### LunarVim version

N/A

### Neovim version (>= 0.5)

N/A

### Relevant log output

```shell
N/A
```

### Screenshots

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/181469/143007592-019b88d2-0672-46e0-b1b6-020a347fafd1.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
cc: @ChristianChiarulli

**Comment by kylo252** [comment]
Tracked in https://github.com/LunarVim/lunarvim.org/issues/136
