### ISSUE TITLE
Can we get session restore with tmux ?

### ISSUE THREAD

**Issue by Dulanjala007** [LunarVim/LunarVim#1987]
### Feature motivation

tmux can't restore lvim instances...
maybe because `tmux-ressuract` records processes as nvim not lvim..?
any thoughts?

**Comment by kylo252** [comment]
The process name is still `nvim`, but maybe you meant it the other way around. Unfortunately, `tmux-resurrect` uses rudimentary methods to detect session files, which doesn't really help all that much. Also, do take a look at https://github.com/folke/persistence.nvim.

**Comment by Dulanjala007** [comment]
@kylo252 nice to see you again... last time with the lsp-intaller bug..

with tmux i was used to seeing the vim opened and cursor in the last place i left it after the restart..
so i was trying make it happen with the lunarvim as well...

currently trying out various combinations from this documentation to see if i can get it working..
[https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_programs.md](url)

**Comment by clementnuss** [comment]
any enhancement on this topic? that would indeed be really nice 👍🏻

**Comment by daudcanugerah** [comment]
function lvim() { nvim -u ~/.local/share/lunarvim/lvim/init.lua "$@" }

**Comment by abzcoding** [comment]
you can now probably use the new lvim binary to achieve this, feel free to reopen if the issue still persists

**Comment by clementnuss** [comment]
thanks for that info. not sure where/how to find the `lvim` binary though.
the `lvim` file in `~/.local/bin` isn't producing the expected results
is that on another branch than rolling?

**Comment by abzcoding** [comment]
the lvim binary should look like this ( your username instead of `abz` )
<img width="740" alt="Screen Shot 2022-02-08 at 2 35 00 PM" src="https://user-images.githubusercontent.com/10992695/152974928-53f61197-d90c-4845-9d8b-e88833967b0f.png">

**Comment by clementnuss** [comment]
the `lvim`  POSIX shell script is an executable shell script and not a binary file, and its content is the same as the one you showed.

The issue however is that `tmux` restores the process name, which will be something looking like `nvim ...` and not `lvim`.
I looked a bit more in the `~/.tmux/resurrect` folder, and having one of the session restore files, noticed that tmux records the `lvim` sessions as follows:
```
pane    daily   0       1       :*      0       :/home/clement/currentWorkingDirectory   1       nvim    :nvim -u /home/clement/.local/share/lunarvim/lvim/init.lua
```

when restoring as is, this fails, because the `LUNARVIM_...` environment variables aren't set.

after setting the 3 env variables (as in the `lvim` shell script), restoring with tmux works! So I'll simply add those variables to my default env variables and this will solve the issue 👍🏻

**Comment by is-ahmed** [comment]
Hey @clementnuss , so I'm currently having this issue as well and the solution you posted works somewhat for me, but it doesn't retain any of the open files I'd have in a project and just puts me back at the main menu for lvim. Have you experienced this before?

This is my lvim script

`#!/bin/sh

export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"/home/isahmed/.local/share/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"/home/isahmed/.config/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"/home/isahmed/.cache/lvim"}"

exec nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
`

and this was the last session restore file I had

`pane	gatsby	0	1	:*	0	graphql.js (~/SoftwareProjects/gatsby/packages/gatsby) - NVIM	:/home/isahmed/SoftwareProjects/gatsby/packages/gatsby	1	nvim	:nvim -u /home/isahmed/.local/share/lunarvim/lvim/init.lua
window	gatsby	0	:nvim	1	:*	c07d,146x35,0,0,0	:
state	gatsby	
`

**Comment by kylo252** [comment]
you can also change [`${argv[0]}`](https://stackoverflow.com/questions/3251550/how-to-change-argv0-in-bash-so-command-shows-up-with-different-name-in-ps) like this to detect lvim explicitly

```bash
#!/usr/bin/env bash

export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"$HOME/.local/share/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"$HOME/.config/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"$HOME/.cache/lvim"}"

exec -a lvim nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
```

then you can use it inside tmux with something like this, https://github.com/kylo252/dotfiles/blob/758df9e5089f08914fb3a011512e0421e9f424a4/.config/tmux/tmux.conf#L144-L145
