### ISSUE TITLE
error processng init.lua

### ISSUE THREAD

**Issue by pannet1** [LunarVim/LunarVim#1991]
ignore the below, seems the issue could be i am using legacy neovim without luaJIT support.

it seems i have installed lunarvim successfully. i am using the neovim provided by my current distribution MX Linux.
i have also install lua and luarocks. 

`Error detected while processing /home/sweethome/.local/share/lunarvim/lvim/init.lua:`
`line    1:`
`E492: Not an editor command: local init_path = debug.getinfo(1, "S").source:sub(2)`
`line    2:`
`E492: Not an editor command: local base_dir = init_path:match("(.*[/\\])"):sub(1, -2)`
`line    4:`
`E121: Undefined variable: not`
`E15: Invalid expression: not vim.tbl_contains(vim.opt.rtp:get(), base_dir) then`
`line    8:
E492: Not an editor command: require("lvim.bootstrap"):init(base_dir)
line   10:
E492: Not an editor command: require("lvim.config"):load()
line   12:
E492: Not an editor command: local plugins = require "lvim.plugins"
line   13:
E492: Not an editor command: require("lvim.plugin-loader").load { plugins, lvim.plugins }
line   15:
E492: Not an editor command: local Log = require "lvim.core.log"
line   16:
E492: Not an editor command: Log:debug "Starting LunarVim"
colors_name"colors_name" [New File]
Cannot open file "colors_name"
="=" [New File]
Cannot open file "=""lvim.colorscheme" [New File]
Cannot open file "lvim.colorscheme""--" [New File]
Cannot open file "--""Colorscheme" [New File]
Cannot open file "Colorscheme""must" [New File]
Cannot open file "must""get" [New File]
Cannot open file "get""called" [New File]
Cannot open file "called""after" [New File]
Cannot open file "after""plugins" [New File]
Cannot open file "plugins""are" [New File]
Cannot open file "are""loaded" [New File]
Cannot open file "loaded""or" [New File]
Cannot open file "or""it" [New File]
Cannot open file "it""will" [New File]
Cannot open file "will""break" [New File]
Cannot open file "break""new" [New File]
Cannot open file "new""installs." [New File]
Cannot open file "installs."
line   18:
E480: No match: g
."." is a directory
Cannot open file "."
lvim.colorscheme)"lvim.colorscheme)" [New File]
Cannot open file "lvim.colorscheme)"
line   19:
E480: No match: cmd("colorscheme " 
line   21:
E492: Not an editor command: local commands = require "lvim.core.commands"
line   22:
E492: Not an editor command: commands.load(commands.defaults)
line   24:
E492: Not an editor command: require("lvim.lsp").setup()
Press ENTER or type command to continue`

after pressing ENTER i am dropped into neovim. can you please advise me how to fix this init error.

**Comment by Uzaaft** [comment]
@pannet1  What is your current status? Do you get things working locally?

**Comment by pannet1** [comment]
thanks @Uzaaft 
i was not able to build my own neovim. the developments are [https://forum.mxlinux.org/viewtopic.php?p=664167#p664167](url)
i will also let the package maintainers of MX Linux know about this.

**Comment by Uzaaft** [comment]
I am not familiar with MX Linux, but seems to me that it used an APT frontend. 
Test out the Ubuntu section here. 

https://github.com/neovim/neovim/wiki/Installing-Neovim

Although this seems like a user/distro issue, so I think you should just go ahead and close the issue. We can resume the conversation in this thread.
