### ISSUE TITLE
[Bug]: Error while installing LunarVim while preparing Packer Setup

### ISSUE THREAD

**Issue by dwskme** [LunarVim/LunarVim#1992]
### Problem description

Just used the script to install lunarvim (same bug for both rolling and stable).
Error just popes off

### LunarVim version

No idea (error while installing)

### Neovim version (>= 0.5)

0.5.1

### Screenshots

![2021-11-25-21:12:16-screenshot](https://user-images.githubusercontent.com/55840147/143468445-89e576d3-c7a9-43bf-b2bd-1116f9cc6c30.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by angryheng** [comment]
try this `bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh`

**Comment by angryheng** [comment]
try `bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh` and reinstall

**Comment by kylo252** [comment]
This was fixed recently on rolling.
