### ISSUE TITLE
[Feature]: Include support for haskell

### ISSUE THREAD

**Issue by kush87** [LunarVim/LunarVim#1996]
### Feature motivation

Avid user of lunarvim, however while writing haskell code  i have to switch to different setup. It would be great if you guys can support Haskell language as well.

**Comment by Uzaaft** [comment]
You can add Haskell LSP and linters etc by following the guide here: https://www.lunarvim.org/languages/#at-a-glance

**Comment by Uzaaft** [comment]
In short, do the following to add LSP support and syntax:
`:TsInstall haskell`
`:LspInstall haskell`
And add linters etc by following the guide.
