### ISSUE TITLE
[Bug]: weird '$' auto pairing behavior for .tex file

### ISSUE THREAD

**Issue by aik2mlj** [LunarVim/LunarVim#1997]
### Problem description

I'm using lunarvim (awesome work btw!) on wsl2. But I doubt this is not related to platforms.

On a clean rolling branch lunarvim installation:
1. create a new .tex file by `:e a.tex`
2. insert "$"
3. press backspace, lunarvim insert a "0" instead and report some lua errors below
4. also, inserting multiple "$"s produces asymmetric auto pairings
(These behaviors are the same no matter if `texlab` is installed or not, so probably it's not lsp-related)

Moreover, the latex highlighting style is more monotonous than vanilla neovim, even with latex tree-sitter installed.

### LunarVim version

044b53a

### Neovim version (>= 0.5)

0.5.1

### Screenshots

![delete-autopaired-$](https://user-images.githubusercontent.com/53085155/143672610-af9e0300-72b4-4ccf-b163-01760b9f5d90.gif)
![multi-$](https://user-images.githubusercontent.com/53085155/143672625-dfa85237-dca1-4ff5-8027-bbc5bf2d6e2c.gif)

### I have

- [x] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by chase** [comment]
Source: https://github.com/LunarVim/LunarVim/blob/891cf9944a9f18badffec0c32442610d91f0e96b/lua/lvim/core/autopairs.lua#L34

Autopairs isn't very good at things sometimes

**Comment by aik2mlj** [comment]
Thanks! I wonder if there's a way to change that rule in my `config.lua` file directly?

I've tried these lines but they did not work. `nvim-autopair` was still on for .tex files, so did the `$` bugs.
```lua
local autoPair = require("nvim-autopairs")
autoPair.setup({
	disable_filetype = { "TelescopePrompt", "tex" },
})
autoPair.remove_rule("$")
```

However I can shut `nvim-autopair` down completely by adding
```lua
autoPair.disable()
```

Am I getting something wrong?

**Comment by aik2mlj** [comment]
Also, since these core codes are really messing up latex editing experience, would you guys consider fixing that?

**Comment by chase** [comment]
I'm actually not sure, I've long since disabled the autopairs plugin entirely due to issues like this.

I'm not sure the intention behind including these by default, nor am I aware of an easy way to remove them after they have been added.

I believe @ChristianChiarulli added these rules, so maybe he can answer you better.

**Comment by abzcoding** [comment]
@aik2mlj can you try adding this to your config?
```lua
  lvim.builtin.autopairs.on_config_done = function(autopairs)
    autopairs.remove_rule("$$", "$$", "tex")
    autopairs.remove_rule("$", "$", { "tex", "latex" })
    -- or maybe autopairs.remove_rule("$")
  end
```

**Comment by aik2mlj** [comment]
> @aik2mlj can you try adding this to your config?
> 
> ```lua
> lvim.builtin.autopairs.on_config_done = function(autopairs)
>     autopairs.remove_rule("$$", "$$", "tex")
>     autopairs.remove_rule("$", "$", { "tex", "latex" })
>     -- or maybe autopairs.remove_rule("$")
> end
> ```

Yeah that works! Thanks!
May I ask what this `on_config_done` thing does? Completely new to Lua.

btw I notice that the default "$" rules are the same as the example rules `nvim-autopairs` give. Would you guys consider improving that?

**Comment by abzcoding** [comment]
On_config_done is Something that we added, basically it gets called after we are done configuring. To let you alter things that we didn't expose
