### ISSUE TITLE
[Feature]: vue alias Code hint

### ISSUE THREAD

**Issue by kola-web** [LunarVim/LunarVim#2000]
### Feature motivation

vue alias Code hint

**Comment by chase** [comment]
@kola-web Please provide a description of what you want and potentially share examples where this feature is implemented in other editors.

**Comment by kola-web** [comment]
vscode [path-autocomplete](https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete) 
Path completion plugin supports alias

**Comment by chase** [comment]
I don't think this is something we can support directly.
I think that tsserver can be configured to support this however.

**Comment by kola-web** [comment]
@chase grateful 
I will check how to configure
