### ISSUE TITLE
How to change the git source of packer in lunarvim

### ISSUE THREAD

**Issue by Leiyi548** [LunarVim/LunarVim#2005]
I am in China. I want to use fastgit to download the plug-in. I don't know how to modify it in lunarvim.
    packer.init({
        compile_path = packer_compiled,
        git = {clone_timeout = 120},
        disable_commands = true,
        display = {
            open_fn = function()
                return require("packer.util").float({border = "single"})
            end
        },
       git = {
       default_url_format = 'https://hub.fastgit.org/%s'
      }

**Comment by chase** [comment]
@Leiyi548 Unfortunately there's no good way to do this.

You will have to modify this file:
https://github.com/LunarVim/LunarVim/blob/32ca5afa4ad21f1a616cc30323c272191e7548c1/lua/lvim/plugin-loader.lua#L21-L31

You can probably find it at '~/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua'

**Comment by Leiyi548** [comment]
@chase  Thankyou!
