### ISSUE TITLE
[Bug]: Auto complete duplicates existing text

### ISSUE THREAD

**Issue by aimran-adroll** [LunarVim/LunarVim#2006]
### Problem description

Hi Devs. First of all, thank you for the wonderful tool and your hardwork. 

I am having exact  issues to the one outlined here https://github.com/hrsh7th/nvim-cmp/issues/469, namely, the autocompletion appends to the existing text on screen!

Updating nvim-cmp (or all the packages) did not help. I have disabled all/any extra plugins and using the pure `LunarVim` goodness to no avail. 

I first wanted to check if its a known issue before making a fuss. 

Thanks for reading

![See this](http://g.recordit.co/tJnlM9dtpB.gif)

### LunarVim version

rolling (044b53a6f)

### Neovim version (>= 0.5)

v0.5.1

### Relevant log output

```shell
mac osx 10.15.7

<details><summary>nvim -v</summary>


NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20211103-4538-9q3i0y/neovim-0.5.1/build/config -I/tmp/neovim-20211103-4538-9q3i0y/neovim-0.5.1/src -I/usr/local/include -I/tmp/neovim-20211103-4538-9q3i0y/neovim-0.5.1/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20211103-4538-9q3i0y/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20211103-4538-9q3i0y/neovim-0.5.1/build/include
Compiled by brew@iMac-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.1_1/share/nvim"
```
</details>

I would paste `:checkhealth` except its [busted right now](https://github.com/nvim-treesitter/nvim-treesitter/issues/2044) 

```
❯ lua -v
Lua 5.4.3  Copyright (C) 1994-2021 Lua.org, PUC-Rio
```
```


### Screenshots

![See this](http://g.recordit.co/tJnlM9dtpB.gif)


### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
can you try
```lua
lvim.builtin.cmp.confirm_opts.behavior = require("cmp").ConfirmBehavior.Insert
```

**Comment by chase** [comment]
@aimran-adroll If you do an update to use the latest rolling release, does this fix your issue? It might be resolved after https://github.com/LunarVim/LunarVim/pull/1989

This issue might be related and has been fixed since we bumped the version:
https://github.com/hrsh7th/nvim-cmp/issues/516

---

This isn't something I've encountered and I use the replace behavior, that being said I also have autopairs disabled. It's entirely possible that this is an issue caused by autopairs.

Does this still occur if you disable autopairs, do `:LvimCacheReset`, then try to repeat what you did above?

**Comment by aimran-adroll** [comment]
@abzcoding @chase Thank you for your kind suggestions. 

I tried the `Insert` behavior and it did not work

I then tried Chase's suggestion and tried updating. At first it did not work but I realized that the nvim-lspconfig package was completely messed up after the PackerSync. So I nuked it and re-installed. Finally it seems to be working 🎉 

I shall close it for now. 

Thanks again
