### ISSUE TITLE
[Question] How to change GitSigns color in lualine

### ISSUE THREAD

**Issue by NikoKS** [LunarVim/LunarVim#2009]
https://github.com/LunarVim/LunarVim/blob/8641c38c862d3e9818791673a9366831b81ff603/lua/lvim/core/lualine/components.lua#L40-L42

Hi, I was wondering on how to change the color of GitSigns components in lualine.

**Comment by chase** [comment]
Something like this:
https://github.com/chase/lvim/blob/main/config.lua#L206-L244
