### ISSUE TITLE
[Bug]: The output pwd shows the root directory in lvim(Telescope did not search the current folder)  Please help me.🙏🏻🙏🏻

### ISSUE THREAD

**Issue by Leiyi548** [LunarVim/LunarVim#2011]
### Problem description

When I use nvim to use telescope, he can search the current folder, and when I use lvim, he will search the root directory.

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6.0 HEAD

### Relevant log output

```shell
NVIM v0.6.0-dev+647-gb16b7021e
Build type: Release
LuaJIT 2.1.0-beta3
```

### Screenshots

![image](https://user-images.githubusercontent.com/76139422/144080640-e5abe6db-0d89-4766-b7e3-e39ee388d753.png)
![image](https://user-images.githubusercontent.com/76139422/144080795-75d3de94-ca6d-4a8a-b55a-561342b56098.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Leiyi548** [comment]
telescope screenshot 
![image](https://user-images.githubusercontent.com/76139422/144081402-7a820588-7b01-417f-9c5c-061e0f96e37b.png)
![image](https://user-images.githubusercontent.com/76139422/144081514-08b5196c-0626-43ea-a329-f498bf3ca856.png)
This first picture is lvim, and the second picture is nvim.

**Comment by kylo252** [comment]
- please do `LvimUpdate` and try again
- what is the full path to that file? I'm wondering if it has something to do with unicode
- try `lvim.builtin.telescope.extensions.fzf = nil` and see if it makes a difference

**Comment by Leiyi548** [comment]
@kylo252 I found that if I was in a directory controlled by git, he could search normally in that file directory, and when I went to a normal directory, I would search for the root directory.

**Comment by Leiyi548** [comment]
@kylo252 I think it's project.nvim 's problem.

**Comment by Leiyi548** [comment]
@kylo252 
 -- All the patterns used to detect root dir, when **"pattern"** is in
  -- detection_methods
  patterns = { ".git", "_darcs", ".hg", ".bzr", ".svn", "Makefile", "package.json" },
It will search the root directory based on this pattern, and when it does not have it, it will search all the way up to the root directory.

**Comment by Leiyi548** [comment]
@kylo252 
set	lvim.builtin.project.manual_mode = true
Project.nvim will not automatically change your directory, but you need to do it manually

**Comment by kylo252** [comment]
> @kylo252 set lvim.builtin.project.manual_mode = true Project.nvim will not automatically change your directory, but you need to do it manually

You can also try only enabling `lsp` in as a detection mode and see if it helps
```lua
lvim.builtin.project.detection_methods = { "lsp" }
```

**Comment by Leiyi548** [comment]
@kylo252 Yes, so he won't change my catalog. He will judge the project based on lsp.
