### ISSUE TITLE
[Bug]: Multiple LSP servers spawned

### ISSUE THREAD

**Issue by youdaniel** [LunarVim/LunarVim#2012]
### Problem description

`lvim a.py`
`:LspInfo`
![image](https://user-images.githubusercontent.com/39450656/144133701-1b60f071-0732-4f64-aa25-135228f450bf.png)
Also happens in some other languages too. Started happening after #1989

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by mjlbach** [comment]
This is a feature of lspconfig. If you open a bare python file, with no way for us to identify the project structure, we spawn a single language server per directory which is shared.

**Comment by youdaniel** [comment]
> per directory which is shared

What do you mean by this? Pyright always seems to spawn three times for me, except in a directory where the root directory pattern matches.

Is there a way for it to only spawn once for bare files? The duplicate error messages can be weird to work with.

**Comment by kylo252** [comment]
I'm unable to replicate this issue. I only get a single `pyright` instance with these steps:

```shell
mkdir -p /tmp/test
touch /tmp/test/test.py
lvim  /tmp/test/test.py
```

Where is that file that you're testing is located?

**Comment by abzcoding** [comment]
@kylo252 i'm not sure why but it seems like this part is called more than once
```lua
  requested_server:on_ready(function()
    if install_notification then
      vim.notify(string.format("Installation complete for [%s] server", requested_server.name), vim.log.levels.INFO)
    end
    install_notification = false
    requested_server:setup(config)
  end)
```

**Comment by kylo252** [comment]
@abzcoding, unless something has changed in implementation in the installer, then we're only setting up once. I'm not sure which instance you're referring to as being called twice.

**Comment by kylo252** [comment]
> Hey, I seem to have the same issue. Here this is regarding "sumneko_lua". When I open `config.lua` 2 instances of lua-language server is spawned 

@ashincoder, please try using [tests/minimal_lsp.lua](https://github.com/LunarVim/LunarVim/blob/rolling/tests/minimal_lsp.lua), just make sure to change the server name to whichever server you're having trouble with, and then start neovim like this:

```shell
nvim -u tests/minimal_lsp.lua
```

**Comment by abzcoding** [comment]
> @abzcoding, unless something has changed in implementation in the installer, then we're only setting up once. I'm not sure which instance you're referring to as being called twice.

<img width="1679" alt="Screen Shot 2021-12-01 at 6 44 29 PM" src="https://user-images.githubusercontent.com/10992695/144260726-1733db95-c851-43b2-96f7-0254f1f25f1f.png">

**Comment by kylo252** [comment]
@abzcoding, what's the result of
```console
:! git -C $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/nvim-lsp-installer log -1
```

- is it the same issue with `minimal_lsp.lua` ?
- what happens if you switch the `on_server_ready` callback to use `schedule_wrap` instead, I know I had problems with it at some point. Change it here: https://github.com/williamboman/nvim-lsp-installer/blob/a4016db22296e4eefbcda2e8b94de74db2d7cb65/lua/nvim-lsp-installer.lua#L217

**Comment by abzcoding** [comment]
> @abzcoding, what's the result of
> 
> ```
> :! git -C $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/nvim-lsp-installer log -1
> ```
> 
>  * is it the same issue with `minimal_lsp.lua` ?
> * what happens if you switch the `on_server_ready` callback to use `schedule_wrap` instead, I know I had problems with it at some point. Change it here: https://github.com/williamboman/nvim-lsp-installer/blob/a4016db22296e4eefbcda2e8b94de74db2d7cb65/lua/nvim-lsp-installer.lua#L217

this is the result of that git command, let me try the rest
<img width="691" alt="Screen Shot 2021-12-01 at 7 03 02 PM" src="https://user-images.githubusercontent.com/10992695/144263903-36dbcc44-8f46-436e-8292-d5d8b70f98b5.png">

**Comment by ashincoder** [comment]
Now it works fine. I don't know how. here is the recording

https://user-images.githubusercontent.com/83629316/144265784-67c8dd7c-c4ba-4275-8382-f7059db5a0a2.mp4

**Comment by abzcoding** [comment]
@kylo252 it seems like [this commit](https://github.com/LunarVim/LunarVim/commit/24be0ef1ef36b8cc725655e920104e9676b72f25)  causes the issue 
anything before that is fine

**Comment by Manndung75** [comment]
Báo

**Comment by kylo252** [comment]
@abzcoding, try `<leader>Lg` --> search for `pyright`.  I wonder if `require("lvim.lsp.manager").setup("pyright")` is defined more than once for some reason.

**Comment by abzcoding** [comment]
> @abzcoding, try `<leader>Lg` --> search for `pyright`. I wonder if `require("lvim.lsp.manager").setup("pyright")` is defined more than once for some reason.

nope 😞 
<img width="1593" alt="Screen Shot 2021-12-01 at 7 52 48 PM" src="https://user-images.githubusercontent.com/10992695/144272381-62b7dd66-cb04-4750-b484-217171f1b4e2.png">

**Comment by abzcoding** [comment]
the weird thing is that, it only happens for pyright 🤔 , let me try some stuff and get back to you

**Comment by youdaniel** [comment]
> I'm unable to replicate this issue. I only get a single `pyright` instance with these steps:
> 
> ```shell
> mkdir -p /tmp/test
> touch /tmp/test/test.py
> lvim  /tmp/test/test.py
> ```
> 
> Where is that file that you're testing is located?

It happens to me pretty much everywhere, except in a directory where the root marker is found (e.g. pyproject.toml). I also tried in /tmp, same issue.

Another weird thing I noticed is that if I do `lvim test.py` multiple pyright instances are spawned, but if I do `:e test.py` only one instance is spawned.

**Comment by ashincoder** [comment]
https://user-images.githubusercontent.com/83629316/144277026-65160b07-abed-4305-8bb6-2546c6e0fee3.mp4

It does happen with lua also. Check this ..

**Comment by abzcoding** [comment]
@kylo252 sth like this fixes the issue, but i think we should find the root cause
<img width="526" alt="Screen Shot 2021-12-01 at 8 26 59 PM" src="https://user-images.githubusercontent.com/10992695/144278553-3a828b39-979f-4e43-a701-7cb4b2b4cb09.png">

**Comment by kylo252** [comment]
I still can't reproduce this 😞 

https://user-images.githubusercontent.com/59826753/144290057-97897108-6563-4782-9404-0099b95a7828.mp4

**Comment by abzcoding** [comment]
> I still can't reproduce this 😞
> 
>  f6dWFqLFc0.mp4

make sure you have some linters/formatters configured as well, maybe that helps 🤔

**Comment by kylo252** [comment]
> make sure you have some linters/formatters configured as well, maybe that helps 🤔

Still can't trigger the bug 😞 

https://user-images.githubusercontent.com/59826753/144292590-92fc7024-7186-40df-9860-31dbdfedbef0.mp4

**Comment by abzcoding** [comment]
somehow the `.local/share/lunarvim/lvim/site/after/ftplugin/python.lua` file gets called twice, still looking for the root cause
<img width="910" alt="Screen Shot 2021-12-01 at 10 23 02 PM" src="https://user-images.githubusercontent.com/10992695/144295856-1a9b5aaf-808f-4ceb-91f9-58a1a9d4a9bc.png">

**Comment by abzcoding** [comment]
@kylo252 can you try adding this to `lvim.plugins`, and check if you face the issue or not?
```lua
    {
      "danymat/neogen",
      config = function()
        require("neogen").setup {
          enabled = true,
        }
      end,
      ft = { "lua", "python", "javascript", "typescriptreact", "c", "cpp", "go", "java" },
      event = "InsertEnter",
      requires = "nvim-treesitter/nvim-treesitter",
    },
```

**Comment by abzcoding** [comment]
this change in my configuration fixes everything, i'm officially mind blown 🤯 
<img width="773" alt="Screen Shot 2021-12-01 at 10 58 34 PM" src="https://user-images.githubusercontent.com/10992695/144300680-34a35cf0-5733-468b-823f-66075c32231e.png">

**Comment by youdaniel** [comment]
Changed something similar in my config and it seemed to fix the issue too 🤯 
It's somehow related to lazy loading plugins (getting rid of the lazy load fixed it). For me I had to disable lazy loading for `andymass/vim-matchup`, `mfussenegger/nvim-dap-python`, and `Vimjas/vim-python-pep8-indent`.

**Comment by kylo252** [comment]
ummmm... yeah, I don't know how to explain any of this 😅 
I haven't really changed anything regarding the lsp-setup for quite a while, so I'm not really sure what is up with that.

One thing to try is override `pyright`, install it manually and see if it makes a difference. Ref: https://www.lunarvim.org/languages/#overriding-the-default-setup-options

**Comment by ashincoder** [comment]
But I don't see a difference. I deleted all the custom plugins I had. I use neorg and neogen.
Still no difference

https://user-images.githubusercontent.com/83629316/144350590-dc02329f-c6fc-4289-8d90-25d1d352911b.mp4

**Comment by aik2mlj** [comment]
Hi I also encountered this multiple servers stuff when using `texlab`.
![图片](https://user-images.githubusercontent.com/53085155/144697059-3c4912fb-5dd5-43f0-8f53-33c9debf5831.png)

Everytime I save my tex file, it will ask me to choose one server, which is really annoying.
![图片](https://user-images.githubusercontent.com/53085155/144697043-514b6a31-a5d4-4d65-8a91-8b76bdbdcd98.png)

**Comment by ashincoder** [comment]
These are the things I found out.
So for instance using pyright, if I open a bare python file more than 1 pyright servers are spawned.
But if I have setup.py in my root dir, then only 1 instance is spawned. 
This is applies for all the lang servers I think. If I have a git managed dir, then sumneko_lua is spawned once. But if I launch a bare lua file more than 1 instances of sumneko is spawned. But this happens in LunarVim only.

I do have my own personal config. When I launch a bare lua file only 1 instance of sumneko is spawned.

**Comment by kylo252** [comment]
> I do have my own personal config. When I launch a bare lua file only 1 instance of sumneko is spawned.

What setup call are you using? is it directly with lspconfig? or are you also using the lsp-installer?

**Comment by ashincoder** [comment]
> > I do have my own personal config. When I launch a bare lua file only 1 instance of sumneko is spawned.
> 
> What setup call are you using? is it directly with lspconfig? or are you also using the lsp-installer?

I did use lspconfig with nix package manager. Now I have made it setup using lsp-installer

**Comment by ashincoder** [comment]
https://user-images.githubusercontent.com/83629316/144702715-2d24db78-d645-402d-8296-0a81e25a2848.mp4

**Comment by kylo252** [comment]
@ashincoder, please share:
- lvim version (`:LvimVersion`)
- neovim version (`:version`)
- system version (probably `cat /etc/*release*`)

I still can't reproduce this, so please try the following in your `config.lua`

```lua
vim.list_extend(lvim.lsp.override, { "pyright" })
require('lvim.utils.hooks').reset_cache() -- or call `:LvimCacheReset`
```

Now you need to call the setup function manually, first try

```lua
require("lvim.lsp.manager").setup("pyright", {})
```

If that still causes the issue then try this instead of 

```lua
require("lspconfig").setup["pyright"]({})
```

It would be good if you could try this

```lua
local lsp_installer_servers = require'nvim-lsp-installer.servers'
local server_available, requested_server = lsp_installer_servers.get_server("pyright")
if server_available then
    requested_server:on_ready(function ()
        local opts = {}
        requested_server:setup(opts)
    end)
end
```

**Comment by ashincoder** [comment]
- lvim version : Latest commit on rolling branch
- nvim version : 0.6

Hey, I also found a way to solve this issue. Could u look at this video and give ur thoughts.

https://user-images.githubusercontent.com/83629316/144704545-373491e8-eed1-4ad3-9412-93ee755156df.mp4

I tried this method with the following lang servers and now it only spawns a single instance.

**Comment by kylo252** [comment]
> I think by setting up lang servers in after/ftplugin, the lang servers are been called for second time.

@ashincoder, are you overriding `pyright`? did you run `:LvimCacheReset`? 

If you did both of those, then you shouldn't have any call to set up `pyright` unless you write it yourself, otherwise `pyright` will **not** be configured whatsoever. See here: https://github.com/LunarVim/LunarVim/issues/2012#issuecomment-983803704.

You can also search for the call manually from the command-line

```shell
rg 'setup\("pyright"\)' ~/.config/lvim ~/.local/share/lunarvim
# also check the results of this
rg 'setup.pyright' ~/.config/lvim ~/.local/share/lunarvim
```

**Comment by abzcoding** [comment]
@ashincoder 
since we are setting up the pyright server in
 ` ~/.local/share/lunarvim/site/after/ftplugin/python.lua` 
why are you setting it up again in 
`~/.config/lvim/after/python.lua` ?

**Comment by ashincoder** [comment]
I made the mistake. The thing is that I didn't override pyright before configuring it. Sorry for the inconvenience I made. :cry:

**Comment by meijieru** [comment]
@abzcoding So does this come from the packer's lazy loading? And what's the best practice to avoid it?

**Comment by meijieru** [comment]
Seems related https://github.com/wbthomason/packer.nvim/issues/648

**Comment by abzcoding** [comment]
> @abzcoding So does this come from the packer's lazy loading? And what's the best practice to avoid it?
> Lazy loading something like `vim-matchup` may break the LSP, that seems crazy.
> I have a similar observation the files in `after/ftplugin` may be called multiple times.

I think issue raises when you use `ft=` in your plugins. Not entirely sure though

**Comment by MOHENOO** [comment]
> Changed something similar in my config and it seemed to fix the issue too 🤯 It's somehow related to lazy loading plugins (getting rid of the lazy load fixed it). For me I had to disable lazy loading for `andymass/vim-matchup`, `mfussenegger/nvim-dap-python`, and `Vimjas/vim-python-pep8-indent`.

When i uninstall andymass/vim-matchup,It works fiine. And i reinstall  andymass/vim-matchup, two lsp server is running.

**Comment by abzcoding** [comment]
> > Changed something similar in my config and it seemed to fix the issue too 🤯 It's somehow related to lazy loading plugins (getting rid of the lazy load fixed it). For me I had to disable lazy loading for `andymass/vim-matchup`, `mfussenegger/nvim-dap-python`, and `Vimjas/vim-python-pep8-indent`.
> 
> When i uninstall andymass/vim-matchup,It works fiine. And i reinstall andymass/vim-matchup, two lsp server is running.

you can either try
```lua
    {
      "andymass/vim-matchup",
      event = "BufReadPost",
      config = function()
        vim.g.matchup_enabled = 1
        vim.g.matchup_surround_enabled = 1
        vim.g.matchup_matchparen_deferred = 1
        vim.g.matchup_matchparen_offscreen = { method = "popup" }
      end,
    },
```
or https://github.com/LunarVim/LunarVim/pull/2042

**Comment by edte** [comment]
I encountered the same problem. When I opened the go file, two gopls clients were generated. The final investigation found that I set the lazy loading event in the gopls plug-in. After commenting out the lazy loading, it returned to normal.
