### ISSUE TITLE
[Bug]: nvimtree 'h' and 'l' are not working

### ISSUE THREAD

**Issue by angryheng** [LunarVim/LunarVim#2013]
### Problem description

nvimtree 'h' and 'l' are not working

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Gael101** [comment]
https://github.com/LunarVim/LunarVim/pull/2007 
Fyi a PR fixing this has already been accepted and is waiting to get merged :)

**Comment by angryheng** [comment]
@Gael101 thanks
