### ISSUE TITLE
[Feature]: Label Comment.nvim bindings in which-key

### ISSUE THREAD

**Issue by lavifb** [LunarVim/LunarVim#2022]
### Feature motivation

Currently, hitting `g` pulls up the nice which-key window but the Comment.nvim bindings (`gb` and `gc` for instance) show the lua code instead of nice names like comment line or block comment
![Screen Shot 2021-12-02 at 10 25 43 AM](https://user-images.githubusercontent.com/1918691/144451752-22792c06-74c4-4526-8e04-45a32e4f4e88.png)

### Describe the expected solution

All these key bindings should be named in the which-key config.
It looks like currently the which-key config does not include bindings for `g` presets so they may need to be added

### Additional context

This has likely been an issue since https://github.com/LunarVim/LunarVim/pull/1736

**Comment by abzcoding** [comment]
sadly this was rejected on https://github.com/numToStr/Comment.nvim/pull/80

**Comment by hawkinchina** [comment]
why gbc  (block comment) cannot work for lua/ typescript ?   gcc is OK.
