### ISSUE TITLE
[Feature]: Support for nvim-orgmode/orgmode treesitter parser config

### ISSUE THREAD

**Issue by muhmud** [LunarVim/LunarVim#2024]
### Feature motivation

The [nvim-orgmode](https://github.com/nvim-orgmode/orgmode) treesitter parser requires some setup, it would be great if lunarvim had this out-of-the-box.

### Describe the expected solution

I can use `TSInstall` to add the parser for orgmode.

### Describe the alternatives you've considered

I've considered setting it up myself in a way that works with lvim

**Comment by luxus** [comment]
https://github.com/abzcoding/lvim/search?q=orgmode
there is a intigration .. i don't think this should be in lunarvim core..

**Comment by muhmud** [comment]
As far as I can see, this doesn't have the treesitter parser setup, which is a fairly new addition to org-mode.

If there's tree-sitter support included for so many other languages, why not include org-mode as well? I'm not saying include org-mode itself, just the treesitter parts

**Comment by muhmud** [comment]
This is actually fine, I think I was using `LspInstall` rather than `TSInstall`.

Strange this, is now I have no colouring at all, which is, however, a separate issue.
