### ISSUE TITLE
[Bug]: Telescope File Finder doesn't Ignore `.gitignore`

### ISSUE THREAD

**Issue by christopher-besch** [LunarVim/LunarVim#2028]
### Problem description

In a version of LunarVim from over a month ago the Telescope file finder ignored anything matched by the local `.gitignore`. In the latest release this isn't the case anymore and searching with it results in a lot of clutter.
When I'm looking for one of my code files I don't care about those bazillion `node_module` files.

### LunarVim version

0.6.1
As of the creation of this Issue, the latest rolling version shows the same problem.

### Neovim version (>= 0.5)

v0.7.0-dev+667-g419e0d117

### Screenshots

![image](https://user-images.githubusercontent.com/57909184/144698670-77381065-c294-4815-a93d-c76b3c8df535.png)
I'm looking for my `index.tsx` file but instead I get a lot of garbage from the `node_modules` directory.

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by chase** [comment]
If you do a `fd index` in the same directory does it produce the same output?

We haven't changed the settings and Telescope's version is pinned, so I'm not sure this is on our side of things. Can you post your config.lua?

**Comment by christopher-besch** [comment]
[This](https://github.com/christopher-besch/lvim_like_me/blob/main/config.lua) is my config but the problem is still present when I comment my entire config. In addition to that I didn't change anything in my `config.lua` when updating LunarVim, since Nov 15, 2021 (the commits after that are only adding some comments).

**Comment by christopher-besch** [comment]
Solved it; I didn't have `fd` installed as I moved from Fedora to Manjaro. I didn't know this was a dependency of LunarVim. Maybe this should be noted in the documentation.

**Comment by christopher-besch** [comment]
I've opened a [PR](https://github.com/LunarVim/lunarvim.org/pull/144), which is also adding `xclip`.

**Comment by kylo252** [comment]
> Solved it; I didn't have `fd` installed as I moved from Fedora to Manjaro. I didn't know it was a dependency of LunarVim. Maybe this should be noted in the documentation.

It does show up in `:checkhealth` as well.

**Comment by kylo252** [comment]
The weird part is that `ripgrep` should've been the next in line if `fd` was not found, and it should've ignored those unless you have modified its config somehow.

**Comment by christopher-besch** [comment]
> `ripgrep` should've been the next in line

I mean the file search still worked, it just didn't ignore using the `.gitignore`. Maybe `ripgrep` just doesn't care about the `.gitignore`.

**Comment by kylo252** [comment]
It does care unless you specified otherwise.

**Comment by christopher-besch** [comment]
> It does care unless you specified otherwise.

Weird, even with the default config it didn't work...

**Comment by kylo252** [comment]
> Weird, even with the default config it didn't work and I'm pretty sure I didn't explicitly tell it not to...

It could be that it was invoked from a different directory then. 

---

_Tip: you can add global ignore settings for `fd` in `~/.config/fd/ignore` and for `rg` in `~/.config/ripgrep/ripgreprc`._

**Comment by christopher-besch** [comment]
![image](https://user-images.githubusercontent.com/57909184/144711312-7228963b-6fb9-4c05-a23d-d712bad450db.png)
mh...
I didn't touch these.
