### ISSUE TITLE
[Bug]: nvim-ts-context-commentstring broken with new commit

### ISSUE THREAD

**Issue by Dulanjala007** [LunarVim/LunarVim#2029]
### Problem description

`core/commnt.lua` needs to be updated (rename `pre_hook` to `custom_calculation`) according to https://github.com/JoosepAlviste/nvim-ts-context-commentstring/commit/9f5e422e1030e7073e593ad32c5354aa0bcb0176

### LunarVim version

rolling

### Neovim version (>= 0.5)

NVIM v0.7.0-dev

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
@kylo252 can you add this fix to the https://github.com/LunarVim/LunarVim/pull/2031 as well?

**Comment by kylo252** [comment]
I think it's the wrong file. The options in `core/comment.lua` are only passed to `comment.nvim` and not to `ts-context-commentstring`.

**Comment by abzcoding** [comment]
> I think it's the wrong file. The options in `core/comment.lua` are only passed to `comment.nvim` and not to `ts-context-commentstring`.

oh you are right, we don't even use it atm, https://github.com/LunarVim/LunarVim/blob/e292d665f161ee58477a5c1011313ef10a7fef8e/lua/lvim/core/treesitter.lua#L18-L30

**Comment by kylo252** [comment]
So I don't think there's anything to be done, right? Maybe some of these are read internally in 'comment.nvim'.

**Comment by abzcoding** [comment]
> So I don't think there's anything to be done, right? Maybe some of these are read internally in 'comment.nvim'.

yep, we are fine https://github.com/numToStr/Comment.nvim#-hooks
