### ISSUE TITLE
[Bug]: [ERROR]: Unable to find dependency []

### ISSUE THREAD

**Issue by BrightXiaoHan** [LunarVim/LunarVim#2032]
### Problem description

I install lunarVim on windows10 by:
```
.\install.ps1
```
I have installed nodejs, but the install script raise an error when checking lunarvim's NodeJS dependencies.

![image](https://user-images.githubusercontent.com/25839309/144708242-01c185f2-b947-4d5a-8608-2cac3b814f95.png)

my node and npm versions

![image](https://user-images.githubusercontent.com/25839309/144708256-4aa2b2c0-99cf-48eb-90ae-9fa403e52b84.png)

### LunarVim version

rolling

### Neovim version (>= 0.5)

v0.6.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Please run these commands manually, and show me the output if they fail

```shell
npm install -g neovim tree-sitter-cli
python -m pip install --user pynvim
```

**Comment by BrightXiaoHan** [comment]
![image](https://user-images.githubusercontent.com/25839309/144717181-f0acc0fe-a57f-4011-a300-2df0df70a7bb.png)
No error raised for both commands

**Comment by kylo252** [comment]
> No error raised for both commands

You can now skip both node and python deps in the installer then :)

**Comment by BrightXiaoHan** [comment]
Thanks, works for me. 
By the way, is it possible to provide an "exe" format installer in the future?

**Comment by BrightXiaoHan** [comment]
or "choco install lunarvim" stuff

**Comment by kylo252** [comment]
I'm more inclined to using scoop if anything. This should all be tracked, probably in #1823.
