### ISSUE TITLE
[Bug]: I want to map some of my keys to ctrl+ direction keys, but it doesn't work.

### ISSUE THREAD

**Issue by Leiyi548** [LunarVim/LunarVim#2036]
### Problem description

I want to map some of my keys to ctrl+ direction keys, but it doesn't work.

### LunarVim version

rolling

### Neovim version (>= 0.5)

NVIM v0.7.0-dev+656-g36565c9da Build type: Release LuaJIT 2.1.0-beta3

### Relevant log output

```shell
NVIM v0.7.0-dev+656-g36565c9da
Build type: Release
LuaJIT 2.1.0-beta3
```

### Screenshots

![image](https://user-images.githubusercontent.com/76139422/144739934-64e5119e-080f-42a3-9647-8831491ae4cc.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
can you run 
```vim
:verbose map <C-Left>
```

**Comment by Leiyi548** [comment]
@abzcoding  
![image](https://user-images.githubusercontent.com/76139422/144741806-39f7e956-e27a-482d-994e-58bc0092c0aa.png)

**Comment by abzcoding** [comment]
> @abzcoding
> ![image](https://user-images.githubusercontent.com/76139422/144741806-39f7e956-e27a-482d-994e-58bc0092c0aa.png)

so the keybinding has been set, what is the issue here 😅

**Comment by abzcoding** [comment]
sidenote: please try using `:` instead of `<Cmd>`

**Comment by abzcoding** [comment]
> @abzcoding I rewrote it, and I found that this key didn't work. I didn't execute it with the ctrl+ arrow key.

i'm a bit confused here, the keybinding has been set correctly so is there anything else that you expect to happen or?

**Comment by Leiyi548** [comment]
@abzcoding  I rewrote ctrl+up,ctrl+down, but its behavior is not what I expected, but to move the current line, I am in macos catlina

**Comment by abzcoding** [comment]
> @abzcoding I rewrote ctrl+up,ctrl+down, but its behavior is not what I expected, but to move the current line, I am in macos catlina

ctrl+up and ctrl+down are system keybindings in macos, you cannot use them in lvim
