### ISSUE TITLE
rust-tools plugin does not work properly

### ISSUE THREAD

**Issue by crucificados666** [LunarVim/LunarVim#2038]
I use Lunarvim (master, v0.6.1). I did follow exactly all instructions @lunarvim.org to install rust support and  rust-tools.nvim. Everything worked fine the first time when I opened a .rs file. After that all additional rust-tools commands disappear from the wildmenu when I reopened this file. Here is my config.lua from ~/config/lvim/

```lua
local formatters = require("lvim.lsp.null-ls.formatters")
formatters.setup({
	{
		exe = "stylua",
		filetypes = { "lua" },
	},
	{
		exe = "rustfmt",
		filetypes = { "rust", "rs" },
	},
})

-- -- set additional linters
-- local linters = require "lvim.lsp.null-ls.linters"
-- linters.setup {
--   { exe = "flake8", filetypes = { "python" } },
--   {
--     exe = "shellcheck",
--     ---@usage arguments to pass to the formatter
--     -- these cannot contain whitespaces, options such as `--line-width 80` become either `{'--line-width', '80'}` or `{'--line-width=80'}`
--     args = { "--severity", "warning" },
--   },
--   {
--     exe = "codespell",
--     ---@usage specify which filetypes to enable. By default a providers will attach to all the filetypes it supports.
--     filetypes = { "javascript", "python" },
--   },
-- }

-- Additional Plugins
-- lvim.plugins = {
--     {"folke/tokyonight.nvim"},
--     {
--       "folke/trouble.nvim",
--       cmd = "TroubleToggle",
--     },
-- }
lvim.lsp.override = { "rust" }
lvim.plugins = {
	{
		"norcalli/nvim-colorizer.lua",
		config = function()
			require("colorizer").setup({ "*" }, {
				RGB = true, -- #RGB hex codes
				RRGGBB = true, -- #RRGGBB hex codes
				RRGGBBAA = true, -- #RRGGBBAA hex codes
				rgb_fn = true, -- CSS rgb() and rgba() functions
				hsl_fn = true, -- CSS hsl() and hsla() functions
				css = true, -- Enable all CSS features: rgb_fn, hsl_fn, names, RGB, RRGGBB
				css_fn = true, -- Enable all CSS *functions*: rgb_fn, hsl_fn
			})
		end,
	},
	{
		"folke/todo-comments.nvim",
		event = "BufRead",
		config = function()
			require("todo-comments").setup()
		end,
	},

	{
		"tpope/vim-surround",
		keys = { "c", "d", "y" },
	},
	{
		"p00f/nvim-ts-rainbow",
	},
	{
		"simrat39/rust-tools.nvim",
		config = function()
			require("rust-tools").setup({
				tools = {
					autoSetHints = true,
					hover_with_actions = true,
					runnables = {
						use_telescope = true,
					},
				},
				server = {
					cmd = { vim.fn.stdpath("data") .. "/lsp_servers/rust/rust-analyzer" },
					on_attach = require("lvim.lsp").common_on_attach,
					on_init = require("lvim.lsp").common_on_init,
				},
			})
		end,
		ft = { "rust", "rs" },
	},
}

```

**Comment by abzcoding** [comment]
can you use this instead
```lua
vim.list_extend(lvim.lsp.override, { "rust_analyzer" })

lvim.plugins = {
  {
    "simrat39/rust-tools.nvim",
    config = function()
      local lsp_installer_servers = require "nvim-lsp-installer.servers"
      local _, requested_server = lsp_installer_servers.get_server "rust_analyzer"
      require("rust-tools").setup {
        tools = {
          autoSetHints = true,
          hover_with_actions = true,
          runnables = {
            use_telescope = true,
          },
        },
        server = {
          cmd = requested_server._default_options.cmd,
          on_attach = require("lvim.lsp").common_on_attach,
          on_init = require("lvim.lsp").common_on_init,
        },
      }
    end,
    ft = { "rust", "rs" },
  },
}
```

**Comment by crucificados666** [comment]
does not work. same result as before. my config.lua looks now

local formatters = require("lvim.lsp.null-ls.formatters")
formatters.setup({
	{
		exe = "stylua",
		filetypes = { "lua" },
	},
	{
		exe = "rustfmt",
		filetypes = { "rust", "rs" },
	},
})

-- -- set additional linters
-- local linters = require "lvim.lsp.null-ls.linters"
-- linters.setup {
--   { exe = "flake8", filetypes = { "python" } },
--   {
--     exe = "shellcheck",
--     ---@usage arguments to pass to the formatter
--     -- these cannot contain whitespaces, options such as `--line-width 80` become either `{'--line-width', '80'}` or `{'--line-width=80'}`
--     args = { "--severity", "warning" },
--   },
--   {
--     exe = "codespell",
--     ---@usage specify which filetypes to enable. By default a providers will attach to all the filetypes it supports.
--     filetypes = { "javascript", "python" },
--   },
-- }

-- Additional Plugins
-- lvim.plugins = {
--     {"folke/tokyonight.nvim"},
--     {
--       "folke/trouble.nvim",
--       cmd = "TroubleToggle",
--     },
-- }
vim.list_extend(lvim.lsp.override, { "rust_analyzer" })
lvim.plugins = {
	{
		"norcalli/nvim-colorizer.lua",
		config = function()
			require("colorizer").setup({ "*" }, {
				RGB = true, -- #RGB hex codes
				RRGGBB = true, -- #RRGGBB hex codes
				RRGGBBAA = true, -- #RRGGBBAA hex codes
				rgb_fn = true, -- CSS rgb() and rgba() functions
				hsl_fn = true, -- CSS hsl() and hsla() functions
				css = true, -- Enable all CSS features: rgb_fn, hsl_fn, names, RGB, RRGGBB
				css_fn = true, -- Enable all CSS *functions*: rgb_fn, hsl_fn
			})
		end,
	},
	{
		"folke/todo-comments.nvim",
		event = "BufRead",
		config = function()
			require("todo-comments").setup()
		end,
	},

	{
		"tpope/vim-surround",
		keys = { "c", "d", "y" },
	},
	{
		"p00f/nvim-ts-rainbow",
	},
	{
		"simrat39/rust-tools.nvim",
		config = function()
			local lsp_installer_servers = require("nvim-lsp-installer.servers")
			local _, requested_server = lsp_installer_servers.get_server("rust_analyzer")
			require("rust-tools").setup({
				tools = {
					autoSetHints = true,
					hover_with_actions = true,
					runnables = {
						use_telescope = true,
					},
				},
				server = {
					cmd = requested_server._default_options.cmd,
					on_attach = require("lvim.lsp").common_on_attach,
					on_init = require("lvim.lsp").common_on_init,
				},
			})
		end,
		ft = { "rust", "rs" },
	},
}

@abzcoding  
When I did clone your repo/config a few days ago then rust-tools did work properly. 

I forgot to mention that I use nvim 0.7 dev.

**Comment by abzcoding** [comment]
yeah wanted to say that this is my current nvim as well, and the rust stuff works perfect
<img width="205" alt="Screen Shot 2021-12-05 at 10 42 29 PM" src="https://user-images.githubusercontent.com/10992695/144760217-34d6e24a-d5d5-4959-9823-01480724d9db.png">
 
 wonder what might be the issue 🤔

**Comment by abzcoding** [comment]
@kylo252 @chase do you guys have any idea what might cause this?

**Comment by crucificados666** [comment]
I have just done a :LvimCacheReset

It works at the moment.

**Comment by abzcoding** [comment]
> I have just done a :LvimCacheReset
> 
> It works at the moment.

my bad, forgot to mention that you have to run that to make sure nothing from your old config is cached  🤦
