### ISSUE TITLE
[Bug]: Not function with Intelephense lsp

### ISSUE THREAD

**Issue by yebt** [LunarVim/LunarVim#2041]
### Problem description

Try install  lsp support to PHP and configure the license key
but the server don't start, not found the root intelephense directory 

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [ ] The programs specified by the config are installed

### LunarVim version

stable

### Neovim version (>= 0.5)

0.6

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Please make sure it's in a git repo or create a `compose.json` file in the same directory.

ref: https://github.com/neovim/nvim-lspconfig/blob/22b21bc000a8320675ea10f4f50f1bbd48d09ff2/doc/server_configurations.md#L2402
