### ISSUE TITLE
[Bug]: Unable to run executable lazygit

### ISSUE THREAD

**Issue by camiloaromero23** [LunarVim/LunarVim#2047]
### Problem description

1. Update LunarVim from commit 02a1e769be9139dfe7294d24b7be2d09bb30b77f with `lvim +LvimUpdate +q` command.
2. Open LunarVim
3. See error log

### LunarVim version

Rolling branch

### Neovim version (>= 0.5)

NVIM v0.6.0

### Relevant log output

```shell
12:52:28 [ERROR] lvim: "Unable to run executable lazygit. Please make sure it is installed properly." file="terminal.lua", line=86
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by Uzaaft** [comment]
Just to make sure, since you did not mention it anywhere: Do you have lazygit installed?
