### ISSUE TITLE
[Bug]: Lvim crashes after updating with bufferline.nvim plugin installed

### ISSUE THREAD

**Issue by Nephasis** [LunarVim/LunarVim#2058]
### Problem description

To reproduce:
1. Install Lvim from master
2. Add   
`{'akinsho/bufferline.nvim', requires = 'kyazdani42/nvim-web-devicons'},`
To plugins
3. Run :PackerSync (at this point everything works fine)
4. Run :LvimUpdate - this is when things break with the following error:

`Error detected while processing BufWinEnter Autocommands for "*":                                                                                                                                            
E5108: Error executing lua ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/l
oad.lua:110: Vim(let):E5108: Error executing lua [string \"luaeval()\"]:1: loop or previous error loading module 'bufferline.render'                                                                         
stack traceback:                                                                                                                                                                                             
        [C]: in function 'cmd'                                                                                                                                                                               
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:161>                                                       
        [string ":lua"]:1: in main chunk                                                                                                                                                                     
Error detected while processing function bufferline#update[4]..bufferline#render:                                                                                                                            
line    1:                                                                                                                                                                                                   
E5108: Error executing lua [string "luaeval()"]:1: loop or previous error loading module 'bufferline.render'                                                                                                 
stack traceback:                                                                                                                                                                                             
        [C]: in function 'require'                                                                                                                                                                           
        [string "luaeval()"]:1: in main chunk                                                                                                                                                                
E5108: Error executing lua [string "luaeval()"]:1: loop or previous error loading module 'bufferline.render'                                                                                                 
stack traceback:                                                                                                                                                                                             
        [C]: in function 'require'                                                                                                                                                                           
        [string "luaeval()"]:1: in main chunk  `

### LunarVim version

Master

### Neovim version (>= 0.5)

0.6.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
You need to disable Barbar first (it happens to be called `bufferline` here for legacy reasons 😅)
```lua
 lvim.builtin.bufferline.active = false
```
