### ISSUE TITLE
[Feature]: Lazygit as part of the install process

### ISSUE THREAD

**Issue by Vanderscycle** [LunarVim/LunarVim#2062]
### Feature motivation

During my last reinstall I kept getting errors on startup which I managed to trace down to lazygit not being installed.

### Describe the expected solution

Make lazygit part of the install or at least very clear that the user should install it or document how to remove it.

### Describe the alternatives you've considered

There's lots of different plugins like tpope/fugitive which are well documented in the website.

### Additional context

Thank you for your work on Nvim and lvim.

**Comment by kylo252** [comment]
This has already been fixed in #2051, or did you have something else in mind?

**Comment by Vanderscycle** [comment]
Oh amazing, thanks I didn't see that pr.
