### ISSUE TITLE
[Bug]: Updated to nvim 0.6.0 and the Lunarvim startup pages disappeared

### ISSUE THREAD

**Issue by w-r-z-k** [LunarVim/LunarVim#2063]
### Problem description

brew upgrade

lvim

### LunarVim version

Where do I find this?

### Neovim version (>= 0.5)

NVIM v0.6.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@BigSur

### Relevant log output

```shell
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.0/share/nvim"

Run :checkhealth for more info
```

### Screenshots

<img width="1221" alt="Screen Shot 2021-12-09 at 6 51 25 PM" src="https://user-images.githubusercontent.com/3805659/145493650-95372c2d-6e64-456a-95aa-2280812e6340.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by w-r-z-k** [comment]
The buffer names at the top are also missing.

**Comment by angryheng** [comment]
@w-r-z-k Try PackerCompile

**Comment by w-r-z-k** [comment]
I reinstalled everything.  But next time I'll try that. Thanks
