### ISSUE TITLE
[Feature]: Jsonnet LSP

### ISSUE THREAD

**Issue by zalegrala** [LunarVim/LunarVim#2075]
### Feature motivation

https://github.com/williamboman/nvim-lsp-installer/pull/240 has been merged, but I expected that would mean a `:PackerSync` and `:PackerCompile` would mean that I could `LSPInstall jsonnet`, but that doesnt' seem to be the case.  Is there an additional step that is needed to connect these dots?

**Comment by abzcoding** [comment]
if you are on the `rolling` branch, these are the available options
<img width="234" alt="Screen Shot 2021-12-14 at 11 13 39 AM" src="https://user-images.githubusercontent.com/10992695/145954406-7582660c-9c6d-4b4e-9c2c-7d532a173f47.png">

so you need to do `:LSPInstall jsonnet_ls`

**Comment by zalegrala** [comment]
I see.  I think I'm on a released version.  So is the lsp-installer plugin pinned to a commit that prevents `:PackerSync` from updating it?

**Comment by abzcoding** [comment]
> I see. I think I'm on a released version. So is the lsp-installer plugin pinned to a commit that prevents `:PackerSync` from updating it?

yes
