### ISSUE TITLE
[Feature]: Lua language docs include global `lvim` resolution

### ISSUE THREAD

**Issue by zalegrala** [LunarVim/LunarVim#2076]
### Feature motivation

When I open my config.lua, the LSP complains that the global `lvim` isn't defined.

### Describe the expected solution

The docs for the Lua language would show how to resolve this.

https://www.lunarvim.org/languages/lua.html

### Describe the alternatives you've considered

Crying every time I open my config.lua. :)

**Comment by abzcoding** [comment]
if you are using the sumneko_lua language server only, it should not warn you about it
if you are using luacheck for example, you need a file called `~/.config/lvim/.luacheckrc`
```lua
-- vim: ft=lua tw=80

stds.nvim = {
  globals = {
    "lvim",
    vim = { fields = { "g" } },
    "CONFIG_PATH",
    "CACHE_PATH",
    "DATA_PATH",
    "TERMINAL",
    "USER",
    "C",
    "Config",
    "WORKSPACE_PATH",
    "JAVA_LS_EXECUTABLE",
    "MUtils",
    os = { fields = { "capture" } },
  },
  read_globals = {
    "jit",
    "os",
    "vim",
    -- vim = { fields = { "cmd", "api", "fn", "o" } },
  },
}
std = "lua51+nvim"

-- Don't report unused self arguments of methods.
self = false

-- Rerun tests only if their modification time changed.
cache = true

ignore = {
  "631", -- max_line_length
  "212/_.*", -- unused argument, for vars with "_" prefix
}
```

**Comment by zalegrala** [comment]
This is what I've got currently, but I'd set that up a while ago.  So is there newer way to get sumneko?

![image](https://user-images.githubusercontent.com/88330524/146030484-64014612-ddbe-4865-bccd-0ec2920dcde0.png)

**Comment by abzcoding** [comment]
> This is what I've got currently, but I'd set that up a while ago. So is there newer way to get sumneko?
> 
> ![image](https://user-images.githubusercontent.com/88330524/146030484-64014612-ddbe-4865-bccd-0ec2920dcde0.png)

in the `rolling` branch it has been set up already so you just need to to a `:LspInstall sumneko_lua` and it should work out of the box
cc: @kylo252 ( am i missing sth ? )

**Comment by kylo252** [comment]
There's no need to specify a root_path for the server anymore, see: https://github.com/neovim/nvim-lspconfig/blob/dd15974986619b1f3143a9e666e36f41763ccdb4/lua/lspconfig/server_configurations/sumneko_lua.lua#L5

There's a problem with `luacheck` not being able to read the root-directory correctly, but the server should be fine.

**Comment by zalegrala** [comment]
Nice, it looks like I can remove all of the sumneko from my config and the LS still gets loaded and does the right thing.

**Comment by avently** [comment]
@abzcoding
>if you are using the sumneko_lua language server only, it should not warn you about it

I just installed sumneko_lua and found this issue afterwards because of tons of compains about missing lvim global. Was something broken since your comment? I have to disable lua in order to not see these warnings.

Is there a fix?
P.s. I use `master`.
