### ISSUE TITLE
[Bug]: Lunarvim doesn't launch properly

### ISSUE THREAD

**Issue by RickStanley** [LunarVim/LunarVim#2078]
### Problem description

Steps to reproduce:
1. Execute `bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)` in terminal;
2. Accept all dependencies;
3. Launch lunarvim with `.local/bin/lvim`;
4. See the basic nvim UI.

I had an alias for lvim in my .zshrc, I removed and tried the absolute path to check if there was conflict. Also, I did not install any other preconfigured settings for neovim. But it isn't by any means a clean install of a Lunarvim installation, I had other previous installations removed the uninstall script. I also reinstalled neovim.

I also tried to install the rolling branch, this is the output:
```bash
stanley in ~ λ LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)

      88\                                                   88\
      88 |                                                  \__|
      88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
      88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
      88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
      88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
      88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
      \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|

--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
Installing node modules with yarn..
yarn global v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "neovim@4.10.1" with binaries:
      - neovim-node-host
success Installed "tree-sitter-cli@0.20.1" with binaries:
      - tree-sitter
Done in 13.50s.
All NodeJS dependencies are successfully installed
--------------------------------------------------------------------------------
Would you like to install LunarVim's Python dependencies?
[y]es or [n]o (default: no) : y
Verifying that pip is available..
Installing with pip..
Requirement already satisfied: pynvim in ./.local/lib/python3.10/site-packages (0.4.3)
Requirement already satisfied: msgpack>=0.5.0 in /usr/lib/python3.10/site-packages (from pynvim) (1.0.2)
Requirement already satisfied: greenlet in ./.local/lib/python3.10/site-packages (from pynvim) (1.1.2)
All Python dependencies are successfully installed
--------------------------------------------------------------------------------
Would you like to install LunarVim's Rust dependencies?
[y]es or [n]o (default: no) : y
All Rust dependencies are successfully installed
--------------------------------------------------------------------------------
Backing up old /home/stanley/.cache/nvim to /home/stanley/.cache/nvim.bak

Number of files: 3 (reg: 2, dir: 1)
Number of created files: 2 (reg: 2)
Number of deleted files: 0
Number of regular files transferred: 2
Total file size: 0 bytes
Total transferred file size: 0 bytes
Literal data: 0 bytes
Matched data: 0 bytes
File list size: 0
File list generation time: 0.002 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 183
Total bytes received: 57

sent 183 bytes  received 57 bytes  480.00 bytes/sec
total size is 0  speedup is 0.00
--------------------------------------------------------------------------------
Backup operation complete
--------------------------------------------------------------------------------
Cloning LunarVim configuration
Klone nach '/home/stanley/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 174, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (162/162), done.
remote: Total 174 (delta 3), reused 81 (delta 1), pack-reused 0
Empfange Objekte: 100% (174/174), 1.65 MiB | 1.66 MiB/s, fertig.
Löse Unterschiede auf: 100% (3/3), fertig.
--------------------------------------------------------------------------------
Installing LunarVim shim
Preparing Packer setup
packer.compile: CompletePacker setup complete
--------------------------------------------------------------------------------
Thank you for installing LunarVim!!
You can start it by running: /home/stanley/.local/bin/lvim
Do not forget to use a font with glyphs (icons) support [https://github.com/ryanoasis/nerd-fonts]
```

## Expected behavior
See lunarvim's dashboard.

### LunarVim version

0.6.1

### Neovim version (>= 0.5)

0.6.0

### Relevant log output

```shell
stanley in ~ λ nvim -v                                    
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Übersetzt von builduser

Features: +acl +iconv +tui
See ":help feature-compile"

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Screenshots

Launching normal nvim:
![grafik](https://user-images.githubusercontent.com/23178554/145940027-617bbae9-b0c1-4a74-ad51-7ec90f4acb14.png)

Launching lvim:
![grafik](https://user-images.githubusercontent.com/23178554/145938391-70a237a4-c59c-40a8-a6b2-a7085217f343.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
I've updated the tag with https://github.com/LunarVim/LunarVim/pull/2079. There was an issue with `nvim-tree` which might've been causing `PackerCompiler` to not complete correctly. 

Please give it another try now.

**Comment by RickStanley** [comment]
Still doesn't work. :(

Should I remove a folder in particular?

I ran uninstall script and some `rm -rf`s.

**Comment by kylo252** [comment]
Please try running `'PackerSync` and show me the output.

**Comment by RickStanley** [comment]
Running :PackerSync

```bash
[nvim-treesitter] [0/22] Extracting...
nvim-treesitter[css]: Could not create tree-sitter-css-tmp
mkdir: das Verzeichnis „tree-sitter-css-tmp“ kann nicht angelegt werden: Die Datei existiert bereits
Betätigen Sie die EINGABETASTE oder geben Sie einen Befehl ein
```

It's saying that the data/folder already exists. I'll try deleting that.

**Comment by RickStanley** [comment]
Actually I didn't have to do anything. I just reopened lvim and it worked.

But now I'm in version `dev-6cf21e9`. Why is that? I installed the stable version.

Anyway, thank you. Closing this.

**Comment by kylo252** [comment]
> But now I'm in version dev-6cf21e9. Why is that? I installed the stable version.

This is a side effect of me not knowing how to set the tag correctly 😢

**Comment by PyDataBlog** [comment]
I just had the exact experience. I was losing my mind and deleted everything again. I'll try again tomorrow. Should I go with the same instructions on the stable branch or rolling release one?

**Comment by PyDataBlog** [comment]
I can confirm that this bug still persists with nvim 0.6.1 and latest lunarvim. I had to run `:PackerSync` and got the error that the folder already exists. Then opened a new lvim instance to get the right one loading properly. I can make a new issue if you want.

**Comment by kylo252** [comment]
> I can confirm that this bug still persists with nvim 0.6.1 and latest lunarvim. I had to run `:PackerSync` and got the error that the folder already exists. Then opened a new lvim instance to get the right one loading properly. I can make a new issue if you want.

Please do, along with the error message you got.

**Comment by istvan-b01** [comment]
This is what I get after installing lunarvim and having all the prerequisites installed (nvim version is 0.8.2 with snap):


panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x555dde852d95]

goroutine 1 [running]:
main.main.func1()
	/build/snapd/parts/snapd-deb/build/cmd/snap/main.go:492 +0x95
panic(0x555ddeef7840, 0x555ddf571900)
	/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b6
main.run(0xc000423db8, 0xe)
	/build/snapd/parts/snapd-deb/build/cmd/snap/main.go:559 +0x375
main.main()
	/build/snapd/parts/snapd-deb/build/cmd/snap/main.go:497 +0x371
