### ISSUE TITLE
[Bug]: Mildly misleading error on setup

### ISSUE THREAD

**Issue by unredundant** [LunarVim/LunarVim#2084]
### Problem description

First of all, just need to say... what an unbelievably good Github issue template.  I didn't even know it was possible to build out forms like this 🤯 Anyway, on to the issue. 

I'm setting up a shiny new laptop and wanted to get LunarVim installed (of course 💙). I had Node installed via Volta, and got an error (posted in log output box)

Hmm... I definitely have node installed, so I peaked at the logs and see the output (pasted in log output box) 

However, the problem here is that I don't have yarn installed, not that I don't have Node installed.  

That's all, not a very pernicious issue, but I think it may be confusing to newcomers :) 

### LunarVim version

latest

### Neovim version (>= 0.5)

latest

### Relevant log output

Initial error in terminal
```shell
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
Installing node modules with yarn..
   note: Volta is processing each package separately
Volta error: Node is not available.

To run any Node command, first set a default version using `volta install node`
Error details written to /Users/lappy/.volta/log/volta-error-2021-12-14_22_50_00.722.log
```

Output of logs 

```
   1   │ "yarn" "global" "add" "neovim"
   2   │ Volta v1.0.5
   3   │ 
   4   │ Node is not available.
   5   │ 
   6   │ To run any Node command, first set a default version using `volta insta
       │ ll node`
   7   │ 
   8   │ Error cause: No such file or directory (os error 2)
```
```


### Screenshots

_No response_

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
ummm this error is coming directly from Volta, and it's even telling you what to do 😅 

```console
To run any Node command, first set a default version using `volta install node`
Error details written to /Users/lappy/.volta/log/volta-error-2021-12-14_22_50_00.722.log
```

The errors from the installer would have this prefix `[ERROR]`
https://github.com/LunarVim/LunarVim/blob/bccbcff3ab081ffdeb7c615cc42bfd84ae680dcb/utils/installer/install.sh#L161-L171

**Comment by unredundant** [comment]
if it's a volta error it's fine, i can open w/ them (though i don't think it is).  However, it's totally not telling me what to do, clearly you didn't read the issue.  The problem is that **yarn** is not installed, not node.  I confirmed this by installing yarn separately and then it worked exactly as expected.  Thanks for the response tho :) 

I don't think this is closed, but will defer to the project maintainers on whether this should stay open

**Comment by kylo252** [comment]
> if it's a volta error it's fine, i can open w/ them (though i don't think it is). However, it's totally not telling me what to do, clearly you didn't read the issue. 

All of this output is from `volta` directly.  It's saying that you need to perform `volta install node`

```console
Installing node modules with yarn..
   note: Volta is processing each package separately
Volta error: Node is not available.

To run any Node command, first set a default version using `volta install node`
Error details written to /Users/lappy/.volta/log/volta-error-2021-12-14_22_50_00.722.log
```

If I have to guess, you either didn't have `node` installed after installing `volta`, or maybe you didn't `VOLTA_HOME` to your path.

> The problem is that **yarn** is not installed, not node. I confirmed this by installing yarn separately and then it worked exactly as expected.

It may have been that you needed a new login shell to refresh the environment. It might also be related to https://github.com/volta-cli/volta/issues/764

**Comment by abzcoding** [comment]
basically, we are calling

```shell
yarn global add neovim
yarn global add tree-sitter-cli
```
and volta is showing you 
<img width="640" alt="Screen Shot 2021-12-15 at 9 03 41 PM" src="https://user-images.githubusercontent.com/10992695/146236303-444ca35f-320d-4721-bbd4-401f89ce2239.png">

which is indeed misleading, but here is what we are doing
if the output is not zero, print the output from your own os,
so not sure what more can be done 🤔 
though, I'd be happy to hear any suggestions to make it more clear

**Comment by unredundant** [comment]
maybe nothing more can be done... just wanted to bring it up :) feel free to close if it's not actionable!

**Comment by mandaputtra** [comment]
I also encounter this issue, I solve it by upgrading to the latest volta, so uninstall volta and then install it again

**Comment by kylo252** [comment]
This was hopefully improved in #2113. Let me know if you're still having problems with it otherwise.
