### ISSUE TITLE
snippet expand is not expected behavior

### ISSUE THREAD

**Issue by ZestyXin** [LunarVim/LunarVim#2086]
### Problem description

when expand a snippet and the snippet is jumpable, it will have a strange behavior in expanding another snippet. 

### LunarVim version

i dont know how look this

### Neovim version (>= 0.5)

NVIM v0.5.1

### Screenshots

![Peek 2021-12-15 21-47](https://user-images.githubusercontent.com/47104456/146202176-533d97c8-7755-4611-9c30-57416158b6aa.gif)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
Sadly I can't reproduce it, @chase. Do you have any idea what might be causing this?

**Comment by chase** [comment]
> Sadly I can't reproduce it, @chase. Do you have any idea what might be causing this?

I'm guessing @ZestyXin is running an old version of LunarVim or the most recent plugin bump introduced a bug, let check the recent commits and issues

**Comment by chase** [comment]
This seems _very_ similar to: https://github.com/LunarVim/LunarVim/issues/2006

I think he may just need to upgrade, because I cannot reproduce this issue

**Comment by ZestyXin** [comment]
@chase  thank you fof your suggestion

update lvim is useless, but i reinstall lvim by runing `install.sh`. now it is work
