### ISSUE TITLE
[Bug]: Scala Worksheet.sc isn't working

### ISSUE THREAD

**Issue by w-r-z-k** [LunarVim/LunarVim#2087]
### Problem description

It seems that the worksheet isn't working. I don't think the settings for nvim-metals recognizes *.worksheet.sc as a workspace.

If I install nvim from scratch and setup nvim-metals, it works. But what I have done is install the lunarvim IDE layer on nvim and then activated nvim-metals via that mechanism. So I suspect that there's some setting in lunarvim that is overriding the setting in nvim-metals. If I knew what that setting was perhaps I could make it work.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [ ] The programs specified by the config are installed

### LunarVim version

Where do find this?

### Neovim version (>= 0.5)

0.6

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
can you try following this https://www.lunarvim.org/languages/scala.html#configure-lunarvim
let me know if it didn't help

**Comment by abzcoding** [comment]
closed due to inactivity
