### ISSUE TITLE
[Bug]: Error executing vim.schedule lua callback null-ls

### ISSUE THREAD

**Issue by qvieth** [LunarVim/LunarVim#2092]
### Problem description

enter insert mode, insert text and return to normal mode threw this

### LunarVim version

dev-ccb5a6f

### Neovim version (>= 0.5)

0.5.1

### Screenshots

![image](https://user-images.githubusercontent.com/71810726/146476707-5044afe5-1966-45f8-b60c-3b3da833e459.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
you might wanna update your neovim a bit, that lines is 
```lua
vim.diagnostic.set(namespace, bufnr, diagnostics)
```
which was added a while back ( instead of `vim.lsp.diagnostic` we now have `vim.diagnostic` )
cc: @kylo252

**Comment by kylo252** [comment]
You can't really `vim.diagnostic` unless you upgrade to Neovim v0.6.0. However, you shouldn't be getting this error unless you specifically call it, unless null-ls has dropped support for 0.5.1 as well.

**Comment by abzcoding** [comment]
this should be fixed in master and rolling
