### ISSUE TITLE
[Bug]: lvim.lsp.popup_border ignored by handlers

### ISSUE THREAD

**Issue by meijieru** [LunarVim/LunarVim#2095]
### Problem description

change `lvim.lsp.popup_border` doesn't has any effect.
I have checked `vim.lsp.with`, when called, the border is "none".

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

rolling

### Neovim version (>= 0.5)

NVIM v0.7.0-dev+746-g95803f0e90

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
You should be modifying the `float` options instead if you're on v0.6.0+

**Comment by xeluxee** [comment]
Same issue, even using `float` option I can't get the border back

**Comment by kylo252** [comment]
I thought these options were globally inherited by handlers as well, but apparently not. I'll fix this separately from #2093
