### ISSUE TITLE
[Bug]: Current Lua LSP download link is 404

### ISSUE THREAD

**Issue by rizkyzhang** [LunarVim/LunarVim#2096]
### Problem description

1. :LspInstall lua
2. Select sumneko_lua
3. Error 404 https://github.com/sumneko/vscode-lua/releases/download/v2.5.5/lua-2.5.5.vsix

The correct link is this: https://github.com/sumneko/vscode-lua/releases/download/v2.5.5/vscode-lua-v2.5.5-linux-x64.vsix. The problem is that I don't have any idea how to change default download link yet as I am still pretty new to vim, I have already trying to find resources on google but to no avail. Any advice would be very helpful :)

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [ ] The programs specified by the config are installed

### LunarVim version

Rolling

### Neovim version (>= 0.5)

0.6.0

### Screenshots

![lua-error](https://user-images.githubusercontent.com/41568558/146669757-9d257644-aa5e-4333-8712-4fc4d25c58b3.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
that link comes from this plugin -> https://github.com/williamboman/nvim-lsp-installer
maybe we need to raise the issue there

**Comment by rizkyzhang** [comment]
> that link comes from this plugin -> https://github.com/williamboman/nvim-lsp-installer maybe we need to raise the issue there

Thank you for the suggestion :)

**Comment by kylo252** [comment]
We need to bump the version of the installer plugin to fix this.
