### ISSUE TITLE
[Feature]: java debugger

### ISSUE THREAD

**Issue by cladera** [LunarVim/LunarVim#2097]
### Feature motivation

I believe Java development cannot be considered fully supported if it is not possible to run applications and tests and debug the code without using external applications. 

### Describe the expected solution

I would expect being able to configure java debugging, for example with [java-debug](https://github.com/microsoft/java-debug) and [vscode-java-test](https://github.com/microsoft/vscode-java-test).

### Describe the alternatives you've considered

I've considered disabling null-ls and configure manually [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls). I used @ChristianChiarulli 's [config repo](https://github.com/ChristianChiarulli/lvim) as a reference.

I kind of succeeded but I ended up loosing other important features such as "Go to definition", "Organize Imports", "Generate constructors", etc.

**Comment by cladera** [comment]
I'm going to rephrase my proposal as question: 

How can I configure jdtls' init_options to include java-debug and vscode-java-test artifacts in the init_options bundles? Then, how can I configure DAP to use them?

**Comment by cladera** [comment]
This is my current lvim configuration that supports java debugging and running tests with vscode-java-test https://github.com/cladera/lvim.

But as I mentioned, I've lost some Code Actions such as Organize Imports (there is a workaround for this one), Generate constructors among others.

**Comment by phenrique** [comment]
I'm very interested in debugging java with lvim..
I will certainly try your settings

**Comment by cladera** [comment]
@phenrique sure! let me know if you any help.

**Comment by abzcoding** [comment]
check my [configuration](https://github.com/abzcoding/lvim/blob/main/ftplugin/java.lua) for full integration with java including debugging using [java-debug](https://github.com/microsoft/java-debug)

**Comment by hawkinchina** [comment]
@abzcoding  use your configuration , it's ok. 

but the configuration of the 
[starter.lvim](https://github.com/LunarVim/starter.lvim)
cannot debug. it had better have the same config for starter.lvim.

otherwise, lots of people will meet this question.
