### ISSUE TITLE
[Feature]: Rename lvim.builtin.bufferline config to lvim.builtin.barbar

### ISSUE THREAD

**Issue by LandonSchropp** [LunarVim/LunarVim#2100]
### Problem description

I was a bit surprised to learn that LunarVim is using barber instead of bufferline. With the rest of the builtin configuration options, the config value is named after the plugin. However, since barbar is configured using `lvim.builtin.bufferline`, this led me to look at [bufferline.nvim](https://github.com/akinsho/bufferline.nvim)'s config instead.

### LunarVim version

Latest

### Neovim version (>= 0.5)

v0.6.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by LandonSchropp** [comment]
Sorry, I didn't mean to open this as a bug. It should be a feature request.

**Comment by sangdth** [comment]
I think it's the `barbar` who decided to take the `vim.g.bufferline` from beginning (so weird), thus lunar team just following that. But agree that it made very sense to change that namespace as I was confused before I found out this issue.

Thanks.
