### ISSUE TITLE
[Feature]: Automatically display dashboard when all buffers closed

### ISSUE THREAD

**Issue by LandonSchropp** [LunarVim/LunarVim#2101]
### Feature motivation

When all of the buffers are closed, LunarVim currently displays an empty buffer. This can be a tiny bit annoying, especially if you close all of your current buffers and then one a new one, because the empty buffer will stay in your buffer line.

### Describe the expected solution

Instead of opening a new empty buffer, it'd be awesome if LunarVim could reopen the dashboard.

**Comment by kobzar** [comment]
This is good idea. Any updates?

**Comment by Uzaaft** [comment]
@kylo252  @abzcoding  I got something locally for another similar scenario. If this is something you guys are open for merging this feature, I'll give it a try.

**Comment by abzcoding** [comment]
> @kylo252 @abzcoding I got something locally for another similar scenario. If this is something you guys are open for merging this feature, I'll give it a try.

that would be appreciated, tyvm

**Comment by Uzaaft** [comment]
Sorry about the radio silence.
I abandoned the efforts due to lack of time.
