### ISSUE TITLE
[Bug]:E5108: Error executing lua ...line.nvim/lua/lualine/components/diagnostics/sources.lua:15: 

### ISSUE THREAD

**Issue by ZeroPie** [LunarVim/LunarVim#2102]
### Problem description

lvim 
open any file

### LunarVim version

Latest

### Neovim version (>= 0.5)

0.5

### Relevant log output
```
attempt t Error executing vim.schedule lua callback: ...Cellar/neovim/0.5.1_1/share/nvim/runtime/lua/vim/uri.l ua:116: attempt to index local 'uri' (a nil value)
```

### Screenshots

When i open lvim my screen only shows an nvim window when i try to update lvim using :
![Screenshot 2021-12-20 at 19 17 05](https://user-images.githubusercontent.com/8741666/146854302-0a0408aa-1ae0-4f4e-94ff-f07b2f45eab2.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kavinvin** [comment]
@ZeroPie updating neovim to 0.6.0 solves this for me
