### ISSUE TITLE
[Bug]: Nvimtree shows tree for wrong directory when focused

### ISSUE THREAD

**Issue by alfa07** [LunarVim/LunarVim#2106]
### Problem description

Steps to reproduce:
1. Open file AF in repo A
2. Show nvimtree with `<space>e`
3. Open file BF in repo B
4. Observe that nvimtree shows file BF and rooted at repo B
5. Hit `<C-h>` to get into nvimtree panel
6. BUG: nvimtree changes root to repo A
7. Expected behavior nvimtree should stay at repo B

What is happening is that (most likely) this event gets fired when cursor moves to nvimtree buffer:
https://github.com/kyazdani42/nvim-tree.lua/blob/65b8b19c8bcea36e37474338c7e2d2fea95553d3/lua/nvim-tree.lua#L399
which for whatever reason has `vim.loop.cwd()` set to directory which does not match root which is currently displayed.

The workaround is to add this to config.vim:
```lua
local nvimtree_lib = require "nvim-tree.lib"
local change_dir = nvimtree_lib.change_dir
local is_file = require "project_nvim.project".is_file
nvimtree_lib.change_dir = function(d)
  if not is_file() then
    return
  end
  change_dir(d)
end
```

### LunarVim version

dev-7244220, tag: 1.0.0-rc

### Neovim version (>= 0.5)

NVIM v0.6.0

### Relevant log output

```shell
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by linuxbrew@47b333addab8

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/0.6.0/share/nvim"

Run :checkhealth for more info
```

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by alfa07** [comment]
Here is recording: [![asciicast](https://asciinema.org/a/PidAU52biD8LLmtqOMLRgB592.svg)](https://asciinema.org/a/PidAU52biD8LLmtqOMLRgB592)

**Comment by abzcoding** [comment]
this has been fixed in the latest rolling branch, just need to update lunarvim and packagers `LvimUpdate`
