### ISSUE TITLE
[Bug]: Mac lvim not working as expected

### ISSUE THREAD

**Issue by ceelias** [LunarVim/LunarVim#2108]
### Problem description

1. Install lvim stable using script `bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`
2. Install all dependencies
3. run `lvim`

Expected: Expected LunarVim to show up with the lunarvim banner an info as expected. I can tell that it is running something different than pure `nvim` but it is not showing things correctly. If you look at the provided screenshot, you will see `lvim` above and `nvim` below.

Running on Monterey

### LunarVim version

Stable

### Neovim version (>= 0.5)

v0.6.0

### Relevant log output

```shell
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.0/share/nvim"

Run :checkhealth for more info

:checkhealth

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /Users/celias/.config/nvim/init.vim
    - ADVICE:
      - :help init.vim

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help provider-python
          /usr/bin/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help provider-python
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.9.9
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help g:ruby_host_prog for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v14.17.0
  - INFO: Nvim node.js host: /Users/celias/.config/yarn/global//node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /Users/celias/.cache/nvim/lsp.log
  - INFO: Log size: 0 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
```

### Screenshots

Above is `lvim` and below is `nvim`
<img width="1610" alt="Screen Shot 2021-12-21 at 5 39 47 PM" src="https://user-images.githubusercontent.com/11580747/147008165-94c41a9c-08d3-4210-b59d-329d42c54b97.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by asuyou** [comment]
Having the same issue on an arch based machine.
Running `:PackerUpdate`, then `:PackerSync` seems to have fixed some stuff

**Comment by cserb** [comment]
Same here, but `:PackerUpdate` + `:PackerSync` ist not solving the issue

Also I should mention that due to using fish shell I first downloaded `install.sh` and than executed it. But this seems to have worked fine

**Comment by novito** [comment]
I'm on the same boat as @cserb , also using fish and seeing the same thing that you folks are mentioning.

**Comment by kylo252** [comment]
Please run `:PackerSync` and see if that fixes it.

Make sure to check this section regarding using `fish` as the default shell in neovim https://www.lunarvim.org/troubleshooting/#are-you-using-fish

**Comment by cserb** [comment]
> Please run `:PackerSync` and see if that fixes it.

As mentioned, this did not help.

> Make sure to check this section regarding using `fish` as the default shell in neovim https://www.lunarvim.org/troubleshooting/#are-you-using-fish

actually I managed to make it work by clearing the cache `lvim +LvimCacheReset` https://www.lunarvim.org/troubleshooting/#getting-a-lot-of-errors-when-opening-lvim-after-an-update

**Comment by Curricane** [comment]
i want to reinstall lvim and run the same command, howerver i got another problem 
![image](https://user-images.githubusercontent.com/36157286/147634761-a06fbca8-98ae-4ae4-9d19-fb2e89a1c035.png)

then i use lvim, it did not open dashbord. i try to run PackerSync and reopen lvim, dashboard is ok, but still had some problem
![image](https://user-images.githubusercontent.com/36157286/147634976-90c2a88a-bdb8-412e-9bca-06a3617645ee.png)
![image](https://user-images.githubusercontent.com/36157286/147634985-6fba5b53-e478-4a7e-bc92-4a3d12b4d165.png)

**Comment by abzcoding** [comment]
> i want to reinstall lvim and run the same command, howerver i got another problem 

It seems like you have an older version of neovim; please install the neovim 0.6 release

**Comment by Curricane** [comment]
i tred to use nvim 0.6 and nvim 0.7,but not work

**Comment by Curricane** [comment]
> > i want to reinstall lvim and run the same command, howerver i got another problem
> 
> It seems like you have an older version of neovim; please install the neovim 0.6 release

i tred to use nvim 0.6 and nvim 0.7,but not work

**Comment by kylo252** [comment]
> i tred to use nvim 0.6 and nvim 0.7,but not work

Please run the uninstaller first

```console
bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh
```

you can download it manually if it's missing https://github.com/LunarVim/LunarVim/blob/rolling/utils/installer/uninstall.sh

**Comment by abzcoding** [comment]
this should be fixed
