### ISSUE TITLE
[Bug]: Auto Command Lua Mismatched Opts

### ISSUE THREAD

**Issue by superfive666** [LunarVim/LunarVim#2110]
### Problem description

autocmds.lua
Error detected while processing /home/ubuntu/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: ...local/share/lunarvim/lvim/lua/lvim/core/autocmds.lua:81: bad argument #2 to 'format' (string expected, got nil)
stack traceback:
	[C]: in function 'format'
	...local/share/lunarvim/lvim/lua/lvim/core/autocmds.lua:81: in function 'enable_format_on_save'
	...local/share/lunarvim/lvim/lua/lvim/core/autocmds.lua:100: in function 'configure_format_on_save'
	...ntu/.local/share/lunarvim/lvim/lua/lvim/lsp/init.lua:174: in function 'setup'
	/home/ubuntu/.local/share/lunarvim/lvim/init.lua:21: in main chunk

The "opts" object has attribute "timeout" but not attribute "timeout_ms".

### LunarVim version

master

### Neovim version (>= 0.5)

v0.7.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by superfive666** [comment]
![image](https://user-images.githubusercontent.com/7760702/147175963-35ff0a34-18c0-4cfc-a36a-57328799c848.png)

**Comment by abzcoding** [comment]
fixed via https://github.com/LunarVim/LunarVim/commit/655fd1b0ca5405ce67f3f8083ef6a4f7d2dedea0
