### ISSUE TITLE
[Bug]: Unable to install without administrative privilages. Please set you NPM_HOME correctly and try again.

### ISSUE THREAD

**Issue by uneconomicalfairy14** [LunarVim/LunarVim#2112]
### Problem description

steps to reproduce
1. use the one-click script to install
2. use nvm to install node dependencies

the following problem arises

Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
[ERROR] Unable to install without administrative privilages. Please set you NPM_HOME correctly and try again.

### LunarVim version

latest stable release

### Neovim version (>= 0.5)

0.6.01

### Relevant log output

```shell
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Screenshots

![Screenshot (12)](https://user-images.githubusercontent.com/87299490/147354746-cf2dde27-29b8-4109-8494-a2a289b1b1f5.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by diego-rapoport** [comment]
I'm having the exact same problem.

**Comment by kylo252** [comment]
Please share the output of
```shell
npm config get prefix
```

Otherwise, is working as intended, you need to configure `npm` correctly to install to a user-owned folder. You can also skip that step and handle installing the nodejs deps manually.

**Comment by fbaltor** [comment]
Can you check the draft PR? I guess it solves this issue.

**Comment by fbaltor** [comment]
![PREFIX](https://user-images.githubusercontent.com/9384697/147372202-52ecb637-7f99-4a8a-abcc-350489dd7f8b.png)

**Comment by uneconomicalfairy14** [comment]
![image](https://user-images.githubusercontent.com/87299490/147376542-d5cebce9-ca04-4c04-a9c6-c4ea33bccce0.png)

output of npm config get prefix

**Comment by uneconomicalfairy14** [comment]
as u can see the node package manager is installed in home dir so it doesnt need root access

so the error doesnt make sense

**Comment by kylo252** [comment]
was `nvm` activated when you ran the installer? The detection logic is pretty simple:

```console
$ [ -w "/home/hatsu/.local/share/npm" ] && echo "writable" || echo "not writable"
writable
$ [ -w "/home/hatsu/.local/share/blahblah" ] && echo "writable" || echo "not writable"
not writable
```

here's the function if you want to test it:

```shell
#!/usr/bin/env bash
set -eoux pipefail

function __validate_node_installation() {
  local pkg_manager="$1"
  local manager_home
  manager_home="$($pkg_manager config get prefix 2>/dev/null)"

  if [ ! -d "$manager_home" ] || [ ! -w "$manager_home" ]; then
    echo "[ERROR] Unable to install without administrative privileges. Please set your NPM_HOME correctly and try again."
    exit 1
  else
    echo "[SUCCESS] using prefix $manager_home"
  fi

}

__validate_node_installation "npm"
# __validate_node_installation "yarn"
```

**Comment by binjiaqm** [comment]
I solved the issue with the instructions here. https://stackoverflow.com/questions/10081293/install-npm-into-home-directory-with-distribution-nodejs-package-ubuntu

**Comment by lavantien** [comment]
I've solved the issue, I was baffling why my npm is configure correctly and still not work, but it turns out that it's about yarn not setting the config, the install script need both npm and yarn to be properly config with the `... config get prefix`

I followed the instructions here https://stackoverflow.com/a/53879534/4578386
