### ISSUE TITLE
[Bug]: sumneko_lua override issues

### ISSUE THREAD

**Issue by ssbanerje** [LunarVim/LunarVim#2115]
## Steps to reproduce
1. Add the following into `config.lua`:
```lua
lvim.lsp.automatic_servers_installation = true
vim.list_extend(lvim.lsp.override, {
  "sumneko_lua",
})
```
2. Add the following into `ftplugin/lua.lua`:
```lua
require("lvim.lsp.manager").setup("sumneko_lua", {
  settings = {
    Lua = {
      diagnostics = {
        globals = { "vim", "lvim", "hs" },
      },
      workspace = {
        library = {
          [require("lvim.utils").join_paths(get_runtime_dir(), "lvim", "lua")] = true,
          [vim.fn.expand("$VIMRUNTIME/lua")] = true,
          [vim.fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true,
          ["/Applications/Hammerspoon.app/Contents/Resources/extensions/hs"] = (vim.fn.has("macunix") == 1),
        },
        maxPreload = 100000,
        preloadFileSize = 10000,
      },
      telemetry = { enable = false },
    },
  },
})
```

## Expected Behavior
The lua LSP is installed and then loaded with the user settings.

## Actual Behavior
1. The setup call is not made.
2. Even with a manual install with `:LspInstall`, `sumneko_lua` is not loadable in lvim (i.e., a command mode call `:lua require("lvim.lsp.manager").setup("sumneko_lua",...` also returns early) .

## Traced Problem
AFAIK, I could trace the problem to here:
https://github.com/LunarVim/LunarVim/blob/a79de08d40f08e9a3b753175df11283ed737067c/lua/lvim/lsp/manager.lua#L69-L72:

The `client_is_configured()` returns true, because of the following autocmds:
```
--- Autocommands ---
FileType
    lua       unsilent lua require'lspconfig'["sumneko_lua"].manager.try_add()
              setlocal indentexpr=nvim_treesitter#indent()
```
And as a result, the setup call cannot go through.

I am unsure where this is getting added from? The only trace I could find was the call to `buf_try_add()` in the same `setup()` function. But the code returned before that, so I could not quite understand where this autocmd is being added from.

This problem also seems to happen only for the sumneko_lua server. Other overrides (e.g., dockerls) seems to work as expected.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

rolling @ a79de08

### Neovim version (>= 0.5)

0.6.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
this is how I am overriding it https://github.com/abzcoding/lvim/blob/main/ftplugin/lua.lua

especially this part:
```lua
local servers = require "nvim-lsp-installer.servers"
local server_available, requested_server = servers.get_server "sumneko_lua"

if server_available then
  requested_server:setup(luadev)
end
```

**Comment by kylo252** [comment]
`LspInstall` doesn't have any direct effect on this, see https://www.lunarvim.org/languages/#server-override

> Notice
Overriding a server will completely bypass the lsp-installer, so you would have to manage the installation for any of those servers manually.

Try setting the full command yourself, or use the same snippet that was suggested if you want to utilize the installer.

**Comment by ssbanerje** [comment]
@kylo252 I am following the steps in the link like you suggested (see code snippets in original post). But for `sumneko_lua`, the call to `setup()` does not execute the entire function but exits early because `client_is_configured()` returns true.

This is unexpected (the bug) because the LSP has been overridden and the first call to the `setup` function is exiting early.

**Comment by kylo252** [comment]
@ssbanerje, the check you're seeing in `client_is_configured()` is necessary to avoid configuring the server more than once, see https://github.com/LunarVim/LunarVim/pull/2048 for more context.

Whenever a setup function is called, it will then eventually call `require'lspconfig'["sumneko_lua"].setup(opts)` which in turn will add this autocmd that you're seeing

```lua
lua require'lspconfig'["sumneko_lua"].manager.try_add()
```

 `client_is_configured()`  would _only_ return `true`  if any `myserver.setup()` has been called before, which can be triggered in three different ways:
1. using `lvim.lsp.manager.setup(myserver, opts)`
2. using _some_ setup function from `lsp-installer`, probably `on_server_ready()` or `myserver:on_ready()`
3. using `lspconfig.myserver.setup(opts)` directly.

So I'm suspecting that you have another file calling the `setup()` function somewhere, try `<leader>Lg` --> search for `sumneko` to double-check the template files. 

Also, please try overriding something else as well, just to make sure it's not something specific to `settings`

```lua
local on_attach_callback = function(client, bufnr)
  if client.name:match "sumneko" then
    print("got client_id: " .. client.id)
  end
end
require("lvim.lsp.manager").setup("sumneko_lua", { on_attach = on_attach_callback })
```

For reference, this is how I override the server: https://github.com/kylo252/lvim/blob/3177761276ca15d3879ab4dd1cf219f325ba100a/after/ftplugin/lua.lua

**Comment by abzcoding** [comment]
the overriding method has changed completely
here is the example in my [config.lua](https://github.com/abzcoding/lvim/blob/1a576b710243a57860a36a25436f77a13fb350c8/config.lua#L89) for [sumneko_lua](https://github.com/abzcoding/lvim/blob/main/ftplugin/lua.lua)
