### ISSUE TITLE
[Feature]: Integrate solc 0.8.11's LSP server

### ISSUE THREAD

**Issue by OliverNChalk** [LunarVim/LunarVim#2117]
### Brief

There have been a few [prior attempts](https://github.com/LunarVim/LunarVim/issues/454) at getting a strong solidity user experience in `vim`/`neovim`, however, to my knowledge none have truly succeeded. This was largely due to no robust LSP implementation being available. Solidity's [`0.8.11`](https://github.com/ethereum/solidity/releases/tag/v0.8.11) releases includes support for running `solc` in `--lsp` mode.

### Benefits over status quo

Integration with `solc`, over alternatives like Solang, this would let us benefit form continued improvements on the [canonical Solidity repo](https://github.com/ethereum/solidity/).

**Comment by abzcoding** [comment]
we are using [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer) as our language server installer, I would suggest adding the support there ( or rather asking for it), so everyone can enjoy the support

**Comment by OliverNChalk** [comment]
[Opened the issue in nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer/issues/368)

**Comment by kylo252** [comment]
Would you say this is better than the other server? we have to enable only one of them by default, see [`1947ba0` (#2125)](https://github.com/LunarVim/LunarVim/pull/2125/commits/1947ba0db266656ed72e0876d1ab7109c26276cd)

**Comment by OliverNChalk** [comment]
That's a good question, my proposal for `solc` over `solang` is driven by the fact that `solc` is the canonical `solidity` server and the one that target Ethereum's EVM. To my knowledge, `solang` targets WASM and other blockchains. With this in mind in stands to reason that `solc` would be the stronger language server in the long run.

For present day capabilities, I have not been able to check the feature coverage on either of these language servers. Are any maintainers familiar with `solang` and what features it claims to cover? My understanding is the LSP support was quite limited with `solang`?

**Comment by kylo252** [comment]
Thanks! Added in #2125
