### ISSUE TITLE
Scala Metals not initialize with custom config table

### ISSUE THREAD

**Issue by tzaavi** [LunarVim/LunarVim#2121]
### Problem description

I'm trying the setup scala metals according to docs https://www.lunarvim.org/languages/scala.html#install-language-server

in the config function we setup the custom metals config object and call `initialize_or_attach`.
but the in the auto command section we call `initialize_or_attach` with empty config.
the problem is that when we open a scala buffer the auto command call attach with empty config and not our custom config and because of that the `on_attach` method is not getting called and all the binding is never happen. so at the end metals works with default config and we don't have out custom bindings.

I'm not sure how to pass the custom config object to metals in the auto command. 

### LunarVim version

0.6.1

### Neovim version (>= 0.6)

0.6.0

### Operating system/version

endevouros (arch)

### Affected language servers

scala metals

### Actual behavior

Metals is working with default config

### Expected behavior

Metals should work with custom config

### log and support info

```shell
-
```

**Comment by abzcoding** [comment]
create a file called `~/.config/lvim/user/metals.lua`
```lua
local M = {}

M.config = function()
  local metals_config = require("metals").bare_config()
  metals_config.on_attach = require("lvim.lsp").common_on_attach
  metals_config.settings = {
    showImplicitArguments = false,
    showInferredType = true,
    excludedPackages = {},
  }
  metals_config.init_options.statusBarProvider = false
  require("metals").initialize_or_attach { metals_config }
end

return M
```

and then use this 
```lua
lvim.autocommands.custom_groups = {
    { "FileType", "scala,sbt", "lua require('user.metals').config()" },
}
```

**Comment by tzaavi** [comment]
Thanks for the quick response.
I try to implement this solution. if I open lvim from `~/.config/lvim` dir it works find but if I open lvim from any other location I'm getting error: module `user.metals` not found.

Not sure what I'm doing wrong.
Thanks

**Comment by abzcoding** [comment]
@kylo252 any ideas?

**Comment by abzcoding** [comment]
@tzaavi there was a typo in comment, the file should be `~/.config/lvim/lua/user/metals.lua`

**Comment by tzaavi** [comment]
After got over nvim-metals repo and review how @ckipp01 (one of the creator of nvim-metals) is configure metals.
I figure that we need to `Metals_config` so we can use the same config object in the autocmd command.
once  I did that everything is working.

you can see an example here: https://github.com/ckipp01/dots/blob/master/nvim/.config/nvim/lua/mesopotamia/lsp.lua#L25

**Comment by abzcoding** [comment]
> After got over nvim-metals repo and review how @ckipp01 (one of the creator of nvim-metals) is configure metals. I figure that we need to make `Metals_config` object global so we can use the same config object in the autocmd command. once I did that everything is working.
> 
> you can see an example here: https://github.com/ckipp01/dots/blob/master/nvim/.config/nvim/lua/mesopotamia/lsp.lua#L25

glad that is working for you, i would appreciate it if you could do a PR to our [docs repo](https://github.com/LunarVim/lunarvim.org/) and let other users know the correct way to configure it

**Comment by tzaavi** [comment]
Sorry for the late response. I'm not using Lunar anymore so I hope this still work. 
In the `lvim.plugins` I have this code 

```lua
{
    "scalameta/nvim-metals",
    config = function()
      vim.opt_global.shortmess:remove("F"):append("c") -- required by metals
      Metals_config = require("metals").bare_config()
      Metals_config.on_attach = function(client, bufnr)
        require("lvim.lsp").common_on_attach(client, bufnr)
        local wk = require("which-key")
        wk.register({ ["go"] = { "<cmd>lua require('metals').organize_imports()<CR>", "Organize Imports" } }, { mode = "n", buffer = bufnr})
        require("metals").setup_dap()
      end
      Metals_config.settings = {
        showImplicitArguments = true,
        showInferredType = true,
        excludedPackages = {
          "akka.actor.typed.javadsl",
          "com.github.swagger.akka.javadsl",
          "akka.stream.javadsl",
        },
        fallbackScalaVersion = "2.13.7",
        -- serverVersion = "0.10.9+176-3fbe9bd8-SNAPSHOT",
      }
      Metals_config.init_options.statusBarProvider = false
    end,
},
```

and some where in the config file add this code:

```lua
lvim.autocommands.custom_groups = {
   { "FileType", "scala,sbt", "lua require('metals').initialize_or_attach(Metals_config)" }
}
```

**Comment by channingwalton** [comment]
Thanks @tzaavi, much appreciated.
