### ISSUE TITLE
[Bug] `Error running config for nvim-tree.lua` while running lvim installation

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [LunarVim/LunarVim#2123]
### Problem description

1. Install the latest version of `nvim` using the script provided in the lunarvim.org installation page
2. Attempt to install the latest `lvim` by using the script provided in the lunarvim.org installation page

This produces the above that's shown in the screenshot

### LunarVim version

Rolling release with commit sha `781b2fc`

### Neovim version (>= 0.6)

NVIM v0.6.0-dev+559-gc0ba315b5

### Operating system/version

macOS 12.1

### Relevant log output

```shell
--------------------------------------------------------------------------------
Backing up old /Users/nithishkarthik/.cache/nvim to /Users/nithishkarthik/.cache/nvim.bak

Number of files: 6
Number of files transferred: 3
Total file size: 132 bytes
Total transferred file size: 132 bytes
Literal data: 132 bytes
Matched data: 0 bytes
File list size: 159
File list generation time: 0.003 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 449
Total bytes received: 98

sent 449 bytes  received 98 bytes  1.07K bytes/sec
total size is 132  speedup is 0.24
--------------------------------------------------------------------------------
Backup operation complete
--------------------------------------------------------------------------------
Installing LunarVim shim
Preparing Packer setup
packer.compile: Complete
packer.nvim: Error running config for nvim-tree.lua: ...packer/start/nvim-tree.lua/lua/nvim-tree/diagnostics.lua:161: Vim(autocmd):E216: No such group or event: DiagnosticChanged * lua require'nvim-tree.diagnostics'.update()
Press ENTER or type command to continuel
^C
```

### Screenshots

<img width="1440" alt="Screenshot 2021-12-29 at 4 55 28 PM" src="https://user-images.githubusercontent.com/75248557/147657758-eaa51cb4-1f82-4e46-91e1-7ae69c09076b.png">

**Comment by abzcoding** [comment]
https://github.com/kyazdani42/nvim-tree.lua/issues/801

You need to update your (nightly) nvim: [neovim/neovim#14090 (comment)](https://github.com/neovim/neovim/issues/14090#issuecomment-979424077).

**Comment by sudo-NithishKarthik** [comment]
Thanks @abzcoding 👍
