### ISSUE TITLE
Seemingly Nondeterministic fail to load of plugins (propably my fault)

### ISSUE THREAD

**Issue by dev-loki** [LunarVim/LunarVim#2124]
Hey,
I started using lunarvim recently. But now sometime when I activate/deactivate a plugin it seems plugins don't load anymore (especially which-key, but also stuff like hop).

My config:
http://ix.io/3K3M

What I tried:
 - Seemingly all combinations from :PackerSync, PackerUpdate, :PackerCompile
 - Looking into the compiles lua config (and not really finding anything)
 - Removing/Adding "hop" 

Odd:
 - Sometime all worked well after `:PackerLoad [tab]` and choosing e.g. which-key. But now it's even more broken and I get following message:
```
E5108: Error executing lua ...narvim/site/pack/packer/start/packer.nvim/lua/packer.lua:778: bad argument LunarVim/lunarvim.org#1 to 'pairs' (table expected, got nil)
stack traceback:                                                                                                                                           
        [C]: in function 'pairs'
        ...narvim/site/pack/packer/start/packer.nvim/lua/packer.lua:778: in function <...narvim/site/pack/packer/start/packer.nvim/lua/packer.lua:776>
E471: Argument required
```

The specific lines for this error are:
```
-- Completion for not yet loaded plugins
-- Intended to provide completion for PackerLoad command
packer.loader_complete = function(lead, _, _)
  local completion_list = {}
  for name, plugin in pairs(_G.packer_plugins) do      -- <-- this one. It seems _G.packer_plugins is empty?
    if vim.startswith(name, lead) and not plugin.loaded then
      table.insert(completion_list, name)
    end
  end
  table.sort(completion_list)
  return completion_list
end
```

I even stripped down my config to a very small minimum:
http://ix.io/3K4h

Even now I need to `:PackerLoad ...` stuff to get which key working, but I closed and reopened vim and I have the same error as above :/

**Comment by kylo252** [comment]
I think you might be using the wrong remote for the repo somewhere? because https://github.com/LunarVim/lunarvim.org is only used for the documentation, while the main repo is this one here https://github.com/LunarVim/LunarVim

**Comment by dev-loki** [comment]
> I think you might be using the wrong remote for the repo somewhere? because https://github.com/LunarVim/lunarvim.org is only used for the documentation, while the main repo is this one here https://github.com/LunarVim/LunarVim

Thanks. Oh man. Holiday brain is not working well ^^
