### ISSUE TITLE
(Documentation) What do the NodeJS/Python/etc. dependencies do?

### ISSUE THREAD

**Issue by digital-carver** [LunarVim/LunarVim#2130]
### Problem description

The website lists as part of the **Prerequisites**: "Have npm, node and cargo installed on your system." This seems to imply that these are necessary parts of the installation. 

However, during installation, these options default to "no". This seems to imply they're not. 

I tried to look around on the website and here for information about what the dependencies do in practice and when they are needed, but couldn't find an explanation. I may simply have missed it, but displaying this information in a sentence or two during the installation process would make it easy to access, and would allow us to make an informed choice. 

### LunarVim version

Stable

### Neovim version (>= 0.6)

0.6.1

### Operating system/version

Linux (OpenSUSE 15.2)

### Relevant log output

```shell
--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : 
--------------------------------------------------------------------------------
Would you like to install LunarVim's Python dependencies?
[y]es or [n]o (default: no) : ^C
```

**Comment by hoshsadiq** [comment]
For reference, the following dependencies are installed:

Node ([source](https://github.com/LunarVim/LunarVim/blob/21b41688ee8c5056ffbb2b07df141ce1ccb4b213/utils/installer/install.sh#L35-L38)):
- `tree-sitter-cli`: [npm](https://www.npmjs.com/package/tree-sitter-cli) [repo](https://github.com/tree-sitter/tree-sitter)
- `neovim`: [npm](https://www.npmjs.com/package/neovim) [repo](https://github.com/neovim/node-client)

Python ([source](https://github.com/LunarVim/LunarVim/blob/21b41688ee8c5056ffbb2b07df141ce1ccb4b213/utils/installer/install.sh#L40-L42)):
- `pynvim` [pipy](https://pypi.org/project/pynvim/) [repo](https://github.com/neovim/pynvim)

Rust ([source](https://github.com/LunarVim/LunarVim/blob/21b41688ee8c5056ffbb2b07df141ce1ccb4b213/utils/installer/install.sh#L283)):
- `fd-find` [crates](https://crates.io/crates/fd-find) [repo](https://github.com/sharkdp/fd)
- `ripgrep` [crates](https://crates.io/crates/ripgrep) [repo](https://github.com/BurntSushi/ripgrep)

I don't know enough about neovim but it seems like they might be optional, and only required depending on the plugins you enable. It would be nice to document which of the required plugins need those specific dependencies.

Side note: it seems odd to install `tree-sitter-cli` via node, when Rust dependencies are already handled.

**Comment by owod24** [comment]
Is there a way to check if you have these dependencies?

**Comment by kylo252** [comment]
> Is there a way to check if you have these dependencies?

@owod24, try this

1. check for neovim's clients `:checkhealth provider`
2. check telescope's dependencies `:checkhealth telescope`
3. [optional] check that you have all the clients/runtimes you care about for LSP, `:checkhealth mason`
