### ISSUE TITLE
Error detected while processing function `health#check`

### ISSUE THREAD

**Issue by Logarithmus** [LunarVim/LunarVim#2138]
### Problem description

1. Install LunarVim
2. Start it
3. Run `:checkhealth`
4. See error:
```
Running healthchecks...
Error detected while processing function health#check:
line   33:
E684: list index out of range: 0
```

After some investigation I found out that `nvim-lspconfig` & `null-ls` return empty checkhealth

### LunarVim version

`679cadf590466f36c08278aaab9db17c64442231 (master)`

### Neovim version (>= 0.6)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by void-buildslave@a-fsn-de  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim" 

### Operating system/version

Void Linux

### Relevant log output

```shell
Running healthchecks...
Error detected while processing function health#check:
line   33:
E684: list index out of range: 0
```

**Comment by nikosNalmpantis** [comment]
I have the same problem but only `nvim-lspconfig` returns empty checkhealth

**Comment by MahmoudAlawdh** [comment]
i have the same issue 

Error detected while processing function health#check:
line   33:                                                                                                                                                                            
E684: list index out of range: 0

**Comment by kylo252** [comment]
It's an issue with the healthcheck for lspconfig.

**Comment by MikulasVanousek** [comment]
I have the same issue in nvim. Would you happen to know which version of lsp-config fixed the issue?

**Comment by MikulasVanousek** [comment]
If you are not running lunar vim, updating lsp-config plugin fixed the issue for me.
