### ISSUE TITLE
issue when launching lvim

### ISSUE THREAD

**Issue by mezyoucef32** [LunarVim/LunarVim#2139]
### Problem description

lvim was working and today got this message

### LunarVim version

679cadf

### Neovim version (>= 0.6)

0.7

### Operating system/version

linux

### Relevant log output

```shell
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua ...te/pack/packer/opt/which-key.nvim/lua/which-key/keys.lua:251: Expected Lua
 number
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...te/pack/packer/opt/which-key.nvim/lua/which-key/keys.lua:251: in function 'map'
        ...te/pack/packer/opt/which-key.nvim/lua/which-key/keys.lua:301: in function 'register'
        ...te/pack/packer/opt/which-key.nvim/lua/which-key/init.lua:96: in function 'load'
        [string ":lua"]:1: in main chunk
```

**Comment by abzcoding** [comment]
the fix is not merged yet -> https://github.com/folke/which-key.nvim/pull/227

**Comment by abzcoding** [comment]
i would recommend keeping your neovim version before https://github.com/neovim/neovim/pull/16745/files got merged
and wait a bit to make sure all plugins are working, then going back to master

**Comment by abzcoding** [comment]
cc: @kylo252 -> https://github.com/neovim/neovim/issues/14090#issuecomment-1004318147

**Comment by kylo252** [comment]
I was looking at this yesterday, and it's not something specific to lvim. Just need to keep all the plugins updated, and help patch them if possible.
