### ISSUE TITLE
Cannot open multiple terminals

### ISSUE THREAD

**Issue by 00sapo** [LunarVim/LunarVim#2146]
https://github.com/LunarVim/LunarVim/blob/8233522e0b9b026c5ece9e420c4d9642f5a0c889/lua/lvim/core/terminal.lua#L53-L64

The above lines break the ability to open multiple terminals using the keymap (e.g. `1<C-t>`, `2<C-t>`, `3<C-t>`, etc). Using `:1ToggleTerm`, `:2ToggleTerm`  command works, but hiding the terminal with `<C-t>` not. Commenting out those lines fixes everything for me. Why do we need those lines?

**Comment by kylo252** [comment]
I had to add them because of `lazygit`, otherwise `<c-t>` would be dependent on which terminal you open first. My idea with the current implementation is that one would be explicit about the terminals that they like, the simplest thing to do is set it to empty or whatever else you like.
```lua
lvim.builtin.terminal.execs = {}
```

**Comment by 00sapo** [comment]
For me, it doesn't work. I fixed the issue by setting lazygit on terminals 101 and 102... could it work?, basically from this:

https://github.com/LunarVim/LunarVim/blob/8233522e0b9b026c5ece9e420c4d9642f5a0c889/lua/lvim/core/terminal.lua#L53-L77

to this:
```lua

-- no default terminal <=======

  for i, exec in pairs(lvim.builtin.terminal.execs) do
    local opts = {
      cmd = exec[1],
      keymap = exec[2],
      label = exec[3],
      count = i + 100, --  <==== start from 100 for the default execs
      direction = exec[4] or lvim.builtin.terminal.direction,
      size = lvim.builtin.terminal.size,
    }


    M.add_exec(opts)
  end
```

**Comment by kylo252** [comment]
> For me, it doesn't work. I fixed the issue by setting lazygit (and other execs) on terminals 101 and 102... could it work?, basically from this:

Sure, that should be fine assuming no one is using that feature. Otherwise, it seems to me that we can just remove the default shell setup which seems to work fine anyway. That will prevent overwriting `<c-t>` which seems so operate as a catch-all? 

```diff
diff --git a/lua/lvim/core/terminal.lua b/lua/lvim/core/terminal.lua
index c5d1ea0..b3f10ca 100644
--- a/lua/lvim/core/terminal.lua
+++ b/lua/lvim/core/terminal.lua
@@ -50,19 +50,6 @@ M.setup = function()
   local terminal = require "toggleterm"
   terminal.setup(lvim.builtin.terminal)
 
-  -- setup the default terminal so it's always reachable
-  local default_term_opts = {
-    cmd = lvim.builtin.terminal.shell,
-    keymap = lvim.builtin.terminal.open_mapping,
-    label = "Toggle terminal",
-    count = 1,
-    direction = lvim.builtin.terminal.direction,
-    size = lvim.builtin.terminal.size,
-  }
-  if lvim.builtin.terminal.open_mapping then
-    M.add_exec(default_term_opts)
-  end
-
   for i, exec in pairs(lvim.builtin.terminal.execs) do
     local opts = {
       cmd = exec[1],
```

That said, I think there's still another problem but it's seems like a bug in toggle-term itself, probably because of that weird fallback to first term: https://github.com/akinsho/toggleterm.nvim/blob/ce92e485a9a731405393af2bd1aff5b49ba9eb73/lua/toggleterm/terminal.lua#L69-L76

You can add a keybind to test it like this:
```vim
tnoremap <c-e> <esc><cmd>lua print("got term-id: " .. require("toggleterm.terminal").get_toggled_id())<cr>
```

![image](https://user-images.githubusercontent.com/59826753/148409788-f064b8a2-d090-4b8f-ace0-f1df40716cda.png)

**Comment by 00sapo** [comment]
By removing those lines, there are still issues when opening lazygit after having created 2 or 3 terminals. I don't see th eproblem for reserving terminal ids for special commands. Maybe ids >1000?

**Comment by kylo252** [comment]
> I don't see the problem for reserving terminal ids for special commands. Maybe ids >1000?

The main problem is that I still don't see how the actual workflow is supposed to be, because either we're registering them wrong or something is broken in toggle-term. I'd really like to know which one it is, so we can adjust the config once and for all.

Please try this:

1. disable the default config for toggle-term
https://github.com/LunarVim/LunarVim/blob/d63d87c7ea7b0f7393a61714d2ed5682d0f4ca0c/lua/lvim/plugins.lua#L271-L273
2. set it up manually and configure at least two terminals, a default shell one and some external program, e.g: `lazygit`, `htop`, etc. with one of them should be floating and the other a split.
3. check that the hotkey with count actually works consistently for a simple use-case like this

**Comment by 00sapo** [comment]
I've tried and what happens is:
* toogleterm creates two terminals with id 1 and 2 for the two processes 
* all the other terminals have id 3 according to the command you suggested above; however, when trying to compare the terminal itself by writing something in each terminal, I can see that the terminals are not the same and they respect the buffer name
* when trying to toggle terminals with id 1 and 2, it creates new terminals with the first free buffer name (>=3)  (weird!)
* when trying to toggle terminals with id >= 3, it creates/toggle terminals with buffer name as expected
* id 1 and 2 work as "create a new terminal with the first available buffer name" and they never toggle a terminal (weird!)

Example of session:
    `:1ToggleTerm`, `:2ToggleTerm`, `:3ToggleTerm`, `:4ToggleTerm`, `:1ToggleTerm` ->  3 terminals are created with buffer name 3, 4, and 5

Long story short, I think the problem comes from toggleterm itself and that lunarvim should define a guideline for defining special terminals on predefined and unused ids by default (something like 100 or 1000).

---

The following is how I got these results.

1. I commented the following lines: https://github.com/LunarVim/LunarVim/blob/d63d87c7ea7b0f7393a61714d2ed5682d0f4ca0c/lua/lvim/plugins.lua#L266-L275

2. I've added the following to my `config.lua` (copied-and pasted from toggleterm readme):
```lua
lvim.plugins = {
  { "akinsho/toggleterm.nvim", 
    config = function ()
      require'toggleterm'.setup{
          -- size can be a number or function which is passed the current terminal
        size = function(term)
          if term.direction == "horizontal" then
            return 15
          elseif term.direction == "vertical" then
            return vim.o.columns * 0.4
          end
        end,
        open_mapping = [[<c-\>]],
        -- on_open = fun(t: Terminal), -- function to run when the terminal opens
        -- on_close = fun(t: Terminal), -- function to run when the terminal closes
        hide_numbers = true, -- hide the number column in toggleterm buffers
        shade_filetypes = {},
        shade_terminals = true,
        shading_factor = '<number>', -- the degree by which to darken to terminal colour, default: 1 for dark backgrounds, 3 for light
        start_in_insert = true,
        insert_mappings = true, -- whether or not the open mapping applies in insert mode
        persist_size = true,
        direction = 'horizontal', -- | 'window' | 'float',
        close_on_exit = true, -- close the terminal window when the process exits
        shell = vim.o.shell, -- change the default shell
        -- This field is only relevant if direction is set to 'float'
        float_opts = {
          -- The border key is *almost* the same as 'nvim_open_win'
          -- see :h nvim_open_win for details on borders however
          -- the 'curved' border is a custom border type
          -- not natively supported but implemented in this plugin.
          border = 'single', -- | 'double' | 'shadow' | 'curved' | ... other options supported by win open
          width = 200,
          height = 200,
          winblend = 3,
          highlights = {
            border = "Normal",
            background = "Normal",
          }
        }
      }

      local Terminal  = require('toggleterm.terminal').Terminal
      local lazygit = Terminal:new({
        cmd = "lazygit",
        dir = "git_dir",
        direction = "float",
        float_opts = {
          border = "double",
        },
        -- function to run on opening the terminal
        on_open = function(term)
          vim.cmd("startinsert!")
          vim.api.nvim_buf_set_keymap(term.bufnr, "n", "q", "<cmd>close<CR>", {noremap = true, silent = true})
        end,
        -- function to run on closing the terminal
        on_close = function(term)
          vim.cmd("Closing terminal")
        end,
      })

      local htop = Terminal:new({
        cmd = "htop",
        direction = "vertical",
        -- function to run on opening the terminal
        on_open = function(term)
          vim.cmd("startinsert!")
          vim.api.nvim_buf_set_keymap(term.bufnr, "n", "q", "<cmd>close<CR>", {noremap = true, silent = true})
        end,
        -- function to run on closing the terminal
        on_close = function(term)
          vim.cmd("Closing terminal")
        end,
      })

      function _lazygit_toggle()
        lazygit:toggle()
      end

      function _htop_toggle()
        htop:toggle()
      end

      vim.api.nvim_set_keymap("n", "<leader>gg", "<cmd>lua _lazygit_toggle()<CR>", {noremap = true, silent = true})
      vim.api.nvim_set_keymap("n", "<leader>hh", "<cmd>lua _htop_toggle()<CR>", {noremap = true, silent = true})
     -- get the true id
      vim.api.nvim_set_keymap("t", "<c-e>", '<cmd>lua print("got term-id: " .. require("toggleterm.terminal").get_toggled_id())<cr>', {noremap=true})
    end
  },
-- [...]
}
```

**Comment by 00sapo** [comment]
I think that what I called "buffer name" is only actually the status line, which uses `b:toggle_number` variable: https://github.com/akinsho/toggleterm.nvim#statusline

**Comment by kylo252** [comment]
Thank you so much for all the effort that went into this! 

We can now just shift the IDs since `:2ToggleTerm` doesn't seem to consistently work for any of the execs anyway.
