### ISSUE TITLE
html lsp and emmet_ls doesn't work. 

### ISSUE THREAD

**Issue by Leiyi548** [LunarVim/LunarVim#2152]
### Problem description

I installed html lsp using LspInstall html, but when I opened html, it didn't work, and emmet_ls didn't work either.

### LunarVim version

rolling

### Neovim version (>= 0.6)

NVIM v0.7.0-dev+656-g36565c9da Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

macos 10.5

### Relevant log output

```shell
Language client log: /Users/macos/.cache/nvim/lsp.log
 Detected filetype:   html
 
 1 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, pid: 5001, bufnr: [1])
 	filetypes:       html, javascriptreact, typescriptreact, markdown, javascript, scss, css, typescript, graphql, yaml, less, vue, json
 	autostart:       false
 	root directory:  /Users/macos/Desktop/leetcode/dayPratice/Python
 	cmd:             nvim
 
 Configured servers list: null-ls
```

### Screenshots

![image](https://user-images.githubusercontent.com/76139422/148551065-3fdfaac5-d3df-4e63-bd95-de11a30f321a.png)
![Uploading image.png…]()

**Comment by hobochild** [comment]
I'm seeing the same issues except with black formatting python code. I can see null-ls is attached to the buffer. But formatting doesn't work. 

![image](https://user-images.githubusercontent.com/9499917/148637316-a6d5a5ce-6a7a-488e-b5e6-f6acb825c89f.png)

nvim version: NVIM v0.7.0-dev+733-gb1757e1c2
lvim version: 679cadf

My formatter config looks like this: 

```
local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup {
  { exe = "black", filetypes = { "python" } }
}
```

I have black installed locally too. Any ideas where too look?

**Comment by kylo252** [comment]
@Leiyi548, please show me the folder structure, and the output of 
```lua
:lua print(vim.inspect(lvim.lsp.override))
```

---

@hobochild, please test #2154 to see if it fixes your issue

**Comment by Leiyi548** [comment]
@kylo252  { "angularls", "ansiblels", "ccls", "csharp_ls", "cssmodules_ls", "denols", "
ember", "emmet_ls", "eslint", "eslintls", "grammarly", "graphql", "jedi_langu
age_server", "ltex", "phpactor", "pylsp", "quick_lint_js", "rome", "solang",
"solidity_ls", "sorbet", "sourcekit", "spectral", "sqlls", "sqls", "stylelint
_lsp", "tailwindcss", "tflint", "volar", "zk" }

**Comment by kylo252** [comment]
@Leiyi548, you can see that `emmet_ls` is overridden so you need to call the setup function manually, see: https://www.lunarvim.org/languages/#server-override

I need more info regarding the html server, you can also check https://www.lunarvim.org/troubleshooting/#language-server-xxx-does-not-start-for-me

**Comment by Leiyi548** [comment]
@kylo252  
emmet_ LS is valid, but HTML LSP is not

**Comment by hobochild** [comment]
Thanks @Leiyi548, I've tested against #2154. But the issue still persists.

**Comment by angryheng** [comment]
same issue

**Comment by kylo252** [comment]
> emmet_ LS is valid, but HTML LSP is not

Please test the html server with the minimal config, but remember to change this entry first
https://github.com/LunarVim/LunarVim/blob/e9caf5a69a0c31adcfeeeee928ffe76ad6ba4ceb/tests/minimal_lsp.lua#L77-L78

---

You can run it like this

```shell
cd ~/.local/share/lunarvim/lvim
nvim -u tests/minimal_lsp.lua
```

**Comment by hobochild** [comment]
Sure I've created an issue here: https://github.com/LunarVim/LunarVim/issues/2168
