### ISSUE TITLE
rust-tools not working

### ISSUE THREAD

**Issue by bob3000** [LunarVim/LunarVim#2163]
### Problem description

Currently the `rust_analyzer` language server is not attaching to any rust buffers on my machine when set up via `rust-tools`.

This is the relevant part of my configuration my configuration:

```lua
vim.list_extend(lvim.lsp.override, { "rust_analyzer" })
lvim.plugins = {
	{
		"simrat39/rust-tools.nvim",
		config = function()
			local lsp_installer_servers = require("nvim-lsp-installer.servers")
			local _, requested_server = lsp_installer_servers.get_server("rust_analyzer")
			require("rust-tools").setup({
				tools = {
					autoSetHints = true,
					hover_with_actions = true,
					runnables = {
						use_telescope = true,
					},
				},
				server = {
					cmd = requested_server._default_options.cmd,
					on_attach = require("lvim.lsp").common_on_attach,
					on_init = require("lvim.lsp").common_on_init,
				},
			})
		end,
		ft = { "rust", "rs" },
	},
}
```
I already uninstalled and reinstalled Lunar Vim.
I also read through issue #2038  and tried the solutions described there including `:LvimCacheReset` without any luck.
Does anyone else have the same issue? Any ideas how to fix or further debug?

### LunarVim version

1.0.0

### Neovim version (>= 0.6)

0.6.0

### Operating system/version

Arch Linux

### Affected language servers

rust_analyzer

### Actual behavior

`:LspInfo` does not show any attached buffers after opening a rust file.

### Expected behavior

`rust_analyzer` should attach to rust buffers

### log and support info

```shell
Buffer info                      
* filetype:                rust  
* bufnr:                   4     
* treesitter status:       active
                                 
Active client(s)                 
                                 
Overridden rust server(s)        
* list: rust_analyzer            
                                 
Formatters info                  
* Active:                        
* Supported: rustfmt             
                                 
Linters info                     
* Active: codespell             
* Supported: []                  
                                 
Code actions info                
* Active:
```

**Comment by abzcoding** [comment]
can you test changing 
```lua
cmd = requested_server._default_options.cmd,
```
to 
```lua
cmd_env = requested_server._default_options.cmd_env,
```

**Comment by kylo252** [comment]
It would be good to update this section (https://www.lunarvim.org/languages/rust.html#extra-plugins) with a minimal working config that's compatible with the installer's  new API.

**Comment by bob3000** [comment]
@abzcoding Unfortunately it won't help

**Comment by kylo252** [comment]
@bob3000, does `LspInfo` show the server as configured?

**Comment by bob3000** [comment]
@kylo252 only `null-ls` is showing up

```
Language client log: /home/bob/.cache/nvim/lsp.log
Detected filetype:   rust

1 client(s) attached to this buffer:

Client: null-ls (id: 1, pid: 5001, bufnr: [1])
 filetypes:       javascript, typescript, typescriptreact, javascriptreact, vue, python, lua, sh, json
 autostart:       false
 root directory:  /home/bob/code/rust/thevault
 cmd:             nvim

Configured servers list:


```

**Comment by abzcoding** [comment]
that is weird, it seems to be working for me 🤔 
<img width="453" alt="Screen Shot 2022-01-11 at 1 28 05 PM" src="https://user-images.githubusercontent.com/10992695/148921514-0756c410-a7f7-4bbe-a6a1-c1e9c45653e5.png">
<img width="1169" alt="Screen Shot 2022-01-11 at 1 28 15 PM" src="https://user-images.githubusercontent.com/10992695/148921522-d58e8183-9897-4e87-aa38-5541ab10e263.png">

**Comment by kylo252** [comment]
Some things to test
1. move that function away from packer, and just call it manually in `config.lua`
2. use the public API instead `requested_server:get_default_options().cmd_env`
3. validate that the installer actually has the server

```lua
local lsp_installer_servers = require("nvim-lsp-installer.servers")
local server_ok, requested_server = lsp_installer_servers.get_server("rust_analyzer")
if server_ok then
	print("using server's env: " .. requested_server:get_default_options().cmd_env)
end
```

**Comment by bob3000** [comment]
It working again. The solution however is completely opaque and dissatisfying. I went back in git history to the 14th of December and ran `PackerSync` and `LvimCacheReset` and it was working again. Then I moved forward in the history and repeated the process until I arrived at the present again and now it's still working :man_shrugging:

As I mentioned before I even completely uninstalled and reinstalled lvim in between and the problem was not fixed by that. Which actually means that something is not removed by the uninstall script or by the cache reset.

Is it maybe somehow connected to packer? It's a different matter but maybe it points to something: Whenever I run `PackerUpdate` (even on the latest commit) it want's to remove the `notify` plugin and won't try to reinstall it in the next step.
Is there maybe any packer cache that is not reset by `LvimCacheReset` which could also cause the issue with the `rust-tools`?

**Comment by bob3000** [comment]
@kylo252 It must be some kind of issue with packer. To sum up I can state, that I run into the trouble even after a fresh install however I was able to fix the `notify` problem (and it's probably the same with the `rust-tools`) by removing `~/.local/share/lunarvim/site/pack/packer` and then running `:PackerInstall` and `:PackerCompile`.

**Comment by bob3000** [comment]
I'll close this for now since the problem doesn't seem to be directly related to the `rust-tools` even though it was the only place where the error became noticeable.

@abzcoding @kylo252 Thanks for your help. You guys and many others are doing absolutely awesome job here. LunarVim is such a great project.

**Comment by abzcoding** [comment]
> It seems like rust-tools is not working again with the latest rolling release and when using the [Extra Plugins ](https://www.lunarvim.org/languages/rust.html#debugger) snippet defined on the website.
> 
> The problem seems to be that the word **rust** is used in this part `lvim.lsp.override = { "rust" }` instead of **rust_analyzer**. I also found that ~/.local/share/lunarvim/lvim/lua/lvim/config.lua contains an overrides table that does not have **rust_analyzer** as an entry. Though forgive me if this list is auto-generated somehow.
> 
> In short, to fix the problem with the config on the website I used the config posted by @bob3000 at the top of this issue that already uses the correct **rust_analyzer** name and added the missing entry in the share/.../config.lua.
> 
> I may have re-run PackerSync after this too.

thank you for mentioning it, updated the [docs](https://github.com/LunarVim/lunarvim.org/blob/master/docs/languages/rust.md) accordingly
