### ISSUE TITLE
Weird Lunarvim theme behavior

### ISSUE THREAD

**Issue by fabioluciano** [LunarVim/LunarVim#2164]
### Problem description

I added the dracula theme in Lunarvim and the colorscheme configuration dont persist.

### LunarVim version

1.0.0

### Neovim version (>= 0.6)

NVIM v0.6.1

### Operating system/version

Linux iorek 5.15.13-arch1-1 #1 SMP PREEMPT Wed, 05 Jan 2022 16:20:59 +0000 x86_64 GNU/Linux

### Relevant log output

```shell
NA
```

### Screenshots

![Dracula theme Issue](https://i.imgur.com/t9G2JYt.gif)

**Comment by abzcoding** [comment]
please make sure you have this in your config
```lua
lvim.colorscheme = "dracula"
```

also you can try doing a `:LvimCacheReset` if that didn't help

**Comment by fabioluciano** [comment]
this is my config.lua


``` lua

-- general
lvim.log.level = "warn"
lvim.format_on_save = true
lvim.colorscheme = "dracula"

-- keymappings [view all the defaults by pressing <leader>Lk]
lvim.leader = "space"
-- add your own keymapping
lvim.keys.normal_mode["<C-s>"] = ":w<cr>"

lvim.builtin.dashboard.active = true
lvim.builtin.notify.active = true
lvim.builtin.terminal.active = true
lvim.builtin.nvimtree.setup.view.side = "left"
lvim.builtin.nvimtree.show_icons.git = 0

-- if you don't want all the parsers change this to a table of the ones you want
lvim.builtin.treesitter.ensure_installed = {
  "bash",
  "c",
  "javascript",
  "json",
  "lua",
  "python",
  "typescript",
  "css",
  "rust",
  "java",
  "yaml",
}

lvim.builtin.treesitter.ignore_install = { "haskell" }
lvim.builtin.treesitter.highlight.enabled = true

-- Additional Plugins
lvim.plugins = {
    {
      "dracula/vim",
      config = function()
        vim.g.dracula_colorterm = 0
      end
    },
}


Also, i tried with `:LvimCacheReset`, ans keeps the same behavior.

```

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by kylo252** [comment]
Can you try commenting out this line: 
https://github.com/LunarVim/LunarVim/blob/e9caf5a69a0c31adcfeeeee928ffe76ad6ba4ceb/lua/lvim/utils/hooks.lua#L16

**Comment by fabioluciano** [comment]
Key @kylo252!

I tried what you suggested, and the behavior stills.

![Steps](https://i.imgur.com/deBGDHe.gif)

**Comment by kylo252** [comment]
Is that tmux? does the issue exist when running without it?

**Comment by fabioluciano** [comment]
@kylo252 i have new informations to give to you!

I've been trying to address where the issue is been triggered, and i discovered that the weird behaviour only happens when i open `.yaml` files.

I tested both scenarios. With and without tmux, "confirming" that tmux is not influencing the result. In both tests, i opened a `.js` file(that renders the theme), and a `.yaml`(i need to reload LunarVim configurations to apply the theme).

**Test without tmux**
![Test without tmux](https://i.imgur.com/r1NTYVs.gif) 


**Test with tmux**
![Test with tmux](https://i.imgur.com/rJGgmEq.gif)

**Comment by abzcoding** [comment]
@fabioluciano can you try this
```lua
lvim.plugins = {
    {
      "Mofiqul/dracula.nvim",
    },
}
```
instead of this and see if it fixes anything or not?
```lua
lvim.plugins = {
    {
      "dracula/vim",
      config = function()
        vim.g.dracula_colorterm = 0
      end
    },
}
```
note: you need to run `:PackerSync`

**Comment by danielyrovas** [comment]
I experienced a similar issue today,  however it went away after a few restarts and a PackerSyncs.

**Comment by kylo252** [comment]
It should hopefully be fixed in [`e33bfb7` (#2351)](https://github.com/LunarVim/LunarVim/pull/2351/commits/e33bfb749eacd9b2a32fb0a129f55a1f2554ad3a)

**Comment by aik2mlj** [comment]
hello I encountered the same issue with my colorscheme setting.
```
lvim.colorscheme = "kanagawa"
```
lunarvim falls back to the default neovim theme. I've rolled to the latest commit and `:LvimCacheReset` for some times, but they didn't help... My theme did come back after a `:PackerSync` but it didn't persist the next time I open lunarvim :-(

**Comment by abzcoding** [comment]
> hello I encountered the same issue with my colorscheme setting.
> 
> ```
> lvim.colorscheme = "kanagawa"
> ```
> 
> lunarvim falls back to the default neovim theme. I've rolled to the latest commit and `:LvimCacheReset` for some times, but they didn't help... My theme did come back after a `:PackerSync` but it didn't persist the next time I open lunarvim :-(

that should be fixed with (https://github.com/LunarVim/LunarVim/pull/2392)

**Comment by aik2mlj** [comment]
seems fixed!
