### ISSUE TITLE
black format is not running

### ISSUE THREAD

**Issue by hobochild** [LunarVim/LunarVim#2168]
### Problem description

Black format isn't running on_save or when triggering lsp format. 

I can see null-ls is attached to the buffer and  NullLsLog is empty too.

My formatter config looks like this: 

```
local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup {
  { exe = "black", filetypes = { "python" } }
}
```

Any ideas where to look? Thanks!

### LunarVim version

8fe7cf2

### Neovim version (>= 0.6)

NVIM v0.7.0-dev+733-gb1757e1c2

### Operating system/version

Ubuntu 20.04.3 LTS

### Affected language servers

null-ls

### Steps to reproduce

1. Make a change that conflicts with black formatter on a `*.py` file
2. `<leader>lf` - Doesn't reformat the buffer.
3. Saving the file also doesn't format, even though `lvim.format_on_save = true` is set.
4. Manually run `black <file>` and the file will be formatted correctly.

### Actual behavior

black formatter is run on save with python files.

### log and support info

```shell
LspInfo:
![image](https://user-images.githubusercontent.com/9499917/148637316-a6d5a5ce-6a7a-488e-b5e6-f6acb825c89f.png)

LvimInfo:
![image](https://user-images.githubusercontent.com/9499917/149103275-29aa515a-5c88-4015-b514-61a11cc992f2.png)

`healthcheck` gives me: 

null-ls: require("null-ls.health").check()
========================================================================
  - OK: black: the command "black" is executable.
```

**Comment by kylo252** [comment]
I'm unable to reproduce this, but I can see that `null-ls` is using the `--quite` flag.

Things to try:
1. enable debug logging in both lvim and null-ls
```lua
lvim.log.level = "debug"
lvim.lsp.null_ls.setup = {
  log = {
    level = "debug",
  },
}
```
2. format the file directly from neovim and see if it's complaining about something
```vim
:! black %
```
3. set up null-ls manually with the default settings, and see if it makes a difference
```lua
local null_ls = require "null-ls"
local sources = { null_ls.builtins.formatting.black }
null_ls.register {sources = sources} 
```

**Comment by hobochild** [comment]
1. Here are the debug logs from null-ls: 
```
[DEBUG Fri 14 Jan 2022 09:13:56 SAST] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[DEBUG Fri 14 Jan 2022 09:13:58 SAST] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:333: spawning command [black] with args { "--stdin-filename", "/home/hobochild/Play/dream/tests/conftest.py", "--quiet", "-" }
[DEBUG Fri 14 Jan 2022 09:13:58 SAST] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:55: received edits from generators
[DEBUG Fri 14 Jan 2022 09:13:58 SAST] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:74: successfully applied edits
[DEBUG Fri 14 Jan 2022 09:13:58 SAST] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[DEBUG Fri 14 Jan 2022 09:14:01 SAST] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:333: spawning command [black] with args { "--stdin-filename", "/home/hobochild/Play/dream/tests/conftest.py", "--quiet", "-" }
[DEBUG Fri 14 Jan 2022 09:14:01 SAST] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:55: received edits from generators
[DEBUG Fri 14 Jan 2022 09:14:01 SAST] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:74: successfully applied edits
[DEBUG Fri 14 Jan 2022 09:14:01 SAST] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:141: buffer unchanged; ignoring didSave notification
[DEBUG Fri 14 Jan 2022 09:14:07 SAST] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
[DEBUG Fri 14 Jan 2022 09:14:07 SAST] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:333: spawning command [black] with args { "--stdin-filename", "/home/hobochild/Play/dream/tests/conftest.py", "--quiet", "-" }
[DEBUG Fri 14 Jan 2022 09:14:08 SAST] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:55: received edits from generators
[DEBUG Fri 14 Jan 2022 09:14:08 SAST] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:74: successfully applied edits
[DEBUG Fri 14 Jan 2022 09:14:08 SAST] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:12: no generators available
``` 
I thought the no generators available is the only thing that looked error-like. There is this [issue](https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/543) which might be similar which seems to have resolved itself.

2. Running black directly works and the buffer is updated.
3. Running null-ls manually doesn't work. 
4. I also tried disabling all extra-plugins to with no effect.

Unless you have any other ideas, I can only think of completely removing lvim and re-installing and to see if that has any effect?

**Comment by hobochild** [comment]
Okay, I've figured it out. You can see null-ls is executing args  `{ "--stdin-filename", "/home/hobochild/Play/dream/tests/conftest.py", "--quiet", "-" }`. 

So I tried to run black directly with those args. it complains that `--stdin-filename` is not a valid option. I was running black `20.8b1` it appears that flag was added later. I've upgraded black to `21.12b0` and it's now working. Still unclear why that error isn't surfaced in the logs I assume null-ls is dropping it somewhere. 

Thanks for your help!
