### ISSUE TITLE
Cannot install which-key

### ISSUE THREAD

**Issue by glatavento** [LunarVim/LunarVim#2173]
### Problem description

1. Run `:PackerUpdate`
2. An error occurs

Also, I can't open https://github.com/zeertzjq/which-key.nvim. I guess this is the problem.

### LunarVim version

d084051

### Neovim version (>= 0.6)

NVIM v0.6.0 Build type: Release LuaJIT 2.0.5

### Operating system/version

Linux 5.10

### Relevant log output

```shell
NA
```

### Screenshots

![图片](https://user-images.githubusercontent.com/76601050/149307764-7282c0ea-8b2a-4b54-bebc-fa1a68b2b5c3.png)

**Comment by abzcoding** [comment]
Fixed via https://github.com/LunarVim/LunarVim/commit/8a557b90c6da7b598250b48198a972cca0ff31c2
