### ISSUE TITLE
Disabling which_key breaks comment plugin?

### ISSUE THREAD

**Issue by pudymody** [LunarVim/LunarVim#2179]
### Problem description

I was trying this config and everything was excellent until i tried to diable *which_key* plugin. After that, the comment plugin stopped working. I could no longer toggle comments with the *gcc* shortcut, neither the *CommentToggle* was available.

I dont know if this is a bug or a problem on my side. The only thing i did was add the following line to the config file, and run the needed Packer commands

```
lvim.builtin.which_key.active = false
```

### LunarVim version

7125e2b (stable)

### Neovim version (>= 0.6)

NVIM v0.6.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 (latest stable appimage)

### Operating system/version

Ubuntu 20.04.3 LTS

### Relevant log output

```shell
Dont think its relevant
```

**Comment by abzcoding** [comment]
first off please run `:LvimCacheReset` to make sure nothing is cached,
after that please run
```vim
:verbose map gcc
```
to see what is it mapped to

sidenote: the leader keybindings wouldn't work anymore, since we are setting all of them using `which_key`

**Comment by pudymody** [comment]
Ran `:LvimCacheReset` but nothing changed

It seems that its currently mapped, but i doesnt fire.

This is with which_key **disabled**

```
x  gc          * <Esc><Cmd>lua require("Comment.api").toggle_linewise_op(vim.fn.visualmode())<CR>
Se definió por última vez en anonymous :source

n  gc          * <Cmd>lua require("Comment.api").call("toggle_linewise_op")<CR>g@
Se definió por última vez en anonymous :source

n  gcc         * v:count == 0 ? '<Cmd>lua require("Comment.api").call("toggle_current_linewise_op")<CR>g@$' : '<Cmd>lua require("Comment.api").toggle_linewise_count()
<CR>'
Se definió por última vez en anonymous :source
```

And this is with which_key **enabled**

```
n  g           * <Cmd>lua require("which-key").show("g", {mode = "n", auto = true})<CR>
x  g           * <Cmd>lua require("which-key").show("g", {mode = "v", auto = true})<CR>
Se definió por última vez en anonymous :source

x  gc          * <Esc><Cmd>lua require("Comment.api").toggle_linewise_op(vim.fn.visualmode())<CR>
Se definió por última vez en anonymous :source

n  gc          * <Cmd>lua require("Comment.api").call("toggle_linewise_op")<CR>g@
Se definió por última vez en anonymous :source

n  gcc         * v:count == 0 ? '<Cmd>lua require("Comment.api").call("toggle_current_linewise_op")<CR>g@$' : '<Cmd>lua require("Comment.api").toggle_linewise_count()
<CR>'
Se definió por última vez en anonymous :source
```

**Comment by abzcoding** [comment]
i would suggest increasing your `timeoutlen` to make the keybindings register properly
```lua
vim.opt.timeoutlen = 300
```

**Comment by pudymody** [comment]
Now it works flawlessly, thank you so much for your time.
