### ISSUE TITLE
PHP Formatting

### ISSUE THREAD

**Issue by RizaHKhan** [LunarVim/LunarVim#2185]
### Problem description

Having a hard time figuring out how to set the indentation to 4 instead of the default 2

### LunarVim version

7125e2b

### Neovim version (>= 0.6)

0.6

### Operating system/version

macOS Monterey version 12.1

### Affected language servers

intelephense

### Steps to reproduce

1. Open a PHP file
2. Save using `<leader>w`

### Actual behavior

Formatting is set to 2 spaces

### Expected behavior

Would like to adjust to 4

### log and support info

```shell
See below:
```

### Screenshots

LspInfo:
![image](https://user-images.githubusercontent.com/51720003/149628471-80a4fe0e-0014-425c-9a1e-7725e65d430d.png)

:LvimInfo:
![image](https://user-images.githubusercontent.com/51720003/149628490-f370f20b-8265-4c72-83a8-b61636710094.png)

**Comment by abzcoding** [comment]
from [documentation](https://www.lunarvim.org/configuration/05-autocommands.html):
```lua
lvim.autocommands.custom_groups = {
  -- On entering a php file, set the tab spacing and shift width to 4
  { "BufWinEnter", "*.php", "setlocal ts=4 sw=4" },
}
```
