### ISSUE TITLE
VueJS And VueLS formatting

### ISSUE THREAD

**Issue by RizaHKhan** [LunarVim/LunarVim#2197]
### Problem description

Fresh install of Lunvarvim (love how fast it is...) and am developing in a Laravel app.

The PHP language server works great! The VueJS server doesn't.

I can't format files. 

### LunarVim version

7125e2b

### Neovim version (>= 0.6)

NVIM v0.6.1

### Operating system/version

macOS Monterey version 12.1

### Affected language servers

vuels

### Steps to reproduce

1. Install a VueJS app (either from vue-cli or an existing one)
2. Open a .vue file
3. Make formatting wrong (put an extra indent which shouldn't belong)
2. Save file (assuming format on save is true)

### Actual behavior

Nothing happens, formatting is not corrected

### Expected behavior

I would like the formatter to run and fix any problems on save (like it does on the PHP files).

Should VueJS formatting/linting work out of the box with Lunarvim or is there additional servers to install?

### log and support info

```shell
Error from `lsp.log`:

[START][2022-01-18 21:58:26] LSP logging initiated
[WARN][2022-01-18 21:58:31] ...lsp/handlers.lua:109	"The language server vuels triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2022-01-18 21:58:31] ...lsp/handlers.lua:404	'(node:53342) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/rizakhan/labspend/node_modules/vuex/package.json.\nUpdate this package.json to use a subpath pattern like "./*".\n(Use `node --trace-deprecation ...` to show where the warning was created)'
```

### Screenshots

![image](https://user-images.githubusercontent.com/51720003/150056573-785786e9-fcf5-40b5-be54-1c449a915fde.png)
![image](https://user-images.githubusercontent.com/51720003/150056681-d08e4d4c-378c-4e3b-85d1-b32531f38c3b.png)

**Comment by abzcoding** [comment]
can you try `:TSInstall vue` to install the treesitter support

**Comment by RizaHKhan** [comment]
@abzcoding Continued to play around with the configuration and I think I'm at the point where I'm comfortable with my setup.

Is this configuration OK for linting/formatting:

```
-- -- set a formatter, this will override the language server formatting capabilities (if it exists)
formatters.setup {
  {
    exe = "prettier",
    filetypes = {
      "javascriptreact",
      "javascript",
      "typescriptreact",
      "typescript",
      "json",
      "markdown",
      "vue"
    },
  },
  {
    exe = 'eslint',
    filetypes = {
      -- "vue"
    }
  }
}

-- ESLint
local linters = require "lvim.lsp.null-ls.linters"
linters.setup {
  {
    exe = "eslint",
    filetypes = {
      "javascriptreact",
      "javascript",
      "typescriptreact",
      "typescript",
      "vue",
    },
  },
}
```

**Comment by abzcoding** [comment]
i mean they seem to be ok 🤷

**Comment by carmolim** [comment]
The link for the doc is missing, tried the same configuration, but nothing happens when I save the file
