### ISSUE TITLE
Wrong config for nvim-autopair

### ISSUE THREAD

**Issue by kuang22** [LunarVim/LunarVim#2204]
### Problem description

With the configuration in lunarvim/lvim/lua/lvim/core/autopairs.lua.
1. open a test.tex file
2. Enter insert mode, and input "$$"
3. There will be five '$', and we expect when we input "$$" we get four $
4. After checking the plugins and lsp config, I found that this is caused by the autopairs configuration problem.
```
  autopairs.add_rule(Rule("$$", "$$", "tex"))
  autopairs.add_rules {
    Rule("$", "$", { "tex", "latex" }) -- don't add a pair if the next character is %
      :with_pair(cond.not_after_regex_check "%%") -- don't add a pair if  the previous character is xxx
      :with_pair(cond.not_before_regex_check("xxx", 3)) -- don't move right when repeat character
      :with_move(cond.none()) -- don't delete if the next character is xx
      :with_del(cond.not_after_regex_check "xx") -- disable  add newline when press <cr>
      :with_cr(cond.none()),
  }
  autopairs.add_rules {
    Rule("$$", "$$", "tex"):with_pair(function(opts)
      print(vim.inspect(opts))
      if opts.line == "aa $$" then
        -- don't add pair on that line
        return false
      end
    end),
  }
```

Apparently, these lines code are from the windwp/nvim-autopairs ReadMe, I think this is just examples the author(windwp) to explain how to add_rules with cond, these lines should not be put into the default configuration for autopairs as you do now, which leads to some problems.

I suggest 
1. Delete these lines of code.
2. Write a right config for '$' and '$$' auto pair rules.

This is a minor but annoying problem for people usign lvim writing latex. Wish that you can fix that, thx in advance.

### LunarVim version

The latest commit

### Neovim version (>= 0.6)

VIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 

### Operating system/version

ubuntu 20.04

### Relevant log output

```shell
nothing
```

**Comment by abzcoding** [comment]
i'm kind of in favor of removing all of those lines, what do you think @kylo252 ?
