### ISSUE TITLE
Comment mappings with space / not working

### ISSUE THREAD

**Issue by jordisantamaria** [LunarVim/LunarVim#2207]
### Problem description

When press `space /` It gives me this error.
![image](https://user-images.githubusercontent.com/6263700/150678552-339fbb0b-f8a7-441b-8ef7-459738fdfad1.png)

### LunarVim version

#2205

### Neovim version (>= 0.6)

NVIM v0.6.0-dev+5ad15c9

### Operating system/version

linux mint 20.2 (uma)

### Relevant log output

```shell
![image](https://user-images.githubusercontent.com/6263700/150678552-339fbb0b-f8a7-441b-8ef7-459738fdfad1.png)
```

**Comment by abzcoding** [comment]
can you run a `:LvimCacheReset` to make sure nothing has been weirdly cached

**Comment by jordisantamaria** [comment]
I fixed It like that https://github.com/winston0410/commented.nvim/issues/11 , but now I have the issue of `Not an editor command: NvimTreeToggle`

**Comment by abzcoding** [comment]
did you ran `:LvimCacheReset` as i mentioned?

**Comment by jordisantamaria** [comment]
yes

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by kylo252** [comment]
It might be some lazy-loading issue, what's the result of this:
```lua
:lua print(vim.inspect(require("ts_context_commentstring.internal")))
:lua print(vim.inspect(require("ts_context_commentstring.internal").calculate_commentstring()))
```

**Comment by jordisantamaria** [comment]
:lua print(vim.inspect(require("ts_context_commentstring.internal").calculate_commentstring())) = nil
:lua print(vim.inspect(require("ts_context_commentstring.internal"))) = 
![image](https://user-images.githubusercontent.com/6263700/150938518-4d3c3860-944e-4a89-ada3-67e22a116b25.png)
![image](https://user-images.githubusercontent.com/6263700/150938551-262e7855-5b51-46ce-892d-85acfe9f99b6.png)

**Comment by kylo252** [comment]
> `:lua print(vim.inspect(require("ts_context_commentstring.internal").calculate_commentstring())) `

What filetype are you trying? is it supported by the plugin? do you have the treesitter parser installed?
Also, please try this again just before you call the comment command.

**Comment by abzcoding** [comment]
this should be fixed, feel free to reopen if you still face this issue
