### ISSUE TITLE
Add Racket as a Lsp language

### ISSUE THREAD

**Issue by tran1903alt** [LunarVim/LunarVim#2213]
### Feature Description

I'd like to have RacketLang as a LSP language in LunarVim, is that possible?

### Describe the alternatives you have considered

:LspInstall Racket should be usable

### Support information

http://racket-lang.org

**Comment by abzcoding** [comment]
we are using [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer) as our lang server provider,
so you can either create an issue in their repo, or just create your own custom one, [here is an example for r](https://github.com/abzcoding/lvim/blob/main/ftplugin/r.lua)
