### ISSUE TITLE
Image charge error

### ISSUE THREAD

**Issue by PabloMartinMoreno** [LunarVim/LunarVim#2214]
### Problem description

Image charge error

![pic-full-220126-2022-55](https://user-images.githubusercontent.com/44477540/151263718-b7d0d523-99df-4002-a44d-c9150f1d8bfb.png)

### LunarVim version

Latest

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Artix linux

### Relevant log output

```shell
All installed
```

**Comment by abzcoding** [comment]
please install and configure a nerd font as mentioned in the [docs](https://www.lunarvim.org/02-after-install.html#nerd-fonts)
