### ISSUE TITLE
I open the lvim and    Unable to retrieve the name of the current branch. Check the log for further information

### ISSUE THREAD

**Issue by jiadsii** [LunarVim/LunarVim#2226]
### Feature Description

Unable to retrieve the name of the current branch. Check the log for further information

### Describe the alternatives you have considered

<img width="1280" alt="截屏2022-01-30 下午6 49 07" src="https://user-images.githubusercontent.com/45071541/151696552-6495015f-6806-4259-94d7-f89882b8b585.png">

**Comment by abzcoding** [comment]
@jiadsii can you check if this fixes your issue?
open `~/.local/share/lunarvim/lvim/lua/lvim/utils/git.lua`
change line 92 from
```lua
local ret, branch = git_cmd { args = { "branch", "--show-current" } }
```
to
```lua
local ret, branch = git_cmd { args = { "rev-parse", "--abbrev-ref", "HEAD" } }
```

**Comment by jiadsii** [comment]
ok yes ,it fix my problem, and it work well and not report this problem.

**Comment by abzcoding** [comment]
btw you can change that back after #2225 is merged
