### ISSUE TITLE
I need some document to learn how to use it

### ISSUE THREAD

**Issue by jiadsii** [LunarVim/LunarVim#2227]
### Feature Description

I do not know how to use it

and it needs some document to learn it : for such as Shortcut key

and now I need to order to run this code , but I donot know how to quickrun this code. 
<img width="1280" alt="截屏2022-01-30 下午7 51 42" src="https://user-images.githubusercontent.com/45071541/151698468-d28d61ad-7d6f-417d-95aa-1f80e5288fbc.png">

**Comment by abzcoding** [comment]
if you want to run your code, you need to [install an extra plugin](https://www.lunarvim.org/plugins/01-installing.html#example), for example:
1. [sniprun](https://github.com/michaelb/sniprun)
2. [yabs.nvim](https://github.com/pianocomposer321/yabs.nvim)
3. [code_runner.nvim](https://github.com/CRAG666/code_runner.nvim)

**Comment by jiadsii** [comment]
yes , I do it as you tell me that and it works well.

**Comment by throwaway69420-69420** [comment]
I don't understand how to configure code_runner.nvim in lunarvim

**Comment by jiadsii** [comment]
https://github.com/CRAG666/code_runner.nvim

I use it , and add it to config.lua
<img width="1280" alt="截屏2022-01-31 上午12 46 58" src="https://user-images.githubusercontent.com/45071541/151708813-2f5a7179-4c05-45fd-a582-6bff74714bdc.png">

but when I use run code
<img width="1280" alt="截屏2022-01-31 上午12 50 24" src="https://user-images.githubusercontent.com/45071541/151708980-9d700c2d-1af1-469c-80bf-723a6e3a85b5.png">

it can be run

**Comment by abzcoding** [comment]
1. first off please don't use `Terminal.app`, use any other terminal emulator that you want like `iterm`, `kitty`, `alacritty`, `wezterm` ...

2. after that please remove `branch = "new_features"` from your code, and run save and reopen lunarvim
and then run `:PackerSync`

3. and in the end please fix your code first ( `unnclude` should be `#include` ) and then use `:RunCode`

**Comment by jiadsii** [comment]
I do this and it also do not work
I use iterm and just use one of it. and it also do not work.
<img width="1280" alt="截屏2022-01-31 下午4 44 14" src="https://user-images.githubusercontent.com/45071541/151763247-32389e98-bade-40c1-855e-3c63a94eb7c1.png">
<img width="1280" alt="截屏2022-01-31 下午4 45 40" src="https://user-images.githubusercontent.com/45071541/151763436-98111f19-8886-4265-ae8c-b019b9580944.png">

**Comment by abzcoding** [comment]
@jiadsii to use code_runner.nvim you need to do a couple of other steps
like adding this to your config.lua
<img width="380" alt="Screen Shot 2022-01-31 at 12 26 35 PM" src="https://user-images.githubusercontent.com/10992695/151764934-61b680e9-c3cb-4448-a473-7998322956d5.png">
and also doing this for every filetype
<img width="698" alt="Screen Shot 2022-01-31 at 12 27 24 PM" src="https://user-images.githubusercontent.com/10992695/151765042-44e7fc9d-80ec-4c55-a69c-e30e8092e787.png">

which is a bit much 😅 

so you can use [SnipRun](https://github.com/michaelb/sniprun/blob/master/README.md) instead
add this to your config.lua
```lua
lvim.plugins = {
    { "michaelb/sniprun", run = "bash ./install.sh" },
}
```
and select the part that you want to run and use `:SnipRun` to run it

![](https://github.com/michaelb/sniprun/raw/master/ressources/visual_assets/demo_c.gif)


i did test it locally and it worked fine
<img width="481" alt="Screen Shot 2022-01-31 at 12 30 33 PM" src="https://user-images.githubusercontent.com/10992695/151765497-05a2122b-3e1b-486e-9952-f409d5409483.png">


if you want a more comprehensive make and build system you can use [asynctasks.vim](https://github.com/skywind3000/asynctasks.vim) but it does require a bit of configuration

**Comment by jiadsii** [comment]
when i do this :RunCode apear ,but it run wrongly.
<img width="1280" alt="截屏2022-01-31 下午5 04 41" src="https://user-images.githubusercontent.com/45071541/151765993-43e91836-7bf4-4a1f-876e-9176b6824dfa.png">
<img width="1280" alt="截屏2022-01-31 下午5 05 57" src="https://user-images.githubusercontent.com/45071541/151766135-77bd242b-1bbd-436f-a3fa-4d0a3b44a7fa.png">

**Comment by abzcoding** [comment]
@jiadsii you can ask in their repo, but it seems to be related to [this](https://github.com/CRAG666/code_runner.nvim/issues/14)

**Comment by abzcoding** [comment]
these does not exist in your system
<img width="417" alt="Screen Shot 2022-01-31 at 12 38 43 PM" src="https://user-images.githubusercontent.com/10992695/151766595-1df88e7d-61b1-4a2b-b768-38bbc4fac30d.png">

**Comment by jiadsii** [comment]
<img width="1280" alt="截屏2022-01-31 下午6 13 00" src="https://user-images.githubusercontent.com/45071541/151775399-37bc08f4-1c8f-4335-9d0a-04ae0efffdd8.png">
I do this and it  work well
<img width="1280" alt="截屏2022-01-31 下午6 14 45" src="https://user-images.githubusercontent.com/45071541/151775647-d5bb53c1-d44c-432c-bbb1-587bc36823fe.png">

**Comment by throwaway69420-69420** [comment]
@jiadsii what did you write in projects.json?

**Comment by jiadsii** [comment]
@abzcoding 
projects.json,
run code_json,

can you write more in these, I hope this can help another people who need the code-run plugs

@throwaway69420-69420  I do not write more in the project json.

**Comment by throwaway69420-69420** [comment]
you mean project json is completely empty? @jiadsii

**Comment by jiadsii** [comment]
yes , I do not know how to write it so it can work

**Comment by throwaway69420-69420** [comment]
thanks for the help @jiadsii

**Comment by abzcoding** [comment]
@jiadsii here are some samples if you need still need them

projects.json ->
```json
{
    "~/github/TeamProject2022_28/ARMS": {
        "name": "ARMS"
        "description": "Project with MVN file",
        "command": "mvn test"
    }
}
```


and code_runner.json ->
```json
{
    "javascript": "node",
    "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
    "kotlin": "cd $dir && kotlinc-native $fileName -o $fileNameWithoutExt && ./$fileNameWithoutExt.kexe",
    "c": "cd $dir && gcc $fileName -o $fileNameWithoutExt && ./$fileNameWithoutExt",
    "cpp": "cd $dir && g++ $fileName -o $fileNameWithoutExt && ./$fileNameWithoutExt",
    "python": "python -u",
    "shellscript": "bash",
    "csharp": "cd $dir && mcs $fileName && mono $fileNameWithoutExt.exe",
    "typescript": "deno run",
    "rust": "cd $dir && rustc $fileName && $dir$fileNameWithoutExt",
    "dart": "dart"
}
```
