### ISSUE TITLE
:DI can not be used

### ISSUE THREAD

**Issue by jiadsii** [LunarVim/LunarVim#2228]
### Feature Description

I use :DIInstall in the lunarVim but it cannot be work
<img width="1280" alt="截屏2022-01-30 下午8 03 08" src="https://user-images.githubusercontent.com/45071541/151698786-f3301333-68e1-4dc4-b8ec-07902cef7a88.png">

**Comment by abzcoding** [comment]
if you want to use debugging
you need to enable debugging in lunarvim by adding this to your `~/.config/lvim/config.lua`:
```lua
lvim.builtin.dap.active = true
```
and then save it ( you might need to reopen lunarvim)
and then you can follow [this guide](https://www.lunarvim.org/plugins/02-default-plugins.html#debugging)

**Comment by abzcoding** [comment]
also, I would recommend joining the [lunarvim discord](https://discord.gg/Xb9B4Ny), in case you had more questions

**Comment by jiadsii** [comment]
yes , I do it as you tell me ,and it works

**Comment by endlesscpp** [comment]
> yes , I do it as you tell me ,and it works
Hi, I'm using nvim 0.7.0.
I have set 
lvim.builtin.dap.active = true
in ~/.config/lvim/config.lua, and the DAPInstall and nvim-dap plugin are installed.

However, there still no :DIInstall command.
