### ISSUE TITLE
Replace `vuels` with volar

### ISSUE THREAD

**Issue by Suyashtnt** [LunarVim/LunarVim#2229]
### Problem description

vuels (vetur) is slowly being replaced by volar, which is by far better. Evan You suggests using it (https://twitter.com/youyuxi/status/1458004347854356484). Instead of using vuels as the default vue lsp it should be volar

### LunarVim version

2FA176F

### Neovim version (>= 0.6.1)

NVIM v0.6.1 Build type: Release LuaJIT 2.0.5 Compiled by builduser

### Operating system/version

Arch running in WSL2

### Affected language servers

vuels, volar

### Steps to reproduce

1. Open vue SFC
2. Observe vuels being used

### Actual behavior

It uses vuels

### Expected behavior

It to be using volar

### log and support info

```shell
Shouldnt be needed:tm:
```

**Comment by abzcoding** [comment]
sounds good to me 👍
