### ISSUE TITLE
Wich Key text not wanted

### ISSUE THREAD

**Issue by PabloMartinMoreno** [LunarVim/LunarVim#2231]
### Problem description

When I add the Easy Motion plugin, it automatically adds a function when I press <space> that does nothing. How can I remove it?
![pic-full-220130-1035-14](https://user-images.githubusercontent.com/44477540/151702260-5e0c36d2-bf30-42df-874c-cd42caeb3573.png)

### LunarVim version

Last

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Artix Linux

### Relevant log output

```shell
Nothing
```

**Comment by abzcoding** [comment]
as mentioned in [documentation](https://www.lunarvim.org/configuration/02-keybindings.html#whichkey-bindings)
instead of that `vim.cmd`
use this syntax for keybindings that start with `<leader>`
```lua
lvim.builtin.which_key.mappings["l"] = {
  "<Plug>(easymotion-bd-jk)<cr>", "some description"
}
```
or add this to your `config.lua` to not show any leader keybinding without description
```lua
lvim.builtin.which_key.setup.ignore_missing = true
```

**Comment by PabloMartinMoreno** [comment]
> 

I have tried deleting all the rules and restarting vim and the problem still appears. I had already read the documentation but I have a hard time understanding it.
![pic-full-220130-1332-22](https://user-images.githubusercontent.com/44477540/151708229-b1cf493f-bb0d-45c6-9445-18d1961d7399.png)

**Comment by rebuilt** [comment]
This is from the documentation of easymotion: 

```The default leader has been changed to <Leader><Leader> to avoid conflicts with other plugins you may have installed. This can easily be changed back to pre-1.3 behavior by rebinding the leader in your vimrc:

map <Leader> <Plug>(easymotion-prefix)
All motions will then be triggered with <Leader> by default, e.g. <Leader>s, <Leader>gE.
```

What does your easymotion configuration look like?  

From the easymotion readme, I would expect `<leader><leader>` to do nothing by default, but `<leader><leader>s` to trigger the plugin

**Comment by abzcoding** [comment]
> I have tried deleting all the rules and restarting vim and the problem still appears. I had already read the documentation but I have a hard time understanding it.

did you add this to your config by any chance?
```lua
lvim.builtin.which_key.setup.ignore_missing = true
```

**Comment by PabloMartinMoreno** [comment]
> > I have tried deleting all the rules and restarting vim and the problem still appears. I had already read the documentation but I have a hard time understanding it.
> 
> did you add this to your config by any chance?
> 
> ```lua
> lvim.builtin.which_key.setup.ignore_missing = true
> ```

That works but other keyboard shortcuts that are configured with lvim stop working

**Comment by PabloMartinMoreno** [comment]
> 

At the end change map <Leader> for <\> and it stays like this map <\> <Plug>(easymotion-prefix). With that I reach for the annoying text to go away. Thank you.
