### ISSUE TITLE
Cannot override formatoptions

### ISSUE THREAD

**Issue by mandreyel** [LunarVim/LunarVim#2232]
### Problem description

Setting the following in my ~/.config/lvim/config.lua has no effect:
```lua
lvim.user_autocommands = {
  { "BufWinEnter,BufRead,BufNewFile", "*", [[
set formatoptions="" " Reset formatoptions.
set formatoptions+=j " Remove comment leader when joining comment lines.
set formatoptions+=c " Auto format text in plaintext files, or comments in source files.
set formatoptions+=r " Auto insert comment leader after hitting <Enter>.
set formatoptions+=o " Auto insert comment leader when hitting 'o' or 'O' in normal mode.
set formatoptions+=q " Allow formatting of comments with 'gq'.
set formatoptions+=l " Don't break long lines in insert mode.
set formatoptions+=1 " Break line before a single-letter word.
set formatoptions+=n " Recognize numbered lists.
set formatoptions+=2 " Indent paragraph based on the second line rather than the first.
  ]] }
}
```

I dug around in the source and it seems lvim [overrides `fo`](https://github.com/LunarVim/LunarVim/blob/df814d5a84501b8d064ddc5e00d903ad3d02f8d8/lua/lvim/core/autocmds.lua#L30-L35) on every buffer enter. I wonder why that is.

Is there another way to override `fo`? I find this to be a major issue because the default `fo` settings make writing inline code comments and documentation very painful.

I tried searching around existing issues and discussions and to my surprise no one has raised this problem. The only mention of `fo` I found was [in this issue](https://github.com/LunarVim/LunarVim/issues/900) where it was suggested that the user autocommand overriding was fixed in rolling, but this appears not to be the case.

### LunarVim version

36f2322

### Neovim version (>= 0.6.1)

Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include Compiled by runner@fv-az87-780  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: " /home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

### Operating system/version

Linux p5540 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Relevant log output

```shell
nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date
```

**Comment by abzcoding** [comment]
you can just override them or any other settings in lunarvim
```lua
lvim.autocommands._formatoptions = {}
```

**Comment by abzcoding** [comment]
and you can use this syntax to add your own custom autocommands
```lua
lvim.autocommands.custom_groups = {
      {
        "BufWinEnter,BufRead,BufNewFile",
        "*", -- or any filetype for example *.md
        "setlocal formatoptions-=c formatoptions-=r formatoptions-=o",
      },
}
```

**Comment by abzcoding** [comment]
or you can use the neovim style, like i do by adding this to your `~/.config/lvim/config.lua`
```lua
vim.opt.formatoptions = {
    ["1"] = true,
    ["2"] = true, -- Use indent from 2nd line of a paragraph
    q = true, -- continue comments with gq"
    c = true, -- Auto-wrap comments using textwidth
    r = true, -- Continue comments when pressing Enter
    n = true, -- Recognize numbered lists
    t = false, -- autowrap lines using text width value
    j = true, -- remove a comment leader when joining lines.
    -- Only break if the line was not longer than 'textwidth' when the insert
    -- started and only at a white character that has been entered during the
    -- current insert command.
    l = true,
    v = true,
  }
```

**Comment by mandreyel** [comment]
Thank you for the super quick answer @abzcoding.

I actually already tried both `lvim.autocommands.custom_groups` and `vim.opt.formatoptions` before but neithert worked. I tried them again now and still no luck.

I tried now overriding the default autocommand for `fo` and that causes `echo &fo` not to output anything at all (as though the settings were not set at all).

I'm using a mostly default LV, and I tried with a completely barebones installation as well, both with the same outcome. Any idea?

**Comment by abzcoding** [comment]
can you try running `:LvimCacheReset` to make sure nothing is cached?

**Comment by abzcoding** [comment]
here is what i have
<img width="683" alt="Screen Shot 2022-01-30 at 11 51 35 PM" src="https://user-images.githubusercontent.com/10992695/151716259-494fe5b9-6a6a-4c1a-8204-7fb65f901ae4.png">
and what `echo &fo` outputs
<img width="96" alt="Screen Shot 2022-01-30 at 11 51 10 PM" src="https://user-images.githubusercontent.com/10992695/151716251-b70bf38a-2fa3-4dd4-baf7-0fb68507805c.png">

**Comment by mandreyel** [comment]
That actually worked! Thank you so much.
