### ISSUE TITLE
Tabline doesn't restored after loading of saved session

### ISSUE THREAD

**Issue by borisxm** [LunarVim/LunarVim#2234]
### Problem description

When session restored using `SessionLoad` command from the Dashboard screen, the value of `showtabline` option aren't restored which results in an absent tabline. Manual command `set showtabline=2` restores it.

How to repeat:

* open two or more files;
* save session using command `:SessionSave test`;
* quit LunarVim;
* launch it again;
* type `:SessionLoad test`, observe missing tabline.

Simple, but incorrect fix is to not hide tabline at all:
```diff
diff --git a/lua/lvim/core/dashboard.lua b/lua/lvim/core/dashboard.lua
index 438b46f..dbf8d2f 100644
--- a/lua/lvim/core/dashboard.lua
+++ b/lua/lvim/core/dashboard.lua
@@ -101,7 +101,7 @@ M.setup = function()
       {
         "FileType",
         "dashboard",
-        "set showtabline=0 | autocmd BufLeave <buffer> set showtabline=" .. vim.opt.showtabline._value,
+        "set showtabline=2 | autocmd BufLeave <buffer> set showtabline=" .. vim.opt.showtabline._value,
       },
       { "FileType", "dashboard", "nnoremap <silent> <buffer> q :q<CR>" },
     },
```

In the other usage cases, tabline works as expected.

### LunarVim version

Latest

### Neovim version (>= 0.6.1)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by team+vim@tracker.debian.org

### Operating system/version

Ubuntu 20.04.3 LTS

### Relevant log output

```shell
none
```

**Comment by abzcoding** [comment]
i didn't mean `we won't fix it forever`, rather `low priority bug` 😅

**Comment by borisxm** [comment]
Well, "wontfix" is won't fix. Workaround is simple, just slightly degrades aesthetics, so I don't care much.

**Comment by abzcoding** [comment]
> Well, "wontfix" is won't fix. Workaround is simple, just slightly degrades aesthetics, so I don't care much.

there happy now 😅

**Comment by rebuilt** [comment]
Does `:redraw` or `:redraw!`  make it appear again?   

Does `CTRL-L` make it appear?

**Comment by borisxm** [comment]
No, none of the above commands make tabline to appear. The only found way to restore it, is to type `:set showtabline=2`.

**Comment by abzcoding** [comment]
we are migrating from dashboard.nvim to alpha.nvim -> https://github.com/LunarVim/LunarVim/pull/1906
@kylo252 can we fix this in the process as well?

**Comment by kylo252** [comment]
> we are migrating from dashboard.nvim to alpha.nvim -> #1906 @kylo252 can we fix this in the process as well?

Alpha does not have any session management. My custom session-manager works, but it's intentionally minimal since I didn't want to bother with adding auto-save or auto-reload. A more featured alternative would be https://github.com/Shatur/neovim-session-manager.

**Comment by kylo252** [comment]
Works correctly since the switch to bufferline.nvim.
