### ISSUE TITLE
installation lunar vim error for tree-sitter-cli on raspberrypi

### ISSUE THREAD

**Issue by slinky07** [LunarVim/LunarVim#2235]
### Problem description

when i install lunarvim on my rpi 4B+ I get an error saying installation failed. relevant log output below. Tried lastest stable which Is 1.0 i think.  any way I can get around this for my rpi? 

### LunarVim version

1.0

### Neovim version (>= 0.6.1)

0.7.0

### Operating system/version

Raspbian 10 buster on armv7l Linux 5.10.63-v7l+

### Relevant log output

```shell
npm ERR! code 1
npm ERR! path /home/pi/.npm-global/lib/node_modules/tree-sitter-cli
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Cannot install tree-sitter-cli for platform linux, architecture arm

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-02-02T00_21_14_059Z-debug.log
```

### Screenshots

<img width="935" alt="Screen Shot 2022-02-01 at 7 31 29 PM" src="https://user-images.githubusercontent.com/36781256/152074200-5f1c4684-044b-42dd-8b95-d4ca2143eb08.png">

**Comment by abzcoding** [comment]
you can say no to that and install tree-sitter manually
check [their repo](https://github.com/tree-sitter/tree-sitter/blob/master/cli/README.md) for more info
