### ISSUE TITLE
Make the Notifications get back to defaults nvim 0.5.1

### ISSUE THREAD

**Issue by BlueDruddigon** [LunarVim/LunarVim#2242]
### Feature Description

Hello, I've using lvim 0.5 and 0.6. When upgrading from 0.5 to 0.6, I have noticed that the notifications have changed from bottom to floated top right of the screen. It seems to be slow motion and I don't want that new stuff. So how can I turn the notifications back to the original like the previous version!

### Describe the alternatives you have considered

Could you please make an option to choose which style of notification that users prefer?
Something like ```lvim.notify.style = default|modern``` maybe ?
Hope for your reply soon.

**Comment by BlueDruddigon** [comment]
Hmm. It seems to be caused by ```nvim-notify``` plugin.
Better to disable it!

**Comment by abzcoding** [comment]
yes you can disable it if you want
```lua
lvim.builtin.notify.active = false
```
