### ISSUE TITLE
Set tabstop and shiftwidth in c/c++ is buggy

### ISSUE THREAD

**Issue by YaQia** [LunarVim/LunarVim#2244]
### Problem description

1. set `vim.opt.shiftwidth = 4` and `vim.opt.tabstop  = 4` first
2. create or open a c/cpp file
3. type in `if()` or `while()` and type enter
4. type `{`, you'll see the tab will be presented like this:
```c
if()
    {

}
```
After you type enter, once you delete the tab which is automatically generated, you'll see something like this:
```c
while()
{

    }
```
in nvim, these sentences are correct in the same procedure if you have you configuration properly:
```vim
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
```
BTW, if `tabstop=2` and `shiftwidth=2` are set, the identation can run properly.

### LunarVim version

2fa176f

### Neovim version (>= 0.6.1)

NVIM v0.7.0-dev+963-g082ff2190

### Operating system/version

Ubuntu20.04

### Relevant log output

```shell
## Parser/Features H L F I J
  - cpp            √ √ √ √ √
  - c              √ √ √ √ √
  
  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
```

### Screenshots

![2022-02-03 23-09-51 的屏幕截图](https://user-images.githubusercontent.com/61108050/152370159-e019b18e-ab4b-47e6-a4db-87262e2600a3.png)

**Comment by YaQia** [comment]
BTW, the indentation is wrong in the first pair in a function, all other identation levels work properly.

**Comment by abzcoding** [comment]
can you try disabling the treesitter backed indentations for it?
```lua
lvim.builtin.treesitter.indent = { enable = true, disable = { "c", "cpp" } }
```
other than that maybe you can look into `formatoptions`
```vim
:help 'formatoptions'
```

cc: @kylo252

**Comment by YaQia** [comment]
Thanks a lot! The first instruction works well! I've never check for the treesitter and thought that the indentation is only relavent to nvim's settings.

**Comment by jonatas-moraes** [comment]
> Thanks a lot! The first instruction works well! I've never check for the treesitter and thought that the indentation is only relavent to nvim's settings.

@YaQia in which file did you insert the instruction? I have the same issue.

**Comment by kylo252** [comment]
> @YaQia in which file did you insert the instruction? I have the same issue.

just add this to your `config.lua`

```lua
lvim.builtin.treesitter.indent = { enable = true, disable = { "c", "cpp" } }
```
