### ISSUE TITLE
Java formatting through jdtls is different than other programs using the same language server

### ISSUE THREAD

**Issue by obj-obj** [LunarVim/LunarVim#2245]
### Problem description

LunarVim's formatting for java files is different that vscode or the spotless gradle plugin, causing different tools to fight with each other. Not sure why this is, because all the tools are using jdtls

### LunarVim version

Rolling (commit 41b3f63)

### Neovim version (>= 0.6.1)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser

### Operating system/version

Arch Linux

### Affected language servers

jdtls

### Actual behavior

LunarVim formats differently than vanilla jdtls

### Expected behavior

LunarVim formats the same as vscode/spotless

### log and support info

```shell
Language client log: /home/*user*/.cache/nvim/lsp.log
 Detected filetype:   java
 
 1 client(s) attached to this buffer: 
 
 Client: jdtls (id: 1, pid: 343491, bufnr: [16, 4])
 	filetypes:       java
 	autostart:       true
 	root directory:  /home/*user*/Documents/code/RapidReact2022
 	cmd:             /usr/lib/jvm/java-17-openjdk/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dlog.protocol=true -Dlog.level=ALL -Xms1g -Xmx2G -javaagent:/home/*user*/.local/share/nvim/lsp_servers/jdtls/lombok.jar --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -jar /home/*user*/.local/share/nvim/lsp_servers/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -configuration /home/*user*/.local/share/nvim/lsp_servers/jdtls/config_linux -data /home/*user*/workspace/RapidReact2022
 
 Configured servers list: jdtls
```

**Comment by abzcoding** [comment]
can you elaborate a bit more? like 
- is the difference in the number of spaces ( 2 instead of 4) 
- is it tabs instead of spaces
- is the style completely different
- something else?

p.s: screenshot or a diff would be appreciated

**Comment by obj-obj** [comment]
Yeah a diff would be useful lol, should have attached one

**Comment by obj-obj** [comment]
> can you elaborate a bit more? like
> 
>     * is the difference in the number of spaces ( 2 instead of 4)
> 
>     * is it tabs instead of spaces
> 
>     * is the style completely different
> 
>     * something else?
> 
> 
> p.s: screenshot or a diff would be appreciated

@abzcoding looking it at it more the issue seems to be very specific: 8 spaces rather than 4 on doc comment newlines\

Before:
```java
    /**
     * Constructor for shooter subsystem.
     * 
     * @param flywheelMotor1
     *            The first motor connected to the flywheel
     * 
     * @param flywheelMotor2
     *            The second motor connected to the flywheel
     * 
     * @param turretMotor
     *            The motor that controls the horizontal rotation of the
     *            turret
     * 
     * @param hoodMotor
     *            The motor that controls the angle of the hood above the
     *            turret
     * 
     */
```

After:
```java
    /**
     * Constructor for shooter subsystem.
     * 
     * @param flywheelMotor1
     *                       The first motor connected to the flywheel
     * 
     * @param flywheelMotor2
     *                       The second motor connected to the flywheel
     * 
     * @param turretMotor
     *                       The motor that controls the horizontal rotation of the
     *                       turret
     * 
     * @param hoodMotor
     *                       The motor that controls the angle of the hood above the
     *                       turret
     * 
     */
```

Not quite a diff but I don't know how to put embedded diffs in github comments (if you even can?)

**Comment by abzcoding** [comment]
basically, VSCode uses a different formatting profile than the default one in `jdtls`
this is how you can change that, 
1. create a profile inside your lvim, [here is mine](https://github.com/abzcoding/lvim/blob/main/.java-google-formatter.xml)
2. create a file called `~/.config/lvim/ftplugin/java.lua` and change profile inside it, [here is how](https://github.com/abzcoding/lvim/blob/main/ftplugin/java.lua)
especially this part
```lua
settings = {
    ["java.format.settings.url"] = vim.fn.expand "~/" .. ".config/lvim/.java-google-formatter.xml",
    ["java.format.settings.profile"] = "GoogleStyle",
  },
```

alternatively, you can also define the formatting preferences in your project's [.settings/org.eclipse.jdt.core.prefs](https://gist.github.com/fbricon/30c5971f7e492c8a74ca2b2d7a7bb966). It will override global formatting settings.

**Comment by obj-obj** [comment]
> basically, VSCode uses a different formatting profile than the default one in `jdtls` this is how you can change that,
> 
>     1. create a profile inside your lvim, [here is mine](https://github.com/abzcoding/lvim/blob/main/.java-google-formatter.xml)
> 
>     2. create a file called `~/.config/lvim/ftplugin/java.lua` and change profile inside it, [here is how](https://github.com/abzcoding/lvim/blob/main/ftplugin/java.lua)
>        especially this part
> 
> 
> ```lua
> settings = {
>     ["java.format.settings.url"] = vim.fn.expand "~/" .. ".config/lvim/.java-google-formatter.xml",
>     ["java.format.settings.profile"] = "GoogleStyle",
>   },
> ```
> 
> alternatively, you can also define the formatting preferences in your project's [.settings/org.eclipse.jdt.core.prefs](https://gist.github.com/fbricon/30c5971f7e492c8a74ca2b2d7a7bb966). It will override global formatting settings.
> 
> [more info](https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings)

Ah ok, it's vscode being bad then. I already have the xml file for spotless to use, but I assumed it was just defaults

**Comment by obj-obj** [comment]
Yep, it works :)

**Comment by obj-obj** [comment]
Nope, I just had format on save off...
@abzcoding it doesn't seem to do anything, the formatting is still incorrect. Here is my current java.lua:

```lua
local status_ok, jdtls = pcall(require, "jdtls")
if not status_ok then
  return
end

local workspace_path = os.getenv "HOME" .. "/workspace/"
local JAVA_LS_EXECUTABLE = os.getenv "HOME" .. "/.local/share/lunarvim/lvim/utils/bin/jdtls"

jdtls.start_or_attach {
  on_attach = function()
    require("jdtls.setup").add_commands()
    require("lvim.lsp").common_on_attach()
  end,
  flags = {
    allow_incremental_sync = true,
    server_side_fuzzy_completion = true,
  },
  settings = {
    ["java.format.settings.url"] = vim.fn.expand "~/" .. ".config/lvim/eclipse-formatter.xml",
    ["java.format.settings.profile"] = "Eclipse",
  },
  cmd = { JAVA_LS_EXECUTABLE, workspace_path .. vim.fn.fnamemodify(vim.fn.getcwd(), ":p:h:t") },
}
```

**Comment by abzcoding** [comment]
well as i mentioned there is nothing else that we can do about it, since we are not changing anything about jdtls
you can bring that up in their repo
as a side note make sure that `~/.config/lvim/eclipse-formatter.xml` exists and also tune it to your liking

**Comment by obj-obj** [comment]
> well as i mentioned there is nothing else that we can do about it, since we are not changing anything about jdtls you can bring that up in their repo as a side note make sure that `~/.config/lvim/eclipse-formatter.xml` exists and also tune it to your liking

Yes, the file exists and my config is in there. No idea why jdtls is formatting differently in everything else, now that they're using the same config

**Comment by obj-obj** [comment]
@abzcoding looking at it a few hours later the issue is that I literally forgot to install `nvim-jdtls`...
Thought I had it installed lmao

**Comment by abzcoding** [comment]
😢
