### ISSUE TITLE
Error while trying to installing

### ISSUE THREAD

**Issue by Ruivalim** [LunarVim/LunarVim#2251]
### Problem description

I have a Macbook M1 and when I try to install I see this error: 

E5113: Error while calling lua chunk: ....local/share/lunarvim/lvim/lua/lvim/lsp/null-ls/init.lua:13: attempt to call field 'setup' (a nil value)
stack traceback:
	....local/share/lunarvim/lvim/lua/lvim/lsp/null-ls/init.lua:13: in function 'setup'
	.../.local/share/lunarvim/lvim/lua/lvim/lsp/init.lua:149: in function 'setup'
	.../.local/share/lunarvim/lvim/init.lua:21: in main chunk

when I try to open lunar vim I see this same error.

This is the command I use to install: 
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

### LunarVim version

not installed succesfully

### Neovim version (>= 0.6.1)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compilado por brew@HMBRW-A-001-M1-001.local  Features: +acl +iconv +tui See ":help feature-compile"      arquivo vimrc de sistema: "$VIM/sysinit.vim"             padrão para $VIM: "/opt/homebrew/Cellar/neovim/0.6.1/share/nvim"  Run :checkhealth for more info

### Operating system/version

macOS 11.4 M1

### Relevant log output

```shell
Installing LunarVim shim
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: /Users/.../.local/bin/lvim
Preparing Packer setup
Error detect while processing /Users/.../.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: ....local/share/lunarvim/lvim/lua/lvim/lsp/null-ls/init.lua:13: attempt to call field 'setup' (a nil value)
stack traceback:
	....local/share/lunarvim/lvim/lua/lvim/lsp/null-ls/init.lua:13: in function 'setup'
	.../.local/share/lunarvim/lvim/lua/lvim/lsp/init.lua:149: in function 'setup'
	/Users/.../.local/share/lunarvim/lvim/init.lua:21: in main chunk
```

**Comment by abzcoding** [comment]
please uninstall and reinstall again
```shell
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/uninstall.sh)
LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)
```

**Comment by Ruivalim** [comment]
Same error

**Comment by Ruivalim** [comment]
This is the contents of `init.lua`


```lua
local M = {}

local Log = require "lvim.core.log"

function M:setup()
  local status_ok, null_ls = pcall(require, "null-ls")
  if not status_ok then
    Log:error "Missing null-ls dependency"
    return
  end

  local default_opts = require("lvim.lsp").get_common_opts()
  null_ls.setup(vim.tbl_deep_extend("force", default_opts, lvim.lsp.null_ls.setup))
end

return M
```

**Comment by Ruivalim** [comment]
After running `rm -rf ~/.local/share/lunarvim` it was installed successfully, I think there's an issue with the uninstall script.
