### ISSUE TITLE
How to run the current script in lunarvim? 

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#2255]
### Problem description

I want to run the current code I am editing. Does lunarvim has a build-in command for this? like run python js etc. 

### LunarVim version

7125e2b

### Neovim version (>= 0.6.1)

0.6.0

### Operating system/version

manjaro 21

### Relevant log output

```shell
...
```

**Comment by abzcoding** [comment]
I would suggest using an external plugin like [SnipRun](https://github.com/michaelb/sniprun)

we don't have anything extra on top of neovim for this
