### ISSUE TITLE
Update for plugins master branch

### ISSUE THREAD

**Issue by BlueDruddigon** [LunarVim/LunarVim#2257]
### Feature Description

Hi. I've read the lvim config for plugins and realized that LunarVim fixed the commits for all default plugins.
So how do I change it to master(latest version) of a specific plugin such as ```nvim-tree.lua```?

### Describe the alternatives you have considered

I suppose a solution like changing the default plugin's commit option in config.lua file, something like 
```lvim.builtin.nvimtree.commit = "master"```. So that I could update for the latest version of that plugin.

Thanks.

**Comment by Uzaaft** [comment]
I don't have a solution for the issue, but consider this:
Let's say that one of the core plugins, for.eks nvimtree has a breaking changing. If updated with this breaking change, this will cause issues with lvim, and this has happened earlier before he locked down the commits of each plugin.

**Comment by abzcoding** [comment]
as the old saying goes "this is a feature not a bug"

basically, we did this to make sure breaking changes doesn't find their way into our code
if you want to stay current, use the `rolling` branch, worst case scenario you would get the updates within 72 hours

**Comment by abzcoding** [comment]
as you can see in PRs, i'm constantly keeping the plugins up to date, while make sure nothing in core breaks because of them
<img width="1327" alt="Screen Shot 2022-02-08 at 9 48 16 PM" src="https://user-images.githubusercontent.com/10992695/153050782-41cbd52e-9986-4ae3-9d6f-7d8346455574.png">
