### ISSUE TITLE
Windows "~/.config/lvim/config.lua" location

### ISSUE THREAD

**Issue by omar2205** [LunarVim/LunarVim#2259]
### Problem description

Where do I save `~/.config/lvim/config.lua` in Windows?

### LunarVim version

24537be03e3b7668e565fc652f8a0bfdea715652

### Neovim version (>= 0.6.1)

v0.6.1

### Operating system/version

Windows 11

### Relevant log output

```shell
N/A
```

**Comment by abzcoding** [comment]
`C:\Users\<USERNAME>\AppData\Local\lvim\config.lua`

check https://github.com/LunarVim/LunarVim/blob/rolling/utils/installer/install.ps1 for more info

**Comment by alexxbb** [comment]
Thanks @abzcoding This should be in the documentation.
