### ISSUE TITLE
LunarVim dashboard crashes after opening it with space+; on a project

### ISSUE THREAD

**Issue by brunobmello25** [LunarVim/LunarVim#2263]
### Problem description

Steps to reproduce:

1. Install neovim 0.6.1
2. Install latest LunarVim
3. Open a project (could be any language from what I could tell)
4. search for a file with telescope (with <space+f>) and open it
5. Open dashboard with <space+;>
6. see the error like below:

![image](https://user-images.githubusercontent.com/29875060/153423478-92db4f97-cd6b-4d58-b558-9df879d34149.png)

### LunarVim version

2fa176f

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Pop!_OS 20.04

### Relevant log output

```shell
The full output of the LvimVersion is shown in the screenshots section bellow
```

### Screenshots

![image](https://user-images.githubusercontent.com/29875060/153925441-49b2039f-6e92-4150-9b1a-18b1ab1a100b.png)

**Comment by abzcoding** [comment]
@kylo252 I think it's time to merge rolling into master

**Comment by kylo252** [comment]
> @kylo252 I think it's time to merge rolling into master

Semi related, we can't update nvim-tree since it's broken for me on HEAD, but we'll cross that bridge when we get to it 😅  

Maybe it's time to finish up Alpha's PR already?
