### ISSUE TITLE
The buffer that appears in peek window would get closed when cycling to another buffer

### ISSUE THREAD

**Issue by aik2mlj** [LunarVim/LunarVim#2278]
### Problem description

1. Open 2 buffers, namely A & B;
2. In buffer A, move cursor to a function head (e.g. in a python file);
2. Press `gp` to peek definition (notice that the peek window also displays contents in buffer A);
3. Move around to let the peek window disappear;
3. Cycle to buffer B by `:BufferLineCycleNext` (or whatever shortcut);
4. Buffer A is gone!

Why is that? Is it related to the way `bufferline.nvim` works?

### LunarVim version

e8e8e8b

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Garuda Linux

### Relevant log output

```shell
Sorry but I didn't get any useful log output when executing these commands. Please tell me how if necessary!
```

**Comment by abzcoding** [comment]
you can get back using `<ctrl-o>`, not sure about the bufferline behavior though, you can probably find another shortcut that behaves differently

**Comment by aik2mlj** [comment]
Ok really sorry I just updated lunarvim and everything works fine... Thanks for your patience.
