### ISSUE TITLE
Various themes for the main UIs

### ISSUE THREAD

**Issue by premell** [LunarVim/LunarVim#2286]
Recently I tried nvchad, and while I prefer lunarvims configuration and defaults, I found their UI to be really beatiful. These are some examples from nvchad: 

This is their theme for telescope: 
![image](https://user-images.githubusercontent.com/65544203/154215161-70e3e0c6-c87b-4a4a-9301-bd22538c7fb6.png)

This is their window for showing keymappings
![image](https://user-images.githubusercontent.com/65544203/154215263-8a04bc75-ea25-465c-ad1f-601b1e65e20a.png)

I think it would be really cool to have a few different themes for some plugins, like telescope, which you could choose from your config like "lvim.builtin... telescope.themes = 'gravity'" or something like that. Right now I feel like the structure of lunarvim is great, and the defaults are awesome. However there is not that much builtin support for customizing the look

**Comment by abzcoding** [comment]
I agree with you, and I like your idea 👍 I'll work on this in a week or so.

**Comment by abzcoding** [comment]
testing it on [my own config](https://github.com/abzcoding/lvim)

kanagawa:
<img width="1752" alt="Screen Shot 2022-02-17 at 12 33 20 AM" src="https://user-images.githubusercontent.com/10992695/154356707-aa206af5-de28-4d8d-9c29-e2208b42b972.png">


catppuccin:
<img width="1751" alt="Screen Shot 2022-02-17 at 12 37 39 AM" src="https://user-images.githubusercontent.com/10992695/154357253-e3550ef3-ee74-4bb8-876f-0d87c8bb69bc.png">

tokyonight:
<img width="1742" alt="Screen Shot 2022-02-17 at 12 38 51 AM" src="https://user-images.githubusercontent.com/10992695/154357439-63c1721e-0c82-4515-b8cf-a41ef56c99a8.png">

rose-pine:
<img width="1711" alt="Screen Shot 2022-02-17 at 12 40 42 AM" src="https://user-images.githubusercontent.com/10992695/154357706-a4c2ae7a-cfd5-47a2-a050-7d64e245fcfb.png">


what do you think?

**Comment by abzcoding** [comment]
this would be an alternative look ( prompt being a different color)

<img width="1785" alt="Screen Shot 2022-02-17 at 1 06 46 AM" src="https://user-images.githubusercontent.com/10992695/154361278-92410d66-b96d-4803-97d0-b52484bf7cc4.png">


would this be better?

**Comment by abzcoding** [comment]
we can hide `Results` title as well
<img width="1760" alt="Screen Shot 2022-02-17 at 1 27 12 PM" src="https://user-images.githubusercontent.com/10992695/154451453-225ea46d-7c2c-48d0-9ca6-d7b59d295bb2.png">

**Comment by israelss** [comment]
> this would be an alternative look ( prompt being a different color)
> 
This looks awesome! One question: will this work automatically for any theme?

**Comment by abzcoding** [comment]
> > this would be an alternative look ( prompt being a different color)
> 
> This looks awesome! One question: will this work automatically for any theme?

🤞 yes, that is what i'm trying to achieve, though i've not figured it out completely yet

**Comment by premell** [comment]
Dude great work and amazing how fast you've started working on this!

I am not that artistic, so it would be great to have more input on this issue. Anyway here are some quick thoughts: 

- I am not sure about the transparency, it risks getting a bit noisy. 
- Maybe adding some padding, especially around the prompt. 
- I also think it looks best without the lighter color around the prompt and without the result label.
- Having a ratio of 6/10 or 2/3 between the search area and preview area would also be more functional, as you often need more space to preview a file than a path

I am also quite uncertain how to handle the labels. I really like their color, but I dislike their form. Their hard corners make it look like they don't quite belong and their strong color makes it hard not to notice. Maybe it would look better if one made their corners more rounded? In that case maybe we could make the corners rounded on all corners? Although I really like the squared look. Or maybe we could use big rounded icons and not use text at all? 

I like that you have the search prompt on the bottom, as it makes it easier to see and use. However that kind of amplifies the problem with the labels as they become unsymmetrical and stick out even more.

Another thing I was thinking of is if we should have some sort of divider between the search area and the results. On the one hand it looks really clean with it being the same color, but I am wondering if it can become distracting. Although I cant really think of any good ways of improving it. 

These are just some random thoughts I had while seeing the themes. I think its likely that a majority of my suggestions are bad, and that even I would prefer your current design to my hypothetical changes. However I think its good to just spew ideas and see whats sticks.

Anyway I think you did a great job and I think its several times better than the default theme. 

Also if we succeed in making the themes encapsulated, we can easily accept PRs with different looks.

**Comment by abzcoding** [comment]
@premell, thanks so much for your wonderful suggestions, sadly I'm unavailable for a couple of days ( relocating to a new city/apartment ), but I'll try to incorporate your suggestions into the design as well

**Comment by abzcoding** [comment]
ok what do you think about this?
<img width="1563" alt="Screen Shot 2022-02-18 at 1 46 23 AM" src="https://user-images.githubusercontent.com/10992695/154580152-2177d79f-4b6a-4b48-9860-4d140f26db79.png">


Also, to round the corners, we have to use custom glyphs ( because I'm basically setting `guibg`, which is gonna  look like a square)

**Comment by abzcoding** [comment]
sadly padding is not configurable yet
<img width="1327" alt="padding" src="https://user-images.githubusercontent.com/10992695/154860580-7709892a-8911-4cda-816b-c4fff14282ba.png">


also here is a full screenshot to compare border and no-border
<img width="1680" alt="border" src="https://user-images.githubusercontent.com/10992695/154860605-5d3523df-6e46-4587-9339-9cfe58e55eda.png">
<img width="1680" alt="no-border" src="https://user-images.githubusercontent.com/10992695/154860761-2582f0b5-d5eb-4146-9b63-2f1414f81edf.png">

**Comment by premell** [comment]
I think I prefer with border actually, but not sure, they are almost equally good imo. great work!

**Comment by abzcoding** [comment]
ok guys i need some testers
to make sure if this works with different colorschemes or not

1. add this to your `~/.config/lvim/config.lua`
```lua
-- ~/.config/lvim/config.lua
lvim.builtin.telescope.defaults.prompt_prefix = "  "
lvim.builtin.telescope.defaults.borderchars = {
      prompt = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
      results = { "─", "▐", "─", "│", "╭", "▐", "▐", "╰" },
      preview = { " ", "│", " ", "▌", "▌", "╮", "╯", "▌" },
}
lvim.builtin.telescope.defaults.selection_caret = "  "
```


2. create a file called `~/.config/lvim/after/plugin/highlights.vim`
```vim
" ~/.config/lvim/after/plugin/highlights.vim
lua require('user.theme').telescope_theme()
```


3. then create a file called `~/.config/lvim/lua/user/theme.lua`
```lua
-- ~/.config/lvim/lua/user/theme.lua
local M = {}

M.hi_colors = function()
  local colors = {
    bg = "#16161D",
    bg_alt = "#1F1F28",
    fg = "#DCD7BA",
    green = "#76946A",
    red = "#E46876",
  }
  local color_binds = {
    bg = { group = "NormalFloat", property = "background" },
    bg_alt = { group = "Cursor", property = "foreground" },
    fg = { group = "Cursor", property = "background" },
    green = { group = "diffAdded", property = "foreground" },
    red = { group = "diffRemoved", property = "foreground" },
  }
  local function get_hl_by_name(name)
    local ret = vim.api.nvim_get_hl_by_name(name.group, true)
    return string.format("#%06x", ret[name.property])
  end
  for k, v in pairs(color_binds) do
    local found, color = pcall(get_hl_by_name, v)
    if found then
      colors[k] = color
    end
  end
  return colors
end

M.telescope_theme = function()
  local function set_bg(group, bg)
    vim.cmd("hi " .. group .. " guibg=" .. bg)
  end

  local function set_fg_bg(group, fg, bg)
    vim.cmd("hi " .. group .. " guifg=" .. fg .. " guibg=" .. bg)
  end

  local colors = M.hi_colors()
  set_fg_bg("TelescopeBorder", colors.bg_alt, colors.bg)
  set_fg_bg("TelescopePromptBorder", colors.bg, colors.bg)
  set_fg_bg("TelescopePromptNormal", colors.fg, colors.bg_alt)
  set_fg_bg("TelescopePromptPrefix", colors.red, colors.bg)
  set_bg("TelescopeNormal", colors.bg)
  set_fg_bg("TelescopePreviewTitle", colors.bg, colors.green)
  set_fg_bg("TelescopePromptTitle", colors.bg, colors.red)
  set_fg_bg("TelescopeResultsTitle", colors.bg, colors.bg)
  set_fg_bg("TelescopeResultsBorder", colors.bg, colors.bg)
  set_bg("TelescopeSelection", colors.bg_alt)
end

return M
```

**Comment by israelss** [comment]
> ok guys i need some testers
> to make sure if this works with different colorschemes or not

I'm not at home right now, but as soon as I can I'll try this out. I am currently using catppuccin theme, and will post here some screenshots later.

**Comment by israelss** [comment]
@abzcoding, it works as expected for catppuccin theme, as per screenshots below:
![highlight](https://user-images.githubusercontent.com/8899819/155382465-eb50a8c5-53d2-4431-923f-45dc3d902f0c.png)
![highlight_2](https://user-images.githubusercontent.com/8899819/155382565-ab18f0cf-e0df-4d4d-b5bc-735fbe38409c.png)
![highlight_buffers](https://user-images.githubusercontent.com/8899819/155382578-337de5f3-1745-45a7-86bb-d0c24a815cf9.png)
![highlight_change_colorscheme](https://user-images.githubusercontent.com/8899819/155382589-4ede223e-42df-47ad-9625-f979db7d8aff.png)
![highlight_changelog](https://user-images.githubusercontent.com/8899819/155382600-321124eb-f0db-4532-a624-3d18c12e973a.png)
![highlight_grep](https://user-images.githubusercontent.com/8899819/155382610-11413a7e-7dd6-4d3f-a0b5-75ea6e29d6e0.png)
![highlight_keymaps](https://user-images.githubusercontent.com/8899819/155382618-8a6b4eeb-4851-42af-b198-5e8cf8cf1ed4.png)
![highlight_projects](https://user-images.githubusercontent.com/8899819/155382638-14d34715-b977-4d51-94f0-623e1c7d410a.png)

The only problem that I was able to find is that if I try to preview theme (`<leader>sp`) telescope will became "unstyled" again, and only gets styled again when I close and reopen lvim:
![highlight_preview_colorscheme](https://user-images.githubusercontent.com/8899819/155382895-5de464e2-1d65-4ff3-a205-f0c5ee912038.png)

**Comment by abzcoding** [comment]
@israelss thank you for testing it, yeah i need to make sure that all of our custom telescope providers are using similar styles

**Comment by israelss** [comment]
@abzcoding with these configs telescope is WAY better, there's more room to see the previewed file and filepath. Thank you!

![highlight_new_2](https://user-images.githubusercontent.com/8899819/155402608-0ee15e57-cf40-4e99-bfe7-0f93c6ae70af.png)

But one thing that I didn't like was the prompt at the bottom, e.g. on changelog, so maybe is better to not include `prompt_position = "bottom",`.

![highlight_new](https://user-images.githubusercontent.com/8899819/155402258-d16886fb-3a40-4fbe-8b00-72bffb0e4e9a.png)

Also, that made me wonder: it is possible to hide `Git Show Preview` label? It is kinda awkward and feel a little out of place now... Also, I feel that it's unnecessary, because it is quite obvious that that section is a preview... :eyes:

![highlight_new_3](https://user-images.githubusercontent.com/8899819/155403571-49cc4f39-9a40-422c-a674-cdf10042eba0.png)

**Comment by casonadams** [comment]
Would be nice to just support the terminal base 16 colors.

**Comment by LostNeophyte** [comment]
https://github.com/LunarVim/lvim-themes
![image](https://user-images.githubusercontent.com/110467150/208163876-8fb9a377-dab8-4abc-bd72-649507ac6625.png)
what do you all think?
