### ISSUE TITLE
How to setup eslint and/or tailwindcss lsp correctly

### ISSUE THREAD

**Issue by namimo** [LunarVim/LunarVim#2299]
### Feature Description

I installed  lsp through:
```
:LspInstall tailwindcss
:LspInstall eslint
```

And these are the configs I tried. I am showing the config for `eslint` but its the same for `tailwindcss` too:

```lua
lvim.lsp.automatic_servers_installation = false

-- this wont work
require("lvim.lsp.manager").setup("eslint")
-- this wont work
require("lvim.lsp.manager").setup("eslint", {
    cmd = { "vscode-eslint-language-server", "--stdio" },
})
-- this works but i have to explicitly point the lsp directory
require("lvim.lsp.manager").setup("eslint", {
    cmd = {
      "/home/XXX/.local/share/nvim/lsp_servers/vscode-eslint/node_modules/vscode-langservers-extracted/bin/vscode-eslint-language-server",
      "--stdio",
    },
})
```

Another way is installalling lsp globally through npm but I would like to avoid creating another copy

I recently migrated from vscode vim to lunarvim, so I don't know much about configs
Am I doing something wrong here or is 3rd option the right way.

**Comment by williamgoulois** [comment]
Please read the docs here https://www.lunarvim.org/languages/
- For tailwind you have to override it and add it in ftplugin files
- eslint is not a language server it's a linter you should add it to your config and enable it for specific filetypes

**Comment by Uzaaft** [comment]
This is what I have added in my `ftplugin/typescriptreact.lua` file:
```lua
require("lvim.lsp.manager").setup "tailwindcss"
```
It might or might not work for you. Make sure you have the lsp installed.

**Comment by kylo252** [comment]
@Uzaaft, should we add more info to the typescript page maybe? but then we don't want to duplicate the info for javascript and all the other ones. I feel like it could be a new page, either JS-family or web-dev. 

I'll also try to ask on discord to get some more opinions.

**Comment by Uzaaft** [comment]
Yeah Sure thing. I think that's useful! 
I think we should have it as either TailWindCS, or something like: JS tooling?
I'll start working on a draft for lunarvim.org regarding that, opening up a RFC so that people from Discord can comment on it instead?

**Comment by namimo** [comment]
I tried both `config.lua` and `ftplugin/vue.lua`. And both throw error about spawning language server if I dont use the third way. I have lsp installed too.

**Comment by kylo252** [comment]
> I tried both `config.lua` and `ftplugin/vue.lua`. And both throw error about spawning language server if I dont use the third way. I have lsp installed too.

@namimo, that's because the current impl prevents lsp-installer from running if a server is overridden. I have a few ideas to address this which should go into https://github.com/LunarVim/LunarVim/pull/2243

**Comment by Oungseik** [comment]
[#2320 ](https://github.com/LunarVim/LunarVim/issues/2320) - Configure manually and install tailwind lsp globally is work in my machine.

**Comment by hademo** [comment]
@Uzaaft I would restrict this on common filetypes like html, tsx, jsx & vue:
```lua
require("lvim.lsp.manager").setup("tailwindcss", {
  filetypes = { "html", "vue", "typescriptreact", "javascriptreact" }
})

```

**Comment by opchav** [comment]
@hademo Thanks for that.
If anyone wants to support tailwind autocompletion in `.erb` files, just add the `eruby` to the filetypes list.

**Comment by felixpohlmann** [comment]
> @Uzaaft I would restrict this on common filetypes like html, tsx, jsx & vue:
> 
> ```lua
> require("lvim.lsp.manager").setup("tailwindcss", {
>   filetypes = { "html", "vue", "typescriptreact", "javascriptreact" }
> })
> ```

I've did this step, but still get linting problems and the LSP server is not being loaded... (see screenshots)

<img width="777" alt="Screenshot 2022-09-01 at 16 06 54" src="https://user-images.githubusercontent.com/68960775/187934433-85ecb6f0-64fc-431b-9658-ed0345abdecc.png">
<img width="1798" alt="Screenshot 2022-09-01 at 16 07 13" src="https://user-images.githubusercontent.com/68960775/187934445-330370a1-3381-473c-b684-941915f7b49e.png">
