### ISSUE TITLE
PackerSync/Update error on fresh install

### ISSUE THREAD

**Issue by fematarazzo** [LunarVim/LunarVim#2302]
### Problem description

After installing LunarVim and all its dependencies, I get a "Failed to update wbthomason/packer.nvim" error with the following error:

`fatal: reference is not a tree: c5e98e3ca84843dbae47cd8f3a76bc38c6404241`

Can anyone help me Sync/Update Packer properly? I'm unable to use it.

### LunarVim version

c8157a0

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

ArchLinux

### Relevant log output

```shell
:
```

**Comment by miguno** [comment]
I had the same problem on a fresh install today, but my error message referenced a different commit hash (`c576ab3f1488ee86d60fd340d01ade08dcabd256`). My workaround fix has been as follows.

```sh
# Go to LunarVim's local checkout of webthomason/packer.nvim
$ cd ~/.local/share/lunarvim/site/pack/packer/start/packer.nvim

# If needed, run a `git pull` first in this repo to get the latest code.
$ git pull

# Get the hash of the last commit. Remember it, you need it later.
$ git rev-parse HEAD
4dedd3b08f8c6e3f84afbce0c23b66320cd2a8f2

# Edit `plugins.lua`.
$ vim ~/.local/share/lunarvim/lvim/lua/lvim/plugins.lua

# In the file, find the `packer = ...` entry.  In your case, this should read
# "packer = c5e98e3ca84843dbae47cd8f3a76bc38c6404241".
#
# Replace the commit hash with the previous commit hash from above:
# "packer = 4dedd3b08f8c6e3f84afbce0c23b66320cd2a8f2"
#
# Save and exit `plugins.lua`.
```

Now you can re-open LunarVim and run `:PackerSync` successfully (hopefully).

**Comment by abzcoding** [comment]
> I had the same problem on a fresh install today, but my error message referenced a different commit hash (`c576ab3f1488ee86d60fd340d01ade08dcabd256`). My workaround fix has been as follows.
> 
> ```shell
> # Go to LunarVim's local checkout of webthomason/packer.nvim
> $ cd ~/.local/share/lunarvim/site/pack/packer/start/packer.nvim
> 
> # If needed, run a `git pull` first in this repo to get the latest code.
> $ git pull
> 
> # Get the hash of the last commit. Remember it, you need it later.
> $ git rev-parse HEAD
> 4dedd3b08f8c6e3f84afbce0c23b66320cd2a8f2
> 
> # Edit `plugins.lua`.
> $ vim ~/.local/share/lunarvim/lvim/lua/lvim/plugins.lua
> 
> # In the file, find the `packer = ...` entry.  In your case, this should read
> # "packer = c5e98e3ca84843dbae47cd8f3a76bc38c6404241".
> #
> # Replace the commit hash with the previous commit hash from above:
> # "packer = 4dedd3b08f8c6e3f84afbce0c23b66320cd2a8f2"
> #
> # Save and exit `plugins.lua`.
> ```
> 
> Now you can re-open LunarVim and run `:PackerSync` successfully (hopefully).

yeah thata would get fixed when we merge `rolling` into `master`

**Comment by miguno** [comment]
Thank you!

**Comment by danielo515** [comment]
Can this fix be merged and release a hotfix version? It is very annoying

**Comment by abzcoding** [comment]
> Can this fix be merged and release a hotfix version? It is very annoying

cc: @kylo252

**Comment by kylo252** [comment]
> Can this fix be merged and release a hotfix version? It is very annoying

can't really do anything about it as it's git issue in packer, and it isn't even that straight forward to handle in a safe way, see https://www.lunarvim.org/troubleshooting/#plugin-issue

solution? tell plugin authors to avoid re-writing history on their main branch

**Comment by danielo515** [comment]
> > Can this fix be merged and release a hotfix version? It is very annoying
> 
> can't really do anything about it as it's git issue in packer, and it isn't even that straight forward to handle in a safe way, see https://www.lunarvim.org/troubleshooting/#plugin-issue
> 
> solution? tell plugin authors to avoid re-writing history on their main branch

I don't get the problem that prevents form adding a single commit changing this line to a correct commit and merge that into the rolling branch (if that is the considered stable)
