### ISSUE TITLE
clangd: error popover whenever the document is modified.

### ISSUE THREAD

**Issue by sudonym1** [LunarVim/LunarVim#2305]
### Problem description

1. Setup clangd, Open C++ source, preferably with a large project.
2. Modify and save the open file.
3. Get a popover indicating an error.

Ideally, there would be a documented way to suppress these popover errors. Perhaps by regex?

### LunarVim version

3abb0a7

### Neovim version (>= 0.6.1)

NVIM v0.6.1

### Operating system/version

Ubuntu 18.04

### Relevant log output

```shell
From the clangd log file

[ERROR][2022-02-22 09:34:24] .../vim/lsp/rpc.lua:420	"rpc"	"clangd"	"stderr"	"I[09:34:24.070] --> reply:textDocument/documentHighlight(3) 6780 ms, error: Task was cancelled.\nI[09:34:24.070] --> reply:textDocument/documentHighlight(5) 4068 ms, error: Task was cancelled.\nI[09:34:24.070] --> reply:textDocument/documentHighlight(6) 1698 ms, error: Task was cancelled.\n"
```

### Screenshots

![image](https://user-images.githubusercontent.com/117678/155186893-bb39f4ab-7162-4914-ada2-baec6e6b55cd.png)

**Comment by sudonym1** [comment]
IMO, this isn't strictly an issue with lunarvim, but I do consider this a bug in lunarvim's documentation. I don't personally mind digging into the source (probably the popup plugin?) to figure out how to address this issue. Still, if there is already a known mechanism to avoid this popup, I would be happy to submit a PR for the docs, if someone could point me at some initial information.

**Comment by abzcoding** [comment]
you have a couple of options:

1. Disable the popup plugin
2. Set a higher timeout for clangd to make sure tasks can be finished without issues 
3. Find out why is it taking more than 5 seconds for language server to do something

Personally I am not much familiar with clangd but @kylo252 might be able to help

**Comment by kylo252** [comment]
Are you using a compile_commands.json? I've never encountered that error with clangd otherwise, so I'm assuming it's trying to parse the file still.

**Comment by pidgeon777** [comment]
This also happens to me, and I'm using a `compile_commands.json` file.

**Comment by sudonym1** [comment]
Yeah, the error itself is expected. There are many compilation units in this project that are very slow to compile (the project is a template nightmare). Suppressing the pop up would be sufficient. I will look into this some more this weekend.

**Comment by kylo252** [comment]
I suggest tweaking the autosave settings, you can choose any pattern you want `:h autocmd-pattern`, e.g. I only allow a certain extension https://github.com/kylo252/lvim/blob/ac00547006cc6a35efb62d41dea2dbad7908d118/config.lua#L10-L5.

One thing interesting to try is checking the progress status of `clangd` to see if maybe it was still indexing the project. You can use this utility for Lualine
```lua
table.insert(lvim.plugins, {
  "arkav/lualine-lsp-progress",
  opt = false,
  disable = false,
})
local components = require "lvim.core.lualine.components"
lvim.builtin.lualine.sections.lualine_c = { components.diff, "lsp_progress" } -- you can put it in any other section as well
```
