### ISSUE TITLE
We could probably remove the colorscheme from the repo and manage it elsewhere

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#2310]
### Problem description

we set this here, we can just wrap it in a pcall and use default if colorscheme isn't found.

https://github.com/LunarVim/LunarVim/blob/ec1e4140fa4156df50785da5d6297145762a7daa/lua/lvim/plugin-loader.lua#L99

We may also consider updating the colorscheme, and maybe adding some new images to the readme.

### LunarVim version

latest

### Neovim version (>= 0.6.1)

latest

### Operating system/version

I use arch btw

### Relevant log output

```shell
...
```

**Comment by israelss** [comment]
@ChristianChiarulli are you thinking in any particular theme to update to? If not, I suggest [catppuccin](https://github.com/catppuccin/nvim) :black_cat:
