### ISSUE TITLE
[Windows] lvim command does not start with dashboard

### ISSUE THREAD

**Issue by tiagaoalb** [LunarVim/LunarVim#2314]
### Problem description

1. Just installed lunarvim on windows and accepted the option to start on powershell using the lvim command.
2. When I type lvim, neovim shows on screen

### LunarVim version

1.1.1

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Windows 11

### Relevant log output

```shell
nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: C:\Users\tiaga\AppData\Local\nvim/init.vim
    - ADVICE:
      - :help |init.vim|

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          C:\Python310\python.EXE is Python 3.10 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python in the environment.
  - INFO: Multiple python executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: C:\Python310\python.EXE
  - INFO: Other python executable: C:/Python310/python
  - INFO: Other python executable: /python
  - INFO: Python version: 3.10.1
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v16.13.2
  - INFO: Nvim node.js host: C:\Users\tiaga\AppData\Roaming\npm\node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - WARNING: No usable perl executable found

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: C:\Users\tiaga\AppData\Local\Temp\nvim\lsp.log
  - INFO: Log size: 0 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for c: ABI version 13
```

### Screenshots

![Lunarvim](https://user-images.githubusercontent.com/26368452/155824941-48bf0d9d-dc04-4da3-a62a-773e66875eb8.png)
)

**Comment by abzcoding** [comment]
Can you run  ':PackerSync' inside there ?

**Comment by kylo252** [comment]
@tiagaoalb, please try installing msys2, you can use my bootstrap script if you'd like,  https://gist.github.com/kylo252/a0e799c9bf269093d715b5dec3e37eb4.

**Comment by tiagaoalb** [comment]
> @tiagaoalb, please try installing msys2, you can use my bootstrap script if you'd like, https://gist.github.com/kylo252/a0e799c9bf269093d715b5dec3e37eb4.

Where do I put this file, and how to use it?

**Comment by tiagaoalb** [comment]
@kylo252 got this error using your script.
![image](https://user-images.githubusercontent.com/26368452/155992265-0528d9db-d2a9-4191-af40-444edaa28b99.png)

**Comment by kylo252** [comment]
Oh, it seems that the error is caused by `--confirm-command` switch. You can just follow the installation instructions here: https://www.msys2.org

**Comment by tiagaoalb** [comment]
@kylo252 after installed msys2 I tried do `:PackerSync` inside lvim and this happened.

![image](https://user-images.githubusercontent.com/26368452/156038218-863b3d87-188b-461f-a169-e819cc3d4904.png)

**Comment by kylo252** [comment]
@tiagaoalb, please follow the discussion in https://github.com/LunarVim/LunarVim/issues/1804

**Comment by ntahpc** [comment]
I also encounter this issue but I solve this by this way:
1. I go to .zshrc file (i use zsh for shell, but if you use bash, go to .bashrc)
2. use this command in that file: alias lvim = 'source ~/.local/bin/lvim'
3. save and restart terminal

**Comment by kylo252** [comment]
> @tiagaoalb I also encountered this issue but I solve this by this way:

> 2. use this command in that file: alias lvim = 'source ~/.local/bin/lvim'

You're probably missing an entry in your $PATH, remove that alias and try this instead

```bash
# add this to your shell rc
export PATH="$HOME/.local/bin:$PATH"
```

**Comment by tiagaoalb** [comment]
> 

@ntahpc I'm on windows, so there's no .zshrc.

**Comment by kylo252** [comment]
Should be working correctly since the switch to alpha.nvim.
