### ISSUE TITLE
Failed to locate nvim when using AppImage + alias

### ISSUE THREAD

**Issue by KyleTryon** [LunarVim/LunarVim#2316]
### Problem description

The latest version of neovim that can be installed via `apt` is `0.4.4`, which is below the minimum required version for LunarVim and `apt` is still currently the suggested install method in LunarVim.

1. Install the latest version of neovim via AppImage.
2. alias the Appimage to access it from `nvim`
3. Run the installer `zsh <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`
4. `[ERROR]: Unable to find dependency [neovim]`

This is how I am currently installing neovim, it is slightly different from the Readme, as the readme didn't cover where to install the AppImage.

```shell
mkdir ~/Applications
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
./nvim.appimage
mv nvim.appimage ~/Applications/nvim.appimage
path+=("~/Applications/")
```

And then aliasing like this: 

```shell
echo "alias nvim=nvim.appimage" >> ~/.zshrc
echo "alias vi=nvim" >> ~/.zshrc
echo "alias vim=nvim" >> ~/.zshrc
```

You can see here is where the installation script is checking to ensure that neovim is installed
https://github.com/LunarVim/LunarVim/blob/d16065ce585f12eacc95cd1e5f8725fc0db6a8d9/utils/installer/install.sh#L197

Here is the output of some tests I ran locally to ensure that this script _should_ be working.

### LunarVim version

1.1.1

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Ubuntu 20.04.3 LTS

### Relevant log output

```shell
➜  ~ command -v nvim
alias nvim=nvim.appimage
➜  ~ echo $?
0
➜  ~ command -v git
/usr/bin/git
➜  ~ echo $?
0
➜  ~ if ! command -v git &>/dev/null; then echo "missing git"; fi
➜  ~ if ! command -v nvim &>/dev/null; then echo "missing nvim"; fi
➜  ~ if ! command -v xyz &>/dev/null; then echo "missing xyz"; fi
missing xyz
```

So it does appear that the line in the install script should apparently be working and I have a feeling it has something to do with my shell, anyone have any ideas?

**Comment by abzcoding** [comment]
can you try downloading the installer and running it locally?
```sh
wget https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh
chmod +x install.sh
./install.sh
```

**Comment by veso-k** [comment]
> can you try downloading the installer and running it locally?
> 
> ```shell
> wget https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh
> chmod +x install.sh
> ./install.sh
> ```

Same result.

**Comment by abzcoding** [comment]
[this](https://www.reddit.com/r/neovim/comments/f9661m/comment/firh06q/?utm_source=share&utm_medium=web2x&context=3) might be helpful 
<img width="724" alt="Screen Shot 2022-03-01 at 4 33 06 PM" src="https://user-images.githubusercontent.com/10992695/156173778-066e296b-0489-44c5-a5b3-a625b4666a5e.png">

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by kylo252** [comment]
My first guess is that you're adding an an alias to one shell (zsh) and expecting the other one (bash) to know about it as well, which wouldn't really work.

I suggest creating a symlink or a shim instead, since you generally wouldn't want your shell scripts to rely on your personal configs.

```console
$ ln -s ~/Applications/nvim.appimage ~/.local/bin/nvim # or any other user path
$ export PATH="$HOME/.local/bin:$PATH" # in case it's not already
$ where nvim # this works
/home/user/.local/bin/nvim
$ command -v nvim # so does this
/home/user/.local/bin/nvim
```

**Comment by kylo252** [comment]
Please let me know if that still doesn't fix your issue.

**Comment by KyleTryon** [comment]
Thank you @kylo252! That makes sense and I was able to fix it with your instructions. 🙇
