### ISSUE TITLE
How to turn off automatic formatting

### ISSUE THREAD

**Issue by j2501987804** [LunarVim/LunarVim#2323]
### Problem description

I would like to turn this off because it would conflict with autosave

### LunarVim version

last

### Neovim version (>= 0.6.1)

>=0.6

### Operating system/version

mac os12

### Relevant log output

```shell
no
```

**Comment by abzcoding** [comment]
https://www.lunarvim.org/languages/#formatting-on-save

```lua
lvim.format_on_save = false
```
