### ISSUE TITLE
HOW I CAN EXIT LVIM BUT STILL KEEP TERMINAL SHELL?

### ISSUE THREAD

**Issue by ntahpc** [LunarVim/LunarVim#2326]
### Problem description

when I open a lvim file from terminal, and at the moment I wanna exit lvim, I use ':q' to exit lvim but the terminal also exit , HOW I CAN EXIT LVIM BUT STILL KEEP TERMINAL SHELL?

### LunarVim version

1.1.1

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Kali Linux 20.1

### Relevant log output

```shell
:q
```

**Comment by abzcoding** [comment]
This has nothing to do with lunarvim. Check your terminal configuration to see what is causing your terminal to exit when no program is running.
also make sure that `q` key is not bound to anything (for example quitting) in your terminal
