### ISSUE TITLE
Installer.ps1: It may create alias improperly when profile.ps1 already exists

### ISSUE THREAD

**Issue by gaeulbyul** [LunarVim/LunarVim#2329]
### Problem description

* Powershell: v7.2.1 (but the Powershell v5.1 has same problem)

1. Try to install Lunarvim with `installer.ps1`
2. Answer "**Y**" to create alias when the installer asks *"Would you like to create an alias inside your Powershell profile?"*.

example `Microsoft.PowerShell_profile.ps1`, before install:

```powershell
Set-PSReadLineOption -EditMode emacs
```

example `Microsoft.PowerShell_profile.ps1`, after install:

```powershell
Set-PSReadLineOption -EditMode emacsSet-Alias lvim "C:\Users\aeiou\.local\bin\lvim.ps1"
```

I think the installer need to insert newline("`n") before create an alias.

### LunarVim version

N/A

### Neovim version (>= 0.6.1)

N/A

### Operating system/version

Windows 10

### Relevant log output

```shell
N/A (bug is on installer, not lunarvim itself)
```

**Comment by kylo252** [comment]
I just tried the command locally and I don't have this problem, please test this:
```pwsh
Add-Content -Path $PROFILE -Value $( -join @('#', " this ", 'is just a test', '!'))
# now see the changes
lvim $PROFILE
```
Make sure to try running with `-noprofile` as well, just in case you have something incompatible with your `$PROFILE`.

**Comment by gaeulbyul** [comment]
> Add-Content -Path $PROFILE -Value $( -join @('#', " this ", 'is just a test', '!'))

Before
-----
![image](https://user-images.githubusercontent.com/830515/156892658-11b97c08-3146-4230-8d01-fbb950684f52.png)

After
-----
![image](https://user-images.githubusercontent.com/830515/156892671-acc2c7d8-c65f-44a7-93a3-0d4c3aa2193f.png)

**Comment by kylo252** [comment]
Fixed in https://github.com/LunarVim/LunarVim/pull/2404
