### ISSUE TITLE
Error on start up nlsp-seeting

### ISSUE THREAD

**Issue by grimgort** [LunarVim/LunarVim#2334]
### Problem description

Error on start up nlsp-seeting

### LunarVim version

4a9e664

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

windows 10

### Relevant log output

```shell
no
```

### Screenshots

![image](https://user-images.githubusercontent.com/44238325/157006454-78e753e9-33f2-48b1-adee-3c1de139f256.png)

**Comment by abzcoding** [comment]
might be related to https://github.com/tamago324/nlsp-settings.nvim/issues/16
