### ISSUE TITLE
Keep keybinds on the same key for different layouts (except insert mode)

### ISSUE THREAD

**Issue by kplieven** [LunarVim/LunarVim#2336]
### Feature Description

I've been meaning to learn Colemak for a while now, but the one thing holding me back is all the keybinds in (lunar)vim. It would be nice if we could just set `lvim.layout = "US Colemak"` (or similar, its just an example) and it would handle the rest. What I'd like the behaviour to be is to keep all the keybinds as they are in qwerty but use the keyboards layout for insert mode.

### Describe the alternatives you have considered

I think I could remap every key individually, although I don't know how that would affect other mappings and if those mappings would have to be changed as well. I'm willing to try and implement a more general way myself but I have no idea how I would go about that, if someone could give me some pointers of where to start I could try and give it a shot.

**Comment by RomanHN** [comment]
I use Colemak and am currently figuring out a way to remap everything. I'll share my config file if I figure it out.

**Comment by RomanHN** [comment]
https://github.com/RomanHN/scripts_n_stuff/blob/main/Lunarvim_Colemak.lua

**Comment by ZhiyuanChen** [comment]
Really wish it could be a default behavior
