### ISSUE TITLE
support proxy and provide a detailed debugging tutorial

### ISSUE THREAD

**Issue by hawkinchina** [LunarVim/LunarVim#2337]
### Feature Description

1. support proxy github download.  it can config this proxy url before the github url of all plugins. 
2. detail document of debugging for c/c++/ts/js/node.   it had better give some examples all in one.

**Comment by abzcoding** [comment]
for the first part, check if this method works or not -> https://www.lunarvim.org/01-installing.html#tips-for-users-in-mainland-china

for the second part i have some examples in my own config, but yeah we should probably do a more extensive documentation

https://github.com/abzcoding/lvim/blob/main/lua/user/dap.lua

**Comment by hawkinchina** [comment]
@abzcoding 
1. the first part, i try. it cannot work.. :(,   the proxy is most used  by manually downloading these git plugins.  Give one option when it set,  the url will be prefixed of git url. it will be work.
2. give some examples of c/c++/ts/java, it will save a lot of time for developers.  thanks.

**Comment by abzcoding** [comment]
all the plugins are installed using git, so you should be fine just configuring a proxy for git
https://gist.github.com/evantoli/f8c23a37eb3558ab8765

**Comment by Uzaaft** [comment]
@abzcoding Do you have a gist of a MVP working example of debugging in C/C++, if so I'll try and write a guide on those first and add that to lunarvim.org.

**Comment by Uzaaft** [comment]
Also, could you edit the title to be something more constructive regarding the actual issues? I find the current title severely lacking.

**Comment by abzcoding** [comment]
> @abzcoding Do you have a gist of a MVP working example of debugging in C/C++, if so I'll try and write a guide on those first and add that to lunarvim.org.

i have some stuff [here](https://github.com/abzcoding/lvim/blob/main/lua/user/dap.lua), but sadly not a complete working example

**Comment by Uzaaft** [comment]
Love the latest commit message in your repo.😂
I'll see what I can whip up.

**Comment by hawkinchina** [comment]
if configuring a proxy for git， Can it  support like the following URL: 
git clone https://mirror.ghproxy.com/https://github.com/stilleshan/ServerStatus.git ?

--> config https://mirror.ghproxy.com as global  git  proxy. so it will work after running the command:
git clone https://github.com/stilleshan/ServerStatus.git ?

i try, it failed.

if you run the command directly: 
git clone https://mirror.ghproxy.com/https://github.com/stilleshan/ServerStatus.git
it download very fast.
