### ISSUE TITLE
[Bug] Installation Bug on PowerShell (v7.2.1)

### ISSUE THREAD

**Issue by marechal-dev** [LunarVim/LunarVim#2342]
### Problem description

1. Try to use `Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression`
2. The error is thrown.

(As my PowerShell is in another language, I translated the Relevant log output. Sorry for any typos, I'm still practicing!)

### LunarVim version

N/A

### Neovim version (>= 0.6.1)

NVIM v0.6.1 Build type: RelWithDebInfo LUAJIT 2.1.0-beta3

### Operating system/version

Windows 10 Version 21H2 Compilation 19044.1566

### Relevant log output

```shell
Invoke-Expression : No linha:5 caractere:25
+ $LV_BRANCH = $LV_BRANCH ?? "rolling"
+                         ~~
Unexpected Token or Instruction '??'.
Line:6 char:25
+ $LV_REMOTE = $LV_REMOTE ??  "lunarvim/lunarvim.git"
+                         ~~
Unexpected Token or Instruction '??'.
Line:7 Char:35
+ $INSTALL_PREFIX = $INSTALL_PREFIX ?? "$HOME\.local"
+                                   ~~
Unexpected Token or Instruction '??'.
Linha:9 Char:41
+ $env:XDG_DATA_HOME = $env:XDG_DATA_HOME ?? $env:APPDATA
+                                         ~~
Unexpected Token or Instruction '??'.
Line:10 Char:45
+ $env:XDG_CONFIG_HOME = $env:XDG_CONFIG_HOME ?? $env:LOCALAPPDATA
+                                             ~~
Unexpected Token or Instruction '??'.
Line:11 Char:43
+ $env:XDG_CACHE_HOME = $env:XDG_CACHE_HOME ?? $env:TEMP
+                                           ~~
Unexpected Token or Instruction '??'.
Line:13 Char:55
+ $env:LUNARVIM_RUNTIME_DIR = $env:LUNARVIM_RUNTIME_DIR ?? "$env:XDG_DA ...
+                                                       ~~
Unexpected Token or Instruction '??'.
Line:14 Char:53
+ $env:LUNARVIM_CONFIG_DIR = $env:LUNARVIM_CONFIG_DIR ?? "$env:XDG_CONF ...
+                                                     ~~
Unexpected Token or Instruction '??'.
Line:15 Char:51
+ $env:LUNARVIM_CACHE_DIR = $env:LUNARVIM_CACHE_DIR ?? "$env:XDG_CACHE_ ...
+                                                   ~~
Unexpected Token or Instruction '??'.
Line:16 Char:49
+ $env:LUNARVIM_BASE_DIR = $env:LUNARVIM_BASE_DIR ?? "$env:LUNARVIM_RUN ...
+                                                 ~~
Unexpected Token or Instruction '??'.
Line:1 Char:108
+ ... arVim/LunarVim/master/utils/installer/install.ps1 | Invoke-Expression
+                                                         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : UnexpectedToken,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by ffaanngg** [comment]
I installed the latest version and this error message doesn't appear anymore

**Comment by marechal-dev** [comment]
@ffaanngg how did you install the latest? I'm trying by using the default command (`Invoke-WebRequest`...), but I still facing the same error.

**Comment by ffaanngg** [comment]
I was actually referring to the latest version of Powershell

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2 guide for installing the latest version

**Comment by kylo252** [comment]
Seems like a powershell bug since this feature should be available in v7+
https://docs.microsoft.com/en-gb/powershell/scripting/whats-new/what-s-new-in-powershell-70?view=powershell-7#null-coalescing-assignment-and-conditional-operators

I wonder if it's an encoding issue. Please download the script first and then run it manually.

**Comment by marechal-dev** [comment]
@kylo252 I downloaded the Microsoft Store's version of Powershell, only then I could install Lunarvim (thanks for the advice @ffaanngg).
I came across an error at "add lvim alias" step of installation. It had an unexpected token `=` (no error line was outputted).

**Comment by nos-nart** [comment]
@kylo252 Cope with this same issue. Tried with PowerShell-7.2.1, install LunarVim failed after 2, 3 seconds It prints LunarVim then shell is closed 😟

**Comment by kylo252** [comment]
@nos-nart, please open a new issue with a full bug report so it's easier to track.

**Comment by nappalm** [comment]
I have the same problem 😔

**Comment by Veganov** [comment]
I've faced with the same issue, but have used the advice of @kylo252 

> Please download the script first and then run it manually.
So, to install LunarVim on Windows, first check all the LunarVim Prerequisits, then download the script (I've just follow the link https://raw.githubusercontent.com/LunarVim/LunarVim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.ps1 and copy and save the text of the script to install.ps1 file on the Desktop) and run in the PowerShell (v 7.3.3) as an administrator (requires entering the administrator password):
`$LV_BRANCH='release-1.2/neovim-0.8'; "C:\Users\YourUsername\Desktop\install.ps1" | Invoke-Expression`
Hope it helps.
