### ISSUE TITLE
Packer snapshot integration

### ISSUE THREAD

**Issue by kylo252** [LunarVim/LunarVim#2343]
### Feature Description

Replace/integrate the current workflow for pinning plugins with the new snapshot implementation `:h packer.snapshot()`. 

The snapshot file is in json (even though the documentation states that they're in lua).

**Comment by abzcoding** [comment]
quick question, how is this different from what we are currently doing ( regarding plugin commit hash ) ?

**Comment by kylo252** [comment]
> quick question, how is this different from what we are currently doing ( regarding plugin commit hash ) ?

It's more about using the API, there's a specific command `:PackerSnapshotRollback <snapshot-name>` that could be used for example instead of `:PackerUpdate`. I generally figured that it's easier for the user to track as well.

**Comment by jameswalmsley** [comment]
Awesome this looks great. In my config I sometimes comment out the pins to test the upstream plugins..

Now I'll be able to do this and easily revert if I'm unhappy.

**Comment by kylo252** [comment]
@jameswalmsley, I still need to add documentation, but I added a feature that I discussed earlier in #2085 which also allows you to _unlock_ all the plugins pinning if you enable `$LVIM_DEV_MODE`, see
https://github.com/LunarVim/LunarVim/blob/fdffa099a869f6b819bd4bf5c5f45e63992668a2/lua/lvim/plugins.lua#L220-L224
