### ISSUE TITLE
Deprecate redundant `lvim.lsp.diagnostics`

### ISSUE THREAD

**Issue by kylo252** [LunarVim/LunarVim#2344]
### Feature Description

These options are originally from before 0.6, otherwise they aren't really needed, so there's no need to go through or maintain this API. We should've removed them when bumped the reqs to 0.6+. 

- That would also be inline with how the options in `settings.lua` are loaded once to avoid overriding user's new config (we should probably just move those values there)
- `vim.diagnostic.config` is easier to point to with regards to documentation.
- It's still under `lsp` even though it's not _LSP_-only necessarily.

### Support information

Semi related: https://github.com/LunarVim/LunarVim/pull/1965

**Comment by danielo515** [comment]
Do you mind explaining what should be used instead when this gets deprecated?

**Comment by kylo252** [comment]
> Do you mind explaining what should be used instead when this gets deprecated?

There's a native API for this as mentioned in the description, see `:h vim.diagnostic.config()`

**Comment by danielo515** [comment]
to keep things simple, can configuration examples be added to the example configuration?
