### ISSUE TITLE
DAPInstall.nvim has been archived

### ISSUE THREAD

**Issue by abzcoding** [LunarVim/LunarVim#2345]
we should remove https://github.com/Pocco81/DAPInstall.nvim since it is not maintained anymore

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by starptr** [comment]
Will there be an alternative method for installing debug adapters within lvim?

**Comment by starptr** [comment]
cc @Pocco81 if you'd like, you can transfer the repo to me & I can maintain it; integrated debugging is important to me & I work in environments where I don't have great alternatives for installing debug adapters.

**Comment by abzcoding** [comment]
possible replacement 🤞 https://github.com/asmodeus812/nvim-dap-install

**Comment by abzcoding** [comment]
the changes will be tracked here -> https://github.com/LunarVim/LunarVim/pull/2504
