### ISSUE TITLE
some config of indent-blankline cannot work.

### ISSUE THREAD

**Issue by hawkinchina** [LunarVim/LunarVim#2346]
### Problem description

some config of indent-blankline cannot work.

i want to config the following : 
----------------------
vim.opt.list = true
vim.opt.listchars:append("space:⋅")
vim.opt.listchars:append("eol:↴")

require("indent_blankline").setup {
    space_char_blankline = " ",
    show_current_context = true,
    show_current_context_start = true,
}
-----------------------
but the config of lvim:
{
  "lukas-reineke/indent-blankline.nvim",
  event = "BufRead",
  setup = function()
    vim.g.indentLine_enabled = 1
    vim.g.indent_blankline_char = "▏"
    vim.g.indent_blankline_filetype_exclude = {"help", "terminal", "dashboard"}
    vim.g.indent_blankline_buftype_exclude = {"terminal"}
    vim.g.indent_blankline_show_trailing_blankline_indent = false
    vim.g.indent_blankline_show_first_indent_level = false

vim.g.indent_blankline_show_end_of_line = true
vim.g.indent_blankline_show_current_context = true
vim.g.indent_blankline_show_current_context_start = true

  end
},

i am not sure how to config the opt in lvim config.

vim.opt.list = true
vim.opt.listchars:append("space:⋅")
vim.opt.listchars:append("eol:↴")

### LunarVim version

1.1.2

### Neovim version (>= 0.6.1)

NVIM v0.7.0-dev+1136-g005a7aa16 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

macos 10.13

### Relevant log output

```shell
not needed.
```

**Comment by abzcoding** [comment]
just add them wherever in your `~/.config/lvim/config.lua`
for example here is mine:
```lua
  vim.opt.fillchars = {
    vert = "▕", -- alternatives │
    fold = " ",
    eob = " ", -- suppress ~ at EndOfBuffer
    diff = "╱", -- alternatives = ⣿ ░ ─
    msgsep = "‾",
    foldopen = "▾",
    foldsep = "│",
    foldclose = "▸",
  }
```

**Comment by hawkinchina** [comment]
why I config like the blow, but it cannot work? 
{
		"lukas-reineke/indent-blankline.nvim",
		event = "BufRead",
		setup = function()
			vim.g.indentLine_enabled = 1
			vim.g.indent_blankline_char = "▏"
			vim.g.indent_blankline_filetype_exclude = { "help", "terminal", "dashboard" }
			vim.g.indent_blankline_buftype_exclude = { "terminal" }
			vim.g.indent_blankline_show_trailing_blankline_indent = false
			vim.g.indent_blankline_show_first_indent_level = false

			vim.g.indent_blankline_show_end_of_line = true
			vim.g.indent_blankline_show_current_context = true
			vim.g.indent_blankline_show_current_context_start = true

			vim.opt.list = true
			vim.opt.listchars:append("space:⋅")
			vim.opt.listchars:append("eol:↴")
		end,
	},

**Comment by abzcoding** [comment]
`vim.opt` thingies should be kept out of setup function ( inside your `config.lua`)
the rest are changed to lua
so you need to change to something like this
```lua
{
  "lukas-reineke/indent-blankline.nvim",
  setup = function()
    vim.g.indent_blankline_char = "▏"
  end,
  config = function()
      require("indent_blankline").setup {
        enabled = true,
        bufname_exclude = { "README.md" },
        buftype_exclude = { "terminal", "nofile" },
        filetype_exclude = {
          "alpha",
          "log",
          "gitcommit",
          "dapui_scopes",
          "dapui_stacks",
          "dapui_watches",
          "dapui_breakpoints",
          "dapui_hover",
          "LuaTree",
          "dbui",
          "UltestSummary",
          "UltestOutput",
          "vimwiki",
          "markdown",
          "json",
          "txt",
          "vista",
          "NvimTree",
          "git",
          "TelescopePrompt",
          "undotree",
          "flutterToolsOutline",
          "org",
          "orgagenda",
          "help",
          "startify",
          "dashboard",
          "packer",
          "neogitstatus",
          "NvimTree",
          "Outline",
          "Trouble",
          "lspinfo",
          "", -- for all buffers without a file type
      },
        show_trailing_blankline_indent = false,
        show_first_indent_level = false,
        space_char_blankline = " ",
        use_treesitter = true,
        show_foldtext = false,
        show_current_context = true,
        show_current_context_start = false,
        context_patterns = {
          "class",
          "return",
          "function",
          "method",
          "^if",
          "^do",
          "^switch",
          "^while",
          "jsx_element",
          "^for",
          "^object",
          "^table",
          "block",
          "arguments",
          "if_statement",
          "else_clause",
          "jsx_element",
          "jsx_self_closing_element",
          "try_statement",
          "catch_clause",
          "import_statement",
          "operation_type",
        },
      }
  end,
  event = "BufRead",
},
```

**Comment by hawkinchina** [comment]
OK. thanks...
just config  like global variable in ~/.config/lvim/config.lua anywhere outside of lvim.plugin.  it works.


--- the following config is failed. ----
--- you should config the opts outside of lvim.plugin. it will work ---
if you config in lvim.plugin = {
...
{
		"lukas-reineke/indent-blankline.nvim",
		event = "BufRead",
		setup = function()
			vim.g.indentLine_enabled = 1
			vim.g.indent_blankline_char = "▏"
			vim.g.indent_blankline_filetype_exclude = { "help", "terminal", "dashboard" }
			vim.g.indent_blankline_buftype_exclude = { "terminal" }
			vim.g.indent_blankline_show_trailing_blankline_indent = false
			vim.g.indent_blankline_show_first_indent_level = false
			vim.g.indent_blankline_show_end_of_line = true
			vim.g.indent_blankline_show_current_context = true
			vim.g.indent_blankline_show_current_context_start = true
			**vim.opt.list = true
			 vim.opt.listchars:append("space:⋅")
			 vim.opt.listchars:append("eol:↴")**
		end,
	},

...
}
