### ISSUE TITLE
Installation error on Windows 10

### ISSUE THREAD

**Issue by mathstylish** [LunarVim/LunarVim#2356]
### Problem description

I'm trying to install Lunarvim on Windows 10. I've already installed all necessary dependencies (neovim 0.5+, node, python, cargo, lua and it also asked for make), all with the scoop package manager. However, I am encountering the following error after install dependencies:

```
Updating LunarVim
-------------------------------------------------- ------------------------------

Error detected while processing command line:
E5108: Error executing lua ...ish\AppData\Roaming\lunarvim\lvim/lua/lvim/utils/git.lua:16: attempt to call method 'new' (a nil value)
stack traceback:
         ...ish\AppData\Roaming\lunarvim\lvim/lua/lvim/utils/git.lua:16: in function 'git_cmd'
         ...ish\AppData\Roaming\lunarvim\lvim/lua/lvim/utils/git.lua:57: in function 'update_base_lvim'
         ...ish\AppData\Roaming\lunarvim\lvim/lua/lvim/bootstrap.lua:118: in function 'update'
         [string ":moon"]:1: in main chunk
E114: Missing quote: " | cquit | else | quit | endif 
```

### LunarVim version

None. After all, the installation was not complete.

### Neovim version (>= 0.6.1)

NVIM v0.6.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compiled by runneradmin@fv-az152-430  Features: -acl +iconv +tui

### Operating system/version

Windows 10 21H2 build 19044.1586

### Relevant log output

```shell
nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: C:\Users\stylish\AppData\Local\nvim/init.vim
    - ADVICE:
      - :help init.vim

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available           executable for diagnostics.
  - ERROR: Python provider error:
[Scratch]                                                                         1,0-1          Top
 [No Name]  [Scratch]                                                                                                                                X
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: C:\Users\stylish\scoop\shims\python3.EXE
  - INFO: Other python executable: C:/Users/stylish/scoop/shims/python3
  - INFO: Python version: 3.10.2^M
  - INFO: pynvim version: 0.4.3^M
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v16.13.1^M
  - INFO: Nvim node.js host: C:\Users\stylish\scoop\apps\nvm\current\nodejs\nodejs\node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - WARNING: No usable perl executable found

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: C:\Users\stylish\AppData\Local\Temp\nvim\lsp.log
  - INFO: Log size: 0 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for c: ABI version 13
```

### Screenshots

![image](https://user-images.githubusercontent.com/44449793/158501225-06924418-5d09-4825-9c9f-d59aa8102d54.png)

**Comment by rodvicj** [comment]
Try updating your powershell to the current latest version. 
Check this link below.
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2

**Comment by mathstylish** [comment]
> Try updating your powershell to the current latest version. Check this link below. https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2

I'm currently on the latest version. Because I download directly from github.

**Comment by rodvicj** [comment]
> > Try updating your powershell to the current latest version. Check this link below. https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2
> 
> I'm currently on the latest version. Because I download directly from github and my 'pwsh -v' show 7.2.1. Thank you for comment.

I wonder how I managed to fixed the same problem before just by upgrading powershell. Do you have lua installed? If not try installing it with scoop.

**Comment by kylo252** [comment]
It seems that the problem is that `Plenary` is not installed, please try the uninstaller first, https://github.com/LunarVim/LunarVim/blob/a5e5b50bc4c95905d8fd1fc1bf8bd0a1306dfe06/utils/installer/uninstall.ps1

This should avoid trying to run the update function, which is not working correctly on Windows in all cases. You'd have to run `:PackerSync` manually as well.

**Comment by Untesler** [comment]
Yeah, I had the same problem as you, and all I did was make sure I had all of the prerequisite programs, then go check all existing files and delete them. It should be around in these paths. 

- $env:APPDATA/lunarvim
- $env:LOCALAPPDATA/lvim
- $env:TEMP/lvim

After that, you can try running the installer again, but make sure you read #2360 first.

**Comment by mathstylish** [comment]
> Yeah, I had the same problem as you, and all I did was make sure I had all of the prerequisite programs, then go check all existing files and delete them. It should be around in these paths.
> 
>     * $env:APPDATA/lunarvim
> 
>     * $env:LOCALAPPDATA/lvim
> 
>     * $env:TEMP/lvim
> 
> 
> After that, you can try running the installer again, but make sure you read #2360 first.

Thank you very much, that was exactly it. When I installed it for the first time, this error referenced in #2360 actually appeared, so I chose to test your resolution first.

**Comment by mathstylish** [comment]
@Untesler and @kylo252, thanks!! You guys solve my problem both in the solution to make the script install Lunarvim, and in the solution to make PackerSync manually!! Thanks again!!
