### ISSUE TITLE
[bug] Wrong condition expression in install.ps1

### ISSUE THREAD

**Issue by hungpham3112** [LunarVim/LunarVim#2360]
This is the first time I use lunarvim and I see this message:

![image](https://user-images.githubusercontent.com/75968004/159029909-5dcaa1de-8903-4c10-a2c2-aa1219dd5d9c.png)

The script comes from installer\install.ps1.

This should be changed to be:

```
if ($lvim_alias.Definition -eq $lvim_bin) {
        Write-Output "Alias is already set and will not be reset."
        return
    }
```

**Comment by Doomwhite** [comment]
Thanks to this alternative I could finally install LunarVim, Ty!

**Comment by kylo252** [comment]
Sorry about that! 😅 

I'm quite surprised that none of the linters picked up such a basic syntax error...
