### ISSUE TITLE
Git gutter not transparent when lvim.transparent_window = true

### ISSUE THREAD

**Issue by gekoke** [LunarVim/LunarVim#2361]
### Problem description

Steps to reproduce the behaviour:
1. Set `lvim.transparent_window = true` in `config.lua`
2. Modify a tracked file in a git repository
3. Observe the gutter of the modfied lines, they are not transparent

Is what I have described the expected behaviour? [The documentation]("https://www.lunarvim.org/configuration/03-colorschemes.html#switching-colors") mentions that `lvim.transparent_window = true` expands into several vim commands. Are there any that could be added to remedy this?

### LunarVim version

5ee460f

### Neovim version (>= 0.6.1)

NVIM v0.7.0-dev+926-g6006e15e7 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include Compiled by runner@fv-az65-979  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/share/nvim"  Run :checkhealth for more info

### Operating system/version

Linux archlinux 5.16.14-arch1-1 #1 SMP PREEMPT Fri, 11 Mar 2022 17:40:36 +0000 x86_64 GNU/Linux

### Relevant log output

```shell
-
```

### Screenshots

![image](https://user-images.githubusercontent.com/63151928/159047168-3cff342f-e026-432d-b268-c6329e4d6d52.png)

**Comment by kylo252** [comment]
Which theme is this? and are you using something other than `gitsigns`? I don't see the same problem with [onedarker](https://github.com/LunarVim/onedarker.nvim/blob/b00dd2189f264c5aeb4cf04c59439655ecd573ec/lua/onedarker/highlights/Git.lua#L1-L12)

![image](https://user-images.githubusercontent.com/59826753/159160247-e0d3e22f-5583-41e3-8a9c-5cbc186c0b24.png)

**Comment by gekoke** [comment]
Yes, I am using gitsigns. The colorscheme I am using is everforest. The issue is not there with onedarker. I hadn't considered that the colorscheme would have to support this, so it seems like it's not an issue with LunarVim.
