### ISSUE TITLE
colorscheme not loading after #2359

### ISSUE THREAD

**Issue by youdaniel** [LunarVim/LunarVim#2364]
### Problem description

A custom colorscheme set through `lvim.colorscheme` no longer works after #2359. I suspect it's because this was removed:

![image](https://user-images.githubusercontent.com/39450656/159130223-eec113bc-3831-4a0e-96ac-4315e56cdc98.png)

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by kylo252** [comment]
This should be fixed now after #1906 since I included the fix for the theme.

**Comment by youdaniel** [comment]
Hmm... doesn't seem to work unless I explicitly call `vim.cmd "colorscheme foo"`

**Comment by MaxVerevkin** [comment]
I `grep`ed the whole repo and I couldn't thing any `colorscheme` calls.

**Comment by kylo252** [comment]
D

**Comment by MaxVerevkin** [comment]
@kylo252 Yeah, only `onedarker` works...

**Comment by kylo252** [comment]
Yeah, because it's now back to the default behavior of letting the setup handled by the (new) theme itself, whether that be a `setup()` call or otherwise. In this case they should be recommending to explicitly set `colorscheme <my-theme>`.

 I had figured that this is better since it decouples the API and avoids any unnecessary problems arising from setting `colorscheme` too early or too late (this might be specifically problematic with lualine's auto theme mode).
 
That said, I'm happy to revert this specific change if it's too inconvenient. 

---

@abzcoding, how's your experience with multiple themes?

**Comment by abzcoding** [comment]
> @abzcoding, how's your experience with multiple themes?
this is what i'm doing
```lua
    {
      "rose-pine/neovim",
      as = "rose-pine",
      config = function()
        require("user.theme").rose_pine()
        vim.cmd [[colorscheme rose-pine]]
      end,
      cond = function()
        local _time = os.date "*t"
        return (_time.hour >= 1 and _time.hour < 9)
      end,
    },
    {
      "folke/tokyonight.nvim",
      config = function()
        require("user.theme").tokyonight()
        vim.cmd [[colorscheme tokyonight]]
      end,
      cond = function()
        local _time = os.date "*t"
        return _time.hour >= 9 and _time.hour < 17
      end,
    },
    {
      "catppuccin/nvim",
      as = "catppuccin",
      config = function()
        require("user.theme").catppuccin()
        vim.cmd [[colorscheme catppuccin]]
      end,
      cond = function()
        local _time = os.date "*t"
        return (_time.hour >= 17 and _time.hour < 21)
      end,
    },
    {
      "rebelot/kanagawa.nvim",
      config = function()
        require("user.theme").kanagawa()
        vim.cmd [[colorscheme kanagawa]]
      end,
      cond = function()
        local _time = os.date "*t"
        return (_time.hour >= 21 and _time.hour < 24) or (_time.hour >= 0 and _time.hour < 1)
      end,
    },
```

**Comment by MaxVerevkin** [comment]
Hmm, I tried this and is doesn't seem to work...

```lua
lvim.plugins = {
  {
    "ellisonleao/gruvbox.nvim",
    disable = lvim.colorscheme ~= "gruvbox",
    config = function ()
      vim.cmd [[colorscheme gruvbox]]
    end
  },
}
```

Am I doing something wrong?

**Comment by abzcoding** [comment]
> Hmm, I tried this and it doesn't seem to work...
> 
> ```lua
> lvim.plugins = {
>   {
>     "ellisonleao/gruvbox.nvim",
>     disable = lvim.colorscheme ~= "gruvbox",
>     config = function ()
>       vim.cmd [[colorscheme gruvbox]]
>     end
>   },
> }
> ```
> 
> Am I doing something wrong?

are you setting `lvim.colorscheme` somewhere before doing this? cause otherwise it would disable it

**Comment by MaxVerevkin** [comment]
Yes, I have this in the beginning of the file:

```lua
lvim.colorscheme = "gruvbox"
```

**Comment by MaxVerevkin** [comment]
It still doesn't quite work. I.e. setting `lvim.colorscheme = "gruvbox"` doesn't affect the colorscheme, unless I manually reload my config (via space+L+r or when saving the config file).

**Comment by abzcoding** [comment]
> It still doesn't quite work. I.e. setting `lvim.colorscheme = "gruvbox"` doesn't affect the colorscheme, unless I manually reload my config (via space+L+r or when saving the config file).

can you run `:LvimCacheReset` to make sure nothing is cached

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by MaxVerevkin** [comment]
> can you run :LvimCacheReset to make sure nothing is cached

Doesn't help.

**Comment by abzcoding** [comment]
> > can you run :LvimCacheReset to make sure nothing is cached
> 
> Doesn't help.

and what is the output of this command?
```lua
git -C ~/.local/share/lunarvim/lvim rev-parse HEAD
```

**Comment by MaxVerevkin** [comment]
```
❯ git -C ~/.local/share/lunarvim/lvim rev-parse HEAD
d8628ccd111e0aa9da1ea1bb24c87891069150f8
```

**Comment by kylo252** [comment]
@MaxVerevkin, please enable trace logging 
```lua
lvim.log.level = "trace"
```
and share the content of the logfile, which you can open with `<leader>LlD` or 
```vim
:lua vim.cmd('edit ' .. require('lvim.core.log').get_path())
```


_Note: please make sure to clear/empty the logfile first!_

**Comment by MaxVerevkin** [comment]
```
13:23:00 [DEBUG] lvim: "Templates installation in progress" file="lua/lvim/lsp/templates.lua", line=47
13:23:00 [DEBUG] lvim: "Templates installation is complete" file="lua/lvim/lsp/templates.lua", line=68
13:23:22 [DEBUG] lvim: "Templates installation in progress" file="lua/lvim/lsp/templates.lua", line=47
13:23:22 [DEBUG] lvim: "Templates installation is complete" file="lua/lvim/lsp/templates.lua", line=68
```

**Comment by kylo252** [comment]
I got it working, but I had to manually call `:PackerSync`, which used to be default behavior at some point but it caused way too many issues with reloading. However, it should hopefully be easier to re-implement once #2343 has landed. 

This is all I added to my `config.lua`

```diff
diff --git a/config.lua b/config.lua
index 40814a0..50f762c 100644
--- a/config.lua
+++ b/config.lua
@@ -111,4 +111,14 @@ table.insert(lvim.plugins, {
   opt = false,
   disable = false,
 })
+
+lvim.colorscheme = "gruvbox"
+table.insert(lvim.plugins, {
+  "ellisonleao/gruvbox.nvim",
+  disable = lvim.colorscheme ~= "gruvbox",
+  config = function()
+    vim.cmd [[colorscheme gruvbox]]
+  end,
+})
```

**Comment by MaxVerevkin** [comment]
That still doesn't work for me. Plus using `table.insert` causes packer warnings when reloading the config.
