### ISSUE TITLE
globalstatus doesn't work when entering from dashboard

### ISSUE THREAD

**Issue by argapost** [LunarVim/LunarVim#2365]
### Problem description

Hello,

globalstatus works fine when opening lvim with a file: lvim file.py
But, if I just open lvim which opens the dashboard.nvim and search for a file through telescope then the global statusline doesn't work.

Can anyone reproduce or is it just me?

Thanks in advance

### LunarVim version

Rolling

### Neovim version (>= 0.6.1)

nvim v0.7.0 dev

### Operating system/version

manjaro

### Relevant log output

```shell
--
```

**Comment by abzcoding** [comment]
can you try running this ( when the globalstatus is not showing)
```vim
:set laststatus?
```

**Comment by argapost** [comment]
laststatus=2, this should be 3 I guess.

and here is the screenshot:

![image](https://user-images.githubusercontent.com/58076098/159132356-70f96e95-db90-4100-86b7-cdf2803ee807.png)

(any resemblance with your config is purely accidental :p)

**Comment by abzcoding** [comment]
:)
ok we are getting somewhere, now can you check your config for `laststatus` and make sure that you've not set it anywhere

**Comment by argapost** [comment]
I dont change laststatus anywhere in my config.

**Comment by abzcoding** [comment]
ok lets go over the next step, are you on the latest lunarvim `rolling` and have you ran `:LvimUpdate` or `:PackerSync`?

basically running this command
```shell
git -C ~/.local/share/lunarvim/site/pack/packer/start/lualine.nvim rev-parse HEAD
```
should output

`181b14348f513e6f9eb3bdd2252e13630094fdd3`

**Comment by argapost** [comment]
Yes that's the output.

So for you when you open `lvim` and then open a file through `telescope` the globalstatus works fine?

**Comment by abzcoding** [comment]
> Yes that's the output.
> 
> So for you when you open `lvim` and then open a file through `telescope` the globalstatus works fine?

you are right, it actually doesn't work as expected 😅 let me fix it locally and report back

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by abzcoding** [comment]
this is a temporary workaround till i find out what is actually causing it
```lua
lvim.autocommands.custom_groups = {
    { "WinEnter", "*", "set laststatus=3" },
}
```

**Comment by argapost** [comment]
yeap this works for now. thanks anyway for your help! (and your config!)

**Comment by abzcoding** [comment]
found the issue
<img width="932" alt="Screen Shot 2022-03-19 at 10 28 35 PM" src="https://user-images.githubusercontent.com/10992695/159134834-7bae487e-e52c-4599-ac77-a4498f1bec6e.png">

**Comment by kylo252** [comment]
> found the issue <img alt="Screen Shot 2022-03-19 at 10 28 35 PM" width="932" src="https://user-images.githubusercontent.com/10992695/159134834-7bae487e-e52c-4599-ac77-a4498f1bec6e.png">

@abzcoding, is this behavior undesired with globalstatus? I also just merged that PR, so I don't think the original issue has tested it yet.

**Comment by abzcoding** [comment]
> > found the issue <img alt="Screen Shot 2022-03-19 at 10 28 35 PM" width="932" src="https://user-images.githubusercontent.com/10992695/159134834-7bae487e-e52c-4599-ac77-a4498f1bec6e.png">
> 
> @abzcoding, is this behavior undesired with globalstatus? I also just merged that PR, so I don't think the original issue has tested it yet.

yeah, basically this sets laststatus to its default value which is `2` and that removes global status line

**Comment by kylo252** [comment]
@abzcoding, this is why I added that autocmd: https://github.com/LunarVim/LunarVim/pull/1906#issuecomment-1037351575

You can just remove these calls and then one can define them manually if they wish, or add a check for globalstatus availability, I don't mind it either way.

**Comment by abzcoding** [comment]
this is how i fixed it in my local config
<img width="1154" alt="Screen Shot 2022-03-19 at 10 46 15 PM" src="https://user-images.githubusercontent.com/10992695/159135325-c98d36ac-42a0-42f5-9313-585aea414ff7.png">

**Comment by abzcoding** [comment]
@argapost in case you want it as well
```lua
lvim.autocommands._alpha = {
       {
         "FileType",
         "alpha",
         "set showtabline=0 | autocmd BufLeave <buffer> set showtabline=" .. vim.opt.showtabline._value,
       },
}
```
