### ISSUE TITLE
Peek definition fails in C#

### ISSUE THREAD

**Issue by otto-gebb** [LunarVim/LunarVim#2369]
### Problem description

1. Open a C# file.
2. Move the cursor over a method call.
3. Press Space, l, p, d. (LSP Peek Definition).

An error message appears:

> Error executing vim.schedule lua callback: /home/gebb/.local/share/lunarvim/lvim/lua/lvim/lsp/peek.lua:42: 'width' key must be a positive Integer
stack traceback:
        [C]: in function 'nvim_open_win'
        /home/gebb/.local/share/lunarvim/lvim/lua/lvim/lsp/peek.lua:42: in function 'create_floating_file'
        /home/gebb/.local/share/lunarvim/lvim/lua/lvim/lsp/peek.lua:71: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:964: in function 'cb'
        vim.lua:285: in function <vim.lua:285>

### LunarVim version

5ee460f  chore(release): update changelog

### Neovim version (>= 0.6.1)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

Arch Linux

### Relevant log output

```shell
:checkhealth
Nothing suspicious.
```

### Screenshots

LSP info:
![image](https://user-images.githubusercontent.com/5798003/159154131-a830d8da-3100-48f9-b86b-07c50e485dd0.png)

**Comment by abzcoding** [comment]
feel free to reopen if the issue still persists after the fix
