### ISSUE TITLE
Config reloading (<leader>Lr) errors when used on the start screen

### ISSUE THREAD

**Issue by MaxVerevkin** [LunarVim/LunarVim#2372]
### Problem description

- Open `lvim`
- Press `<leader>Lr`

### LunarVim version

https://github.com/LunarVim/LunarVim/commit/d8628ccd111e0aa9da1ea1bb24c87891069150f8

### Neovim version (>= 0.6.1)

NVIM v0.6.1

### Operating system/version

Linux

### Relevant log output

```shell
See screenshot
```

### Screenshots

![image](https://user-images.githubusercontent.com/34583604/159160131-c9746e00-29c0-4a73-814f-4a4d166d0cd7.png)

**Comment by abzcoding** [comment]
can you link your `~/.config/lvim/config.lua` somewhere?

**Comment by MaxVerevkin** [comment]
https://paste.rs/gcE

**Comment by abzcoding** [comment]
this is what i changed, and the colorscheme seem to be working as well
<img width="1909" alt="Screen Shot 2022-03-20 at 6 51 11 PM" src="https://user-images.githubusercontent.com/10992695/159169598-99368146-bd21-4004-ab9f-cf17f425675d.png">


```lua
-- Additional Plugins
lvim.colorscheme = "gruvbox"
vim.opt.termguicolors = true
vim.o.background = "dark"
lvim.plugins = {
  "ellisonleao/gruvbox.nvim",
  disable = lvim.colorscheme ~= "gruvbox",
  config = function()
    vim.cmd [[colorscheme gruvbox]]
  end,
}
```

**Comment by abzcoding** [comment]
just make sure to run `:PackerSync`

**Comment by MaxVerevkin** [comment]
> just make sure to run `:PackerSync`

Ah, that's it, thanks! I, for some reason, thought it was run automatically then saving the config file.

**Comment by MaxVerevkin** [comment]
But the error on reloading is still there.

**Comment by abzcoding** [comment]
> But the error on reloading is still there.

note that instead of
```lua
table.insert(lvim.plugins, {
```
i did put
```lua
lvim.plugins = {
```

**Comment by abzcoding** [comment]
btw you are not running this from dashboard by any chance are you?

**Comment by MaxVerevkin** [comment]
> btw you are not running this from dashboard by any chance are you?

I assure that's the name of the start screen. So, yes.

**Comment by MaxVerevkin** [comment]
> ```lua
> config = function()
>    vim.cmd [[colorscheme gruvbox]]
>  end,
> ```

It even works without these lines

**Comment by abzcoding** [comment]
yeah that is the issue, the start screen buffer is non modifiable, so you should not run any commands from that screen
if you want to reload your config, open a modifiable buffer and then run it

**Comment by MaxVerevkin** [comment]
Hmm, okay.
