### ISSUE TITLE
Telescope errors after selecting a code action

### ISSUE THREAD

**Issue by MaxVerevkin** [LunarVim/LunarVim#2374]
### Problem description

I encountered this error using rust with rust_analyzer, but I don't think this is specific to rust. I do think this is related to lunarvim because the same code action works fine with my previous nvim config.

- Open a rust project
- Create an empty struct, write an incomplete `FromStr` implementation.
- Place the cursor over that impl block.
- Press `<leader>la<cr>`

### LunarVim version

d8628ccd111e0aa9da1ea1bb24c87891069150f8

### Neovim version (>= 0.6.1)

NVIM v0.6.1

### Operating system/version

Linux

### Relevant log output

```shell
I couldn't find anything relevant in the logs.
```

### Screenshots

![image](https://user-images.githubusercontent.com/34583604/159176402-b5aafb0f-9e02-435f-a285-57ef4ae2091c.png)

**Comment by abzcoding** [comment]
this is a telescope related issue, because we've pinned the commit version it might differ from your nvim
can you edit this file `~/.local/share/lunarvim/lvim/lua/lvim/plugins.lua`
and change this line
```diff
-  telescope = "a36a813d5d031e6f5d52b74986915e68130febd9",
+  telescope = "8c7ac1df9dff09630461e99f169047b37b903619",
```
and run a `:PackerSync` and check if your issue is fixed or not

**Comment by MaxVerevkin** [comment]
No, it doesn't fix this

**Comment by abzcoding** [comment]
it is weird since there are a couple of directly related commits in telescope,
like this one https://github.com/nvim-telescope/telescope.nvim/pull/1487

**Comment by abzcoding** [comment]
this is the what we are calling when you hit `<Leader>la`
```lua
function M.code_actions()
  local opts = {
    winblend = 15,
    layout_config = {
      prompt_position = "top",
      width = 80,
      height = 12,
    },
    borderchars = lvim.builtin.telescope.defaults.borderchars,
    border = {},
    previewer = false,
    shorten_path = false,
  }
  local builtin = require "telescope.builtin"
  local themes = require "telescope.themes"
  builtin.lsp_code_actions(themes.get_dropdown(opts))
end
```

**Comment by MaxVerevkin** [comment]
Hm, so I have both configs using the latest version of telescope, and I enable the actions using the same command: `:Telescope lsp_code_actions` (so the code from https://github.com/LunarVim/LunarVim/issues/2374#issuecomment-1073688370) should be irrelevant. Still, I get this error in lunarvim.

**Comment by abzcoding** [comment]
@kylo252 any ideas?

**Comment by kylo252** [comment]
Try calling the native API directly to see if that works
```console
:lua vim.lsp.buf.code_action()
```

**Comment by MaxVerevkin** [comment]
> `:lua vim.lsp.buf.code_action()`

Native (`vim.lsp`) code actions work as expected in both configs.

**Comment by dastein1** [comment]
I've been bitten by this too. Is there any good fix available?

**Comment by captain-neo** [comment]
@dastein1 
I'm using basic code_action now
```lua
lvim.builtin.which_key.mappings.l.a = { "<cmd>lua vim.lsp.buf.code_action()<cr>", "Code Action" }
```

**Comment by abzcoding** [comment]
@MaxVerevkin can you point me towards a sample project on github, so i can debug it locally, cause i cannot reproduce this with my own projects ( golang, python, rust)

**Comment by MaxVerevkin** [comment]
The minimal example I can think of:
```sh
$ cargo new hello
$ cd hello
$ cat src/main.rs
fn main() {
    println!("Hello, world!");
}

struct S;

impl From<()> for S {}
```

My config: https://github.com/MaxVerevkin/dotfiles/blob/9f72d054078a3b84d7fa34aec5325684a9d2f2f6/lvim/.config/lvim/config.lua

Demo: (by the way, I just realized it works if I go to normal mode before pressing enter)

https://user-images.githubusercontent.com/34583604/160120815-7969191f-0a05-4f5e-bb79-8ae9dc198409.mp4

**Comment by abzcoding** [comment]
yep still cannot reproduce it 🤔 
![Mar-25-2022 17-05-17](https://user-images.githubusercontent.com/10992695/160121937-8cb18439-6bce-41c6-bb7a-8f28daf1d5fd.gif)


i'll work on it later tonight, hopefully i can pinpoint the issue

**Comment by abzcoding** [comment]
one quick note though, i do have https://github.com/simrat39/rust-tools.nvim

**Comment by alealv** [comment]
Hi, I'm having the same issue and I'm using only rust-analyzer.

**Comment by daniel-vera-g** [comment]
I don't think this issue is rust related. Experiencing  the same behaviour also with Go, Lua and Typescript.
Getting the same error message, but as already mentioned switching to normal mode + enter works. Now also using the basic code action workaround.

**Comment by abzcoding** [comment]
can you guys check if adding this to your config changes anything or not?
```lua
local actions = require "telescope.actions"
lvim.builtin.telescope.defaults.mappings.i["<CR>"] = actions.select_default
```

**Comment by MaxVerevkin** [comment]
@abzcoding this fixes the error :+1:
