### ISSUE TITLE
Powershell installing error.

### ISSUE THREAD

**Issue by yusufalikaraca0** [LunarVim/LunarVim#2375]
### Problem description

I get an error when I try to install my lunarvi with powershell.

### LunarVim version

1.1.2

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Windows 11

### Relevant log output

```shell
Attempting to install dependency [make] with winget
[ERROR]: Unable to find dependency [make]
Please install it first and re-run the installer. I get an error
```

### Screenshots

![image](https://user-images.githubusercontent.com/90636465/159177746-4692bcd7-b7bf-4bfc-a52e-1f0987459571.png)

**Comment by ahsan-a** [comment]
installing make from here worked for me: http://gnuwin32.sourceforge.net/packages/make.htm
gnuwin32 is a port of tools with a gnu license for windows.

**Comment by ahsan-a** [comment]
- does the make command exist?
- What happens when you run the install command?

**Comment by ahsan-a** [comment]
I got that error too, I haven't looked into it and I'm not sure why. lvim should work after terminal restart and running `:PackerInstall`, but i think it might be worth creating an issue for that, and maybe closing this. :)

**Comment by kylo252** [comment]
> but i think it might be worth creating an issue for that, and maybe closing this. :)

@ahsan-a, I sadly was not able to get `PackerSync` working in headless mode even after a lot of effort, see https://github.com/LunarVim/LunarVim/pull/2330#issuecomment-1063117697

My theory is that it's related to the fact that autocmds _always_ require forward slashes regardless of the platform, and headless mode complicates things further, and I can't even run any unit-tests for windows either... :cry: 

I'd really appreciate some support and/or ideas of how to solve these kinds of issues!

**Comment by itsrxmmy** [comment]
i got this too. in the website it said to install node js, npm, and cargo (or u can install rust completely). so i did that and didnt get that error

**Comment by reiend** [comment]
I fix the problem by installing make using chocolatey, 
choco install make
you can also use scoop

**Comment by kylo252** [comment]
> i got this too. in the website it said to install node js, npm, and cargo (or u can install rust completely). so i did that and didnt get that error

@itsrxmmy, the website is probably only listing dependencies for linux/macos where `make` is readily available

> I got this error too, error was fixed by installing make using chocolatey, choco install make you can also use scoop

@reiend, weird, I thought it should've been possible to install it using the `GnuWin32.Make` moniker

![image](https://user-images.githubusercontent.com/59826753/161298725-ff178470-0f2e-41f7-a2cb-518d947c04b4.png)

**Comment by reiend** [comment]
@kylo252 yeah weird, but after some searching I found out that GnuWin32 only works on some specific version of windows.
for more info refer -> http://gnuwin32.sourceforge.net/
there's also a discussion here for alternatives -> https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows

**Comment by kylo252** [comment]
@reiend, looks like we might be forced to require bootstrapping msys2 first. I was hoping winget is able to handle this, there's even a neovim package coming soon.

**Comment by crstnmac** [comment]
`scoop install make`

**Comment by hopezh** [comment]
> `scoop install make`

The suggestion above solved the problem I encountered: Unable to install LunarVim in PowerShell 7 (x64). PowerShell shuts down after seeing LunarVim logo briefly while running the installation command.

**Comment by bart-b8** [comment]
> ![image](https://user-images.githubusercontent.com/90636465/159334397-6502fcb2-1e9e-4d01-af5d-f67e77c2f703.png) i installed but still not working

After `cmake` is installed, you set an Alias so that `make` will actually call `cmake` 
Use : 
`Set-Alias -Name make -Value cmake`
I set this in my profile and it worked after that. 

Hope this helps

I got some weird stuff trying to use `winget install make` so I'm not going that direction again.

**Comment by lschiavini** [comment]
> I got this error too, error was fixed by installing make using chocolatey, choco install make you can also use scoop

Thanks!!! That was the only thing that helped

**Comment by ramialkaro** [comment]
Manage to resolve issues and install make using a scoop

```
scoop install make
```

**Comment by beppvis** [comment]
yep scoop install make works 100%

**Comment by WasathTheekshana** [comment]
1. Install ```chocolatey``` using this think https://chocolatey.org/
2. Run terminal as admin
3. Enter ```choco install make``` in terminal

**Comment by byueng** [comment]
reboot your powershell with administrator

**Comment by Can-Kar** [comment]
Be sure to add directory which contains make.exe to system PATH variables. Worked after adding it for me.
