### ISSUE TITLE
Database connect and management.

### ISSUE THREAD

**Issue by Nojipiz** [LunarVim/LunarVim#2387]
### Feature Description

A cool feature for Lunarvim is the database management, a kind of SQL Script in Dbeaver, where you can connect to the database and write querys and basic things of the db.

It's a hard function, but it can make the difference between Lunarvim and the other Ide-layers of Neovim

### Describe the alternatives you have considered

I have seen some utils to connect nvim to a database but it might be an extra point for Lunarvim.

### Support information

I 'm thinking in something like this, https://github.com/dinhhuy258/vim-database

**Comment by abzcoding** [comment]
I'm using https://github.com/kristijanhusak/vim-dadbod-ui and vim-dadbod-completion in my config

**Comment by Nojipiz** [comment]
Dadbod ui makes sense for me, i cannot connect my oracle database, but it works fine in mysql and postgres.
Thank you, this change isn't necessary
