### ISSUE TITLE
lvim.colorschema invalid

### ISSUE THREAD

**Issue by angryheng** [LunarVim/LunarVim#2388]
### Problem description

I installed a theme and then configured lvim.colorschema in config.lua , but it didn't take effect.

### LunarVim version

rolling

### Neovim version (>= 0.6.1)

nightly

### Operating system/version

windows11 wsl2 ubuntu20.04

### Relevant log output

```shell
no problem
```

### Screenshots

I installed a theme and then configured lvim.colorschema in config.lua , but it didn't take effect.

**Comment by Rongjianying** [comment]
`lvim.colorstheme` do not work for me either.
nvim version: v0.7.0-dev+1280-gf2e5f509
lvim version: stable

**Comment by cpea2506** [comment]
A temporarily fix is you will set `lvim.colorscheme="your theme` as normally. Then in your `lvim.plugins` where your theme plugin were put, setup theme config function like below

<img width="328" alt="Screen Shot 2022-03-25 at 15 32 29" src="https://user-images.githubusercontent.com/42694704/160089776-3d130a0b-7ab1-435a-b08f-aaf633506372.png">

or 

<img width="368" alt="Screen Shot 2022-03-25 at 16 06 48" src="https://user-images.githubusercontent.com/42694704/160090196-59924553-de6c-4a73-a791-aa837c03ca7f.png">

**Comment by abzcoding** [comment]
gonna be fixed via https://github.com/LunarVim/LunarVim/pull/2392
