### ISSUE TITLE
Doesn't work lsp rename on erlang

### ISSUE THREAD

**Issue by ivano9** [LunarVim/LunarVim#2389]
### Problem description

Just try to rename a function with lsp 

### LunarVim version

master-23feb96

### Neovim version (>= 0.6.1)

NVIM v0.6.1

### Operating system/version

No LSB modules are available. Distributor ID:	Ubuntu Description:	Ubuntu 21.10 Release:	21.10 Codename:	impish

### Affected language servers

erlangls

### Steps to reproduce

Put cursor over name of a function
hit: space -> l -> r

### Actual behavior

show in the status bar:
Output: LSP[erlangls][Info] Method not implemented: textDocument/prepareRename

### Expected behavior

give me a input for introduce the new name of the function and then after press enter the editor change the old name to the new name of function over all file.

### log and support info

```shell
LSP INFO
----------
` Language client log: /home/iroot/.cache/nvim/lsp.log
 Detected filetype:   erlang
 
 1 client(s) attached to this buffer: 
 
 Client: erlangls (id: 1, pid: 20220, bufnr: [1])
 	filetypes:       erlang
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             erlang_ls
 
 Configured servers list: erlangls`
---------

Lvim Info
---------
`        Buffer info
        * filetype:                erlang
        * bufnr:                   1
        * treesitter status:       inactive
        
        Active client(s)
        * name:                      erlangls
        * id:                        1
        * supported filetype(s):     erlang
        * attached buffers:          1
        * root_dir pattern:          1
        * capabilities:              document_symbol  | call_hierarchy           | document_highlight
                                     find_references  | text_document_open_close | completion
                                     goto_definition  | code_lens                | implementation
                                     hover            | execute_command          | code_action
                                     workspace_symbol | rename                   | document_formatting
        
        
        
        Formatters info
        * Active: 
        * Supported: erlfmt
        
        Linters info
        * Active: 
        * Supported: []
        
        Code actions info
        * Active: `
--------
Messages
---------
`LSP[erlangls][Info] Erlang LS (in Documents), version: 0.0.0+build.1.refe12f90c, OTP version: 24
LSP[erlangls][Info] Method not implemented: textDocument/prepareRename
LSP[erlangls][Info] Method not implemented: textDocument/prepareRename
LSP[erlangls][Info] Method not implemented: textDocument/prepareRename
12 lines yanked
29 lines yanked`

-----------
Checkhealth
-----------
`
LSP INFO
----------
` Language client log: /home/iroot/.cache/nvim/lsp.log
 Detected filetype:   erlang
 
 1 client(s) attached to this buffer: 
 
 Client: erlangls (id: 1, pid: 20220, bufnr: [1])
 	filetypes:       erlang
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             erlang_ls
 
 Configured servers list: erlangls`
---------

Lvim Info
---------
`        Buffer info
        * filetype:                erlang
        * bufnr:                   1
        * treesitter status:       inactive
        
        Active client(s)
        * name:                      erlangls
        * id:                        1
        * supported filetype(s):     erlang
        * attached buffers:          1
        * root_dir pattern:          1
        * capabilities:              document_symbol  | call_hierarchy           | document_highlight
                                     find_references  | text_document_open_close | completion
                                     goto_definition  | code_lens                | implementation
                                     hover            | execute_command          | code_action
                                     workspace_symbol | rename                   | document_formatting
        
        
        
        Formatters info
        * Active: 
        * Supported: erlfmt
        
        Linters info
        * Active: 
        * Supported: []
        
        Code actions info
        * Active: `
--------
Messages
---------
`LSP[erlangls][Info] Erlang LS (in Documents), version: 0.0.0+build.1.refe12f90c, OTP version: 24
LSP[erlangls][Info] Method not implemented: textDocument/prepareRename
LSP[erlangls][Info] Method not implemented: textDocument/prepareRename
LSP[erlangls][Info] Method not implemented: textDocument/prepareRename
12 lines yanked
29 lines yanked`
`
```

### Screenshots

![image](https://user-images.githubusercontent.com/43305758/160040243-c72f8fcf-62dc-4514-b8e8-ab55ff6cfe59.png)

**Comment by abzcoding** [comment]
can you point me towards a sample erlang project somewhere on github, so i can test it locally?

**Comment by ivano9** [comment]
Here are alot of proyects written in erlang https://github.com/Leapsight

**Comment by abzcoding** [comment]
btw can you open an erlang file and then run 
```vim
:LvimInfo
```
and take a screenshot

**Comment by abzcoding** [comment]
i think this is the issue
```
 * treesitter status:       inactive
``` 

somehow treesitter is not activating, and that might cause the erlangls rename issue

**Comment by abzcoding** [comment]
i'll debug this locally and get back to you

**Comment by abzcoding** [comment]
might be related to https://github.com/LunarVim/LunarVim/issues/1759

**Comment by abzcoding** [comment]
btw can you open `~/.cache/nvim/lvim.log` and look for errors or warnings related to erlang and copy some of them here

**Comment by ivano9** [comment]
here are the last lines
`
[START][2022-03-25 10:27:24] LSP logging initiated
[START][2022-03-25 10:31:07] LSP logging initiated
[WARN][2022-03-25 10:31:19] ...lsp/handlers.lua:406	'[2022-03-25T10:31:19.339864-03:00] [warning] Could not read config file: path="/home/iroot/Documents/bondy/erlang_ls.config" class=throw error={yamerl_exception,[{yamerl_parsing_error,error,"Failed to open file \\"/home/iroot/Documents/bondy/erlang_ls.config\\": no such file or directory",undefined,undefined,file_open_failure,undefined,[{error,enoent}]}]} [els_config:consult_config/1 L251] <0.150.0>\n'
[WARN][2022-03-25 10:31:19] ...lsp/handlers.lua:406	'[2022-03-25T10:31:19.340140-03:00] [warning] Could not read config file: path="/home/iroot/Documents/bondy/erlang_ls.yaml" class=throw error={yamerl_exception,[{yamerl_parsing_error,error,"Failed to open file \\"/home/iroot/Documents/bondy/erlang_ls.yaml\\": no such file or directory",undefined,undefined,file_open_failure,undefined,[{error,enoent}]}]} [els_config:consult_config/1 L251] <0.150.0>\n'
[WARN][2022-03-25 10:31:19] ...lsp/handlers.lua:406	"[2022-03-25T10:31:19.569073-03:00] [warning] Elvis error.[Err=enoent] [els_elvis_diagnostics:run/1 L48] <0.185.0>\n"
[WARN][2022-03-25 10:31:19] ...lsp/handlers.lua:406	"[2022-03-25T10:31:19.597028-03:00] [warning] Error finding dependency [module=bondy_auth] [error=enoent] [els_compiler_diagnostics:load_dependency/2 L754] <0.183.0>\n"
[WARN][2022-03-25 10:31:36] ...lsp/handlers.lua:406	"[2022-03-25T10:31:36.887856-03:00] [warning] [Method not implemented] [method=textDocument/prepareRename] [els_methods:not_implemented_method/2 L109] <0.166.0>\n"
`

**Comment by ivano9** [comment]
I remember that this feature was working some time ago.

**Comment by abzcoding** [comment]
> I remember that this feature was working some time ago.

i mean you can always go back to previous releases, since we are pinning the plugin versions

but i'm trying to figure out why is this happening

**Comment by kylo252** [comment]
please verify that this works with a [minimal_lsp.lua](https://github.com/lunarvim/lunarvim/blob/5d08a337faa798b67611a1bba545ff5116579da4/tests/minimal_lsp.lua#L1) config first, you can also just follow the steps https://github.com/neovim/nvim-lspconfig#debugging

**Comment by ivano9** [comment]
Ok, where I add this minimal config on lunar vim?

**Comment by kylo252** [comment]
You use the minimal config with neovim directly, e.g

```sh
nvim -u <path-to>/minimal_lsp.lua
```

**Comment by ivano9** [comment]
> You use the minimal config with neovim directly, e.g
> 
> ```shell
> nvim -u <path-to>/minimal_lsp.lua
> ```

ok I did it, and then run  :LspInstall erlangls, but the lsp is not working, i checked it with :LspInfo and show
![image](https://user-images.githubusercontent.com/43305758/160419444-7b284e92-f886-46e0-837a-c4aca1632a4b.png)

**Comment by ivano9** [comment]
I tested with erlangls and show the same output
![image](https://user-images.githubusercontent.com/43305758/160421006-a6b6a56f-72c8-4c41-9933-988c6be33400.png)

**Comment by ivano9** [comment]
Here the log of lsp server

```
}
[TRACE][2022-03-28 11:32:46] ...lsp/handlers.lua:437    "default_handler"       "window/showMessage"    {
  ctx = '{\n  client_id = 1,\n  method = "window/showMessage"\n}',
  result = {
    message = "Method not implemented: textDocument/prepareRename",
    type = 3
  }
}
[DEBUG][2022-03-28 11:32:46] .../vim/lsp/rpc.lua:454    "rpc.receive"   {
  jsonrpc = "2.0",
  method = "window/logMessage",
  params = {
    message = "[2022-03-28T11:32:46.487427-03:00] [warning] [Method not implemented] [method=textDocument/prepareRename] [els_methods:not_implemented_method/2 L109] <0.166.0>\n",
    type = 2
  }
}
[TRACE][2022-03-28 11:32:46] .../lua/vim/lsp.lua:731    "notification"  "window/logMessage"     {
  message = "[2022-03-28T11:32:46.487427-03:00] [warning] [Method not implemented] [method=textDocument/prepareRename] [els_methods:not_implemented_method/2 L109] <0.166.0>\n",
  type = 2
}
[TRACE][2022-03-28 11:32:46] ...lsp/handlers.lua:437    "default_handler"       "window/logMessage"     {
  ctx = '{\n  client_id = 1,\n  method = "window/logMessage"\n}',
  result = {
    message = "[2022-03-28T11:32:46.487427-03:00] [warning] [Method not implemented] [method=textDocument/prepareRename] [els_methods:not_implemented_method/2 L109] <0.166.0>\n",
    type = 2
  }
}
[WARN][2022-03-28 11:32:46] ...lsp/handlers.lua:406     "[2022-03-28T11:32:46.487427-03:00] [warning] [Method not implemented] [method=textDocument/prepareRename] [els_methods:not_implemented_method/2 L109] <0.166.0>\n"
```

**Comment by ivano9** [comment]
I think the method to be call is this 
https://github.com/erlang-ls/erlang_ls/blob/9eed7d4e865b6ad8a653cb495944bda53bf82db1/apps/els_core/src/els_client.erl#L420

**Comment by kylo252** [comment]
> I tested with minimal lsp config with erlangls and show the same output ![image](https://user-images.githubusercontent.com/43305758/160421006-a6b6a56f-72c8-4c41-9933-988c6be33400.png)

This is an upstream issue then, please open a ticket about it in https://github.com/neovim/nvim-lspconfig/issues
