### ISSUE TITLE
lvim not found after installing zsh and oh my zsh

### ISSUE THREAD

**Issue by jovanmaks** [LunarVim/LunarVim#2396]
### Feature Description

I should probably make a pull request but I'm in a time shortage and newer did it before so i will yust trow it like this as bug and hope someone will take a look.
After i installed zsh and oh my zsh i got lvim not found error.
(using Fedora 35)
Just add:

PATH=$PATH:~/.local/bin
export PATH

in the .zshrc and it should work

**Comment by abzcoding** [comment]
https://www.lunarvim.org/02-after-install.html#add-lvim-to-path

**Comment by GeekyNinja2003** [comment]
@jovanmaks  You're the best ! ;-}
