### ISSUE TITLE
Treesitter not working inside nvim-bqf preview

### ISSUE THREAD

**Issue by williamgoulois** [LunarVim/LunarVim#2399]
### Problem description

I use the plugin [nvim-bqf](https://github.com/kevinhwang91/nvim-bqf)

When I want to see references i use the `gr` go to references to create a quickfix buffer with preview above.

If the file containing the reference is not opened in one of my buffers i don't have treesitter highlighting and i get this error filetype unknown (1st screenshot).

If the file is already opened in a buffer i have correct highlight (2nd screenshot).

### LunarVim version

5d08a33 latest rolling

### Neovim version (>= 0.6.1)

NVIM v0.7.0-dev+1328-gfb5587d2b

### Operating system/version

macOS 11.6

### Affected language servers

tsserver (did not try others)

### Steps to reproduce

1. Open a javascript project
2. Go to references on a function, a component, variable also called in other files that current buffer
3. Select an entry in the quickfix list with the reference in a file not opened in a buffer
4. The preview will not have syntax highlighting and you will get an error `filetype unknown`

### Actual behavior

The preview is not highlighted inside the preview of nvim-bqf

The filetype is maybe not correctly recognized if the file is not opened ?

### Expected behavior

The preview should be correctly highlighted according to filetype

### log and support info

```shell
I don't think that any logs could help here but i can provide them if needed

I have tested with my own config and abzcoding config and got the same bug. (screenshots are with abzcoding config)
```

### Screenshots

No highlight => file not opened
<img width="960" alt="Screenshot 2022-03-26 at 18 10 21" src="https://user-images.githubusercontent.com/37271970/160250182-a459638c-381e-4193-a5b8-c96c59e2b766.png">

Highlight OK => file opened in another buffer
<img width="960" alt="Screenshot 2022-03-26 at 18 11 41" src="https://user-images.githubusercontent.com/37271970/160250202-a6fe514d-21e2-48be-b124-7442ff7262cd.png">

nvim-bqf config (from 
<img width="1322" alt="Screenshot 2022-03-26 at 18 16 29" src="https://user-images.githubusercontent.com/37271970/160250349-0414d693-87f4-4972-995c-7e311847ae2f.png">
abzcoding config):

**Comment by williamgoulois** [comment]
This bug is common to all filetypes. I managed to trigger it inside lunarvim source code

<img width="827" alt="Screenshot 2022-03-26 at 18 33 07" src="https://user-images.githubusercontent.com/37271970/160250835-573d3208-b10d-4c75-809f-479785718d90.png">

**Comment by abzcoding** [comment]
yeah i have this issue as well, i'll work on it tonight or tomorrow

**Comment by abzcoding** [comment]
it seems to be coming from `filetype.nvim`
https://github.com/kevinhwang91/nvim-bqf/issues/43

**Comment by abzcoding** [comment]
without filetype.nvim
<img width="751" alt="Screen Shot 2022-03-26 at 10 44 37 PM" src="https://user-images.githubusercontent.com/10992695/160252141-4898af88-3c9f-4bf8-af78-babec4a8f352.png">

with filetype.nvim
<img width="778" alt="Screen Shot 2022-03-26 at 10 45 05 PM" src="https://user-images.githubusercontent.com/10992695/160252146-070a3b7c-86bb-4044-9dc1-447b2650ad99.png">

also this -> https://github.com/nathom/filetype.nvim/issues/80

**Comment by abzcoding** [comment]
and this is probably why this happens
 `filetype.nvim` does this https://github.com/nathom/filetype.nvim/blob/25b5f7e5314d5e7739be726860253c67f7e513bf/lua/filetype/init.lua#L104
<img width="495" alt="Screen Shot 2022-03-26 at 10 53 41 PM" src="https://user-images.githubusercontent.com/10992695/160252389-1afe1073-c500-4e74-ac04-100be711646b.png">

which translates to this if used with nvim-bqf
<img width="344" alt="Screen Shot 2022-03-26 at 10 53 31 PM" src="https://user-images.githubusercontent.com/10992695/160252387-e3ea503b-ac12-49fd-a129-293f2b153064.png">

so it cannot identify the syntax of (not currently open) files

**Comment by williamgoulois** [comment]
Oh nice you found the culprit quickly !
Do we really need filetype.nvim ? I saw on their repo page that it's only a replacement for quicker startup time ?

**Comment by abzcoding** [comment]
> Oh nice you found the culprit quickly !
> Do we really need filetype.nvim ? I saw on their repo page that it's only a replacement for quicker startup time ?

yeah i'm trying to find the way to make them to work nicely together 🤞

**Comment by abzcoding** [comment]
can you test if this fixes your issue or not?
https://github.com/abzcoding/lvim/commit/6fa727f356313c5fc752763c969dc89cc4718e29

**Comment by williamgoulois** [comment]
> can you test if this fixes your issue or not? [abzcoding/lvim@6fa727f](https://github.com/abzcoding/lvim/commit/6fa727f356313c5fc752763c969dc89cc4718e29)

Yes this works !

**Comment by abzcoding** [comment]
to wrap this up, i've done a PR 
https://github.com/nathom/filetype.nvim/pull/82

but in the meantime you can either 
1. keep `filetype.nvim` or `nvim-bqf`, not both of them
2. use my branch
```lua
"abzcoding/filetype.nvim",
branch="fix/qf-syntax",
```
instead of
```lua
"nathom/filetype.nvim",
```

**Comment by williamgoulois** [comment]
Thanks a lot man 🚀
