### ISSUE TITLE
Lualine color theme gaps

### ISSUE THREAD

**Issue by bob3000** [LunarVim/LunarVim#2403]
### Problem description

Since I last updated lvim there are some gaps in the lualine where the color doesn't match the rest of the line. The background seems to transparent. I tried different color schemes but I always get the same behaviour. Does anybody have the same issue?

### LunarVim version

7807f147c192fdb6aec7659a3098b4bf31852fcd

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Arch Linux

### Relevant log output

```shell
nil
```

### Screenshots

![Screenshot from 2022-03-28 13-57-33](https://user-images.githubusercontent.com/1550574/160393867-bec12829-cbd4-4c3d-b653-b10c9f8b3359.png)
![Screenshot from 2022-03-28 13-45-29](https://user-images.githubusercontent.com/1550574/160393879-0e311e31-28b6-4dc2-a1b2-508540dd2757.png)

**Comment by chsjr1996** [comment]
Hello @bob3000, same issue here.

I've modified `.local/share/lunarvim/lvim/lua/lvim/core/lualine/components.lua` file, removing `color` key from "diagnostics", "filetype" and "diff" components and now color theme is respected.

I don't know the source of this problem, but I believe that is related with 'lualine' plugin theme colors detection. Others components sections has empty `color` keys, but this bug only occurs in some sections (like "diagnostic").

### Modification example:

**Before**
```
  diagnostics = {
    "diagnostics",
    sources = { "nvim_diagnostic" },
    symbols = { error = " ", warn = " ", info = " ", hint = " " },
    color = {},
    cond = conditions.hide_in_width,
  },
```

**After**
```
  diagnostics = {
    "diagnostics",
    sources = { "nvim_diagnostic" },
    symbols = { error = " ", warn = " ", info = " ", hint = " " },
    cond = conditions.hide_in_width,
  },
```

![image](https://user-images.githubusercontent.com/33254540/163404503-d1235ea4-8b5a-4dd9-89dc-9d459af74693.png)

**Comment by bob3000** [comment]
@chsjr1996 Good job. I can confirm that your changes solve the problem. The same applies for some other sections. In my case the sections `diff` and `filetype` are affected as well. Maybe you could open a PR?!

**Comment by chsjr1996** [comment]
@bob3000 of course! PR created #2465
