### ISSUE TITLE
starting and running lunarvim in nvim-qt/fvim ...

### ISSUE THREAD

**Issue by kraxli** [LunarVim/LunarVim#2405]
running neovim in a Gui like nvim-qt, fvim, ... on Windows 10 picks the config up at ~/AppData/Local/nvim by default but not ~/AppData/Local/lvim. 
How can I run lunarvim in a Gui on Windows 10?

**Comment by abzcoding** [comment]
for fvim you can use 
```
 --nvim path-to-program      Use an alternative nvim program
 ```
and for nvim-qt you can use
```
--nvim {path_to_nvim}
```

for more info check their readme

**Comment by matthewfee** [comment]
quick question, where does this command go?

**Comment by upperxcode** [comment]
> @abzcodingpergunta rápida, para onde vai esse comando?
apenas um exemplo:
nvim-qt . --nvim ~/.local/bin/lvim
