### ISSUE TITLE
lsp-Ltex not attached to markdown file (and other type too)

### ISSUE THREAD

**Issue by grimgort** [LunarVim/LunarVim#2406]
### Problem description

lsp-Ltex not attached to markdown file (and other type too)

### LunarVim version

7807f14

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

windows 10

### Affected language servers

ltex

### Actual behavior

*

### log and support info

```shell
Language client log: D:\ftarroux\AppData\Local\Temp\nvim\lsp.log
 Detected filetype:   markdown
 
 0 client(s) attached to this buffer: 
 
 2 active client(s) not attached to this buffer: 
 
 Client: clangd (id: 1, pid: 3108, bufnr: [22])
 	filetypes:       c, cpp, objc, objcpp
 	autostart:       true
 	root directory:  D:/ftarroux/Documents/FRED/BaseGit/matisse_fred
 	cmd:             clangd --all-scopes-completion --suggest-missing-includes --background-index --pch-storage=disk --cross-file-rename --log=info --completion-style=detailed --enable-config --clang-tidy
 
 Client: powershell_es (id: 2, pid: 16712, bufnr: [40])
 	filetypes:       ps1
 	autostart:       true
 	root directory:  D:/ftarroux/Documents/FRED/BaseGit/matisse_fred
 	cmd:             pwsh -NoLogo -NoProfile -Command D:\ftarroux\AppData\Roaming\nvim-data\lsp_servers\powershell_es/PowerShellEditorServices/Start-EditorServices.ps1 -BundledModulesPath D:\ftarroux\AppData\Roaming\nvim-data\lsp_servers\powershell_es -LogPath D:\ftarroux\AppData\Local\Temp\nvim/powershell_es.log -SessionDetailsPath D:\ftarroux\AppData\Local\Temp\nvim/powershell_es.session.json -FeatureFlags @() -AdditionalModules @() -HostName nvim -HostProfileId 0 -HostVersion 1.0.0 -Stdio -LogLevel Normal
 
 Configured servers list: clangd, powershell_es
```

### Screenshots

![image](https://user-images.githubusercontent.com/44238325/161019283-157fadac-c874-4bc1-ae3c-a32c79bb048c.png)
![image](https://user-images.githubusercontent.com/44238325/161019367-04fb42e4-928c-4d90-9567-252a572328f4.png)

**Comment by abzcoding** [comment]
ltex is one of our ignored servers
https://github.com/LunarVim/LunarVim/blob/7807f147c192fdb6aec7659a3098b4bf31852fcd/lua/lvim/lsp/config.lua#L79-L81
you have to set it up yourself as mentioned in [the docs](https://www.lunarvim.org/languages/#server-setup)
<img width="803" alt="Screen Shot 2022-03-31 at 3 31 29 PM" src="https://user-images.githubusercontent.com/10992695/161040680-f00d3e50-b48a-4b4a-8cf4-669291ce8445.png">
