### ISSUE TITLE
Lunarvim just crash after sometime

### ISSUE THREAD

**Issue by expoure** [LunarVim/LunarVim#2407]
### Problem description

I'm programming in typescript, so, i'm using tsserver + prettier + eslint...
I dont if its because one of this, but when i use nvim only i'm facing the same problem...

my formateer:

```
  local formatters = require "lvim.lsp.null-ls.formatters"
  formatters.setup {
        { command = "prettier", filetypes = { "typescript", "javascript" } },
  }
```

```
-- -- set additional linters
local linters = require "lvim.lsp.null-ls.linters"
linters.setup {
    { command = "eslint", filetypes = { "typescript", "javascript" } },
}
```

### LunarVim version

master-23feb96

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Archlinux

### Relevant log output

```shell
Just crash
```

**Comment by abzcoding** [comment]
can you please take an screenshot of what that crash looks like
also please check the following log files for more clues

```
~/.cache/nvim/lsp.log
~/.cache/nvim/lvim.log
~/.cache/nvim/log
```

**Comment by expoure** [comment]
lsp.log:
`[START][2022-03-31 08:59:34] LSP logging initiated
[START][2022-03-31 09:00:12] LSP logging initiated
[WARN][2022-03-31 09:00:36] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 09:00:36] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 09:00:43] LSP logging initiated
[START][2022-03-31 09:01:01] LSP logging initiated
[WARN][2022-03-31 09:11:09] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 09:11:09] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 09:16:34] LSP logging initiated
[WARN][2022-03-31 09:19:35] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 09:19:35] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 09:20:41] LSP logging initiated
[START][2022-03-31 09:26:41] LSP logging initiated
[WARN][2022-03-31 09:38:55] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 09:38:55] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 09:45:32] LSP logging initiated
[WARN][2022-03-31 09:45:39] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 09:45:39] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 09:46:25] LSP logging initiated
[WARN][2022-03-31 09:49:27] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 09:49:27] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 09:54:43] LSP logging initiated
[WARN][2022-03-31 09:55:42] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 09:55:42] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 09:59:37] LSP logging initiated
[WARN][2022-03-31 10:03:18] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 10:03:18] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 10:11:31] LSP logging initiated
[WARN][2022-03-31 10:13:18] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 10:13:18] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 10:15:27] LSP logging initiated
[WARN][2022-03-31 10:15:47] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 10:15:47] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 10:16:04] LSP logging initiated
[START][2022-03-31 10:16:56] LSP logging initiated
[WARN][2022-03-31 10:17:00] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 10:17:00] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 10:18:13] LSP logging initiated
[WARN][2022-03-31 10:18:17] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 10:18:17] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 10:20:31] LSP logging initiated
[WARN][2022-03-31 10:20:40] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 10:20:40] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 10:20:53] LSP logging initiated
[WARN][2022-03-31 10:21:02] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 10:21:02] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 10:21:07] LSP logging initiated
[START][2022-03-31 10:21:37] LSP logging initiated
[START][2022-03-31 11:16:35] LSP logging initiated
[START][2022-03-31 11:17:35] LSP logging initiated
[START][2022-03-31 11:17:55] LSP logging initiated
[START][2022-03-31 11:21:53] LSP logging initiated
[START][2022-03-31 15:26:00] LSP logging initiated
[START][2022-03-31 15:26:26] LSP logging initiated
[START][2022-03-31 15:52:04] LSP logging initiated
[START][2022-03-31 15:30:27] LSP logging initiated
[WARN][2022-03-31 15:53:07] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 15:53:07] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 16:17:03] LSP logging initiated
[WARN][2022-03-31 16:17:06] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[WARN][2022-03-31 16:17:06] .../lua/vim/lsp.lua:751	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[START][2022-03-31 16:23:19] LSP logging initiated
[START][2022-03-31 16:24:12] LSP logging initiated
[START][2022-03-31 16:27:23] LSP logging initiated
`
lvim.log
`09:45:27 [WARN ] lvim: "Invalid configuration: /home/dyonatha/.config/lvim/config.lua:124: attempt to index global 'code_actions' (a nil value)" file="lua/lvim/config/init.lua", line=105
09:45:32 [WARN ] lvim: "Invalid configuration: /home/dyonatha/.config/lvim/config.lua:124: attempt to index global 'code_actions' (a nil value)" file="lua/lvim/config/init.lua", line=105
09:53:48 [WARN ] lvim: "Invalid configuration: ...e/pack/packer/start/null-ls.nvim/lua/null-ls/sources.lua:208: filetypes: expected table, got string" file="lua/lvim/config/init.lua", line=105
09:54:00 [WARN ] lvim: "Invalid configuration: ...e/pack/packer/start/null-ls.nvim/lua/null-ls/sources.lua:208: filetypes: expected table, got string" file="lua/lvim/config/init.lua", line=105
`

nvim/log: nothing.

**Comment by abzcoding** [comment]
can you use `prettierd` instead of `prettier` and `eslint_d` instead of `eslint` and see if that helps anything or not

also, have you fixed this line in your config?
```lua
Invalid configuration: /home/dyonatha/.config/lvim/config.lua:124: attempt to index global 'code_actions'
```

**Comment by expoure** [comment]
> can you use `prettierd` instead of `prettier` and `eslint_d` instead of `eslint` and see if that helps anything or not
> 
> also, have you fixed this line in your config?
> 
> ```lua
> Invalid configuration: /home/dyonatha/.config/lvim/config.lua:124: attempt to index global 'code_actions'
> ```

Yes, i've been fixed this issue before freezing

**Comment by abzcoding** [comment]
well try this
> can you use `prettierd` instead of `prettier` and `eslint_d` instead of `eslint` and see if that helps anything or not

also can you run `node -v`

**Comment by expoure** [comment]
My node version is 17.8.0.
Later during work I will test the settings with prettierd and eslint_d, so, after a report if everything went well or not.

**Comment by abzcoding** [comment]
@kylo252 any ideas what might cause the crash?

**Comment by zalegrala** [comment]
I'm seeing crashes this week also.  Three so far, periodically opening a new Go file.  But then after the crash I can open that file without issue.  I only have prettier enabled for yaml files.

**Comment by abzcoding** [comment]
> I'm seeing crashes this week also. Three so far, periodically opening a new Go file. But then after the crash I can open that file without issue. I only have prettier enabled for yaml files.

have you noticed anything in your log files?
```
~/.cache/nvim/lsp.log
~/.cache/nvim/lvim.log
~/.cache/nvim/log
```

**Comment by expoure** [comment]
The problem happened again, but it didn't freeze the computer. this time I didn't upload the docker containers, but I opened a terminal with htop to monitor the behavior while working. Sometimes the memory would just jump from 30% to 70% for two or three seconds, too fast to identify if the problem is eslint, prettie or lsp.

**Comment by kylo252** [comment]
> @kylo252 any ideas on what might cause the crash?

It could be a treesitter issue, please run `TSUpdate` manually.

**Comment by expoure** [comment]
[off] btw, how can i create a dir in tree explore? I can not figure out the command.

**Comment by kylo252** [comment]
> [off] btw, how can i create a dir in tree explore? I can not figure out the command.

`:h nvim-tree-mappings`

---

I just noticed you mentioned this was running in docker, does this only happen in a container? You should also test with a minimal configuration to see if you can reproduce the issue.

**Comment by expoure** [comment]
> > [off] btw, how can i create a dir in tree explore? I can not figure out the command.
> 
> `:h nvim-tree-mappings`
> 
> I just noticed you mentioned this was running in docker, does this only happen in a container? You should also test with a minimal configuration to see if you can reproduce the issue.

There is no option to create a folder, just a file by rpessing "a". In nvim-tree documentation to create a folder has a command "mk_dir" or "mkdir". The "a" keymap run a command "create".

I using lvim in my archlinux, but working with docker (my project and services run docker, not lvim).

**Comment by kylo252** [comment]
If this happens with a minimal configuration, then I'm afraid that there isn't much that can be done about it here, since it would be an upstream issue. It could very well be that tsserver (or eslint) is trying to parse a very large project, but it could also be any number of things, e.g. some memory-leak somewhere.

**Comment by abzcoding** [comment]
Add / at the end of the filename after hitting 'a' it will automatically create a folder instead of file

**Comment by expoure** [comment]
This problem seems to be related... after closing lvim (it also happens in nvim using the null-ls plugin) eslint_d keeps running on the system

https://user-images.githubusercontent.com/12136268/162029036-d6994151-be17-42e9-bbd9-9f088bf376b7.mp4

**Comment by abzcoding** [comment]
> This problem seems to be related... after closing lvim (it also happens in nvim using the null-ls plugin) eslint_d keeps running on the system
> 
>  simplescreenrecorder-2022-04-06_14.03.36.mp4

maybe we need to report this upstream ( https://github.com/jose-elias-alvarez/null-ls.nvim )
