### ISSUE TITLE
Lualine progress bars are not aligned

### ISSUE THREAD

**Issue by shenhai-ran** [LunarVim/LunarVim#2413]
https://github.com/LunarVim/LunarVim/blob/7807f147c192fdb6aec7659a3098b4bf31852fcd/lua/lvim/core/lualine/components.lua#L147

The fifth bar progress symbol is not aligned with others. It is slightly lower. 
It is not a big deal, but do you think you could fixed? Or where can I find such resources?

Thanks!

**Comment by abzcoding** [comment]
![3x](https://user-images.githubusercontent.com/10992695/161333373-1f731319-8a9d-428d-a757-16b971c0092f.gif)

**Comment by abzcoding** [comment]
they are basically two chars attached, they come from strings like this
```
▆▊█▋▄ ▌ ▄▌▍█▆ ▋▌ ▆▌▊▍█▊█ ▇▉▉▋▌▉▌▇ ▇▅▌▆▉▌▋ ▅▉▇██▌ ▋█▅▇▇▅ ▍▇▌▅ ▅█▉▍▋▅ ▊▌ █▄▋▉▋▊▄ ▅▍█▋▅▊▍▅ ▊▉▅▇▇▉█▌ ▄▉▄▊▋▍ ▍▄▄▌█▄ █▅▆▊▉▇▆ ▅█
```

as you can see, except the first one, they are all aligned
<img width="1756" alt="Screen Shot 2022-05-03 at 7 08 20 AM" src="https://user-images.githubusercontent.com/10992695/166396935-b026572a-a4f1-49bf-95f2-10c376c2f3ab.png">
