### ISSUE TITLE
powershell create an alias error

### ISSUE THREAD

**Issue by coolusernameforgit** [LunarVim/LunarVim#2424]
### Problem description

1. i've run the script in powershell 7.2.1 :
> Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression

2. checked nodejs and python dependencies
3. wanted to create an alias for powershell profile but faced an error which described in log output 

### LunarVim version

none

### Neovim version (>= 0.6.1)

NVIM v0.6.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 compiled by runneradmin@fv-az152-430 

### Operating system/version

windows10 19044.1586

### Relevant log output

```shell
Would you like to create an alias inside your Powershell profile?
(This enables you to start lvim with the command 'lvim') [y]es or [n]o (default: no): y
Add-Content:
Line |
 270 |      Add-Content -Path $PROFILE -Value $("Set-Alias lvim $lvim_bin")
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find a part of the path 'C:\Users\user1\Documents\PowerShell\Microsoft.PowerShell_profile.ps1'.
```

**Comment by RaphaelKhy** [comment]
I have the same issue as OP after  #2404.

I'm using NVIM v0.6.1, Powershell 7.2.2, and Windows 11

**Log Output**
```
Would you like to create an alias inside your Powershell profile?
(This enables you to start lvim with the command 'lvim') [y]es or [n]o (default: no): y
Add-Content:
Line |
 270 |      Add-Content -Path $PROFILE -Value $("`r`nSet-Alias lvim $lvim_bin …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find a part of the path 'C:\Users\rapha\Documents\PowerShell\Microsoft.PowerShell_profile.ps1'.
```

I think the issue is caused because the path: `C:\Users\rapha\Documents\PowerShell` doesn't exist. 
Instead this path exists: `C:\Users\rapha\Documents\WindowsPowerShell` 

Note: I preformed a default installation of Powershell using the x-64 installer and did not rename the directory.

**Comment by kylo252** [comment]
> I have the same issue as OP after #2404
> 
> I'm using NVIM v0.6.1, Powershell 7.2.2, and Windows 11
> 
> I think the issue is caused because the path: `C:\Users\rapha\Documents\PowerShell` doesn't exist. Instead this path exists: `C:\Users\rapha\Documents\WindowsPowerShell`
> 
> Note: I preformed a default installation of Powershell using the x-64 installer and did not rename the directory

Isn't this a PowerShell bug at this point tho? It's not like the installer is setting `$PROFILE` either 🤷 

The assumption is that a user already has this file, otherwise, It would be good if there's a shorthand for creating this file (and its parent folder).
