### ISSUE TITLE
Tab commands (`:tabnext`, `:tabprev`) do not work for auto-created tabs when opening files

### ISSUE THREAD

**Issue by albertas** [LunarVim/LunarVim#2427]
### Problem description

Steps to reproduce the behaviour:
1. Open file A. (a tab is created for this file)
2. Open file B. (another tab is created)
3. Execute command `:tabnext` or `:tabprev` to switch to another file/tab.

Expected behaviour: tab of another file gets opened.

Observed behaviour: nothing happens.

### LunarVim version

stable (3abb0a7)

### Neovim version (>= 0.6.1)

NVIM v0.6.1

### Operating system/version

Ubuntu 20.04

### Relevant log output

```shell
`:checkhealth` shows :OK:
```

**Comment by abzcoding** [comment]
we are using [bufferline.nvim](https://github.com/akinsho/bufferline.nvim) which might mess with this, you can either disable that plugin or use these keybindings
https://github.com/LunarVim/LunarVim/blob/fcb16c0961cd2b6ca522a0b2088ad663fd605b85/lua/lvim/keymappings.lua#L58-L61

or even play with [bufferline settings](https://github.com/LunarVim/LunarVim/blob/fcb16c0961cd2b6ca522a0b2088ad663fd605b85/lua/lvim/core/bufferline.lua#L37) and tune it to your liking, for example
```lua
lvim.builtin.bufferline.options.mode = "buffers", -- set to "tabs" to only show tabpages instead
```

**Comment by albertas** [comment]
Thanks, it really solves my issue.
