### ISSUE TITLE
Code action not working

### ISSUE THREAD

**Issue by expoure** [LunarVim/LunarVim#2428]
### Problem description

When i press <leader>+l+a the LSP Code Actions modal open and when i press enter to resolve the issue an error occurs.

### LunarVim version

master-23feb96

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Archlinux

### Affected language servers

tsserver

### Actual behavior

LSP Code Actions does not work

### log and support info

```shell
Look at screenshot

logs are empty, the screenshot information is from ":message"
```

### Screenshots

![2022-04-06_09-28](https://user-images.githubusercontent.com/12136268/161975210-38a3724e-9685-46bb-b396-b5856345af47.png)

**Comment by engineersamuel** [comment]
I'm seeing the same thing against the latest stable installation

**Comment by abzcoding** [comment]
this has been fixed in `rolling` -> https://github.com/LunarVim/LunarVim/commit/ea0e1f99e7df476638569a10ddcfdff1dbce52dd

@kylo252 we probably should merge rolling into master

**Comment by abzcoding** [comment]
@expoure @engineersamuel 
can you guys pull the latest changes and test it again?
it should be fixed now
