### ISSUE TITLE
Nvim-Dap and :DIInstall

### ISSUE THREAD

**Issue by TheEccentricDuck** [LunarVim/LunarVim#2430]
### Problem description

After you start up LunarVim, type :DIInstall cpppr_vsc, and LunarVim reports that :DIInstall isn't a valid editor command. This is unexpected because the LunarVim docs say that this command can be used to install the CPP debugger, and debuggers for quite a lot of other languages. Checkout this link: https://www.lunarvim.org/languages/c_cpp.html#debugger. Also, when I check the Packer status, it doesn't list nvim-dap as one of the installed packages, even though it is listed in plugins.lua. Can anyone explain this? Thank you very much. 
![image](https://user-images.githubusercontent.com/51841456/162024114-31256614-07a6-4411-ad5f-a49cefedc862.png)
![image](https://user-images.githubusercontent.com/51841456/162024331-304dd69e-e16d-4ac4-bb65-bda9da2c1dcd.png)
![image](https://user-images.githubusercontent.com/51841456/162024481-98a150a3-f81e-48bb-be36-19d730f32754.png)
![image](https://user-images.githubusercontent.com/51841456/162024745-d96d8635-8384-43fe-9355-5147c4f96836.png)
![image](https://user-images.githubusercontent.com/51841456/162024546-76f317b9-82c4-4576-bd21-64fd7af20e64.png)

### LunarVim version

master-46b8aee

### Neovim version (>= 0.6.1)

NVIM v0.6.1

### Operating system/version

5.15.28-1-MANJARO

### Relevant log output

```shell
No relevant log output.
```

**Comment by abzcoding** [comment]
first off this plugin has been deprecated -> https://github.com/Pocco81/DAPInstall.nvim
and we will remove it from lunarvim pretty soon,

also you need to enable dap first
```lua
lvim.builtin.dap.active = true
```

**Comment by TheEccentricDuck** [comment]
I’m really sorry, I’m new to nvim and lvim so I just didn’t know how to fix it, thank you very much.

**Comment by abzcoding** [comment]
> I’m really sorry, I’m new to nvim and lvim so I just didn’t know how to fix it, thank you very much.

no worries mate, feel free to ask your questions there is nothing wrong with that <3

**Comment by TheEccentricDuck** [comment]
Alright, thank you so much for your help! :) I managed to get it working.

**Comment by endlesscpp** [comment]
> Alright, thank you so much for your help! :) I managed to get it working.

Hi, I have enabled dap and DAPInstall, nvim-dap plugins are installed. 
However, LunarVim still report ":DIInstall isn't a valid editor command", could you please help on this?

**Comment by MyraBaba** [comment]
Hi, @abzcoding 

I have the same problem. We loved lunarvim and want to use our C++ and python development projects. What we missed is the debugger.

We cant find a straight way to install debugger step by step.

:DIInstall ccppr_vsc certainly not working.

Best

**Comment by abzcoding** [comment]
@MyraBaba @endlesscpp this issue should be fixed on the `rolling` branch, since we are using the dev branch of dap-buddy in there

can you guys check if that fixes your issues?

**Comment by abzcoding** [comment]
> Hi, @abzcoding I installed rolling branch and still no DIInstall command in editor.
> 
> FYI

did you ran `:PackerSync` or `:LvimSyncCorePlugins` as well?
I'm on the rolling branch and I have the `:DIInstall` command
<img width="162" alt="Screen Shot 2022-05-16 at 5 44 21 PM" src="https://user-images.githubusercontent.com/10992695/168600856-1940f031-c982-4555-ae7f-d241b908ca7e.png">

**Comment by abzcoding** [comment]
please check the output of these commands
```shell
git -C ~/.local/share/lunarvim/lvim rev-parse HEAD
ls -l ~/.local/share/lunarvim/site/pack/packer/start/dap-buddy.nvim
```
<img width="611" alt="Screen Shot 2022-05-16 at 5 45 50 PM" src="https://user-images.githubusercontent.com/10992695/168601032-5154daa9-d509-419a-a69f-2be75bcbdbbe.png">

**Comment by MyraBaba** [comment]
Yes after sync there is DBInstall.

now I am trying to make working c++ debugging...

**Comment by MyraBaba** [comment]
git -C ~/.local/share/lunarvim/lvim rev-parse HEAD
l│aa4c9930d9131c60d7a6f2e9bec8a2f3ba6c4055

ls -l ~/.local/share/lunarvim/site/pack/packer/start/dap-buddy.nvim
no such file

**Comment by abzcoding** [comment]
> Yes after sync there is DBInstall.
> 
> now I am trying to make working c++ debugging...

you can check [my config](https://github.com/abzcoding/lvim/blob/58e6014259937ee99579e9077bb63fdc8a3f1caa/lua/user/dap.lua#L212) or the [nvim-dap documentation](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation)

---

btw you are not on the rolling branch, it seems like you are on the master branch
```shell
git -C ~/.local/share/lunarvim/lvim status
```

**Comment by MyraBaba** [comment]
@abzcoding   I installed with 
LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)

**Comment by abzcoding** [comment]
> @abzcoding I installed with
> LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)

you need to first uninstall the previous one
```shell
bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh
# or
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/uninstall.sh)
```

and then install the new one
```shell
LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)
```

**Comment by MyraBaba** [comment]
git -C ~/.local/share/lunarvim/lvim status
On branch rolling
Your branch is up to date with 'origin/rolling'.

nothing to commit, working tree clean


now on the rolling..

Lets see how much we can roll :)

**Comment by MyraBaba** [comment]
@abzcoding  vimspector vs nvim-dap according to your experience which is learned in the field.?

**Comment by abzcoding** [comment]
> @abzcoding vimspector vs nvim-dap according to your experience which is learned in the field.?

usually people use `nvim-dap` alongside `nvim-dap-ui`

**Comment by MyraBaba** [comment]
@abzcoding  I dont knof if its due to I am almost beginner to nvim/lunarvim or nvim-dap things complicated and assuming that everybody has some background for configuration .

where I need to put the dap.configuration. ? 
there is numerous dap.lua:

> /home/alp2080/.local/share/lunarvim/lvim/lua/lvim/core/dap.lua
/home/alp2080/.local/share/lunarvim/site/pack/packer/start/nvim-dap/lua/dap.lua
/home/alp2080/.local/share/lunarvim/site/pack/packer/start/nvim-dap/plugin/dap.lua

is assuming to put there :

>   dap.configurations.cpp = {
    {
      name = "Launch file",
      type = "codelldb",
      request = "launch",
      program = function()
        return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
      end,
      cwd = "${workspaceFolder}",
      stopOnEntry = true,
    },
  }
  dap.configurations.c = dap.configurations.cpp

or where. 

If I can successfully use neo/lunarvim for c++ /python  I will transfer all the dev to the  lunarvim.  I hope its not and utopia that I believe all dev team more productive if all we transfer to the terminal based work.

Best 
thx for your help

**Comment by abzcoding** [comment]
please do not touch any files under `~/.local/share/lunarvim`
just put your configurations in `~/.config/lvim/config.lua`

for example, put this in your `~/.config/lvim/config.lua`
```lua
local dap = require("dap")
  dap.configurations.cpp = {
    {
      name = "Launch file",
      type = "codelldb",
      request = "launch",
      program = function()
        return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
      end,
      cwd = "${workspaceFolder}",
      stopOnEntry = true,
    },
  }
  dap.configurations.c = dap.configurations.cpp
```

**Comment by MyraBaba** [comment]
Error detected while processing BufWritePost Autocommands for "*":
Error executing vim.schedule lua callback: ...alp2080/.local/share/lunarvim/lvim/lua/lvim/core/dap.lua:28: attempt to index global 'dap' (a nil value
)
stack traceback:
        ...alp2080/.local/share/lunarvim/lvim/lua/lvim/core/dap.lua:28: in function 'config'
        ...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:24: in function 'config'
        ...2080/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:32: in function 'init'
        ...2080/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:137: in function <...2080/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:134
>
        [C]: in function 'wait'
        .../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:125: in function '_wait'
        .../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:143: in function 'run'
        ...ck/packer/start/nvim-tree.lua/lua/nvim-tree/git/init.lua:17: in function 'reload'
        .../start/nvim-tree.lua/lua/nvim-

**Comment by MyraBaba** [comment]
@abzcoding 

Is there any tutorial for newbies for lvim to setup full c++ lunarvim including to debugging ? Best practices .

We are almost giving up due to struggling to setup debugging environment..   

Best
