### ISSUE TITLE
Tree explore does not match microservice project properly

### ISSUE THREAD

**Issue by expoure** [LunarVim/LunarVim#2432]
### Problem description

1. Open lvim
2. Select a project
3. Select a file inside one microservice
4. Tree and Telescope will only search inside .src from current file

### LunarVim version

master-23feb96

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Archlinux

### Relevant log output

```shell
No relevant log
```

### Screenshots

https://user-images.githubusercontent.com/12136268/162028514-b3649d78-f606-40a4-bb68-34bbd5f8540a.mp4

**Comment by expoure** [comment]
Yeap, that's work! In my case i just take off "package.json". 
Btw: there's a way to show hidden files in telescope?

**Comment by abzcoding** [comment]
> Yeap, that's work! In my case i just take off "package.json".
> Btw: there's a way to show hidden files in telescope?

yes sir there is, you can either call this command
```vim
:Telescope find_files hidden=true no_ignore=true
```
(or create a keybinding for it)
```lua
lvim.builtin.which_key.mappings["f"] = { "<cmd>Telescope find_files hidden=true no_ignore=true<cr>", "Find File" },
```

or you can play with telescope options of
```lua
lvim.builtin.telescope.defaults.vimgrep_arguments
-- or
vim.builtin.telescope.defaults.file_ignore_patterns 
```
