### ISSUE TITLE
Telescope previewer times out in big projects

### ISSUE THREAD

**Issue by expoure** [LunarVim/LunarVim#2434]
### Problem description

1 - open a big project
2 - try navigate in telescope

below a compartion between nvim and lvim

my nvim configuration for telescope:
`if !exists('g:loaded_telescope') | finish | endif

nnoremap  <silent> ;f <cmd>lua require('telescope.builtin').find_files()<cr>
nnoremap  <silent> ;r <cmd>lua require('telescope.builtin').live_grep()<cr>
nnoremap  <silent> ;b <cmd>lua require('telescope.builtin').file_browser()<cr>
nnoremap <silent> \\ <cmd>Telescope buffers<cr>
nnoremap <silent> ;; <cmd>Telescope help_tags<cr>

lua << EOF
function telescope_buffer_dir()
  return vim.fn.expand('%:p:h')
end

local telescope = require('telescope')
local actions = require('telescope.actions')

telescope.setup{
  defaults = {
    mappings = {
      n = {
        ["q"] = actions.close
      },
    },
  }
}
EOF`

https://user-images.githubusercontent.com/12136268/162202466-7d695897-664f-4020-ad0a-e3ea5580bfab.mp4

### LunarVim version

master-23feb96

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Archlinux

### Relevant log output

```shell
No output
```

**Comment by abzcoding** [comment]
hmm, @kylo252 any ideas what might cause this?

**Comment by kylo252** [comment]
please share the output of `:checkhealth telescope`

**Comment by expoure** [comment]
`telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided
`

**Comment by kylo252** [comment]
Looking at that demo again, the project isn't that big, and it seems that only the previewer is slow. 
- compare the performance with the previewer disabled
```vim
:Telescope find_files previewer=false
```
- run `:TSUpdate`, restart `lvim` and see if there's a difference (in case there was an update to the typescript parser)

**Comment by expoure** [comment]
With no previewer there is no lag. I run TSUpdate, restart lvim and telescope with lvim default config still lagging...

**Comment by kylo252** [comment]
I don't really think there's anything to be done from lunarvim's side to be honest. Seems like a bottleneck somewhere between treesitter and telescope. You have actually installed the parser for typescript, right?

some more things to try
- `:TSUninstall typescript`
- use a different colorscheme, in case it was defining too many highlight groups

then search the issue tracker of either plugin, depending on the outcome of the 2 earlier tests

**Comment by abzcoding** [comment]
i mean you can try a couple of things as well
1. using a higher previewer timeout
```vim
:Telescope find_files preview={timeout=1000}
```
2. use different previewers
```lua
lvim.builtin.telescope.file_previewer = previewers.vim_buffer_cat.new
```

**Comment by expoure** [comment]
None of the alternatives worked... what intrigues me is that in nvim works perfectly. I also set this `lvim.builtin.telescope.defaults = {}` but it keeps lagging.

**Comment by abzcoding** [comment]
> None of the alternatives worked... what intrigues me is that in nvim works perfectly. I also set this `lvim.builtin.telescope.defaults = {}` but it keeps lagging.

I actually would love to get to the bottom of this, this probably is caused because of some autocommand/misconfiguration on our part, but I'm not quite sure where to begin debugging it 😅 
so I think we should keep this issue open until someone comes up with a solution

**Comment by frontendwizard** [comment]
specifically on my case, when the project is new and git hasn't been initialised yet, telescope with preview is incredibly slow. After I initialise git, the delay is gone and the preview works normally again. Adding it here cause it might be a good lead on why.

**Comment by kylo252** [comment]
> specifically on my case, when the project is new and git hasn't been initialised yet, telescope with preview is incredibly slow. After I initialise git, the delay is gone and the preview works normally again. Adding it here cause it might be a good lead on why.

Which command is specifically slow? is it `:Telescope find_files`? or are you using the mapping `<leader>f`  because that one is bound to use this function
https://github.com/LunarVim/LunarVim/blob/7712a63e7f1189788fd99be2f0af1159acf54b14/lua/lvim/core/telescope/custom-finders.lua#L87-L95

**Comment by LandonSchropp** [comment]
I'm experiencing lag when trying to use Telescope in a large Rails project. For example, if I want to open the `config/test.rb` file, I type `test` and see the UI update immediately with bad results. However, a couple of seconds later, the results update again with the correct match.

**Comment by expoure** [comment]
i just updated nvim to 0.7 and the telescope error disappeared...

**Comment by kylo252** [comment]
> I'm experiencing lag when trying to use Telescope in a large Rails project. For example, if I want to open the `config/test.rb` file, I type `test` and see the UI update immediately with bad results. However, a couple of seconds later, the results update again with the correct match.

just a sanity check, but you have installed a treesitter parser for ruby, right? and the performance there is acceptable?

**Comment by LandonSchropp** [comment]
> just a sanity check, but you have installed a treesitter parser for ruby, right? and the performance there is acceptable?

Yep (assuming it was installed automatically by LunarVIm). Syntax highlight seems to work without a perceptible lag, so it seems to be working well. The null-ls Rubocop checks take about a second to run, but I think that's normal performance for Rubocop.

I have a gut feeling that this might be related to #2514, specifically, it being slow in projects with a large number of commits. I added a repro case to that PR for a project with a semi-large number of commits, and I noticed a perceptible slowdown for Telescope.

**Comment by kylo252** [comment]
are you sure you're not somehow bottlenecked with your `git` version? I can't reproduce this with https://github.com/LandonSchropp/lunar-vim-example-issue either.

**Comment by LandonSchropp** [comment]
Hmm, I don't think so. I'm running `2.35.1` currently, which is fairly up-to-date.

Are you maybe using a more powerful machine than me? Could you try generating another 100,000 commits using the script in that repo and seeing if you still don't have any performance issues?

**Comment by chsjr1996** [comment]
Hello everyone! I'm current using the Neovim 0.7 and I'm experiencing some lag when trying to use Telescope in some projects, specially in projects with minified JS files.

I'm found this issue on Telescope repository [Telescope live_grep freezes nvim sometimes](https://github.com/nvim-telescope/telescope.nvim/issues/1379) and following [this comment](https://github.com/nvim-telescope/telescope.nvim/issues/1379#issuecomment-996590765) I've changed the `/.local/share/lunarvim/lvim/lua/lvim/core/telescope.lua` file, adding this (`preview.treesitter = false`) on `lvim.builtin.telescope.defaults` section (line 16):

```lua
-- ...
  lvim.builtin.telescope = vim.tbl_extend("force", lvim.builtin.telescope, {
    defaults = {
      preview = {
        treesitter = false,
      },
      prompt_prefix = " ",
-- ...
```
![image](https://user-images.githubusercontent.com/33254540/167174530-e311f202-9820-4f7d-821d-6145c776eb45.png)

After this change, the Telescope find and live_grep modes works much more faster here!

**Comment by kylo252** [comment]
> I've changed the `/.local/share/lunarvim/lvim/lua/lvim/core/telescope.lua` file, adding this (`preview.treesitter = false`) on `lvim.builtin.telescope.defaults` section (line 16):

This is more of a hammer fix that isn't really needed

> specially in projects with minified JS files.

you've identified the problem here, and so you can achieve the same thing in multiple more flexible ways

### alternative 1

turn off treesitter for js until they fix the parser, `:TSUninstall javascript typescript`

```lua
-- remove it from this list
lvim.builtin.treesitter.ensure_installed = { "lua", "c", --[[ ... ]] }
```

### alternative 2

create another telescope function that doesn't use the treesitter previewer which you can use in those projects

```lua
local function grep_no_ts()
  require("telescope.builtin").live_grep { preview = { treesitter = false }, prompt_title = "no treesitter" }
end

-- add a keybind for it for easier access
vim.keymap.set("n", "<c-f>", grep_no_ts)
```

### alternative 3

if you're still not happy with all of this, simply use your solution like this

```lua
lvim.builtin.telescope.defaults.preview = { treesitter = false }
-- I think you can even do this
-- lvim.builtin.telescope.defaults.live_grep.preview = { treesitter = false }
```

**Comment by chsjr1996** [comment]
@kylo252 I forgot of this option (alternative 1), it's works much more better, thank you!
