### ISSUE TITLE
How to configure custom formatter (not in `null-ls` builtins)?

### ISSUE THREAD

**Issue by Logarithmus** [LunarVim/LunarVim#2435]
I'm trying to use `jq` as `json` formatter. Unfortunately, this config doesn't work:
```lua
formatters.setup {
    {exe = "jq", args = {"--indent", "4"}, filetypes = {"json"}}
}
```
It says `Not a valid formatter: jq`.

UPD: my ugly workaround is to symlink `jq` to `fixjson`. It works, but I'd like to configure it properly.

**Comment by abzcoding** [comment]
> I'm trying to use `jq` as `json` formatter. Unfortunately, this config doesn't work:
> 
> ```lua
> formatters.setup {
>     {exe = "jq", args = {"--indent", "4"}, filetypes = {"json"}}
> }
> ```
> 
> It says `Not a valid formatter: jq`.
> 
> UPD: my ugly workaround is to symlink `jq` to `fixjson`. It works, but I'd like to configure it properly.

use [this guide](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/HELPERS.md#make_builtin) to create new  sources
then use the normal null-ls way to use them 

for example, these are my custom stuff
1. [custom markdown dictionary hover](https://github.com/abzcoding/lvim/blob/38d662584f92730908ffcb5bf4057db79639a6eb/lua/user/null_ls/markdown.lua#L6)
2. [golang code actions](https://github.com/abzcoding/lvim/blob/38d662584f92730908ffcb5bf4057db79639a6eb/lua/user/null_ls/go.lua#L6)

and then instead the syntax that you mentioned, just use
```lua
local nls = require("null-ls")
nls.setup {
    on_attach = require("lvim.lsp").common_on_attach,
    debounce = 150,
    save_after_format = false,
    sources = {
-- add them here
      nls.builtins.formatting.isort.with { extra_args = { "--profile", "black" }, filetypes = { "python" } },
      nls.builtins.diagnostics.ansiblelint.with {
        condition = function(utils)
          return utils.root_has_file "roles" and utils.root_has_file "inventories"
        end,
      },
      custom_go_actions.gomodifytags,
      custom_go_actions.gostructhelper,
      custom_md_hover.dictionary,    
      -- and more
    }
}
```

**Comment by abzcoding** [comment]
solution 2 (easier 😅 )

add it upstream 
here is a full example -> https://github.com/jose-elias-alvarez/null-ls.nvim/pull/793/files

**Comment by luong-komorebi** [comment]
Once this is figured out, we should have a document for this here https://www.lunarvim.org/languages/#linting-formatting
