### ISSUE TITLE
Can't install nodejs dependencies on Fedora 35

### ISSUE THREAD

**Issue by tiagaoalb** [LunarVim/LunarVim#2436]
### Problem description

Just used the command to install and got that message.

### LunarVim version

doesn't have

### Neovim version (>= 0.6.1)

NVIM v0.6.1

### Operating system/version

Fedora 35

### Relevant log output

```shell
doesn't have
```

### Screenshots

![Screenshot from 2022-04-07 16-17-10](https://user-images.githubusercontent.com/26368452/162281326-01ea4af0-a1e4-47f6-bd06-a564be78ce52.png)

**Comment by tiagaoalb** [comment]
Obs: pnpm, yarn and npm are installed

**Comment by abzcoding** [comment]
this is where we check for those dependencies
https://github.com/LunarVim/LunarVim/blob/4d1cfc4687534bbfde3da36e6d389e86f581be14/utils/installer/install.sh#L239-L249

please make sure that you can run those without administrative privileges

**Comment by tiagaoalb** [comment]
Now I get this error:
![lvim](https://user-images.githubusercontent.com/26368452/162444640-8b0d8d7f-5ed6-481f-8f32-3c76d6922948.png)

**Comment by abzcoding** [comment]
> Now I get this error:
> ![lvim](https://user-images.githubusercontent.com/26368452/162444640-8b0d8d7f-5ed6-481f-8f32-3c76d6922948.png)

this part is duplicate of https://github.com/LunarVim/LunarVim/issues/2195
for some weird reason, you have to install these on fedora
```
Here are the dependencies I had to install to make it work:
libstdc++.x86_64
libstdc++-devel.x86_64
libstdc++-static.x86_64
g++
```

**Comment by tiagaoalb** [comment]
Thank you very much 😃

**Comment by zzzgit** [comment]
> 

However, I couldn't understand **shellscript**. Pls tell me how to pass an argument to let it use `npm` instead of `pnpm` to install dependencies.

**Comment by zzzgit** [comment]
> However, I couldn't understand any **shellscript**. Pls tell me how to pass an argument to let it use `npm` instead of `pnpm` to install dependencies.

However, I couldn't understand any **shellscript**. Pls tell me how to pass an argument to let it use `npm` instead of `pnpm` to install dependencies.
