### ISSUE TITLE
Deprecation notice: `lvim.builtin.dashboard` 

### ISSUE THREAD

**Issue by hungpham3112** [LunarVim/LunarVim#2437]
![image](https://user-images.githubusercontent.com/75968004/162340190-245a80a5-55bc-42ae-8000-85fc0a420d82.png)

Today, I reinstall LunarVim and see this message. How to solve this?

**Comment by tuanbass** [comment]
Just add following to your config.lua

```
lvim.builtin.dashboard.active = false

```

**Comment by abzcoding** [comment]
<img width="103" alt="Screen Shot 2022-04-08 at 3 58 24 PM" src="https://user-images.githubusercontent.com/10992695/162426966-27d21733-cd6d-4ea8-9fdd-57a9afd98a07.png">
https://github.com/LunarVim/LunarVim/pull/1906
