### ISSUE TITLE
Clarity Language Server & MQL4 Language Server Not Available

### ISSUE THREAD

**Issue by eqan** [LunarVim/LunarVim#2440]
### Feature Description

Unlike Lunarvim, VS Code has the extension for clarity server(Clarity is a smart contract language like solidity), thus I would request Chris and his team to make it available

Below is the link for clarity LSP:
https://github.com/hirosystems/clarity-lsp

Similarly for MQL4 LSP:
https://github.com/pnetherwood/mql4-dev

**Comment by abzcoding** [comment]
we are using [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer) as our language server provider(installer) please create a new issue(feature request) on their repo
