### ISSUE TITLE
Set hidden = true as default for Telescope

### ISSUE THREAD

**Issue by hungpham3112** [LunarVim/LunarVim#2443]
### Feature Description

Show hidden file with Telescope

### Describe the alternatives you have considered

no

### Support information

I'm not used to using Telescope. If you don't want this become default, please tell me how to show hidden in configuration file. Thanks

**Comment by abzcoding** [comment]
can you elaborate?
it should already show hidden files ( but not .git folder)
https://github.com/LunarVim/LunarVim/blob/c7f6b386744a8e8e64947c040e054d424c58c0c8/lua/lvim/core/telescope.lua#L39-L49

what are you using?
1. `find_files` from dashboard
2. `<leader>f` keybinding
3. running `:Telescope find_files`

also what types of files do you want to see that you can't right now?

**Comment by hungpham3112** [comment]
> can you elaborate? it should already show hidden files ( but not .git folder)
> 
> https://github.com/LunarVim/LunarVim/blob/c7f6b386744a8e8e64947c040e054d424c58c0c8/lua/lvim/core/telescope.lua#L39-L49
> 
> what are you using?
> 
> 1. `find_files` from dashboard
> 2. `<leader>f` keybinding
> 3. running `:Telescope find_files`
> 
> also what types of files do you want to see that you can't right now?

I'm using `find_files` and `<leader>f`. Here is my folders on Windows:

![image](https://user-images.githubusercontent.com/75968004/162617416-713590b0-f618-48f4-aa2a-ebaecebde4ab.png)


https://user-images.githubusercontent.com/75968004/162617485-7422b847-3ce5-4e85-b6d9-3a876ae4e72a.mp4

I want to find a folder in `.julia/`

**Comment by abzcoding** [comment]
`<leader>f` is using this command **which only searches inside git_files**
- you can change it though
```lua
lvim.builtin.which_key.mappings["f"] = { "<cmd>Telescope find_files hidden=true no_ignore=true<CR>", "Find file" }
```
- also you can change the one in dashboard by adding this to your config
```lua
lvim.builtin.alpha.dashboard.section.buttons.entries[1] = {
    "SPC f",
    "  Find File",
    "<CMD>Telescope find_files hidden=true no_ignore=true<CR>",
}
```
