### ISSUE TITLE
Banner looks weird

### ISSUE THREAD

**Issue by jonas-w** [LunarVim/LunarVim#2445]
### Problem description

1. Install DroidSansMono Nerd Font
2. Open LVim
3. Banner looks not as supposed to be

### LunarVim version

f92a0d6

### Neovim version (>= 0.6.1)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Operating system/version

Arch Linux

### Relevant log output

```shell
I'm using Alacritty and set the font in the alacritty.yml
Tested also on other terminal emulators, no matter which font, it looks like this:
```

### Screenshots

![image](https://user-images.githubusercontent.com/32615971/162614350-aa54cefa-9819-44aa-9067-06274491f608.png)

**Comment by MarcosPauloC** [comment]
You can fix?

**Comment by kylo252** [comment]
I haven't really seen this before, feel free to re-open this issue if the problem persists.
