### ISSUE TITLE
Closing one buffer through BufferLine closes (hides) the entire window

### ISSUE THREAD

**Issue by andyliuhaowen** [LunarVim/LunarVim#2455]
### Problem description

1. Open 2 buffers
2. Close one of them through BufferLine

Ps: Using `:q` to close a buffer also closes the window. But BufferLine seems to survive the quit unlike shown below.

### LunarVim version

f92a0d6

### Neovim version (>= 0.6.1)

NVIM v0.6.1

### Operating system/version

Fedora 35

### Relevant log output

```shell
nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6800'
  - INFO: $COLORTERM='truecolor'

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/bin/python2"
  - INFO: Executable: /usr/bin/python2
  - ERROR: Command error (job=6, exit code 1): `'/usr/bin/python2' -c 'import sys; sys.path = list(filter(lambda x: x != "", sys.path)); import neovim; print(neovim.__file__)'` (in '/home/haowenl/omnilore_scheduler')
    stderr: Traceback (most recent call last):  File "<string>", line 1, in <module>ImportError: No module named neovim
  - INFO: Python version: 2.7.18
  - INFO: pynvim version: unable to load neovim Python module
  - ERROR: pynvim is not installed.
    Error: unable to load neovim Python module
    - ADVICE:
      - Run in shell: /usr/bin/python2 -m pip install pynvim

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.10.4
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v16.14.1
  - INFO: Nvim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/haowenl/.cache/nvim/lsp.log
  - INFO: Log size: 4 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
```

### Screenshots

https://user-images.githubusercontent.com/35328328/163056776-e5d1dcf6-d0c0-4346-a099-84450997787d.mp4

**Comment by andyliuhaowen** [comment]
@abzcoding Thanks for pointing to duplicates!

I tried:
1. `require("lvim.core.bufferline").buf_kill("bd", 0, true)`. Same behavior.
2. `:bd`. Same behavior.
3. `:bd`. Same behavior.
4. I tried to tweak some of the following configs with no luck:
```lua
 -- default values
lvim.builtin.nvimtree.setup.actions.open_file.quit_on_open = false
lvim.builtin.nvimtree.setup.hijack_unnamed_buffer_when_opening = false
lvim.builtin.nvimtree.setup.hijack_directories.auto_open = true
lvim.builtin.nvimtree.setup.open_on_setup = false
lvim.builtin.nvimtree.setup.open_on_tab = false
```

I have to admit tho I haven't tried all 32 combinations lol.

**Comment by abzcoding** [comment]
> @abzcoding Thanks for pointing to duplicates!
> 
> I tried:
> 
> 1. `require("lvim.core.bufferline").buf_kill("bd", 0, true)`. Same behavior.
> 2. `:bd`. Same behavior.
> 3. `:bd`. Same behavior.
> 4. I tried to tweak some of the following configs with no luck:
> 
> ```lua
>  -- default values
> lvim.builtin.nvimtree.setup.actions.open_file.quit_on_open = false
> lvim.builtin.nvimtree.setup.hijack_unnamed_buffer_when_opening = false
> lvim.builtin.nvimtree.setup.hijack_directories.auto_open = true
> lvim.builtin.nvimtree.setup.open_on_setup = false
> lvim.builtin.nvimtree.setup.open_on_tab = false
> ```
> 
> I have to admit tho I haven't tried all 32 combinations lol.

please don't use `:bd`, try using `:BufferKill` or `<leader>c`

**Comment by abzcoding** [comment]
which corresponds to this function
https://github.com/LunarVim/LunarVim/blob/1569202d39c40d7a44de5eb1b10cf203dd33af41/lua/lvim/core/bufferline.lua#L142-L155

**Comment by kylo252** [comment]
I'm pretty sure it's something to do with `nvim-tree.lua` so this only happens with `lvim .`

Please test any setup you like by modifying this function directly and report back with the combination that works, as I don't think we're doing anything special.
https://github.com/LunarVim/LunarVim/blob/5ed708a1b1d2c77b32766bb6e2750a263898cc0d/lua/lvim/core/nvimtree.lua#L4

It's also hard to keep up with all the refactoring happening in the plugin, so it could be something we're missing 🤷 

---

> * `require("lvim.core.bufferline").buf_kill("bd", 0, true)`. Same behavior.

You might want to try either https://github.com/moll/vim-bbye or https://github.com/ojroques/nvim-bufdel to see if I've missed something up with my (minimal) implementation.

**Comment by andyliuhaowen** [comment]
Okay I'll keep trying things and report here if I got it to work.

**Comment by BWbwchen** [comment]
I also have the same problem and I find the solution with add the below code into your config.lua file:
```
lvim.autocommands.custom_groups = {
    { "BufEnter", "*", "++nested if winnr('$') == 1 && bufname() == 'NvimTree_' . tabpagenr() | quit | endif" },
}
```

**Comment by abzcoding** [comment]
@kylo252 maybe we can add this autocommand to your latest PR 🤔 wdyt?

**Comment by BWbwchen** [comment]
I think the problem is the [bufferline.nvim](https://github.com/akinsho/bufferline.nvim) plugin. I resolve this problem by changing the [bufferline.nvim](https://github.com/akinsho/bufferline.nvim) plugin to [barbar.nvim](https://github.com/romgrk/barbar.nvim) and it didn't happen again.

**Comment by neandrake** [comment]
I think this happens because the default `close_command` for bufferline is `bdelete! %d`. Looking at `:h bdelete` it notes:
>... Any windows for this buffer are closed. ...

That behavior is the main point addressed by [vim-bbye](https://github.com/moll/vim-bbye) which creates new commands to close or mimic closing buffers while retaining the window.

And [barbar.nvim](https://github.com/romgrk/barbar.nvim) utilizes bbye, or a rewrite of it in lua, to allow closing buffers without this behavior.
https://github.com/romgrk/barbar.nvim/blob/master/lua/barbar/bbye.lua

To work around this issue when using bufferline I have done:
1. Include https://github.com/famiu/bufdelete.nvim plugin in my setup, which provides similar functionality as vim-bbye.
2. Configure bufferline's `close_command` to use the `bufdelete` plugin/function.
```lua
-- simplified example:
require('bufferline').setup {
  options = {
    close_command = require('bufdelete').bufdelete,
  }
}
```

After doing so, closing tabs results in maintaining the window layout

**Comment by lesar** [comment]
I have done this key binding and seems work: 
 .config/lvim/config.lua
```
lvim.keys.normal_mode["<leader>bx"] = ":lua lvim.builtin.bufferline.options.close_command()<CR>"
```
best regards
Leonardo

**Comment by jimafisk** [comment]
Thanks for this answer @neandrake!

I'm using a [slightly modified vim-bbye](https://github.com/jimafisk/vim-bbye) (adds save/discard/resume confirmation) so was able to do:

```lua
require("bufferline").setup({
    options = {
        close_command = ":Bdelete",
    }
})
```
