### ISSUE TITLE
Installation error bash: /proc/self/fd/11

### ISSUE THREAD

**Issue by dvsociety** [LunarVim/LunarVim#2456]
### Problem description

I attach the error in an image

![pic-selected-220412-2120-29](https://user-images.githubusercontent.com/102924958/163075174-6b6bc2bf-9509-4ba7-9048-36d757e18cfe.png)

### LunarVim version

Last

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Arch linux 

### Relevant log output

```shell
Nothing
```

**Comment by abzcoding** [comment]
that script should not be run using `sudo`

**Comment by dvsociety** [comment]
> please run the script without `sudo`

That was the first thing I tried but it rejects it.  The installation of the dependencies need the superuser.

**Comment by abzcoding** [comment]
> The installation of the dependencies need the superuser.

no it does not, it actually doesn't work if you use `sudo` and will just print a warning
<img width="761" alt="Screen Shot 2022-04-13 at 3 11 58 PM" src="https://user-images.githubusercontent.com/10992695/163163679-5129c208-c9a5-40ff-82aa-369c1536a8d1.png">

**Comment by abzcoding** [comment]
can you try this?
```shell
wget https://raw.githubusercontent.com/LunarVim/LunarVim/rolling/utils/installer/install.sh
chmod +x install.sh
./install.sh
```

**Comment by diningPhilosopher64** [comment]
Faced a similar issue, try adding the `-y flag` and install all dependencies. I've installed Node and Python dependencies but skipped the Rust one. 

Installation was successful after that.

**Comment by dvsociety** [comment]
> can you try this?
> 
> ```shell
> wget https://raw.githubusercontent.com/LunarVim/LunarVim/rolling/utils/installer/install.sh
> chmod +x install.sh
> ./install.sh
> ```

it worked, thanks.
