### ISSUE TITLE
update core plugins

### ISSUE THREAD

**Issue by argapost** [LunarVim/LunarVim#2457]
### Problem description

Hi! Just a quick question:

For updating the core plugins we need to pull the latest version of LunarVim, after the bot PR has been merged, and then run :LvimUpdate right? :PackerSync wont update the core plugins. 

after running :LvimUpdate we should get this:
![image](https://user-images.githubusercontent.com/58076098/163124203-7324cbfe-b735-45b2-bfb3-a4572ca5dee1.png)

and we are not able to see what has been updated in the plugin.

Am I right or I have done something completely wrong?!

### LunarVim version

Rolling

### Neovim version (>= 0.6.1)

nvim v0.7.0 dev

### Operating system/version

manjaro

### Relevant log output

```shell
--
```

**Comment by abzcoding** [comment]
it makes sure all of those plugins are at commits mentioned here -> https://github.com/LunarVim/LunarVim/blob/rolling/snapshots/default.json

if you want to stay at the latest, set `LVIM_DEV_MODE` in your env
https://github.com/LunarVim/LunarVim/blob/1569202d39c40d7a44de5eb1b10cf203dd33af41/lua/lvim/plugins.lua#L242-L245
