### ISSUE TITLE
PowerShell installation error

### ISSUE THREAD

**Issue by JoeABCDEF** [LunarVim/LunarVim#2463]
### Problem description

Is the LunarVim version executed in VIM? I don't
![image](https://user-images.githubusercontent.com/39638510/163417328-2d720269-bd6d-4fd3-9ea2-49412f125cf9.png)

Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression

### LunarVim version

.

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

winsows 10

### Relevant log output

```shell
Backup operation complete
--------------------------------------------------------------------------------

Checking dependencies..
--------------------------------------------------------------------------------

Attempting to install dependency [nvim] with winget
[ERROR]: Unable to find dependency [nvim]
Please install it first and re-run the installer.

[已退出进程，代码为 1 (0x00000001)]
```

### Screenshots

I installed neovim in the custom directory
`winget search nvim `  there is no such package

![image](https://user-images.githubusercontent.com/39638510/163416425-c651e5a0-1983-4a92-bd99-707ecb2f1635.png)

I set the alias' nvim 'and still report an error
![image](https://user-images.githubusercontent.com/39638510/163418862-0a00b25d-e6b5-4d91-9a8a-ac0c37d3c83e.png)

please, How to solve it

**Comment by kylo252** [comment]
Please install neovim 0.6.1+ separately, you can use scoop or the release from github. I was hoping it would be available in winget, but at this point it seems that we need to wait until 0.7 is released. 

You might also want to run the uninstall.ps1 script just to make sure it's a clean install. The windows installer is still rough, and any suggestions/fixes are always welcome.

**Comment by vmnog** [comment]
I was facing a issue with installing "make", so I just installed it separately using chocolatey (windows). `$ choco install make`.

After installing it I could install LunarVim 🚀

**Comment by jukrb0x** [comment]
> I was facing a issue with installing "make", so I just installed it separately using chocolatey (windows). `$ choco install make`.
> 
> After installing it I could install LunarVim 🚀

same prob here, I use `scoop install make` and it works well.

you may try `scoop install neovim`, which is my initial way to install neovim.

**Comment by vunhatchuong123** [comment]
I get the error while trying to install node dependencies, so I use `scoop install nodejs`.
