### ISSUE TITLE
No snippets shown

### ISSUE THREAD

**Issue by aik2mlj** [LunarVim/LunarVim#2480]
### Problem description

Hello I'm puzzled why lunarvim isn't showing any snippets anymore when I type. I've tried reinstalling it several times and my config file has nothing related to snippets. I just want the default `friendly-snippets` stuff.
Sorry in advance if I missed something.

### LunarVim version

10c7753

### Neovim version (>= 0.6.1)

NVIM v0.8.0-dev+2-g08a144912c

### Operating system/version

Archlinux

### Relevant log output

```shell
no log output related
```

### Screenshots

I have `LuaSnip` and `friendly-snippets` loaded.

![image](https://user-images.githubusercontent.com/53085155/163707293-759d7cdc-74dc-4fa5-b7ac-4818253df603.png)

**Comment by kylo252** [comment]
Hey, does creating this folder `~/.config/lvim/snippets` fixes it? I think it's an untended side-effect from https://github.com/LunarVim/LunarVim/pull/2447

**Comment by aik2mlj** [comment]
Oh, then it throws some errors:
```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua ...site/pack/packer/start/LuaSnip/lua/luasnip/util/path.lua:45: ENOENT: no such file or directory: /home/aik2/.config/lvim/snippets/package.json
stack traceback:
        [C]: in function 'assert'
        ...site/pack/packer/start/LuaSnip/lua/luasnip/util/path.lua:45: in function 'read_file'
        ...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:79: in function 'load_snippet_folder'
        ...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:131: in function 'load'
        ...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:140: in function '_luasnip_vscode_lazy_load'
        [string ":lua"]:1: in main chunk
Error detected while processing BufWinEnter Autocommands for "*":
E5108: Error executing lua ...site/pack/packer/start/LuaSnip/lua/luasnip/util/path.lua:45: ENOENT: no such file or directory: /home/aik2/.config/lvim/snippets/package.json
stack traceback:
        [C]: in function 'assert'
        ...site/pack/packer/start/LuaSnip/lua/luasnip/util/path.lua:45: in function 'read_file'
        ...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:79: in function 'load_snippet_folder'
        ...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:131: in function 'load'
        ...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:140: in function '_luasnip_vscode_lazy_load'
        [string ":lua"]:1: in main chunk
```

**Comment by ajboni** [comment]
I managed to make it work like this, not really sure about any side effects:

```bash
mkdir ~/.config/lvim/snippets
cd  ~/.config/lvim/snippets
touch package.json
```

**Comment by abzcoding** [comment]
ah shit, this is the culprit
https://github.com/LunarVim/LunarVim/blob/10c7753d8e6f572974f9b9e0d0d8631cd13e60ea/lua/lvim/plugins.lua#L75-L77
