### ISSUE TITLE
cannot use "sqlfluff" as linter

### ISSUE THREAD

**Issue by FelipeLema** [LunarVim/LunarVim#2483]
### Problem description

use the following in config.lua:
```lua
local linters = require "lvim.lsp.null-ls.linters"
linters.setup {
  {
   command = "sqlfluff",
   filetypes = {"sql"},
   extra_args = {"--dialect", "postgres"}
  }
}
```
It's pointed out [in null-ls docs](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#sqlfluff) that one is supposed to use `null_ls.builtins.diagnostics.sqlfluff` as a source whereas one cannot use that one in config.lua 

### LunarVim version

f92a0d6

### Neovim version (>= 0.6.1)

NVIM v0.7.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS _HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gn u99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-proto types -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc  -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_ GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL= 3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work /neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/h ome/runner/work/neovim/neovim/build/include Compiled by runner@fv-az316-460  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: " /home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"  Run :checkhealth for more info

### Operating system/version

devuan daedalus (debian bookworm sans systemd)

### Relevant log output

```shell
:checkhealth

```

:messages
```
[null-ls] [WARN  14:59:47] .../packer/start/null-ls.nvim/lua/null-ls/builtins/init.lua:17: failed to load builtin sqlfluff for method diagnostics; please check your config                                          
14:59:47 [ERROR] lvim: "Not a valid source: sqlfluff" file="services.lua", line=77                                                                                                                                   
[packer.nvim] [DEBUG 14:59:47] packer.lua:528: packer.sync: requiring modules                                                                                                                                        
[packer.nvim] [DEBUG 14:59:47] packer.lua:324: Processing plugin specs                                                                                                                                               
[packer.nvim] [DEBUG 14:59:50] packer.lua:558: Gathering install tasks                                                                                                                                               
[packer.nvim] [DEBUG 14:59:50] packer.lua:561: Gathering update tasks                                                                                                                                                
[packer.nvim] [DEBUG 14:59:50] packer.lua:565: Gathering luarocks tasks                                                                                                                                              
[packer.nvim] [DEBUG 14:59:50] packer.lua:578: Running tasks                                                                                                                                                         
[packer.nvim] [DEBUG 14:59:52] packer.lua:324: Processing plugin specs                                                                                                                                               
[packer.nvim] [INFO  14:59:52] packer.lua:736: Finished compiling lazy-loaders!                                                                                                                                      
[packer.nvim] [DEBUG 14:59:52] packer.lua:344: packer.compile: Complete     
```

:e $LUNARVIM_CACHE/DIR/lvim.log
```
14:59:47 [ERROR] lvim: "Not a valid source: sqlfluff" file="lvim/lsp/null-ls/services.lua", line=77
```
```


### Screenshots

_No response_

**Comment by abzcoding** [comment]
can you set this in your config and then print `:e $LUNARVIM_CACHE/DIR/lvim.log` here
```lua
lvim.log.level = "debug"
```

**Comment by FelipeLema** [comment]
I booted lvim, then I reloaded config.lua
```
09:05:45 [ERROR] lvim: "Not a valid source: sqlfluff" file="lvim/lsp/null-ls/services.lua", line=77
09:05:45 [DEBUG] lvim: "Templates installation in progress" file="lua/lvim/lsp/templates.lua", line=47
09:05:46 [DEBUG] lvim: "Templates installation is complete" file="lua/lvim/lsp/templates.lua", line=68
09:06:05 [ERROR] lvim: "Not a valid source: sqlfluff" file="lvim/lsp/null-ls/services.lua", line=77
09:06:59 [ERROR] lvim: "Not a valid source: sqlfluff" file="lvim/lsp/null-ls/services.lua", line=77
09:06:59 [DEBUG] lvim: "Templates installation in progress" file="lua/lvim/lsp/templates.lua", line=47
09:06:59 [DEBUG] lvim: "Templates installation is complete" file="lua/lvim/lsp/templates.lua", line=68
```

**Comment by abzcoding** [comment]
are you on rolling branch?
i just tested this locally and it works just fine
<img width="1891" alt="Screen Shot 2022-04-22 at 7 18 09 PM" src="https://user-images.githubusercontent.com/10992695/164738610-64266f20-d59d-4c4c-929d-43bfb31fde68.png">


cc: @kylo252

**Comment by kylo252** [comment]
please share the output of
```vim
:! git -C "$LUNARVIM_RUNTIME_DIR/site/pack/packer/start/null-ls.nvim" log -1
```
I think you have somehow missed to run `:LvimSyncCorePlugins`, because the null-ls commit you're using should be https://github.com/jose-elias-alvarez/null-ls.nvim/commit/899785c17c8ec701efc618520edf46bc0f3f367b
https://github.com/LunarVim/LunarVim/blob/f92a0d610c1ee899ec8acb091130f2a5eec22812/snapshots/default.json#L47-L49
which should already include the `sqlfluff` integration introduced in https://github.com/jose-elias-alvarez/null-ls.nvim/commit/ffee94f2ccf211ea245a46616f0d49b89916b1ef

**Comment by FelipeLema** [comment]
I must've hit a transient. I changed laptop, copied my `config.lua` and everything seems to be working

Thanks for the time invested.
