### ISSUE TITLE
Documentation does not mention the git dependency

### ISSUE THREAD

**Issue by paskozdilar** [LunarVim/LunarVim#2486]
### Problem description

Running `docker build .` with the following Dockerfile:

```Dockerfile
FROM ubuntu:20.04
RUN apt-get -y update && \
    apt-get -y install software-properties-common && \
    add-apt-repository -y ppa:neovim-ppa/stable && \
    apt-get -y update && \
    apt-get -y install neovim nodejs npm cargo
RUN apt-get -y update && \
    apt-get -y install curl && \
    curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh > install.sh && \
    bash install.sh
````

prints the following error:

```
#6 5.414 [ERROR]: Unable to find dependency [git]
#6 5.414 Please install it first and re-run the installer. Try: sudo apt install -y git
```

even though `git` is not mentioned in the list of prerequisites for installation: https://www.lunarvim.org/01-installing.html#prerequisites

### LunarVim version

not applicable

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Ubuntu 20.04 LTS

### Relevant log output

```shell
#6 5.410 Detecting platform for managing any additional neovim dependencies
#6 5.414 [ERROR]: Unable to find dependency [git]
#6 5.414 Please install it first and re-run the installer. Try: sudo apt install -y git
```

**Comment by paskozdilar** [comment]
Additionally:

After resolving the issue with `git` dependency, it appears that the installation script also requires `pip`.

**Comment by abzcoding** [comment]
fixed via https://github.com/LunarVim/lunarvim.org/commit/3d6cb603a97ea5ab06d8dd48533958c7d57ec71b
gonna take a bit for the actual site to sync
