### ISSUE TITLE
Install script destroys existing config.lua

### ISSUE THREAD

**Issue by dechimp** [LunarVim/LunarVim#2487]
From time to time, people reinstall lunarvim (rather than updating). But I noticed that the config.lua gets completely overwritten.

It might be nice for the install script to either back up any existing config.lua, just not overwrite it at all.

There is no warning about this in the docs https://www.lunarvim.org/01-installing.html

**Comment by abzcoding** [comment]
backup is always taken unless you set it explicitly not to

https://github.com/LunarVim/LunarVim/blob/1ae89bee93a01f2c64884ae8bed3f28681c2abff/utils/installer/install.sh#L323-L340
<img width="1102" alt="Screen Shot 2022-04-19 at 9 57 29 PM" src="https://user-images.githubusercontent.com/10992695/164061135-864cd1ab-ecca-44ef-911a-52bcabeed5c6.png">

**Comment by dechimp** [comment]
Ah okay.  The entire config directory is backed up. I suppose I also never caught the output `"Backing up old $src to $src.old" ` when the install ran either.  I guess the problem is just me.
