### ISSUE TITLE
Allow to configure width and height of peek floating window

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#2489]
### Feature Description

I want to be able to configure the width and height of the floating window that appears when you peek a definition. Ideally I would want to express this in relative terms (% of screen) but absolute ones will be also good.
Currently both sizes are hardcoded into the peek.lua file. Should be easy to add a couple of global (or lvim namepsaced) tables to configure this.

### Describe the alternatives you have considered

The only alternative I can think of is to duplicate the feature on my local settings and use it instead.

**Comment by abzcoding** [comment]
those are computed dynamically, we just have some minimums, but yeah that should be easy to make those configurable as well

https://github.com/LunarVim/LunarVim/blob/1ae89bee93a01f2c64884ae8bed3f28681c2abff/lua/lvim/lsp/peek.lua#L30-L42

**Comment by danielo515** [comment]
I think the context should be configurable too. I find a context of 10 lines (specially if it is 5 up and 5 down) to not be enough
