### ISSUE TITLE
core builtins config method have no parameter,why whis code add parameter “user_config_file” 

### ISSUE THREAD

**Issue by yangqi766** [LunarVim/LunarVim#2494]
### Problem description

~/.local/share/lunarvim/lvim/lua/config/init.lua : 

```lua
function M:init()
 -------------
  builtins.config { user_config_file = user_config_file }
  --------------
end
```
but, every builtins has no parameter, like notify.lua : 
```lua
function M.config()
  lvim.builtin.notify = vim.tbl_deep_extend("force", defaults, lvim.builtin.notify or {})
end
```

### LunarVim version

dcf045de7fc354e8bb2bbc1cda4fbedbcd908b49

### Neovim version (>= 0.6.1)

NVIM v0.7.0-dev+1269-g746a29c58

### Operating system/version

ubuntu 20 

### Relevant log output

```shell
when I drop the  { user_config_file = user_config_file } ,all function do not receive impact.
```

### Screenshots

![企业微信截图_20220421142834](https://user-images.githubusercontent.com/13087771/164388389-35e4ced1-0564-4adf-9d0d-c4f0069c5a3f.png)

**Comment by kylo252** [comment]
I think you mean that the table passed in the config isn't used? if that's the case, then take a look at https://github.com/LunarVim/LunarVim/pull/1406
