### ISSUE TITLE
server not found in `lsp_servers` folder

### ISSUE THREAD

**Issue by alealv** [LunarVim/LunarVim#2497]
### Problem description

I've copied [the documentation](https://www.lunarvim.org/languages/rust.html#extra-plugins) on how to setup `rust-tools` but the following line is causing errors.

```lua
cmd = { vim.fn.stdpath("data") .. "/lsp_servers/rust/rust-analyzer" },
```
I replaced it with an absolute path `~/.local/share/nvim/lsp_servers/rust/rust-analyzer` and now it's working.

So the runtime path where `lsp-installer` should put the binaries should be `~/.local/share/lunarvim` is not `~/.local/share/nvim`, right?

### LunarVim version

e81d24e  chore: update changelog

### Neovim version (>= 0.6.1)

NVIM v0.8.0-dev

### Operating system/version

Ubuntu 21.10

### Affected language servers

rust-analyzer

### Actual behavior

I'm getting the message

`Spawning language server with cmd: `/home/aalvarez/.local/share/lunarvim/lsp_servers/rust/rust-analyzer` failed. The language server is either not installed, missing from PATH, or not executable.`

### log and support info

```shell
no need
```

**Comment by abzcoding** [comment]
Nah we should just update the documentation

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by abzcoding** [comment]
> There's an API from the installer that should be leveraged, instead of hard-coding any path, see: https://github.com/williamboman/nvim-lsp-installer/wiki/Rust#setting-up
> 
> I wonder if we should just undo the override to `vim.fn.stdpath "data"`, if it's starting to become a burden to maintain. We'd only keep the one for `cache`, which should be a lot less problematic.
> 
> I don't use that many plugins, so could you guys run a search for `vim.fn.stdpath "data"`/`vim.fn.stdpath("data")` in `~/.local/share/lunarvim/site` to see how many plugins have some implicit dependency on it.

we should use this in our documentation instead
````lua
      cmd_env = requested_server._default_options.cmd_env,
```

**Comment by abzcoding** [comment]
Fixed via https://github.com/LunarVim/lunarvim.org/commit/b817fc1dcfe33d7cf131e747afb22c8036a076b9

**Comment by alealv** [comment]
Thanks for the fix!

I have one doubt, though. With these changes, will `nlsp-settings` still be able to inject custom config to `nlsp-config`?

**Comment by abzcoding** [comment]
> Thanks for the fix!
> 
> I have one doubt, though. With these changes, will `nlsp-settings` still be able to inject custom config to `nlsp-config`?

that would be fixed via https://github.com/LunarVim/LunarVim/pull/2502
