### ISSUE TITLE
on_config_done callback of nvimtree is getting a table instead of the setup function

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#2508]
### Problem description

[On a previous discussion](https://github.com/LunarVim/LunarVim/issues/2426#issuecomment-1093364338) with @abzcoding about how on_config_done callbacks are supposed to behave, this is the conclusions we got:

>> Also, I still don't know what the thing you get is exactly. Is the instance of the plugin? Is the configuration object? Is it equivalent to do require"plugin-name"? Does it change from plugin to plugin?
> it is equivalent to do require"plugin-name"

However, looking at the code of nvim tree, it is not passing down the equivalent of requiring the module, it is passing down the config submodule, which I guess contains the relevant configuration, but it is not what the expected API is. Take a look here:

https://github.com/LunarVim/LunarVim/blob/f42008ddde7ce9a7a03081a64155558eae99d25a/lua/lvim/core/nvimtree.lua#L124-L129

Then here:

https://github.com/LunarVim/LunarVim/blob/f42008ddde7ce9a7a03081a64155558eae99d25a/lua/lvim/core/nvimtree.lua#L161-L163

### LunarVim version

f41edc6

### Neovim version (>= 0.6.1)

NVIM 0.6.1

### Operating system/version

macOS 12.1

### Relevant log output

```shell
all is good
```

**Comment by danielo515** [comment]
Also I noticed that the function is being called BEFORE the last call to setup of the config tree, overriding any config the user may have tried inside that function. This order should be reversed, as config has not yet been done when the function is called.

**Comment by abzcoding** [comment]
> Also I noticed that the function is being called BEFORE the last call to setup of the config tree, overriding any config the user may have tried inside that function. This order should be reversed, as config has not yet been done when the function is called.

my bad 😅 
it should be fixed now
