### ISSUE TITLE
Clarity LSP not detecting the clarity file

### ISSUE THREAD

**Issue by eqan** [LunarVim/LunarVim#2511]
### Problem description

Recently I made a feature request to the neovim LSP community for clarity language support and they had added clarity to the LSP server which I have successfully installed. Now the issue is when I open the .clar file, lunarvim doesn't detect it as a clarity file and doesn't start the server. Any help in this regard would be grateful as I need syntax highlighting and autocompletion features.

### LunarVim version

0fa5a5d

### Neovim version (>= 0.6.1)

NVIM v0.6.1

### Operating system/version

Windows 10

### Affected language servers

clarity

### Actual behavior

LSP not detecting the clarity file

### log and support info

```shell
Screenshots attached below
```

### Screenshots

![image](https://user-images.githubusercontent.com/61124752/164959716-e983cfcf-7b5a-4f42-a53b-f3077e2c1917.png)
![image](https://user-images.githubusercontent.com/61124752/164959722-5a074706-c6c1-48f9-a823-ac180953cb82.png)
![image](https://user-images.githubusercontent.com/61124752/164959737-4495c99c-4703-40e5-b9b4-a9361330d051.png)
![image](https://user-images.githubusercontent.com/61124752/164959751-87c2dd1f-251c-4896-ae42-fe728bb81895.png)

**Comment by abzcoding** [comment]
first off please fix the deprecation issue, `lvim.builtin.dashboard` is no longer valid, see https://github.com/LunarVim/LunarVim#breaking-changes


after that please run `:LvimSyncCorePlugins` to make sure `nvim-lsp-installer` plugin is up to date

hopefully these will fix your issue

**Comment by eqan** [comment]
Nope already up to date,issue still there
![image](https://user-images.githubusercontent.com/61124752/165144473-f00b3abf-6945-4690-9291-77136419a73c.png)

**Comment by abzcoding** [comment]
> Nope already up to date,issue still there
> ![image](https://user-images.githubusercontent.com/61124752/165144473-f00b3abf-6945-4690-9291-77136419a73c.png)

ok can you run `:LspInstall clarity_lsp` and try again?

**Comment by eqan** [comment]
Reinstalled it again still the issue remains the same
![image](https://user-images.githubusercontent.com/61124752/165318028-b992a690-ace4-4085-b246-f6581b49c6b6.png)

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by kylo252** [comment]
you can see that LspInfo is not showing the filetype

from: https://github.com/neovim/nvim-lspconfig#debugging

> Missing filetype plugins. Certain languages are not detecting by vim/neovim because they have not yet been added to the filetype detection system. Ensure `:set ft?` shows the filetype and not an empty value.

add this to your `config.lua`

```lua
-- NOTE: I'm not sure if this is the actual extension
vim.filetype.add({
  extension = {
    clar = "clarity", 
}})
```
