### ISSUE TITLE
(Re)install NvimTree unknown option view.auto_resize update_to_buf_dir actions.window_picker auto_close

### ISSUE THREAD

**Issue by drmikecrowe** [LunarVim/LunarVim#2512]
### Problem description

I attempted to upgrade and screwed up my system.  To fix, I did:

```sh
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/uninstall.sh)
```

Next, downloaded the latest `neovim` .deb from github and installed.  Then ran:

```sh
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
```

See screenshot below for error

### LunarVim version

e81d24e

### Neovim version (>= 0.6.1)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by runner@fv-az316-460

### Operating system/version

Ubuntu 21.10 impish

### Relevant log output

```shell
null-ls: require("null-ls.health").check()
========================================================================
  - INFO: no sources registered

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /home/mcrowe/.config/nvim/init.vim
    - ADVICE:
      - :help |nvim-from-vim|

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='Tabby'

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **cargo**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **javac**: not available
  - WARNING: **julia**: not available
  - OK: **sh**: `Ok`
  - OK: **bash**: `GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.10`
  - OK: **curl**: `curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 libidn2/2.3.1 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3`
  - OK: **wget**: `GNU Wget 1.21 built on linux-gnu.`
  - OK: **node**: `v16.14.2`
  - OK: **Ruby**: `ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]`
  - ERROR: **Go**: unsupported version `go version go1.16.13 linux/amd64`. Go version must be >= 1.17.
  - OK: **python3**: `Python 3.9.8`
  - OK: **java**: `Ok`
  - OK: **RubyGem**: `3.2.5`
  - OK: **npm**: `8.6.0`
  - OK: **pip3**: `pip 22.0.4 from /home/mcrowe/.pyenv/versions/3.9.8/lib/python3.9/site-packages/pip (python 3.9)`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.14.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 11.2.0-7ubuntu2) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - java           ✓ ✓ . ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 3 provider (optional)
  - INFO: pyenv: Path: /home/mcrowe/.pyenv/libexec/pyenv
  - INFO: pyenv: Root: /home/mcrowe/.pyenv
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /home/mcrowe/.pyenv/versions/3.9.8/bin/python3
  - INFO: Python version: 3.9.8
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.
      - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

## Node.js provider (optional)
  - INFO: Node.js: v16.14.2
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
      - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/mcrowe/.cache/lvim/lsp.log
  - INFO: Log size: 0 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for c: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gb"**
  - INFO: rhs: `<Plug>(comment_toggle_blockwise)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gc"**
  - INFO: rhs: `<Plug>(comment_toggle_linewise)`

No :messages nor lvim.log
```

### Screenshots

![image](https://user-images.githubusercontent.com/90312/164971726-655ef0e5-dd92-43a0-9226-47b4003e3145.png)

**Comment by zahimeen** [comment]
I experience the same problem. It occurs every time the config is loaded (which includes the startup). However, I do think this is a NvimTree issue, not a LunarVim one. It probably has to do with the new Neovim version we updated to.

**Comment by kylo252** [comment]
Seems like something is up with Packer, because the locked version: 
https://github.com/LunarVim/LunarVim/blob/f49f687bc244ff603f3dde6828a85538c50df220/snapshots/default.json#L68-L70

which is before this validation was added to nvim-tree: https://github.com/kyazdani42/nvim-tree.lua/commit/5bbd3a0a917122b9330dab10b55bb56cc18c9a3d

Please run `:LvimSyncCorePlugins` and see if packer checks out the specified version correctly.

**Comment by drmikecrowe** [comment]
Yes, that fixes it

**Comment by chuan137** [comment]
what is the fix? I still see the error after `:LvimSyncCorePlugins`

**Comment by drmikecrowe** [comment]
After running, I exited/reloaded and it worked w/o an issue for me

**Comment by zhangtai** [comment]
> After running, I exited/reloaded and it worked w/o an issue for me

Thanks, but just reopen lvim not works for me, I need to reopen terminal.

**Comment by hensou** [comment]
I'm also having the same issue and running `:LvimSyncCorePlugins` did not fix it.

**Comment by amrox** [comment]
@hensou `:LvimSyncCorePlugins` did not work for me either. However, I ran some combination of `:PackerCompile`, `:PackerClean` and `:PackerInstall` and I am not seeing the problem anymore.

**Comment by apenney** [comment]
I just tried a combination of everything above but I also cannot get this to behave.  I am a brand new user, so I was starting from a clean slate but it still pops up the errors on startup (it's pretty easy to ignore, but I just figured this could be a useful datapoint)

**Comment by c02y** [comment]
> I just tried a combination of everything above but I also cannot get this to behave. I am a brand new user, so I was starting from a clean slate but it still pops up the errors on startup (it's pretty easy to ignore, but I just figured this could be a useful datapoint)

+1, and I completely remove `.local/share/lunarvim/site/pack/packer/start/nvim-tree.lua/` and reinstall it, and message doesn't go away when I start vim

**Comment by hensou** [comment]
@amrox, now I've tried removing `.local/share/lunarvim/site/pack/packer/start/nvim-tree.lua/`(a pointed by @c02y), and then `:PackerClean`, `:PackerIntall`, `:PackerCompile` and the error appears while executing `:PackerCompiler`.

**Comment by danilobjr** [comment]
Same issue here. I've just tried solutions above, but it still pops the message up.

Maybe this issue should be reopen?

**Comment by rbellido** [comment]
Tried the combinations mentioned above as well. I still see the error.

**Comment by cloud303-cholden** [comment]
Ran into this issue using fish shell. Appears to work doing the following:
```bash
bash
LV_BRANCH=rolling curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh | bash

**Comment by c02y** [comment]
> 

Just tried it, and tried all above commands, it doesn't fix it for me.

**Comment by kylo252** [comment]
> Just tried it, and tried all above commands, it doesn't fix it for me.

can you please share the content of `~/.local/bin/lvim`? also, do you use your normal neovim config concurrently?

**Comment by c02y** [comment]
> > Just tried it, and tried all above commands, it doesn't fix it for me.
> 
> can you please share the content of `~/.local/bin/lvim`? also, do you use your normal neovim config concurrently?


```
>> cat ~/.local/bin/lvim
#!/bin/sh

export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"/home/chz/.local/share/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"/home/chz/.config/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"/home/chz/.cache/lvim"}"

exec nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
```
No, when I run nvim directly, it has zero config.

**Comment by andyliuhaowen** [comment]
Same here with neovim 0.7.0. No custom nvim / lvim config. I think this should be reopened.

**Comment by alanmrochadeveloper** [comment]
> @hensou `:LvimSyncCorePlugins` did not work for me either. However, I ran some combination of `:PackerCompile`, `:PackerClean` and `:PackerInstall` and I am not seeing the problem anymore.

this worked for me.

**Comment by andyliuhaowen** [comment]
>  >   @hensou :LvimSyncCorePlugins did not work for me either. However, I ran some combination of :PackerCompile, :PackerClean and :PackerInstall and I am not seeing the problem anymore.
>
> this worked for me. Thank you

Do you mind sharing specifically what combination worked for you? I have tried my different orderings but the error persists.

**Comment by kylo252** [comment]
> Do you mind sharing specifically what combination worked for you? I have tried my different orderings but the error persists.

you can just to it manually from your terminal like this
```sh
rm ~/.config/lvim/plugin/packer_compiled.lua
cd ~/.local/share/lunarvim/site/pack/packer/start/nvim-tree.lua
git fetch --all
git checkout fd2332a # see https://github.com/LunarVim/LunarVim/blob/rolling/snapshots/default.json
lvim +'PackerSync'
```

**Comment by hensou** [comment]
For me, it got fixed by doing what @kylo252 showed but without the git part and with `:LvimSyncCorePlugins` instead of `PackerSync`. 

So, the complete solution for me was:

```bash
rm ~/.config/lvim/plugin/packer_compiled.lua
cd ~/.local/share/lunarvim/site/pack/packer/start/nvim-tree.lua
lvim +'LvimSyncCorePlugins'
```

**Comment by c02y** [comment]
> 



> For me, it got fixed by doing what @kylo252 showed but without the git part and with `:LvimSyncCorePlugins` instead of `PackerSync`.
> 
> So, the complete solution for me was:
> 
> ```shell
> rm ~/.config/lvim/plugin/packer_compiled.lua
> cd ~/.local/share/lunarvim/site/pack/packer/start/nvim-tree.lua
> lvim +'LvimSyncCorePlugins'
> ```

Doesn't work for me.

**Comment by kylo252** [comment]
> Doesn't work for me.

Please be more specific, also please share the output of these commands

```sh
git -C ~/.local/share/lunarvim/site/pack/packer/start/nvim-tree.lua log -1
git -C ~/.local/share/lunarvim/lvim log -1
rg 'nvimtree' -tlua ~/.config/lvim
```

**Comment by c02y** [comment]
> 

``

> > Doesn't work for me.
> 
> Please be more specific, also please share the output of these commands
> 
> ```shell
> git -C ~/.local/share/lunarvim/site/pack/packer/start/nvim-tree.lua log -1
> git -C ~/.local/share/lunarvim/lvim log -1
> rg 'nvimtree' -tlua ~/.config/lvim
> ```

```
>> git -C ~/.local/share/lunarvim/site/pack/packer/start/nvim-tree.lua log -1
commit fd2332a33f0fc7c8545cd1c358ad032876318a43 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Vincent Law <vlaw@users.noreply.github.com>
Date:   Thu Apr 28 08:43:58 2022 +0800

    feat: case sensitive sorter (#1198)
>> git -C ~/.local/share/lunarvim/lvim log -1
commit ad5eeaf6ad12cf05e4b936690bf78bc53827b12c (grafted, HEAD -> master, origin/master)
Author: kylo252 <59826753+kylo252@users.noreply.github.com>
Date:   Wed Apr 27 17:38:56 2022 +0200

    chore: update changelog
>> rg 'nvimtree' -tlua ~/.config/lvim
/home/chz/.config/lvim/plugin/packer_compiled.lua
227:    config = { "\27LJ\2\n@\0\0\3\0\3\0\0066\0\0\0'\2\1\0B\0\2\0029\0\2\0B\0\1\1K\0\1\0\nsetup\23lvim.core.nvimtree\frequire\0" },
385:try_loadstring("\27LJ\2\n@\0\0\3\0\3\0\0066\0\0\0'\2\1\0B\0\2\0029\0\2\0B\0\1\1K\0\1\0\nsetup\23lvim.core.nvimtree\frequire\0", "config", "nvim-tree.lua")

/home/chz/.config/lvim/config.lua
303:lvim.builtin.nvimtree.setup.view.side = "left"
304:lvim.builtin.nvimtree.show_icons.git = 0
```

**Comment by douzeping** [comment]
> > Do you mind sharing specifically what combination worked for you? I have tried my different orderings but the error persists.
> 
> you can just to it manually from your terminal like this
> 
> ```shell
> rm ~/.config/lvim/plugin/packer_compiled.lua
> cd ~/.local/share/lunarvim/site/pack/packer/start/nvim-tree.lua
> git fetch --all
> git checkout fd2332a # see https://github.com/LunarVim/LunarVim/blob/rolling/snapshots/default.json
> lvim +'PackerSync'
> ```

work for me
just delete the packer_compiled.lua and rerun LvimSyncCorePlugins
