### ISSUE TITLE
Telescope displays deleted files

### ISSUE THREAD

**Issue by LandonSchropp** [LunarVim/LunarVim#2514]
### Problem description

If I remove a file, it's still displayed in Telescope's file finder results.

1. Search for a file (such a `readme.md`) using `<leader>f`.
2. Remove the file (`rm readme.md`)
3. Search for the file again

### LunarVim version

e81d24e

### Neovim version (>= 0.6.1)

0.7.0

### Operating system/version

macOS 12.3.1 

### Relevant log output

```shell
N/A
```

### Screenshots

<img width="597" alt="Screen Shot 2022-04-24 at 5 24 11 PM" src="https://user-images.githubusercontent.com/361591/164999213-1b4d8468-2944-4c10-a253-23d3f7895c18.png">

**Comment by abzcoding** [comment]
are you are removing the file outside of neovim?

**Comment by LandonSchropp** [comment]
I've tried both: removing the files outside of Neovim and removing them inside of Neovim.

Ideally, the file picker would work both ways. Using VS Code as an example, if I delete a file, that file is no longer displayed in the file picker. I think this is the most intuitive UX, and what we should strive for.

**Comment by abzcoding** [comment]
> I've tried both: removing the files outside of Neovim and removing them inside of Neovim. I get the same result both ways.
> 
> Ideally, the file picker would work both ways. Using VS Code as an example, if I delete a file, that file is no longer displayed in the file picker. I think this is the most intuitive UX, and what we should strive for.

ok but there is not much we can do about it,
i mean if the issue is there outside of lunarvim ( in neovim + telescope)
then we should file an issue upstream

**Comment by LandonSchropp** [comment]
Makes sense. Do you think the issue is related to Telescope in general, or is it specific to how LunarVim configures `fd`? Is there anything in the LunarVim code that enables or configures caching in Telescope?

**Comment by abzcoding** [comment]
> Makes sense. Do you think the issue is related to Telescope in general, or is it specific to how LunarVim configures `fd`? Is there anything in the LunarVim code that enables or configures caching in Telescope?

we can test it using https://github.com/nvim-lua/kickstart.nvim
you can install that alongside lunarvim ( in your `~/.config/nvim` ) and check if that one is working properly or not
if the issue persists, then we should file it upstream
if that one is working correctly, then we should fix our telescope config

**Comment by LandonSchropp** [comment]
Okay, I'll follow up with that tonight and see if it's the same problem. Thanks!

**Comment by abzcoding** [comment]
> Okay, I'll follow up with that tonight and see if it's the same problem. Thanks!

that would be much appreciated <3

**Comment by LandonSchropp** [comment]
Apologies for the delay on this.

I ran Kickstart locally, and I can't reproduce the issue in that repository. If I delete the `readme.md` file, it's no longer present in the search results. 

The search results also complete *much* faster than they do for me in LunarVim. In a fairly large project, I can't perceive a delay.

**Comment by abzcoding** [comment]
> Apologies for the delay on this.
> 
> I ran Kickstart locally, and I can't reproduce the issue in that repository. If I delete the `readme.md` file, it's no longer present in the search results.
> 
> The search results also complete _much_ faster than they do for me in LunarVim. In a fairly large project, I can't perceive a delay.

Thank you for the feedback. The issue is from our misconfiguration

probably here
https://github.com/LunarVim/LunarVim/blob/3de829e76ed3d90b25250b1ab76f6425146af9d2/lua/lvim/core/telescope.lua#L39-L49


cc: @kylo252 maybe the telescope previewer being slow is related as well

**Comment by abzcoding** [comment]
@LandonSchropp sorry to bother you again, can you test this scenario as well


inside of lunarvim, instead of calling the telescope via shortcuts,
just run this command
```vim
:Telescope git_files previewer=false
```
or 
```vim
:Telescope find_files previewer=false
```
and see if that is faster/without issues or not

**Comment by LandonSchropp** [comment]
Would the `find_files` configuration be affected by `vimgrep_arguments`?

**Comment by abzcoding** [comment]
> Would the `find_files` configuration be affected by `vimgrep_arguments`?

oh i meant that whole configuration section, not just the vimgrep part, github preview limits to 10 lines 😅

**Comment by abzcoding** [comment]
> a reminder that `<leader>f` uses `git_files` by default since your change in #2089 😄
> 
> so you'd need to commit the deletion first, hopefully this example is clear ![image](https://user-images.githubusercontent.com/59826753/165986518-cac8568e-caba-44cb-b961-a1bbe3080268.png)

yeah we should probably revert that, or use `find_files` that makes more sense
cc: @LandonSchropp

**Comment by kylo252** [comment]
@LandonSchropp, I wouldn't count out `git ls-files` just yet tho! check out this interesting rabbit-hole
- article: https://cj.rs/blog/git-ls-files-is-faster-than-fd-and-find/
- hn discussion: https://news.ycombinator.com/item?id=29298017

**Comment by LandonSchropp** [comment]
Interesting stuff! I wasn't expecting the performance difference.

What's the final verdict from you guys on this one then? Does the current behavior of displaying deleted files until they're removed from Git make sense? 

One other oddity I've noticed is that occasionally the file picker displays the same file multiple times. I haven't reported this one yet because I haven't found a reliable way to repro it. Could it potentially be related to `git_files`?

**Comment by kylo252** [comment]
> Does the current behavior of displaying deleted files until they're removed from Git make sense?

Personally, I think it's fine, since it shouldn't happen that often.

Another thing to keep in mind is that we're _only_ setting the binding, so it's not like `:Telescope find_files` has gone anywhere, and you can always bind either function to fit your workflow and the kind of repos you use.

**Comment by LandonSchropp** [comment]
Works for me! I'll close this issue then. Thank you!
