### ISSUE TITLE
list all symbols in project

### ISSUE THREAD

**Issue by Ali-Aref** [LunarVim/LunarVim#2516]
### Feature Description

I'm coming from sublime text and missing my fav shortcut (Ctrl+Shift+r) which was listing the project symbols (classes, methods, functions, ...)

here we have telescope and that's great. it would be greater if we could have that functionality here too.
the actual shortcut is not important but the functionality.

**Comment by abzcoding** [comment]
for example add this to your keybiding 
```lua
lvim.keys.normal_mode["<C-s>"] = "<cmd>Telescope lsp_workspace_symbols<CR>"
```
and you can use ctrl+s to show all symbols

`ctrl+r` is used for `redo` in neovim, so i would not recommend using that, but feel free to use any other keybinding
