### ISSUE TITLE
how to modify the lsp languageserver config in ~/lvim/config.lua

### ISSUE THREAD

**Issue by yangqi766** [LunarVim/LunarVim#2520]
### Problem description

I want to modify the pyright config in ~/lvim/config.lua .

I find the config 

`
-- local opts = {} 
-- require("lvim.lsp.manager").setup("pyright", opts)
`

For example, I want to set   python.analysis.extraPaths : ["src"]

how to config?  

### LunarVim version

1.1.3

### Neovim version (>= 0.6.1)

NVIM v0.7.0-dev+1269-g746a29c58

### Operating system/version

ubuntu 20 

### Relevant log output

```shell
no output
```

**Comment by abzcoding** [comment]
it seems like you've figured it out here -> https://github.com/LunarVim/LunarVim/issues/2519#issuecomment-1109600729
