### ISSUE TITLE
no LspSettings cmd?

### ISSUE THREAD

**Issue by yangqi766** [LunarVim/LunarVim#2521]
### Problem description

Packer has installed the plugin nlsp-settings.nvim.  But there is no LspSettings cmd.

![企业微信截图_20220426145816](https://user-images.githubusercontent.com/13087771/165240583-26dfbed9-9f51-442d-837d-7d4aeaa4018e.png)

### LunarVim version

1.1.3

### Neovim version (>= 0.6.1)

NVIM v0.7.0-dev+1269-g746a29c58

### Operating system/version

ubuntu 20 

### Affected language servers

python

### Steps to reproduce

https://github.com/tamago324/nlsp-settings.nvim

### Actual behavior

Execute :LspSettings sumneko_lua.

### Expected behavior

sumneko_lua.json will be created under the directory set in config_home. Type <C-x><C-o>. You should now have jsonls completion enabled.

### log and support info

```shell
Language client log: /home/zhenjiema/.cache/nvim/lsp.log
 Detected filetype:   lua
 
 1 client(s) attached to this buffer: 
 
 Client: sumneko_lua (id: 2, pid: 3036769, bufnr: [5, 6, 7, 8])
 	filetypes:       lua
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             lua-language-server
 
 2 active client(s) not attached to this buffer: 
 
 Client: sumneko_lua (id: 1, pid: 3036044, bufnr: [3, 4, 30, 44])
 	filetypes:       lua
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             lua-language-server
 
 Client: sumneko_lua (id: 3, pid: 3045218, bufnr: [20])
 	filetypes:       lua
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             lua-language-server
```

**Comment by abzcoding** [comment]
you are on `1.1.3`, i think in that version you need to run `:NlspSettings` instead of `:LspSettings` since we're locking plugin versions ( for stability reasons)


if you want to stay up to date and always use the latest version. use `rolling` branch instead of staying on a release
