### ISSUE TITLE
Code folding of methods and classes with default shortcuts 

### ISSUE THREAD

**Issue by diningPhilosopher64** [LunarVim/LunarVim#2522]
### Feature Description

I couldn't find a way to fold code in methods or classes with some default shortcuts in lunarvim. 
The documentation doesn't mention anything on setting up the shortcuts.

I believe its related to treesitter config. May I know how to go about configuring it in lunarvim ?

It would be really nice to have default shortcuts for code folding. 

Thanks.

**Comment by abzcoding** [comment]
press `z` in your lunarvim, it will show you the proper folding shortcuts

<img width="1700" alt="Screen Shot 2022-04-26 at 11 28 00 PM" src="https://user-images.githubusercontent.com/10992695/165372536-f16c883d-38eb-4b54-9c4e-ffb8ac3b632b.png">

**Comment by diningPhilosopher64** [comment]
@abzcoding,  thanks for the prompt response!

It would be great if there is an option describing code folding shortcuts after pressing the <leader>key as a default entry!
