### ISSUE TITLE
Unable to override linter command for Rubocop

### ISSUE THREAD

**Issue by LandonSchropp** [LunarVim/LunarVim#2523]
In my project, to run the Rubocop linter in null-ls, I need to run `bundle exec rubocop`. In order to support this, the [suggestion from the null-ls maintainer](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/400#issuecomment-1004888014) is to do something like this:

``` lua
null_ls.builtins.formatting.rubocop.with({
  command = "bundle",
  args = vim.list_extend({ "exec", "rubocop" }, null_ls.builtins.formatting.rubocop._opts.args),
})
```

I've had a quite a difficult time accomplishing this change inside of the LunarVim linter config. Here's what I tried.

``` lua
local linters = require("lvim.lsp.null-ls.linters")
local null_ls = require("null-ls")

linters.setup({
  {
    name = "rubocop",
    command = "bundle",
    args = vim.list_extend({ "exec", "rubocop" }, null_ls.builtins.diagnostics.rubocop._opts.args),
  }
})
```

Unfortunately, it seems like LunarVim makes a few assumptions in [services.lua](https://github.com/LunarVim/LunarVim/blob/rolling/lua/lvim/lsp/null-ls/services.lua#L81-L94) that prevent this from working. First, the `register_sources` always uses the source command.

that a Linter's command will not change when extending the default config.

``` lua
local command = M.find_command(source._opts.command) or source._opts.command

...

local opts = vim.tbl_deep_extend("keep", { command = command }, compat_opts)
```

Second, LunnarVim inserts args as `extra_args`.

``` lua
if config.args then
  compat_opts.extra_args = config.args or config.extra_args
  compat_opts.args = nil
end
```

---

To suppor this use case, I'd suggest two changes:

First, I'd suggest we modify the command code to look like this:

```
local command = cmd or M.find_command(source._opts.command) or source._opts.command
```

Second, I'd suggest we rename `args` to `extra_args`, and allow `args` to be provided independently to null-ls.

**Comment by abzcoding** [comment]
you can ignore the lunarvim way, and do it raw `null-ls` way
i'm using the same thing in my own config

configured here
https://github.com/abzcoding/lvim/blob/de9e79ae6e38e26e8b59e2deb61e9fd882137274/lua/user/null_ls/init.lua#L3


and called here 
https://github.com/abzcoding/lvim/blob/main/config.lua#L113
