### ISSUE TITLE
Some cyrillic letters shows not correctly if there's some keybindings on cyrillic

### ISSUE THREAD

**Issue by nacknime-official** [LunarVim/LunarVim#2527]
### Discussed in https://github.com/LunarVim/LunarVim/discussions/2400

<div type='discussions-op-text'>

<sup>Originally posted by **nacknime-official** March 26, 2022</sup>
Vanilla NVIM works correctly, but Lunarvim shows (or prints, idk) russian and ukrainian letters not correctly.
Instead of "привет" it types "Ð°рÐ¸Ð²Ðµт".

Video:
https://asciinema.org/a/VHzOfrmNRE8RNJr3Hub6dYI4t</div>

But I've found that I see this bug only when there's at least one mapping on cyrillic, you can see video: https://asciinema.org/a/3MR3KxrMpNSoPM8pqYZ2Z89if

**Comment by kobzar** [comment]
Its was locale setting problem 
https://github.com/LunarVim/LunarVim/issues/2657

**Comment by nacknime-official** [comment]
> Its was locale setting problem #2657

Yes, really, thank you so much!
