### ISSUE TITLE
Which plugin is causing this red dialog to pop up and how do I disable it?

### ISSUE THREAD

**Issue by droctothorpe** [LunarVim/LunarVim#2541]
### Problem description

Add this (or anything else that results in linter complaints) to your buffer:

```python
class HashTable:
    def __init__(self, size = 7):
        self.data_map = [None] * size

    def _hash(self, key):
        my_hash = 0
        for letter in key:
            my_hash = (my_hash + ord(letter) * 23) % len(self.data_map)
        return my_hash

    def print_table(self):
        for i, val in enumerate(self.data_map):
            print(i, ": ", val)

    def set_item(self, key, value):
        index = self._hash(key)
        if self.data_map[index] == None:
            self.data_map[index] = []
        self.data_map[index].append([key, value])
```

### LunarVim version

f41edc6

### Neovim version (>= 0.7)

NVIM v0.6.1

### Operating system/version

MacOS 12.2

### Relevant log output

```shell
None
```

### Screenshots

<img width="1541" alt="image" src="https://user-images.githubusercontent.com/24783969/165960257-2abeb242-59c9-4817-9b0c-09354621b3a2.png">

**Comment by abzcoding** [comment]
that is the language server showing you errors
you can add this to your `~/.config/lvim/config.lua`
```lua
lvim.lsp.diagnostics.virtual_text = false
```

and use `<leader>lj` to goto next diagnostic
or use `gl` on the line to show the diagnostic
