### ISSUE TITLE
Telescope code_actions is removed.

### ISSUE THREAD

**Issue by dnjmn** [LunarVim/LunarVim#2550]
### Problem description

since telescope code actions are removed there are multiple bugs while accessing code actions...
please add a work around/new feature for code actions.

### LunarVim version

a68c1cf

### Neovim version (>= 0.7)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@HMBRW-A-001-M1-004.local

### Operating system/version

macos 12.3

### Relevant log output

```shell
$LUNARVIM_CACHE/DIR/lvim/log: 
========================================================================
  - ERROR: No healthcheck found for "$LUNARVIM_CACHE/DIR/lvim/log" plugin.

:messages:e: 
========================================================================
  - ERROR: No healthcheck found for ":messages:e" plugin.
```

### Screenshots

<img width="1440" alt="Screenshot 2022-05-01 at 10 40 23 PM" src="https://user-images.githubusercontent.com/49618740/166156670-9b146b44-086f-4d24-b8d5-d98a2f0c67b0.png">

**Comment by dnjmn** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/1866

**Comment by abzcoding** [comment]
gonna be fixed via https://github.com/LunarVim/LunarVim/pull/2544
