### ISSUE TITLE
Accessing client.resolved_capabilities is deprecated

### ISSUE THREAD

**Issue by ll931217** [LunarVim/LunarVim#2558]
### Problem description

I just did a clean install of LunarVim, however after opening a the LunarVim `config.lua` file, this warning pops up. I notice that it also pops up for my python applications as well.

 There is also the warning at the bottom about `plugin-loader.lua`, not sure how to make them go away.

![Selection_001](https://user-images.githubusercontent.com/12750413/166413547-0dc81c7c-519a-4c6d-82fe-57e8b7715aa4.png)

### LunarVim version

ad5eeaf

### Neovim version (>= 0.7)

NVIM v0.8.0-dev

### Operating system/version

PopOS 22.04

### Affected language servers

lua, python

### Steps to reproduce

1. cd ~/.config/lvim/
2. lvim config.lua

### Actual behavior

Showing annoying warning popups

### Expected behavior

No warning popups

### log and support info

```shell
## LspInfo

Language client log: /home/ll931217/.cache/lvim/lsp.log
Detected filetype: alpha

0 client(s) attached to this buffer:

Configured servers list:

## LvimInfo

14:53:13 [WARN ] lvim: "problems detected while loading plugins' configurations" file="plugin-loader.lua", line=113
E5108: Error executing lua vim/shared.lua:220: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:662: in function 'validate'
        vim/shared.lua:220: in function 'func'
        vim/shared.lua:207: in function 'tbl_filter'
        ...931217/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:114: in function 'make_auto_lsp_info'
        ...931217/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:158: in function 'toggle_popup'
        [string ":lua"]:1: in main chunk

## messages
14:54:38 [WARN ] lvim: "problems detected while loading plugins' configurations" file="plugin-loader.lua", line=113
E5108: Error executing lua vim/shared.lua:220: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:662: in function 'validate'
        vim/shared.lua:220: in function 'func'
        vim/shared.lua:207: in function 'tbl_filter'
        ...931217/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:114: in function 'make_auto_lsp_info'
        ...931217/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:158: in function 'toggle_popup'
        [string ":lua"]:1: in main chunk
```

### Screenshots

![LspInfo](https://user-images.githubusercontent.com/12750413/166415171-e8a55572-0089-4b60-9e0c-66414361564f.png)

![LvimInfo](https://user-images.githubusercontent.com/12750413/166415176-4693ab6d-a4b5-4aca-ab9d-f3c6f0415616.png)

![messages](https://user-images.githubusercontent.com/12750413/166415180-9200a787-bb10-4f7d-8b1a-f4703a0f1f12.png)

**Comment by kylo252** [comment]
@ll931217, can you try again with https://github.com/LunarVim/LunarVim/commit/9ad3510adf2b6a23c25f4eda5a8862a8236ef223?

be sure to run the uninstaller first tho, so that the installer wouldn't attempt to update instead.

**Comment by ll931217** [comment]
@kylo252 Using the latest commit seems to have fixed it, thank you!
