### ISSUE TITLE
Cannot trigger code actions, telescope lsp_code_actions a nil value

### ISSUE THREAD

**Issue by torkelo** [LunarVim/LunarVim#2561]
### Problem description

1. Place cursor over not imported type in a Typescript file
2. Trigger code actions 

Error 
o/.local/share/lunarvim/lvim/lua/lvim/core/telescope.lua:109: attempt to call field 'lsp_code_actions' (a nil value)

If I open Telescope finder window by ":Telecope" I can only find these:

![Screenshot from 2022-05-03 13-04-13](https://user-images.githubusercontent.com/10999/166442369-1de5af2d-53c7-4fa8-b12d-992ad0c92dd8.png)

### LunarVim version

Rolling a68c1cfbf56a70b254252000038e22ae85e932b4  (2 days old)

### Neovim version (>= 0.7)

0.7.0

### Operating system/version

Ubuntu 20

### Relevant log output

```shell
o/.local/share/lunarvim/lvim/lua/lvim/core/telescope.lua:109: attempt to call field 'lsp_code_actions' (a nil value)
```

**Comment by abzcoding** [comment]
that has been removed from telescope (also from our code)
use 
```vim
:lua vim.lsp.buf.code_action()
```

https://github.com/LunarVim/LunarVim/blob/5566076ebb539a7d72dd64af257413fd4dde6157/lua/lvim/core/which-key.lua#L157-L158

**Comment by timoxley** [comment]
@abzcoding with this change, should code actions still appear in a dropdown?

Mine looks like this, not in a popup, displayed at the bottom of the window:
![image](https://user-images.githubusercontent.com/43438/166474532-8f514180-4bcb-496a-a928-f7608f7c445f.png)

Updated LunarVim, updated Neovim, updated Packer.

**Comment by abzcoding** [comment]
> Updated LunarVim, updated Neovim, updated Packer.

yes, telescope decided to remove support for `code_actions` and `range_code_actions`
but you can use plugins to achieve the same functionality
for example https://github.com/nvim-telescope/telescope-ui-select.nvim
or https://github.com/stevearc/dressing.nvim

**Comment by timoxley** [comment]
@abzcoding thanks, dressing does the job nicely

**Comment by timoxley** [comment]
Maybe it should be bundled with lunarvim?

**Comment by abzcoding** [comment]
> Maybe it should be bundled with lunarvim?

that sounds good to me, i'm using it in my own config as well

also there is this PR -> https://github.com/LunarVim/LunarVim/pull/2557

**Comment by danielo515** [comment]
but... but... why? why did they removed it? And why did we removed it from here too? Aren't we using snapshots to ensure compatibility?
