### ISSUE TITLE
Lspconfig for pyright with nlsp-setting failed

### ISSUE THREAD

**Issue by BlueDruddigon** [LunarVim/LunarVim#2565]
### Problem description
```
The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless
stubPath ```$Project/typings``` is not a valid directory.
Location of stub path is ~/Documents/typings
```
### LunarVim version

e1d32ca feat(quit): make sure to ask before discarding changes

### Neovim version (>= 0.7)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

Ubuntu 20.04

### Affected language servers

pyright

### Steps to reproduce

1. Override pyright langserver manually (copied from lspconfig pyright configuration with root_files modified)
```lua
vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "pyright" })

local root_files = {
  "pyproject.toml",
  "setup.py",
  "setup.cfg",
  "requirements.txt",
  "Pipfile",
  "pyrightconfig.json",
  ".git",
  ".gitignore"
}

local function organize_imports()
  local params = {
    command = "pyright.organizeimports",
    arguments = { vim.uri_from_bufnr(0) },
  }
  vim.lsp.buf.execute_command(params)
end

local opts = {
  cmd = { "$HOME/.local/share/nvim/lsp_servers/pyright/node_modules/.bin/pyright-langserver", "--stdio" },
  filetypes = { "python" },
  root_dir = require("lspconfig.util").root_pattern(unpack(root_files)),
  single_file_support = true,
  settings = {
    python = {
      analysis = {
        autoSearchPaths = true,
        useLibraryCodeForTypes = true,
        diagnosticMode = "workspace",
      },
    },
  },
  commands = {
    PyrightOrganizeImports = {
      organize_imports,
      description = "Organize Imports",
    },
  }
}

require("lvim.lsp.manager").setup("pyright", opts)
```
2. Enable on_attach_callback
```lua
lvim.lsp.on_attach_callback = function(_, bufnr)
  local function buf_set_option(...)
    vim.api.nvim_buf_set_option(bufnr, ...)
  end

  --Enable completion triggered by <c-x><c-o>
  buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")
end
```
3. Config pyright with LspSettings:
```json
{
  "python.venvPath": "$HOME/.env",
  "python.pythonPath": "$HOME/.env/bin/python3",
  "python.analysis.logLevel": "Information",
  "python.analysis.stubPath": "$HOME/Documents/typings",
  "python.analysis.extraPaths": [],
  "python.analysis.typeshedPaths": [],
  "python.analysis.diagnosticMode": "workspace",
  "python.analysis.autoSearchPaths": true,
  "python.analysis.typeCheckingMode": "off",
  "python.analysis.autoImportCompletions": true,
  "python.analysis.useLibraryCodeForTypes": true,
  "python.analysis.diagnosticSeverityOverrides": {},
  "pyright.disableOrganizeImports": true,
  "pyright.disableLanguageServices": true
}
```

### Actual behavior

[START][2022-05-03 21:59:16] LSP logging initiated
[WARN][2022-05-03 21:59:17] ...lsp/handlers.lua:109	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2022-05-03 21:59:18] ...lsp/handlers.lua:456	"stubPath $Project/typings is not a valid directory."

### log and support info

```shell
:LvimInfo

                        
                            __                          _    ___         
                           / /   __  ______  ____ _____| |  / (_)___ ___ 
                          / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
                         / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
                        /_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 
                        
                        
                        Buffer info
                        * filetype:                python
                        * bufnr:                   1
                        * treesitter status:       active
                        
                        Active client(s)
                        * name:                      pyright
                        * id:                        1
                        * supported filetype(s):     python
                        * attached buffers:          1
                        * root_dir pattern:          1
                        * capabilities:              callHierarchyProvider
                        
                        Automatic LSP info
                        * Skipped servers: [jedi_language_server, pylsp, sourcery, pyright]
                        
                        Formatters info
                        * Active: yapf  
                        * Supported: [autopep8, black, isort, reorder_python_imports, yapf]
                        
                        Linters info
                        * Active: 
                        * Supported: [flake8, mypy, pydocstyle, pylama, pylint, pyproject_flake8, semgrep, vulture]
                        
                        Code actions info
                        * Active: 
```

:LspInfo
```
 
 Language client log: $HOME/.cache/lvim/lsp.log
 Detected filetype:   python
 
 2 client(s) attached to this buffer: 
 
 Client: pyright (id: 1, pid: 72063, bufnr: [1])
 	filetypes:       python
 	autostart:       true
 	root directory:  $PROJECT
 	cmd:             $HOME/.local/share/nvim/lsp_servers/pyright/node_modules/.bin/pyright-langserver --stdio
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [1])
 	filetypes:       python
 	autostart:       false
 	root directory:  $PROJECT
 	cmd:             nvim
 
 Configured servers list: pyright
```
```


### Screenshots

_No response_

**Comment by abzcoding** [comment]
you are kind of overriding it both ways so i'm not sure which one is taking precedence,
maybe change this
```lua
    python = {
      analysis = {
        autoSearchPaths = true,
        useLibraryCodeForTypes = true,
        diagnosticMode = "workspace",
      },
    },
```
to this
```lua
    python = {
      analysis = {
        autoSearchPaths = true,
        useLibraryCodeForTypes = true,
        diagnosticMode = "workspace",
        stubPath": "$HOME/Documents/typings",
      },
    },
```
and see if that changes anything,



more info -> https://github.com/microsoft/pyright/blob/main/docs/type-stubs.md

**Comment by BlueDruddigon** [comment]
> ```lua
> python = {
>       analysis = {
>         autoSearchPaths = true,
>         useLibraryCodeForTypes = true,
>         diagnosticMode = "workspace",
>         stubPath = "$HOME/Documents/typings",
>       },
> ```

Does not work though

**Comment by abzcoding** [comment]
that seems like a bug 🤔 

cc: @kylo252 are we sure the providers are running or not?

**Comment by abzcoding** [comment]
@[BlueDruddigon](https://github.com/BlueDruddigon) can you try doing this?
```shell
cd ~/.local/share/lunarvim/site/pack/packer/start/schemastore.nvim
git reset --hard
git checkout main
git pull
```

and see if your issues are fixed or not?

**Comment by BlueDruddigon** [comment]
> @[BlueDruddigon](https://github.com/BlueDruddigon) can you try doing this?
> 
> ```shell
> cd ~/.local/share/lunarvim/site/pack/packer/start/schemastore.nvim
> git reset --hard
> git checkout main
> git pull
> ```
> 
> and see if your issues are fixed or not?

Thanks for your reply, but it doesn't work.

**Comment by kylo252** [comment]
do you have the actual variable `$HOME` in the json string? because that wouldn't work sadly.
you generally want a single virtual environment per project, so then you can use the project relative path instead, e.g.
```json
 "python.venvPath": "./.env",
```

**Comment by kylo252** [comment]
> EDIT: I push the $HOME to GitHub in order to hide my username because of personal rules (so sorry about the inconvenient)

no worries! either way, I'm fairly confident that this wouldn't go so well with pyright. 

- what happens if you don't set these options? 
- aren't you activating the virtual env from the shell before opening `lvim`?
- do you have any problems if you bypass nlsp-settings and use `pyrightconfig.json` in the root of the project instead?

**Comment by BlueDruddigon** [comment]
> * pyrightconfig.json

First of all, if i don't set these options, the stubPath goes wrong and the pyright lsp didn't work!
Secondly, I have activated the virtualenv ```before``` starting lvim command.
Last, the bypassed config file of nlsp-settings in my case is ````pyright.json```, not ```pyrightconfig.json```. I ran ```:LspSettings pyright``` command and the plugin suggest to create pyright.json file!

**Comment by kylo252** [comment]
> Last, the bypassed config file of nlsp-settings in my case is `pyright.json`, not `pyrightconfig.json`. I ran `:LspSettings pyright` command and the plugin suggest to create pyright.json file!

I guess there's some confusion since `:LspSettings` is basically just renamed from `:NlspSettings`, so you're still not bypassing the plugin.

This is the file that I'm talking about
> Pyright offers flexible configuration options specified in a JSON-formatted text configuration. By default, the file is called “pyrightconfig.json” and is located within the root directory of your project. Multi-root workspaces (“Add Folder to Workspace…”) are supported, and each workspace root can have its own “pyrightconfig.json” file.

ref: https://github.com/microsoft/pyright/blob/ccc95e054552caeff81325af98f2a1ead58ba1fb/docs/configuration.md

**Comment by BlueDruddigon** [comment]
> > Last, the bypassed config file of nlsp-settings in my case is `pyright.json`, not `pyrightconfig.json`. I ran `:LspSettings pyright` command and the plugin suggest to create pyright.json file!
> 
> I guess there's some confusion since `:LspSettings` is basically just renamed from `:NlspSettings`, so you're still not bypassing the plugin.

Yeah, I know it's just a renamed command.

> This is the file that I'm talking about
> 
> > Pyright offers flexible configuration options specified in a JSON-formatted text configuration. By default, the file is called “pyrightconfig.json” and is located within the root directory of your project. Multi-root workspaces (“Add Folder to Workspace…”) are supported, and each workspace root can have its own “pyrightconfig.json” file.
> 
> ref: https://github.com/microsoft/pyright/blob/ccc95e054552caeff81325af98f2a1ead58ba1fb/docs/configuration.md

So, the bypassed file name was "pyrightconfig.json", not "pyright.json". But every run command the created filename was pyright.json. It's too inconvenient to rename that file! How can I fix this automatically ?

**Comment by kylo252** [comment]
I think you're still mixing up the two files, nlsp-settings should only be creating a file under a specific folder, see https://github.com/tamago324/nlsp-settings.nvim/blob/0ca91e1980ba529670ecacf86eabb12bc9245fc6/README.md#settings-files-for-each-project

> The settings file will be created in `{project_path}/.nlsp-settings/{server_name}.json`

while `pyrightconfig.json` is directly in the root of the project

`{project_path}/pyrightconfig.json`

furthermore, unless there's a code-action, then there's no command whatsoever from lvim to modify `pyrightconfig.json`, because that's a file only the server knows about.

**Comment by BlueDruddigon** [comment]
> 

Do I have any other ways to get the correct filename like pyrightconfig.json when the command ```:LspSettings pyright``` is triggered instead of pyright.json? Or it depends on Nlsp-setting plugin?

**Comment by kylo252** [comment]
Yeah, as I said, these are different files and have different schemas.

You can use a local config for each project with `:LspSettings local pyright`, _again this does not have anything to do with `pyrightconfig.json`_

I've made a demo with asciinema that you can check out 

[![asciicast](https://asciinema.org/a/sHYPa3xNKhpQDcF4280AtZZKN.svg)](https://asciinema.org/a/sHYPa3xNKhpQDcF4280AtZZKN)

Let me know if you still have further issues.

P.s. sorry it ended up a bit longer than expected, it took a while for me to find the setting I wanted to turn off 😅
