### ISSUE TITLE
Visual path glitch in lvim, which_key errors.

### ISSUE THREAD

**Issue by B4mbus** [LunarVim/LunarVim#2566]
### Problem description

Hey. I just got to coding today and lunarvim starts bugging.
I get a weird `fillename (full path) - NVIM` string appearing in the command line (like the line at the very bottom where one inputs commands), in the statusline and everywhere I start editing code.

It's obviously out of place, because it's visible that plugins and buffers are fighting over which one is higher in the Z position (them or the weird text) and it just covers my code.

I've done nothing yesterday except updating and upgrading all of my apt plugins.
A gif is in the screenshots section.

I tried commenting all of my config out - didn't work.
Using `nvim` with no config doesn't create that problem.

I thought it's maybe because I have neovim version 0.6.1 installed.
So I uninstalled lunarvim, installed the stable neovim version by hand and I have 0.7.0 now.

But not only didnt it help, but also made so that everytime I open LunarVim I get a whichkey error:
```
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua ...te/pack/packer/opt/which-key.nvim/lua/which-key/keys.lua:224: attempt to concatenate a function value
stack traceback:
        ...te/pack/packer/opt/which-key.nvim/lua/which-key/keys.lua:224: in function 'parse_mappings'
        ...te/pack/packer/opt/which-key.nvim/lua/which-key/keys.lua:184: in function 'parse_mappings'
        ...te/pack/packer/opt/which-key.nvim/lua/which-key/keys.lua:184: in function 'parse_mappings'
        ...te/pack/packer/opt/which-key.nvim/lua/which-key/keys.lua:290: in function 'register'
        ...te/pack/packer/opt/which-key.nvim/lua/which-key/init.lua:94: in function 'load'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```
and many whichkey mappings don't work.

I don't really a whole day to try and solve both of these issues, so please, if anyone knows what might be causing it, please let me know.

### LunarVim version

23feb96 (Thursday, May 24, 16:07:02)

### Neovim version (>= 0.7)
```
NVIM v0.7.0 Build type: Debug LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/mnt/f/Private/sandbox/neovim/build/config -I/mnt/f/Private/sandbox/neovim/src -I/mnt/f/Private/sandbox/neovim/.deps/usr/include -I/usr/include -I/mnt/f/Private/sandbox/neovim/build/src/nvim/auto -I/mnt/f/Private/sandbox/neovim/build/include Compiled by b4mbus@stacjonarny  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/share/nvim"  Run :checkhealth for more info
```

### Operating system/version

Linux stacjonarny 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux

### Relevant log output

```shell
**:checkhealth**: https://gist.github.com/B4mbus/94c909238740bcbcb5106955bfb65ede
**:messages**: produces the same whichkey error as when opening lunarvim, nothing else happens
**lvim.log**: empty
```

### Screenshots

![Gif](https://cdn.discordapp.com/attachments/648964758128558103/971369808719384606/wtf.gif)

**Comment by abzcoding** [comment]
first things first, can you run `:TSUpdate`
after that try switching to the `rolling` branch (latest commit)
since we are using a different which-key there

**Comment by B4mbus** [comment]
@abzcoding Hey, thanks for your concern.
I reinstalled lvim, this time with a rolling branch. I did `TSUpdateSync`, `LvimUpdate` and `PackerSync`. 
The issue with a visual path glitch is present no matter what.
The issue with a whichkey error is apparently because whichkey no longer supports functions in the mappings which my config had? Idk, Ill look into it myself.

**Comment by B4mbus** [comment]
@abzcoding 
Hey. I think expressed myself incorrectly. 
By "Idk, I'll look into myself" I just meant the whichkey problem.
The visual glitch is still present and I have no idea how to resolve or even start diagnosing this issue, so I'm still very open for any help.

Excuse my lack of communication skills.

**Comment by abzcoding** [comment]
> @abzcoding Hey. I think expressed myself incorrectly. By "Idk, I'll look into myself" I just meant the whichkey problem. The visual glitch is still present and I have no idea how to resolve or even start diagnosing this issue, so I'm still very open for any help.
> 
> Excuse my lack of communication skills.

hmm no worries, ok can you a different terminal?
also check this issue -> https://github.com/LunarVim/LunarVim/issues/2531

**Comment by B4mbus** [comment]
@abzcoding 
I can't really try a different terminal right now.

Doing `set TERM linux` indeed works, but it messes up my `fish` shell.

**Comment by abzcoding** [comment]
> @abzcoding I can't really try a different terminal right now.
> 
> Doing `set TERM linux` indeed works, but it messes up my `fish` shell.

yep, so maybe try using a different terminal or fix your TERM since this is more of a terminal issue

**Comment by gytis-ivaskevicius** [comment]
I am having the same issue tho with standard Linux and alacrity. Can anyone identify where that text should go or why it is shown there?

**Comment by danielmckinnonanderson** [comment]
Seeing this now as well, also using Alacrity on Fedora 37. I'm experiencing all the symptoms that @B4mbus was above, including that plain neovim `0.8.1` doesn't produce the issues. Have tried multiple clean installs of both Lunarvim and Neovim, as well as trying the default Fedora terminal in addition to Alacritty and the issue persists with LunarVim in both instances. Did anyone find a solution?
