### ISSUE TITLE
Codelens refresh fails on InsertLeave

### ISSUE THREAD

**Issue by cladera** [LunarVim/LunarVim#2574]
### Problem description

When codelens refresh is executed by InsertLeave autocomand it throws the following exception:

```
Error detected while processing InsertLeave Autocommands for "<buffer=9>":
Error executing lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/codelens.lua:119: attempt to index field 'range' (a nil value)
stack traceback:
        /usr/local/share/nvim/runtime/lua/vim/lsp/codelens.lua:119: in function </usr/local/share/nvim/runtime/lua/vim/lsp/codelens.lua:113>
```

### LunarVim version

master-aa4c993

### Neovim version (>= 0.7)

NVIM v0.8.0-dev+133-g82c7a82c3

### Operating system/version

macOs 12.3.1

### Affected language servers

Java

### Steps to reproduce

1. Open a Java class
2. Enter insert mode
3. Leave instert mode

### Actual behavior

nvim throws the error mentioned in the description.

### log and support info

```shell
:messages

Error detected while processing InsertLeave Autocommands for "<buffer=16>":
Error executing lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/codelens.lua:119: attempt to index field 'range' (a nil value)
stack traceback:
        /usr/local/share/nvim/runtime/lua/vim/lsp/codelens.lua:119: in function </usr/local/share/nvim/runtime/lua/vim/lsp/codelens.lua:113>
E5108: Error executing lua vim/shared.lua:0: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function <vim/shared.lua:0>
        vim/shared.lua: in function 'tbl_filter'
        ...ladera/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info'
        ...ladera/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'
        [string ":lua"]:1: in main chunk
Error detected while processing InsertLeave Autocommands for "<buffer=16>":
Error executing lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/codelens.lua:119: attempt to index field 'range' (a nil value)
stack traceback:
        /usr/local/share/nvim/runtime/lua/vim/lsp/codelens.lua:119: in function </usr/local/share/nvim/runtime/lua/vim/lsp/codelens.lua:113>
```
```


### Screenshots

_No response_

**Comment by abzcoding** [comment]
i cannot reproduce this locally
<img width="525" alt="Screen Shot 2022-05-05 at 10 59 17 PM" src="https://user-images.githubusercontent.com/10992695/166993342-1b9af5a6-c9a0-426a-8345-95a004d453b0.png">
<img width="1680" alt="Screen Shot 2022-05-05 at 10 58 46 PM" src="https://user-images.githubusercontent.com/10992695/166993528-686b0d4f-6b98-4e99-bad0-4bbdadcc9c14.png">

**Comment by cladera** [comment]
Removing "java" from the skipped automatic server config didn't help. Here is the prints of the lines you made me add:

```
{ "jdtls" }
{ "angularls", "ansiblels", "ccls", "csharp_ls", "cssmodules_ls", "denols", "ember", "emmet_ls", "eslint", "eslintls", "golangci_lint_ls", "graphql", "jedi_language_server", "ltex", "ocamlls", "phpactor", "psalm", "pylsp", "quick_lint_j
s", "rome", "reason_ls", "scry", "solang", "solidity_ls", "sorbet", "sourcekit", "sourcery", "spectral", "sqlls", "sqls", "stylelint_lsp", "tailwindcss", "tflint", "verible", "vuels", "jdtls" }
```

**Comment by cladera** [comment]
I haven't check new autocmd api yet, but it seems to be related to that. On `lua/lvim/lsp/utils.luaL130` an autocmd is defiend to display code lenses. I've replaced the callback by noop one just to print the arguments it receives. The callback it's being called once with the first argument with the following value:

```
{
  buf = 9,
  event = "InsertLeave",
  file = "/path/to/Foo.java",
  group = 64,
  id = 28,
  match = "/path/to/Foo.java"
}
```

Followed by this call I see several other invocations with a totally different object structure, example:

```
{
  data = { "/path/to/Foo.java", {
      character = 23,
      line = 47
    }, "references" },
  range = {
    end = {
      character = 32,
      line = 47
    },
    start = {
      character = 23,
      line = 47
    }
  }
}
```

It seems that the first invocation is the one that makes `codelens.display` fail.

**Comment by abzcoding** [comment]
no you can remove them if you want
```lua
lvim.lsp.code_lens_refresh = false -- or true, don't remember which one 😅 
```

**Comment by cladera** [comment]
I still think this autocmd here seems wrong:

```
  vim.api.nvim_create_autocmd("InsertLeave", {
    group = "lsp_code_lens_refresh",
    buffer = bufnr,
    callback = vim.lsp.codelens.display,
  })
```

As far I understand, the event fired by the autocmd will always make `vim.lsp.codelens.display` fail.

**Comment by abzcoding** [comment]
> 
> As far I understand, the event fired by the autocmd will always make `vim.lsp.codelens.display` fail.

let me look into it 🔭
