### ISSUE TITLE
Install Lunarvim with Neovim latest.

### ISSUE THREAD

**Issue by butterfly1924** [LunarVim/LunarVim#2580]
### Feature Description

Users have to install latest version of neovim each time before lunarvim which it very repetitive. We can use neovim's appimage and install neovim+lunarvim with one step instead of two.

### Describe the alternatives you have considered

Install Neovim AppImage or do a platform detection and install corresponding neovim latest version.

### Support information

https://github.com/neovim/neovim

**Comment by abzcoding** [comment]
the installer is available already -> https://github.com/LunarVim/LunarVim/blob/rolling/utils/installer/install-neovim-from-release

you can run that before calling lunarvim installation if you want
