### ISSUE TITLE
Add an option to update Lunarvim with diffing configs like in spacemacs

### ISSUE THREAD

**Issue by Zwo1in** [LunarVim/LunarVim#2585]
### Feature Description

When one updates LunarVim after some time, it's not necessarily clear what changes were done and what options are available / have changed.
When I was using Spacemacs, there was a really helpful option that during updating you got a vimdiff view where you had your old modified default configuration on left side and the new default config on the right side diffed.
Maybe something similar could be implemented here?

**Comment by abzcoding** [comment]
our changelogs is accessible using `<leader>LI` 
<img width="742" alt="Screen Shot 2022-05-07 at 4 03 25 AM" src="https://user-images.githubusercontent.com/10992695/167227924-11c4f89d-e29e-4394-9dda-bc1f47a62cdc.png">
<img width="1902" alt="Screen Shot 2022-05-07 at 4 03 39 AM" src="https://user-images.githubusercontent.com/10992695/167227925-2fe944c3-0d52-4040-b405-fd690357fae2.png">

and the normal diff is available using `<leader>gd` 
or if you want more control you can use ( change 5 to how many commits you want)
```vim
:Gitsigns diffthis HEAD~5
```
