### ISSUE TITLE
Not able to quit lunarvim properly.

### ISSUE THREAD

**Issue by Sabitra** [LunarVim/LunarVim#2587]
## This is the problem that I face :

1. I have just installed lunar vim on macos.
2. After opening it, to close it as we know we can use :q or <Shift> zq (I can use vim!!)
3. Also <space>q suggested by which key produces the same situation.
4. After this there is a terminal prompt [process completes] and the terminal hangs.
5. <ctrl> c also does not work.
6. I have to force quit the terminal and restart.

### LunarVim version

aa4c993 Merge remote-tracking branch 'origin/rolling'

### Neovim version (>= 0.7)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@iMac-Pro  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"

### Operating system/version

macOS 10.15.3

### Relevant log output

```shell
Almost same output as normal nvim checkhealth.
```

### Screenshots

![Screenshot 2022-05-08 at 8 16 59 PM](https://user-images.githubusercontent.com/20304520/167302317-f02ed1c0-e396-4e78-bb6e-a40671c6b277.png)

**Comment by abzcoding** [comment]
open `~/.local/bin/lvim` file
and change the
```shell
exec nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
```
to
```shell
nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua" "$@"
```

**Comment by Sabitra** [comment]
Thanks worked out!!
