### ISSUE TITLE
Lunar vim looks patchy on macos.

### ISSUE THREAD

**Issue by Sabitra** [LunarVim/LunarVim#2588]
### Problem description

Lunar vim looks patchy on macos. Maybe because I use bash and dont have the proper font files. Help would be appreciated.

### LunarVim version

aa4c993 Merge remote-tracking branch 'origin/rolling'

### Neovim version (>= 0.7)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@iMac-Pro  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"

### Operating system/version

macOS 10.15.3

### Relevant log output

```shell
:No issues in checkhealth.
```

### Screenshots

![Screenshot 2022-05-08 at 8 15 43 PM](https://user-images.githubusercontent.com/20304520/167302542-7e7ec6dd-dbac-4e51-917e-5eff71da53b1.png)
![Screenshot 2022-05-08 at 8 18 49 PM](https://user-images.githubusercontent.com/20304520/167302550-769541fd-7760-4e73-9719-4e8bde757702.png)

**Comment by jakubreron** [comment]
Does your terminal support 256 colors? Did you try switching to another terminal? Like Alacritty or iTerm2 for example?
I guess you are using the native terminal, that might cause some issues

**Comment by abzcoding** [comment]
please use any terminal other than the default mac terminal
