### ISSUE TITLE
Provide a function to add/override mappings

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#2602]
### Feature Description

I would love to have a function to add/override lunar vim mappings. 
The list of lunar-vim mappings is quite big already, and it is impossible to know it by memory. 
Because of this, there are some edge cases where the user experience can be frustrating if you are not overriding the mappings properly or you may override a mapping that you didn't wanted to.
For example, let's say I want to bind a mapping to `alt+k`, seems like a trivial task, but could give you a headache because the different ways to create the mapping and the lua semantics. In my case, I was mapping it as `<M-K>` while on lunar-vim core it is defined as `<A-k>`. The number of combinations this could go wrong is big (different way to call the alt key + upper or lower case). This is not easy to find, specially because telescope will not list the mapping as `<A-k>` but as `<M-k>`, which can be confusing.

Providing a function where you pass your mappings that performs some basic validation and normalises the input will help reduce this frustrating situations. Also, if it takes a second argument like, fail on overwrite, you will be able to be sure that you are not overriding any existing mapping somewhere.

### Describe the alternatives you have considered

Checking the entire source code for mappings every time I find something weird, but that is frustrating.

**Comment by kylo252** [comment]
If you're talking about the keymaps in https://github.com/LunarVim/LunarVim/blob/b0608275189f6adf389053e4a19447732eae08dd/lua/lvim/keymappings.lua, then this should be solved after https://github.com/LunarVim/LunarVim/pull/2592

those will be loaded only once, so you can use the native neovim API
```lua
vim.keymap.set("n", "<A-k>", ...)
```

**Comment by danielo515** [comment]
yes, I'm referring to those. Can you explain a bit further how your c
PR will fix the problem for users using `lvim.keys.xxx = mapping` already?

**Comment by kylo252** [comment]
check the updated `config.example.lua` for some more examples

https://github.com/LunarVim/LunarVim/blob/59361ebe7b677dea0ca490b989af89c8918e1618/utils/installer/config.example.lua#L18-L25

**Comment by danielo515** [comment]
So lunar vim will not override user defined mappings using the vim api ? No need to ser them to null first? If that's the case,then it's great ,makes the config more portable
