### ISSUE TITLE
Support for test runner

### ISSUE THREAD

**Issue by przbadu** [LunarVim/LunarVim#261]
I have been using https://github.com/vim-test/vim-test from long time. It also supports various languages. I think something like this will be a good candidate for LunarVim.

Thoughts?

**Comment by thepenguinthatwants** [comment]
I think nvim-dap is supposed to be used for testing and debugging, altho vim-test is good it might become bloat if it has too many tools to do similar stuff.

**Comment by przbadu** [comment]
@thepenguinthatwants I agree with the simplicity of LunarVim, and I was just suggesting that tool, and haven't looked into nvim-dap before. But Yeah, we need a tool for testing anyways.

**Comment by ChristianChiarulli** [comment]
I may have to do a deeper dive into nvim dap to see if it supports this.

**Comment by przbadu** [comment]
Sample Keymappings:

```sh
-- Test keymappings
vim.cmd([[
  nmap <silent> <leader>tt :TestNearest<cr>
  nmap <silent> <leader>tf :TestFile<cr>
  nmap <silent> <leader>ts :TestSuite<cr>
  nmap <silent> <leader>tl :TestLast<cr>
  nmap <silent> <leader>tv :TestVisit<cr>
]])
```

**Comment by abzcoding** [comment]
in the meantime you can use this for integrating vim-test and the terminal used in lunarvim
```lua
lvim.builtin.terminal.active = true
lvim.plugins = {
  {
      "vim-test/vim-test",
      cmd = { "Test*" },
      keys = { "<localleader>tf", "<localleader>tn", "<localleader>ts" },
      config = function()
        vim.cmd [[
          function! ToggleTermStrategy(cmd) abort
            call luaeval("require('toggleterm').exec(_A[1])", [a:cmd])
          endfunction
          let g:test#custom_strategies = {'toggleterm': function('ToggleTermStrategy')}
        ]]
        vim.g["test#strategy"] = "toggleterm"
      end,
    },
}
lvim.builtin.which_key.mappings["T"] = {
    name = "Test",
    f = { "<cmd>TestFile<cr>", "File" },
    n = { "<cmd>TestNearest<cr>", "Nearest" },
    s = { "<cmd>TestSuite<cr>", "Suite" },
  }
  ```

**Comment by abzcoding** [comment]
i would suggest using `vim-ultest`
```lua
lvim.builtin.terminal.active = true
lvim.plugins = {
  {
          {
      "rcarriga/vim-ultest",
      cmd = { "Ultest", "UltestSummary", "UltestNearest" },
      wants = "vim-test",
      requires = { "vim-test/vim-test" },
      run = ":UpdateRemotePlugins",
      opt = true,
      event = { "BufEnter *_test.*,*_spec.*" },
    },
}
  lvim.builtin.which_key.mappings["t"] = {
    name = "Test",
    f = { "<cmd>Ultest<cr>", "File" },
    n = { "<cmd>UltestNearest<cr>", "Nearest" },
    s = { "<cmd>UltestSummary<cr>", "Summary" },
  }
```

**Comment by ukutaht** [comment]
> in the meantime you can use this for integrating vim-test and the terminal used in lunarvim
> 
> ```lua
> lvim.builtin.terminal.active = true
> lvim.plugins = {
>   {
>       "vim-test/vim-test",
>       cmd = { "TestNearest", "TestFile", "TestSuite", "TestLast", "TestVisit" },
>       keys = { "<localleader>tf", "<localleader>tn", "<localleader>ts" },
>       config = function()
>         vim.cmd [[
>           function! ToggleTermStrategy(cmd) abort
>             call luaeval("require('toggleterm').exec(_A[1])", [a:cmd])
>           endfunction
>           let g:test#custom_strategies = {'toggleterm': function('ToggleTermStrategy')}
>         ]]
>         vim.g["test#strategy"] = "toggleterm"
>       end,
>     },
> }
> lvim.builtin.which_key.mappings["T"] = {
>     name = "Test",
>     f = { "<cmd>TestFile<cr>", "File" },
>     n = { "<cmd>TestNearest<cr>", "Nearest" },
>     s = { "<cmd>TestSuite<cr>", "Suite" },
>   }
> ```

Thanks @abzcoding. I cannot find a way to send the `size` and `dir` arguments to `require('toggleterm').exec(_A[1])`. I'd like to make the terminal split vertically on the bottom. How would I send these arguments? Sorry for my lack of Lua knowledge.

**Comment by abzcoding** [comment]
> How would I send these arguments? 

this is the general way to create terminals:

```lua
M.create_terminal = function(num, keymap, size, direction)
  local terms = require "toggleterm.terminal"
  local ui = require "toggleterm.ui"
  local dir = vim.loop.cwd()
  vim.keymap.set({ "n", "t" }, keymap, function()
    local term = terms.get_or_create_term(num, dir, direction)
    ui.update_origin_window(term.window)
    term:toggle(size, direction)
  end, { noremap = true, silent = true })
end
```

`M.create_terminal(3, "<A-0>", vim.o.columns * 0.4, "vertical")` will create a vertical terminal with size equaling 40% of the screen and keybinding of `<A-0>`


use this example to create your own desired terminal anywhere
