### ISSUE TITLE
Add date to the timestamp of the logs

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#2611]
### Feature Description

Something that always confuses me when checking lunar vim logs are the timestamps. Because they don't include the date, there were some situations were I was reading errors of 2 or 3 days ago, and thinking they were recent.
This is a very confusing user experience with very easy fix: include the date in the logs timestamps.

### Describe the alternatives you have considered

Kill myself 😄 , just joking.

**Comment by kylo252** [comment]
Structlog should be able to handle this easily, please open a PR to fix this

https://github.com/LunarVim/LunarVim/blob/5566076ebb539a7d72dd64af257413fd4dde6157/lua/lvim/core/log.lua#L40-L50

**Comment by danielo515** [comment]
sorry @kylo252 isn't structlog a python library?

**Comment by kylo252** [comment]
> sorry @kylo252 isn't structlog a python library?

it is, but we're using a lua port 😄 

https://github.com/LunarVim/LunarVim/blob/a2454310b6c0b5b530521a77b9b8eb290274e040/lua/lvim/plugins.lua#L33

**Comment by danielo515** [comment]
Opened a PR
