### ISSUE TITLE
optimize the shortcuts to trigger nvim-cmp and luasnip

### ISSUE THREAD

**Issue by xyegithub** [LunarVim/LunarVim#2614]
### Feature Description

`Tab` is used for both picking the items of nvim-cmp and changing the position in luasnip. It brings some wrong codes when I use `<enter>` to choose an item of cmp in some lua-snippets (illustrated in the Support Information Part). 

In fact, it is more convenient to pick the items of cmp only by `ctrl-j` or `ctrl-k`. I think it may be no need to use `tab` as the trigger of cmp. And `tab` can be only used to change the position in lua-snippets?

### Support information

when I use the `codeblock` snippet in a markdown file and the word `python` is in my buffer, like this.
![image](https://user-images.githubusercontent.com/46625185/168241474-72fb62ea-699b-445b-a13b-37619956736f.png)
`python` will be displayed in the cmp table. I can not change the place of defined by luasnip by `tab` at this time. However, when i use `tab` or `ctrl-k`   + `<enter>` to choose `python` in the cmp table. It becomes
![image](https://user-images.githubusercontent.com/46625185/168241838-d82de544-db1e-4b06-babc-1485638d59ee.png)

**Comment by kylo252** [comment]
I'm not sure what the best way is since a lot of people are used to "supertab", but with that in mind:

- the cmp mappings should be updated using the native neovim API

```lua
local has_words_before = function()
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end

local feedkey = function(key, mode)
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(key, true, true, true), mode, true)
end
```

- it's already possible to override all of these mappings, but maybe it's not clear enough how?

**Comment by xyegithub** [comment]
> 

Sorry, I do not figure out how to use these two functions. I can change the shortcut of cmp into only `ctrl-j` and `ctrl-k` in the `config.lua` file by these two function?

**Comment by kristiansordal** [comment]
I'm having the same problem when I'm writing tex files. I like supertab, but having a way to complete the suggested word / snippet from cmp by pressing enter, without having it completely ruin the rest of the snippet would be great!

As an example if I'm in a snippet that expands to \frac{}{}, and autotcomplete a word from the buffer in the first braces, the result ends up being \frac{word}, instead of \frac{word}{}

**Comment by kristiansordal** [comment]
This works pretty good, thanks alot!

Out of curiosty, do you know why expanding cmp suggestiongs with <CR> inside snippets has this weird behaviour if we don't remap like this?

**Comment by abzcoding** [comment]
> This works pretty good, thanks alot!
> 
> Out of curiosty, do you know why expanding cmp suggestiongs with inside snippets has this weird behaviour if we don't remap like this?

well, half of the users prefer the current behavior, and the rest prefer this other behavior so 😅

**Comment by kristiansordal** [comment]
True, good to have the option to change!

**Comment by abzcoding** [comment]
@xyegithub instead of that entire blob of code that defines `jumpable` you could've used 
```lua
local jumpable = require("lvim.core.cmp").methods.jumpable
```

**Comment by xyegithub** [comment]
> @xyegithub instead of that entire blob of code that defines `jumpable` you could've used
> 
> ```lua
> local jumpable = require("lvim.core.cmp").methods.jumpable
> ```

Great! Thanks!
