### ISSUE TITLE
Highlights of words continue to show after entering insert mode

### ISSUE THREAD

**Issue by aik2mlj** [LunarVim/LunarVim#2617]
### Problem description

1. move to a word that triggers highlighting in normal mode (i.e. the automatic highlighting of same words)
2. enter insert mode by pressing `i` or `o`
3. the highlight doesn't disappear, which is a bit annoying

### LunarVim version

d868dc1

### Neovim version (>= 0.7)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

Archlinux

### Relevant log output

```shell
no relevant log
```

### Screenshots

![Peek 2022-05-14 11-58](https://user-images.githubusercontent.com/53085155/168409999-7499193a-5228-45b9-91ac-795097597fd4.gif)

**Comment by rebuilt** [comment]
A temporary fix is to add an autocommand to turn off highlighting when entering insert mode.   I'm not sure why the behavior changed.

```
	lvim.autocommands.custom_groups = {
		{ "InsertEnter", "*", "set nohls" },
	}
```

**Comment by rebuilt** [comment]
I'm not sure this is a LunarVim bug since it also happens in vanilla neovim 0.7

**Comment by aik2mlj** [comment]
Thanks! Then maybe it's an upstream bug?

I tried your method but it seems that `set nohls` only applies to the highlights of the searched content? I mean the "automatic highlights" when you move to a word (don't know which plugin or function corresponds to that)

**Comment by aik2mlj** [comment]
it works. only that the handy highlighting is no longer available haha.

**Comment by abzcoding** [comment]
well either like it or you don't :)
here is the code for it
https://github.com/LunarVim/LunarVim/blob/d868dc14fe04792fc989bb94592f3ba697edd692/lua/lvim/lsp/utils.lua#L100-L109

you can disable that and use a plugin instead to make sure you can tune it to your liking
- https://github.com/RRethy/vim-illuminate
- https://github.com/xiyaowong/nvim-cursorword
