### ISSUE TITLE
Images in terminal?!!!

### ISSUE THREAD

**Issue by palandovalex** [LunarVim/LunarVim#2619]
### Feature Description

In this repo i seen that [image](https://user-images.githubusercontent.com/59826753/159940004-84975294-5703-4bf1-aa98-2cc97cb38d96.png).

That terminal do you used?
[Terminology](https://www.enlightenment.org/about-terminology)

Or [kitty](https://sw.kovidgoyal.net/kitty/)?

Or some other terminal?

**Comment by abzcoding** [comment]
https://github.com/nvim-telescope/telescope-media-files.nvim
