### ISSUE TITLE
netrw plugin is loaded even with lvim.builtin.nvimtree.setup.disablenetrw=true

### ISSUE THREAD

**Issue by nobodyatandnothing** [LunarVim/LunarVim#2621]
### Problem description

nvim-tree has the following:

https://github.com/kyazdani42/nvim-tree.lua/blob/9d26594b6caf3caee46dc12ceae62b5dcbbc28d6/lua/nvim-tree.lua#L251-L254

however when `:E` we get "E117 Unkown function: netrw#Explore"
upon which which it seems that although the autoload is not loaded, the plugin is.

### LunarVim version

d868dc1

### Neovim version (>= 0.7)

0.7.0

### Operating system/version

linux

### Relevant log output

```shell
upon inquiry
```

**Comment by abzcoding** [comment]
we have these in our config
https://github.com/LunarVim/LunarVim/blob/42529e1c4f55824534184ec0658f0eefb328ac3d/lua/lvim/core/nvimtree.lua#L10-L11

you can change them via
```lua
lvim.builtin.nvimtree.setup.disable_netrw = true -- or false
lvim.builtin.nvimtree.setup.hijack_netrw = true -- or false
```
and to make sure everything is settled
you can do a `:LvimCacheReset`

not sure if you meant something else or not

**Comment by nobodyatandnothing** [comment]
nvim-tree should prevent the netrw plugin from loading with `disable_netrw = true`
if the netrw plugin is not loaded then `:E` would result in "E492: Not an editor command: E".
but instead `:E` results in "E117 Unkown function: netrw#Explore"

**Comment by abzcoding** [comment]
can you run this command? ( and print the output here )
```vim
:lua print(vim.g.loaded_netrw)
```

also I put the command there because in title you've put `disablenetrw` but it should be `disaable_netrw` ( just to be sure)

**Comment by nobodyatandnothing** [comment]
it's 1, but that just means that nvim-tree is loaded after netrwPlugin had already been sourced.
if netrwPlugin is not sourced then what defines :E to be netrw#Explore?
to demonstrate, if `vim.g.loaded_netrwPlugin=true` is put in config.lua, then `:E` results in  "E492: Not an editor command: E"

**Comment by abzcoding** [comment]
> it's 1, but that just means that nvim-tree is loaded after netrwPlugin had already been sourced.
> if netrwPlugin is not sourced then what defines :E to be netrw#Explore?
> to demonstrate, if `vim.g.loaded_netrwPlugin=true` is put in config.lua, then `:E` results in "E492: Not an editor command: E"

hmm interesting 🤔, nvim-tree has the following line
https://github.com/kyazdani42/nvim-tree.lua/blob/99e32fea149a21ef9a3a34ccd98cc64c9dff823c/lua/nvim-tree.lua#L515

so you have to make sure both are true ( which is the default in lunarvim )


btw, to make sure that those lines actually gets called
edit this file `v ~/.local/share/lunarvim/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua`
and add the following line
```lua
    vim.notify("i'm disabling netrw", vim.log.levels.WARN)
```
at line 252
<img width="531" alt="Screen Shot 2022-05-17 at 10 26 15 AM" src="https://user-images.githubusercontent.com/10992695/168739176-f30f3a73-351b-438b-8d94-6c7831f84a65.png">

and then close and reopen `lvim`, you should see sth like this
<img width="464" alt="Screen Shot 2022-05-17 at 10 25 16 AM" src="https://user-images.githubusercontent.com/10992695/168739225-e2213ee7-e7fa-4fa3-ac56-f39cb950e210.png">

which means it is working as intended
