### ISSUE TITLE
How can I access default whichkey panel? 

### ISSUE THREAD

**Issue by xbladesub** [LunarVim/LunarVim#2625]
I compare Lunarvim with 'neovim from scratch' projects and can't understand how to setup config to be able to call it.

<img width="1498" alt="Screen Shot 2022-05-17 at 10 11 59 AM" src="https://user-images.githubusercontent.com/45129790/168714767-d03f877e-e189-41a0-9d72-2df077415525.png">

I try to reassign this in my config, but nothing happens

```lua
lvim.builtin.which_key.presets = {
  operators = false, -- adds help for operators like d, y, ...
  motions = false, -- adds help for motions
  text_objects = false, -- help for text objects triggered after entering an operator
  windows = true, -- default bindings on <c-w>
  nav = true, -- misc bindings to work with windows
  z = true, -- bindings for folds, spelling and others prefixed with z
  g = true,
}
```

**Comment by abzcoding** [comment]
with that blob of code, you are overriding the entire thing ( which you should not)
if you want to just access it, use `leader` key ( space) or `g` or `z`

you can check our docs -> https://www.lunarvim.org/configuration/02-keybindings.html#whichkey-bindings

you can add new mappings like this:
```lua
lvim.builtin.which_key.mappings["a"] = { "<cmd>lua require('harpoon.mark').add_file()<CR>", " Add Mark" }
lvim.builtin.which_key.mappings["m"] = {
      name = " Make",
      f = { "<cmd>AsyncTask file-build<cr>", "File" },
      p = { "<cmd>AsyncTask project-build<cr>", "Project" },
      e = { "<cmd>AsyncTaskEdit<cr>", "Edit" },
      l = { "<cmd>AsyncTaskList<cr>", "List" },
}
```

if you want to change which-key settings, you can do them one by one
```lua
  lvim.builtin.which_key.setup.window.winblend = 10
  lvim.builtin.which_key.setup.window.border = "none"
  lvim.builtin.which_key.setup.icons = {
    breadcrumb = "/", -- symbol used in the command line area that shows your active key combo
    separator = "·", -- symbol used between a key and it's label
    group = "", -- symbol prepended to a group
  }
  lvim.builtin.which_key.setup.triggers = { "<leader>", "g", "z", "]", "[" }
  lvim.builtin.which_key.setup.ignore_missing = true
  -- and more
```

**Comment by xbladesub** [comment]
> with that blob of code, you are overriding the entire thing ( which you should not) if you want to just access it, use `leader` key ( space) or `g` or `z`
> 
> you can check our docs -> https://www.lunarvim.org/configuration/02-keybindings.html#whichkey-bindings
> 
> you can add new mappings like this:
> 
> ```lua
> lvim.builtin.which_key.mappings["a"] = { "<cmd>lua require('harpoon.mark').add_file()<CR>", " Add Mark" }
> lvim.builtin.which_key.mappings["m"] = {
>       name = " Make",
>       f = { "<cmd>AsyncTask file-build<cr>", "File" },
>       p = { "<cmd>AsyncTask project-build<cr>", "Project" },
>       e = { "<cmd>AsyncTaskEdit<cr>", "Edit" },
>       l = { "<cmd>AsyncTaskList<cr>", "List" },
> }
> ```
> 
> if you want to change which-key settings, you can do them one by one
> 
> ```lua
>   lvim.builtin.which_key.setup.window.winblend = 10
>   lvim.builtin.which_key.setup.window.border = "none"
>   lvim.builtin.which_key.setup.icons = {
>     breadcrumb = "/", -- symbol used in the command line area that shows your active key combo
>     separator = "·", -- symbol used between a key and it's label
>     group = "", -- symbol prepended to a group
>   }
>   lvim.builtin.which_key.setup.triggers = { "<leader>", "g", "z", "]", "[" }
>   lvim.builtin.which_key.setup.ignore_missing = true
>   -- and more
> ```

Thanks for detailed explanation
