### ISSUE TITLE
Python auto tabs/spaces

### ISSUE THREAD

**Issue by kobzar** [LunarVim/LunarVim#2630]
### Problem description

When i put Enter key after prebuilting methods in Python foles like as 
for i in x: , while true:, e.t.c - i mean after ":" symbol
cursor moving to next line without add tabs/spaces.
This is default action for python in eny editor 

### LunarVim version

Last

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

os X/Archlinux

### Steps to reproduce

lvim z.py

for i in range(3):  <- Enter

### support info

                            Buffer info
                            * filetype:                python
                            * bufnr:                   3
                            * treesitter status:       active
                            
                            Active client(s)
                            * name:                      pyright
                            * id:                        1
                            * supported filetype(s):     python
                            * attached buffers:          3
                            * root_dir pattern:          3
                            * capabilities:              callHierarchyProvider
                            
                            Automatic LSP info
                            * Skipped servers: [jedi_language_server, pylsp, sourcery]
                            
                            Formatters info
                            * Active: black ÔÅÜ , isort ÔÅÜ 
                            * Supported: [autopep8, black, isort, reorder_python_imports, yapf]
                            
                            Linters info
                            * Active: flake8 ÔÅÜ 
                            * Supported: [flake8, mypy, pydocstyle, pylama, pylint, pyproject_flake8, semgrep, vulture]
                            
                            Code actions info
                            * Active:

**Comment by abzcoding** [comment]
that issue comes from treesitter indent
add this to your `~/.config/lvim/config.lua`
```lua
lvim.builtin.treesitter.indent = { enable = true, disable = { "yaml", "python" } } -- treesitter is buggy :(
```
