### ISSUE TITLE
Not an editor command: DIInstall

### ISSUE THREAD

**Issue by andyliuhaowen** [LunarVim/LunarVim#2631]
### Problem description

1. Add the following in configuration:
```
lvim.builtin.dap.active = true
```

2. Run `LvimSyncCorePlugins`.
Verify that `PackerStatus` output has both `DAPInstall.nvim` and `nvim-dap` in its list.

3. `DIInstall` does not work. Manually requiring `dap-install` in config also errors because lua cannot find the module.

### LunarVim version

aa4c993

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

Fedora 36

### support info

This issue is not related to LSP.

And `LvimInfo` throws the following error:
```
E5108: Error executing lua vim/shared.lua:0: t: expected table, got nil
stack traceback:                                                                                                                                                   
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function <vim/shared.lua:0>
        vim/shared.lua: in function 'tbl_filter'
        ...aowenl/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info'
        ...aowenl/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'
        [string ":lua"]:1: in main chunk
```

**Comment by abzcoding** [comment]
first off `LvimInfo` is supposed to be called from an opened buffer ( not dashboard)

**Comment by wren** [comment]
@abzcoding Is there any info anywhere about how to use the current debugger in LunarVim?

The LunarVim docs still reference the outdated `DIInstall` command, and `dap-buddy` itself doesn't have any documentation as far as I can tell.
