### ISSUE TITLE
Explorer focus

### ISSUE THREAD

**Issue by kobzar** [LunarVim/LunarVim#2632]
### Feature Description

 Usually we use SPS + e to open FileExplorer
 After this we choose and open some file for work and cursor change focus to opened file/tab
 In next time, when we want select another file we must use this combination twice
 First to close FE, next top open to change focus, or use another combination like C-w-w e.t.c.
So idea is next, if FE is openned just make focus to it by SPS+e

**Comment by abzcoding** [comment]
can you try `:NvimTreeFocus` ?
```lua
lvim.builtin.which_key.mappings["e"] = { "<cmd>NvimTreeFocus<CR>", "Explorer" }
```

**Comment by kobzar** [comment]
Thanks. This is that i am needed.

**Comment by sigurdo** [comment]
An alternative (or complementary) solution is to auto-close the explorer when opening a file.

```
lvim.builtin.nvimtree.setup.actions.open_file.quit_on_open = true
```
