### ISSUE TITLE
How to change the default new file directory?

### ISSUE THREAD

**Issue by expacc007** [LunarVim/LunarVim#2633]
How to change the default new file directory? 
How do we name a file created using lunar vim, I currently do it using w: filename, is there any better way of doing it?

**Comment by cpea2506** [comment]
1. `cd <to-folder-u-want-to-save-file>`. 

<img width="800" alt="Screen Shot 2022-05-18 at 18 57 38" src="https://user-images.githubusercontent.com/42694704/169033414-26a27489-c224-4b39-aeb1-fbfce47c3afe.png">

2. Using `lvim .` to open the folder with `lunarvim`. 

<img width="801" alt="Screen Shot 2022-05-18 at 19 01 18" src="https://user-images.githubusercontent.com/42694704/169033986-2d82c1d2-23e4-462e-895a-ae402e780d4d.png">


3. The `tree` will open and you can create your new file with `a` in the keyboard. 
<img width="802" alt="Screen Shot 2022-05-18 at 19 01 40" src="https://user-images.githubusercontent.com/42694704/169034074-67435254-9373-4f57-bae0-d43f5c19835d.png">

<img width="799" alt="Screen Shot 2022-05-18 at 19 00 03" src="https://user-images.githubusercontent.com/42694704/169033797-9b93df99-7ca1-4040-85f3-43d663bc7f3f.png">

Or if you are in an opening project. You can still do the same by `<space-e>` to open the `tree`.
<img width="800" alt="Screen Shot 2022-05-18 at 19 02 57" src="https://user-images.githubusercontent.com/42694704/169034273-177406b1-08f4-4575-96ee-d7f589e32fda.png">

And in the `tree` you can find more `shortcut` by pressing `g + ?`

Maybe there will be better way out there.

**Comment by kobzar** [comment]
How are you move bottom line for input file name to centered window???

**Comment by cpea2506** [comment]
> How are you move bottom line for input file name to centered window???

Here you go: [popui](https://github.com/hood/popui.nvim)

**Comment by kobzar** [comment]
> 

Cold you show how to add this in cinfig?

**Comment by cpea2506** [comment]
> Cold you show how to add this in cinfig?

Just add this to your `config.lua` after your install `popui`:

```lua
vim.ui.input = require"popui.input-overrider"
```

**Comment by kobzar** [comment]
> ```lua
> vim.ui.input = require"popui.input-overrider"
> ```

"config.lua" 365L, 13187B written
10:04:53 [WARN ] lvim: "Invalid configuration: ...ck/packer/start/popui.nvim/lua/popui/input-overrider.lua:1: module 'popfix' not found:\n\tno field package.preload['popfix']\n\tno fi
le './popfix.lua'\n\tno file '/usr/local/Cellar/luajit-openresty/2.1-20220411/share/luajit-2.1.0-beta3/popfix.lua'\n\tno file '/usr/local/share/lua/5.1/popfix.lua'\n\tno file '/usr/lo
cal/share/lua/5.1/popfix/init.lua'\n\tno file '/usr/local/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/popfix.lua'\n\tno file '/usr/local/Cellar/luajit-openresty/2.1-20220411/sh
are/lua/5.1/popfix/init.lua'\n\tno file '/Users/kobzar/.cache/lvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/popfix.lua'\n\tno file '/Users/kobzar/.cache/lvim/packer_hererocks/2.1.0-
beta3/share/lua/5.1/popfix/init.lua'\n\tno file '/Users/kobzar/.cache/lvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/popfix.lua'\n\tno file '/Users/kobzar/.cache/lvim/packer
_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/popfix/init.lua'\n\tno file './popfix.so'\n\tno file '/usr/local/lib/lua/5.1/popfix.so'\n\tno file '/usr/local/Cellar/luajit-openresty/2.
1-20220411/lib/lua/5.1/popfix.so'\n\tno file '/usr/local/lib/lua/5.1/loadall.so'\n\tno file '/Users/kobzar/.cache/lvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/popfix.so'" file="init.
lua", line=112
[packer.nvim] [DEBUG 10:04:53] packer.lua:380: packer.install: requiring modules
[packer.nvim] [DEBUG 10:04:53] packer.lua:324: Processing plugin specs

**Comment by cpea2506** [comment]
> ```lua
> ```lua
> vim.ui.input = require"popui.input-overrider"
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> "config.lua" 365L, 13187B written
> 10:04:53 [WARN ] lvim: "Invalid configuration: ...ck/packer/start/popui.nvim/lua/popui/input-overrider.lua:1: module 'popfix' not found:\n\tno field package.preload['popfix']\n\tno fi
> le './popfix.lua'\n\tno file '/usr/local/Cellar/luajit-openresty/2.1-20220411/share/luajit-2.1.0-beta3/popfix.lua'\n\tno file '/usr/local/share/lua/5.1/popfix.lua'\n\tno file '/usr/lo
> cal/share/lua/5.1/popfix/init.lua'\n\tno file '/usr/local/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/popfix.lua'\n\tno file '/usr/local/Cellar/luajit-openresty/2.1-20220411/sh
> are/lua/5.1/popfix/init.lua'\n\tno file '/Users/kobzar/.cache/lvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/popfix.lua'\n\tno file '/Users/kobzar/.cache/lvim/packer_hererocks/2.1.0-
> beta3/share/lua/5.1/popfix/init.lua'\n\tno file '/Users/kobzar/.cache/lvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/popfix.lua'\n\tno file '/Users/kobzar/.cache/lvim/packer
> _hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/popfix/init.lua'\n\tno file './popfix.so'\n\tno file '/usr/local/lib/lua/5.1/popfix.so'\n\tno file '/usr/local/Cellar/luajit-openresty/2.
> 1-20220411/lib/lua/5.1/popfix.so'\n\tno file '/usr/local/lib/lua/5.1/loadall.so'\n\tno file '/Users/kobzar/.cache/lvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/popfix.so'" file="init.
> lua", line=112
> [packer.nvim] [DEBUG 10:04:53] packer.lua:380: packer.install: requiring modules
> [packer.nvim] [DEBUG 10:04:53] packer.lua:324: Processing plugin specs
> ```

Ah. You need to install `popfix` to make sure it works.

**Comment by kobzar** [comment]
Yes. NOw all is perfect. Thanks
