### ISSUE TITLE
Get file's type and have an empty result

### ISSUE THREAD

**Issue by FrankOu2001** [LunarVim/LunarVim#2637]
### Problem description

In `config.lua`, after writing following commands:
```lua
lvim.keys.normal_mode["<F5>"] = vim.cmd('echo &filetype')
-- or
lvim.keys.normal_mode["<F5>"] = string.format('echo %s', vim.bo.filetype)
```
Press `F5` and nothing is printed, which implements that the result of `echo &filetype` and `vim.bo.filetype` and `""`

### LunarVim version

aa4c993

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

macOS 12.3

### support info

# :Lviminfo
```
E5108: Error executing lua vim/shared.lua:0: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function <vim/shared.lua:0>
        vim/shared.lua: in function 'tbl_filter'
        ...junyue/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info'
        ...junyue/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'
        [string ":lua"]:1: in main chunk
```

**Comment by cpea2506** [comment]
It didn't work like that. You need to make it as an command:

```lua
lvim.keys.normal_mode["<F5>"] = [[:lua print(vim.bo.filetype)<cr>]]
```
<img width="217" alt="Screen Shot 2022-05-20 at 08 29 48" src="https://user-images.githubusercontent.com/42694704/169430603-cb7d821b-4546-4094-b56c-9c46b5ee108c.png">

**Comment by kylo252** [comment]
you can also see the filetype both on the statusline, and in `:LvimInfo`.
