### ISSUE TITLE
Error on writing to file

### ISSUE THREAD

**Issue by parasaito** [LunarVim/LunarVim#2640]
### Problem description

Sorry I can't describe in technical terms since I don't understand lua or much of lvim config.

Basically I keep getting this error when writing to a file. The write itself is successful, but the error prompt is annoying.

```console
Error detected while processing BufWritePre Autocommands for "*":                                                                                  
Error executing lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:452: end_col out of bounds                                              
stack traceback:                                                                                                                                   
        [C]: in function 'nvim_buf_set_text'                                                                                                       
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:452: in function 'apply_text_edits'                                                           
        .../$(whoami)/.local/share/lunarvim/lvim/lua/lvim/lsp/utils.lua:192: in function 'format'                                                      
        ...mi)/.local/share/lunarvim/lvim/lua/lvim/core/autocmds.lua:80: in function <...mi)/.local/share/lunarvim/lvim/lua/lvim/core/autocmds.lua:79
```

Remark : Replaced actual username with $(whoami) everywhere

### LunarVim version

aa4c993

### Neovim version (>= 0.7)

0.7.0

### Operating system/version

Linux fedora 5.17.8-300.fc36.x86_64

### Steps to reproduce

Save a file with `:w`

## LspInfo

```console
Language client log: /home/$(whoami)/.cache/lvim/lsp.log
 Detected filetype:   c
 
 1 client(s) attached to this buffer: 
 
 Client: clangd (id: 1, pid: 31840, bufnr: [30])
 	filetypes:       c, cpp, objc, objcpp
 	autostart:       true
 	root directory:  /home/$(whoami)/${PWD}
 	cmd:             clangd
 
 Configured servers list: clangd

```

## LvimInfo
```console
E5108: Error executing lua vim/shared.lua:0: t: expected table, got nil                                                                            
stack traceback:                                                                                                                                   
        [C]: in function 'error'                                                                                                                   
        vim/shared.lua: in function 'validate'                                                                                                     
        vim/shared.lua: in function <vim/shared.lua:0>                                                                                             
        vim/shared.lua: in function 'tbl_filter'                                                                                                   
        .../$(whoami)/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info'                                          
        .../$(whoami)/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'                                                
        [string ":lua"]:1: in main chunk 
```

**Comment by kylo252** [comment]
1. are you running anything besides clangd?
2. do you get the same error if you try formatting the buffer manually?
3. what's the value of `$LANG`, `$LANGUAGE`, `$LC_ALL`?
4. do you have a `.clang-format` file?

**Comment by parasaito** [comment]
> 1. are you running anything besides clangd?

No. In fact the only two servers installed are clangd and sumnekolua

> 2. do you get the same error if you try formatting the buffer manually?

Not sure what that means exactly. But if that means not using clangd, I tried stopping the Lsp server with `:LspStop` and I did NOT get that error, just a notification that " Format request failed, no matching language servers.". I get this notification everytime I write to file.

> 3. what's the value of `$LANG`, `$LANGUAGE`, `$LC_ALL`?

No idea what this means, these don't seem to be standard environment variables. Where do I execute/echo these?

> 4. do you have a `.clang-format` file?

I have a `compile_commands.json` file that is used by clangd, but nothing else. The work flow consists of GNU Make and I create the json file with [Bear](https://github.com/rizsotto/Bear)

**Comment by kylo252** [comment]
> Not sure what that means exactly. But if that means not using clangd, I tried stopping the Lsp server with `:LspStop` and I did NOT get that error, just a notification that " Format request failed, no matching language servers.". I get this notification everytime I write to file.

run `:lua vim.lsp.buf.format()`

> No idea what this means, these don't seem to be standard environment variables. Where do I execute/echo these?

run `:! echo LANG=$LANG LANGUAGE=$LANGUAGE LC_ALL=$LC_ALL`

> I have a `compile_commands.json` file that is used by clangd, but nothing else. The work flow consists of GNU Make and I create the json file with [Bear](https://github.com/rizsotto/Bear)

try configuring `clangd` manually to if it's any different: https://www.lunarvim.org/languages/c_cpp.html#lsp-settings
also try it with the flag `--offset-encoding=utf-16`, see https://github.com/kylo252/lvim/blob/b32d87febbe381349154c038a57d24f098b09e6f/after/ftplugin/c.lua#L12

**Comment by csy19960309** [comment]
> 3\. `$LC_ALL`

Meet this error in Windows 10 but using native Neovim instead.
Gets the same error if you try formatting the buffer manually, and a .clang-format file is there. No language server else besides clangd is in use.

**Comment by csy19960309** [comment]
> 1. are you running anything besides clangd?
> 
>     2. do you get the same error if you try formatting the buffer manually?
> 
>     3. what's the value of `$LANG`, `$LANGUAGE`, `$LC_ALL`?
> 
>     4. do you have a `.clang-format` file?

Gets the same error in Windows even if I format the source file manually. A .clang-format file is there and no language server else besides clangd is in use.

**Comment by huydangg** [comment]
I am facing the same issue (lsp: gopls)

**Comment by randalthor17** [comment]
Facing the same issue. Using bashls as LSP.
$LANG is en_US.UTF-8, $LANGUAGE and $LC_ALL are empty.
:lua vim.lsp.buf.format() gives this error:
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'format' (a nil value)
stack traceback:                                                                                                                                    
        [string ":lua"]:1: in main chunk
Also, if I do :LspRestart then do :w then I don't get the notifications, until i close lvim and reopen.
