### ISSUE TITLE
Errors while closing the :term buffer

### ISSUE THREAD

**Issue by jakubreron** [LunarVim/LunarVim#2642]
### Problem description

It is currently impossible to close a terminal buffer with `<cmd>BufferKill<CR>` command (mapped to `<Leader> c` in which-key)

Following error occurs:
```console
E5108: Error executing lua .../.local/share/lunarvim/lvim/lua/lvim/core/bufferline.lua:203: Vim(bdelete):E89: term://~/.config/lvim//17651:/bin/zsh will be killed (add ! to override)
stack traceback:
        [C]: in function 'cmd'
        .../.local/share/lunarvim/lvim/lua/lvim/core/bufferline.lua:203: in function 'buf_kill'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue

```

### LunarVim version

a245431 chore(docs): trim trailing white space

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

reproducible on both my Arch Linux and macOS Monterey 12.3.1

### Steps to reproduce

1. Open new terminal buffer using `:term` command
2. Try to close it with built-in "Close Buffer" command (`<Leader> c`)
3. The terminal does not close, we see an error instead:
![image](https://user-images.githubusercontent.com/25802053/169532761-43f0a5f5-63e0-4218-bcf4-5d81ce86e1b8.png)
```console
E5108: Error executing lua .../.local/share/lunarvim/lvim/lua/lvim/core/bufferline.lua:203: Vim(bdelete):E89: term://~/.config/lvim//17651:/bin/zsh will be killed (add ! to override)
stack traceback:
        [C]: in function 'cmd'
        .../.local/share/lunarvim/lvim/lua/lvim/core/bufferline.lua:203: in function 'buf_kill'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue

```

### support info

```console
 Language client log: /Users/jakub/.cache/lvim/lsp.log
 Detected filetype:   lua
 
 2 client(s) attached to this buffer: 
 
 Client: sumneko_lua (id: 1, pid: 16865, bufnr: [2])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /Users/jakub/.config/lvim
 	cmd:             lua-language-server
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [2])
 	filetypes:       typescriptreact, javascript, typescript, javascriptreact, vue, scss, less, css, sass, html, markdown, json, yaml, lua
 	autostart:       false
 	root directory:  /Users/jakub/.config/lvim
 	cmd:             nvim
 
 Configured servers list: sumneko_lua, vuels, tailwindcss, emmet_ls
```

```console
                                            
                                                __                          _    ___         
                                               / /   __  ______  ____ _____| |  / (_)___ ___ 
                                              / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
                                             / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
                                            /_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 
                                            
                                            
                                            Buffer info
                                            * filetype:                lua
                                            * bufnr:                   2
                                            * treesitter status:       active
                                            
                                            Active client(s)
                                            * name:                      sumneko_lua
                                            * id:                        1
                                            * supported filetype(s):     lua
                                            * attached buffers:          2
                                            * root_dir pattern:          2
                                            * capabilities:              referencesProvider      | definitionProvider        | foldingRangeProvider
                                                                         workspaceSymbolProvider | documentSymbolProvider    | hoverProvider
                                                                         typeDefinitionProvider  | documentHighlightProvider
                                            
                                            
                                            
                                            Formatters info
                                            * Active: stylua  
                                            * Supported: [lua_format, stylua]
                                            
                                            Linters info
                                            * Active: luacheck  
                                            * Supported: [luacheck, selene]
                                            
                                            Code actions info
                                            * Active: 
```

**Comment by abzcoding** [comment]
first off you can always use toggleterm ( `<c-t>`) or change the mapping using:
```lua
lvim.builtin.terminal.open_mapping = [[<c-\>]] -- use <c-\> for toggling
```

also do you see sth like this when you run `BufferKill` ?
<img width="588" alt="Screen Shot 2022-05-24 at 9 11 48 AM" src="https://user-images.githubusercontent.com/10992695/169950773-5bf636c4-ea1a-4ca2-9066-ef459f0a68b5.png">

and one last thing, do you run `<Leader>c` in Normal mode? ( do you press `ESC` in `:term` and then run `:BufferKill` ? )

**Comment by jakubreron** [comment]
@abzcoding I know we have toggleterm as a core plugin, but sometimes I just feel a need to have some terminals in split buffers to be able to see them all the time

This is what I see after running `:BufferKill` command on an empty `zsh` terminal buffer

![image](https://user-images.githubusercontent.com/25802053/169974862-fec8d084-7697-4603-87e0-7d674fe19665.png)
![image](https://user-images.githubusercontent.com/25802053/169974898-bb14314c-e8b2-4972-b760-d935d6abcb89.png)

And yep, I run `<Leader>c` and `:BufferKill` in normal mode (the terminal has focus, and I can navigate in it using the VIM movements, I cannot insert any text unless I press `i`)

**Comment by jakubreron** [comment]
Here is a screenshot from my Arch Linux machine (obviously old ThinkPad btw) after running `:BufferKill`, the error is mostly the same, but maybe it will help somehow

![image](https://user-images.githubusercontent.com/25802053/170226702-891254e8-faa6-450a-b725-8927537fa652.png)
```console
Error executing Lua callback: .../.local/share/lunarvim/lvim/lua/lvim/core/bufferline.lua:203: Vim(bdelete):E89: term://~/.config/personal/universal//7003:/bin/zsh will b
e killed (add ! to override)
stack traceback:
        [C]: in function 'cmd'
        .../.local/share/lunarvim/lvim/lua/lvim/core/bufferline.lua:203: in function 'buf_kill'
        ...ub/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:17: in function <...ub/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:16>
Press ENTER or type command to continue
```

If I click on this `x` thingy 
![image](https://user-images.githubusercontent.com/25802053/170227201-2cae4f11-9ecc-4969-8641-79ac5b521ef4.png)
or write `:bd!`, then it works (`:BufferKill!` with "!" doesn't work, but `:bd!` works 😐)

**Comment by kylo252** [comment]
I wouldn't call this a bug, it's just something that neovim does to help you avoid losing data. you should consider actually toggling the terminal instead of closing it (that's the whole point of using ToggleTerm 😄), try pressing `ctrl` + `\`

you can also simple assign `buf_kill` as well

```lua
vim.keymap.set("n", "<leader>C", function()
  local kill_cmd = "bd"
  local force = true
  require("lvim.core.bufferline").buf_kill(kill_cmd, 0, force)
end, { noremap = true, silent = true, desc = "force kill buffer" })
```

**Comment by jakubreron** [comment]
Yep it's a nice feature to have a confirmation dialog, but shouldn't I get a notice like this one?
![image](https://user-images.githubusercontent.com/25802053/170338272-00a61ce5-ef9a-42cf-b70c-e43ae5fded01.png)
I've tested it also on a clean install, it's weird that no one else has this error, I can recreate it every time across different machines with different operating systems 😱
Idk, maybe something is wrong with my nvim if it's not lvim config specific 🤔

I will leave this issue open, feel free to close it if no one else gets this error, thanks for all the replies 🙂

**Comment by kylo252** [comment]
@abzcoding, I'm even sure how he's getting that prompt 👀 

> Idk, maybe something is wrong with my nvim if it's not lvim config specific 🤔

I don't have it either 😄 

I made some improvements to `BufferKill` in #2658 to accommodate this and the unsaved changes case, let me know how you like the new workflow!

**Comment by abzcoding** [comment]
i think it comes from `dressing.nvim` we should really add it lunarvim, it helps with  `code_action + telescope` integration as well

**Comment by jakubreron** [comment]
The changes from #2658 work like a charm, thanks! 🎉
