### ISSUE TITLE
Exception on :LvimInfo, if buffer is empty, or using txt file

### ISSUE THREAD

**Issue by palandovalex** [LunarVim/LunarVim#2645]
### Problem description

1 Opening a txt file.
2 try to call Toggle LunarVim info
3 See traceback of strange exception.

### LunarVim version

a245431

### Neovim version (>= 0.7)

NVIM v0.8.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

from `cat /etc/lsb-release`: DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"

### Steps to reproduce

1 run lunarvim, i use  lvim
2 try to use :LvimInfo on txt file or an empty buffer
3 get exception.

### support info

E5108: Error executing lua vim/shared.lua:0: t: expected table, got nil
stack traceback:                                                                                                              
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function <vim/shared.lua:0>
        vim/shared.lua: in function 'tbl_filter'
        ...landov/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info'
        ...landov/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'
        [string ":lua"]:1: in main chunk

### Screenshots

In .lua file    command :LvimInfo works correctly
![LvimInfo](https://user-images.githubusercontent.com/75374436/169588527-15d00028-4d3c-4465-acd0-0b91677fc82f.png)

_No response_

**Comment by abzcoding** [comment]
yes, lviminfo is only supposed to work on buffers with known filetypes ( since it is only useful for showing lsp stuff)
