### ISSUE TITLE
How to add relative number

### ISSUE THREAD

**Issue by expacc007** [LunarVim/LunarVim#2646]

**Comment by jakubreron** [comment]
https://www.lunarvim.org/configuration/01-settings.html#example-options
👀

**Comment by megasuperlexa** [comment]
> https://www.lunarvim.org/configuration/01-settings.html#example-options 👀

Page not found

**Comment by eshaffer321** [comment]
vim.opt.relativenumber = false -- set relative numbered lines

This is now shown in the general configuration section of the docs.
https://www.lunarvim.org/docs/configuration/settings

**Comment by xuxu12333339A** [comment]
In  .local/share/lunarvim/lvim/lua/lvim/config/setting.lua

**Comment by xuxu12333339A** [comment]
In .local/share/lunarvim/lvim/lua/lvim/config/settings.lua
