### ISSUE TITLE
Norg.so sysmbol not found

### ISSUE THREAD

**Issue by MyraBaba** [LunarVim/LunarVim#2648]
### Problem description

:NeoStart always loading as first time downloading an give erroR:

install and reinstall both nvim & lunarvim same error:
nvim:0.8
lvim:rolling

<img width="1105" alt="Screen Shot 2022-05-23 at 02 44 34" src="https://user-images.githubusercontent.com/17505439/169721186-83139910-a5a0-40a7-9cf5-235c13c551d9.png">

### LunarVim version

rolling

### Neovim version (>= 0.7)

v0.8.dev

### Operating system/version

catalina 10.15

### Steps to reproduce

:NeorgStart

### support info

` 
 Language client log: /Users/tulpar/.local/state/nvim/lsp.log
 Detected filetype:   norg
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: clangd`

### Screenshots

attached

**Comment by abzcoding** [comment]
this is not a neovim/lunarvim issue
this is an issue with your compiler+neorg
check this out -> https://github.com/nvim-neorg/neorg/issues/74#issuecomment-906627223
