### ISSUE TITLE
Unable to remap which_key/lsp keybindings

### ISSUE THREAD

**Issue by akabolov** [LunarVim/LunarVim#2650]
Hey guys LunarVim gives me no errors,but I'm not able to remap default which_key binds like `Goto references` etc.

I've tried a couple of times with: 
```
lvim.builtin.which_key.mappings["g"] = { ["d"] = { "<cmd>Telescope lsp_definitions<cr>", "Goo to Definiton" } }
-- or
lvim.builtin.which_key.mappings["gd"] = {  "<cmd>Telescope lsp_definitions<cr>", "Goo to Definiton" } 

````

But I'm still having default vim's window. Could you please tell me what I'm doing wrong.
P.S. Remapping for normal mode didn't work as well but at least `:nmap gd` showed my remap there

**Comment by abzcoding** [comment]
those are buffer mappings, which are defined here:
https://github.com/LunarVim/LunarVim/blob/23df368b00bda0ed4a01fac92f7ad80998c1d34a/lua/lvim/lsp/config.lua#L95-L105

you can change them with this syntax
```lua
lvim.lsp.buffer_mappings.normal_mode["gd"] = {  "<cmd>Telescope lsp_definitions<cr>", "Goo to Definiton" }
```
