### ISSUE TITLE
Compile and post the changelog to the Lunarvim page

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#2661]
### Feature Description

I think this is a new feature.
Every-time I want to know what each version of lunarvim contains, I have to go through the commit history (let me know if it is a better way). I would prefer to be able to go to the main page of the project (specially when I'm on mobile) and be able to check it there.

### Describe the alternatives you have considered

I think there is no comfortable alternative other than going through GH interface and read the comments? Correct me if I'm wrong

**Comment by kobzar** [comment]
This is good idea
First, we must see verssion on the dashboard when lvim is started (not thr brunch name)
And secind one, get human desription on homepage/git/lvim with descriptions in humanity format
like
Version 1.3.2
  Newed: add some plugin
  Changes: in config
End add some command like LvimVersionLog analog of LvimChangeLog
Or replace action for last - no one needed read git changes in vim...

**Comment by kylo252** [comment]
There's already a [CHANGELOG.md](https://github.com/LunarVim/LunarVim/blob/master/CHANGELOG.md) file if you are on the master branch 😅 

I'm not sure this one makes too much sense for the rolling branch tho. Let me know if there are any other suggestions!
