### ISSUE TITLE
Need to modify cmp.lua when configuring nvim-cmp cmdline

### ISSUE THREAD

**Issue by kuang22** [LunarVim/LunarVim#2663]
### Problem description

Here I want to add a plugin cmp-cmdline which is a part of nvim-cmp.
I simply add the plugin name in my user configuration, but I need to setup this plugin like this:
```lua
cmp.setup.cmdline(":", {
  sources = cmp.config.sources({
    { name = "path" },
    { name = "cmdline" },
  }),
})
```
However, when I want to reference cmp by
```lua
cmp = require("cmp")
cmp.setup.cmdline(":", {
  sources = cmp.config.sources({
    { name = "path" },
    { name = "cmdline" },
  }),
})
```
It seems some problems related to permission happened, so that I could not add this cmdline configuration.

After exploring the lvim code directory, finally I have to put these code to lvim/core/cmp.lua like this:
```lua
function M.setup()
  require("cmp").setup(lvim.builtin.cmp)
  -- These code are added
  local cmp = require("cmp")
  cmp.setup.cmdline(":", {
    sources = {
      {name = 'cmdline'},
      {name = 'path'}
    }
  })
  cmp.setup.cmdline("/", {
    sources = {
      {name = 'buffer'}
    }
  })
  -- Done
end

```
Now, it works. BUT I have changed some files coming with lvim repo, so I wonder is there any interfaces to config un-predefined options of core plugins  in my user config file without changing lvim core config files?

### LunarVim version

3abb0a7

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

macOS 12.3.1

### support info

Maybe No need for this

**Comment by abzcoding** [comment]
```lua

-- to make sure you won't get any errors
  local cmp_ok, cmp = pcall(require, "cmp")
  if not cmp_ok or cmp == nil then
    cmp = {
      mapping = function(...) end,
      setup = { filetype = function(...) end, cmdline = function(...) end },
      config = { sources = function(...) end },
    }
  end

cmp.setup.cmdline(":", {
      mapping = cmp.mapping.preset.cmdline {},
      sources = {
        { name = "cmdline" },
        { name = "path" },
      },
})
```
