### ISSUE TITLE
Is this reference to lv-settings.lua deprecated?

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#2664]
Take a look here:
https://github.com/LunarVim/LunarVim/blob/7220f1f2041c35580cff799037f1421a211ccf79/lua/lvim/utils.lua#L48

**Comment by kylo252** [comment]
this is used as an output to the function containing that exact line 😄 

```sh
lvim --headless +'lua require("lvim.utils").generate_settings()' +qa && sort -o lv-settings.lua{,}
```

see: https://www.lunarvim.org/configuration/#configuration
