### ISSUE TITLE
green ansi issue on macos

### ISSUE THREAD

**Issue by 9xN** [LunarVim/LunarVim#2666]
### Problem description

installed lua rust cargo all python stuff ansi 256 bit terminal a nerd font with glyphs ( was having an issue but fixed it ) and nodejs and there seems to be an escape code issue or perhaps an ansi code difference issue ( maybe cause macos? ) any help would be appreciated

### LunarVim version

master-3475f76

### Neovim version (>= 0.7)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@BigSur  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"

### Operating system/version

macOS 11.4

### Steps to reproduce

lvim

### support info

![Screen Shot 2022-05-28 at 12 03 47 AM](https://user-images.githubusercontent.com/94141577/170812506-2d5606e9-7114-4e61-b15e-9114210512a0.png)
![Screen Shot 2022-05-28 at 12 04 07 AM](https://user-images.githubusercontent.com/94141577/170812514-0ea6759b-325d-450d-934f-3892f2b96086.png)

### Screenshots

![Screen Shot 2022-05-28 at 12 01 50 AM](https://user-images.githubusercontent.com/94141577/170812439-2c925438-d8e3-480e-99a0-a21b331ff49d.png)
![Screen Shot 2022-05-28 at 12 02 02 AM](https://user-images.githubusercontent.com/94141577/170812443-9eaae048-2e78-42e0-86f8-ff0836ebbba3.png)
![Screen Shot 2022-05-28 at 12 03 13 AM](https://user-images.githubusercontent.com/94141577/170812487-e3bea583-17d4-41b4-9bbf-ddb91d6af238.png)

**Comment by kobzarchekg** [comment]
Try to use iterm
https://iterm2.com

**Comment by Uzaaft** [comment]
This seems to be an issue with your term, and not with Lunarvim.

**Comment by 9xN** [comment]
> Try to use iterm https://iterm2.com

same thing is happening but on a shittier terminal now

**Comment by 9xN** [comment]
![Screen Shot 2022-05-28 at 10 04 55 PM](https://user-images.githubusercontent.com/94141577/170851681-533d1920-caaa-49ad-9a9e-31a3d6d2bb89.png)
ive tried all these encodings and none of them make it work

**Comment by 9xN** [comment]
![Screen Shot 2022-05-28 at 10 08 12 PM](https://user-images.githubusercontent.com/94141577/170851760-108a0e76-2792-4bc6-b8ee-d6aced4765b0.png)

**Comment by 9xN** [comment]
![Screen Shot 2022-05-28 at 10 10 16 PM](https://user-images.githubusercontent.com/94141577/170851800-b64f6936-7b63-47e4-8cff-6650e69f1f3d.png)

update: when i disable the display ansi colours flag it gets rid of the bars and disgusting shit the only problem is that now there are no colours and no syntax shit or anything special

**Comment by 9xN** [comment]
double update: i found the issue; its that macos terminal.app doesnt support true colour 24 bit ansi escape colour codes, its only goes up to 256, ill have to make a fork of neovim in general or find another solution (probably just patch and compile my own version of neovim and lunarvim to change out the colour codes)

**Comment by Uzaaft** [comment]
iterm2 has 24-bit and 256 bit modes. I have no issue while using iterm2 with Lunarvim.
What is your term variable?

**Comment by kobzar** [comment]
You also can try to disable 
termguicolors in config. 
but really use normal terminal emulator like iterm2 or alacritty.

**Comment by 9xN** [comment]
> iterm2 has 24-bit and 256 color modes. I have no issue while using iterm2 with Lunarvim. What is your term variable?

i literally showed that i tried every single one possible in the screen shots above lol
![Screen Shot 2022-05-29 at 9 58 40 PM](https://user-images.githubusercontent.com/94141577/170914656-5493c8db-f102-4e8c-8f0c-8e4c86f461fb.png)
currently using xterm-256color

**Comment by 9xN** [comment]
> You also can try to disable termguicolors in config. but really use normal terminal emulator like iterm2 or alacritty.

i cant live without apples terminal its so much better

**Comment by Uzaaft** [comment]
> > You also can try to disable termguicolors in config. but really use normal terminal emulator like iterm2 or alacritty.
> 
> i cant live without apples terminal its so much better


Can you attempt to run the following script https://github.com/gnachman/iTerm2/blob/master/tests/24-bit-color.sh
Btw, most people prefer other terms instead of apples terminal, me included.

**Comment by 9xN** [comment]
> > > You also can try to disable termguicolors in config. but really use normal terminal emulator like iterm2 or alacritty.
> > 
> > 
> > i cant live without apples terminal its so much better
> 
> Can you attempt to run the following script https://github.com/gnachman/iTerm2/blob/master/tests/24-bit-color.sh Btw, most people prefer other terms instead of apples terminal, me included.

ok well i dont

**Comment by 9xN** [comment]
![Screen Shot 2022-05-30 at 1 52 35 PM](https://user-images.githubusercontent.com/94141577/171052858-b6c244ff-f2df-4854-bd5e-c465c45c017a.png)

**Comment by 9xN** [comment]
nothing shows up

**Comment by 9xN** [comment]
> Then your does not support 24-bit color. I guess we should add it as a requirement. @kylo252 @abzcoding Any idea where it should go? I can open a PR for it at Lunarvim.org

yea i know i figured that out about an hour after i opened the issue lol (thought i mentioned it) personally i would recommend changing the colour settings to just use 256 coloured escape codes i dont think theres very many terminals that cant support that

**Comment by Uzaaft** [comment]
Then you can go ahead and close the issue. 

From what I have gathered, most standard shells on Linux(Konsole etc) , and even the windows terminal has support for it. So it's a sensible default. And most users on Apple machines use another terminal.

You can just change the theme in your lunarvim config, or change the terminal. I don't think we will be changing the default colortheme just because the default apple terminal does not support 24-bit color, especially when the consensus is that most apple user's use iterm2.

**Comment by kylo252** [comment]
I'm not really all that familiar with iterm2, so I'm pretty sure I've only done some minimal changes to the default profile, you can see it here https://gist.github.com/kylo252/5d4a544d6bfbb2341f07217dcef5a7b1

maybe @abzcoding has better experience with it, although I know he prefers kitty 😸

**Comment by Uzaaft** [comment]
@kylo252  Problem is that the user prefers the built in Mac terminal.

**Comment by kobzar** [comment]
If you dont want use iterm 
Try to neovide + lvim

**Comment by abzcoding** [comment]
please use anything but the default mac terminal
https://github.com/neovim/neovim/issues/11327

**Comment by Uzaaft** [comment]
@abzcoding @kylo252 You guys can just go ahead and close the issue. We’ve found the issue.

**Comment by 9xN** [comment]
> please use anything but the default mac terminal [neovim/neovim#11327](https://github.com/neovim/neovim/issues/11327)

this isnt helping anyone

**Comment by 9xN** [comment]
> Ok. I see you dont understand something. So, catch the official answer: LunarVim isn’t correctly work in Terminal.app Choose another terminal or Vimdistro. try SpaceVim.
> 
> Please, close the issue.

are you fucking stupid or retarded i cant tell

**Comment by Uzaaft** [comment]
> > Ok. I see you dont understand something. So, catch the official answer: LunarVim isn’t correctly work in Terminal.app Choose another terminal or Vimdistro. try SpaceVim.
> > Please, close the issue.
> 
> are you fucking stupid or retarded i cant tell

No need to use such words, keep things civil.

**Comment by kylo252** [comment]
> holy christ for the 5th time i dont want to use iterm

sorry, I assumed that iterm _is_ the default terminal, my bad!

> this isnt helping anyone

sorry again if the solution wasn't clear, you basically need to turn off [termguicolors](https://neovim.io/doc/user/options.html#'termguicolors'), add this somewhere to your `config.lua`

```lua
vim.opt.termguicolors = false
```

keep in mind, you really should check which plugins require this setting, here's a quick way to do it

```bash
# you can also filter the results further with `--type` 
rg 'termguicolors' ~/.local/share/lunarvim/site
```

**Comment by kobzar** [comment]
> > holy christ for the 5th time i dont want to use iterm
> 
> sorry, I assumed that iterm _is_ the default terminal, my bad!
> 
> > this isnt helping anyone
> 
> sorry again if the solution wasn't clear, you basically need to turn off [termguicolors](https://neovim.io/doc/user/options.html#'termguicolors'), add this somewhere to your `config.lua`
> 
> ```lua
> vim.opt.termguicolors = false
> ```
> 
> keep in mind, you really should check which plugins require this setting, here's a quick way to do it
> 
> ```shell
> # you can also filter the results further with `--type` 
> rg 'termguicolors' ~/.local/share/lunarvim/site
> ```

I was advise it for him here
https://github.com/LunarVim/LunarVim/issues/2666#issuecomment-1140508378
