### ISSUE TITLE
Quit whitekey should not quit by force

### ISSUE THREAD

**Issue by YaQia** [LunarVim/LunarVim#2667]
### Feature Description

I've using lunarvim for half a year, but recently the quit action really confuse me. Once I finished editing with my code, I simply typed <Space>q to quit, only found the file leaved unchanged. I was wandering **why shouldn't it just save and quit**? **It's there any concern about that?**

I changed my which-key.lua configuration file, set the quit action to be \<cmd\>wq\<CR\>, which works perfect till now.

**Comment by YaQia** [comment]
now I change it to just <cmd>q<CR>, because w is not avaliable for temp buffer.

**Comment by kylo252** [comment]
fixed in https://github.com/LunarVim/LunarVim/pull/2554
