### ISSUE TITLE
Opening empty dart files crashes LunarVim

### ISSUE THREAD

**Issue by AmaaelTyrneaMitore** [LunarVim/LunarVim#2668]
### Problem description

Fresh installation of LunarVim crashes when I try to open an empty dart file with the following error in the terminal:
`fish: Job 1, 'nvim $argv' terminated by signal SIGSEGV (Address boundary error)`

And sometimes, when it manages to open that empty dart file, it crashes again with the same error as soon as I enter insert mode or try to type some text in insert mode. And if try to create an empty dart file as `touch test.dart` and then if I do `echo "print('A');" >> test.dart` and then I try to open it, it still crashes.

And also, sometimes when it opens the file and let me edit it, then I don't know what happens with the LSP, it doesn't start. I noticed that when I try to open a dart file from my flutter project (already popoulated with code), there the LSP and LVim works just fine but when I try to open an empty file, it either crashes or LSP doesn't work

I installed Neovim using `pacman`
I tried using both Kitty and Alacritty terminal

### LunarVim version

master-3475f76

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

Linux poseidon 5.17.9-arch1-1 #1 SMP PREEMPT Wed, 18 May 2022 17:30:11 +0000 x86_64 GNU/Linux

### Affected language servers

all

### Steps to reproduce

1.) Install LunarVim using the official install script provided by this repo.
2.) Open an empty dart file
3.) If it doesn't crash in the above step, then try to type some text in insert mode.

### Actual behavior

Suddenly crashes with an error message in the terminal saying: `fish: Job 1, 'nvim $argv' terminated by signal SIGSEGV (Address boundary error)`

### Expected behavior

Umm... work?

## Output of `:LspInfo`

```
Language client log: /home/honey/.cache/lvim/lsp.log
 Detected filetype:   dart
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: dart
 
 Config: dartls
 	filetypes:         dart
 	root directory:    NA
 	cmd:               dart language-server
 	cmd is executable: true (checked by nvim-lsp-installer)
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: dartls
```

## Output of `:LvimInfo`
                             
```
                                 __                          _    ___         
                                / /   __  ______  ____ _____| |  / (_)___ ___ 
                               / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
                              / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
                             /_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 
                             
                             
                             Buffer info
                             * filetype:                dart
                             * bufnr:                   8
                             * treesitter status:       inactive
                             
                             Active client(s)
                             
                             
                             
                             Formatters info
                             * Active: 
                             * Supported: dart_format
                             
                             Linters info
                             * Active: 
                             * Supported: []
                             
                             Code actions info
                             * Active: 

```

### logs

```console
I don't know how where to find logs..
```

### Screenshots

![2022-05-29-00_20_07-selection](https://user-images.githubusercontent.com/96770927/170839099-f09ec642-b8bb-4177-80f4-c497aa9cfaa0.png)

**Comment by Uzaaft** [comment]
Please check the[Troubleshooting guide]( https://www.lunarvim.org/troubleshooting/#language-server-xxx-does-not-start-for-me) before creating an issue.
