### ISSUE TITLE
Shorter file finder keymap on nvim-tree

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#2670]
### Feature Description

I think the current way of finding files in nvim-tree is too complex and very few people actually uses it.
However, there is the key `f`, which makes very little sense within in the context of nvim-tree (do you really need to jump to an specific char of a file name??).
I think we should take advantage of the mnemonic of F for files and map `f` to the telescope find files that now is behind `gtf`, which is too long for such a common operation.
Note that this is in line with other default mappings, for example `q` does not record a macro, it closes the window.

### Describe the alternatives you have considered

I have customized it on my local config, but I think majority of users will take advantage of this.

**Comment by kobzar** [comment]
Why are You dont use "/" for search file in nvimTree?

**Comment by danielo515** [comment]
I do use it when I want to jump to certain file or folder that it's in view. But it is different from what the action behind `gtf` offers. What I'm proposing to add opens a popup that allows you to fuzzy find within certain folder, without it having to be open

**Comment by kylo252** [comment]
nvim-tree now supports using `f` for filtering, still feel free to open a PR if you have some suggestions for a better remap.
