### ISSUE TITLE
How do I get rid of this warning?

### ISSUE THREAD

**Issue by beyourahi** [LunarVim/LunarVim#2673]
### Problem description

Every time I open LVIM I get the following warning

`Following options were moved to setup, see bit.ly/3vIpEOJ: nvim_tree_root_folder_modifier, nvim_tree_show_icons, nvim_tree_icons....`

How do I deal with this?

### LunarVim version

master-3475f76

### Neovim version (>= 0.7)

NVIM v0.8.0-dev+334-ge9803e1de

### Operating system/version

Parrot OS Home Edition 5.0.1 Electro Ara

### support info

LspInfo:
```console
Language client log: /home/rahi/.local/state/nvim/lsp.log
 Detected filetype:   NvimTree
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: 
```

LvimInfo:
```console
Error executing Lua callback: vim/shared.lua:224: t: expected table, got nil
stack traceback:                                                                                                                                                                    
        [C]: in function 'error'
        vim/shared.lua:688: in function 'validate'
        vim/shared.lua:224: in function 'func'
        vim/shared.lua:211: in function 'tbl_filter'
        ...e/rahi/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info'
        ...e/rahi/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'
        ...hi/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:29: in function <...hi/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:28>
```

### Screenshots

![image](https://user-images.githubusercontent.com/65137116/170945457-c852f62a-d39d-4798-b91e-3b767f23c710.png)

**Comment by kjgfcdb** [comment]
It is related to #2665. If you want to get rid of it temporarily, simply comment this line

https://github.com/LunarVim/LunarVim/blob/7220f1f2041c35580cff799037f1421a211ccf79/lua/lvim/core/nvimtree.lua#L163

**Comment by beyourahi** [comment]
in which file and where do I find it?
sorry I'm new to all these

**Comment by AmaaelTyrneaMitore** [comment]
You should have a look at #2665.

**Comment by gnmearacaun** [comment]
that file is located at `~/.local/share/lunarvim/lvim/lua/lvim/core/nvimtree.lua` on Linux. If you comment out line 163 with `--` as was suggested you may run into a merge conflict the next time you update lunarvim because the file is part of lunarvim core. You might be as well to live with the error until it is fixed by the core team.

**Comment by ggteixeira** [comment]
Hi! I'm running Lunarvim's latest version, and still gettint that annoying nvim-tree notification. Do you know what could've happened?

**Comment by abzcoding** [comment]
> Hi! I'm running Lunarvim's latest version, and still gettint that annoying nvim-tree notification. Do you know what could've happened?

just to be sure packer didn't do anything weird run this
```shell
cd ~/.local/share/lunarvim/site/pack/packer/start/nvim-tree.lua
git reset --hard
git pull origin master
```

also make sure that you are on the rolling branch of lunarvim
```shell
cd ~/.local/share/lunarvim/lvim
git status
git rev-parse HEAD
```
<img width="404" alt="Screen Shot 2022-06-04 at 10 35 04 PM" src="https://user-images.githubusercontent.com/10992695/172020003-fe4a9bb7-4003-4205-96a1-44c29db61036.png">

**Comment by gnmearacaun** [comment]
If your choice is to stay on the master branch,  you can replace your nvimtree.lua with the contents of rollings https://github.com/LunarVim/LunarVim/blob/rolling/lua/lvim/core/nvimtree.lua

**Comment by ggteixeira** [comment]
> also make sure that you are on the rolling branch of lunarvim

Thank you, I did the 1/2 part, and pulled nvim-tree from its master branch.

However, according to the docs, lvim's rolling branch brings the bugs, and I need to stick to the stable branch 😞 

Maybe the best thing to do in this case is turning off the notification as mentioned [here](https://github.com/LunarVim/LunarVim/issues/2673#issuecomment-1141010166)?

**Comment by gnmearacaun** [comment]
It's safe to ignore that line in the docs. It is misleading and needlessly alarming for new users. The above is an example of the opposite being true. The LunarVim master branch historically is way behind, and new releases are few and far between. Almost everyone is using rolling except those rightly scared off by the words "all the latest bugs". That said, the issue will be fixed with PR #2692 

        "Trust the developers, not the code hosting infrastructure." ~[Linux Kernel Maintainers PGP Guide](https://www.kernel.org/doc/html/latest/process/maintainer-pgp-guide.html)

**Comment by ggteixeira** [comment]
Thanks for clarifying @gnmearacaun! I'll switch to rolling release. And thanks for the fix!

**Comment by ggteixeira** [comment]
You're right, I agree. I've been using Vim since 2017-18, but I am a complete newbie when it comes to Neovim w/ Lua and LunarVim.

> Have we crossed paths before in the After-Dark (Hugo theme) community

I don't think so, but I hope that Guilherme treated you well. We Guilhermes are known for being nice people :)
