### ISSUE TITLE
Is there a way to get WebStorm like tooltips when hovering html elements and css classes in jsx/tsx?

### ISSUE THREAD

**Issue by spacegoldminer** [LunarVim/LunarVim#2676]
### Feature Description

I like the extra information Webstorm provides when hovering certain elements in jsx/tsx files, like showing information about what a class entails, information about an html tag, etc.

Having enabled tsserver, eslint, and css lsp servers in lunarvim, i hoped to get something similar using peek definition, but i don't get anything of the sort.

Is such functionality possible and if so how can i use it?

https://user-images.githubusercontent.com/106533249/170995935-14e0fd53-79c6-40df-99dd-4a5c0d05e3ba.mp4

**Comment by kobzar** [comment]
Shift + K
