### ISSUE TITLE
Indent Blankline Highlight groups are not working

### ISSUE THREAD

**Issue by AmaaelTyrneaMitore** [LunarVim/LunarVim#2677]
### Problem description

Installed the [Indent-Blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) plugin. Everything is working except the highlight groups are not working. I am unable to apply custom color scheme for indent line. It just shows the default colors.

### LunarVim version

rolling-ed50b7d

### Neovim version (>= 0.7)

NVIM v0.8.0-dev+336-g8427da929

### Operating system/version

Linux 

### Steps to reproduce

Installed the plugin by using packer and used the following configurations:

```
local status_ok, indent_blankline = pcall(require, "indent_blankline")
if not status_ok then
  return
end

vim.g.indent_blankline_buftype_exclude = { "terminal", "nofile" }
vim.g.indent_blankline_filetype_exclude = {
  "help",
  "startify",
  "dashboard",
  "packer",
  "neogitstatus",
  "NvimTree",
  "Trouble",
}
vim.g.indentLine_enabled = 1
vim.g.indent_blankline_char = "▏"
vim.g.indent_blankline_show_trailing_blankline_indent = false
vim.g.indent_blankline_show_first_indent_level = true
vim.g.indent_blankline_use_treesitter = true
vim.g.indent_blankline_show_current_context = true
vim.g.indent_blankline_context_patterns = {
  "class",
  "return",
  "function",
  "method",
  "^if",
  "^while",
  "jsx_element",
  "^for",
  "^object",
  "^table",
  "block",
  "arguments",
  "if_statement",
  "else_clause",
  "jsx_element",
  "jsx_self_closing_element",
  "try_statement",
  "catch_clause",
  "import_statement",
  "operation_type",
}
vim.wo.colorcolumn = "99999"

vim.cmd([[highlight IndentBlanklineIndent1 guifg=#bd93f9 gui=nocombine]])
vim.cmd([[highlight IndentBlanklineIndent2 guifg=#ffb86c gui=nocombine]])
vim.cmd([[highlight IndentBlanklineIndent3 guifg=#50fa7b gui=nocombine]])
vim.cmd([[highlight IndentBlanklineIndent4 guifg=#f1fa8c gui=nocombine]])
vim.cmd([[highlight IndentBlanklineIndent5 guifg=#8be9fd gui=nocombine]])
vim.cmd([[highlight IndentBlanklineIndent6 guifg=#f8f8f2 gui=nocombine]])
vim.cmd([[highlight IndentBlanklineContextChar guifg=#ff79c6 gui=nocombine]])
vim.cmd([[highlight NvimTreeIndentMarker guifg=#ff79c6 gui=nocombine]])
vim.opt.list = true

indent_blankline.setup({
  show_current_context = true,
  char_highlight_list = {
    "IndentBlanklineIndent1",
    "IndentBlanklineIndent2",
    "IndentBlanklineIndent3",
    "IndentBlanklineIndent4",
    "IndentBlanklineIndent5",
    "IndentBlanklineIndent6",
  },
})
```

### support info

not necessary 

### Screenshots

![2022-05-31-04_05_58-selection](https://user-images.githubusercontent.com/96770927/171065288-fb597e37-338c-447e-90f5-93f286c5fae1.png)

**Comment by kobzar** [comment]
Use documentation
Just add plugin for example

  -- indentation guides for every line
  {
    "lukas-reineke/indent-blankline.nvim",
    event = "BufRead",
    setup = function()
      vim.g.indentLine_enabled = 1
      vim.g.indent_blankline_char = "‚ñè"
      vim.g.indent_blankline_filetype_exclude = { "help", "terminal", "dashboard", "lspinfo" }
      vim.g.indent_blankline_buftype_exclude = { "terminal", "dashboard", "nofile", "quickfix" }
      vim.g.indent_blankline_show_trailing_blankline_indent = false
      vim.g.indent_blankline_show_first_indent_level = false
      vim.g.indent_blankline_show_current_context = true
      vim.g.indent_blankline_show_current_context_start = true
    end
  },

**Comment by AmaaelTyrneaMitore** [comment]
Also, when I tried to apply highlight group using the command line by running `:highlight IndentBlanklineIndent1 guifg=#bd93f9 gui=nocombine`, It works, so I guess maybe the groups are getting overridden or something like that? I don't know, I am new to vim.

**Comment by AmaaelTyrneaMitore** [comment]
Uhm.. I'm pretty sure this is a very active repo but still I don't have any response from anyone, should I close this issue?

**Comment by kobzar** [comment]
Did you try to add configuration in lunarvim style?
Just remove you raw config and configuration example as i show you.
For example, in my case we can see ancor BuffRead e.t.c.
You are want use lunarvim but choose raw nvim way. 
Just try it, i hope it will resolve your issue

**Comment by xtevenx** [comment]
I had the same issue and it was because my colorscheme was overwriting the highlights. Not sure how LunarVim organizes highlights though (I came across this while googling for solutions).

Solution for me was to just chuck in the highlight definition after the colorscheme. Perhaps with packer you can use the config term and the `after` directive? I'm not sure.

**Comment by AmaaelTyrneaMitore** [comment]
Instead of specifying the plugin configuration in `config.lua` file, I used `ftplugin` and specified config for every file type in `after/ftplugin/<filetype>.lua` and now it works. At first I though my colorscheme is overriding the highlight groups but that wasn't the case. It's working now.

**Comment by kobzar** [comment]
Attach some filetype config for future please

**Comment by AmaaelTyrneaMitore** [comment]
Sure, here is the config that I used for every file type. Place it under `after/ftplugin/<filetype>.lua`. The highlight groups are based on Dracula Theme.

```
local status_ok, indent_blankline = pcall(require, "indent_blankline")
if not status_ok then
  return
end

vim.g.indent_blankline_buftype_exclude = { "terminal", "nofile" }
vim.g.indent_blankline_filetype_exclude = {
  "help",
  "startify",
  "dashboard",
  "packer",
  "neogitstatus",
  "NvimTree",
  "Trouble",
}
vim.g.indentLine_enabled = 1
-- vim.g.indent_blankline_char = "│"
vim.g.indent_blankline_char = "▏"
-- vim.g.indent_blankline_char = "▎"
vim.g.indent_blankline_show_trailing_blankline_indent = false
vim.g.indent_blankline_show_first_indent_level = true
vim.g.indent_blankline_use_treesitter = true
vim.g.indent_blankline_show_current_context = true
vim.g.indent_blankline_context_patterns = {
  "class",
  "return",
  "function",
  "method",
  "^if",
  "^while",
  "jsx_element",
  "^for",
  "^object",
  "^table",
  "block",
  "arguments",
  "if_statement",
  "else_clause",
  "jsx_element",
  "jsx_self_closing_element",
  "try_statement",
  "catch_clause",
  "import_statement",
  "operation_type",
}
vim.wo.colorcolumn = "99999"

vim.cmd [[highlight IndentBlanklineIndent1 guifg=#bd93f9 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent2 guifg=#ffb86c gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent3 guifg=#50fa7b gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent4 guifg=#f1fa8c gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent5 guifg=#8be9fd gui=nocombine]]
vim.cmd [[highlight IndentBlanklineIndent6 guifg=#f8f8f2 gui=nocombine]]
vim.cmd [[highlight IndentBlanklineContextChar guifg=#ff79c6 gui=nocombine]]
vim.cmd [[highlight NvimTreeIndentMarker guifg=#ff79c6 gui=nocombine]]
vim.opt.list = true

indent_blankline.setup({
  show_current_context = true,
  char_highlight_list = {
    "IndentBlanklineIndent1",
    "IndentBlanklineIndent2",
    "IndentBlanklineIndent3",
    "IndentBlanklineIndent4",
    "IndentBlanklineIndent5",
    "IndentBlanklineIndent6",
  },
})
```

**Comment by MrMic** [comment]
> Also, when I tried to apply highlight group using the command line by running `:highlight IndentBlanklineIndent1 guifg=#bd93f9 gui=nocombine`, It works, so I guess maybe the groups are getting overridden or something like that? I don't know, I am new to vim.

Got the same issue!
Struggle and cannot configure indent_blankline! :(
