### ISSUE TITLE
Question: How to interact with virtual text `Run | Run Test | Debug`?

### ISSUE THREAD

**Issue by dycw** [LunarVim/LunarVim#2679]
### Problem description

I'm unable to find help on how to use these as I don't know the proper name of these.

![image](https://user-images.githubusercontent.com/10572122/171066858-c98444a6-d0f8-4cca-98ff-874a61266466.png)

### LunarVim version

master-3475f76

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

Ubuntu 22.04 LTS

### Steps to reproduce

Current example is a simple `rust` file, with contents:

```rust
#[test]                                
fn test_main() {
   timeout_ms(                        
        || {                           
        │   elevator::run_simulation();
        },                             
        300000,                        
   );                                 
}                                      

### support info

None

### Screenshots

_No response_

**Comment by dycw** [comment]
Sorry am I missing something here? In the screenshot above, `shift + K` on `fn`, `test_main()` or `{` all give documentation but no actions. For example:

![image](https://user-images.githubusercontent.com/10572122/171177705-946acdf3-d0c5-4093-b548-62a08f98b386.png)

**Comment by abzcoding** [comment]
using `<leader>ll` or 
```vim
:lua vim.lsp.codelens.run()
```

**Comment by dycw** [comment]
Hi @cpea2506 , @abzcoding , thank you both!
