### ISSUE TITLE
Global statusline should not be hidden when nvim-tree has focus

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#2682]
### Problem description

When you open nvim-tree it hides the statusline, which makes sense when you have per-window statuslines, but it does not make much sense if you have a global one, in that case, it is annoying.

1. set `vim.opt.laststatus = 3`
2. open nvim-tree window
3. See how the statusline dissapears

I think lvim should inspect the value of laststatus and then do not set the option to hide the statusline when focusing nvim-tree

### LunarVim version

aa4c993

### Neovim version (>= 0.7)

NVIM v0.7.0-dev+882-g9304ee387

### Operating system/version

macOS 12.4

### Steps to reproduce

`vim.opt.laststatus = 3`

### support info

<img width="850" alt="image" src="https://user-images.githubusercontent.com/2270425/171336533-8b90f8b8-5963-4655-bf8c-23e993fcdf07.png">

**Comment by danielo515** [comment]
Hello @kylo252 , thanks for the configuration, works like a charm (albeit I tuned it a bit to my liking 😄 )
Don't you think that `globalstatus` can be put into lunarvim default configuration?

By the way, now that I have statusline globally enabled, I see it adds value even for the nvim-tree buffer. Take a look at this screenshot:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/2270425/171569203-6f461cb4-b5b1-469e-bf34-f310cc688aec.png">

It shows the currently working directory, no matter the scroll status of the tree (which in my case can be huge) you always see the CWD. For me that is very valuable!

**Comment by abzcoding** [comment]
> we could also just have a different theme if global statusline is enabled.
> pinging our resident design lead, wdyt @abzcoding?

well tbh, I do love adding `global statusline + winbar + dressing.nvim` to lunarvim and making it the default behavior because it looks wonderful but sadly I can't find the spare time to do it rn 😢
