### ISSUE TITLE
No syntax highlighting for Terraform (.tf) files

### ISSUE THREAD

**Issue by colutti** [LunarVim/LunarVim#2684]
### Problem description

Fresh install of Lunarvim. The LSP is installed, but there is no highlighting for .tf files (terraform).

### LunarVim version

master-3475f76

### Neovim version (>= 0.7)

0.7.0

### Operating system/version

macOS 11.6.6

### Affected language servers

terraformls

### Steps to reproduce

Create a .tf file

### Actual behavior

There would be no highlighting. 

### Expected behavior

Highlighting should work

### Screenshots

![sc1](https://user-images.githubusercontent.com/9368892/171583772-c7054efd-4850-4690-a07a-7e89c7efa291.png)
![sc2](https://user-images.githubusercontent.com/9368892/171583776-86fb74e5-fa92-4329-bba4-ae5e18011163.png)

**Comment by kylo252** [comment]
This looks like a regression in https://github.com/nvim-treesitter/nvim-treesitter/commit/58a4897e6d5f21a9178ae0f802d47af26d67a219, please open an issue at their repo to track it.

In the meantime, this should work `:TSInstall hcl`

**Comment by csalotti** [comment]
For those who still encounter the same issue, you also need to ensure that terraform is installed with treesitter :
`:TSInstall terraform`
