### ISSUE TITLE
Untracked symbol

### ISSUE THREAD

**Issue by kobzar** [LunarVim/LunarVim#2685]
### Feature Description

When we use git status icons for nvim-tree the untracked files has “U” symbol. 
This is bad idea, because the file has name. 

So, best solution, is change letter to some symbol or glyphs. Like +/- etc by default.

**Comment by kobzar** [comment]
I was fixed it by myself by next configuration
```
lvim.builtin.nvimtree.setup.renderer.icons.glyphs.git = {
          unstaged = "✗",
          staged = "✓",
          unmerged = "",
          renamed = "➜",
          untracked = "★",
          deleted = "",
          ignored = "◌",
}
```
But maybe we have options to use it by default?
-- File explorer settings
lvim.builtin.nvimtree.setup.view.side = "right"
lvim.builtin.nvimtree.setup.renderer.icons.show.git = true

**Comment by rebuilt** [comment]
You can also set the symbol for untracked directly with:
```
lvim.builtin.nvimtree.setup.renderer.icons.glyphs.git["untracked"] = "★"
```

**Comment by rebuilt** [comment]
Or you can use
```
lvim.builtin.nvimtree.setup.renderer.icons.glyphs.git.untracked = "★"
```
