### ISSUE TITLE
No starts after update nvim

### ISSUE THREAD

**Issue by epileftro85** [LunarVim/LunarVim#2686]
### Problem description

nvim --version                                                                                                                                                                           andres@andres-clavijo
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-xCvtFQ/neovim-0.7.0~ubuntu1+git202206022131-9745941ef-dd05b3569=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-xCvtFQ/neovim-0.7.0~ubuntu1+git202206022131-9745941ef-dd05b3569/build/config -I/build/neovim-xCvtFQ/neovim-0.7.0~ubuntu1+git202206022131-9745941ef-dd05b3569/src -I/build/neovim-xCvtFQ/neovim-0.7.0~ubuntu1+git202206022131-9745941ef-dd05b3569/.deps/usr/include -I/usr/include -I/build/neovim-xCvtFQ/neovim-0.7.0~ubuntu1+git202206022131-9745941ef-dd05b3569/build/src/nvim/auto -I/build/neovim-xCvtFQ/neovim-0.7.0~ubuntu1+git202206022131-9745941ef-dd05b3569/build/include
Compiled by buildd@lcy02-amd64-039

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

`[1]    12354 segmentation fault (core dumped)  lvim` <= This is the error when it doesn't start

### LunarVim version

master

### Neovim version (>= 0.7)

v0.8.0-dev

### Operating system/version

Ubuntu 20.04

### Steps to reproduce

It has no steps to repruduce, I think is the new version of nvim.

### support info

Can't give more specifications due I can't even start lunarvim

**Comment by DouglasMarq** [comment]
I've just updated my ubuntu and it is throwing 18897 segmentation fault (core dumped)  /home/user/.local/bin/lvim as well, both in stable and rolling update branch.

**Comment by kobzar** [comment]
try remove your nvim like apt purge neovim
And install it manual from downloaded deb package from oficial repo
https://github.com/neovim/neovim/releases/tag/v0.7.0

**Comment by RomjanHossain** [comment]
I'm having the **19894 segment fault  (core dump)** error too

**Comment by kobzar** [comment]
> I'm having the **19894 segment fault (core dump)** error too

Did U try to install neovim from deb - not from my Ubuntu repo?

**Comment by RomjanHossain** [comment]
> > I'm having the **19894 segment fault (core dump)** error too
> 
> Did U try to install neovim from deb - not from my Ubuntu repo?

i'm using Manjaro. neovim is downloaded through the official repo.
