### ISSUE TITLE
Why is tmux listed as an source in cmp config?

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#2687]
### Problem description

As far as I know, lunar-vim doesn't came with any source for cmp that provides tmux auto-completions, that's why I was surprised to see that there is one listed in the sources list of the default configuration.
Is this an error? A leftover?

### LunarVim version

aa4c993

### Neovim version (>= 0.7)

NVIM v0.7.0-dev+882-g9304ee387

### Operating system/version

macOS 12.4

### support info

I don't think is needed

**Comment by kylo252** [comment]
see https://github.com/LunarVim/LunarVim/pull/2542
