### ISSUE TITLE
Node dependency install fails on a fresh node install

### ISSUE THREAD

**Issue by stocks29** [LunarVim/LunarVim#2690]
### Problem description

With a fresh node install, the lunarvim installation with nodejs dependencies fails with this error:

```
[ERROR] Unable to install using [npm] without administrative privileges.
```

### LunarVim version

master-3475f76

### Neovim version (>= 0.7)

v0.7.0

### Operating system/version

macOS 12.2.1

### Steps to reproduce

1. Install a fresh version of node with asdf
2. Use the new version of node globally
3. Attempt to install lunarvim with nodejs dependencies

The node dependency install fails on this check because the `$manager_home` directory does not yet exist for npm because no npm modules have been installed yet:

```bash
  if [ ! -d "$manager_home" ] || [ ! -w "$manager_home" ]; then
    echo "[ERROR] Unable to install using [$pkg_manager] without administrative privileges."
    return 1
  fi
```

The workaround is simply installing an npm module first.

### support info

N/A

**Comment by kobzar** [comment]
In docs
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by Uzaaft** [comment]
This is more of an issue with node and npm than LunarVim (re kobzar's link).
So you can just go ahead and close the issue. @stocks29

**Comment by stocks29** [comment]
I think it begs the question: should the LunarVim install script be digging around in the guts of the package manager, or should it just verify that the package manager CLI is installed/available? The latter would be more resilient and would avoid this issue.

**Comment by kylo252** [comment]
> I think it begs the question: should the LunarVim install script be digging around in the guts of the package manager, or should it just verify that the package manager CLI is installed/available? The latter would be more resilient and would avoid this issue.

This is just a pre-emptive measure against people not having configured npm/yarn correctly, see: 
- https://github.com/LunarVim/LunarVim/pull/2091
- https://github.com/LunarVim/LunarVim/issues/2114
- https://github.com/LunarVim/LunarVim/issues/1468
- https://github.com/LunarVim/LunarVim/issues/739

Please try

```sh
npm i -g tree-sitter-cli
tree-sitter --help
```

if that works for you, but the installer doesn't then you have hit an edge-case where the npm/yarn is configured correctly but hasn't even been used once.


Please let me know if you still have issues.

**Comment by stocks29** [comment]
I already worked around the issue by installing a single npm module so npm created the folders which the install script checks. Easy workaround, but I'm sure others will hit this issue and be confused.

**Comment by kylo252** [comment]
> I already worked around the issue by installing a single npm module so npm created the folders which the install script checks. Easy workaround, but I'm sure others will hit this issue and be confused.

Could you please open a PR to attempt to create that folder and then error out if not possible?

**Comment by stocks29** [comment]
> Could you please open a PR to attempt to create that folder and then error out if not possible?

I wouldn't feel comfortable attempting to create the folder of the package manager as the current user since I wouldn't be confident that the permissions/structure would be accurate today and in future versions of the package manager. Would it make more sense to separate the validation conditions and give a more targeted error message? Perhaps something like this:

```sh
if [ ! -d "$manager_home" ]; then
  echo "[ERROR] Prefix directory ($manager_home) does not exist for [$pkg_manager]. Please install a global package using $pkg_manager to create it."
  return 1
elif [ ! -w "$manager_home" ]; then
  echo "[ERROR] Unable to install using [$pkg_manager] without administrative privileges."
  return 1
fi
```

**Comment by kylo252** [comment]
> Would it make more sense to separate the validation conditions and give a more targeted error message?

Yeah, that could work, but [`npm` basically suggests using `mkdir`](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) 
```bash
if [ ! -d "$manager_home" ]; then
  mkdir -p "$manager_home" || echo "[ERROR] Prefix directory ($manager_home) does not exist for [$pkg_manager]. Please check their perspective documentation on how to fix this."
  return 1
elif [ ! -w "$manager_home" ]; then
  echo "[ERROR] Unable to install using [$pkg_manager] without administrative privileges."
  return 1
fi
```
