### ISSUE TITLE
Prevent from removing `packer/start` content when config changed.

### ISSUE THREAD

**Issue by jukrb0x** [LunarVim/LunarVim#2695]
### Problem description

when set to other `colorscheme`, the lvim prompt to remove the start one. I suppose we could not switch back to default one as long as it is removed. check the screenshot attached.

imho we should prevent lvim from removing the `packer/start` content.

### LunarVim version

rolling-f778a38

### Neovim version (>= 0.7)

0.7.0

### Operating system/version

macOS 12.2.1

### support info

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/15688641/172199324-88cc67fa-14c6-4b18-9fab-112dcc576df9.png)

**Comment by kylo252** [comment]
> I think that is expected. Because `onedarker` is now seeing as a separated plugin, not the default one.

exactly.

This has been the case since #2359

**Comment by jukrb0x** [comment]
> I think that is expected. Because `onedarker` is now seeing as a separated plugin, not the default one. So if i want to install another colorscheme, i don't want `onedarker` is in my plugins folder anymore (save some space). Hehe!

that makes sense, if i want to install it back, what should i do? (cuz it looks like not a plugin in someone's repo)

**Comment by cpea2506** [comment]
> > I think that is expected. Because `onedarker` is now seeing as a separated plugin, not the default one. So if i want to install another colorscheme, i don't want `onedarker` is in my plugins folder anymore (save some space). Hehe!
> 
> that makes sense, if i want to install it back, what should i do? (cuz it looks like not a plugin in someone's repo)

```lua
lvim.colorscheme = "onedark"
```

That's it :D

It will display a prompt to ask if you want to install `onedarker` again.

**Comment by beatslikeahelix** [comment]
Instead of receiving 

> > > I think that is expected. Because `onedarker` is now seeing as a separated plugin, not the default one. So if i want to install another colorscheme, i don't want `onedarker` is in my plugins folder anymore (save some space). Hehe!
> > 
> > 
> > that makes sense, if i want to install it back, what should i do? (cuz it looks like not a plugin in someone's repo)
> 
> ```lua
> lvim.colorscheme = "onedarker"
> ```
> 
> That's it :D
> 
> It will display a prompt to ask if you want to install `onedarker` again.
> 
> Take a look at `onedarker` plugin options
> 
> https://github.com/LunarVim/LunarVim/blob/5d964c58848dde02bf04ce67bffe2398d2bbf1a1/lua/lvim/plugins.lua#L14-L23

Instead of receiving a prompt, I seem to get the follow error message:

`
"problems detected while loading plugins' configurations"
`

Perhaps there is some other problem with my config, but it's reasonably fresh, with only a few other user plugins.
Only get the error when attempting to set `lvim.colorscheme = "onedarker"`. Confusing!

**Comment by cpea2506** [comment]
> Instead of receiving
> 
> > > > I think that is expected. Because `onedarker` is now seeing as a separated plugin, not the default one. So if i want to install another colorscheme, i don't want `onedarker` is in my plugins folder anymore (save some space). Hehe!
> > > 
> > > 
> > > that makes sense, if i want to install it back, what should i do? (cuz it looks like not a plugin in someone's repo)
> > 
> > 
> > ```lua
> > lvim.colorscheme = "onedarker"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That's it :D
> > It will display a prompt to ask if you want to install `onedarker` again.
> > Take a look at `onedarker` plugin options
> > https://github.com/LunarVim/LunarVim/blob/5d964c58848dde02bf04ce67bffe2398d2bbf1a1/lua/lvim/plugins.lua#L14-L23
> 
> Instead of receiving a prompt, I seem to get the follow error message:
> 
> `"problems detected while loading plugins' configurations"`
> 
> Perhaps there is some other problem with my config, but it's reasonably fresh, with only a few other user plugins. Only get the error when attempting to set `lvim.colorscheme = "onedarker"`. Confusing!

Maybe there is something happens with `packer`. Now you need to exit `lvim` and then run `lvim +PackerSync`. That will fix it.
