### ISSUE TITLE
Create a one-step report command

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#2710]
### Feature Description

One of the things I like the most about VSCode is how easy is to report a bug.
You click a button, a simple popup appears, you describe your problem and it then opens a browser for you with one issue with all the required details already filled. 
From the user perspective this means no need to gather your Os version, installed plugins or other details.
From the maintainers perspective this means no details hunting, no omissions from the reporter and a standardised format.

I think lunarvim could provide such a feature in form of command or which key mapping. It will be a matter of gathering all the details, form a proper URL and then do an open to open the user browser with it.

### Describe the alternatives you have considered

Instead we can gather all the required information, put it on the user clipboard and then prompt then to open a link shown in a popup or something like that?

**Comment by kylo252** [comment]
I don't really think the overhead would be worth it, it is far simpler to just use `gh` which gives you access to the issue template in the terminal directly

![image](https://user-images.githubusercontent.com/59826753/184087359-47b41a2e-55e8-42d7-b2ea-4a5aeaaeb561.png)

**Comment by danielo515** [comment]
@kylo252 the part that is cumbersome and the reason why I'm suggesting this is gathering all the required information to fulfil the template. It requires executing several commands and copying them using different ways. Everytime you want to open an issue is a tedious process. My suggestion was to create a command that puts all the required information into the same place, so you can easily copy it in one go, rather than having to go back and forth between the template requirements and the console.
