### ISSUE TITLE
Error when enabling spell checker for multiple languages at the same time

### ISSUE THREAD

**Issue by renaldofreire** [LunarVim/LunarVim#2711]
### Problem description

I am trying to use spell check for EN and PT-BR. But I get an error message.

### LunarVim version

master-f1a672f

### Neovim version (>= 0.7)

v0.7.0

### Operating system/version

Arch Linux

### Steps to reproduce

1. In `config.lua` I add:
```
vim.opt.spell = true
vim.opt.spelllang = { "en", "pt-br" }
```
2. I aim to have spell check for English and Brazilian Portuguese
3. However, it doesn't work. I get the following error message:
`Warning: Cannot find word list "pt-br.utf-8.spl" or "pt-br.ascii.spl"`

### support info

```
LspInfo:

 Language client log: /home/renaldo/.cache/lvim/lsp.log              ⠀⠀⠀⠀
  ⠀⠀⠀⠀⠀⠀  Detected filetype:   alpha                                          ⠀⠀⠀⠀
  ⠀⠀⠀⠀⠀⠀                                                                      ⠀⠀⠀⠀
  ⠀⠀⠀⠀⠀⠀  0 client(s) attached to this buffer:                                ⠀⠀⠀⠀
  ⠀⠀⠀⠀⠀⠀                                                                      ⠀⠀⠀⠀
  ⠀⠀⠀⠀⠀⠀  Configured servers list: 
  ```
 ```
LvimInfo:

Error executing Lua callback: vim/shared.lua:0: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function <vim/shared.lua:0>
        vim/shared.lua: in function 'tbl_filter'
        ...enaldo/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info'
        ...enaldo/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'
        ...do/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:29: in function <...do/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:28>
```

### Screenshots

<a href="https://ibb.co/sRFmNfV"><img src="https://i.ibb.co/RbCvsFD/06-12-22-Sunday-22-56-36.png" alt="06-12-22-Sunday-22-56-36" border="0"></a>

**Comment by renaldofreire** [comment]
The same error also occurs. Is there a way to add the dictionary manually? I think it might have something to do with the fact that my system is in English.

**Comment by kobzar** [comment]
Did You resolve the issue?

**Comment by renaldofreire** [comment]
Hello @kobzar , I confess that I am having a little difficulty. There are variations of dictionaries (aspell, hunspell, nuspell). I know that there are specific versions for pt-BR. Can you tell which of these is the best option? I am checking this article https://wiki.archlinux.org/title/Language_checking

**Comment by kobzar** [comment]
Try to this one
https://github.com/mateusbraga/vim-spell-pt-br

**Comment by renaldofreire** [comment]
Thanks for the help @kobzar. 

When I checked the repository you sent me, I realized that it declared the language differently.

I just decided to follow the same pattern in `config.lua`.

I changed from:
vim.opt.spelllang = { "en", **"pt-br"** }

To
vim.opt.spelllang = { "en", **"pt_br"**}


And now it is working perfectly.
