### ISSUE TITLE
Turn off pop-up like notifications in the top right corner

### ISSUE THREAD

**Issue by av-maslov** [LunarVim/LunarVim#2713]
### Feature Description

Hi, 

Thanks for LunarVim!

I asked in Matrix channel but couldn't get answer.

How to turn off notifications like this:

![image](https://user-images.githubusercontent.com/71869629/173301442-86462322-2e21-483a-bf05-a7991df8882f.png)

**Comment by kobzar** [comment]
You have a lot of variants:
1. Fix the issue 
2. Configure notify plugin
https://github.com/rcarriga/nvim-notify
3. change lvim general option
lvim.log.level = "warn"

**Comment by kylo252** [comment]
> You have a lot of variants:
> 1. Fix the issue 
> 2. Configure notify plugin
> https://github.com/rcarriga/nvim-notify
> 3. change lvim general option
> lvim.log.level = "warn"
> 

you can also completely disable nvim-notify
