### ISSUE TITLE
Can`t copy text from neovim to windows 

### ISSUE THREAD

**Issue by MadScientisto23** [LunarVim/LunarVim#2716]
### Problem description

Hello,
I`m a new user and I want to use VSCode with embedded Neovim(I saw this [video](https://www.youtube.com/watch?v=g4dXZ0RQWdw)).  I`ve cloned the master branch and did a git checkout to the branch [4625145d02](https://github.com/LunarVim/LunarVim/tree/4625145d0278d4a039e55c433af9916d93e7846a) and renamed the folder to nvim, so I could use it on VSCode. Took me a while to find that i needed to do all those steps.

I`m on a WSL2 Archlinux(no visual interface installed just the terminal) distro on a windows 10 PC.

Now everything works except the copy and paste. I`ve tried to use xsel after putting this code on my init.vim.

let g:clipboard = {
\ 'name': 'xsel_override',
\ 'copy': {
\ '+': 'xsel --input --clipboard',
\ '': 'xsel --input --primary',
\ },
\ 'paste': {
\ '+': 'xsel --output --clipboard',
\ '': 'xsel --output --primary',
\ },
\ 'cache_enabled': 1,
\ 

Now when I press y after selecting the text on visual mode it shows this message:

clipboard: error invoking xsel: /usr/sbin/xsel: Can`t open display: (null) : Inappropriate ioctl for device

Sorry if this is not the place to ask, but I`m kinda desperate for a solution.

Thanks in advance.

### LunarVim version

4625145d02

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

Windows 10/ WSL Arch

### support info

:LspInfo
E492: Not an editor command: LspInfo
:LvimInfo
E492: Not an editor command: LvimInfo

### Screenshots

![image](https://user-images.githubusercontent.com/102111912/173367746-861cff94-3d01-479d-8753-78c4566f8997.png)

**Comment by kobzar** [comment]
Try Y (shift + y)
Also try to play with mouse settings in config. Disable it for test change it to “”

**Comment by MadScientisto23** [comment]
Solved my problem with the clipboard using this from the [FAQ](https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl), sry I didn`t see this FAQ earlier.
Decided to use win32yank instead of xsel.

Thanks for the patience!
