### ISSUE TITLE
Unable to recognise python package 

### ISSUE THREAD

**Issue by Manoj0Marmat** [LunarVim/LunarVim#2719]
### Problem description

I create market(package name) python package But whenever i import package lunar Vim showing Import "market" could not be resolved / import "market.model" could not be resolved errors even App running without any Error it's working but getting frustrating when saw this error again and again

### LunarVim version

1.1.3

### Neovim version (>= 0.7)

0.7.0

### Operating system/version

macOs 12.4 

### support info

Language client log: /Users/manojdilipmarmat/.cache/lvim/lsp.log
 Detected filetype:   python
 
 1 client(s) attached to this buffer: 
 
 Client: pyright (id: 3, pid: 9995, bufnr: [193, 162, 189, 227])
 	filetypes:       python
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             pyright-langserver --stdio
 
 2 active client(s) not attached to this buffer: 
 
 Client: pyright (id: 1, pid: 7636, bufnr: [11, 81, 159, 70])
 	filetypes:       python
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             pyright-langserver --stdio
 
 Client: html (id: 2, pid: 7666, bufnr: [21])
 	filetypes:       html
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             vscode-html-language-server --stdio
 
 Configured servers list: pyright, html

### Screenshots

![Screenshot 2022-06-14 at 5 20 58 PM](https://user-images.githubusercontent.com/85970385/173571712-87d708ab-d1de-4638-bdd5-1737a643f9a1.png)
![Screenshot 2022-06-14 at 5 27 14 PM](https://user-images.githubusercontent.com/85970385/173571725-2049fb00-db77-443b-ae7f-d58891a57ddd.png)

**Comment by kobzar** [comment]
First of them its no LunarVim error. 
From first screen its pyright error. You can google it and choose method to fix it. For example add root_dir in lsp config. 
you can create it by :Lspsertings

from second scren you have a python error because you dont have db.py module in your project. Does you __init__.py is correct?

**Comment by Manoj0Marmat** [comment]
this is my init file 

![Screenshot 2022-06-14 at 9 36 21 PM](https://user-images.githubusercontent.com/85970385/173624184-94f5629d-c820-4355-b80d-5283c5c4d4e6.png)

**Comment by kobzar** [comment]
You DONT HAVE module market.py
Thets why pyright show you error
https://github.com/microsoft/pyright/blob/main/docs/configuration.md
you can add your path in config, or try to add requirements.txt or just disable pyright to check imports
Thats why i propouse you to find the solution in gogle wich will best for you.

**Comment by Manoj0Marmat** [comment]
okay got it thank you so much

**Comment by kobzar** [comment]
try to use pylsp around of pyright

**Comment by Manoj0Marmat** [comment]
@kobzar Solves no issue in pyright it's just bcz one fucking space in my project directory damn
