### ISSUE TITLE
nvim-tree cannot be disabled

### ISSUE THREAD

**Issue by cladera** [LunarVim/LunarVim#2720]
### Problem description

NvimTree plugin cannot be disabled using `lvmi.builtin.nvimtree.active` flag.

### LunarVim version

HEAD-ed50b7d

### Neovim version (>= 0.7)

NVIM v0.8.0-dev+341-gbfc85eab1

### Operating system/version

macOS 12.3.1

### Steps to reproduce

# Reproduce steps
1. Open lvim's config.lua file
2. Add the following line: `lvim.builtin.nvimtree.active = false`
3. Resource or restart lvim
4. Try to open NvimTree

## Expected behaviour
It should not open since nvimtree plugin should've not been activated.

### support info

NA

**Comment by kylo252** [comment]
did you try `:PackerSync` after restarting lvim?

**Comment by cladera** [comment]
@kylo252 No I didn't. I can try it although I don't think it's going to make any difference. The flag is completely ignored in the setup. I already submit a PR with a fix proposal.

**Comment by abzcoding** [comment]
if you disable a plugin
the setup part doesn't get called at all
the only problem with our current code is that `<leader>e` should be moved to `setup`

**Comment by abzcoding** [comment]
fixed via #2750
