### ISSUE TITLE
npm & tree-sitter errors while intalling lvim fresh arch install.

### ISSUE THREAD

**Issue by JeremiahCheatham** [LunarVim/LunarVim#2727]
So using the command given to install lvim i came accross the error that i needed pnpm yarn or npm. It gave the commands to install each. Since it seemed pnpm was first and i don't know any better i tried to install that one. But this is not an archlinux package so it's not possible with the command given. I instead changed to npm and that installed.

Then running the command again it gives me an error about npm permisssions. So i figured that this needs to be run with sudo so i downloaded the install.sh and ran that from sudo. Now it gives me error about tree-sitter already being installed. So now i am worrying because i don't remember installing it. pacman -Qi tree-sitter tells me that it was required by neovim when i installed that. So The script is trying to install tree-sitter but neovim is already installed with it and there is a clash. I don't feel comfortable removing it if it's part of an archlinux package requirement and it's maintained via pacman. 

So pnpm can't be installed since it's not a package, there is some permission issues with the script needing root or i'm not sure if that's right. And it's complaining tree-sitter is installed already when it's already supposed to be installed. Not sure if tree-sitter was recently added to neovim.

Any help would be appreciated.

**Comment by kobzar** [comment]
Read documentation
https://www.lunarvim.org/01-installing.html#prerequisites

**Comment by JeremiahCheatham** [comment]
I read the documentation from here:
https://github.com/LunarVim/LunarVim
Is this the wrong place? Or is it wrong here?

Also the links there threw up some major red flags. It seems to me being an amateur that npm is not having a permission issue but the script is attempting to use it in a unintended way? And the links took me way down a rabbit hole. So can lunarvim no longer be installed to vanilla arch?  I had installed I many times before.

**Comment by kobzar** [comment]
Read documentation
https://www.lunarvim.org/01-installing.html#prerequisites

![image](https://user-images.githubusercontent.com/1912842/174424780-40fcf541-70e3-4472-8d83-95802b3129ad.png)

install npm

pacman -S nodejs npm

install neovim
pacman -S neovim

install lunarvim
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

be happy

**Comment by JeremiahCheatham** [comment]
tried this command.
``
sudo pacman -S git make pip npm node cargo nodejs neovim
``
but since pip and node are not packages my best guess is python-pip and nodejs maybe an update needs to be made there.


This works though.
``
sudo pacman -S git make python-pip npm nodejs cargo neovim
``
Or
``
sudo pacman -S -needed base-devel git python-pip npm nodejs cargo neovim
``



Could we get some clerification on this command here. It seems to be running with user permissions right.
``
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
``
````
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
[ERROR] Unable to install using [npm] without administrative privileges.
[ERROR]: Unable to find dependencies [pnpm][ERROR]: Unable to find dependencies [yarn][ERROR]: Unable to find dependencies [npm]Please install any one of the dependencies and re-run the installer. Try: 
sudo pacman -S pnpm
sudo pacman -S yarn
sudo pacman -S npm
````

**Comment by JeremiahCheatham** [comment]
If I were to try and break out of this and give it admin privileges then the command wont even work. But it seems that it should be user level since it's affecting my user account.
``wget https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh
``
and 
``
sudo bash ./install.sh
``
````
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
Installing node modules with npm..
npm ERR! code EEXIST
npm ERR! path /usr/bin/tree-sitter
npm ERR! EEXIST: file already exists
npm ERR! File exists: /usr/bin/tree-sitter
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-18T13_03_54_914Z-debug-0.log
````

And now we are back at the very beginning this is the original issue i had. The one from the very first post this is where i was at. All the other suggested stuff was already in place.

**Comment by kobzar** [comment]
as i see you dont read the docs
you dont need to use sudo
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by JeremiahCheatham** [comment]
Alax (kobzar) I really tried very hard to not post a reply asking you to not send me a response underlining something we have already talked about several times. I found it quite rude and unhelpful since i have already mentioned it several times why would you feel the need to underline it. So to quote someone who is not reading my issue and my replies. Please read my original issue above and also my responses following your suggestions that resulted in my original issue. As i already stated it seems you are attempting to do something with the script that is not meant to be done. and your using possibly a "HACK" to work around it. your attempting to install global package with local permissions. I have already stated this above. I said i didn't feel comfortable with this and it's not the way it's meant to work.

Again i had already replied to that message above that you for some unknown reason thought to send me underline. I wrote a reply and thought i should caution on the side that you were confused and maybe your feeling would be hurt if i pointed it out. But again you are doing the same. If this local script is installing it locally it doesn't need global permissions. If it needs global permissions that something is wrong. If i need to hack on the npm package to make it work something definitely is wrong.

And FYI I did all the steps needed and read all of this several times before ever posting the bug report. So i keeping my mouth shut the whole time you walked me threw all the steps i had already done. Just to make things smooth and hopefully help you track down the isssue.

You documentation on github is missing steps. Also your documentation on the site and in the script is incorrect as you can't install pnpm with packman, you should already have base-devel installed as well as  unzip. npm seems to be broken or your script out of the box so since pnpm is not even a package yarn is the only viable option. I see others complaining these same problems. If you are going to be condescending and blind to the issues, you will never fix the issues. 

Thanks

**Comment by JeremiahCheatham** [comment]
Sorry for my blunt tone. But to sum things up. Your very first reply was a condescending one, but i shrugged it off. Your second reply extremely condescending and i actually typed out an entire reply and deleted it hoping if i walked you though it you would see. 3 reply even more condescending. If your replying to the same thing so many times that your answers become like this then think about what is the issue all these people not getting what you see. Or maybe there's something wrong. If you just feel the need to be rude to people then it's really not acceptable is it?

**Comment by kobzarchekg** [comment]
Im am sorry. It was my mistake. 
You are still like writing - not reading.
So i will try compress information for you:

What are we have for test:

Working Arch x64 system. All nvim and lvim configuration is cleaned 
(i mean next dirs  .config/{nvim,lvim}, .cache/{nvim,lvim}, .local/share/{nvim,lvim})

the packages npm, nodejs  and neovim is installed
```
community/nodejs 18.3.0-1 [installed]
community/npm 8.5.5-1 [installed]
community/neovim 0.7.0-3 [installed]
```
So, its time to install LunarVim. And yes.  We are catch the error about we speak before.
Ok. We are going to link going next next and found resolve issue variants. Take a simple way 

https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
```
make few simple actions:
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
```
next we must add path,
```
nvim ~/.bash_profile
```
add next
``` 
export PATH=~/.npm-global/bin:$PATH
```
Thats all. Now reopen your terminal, change shell to bash and check mpm like
npm install -g jshint

Yuhhhuu!!! Its live!
So, run the install LunarVim again


```
--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
Installing node modules with npm..

added 34 packages, and audited 35 packages in 4s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 1 package, and audited 2 packages in 3s

found 0 vulnerabilities
All NodeJS dependencies are successfully installed
--------------------------------------------------------------------------------
Would you like to install LunarVim's Python dependencies?
[y]es or [n]o (default: no) : y
Verifying that pip is available..
```

and like a cherry on the cacke

![image](https://user-images.githubusercontent.com/56685094/175086965-ff3e6b61-6904-468a-87a1-479ab87409f6.png)

**Comment by JeremiahCheatham** [comment]
I really hope this is a Joke!

Thanks for giving me that perfect condescending reply kobzarchekg. Letting me know either you didn't read my post or you are just backing up the bad behaviour of others.

I have already got this up and running right after posting. I was only walking though the steps so that you guys could fix your problem. I also came across this the last time i installed too. Not sure if you have some kind of selective reading. But lets run though this again.

The documentation on github is missing you probably need something like this.
``sudo pacman -S --needed base-devel unzip git python-pip yarn nodejs cargo neovim``

Of if you want to force npm into the user space and fake that global with the hack work around.
As said in my reply up top this seems like a hack and bad practice. But if you insist then maybe add it to your pages. And not ignoring what people are saying and giving rude replies. Would be nice if just one of you read my messages.

````sudo pacman -S --needed base-devel unzip git python-pip npm nodejs cargo neovim
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
echo 'export PATH=~/.npm-global/bin:$PATH' >> ~/.bash_profile````

Don't forget to update both your website and also your github page. Having good documentation is almost as good as having good communication, you need to work on that.

Dont forget to remove pnpm since that's not a package and also from your script. And don't forget to include base-devel and unzip since those are also required.

I know you will not read or understand what i'm saying. But maybe one of the next 100 people asking the same question will find this useful.

Thanks 1 or both of you using similar names i don't care. None of your replies were helpful what so ever. Except in the future if i ever wish to go that route with npm. The first time i came across this i fixed it myself. And this time i also fixed it myself. But i was simply trying to clarify the issue and maybe get it fix. Seems that is not happening.

**Comment by kylo252** [comment]
I agree that @kobzar needs to tone it down, but I believe he did answer your main question

> Or if you want to force npm into the user space and fake that global with the hack work around.

I'm not sure I would call it a hack, I'm not sure why npm doesn't have a `user` scope, but you basically need to have set this variable https://docs.npmjs.com/cli/v8/using-npm/config#prefix

> The documentation on github is missing you probably need something like this.
> `sudo pacman -S --needed base-devel unzip git python-pip yarn nodejs cargo neovim`

that's a separate issue, and not really a realistic goal of this (basic) installer to handle suggestions for 10 different package managers 😞 

any enhancements to the docs are always welcomed!
