### ISSUE TITLE
how to always show bufferline?

### ISSUE THREAD

**Issue by jrafaaael** [LunarVim/LunarVim#2728]
### Discussed in https://github.com/LunarVim/LunarVim/discussions/2724

<div type='discussions-op-text'>

<sup>Originally posted by **jrafaaael** June 16, 2022</sup>
The buffers are shown when I open more than one buffer. How to show with one or more buffers opened?</div>

**Comment by kobzar** [comment]
By configuration it must be by deffault
```
'showtabline' 'stal'	number	(default 1)
			global
	The value of this option specifies when the line with tab page labels
	will be displayed:
		0: never
		1: only if there are at least two tab pages
		2: always
	This is both for the GUI and non-GUI implementation of the tab pages
	line.
	See |tab-page| for more information about tab pages.
```
and we have this in our config
lvim.opt.showtabline = 2

but it not working now

**Comment by kylo252** [comment]
see `:h bufferline-settings`

```lua
lvim.builtin.bufferline.options.always_show_bufferline = true
```

also make sure to check the lsp suggestions for some helpful tips about available settings 😃 

![image](https://user-images.githubusercontent.com/59826753/174428193-3b5a2fd3-d104-4f2d-bf50-03dcc21549c1.png)

**Comment by kylo252** [comment]
sorry, I didn't see that you mentioned you tried that option.

is this the same for all buffers? because alpha has a specific autocmd to hide a lot of elements
https://github.com/LunarVim/LunarVim/blob/5d964c58848dde02bf04ce67bffe2398d2bbf1a1/lua/lvim/core/alpha.lua#L52-L56

if you want to get rid of it, use this (you can add it to your `config.lua` if you'd like)

```lua
pcall(vim.api.nvim_clear_autocmds, { group = "_dashboard_settings" })
```

**Comment by kobzar** [comment]
> see `:h bufferline-settings`
> 
> ```lua
> lvim.builtin.bufferline.options.always_show_bufferline = true
> ```
> 
> also make sure to check the lsp suggestions for some helpful tips about available settings 😃
> 
> ![image](https://user-images.githubusercontent.com/59826753/174428193-3b5a2fd3-d104-4f2d-bf50-03dcc21549c1.png)

How i can add completion like you? Tabnine is active but my completion is different
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/1912842/174428888-e02ef1d5-113b-4e30-895a-e0c26566ea43.png">

**Comment by kylo252** [comment]
> How i can add completion like you? Tabnine is active but my completion is different 

I haven't made any custom changes to the cmp configuration, try running `:CmpStatus` to see if the lsp source is working.

**Comment by jrafaaael** [comment]
> ```lua
> lvim.builtin.bufferline.options.always_show_bufferline = true
> ```
this works for me. Originally, I tried `lvim.builtin.bufferline.always_show_bufferline = true`. My error
