### ISSUE TITLE
Instruction to implement treesitter-textobjects

### ISSUE THREAD

**Issue by SerhatTeker** [LunarVim/LunarVim#2730]
### Feature Description

How can we add [nvim-treesitter-textobjects]?

[nvim-treesitter-textobjects]: https://github.com/nvim-treesitter/nvim-treesitter-textobjects

### Describe the alternatives you have considered

Currently I'm adding it into *extra-plugins*.

```lua
-- config.lua

lvim.plugins = {
    {
        'nvim-treesitter/nvim-treesitter-textobjects',
        config = function()
            require('nvim-treesitter.configs').setup({
                textobjects = {
                    select = {
                        enable = true,
                        lookahead = true,
                        keymaps = {
                            ["af"] = "@function.outer",
                            ["if"] = "@function.inner",
                            ["ac"] = "@class.outer",
                            ["ic"] = "@class.inner",
                        },
                    },
                },
            })
        end,
    },
}
```

### Support information

However I see that we already implemented it in the core as `nvim-treesitter.configs`: [core textobjects].

Also we already merged #700 PR for this.

So, is there a current way to add this *treesitter textobject plugin* as a core plugin in our config as user? I mean as a `builtin` way: `lvim.builtin.treesitter.textobjects = ...`.
Or adding it as an *extra plugin* is the way to go?

[core textobjects]: https://github.com/LunarVim/LunarVim/blob/958030e728d3a853cc85051edf0326593c24148f/lua/lvim/core/treesitter.lua#L34-L44

[#700]: https://github.com/LunarVim/LunarVim/pull/700

**Comment by SerhatTeker** [comment]
OK, I found my issue and fixed it: I missed the import/`require`. For future references, below people can find how to add/enable `nvim-treesitter-textobjects`:

```lua
-- ~/.config/lvim/config.lua

-- Additional Plugins
lvim.plugins = {
    { 'nvim-treesitter/nvim-treesitter-textobjects' },
}

-- Treesitter
local ts = lvim.builtin.treesitter
ts.textobjects = {
    select = {
        enable = true,
        -- Automatically jump forward to textobj, similar to targets.vim
        lookahead = true,
        keymaps = {
            -- You can use the capture groups defined in textobjects.scm
            ["af"] = "@function.outer",
            ["if"] = "@function.inner",
            ["ac"] = "@class.outer",
            ["ic"] = "@class.inner",
        },
    },
    swap = {
      enable = false,
      -- swap_next = textobj_swap_keymaps,
    },
}
```

However, I believe it would be better to add doc about it, since it's one of the core module of the tree-sitter plugin and it's already mainly configured on lunarvim core, of the tree-sitter plugin. I can send PR for it.

**Comment by martisj** [comment]
@SerhatTeker how do you use this after setting it up like this? 
`vaf` I am guessing will select the "outer function", however I can't get it working.

**Comment by martisj** [comment]
Nvm 🤦‍♂️ I had to restart Lunar

**Comment by 00sapo** [comment]
> Is this outdated? I copied this approach but I think treesitter-textobjects is not working for me. If I understand correctly `vif` or `vic` should select function or class but does nothing for me.
> 
> I couldn't find any other guidelines for configuring it though...

Same issue for me, also tried to modify `lvim.core.treesitter` without success

**Comment by Eryx5502** [comment]
@00sapo, I couldn't make it work like this but found [this answer to another thread](https://github.com/LunarVim/LunarVim/issues/4298#issuecomment-1642973973) which does work for me.

**Comment by DjTuner13** [comment]
This helped so much thank you. I had no idea if could append things like this to the config.
