### ISSUE TITLE
LSP[sumneko_lua] Lua Language server refused to load this directory.

### ISSUE THREAD

**Issue by KalleChen** [LunarVim/LunarVim#2736]
### Problem description

<img width="1360" alt="Screen Shot 2022-06-20 at 4 15 32 PM" src="https://user-images.githubusercontent.com/48475056/174556650-2fe51312-b08a-40d6-8844-23eb3dfb7a72.png">

I got this error while opening config.lua

### LunarVim version

master-f1a672f

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

macOS 12.4 (macbook air m1)

### Affected language servers

sumnako_lua

### Steps to reproduce

1. Install LunarVim by stable install script
2. Run lvim
3. Select configuration
4. Got this error message

### Actual behavior

Got the lsp error message.

### Expected behavior

No error message.

### support info

<img width="1111" alt="Screen Shot 2022-06-20 at 4 20 37 PM" src="https://user-images.githubusercontent.com/48475056/174557628-9cc1273f-6c82-437f-962c-8c75f3ac93ad.png">
<img width="945" alt="Screen Shot 2022-06-20 at 4 21 12 PM" src="https://user-images.githubusercontent.com/48475056/174557753-0ed1715e-5874-4ff7-9e2a-815344274b0c.png">

### logs

```console
[START][2022-06-20 16:06:37] LSP logging initiated
[START][2022-06-20 16:06:50] LSP logging initiated
[ERROR][2022-06-20 16:07:02] ...lsp/handlers.lua:454	"Your workspace is set to `/Users/kallechen`. Lua language server refused to load this directory. Please check your configuration.[learn more here](https://github.com/sumneko/lua-language-server/wiki/Why-scanning-home-folder)"
[WARN][2022-06-20 16:07:06] .../lua/vim/lsp.lua:812	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-06-20 16:07:21] LSP logging initiated
[START][2022-06-20 16:08:05] LSP logging initiated
[ERROR][2022-06-20 16:08:07] ...lsp/handlers.lua:454	"Your workspace is set to `/Users/kallechen`. Lua language server refused to load this directory. Please check your configuration.[learn more here](https://github.com/sumneko/lua-language-server/wiki/Why-scanning-home-folder)"
[WARN][2022-06-20 16:08:11] .../lua/vim/lsp.lua:812	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2022-06-20 16:08:20] .../vim/lsp/rpc.lua:420	"rpc"	"lua-language-server"	"stderr"	"NMD, WSM `endLine > #rows` ?\nstack traceback:\n\tscript/text-merger.lua:72: in upvalue 'mergeRows'\n\tscript/text-merger.lua:106: in function 'text-merger'\n\tscript/provider/provider.lua:284: in function <script/provider/provider.lua:269>\n\t[C]: in function 'xpcall'\n\tscript/proto/proto.lua:184: in function <script/proto/proto.lua:159>\n"
[WARN][2022-06-20 16:08:26] ...lsp/handlers.lua:109	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2022-06-20 16:08:34] LSP logging initiated
[WARN][2022-06-20 16:08:35] ...lsp/handlers.lua:109	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2022-06-20 16:08:40] ...lsp/handlers.lua:454	"Notification handler 'textDocument/didChange' failed with message: Cannot read property 'offsetAt' of undefined"
[START][2022-06-20 16:12:39] LSP logging initiated
[WARN][2022-06-20 16:12:40] ...lsp/handlers.lua:109	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2022-06-20 16:12:47] ...lsp/handlers.lua:454	"Your workspace is set to `/Users/kallechen`. Lua language server refused to load this directory. Please check your configuration.[learn more here](https://github.com/sumneko/lua-language-server/wiki/Why-scanning-home-folder)"
[WARN][2022-06-20 16:12:51] .../lua/vim/lsp.lua:812	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-06-20 16:16:04] LSP logging initiated
[WARN][2022-06-20 16:16:04] ...lsp/handlers.lua:109	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2022-06-20 16:16:05] ...lsp/handlers.lua:454	"Your workspace is set to `/Users/kallechen`. Lua language server refused to load this directory. Please check your configuration.[learn more here](https://github.com/sumneko/lua-language-server/wiki/Why-scanning-home-folder)"
[WARN][2022-06-20 16:16:07] .../lua/vim/lsp.lua:812	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-06-20 16:17:17] LSP logging initiated
[WARN][2022-06-20 16:17:18] ...lsp/handlers.lua:109	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2022-06-20 16:20:28] ...lsp/handlers.lua:454	"Your workspace is set to `/Users/kallechen`. Lua language server refused to load this directory. Please check your configuration.[learn more here](https://github.com/sumneko/lua-language-server/wiki/Why-scanning-home-folder)"
[WARN][2022-06-20 16:20:31] .../lua/vim/lsp.lua:812	"server_request: no handler found for"	"workspace/diagnostic/refresh"
```

**Comment by evan-leigh** [comment]
I'm having the same issue after a fresh install, although the issue doesn't happen when in a git repository. Guessing it has to do with the language server itself and not LunarVim

**Comment by kylo252** [comment]
The lua language server uses these files as root pattern https://github.com/neovim/nvim-lspconfig/blob/325a5daeff870b277bd90fabe46fa92d87fdffb7/lua/lspconfig/server_configurations/sumneko_lua.lua#L3-L8 
- check that they don't exist in your home directory
- create at least one of them in your current project folder (or make it a git repo)

check https://github.com/neovim/nvim-lspconfig#troubleshooting for more info

**Comment by khuedoan** [comment]
Thanks, that fixed it for me! (https://github.com/khuedoan/dotfiles/commit/37aebb82ef19defe341ffb748bf21660ba56bc86)

My `$HOME` is a git repo for my dotfiles, so [it tried fall back to the nearest git repo](https://github.com/neovim/nvim-lspconfig/blob/325a5daeff870b277bd90fabe46fa92d87fdffb7/lua/lspconfig/server_configurations/sumneko_lua.lua#L14).

**Comment by Vermoot** [comment]
I'm getting the same message, and it seems my issue is the same, since my whole home folder is also a git repo for the same reasons.
I don't quite get your solution though?

**Comment by khuedoan** [comment]
You can add one of the [root files](https://github.com/neovim/nvim-lspconfig/blob/325a5daeff870b277bd90fabe46fa92d87fdffb7/lua/lspconfig/server_configurations/sumneko_lua.lua#L3-L8) to your `~/.config/nvim` directory, in my case I use Stylua to format my code so it's `.config/nvim/.stylua.toml`). An empty file will also work.

**Comment by Vermoot** [comment]
Alright, that worked, thanks!
Though I'd prefer not to have empty, undescript files in my config folder. At least I'm good now!

**Comment by KalleChen** [comment]
Thanks @kylo252 it works for me.

**Comment by tcstory** [comment]
it seems  i can ignore this warming. because LspInfo show me the root directory is correct.

**Comment by alexgenaud** [comment]
In my case, .git within my home directory caused this issue. Removing the .git directory fixes the issue for me.

**Comment by devhaocui** [comment]
> You can add one of the [root files](https://github.com/neovim/nvim-lspconfig/blob/325a5daeff870b277bd90fabe46fa92d87fdffb7/lua/lspconfig/server_configurations/sumneko_lua.lua#L3-L8) to your `~/.config/nvim` directory, in my case I use Stylua to format my code so it's `.config/nvim/.stylua.toml`. An empty file will also work.

This worked for me. If you are using neovim and lazyvim. In every folder that you store all your .lua files make an extra file named exactly what the list of root files u can name. I named mine stylua.toml and it fixed the error for me and I can now use the sumneko_lua lsp server in peace. Thank you Jesus.
![Screenshot 2024-05-26 at 11 24 15 PM](https://github.com/LunarVim/LunarVim/assets/142655679/5e3d9f7f-ef12-4ee6-96db-40f9522b4aac)
