### ISSUE TITLE
Functionality broken after LvimUpdate

### ISSUE THREAD

**Issue by Chris-Leeworthy** [LunarVim/LunarVim#2737]
### Problem description

After running `LvimUpdate` I started getting warnings when lvim started up.  When I tried to collect some information to help diagnose the problem I found more errors like the `LvimInfo` error shown below.

Start lvim
`:LvimInfo`

Instead of getting information I get the following errors
```Error executing Lua callback: vim/shared.lua:0: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function <vim/shared.lua:0>
        vim/shared.lua: in function 'tbl_filter'
        ...leewoc/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info'
        ...leewoc/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'
        ...oc/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:29: in function <...oc/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:28>```

The attached screen capture shows the startup warning I get.

### LunarVim version

master-f1a672f

### Neovim version (>= 0.7)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

macOS 12.4

### Steps to reproduce

_No response_

### support info

```
:LspInfo
 Language client log: /Users/leewoc/.cache/lvim/lsp.log
 Detected filetype:   alpha

  0 client(s) attached to this buffer:

  Configured servers list:
```
```
:LvimInfo
Error executing Lua callback: vim/shared.lua:0: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function <vim/shared.lua:0>
        vim/shared.lua: in function 'tbl_filter'
        ...leewoc/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info'
        ...leewoc/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'
        ...oc/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:29: in function <...oc/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:28>
```

### Screenshots

![Screenshot 2022-06-20 at 17 00 08](https://user-images.githubusercontent.com/13499355/174641152-db3b0312-a27a-4297-be96-10342d5b097a.png)

**Comment by rebuilt** [comment]
Some configuration options have changed between older and newer versions of Lunarvim.  From the image you posted, it looks like like 66 of your config.lua is a problem.  Comment it out and see what happens.  Also try running a blank config.lua file.  If Lunarvim starts up without errors, you'll know you just have to update your config.lua.  If, after running a blank config file, you still get errors, back up your original config.lua to a different folder and reinstall Lunarvim.  https://www.lunarvim.org/01-installing.html#uninstall

**Comment by Chris-Leeworthy** [comment]
Hi, 
I didn't have any customisations so I thought the best approach would be to completely remove lunarvim and do a clean install from scratch.  

The problems still happen and it's using the config.lua that came with the install.

**Comment by Chris-Leeworthy** [comment]
Here's some more information.
 `:LvimInfo` only crashes if you don't have a file open in a buffer.

**Comment by Chris-Leeworthy** [comment]
Found a config problem too.
