### ISSUE TITLE
Terminal directory different from buffer directory

### ISSUE THREAD

**Issue by nachiketkanore** [LunarVim/LunarVim#2739]
### Problem description

![Monday 20 June 2022 10:55:46 PM IST](https://user-images.githubusercontent.com/44920607/174653366-b815822d-f7b7-475e-b07c-ef914c5e7571.png)
![Monday 20 June 2022 10:55:29 PM IST](https://user-images.githubusercontent.com/44920607/174653370-dbe49362-95a0-4679-b7cb-cfc39c6b78dd.png)

- LunarVim buffer directory is different from the terminal directory
- I wanted to fire command in the terminal consisting of the current directory, to run a script, but it runs it on some different(parent path in this case) path

### LunarVim version

master-f1a672f

### Neovim version (>= 0.7)

NVIM v0.8.0-dev

### Operating system/version

Ubuntu 20.04.4 LTS x86_64

### Steps to reproduce

1. New LunarVim setup
2. create .cpp file
3. run `!pwd` in command 

### support info

 :LspInfo
 Language client log: /home/nachiket/.cache/lvim/lsp.log
 Detected filetype:   cpp
 
 1 client(s) attached to this buffer: 
 
 Client: clangd (id: 1, pid: 2205206, bufnr: [1])
 	filetypes:       c, cpp, objc, objcpp, cuda
 	autostart:       true
 	root directory:  /home/nachiket/L
 	cmd:             clangd
 
 Configured servers list: clangd

:LvimInfo
    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 

Buffer info
* filetype:                cpp
* bufnr:                   1
* treesitter status:       inactive

Active client(s)
* name:                      clangd
* id:                        1
* supported filetype(s):     [c, cpp, objc, objcpp, cuda]
* attached buffers:          1
* root_dir pattern:          1
* capabilities:              definitionProvider       | selectionRangeProvider          | declarationProvider
                             callHierarchyProvider    | referencesProvider              | documentHighlightProvider
                             memoryUsageProvider      | documentRangeFormattingProvider | documentFormattingProvider
                             hoverProvider            | astProvider                     | typeHierarchyProvider
                             clangdInlayHintsProvider | implementationProvider          | documentSymbolProvider
                             workspaceSymbolProvider  | typeDefinitionProvider

Automatic LSP info
* Skipped servers: [ccls, sourcekit]

Formatters info
* Active: 
* Supported: [astyle, clang_format, uncrustify]

Linters info
* Active: 
* Supported: [cppcheck, gccdiag]

Code actions info
* Active:

**Comment by rebuilt** [comment]
LunarVim uses project.nvim to set your working directory.   If you want to disable automatic switching of the working directory to the project root, add this to your config:

```
lvim.builtin.project.manual_mode = true

```

That will leave your working directory intact.  The working directory will be the one from which you launched lunarvim.  

Then, if you want project.nvim to detect your project root you can do so with the `:ProjectRoot` command.

To disable project.nvim altogether:

```
lvim.builtin.project.active = false
```

If you want to set the cwd programmatically yourself, you can read the help docs with `:help nvim_set_current_dir` to do so with lua.  (vim.api.nvim_set_current_dir)

Or you can follow the instructions here to set the directory with vimscript

```
https://vim.fandom.com/wiki/Set_working_directory_to_the_current_file
```
