### ISSUE TITLE
Support Range Formatting

### ISSUE THREAD

**Issue by luong-komorebi** [LunarVim/LunarVim#2741]
### Feature Description

vim.lsp.buf.range_formatting is not currently supported with Lunarvim. However, in some libraries like null-ls and even on upstream lsp, vim.lsp.buf.range_formatting() is supprorted

It would be nice if we can support visual selection of a block of code, then call format range and it will maps to some function like the current format helper at https://github.com/LunarVim/LunarVim/blob/958030e728d3a853cc85051edf0326593c24148f/lua/lvim/lsp/utils.lua#L152

### Describe the alternatives you have considered

Self mapping to: "<cmd>lua vim.lsp.buf.range_formatting()<CR>", which would be okay, but would not cover a lot of meaningful checks like what LunarVim is doing

**Comment by kylo252** [comment]
please try this to use `gq` for range-formatting

```lua
lvim.lsp.on_attach_callback = function(_, bufnr)
  local function buf_set_option(...)
    vim.api.nvim_buf_set_option(bufnr, ...)
  end

  -- use gq for formatting
  buf_set_option("formatexpr", "v:lua.vim.lsp.formatexpr(#{timeout_ms:250})")
end
```

**Comment by LinuxIsCool** [comment]
I don't understand what is happening in the above code, but I pasted into config.lua and `gq` is still not working for range formatting. I'm unable to find any supported formatter for python that supports range formatting. Actually yapf and autopep8 say that they support range formatting, but they fail to format long lines. 

I'm stuck on this and `gq` is very critical to my vim workflow.

**Comment by nettrino** [comment]
What about simple column-width formatting? Seems like we would need a formatter just to wrap on 80 columns for instance. This used to be the default behavior in vim so its confusing coming from vim to lunarvim. Is there a way to configure this equivalent behavior?

**Comment by kylo252** [comment]
> What about simple column-width formatting? Seems like we would need a formatter just to wrap on 80 columns for instance. This used to be the default behavior in vim so its confusing coming from vim to lunarvim. Is there a way to configure this equivalent behavior?

@nettrino see [`:h 'textwidth'`](https://neovim.io/doc/user/options.html#'textwidth')

**Comment by nettrino** [comment]
Thank you for the reply @kylo252. I had set `textwidth` appropriately but was confused with `gq` deviating from vim. Turns out `gw` does what I expected in lunarvim as discussed in https://github.com/LunarVim/LunarVim/issues/3553
