### ISSUE TITLE
Is rust and cargo a required dependency?

### ISSUE THREAD

**Issue by saimonmoore** [LunarVim/LunarVim#2746]
### Problem description

When installing lunarvim via 
```
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
```

it requires that rust & cargo be preinstalled.

I do not use rust and it takes a while to install these deps. If they're not actually required, I'd rather not install them.

If they are optional, how do I get the installer to not complain about them?

If they are required, I'd be interested in knowing why they are required.

### LunarVim version

n/a

### Neovim version (>= 0.7)

n/a

### Operating system/version

macOs 11.5

### Steps to reproduce

n/a

### support info

n/a

**Comment by Chris-Leeworthy** [comment]
If I remember rightly Rust is used to build the fuzzy find plugin `fd-find` (maybe some others too).  So if you don't install that dependency lunarvim will install, but some parts of it may not work as expected.

**Comment by saimonmoore** [comment]
If I remember correctly, the installer exits if it doesn't find cargo & rust by default. This is why I'm asking wether there are any opts that can be passed to the installer.
