### ISSUE TITLE
Problem getting suggestions from copilot-cmp

### ISSUE THREAD

**Issue by Zundrium** [LunarVim/LunarVim#2747]
Forgive me for not understanding the basics.

What I did while setting up was:
1 ) Install LunarVim with the bash script
2 ) Add the plugins as provided in https://github.com/LunarVim/lunarvim.org/blob/master/docs/plugins/02-extra-plugins.md#copilotlua-and-copilot-cmp
3 ) Authenticate with `"github/copilot.vim"` and `:Copilot setup`

Now I can create solutions by running `:Copilot` manually, but I don't see any suggestions popping up in a TypeScript file.
Am I missing a step that I need to do with [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)?

**Comment by rebuilt** [comment]
Where did you place the code to add copilot as a source?  

```
lvim.builtin.cmp.formatting.source_names["copilot"] = "(Copilot)"
table.insert(lvim.builtin.cmp.sources, 1, { name = "copilot" })
```

**Comment by Zundrium** [comment]
Hey @rebuilt thanks for taking a look, 
those lines are part of the example in https://github.com/LunarVim/lunarvim.org/blob/master/docs/plugins/02-extra-plugins.md#copilotlua-and-copilot-cmp in step 2, so yes those are added to my config.lua. 

Might there be another reason as to why these suggestions do not pop-up automatically?

**Comment by rebuilt** [comment]
First make sure you install the original github copilot plugin
```
 {	"github/copilot.vim", },
```
Follow the steps on the Readme to authenticate.   Make sure you're authenticated with the command 
`:Copilot status`
You may have to go into your github settings to allow access.  
View the other available commands with `:help copilot`

Then install the zbirenbaum plugins.
Run `:PackerStatus` and make sure both zbirenbaum/copilot and zbirenbaum/copilot-cmp are loaded and running.   You can use `/` to search that buffer.  

``` 
 • copilot-cmp
 • copilot.lua
```

**Comment by vonPB** [comment]
I just tried the instructions from the example and it works just fine :)
![image](https://user-images.githubusercontent.com/65032978/177014168-2e4cb69f-250b-4b47-9403-e645ef457898.png)

**Comment by Zundrium** [comment]
Thanks @rebuilt for checking this and thank you @vonPB for trying out the steps, I'll use this approach everytime I'm having issues with plugins :) 
I couldn't see the plugins in `:PackerStatus`, I updated the plugins again and for whatever reason it started working.. I'm pretty sure I installed the plugins before..

**Comment by edoardo-bluframe** [comment]
Hey @rebuilt!

I am using `copilot.lua` and it works **great**

When it comes to `copilot-cmp` though I cannot get suggestions!

I tried both the configuration from LunarVim

 https://www.lunarvim.org/docs/plugins/extra-plugins#copilotlua-and-copilot-cmp

And also I tried replacing that with the one suggested by `copilot-cmp`

```
{ "zbirenbaum/copilot.lua",
  cmd = "Copilot",
  event = "VimEnter",
  config = function()
    vim.defer_fn(function()
      require("copilot").setup {
        suggestion = { enabled = false },
        panel = { enabled = false },
      } 
    end, 100)
  end,
},
{ "zbirenbaum/copilot-cmp",
  after = { "copilot.lua" },
  config = function ()
    require("copilot_cmp").setup()
  end
},
```

They are **a little** different - I cannot get suggestions with neither!

Also I tried both entering this in my `config.lua`

```
lvim.builtin.cmp.formatting.source_names["copilot"] = "(Copilot)"
table.insert(lvim.builtin.cmp.sources, 1, { name = "copilot" })
```

And **not** entering as I noticed that in the latest version of the core plugins those are already configured

Either way it doesn't work!

Again - Copilot works **100%** both in Panel and Suggestion modes

When I tried to get suggestions from `copilot-cmp` as a source it just doesn't click in!

Am I doing something wrong?

**Comment by rebuilt** [comment]
Make sure you've already authenticated copilot
```
:Copilot auth
```

Print out the sources table to make sure copilot is in that list.

```
:lua print(vim.inspect(lvim.builtin.cmp.sources))

```

Bring up the list of plugins. `<Space>pS`.    Search that buffer with `/`.  Make sure both the cmp-copilot and copilot plugins are loaded.  

Make sure you're not overriding tab completion with your own tab logic.  

Run 
```
:Copilot status
```
to make sure it reports things are working correctly. 


If that's still not working check the lsp logs to make sure there are no errors there.  `<Space>Lll`

**Comment by matheusgadelha** [comment]
Same for me. No suggestions from copilot in cmp.

**Comment by jkawnkwh85** [comment]
> Same for me. No suggestions from copilot in cmp.
I followed the instructions in the doc. Then I run
```
:Copilot suggestion
```
Everything seems working.

**Comment by jkawnkwh85** [comment]
> lvim.builtin.cmp.formatting.source_names["copilot"] = "(Copilot)"
> table.insert(lvim.builtin.cmp.sources, 1, { name = "copilot" })

Have you managed to solve the issue?

**Comment by jkawnkwh85** [comment]
@edoardo-bluframe have you managed to solve the issue?

**Comment by jkawnkwh85** [comment]
I had a similar issue following the instructions.

I slightly changed the config to
```
{ "zbirenbaum/copilot-cmp",
      after = { "copilot.lua", "nvim-cmp" },
      config = function()
      require("copilot_cmp").setup()
},

Then copilot appears in cmp successfully.

Afterward, the setup works even I restore to the config provided on the doc.

**Comment by edoardo-bluframe** [comment]
@rebuilt **Super** appreciated! :blush: 

@jkawnkwh85 I **did** manage to get it work after about 2 hours. Though I don't remember **exactly** what the problem was - I do remember what kind of problem it was

I had to disable a setting that was interfering with the suggestions - and actually I found that disabling that setting **was** mentioned in the docs - I had overlooked it!

Does that help? :smile:

**Comment by michaelessiet** [comment]
> @rebuilt **Super** appreciated! 😊
> 
> @jkawnkwh85 I **did** manage to get it work after about 2 hours. Though I don't remember **exactly** what the problem was - I do remember what kind of problem it was
> 
> I had to disable a setting that was interfering with the suggestions - and actually I found that disabling that setting **was** mentioned in the docs - I had overlooked it!
> 
> Does that help? 😄

No it doesn't. What did you disable?
