### ISSUE TITLE
Remap using nvim api throw error

### ISSUE THREAD

**Issue by bigzhu** [LunarVim/LunarVim#2752]
### Problem description

when remove which_key plugin, Remap using nvim api code throw error:

<img width="966" alt="Screen Shot 2022-06-23 at 10 01 36 PM" src="https://user-images.githubusercontent.com/489815/175318061-0c614dc3-d33a-4db6-b2af-70b73213bf9e.png">

### LunarVim version

master-f1a672f

### Neovim version (>= 0.7)

NVIM v0.8.0-dev+457-g6d52a29c3

### Operating system/version

macOS 11.6.7

### support info

```console
# LspInfo

lua-language-server```

### Screenshots

_No response_

**Comment by kylo252** [comment]
Please share the content of this command
```lua
:lua =lvim.lsp.buffer_mappings
```

**Comment by bigzhu** [comment]
```
{
  insert_mode = {},
  normal_mode = {
    K = { <function 1>, "Show hover" },
    gD = { <function 2>, "Goto declaration" },
    gI = { <function 3>, "Goto Implementation" },
    gd = { <function 4>, "Goto Definition" },
    gl = { <function 5>, "Show line diagnostics" },
    gp = { <function 6>, "Peek definition" },
    gr = { <function 7>, "Goto references" },
    gs = { <function 8>, "show signature help" }
  },
  visual_mode = {}
}
```
