### ISSUE TITLE
E5112 verify_plugins.lua does not exist with a fresh install

### ISSUE THREAD

**Issue by BlameTroi** [LunarVim/LunarVim#2753]
### Problem description

After a successful uninstall of lunarvim I tried to reinstall using the install.sh via curl into bash. This was done from my home directory. I've done this a few times without issues, but it looks like the commit to verify-plugins for #2751 broke something. I get the following:

Verifying core plugins
Error detected while processing command line:
E5112: Error while creating lua chunk: cannot open ./utils/ci/verify_plugins.lua: No such file or directory

That file does exist at ~/.local/share/lunarvim/lvim/utils/ci/verify_plugins.lua, but I can not tell from the error message what the directory "." is as this executes. I am very new to lua and don't know how to start debugging this so I just have to throw up a bug report without a fix, sorry.

### LunarVim version

can not obtain, but downloaded 1600hrs Eastern 2022/06/23

### Neovim version (>= 0.7)

NVIM V0.7.0 Release

### Operating system/version

Linux * 5.18.5-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Jun 16 12:28:47 UTC 2022 x86_64 GNU/Linux 

### Steps to reproduce

bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

installed all dependencies at prompts

### support info

master-4a7bb09

**Comment by JackRhodes** [comment]
I also encountered this issue, I was able to workaround by using the commit before #8989984

`bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/ecd344128734fe6b0772505e22922dea28338e26/utils/installer/install.sh)`

**Comment by muhajirdev** [comment]
I still get this error, did you get this as well?

```
Error detected while processing /Users/muhajir/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: Vim:E6100: "log" is not a valid stdpath
stack traceback:
        [C]: in function 'stdpath'
        ...ovim/HEAD-c00a3f4/share/nvim/runtime/lua/vim/lsp/log.lua:28: in main chunk
        [C]: in function 'require'
        ...HEAD-c00a3f4/share/nvim/runtime/lua/vim/lsp/handlers.lua:1: in main chunk
        [C]: in function 'require'
        ...r/neovim/HEAD-c00a3f4/share/nvim/runtime/lua/vim/lsp.lua:1: in main chunk
        [C]: in function 'require'
        vim/_init_packages.lua: in function '__index'
        ...r/.local/share/lunarvim/lvim/lua/lvim/core/which-key.lua:172: in function 'config'
        ...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:24: in function 'config'
        ...ajir/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:21: in function 'init'
        ...uhajir/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:110: in function 'init'
        /Users/muhajir/.local/share/lunarvim/lvim/init.lua:8: in main chunk
Error detected while processing /Users/muhajir/.local/share/lunarvim/site/pack/packer/start/nvim-lspconfig/plugin/lspconfig.vim:
line   16:
E5108: Error executing lua vim/_init_packages.lua:0: loop or previous error loading module 'vim.lsp'
stack traceback:
        [C]: in function 'require'
        vim/_init_packages.lua: in function '__index'
        .../pack/packer/start/nvim-lspconfig/lua/lspconfig/util.lua:4: in main chunk
        [C]: in function 'require'
        ...ck/packer/start/nvim-lspconfig/lua/lspconfig/configs.lua:1: in main chunk
        [C]: in function 'require'
        .../site/pack/packer/start/nvim-lspconfig/lua/lspconfig.lua:1: in main chunk
        [C]: in function 'require'
        [string ":lua"]:9: in main chunk
```

**Comment by kylo252** [comment]
This is weird.. I wonder how passed the CI then
