### ISSUE TITLE
Manually installed server doesn't start automatically when configured with LSP manager

### ISSUE THREAD

**Issue by dgmora** [LunarVim/LunarVim#2770]
### Problem description

This could be just a matter of improving the documentation or a bug.

I want to manually install and configure a server (solargraph), but the server does not get started when configuring it following the instructions in https://www.lunarvim.org/languages/#server-setup

`require("lspconfig")["solargraph"].setup(opts)` works correctly and the server gets started, however
`require("lvim.lsp.manager").setup("solargraph", opts)` doesn't.

### LunarVim version

master-f1a672f

### Neovim version (>= 0.7)

 v0.7.0

### Operating system/version

macOs 12.3

### Affected language servers

solargarph

### Steps to reproduce

Not sure how to reproduce using `minimal_lsp`, I get an error because `lvim.`:
`attempt to index global 'lvim'`

This is the configuration I'm trying to add (notice the invalid `cmd`, which should trigger some error/log because it's invalid):
```lua
vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "sorbet", "solargraph" })
lvim.lsp.automatic_servers_installation = false
-- https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/solargraph.lua
local opts = {
  cmd = { 'justfail', 'solargraph', 'stdio' },
  --cmd = { solargraph', 'stdio' },
  settings = {
    solargraph = {
      diagnostics = true,
    },
    init_options = { formatting = true },
  },
  init_options = { formatting = true },
  filetypes = { 'ruby' },
  --  root_dir = util.root_pattern('Gemfile', '.git')
}

--require("lspconfig")["solargraph"].setup(opts)
require("lvim.lsp.manager").setup("solargraph", opts)
```

Nothing happens. No error, nor the server starts.
If I replace `require("lvim.lsp.manager").setup("solargraph", opts)` with `require("lspconfig")["solargraph"].setup(default_config)` things are normal

### Actual behavior

The server does not start when it is installed manually

### Expected behavior

Even if the server configuration is overwritten and the server is installed manually, I would expect that the server gets started automatically.

The docs don't mention this, so I assumed this is how it is supposed to work. 

### support info

`:LspInfo`
```console

                                Language client log: /Users/david/.cache/lvim/lsp.log
                                Detected filetype:   ruby

                                0 client(s) attached to this buffer:

                                Configured servers list:

```

`:LvimInfo`
```console
        __                          _    ___         
       / /   __  ______  ____ _____| |  / (_)___ ___ 
      / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
     / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
    /_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 
    
    
    Buffer info
    * filetype:                ruby
    * bufnr:                   1
    * treesitter status:       active
    
    Active client(s)
    
    Automatic LSP info
    * Skipped servers: [sorbet, sorbet, solargraph]
    
    Formatters info
    * Active: 
    * Supported: [rubocop, rufo, standardrb]
    
    Linters info
    * Active: 
    * Supported: [rubocop, semgrep, standardrb]
    
    Code actions info
    * Active: 
```

### logs

lsp log only shows
```console
[START][2022-06-28 09:43:59] LSP logging initiated
```
 when _exiting_ lvim. (`:x`)

**Comment by kylo252** [comment]
- do you have `solargraph` installed and available on path?
- use `lvim.log.level = "debug"` (requires a restart) and try again

this already works for me with `clangd` without any issues, see https://github.com/kylo252/lvim/blob/d950b1fc55db35d26baf8997dd100562f9ff9924/after/ftplugin/c.lua#L32

this is what LSP manager is doing in a nutshell

```lua
local common_opts = require'lvim.lsp'.get_common_opts()
local opts = vim.tbl_deep_extend("force", common_opts, my_opts or {}) -- see `resolve_config()`
require("lspconfig")["solargraph"].setup(opts)
```

**Comment by rebuilt** [comment]
Did you already `gem install solargraph` ?

**Comment by dgmora** [comment]
> * do you have `solargraph` installed and available on path?
> * use `lvim.log.level = "debug"` (requires a restart) and try again
> 
> this already works for me with `clangd` without any issues, see https://github.com/kylo252/lvim/blob/d950b1fc55db35d26baf8997dd100562f9ff9924/after/ftplugin/c.lua#L32
> 
> this is what LSP manager is doing in a nutshell
> 
> ```lua
> local common_opts = require'lvim.lsp'.get_common_opts()
> local opts = vim.tbl_deep_extend("force", common_opts, my_opts or {}) -- see `resolve_config()`
> require("lspconfig")["solargraph"].setup(opts)
> ```

Server is installed correctly and starts correctly when manually configured with `require("lspconfig")["solargraph"].setup(default_config)`. I have tried with a very explicit configuration where I point directly to the binary in the `cmd` (`cmd = { '/Users/david/../solargraph', 'stdio' }`) but it was still an issue.

I think it wasn't explicit enough, but I added this invalid command to showcase that the configuration is never used:

```
 cmd = { 'justfail', 'solargraph', 'stdio' },
```
This command isn't valid, so I should see an error. But I don't see any error anywhere, nvim starts but the server doesn't and I don't see any error in the logs. On the other hand, if I manually configure it with `require("lspconfig")["solargraph"].setup(default_config)`, I see an error when starting `lvim`.

with `lspconfig` and a valid command, the server starts correctly.

These are the only logs I see with the lsp manager are:

`lvim: "solargraph is not managed by the automatic installer" file="lua/lvim/lsp/manager.lua", line=87`

I added some print statements and what seems to be happening is the following: solargraph is still installed with lspinstaller (from before), but it isn't managed by lspinstaller because I disabled it. I added an else [here](https://github.com/lunarvim/lunarvim/blob/0000000000000000000000000000000000000000/lua/lvim/lsp/manager.lua#L71) and printed the server with `Log:warn(server)`:
```
  languages = { "ruby" },
  name = "solargraph",
  root_dir = "/Users/david/.local/share/nvim/lsp_servers/solargraph",
```

I will fiddle a bit with this but the I think re-ordering a bit the if/else and the order of the checks should fix this inconsistency.

**Comment by dgmora** [comment]
Looks to me like `get_server` returns false only if the server doesn't exist [at all](`https://github.com/williamboman/nvim-lsp-installer/blob/c2adbc87a070bedc7df10fdfbdc5d1ae6376d627/lua/nvim-lsp-installer/servers/init.lua#L230) within lsp-installer. But it returns true if it exists, even if it's not managed.

This change starts the server correctly with my command, but I am not sure how it could affect different situations:

```diff
-  if not server:is_installed() then
-    if lvim.lsp.automatic_servers_installation then
-      Log:debug "Automatic server installation detected"
-      server:install()
-      install_in_progress = true
-    else
-      Log:debug(server.name .. " is not managed by the automatic installer")
-    end
- end

+ if lvim.lsp.automatic_servers_installation then
+   if (not server:is_installed()) then
+      Log:warn "Automatic server installation detected"
+      server:install()
+      install_in_progress = true
+   end
+ else
+   Log:debug(server.name .. " is not managed by the automatic installer but it's configured")
+   local config = resolve_config(server_name, user_config)
+   -- a log in launch_server would b useful to show the server config/name!
+   launch_server(server_name, config)
+ end
```

**Comment by dgmora** [comment]
Any update about this?

**Comment by lvimuser** [comment]
Does that happen on rolling and did you run `:LvimCacheReset` ?
I get the expected behavior (i.e. it fails if I pass that cmd).

**Comment by kylo252** [comment]
Please let me know if this is still an issue.
