### ISSUE TITLE
Is there a way to install lunarvim as a single binary? e.g. flatpack or appimage or the like

### ISSUE THREAD

**Issue by saimonmoore** [LunarVim/LunarVim#2774]
### Feature Description

I have a use case where I'd like to install lvim on ssh connection but right now it's taking too long due to lvim installing n dependencies.

Would it be possible to install lunarvim as a single binary/package? e.g. flatpack or appimage or the like?

**Comment by kobzar** [comment]
LunarVim is just configuration for neovim. 
after first start plugin must be downloaded from sourses with last version. 
it can’t be in binary file.

**Comment by saimonmoore** [comment]
yeah...but it also downloads a bunch of dependencies...

But yes... I see now it's a bit of a pipe dream.

Thanks @kobzar

**Comment by kobzar** [comment]
I think we can close this enhansemet?

**Comment by BrightXiaoHan** [comment]
Similar with #1511

**Comment by rebuilt** [comment]
Closing since this is tracked elsewhere and because the feasibility of implementation is unclear.
