### ISSUE TITLE
lvim.autocmds does not do anything

### ISSUE THREAD

**Issue by YoungeonLee** [LunarVim/LunarVim#2777]
### Problem description

Setting a table `lvim.autocmds` in `config.lua` doesn't add any autocommands. Is the [doc](https://www.lunarvim.org/configuration/05-autocommands.html) wrong? 
I checked the source code, and I couldn't find any point where `lvim.autocmds` gets passed to [define_autocmds()](https://github.com/LunarVim/lunarvim/blob/3475f7675d8928b49c85878dfc2912407de57342/lua/lvim/core/autocmds.lua#L177).
`lvim.autocommands` works as expected.
Maybe the documentation meant to say `lvim.autocommands` instead of `lvim.autocmds`?

### LunarVim version

master-b04aefb

### Neovim version (>= 0.7)

v0.7.2

### Operating system/version

macOS 12.3

### Steps to reproduce
add following code or similar to `config.lua`
```
lvim.autocmds = {
  {
    "CursorHoldI", {
      pattern = { "*" },
      command = "write"
    },
  }
}
```
no autocommands added

### support info

-

**Comment by rebuilt** [comment]
Looks like it's just a typo.  I think the documentation was updated after this change:  https://github.com/LunarVim/LunarVim/pull/2592

**Comment by rebuilt** [comment]
Docs updated
