### ISSUE TITLE
Unable to load user snippets

### ISSUE THREAD

**Issue by ArnoldWolfstein** [LunarVim/LunarVim#2783]
### Problem description

Hi there,

Lvim doesn't load user defined snippets.
Actually this is exactly the familiar issue with #2626. But even though I did the same instructions mentioned on this issue, I couldn't make user snippets to load. **friendly-snippets** is working fine.

### LunarVim version

rolling-958030e

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

macOS 12.4 & Ubuntu 20.04

### Steps to reproduce

1. Create `~/.config/lvim/snippets/package.json` :

```json
{
  "name": "nvim-snippets",
  "author": "somename",
  "engines": {
    "vscode": "^1.11.0"
  },
  "contributes": {
    "snippets": [
      {
        "language": "python",
        "path": "./python.json"
      }
    ]
  }
}
```

2. Create `~/.config/lvim/python.json`

```json
{
    "Something": {
        "prefix": "something",
        "body": [
            "import logging",
            "",
            "logging.basicConfig(level=logging.INFO)",
            "logger = logging.getLogger(__name__)\n$0",
        ],
        "description": "Code snippet for logging"
    },
}
```

### support info

`:LspInfo`

```console
 Language client log: /Users/arnold/.cache/lvim/lsp.log
 Detected filetype:   python

 2 client(s) attached to this buffer:

 Client: pyright (id: 1, pid: 47986, bufnr: [3])
 	filetypes:       python
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             pyright-langserver --stdio

 Client: null-ls (id: 2, pid: 5001, bufnr: [3])
 	filetypes:       python, javascript, typescriptreact, javascriptreact, typescript, sh
 	autostart:       false
 	root directory:  /private/tmp/dummy
 	cmd:             nvim

 Configured servers list: pyright
```

`:LvimInfo`

```console
      __                          _    ___
     / /   __  ______  ____ _____| |  / (_)___ ___
    / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
   / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
  /_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/


  Buffer info
  * filetype:                python
  * bufnr:                   3
  * treesitter status:       active

  Active client(s)
  * name:                      pyright
  * id:                        1
  * supported filetype(s):     python
  * attached buffers:          3
  * root_dir pattern:          3
  * capabilities:              callHierarchyProvider

  Automatic LSP info
  * Skipped servers: [jedi_language_server, pylsp, sourcery]

  Formatters info
  * Active: isort  , black 
  * Supported: [autopep8, black, blue, isort, reorder_python_imports, yapf]

  Linters info
  * Active: flake8  , codespell 
  * Supported: [flake8, mypy, pydocstyle, pylama, pylint, pyproject_flake8, semgrep, vulture]

  Code actions info
  * Active:
```

### Screenshots

Lvim structure:

<img width="203" alt="ss0" src="https://user-images.githubusercontent.com/42518681/177005008-5008b77c-4a48-4daa-87f5-d3a83e502af6.png">

User defined snippet:

<img width="344" alt="ss1" src="https://user-images.githubusercontent.com/42518681/177005022-83033625-8048-4f09-9867-6ac06abc6d2f.png">

Plugin snippets:

<img width="684" alt="ss2" src="https://user-images.githubusercontent.com/42518681/177005027-ef4aa132-dcd0-4bf0-9e83-dcf07054de34.png">

**Comment by cpea2506** [comment]
I think because your path is `"./python.json"` then you need to create your `python.json` inside your snippets folder

**Comment by ArnoldWolfstein** [comment]
Unfortunately no, it was the first thing that I tried and it doesn't work either.

**Comment by cpea2506** [comment]
> Unfortunately no, it was the first thing that I tried and it doesn't work either.

Then i think i've found the problem. You need to get rid all of comma at the last field of JSON object (or array).

See: https://github.com/L3MON4D3/LuaSnip/issues/388#issuecomment-1100602459

First, fix your path to file. Then edit `python.json` file follows these change.

```diff
{
 "Something": {
        "prefix": "something",
        "body": [
            "import logging",
            "",
            "logging.basicConfig(level=logging.INFO)",
-           "logger = logging.getLogger(__name__)\n$0",
+           "logger = logging.getLogger(__name__)\n$0"
        ],
        "description": "Code snippet for logging"
-   },
+   }
}
```

**Comment by ArnoldWolfstein** [comment]
> First, fix your path to snippet file.

I don't have any user settings. It comes from core settings: [lvim plugins]. Should we change it? Or should we use a custom one?

[lvim plugins]: https://github.com/LunarVim/LunarVim/blob/8989984b781367b2744c4857e73d8943311db241/lua/lvim/plugins.lua#L75-L82

**Comment by cpea2506** [comment]
> > First, fix your path to snippet file.
> 
> I don't have any user settings. It comes from core settings: [lvim plugins](https://github.com/LunarVim/LunarVim/blob/8989984b781367b2744c4857e73d8943311db241/lua/lvim/plugins.lua#L75-L82). Should we change it? Or should we use a custom one?

Nah! I mean, you move your `python.json` file to snippet folder 🥲

**Comment by kylo252** [comment]
As mentioned, you need to move your snippet file into the snippets folder, or use an absolute path instead.

see a full example at:  https://www.lunarvim.org/configuration/08-custom-snippets.html#json-version
