### ISSUE TITLE
New terminal tab opens inside LSP installation directory

### ISSUE THREAD

**Issue by Lun4m** [LunarVim/LunarVim#2790]
### Problem description

I'm not sure this is a LunarVim bug, but when I open a new (`kitty`) terminal tab with `<ctrl-shift-t>` while editing a python file with `pyright` enabled I get redirected to the LSP server installation directory (`~/.local/share/nvim/lsp_servers/pyright/node_modules/pyright/dist`). 

It doesn't happen with other servers, for example if edit the `config.lua` in `~/.config/lvim` with `sumneko_lua` active the new tab opens in that same directory. And it doesn't seem to happen with other terminals (I've only tested Gnome terminal, but in this case the new tab is opened in the directory from where `lvim` is started)

### LunarVim version

rolling-e662039 (but it has been happening for some time now, a couple weeks maybe)

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

Ubuntu 22.04

### Affected language servers

pyright

### Steps to reproduce

1. Open a `.py` file with `pyright` enabled in `kitty`
2. Open a new terminal tab with `<ctrl-shift-t>`

### Actual behavior

The tab is opened in `~/.local/share/nvim/lsp_servers/pyright/node_modules/pyright/dist`.

### Expected behavior

The tab should open in the `.py` file root directory.

### support info

```console
 Language client log: /home/manuel/.cache/lvim/lsp.log
 Detected filetype:   python
 
 2 client(s) attached to this buffer: 
 
 Client: pyright (id: 1, pid: 20760, bufnr: [1])
 	filetypes:       python
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             pyright-langserver --stdio
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [1])
 	filetypes:       python
 	autostart:       false
 	root directory:  /home/manuel/test
 	cmd:             nvim
 
 Configured servers list: pyright
```

```console

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                python
* bufnr:                   1
* treesitter status:       active

Active client(s)
* name:                      pyright
* id:                        1
* supported filetype(s):     python
* attached buffers:          1
* root_dir pattern:          1
* capabilities:              callHierarchyProvider

Automatic LSP info
* Skipped servers: [jedi_language_server, pylsp, sourcery]

Formatters info
* Active: black  
* Supported: [autopep8, black, blue, isort, reorder_python_imports, yapf]

Linters info
* Active: 
* Supported: [flake8, mypy, pydocstyle, pylama, pylint, pyproject_flake8, semgrep, vulture]

Code actions info
* Active: 
```

**Comment by kobzar** [comment]
Arch linux
neovim 7.2
LunarVim stable
kitty with default config

Can't repeat the problem

**Comment by Lun4m** [comment]
It's probably a problem with my config then, I'll try with a fresh install of LunarVim. But with stable you mean the `master` or `rolling` branch?

**Comment by kobzar** [comment]
I mean kitty clear config. Not lunarvim. Test it with kitty default settings.

**Comment by Lun4m** [comment]
Yeah, my `kitty.conf` was the culprit. 
This line in particular: `map ctrl+shift+t launch --cwd=current --type=tab`. 
Apparently kitty reads the current path inside LunarVim as the LS install directory while if I type `:pwd` inside nvim I get the correct path. 
Anyway this behaviour wasn't there a couple weeks ago, so I don't know what changed in either kitty or LunarVim.
