### ISSUE TITLE
LunarVim cannot completely be installed because of "Killing git due to timeout!"

### ISSUE THREAD

**Issue by dennis605** [LunarVim/LunarVim#2794]
### Problem description

If I try to install LunarVim with following command
` bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
`
everything went fine until installer tries to prepare Packer setup.
If installer is in that phase there is a break for about 5 Minutes and then installer hangs with error:

`[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!`  
and will throw more errors saying: "Killing git due to timeout!"
I will put the whole output in field "support info"

### LunarVim version

master-b04aefb

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Debian 11

### Steps to reproduce

1. install LunarVim with following command: `bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`
2. answer all following question with YES

### support info

` bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

      88\                                                   88\
      88 |                                                  \__|
      88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
      88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
      88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
      88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
      88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
      \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|

--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : yes
[ERROR] Unable to install using [pnpm] without administrative privileges.
Installing node modules with yarn..
yarn global v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "neovim@4.10.1" with binaries:
      - neovim-node-host
success Installed "tree-sitter-cli@0.20.6" with binaries:
      - tree-sitter
Done in 1.86s.
All NodeJS dependencies are successfully installed
--------------------------------------------------------------------------------
Would you like to install LunarVim's Python dependencies?
[y]es or [n]o (default: no) : yes
Verifying that pip is available..
Installing with pip..
Requirement already satisfied: pynvim in /usr/lib/python3/dist-packages (0.4.2)
All Python dependencies are successfully installed
--------------------------------------------------------------------------------
Would you like to install LunarVim's Rust dependencies?
[y]es or [n]o (default: no) : yes
All Rust dependencies are successfully installed
--------------------------------------------------------------------------------
Cloning LunarVim configuration
Klone nach '/home/dock/.local/share/lunarvim/lvim' ...
remote: Enumerating objects: 147, done.
remote: Counting objects: 100% (147/147), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 147 (delta 6), reused 56 (delta 6), pack-reused 0
Empfange Objekte: 100% (147/147), 120.13 KiB | 3.25 MiB/s, fertig.
Löse Unterschiede auf: 100% (6/6), fertig.
--------------------------------------------------------------------------------
Installing LunarVim shim
make: Verzeichnis „/home/dock/.local/share/lunarvim/lvim“ wird betreten
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: /home/dock/.local/bin/lvim
make: Verzeichnis „/home/dock/.local/share/lunarvim/lvim“ wird verlassen
Preparing Packer setup
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca145a20 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca144d50 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3f7250 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3f51e0 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca11d4c0 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3f5ca0 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3f6250 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3e39d0 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3e4020 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3e4670 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3e4cc0 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3f8020 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3f8670 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3f8cc0 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3f9720 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3f9d70 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3fa3c0 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3faa10 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3fb060 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3fb6b0 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3fbd00 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3fc350 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3fc9a0 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3fcff0 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3fd640 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3fdc90 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca3fe2e0 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:86: bad argument #1 to 'is_active' (Expected uv_handle userdata)
stack traceback:
	[C]: in function 'is_active'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:86: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:86: bad argument #1 to 'is_active' (Expected uv_handle userdata)
stack traceback:
	[C]: in function 'is_active'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:86: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:86: bad argument #1 to 'is_active' (Expected uv_handle userdata)
stack traceback:
	[C]: in function 'is_active'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:86: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:86: bad argument #1 to 'is_active' (Expected uv_handle userdata)
stack traceback:
	[C]: in function 'is_active'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:86: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca400270 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca4008c0 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>
[packer.nvim] [WARN  23:32:51] jobs.lua:87: Killing git due to timeout!
Error executing luv callback:
...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: handle 0x55e1ca400f10 is already closing
stack traceback:
	[C]: in function 'close'
	...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:91: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83>^Z
[1]+  Angehalten              bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`

**Comment by kobzar** [comment]
try to install rolling release for test please

**Comment by dennis605** [comment]
Hi kozbar, thanks for your response, but I already tried it with rolling release - same result unfortunately, but just a little more verbose.

**Comment by rebuilt** [comment]
The number of max jobs was changed two days ago from an unlimited number to 40 in this commit:  https://github.com/LunarVim/LunarVim/commit/48320e5f882a911707c56baf3865f663acb39f08#diff-f3e7cf9b1162ca847a396d5bdee23e60fc38f045cfa841bc516699c42dcea244

You can set the max number of jobs yourself with this in your configuration

```
require("packer").init({
	max_jobs = nil,
})

```

I realize this does not fix the installer script.  But it seems like you can clone the repo yourself so I'm hoping you can do some testing and report back with a number of jobs that works on your machine.  

First try opening `lvim` and running `:PackerSync` to confirm you get the same timout message when installing manually. Then please set the max number of jobs to `nil` or some other values to see if that makes a difference.

If that doesn't work, packer also has some other git settings you might try adjusting.  The most interesting one being  `clone_timeout`

```lua
require("packer").init({
	  git = {
                  cmd = 'git', -- The base command for git operations
                  subcommands = { -- Format strings for git subcommands
                    update         = 'pull --ff-only --progress --rebase=false',
                    install        = 'clone --depth %i --no-single-branch --progress',
                    fetch          = 'fetch --depth 999999 --progress',
                    checkout       = 'checkout %s --',
                    update_branch  = 'merge --ff-only @{u}',
                    current_branch = 'branch --show-current',
                    diff           = 'log --color=never --pretty=format:FMT --no-show-signature HEAD@{1}...HEAD',
                    diff_fmt       = '%%h %%s (%%cr)',
                    get_rev        = 'rev-parse --short HEAD',
                    get_msg        = 'log --color=never --pretty=format:FMT --no-show-signature HEAD -n 1',
                    submodules     = 'submodule update --init --recursive --progress'
                  },
                  depth = 1, -- Git clone depth
                  clone_timeout = 60, -- Timeout, in seconds, for git clones
                  default_url_format = 'https://github.com/%s' -- Lua format string used for "aaa/bbb" style plugins
                },
})
```

**Comment by rebuilt** [comment]
User configs for lunarvim are in `~/.config/lvim/config.lua`   You can place any configuration options you want to change in that file.  

For more info:  https://www.lunarvim.org/configuration/

**Comment by dennis605** [comment]
Oh wow! thank you very much. I put `require("packer").init({ max_jobs = 1, }) ` in the configuration file. Now it tooks longer, because it clones one after another, but it works and that is the important thing. Thank you so much for your help.

**Comment by rebuilt** [comment]
Great!  Glad it worked out for you.
