### ISSUE TITLE
The color of popup window for default colorscheme

### ISSUE THREAD

**Issue by c02y** [LunarVim/LunarVim#2798]
### Problem description

The color of popup window for "default" colorscheme is weird.

I can use the following config to solve this:
```
lvim.autocommands = {
	{ "ColorScheme", { pattern = { "*" }, command = "highlight Pmenu ctermbg=NONE guibg=NONE" } },
	{ "ColorScheme", { pattern = { "*" }, command = "highlight FloatBorder ctermbg=NONE guibg=NONE" } },
}
```
But since it is an issue of `default` colorscheme, I'll consider it as a bug or it needs improvement.

### LunarVim version

master-b04aefb

### Neovim version (>= 0.7.2)

v0.7.2

### Operating system/version

Arch Linux 5.18.9-zen1-1-zen

### Steps to reproduce

1. refresh new lunarvim install
2. use `lvim.colorscheme = "default"` in config.lua
3. Hit `Space` to activae which-key window or `Space p u` to active the packer update window
4. check the background of pop up windows

### support info

Open vim without any buffer:
LspInfo:
```


                       Language client log: /home/chz/.cache/lvim/lsp.log
                       Detected filetype:   alpha

                       0 client(s) attached to this buffer:

                       Configured servers list:

```

LvimInfo:
```
Error executing Lua callback: vim/shared.lua:0: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function <vim/shared.lua:0>
        vim/shared.lua: in function 'tbl_filter'
        /home/chz/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info'
        /home/chz/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'
        ...hz/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:29: in function <...hz/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:28>
```

### Screenshots

![2022-07-08_00-20](https://user-images.githubusercontent.com/2135996/177822752-32b757a9-a00d-44f4-8a67-166924db6f72.png)
![2022-07-08_00-20_1](https://user-images.githubusercontent.com/2135996/177823213-6606ffa2-33bd-483c-81e6-2c4b9d23e826.png)

**Comment by c02y** [comment]
> [`default`](https://github.com/neovim/neovim/blob/master/runtime/colors/default.vim) is `Neovim's colorscheme`. I don't know if `LunarVim` can make some improvements here.

Maybe add this config into LunarVim code when using `default` theme:
```
        { "ColorScheme", { pattern = { "*" }, command = "highlight Pmenu ctermbg=NONE guibg=NONE" } },
	{ "ColorScheme", { pattern = { "*" }, command = "highlight FloatBorder ctermbg=NONE guibg=NONE" } },
```

**Comment by kylo252** [comment]
As mentioned, `default` is a neovim colorscheme, otherwise, the new `tokyonight` colorscheme in rolling offer additional tweaks if you'd like.
