### ISSUE TITLE
Theta Theme for Alpha Nvim

### ISSUE THREAD

**Issue by guilhermeprokisch** [LunarVim/LunarVim#2801]
### Feature Description

In alpha-nvim, besides stratify and dashboard there's also a default theme [theta](https://github.com/goolord/alpha-nvim/blob/main/lua/alpha/themes/theta.lua) that it's a hybrid between both. How can I make or use this for Lunarvim?

### Describe the alternatives you have considered

None

**Comment by guilhermeprokisch** [comment]
@goolord maybe you can have a suggestion here, thanks.

**Comment by cpea2506** [comment]
You can use `lvim.builtin.alpha.dashboard.config` to completely write user's custom config

Here is what I have in mind.

```lua
-- originally authored by @AdamWhittingham

local path_ok, plenary_path = pcall(require, "plenary.path")
if not path_ok then
    return
end

local dashboard = require "alpha.themes.dashboard"
local user_config_path = require("lvim.config"):get_user_config_path()
local cdir = vim.fn.getcwd()
local if_nil = vim.F.if_nil

local function get_extension(fn)
    local match = fn:match "^.+(%..+)$"
    local ext = ""
    if match ~= nil then
        ext = match:sub(2)
    end
    return ext
end

local function icon(fn)
    local nwd = require "nvim-web-devicons"
    local ext = get_extension(fn)
    return nwd.get_icon(fn, ext, { default = true })
end

local function file_button(fn, sc, short_fn)
    short_fn = short_fn or fn
    local ico_txt
    local fb_hl = {}

    if lvim.use_icons then
        local ico, hl = icon(fn)
        table.insert(fb_hl, { hl, 0, 3 })
        ico_txt = ico .. "  "
    else
        ico_txt = ""
    end
    local file_button_el = dashboard.button(sc, ico_txt .. short_fn, "<cmd>e " .. fn .. " <CR>")
    local fn_start = short_fn:match ".*[/\\]"
    if fn_start ~= nil then
        table.insert(fb_hl, { "Comment", #ico_txt - 2, #fn_start + #ico_txt })
    end
    file_button_el.opts.hl = fb_hl
    return file_button_el
end

local default_mru_ignore = { "gitcommit" }

local mru_opts = {
    ignore = function(path, ext)
        return (string.find(path, "COMMIT_EDITMSG")) or (vim.tbl_contains(default_mru_ignore, ext))
    end,
}

--- @param start number
--- @param cwd string optional
--- @param items_number number optional number of items to generate, default = 10
local function mru(start, cwd, items_number, opts)
    opts = opts or mru_opts
    items_number = if_nil(items_number, 10)

    local oldfiles = {}
    for _, v in pairs(vim.v.oldfiles) do
        if #oldfiles == items_number then
            break
        end
        local cwd_cond
        if not cwd then
            cwd_cond = true
        else
            cwd_cond = vim.startswith(v, cwd)
        end
        local ignore = (opts.ignore and opts.ignore(v, get_extension(v))) or false
        if (vim.fn.filereadable(v) == 1) and cwd_cond and not ignore then
            oldfiles[#oldfiles + 1] = v
        end
    end
    local target_width = 35

    local tbl = {}
    for i, fn in ipairs(oldfiles) do
        local short_fn
        if cwd then
            short_fn = vim.fn.fnamemodify(fn, ":.")
        else
            short_fn = vim.fn.fnamemodify(fn, ":~")
        end

        if #short_fn > target_width then
            short_fn = plenary_path.new(short_fn):shorten(1, { -2, -1 })
            if #short_fn > target_width then
                short_fn = plenary_path.new(short_fn):shorten(1, { -1 })
            end
        end

        local shortcut = tostring(i + start - 1)

        local file_button_el = file_button(fn, shortcut, short_fn)
        tbl[i] = file_button_el
    end
    return {
        type = "group",
        val = tbl,
        opts = {},
    }
end

local default_header = {
    type = "text",
    val = {
        [[    __                          _    ___         ]],
        [[   / /   __  ______  ____ _____| |  / (_)___ ___ ]],
        [[  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \]],
        [[ / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /]],
        [[/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ ]],
    },
    opts = {
        position = "center",
        hl = "Type",
        -- wrap = "overflow";
    },
}

local section_mru = {
    type = "group",
    val = {
        {
            type = "text",
            val = "Recent files",
            opts = {
                hl = "SpecialComment",
                shrink_margin = false,
                position = "center",
            },
        },
        { type = "padding", val = 1 },
        {
            type = "group",
            val = function()
                return { mru(0, cdir) }
            end,
            opts = { shrink_margin = false },
        },
    },
}

local buttons = {
    type = "group",
    val = {
        dashboard.button("SPC f", "  Find File", ":Telescope find_files<CR>"),
        dashboard.button("SPC n", "  New File", ":ene!<CR>"),
        dashboard.button("SPC P", "  Recent Projects ", ":Telescope projects<CR>"),
        dashboard.button("SPC s r", "  Recently Used Files", ":Telescope oldfiles<CR>"),
        dashboard.button("SPC s t", "  Find Word", ":Telescope live_grep<CR>"),
        dashboard.button("SPC L c", "  Configuration", ":edit " .. user_config_path .. "<CR>"),
    },
    position = "center",
}

lvim.builtin.alpha.dashboard.config = {
    layout = {
         { type = "padding", val = 2 },
         default_header,
         { type = "padding", val = 2 },
         section_mru,
         { type = "padding", val = 2 },
         buttons,
    },
    opts = {
        margin = 5,
        setup = function()
            vim.cmd [[autocmd alpha_temp DirChanged * lua require('alpha').redraw()]]
        end,
    },
}
```

**Comment by HungLe14** [comment]
@cpea2506 Where is that codes should be located?

**Comment by cpea2506** [comment]
> @cpea2506 Where is that codes should be located?

Just put all of them inside `config.lua` or if you see that it’s too much to put in a config file, you can create `lua/user/alpha.lua`, paste them in and `require "user.alpha"` in `config.lua`

**Comment by HungLe14** [comment]
> > @cpea2506 Where is that codes should be located?
> 
> Just put all of them inside your `config.lua` or if you see that it’s too much to put in a config file, you can create `lua/user/alpha.lua`, paste them in and `require "user.alpha"` in `config.lua`

Lunar has 2 config folder, the first one in ~/.local/bin/share/lunarvim/lvim and the second one in ~/.config/lvim. So which one as you mention?

**Comment by cpea2506** [comment]
> > > @cpea2506 Where is that codes should be located?
> > 
> > 
> > Just put all of them inside your `config.lua` or if you see that it’s too much to put in a config file, you can create `lua/user/alpha.lua`, paste them in and `require "user.alpha"` in `config.lua`
> 
> Lunar has 2 config folder, the first one in ~/.local/bin/share/lunarvim/lvim and the second one in ~/.config/lvim. So which one as you mention?

It should be `~/.config/lvim`. You should not touch any thing inside this folder `~/.local/bin/share/lunarvim/lvim` as it can make you fail to receive update from `LunarVim` 😉

**Comment by HungLe14** [comment]
@cpea2506 Is there anyway to increase the padding between option in dashboard?

**Comment by cpea2506** [comment]
> @cpea2506 Is there anyway to increase the padding between option in dashboard?

I'm not sure but you can try to add `spacing = <number>` into `opts` table where you want to increase spacing.

- mru section
```diff
local section_mru = {
    type = "group",
    val = {
        {
            type = "text",
            val = "Recent files",
            opts = {
                hl = "SpecialComment",
                shrink_margin = false,
                position = "center",
            },
        },
        { type = "padding", val = 1 },
        {
            type = "group",
            val = function()
                return { mru(0, cdir) }
            end,
            opts = { 
                 shrink_margin = false
+                spacing = 2
            },
        },
    },
}
```

- buttons
```diff
local buttons = {
    type = "group",
    val = {
        dashboard.button("SPC f", "  Find File", ":Telescope find_files<CR>"),
        dashboard.button("SPC n", "  New File", ":ene!<CR>"),
        dashboard.button("SPC P", "  Recent Projects ", ":Telescope projects<CR>"),
        dashboard.button("SPC s r", "  Recently Used Files", ":Telescope oldfiles<CR>"),
        dashboard.button("SPC s t", "  Find Word", ":Telescope live_grep<CR>"),
        dashboard.button("SPC L c", "  Configuration", ":edit " .. user_config_path .. "<CR>"),
    },
+   opts = {
+       spacing = 1,
+   },
    position = "center",
}
```

**Comment by HungLe14** [comment]
It doesn't work for me. Do you have another way?

**Comment by HungLe14** [comment]
Thank you @cpea2506! That's great!

**Comment by guilhermeprokisch** [comment]
@cpea2506 thanks a lot your code it's exactly what I want. 

But I still have a problem loading an external script as you mentioned here: 

> > > > @cpea2506 Where is that codes should be located?
> > > 
> > > 
> > > Just put all of them inside your `config.lua` or if you see that it’s too much to put in a config file, you can create `lua/user/alpha.lua`, paste them in and `require "user.alpha"` in `config.lua`
> > 
> > 
> > Lunar has 2 config folder, the first one in ~/.local/bin/share/lunarvim/lvim and the second one in ~/.config/lvim. So which one as you mention?
> 
> It should be `~/.config/lvim`. You should not touch any thing inside this folder `~/.local/bin/share/lunarvim/lvim` as it can make you fail to receive update from `LunarVim` 😉


I create the file `~/.config/lvim/lua/user/alpha.lua` and tried to put `require("user.alpha")` in the begin config.lua but still not working.

**Comment by cpea2506** [comment]
> I create the file `~/.config/lvim/lua/user/alpha.lua` and tried to put `require("user.alpha")` in the config.lua but still not working.

I don't know what you have done with your config before. Maybe it's overridden somewhere in your config.

It works for me in case you wanna see how i set it

<img width="1280" alt="Screen Shot 2022-07-09 at 20 55 40" src="https://user-images.githubusercontent.com/42694704/178108878-dd67a6b3-b86f-47b8-824b-bd23f8fa70e1.png">

**Comment by guilhermeprokisch** [comment]
Cool, thanks. Nice organization, it's the `extend` an Lua builtin or you implemented?

**Comment by cpea2506** [comment]
> Cool, thanks. Nice organization, it's the `extend` a Lua builtin or you implemented?

It's my implemented, a very simple function if you are interested in 😊

```lua
function lvim:extend(opts)
    lvim = vim.tbl_deep_extend("force", self, opts)
end
```

**Comment by guilhermeprokisch** [comment]
Nice! 

Also just fixed the import

Thanks
