### ISSUE TITLE
How to disable format_on_save when opening vim to edit a file

### ISSUE THREAD

**Issue by c02y** [LunarVim/LunarVim#2803]
### Feature Description

I have a few .c/.h files which are from other people, and they are formatted.

When I edit it, I need to disable `format_on_save` which I already set in my `init.lua` file `lvim.format_on_save = true
`, otherwise, when I save them, the format will become quite different from the old one, I have to keep it simple, how can do this from command line?

**Comment by cpea2506** [comment]
<img width="232" alt="Screen Shot 2022-07-09 at 16 14 43" src="https://user-images.githubusercontent.com/42694704/178099654-655b884e-a792-41bb-be56-3365e8280884.png">

**Comment by c02y** [comment]
I mean from command line, not from inside lunarvim.

I use this inside bash script.

**Comment by cpea2506** [comment]
`lvim +LvimToggleFormatOnSave`

**Comment by c02y** [comment]
That's great, thanks.
