### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by SingularisArt** [LunarVim/LunarVim#2804]
[Here](https://github.com/LunarVim/LunarVim/issues/2765#issuecomment-1169792282), someone said that I was in violation of the GPLv3 license and I was violating th at license because of [this](https://github.com/SingularisArt/DeathVim) repo.
Can someone explain how can I fix that because I don't want any issues?

PS: This is my first time doing any of this stuff.

**Comment by luxus** [comment]
@SingularisArt can you close this issue?

**Comment by SingularisArt** [comment]
Yeah.

**Comment by Uzaaft** [comment]
Also, just my personal opinion. But I think credit should be given where it's due. I think me, and most of the Lunarvim contributors would appreciate it if credit is given to Lunarvim, consider how much code you have borrowed. 
Just ***my*** five cents.

**Comment by luxus** [comment]
thats correct I expected he did credit us already by now.. mhh @SingularisArt can u fix that?

**Comment by SingularisArt** [comment]
Sorry. I've been working on other projects.
Of course. By the end of today, I'll add the credit section.

**Comment by luxus** [comment]
thanks, just mark this issue in the commit.
have a great weekend.

**Comment by Uzaaft** [comment]
Added in: https://github.com/SingularisArt/DeathVim/commit/e3f4eddafd2cd9f3b50a97fe20a64271dc42f5eb
