### ISSUE TITLE
Powershell Installation Script Failure

### ISSUE THREAD

**Issue by UnrealApex** [LunarVim/LunarVim#2805]
### Problem description

When running the installation Powershell script
```powershell
Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression
```
LunarVim does not install correctly and the script throws errors:
```
Invoke-Expression : At line:5 char:25
+ $LV_BRANCH = $LV_BRANCH ?? "rolling"
+                         ~~
Unexpected token '??' in expression or statement.
At line:6 char:25
+ $LV_REMOTE = $LV_REMOTE ??  "lunarvim/lunarvim.git"
+                         ~~
Unexpected token '??' in expression or statement.
At line:7 char:35
+ $INSTALL_PREFIX = $INSTALL_PREFIX ?? "$HOME\.local"
+                                   ~~
Unexpected token '??' in expression or statement.
At line:9 char:41
+ $env:XDG_DATA_HOME = $env:XDG_DATA_HOME ?? $env:APPDATA
+                                         ~~
Unexpected token '??' in expression or statement.
At line:10 char:45
+ $env:XDG_CONFIG_HOME = $env:XDG_CONFIG_HOME ?? $env:LOCALAPPDATA
+                                             ~~
Unexpected token '??' in expression or statement.
At line:11 char:43
+ $env:XDG_CACHE_HOME = $env:XDG_CACHE_HOME ?? $env:TEMP
+                                           ~~
Unexpected token '??' in expression or statement.
At line:13 char:55
+ $env:LUNARVIM_RUNTIME_DIR = $env:LUNARVIM_RUNTIME_DIR ?? "$env:XDG_DA ...
+                                                       ~~
Unexpected token '??' in expression or statement.
At line:14 char:53
+ $env:LUNARVIM_CONFIG_DIR = $env:LUNARVIM_CONFIG_DIR ?? "$env:XDG_CONF ...
+                                                     ~~
Unexpected token '??' in expression or statement.
At line:15 char:51
+ $env:LUNARVIM_CACHE_DIR = $env:LUNARVIM_CACHE_DIR ?? "$env:XDG_CACHE_ ...
+                                                   ~~
Unexpected token '??' in expression or statement.
At line:16 char:49
+ $env:LUNARVIM_BASE_DIR = $env:LUNARVIM_BASE_DIR ?? "$env:LUNARVIM_RUN ...
+                                                 ~~
Unexpected token '??' in expression or statement.
At line:1 char:125
+ ... ster/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression
+                                                         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : UnexpectedToken,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

### LunarVim version

N/A

### Neovim version (>= 0.7.2)

N/A

### Operating system/version

Windows 10

### Steps to reproduce

1. Copy  the Powershell script provided in the README:
```powershell
Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression
```
2. Open a Powershell prompt and run it
3. See errors

### support info

N/A, but perhaps the problem is caused by still having an `nvim` folder in my `%APPDATA%`?

### Screenshots

![image](https://user-images.githubusercontent.com/79121360/178130126-26d48c4b-cfcf-4652-a6e0-c839541d9d22.png)

**Comment by rebuilt** [comment]
I don't know anything about powershell so take my advice with a grain of salt.  

It look like the error message is saying powershell doesn't know what the double question marks are.   
The readme states powershell version 7+ is required for the installer.  
My guess is you'll have to upgrade your version of powershell to install it.  

https://github.com/LunarVim/LunarVim#windows-powershell-7
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.2

**Comment by UnrealApex** [comment]
Yeah you were right about that, checking my PowerShell version, it was `5.1`. I installed PowerShell 7 and that solved the errors. Though there are some new errors that occured.

**Comment by kobzar** [comment]
Its just my things:
After a lot of time i was understand that use vim/nvim on windiows is really stupid idea. 
We need install PS 7++, gnu compilator, normal terminal, fonts e.t.c and every time we have some fucking os problem.
So, the best way its use WSL.
Just use it for vim/nvim/lvim and for developer tools for any langs.

**Comment by UnrealApex** [comment]
I see, a majority of Vim enthusiasts use Linux so Windows support is second priority.
> We need install PS 7++, gnu compilator, normal terminal, fonts e.t.c and every time we have some fucking os problem.

I'm not sure if GCC is supported on Windows or without some addition setup that is required.

**Comment by vonPB** [comment]
I personally enjoy using nvim/lunarvim on Windows (without WSL). The support of most plugins/extensions for windows has been great so far.
I've got Windows Terminal setup with powershell, Oh My Posh and of course a nerd font. You are free to use nvim-qt or just launch it in any terminal you already have. And I'm also not aware that you would need gcc.

> I'm not sure if GCC is supported on Windows or without some addition setup that is required.
mingw was created to support gcc on windows. So gcc is not directly supported as far as I know.

back to the problem...
#2758 had a similar issue. Deleting the lunarvim files and running the installation again has worked when I tested his issue in a vm.

**Comment by kobzar** [comment]
Remember for all time:
Windows user - isn't user.
The're need just click on the link, download the exe file, run it, click few time next - finish;


And the second problem, windousers newer reading the documentation. Their phylosofy you can find in my previous message :)

**Comment by UnrealApex** [comment]
I read documentation :), well, when I feel like it.

**Comment by vonPB** [comment]
Don't really understand what you are on a about @kobzar . Sure, windows is focused on having a better UI experience than Linux. I don't think having the possibility to select for instance different components during the installation is a bad thing. It's so much easier for a 80 year old than having to read through a documentation just to install something. Not everyone has the time for that. Why else do you think like 85% of the people use windows? I say that preferring Linux...

And most installers can be used from the command line in a silent mode as well. Download the exe with curl, no mouse clicks, nothing different than a Linux install. 

I'm sure most developers on windows are just as dependent on good documentation as linux users.

**Comment by vonPB** [comment]
@UnrealApex did reinstalling work for you?

**Comment by UnrealApex** [comment]
Reinstalled fixed https://github.com/LunarVim/LunarVim/issues/2805#issuecomment-1179654631 but when I opt to have the script add `lvim` to my path, we get this error:
```
Would you like to create an alias inside your Powershell profile?
(This enables you to start lvim with the command 'lvim') [y]es or [n]o (default: no): y
Add-Content:
Line |
 270 |      Add-Content -Path $PROFILE -Value $("`r`nSet-Alias lvim $lvim_bin …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find a part of the path 'C:\Users\s158658\Documents\PowerShell\Microsoft.PowerShell_profile.ps1'.
```

**Comment by vonPB** [comment]
the creation of the alias is the last step in the installer, so it should work without issues.
https://github.com/LunarVim/LunarVim/blob/c6431a09c7e6541dba46a7f7e6db7a34d0d00092/utils/installer/install.ps1#L225

**Comment by UnrealApex** [comment]
The directory name appears to be `WindowsPowershell`, not `Powershell`.

**Comment by vonPB** [comment]
Only got it without Windows on my systems, but it should be whatever `$PROFILE` points to. 
@UnrealApex did `Microsoft.PowerShell_profile.ps1` exist? I think that's the issue. `$PROFILE` can point to non existing files.

**Comment by UnrealApex** [comment]
Yep it did, I guess the PowerShell script was looking in the wrong directory. Creating the file in the directory the script pointed to did work though.

**Comment by UnrealApex** [comment]
> Strange. U can fix it manually by going to your documents\Powershell and create/add to the file `Microsoft.PowerShell_profile.ps1`
> 
> ```powershell
> Set-Alias lvim C:\Users\s158658\.local\bin\lvim.ps1
> ```


Correction, the path is:
```powershell
Set-Alias lvim C:\Users\User\AppData\Roaming\LunarVim\lvim\utils\bin\lvim.ps1
```

**Comment by LeonardoDaLuz** [comment]
PLEASE! Executable installer PLEASE! TIME IS MONEY? Why does vim always have to be a pain to install and configure everything? Now there's this horrible way of installing from the power shell, which ALWAYS causes problems.

**Comment by LeonardoDaLuz** [comment]
I updated to power shell 7.2. The terminal closes when I run the above installation command. I've been trying to get a complete vim like ide since 2 pm (it's already 21) and I can't. I'm pretty frustrated. The barrier to joining vim as an IDE is too big, it's buggy.

**Comment by vonPB** [comment]
Have you installed all the dependencies (nvim / LunarVim)?
I'm sorry to hear about your difficulties.

**Comment by UnrealApex** [comment]
> Have you installed all the dependencies (nvim / LunarVim)? I'm sorry to hear about your difficulties.

Yep, I guess this is some experience configuring tools designed for Linux.

**Comment by kylo252** [comment]
I think the problem stems from `Invoke-Expression` disregarding the very first line of the file

https://github.com/LunarVim/LunarVim/blob/eefde00ae80f91ecf88a93e869e346fdd04c7ba4/utils/installer/install.ps1#L1

> The #Requires statement prevents a script from running unless the PowerShell version, modules (and version), or snap-ins (and version), and edition prerequisites are met. If the prerequisites aren't met, PowerShell doesn't run the script or provide other runtime features, such as tab completion.

ref: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires

probably related
- https://github.com/PowerShell/PowerShell/issues/11662

**Comment by fernandobracaroto** [comment]
Just tried today, got the same error, this project seems pointless if I have to deal with all the bullshit that comes with setting up vim.

**Comment by UnrealApex** [comment]
Lunarvim is a good project, just I would say that the problem is that this project does not have many maintainers that use Windows, thus Windows support is not fully polished.
