### ISSUE TITLE
How to set max column width for c++ formatter

### ISSUE THREAD

**Issue by RenliangShi** [LunarVim/LunarVim#2807]
Is there any way to set max column width for c++ formatting like wordWrapColumn for vscode?

**Comment by RenliangShi** [comment]
I am new to this, can you please give a complete setting example of clang_format, thanks.

**Comment by RenliangShi** [comment]
> https://www.lunarvim.org/languages/c_cpp.html#install-language-server
> 
> ```
> formatters.setup { { exe = "uncrustify", args = {} } }
> ```

I am new to this, can you please give a complete setting example of clang_format, thanks.

**Comment by kobzar** [comment]
Install clang-format
https://packagecontrol.io/packages/Clang%20Format
add next in your config
```
local formatters = require("lvim.lsp.null-ls.formatters")
formatters.setup({
	{ command = "clang-format", extra_args = { "--ColumnLimit", "120" }, filetypes = { "cpp" } },
})

```

**Comment by RenliangShi** [comment]
> Install clang-format https://packagecontrol.io/packages/Clang%20Format add next in your config
> 
> ```
> local formatters = require("lvim.lsp.null-ls.formatters")
> formatters.setup({
> 	{ command = "clang-format", extra_args = { "--ColumnLimit", "120" }, filetypes = { "cpp" } },
> })
> ```



> Install clang-format https://packagecontrol.io/packages/Clang%20Format add next in your config
> 
> ```
> local formatters = require("lvim.lsp.null-ls.formatters")
> formatters.setup({
> 	{ command = "clang-format", extra_args = { "--ColumnLimit", "120" }, filetypes = { "cpp" } },
> })
> ```

Thanks for your reply, I tried as you suggest, but it didn't work for me. Then I found https://github.com/LunarVim/LunarVim/issues/2597#issuecomment-1122731886.Now it works fine for me.
