### ISSUE TITLE
Colorizer plugin brake the LunarVim

### ISSUE THREAD

**Issue by kobzar** [LunarVim/LunarVim#2808]
### Problem description

After spent some time i can approve that problem with Colorizer plugin is still present.
https://github.com/LunarVim/LunarVim/issues/2718

So, i remove it again.
When plugin is Active have a long freeses in editor for simple actions like move cursor or scroll.
File is small. File type can be any.

### LunarVim version

master

### Neovim version (>= 0.7.2)

7.2

### Operating system/version

any

### Steps to reproduce

Download/Install QMK (this is the library for custom keyboards)
https://docs.qmk.fm/#/newbs_getting_started

next try to go and edit eny config file like
<your qmk path>/keyboards/keycapsss/kimiko/keymaps/default
(/Users/kobzar/Develop/QMK/keyboards/keycapsss/kimiko/keymaps/default) as example
lvim keymap.c

### support info

No need

**Comment by Uzaaft** [comment]
Could you run `lvim` with verbose logging to a file, and add it to a gist while recreating the problem?

**Comment by itsdevcoffee** [comment]
With the latest rolling update `colorizer` was totally broken. 

I ended up changing to `nvim-highlight-colors`

```
	{
		'brenoprata10/nvim-highlight-colors',
		config = function()
			require('nvim-highlight-colors').setup(
				{
					-- render = 'background',
					-- render = 'first_column',
					render = 'foreground',
				})
		end

	},

```

**Comment by opalmay** [comment]
Colorizer works fine for me as shown in the docs, nothing here should be lvim specific. if this is still an issue, try to replicate it in neovim with  [`minimal_init.lua`](https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua) and let us know.
