### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by jackyliu16** [LunarVim/LunarVim#2811]
### Problem description

Because this report is a installing report so that i couldn't giving anykind of information on it. i **just using the install script to install it...**

### LunarVim version

None(BC i haven't install it)

### Neovim version (>= 0.7.2)

NVIM v0.7.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by runner@fv-az164-457  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/share/nvim"  Run :checkhealth for more info

### Operating system/version

ubuntu 2204-TLS WSL2

### Steps to reproduce

`~/.local/share/lunarvim/lvim/tests/minimal_lsp.lua` couldn't been open

I thought this problem is as same as the same problem as #2787,（Also E5113）
but i trying to fixed it like what guide sad, it not work.

1. `just using the install script to install the programme`

```
jacky@LAPTOP-5ONHQ6PL:~/os/rCore-Tutorial-v3/os$ bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

      88\                                                   88\
      88 |                                                  \__|
      88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
      88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
      88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
      88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
      88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
      \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|

--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) :
--------------------------------------------------------------------------------
Would you like to install LunarVim's Python dependencies?
[y]es or [n]o (default: no) :
--------------------------------------------------------------------------------
Would you like to install LunarVim's Rust dependencies?
[y]es or [n]o (default: no) :
--------------------------------------------------------------------------------
Backing up old /home/jacky/.config/lvim to /home/jacky/.config/lvim.old

Number of files: 3 (reg: 2, dir: 1)
Number of created files: 0
Number of deleted files: 0
Number of regular files transferred: 1
Total file size: 6.31K bytes
Total transferred file size: 0 bytes
Literal data: 0 bytes
Matched data: 0 bytes
File list size: 0
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 146
Total bytes received: 35

sent 146 bytes  received 35 bytes  362.00 bytes/sec
total size is 6.31K  speedup is 35.69
--------------------------------------------------------------------------------
Backup operation complete
--------------------------------------------------------------------------------
Removing old installation files
--------------------------------------------------------------------------------
Cloning LunarVim configuration
Cloning into '/home/jacky/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 147, done.
remote: Counting objects: 100% (147/147), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 147 (delta 6), reused 58 (delta 6), pack-reused 0
Receiving objects: 100% (147/147), 120.13 KiB | 427.00 KiB/s, done.
Resolving deltas: 100% (6/6), done.
--------------------------------------------------------------------------------
Installing LunarVim shim
make: Entering directory '/home/jacky/.local/share/lunarvim/lvim'
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: /home/jacky/.local/bin/lvim
make: Leaving directory '/home/jacky/.local/share/lunarvim/lvim'
Preparing Packer setup
Error detected while processing /home/jacky/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: vim/_init_packages.lua:0: module 'vim.diagnostic' not found:
        no field package.preload['vim.diagnostic']
        no file './vim/diagnostic.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/diagnostic.lua'
        no file '/usr/local/share/lua/5.1/vim/diagnostic.lua'
        no file '/usr/local/share/lua/5.1/vim/diagnostic/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/diagnostic.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/diagnostic/init.lua'
        no file './vim/diagnostic.so'
        no file '/usr/local/lib/lua/5.1/vim/diagnostic.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim/diagnostic.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './vim.so'
        no file '/usr/local/lib/lua/5.1/vim.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        vim/_init_packages.lua: in function '__index'
        ...y/.local/share/lunarvim/lvim/lua/lvim/core/which-key.lua:165: in function 'config'
        ...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:24: in function 'config'
        ...acky/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:21: in function 'init'
        .../jacky/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:110: in function 'init'
        /home/jacky/.local/share/lunarvim/lvim/init.lua:8: in main chunk
E484: Can't open file /share/nvim/syntax/syntax.vimError detected while processing command line:
E492: Not an editor command: PackerSync
```

### support info

BC even when i using `/home/jacky/.local/bin/lvim` to open lvim it still show the view of neovim, thus i couldn't giving anykind of information on it. 

### Screenshots

the image which i has using `/home/jacky/.local/bin/lvim` as what install script say.

![image](https://user-images.githubusercontent.com/50787361/178630083-e41fd7af-38b4-46cb-942d-2d157eb385ad.png)
before i enter it
![image](https://user-images.githubusercontent.com/50787361/178630158-2d000f0f-d482-482f-84f6-1b3d7660811e.png)
all kinds of command for lunarvim couldn't been use, basical as same as neovim

**Comment by rebuilt** [comment]
It looks like the installer successfully cloned the LunarVim github repo to the right place.  That's a good sign.  But it seems like there's was a problem during the plugin installation step.

Can you open LunarVim with `/home/jacky/.local/bin/lvim` and run `:PackerSync` please?

**Comment by jackyliu16** [comment]
sorry about that, i show there is no a edit command call :PackerSync
![image](https://user-images.githubusercontent.com/50787361/178647964-a37568d6-96a2-499f-b66b-358dcc7b4f8b.png)

by the ways, the first error information has disappeared ( before i restart my computer，after i restart it show again）
and i have check the other error information
this two error information was correct [
    there is nothing under `/share/` and even this dir not exist _( i have trying to mkdir it by myself but it not work )_
    originally the location of `~/.local/share/lunarvim/lvim/` is not exist，but after i `chmod 777` this location and reinstall lunarvim, _it seem fixed_
]
thus, i have been thinking about the Issues with the WSL permission management mechanism? which I've had similar access issues in installing another programe

**Comment by rebuilt** [comment]
Do you have all the prerequisites installed?  https://www.lunarvim.org/01-installing.html#prerequisites
Specifically, I want to make sure you have git installed.

**Comment by jackyliu16** [comment]
@rebuilt sorry about that i only see your comment on the mail github sent to me, here is my reply.

i have check all prerequisites in `Have , , , , and installed on your system. git make pip npm node cargo`
when i was checking npm and node haven't been installing, but before i installing it, the situation is not improving

**Comment by innerout** [comment]
I ran to the same error recently. Please check the installed git version on your computer. Also, check if you have multiple installations of neovim as this could break your lunarvim installation.

**Comment by jackyliu16** [comment]
emm，my git version is `git version 2.34.1` which is the lastest verison ubuntu provide ...

You mentioned the neovim problem, i was worry about the lastest version of neovim is download by myself will affect the situation. (ubuntu only provide 0.6）

this is my installation procedure:
1. `wget https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-linux64.tar.gz`
the tar.gz package in `https://github.com/neovim/neovim/releases/tag/v0.7.2`
2. `tar xzvf nvim-linux64.tar.gz`
3. putting `./nvim-linux64/bin/nvim` into `/usr/local/bin`

**Comment by jasoneveleth** [comment]
I have the exact same error (MacOS 14" M1 Pro). The configuration files must be messed up since the `PackerSync` command is defined in [this file in Packer](https://github.com/wbthomason/packer.nvim/blob/master/lua/packer.lua) but that file isn't listed when I run `:scriptnames`.

**Comment by jasoneveleth** [comment]
[this comment](https://github.com/LunarVim/LunarVim/issues/2479#issuecomment-1100602061) got me to a different error (and I think it's progress)

**Comment by jasoneveleth** [comment]
Yup, continuing along that line 
```bash
cd ~/.local/share/lunarvim/site/pack/packer/start/packer.nvim
git checkout master && git pull
```
and 
```bash
cd ~/.local/share/lunarvim/site/pack/packer/start/nvim-lsp-installer
git checkout main && git pull
```
Then I was finally able to run `:PackerSync`. That solved the problem for me.

**Comment by rebuilt** [comment]
@jasoneveleth Were you updating or installing fresh?

**Comment by BMilliet** [comment]
Im also facing this problem on a fresh install using linux arm64.
In my case the directory `~/.local/share/lunarvim/site/pack/packer/start/packer.nvim` is not there yet when the script fails.
I tried to clone Packer directly to this location:
`git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/lunarvim/site/pack/packer/start/packer.nvim` and run the installer again, still same error `Not an editor command: PackerSync`.

**Comment by jackyliu16** [comment]
It looks like I don't have directory `~/.local/share/lunarvim/site/pack/packer/start/nvim-lsp-installer` yet

**Comment by jasoneveleth** [comment]
@BMiliet @jackyliu16 I can't remember if I had installed it before, or installing fresh (I was curling and running the bash script). Can you open `lvim` and run: `:echo &runtimepath` to see where nvim is looking for things, and run `:scriptnames` to make sure lvim's init.lua is run? Also copy and paste the output from the install script

**Comment by BMilliet** [comment]
the lvim executable is not defined yet but i can call it directly `.local/bin/lvim` the out put is a log error:
```
Error detected while processing /home/tofu/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: Vim:E6100: "log" is not a valid stdpath
stack traceback:
        [C]: in function 'stdpath'
        /usr/local/share/nvim/runtime/lua/vim/lsp/log.lua:28: in main chunk
        [C]: in function 'require'
        /usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:1: in main chunk
        [C]: in function 'require'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1: in main chunk
        [C]: in function 'require'
        vim/_init_packages.lua: in function '__index'
        ...u/.local/share/lunarvim/lvim/lua/lvim/core/which-key.lua:172: in function 'config'
        ...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:24: in function 'config'
        ...tofu/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:21: in function 'init'
        ...e/tofu/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:110: in function 'init'
        /home/tofu/.local/share/lunarvim/lvim/init.lua:8: in main chunk
```
The neovim home shows up and the output to the commands are:
`:echo &runtimepath`
```
/home/tofu/.config/lvim,/home/tofu/.local/share/lunarvim/site,/home/tofu/.local/share/lunarvim/site/pack/*/start/*,/etc/xdg/nvim,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/local/share/nvim/runti
me,/usr/local/share/nvim/runtime/pack/dist/opt/matchit,/usr/local/lib/nvim,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/etc/xdg/nvim/after,/home/tofu/.local/share/lunarvim/lvim,/home/tofu/
.local/share/lunarvim/site/after,/home/tofu/.config/lvim/after
```
and `:scriptnames`
```
  1: /usr/local/share/nvim/runtime/ftplugin.vim
  2: /usr/local/share/nvim/runtime/indent.vim
  3: ~/.local/share/lunarvim/lvim/init.lua
  4: /usr/local/share/nvim/runtime/filetype.lua
  5: /usr/local/share/nvim/runtime/filetype.vim
  6: ~/.local/share/lunarvim/lvim/ftdetect/json.lua
  7: ~/.local/share/lunarvim/lvim/ftdetect/plaintex.lua
  8: ~/.local/share/lunarvim/lvim/ftdetect/zig.lua
  9: /usr/local/share/nvim/runtime/syntax/syntax.vim
 10: /usr/local/share/nvim/runtime/syntax/synload.vim
 11: /usr/local/share/nvim/runtime/plugin/gzip.vim
 12: /usr/local/share/nvim/runtime/plugin/health.vim
 13: /usr/local/share/nvim/runtime/plugin/man.vim
 14: /usr/local/share/nvim/runtime/plugin/matchit.vim
 15: /usr/local/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
 16: /usr/local/share/nvim/runtime/plugin/matchparen.vim
 17: /usr/local/share/nvim/runtime/plugin/netrwPlugin.vim
 18: /usr/local/share/nvim/runtime/plugin/rplugin.vim
 19: /usr/local/share/nvim/runtime/plugin/shada.vim
 20: /usr/local/share/nvim/runtime/plugin/spellfile.vim
 21: /usr/local/share/nvim/runtime/plugin/tarPlugin.vim
 22: /usr/local/share/nvim/runtime/plugin/tohtml.vim
 23: /usr/local/share/nvim/runtime/plugin/tutor.vim
 24: /usr/local/share/nvim/runtime/plugin/zipPlugin.vim
```

**Comment by jackyliu16** [comment]
@jasoneveleth this is **ouput before using lvim** 

![image](https://user-images.githubusercontent.com/50787361/179134045-729bdaef-1cd0-4479-baaa-6ad91486e162.png)

**and then i run `:echo &runtimepath`**

```
/home/jacky/.config/lvim,/home/jacky/.local/share/lunarvim/site,/home/jacky/.local/share/lunarvim/site/pack/*/start/*,/etc/xdg/nvim,/usr/local/share/nvim/site,/usr/share/nvim/site,/var/lib/snapd/desktop/nvim/site,/share/nvim,/usr/local/lib/nvim,/var/lib/snapd/desktop/nvim/site/after,/usr
/share/nvim/site/after,/usr/local/share/nvim/site/after,/etc/xdg/nvim/after,/home/jacky/.local/share/lunarvim/lvim,/home/jacky/.local/share/luna
rvim/site/after,/home/jacky/.config/lvim/after
```

**the output when i using `:scriptnames`**
![image](https://user-images.githubusercontent.com/50787361/179134218-f4760442-bee4-4e95-b5ff-fb82ee33fc63.png)

**copy and paste the output from the install script**
> sorry about that, i don't understand what are you talking about exactly.
>
> do you means i run the install script again and copy & paste it's output information ?
> if you means that, my output information are as follow:

```
jacky@LAPTOP-5ONHQ6PL:~$ bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

      88\                                                   88\
      88 |                                                  \__|
      88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
      88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
      88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
      88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
      88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
      \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|

--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) :
--------------------------------------------------------------------------------
Would you like to install LunarVim's Python dependencies?
[y]es or [n]o (default: no) :
--------------------------------------------------------------------------------
Would you like to install LunarVim's Rust dependencies?
[y]es or [n]o (default: no) :
--------------------------------------------------------------------------------
Backing up old /home/jacky/.config/lvim to /home/jacky/.config/lvim.old

Number of files: 3 (reg: 2, dir: 1)
Number of created files: 0
Number of deleted files: 0
Number of regular files transferred: 2
Total file size: 6.31K bytes
Total transferred file size: 6.31K bytes
Literal data: 6.31K bytes
Matched data: 0 bytes
File list size: 0
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 6.49K
Total bytes received: 54

sent 6.49K bytes  received 54 bytes  13.09K bytes/sec
total size is 6.31K  speedup is 0.96
--------------------------------------------------------------------------------
Backup operation complete
--------------------------------------------------------------------------------
Removing old installation files
--------------------------------------------------------------------------------
Cloning LunarVim configuration
Cloning into '/home/jacky/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 147, done.
remote: Counting objects: 100% (147/147), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 147 (delta 6), reused 58 (delta 6), pack-reused 0
Receiving objects: 100% (147/147), 120.13 KiB | 307.00 KiB/s, done.
Resolving deltas: 100% (6/6), done.
--------------------------------------------------------------------------------
Installing LunarVim shim
make: Entering directory '/home/jacky/.local/share/lunarvim/lvim'
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: /home/jacky/.local/bin/lvim
make: Leaving directory '/home/jacky/.local/share/lunarvim/lvim'
Preparing Packer setup
Error detected while processing /home/jacky/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: vim/_init_packages.lua:0: module 'vim.diagnostic' not found:
        no field package.preload['vim.diagnostic']
        no file './vim/diagnostic.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/diagnostic.lua'
        no file '/usr/local/share/lua/5.1/vim/diagnostic.lua'
        no file '/usr/local/share/lua/5.1/vim/diagnostic/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/diagnostic.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/diagnostic/init.lua'
        no file './vim/diagnostic.so'
        no file '/usr/local/lib/lua/5.1/vim/diagnostic.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim/diagnostic.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './vim.so'
        no file '/usr/local/lib/lua/5.1/vim.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        vim/_init_packages.lua: in function '__index'
        ...y/.local/share/lunarvim/lvim/lua/lvim/core/which-key.lua:165: in function 'config'
        ...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:24: in function 'config'
        ...acky/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:21: in function 'init'
        .../jacky/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:110: in function 'init'
        /home/jacky/.local/share/lunarvim/lvim/init.lua:8: in main chunk
E484: Can't open file /share/nvim/syntax/syntax.vimError detected while processing command line:
E492: Not an editor command: PackerSync
```

**Comment by rebuilt** [comment]
A lot of people are chiming in to this thread so I'll put some general advice here: 

Make sure you run the installer from the home directory.  Make sure you DO NO run the script with `sudo` privilages.

The error complaining about not finding `vim.diagnostic` is something we've seen [before](https://github.com/LunarVim/LunarVim/issues/2622) and likely means you're launching with an older version of neovim than 0.7.2.  [another issue](https://github.com/LunarVim/LunarVim/issues/2590)
Make sure LunarVim is starting with the correct version of neovim.  If you have two versions of neovim installed, it could be launching with the wrong one.  
You can also open `~/.local/bin/lvim` and change which version of nvim you're using, e.g `/usr/local/bin/nvim`.

Make sure your version of neovim was compiles with luajit `nvim -vv`

Make sure you have the latest versions of the prerequisites installed.  https://www.lunarvim.org/01-installing.html#prerequisites
Older versions, expecially older versions of node, cause problems.

Ensure the installer successfully creates the `~/.local/share/lunarvim/lvim` folder and clones the lunarvim github files there

and finally run `:LvimSyncCorePlugins` to make sure all plugins are synced

To retry the installation, run `bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh` to get a clean start.  Make sure you've backed up any configuration files you've created in `~/.config/lvim`.  And then run the installer again.

**Comment by BMilliet** [comment]
I got it working thanks for the tip @rebuilt
For me the problem was i compiled neovim from source by running:
```bash
make CMAKE_BUILD_TYPE=Release
```
From there i just made the PATH to nvim executable and stopped there, but neovim complete install actually installs more things and those were missing for lunar.
So the complete install is needed:
```bash
make CMAKE_BUILD_TYPE=Release
sudo make install
```

**Comment by jackyliu16** [comment]
@rebuilt sorry about that, but i have even trying to using the latest pre-release to run this program, but it just can't work with a same error information.

**Comment by rebuilt** [comment]
When you installed the newer versions of neovim, did you remove the older ones?   Did you confirm you were running the newest installed version?

**Comment by jackyliu16** [comment]
Thank you very much, my problem has been solved after I installed neovim correctly, according to the information jointly provided by jasoneveleth and BMilliet 

> i have find a question in my procedure ( which i install neovim in a wrong ways, i copy the executable file to PATH but not using ln-s to link it )

> and i can using `:scriptnames`, this is the output 
```
:scriptnames
  1: ~/Downloads/nvim-linux64/share/nvim/runtime/ftplugin.vim
  2: ~/Downloads/nvim-linux64/share/nvim/runtime/indent.vim
  3: ~/.local/share/lunarvim/lvim/init.lua
  4: ~/Downloads/nvim-linux64/share/nvim/runtime/filetype.lua
  5: ~/.local/share/lunarvim/lvim/ftdetect/json.lua
  6: ~/.local/share/lunarvim/lvim/ftdetect/plaintex.lua
  7: ~/.local/share/lunarvim/lvim/ftdetect/zig.lua
  8: ~/Downloads/nvim-linux64/share/nvim/runtime/filetype.vim
  9: ~/Downloads/nvim-linux64/share/nvim/runtime/syntax/syntax.vim
 10: ~/Downloads/nvim-linux64/share/nvim/runtime/syntax/synload.vim
 11: ~/Downloads/nvim-linux64/share/nvim/runtime/plugin/gzip.vim
 12: ~/Downloads/nvim-linux64/share/nvim/runtime/plugin/health.vim
 13: ~/Downloads/nvim-linux64/share/nvim/runtime/plugin/man.vim
 14: ~/Downloads/nvim-linux64/share/nvim/runtime/plugin/matchit.vim
 15: ~/Downloads/nvim-linux64/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
 16: ~/Downloads/nvim-linux64/share/nvim/runtime/plugin/matchparen.vim
 17: ~/Downloads/nvim-linux64/share/nvim/runtime/plugin/netrwPlugin.vim
 18: ~/Downloads/nvim-linux64/share/nvim/runtime/plugin/rplugin.vim
 19: ~/Downloads/nvim-linux64/share/nvim/runtime/plugin/shada.vim
 20: ~/Downloads/nvim-linux64/share/nvim/runtime/plugin/spellfile.vim
 21: ~/Downloads/nvim-linux64/share/nvim/runtime/plugin/tarPlugin.vim
 22: ~/Downloads/nvim-linux64/share/nvim/runtime/plugin/tohtml.vim
 23: ~/Downloads/nvim-linux64/share/nvim/runtime/plugin/tutor.vim
 24: ~/Downloads/nvim-linux64/share/nvim/runtime/plugin/zipPlugin.vim
 25: ~/Downloads/nvim-linux64/share/nvim/runtime/autoload/provider/clipboard.vim
```

**Comment by kylo252** [comment]
This problem is tricky to fix, because the installer is already validating that neovim version is at least `0.7`, but this is not sufficient for prerelease builds, that may have come out just before 0.7 has officially released, and therefore not having all the features. 

The general consensus from neovim-core is that it's the user responsibility to update their installation correctly if they have switched to nightly at any point 🤔

---

Feel free to open a PR to add more checks to the installer, e.g. disallow any nightly build still 0n `0.7`

```diff
diff --git a/utils/installer/install.sh b/utils/installer/install.sh
index dc342d1..50fcde8 100755
--- a/utils/installer/install.sh
+++ b/utils/installer/install.sh
@@ -206,6 +206,13 @@ function check_neovim_min_version() {
     echo "[ERROR]: LunarVim requires at least Neovim v0.7 or higher"
     exit 1
   fi
+
+  local is_outdated_nightly='if v:lua.vim.version().minor == 7 && v:lua.vim.version().prerelease | cquit | else | quit | endif'
+  # exit with an error if min_version not found
+  if ! nvim --headless -u NONE -c "$is_outdated_nightly"; then
+    echo "[ERROR]: LunarVim requires at least Neovim v0.7 or higher, outdated nightly version detected"
+    exit 1
+  fi
 }
```

**Comment by innerout** [comment]
I just wanted to mention also this error occurs even if you have the latest version of neovim (not prebuilt). This is because, in some systems, neovim expects to find `syntax.vim` in the /share path, which does not always exist. This occurs explicitly with the 0.7.2 release. So in case you encounter this, download the latest nightly release. This is a temporary workaround!

**Comment by JayFarei** [comment]
> I ran to the same error recently. Please check the installed git version on your computer. Also, check if you have multiple installations of neovim as this could break your lunarvim installation.

Had the same issue, upgrade git version was the solution for me
