### ISSUE TITLE
[Feature] New session management as there is non in alpha.

### ISSUE THREAD

**Issue by aniketgm** [LunarVim/LunarVim#2820]
### Feature Description

Since, LunarVim is now moved to alpha for dashboard display. It seems there is no session management in alpha. [alpha-nvim](https://github.com/goolord/alpha-nvim), suggests a session manager in it's Readme. However, I've been using [auto-session](https://github.com/rmagatti/auto-session) and I think it's a good option. It also has telescope integration -- [session-lens](https://github.com/rmagatti/session-lens).

How about adding it into LunarVim. Or if there are any other of your favorites that are good, that would be cool too. What are your thoughts ? @ChristianChiarulli and others.

**Comment by kobzar** [comment]
This is good idea
@ChristianChiarulli 

Please, remove 
https://github.com/Pocco81/AutoSave.nvim
https://github.com/ethanholz/nvim-lastplace
From external plugin list and add this one to Core plugins with simle settings like
```
lvim.builtin.save_session.enable = true/false
lvim.builtin.save_session.config = {
    sessionoptions="blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal"
}
```
LV is IDE - not just the editor. IDE must have this option for comfortable work.

**Comment by pidgeon777** [comment]
@kobzar why removing nvim-lastplace? Just curious.

**Comment by aniketgm** [comment]
@pidgeon777 In addition to session management, auto-session will also do what nvim-lastplace does.
@kobzar Although, I'm curious, how come I don't see AutoSave and nvim-lastplace in my LunarVim setup. Even my :PackerStatus doesn't show it was ever installed. I have NVIM 0.8.0-dev-nightly. You sure it comes with LunarVim main installation ? Does it come with some LunarVim branch version ?

**Comment by kobzar** [comment]
2 @aniketgm 
https://www.lunarvim.org/plugins/02-extra-plugins.html#navigation-plugins

2 @pidgeon777 
Compare this plugins and you find that the last much better the both of we have now, and core plugins make our results config more clear and user friendly if we speak about standard IDE tools. 
editor can be with any presets. But ide - must have debugger, code runner and workplace state as ide descr.

**Comment by aniketgm** [comment]
Oh, the one's in the extra plugins. Since it's not in the core, not everyone would be using it. some might be using say 'persistence' instead. I think no need to remove them or anything from docs. So if say anyone who doesn't want to use auto-session should have an option with something like below (default value would be true) and use anything (say even AutoSave or anything) if they wish.
```
lvim.builtin.auto_session.enable = false
```

But yeah, I agree with the point that as an IDE, some default session management system should be provided.

**Comment by kobzar** [comment]
So, what are I can say after week of this plugin use?
This is perfect.
My own config
```
-- Autosession
vim.opt.sessionoptions = "blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal"

-- Plugins ...
	-- Reopen files with saved work
	{
		"rmagatti/auto-session",
		config = function()
			require("auto-session").setup({
				log_level = "info",
				auto_session_enable_last_session = true,
				auto_session_root_dir = vim.fn.stdpath("data") .. "/sessions/",
				auto_session_enabled = true,
				auto_save_enabled = true,
				auto_restore_enabled = true,
				-- auto_session_suppress_dirs = { "~/", "~/Projects" },
				auto_session_suppress_dirs = nil,
				auto_session_use_git_branch = nil,
			})
		end,
	},

```

**Comment by lvimuser** [comment]
Related
https://old.reddit.com/r/neovim/comments/szis80/which_session_manager_for_nvim/hy5z83g/

I personally don't like auto session much and would prefer to have persistence integrated with `project.nvim`. But that's blocked by https://github.com/ahmedkhalf/project.nvim/pull/77.

> @pidgeon777 In addition to session management, auto-session will also do what nvim-lastplace does.

Well, I haven't tried auto session, but for 'persistence' for example and other plugins, they do not do what lastplace does.

Lastplace remembers across multiple files/workspaces/sessions.
If you restore a session, does it remember last viewed/edited place for all the files?

**Comment by aniketgm** [comment]
It seems there is no plan to add any session manager plugin to the default LunarVim plugins by Chris or any other contributors. However, a user can add any of the session manager out there that they like, since customization in LunarVim is possible. Hence closing...
