### ISSUE TITLE
Fedora

### ISSUE THREAD

**Issue by AstroMoon** [LunarVim/LunarVim#2822]
### Problem description

Error detected while processing home/fedora/.config/nvim/init.lua:

E5113: Error while calling lua chunk:
  /home/fedora/.config/nvim/init.lua:1:
  module 'user.options' not found:

	no field package.preload['user.options']
	no file './user/options.lua'
	no file '/build/nvim/parts/nvim/buiild/.deps/usr/share/luajit-2.1.0-beta3/user/options.lua'
	no file '/usr/local/share/lua/5.1/user/options.lua'
	no file '/usr/local/share/lua/5.1/user/options/init.lua'
	no file '/build/nvim/parts/nvim/build/.deps/usr/share/lua/5.1/user/options.lua'
	no file '/build/nvim/parts/nvim/build/.deps/usr/share/lua/5.1/user/options/init.lua'
	no file './user/options.so'
	no file '/usr/local/lib/lua/5.1/user/options.so'
	no file '/build/nvim/parts/nvim/build./deps/usr/lib/lua/5.1/user/options.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './user.so'
	no file '/usr/local/lib/lua/5.1/user.so'
	no file '/build/nvim/parts/nvim/build/.deps/usr/lib/lua/5.1/user.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

stack traceback:

	[C]: in function 'require'
	/home/fedora/.config/nvim/init.lua:1: in main chunk

### LunarVim version

LuaJIT 2.1.0-beta3

### Neovim version (>= 0.7.2)

NVIM v0.7.0

### Operating system/version

Fedora 36

### support info

/usr/local/

./user/options/

???

**Comment by rebuilt** [comment]
First make sure to upgrade your version of neovim

**Comment by kylo252** [comment]
As mentioned, please upgrade your neovim version, and then fully re-install lunarvim. Please let me know if that doesn't fix it.
