### ISSUE TITLE
LvimCacheReset on first time startup to recognize config.lua on startup

### ISSUE THREAD

**Issue by susonwaiba** [LunarVim/LunarVim#2824]
### Problem description

Before the first time startup,
if `~/.config/lvim/config.lua`  is updated
then
on first time startup, lvim should recognize changes.

### LunarVim version

master-b04aefb

### Neovim version (>= 0.7.2)

v0.7.2

### Operating system/version

Linux sws 5.15.53-1-MANJARO, x86_64 GNU/Linux, i3

### Steps to reproduce

1. setup lunar vim
2. update `~/.config/lvim/config.lua`
3. lvim (starting for the first time, installing treesitter, completed)
4. close lvim
5. reopen lvim
6. config.lua is not recognized on first time startup like skipped_servers

sample config at https://gist.github.com/susonwaiba/ec941e8f081106e01bebb2f3b4196cad

### support info

But manually running `:LvimCacheReset` fixes issue.

Everything else is default

**Comment by kylo252** [comment]
it states right there in the example that `LvimCacheReset` is required

https://github.com/LunarVim/LunarVim/blob/9caa457810a26369f848d4f90f6e0ec84e0048e0/utils/installer/config.example.lua#L104

see https://github.com/LunarVim/LunarVim/pull/2243 for more info on the changes
