### ISSUE TITLE
Unable to verify plugins, when starting lvim for the first time

### ISSUE THREAD

**Issue by mrLuisFer** [LunarVim/LunarVim#2825]
### Problem description

Running the bash script installer, when its **Verifying for core plugins** it shows me the following error:
`[ERROR]: Unable to verify plugins, makde sure to manually run ':PackerSync' when starting lvim for the first time.`
The error is displayed only when Bash script is executed

Even installing the dependencies or using `--no-install-dependencies`

### LunarVim version

1.1.3

### Neovim version (>= 0.7.2)

NVIM v0.8.0-dev

### Operating system/version

Pop!_OS 22.04 LTS x86_64 

### Steps to reproduce

1. Just running: `bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`

### support info

```console
E492: Not an editor command: LspInfo
```

```console
E492: Not an editor command: LvimInfo
```

### Screenshots

![Screenshot error](https://user-images.githubusercontent.com/65029792/179414626-0be0971c-2647-46cf-96d4-e5db9218f560.png)

**Comment by kylo252** [comment]
you probably don't have `$HOME/.local/bin` in your `$PATH`, or have configured some old alias that isn't valid anymore.

**Comment by mrLuisFer** [comment]
oh you are right i have commented this line in my `.bashrc` uncommented it and it works, thanks 😄

**Comment by Augusto-Fadanelli** [comment]
Hi, I was having the same error on Arch Linux. I got the output of `$PATH` which was 
> /usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

Just wrote in `~/.bashrc `
> /usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/$USER/.local/bin

 adding `:/home/$USER/.local/bin` to the end and it worked.
