### ISSUE TITLE
Install Errors: Directory not found in 'packpath' on Manjaro

### ISSUE THREAD

**Issue by dachrillz** [LunarVim/LunarVim#2832]
### Problem description

Hello all!

I wanted to try out Lunar Vim but failed running the install script. The output looks as follows,

```
--------------------------------------------------------------------------------
Installing LunarVim shim
make: Entering directory '/home/dachrillz/.local/share/lunarvim/lvim'
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: /home/dachrillz/.local/bin/lvim
make: Leaving directory '/home/dachrillz/.local/share/lunarvim/lvim'
Preparing Packer setup
Error detected while processing /home/dachrillz/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: ...lz/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:41: Vim(packadd):E919: Directory not found in 'packpath': "pack/*/opt/packer.nvim"
stack traceback:
	[C]: in function 'cmd'
	...lz/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:41: in function 'init'
	...hrillz/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:112: in function 'init'
	/home/dachrillz/.local/share/lunarvim/lvim/init.lua:8: in main chunkError detected while processing command line:
E492: Not an editor command: PackerSync

```

I tried this using both the nvim installed via pacman, as well as 
```
bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/rolling/utils/installer/install-neovim-from-release)
```

I figured I could open an issue in case anyone is running into similiar issues. 

All the best

### LunarVim version

stable as of 20th July 2022 ([1.1.3](https://github.com/LunarVim/LunarVim/releases/tag/1.1.3) I think)

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Manjaro

### Steps to reproduce

Simply run,
```
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
```

### support info

not applicable

**Comment by zZer0o** [comment]
encounter the same issue before on CENTOS 6.3. Rerun the "install.sh" multiple times helps. So no more information I can give. Seems like a network issue.

**Comment by kylo252** [comment]
is this still an issue? please try downloading the script first instead of piping it into bash

**Comment by dachrillz** [comment]
This seems to still be an issue. I tried downloading the script directly and ran it with both bash and zsh. I get the same error.

Sadly, I have not debugged this in depth, but could it be that I have a partial install that is broken somehow?

**Comment by kylo252** [comment]
> Sadly, I have not debugged this in depth, but could it be that I have a partial install that is broken somehow?

you should run https://github.com/LunarVim/LunarVim/blob/rolling/utils/installer/uninstall.sh or clean the folders manually.

**Comment by zZer0o** [comment]
When I tried others neovim configs, the same error message shows once before. So I think the problem was caused by the packer extension with some weird network issues.
Maybe you can try to use a Github Mirror, just set
`git config --global url."https://the-mirror-URL".insteadOf "https://github.com/"`
then check whether the Github Mirror works properly.
At the end, run the "install.sh".

**Comment by kylo252** [comment]
Please let me know if you're still facing an issue with this.
