### ISSUE TITLE
Colors on macOS

### ISSUE THREAD

**Issue by Dmole** [LunarVim/LunarVim#2849]
### Problem description

Colors are broken. Just look at this odd green in the attached screenshot.

and when files are open syntax coloring is absent in lvim but working in nvim.

I think other things are broken but let's just start with the colors.

### LunarVim version

master-b04aefb

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

macOS 12.5

### Steps to reproduce

lvim

### support info

```
:LvimInfo

Error executing Lua callback: vim/shared.lua:0: t: expected table, got nil
stack traceback:                                                                                                                              
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function <vim/shared.lua:0>
        vim/shared.lua: in function 'tbl_filter'
        .../.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info'
        .../.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'
        ....local/share/lunarvim/lvim/lua/lvim/core/commands.lua:29: in function <.../.local/share/lunarvim/lvim/lua/lvim/core/commands.lu
a:28>

```

### Screenshots

![Screen Shot 2022-07-24 at 2 59 43 PM](https://user-images.githubusercontent.com/1793802/180662067-6745feb4-9196-4bba-b7fe-ddb57bba2804.png)

**Comment by cpea2506** [comment]
I'm assuming that you are using default mac's terminal which only display 16 term colors. You can follow this step to see if it can make difference: <https://gist.github.com/shawnbot/3277580> 

Alternatively, you can change to another terminal which support 256 term color: `Iterm2`, `Alacritty`, `Kitty`,...

**Comment by Dmole** [comment]
> I'm assuming that you are using default mac's terminal

Yes

> which only display 16 term colors. You can follow this step to see if it can make difference: https://gist.github.com/shawnbot/3277580

I think it has defaulted to 256 for a long time. anyway

    echo "$TERM"
    xterm-256color


> Alternatively, you can change to another terminal which support 256 term colors: `Iterm2`, `Alacritty`, `Kitty`,...

I don't think that's the issue due this:

> coloring is absent in lvim but working in nvim.

and this:

> vim/shared.lua:0: t: expected table, got nil

but I [tested colors](https://askubuntu.com/a/821163) anyway and they work fine:

![Screen Shot 2022-07-25 at 6 00 05 AM(1)](https://user-images.githubusercontent.com/1793802/180752182-d7d34a58-a4e3-4697-89f2-aeeca446cc61.png)

lvim colors do work in kitty so that's a workaround, but there is something about how lvim is not using the terminal properly.

Using the MacOS terminal

    export TERM=xterm-kitty
    export TERMINFO=/Applications/kitty.app/Contents/Resources/kitty/terminfo

will remove the green but still lvim colors are not working in MacOS terminal which I think they should.

**Comment by susonwaiba** [comment]
I am also using macOS default terminal and same issue here. using tmux or iterm2 fixes the issue for now.

**Comment by kobzar** [comment]
This is old question
LunarVim doesn't work correctly in osX default terminal.app
Because it don't support true colours in 2022.
Use  modern app for modern solutions.
"Alternatively, you can change to another terminal which support 256 term colors: Iterm2, Alacritty, Kitty,..."
You can close the issue.

**Comment by Dmole** [comment]
kobzar, either you did not read my previous comment or did not go into enough technical detail to explain why 256 colors appears to be supported but is somehow not enough for lunarvim;

Please explain how I was able to print 256 term colors in terminal.app if they are not supported?
What makes color work in neovim but not lunarvim?

**Comment by cpea2506** [comment]
Okay. Now it make more sense with this issue in neovim. 

https://github.com/neovim/neovim/issues/11327#issuecomment-710761229

**Comment by Dmole** [comment]
Thanks for the link cpea2506,

I see so lunarvim wants 24-bit colors which is "16777216 term colors" (not "256 term colors").

I wonder if the single if statement workaround can be applied to LunarVim...

**Comment by Dmole** [comment]
:set notermguicolors

turned off all colors but

    tmux new -s lvim lvim

works...why does lvim need to be wrapped in tmux to work in Terminal.app?

**Comment by opalmay** [comment]
> ```
> :set notermguicolors
> ```
> 
> turned off all colors but
> 
> ```
> tmux new -s lvim lvim
> ```
> 
> works so
> 
> ```
> alias l="tmux attach -t lvim || tmux new -s lvim lvim"
> ```
> 
> is my workaround for now.
> 
> Why does lvim need to be wrapped in tmux to work in Terminal.app?

You answered yourself in your previous comment.
Closing this...

**Comment by 0x27752357** [comment]
> not sure this should be closed? I would expect lvim to have some readibility on any terminal out of the box (e.g., parity with neovim) - is there a recommendation for having a generic config (e.g., checking env for different OSes and default terminals anywhere?)

had the same problem with macOS terminal, tmux worked fine

**Comment by cpea2506** [comment]
Sadly, until now, the Apple Terminal has not yet supported `true color (24 bit)`. If you want to use colorschemes that are provided by Neovim you can turn off `termguicolors` (`:h termguicolors`) by setting
```lua
vim.opt.termguicolors = false
```
Otherwise, you should use another terminal or run it with `tmux` as was said above.
