### ISSUE TITLE
migrate to mason.nvim

### ISSUE THREAD

**Issue by kylo252** [LunarVim/LunarVim#2850]
### Discussed in https://github.com/LunarVim/LunarVim/discussions/2848

<div type='discussions-op-text'>

<sup>Originally posted by **Aceticia** July 24, 2022</sup>
According to the post [here](https://www.reddit.com/r/neovim/comments/w6w5ij/introducing_masonnvim/?utm_source=share&utm_medium=ios_app&utm_name=iossmf), lsp-installer will no longer be maintained. Mason.nvim seems to be the canon successor to it, supporting linters, formatters, dap and lsp. Should lunarvim consider transitioning to it?</div>

**Comment by luxus** [comment]
so migration would mean breaking all configs that have custom lsp
the migration itself is not that hard:
https://github.com/williamboman/nvim-lsp-installer/discussions/876

but null-ls is still needed right?

maybe the question should be is there any reason not to switch?

**Comment by 00sapo** [comment]
> maybe the question should be is there any reason not to switch?

Is the fact that lsp-installer won't be developed any more enough?

This is not the first breaking change and I don't think that many people have custom configs for lsp-installer, since its purpose is exactly to remove the need for custom configs.

**Comment by rebuilt** [comment]
Is the the proposal to swap out lspinstaller and dapbuddy and then use the mason installer for formatters and linters?   Or is the scope just to swap out lspinstaller?

**Comment by kylo252** [comment]
we can just start with replacing lsp-installer, and see how it goes from there.

**Comment by brneor** [comment]
I would happily help test this.

**Comment by gregdan3** [comment]
Same. I am excited for this move.

**Comment by luxus** [comment]
why excited? are there any changes?

**Comment by gregdan3** [comment]
@luxus Not critical changes, but I appreciate moving the burden of dependency from my system's package manager to the tool that is actually using those dependencies. Moving my LSPs was already very satisfying; moving linters and formatters makes that even better. This would remove ~20 packages from my system for Python alone, mostly in the form of dependencies of black, isort, flake8, etc.

**Comment by kskewes** [comment]
For me it enables using DAP again after the changes with the plugin. 
Plus no doubt cleaner config versus the multiple different mechanisms used now.

**Comment by kylo252** [comment]
I think I have most of the basics ready in #2880, I hope you guys are still willing to help test it! 🧑‍🏭

**Comment by gregdan3** [comment]
What's the process for installing an lvim version aside from current master? The install @kylo252

**Comment by kylo252** [comment]
> What's the process for installing an lvim version aside from current master? @kylo252

it's pretty easy with github's CLI tool

```sh
export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"$HOME/.local/share/lunarvim"}"
cd "$LUNARVIM_RUNTIME_DIR/lvim"
gh pr checkout 2880
lvim +PackerSync
```

**Comment by brneor** [comment]
Did a quick test, fresh lunarvim install, nvim v0.7, Fedora 36.

Servers was not installed automatically, I had to manually install `lua-language-server` and `perlnavigator`. 

Lua server worked just fine but perlnavigator warns `[telescope.builtin.lsp_*]: no client attached` when I try something like seeing Document Symbols.

**Comment by brneor** [comment]
Also, the old `lvim.lsp.automatic_configuration.skipped_servers` option would still works? I'm used to make some adjustments to perlnavigator so I can use a container to provide me an 1:1 production environment.

**Comment by kylo252** [comment]
> Servers was not installed automatically, I had to manually install `lua-language-server` and `perlnavigator`.

they are installed automatically, it's just the old infamous data-race with lspconfig, so you'd need to refresh the buffer `:e`, but I'm trying to figure out a better way to handle this. 

> Also, the old `lvim.lsp.automatic_configuration.skipped_servers` option would still works?

I had forgotten to call the config function for mason, should be fixed in [LunarVim/LunarVim@`0148103` (#2880)](https://github.com/LunarVim/LunarVim/pull/2880/commits/0148103f3df5c8a5f13acf7fa650ec0afa5cf12f), otherwise that should still work, as I have no plans of dropping support for such an important feature.

**Comment by Uzaaft** [comment]
Did anyone get the `gh pr checkout` command to work? I get an 128 error when running it

**Comment by brneor** [comment]
> they are installed automatically, it's just the old infamous data-race with lspconfig, so you'd need to refresh the buffer `:e`, but I'm trying to figure out a better way to handle this.

I tried `:e` and lsp is actually being installed automatically as you said. But I still couldn't figure out why only `perlnavigator` is not working properly among all LSPs that I've tried so far.

**Comment by kylo252** [comment]
> Did anyone get the `gh pr checkout` command to work? I get an 128 error when running it

@Uzaaft, it's using this branch https://github.com/LunarVim/LunarVim/tree/mason-integration from this repo, so you should be able to just do this

```sh
git fetch --all
git switch mason-integration
```

> I tried `:e` and lsp is actually being installed automatically as you said. But I still couldn't figure out why only `perlnavigator` is not working properly among all LSPs that I've tried so far.

@brneor, are you having these issues even after [LunarVim/LunarVim@`a101f53` (#2880)](https://github.com/LunarVim/LunarVim/pull/2880/commits/a101f5350524c463f80c3def50320c4f04f3f905)?

**Comment by brneor** [comment]
> @brneor, are you having these issues even after [LunarVim/LunarVim@`a101f53` (#2880)](https://github.com/LunarVim/LunarVim/pull/2880/commits/a101f5350524c463f80c3def50320c4f04f3f905)?

Yep, same issue. Tried again in a clean environment and only `perlnavigator` is not working properly (tried Lua, Js/Ts, C, Rust and Scss files). Is there any log that I can provide?

**Comment by gregdan3** [comment]
Is there something I'm missing? I did `make uninstall` and `make install` (for good measure) on the `mason-integration` branch and ended up with the latest master installed.

**Comment by kylo252** [comment]
just merged this into rolling, please let me know if you encounter any issues!

**Comment by brneor** [comment]
@kylo252 I'm still facing the same issue with `perlnavigator` on rolling.

**Comment by kylo252** [comment]
> @kylo252 I'm still facing the same issue with `perlnavigator` on rolling.

please create a new ticket with minimal list of steps to reproduce so it's easier to track

**Comment by brneor** [comment]
@kylo252 done! If I can provide more info or help in any other way, please let me know.

**Comment by brneor** [comment]
Now that `perlnavigator` is working properly I'm noticing some issues that I'm not sure it's Lunarvim, Mason or perlnavigator fault.

I got no diagnostics, peek at definition and document symbols. As if LSP itself is not providing anything after the client attached.

**Comment by numine777** [comment]
LSP in general doesn't seem to be working for me.  I do see linters and formatters showing up, but I can tell you that python, lua, cpp, and typescriptreact thus far.  Am I missing a step here?

**Comment by brneor** [comment]
> Now that `perlnavigator` is working properly I'm noticing some issues that I'm not sure it's Lunarvim, Mason or perlnavigator fault.
> 
> I got no diagnostics, peek at definition and document symbols. As if LSP itself is not providing anything after the client attached.

Ran a `LvimCacheReset`, adjusted my container start script for perlnavigator and got everything working just fine. Currently running rolling on my development environment to test Mason on daily use.

**Comment by danielo515** [comment]
So this is my lsp config file, which is now failing and does not allow to properly start lvim, what should I change update?

```lua
local M = {}

local status_ok, nls = pcall(require, "null-ls")
if not status_ok then
  return
end

function M.config()
  local formatters = require "lvim.lsp.null-ls.formatters"
  formatters.setup {
    { name = "eslint_d" },
    { name = "stylua" },
  }

  local linters = require "lvim.lsp.null-ls.linters"
  linters.setup {
    { command = "eslint", filetypes = { "typescript", "typescriptreact" } },
  }
  local graphql_lsp_opts = {
    filetypes = { "graphql", "typescriptreact", "javascriptreact", "typescript" },
  }

  require("lvim.lsp.manager").setup("graphql", graphql_lsp_opts)
  -- require("lvim.lsp.manager").setup "marksman"
  require("lvim.lsp.manager").setup("jsonls", {
    settings = {
      json = {
        schemas = require("schemastore").json.schemas(),
        validate = { enable = true },
      },
    },
  })
  local setup_code_actions = require("lvim.lsp.null-ls.code_actions").setup
  local refactorin_opts = nls.builtins.code_actions.refactoring.with {
    filetypes = { "typescript", "javascript", "lua", "c", "cpp", "go", "python", "java", "php" },
  }
  setup_code_actions { refactorin_opts }
end

return M
```

**Comment by Uzaaft** [comment]
@danielo515  This PR is not a general-purpose support channel for all issues with the mason migration.
Please open a new discussion, or ask the discord chat for help.
