### ISSUE TITLE
Colorscheme cause an error

### ISSUE THREAD

**Issue by 00sapo** [LunarVim/LunarVim#2856]
The following two lines are causing me a bit of headaches. Apparently, everything work, but those lines make nvim output the warning error `"problems detected while loading plugins' configurations"`. Nothing bad happens, but I have this message.

https://github.com/LunarVim/LunarVim/blob/6ab3e8a73920e3d2e02e57f7dd3a1f3d8e54ee63/lua/lvim/plugin-loader.lua#L109-L111

I think there's a problem of cache, but I don't know how to delete it.

**Comment by rebuilt** [comment]
Delete the cache with `LvimCacheReset`.  

How are you setting your colorscheme in your `config.lua` file?

**Comment by 00sapo** [comment]
I tried `LvimCacheReset`, `PackageSync`, and `PackageCompile`. I also tried to `rm ~/.cache/nvim`.

Before, I was using `one-dark`, then removed it (switching to the default `onedarker`) and I started having this error. I'm now using `tokyonight`:

```
lvim.colorscheme = 'tokyonight'

lvim.plugins = {
--[...]
  { 'folke/tokyonight.nvim' }
}
```

**Comment by cpea2506** [comment]
I see that most of the time the message 

>"problems detected while loading plugins' configurations"

comes when user set colorscheme name before installing it. We should find a way to handle this case.
