### ISSUE TITLE
null-ls stops formatting after syntax error in code

### ISSUE THREAD

**Issue by simonvizzini** [LunarVim/LunarVim#2860]
### Problem description

Yesterday I switched from the stable branch to the rolling branch due to a null-ls related bug (#2855). It seems the current rolling version has another null-ls bug.

When my code contains syntax errors and format it with null-ls then I get this notification:
![image](https://user-images.githubusercontent.com/10862380/181222898-3f577be3-e5f7-4d98-8bee-46d35dbf5982.png)

After that null-ls will no longer format any file anymore. `:LspRestart` also doesn't help. I have to restart LunarVim to make formatting work again. This was working fine in the current stable version.

Relevant lunarvim null-ls config:

```
local formatters = require("lvim.lsp.null-ls.formatters")
formatters.setup({
	{
		exe = "prettierd",
		args = { "--config-precedence", "prefer-file" },
	},
	{ exe = "eslint" },
	{ exe = "stylua" },
})

lvim.format_on_save = { timeout = 10000 }

local linters = require("lvim.lsp.null-ls.linters")
linters.setup({
	{ exe = "eslint_d" },
})
```

### LunarVim version

rolling-61b3e8a

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

Arch Linux (5.18.14-arch1-1)

### Affected language servers

null-ls

### Actual behavior

Formatting a file with syntax error completely breaks null-ls formatting

### support info

```console
 Language client log: /home/simon/.cache/lvim/lsp.log
 Detected filetype:   typescript
 
 2 client(s) attached to this buffer: 
 
 Client: tsserver (id: 1, pid: 23505, bufnr: [14])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /home/simon/projects/project/packages/package-a
 	cmd:             typescript-language-server --stdio
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [14, 28])
 	filetypes:       html, javascriptreact, vue, javascript, graphql, json, handlebars, less, scss, css, yaml, typescriptreact, markdown, jsonc, typescript, lua
 	autostart:       false
 	root directory:  /home/simon/projects/project
 	cmd:             nvim
 
 1 active client(s) not attached to this buffer: 
 
 Client: tsserver (id: 3, pid: 23691, bufnr: [28])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /home/simon/projects/project/packages/package-b
 	cmd:             typescript-language-server --stdio
 
 Configured servers list: tsserver
```

```console
                         Buffer info
                         * filetype:                typescript
                         * bufnr:                   14
                         * treesitter status:       active
                         
                         Active client(s)
                         * name:                      tsserver
                         * id:                        1
                         * supported filetype(s):     [javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx]
                         * attached buffers:          14
                         * root_dir pattern:          14
                         * capabilities:              hoverProvider          | callsProvider              | documentRangeFormattingProvider
                                                      documentSymbolProvider | documentHighlightProvider  | referencesProvider
                                                      foldingRangeProvider   | documentFormattingProvider | definitionProvider
                                                      implementationProvider | workspaceSymbolProvider
                                                      typeDefinitionProvider | renameProvider
                         * name:                      tsserver
                         * id:                        3
                         * supported filetype(s):     [javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx]
                         * attached buffers:          28
                         * root_dir pattern:          28
                         * capabilities:              hoverProvider          | callsProvider              | documentRangeFormattingProvider
                                                      documentSymbolProvider | documentHighlightProvider  | referencesProvider
                                                      foldingRangeProvider   | documentFormattingProvider | definitionProvider
                                                      implementationProvider | workspaceSymbolProvider
                                                      typeDefinitionProvider | renameProvider
                         
                         Automatic LSP info
                         * Skipped servers: [angularls, cssmodules_ls, denols, ember, eslint, rome, stylelint_lsp, tailwindcss]
                         
                         Formatters info
                         * Active: prettierd  
                         * Supported: [deno_fmt, eslint, eslint_d, prettier, prettier_d_slim, prettierd, rome, rustywind]
                         
                         Linters info
                         * Active: eslint_d  
                         * Supported: [eslint, eslint_d, semgrep, tsc, xo]
                         
                         Code actions info
                         * Active: 
```

**Comment by rebuilt** [comment]
Can you confirm the following works for you:   

```
local null_ls = require("null-ls")

local sources = {

  -- Formatters
  null_ls.builtins.formatting.prettierd,
  null_ls.builtins.formatting.eslint,
  null_ls.builtins.formatting.stylua,
}

-- Enable the formatters and linters.
null_ls.register({ sources = sources })
```

Please comment out all the example code you listed above where you define formatters using `local formatters = require("lvim.lsp.null-ls.formatters")`

**Comment by simonvizzini** [comment]
I can confirm that manually setting up null-ls per your snippet works. I still get the null-ls generator error notification initially once but after that the formatting still works and no more error notification is shown. Another thing I noticed is that after the initial null-ls error is thrown formatting becomes *much* faster, like before it took 2 seconds to format a larger file but now it is almost instantaneous, feels so snappy. In the stable branch it was equally slow, when null-ls is setup the lvim way, by the way.

One more thing I noticed is that in rolling I can no longer enable null-ls debug mode via `lvim.lsp.null_ls.setup.debug = true`, the log opened with `:NullLsLog` stays empty. This also worked fine in stable branch.

The filetypes I have tried that have this issues are typescript and vue, haven't tried others yet.

**Comment by rebuilt** [comment]
@simonvizzini Can you please post any relevant output from `~/.local/state/nvim/lsp.log`  or `~/.cache/lvim/lvim.log`

@kylo252  It looks like the problem with null-ls is not limited to solargraph.

**Comment by simonvizzini** [comment]
Unfortunately lsp.log and lvim.log doesn't contain anything relevant when I reproduce the problem. I set both lvim and lsp log levels to trace and the lsp.log contains a bunch of traces and debug logs but I don't see any relevant errors or warnings.

lvim.log only contains this:
```
2022-07-27 22:18:31 [DEBUG] lvim: "Templates installation in progress" file="lua/lvim/lsp/templates.lua", line=61
2022-07-27 22:18:32 [DEBUG] lvim: "Templates installation is complete" file="lua/lvim/lsp/templates.lua", line=82
```

**Comment by kylo252** [comment]
There are a few misconceptions here
- `LspRestart` doesn't affect null-ls
- for the most part `lsp.log` wouldn't contain that much info from null-ls, instead use `NullLsLog`

you can access the setup setting to null-ls, including the log level, like this
```lua
lvim.lsp.null_ls.setup = {
  log = {
    level = "info",
  },
}
```

**Comment by benediktms** [comment]
I'm running into a similar problem when editing large (1000+ loc) typescript files. It seems that null-ls will automatically restart/fix itself after a few minutes but `:NullLsLog` does not actually return anything.

![image](https://user-images.githubusercontent.com/48836135/182609785-d4e2c24d-0e14-4f2b-b6d9-8d576124fb33.png)

it seems that setting
```lua
lvim.lsp.null_ls.setup = {
  log = {
    level = "info",
  },
}
```
does not actually set the log level correctly:

![image](https://user-images.githubusercontent.com/48836135/182610425-da34b788-eec5-45c8-92d8-35a21473c82c.png)

**Comment by benediktms** [comment]
I've tested null-la on a separate neovim config where auto formatting is handled asynchronously and it _seems_ to perform much better. Could this be related?

**Comment by kylo252** [comment]
@benediktms, is this still an issue?

**Comment by benediktms** [comment]
@kylo252 personally, I moved to `eslint_d` and `prettier_d` to solve this, so it's no longer an issue for me

**Comment by kylo252** [comment]
> For me it is still reproducible. I'm working around this issue by setting up my formatters and linters with `null-ls` directly, instead of using Lvims null-ls abstraction (via `lvim.lsp.null-ls`)

Please share the `register` snippet that you're using

**Comment by simonvizzini** [comment]
I hope this is what you mean. In my Lvim config:

```
local null_ls = require("null-ls")

local sources = {
	null_ls.builtins.formatting.prettierd,
	null_ls.builtins.formatting.eslint_d,
	null_ls.builtins.formatting.stylua,
	null_ls.builtins.diagnostics.eslint_d,
	null_ls.builtins.code_actions.eslint_d,
}

null_ls.register({ sources = sources })
```

**Comment by simonvizzini** [comment]
I have to add, I don't see the error notification anymore as in the screenshot in the OP. But null-ls formatting still stops working if I try to format a file which contains syntax errors, and it won't format just the buffer that had the syntax error but all buffers are affected.
