### ISSUE TITLE
Null-ls not formatting 

### ISSUE THREAD

**Issue by expoure** [LunarVim/LunarVim#2866]
### Problem description

When i open lvim all formaters work fine, but after some time it just stops working properly.

### LunarVim version

master-b04aefb

### Neovim version (>= 0.7)

0.7.2

### Operating system/version

archlinux

### Affected language servers

tsserver

### Steps to reproduce

https://user-images.githubusercontent.com/12136268/181601301-d5790fc9-7973-4c03-b0e0-7a7e0ed92089.mp4

### Actual behavior

When i save a file this is not formatting how it should

### support info

![image](https://user-images.githubusercontent.com/12136268/181601621-81cdef7c-7136-4d3e-b39e-69948f2f6fa3.png)

**Comment by kylo252** [comment]
should be fixed in #2865
