### ISSUE TITLE
how to enter visual block mode?

### ISSUE THREAD

**Issue by heston922** [LunarVim/LunarVim#2869]
### Problem description

I want insert something in multiple line,
how to do it in lunarvim?
thanks 

### LunarVim version

latest

### Neovim version (>= 0.7.2)

nvim 0.8.0

### Operating system/version

ubuntu 2204

### support info

abc
efg
hij
klm

test_abc
test_efg
test_hij
test_klm

**Comment by rebuilt** [comment]
It's the same as regular vim.   Starting from normal mode, press `control+v`, then use capital `I` to start insert mode.   You'll only see one line change until you finish making changes.

**Comment by heston922** [comment]
yea, I just try another VM it;s work. No idea it doesn't work with WSL. Maybe windows terminal?
Thanks a lot

> It's the same as regular vim. Starting from normal mode, press `control+v`, then use capital `I` to start insert mode. You'll only see one line change until you finish making changes.

**Comment by rebuilt** [comment]
I just tested on my instance of wsl.  It works there.  But I compiled neovim from source instead of just apt installing.  Not sure what would make the difference.

**Comment by kylo252** [comment]
please remove `ctrl+v` from the default mappings, related: https://github.com/microsoft/terminal/issues/5790

**Comment by heston922** [comment]
> please remove `ctrl+v` from the default mappings, related: [microsoft/terminal#5790](https://github.com/microsoft/terminal/issues/5790)

thanks

**Comment by MoAlyousef** [comment]
I ran into this on WSL as well. Normally <C-q> should also go into visual block mode, so I just remove the binding in the ~/.config/lvim/config.lua:
```lua
lvim.keys.normal_mode["<C-q>"] = false
```
LunarVim binds it to show the Quickfix list which I don't really need.

**Comment by im-yosu** [comment]
> I ran into this on WSL as well. Normally should also go into visual block mode, so I just remove the binding in the ~/.config/lvim/config.lua:
> 
> ```lua
> lvim.keys.normal_mode["<C-q>"] = false
> ```
> 
> LunarVim binds it to show the Quickfix list which I don't really need.

You don't have to. You can delete the reference to `ctrl + v` in settings.json for your Windows terminal.

**Comment by msdone-lwt** [comment]
In WSL, it doesn't work, it should be related to the terminal software you are using. I have no problem using the terminal software that comes with WSL, but it doesn't work with Windows Terminal unless I cancel the Ctrl + v binding in the Windows Terminal settings
