### ISSUE TITLE
Add default keybinding to cycle to next buffer

### ISSUE THREAD

**Issue by benediktms** [LunarVim/LunarVim#2872]
### Feature Description

A simple feature to add a default which-key keybinding to cycle to the next buffer, similar to the existing feature to cycle to the next buffer (essentially calling `:BufferLineCycleNext`)

### Describe the alternatives you have considered

The user can simply add a custom keybinding to do this but, providing a default which-key keybinding seems to make sense since we already have one for cycling to the previous buffer

### Support information

I am happy to submit a PR for this if is something that makes sense to add to the project

**Comment by rebuilt** [comment]
Yeah, it seems like an oversight not to have it in whichkey.  If you submit that PR, I'd approve that change.   

As an aside, I'll say that the existing non-whichkey mapping of `<S-l>` and `<S-h>` override some basic vim keys and we should consider removing those.

**Comment by benediktms** [comment]
Cool, I can also remove those in my PR

**Comment by rebuilt** [comment]
Maybe separate PR's since the first change can be merged without controversy but the second might need more input from others.

**Comment by kobzar** [comment]
SPS + b + b working by default
SPS + b  + j
The next one idea is close buffer by SPS + b + c not by SPS + c by default

**Comment by benediktms** [comment]
@kobzar Sorry the description was wrong I meant cycling to the next buffer. `<leader>bb` works to cycle to the previous buffer. I propose adding a similar keybinding (`<leader>bn`) to cycle to the next buffer.

**Comment by kobzar** [comment]
Yep. It must be by default.

**Comment by cpea2506** [comment]
> The next one idea is close buffer by SPS + b + c not by SPS + c by default

Agree! It would make sense if close buffer is in buffer section.

**Comment by miwojc** [comment]
Why not?
next buffer: SPS b n
previous buffer: SPS b p

**Comment by MycrofD** [comment]
@miwojc perhaps because the keys `b` and `n` are right next to each other and it is fast to switch between them. It is even faster to just do `SPS b b` and cycle through buffers.
