### ISSUE TITLE
Treesitter inactive for latex files

### ISSUE THREAD

**Issue by andyliuhaowen** [LunarVim/LunarVim#2879]
### Problem description

1. Open a latex file (*.tex, with g:tex_flavor="latex")
2. Run `:TSInstall latex"
3. Restart and look at `:LvimInfo`
4. See that treesitter is still inactive

This is probably my own issue not setting it up right, because looking at issues listed for `nvim-treesitter` problem people are able to get this to work, like this one https://github.com/nvim-treesitter/nvim-treesitter/issues/2786.

### LunarVim version

master-47e4e5b

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

OpenSUSE Tubleweed

### Steps to reproduce

1. Open a latex file (*.tex, with g:tex_flavor="latex")
2. Run `:TSInstall latex"
3. Restart and look at `:LvimInfo`
4. See that treesitter is still inactive

### support info

```
               Buffer info
               * filetype:                tex
               * bufnr:                   1
               * treesitter status:       inactive
               
               Active client(s)
               * name:                      texlab
               * id:                        1
               * supported filetype(s):     [tex, bib]
               * attached buffers:          1
               * root_dir pattern:          1
               * capabilities:              documentFormattingProvider | workspaceSymbolProvider | documentHighlightProvider
                                            documentSymbolProvider     | referencesProvider      | definitionProvider
                                            foldingRangeProvider       | hoverProvider
               
               Automatic LSP info
               * Skipped servers: ltex
               
               Formatters info
               * Active: 
               * Supported: latexindent
               
               Linters info
               * Active: 
               * Supported: [chktex, proselint, vale]
               
               Code actions info
               * Active: 
```

It does not happen on other files:
```
                        Buffer info
                        * filetype:                python
                        * bufnr:                   1
                        * treesitter status:       active
```

**Comment by rebuilt** [comment]
Add this to your config to enable treesitter for latex files `lvim.builtin.treesitter.highlight.disable = {}`

Treesitter highlighting for latex was intentionally disabled (`lvim.builtin.treesitter.highlight.disable = {"latex"}`)
 because there were problems compared to the default vim regex highlighting.  I'm not sure what state it's in right now.

**Comment by andyliuhaowen** [comment]
Interesting! And yeah, it's broken af. `begin/end` aren't highlighted, `section/subsection` aren't either, among other things.

Do you happen to know how `nvim-treesitter` highlighting works? It seems the LaTeX parser is returning the correct node type, but `nvim-treesitter` isn't highlighting it. I see this file: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/highlight.lua, but I feel like LaTeX-specific highlighting needs should be somewhere separate.

**Comment by rebuilt** [comment]
Anything latex specific will probably be here:   https://github.com/latex-lsp/tree-sitter-latex

But I really don't know much about how it all works together.

**Comment by andyliuhaowen** [comment]
Thanks! I'll look into it!
