### ISSUE TITLE
`:LvimUpdate` timing out after 5000ms

### ISSUE THREAD

**Issue by brice-verint** [LunarVim/LunarVim#2891]
### Problem description

1. Run `:LvimUpdate`

```
Error executing Lua callback: .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:499: 'git fetch --unshallow' was unable to complete in 5000 ms                                                                                                                                            
stack traceback:                                                                                                                                  
        [C]: in function 'error'                                                                                                                  
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:499: in function 'wait'                                                       
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:453: in function 'sync'                                                       
        ...n.Rice/.local/share/lunarvim/lvim/lua/lvim/utils/git.lua:23: in function 'git_cmd'                                                     
        ...n.Rice/.local/share/lunarvim/lvim/lua/lvim/utils/git.lua:44: in function 'safe_deep_fetch'                                             
        ...n.Rice/.local/share/lunarvim/lvim/lua/lvim/utils/git.lua:56: in function 'update_base_lvim'                                            
        ...n.Rice/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:124: in function 'update'                                                     
        ...ce/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:47: in function <...ce/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:4
6>
```

### LunarVim version

master-47e4e5b

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

macOS 12.3 (Monterey)

### Steps to reproduce

1. Run `:LvimUpdate`

### support info

```console
:LvimInfo
Error executing Lua callback: vim/shared.lua:0: t: expected table, got nil                                                                        
stack traceback:                                                                                                                                  
        [C]: in function 'error'                                                                                                                  
        vim/shared.lua: in function 'validate'                                                                                                    
        vim/shared.lua: in function <vim/shared.lua:0>                                                                                            
        vim/shared.lua: in function 'tbl_filter'                                                                                                  
        ...n.Rice/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info'                                         
        ...n.Rice/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'                                               
        ...ce/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:29: in function <...ce/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:2
8>
```

**Comment by brice-verint** [comment]
Just for clarity, I'm on a fast network. I'd assume 5000ms would be sufficient

**Comment by rebuilt** [comment]
Add this to your `config.lua`

```lua
local packer = require('packer')

packer.init({
  max_jobs = 1,
  git = {
    clone_timeout = 300, -- 5 mins
  },
})

```

That code snippet will lower the number of simultaneous network requests and increase the timeout.   

Your network can be both fast and still experience packet loss.   Lowering the number of simultaneous network requests will help eliminate packet loss as the problem.   

If setting max_jobs to 1 works, but is too slow, you can slowly ramp up the number to something that works better for your network.

**Comment by rebuilt** [comment]
Related:  https://github.com/wbthomason/packer.nvim/issues/456

**Comment by brice-verint** [comment]
Yeah, The following seems to be a good balance.
I wasn't aware that `:LvimUpdate` relied upon packer. Thanks :)

```lua
local packer = require('packer')

packer.init({
  max_jobs = 10,
  git = {
    clone_timeout = 10, -- timeout in seconds
  },
})
```

**Comment by rebuilt** [comment]
> Why isn't lvim setting a sensible default for max_jobs?

What is a sensible number?

**Comment by brice-verint** [comment]
> > Why isn't lvim setting a sensible default for max_jobs?
> 
> What is a sensible number?

Personally I think 10 is a really sensible default

**Comment by rebuilt** [comment]
10 is noticeably slower than the 40 it's set to now.

**Comment by brice-verint** [comment]
It won't throw errors on 10 though unless you have network issues.
Setting it to 40 can result in errors even on a sufficiently capable network in my experience.

Performance tuning to prevent errors from the default feels worse than performance tuning for better performance imo

**Comment by rebuilt** [comment]
Get far enough away from your wifi and even 10 isn't small enough.

**Comment by brice-verint** [comment]
I've had 40 cause problems on wired connections.
But I'm fine with configuring what works for me myself as long as I know how to, so thanks for that :)

**Comment by danielo515** [comment]
> Yeah, The following seems to be a good balance. I wasn't aware that `:LvimUpdate` relied upon packer. Thanks :)
> 
> ```lua
> local packer = require('packer')
> 
> packer.init({
>   max_jobs = 10,
>   git = {
>     clone_timeout = 10, -- timeout in seconds
>   },
> })
> ```

Doesn't this override the packer settings deleting all the rest?

**Comment by luxus** [comment]
this is btw the problem and the solution
https://github.com/reo101/reovim/issues/1#issuecomment-1224436894
ulimit is really low in macOS
