### ISSUE TITLE
Contents of Markdown files are not being soft wrapped at the end of the line

### ISSUE THREAD

**Issue by aap01** [LunarVim/LunarVim#2892]
### Problem description

For a long line in markdown file, words are not wrapped at the end of the line. 
But running `:set wrap linebreak nolist` softly wraps the word at the end of the line.
However, this setting resets upon next restart.

Note: I am new to this neovim, lua, lunarvim stuff.

### LunarVim version

rolling-63696c1

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

macOS 12.5 21G72 arm64

### Affected language servers

all

### Steps to reproduce

1. Open LunarVim from terminal
2. Open a `.md` file
3. Put in a long line
4. Put a long word at the end of the line so that it goes to the next line to complete

### Actual behavior

<img width="881" alt="Screenshot 2022-08-10 at 1 42 47 AM" src="https://user-images.githubusercontent.com/19292809/183747429-28a9b305-9591-4c8c-988c-aa16ba309a4c.png">

### Expected behavior

<img width="870" alt="Screenshot 2022-08-10 at 1 42 08 AM" src="https://user-images.githubusercontent.com/19292809/183748049-e2679cc5-f3e8-4c1e-8838-73e0a21f5e83.png">

### support info

```
 Language client log: /Users/alif/.cache/lvim/lsp.log
 Detected filetype:   NvimTree
 
 0 client(s) attached to this buffer: 
 
 1 active client(s) not attached to this buffer: 
 
 Client: sumneko_lua (id: 1, pid: 5320, bufnr: [31])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /Users/alif/.config
 	cmd:             lua-language-server
 
 Configured servers list: sumneko_lua
```
```

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                NvimTree
* bufnr:                   27
* treesitter status:       inactive

Active client(s)
* name:                      sumneko_lua
* id:                        1
* supported filetype(s):     lua
* attached buffers:          31
* root_dir pattern:          31
* capabilities:              documentRangeFormattingProvider | colorProvider           | definitionProvider
                             documentFormattingProvider      | referencesProvider      | documentSymbolProvider
                             documentHighlightProvider       | workspaceSymbolProvider | foldingRangeProvider
                             hoverProvider                   | typeDefinitionProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

**Comment by rebuilt** [comment]
You probably want to set those in your `~/config/lvim/config.lua`

```
vim.opt.wrap = true
vim.opt.linebreak = true
vim.opt.list = false
```

You'll probably want to read this section of the lua guide.  https://github.com/nanotee/nvim-lua-guide#using-meta-accessors

**Comment by aap01** [comment]
This solves the problem. Thanks!
