### ISSUE TITLE
I can't remove the command lvim

### ISSUE THREAD

**Issue by JEHH1828** [LunarVim/LunarVim#2897]
### Problem description

For some reason I uninstall Lunar Vim so that I ran `Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/uninstall.ps1 -UseBasicParsing | Invoke-Expression` thinking thats remove lvim to run Lunar Vim but actually that's not working

I get other IDE for Nvim and it's unpleasant have that

### LunarVim version

Last version 

### Neovim version (>= 0.7.2)

Nvim 0.7.0

### Operating system/version

Windows 11

### Steps to reproduce

Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression

and yes to all

### support info

![WindowsTerminal_swg3nHuWid](https://user-images.githubusercontent.com/70662351/184060623-468fb61c-99e5-41a2-ba1d-ca68898bd145.png)

### Screenshots

![WindowsTerminal_Anmb4YlbrY](https://user-images.githubusercontent.com/70662351/184059872-ec0b24cd-0ea6-46bd-bbca-4d33e09cde52.png)
![WindowsTerminal_paqWTGctEO](https://user-images.githubusercontent.com/70662351/184059876-27848819-1b2c-4f4c-ade2-87acada2a4ca.png)

**Comment by kylo252** [comment]
You need to remove the alias from [`$PROFILE`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles), it's an optional step in the installer

https://github.com/LunarVim/LunarVim/blob/9caa457810a26369f848d4f90f6e0ec84e0048e0/utils/installer/install.ps1#L245-L253
