### ISSUE TITLE
Fsautocomplete No symbol information found

### ISSUE THREAD

**Issue by liidtke** [LunarVim/LunarVim#2903]
### Problem description

Error opening F# source files with fsautocomplete.
"No symbol information found".
Note: in astrovim f# files open just fine.

![image](https://user-images.githubusercontent.com/35538291/184198460-bf3d08ca-4b17-4841-9382-7e3b568d925a.png)

Thanks

### LunarVim version

master-47e4e5b

### Neovim version (>= 0.7)

0.8.0-dev-775-g27ce21ac8

### Operating system/version

Manjaro Linux x86_64

### Affected language servers

fsautocomplete

### Steps to reproduce

1. install lvim
2. open fsharp file
3. install lsp fsautocomplete
4. start getting messages

### Actual behavior

Error Notifications

### support info

 Language client log: /home/aldol/.local/state/nvim/lsp.log
 Detected filetype:   fsharp
 
 1 client(s) attached to this buffer: 
 
 Client: fsautocomplete (id: 2, pid: 59715, bufnr: [61])
 	filetypes:       fsharp
 	autostart:       true
 	root directory:  /home/aldol/Projects/keep-web/api/keep-api
 	cmd:             fsautocomplete --background-service-enabled
 
 
 Configured servers list: fsautocomplete, html

dotnet --info

.NET SDK (reflecting any global.json):
 Version:   6.0.106
 Commit:    4f1e0330de

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.106/

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  3.1.120 [/usr/share/dotnet/sdk]
  5.0.405 [/usr/share/dotnet/sdk]
  6.0.106 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

### Screenshots

![image](https://user-images.githubusercontent.com/35538291/184200951-0b9432c1-1abe-442a-86df-a12659022e0a.png)

**Comment by kylo252** [comment]
Please try to reproduce this with a minimal setup so we can isolate where the issue is coming from, feel free to try it with and without mason.
You can use https://github.com/LunarVim/LunarVim/blob/rolling/tests/minimal_lsp.lua

**Comment by lvimuser** [comment]
Fyi, this is because `textDocument/documentHighlight`. Seems to be the only LSP acting like this, and I really think it shouldn't.

Current workaround is to disable `lvim.lsp.document_highlight`. But you should consider raising an issue at `fsautocomplete`

You could reduce the number of calls by ignoring on empty text/columns. But it keeps triggering on `let`, or `=`.
```lua
    callback = function()
      local cursor = vim.api.nvim_win_get_cursor(0)
      -- check if cursor is on an empty column
      local row, col = cursor[1] - 1, cursor[2]
      local line = vim.api.nvim_buf_get_lines(0, row, row + 1, true)[1]
      if line and (#line == 0 or line:sub(col + 1, col + 1):match "^%s+$") then
        return
      end
      vim.lsp.buf.document_highlight()
    end,
  })
```

**Comment by liidtke** [comment]
Adding `lvim.lsp.document_highlight = false;` to my config helped, thanks.

**Comment by kylo252** [comment]
> Adding `lvim.lsp.document_highlight = false;` to my config helped, thanks.

you could always override [`setup_document_highlight`](https://github.com/LunarVim/LunarVim/blob/08b5e99f53fc5170d35de3f474c7df5ae1fac62f/lua/lvim/lsp/utils.lua#L84) to exclude a server for example, or directly manage the autocmds yourself otherwise, see `:h vim.lsp.buf.document_highlight()`
