### ISSUE TITLE
How do you change the cursor from i:beam to i:block?

### ISSUE THREAD

**Issue by itsrxmmy** [LunarVim/LunarVim#2904]
### Problem description

I want to change my cursor from beam to block

### LunarVim version

master-47e4e5b

### Neovim version (>= 0.7.2)

v0.7.2 

### Operating system/version

Manjaro KDE 5.15

### support info

dont see how this is related to changing my cursor so im gonna leave this empty

**Comment by cpea2506** [comment]
See `:h guicursor`.

Example:
```lua
vim.opt.guicursor = "i:block" --  set cursor of insert mode as block.
```

**Comment by danielo515** [comment]
This needs to be closed, it's not a bug nor a feature
