### ISSUE TITLE
Setting `conceallevel=0` does not impact Lunar Vims behaviour

### ISSUE THREAD

**Issue by John15321** [LunarVim/LunarVim#2906]
### Problem description

I would like to be able to edit markdown files without any concealment of the syntax. I tried changing the `conceallevel` variable to `0` in the `config.lua` but I did not impact the editor's behavior (yes I restarted it multiple times)

![image](https://user-images.githubusercontent.com/56229312/184342326-9faaf670-84d7-4e44-a785-0c699611e1cf.png)

The text is still visible like that is. And if I check the value of the  variable it says its `2` like the change in the config did not impact the editor:

![image](https://user-images.githubusercontent.com/56229312/184342451-7b4964b5-130a-463a-9654-5e3c41899f83.png)

I have it changed like in the docs (https://www.lunarvim.org/configuration/01-settings.html#example-options):

![image](https://user-images.githubusercontent.com/56229312/184342509-fd267a94-c461-4e77-b03c-bbb23a7e9a6a.png)

### LunarVim version

master-47e4e5b

### Neovim version (>= 0.7)

NVIM v0.8.0-dev+2054-g5c3bbb67e

### Operating system/version

v0.8.0-dev+2054-g5c3bbb67e

### Affected language servers

markdown

### Steps to reproduce

This is a link to my `config.lua` where the `conceallevel` is clearly set:

https://github.com/John15321/.my-lvim

### Actual behavior

Does not change the level to `0` it stays as `2`

### Expected behavior

Should change it to `0`

### support info

```console
 Language client log: /Users/john/.local/state/nvim/lsp.log
 Detected filetype:   
 
 0 client(s) attached to this buffer: 
 
 2 active client(s) not attached to this buffer: 
 
 Client: clangd (id: 1, pid: 90939, bufnr: [5])
 	filetypes:       c, cpp, objc, objcpp, cuda
 	autostart:       true
 	root directory:  /Users/john/Documents/Programming/PwrAerospace/Firmware
 	cmd:             clangd
 
 Client: sumneko_lua (id: 2, pid: 91299, bufnr: [13])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /Users/john/.config/lvim
 	cmd:             lua-language-server
 
 Configured servers list: sumneko_lua, clangd
```

**Comment by kylo252** [comment]
Lunarvim is already setting `conceallevel=0`

https://github.com/LunarVim/LunarVim/blob/45f9825d1e666890ed37baf15a14707ae40e5cff/lua/lvim/config/settings.lua#L19

I'm fairly sure it's the plugin you're using that's overriding this
https://github.com/Yggdroot/indentLine/blob/7753505f3c500ec88d11e9373d05250f49c1d900/after/plugin/indentLine.vim#L95-L107

I'd suggest switching to indent_blankline, here's my setup for it: https://github.com/kylo252/lvim/blob/c97b0ad3e9c58c6694156eacefa6c465ccb59315/lua/user/indent.lua#L1

you could also use an autocmd to set local options per filetype, see
https://github.com/LunarVim/LunarVim/blob/45f9825d1e666890ed37baf15a14707ae40e5cff/lua/lvim/core/autocmds.lua#L44-L51
