### ISSUE TITLE
AutoClosing of html tags doesn't work in .jsx or .tsx files

### ISSUE THREAD

**Issue by felixpohlmann** [LunarVim/LunarVim#2907]
### Problem description

I can't get auto-closing tags to work in LunarVim.

Even if if follow the official instructions for a recommended plugin (https://www.lunarvim.org/plugins/02-extra-plugins.html#nvim-ts-autotag).

Am I missing any further steps? 

I tried to follow the solution of issue #2717  https://github.com/LunarVim/LunarVim/issues/2717 but couldn't get it to work, neither with the recommend nor the alternative plugin...

Thanks a lot in advance!!

### LunarVim version

master-dd50268

### Neovim version (>= 0.7.2)

v0.7.2

### Operating system/version

macos 12.3.1

### Steps to reproduce

1. Open .jsx or .tsx file
2. Create a functional component
3. Create sorrounding <div> in return 
4. Try to type <p followed by an > 
5. The closing tag </p> is not coming automatically

### support info

![Screenshot 2022-08-12 at 13 23 38](https://user-images.githubusercontent.com/68960775/184344461-fa7befca-13e6-4514-8401-33973e6d3c4c.png)
![Screenshot 2022-08-12 at 13 23 05](https://user-images.githubusercontent.com/68960775/184344469-351c01a0-d0f9-43bf-8d2c-33521574d952.png)

**Comment by felixpohlmann** [comment]
I tried to follow the solution of issue #2717 but couldn't get it to work, neither with the recommend nor the alternative plugin...

**Comment by cpea2506** [comment]
Can you try with this command (don't ask me where to put it 🥹)

```lua
lvim.builtin.treesitter.autotag.enable = true
```

**Comment by felixpohlmann** [comment]
That's it! Thanks a lot @cpea2506!
