### ISSUE TITLE
How can i disable things like snippets, emojis, calc in nvim-cmp

### ISSUE THREAD

**Issue by BlueDruddigon** [LunarVim/LunarVim#2908]
### Feature Description

Disable some completion sources like vsnip, luasnip, emojis, calc... in LunarVim.
I've using:
- neovim v0.7.2
- lunarvim: latest rolling branch

**Comment by cpea2506** [comment]
## Default cmp sources:

https://github.com/LunarVim/LunarVim/blob/45f9825d1e666890ed37baf15a14707ae40e5cff/lua/lvim/core/cmp.lua#L228-L240

## Custom sources: 
```lua
lvim.builtin.cmp.sources = { 
 -- List of source you wants
}
```

or 

```lua
lvim.builtin.cmp.sources = vim.tbl_filter(function(source)
  source.name ~= "vsnip" and source.name ~= "luasnip" and ...
end, lvim.builtin.cmp.sources)
```
