### ISSUE TITLE
[Feature] Some keybindings for lsp diagnostics (Code Action, signature_help) just like lspsaga.nvim

### ISSUE THREAD

**Issue by BlueDruddigon** [LunarVim/LunarVim#2909]
### Feature Description

Can team update some keybindings like Lsp Diagnostics (CodeAction, Jump through diagnostics, signature_help) in default, or just purely lsp like glepnir's lspsaga plugin ?
Thanks!

**Comment by kylo252** [comment]
There are a lot of LSP keybindings already configured out-of-the-box, which you can even alter to your liking

https://github.com/LunarVim/LunarVim/blob/45f9825d1e666890ed37baf15a14707ae40e5cff/lua/lvim/lsp/config.lua#L96-L121

there're also a bunch of them managed by [which-key](https://github.com/LunarVim/LunarVim/blob/45f9825d1e666890ed37baf15a14707ae40e5cff/lua/lvim/core/which-key.lua#L156-L186), press `<leader>l` to check them out.

**Comment by BlueDruddigon** [comment]
Thanks for your reply. I've found these configurations.
One more question, when I'm in Python Projects, should I have to set up a code action with `null-ls` stuff in my config.lua in order to use <leader>la ?
