### ISSUE TITLE
with vim.opt.clipboard = "unnamedplus" "0 register does not get updated

### ISSUE THREAD

**Issue by jmlucjav** [LunarVim/LunarVim#2915]
### Problem description

0 register is not being updated since I upgraded some weeks ago. I did not try to debug it, yesterday I reinstalled rolling and still the same issue. 

If I remove this from my config.lua

```
vim.opt.clipboard = "unnamedplus"
```

then it is updated fine, but I want unnamedplus behavious.

### LunarVim version

rolling-45f9825

### Neovim version (>= 0.7.2)

NVIM v0.8.0-dev-841-g5854103da

### Operating system/version

wsl, ubuntu 20.04

### Steps to reproduce

1. Set vim.opt.clipboard = "unnamedplus" in your config.lua
2. start lvim
3. check registers, specially 0
4. yiw in some word
5. see 0 reg is not updated

### support info

                  
                       __                          _    ___         
                      / /   __  ______  ____ _____| |  / (_)___ ___ 
                     / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
                    / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
                   /_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 
                   
                   
                   Buffer info
                   * filetype:                markdown
                   * bufnr:                   3
                   * treesitter status:       inactive
                   
                   Active client(s)
                   * name:                      ltex
                   * id:                        1
                   * supported filetype(s):     [bib, gitcommit, markdown, org, plaintex, rst, rnoweb, tex]
                   * attached buffers:          3
                   * root_dir pattern:          3
                   
                   Automatic LSP info
                   * Status: disabled for markdown
                   
                   Formatters info
                   * Active: prettier  
                   * Supported: [cbfmt, markdownlint, mdformat, ocdc, prettier, prettier_d_slim, prettierd, remark, terrafmt]
                   
                   Linters info
                   * Active: 
                   * Supported: [alex, markdownlint, mdl, proselint, vale, write_good]
                   
                   Code actions info
                   * Active:

**Comment by rebuilt** [comment]
What's the output of `set clipboard?`.   

And which clipboard tool are you using?

```
  - |g:clipboard|
  - pbcopy, pbpaste (macOS)
  - wl-copy, wl-paste (if $WAYLAND_DISPLAY is set)
  - xclip (if $DISPLAY is set)
  - xsel (if $DISPLAY is set)
  - lemonade (for SSH) https://github.com/pocke/lemonade
  - doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
  - win32yank (Windows)
  - termux (via termux-clipboard-set, termux-clipboard-set)
  - tmux (if $TMUX is set)
```

**Comment by jmlucjav** [comment]
> What's the output of set clipboard?.

`
clipboard=unnamedplus`
 
`And which clipboard tool are you using?`

```
provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank
 
```
I did this while installing:
sudo cp  .../Neovim/bin/win32yank.exe "/usr/local/bin/win32yank.exe"

thanks!

**Comment by jmlucjav** [comment]
> So, if I understand correctly, you're running Ubuntu in wsl. And the clipboard tool you're using in Ubuntu is the Windows binary win32yank.exe. Did this work at some point? I don't see how a windows executable can be the clipboard intermediary in Ubuntu.

Yes, this was working perfectly for many months (years?). First in plain neovim and then in lvim. I did notn come up with this, it's even in the neovim FAQ https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl

> 
> The other thing I'm wondering about is the expected behavior. Are you trying to copy text exclusively within wsl or are you trying to copy text between wsl and windows applications?

It was working fine across both wsl and windows apps.

And, to be clear, all that is working fine right now with unnamedplus, the only thing is that the "0 register does not get updated when I yank something in lvim.

**Comment by rebuilt** [comment]
Can you confirm you get the same behavior with a blank `~/.config/lvim/config.lua`?   Run `:PackerSync` to remove plugins.

**Comment by jmlucjav** [comment]
I confirm:

1. with a totally blank config.lua "0 get updated on every yank
2. if I add just the line 
vim.opt.clipboard = "unnamedplus"
  then "0 does not get updated

**Comment by jmlucjav** [comment]
I cleaned up and reinstalled nvim/lvim from scratch, no longer able to reproduce this, great!

**Comment by nairobi02** [comment]
I am currently facing the same issue. I am able to paste stuff into lvim, but when I yank, I can paste the yanked stuff in that file, but it doesn't show up in my clipboard and I cant use it anywhere else

**Comment by Doods0** [comment]
I was facing it a moment ago, the issue persisted for a couple of days before I lost my patience.

The unique thing about the issue is using `:set clipboard=unnamedplus` was working, yet
using `vim.o.clipboard = 'unnamedplus'` wasn't, so I tried reinstall with `sudo apt remove neovim` & `sudo apt install neovim` and it worked!

I am using Neovim version  0.10.0-dev - I realize what repo I am on - on Pop!_OS 22.04 from the https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable PPA, which is unofficial, but endorsed enough to be mentioned in official docs, and I am using the unstable version because the stabe repo ships 0.7.
