### ISSUE TITLE
E5108: Error executing lua [string ":lua"]:1: module 'telescope.builtin.internal' not found

### ISSUE THREAD

**Issue by lxwbr** [LunarVim/LunarVim#2920]
### Problem description

E5108: Error executing lua [string ":lua"]:1: module 'telescope.builtin.internal' not found

### LunarVim version

master-47e4e5b

### Neovim version (>= 0.7.2)

v0.7.2

### Operating system/version

macOS 12.5

### Steps to reproduce

1. Start `lvim`
2. Press `space`
3. Press `s`
4. Press `p`

### support info

Nothing in here

### Screenshots

<img width="914" alt="image" src="https://user-images.githubusercontent.com/6862750/184886949-8f8eb3bf-74f7-43e1-a788-12dcc2553ca6.png">

**Comment by rebuilt** [comment]
Can you run `:PackerSync` to make sure the files for all plugins get installed.  Then run `:PackerStatus` to confirm the plugin is loaded and running

**Comment by lxwbr** [comment]
`:PackerSync`:
<img width="776" alt="image" src="https://user-images.githubusercontent.com/6862750/184901476-37499147-329b-4008-a0f0-570108f4e44b.png">
`:PackerStatus`:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/6862750/184901541-9a21ff0e-081d-494b-bc00-c05c7a34f68f.png">

**Comment by rebuilt** [comment]
Is it happening when you try to view color schemes?  The command for that was updated 7 days ago.  https://github.com/LunarVim/LunarVim/pull/2885

**Comment by lxwbr** [comment]
Yes, that only happens when I try to `Colorscheme with Preview` (`␣ s p`). I.e. the `Colorscheme` command itself works fine (`␣ s c`)

**Comment by lxwbr** [comment]
Adding the change described in https://github.com/LunarVim/LunarVim/pull/2885/files#diff-e37fe0339f7197c4036b5ded8ea10438f6bb8021de77aecfb45f44348be1ffefL255-L256 locally fixes the issue, thank you!
