### ISSUE TITLE
The installing bash script in branch rolling is still installing from master

### ISSUE THREAD

**Issue by JerryLiao26** [LunarVim/LunarVim#2922]
https://github.com/LunarVim/LunarVim/blob/08b5e99f53fc5170d35de3f474c7df5ae1fac62f/utils/installer/install.sh#L5

As mentioned in issue title

**Comment by cpea2506** [comment]
Nah. You must read the comment and learn how `:-` works

```
#Set branch to master unless specified by the user
declare LV_BRANCH="${LV_BRANCH:-"master"}"
```

This branch will be merged into master. No one want to accidentally install rolling.

**Comment by JerryLiao26** [comment]
Sorry, I installed it on Windows machine first and that's default on rolling branch
