### ISSUE TITLE
hop.nvim not functioning

### ISSUE THREAD

**Issue by mcheviron** [LunarVim/LunarVim#2929]
### Problem description

Hello, I am not sure how to explain this in detail but basically I wanted to add the hop.nvim plugin and just did what was writting the documentation:
{
  "phaazon/hop.nvim",
  event = "BufRead",
  config = function()
    require("hop").setup()
    vim.api.nvim_set_keymap("n", "s", ":HopChar2<cr>", { silent = true })
    vim.api.nvim_set_keymap("n", "S", ":HopWord<cr>", { silent = true })
  end,
},

I added this snippet to my plugins but after that, nothing happened. I thought that it's maybe due to the default mapping of s and S, but I can't even execute the hop commands like HopWord etc.

I am not sure if there are additional steps I should do, like unset the default mapping, so I thought I should ask prior doing anything.

Thanks in advance!

### LunarVim version

master-47e4e5b

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Fedora Linux 36

### Steps to reproduce

Adding the following snippet to config.lua:

{
  "phaazon/hop.nvim",
  event = "BufRead",
  config = function()
    require("hop").setup()
    vim.api.nvim_set_keymap("n", "s", ":HopChar2<cr>", { silent = true })
    vim.api.nvim_set_keymap("n", "S", ":HopWord<cr>", { silent = true })
  end,
},

### support info

# :LvimInfo

Buffer info
                     * filetype:                lua
                     * bufnr:                   3
                     * treesitter status:       active
                     
                     Active client(s)
                     * name:                      sumneko_lua
                     * id:                        1
                     * supported filetype(s):     lua
                     * attached buffers:          3
                     * root_dir pattern:          3
                     * capabilities:              referencesProvider              | documentFormattingProvider | hoverProvider
                                                  definitionProvider              | documentHighlightProvider  | documentSymbolProvider
                                                  workspaceSymbolProvider         | colorProvider              | foldingRangeProvider
                                                  documentRangeFormattingProvider | typeDefinitionProvider
                     
                     
                     
                     Formatters info
                     * Active: 
                     * Supported: [lua_format, stylua]
                     
                     Linters info
                     * Active: 
                     * Supported: [luacheck, selene]
                     
                     Code actions info
                     * Active:

**Comment by rebuilt** [comment]
Make sure you run `:PackerCompile`.


This is what my config looks like.  It works for me.
```lua
    {
      "phaazon/hop.nvim",
      as = "hop",
      keys = { "s", "S" },
      config = function()
        -- you can configure Hop the way you like here; see :h hop-config
        require("hop").setup({ keys = "etovxqpdygfblzhckisuran" })
        vim.api.nvim_set_keymap("n", "s", ":HopWord<cr>", {})
        vim.api.nvim_set_keymap("n", "S", ":HopPattern<cr>", {})
      end,
    },


```

**Comment by mcheviron** [comment]
Hello. Thank you very much for your fast reply.

I tried :PackerCompile and nothing happened. I went to cook and then as I was replying to you, I tried again, and now it's working. Likewise, I have no flying clue what happened but if it works, I am glad.

One last question, if you know, does :PackerCompile take a while until it takes effect or is it supposed to be something instantaneous?

**Comment by rebuilt** [comment]
`:PackerCompile` is instant but it operates on your configuration file as it existed when you opened it.  It doesn't read the changes you make after editing the source file.  
So, to make sure it works on the changes you make
   - Make your edits
   - Close the file
   - Open the configuration file again
   - run `:PackerSync`

**Comment by mcheviron** [comment]
Thank you very much mate!
