### ISSUE TITLE
Markdown highlighting not looking right

### ISSUE THREAD

**Issue by zenVentzi** [LunarVim/LunarVim#2932]
### Problem description

I don't expect random words to be colored randomly. See the screenshot below.

`:LvimInfo` says no active linters(see **Support Info** section). Also, installing the default AstroNvim distribution highlights markdown properly, so it must be something from LunarVim's distribution.

### LunarVim version

rolling-0fc1e42

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Windows 10 Pro, Version 21H2, WSL2, Windows Terminal

### Steps to reproduce

1. (Re)install lvim rolling release, changing settings/configs
2. Create a markdown file with the contents below
3. lvim filename.md
4. See weird highlighting

<details>
    <summary>Markdown file content(toggle)</summary>

    obs/tasks, key-notation
    
    defaults.vim
    
    - vifm (file explorer)
    - commands (help)
      - quickref
      - command
      - stdpath
      - redir
      - switchbuf
      - vim.fn.system (run bash commands from within lua file)
      - :lua print(vim.inspect(vim.tbl_keys(vim.lsp.handlers))) 
      - special-buffers (scratch buffer)
      - -- More -- pager extract
        - `put =execute('lua print(vim.inspect(package.loaded))')`
          - prints command output to current buffer
        ```
        :redir @a    redirect output of following commands to register a
        :let         list every current option and its value
        G<CR>        go straight to the end of the listing and make it disappear
        :redir END   stop redirection
        :tabnew      open a new buffer in a new window in a new tab page
        "ap          put from register a
        ```
    - macros turn into mappings turn into custom functions
    - [available keybindings in normal mode](https://gist.github.com/romainl/1f93db9dc976ba851bbb)
    - [autocompletion for common json schemas](https://www.schemastore.org/json/)
    - [best-learning-tutorial](https://learnvim.irian.to/)
    - surfingkeys (chrome vim extension)
    - [idiomatic-vim](https://github.com/romainl/idiomatic-vimrc)
    - [nvim-lua-kickstart](https://github.com/nvim-lua/kickstart.nvim)
    - [dotvim](https://github.com/dotphiles/dotvim)
    - [Search through our curated list of neovim plugins](https://neovimcraft.com/)
    - opinionated vim/distributions
      - lunarvim
      - nvchad
      - cosmic vim
        - The biggest differences from lunarvim are
    
          Simpler. The levels of abstraction are much lower.
    
          Opts are VIM opts. Most settings are defined as you would in your own config. No need to mutate a random global variable in order to make an editor change.
    
          Flexible. Add any LSPs, mappings or plugins. Super easy to customize.
    
          Lots of themes to choose from (with more to come) with nothing stopping you from using your own.
    
          Reload config commands
    
          Plenty more
    
          One of my main goals with Cosmic is to provide an easy to use yet powerful config that doesn’t lock in users and is built in a way where, if/when someone is ready to move to their own config, the transition will be easy.
      - spacevim
      - doom-nvim
      - doom-nvim
      - astro-nvim
        - font setup guide
          1. Download JetBrainsMono Nerd Font from [here](https://www.nerdfonts.com/font-downloads).
          2. Extract into a folder
          3. Select all fonts and right-click "Install for all users"
          4. In Windows Terminal open Settings
          6. Under "Profiles" select the profile you use to open AstroNvim with
          7. Additional Settings > Appearance > Font Face > JetBrainsMono Nerd Font
      - vapour-nvim
      - http://vim.spf13.com/
    - [nvim-lua-guide](https://github.com/nanotee/nvim-lua-guide)
    - [nn <space> <cmd>call VSCodeNotify('editor.toggleFold')<cr>](https://github.com/curist/dotvim/blob/98b161f075/code.vim)
    - [minimal-setup](https://github.com/Blacksuan19/init.nvim/blob/master/init.vim)
    - Bulgarian phonetic
      - map <leader>bg :set keymap=bulgarian-phonetic<CR>
      - <C-6> to toggle in insert mode
      - quickJs (alternative to lua)
    - navigate user manual
      - Press <C-]> (Ctrl+]) on a highlighted tag to jump to the corresponding entry
      - Press <C-t> (Ctrl+t) to come back
      - in regular files, cursor go back and forth with C-O C-I
    - why lua for neovim
      - [Being able to call upon the built in Lua API to call vim functions instead of having to run eval on some vimscript?](https://www.reddit.com/r/neovim/comments/mg5ip7/what_is_the_benefit_of_writing_plugins_in_lua/)
    - Using the API instead of calling the vim eval command
      - This is the main point. When you call vim.api.nvim_something from lua, it is not translated into vimscript, or send over message pack. You are calling the underlying C function directly. It's a direct interface with Neovims C code. You have access to the same functions it uses internally as well. That's what makes it "first class"
      - Lua->C function
      - Other-lang->Message pack->C function

</details>

### support info

```console
# :LspInfo

 Language client log: /home/zen_ventzi/.cache/lvim/lsp.log
 Detected filetype:   markdown
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: omnisharp_mono

```
```console
# :LvimInfo

Buffer info
* filetype:                markdown
* bufnr:                   16
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Status: disabled for markdown

Formatters info
* Active: 
* Supported: [cbfmt, deno_fmt, dprint, markdown_toc, markdownlint, mdformat, ocdc, prettier, prettier_d_slim, prettierd, remark, terrafmt]

Linters info
* Active: 
* Supported: [alex, markdownlint, mdl, proselint, vale, write_good]

Code actions info
* Active: 

```

### Screenshots

LunarVim:
![image](https://user-images.githubusercontent.com/11378653/185861068-78a81fff-fb40-447c-97bc-c46133367f73.png)

AstroNvim:
![image](https://user-images.githubusercontent.com/11378653/185865735-5b7ca37c-b4fc-41d6-8956-c116f044ecf8.png)

**Comment by kylo252** [comment]
This is the effect of `spell`, you can see all the pre-configured settings using `:autocmd FileType markdown`.

For more information check
- `:h spell`
- `:h spellcapcheck`
- Astronvim might be installing the tree-sitter parser for markdown by default, so check `:TSInstallInfo`
