### ISSUE TITLE
jtdls not working in windows

### ISSUE THREAD

**Issue by alexpetrean80** [LunarVim/LunarVim#2938]
### Problem description

Lunarvim windows installation cannot find the java language server.

### LunarVim version

rolling-0fc1e42

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

Windows 10

### Affected language servers

jtdls

### Steps to reproduce

install jdtls with :LspInstall in a java project and run it with :LspStart

### Actual behavior

Spawning language server with cmd: `jdtls` failed. The language server is either not installed, missing from PATH, or not executable.

### Expected behavior

jtdls starting and working as expected

### support info

![image](https://user-images.githubusercontent.com/49921909/186103869-80641fab-82e3-4ad1-ad52-42309acea3ee.png)
![image](https://user-images.githubusercontent.com/49921909/186103962-a2192186-607a-40e4-b137-3c74b992d635.png)

**Comment by kylo252** [comment]
this seems like an issue with mason, please open a ticket at https://github.com/williamboman/mason-lspconfig.nvim/issues

- make sure you have a java runtime `:checkhealth mason`
- make sure the installation is complete (try re-opening a java file once you know the server has been installed)
