### ISSUE TITLE
Exit insert mode in FloatTerm

### ISSUE THREAD

**Issue by ngocbh** [LunarVim/LunarVim#2940]
### Problem description

I have several questions regarding FloatTerm in LunarVim.

1. How to exit insert mode in FloatTerm? I want to go to the normal mode to copy the std output. The solution I have now is to use the mouse to click on the output on the screen and it put me in normal mode. How about the key binding?
2. Assuming that I'm in the normal mode now,  what actions could I do next? create another terminal, switch between terminals?
3. How could I copy from LunarVim to the system clipboard to copy to other applications?

### LunarVim version

master-47e4e5b

### Neovim version (>= 0.7.2)

0.7.0

### Operating system/version

Ubuntu 18.04

### support info

None

**Comment by ngocbh** [comment]
Sorry, it's not a bug. Probably I created in the wrong thread.

**Comment by ngocbh** [comment]
I found it in the documents of toggleterm.

**Comment by kuba-gaj** [comment]
How did you do it? 
Docs I found say its <C-\><C-N> but I can't do it as LunarVim maps <C-\> to toggle neoterm

**Comment by tysonmote** [comment]
For future reference: https://github.com/akinsho/toggleterm.nvim/blob/68fdf851c2b7901a7065ff129b77d3483419ddce/doc/toggleterm.txt#L502-L503
