### ISSUE TITLE
Installation asks for NPM/YARN/PNPM despite Yarn installed

### ISSUE THREAD

**Issue by rongcuid** [LunarVim/LunarVim#2942]
### Problem description

```
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

      88\                                                   88\
      88 |                                                  \__|
      88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
      88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
      88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
      88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
      88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
      \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|

--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
00h00m00s 0/0: : [ERROR] Unable to install using [yarn] without administrative privileges.
[ERROR]: Unable to find dependencies [pnpm][ERROR]: Unable to find dependencies [yarn][ERROR]: Unable to find dependencies [npm]Please install any one of the dependencies and re-run the installer. Try: 
sudo apt install -y pnpm
sudo apt install -y yarn
sudo apt install -y npm

```

However:

```
$ yarn --version
0.32+git
```

### LunarVim version

Not installed

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Pop OS 22.04

### Steps to reproduce

1. Use a non-privileged user (no `sudo` access)
2. Have `yarn` installed
3. Try to install LunarVim

### support info

Not installed

**Comment by steveoleary** [comment]
I'm seeing the same error although i'm with npm. Running current node lts installed using asdf nodejs plugin on M! Pro Macbook. 

node --version
v16.16.0

npm --version
8.11.0

**Comment by brneor** [comment]
Have you tried [this](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) (or the yarn equivalent)?

**Comment by steveoleary** [comment]
Hm well I just tried running

npm install -g npm

and the installation proceeded ok after that

**Comment by rongcuid** [comment]
I don't see how they are related. I have Yarn installed, but the installation script does not detect it.

**Comment by rongcuid** [comment]
Oh wow that is unexpected:

```
$ dpkg -S /usr/bin/yarn
cmdtest: /usr/bin/yarn
```

So the `yarn` binary on my system is not Node Yarm, but `cmdtest`.

**Comment by rafo** [comment]
> 



> I'm seeing the same error although i'm with npm. Running current node lts installed using asdf nodejs plugin on M1 Pro Macbook.
> 
> node --version v16.16.0
> 
> npm --version 8.11.0

Maybe a problem with M1 + Homebrew ? https://github.com/LunarVim/LunarVim/issues/1464

**Comment by rongcuid** [comment]
Sorry. The original problem has nothing to do with LunarVim, but debian installing "cmdtest" which provides a "yarn" executable which does something different. I think this issue should be either closed, or lvim should check for this special case.
