### ISSUE TITLE
Parenthesis not proper in Go

### ISSUE THREAD

**Issue by shivahnshankar** [LunarVim/LunarVim#2946]
### Problem description

When i use the import statement and open parenthesis, the matching closing parenthesis is not aligned to the left margin as it should be.

### LunarVim version

master-47e4e5b

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Linux pop-os 22.04

### Steps to reproduce

- Start editing a go 
- type import statement and open parenthesis
- Observe closing parenthesis position that is automatically inserted

### support info

Screenshots below

### Screenshots

![Screenshot from 2022-08-25 09-07-14](https://user-images.githubusercontent.com/8016298/186569266-180cf876-bbd4-414c-a248-43bf2d57aab8.png)
![Screenshot from 2022-08-25 09-09-07](https://user-images.githubusercontent.com/8016298/186569284-895196cc-2858-46bf-bf8a-a7012d30e93e.png)

**Comment by lvimuser** [comment]
Seems fine to me on rolling, it opens on the same line `import ()` then, after `<CR>` inside the parenthesis, I get
```
import (
 | 
)
```
