### ISSUE TITLE
File icons are missing

### ISSUE THREAD

**Issue by Marcellofabrizio** [LunarVim/LunarVim#2949]
### Problem description

File icons are missing or corrupted on installation. 

### LunarVim version

master-47e4e5b

### Neovim version (>= 0.7.2)

0.7.2

### Operating system/version

Pop_Os 22.04

### support info

LspInfo:
![image](https://user-images.githubusercontent.com/39314230/186803589-75cdcf0c-d2a2-4399-8b78-dbe94921bce0.png)

LvimInfo:
![image](https://user-images.githubusercontent.com/39314230/186803710-8bd7ff16-00f3-46bf-9429-d3136be79eab.png)

### Screenshots

![image](https://user-images.githubusercontent.com/39314230/186803280-ba84a4ee-77b3-4643-8ea3-23a4f8515f39.png)

**Comment by Marcellofabrizio** [comment]
I figured it out. Turns out I had to install a nerd-font and configure it on my terminal. This tutorial was really strait forward, especially for someone like me who's new to Vim: https://www.youtube.com/watch?v=fR4ThXzhQYI

**Comment by codersea** [comment]
I had the same problem. Did you resolve it ?

**Comment by rebuilt** [comment]
You can also reference the documentation to install nerd fonts:  https://www.lunarvim.org/02-after-install.html#nerd-fonts

**Comment by Marcellofabrizio** [comment]
> I had the same problem. Did you resolve it ?

I just followed the tutorial on the video to download the fonts, but you can also read the documentation @rebuilt linked. Once I had them installed, I just needed to configure them on my terminal, which I did on the terminal custom profile, but this will depend on which one you are using.
