### ISSUE TITLE
Telescope | Whichkey <C-r> conflicts

### ISSUE THREAD

**Issue by xbladesub** [LunarVim/LunarVim#2951]
### Problem description

Cannot paste yanked text into telescope's search field. It has some conflicts with Whichkey plugin. Consider this solution:
https://github.com/nvim-telescope/telescope.nvim/issues/1047#issuecomment-914336070

### LunarVim version

Rolling branch

### Neovim version (>= 0.7.2)

0.7.2

### Operating system/version

macOS 12.5

### Steps to reproduce

1. Yank any text
2. Open telescope with space-s-t
3. C-r to get registers to paste yank to telescope's field

### support info

 
 Language client log: /Users/nshv/.cache/lvim/lsp.log
 Detected filetype:   lua
 
 2 client(s) attached to this buffer: 
 
 Client: copilot (id: 1, pid: 21372, bufnr: [3])
 	filetypes:       
 	autostart:       true
 	root directory:  /Users/nshv
 	cmd:             node /Users/nshv/.local/share/lunarvim/site/pack/packer/opt/copilot.lua/copilot/index.js
 
 Client: sumneko_lua (id: 2, pid: 21375, bufnr: [3])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /Users/nshv/Repos/config
 	cmd:             lua-language-server
 
 Configured servers list: sumneko_lua, omnisharp_mono, clangd, solidity_ls, sourcekit, kotlin_language_server, solc, rust_analyzer

### Screenshots

<img width="1506" alt="Screen Shot 2022-08-26 at 11 23 53 AM" src="https://user-images.githubusercontent.com/45129790/186811006-46bfdf0a-8597-438b-98b0-ab582be42797.png">

**Comment by lvimuser** [comment]
Should be fixed after https://github.com/folke/which-key.nvim/commit/36fdfe833207c120997c669a2c51060813f2f8a7
Can you try that version?

**Comment by xbladesub** [comment]
> Should be fixed after [folke/which-key.nvim@36fdfe8](https://github.com/folke/which-key.nvim/commit/36fdfe833207c120997c669a2c51060813f2f8a7)
> Can you try that version?

I tried to update to the last version - seems not merged yet. However this works for me. Just added to my config file:
```lua
	vim.api.nvim_exec([[
    augroup telescope
        autocmd!
        autocmd FileType TelescopePrompt inoremap <buffer> <silent> <C-r> <C-r>
    augroup END]], false)
```

**Comment by cpea2506** [comment]
> > Should be fixed after [folke/which-key.nvim@36fdfe8](https://github.com/folke/which-key.nvim/commit/36fdfe833207c120997c669a2c51060813f2f8a7)
> > Can you try that version?
> 
> I tried to update to the last version - seems not merged yet. However this code works for me. Just added to my config file:
> 
> ```lua
> 	vim.api.nvim_exec([[
>     augroup telescope
>         autocmd!
>         autocmd FileType TelescopePrompt inoremap <buffer> <silent> <C-r> <C-r>
>     augroup END]], false)
> ```

Could you please update `LunarVim` and remove the code above to see if it work as expected
