### ISSUE TITLE
Error running config for gitsigns.nvim

### ISSUE THREAD

**Issue by nathan22x3** [LunarVim/LunarVim#2954]
### Problem description

- Open any files with `lvim` and the error show up.
- Futhermore, it show the `Error detected while processing Bufreadpost Autocommands for "*"...` error below the status bar when open any `lua` file. Ex: LunarVim's `config.lua` file.

### LunarVim version

master-47e4e5b

### Neovim version (>= 0.7.2)

NVIM v0.8.0-dev

### Operating system/version

Ubuntu 22.04.1

### support info

```console
:LspInfo

Language client log: /home/nathan22x3/.local/state/nvim/lsp.log
 Detected filetype:   zsh
 
 0 client(s) attached to this buffer: 
 
 Configured servers list:
```

```console
:LspInfo

Error executing Lua callback: vim/shared.lua:0: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function <vim/shared.lua:0>
        vim/shared.lua: in function 'tbl_filter'
        ...an22x3/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:115: in function 'make_auto_lsp_info'
        ...an22x3/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:159: in function 'toggle_popup'
        ...x3/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:29: in function <...x3/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:28>
Press ENTER or type command to continue
```

### Screenshots

![image](https://user-images.githubusercontent.com/67423224/186955224-e87dc3af-039a-4534-8545-1364af74c3c7.png)

**Comment by kylo252** [comment]
should be fixed in 439e0c205a4c09545f08816ab5100fb5d9a93d3b
