### ISSUE TITLE
Buffer is not updated automatically on changing git branch

### ISSUE THREAD

**Issue by artistic-nucleus** [LunarVim/LunarVim#2959]
### Problem description

 I'm new to LunarVim/git in general. When I select "checkout another branch" from Whichkey menu and select a branch, the file in the buffer does not update to show the contents of file from that branch, but instead only shows the indicators in gutter. However, if I reload the file by passing `:e` command the buffer is updated

### LunarVim version

master-47e4e5b

### Neovim version (>= 0.7.2)

0.7.2

### Operating system/version

Fedora 35

### support info

-

**Comment by vonPB** [comment]
I can confirm that the buffer is not updating after checking out another commit.
Do you know if this is working in neovim + Telescope?
I can only find the keymaps that LunarVim sets for the Telescope git pickers. I think that is an issue with Telescope itself.

**Comment by artistic-nucleus** [comment]
> Do you know if this is working in neovim + Telescope?

I am not aware if it happens with neovim+telescope
Also, from [telescope's documentation](https://github.com/nvim-telescope/telescope.nvim#git-pickers), `<C-r>` can be used to rebase from the telescope's branches window, and in my case buffer did not update on rebasing as well.

**Comment by cpea2506** [comment]
Surely it's a problem with `Telescope`. By looking at [`git_checkout`](https://github.com/smithbm2316/telescope.nvim/blob/61966821be0384bb41e781fceb279f462a91e5ad/lua/telescope/actions/init.lua#L330-L346) implementation. It run `git checkout <branch>` under the hood and nothing else related to update file. 

All mapping can be found here: [`git_branches`](
https://github.com/nvim-telescope/telescope.nvim/blob/b923665e64380e97294af09117e50266c20c71c7/lua/telescope/builtin/__git.lua#L294-L314) mapping.

**Comment by artistic-nucleus** [comment]
Sorry for the inconvenience, but can someone file this issue on telescope's repo? I'm having confusion with their issue template

**Comment by liyongxing1410** [comment]
After changed the branch you can use `:e` to reload buffer

**Comment by ChristianChiarulli** [comment]
seems like a telescope issue
