### ISSUE TITLE
Disable Core Plugins notify not working 

### ISSUE THREAD

**Issue by glendell03** [LunarVim/LunarVim#2960]
### Problem description

I disable notify using `lvim.builtin.notify.active = false` 
then run `:PackerSync` and `:LvimSyncCorePlugins`

but notify still shows up

### LunarVim version

Stable and rolling-06fa62e

### Neovim version (>= 0.7.2)

v0.7.2

### Operating system/version

wsl2 - Ubuntu 20 lts

### support info

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/58845052/187075267-912bbe9a-5c34-4f08-827a-3e85b40104b6.png)

**Comment by kylo252** [comment]
It's a bit tricky to handle this like the rest, so please restart `lvim` and then run `:PackerSync`.
