### ISSUE TITLE
User defined keymap is not respected if identical to Lunarvim keymap

### ISSUE THREAD

**Issue by jorgsk** [LunarVim/LunarVim#2961]
I like the established C-] jump in C-t jump out keybindings for entering and leaving tags. This has been the standard in Vim for a long time. With Neovim, C-t is mapped to the terminal. So, I added a map:

-- use contrl-t to jump back in the tag stack
lvim.keys.normal_mode["<C-t>"] = ":pop<cr>"

But this is not respected. :map shows that it's still bound to the terminal:
<C-T>       * <Cmd>execute v:count . "ToggleTerm"<CR>

My other maps are working, such as
<C-X>       * :BufferKill<CR>

so it's an issue with overriding the build in map.

My workaround right now is that I for each session enter the configuration and reload it manually.

Is there a way to override <C-t> during startup?

**Comment by cpea2506** [comment]
Disable the open mapping from terminal config and you can get default behavior of `<C-t>`:

https://github.com/LunarVim/LunarVim/blob/ce621c1cfef280732819d920b9ee5b66142be85b/lua/lvim/core/terminal.lua#L10

```lua
lvim.builtin.terminal.open_mapping = false
```

**Comment by jorgsk** [comment]
Setting 

`lvim.builtin.terminal.open_mapping = false`

works perfectly. Thank you so much! :)
