### ISSUE TITLE
Alpha align issue when toggle nvimtree

### ISSUE THREAD

**Issue by clatisus** [LunarVim/LunarVim#2966]
### Problem description

1. enable alpha plugin
2. open lvim
3. the dashboard is centered vertically
4. toggle nvimtree
5. the dashboard now is not centered
6. move cursor to dashboard
7. it's centered again

### LunarVim version

master-47e4e5b

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

macOS 12.5.1

### Steps to reproduce

just enable alpha with dashboard is enough for reproduce

### support info

```console
 Language client log: /Users/junjie_wu/.cache/lvim/lsp.log
 Detected filetype:   alpha
 
 0 client(s) attached to this buffer: 
 
 1 active client(s) not attached to this buffer: 
 
 Client: copilot (id: 1, pid: 39060, bufnr: [])
 	filetypes:       
 	autostart:       true
 	root directory:  /Users/junjie_wu/repos/dotfiles/.config/lvim
 	cmd:             node /Users/junjie_wu/.local/share/lunarvim/site/pack/packer/opt/copilot.lua/copilot/index.js
 
 Configured servers list: clangd
```

(this should be irrelevant)

### Screenshots

open lvim
<img width="1562" alt="Screen Shot 2022-08-30 at 11 47 52" src="https://user-images.githubusercontent.com/15963765/187344912-5597b034-733f-4c21-aa86-9e0eb0974078.png">

toggle nvimtree (not centered, not expected)
<img width="1562" alt="Screen Shot 2022-08-30 at 11 48 17" src="https://user-images.githubusercontent.com/15963765/187344938-b7492ba0-61cf-40c3-8704-197ee65052f3.png">

focus alpha dashboard (centered again)
<img width="1562" alt="Screen Shot 2022-08-30 at 11 48 31" src="https://user-images.githubusercontent.com/15963765/187344957-e6dc3c73-419c-4d5c-81f6-0982cd3049fa.png">

**Comment by cpea2506** [comment]
https://user-images.githubusercontent.com/42694704/188223364-114d8535-ff51-4616-8677-f1016b82bc45.mov

I can't seem to reproduce this on my side. Please provide your dashboard config here.

**Comment by cpea2506** [comment]
Close this since there is no response and can't reproduce. I assume this problem has been solved. Please feel free to open again!
