### ISSUE TITLE
LSP custom settings seemed not working at startup

### ISSUE THREAD

**Issue by JerryLiao26** [LunarVim/LunarVim#2967]
### Problem description

I have some custom lsp ```root_dir``` configurations for ```denols``` and ```tsserver``` to make them work only in corresponding projects. But since my last LunarVim update, these configurations seemed not working properly on lvim startup. Only a manually reload of the config will make it work.

### LunarVim version

rolling-ce621c1

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

Windows 10 Professional 20H2

### Affected language servers

tsserver, denols

### Steps to reproduce

1. Add following configuration for LunarVim
```lua
local lspconfig = require "lspconfig"
lspconfig.tsserver.setup {
  root_dir = lspconfig.util.root_pattern("package.json"),
}
lspconfig.denols.setup {
  root_dir = lspconfig.util.root_pattern("deno.json", "deno.jsonc"),
  single_file_support = false, -- Prevent from starting with tsserver
}
```

2.  Setting up a directory with following structure
![image](https://user-images.githubusercontent.com/8209341/187363399-bddb8fb8-3145-41d2-8a99-004a95158687.png)

3. Open ```lvim``` in above directory

### Actual behavior

Both ```denols``` and ```tsserver``` start at the same time

### Expected behavior

Only ```denols``` should attach

### support info

```console
# :LspInfo
 Language client log: C:\Users\HZ2105~1\AppData\Local\Temp\lvim\lsp.log
 Detected filetype:   typescript
 
 3 client(s) attached to this buffer: 
 
 Client: denols (id: 1, pid: 125312, bufnr: [3])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  D:/Projects/root_dir_test
 	cmd:             deno lsp
 
 Client: tsserver (id: 2, pid: 59812, bufnr: [3])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  D:/Projects/root_dir_test
 	cmd:             cmd.exe /C typescript-language-server --stdio
 
 Client: null-ls (id: 3, pid: 5001, bufnr: [3])
 	filetypes:       typescript, vue, javascriptreact, javascript, typescriptreact, scss, css, handlebars, graphql, json, markdown, html, yaml, less, jsonc
 	autostart:       false
 	root directory:  D:\Projects\root_dir_test
 	cmd:             nvim
 
 Other clients that match the filetype: typescript
 
 Config: tailwindcss
 	Refer to :h lspconfig-root-detection for help.
 	filetypes:         aspnetcorerazor, astro, astro-markdown, blade, django-html, htmldjango, edge, eelixir, ejs, erb, eruby, gohtml, haml, handlebars, hbs, html, html-eex, heex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte
 	root directory:    Not found. Searched for: root_pattern('tailwind.config.js', 'tailwind.config.ts', 'postcss.config.js', 'postcss.config.ts', 'package.json', 'node_modules', '.git').
 	cmd:               cmd.exe /C tailwindcss-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: tailwindcss, tsserver, denols
```

```console
# :LvimInfo
Buffer info
* filetype:                
* bufnr:                   8
* treesitter status:       inactive

Active client(s)
* name:                      denols
* id:                        1
* supported filetype(s):     [javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx]
* attached buffers:          3
* root_dir pattern:          3
* capabilities:              selectionRangeProvider | typeDefinitionProvider     | hoverProvider
                             callHierarchyProvider  | workspaceSymbolProvider    | implementationProvider
                             foldingRangeProvider   | documentFormattingProvider | definitionProvider
                             renameProvider         | documentHighlightProvider  | referencesProvider
* name:                      tsserver
* id:                        2
* supported filetype(s):     [javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx]
* attached buffers:          3
* root_dir pattern:          3
* capabilities:              inlayHintProvider          | renameProvider            | implementationProvider
                             callsProvider              | workspaceSymbolProvider   | hoverProvider
                             foldingRangeProvider       | definitionProvider        | referencesProvider
                             typeDefinitionProvider     | documentHighlightProvider | documentRangeFormattingProvider
                             documentFormattingProvider | documentSymbolProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active:
```

**Comment by lvimuser** [comment]
Have you looked through https://www.lunarvim.org/languages/#server-override ?

**Comment by JerryLiao26** [comment]
> Have you looked through https://www.lunarvim.org/languages/#server-override ?

@lvimuser  Sorry I'm a newbie here. I ran the below command in the project directory
```:lua print(vim.inspect(lvim.lsp.automatic_configuration.skipped_servers))```
and it outputs
```{ "angularls", "ansiblels", "ccls", "csharp_ls", "cssmodules_ls", "denols", "ember", "emmet_ls", "eslint", "eslintls", "golangci_lint_ls", "graphql", "jedi_language_server", "ltex", "ocamlls", "phpactor", "psalm", "pylsp", "quick_lint_js", "rome", "reason_ls", "scry", "solang", "solidity_ls", "sorbet", "sourcekit", "sourcery", "spectral", "sqlls", "sqls", "stylelint_lsp", "tflint", "svlangserver", "verible", "vuels" }```
Does this mean that ```denols``` configuration will not be followed? It's weird because the ```tsserver``` is not following the root pattern I defined either

**Comment by lvimuser** [comment]
> it's weird because the `tsserver` is not following the root pattern I defined either

Yes, because tsserver is setup/started automatically unles you skip/override it. To the first step would do to that, so that change its settings: `vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "tsserver" })`.
Then, setup with lvim's [lsp manager](https://github.com/LunarVim/LunarVim/blob/rolling/lua/lvim/lsp/manager.lua)
```lua
require("lvim.lsp.manager").setup("tsserver", opts)
require("lvim.lsp.manager").setup("denols", opts)
```

https://www.lunarvim.org/languages/#server-setup

**Comment by JerryLiao26** [comment]
@lvimuser I tried with this config and with no luck, ```tsserver``` and ```denols``` still start together no matter I'm in a deno project or a nodejs project root.
```lua
vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "tsserver", "denols" })
local lspconfig = require "lspconfig"
require("lvim.lsp.manager").setup("tsserver", {
  root_dir = lspconfig.util.root_pattern("package.json"),
})
require("lvim.lsp.manager").setup("denols", {
  root_dir = lspconfig.util.root_pattern("deno.json", "deno.jsonc"),
  single_file_support = false, -- Prevent from starting with tsserver
})
```

**Comment by JerryLiao26** [comment]
I'm also finding with my eldest config on this commit 68e8132b909dab6a748340f81c4b3a6ef452079d things are working fine.

**Comment by lvimuser** [comment]
> @lvimuser I tried with this config and with no luck, `tsserver` and `denols` still start together no matter I'm in a deno project or a nodejs project root.

Did you also run `:LvimCacheReset`?


> I'm also finding with my eldest config on this commit [68e8132](https://github.com/LunarVim/LunarVim/commit/68e8132b909dab6a748340f81c4b3a6ef452079d) things are working fine.

Sorry, is it ok now or..?

**Comment by JerryLiao26** [comment]
@lvimuser Sorry for late reply. Yes, I ran ```:LvimCacheReset``` after config changed. And no, I'm now running on an old commit of LunarVim

**Comment by mattarroz** [comment]
I think I have the same problem. My arduino language server does not start, complaining about `cmd not defined for "arduino_language_server". Manually set cmd in the setup {} `. This message appears even though I did setup `cmd` properly in `config.lua`. However, after I reload the LunarVim configuration using leader-L-r, the arduino language server does start and runs without problems.

**Comment by JerryLiao26** [comment]
I happend to try it today on my new machine and it's working in the WSL Linux environment. So i think it could be a bug related to Windows system. Hope this helps.

**Comment by mattarroz** [comment]
Today, I tried commenting out the lines 
```
local lspconfig = require 'lspconfig'
lspconfig.arduino_language_server.setup {
  cmd = {
    "/home/xxx/.local/bin/arduino-language-server",
    "-cli-config", "/home/xxx/.arduino15/arduino-cli.yaml",
    "-fqbn", "esp32:esp32:esp32",
    "-cli", "/home/xxx/.local/bin/arduino-cli",
    "-clangd", "clangd",
  },
}
```
in my `config.lua`. Then, even after reloading my config using leader-L-r the arduino language server does not start. This probably means my settings are indeed correct and the error is indeed related to the lvim startup. In contrast, when the lines are commented in, the arduino language server does not start at first (with the error message described previously), but then loads after reloading the config using leader-L-r.

I'm using Lvim master-e4a5fe9 and nvim v0.8.0-dev-1162-g2a3cb0893 under Debian 11.

Maybe it is a data race. That is, the LSP is started before the config.lua file is parsed?

**Comment by JerryLiao26** [comment]
> I happend to try it today on my new machine and it's working in the WSL Linux environment. So i think it could be a bug related to Windows system. Hope this helps.

Oops, I find out when I started lvim next time the problem appears again.

**Comment by JerryLiao26** [comment]
I happened to have some time to dig out some lua code tonight. I found out the problem was because I configured ```tsserver``` and ```denols``` both in ```ensure_installed``` and ```skipped_servers``` table so they would both not be skipped. Since they're not skipped, LunarVim generates ftplugin files automatically for me which will call lsp servers setup without user configurations.
@lvimuser Thanks for your time!
