### ISSUE TITLE
Cannot load treesitter with latest version of nvim

### ISSUE THREAD

**Issue by Cronnay** [LunarVim/LunarVim#2968]
### Problem description

Updated nvim. After that I cannot open nvim-tree, nor "which-key", all due to nvim-treesitter. 
Error when opening a file with `lvim .`:
```
Error executing vim.schedule lua callback: ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:92: Vim(append):Error executing lua callback: .../start/nvim-treesitter/lua/nvim-treesitter
/highlight.lua:14: attempt to index local 'hlmap' (a nil value)
stack traceback:
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:14: in main chunk
        [C]: in function 'resolve_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:485: in function 'detach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:499: in function 'reattach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:109: in function <...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:108>
        [C]: in function '__newindex'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:92: in function 'create_buffer'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:280: in function 'open_in_current_win'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:102: in function 'open'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:271: in function 'on_enter'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:718: in function <...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:717>
stack traceback:
        [C]: in function '__newindex'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:92: in function 'create_buffer'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:280: in function 'open_in_current_win'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:102: in function 'open'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:271: in function 'on_enter'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:718: in function <...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:717>
```
I understand that you are not the developers of treesitter, but since its packaged with Lunarvim I thought there could be something that needs to be fixed on your side.

### LunarVim version

master-47e7e5b

### Neovim version (>= 0.7.2)

NVIM v0.8.0-dev

### Operating system/version

Ubuntu 20.04

### Steps to reproduce

1. Update nvim
2. Crash

### support info

```console
# LspInfo 
E5108: Error executing lua ...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:229: Vim(append):Error executing lua callback: ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:
485: loop or previous error loading module 'nvim-treesitter.highlight'
stack traceback:
        [C]: in function 'resolve_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:485: in function 'detach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:499: in function 'reattach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:109: in function <...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:108>
        [C]: in function 'nvim_buf_set_option'
        ...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:229: in function <...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:147>
        .../site/pack/packer/start/nvim-lspconfig/lua/lspconfig.lua:19: in function <.../site/pack/packer/start/nvim-lspconfig/lua/lspconfig.lua:18>
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'nvim_buf_set_option'
        ...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:229: in function <...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:147>
        .../site/pack/packer/start/nvim-lspconfig/lua/lspconfig.lua:19: in function <.../site/pack/packer/start/nvim-lspconfig/lua/lspconfig.lua:18>
        [string ":lua"]:1: in main chunk
```
and then I get:
![image](https://user-images.githubusercontent.com/14805941/187381700-2470695f-1d6a-4e80-bc2f-fd23b3969b1b.png)

LvimInfo
Same error as LSP info, and then:
![image](https://user-images.githubusercontent.com/14805941/187381892-a2ef1573-44b8-4d40-92a2-1382a9412be2.png)

### Screenshots

![image](https://user-images.githubusercontent.com/14805941/187382012-0e051ada-24c3-4035-b12b-7e1b1db60e45.png)
When I try to open LvimInfo. After closing the warning, I get the LvimInfo correctly

**Comment by kylo252** [comment]
This should've already been fixed in https://github.com/LunarVim/LunarVim/commit/df84e4ec

I'm not sure which lunarvim version you're using, I can't find the commit hash based on the version you provided https://github.com/LunarVim/LunarVim/commit/47e7e5b

**Comment by Cronnay** [comment]
Sorry, was a typo. Its 47e4e5b

I tried updating, both inside lvim but also from command-line. I get the error and it wont update. How should I proceed to update?

**Comment by kylo252** [comment]
> Sorry, was a typo. Its [47e4e5b](https://github.com/LunarVim/LunarVim/commit/47e4e5b83808f784010aa480753beaaef16ac579)
> 
> I tried updating, both inside lvim but also from command-line. I get the error and it wont update. How should I proceed to update?

I'm not really sure how to get around this without manually updating the plugin, see the steps mentioned (replace nvim-cmp with nvim-treesitter): https://www.lunarvim.org/troubleshooting/#getting-errors-after-an-update

**Comment by Cronnay** [comment]
It was a mess. I tried to update packages, tried to update lunarvim. It was pretty much broken. So I just uninstalled and reinstalled it. Far easier

Ty your help. Will close this
