### ISSUE TITLE
<CR> doesnt change line if cmp menu open

### ISSUE THREAD

**Issue by argapost** [LunarVim/LunarVim#2977]
### Problem description

When the cmp menu is open and I press \<CR\> to go to next line without selecting an item nothing is happening.

Is this the desired behaviour? If yes, can I change it somehow to go to next line?

thanks in advance!

### LunarVim version

rolling-90e060c

### Neovim version (>= 0.7.2)

NVIM v0.8.0-dev-990-g6b7eed188

### Operating system/version

manjaro

### support info

--

**Comment by Imericxu** [comment]
Same issue using stable version on macOS Monterey 12.5.1

**Comment by danielo515** [comment]
Same here in rolling.
I think it doesn't need to have the cmp window open. If you expand a snippet, as soon as you end "completing" it the enter key does nothing, you have to exit insert mode using esc

**Comment by danielo515** [comment]
Found the bug for both issues (cd doing nothing and snippet text being overriden). I opened a PR to fix both

**Comment by kylo252** [comment]
you could dismiss cmp by pressing `<c-e>` 
https://github.com/LunarVim/LunarVim/blob/62a17376997fb7cf01e288cb2f6c769e8ec7a39e/lua/lvim/core/cmp.lua#L265

----

> Found the bug for both issues (cd doing nothing and snippet text being overriden). I opened a PR to fix both

thanks! we just need to make sure we're not breaking luasnip 😟

**Comment by danielo515** [comment]
> thanks! we just need to make sure we're not breaking luasnip 😟

Jup, I use luasnip heavily myself, so I tested it quite extensively

**Comment by argapost** [comment]
Thanks for the PR, everything looks good now!
