### ISSUE TITLE
Unable to change Telescope theme

### ISSUE THREAD

**Issue by vricop** [LunarVim/LunarVim#2985]
### Problem description

I'm not able to change the default Telescope theme for searching for files.

Here's my config:

```lua
lvim.keys.normal_mode["<Leader>f"] = ":Telescope find_files theme=dropdown previewer=false<CR>"
```

If I close and open lvim back it won't work unless I open config.lua and save it. Then it won't work anymore once I close and open lvim.

¿Can anyone help me please? I tried everything, I don't know what else to do.

Thanks in advance

### LunarVim version

master-b3bcead

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

macOS 12.5.1

### Steps to reproduce

1. Set my theme in a key binding
`lvim.keys.normal_mode["<Leader>f"] = ":Telescope find_files theme=dropdown"`
2. Save
3. Close lvim
4. Open and type `<Space>f`

### support info

```console
# :LspInfo

Language client log: /Users/victor/.cache/lvim/lsp.log
Detected filetype:   alpha
 
0 client(s) attached to this buffer: 
 
Configured servers list: tsserver
```

```console
# :LvimInfo
   __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                alpha
* bufnr:                   1
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

**Comment by vricop** [comment]
## Update

I actually does work, what I just realized is that it only work once you've got a buffer open (or a file), if i trigger `<leader>f` from LunarVim's dashboard it won't apply. So the question is ¿how can I trigger it from the Dashboard?

**Comment by cpea2506** [comment]
Because Dashboard has set its own keymap with `<leader>f` as you see below in button entries.

https://github.com/LunarVim/LunarVim/blob/90c9bd943e83a6d2c626792d91b80f9af621343d/lua/lvim/core/alpha/dashboard.lua#L52-L55

So what you need to do is to override the corresponding button with your change.

```lua
lvim.builtin.alpha.dashboard.section.buttons.entries[1] =
{ "SPC f", "  Find File", "<CMD>Telescope find_files theme=dropdown previewer=false<CR>" }

```

**Comment by vricop** [comment]
> Because Dashboard has set its own keymap with `<leader>f` as you see below in button entries.
> 
> https://github.com/LunarVim/LunarVim/blob/90c9bd943e83a6d2c626792d91b80f9af621343d/lua/lvim/core/alpha/dashboard.lua#L52-L55
> 
> So what you need to do is to override the corresponding button entry with your change.
> 
> ```lua
> lvim.builtin.alpha.dashboard.section.buttons.entries[1] =
> { "SPC f", "  Find File", "<CMD>Telescope find_files theme=dropdown previewer=false<CR>" }
> ```

Great, that worked! I didn't know about that, I'm new to the Nvim and LunarVim world and am really starting to love it.

Thank you very much! you really saved my day. I even learned something new in the process.

I really appreciate for taking your time
