### ISSUE TITLE
Insert mode current line has file path/name overlaid over text

### ISSUE THREAD

**Issue by karlskewes** [LunarVim/LunarVim#2986]
### Problem description

In INSERT mode file or directory names are shown over the top of text, obscuring input.

### LunarVim version

master-504946d (and rolling)

### Neovim version (>= 0.7.2)

NVIM v0.8.0-dev - commit: ea10e0c104897528a20bb1d9618e2b941eed1b3a

### Operating system/version

NixOS 

### Steps to reproduce

Steps to reproduce:
1. Install stable or rolling lunarvim
2. use default configuration
3. packer sync, compile, lvimcachereset
4. open any file
5. enter insert mode
6. start typing and see text being overlaid with `filename - NVIM` or similar. Empty buffers have `[No Name] - NVIM`
7. <cr> to go to next line and see previous line is fine
8. NORMAL mode is fine

### support info

```console
# LspInfo 
 Use [q] or [Esc] to quit the window
 
 Language client log: /home/karl/.local/state/nvim/lsp.log
 Detected filetype:   lua
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: lua
 
 Config: sumneko_lua
 	filetypes:         lua
 	root directory:    /home/karl/src/github.com/karlskewes/nixos
 	cmd:               lua-language-server
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: sumneko_lua
```

```console
# LvimInfo
Buffer info
* filetype:                lua
* bufnr:                   1
* treesitter status:       active

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: [lua_format, stylua]

Linters info
* Active: 
* Supported: [luacheck, selene]

Code actions info
* Active: 
```

### Screenshots

https://asciinema.org/a/0vjcTBX5LeMwIfWrCJ8TJR3eR

**Comment by LoneExile** [comment]
try this
```lua
lvim.builtin.cmp.experimental.ghost_text = false
lvim.lsp.diagnostics.virtual_text = false
```

**Comment by karlskewes** [comment]
Added and retried with neovim 7.2 and example lunarvim config.
Tried with my config.
Tried with neovim 8.0-dev, fresh rolling lunarvim and my config.

Is there a way to turn on some kind of key press -> action level logging?
I can open any file and then just type a couple of characters to get it to start happening.

**Comment by karlskewes** [comment]
Thank you for the suggestions though LoneExile. Will look into how those work and see if I've missed something.
I did delete a bunch of `~/.local` nvim & lunarvim directories, cache reset, packer clean, compile, etc. Not 100% clear on exact best practice.

**Comment by MaliciousXatt** [comment]
> try this
> 
> ```lua
> lvim.builtin.cmp.experimental.ghost_text = false
> lvim.lsp.diagnostics.virtual_text = false
> ```

This did not solve the issue for me.

**Comment by LoneExile** [comment]
> 
> This did not solve the issue for me.

follow with this
1. delete `lvim/plugin/packer_compiled.lua` in your config directory
2. open lvim run `:LvimCacheReset` -> exit lvim
3. open lvim run `:PackerSync` then reopen

**Comment by MaliciousXatt** [comment]
> 

This did also not work.

**Comment by LoneExile** [comment]
> Is there a way to turn on some kind of key press -> action level logging? I can open any file and then just type a couple of characters to get it to start happening.

Did you mean "auto-completion"?

**Comment by MaliciousXatt** [comment]
reinstalling Neovim also did not work for me, sadly.

**Comment by MaliciousXatt** [comment]
![image](https://user-images.githubusercontent.com/111096156/188903266-8d009624-8886-4972-9756-95379e2d894c.png)

This is what is creating the problem, the [ location ] part.
When you pass by that part it becomes buggy.
I reinstalled lunarvim to test it out. and it still happens.

**Comment by MaliciousXatt** [comment]
Also as you notice, at the bottom: test.py (~/.config) - NVIM
This is not there if I'm in xorg instead of wayland.

**Comment by MaliciousXatt** [comment]
[Screencast from 2022-09-07 16-28-21.webm](https://user-images.githubusercontent.com/111096156/188904039-a5a60f1c-0d99-4332-bd58-fbee857315da.webm)

**Comment by LoneExile** [comment]
It looks like they may have a problem with lualine.

Let's add this to your config. It's going to remove lualine.
```lua
lvim.builtin.lualine.sections = {
  lualine_a = {},
  lualine_b = {},
  lualine_c = {},
  lualine_x = {},
  lualine_y = {},
  lualine_z = {},
}
lvim.builtin.lualine.inactive_sections = {
  lualine_a = {},
  lualine_b = {},
  lualine_c = {},
  lualine_x = {},
  lualine_y = {},
  lualine_z = {},
}
```

**Comment by MaliciousXatt** [comment]
[Screencast from 2022-09-07 16-43-55.webm](https://user-images.githubusercontent.com/111096156/188907677-e0c46d63-47ef-415a-b41f-89bdebdd2311.webm)

added that to the config, the lualine is gone, but it's still buggy...

**Comment by MaliciousXatt** [comment]
Okay so I switched back to xorg, now I've noticed I got the problem at xorg too now.... very strange

**Comment by MaliciousXatt** [comment]
What I've noticed is that bufferline is not working after fresh install of lunarvim and neovim.
It says 

(on startup)
bufferline
'indicator_icon' will be deprecated: It should be changed to indicator and icon specified as indicator.icon, with indicator.style = 'icon'

:PackerSync
 ✗ Failed to update akinsho/bufferline.nvim/main


maybe this is what is causing the problems? 
Does anyone know how to fix this? I've looked in the configs, but couldn't find any akinsho/bufferline.nvim/main 
only akinsho/bufferline.nvim

**Comment by rebuilt** [comment]
@MaliciousXatt 
https://github.com/abzcoding/lvim/issues/79

**Comment by MaliciousXatt** [comment]
@rebuilt 
This is not something that helps me? what specific do you mean?
I don't have problems with cargo?
The rolling release did fix packerSync failed to update.
But I'm still getting the "'indicator_icon' will be deprecated: It should be changed to indicator and icon specified as indicator.icon, with indicator.style = 'icon'"

**Comment by MaliciousXatt** [comment]
And the bug of the file location - NVIM is still in screen. :/

**Comment by MaliciousXatt** [comment]
![image](https://user-images.githubusercontent.com/111096156/188962557-98d5be60-59e1-467d-8247-8cd16efc3d0f.png)

[No name] - - NVIM is everywhere...

**Comment by karlskewes** [comment]
Might have found it.
```
vim.opt.title = false
```
Or for testing use `:set notitle` to fix the current buffer. 
Can others please try?

Found via: https://github.com/neovim/neovim/issues/18573 & https://github.com/neovim/neovim/issues/19372#issuecomment-1185253284

```
$ echo $TERM
xterm-256color

$ ncurses-config --version
6.3.20220507
```

**Comment by MaliciousXatt** [comment]
Great! Ill try it out, if i fixed my neovim.

**Comment by MaliciousXatt** [comment]
Yes! Thank you @karlskewes , this worked!
vim.opt.title = false 
did the job.

**Comment by anthr76** [comment]
+1 `vim.opt.title = false` fixed on Fedora 37. Does anyone have an idea of what was causing this?

**Comment by karlskewes** [comment]
It looks related to terminal/ ncurses per https://github.com/neovim/neovim/issues/18573

**Comment by karlskewes** [comment]
Because the bug/behaviour change lies elsewhere shall we close this issue?
Or is it useful to anyone staying open?
I'm easy either way.

**Comment by MaliciousXatt** [comment]
I'd suggest leaving it open, or add it as an additional note to the code, as default in the config.lua with a #

**Comment by pzhzqt** [comment]
> Might have found it.
> 
> ```
> vim.opt.title = false
> ```

Thank you so much!

**Comment by shresth-kumar-lal** [comment]
> Might have found it.
> 
> ```
> vim.opt.title = false
> ```
> 
> Or for testing use `:set notitle` to fix the current buffer. Can others please try?
> 
> Found via: [neovim/neovim#18573](https://github.com/neovim/neovim/issues/18573) & [neovim/neovim#19372 (comment)](https://github.com/neovim/neovim/issues/19372#issuecomment-1185253284)
> 
> ```
> $ echo $TERM
> xterm-256color
> 
> $ ncurses-config --version
> 6.3.20220507
> ```
Thank you so much. Worked on fedora 37

Kudos
