### ISSUE TITLE
bufferline's 'indicator_icon' will be deprecated

### ISSUE THREAD

**Issue by bytooo** [LunarVim/LunarVim#2993]
### Problem description

When starting lvim I get the following warning: 
```
'indicator_icon' will be deprecated: It should be changed to indicator and icon specified as indicator.icon, with indicator.style = 'icon'
```

I expected no warning to happen.

### LunarVim version

master-50494d6

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Arch Linux x86_64

### Steps to reproduce

1. Start lvim

### support info

None

### Screenshots

![2022-09-07-01:26:15-screenshot](https://user-images.githubusercontent.com/42752426/188804471-bd7d1759-7cdd-4bba-aad2-8b3501e19c0e.png)

**Comment by bytooo** [comment]
Easily fixable by changing `indicator_icon = "▎",` to `indicator = {
      style = 'icon',
      icon = '|',
    },` 
at `lunarvim/lvim/lua/lvim/core` according to [this issue](https://github.com/akinsho/bufferline.nvim/issues/524#issuecomment-1226030614)

**Comment by cpea2506** [comment]
Until the new fix get into place. I recommend adding these things to your `config.lua` instead of `core` folder (That could prevent you from getting new update).

```lua
lvim.builtin.bufferline.options.indicator_icon = nil
lvim.builtin.bufferline.options.indicator = { style = "icon", icon = "▎" }
```

**Comment by bytooo** [comment]
Thank you @cpea2506 I tried doing that first but forgot the first line 🙃 so I got some error saying that an option was missing or something like that.
