### ISSUE TITLE
LunarVim acting weird on wayland.

### ISSUE THREAD

**Issue by MaliciousXatt** [LunarVim/LunarVim#2996]
### Problem description

![Screenshot from 2022-09-07 15-20-13](https://user-images.githubusercontent.com/111096156/188888773-0166b72b-f463-460f-8a51-b163f39363cd.png)

### LunarVim version

master-b3bcead

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Fedora 37 Wayland

### Steps to reproduce

It just pops up on wayland (not in my xorg session) see screenshot for the detail.
Just write code and it comes.

### support info

![image](https://user-images.githubusercontent.com/111096156/188889245-9b37f7aa-8c64-4d4e-ac89-d6cda50222fe.png)
![image](https://user-images.githubusercontent.com/111096156/188889324-c7c7d820-7a4a-4073-a585-5ef990b1e0ea.png)

### Screenshots

![Screenshot from 2022-09-07 15-20-13](https://user-images.githubusercontent.com/111096156/188889357-cc26b883-9e7e-4a29-a9ce-a348ae29ed20.png)

**Comment by lvimuser** [comment]
Possibly related #2986

**Comment by lvimuser** [comment]
Closing this in favor of #2986.
