### ISSUE TITLE
latex snippets not working as expected

### ISSUE THREAD

**Issue by argapost** [LunarVim/LunarVim#2997]
### Problem description

Hi,

I am trying to implement the first 2 latex snippets as seen here: https://github.com/L3MON4D3/LuaSnip/wiki/Cool-Snippets

so I put int .config/lvim/luasnippets/tex.lua the following:

```lua
local tex = {}
tex.in_mathzone = function()
	return vim.fn["vimtex#syntax#in_mathzone"]() == 1
end
tex.in_text = function()
	return not tex.in_mathzone()
end

local rec_ls
rec_ls = function()
	return sn(nil, {
		c(1, {
			-- important!! Having the sn(...) as the first choice will cause infinite recursion.
			t({ "" }),
			-- The same dynamicNode as in the snippet (also note: self reference).
			sn(nil, { t({ "", "\t\\item " }), i(1), d(2, rec_ls, {}) }),
		}),
	})
end

return {
	s("ls", {
		t({ "\\begin{itemize}", "\t\\item " }),
		i(1),
		d(2, rec_ls, {}),
		t({ "", "\\end{itemize}" }),
		i(0),
	}),
	s("dm", {
		t({ "\\[", "\t" }),
		i(1),
		t({ "", "\\]" }),
	}, { condition = tex.in_text }),
}
```

For the first one after the first item when I press \<CR\>, no new item is inserted and for the second, the snippet expands both in math and in text mode whereas it should only expand in math mode.

Can anyone reproduce?

Thanks in advance!

### LunarVim version

rolling-2519e07

### Neovim version (>= 0.7.2)

NVIM v0.8.0-dev-990-g6b7eed188

### Operating system/version

manjaro

EDIT: path for snippets

**Comment by cpea2506** [comment]
https://www.lunarvim.org/configuration/08-custom-snippets.html#lua-version

The path should be `~/.config/lvim/luasnippets/`

**Comment by argapost** [comment]
> https://www.lunarvim.org/configuration/08-custom-snippets.html#lua-version
> 
> The path should be `~/.config/lvim/luasnippets/`

yeah typo sorry that's the path I have

**Comment by argapost** [comment]
I figured how to fix the second one: I need to add the show_condition = tex.in_text in order cmp not to show the snippet when in math mode. So scratch that.

Regarding the first one, am I right that LunarVim doesn't set a keymap to cycle through choice nodes? maybe it has to do something; I will look into it further.

**Comment by lvimuser** [comment]
> For the first one after the first item when I press <CR>, no new item is inserted and for the second, the snippet expands both in math and in text mode whereas it should only expand in math mode.

iirc, expand condition is only for `autosnippets`. If you want to not show on completion, should be `show_condition`.

**Comment by lvimuser** [comment]
> Regarding the first one, am I right that LunarVim doesn't set a keymap to cycle through choice nodes? maybe it has to do something; I will look into it further. EDIT: it doesn't

I think you need something like 
```lua
vim.keymap.set("i", "<c-k>", require("luasnip.extras.select_choice"))
```

and the snippet seems a bit strange for me, I need to expand then do some jumps before a choice node is available/present.

In any case, I don't think it's a LunarVim issue.

**Comment by argapost** [comment]
Ok I ll give it a try thanks
