### ISSUE TITLE
Failed to update akinsho/bufferline.nvim/main

### ISSUE THREAD

**Issue by anupj** [LunarVim/LunarVim#3003]
### Problem description

Steps to reproduce the error:
1. Open *any* file using lvim
2. Press <space>pu ( to run PackerUpdate)
3. Packer runs its update and spits out this error message in the end 
 > Failed to update akinsho/bufferline.nvim/main

### LunarVim version

master-50494d6

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

macOS Monterey 12.5.1

### support info

z

### Screenshots

![Screenshot 2022-09-10 at 08 57 54](https://user-images.githubusercontent.com/177374/189474755-9124e7ff-61e7-4072-a666-38bfdb6d0422.png)

**Comment by lvimuser** [comment]
This is usually caused by a force push on the repo.

Go to `~/.local/share/lunarvim/site/pack/packer/{start,opt}/bufferline.nvim` and remove the directory or manually update (`git reset --hard origin main`)

**Comment by anupj** [comment]
@lvimuser  thanks for your response. Here's more info on the error message.

![Screenshot 2022-09-11 at 05 19 55](https://user-images.githubusercontent.com/177374/189512251-785c092c-6b90-4316-9500-e98e7728ef59.png)

**Comment by lvimuser** [comment]
> @lvimuser thanks for your response. Here's more info on the error message.
> 
> ![Screenshot 2022-09-11 at 05 19 55](https://user-images.githubusercontent.com/177374/189512251-785c092c-6b90-4316-9500-e98e7728ef59.png)

I suggest doing a `git fetch --all` then a reset, or deleting the directory.

**Comment by lvimuser** [comment]
Did it work?

**Comment by anupj** [comment]
@lvimuser I followed the steps that you recommended and the error persisted. But after the latest lvim update, the error seems to have gone away. Not sure if it was a combination of your suggestions and latest update made it happen. Thanks for your answer though.
