### ISSUE TITLE
adding Odin programming language support

### ISSUE THREAD

**Issue by Airbus5717** [LunarVim/LunarVim#3005]
### Feature Description

I wish someone can add the odin programming language syntax highlighter (at least the syntax highlighting part)

### Support information

https://github.com/Tetralux/odin.vim

**Comment by lvimuser** [comment]
Unlikely, why should this be a default? You can add it as a plugin.
Might want to look into https://github.com/ap29600/tree-sitter-odin

**Comment by ChristianChiarulli** [comment]
this should be added as a plugin, default highlighting is provided via treesitter, odin should into treesitter
