### ISSUE TITLE
No support for clippy in Rust?

### ISSUE THREAD

**Issue by btegs** [LunarVim/LunarVim#3006]
When using Rust files, we have access to rustfmt and rust_analyzer. Is there a reason we cannot use clippy as an additional utility?

**Comment by cpea2506** [comment]
It's a part of `rust_analyzer` server setting.

1. run `:LspSettings rust_analyzer`
2. Go to `~/.config/lvim/lsp-settings/`
3. Add this line

```json
{
  "rust-analyzer.checkOnSave.command": "clippy"
}
```
4. Go to Rust project make some common mistakes and see.

<img width="975" alt="Screenshot 2022-09-10 at 22 19 58" src="https://user-images.githubusercontent.com/42694704/189489938-4d26462c-4c72-4082-8468-c725d1bceed4.png">

**Comment by btegs** [comment]
Thanks @cpea2506!

I was wondering if this could eventually be added to the main docs at https://www.lunarvim.org/languages/rust.html for those that want to utilize Clippy. Could be handy! :-)

**Comment by cpea2506** [comment]
> Thanks @cpea2506!
> 
> I was wondering if this could eventually be added to the main docs at https://www.lunarvim.org/languages/rust.html for those that want to utilize Clippy. Could be handy! :-)

I'm not sure. You can raise an issue in the document repository and mention this.

https://github.com/LunarVim/lunarvim.org

**Comment by lvimuser** [comment]
> I was wondering if this could eventually be added to the main docs at https://www.lunarvim.org/languages/rust.html for those that want to utilize Clippy. 

Yes, please make a PR.

---

We could/should bring more visibility to `nlspsettings` in general (which provides schemas for `jsonls`, aiding discoverability) but doesn't make sense to replicate every lsp config on our docs. A simple search for 'rust analyzer clippy' returns good enough results.

In this case I think it's fine because
1. provides an example so the user is aware and may check out other options.
2. the field doesn't mention 'clippy' in its completion, since it accepts arbitrary strings.

**Comment by jonesmartins** [comment]
To avoid running `:LspSettings rust_analyzer` and changing the `rust_analyzer.json` file, you can change it in the plugin settings (such as [this](https://github.com/LunarVim/LunarVim/issues/2894#issuecomment-1235012155),) although I did not get it to work. 

Also, the current `rust-tools` setup at https://www.lunarvim.org/languages/rust.html is outdated. If I could get it to work, I could make a PR. 
When I save a rust file, LunarVim notifies me that "module 'nvim-lsp-installer.servers is not installed."

**Comment by DavidEHufnagel** [comment]
> It's a part of `rust_analyzer` server setting. By default, it uses `cargo check` command to lint your file. If you want `cargo clippy` instead, follow these steps:
> 
> 1. Run `:LspSettings rust_analyzer`
> 2. Go to `~/.config/lvim/lsp-settings/rust_analyzer.json`
> 3. Add this line
> 
> ```json
> {
>   "rust-analyzer.checkOnSave.command": "clippy"
> }
> ```
> 
> 4. Go to Rust project makes some common mistakes and see.
> 
> <img alt="Screenshot 2022-09-10 at 22 19 58" width="975" src="https://user-images.githubusercontent.com/42694704/189489938-4d26462c-4c72-4082-8468-c725d1bceed4.png">

This is excellent advice! Can you modify this to always use clippy::pedantic?
