### ISSUE TITLE
Invalid Redirection Target when installing (Mac)

### ISSUE THREAD

**Issue by siq91** [LunarVim/LunarVim#3008]
### Problem description

Hi there,

Receiving this issue when trying to install: `bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`

Receiving this in return:
`fish: Invalid redirection target:
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`

### LunarVim version

1.1.4

### Neovim version (>= 0.7.2)

0.7.2

### Operating system/version

MacOS 12.5.1

### support info

`❯ bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
fish: Invalid redirection target:
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`

**Comment by kobzarchekg** [comment]
run bash before run the install command
```
bash
bash-3.2$
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
```
