### ISSUE TITLE
Jdtls still starts even configured skipped

### ISSUE THREAD

**Issue by qwqawawow** [LunarVim/LunarVim#3011]
version:master-824b2d1

I had configured 
`lvim.lsp.automatic_servers_installation = false`
`lvim.lsp.automatic_configuration.skipped_servers = { "groovyls", "jdtls", "kotlin_language_server"`
And run :LvimResetCache
![Screenshot_20220911_125404.jpg](https://user-images.githubusercontent.com/40905037/189513586-307de20a-a6ef-4462-be94-c32ce328cd0b.jpg)
But the second 'Jdtls' still starts automatically.

**Comment by Lun4m** [comment]
If you haven't resolved this yet, apparently the option `lvim.lsp.automatic_servers_installation` has been moved to `lvim.lsp.installer.setup.automatic_installation`. Then I guess you have to uninstall `Jdtls` through Mason.

**Comment by kylo252** [comment]
please check this configuration https://github.com/LunarVim/starter.lvim/tree/java-ide
