### ISSUE TITLE
Keybinding to toggle between LSP states (LspStart <-> LspStop)

### ISSUE THREAD

**Issue by asch** [LunarVim/LunarVim#3012]
### Feature Description

A keybinding (e.g. \<leader\>L) which will toggle between Lsp enabled and disabled. I.e. call LspStart if stopped and LspStop of started.

**Comment by vonPB** [comment]
I personally never have the need to toggle Lsp on and off. And if, I would probably just run the commands manually `:LspStart/LspStop`. Don't think this has to be added for everyone.

You could just add your own keymaps for these commands. [Docs](https://www.lunarvim.org/configuration/02-keybindings.html#listing-what-is-mapped:~:text=%23-,Whichkey%20Bindings,add%20or%20remap%20keybindings%20for%20whichkey%20use%20lvim.builtin.which_key.mappings,-%23)

If this isn't what you need, please explain a bit more *why* you think this needs to be added.

**Comment by asch** [comment]
For example when writing a text (.md, .txt., .tex …) having Lsp started all the time is very disturbing and would be nice to quickly toggle between the states just for spell checking with ltex-ls.

Also sometimes it is a good idea to skatch out your code in a syntactically incorrect way and fix the problems later. When Lsp is turned on all the time it is annoying.

I understand that it depends on your working style and may not fit everyone. 

So do you have any idea what would the best way to implement such a keybinding since there is no LspToggle command?

**Comment by lvimuser** [comment]
I don't think it warrants a keybind (and doesn't seem like a good idea, I don't think spawning/starting a server will be fast enough for your purposes).

Are you aware of `vim.diagnostic.hide()` and `vim.diagnostic.show()` ?

**Comment by asch** [comment]
Thanks for that, didn't know about these functions. That is even a better way to do it.

BTW plugin `WhoIsSethDaniel/toggle-lsp-diagnostics.nvim` does the same thing.
