### ISSUE TITLE
lvim.lsp.automatic_servers_installation is tried to be read as a list by lsp/manager.lua

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#3013]
### Problem description

I just installed lunarvim rolling, and it seems that my setup for automatic_installation is triggering an error, which you can see more details about below in the logs section.

### LunarVim version

rolling-2519e07

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

macOS 12.4

### Affected language servers

reason_ls

### Steps to reproduce

Just setting this:

```
lvim.lsp.installer.setup.automatic_installation = true
  local lspManager = require "lvim.lsp.manager"
  lspManager.setup("reason_ls", {})

```

Then open any file that is a reason one and set the filetype to reason

### Actual behavior

I get an error as you can see in the log below

### Expected behavior

To get the LSP configured, auto-installed and everything working

### support info

```console
 Use [q] or [Esc] to quit the window
 
 Language client log: /Users/danielo/.cache/lvim/lsp.log
 Detected filetype:   lua
 
 2 client(s) attached to this buffer: 
 
 Client: sumneko_lua (id: 1, pid: 77834, bufnr: [17, 30])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /Users/danielo/.local/share/chezmoi/chezmoi/dot_config/lvim
 	cmd:             lua-language-server
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [17, 30])
 	filetypes:       typescript, javascriptreact, vue, javascript, typescriptreact, lua, go, c, python, java, cpp, php
 	autostart:       false
 	root directory:  /Users/danielo/.local/share/chezmoi
 	cmd:             nvim
 
 Configured servers list: tsserver, sumneko_lua, graphql, jsonls, reason_ls

```

### logs

```console
Error detected while processing /Users/danielo/.local/share/lunarvim/site/after/ftplugin/reason.lua:
E5113: Error while calling lua chunk: ...ielo/.local/share/lunarvim/lvim/lua/lvim/lsp/manager.lua:104: attempt to index field 'automatic_installation' (a boolean value)
stack traceback:
        ...ielo/.local/share/lunarvim/lvim/lua/lvim/lsp/manager.lua:104: in function 'should_auto_install'
        ...ielo/.local/share/lunarvim/lvim/lua/lvim/lsp/manager.lua:108: in function 'setup'
        ...elo/.local/share/lunarvim/site/after/ftplugin/reason.lua:2: in main chunk
```
```


### Screenshots

_No response_

**Comment by Xyhlon** [comment]
same here

**Comment by danielo515** [comment]
Guess what, I was being dumb (am I dumb if I am an average human that makes average mistakes? That's why I love typed languages 😄 )
The property you need to set is `lvim.lsp.installer.setup.automatic_servers_installation = true` not `lvim.lsp.installer.setup.automatic_installation `. The difference is subtle, but one is expected to be a table and the other is expected to be a boolean. The fact the LSP was suggesting it didn't helped either 😅
