### ISSUE TITLE
Ability to sort visual selection

### ISSUE THREAD

**Issue by benediktms** [LunarVim/LunarVim#3017]
### Feature Description

When selecting text, it could be useful to add a keybinding (to which-key) to quickly sort text selection. I am happy to supply a PR for this, if this is a reasonable feature request.

### Describe the alternatives you have considered

Use the standard `%sort` commands

**Comment by lvimuser** [comment]
Is that really needed on which key? If there were a command palette, would that be sufficient?

Also, do consider that `s` is taken by search already (although only on normal mode for now)... We could have 'search current word / visual selection' for example.

**Comment by benediktms** [comment]
Yes, I was planning to only add this as an option in visual mode (which I believe only has the `\` shortcut). I'm not too familiar with the command palette. Are you referring to the options that come up, e.g. when you press the `g` key?

**Comment by benediktms** [comment]
Yes actually I got inspiration from the VSCode command palette for this (very useful feature). In this case probably it makes sense to not add this to which-key if something like legendary will be implemented. 

It's easy enough for users to add this to their `config.lua` file by themselves (adding it below, just to make it searchable):
```lua
lvim.builtin.which_key.vmappings["s"] = {
	name = "Sort",
	a = { "<cmd>'<, '>%sort<cr>", "ASC" },
	d = { "<cmd>'<, '>%sort!<cr>", "DESC" },
	n = { "<cmd>'<, '>%sort n<cr>", "DESC" },
}
```
We can close this for now, if legendary or something similar gets adopted in the future, I'd be happy to contribute towards that.
