### ISSUE TITLE
Custom plugins `config` settings not take effect

### ISSUE THREAD

**Issue by trankchung** [LunarVim/LunarVim#3020]
### Problem description

I'm trying to use [olimorris/onedarkpro.nvim](https://github.com/olimorris/onedarkpro.nvim#configuring-themes) plugin and my `config.lua` is below. The color scheme gets installed, however, none of the settings in the `config` param take effect. 

According to that git repo I could set `theme = "onelight"`, for example, and it should work. Or I can set `light_theme = "onelight"` and set `background = "light"` and it should work. However, nothing in the config block take effect. I tried changing to `onedark_vivid`, `onedark_dark`, and restarted nvim after each changes and nothing take effect; the dark theme stays one color. Doesn't change at all.

Also, I've noticed that it's not just  this theme's `config`. I have `config` in several other plugins but they all don't seem to have any effect. The only thing that LunarVim does is installed the plugins.

`config.lua`
```lua
lvim.colorscheme    = "onedarkpro"
lvim.plugins = {
  {
    "olimorris/onedarkpro.nvim",
    config = function()
      require("onedarkpro").setup({
        theme = "onelight",
        light_theme = "onelight",
        dark_theme = "onedark_vivid"
      })
    end,
  },
}
vim.opt.background = "light"
```

### LunarVim version

rolling-2519e07

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

12.5.1

### Steps to reproduce

1. Install the them
2. Make changes in `config` field
3. Restart vim
4. Nothing changes

### support info

```console
:LspInfo
Language client log: /Users/ctran/.cache/lvim/lsp.log
Detected filetype:   NvimTree

0 client(s) attached to this buffer:

Configured servers list:
```

```console
:LvimInfo
~              ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
~              │                                                                                                                         │
~              │    __                          _    ___                                                                                 │
~              │   / /   __  ______  ____ _____| |  / (_)___ ___                                                                         │
~              │  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \                                                                        │
~              │ / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /                                                                        │
~              │/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/                                                                         │
~              │                                                                                                                         │
~              │                                                                                                                         │
~              │Buffer info                                                                                                              │
~              │* filetype:                                                                                                              │
~              │* bufnr:                   7                                                                                             │
~              │* treesitter status:       inactive                                                                                      │
~              │                                                                                                                         │
~              │Active client(s)                                                                                                         │
~              │                                                                                                                         │
~              │Automatic LSP info                                                                                                       │
~              │* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, gr│
~              │                                                                                                                         │
~              │Formatters info                                                                                                          │
~              │* Active:                                                                                                                │
~              │* Supported: []                                                                                                          │
~              │                                                                                                                         │
~              │Linters info                                                                                                             │
~              │* Active:                                                                                                                │
~              │* Supported: []                                                                                                          │
~              │                                                                                                                         │
~              │Code actions info                                                                                                        │
~              ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
~
```

**Comment by lvimuser** [comment]
Changes on `lvim.plugins` require a `:PackerInstall`, `:PackerSync` and/or `:PackerCompile` to take effect.

https://www.lunarvim.org/plugins/#core-plugins

**Comment by trankchung** [comment]
@lvimuser Thank you very much.

**Comment by trankchung** [comment]
@lvimuser I tried what you suggested and it still doesn't work. I tried all 3 commands you suggested but no dice. Do you know why?

**Comment by lvimuser** [comment]
do you have `vim.cmd.colorscheme "onedarkpro"` ?

**Comment by cpea2506** [comment]
@lvimuser I don't know if the setup function is available only in packer `config` function scope and cannot be accessed globally.

**Comment by cpea2506** [comment]
@lvimuser I don't know if the setup function is available only in packer `config` function scope and cannot be accessed globally.

**Comment by lvimuser** [comment]
> @lvimuser I just think the setup function is available only in packer `config` function scope and cannot be accessed globally.

Not sure... if that were the case it seems tons of stuff would be broken no? You can add a simple print statement there to check.

**Comment by trankchung** [comment]
> do you have `vim.cmd.colorscheme "onedarkpro"` ?

No. I use `lvim.colorscheme    = "onedarkpro”`. I’ll try this out and see if it works.

**Comment by cpea2506** [comment]
> > @lvimuser I just think the setup function is available only in packer `config` function scope and cannot be accessed globally.
> 
> Not sure... if that were the case then lots of stuff would be broken no? You can add a simple print statement there to check.

Ah now I see. There is something prevent the change being loaded when enter lvim and triggering only when we save `config.lua` file

**Comment by trankchung** [comment]
> 

@lvimuser I tried `vim.cmd("colorscheme onedarkpro") and it makes no difference.

**Comment by trankchung** [comment]
> > > @lvimuser I just think the setup function is available only in packer `config` function scope and cannot be accessed globally.
> > 
> > 
> > Not sure... if that were the case then lots of stuff would be broken no? You can add a simple print statement there to check.
> 
> Ah, now I see. There is something that prevents the change from being loaded when entering lvim and triggering only when we save `config.lua` file.
> 
> Edit: I may figure it out. Mostly, that problem comes with colorscheme setup. The reason is `vim.cmd [[colorscheme ...]]` was called before the plugin was loaded as specified in `Packer` document.
> 
> > config = string or function, -- Specifies code to run after this plugin is loaded

Is there a way to fix this? It's not just the color scheme not working. I tried to set the `colors = { ... }` option as well and it doesn't work either. I also tried many other options and none of them seem to work.

**Comment by cpea2506** [comment]
A temporarily fix is 

```lua
lvim.plugins = {
  {
    "olimorris/onedarkpro.nvim",
    config = function()
      require("onedarkpro").setup({
        theme = "onelight",
        light_theme = "onelight",
        dark_theme = "onedark_vivid"
      })

      -- put it here
      vim.cmd("colorscheme onedarkpro")
    end,
  },
```

**Comment by trankchung** [comment]
@cpea2506 That works but if I ever need to change the theme I have to change it there instead of using `lvim.colorscheme`. Also, if I change the them I have to recompile again; which is not a big deal. Just FYI that's all. Thanks for digging into this.
