### ISSUE TITLE
button q randomly appears on start page

### ISSUE THREAD

**Issue by meijieru** [LunarVim/LunarVim#3027]
### Problem description

Using Startify style, the quit button sometimes doesn't appear.

### LunarVim version

rolling-9813096

### Neovim version (>= 0.7.2)

NVIM v0.8.0-dev-1092-g89b9eab638

### Operating system/version

wsl2

### Steps to reproduce

1. `lvim`

### support info

None

**Comment by rebuilt** [comment]
I'm going to assume the start page you're talking about is the [alpha plugin](https://github.com/goolord/alpha-nvim)

When you say it happens randomly, do you mean that every time you start `lvim` the quit button can toggle between being there or not?   

Or do you mean that at some point in the past, there was a quit button, but now you don't see it.  

LunarVim changed from using the (dashboard plugin)[https://github.com/glepnir/dashboard-nvim] to the alpha plugin.  

Make sure to clear the cache  `:LvimCacheReset`   and then check `:PackerStatus` to see if your version of Lunarvim is using the old version of the dashboard or the current dashboard plugin; alpha.

**Comment by ChristianChiarulli** [comment]
I can confirm this is a bug, not sure what is causing it tho
