### ISSUE TITLE
Error while installing Lunarvim

### ISSUE THREAD

**Issue by ArbazIrshad** [LunarVim/LunarVim#3033]
### Problem description

Whenever I tried to install lvim through the shell script. It gives off this error after the dependency installation process failed.

```
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
```
I have nodejs installed through nvm.

### LunarVim version

Script: bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

### Neovim version (>= 0.7.2)

0.7.2

### Operating system/version

Fedora 36

### Steps to reproduce

simply run the shell script

### support info

```
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
```

**Comment by cpea2506** [comment]
If you have `pnpm` installed. Then follows it suggestion, run `pnpm setup`

**Comment by kylo252** [comment]
> If you have `pnpm` installed. Then follows its suggestion, run `pnpm setup`

@ArbazIrshad, let me know if this doesn't fix it

**Comment by ArbazIrshad** [comment]
@kylo252 Fixed the issue. Nvm installed pnpm and yarn too with npm. I didn't know about it. So, I just removed them and the installation could progress.

**Comment by yonydev** [comment]
hi! i ran `pnpm setup` but didn't work for me
