### ISSUE TITLE
Setting vim.opt.swapfile = true in setting.lua has no effect.

### ISSUE THREAD

**Issue by longguzzz** [LunarVim/LunarVim#3039]
### Problem description

Nvim performs correctly.

### LunarVim version

rolling-26d4934

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Windows11 22622.290

### support info

Buffer info
* filetype:                alpha
* bufnr:                   1
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active:

**Comment by rebuilt** [comment]
Setting swapfile to true works but it creates the swapfile in a non-default directory.  If you print out `:set swapfile?` it should report `swapfile`.  If you print out the directory `:set directory?`, it should report something like `~.local/state/nvim/swap`

**Comment by longguzzz** [comment]
My `:set swapfile` tells `noswapfile`, so I try to change more options in `setting.lua` to check whether it really works. And I find there is also a `swapfile` in default_options, but I only noticed  the `vim.opt.swapfile` before. Now the problem have been solved. Thank you.
