### ISSUE TITLE
packer.nvim: Error running config for nvim-navic: [string "..."]:0: attempt to call field 'setup' (a nil value)

### ISSUE THREAD

**Issue by bobek** [LunarVim/LunarVim#3045]
### Problem description

After starting `lvim` the error is shown:

```
packer.nvim: Error running config for nvim-navic: [string "..."]:0: attempt to call field 'setup' (a nil value)
```

This is most-likely related to #3043, but breadcrumbs itself are working. I've done LvimCacheReset, PackerUpdate, PackerSync.

### LunarVim version

rolling-03ec312

### Neovim version (>= 0.7.2)

NVIM v0.8.0-dev-1120-ga0e6e767a

### Operating system/version

Debian/sid

### support info

```console
Language client log: /home/bobek/.local/state/nvim/lsp.log
 Detected filetype:   go
 
 1 client(s) attached to this buffer: 
 
 Client: gopls (id: 1, pid: nil, bufnr: [1])
 	filetypes:       go, gomod, gowork, gotmpl
 	autostart:       true
 	root directory:  /home/bobek/Sources/moistureguard/golang/modbus-poller
 	cmd:             gopls
 
 Configured servers list: gopls
```

```console

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                go
* bufnr:                   1
* treesitter status:       active

Active client(s)
* name:                      gopls
* id:                        1
* supported filetype(s):     [go, gomod, gowork, gotmpl]
* attached buffers:          1
* root_dir pattern:          1
* capabilities:              implementationProvider  | definitionProvider     | referencesProvider
                             workspaceSymbolProvider | documentSymbolProvider | documentHighlightProvider
                             typeDefinitionProvider  | hoverProvider          | documentFormattingProvider
                             callHierarchyProvider   | foldingRangeProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: [gofmt, gofumpt, goimports, goimports_reviser, golines]

Linters info
* Active: 
* Supported: [golangci_lint, revive, semgrep, staticcheck]

Code actions info
* Active: 
```

**Comment by bobek** [comment]
Dah, I have not seen https://github.com/LunarVim/LunarVim/pull/3043#pullrequestreview-1113199705 when started filling in this ticket. Ended up at the same spot, but was not sure, if it is really the culprit :) 

cc @abzcoding , please feel free to close this one, if you don't need it. Thank you.

**Comment by abzcoding** [comment]
@bobek can you test if #3044 fixes your issues?

**Comment by bobek** [comment]
@abzcoding it fixed the `nvim-navic` issue for me, broke the `colorscheme` takeing a closer look (Packer removed the `tokionight` plugin)

**Comment by abzcoding** [comment]
> @abzcoding it fixed the `nvim-navic` issue for me, broke the `colorscheme` takeing a closer look (Packer removed the `tokionight` plugin)

you might need to run another `:PackerInstall` since I've replaced `lunarvim/tokyonight.nvim` with `folke/tokyonight.nvim`

also make sure you've set your theme like this:
```
lvim.colorscheme = "tokyonight"
```

**Comment by bobek** [comment]
Yup, that is exactly my config. But for some reason Packer got confused and hasn't handled the switch correctly. Anyway, I was able to make it behave.

Happy to report, that everything is working as expected for me. Thank you for your awesome support!
