### ISSUE TITLE
LSP: format request failed for shell script

### ISSUE THREAD

**Issue by cataglyphis** [LunarVim/LunarVim#3048]
### Problem description

- install bash-language-server plugin
- create shell script, and use lvim to open this file
- format script with default mapping < leader >lF
- Error: `[LSP] Format request failed, no matching language servers`
- format other json files, no error

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

macOS 12.6

### Affected language servers

bash-language server

### Actual behavior

- Error: `[LSP] Format request failed, no matching language servers` when format shell script file

### support info

```console
 Language client log: /Users/totoro/.cache/lvim/lsp.log
 Detected filetype:   sh
 
 1 client(s) attached to this buffer: 
 
 Client: bashls (id: 1, pid: 62645, bufnr: [1])
 	filetypes:       sh
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             bash-language-server start
 
 Configured servers list: bashls
```
```console
Buffer info
* filetype:                sh
* bufnr:                   1
* treesitter status:       active

Active client(s)
* name:                      bashls
* id:                        1
* supported filetype(s):     sh
* attached buffers:          1
* root_dir pattern:          1
* capabilities:              referencesProvider      | documentHighlightProvider | documentSymbolProvider
                             workspaceSymbolProvider | hoverProvider             | definitionProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: [beautysh, shellharden, shfmt]

Linters info
* Active: 
* Supported: shellcheck

Code actions info
* Active: 
```

### logs

```console
[START][2022-09-20 20:12:18] LSP logging initiated
[START][2022-09-20 20:14:45] LSP logging initiated
[START][2022-09-20 20:16:56] LSP logging initiated
[START][2022-09-20 20:18:58] LSP logging initiated
[START][2022-09-20 20:19:42] LSP logging initiated
[START][2022-09-20 20:21:37] LSP logging initiated
[START][2022-09-20 20:21:49] LSP logging initiated
[START][2022-09-20 20:23:06] LSP logging initiated
[START][2022-09-20 20:25:55] LSP logging initiated
```

### Screenshots

<img width="480" alt="image" src="https://user-images.githubusercontent.com/9249983/191256702-2366ea9e-b227-4032-8768-92542f6ba765.png">

<img width="1476" alt="iShot_2022-09-20_20 33 45" src="https://user-images.githubusercontent.com/9249983/191258716-b6c1d335-2cd9-4ab9-9db1-0a1977ae5faa.png">

**Comment by abzcoding** [comment]
`bashls` doesn't have formatting capability  as apparent in `:LvimInfo` ( lack of `documentFormattingProvider | documentRangeFormattingProvider` )

You might want to set a formatter for shell files (e.g. `shfmt` )

**Comment by cataglyphis** [comment]
> `bashls` doesn't have formatting capability as apparent in `:LvimInfo` ( lack of `documentFormattingProvider | documentRangeFormattingProvider` )
> 
> You might want to set a formatter for shell files (e.g. `shfmt` )

got it, thanks.
I config format for shell file in ftplugin, then everything work well.

**Comment by subhajit-halder** [comment]
@cataglyphis can you please share your lvim config? My bashls is not working for some reason.
