### ISSUE TITLE
Lualine theme can't be changed in configuration

### ISSUE THREAD

**Issue by carlossgv** [LunarVim/LunarVim#3066]
### Problem description

Lualine theme is not beign updated when changing colorscheme from the config file, nor it can be set it in using `lvim.builtin.lualine.options.theme = "onedark"`.

Current behavior:
- Statusline theme won't match selected colorscheme when `lvim.colorscheme = "some_theme"` is set in config file.
- Statusline theme won't change if set in config file like `lvim.builtin.lualine.options.theme = "some_theme"`.
- Statusline will update to current theme when set from command line `:colorscheme some_theme`.

For the time beign I managed to get it to match theme from config file by changing line 86 in `lua/lvim/core/theme.lua` from `lvim.builtin.lualine.options.theme = "tokyonight"` to `lvim.builtin.lualine.options.theme = "auto"`. This will make the statusline to match theme set in config but still won't work when setting the status line theme in config.

### LunarVim version

rolling-817337b

### Neovim version (>= 0.7.2)

NVIM v0.7.2 Release

### Operating system/version

Linux Ubunti 22.04

### Steps to reproduce

1. Go to config file.
2. Set lvim.colorscheme = "pablo"
3. Restart lvim.

1. Go to config file.
2. Set lvim.colorscheme = "pablo"
3. Set. lvim.builtin.lualine.options.theme = "pablo"
4. Restart lvim.

### support info

```
 Use [q] or [Esc] to quit the window
 
 Language client log: /home/carlossgv/.cache/lvim/lsp.log
 Detected filetype:   alpha
 
 1 client(s) attached to this buffer: 
 
 Client: copilot (id: 1, pid: 109644, bufnr: [1])
 	filetypes:       
 	autostart:       false
 	root directory:  Running in single file mode.
 	cmd:             node /home/carlossgv/.local/share/lunarvim/site/pack/packer/start/copilot.vim/copilot/dist/agent.js
 
 Configured servers list: 

```
```

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                alpha
* bufnr:                   1
* treesitter status:       inactive

Active client(s)
* name:                      copilot
* id:                        1
* supported filetype(s):     []
* attached buffers:          1
* root_dir pattern:          1

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 

```

**Comment by Almo7aya** [comment]
try 
```
:PackerSync
:PackerCompile
```
This worked for me

**Comment by FedorLap2006** [comment]
While `PackerSync` might help, it's rather an issue with theme loader.
I'm working on a fix for it, since it's currently overrides the lualine theme on setup. See lines below:
https://github.com/LunarVim/LunarVim/blob/65777d858f75079cb12125ee1aa45f51e10dcb11/lua/lvim/core/theme.lua#L85-L86

**Comment by Almo7aya** [comment]
@FedorLap2006  it's working with me somehow ? 🤷‍♂️
