### ISSUE TITLE
Yaml: [LSP] Format request failed, no matching language servers.  (only on the first save)

### ISSUE THREAD

**Issue by cova-fe** [LunarVim/LunarVim#3069]
### Problem description

I installed (and reinstalled) yaml language server as can be seen here:
![image](https://user-images.githubusercontent.com/385249/191966066-61ba274f-1b9d-4ff4-b663-0cfbf9fe839d.png)

However, when saving the file I get the following message:
![image](https://user-images.githubusercontent.com/385249/191966410-96595734-ed10-434c-bb9a-2ae31eb0142b.png)

I tried to debug 

### LunarVim version

rolling-6511e99

### Neovim version (>= 0.7)

NVIM v0.7.2 RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

Linux Gentoo ~

### Affected language servers

yamlls

### Steps to reproduce

Edit a yaml file, save it (to trigger linting)

### Actual behavior

Getting LSP not installed error

### Expected behavior

The error should not appear

### support info

 ```Language client log: /home/cova/.cache/nvim/lsp.log
 Detected filetype:   yaml
 
 1 client(s) attached to this buffer: 
 
 Client: yamlls (id: 1, pid: 1085235, bufnr: [1])
 	filetypes:       yaml, yaml.docker-compose
 	autostart:       true
 	root directory:  /home/cova/.local/share/lunarvim/lvim
 	cmd:             yaml-language-server --stdio
 
 Configured servers list: terraform_lsp, yamlls
 
 
    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                yaml
* bufnr:                   1
* treesitter status:       active

Active client(s)
* name:                      yamlls
* id:                        1
* supported filetype(s):     [yaml, yaml.docker-compose]
* attached buffers:          1
* root_dir pattern:          1
* capabilities:              documentSymbolProvider | foldingRangeProvider | definitionProvider
                             hoverProvider          | codeActionProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: [prettier, prettier_d_slim, prettierd, yamlfmt]

Linters info
* Active: 
* Supported: [actionlint, cfn_lint, spectral, yamllint]

Code actions info
* Active: 




### logs

```console
[DEBUG][2022-09-23 15:11:48] .../vim/lsp/rpc.lua:347    "rpc.send"      {  jsonrpc = "2.0",  method = "textDocument/didSave",  params = {    textDocument = {      uri = "file:///home/cova/.local/share/lunarvim/lvim/.github/workflows/install.yaml"    }  }}
[DEBUG][2022-09-23 15:11:48] .../vim/lsp/rpc.lua:454    "rpc.receive"   {  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/cova/.local/share/lunarvim/lvim/.github/workflows/install.yaml"  }}
```

**Comment by cpea2506** [comment]
It's because you toggle format on save and the language does not support formatting. But yes, it's too noisy.

**Comment by cova-fe** [comment]
> It's because you toggle format on save on and the language does not support formatting. But yes, it's too noisy.

Should be this bug closed as "work as expected" then or left open in order to find a better approach?

**Comment by cpea2506** [comment]
@lvimuser @kylo252 @ChristianChiarulli 

Should we suppress this noise and make it a debug message instead?

**Comment by kylo252** [comment]
> @lvimuser @kylo252 @ChristianChiarulli 
> 
> Should we suppress this noise and make it a debug message instead as it sometimes can cause confusing to the end user.

I'm pretty sure that this message is not controlled by lunarvim. Instead, we should look into _why_ the request is sent in the first place if no matching clients were found.

**Comment by cpea2506** [comment]
> I'm pretty sure that this message is not controlled by lunarvim. Instead, we should look into _why_ the request is sent in the first place if no matching clients were found.

It appears when the `format` function is called and because the lsp itself does not support formatting.

https://github.com/LunarVim/LunarVim/blob/518b1d4167162a54a6e76784038d30191613b76d/lua/lvim/lsp/utils.lua#L204-L210

**Comment by lvimuser** [comment]
Isn't it fine since we're using `notify_once`?

**Comment by cova-fe** [comment]
> Isn't it fine since we're using `notify_once`?

The first thing that I suspected when I saw that notification only once, was that after the first invocation formatter started to work (and it is not easy to detect visually, as the document could be already formatted). Also, looking in the statusline everything seems to be fine, as LS are listed. Maybe a visual hint would help, like shading the language servers list or something like that. Or a message like "[LSP] Format failed, no formatter found. Turning formatting off".

**Comment by ChristianChiarulli** [comment]
we should probably just remove the notification for now until someone can think of something better, it's mostly just noise at this point. If you have a specific formatter active it will be in the statusline. If there's no formatting your LS simply doesn't support it and you should install a formatter.

**Comment by opalmay** [comment]
Now we are just calling the upstream implementation: 
https://github.com/LunarVim/LunarVim/blob/48d1c38fa88dbfbaa35e81560cf0fa7d8793b195/lua/lvim/lsp/utils.lua#L172-L177
Can we still do anything to silence this notification?

**Comment by nwaywood** [comment]
I have this in my config so it only tries to format on filetypes that I want it to. That solved the issue for me

```lua
lvim.format_on_save = {
	pattern = { "*.lua", "*.scala" },
}
```

**Comment by LostNeophyte** [comment]
notify.nvim is removed now, so the notification won't appear anymore.
