### ISSUE TITLE
[Feature] Add mapping to delete the selected buffer in `Telescope buffers` picker

### ISSUE THREAD

**Issue by pidgeon777** [LunarVim/LunarVim#3070]
### Feature Description

I tried without success to add a mapping to the `Telescope buffer` picker to delete the currently selected buffer.

It would be great to add a keymap for that action:

```lua
require("telescope.actions").delete_buffer
```

but, for the Telescope buffers picker only.

**Comment by abzcoding** [comment]
use `dd`

https://github.com/LunarVim/LunarVim/blob/de5691f2d56c79a9f630c27e6bb623a1638de949/lua/lvim/core/telescope.lua#L163-L164
