### ISSUE TITLE
packer clean falsely suggests to remove lualine and onedarker directories from config dir tree

### ISSUE THREAD

**Issue by kdamaski** [LunarVim/LunarVim#3082]
### Problem description

Firstly i love lunarvim i have spent so many hours with this editor (mostly touching stuff because it's the only way to learn better :) ).
An issue i see on every clean installation when im switching machines is that Packer suggests removing the lualine,onedarker directories from the plugins while they are in use. Both those two directories exist on installation they were not installed later but even if i put the lualine git repo in the packer i still get the suggestion every time i write the config. To solve that i have touched the files that have the functions that output the logical value of whether the cleaner find them dirty or not. Unfortunately i am on a clean boot laptop right now and i can't say exactly which two files, and which line where they but i probably come back tomorrow and update this issue when i will be using the labs pc.

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.7.2)

0.7.2

### Operating system/version

gnu/linux garuda (arch based)

### Steps to reproduce

just write the ~/.config/lvim/config.lua

#### :LvimInfo
![image](https://user-images.githubusercontent.com/64901487/192169427-75a38268-cc90-45c9-8d1a-e4c3ff1f6947.png)

#### :LspInfo
![image](https://user-images.githubusercontent.com/64901487/192169448-0c533b5e-be1e-4882-9786-da3b93c6db63.png)

### Screenshots
![image](https://user-images.githubusercontent.com/64901487/192169360-04e972ee-9ddb-4884-a2e6-91665c5da132.png)

# Solution
file : ~/.local/share/lunarvim/lvim/lua/lvim/plugins.lua
1) line 28 : change line "disable = lvim.colorscheme ~= onedarker" to "disable = false"
![image](https://user-images.githubusercontent.com/64901487/192294296-5fae2f09-53ad-4f83-9609-de7c02f999ee.png)
2) line 196: change line "disable = not lvim.builtin.lualine.active" to "disable = false"
![image](https://user-images.githubusercontent.com/64901487/192294571-a77268da-d1c5-40f9-b930-727f53a622ad.png)

**Comment by cpea2506** [comment]
They will be remove because you do not have 

`lvim.colorscheme = "onedarker"` and `lvim.builtin.lualine.active = true`

https://github.com/LunarVim/LunarVim/blob/67234b748abc7089591c2b6b5f7b1a96a98c5c91/lua/lvim/plugins.lua#L290

https://github.com/LunarVim/LunarVim/blob/67234b748abc7089591c2b6b5f7b1a96a98c5c91/lua/lvim/plugins.lua#L197

**Comment by cpea2506** [comment]
@kdamaski Just wanna say that it will be installed later once these line was set `lvim.colorscheme = "onedarker"` and `lvim.builtin.lualine.active = true` in user's `config.lua` file. Don't touch anything inside core folder of lunarvim
