### ISSUE TITLE
How to refresh file explorer

### ISSUE THREAD

**Issue by arcstur** [LunarVim/LunarVim#3085]
### Problem description

When I create a folder outside LunarVim, it doesn't show up in the file explorer. Thus, I have to close and reopen LunarVim.

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.7.2)

0.7.2

### Operating system/version

ArchLinux

### Steps to reproduce

1. Open Lunarvim at a directory
2. Create a file or a folder in that directory outside of lunar vim (in a separate terminal)

### support info

   __                          _    ___         
                          / /   __  ______  ____ _____| |  / (_)___ ___ 
                         / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
                        / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
                       /_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 
                       
                       
                       Buffer info
                       * filetype:                markdown
                       * bufnr:                   16
                       * treesitter status:       inactive
                       
                       Active client(s)
                       
                       Automatic LSP info
                       * Status: disabled for markdown
                       
                       Formatters info
                       * Active: 
                       * Supported: [markdownlint, mdformat, prettier, prettier_d_slim, prettierd, remark, terrafmt]
                       
                       Linters info
                       * Active: 
                       * Supported: [alex, markdownlint, mdl, proselint, vale, write_good]
                       
                       Code actions info
                       * Active:

**Comment by tuxflo** [comment]
Do you mean in nvim tree? I think the `R` shortcut does a refresh. You can see all available keys with `g? `, which toggles the built in shortcut overview.

**Comment by arcstur** [comment]
Thanks!
