### ISSUE TITLE
"args" option does not work specifically for cpplint

### ISSUE THREAD

**Issue by artistic-nucleus** [LunarVim/LunarVim#3089]
### Problem description

1.Install cpplint via mason
2. use `args = { "--filter=-legal/copyright"}`

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.7.2)

NVIM v0.7.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by runner@fv-az164-457

### Operating system/version

Fedora 35

### support info

-

**Comment by lvimuser** [comment]
Try
`args = { "--filter", "-legal/copyright" }`

**Comment by artistic-nucleus** [comment]
> Try
> `args = { "--filter", "-legal/copyright" }`. Might be worth checking the logs to make sure the args are being passed.
Tried that too, doesn't work.
> (`:NullLsLog`, but need to set the debug flag).
By default NullLsLog is blank. How do I set debug flag?

**Comment by lvimuser** [comment]
>How do I set debug flag?

`lvim.lsp.null_ls.setup["debug"] = true`

**Comment by artistic-nucleus** [comment]
> `lvim.lsp.null_ls.setup["debug"] = true`

Still nothing in logs

**Comment by lvimuser** [comment]
How are you setting up the formatters/linters?

**Comment by artistic-nucleus** [comment]
In `config.lua` as mentioned in the docs. I also tried installing `cpplint.py` via pip3 and then adding it to `config.lua` but still facing the same issue.

**Comment by mathstylish** [comment]
Same for me
