### ISSUE TITLE
VGJ -> E16: Invalid range

### ISSUE THREAD

**Issue by tobdub** [LunarVim/LunarVim#3095]
### Problem description

1. Open a _.txt_ file with multiple lines
2. Type _VGJ_ to join all lines

Expected result: All lines are joined to one line. Works in neovim and vim without LunarVim config.
Actual result: E16: Invalid range

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Ubuntu 20.04

### support info

```console
Detected filetype: text
0 client(s) attached to this buffer
```
```console
Buffer info
* filetype:                text
* bufnr:                   1
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 

```

**Comment by abzcoding** [comment]
That comes from this keymap:
https://github.com/LunarVim/LunarVim/blob/257e3ff3697a55e7a17eab876fb8d0b85fd203de/lua/lvim/keymappings.lua#L85-L87

add the following to your `~/.config/lvim/config.lua` to get your desired behavior:
```lua
lvim.keys.visual_block_mode["J"] = false
```

**Comment by tobdub** [comment]
aha, thanks!
