### ISSUE TITLE
Breaking Changes after 1.0 Release?

### ISSUE THREAD

**Issue by LandonSchropp** [LunarVim/LunarVim#3097]
### Problem description

Recently, I upgraded LunarVim and was surprised to find my `H` and `L` keymappings had disappeared. After a little digging, I tracked down the change to #2874.

While I'm ambivalent about the change itself (it's not hard to add a keymapping), what is concerning to me is that the mapping was changed outside of a version bump. This got me wondering, _what's LunarVim's policy in terms of changes and versioning?_ Should this have been replaced with a warning indicating the mapping had been changed? Should there at least have been a minor version bump, with a changelog entry so I knew to update this mapping?

LunarVim is my daily text editor I use for work, so I value stability in these things. Are there any plans to ensure these types of changes are communicated clearly in the future?

Thanks for creating such a great tool!

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

macOS 11.5

### Steps to reproduce

N/A

### support info

N/A

**Comment by ChristianChiarulli** [comment]
Rolling is like a nightly version of lunarvim, it is subject to change violently. It seems like this PR you shared was against rolling, but if it found its way into master than it was a mistake and we shouldn't have merged that change.

**Comment by matteratomic** [comment]
> Rolling is like a nightly version of lunarvim, it is subject to change violently. It seems like this PR you shared was against rolling, but if it found its way into master than it was a mistake and we shouldn't have merged that change.

I encountered it on the stable branch and it kinda threw me off and had to do some digging in the config. Such changes should be indicated. Lunarvim is still my daily driver. Keep up the good work!

**Comment by LandonSchropp** [comment]
@ChristianChiarulli I definitely don't mean to sould like I'm chastizing here—I'm nothing but grateful for LunarVim. 🙂

Is there some kind of deprecation system that already exists or could be added that could let people know if they're using an outdated configuration? That'd be a nice way to catch these types of things when doing development.

Otherwise, should I close this issue?

**Comment by ChristianChiarulli** [comment]
@LandonSchropp Yea I think it was just a hiccup, not sure exactly why/when it happened but a fundamental change like that should be in a major bump. We do our best to follow semver so you can always assume that if something happens like this in the future it was a mistake. (hopefully it won't)

**Comment by Lun4m** [comment]
@ChristianChiarulli 
Another undocumented change that made its way into master was the switch from `lvim.lsp.automatic_servers_installation` to `lvim.lsp.installer.setup.automatic_installation`. 
I love the work you guys are doing with LunarVim, but I agree with @LandonSchropp that what's merged into `master` should either come with a changelog or deprecation warnings.
