### ISSUE TITLE
[Hacktoberfest] unify border typpes and make it configureable

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#3105]
see title

**Comment by BeeverFeever** [comment]
Hey @ChristianChiarulli I would like to give this a try. 

Would it be something similar to #3092 where all the borders will be aggregated into a file like `lua/lvim/borders.lua` with defaults and import `lvim.borders` everywhere it's needed? Very similar to the issue I mentioned.

**Comment by ChristianChiarulli** [comment]
@BeeverFeever I think you can add the border config here: https://github.com/LunarVim/LunarVim/blob/rolling/lua/lvim/config/defaults.lua

and reference this everywhere

**Comment by BeeverFeever** [comment]
Yeah ok, that sounds good. I'll see how I go.

**Comment by evan-leigh** [comment]
Here is an approach I came up with for adding a border config https://github.com/evan-leigh/LunarVim/pull/1/files

The user could specify a different border for each popup
```lua
  lvim.borders = {
    telescope = {
      style = "rounded",
    },
    nvim_cmp = {
      style = "rounded",
    },
    which_key = {
      style = "single",
    },
  }
```

Using borders in LunarVim
```lua
local b = require("lvim.core.borders")["whichkey"]

border = { b.tl, b.h, b.tr, b.v, b.br, b.h, b.bl, b.v }
```

**Comment by BeeverFeever** [comment]
Would it make sense to have a single 'global' border style for the whole program, for example 
```
borders_style = "rounded",
```
rather than having it separately set for each of the plugins?
Or is more customisability something that lvim wants?

**Comment by BeeverFeever** [comment]
Would it be better to have a single border style setting in `/config/defaults.lua` so that the user only has to set one setting that will change all of the broders to keep them all consistent. Or would the more customisability (being, having a setting for each of the plugins as @evan-leigh has) be better?

**Comment by evan-leigh** [comment]
> Would it be better to have a single border style setting in `/config/defaults.lua`

No reason we couldn't have all borders be the same if only one value is provided, for example `lvim.borders = "single"` then people who want to configure specific borders would have the option

**Comment by BeeverFeever** [comment]
> > Would it be better to have a single border style setting in `/config/defaults.lua`
> 
> 
> 
> No reason we couldn't have all borders be the same if only one value is provided, for example `lvim.borders = "single"` then people who want to configure specific borders would have the option

Sorry my wording was poor but that is pretty much what i meant. Feel free to make a pull request to lunarvim if you think your implementation is ready.
