### ISSUE TITLE
lualine theme get stuck to default, can't change

### ISSUE THREAD

**Issue by qvieth** [LunarVim/LunarVim#3106]
### Problem description

lualine theme doesn't detect current theme, can't change through `lvim.builtin.lualine.options.theme` also

### LunarVim version

rolling-9930fc3

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Fedora 36

### Steps to reproduce

after an PackerSync my lualine become like this, can't change back

### support info

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 

Buffer info
* filetype:                c
* bufnr:                   5
* treesitter status:       active

Active client(s)
* name:                      clangd
* id:                        2
* supported filetype(s):     [c, cpp, objc, objcpp, cuda, proto]
* attached buffers:          5
* root_dir pattern:          5
* capabilities:              referencesProvider      | definitionProvider       | documentRangeFormattingProvider
                             documentSymbolProvider  | astProvider              | documentFormattingProvider
                             workspaceSymbolProvider | clangdInlayHintsProvider | documentHighlightProvider
                             implementationProvider  | declarationProvider      | hoverProvider
                             callHierarchyProvider   | typeHierarchyProvider    | selectionRangeProvider
                             typeDefinitionProvider  | memoryUsageProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: [astyle, clang_format, uncrustify]

Linters info
* Active: 
* Supported: [clang_check, cppcheck, cpplint, gccdiag]

Code actions info
* Active: 

### Screenshots

![image](https://user-images.githubusercontent.com/71810726/193218117-2b9acf43-eee9-4432-a485-169b59a987c5.png)

**Comment by lvimuser** [comment]
See also #3020

**Comment by ChristianChiarulli** [comment]
this is a bug that I can't reproduce, does this happen after a fresh install?

**Comment by qvieth** [comment]
I can reproduce it by removing all my user plugins and then reinstalling these plugins, after the reinstall will not happen right away, just after I do a packer sync, the lualine theme stuck and can't change again.

How I try to reproduce:
1. I remove my user plugin by commenting the plugins and do packer sync:
![Screenshot from 2022-10-01 23-17-44](https://user-images.githubusercontent.com/71810726/193416333-eaa0204b-92ac-46ef-b4c6-213e9287f397.png)

2. Uncomment the plugins and do PackerSync to reinstall:
![Screenshot from 2022-10-01 23-18-55](https://user-images.githubusercontent.com/71810726/193416376-24b1567e-f77f-4ae3-b1e9-400dbb2f9153.png)

3. At first everything seems ok(no bugs appear)
![image](https://user-images.githubusercontent.com/71810726/193416479-b4117760-a273-4c02-ba9d-652b20505f3c.png)

4. Do a PackerSync again and the bug appear:
![Screenshot from 2022-10-01 23-19-20](https://user-images.githubusercontent.com/71810726/193416428-d83d5d96-6660-4b2d-88c2-3d86f46d330a.png)
![Screenshot from 2022-10-01 23-19-26](https://user-images.githubusercontent.com/71810726/193416438-da9d5a2f-63c3-42cc-b72a-d0a3bc5c172c.png)

**Comment by kobzarchekg** [comment]
Do you run PackerCompile after PackerSync?

**Comment by qvieth** [comment]
> Do you run PackerCompile after PackerSync?

No I don't @kobzarchekg

**Comment by opalmay** [comment]
Had the same issue. Configuring my theme like this fixed it:
`lvim.plugins = {
    {
        { "catppuccin/nvim", after = "lualine.nvim" },
...
}
`
Not sure what's the right way to implement this at the source.

**Comment by opalmay** [comment]
This has to do with the order plugins are loaded.
In vanilla Neovim it'd need to be configured like this:
```use {
    'catppuccin/nvim',
    after = "lualine.nvim"
 }```

**Comment by qvieth** [comment]
I updated my lvim and this issue dissapear!

**Comment by opalmay** [comment]
I wouldn't say this is solved, it should be fixed in source.
However, I'm not sure how to approach this. From my understanding in vanilla Neovim you'd use the "after" thingy in Packer to ensure plugins load in the right order. But this is not possible with Lvim custom plugins, nor would you really want to handle it this way.
