### ISSUE TITLE
Main Menu (Leader) is very slow to appear in Windows 10

### ISSUE THREAD

**Issue by Edenshaw** [LunarVim/LunarVim#3116]
### Problem description

1. Open Lvim
2. Press the space bar
3. wait around 3 seconds for the menu to appear

### LunarVim version

Latest (the command LvimVersion does not output anything)

### Neovim version (>= 0.7.2)

0.7.2

### Operating system/version

Windows 10

### Steps to reproduce

1. Open Lvim
2. Press the space bar
3. wait around 3 seconds for the menu to appear

### support info

0

**Comment by cpea2506** [comment]
Set `timeoutlen` around 250 - 500 

```lua
vim.opt.timeoutlen = 250 -- or 500
```

**Comment by rebuilt** [comment]
Be aware that timeoutlen controls how much time you are given to type out your entire keybinding so if you use plugins like vim-surround and have to type out a bunch of characters, you might run out of time and it may seem like the plugin is not working correctly.

**Comment by riotrah** [comment]
Any way to configure such a timeout only for whichkey?

**Comment by rebuilt** [comment]
> Any way to configure such a timeout only for whichkey?
No.  

I set my timeoutlen at the default of 1000 because I don't want a whichkey menu opening up unless I forget my hotkeys.
