### ISSUE TITLE
Installation script not working.

### ISSUE THREAD

**Issue by samirqlvdev** [LunarVim/LunarVim#3119]
### Problem description

The new version of Neovim for Mac automatically installing tree-sitter as a dependency and doesn't work separately. 

### LunarVim version

Latest

### Neovim version (>= 0.7.2)

NVIM v0.8.0 homebrew latest

### Operating system/version

macOS 11.5

### Steps to reproduce

Not working  -- bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
Not working  -- export LV_BRANCH="rolling"; bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)

### support info

0 verbose cli /opt/homebrew/Cellar/node/18.10.0/bin/node /opt/homebrew/bin/npm
1 info using npm@8.19.2
2 info using node@v18.10.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/Users/samirguliyev/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 6ms
18 timing npm:load:configload Completed in 6ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install tree-sitter-cli
22 verbose argv "install" "--global" "tree-sitter-cli"
23 timing npm:load:setTitle Completed in 2ms
24 timing config:load:flatten Completed in 2ms
25 timing npm:load:display Completed in 2ms
26 verbose logfile logs-max:10 dir:/Users/samirguliyev/.npm/_logs
27 verbose logfile /Users/samirguliyev/.npm/_logs/2022-10-02T16_58_01_944Z-debug-0.log
28 timing npm:load:logFile Completed in 2ms
29 timing npm:load:timers Completed in 0ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 12ms
32 timing arborist:ctor Completed in 1ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 2ms
36 timing idealTree:userRequests Completed in 1ms
37 silly idealTree buildDeps
38 silly fetch manifest tree-sitter-cli@*
39 http fetch GET 200 https://registry.npmjs.org/tree-sitter-cli 515ms (cache revalidated)
40 silly placeDep ROOT tree-sitter-cli@0.20.7 OK for:  want: *
41 timing idealTree:#root Completed in 524ms
42 timing idealTree:node_modules/tree-sitter-cli Completed in 0ms
43 timing idealTree:buildDeps Completed in 525ms
44 timing idealTree:fixDepFlags Completed in 0ms
45 timing idealTree Completed in 529ms
46 timing reify:loadTrees Completed in 530ms
47 timing reify:diffTrees Completed in 1ms
48 silly reify moves {}
49 timing reify:retireShallow Completed in 1ms
50 timing reify:createSparse Completed in 1ms
51 timing reify:loadBundles Completed in 0ms
52 silly audit bulk request { 'tree-sitter-cli': [ '0.20.7' ] }
53 timing reify:rollback:createSparse Completed in 1ms
54 timing reify:rollback:retireShallow Completed in 0ms
55 timing command:install Completed in 543ms
56 verbose stack Error: EEXIST: file already exists
56 verbose stack     at failEEXIST (/opt/homebrew/lib/node_modules/npm/node_modules/bin-links/lib/check-bin.js:49:32)
56 verbose stack     at checkLink (/opt/homebrew/lib/node_modules/npm/node_modules/bin-links/lib/check-bin.js:40:12)
56 verbose stack     at async Promise.all (index 0)
56 verbose stack     at async Function.checkBins (/opt/homebrew/lib/node_modules/npm/node_modules/bin-links/lib/check-bins.js:15:3)
56 verbose stack     at async [checkBins] (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:247:5)
56 verbose stack     at async /opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:606:7
56 verbose stack     at async Promise.allSettled (index 0)
56 verbose stack     at async [reifyPackages] (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:231:11)
56 verbose stack     at async Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:155:5)
56 verbose stack     at async Install.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/install.js:145:5)
57 verbose cwd /Users/samirguliyev
58 verbose Darwin 22.1.0
59 verbose node v18.10.0
60 verbose npm  v8.19.2
61 error code EEXIST
62 error path /opt/homebrew/bin/tree-sitter
63 error EEXIST: file already exists
64 error File exists: /opt/homebrew/bin/tree-sitter
65 error Remove the existing file and try again, or run npm
66 error with --force to overwrite files recklessly.
67 verbose exit 1
68 timing npm Completed in 590ms
69 verbose unfinished npm timer reify 1664729881989
70 verbose unfinished npm timer reify:audit 1664729882525
71 verbose unfinished npm timer auditReport:getReport 1664729882525
72 verbose unfinished npm timer reify:unpack 1664729882528
73 verbose unfinished npm timer reifyNode:node_modules/tree-sitter-cli 1664729882528
74 verbose code 1
75 error A complete log of this run can be found in:
75 error     /Users/samirguliyev/.npm/_logs/2022-10-02T16_58_01_944Z-debug-0.log

**Comment by samirqlvdev** [comment]
<img width="1076" alt="Screenshot 2022-10-02 at 20 52 23" src="https://user-images.githubusercontent.com/50010767/193466649-df09ae58-9865-48be-ad00-849effbb3ab2.png">

**Comment by sinnrrr** [comment]
+1

**Comment by samirqlvdev** [comment]
Solved with fork & removing tree-sitter-cli from install.sh 
export LV_BRANCH="rolling"; bash <(curl -s https://raw.githubusercontent.com/samirqlvdev/lunarvim/rolling/utils/installer/install.sh)

**Comment by typkrft** [comment]
This should be reopened. LunarVims install per the directions on their website are completely broken for macOS install, where neovim is install via homebrew, which is likely most of neovim installs on mac.

**Comment by typkrft** [comment]
I was thinking this would work as a fix, but I just tried installing on another mac and it worked and used yarn. Not sure if this a configuration problem or what. 

```SHELL
# Check if macOS
if [[ $(uname -s) = "Darwin" ]]; then 
  # Check if Neovim installed through brew
  if [[ $(brew list neovim) ]]; then
    # Remove tree-sitter dep
    unset __npm_deps[1]
  fi
fi
```

**Comment by LostNeophyte** [comment]
Can you check if this installer fixes the issue`bash <(curl -s https://raw.githubusercontent.com/LostNeophyte/LunarVim/feat/check-if-deps-installed/utils/installer/install.sh)`

**Comment by LostNeophyte** [comment]
@zephaniahong couldn't reproduce ![image](https://user-images.githubusercontent.com/110467150/208866295-97fc4f81-f577-4cb3-b12d-29fcefc4c85e.png)

**Comment by breneser** [comment]
Hi, 

I am having this exact issue on arch linux when trying to install 


![image](https://user-images.githubusercontent.com/5384578/218492587-3750d265-692e-4fc4-a67f-34e81d036aeb.png)

**Comment by breneser** [comment]
@LostNeophyte thanks. Any idea when it would be released?

**Comment by LostNeophyte** [comment]
> @LostNeophyte thanks. Any idea when it would be released?

together with nvim 0.9 if nothing comes up
