### ISSUE TITLE
Error attempt to call an upvalue after update

### ISSUE THREAD

**Issue by qvieth** [LunarVim/LunarVim#3124]
### Problem description

Just do a lvimupdate and it blows my lvim, try to reinstall lvim but still the same issue

### LunarVim version

rolling-9930fc3

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Fedora 36

### Steps to reproduce

Update

### support info

 Use [q] or [Esc] to quit the window
 
 Language client log: /home/qvieth/.cache/lvim/lsp.log
 Detected filetype:   
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: 

### Screenshots

![image](https://user-images.githubusercontent.com/71810726/193486852-f5900229-73c7-4d56-9ef3-f61be0bc7620.png)

**Comment by ChristianChiarulli** [comment]
fixed on latest rolling
