### ISSUE TITLE
Clipboard does not work properly with telescope

### ISSUE THREAD

**Issue by benediktms** [LunarVim/LunarVim#3130]
### Problem description

When opening telescope to search for something, pasting from the clipboard (i.e. the default register) does not work.

### LunarVim version

rolling-9930fc3

### Neovim version (>= 0.7.2)

0.7.2

### Operating system/version

Linux Manjaro

### Steps to reproduce

1. Open LunarVim
2. copy something to the clipboard by either yanking from a buffer or copying something from an external application (`C-c`)
3. Open telescope and attempt to paste (either `p` or `C-S-v`)
4. Nothing will paste

### support info

```console
 Language client log: /home/benedikt/.cache/lvim/lsp.log
 Detected filetype:   typescript
 
 2 client(s) attached to this buffer: 
 
 Client: tsserver (id: 1, pid: 10445, bufnr: [7])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /home/benedikt/code/upp/packages/backend
 	cmd:             typescript-language-server --stdio
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [7])
 	filetypes:       handlebars, jsonc, html, less, graphql, vue, yaml, javascript, json, css, scss, typescriptreact, markdown, javascriptreact, typescript, lua, rust, sh
 	autostart:       false
 	root directory:  /home/benedikt/code/upp
 	cmd:             nvim
 
 Other clients that match the filetype: typescript
 
 Config: tailwindcss
 	Refer to :h lspconfig-root-detection for help.
 	filetypes:         aspnetcorerazor, astro, astro-markdown, blade, django-html, htmldjango, edge, eelixir, elixir, ejs, erb, eruby, gohtml, haml, handlebars, hbs, html, html-eex, heex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte
 	root directory:    Not found. Searched for: root_pattern('tailwind.config.js', 'tailwind.config.ts', 'postcss.config.js', 'postcss.config.ts', 'package.json', 'node_modules', '.git').
 	cmd:               tailwindcss-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: tsserver, tailwindcss
```
```console

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                typescript
* bufnr:                   7
* treesitter status:       active

Active client(s)
* name:                      tsserver
* id:                        1
* supported filetype(s):     [javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx]
* attached buffers:          7
* root_dir pattern:          7
* capabilities:              renameProvider             | referencesProvider      | implementationProvider
                             inlayHintProvider          | typeDefinitionProvider  | callsProvider
                             documentFormattingProvider | workspaceSymbolProvider | foldingRangeProvider
                             documentHighlightProvider  | definitionProvider      | documentRangeFormattingProvider
                             hoverProvider              | documentSymbolProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: prettierd  
* Supported: [deno_fmt, dprint, eslint, eslint_d, prettier, prettier_d_slim, prettierd, rome, rustywind]

Linters info
* Active: eslint_d  
* Supported: [eslint, eslint_d, semgrep, tsc, xo]

Code actions info
* Active: 
```

**Comment by vonPB** [comment]
Experiencing the same
Ctrl + v works in windows terminal tho

**Comment by kylo252** [comment]
is it only in Telescope?

**Comment by vonPB** [comment]
Only in the telescope search for me

**Comment by benediktms** [comment]
@kylo252 only in telescope for me too

**Comment by xbladesub** [comment]
I had similar issue, try to add this to your config: 

```lua
	vim.api.nvim_exec([[
    augroup telescope
        autocmd!
        autocmd FileType TelescopePrompt inoremap <buffer> <silent> <C-r> <C-r>
    augroup END]], false)

```

**Comment by benediktms** [comment]
@xbladesub this works for accessing the system clipboard register directly (thank you), but there is still an issue that telescope does not get the proper information from the registers? Using `:reg` I can see the correct registers both with telescope closed and open but using `p` to past simply doesn't work...

Maybe this is not an issue with LunarVim but with Telescope accessing registers?

**Comment by kylo252** [comment]
@benediktms, I can't actually reproduce this 🤔 

please try rolling with neovim 0.8

**Comment by benediktms** [comment]
@kylo252 I've tried this with neovim 0.8 as well as 0.9 using neovim nightly but I'm running into the same issue. I will try to test this in an isolated environment, to see if maybe it's something to do with my clipboard utility/something else

**Comment by vonPB** [comment]
I've had the same issue on a clean popos vm with alacritty, `neovim v0.8.0-dev-1146-g7a70e9587' and the latest lvim rolling.

It was a bit inconsistent, once pasting worked with `ctrl+o p` (from insert mode), but only when I already had some text in the search bar.
Currently, I cant get any pasting to work.

[Screencast from 05-10-22 01^%17^%17.webm](https://user-images.githubusercontent.com/65032978/193947951-cbab9c3d-add7-4613-9024-02fa1b705593.webm)
(Video might have a few lags)

**Comment by vonPB** [comment]
pretty minimal config
![image](https://user-images.githubusercontent.com/65032978/193948725-a0beb74b-e36e-4028-b69c-b2ffc715a3fa.png)

**Comment by benediktms** [comment]
I tested this in an isolated VM using the default config for LunarVim and I am running into the same issue: telescope can not access anything yanked from a buffer (however C-S-v works without any additional config)

**Comment by opalmay** [comment]
Terminal paste shortcut works normally. Using `p` in normal mode works for me only when the search bar is not empty. But I can replicate this with default Telescope settings. An issue needs to be made there.
