### ISSUE TITLE
Provide built-in mechanism to load lua/vimscript from elsewhere

### ISSUE THREAD

**Issue by rafaelliu** [LunarVim/LunarVim#3135]
### Feature Description

If you want to extend LunarVim, there should be a way to do so without changing the core config. That way it wouldn't get in the way of future updates, users can version control only their own configs, it's easier to recover from a bad change, etc.

One other very specific use case is configs you want to have shared across neovim and lunarvim (e.g. navigation keybindings).

### Describe the alternatives you have considered

The most invasive way of doing this currently is adding a `require` or change `package.path`, and have a separate directory with your own configs.

**Comment by ChristianChiarulli** [comment]
why not use `.config/lvim/config.lua`?

**Comment by rafaelliu** [comment]
That's what I'm using. It works. But it has the drawbacks I mentioned. For people that version control their dot files, it means they'd have to version lvim's config too which wouldn't make sense (the dotfiles should install lunarvim, not keep a copy of it)

I don't know much about the update mechanism of lvim (I'm quite new to it myself), but I image it touches the config files and could break/overwrite any customization done, no?

**Comment by ChristianChiarulli** [comment]
nope, the config directory is all you

**Comment by kylo252** [comment]
> the dotfiles should install lunarvim, not keep a copy of it

these are two separate folders, take a look at the installer for a reference on the defaults: https://github.com/LunarVim/LunarVim/blob/560ee4d7cf4038a22a5556d79ad92cd226a792dc/utils/installer/install.sh#L9-L16
