### ISSUE TITLE
Unwanted keymaps that close buffer for certain file types

### ISSUE THREAD

**Issue by bwright1558** [LunarVim/LunarVim#3136]
After updating LunarVim recently I noticed that hitting escape was closing buffers with markdown file types. I started looking through the LunarVim configs and found [this](https://github.com/LunarVim/LunarVim/blob/35cea14111ce642cbb74df96bf948263b98ebd04/lua/lvim/core/autocmds.lua#L28) autocmd adding custom keymaps for specific file types.

What was the reasoning for adding these keymaps for these specific file types? I find them more annoying than helpful. I frequently hit escape several times to ensure I'm in normal mode, and if I'm in a markdown file, it becomes annoying when that extra press of escape closes the buffer.

I think these keymaps should be either removed or added in a way that they can be easily disabled. With the current state of things, I do not know how to disable this behavior.

**Comment by ChristianChiarulli** [comment]
escape shouldn't be there, neither should markdown, only `q`

**Comment by ChristianChiarulli** [comment]
pull the latest hopefully that fixes it for you

**Comment by bwright1558** [comment]
Yeah, that's much better. Many thanks for this awesome project.
