### ISSUE TITLE
`"` in the normal mode triggers a window similar to which-key

### ISSUE THREAD

**Issue by xyegithub** [LunarVim/LunarVim#3139]
### Feature Description

Press `"` in the normal mode and a window similar to which-key shows up which demonstrates the details of the registers. It is very convenient to choose registers when pasting. Lunarvim had this feature before. However, it disappears after I upgrade someday.

**Comment by ChristianChiarulli** [comment]
```
lvim.builtin.which_key.setup.plugins.registers = true
```
