### ISSUE TITLE
Wrong theme when using tmux

### ISSUE THREAD

**Issue by arcstur** [LunarVim/LunarVim#3143]
### Problem description

The theme colors are wrong when using tmux

Default:
![image](https://user-images.githubusercontent.com/24514392/193832817-eaf43cc6-db4e-4ce3-a117-cc2776c74506.png)

When on tmux:
![image](https://user-images.githubusercontent.com/24514392/193832860-a5f4fb9b-0998-46a0-890f-fbdfc76ce0c7.png)

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.7.2)

0.7.2

### Operating system/version

ArchLinux

### Steps to reproduce

1. Open a tmux session
2. Open lvim

### support info

   __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 

Buffer info
* filetype:                lua
* bufnr:                   5
* treesitter status:       active

Active client(s)
* name:                      sumneko_lua
* id:                        1
* supported filetype(s):     lua
* attached buffers:          5
* root_dir pattern:          5
* capabilities:              foldingRangeProvider       | documentSymbolProvider  | documentHighlightProvider
                             referencesProvider         | hoverProvider           | documentRangeFormattingProvider
                             definitionProvider         | workspaceSymbolProvider | colorProvider
                             documentFormattingProvider | typeDefinitionProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: [lua_format, stylua]

Linters info
* Active: 
* Supported: [luacheck, selene]

Code actions info
* Active:

**Comment by kylo252** [comment]
@arcstur, this is most definitely a `terminfo` issue. you need to: 
- set `$TERM` depending on your terminal emulator
- make sure that `infocmp` produces the correct value
- make sure that you've enabled the corresponding tmux overrides to enable 24-bit support

here's my [`tmux.conf`](https://github.com/kylo252/dotfiles/blob/56f317f9ca11815c59b723103ce8a6619bfbaebb/.config/tmux/tmux.conf#L7-L30)

refs:
- kitty: https://sw.kovidgoyal.net/kitty/faq/#using-a-color-theme-with-a-background-color-does-not-work-well-in-vim
- alacritty: https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo
- arch wiki: https://wiki.archlinux.org/title/Tmux#Setting_the_correct_term
