### ISSUE TITLE
Unable to work with big json file

### ISSUE THREAD

**Issue by qvieth** [LunarVim/LunarVim#3149]
### Problem description

Open JSON file with a big size(about 1MB or more) is extremely slow, even when opened lvim will get stuck and don't do anything.

This problem doesn't happen with pure neovim or even VSCode can open and work with the mentioned file really fast

link to a sample json file with size of 2MB : https://raw.githubusercontent.com/miloyip/nativejson-benchmark/master/data/canada.json

### LunarVim version

rolling-e5bcf01

### Neovim version (>= 0.7.2)

NVIM v0.7.2

### Operating system/version

Fedora 36

### Steps to reproduce

Open any json file bigger than 1MB or maybe 2

### support info

 Use [q] or [Esc] to quit the window
 
 Language client log: /home/qvieth/.cache/lvim/lsp.log
 Detected filetype:   json
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: json
 
 Config: jsonls
 	filetypes:         json, jsonc
 	root directory:    /home/qvieth/programming/thesis_
 	cmd:               vscode-json-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: jsonls

**Comment by opalmay** [comment]
This is mainly because of Treesitter/syntax highlighting. You can create auto commands to disable it on large files (vscode does the same).
This is not really a bug

**Comment by opalmay** [comment]
This is mainly because of Treesitter/syntax highlighting. You can create auto commands to disable it on large files (vscode does the same).
It's not really a bug

**Comment by qvieth** [comment]
i tried to disable treesitter on json file,with the following settings, but the issue still happens

```
require'nvim-treesitter.configs'.setup {
    highlight = {
    enable = true,
    disable = function(lang, bufnr) -- Disable in large C++ buffers
        return lang == "json"
    end,
    }
}
```

```
vim.api.nvim_create_autocmd("BufEnter", {
	pattern = { "*.json" },
	command = "TSBufDisable highlight",
})
```

I'm not sure I'm creating the right autocommand please help

**Comment by opalmay** [comment]
> i tried to disable treesitter on json file,with the following settings, but the issue still happens
> 
> ```
> require'nvim-treesitter.configs'.setup {
>     highlight = {
>     enable = true,
>     disable = function(lang, bufnr) -- Disable in large C++ buffers
>         return lang == "json"
>     end,
>     }
> }
> ```
> 
> ```
> vim.api.nvim_create_autocmd("BufEnter", {
> 	pattern = { "*.json" },
> 	command = "TSBufDisable highlight",
> })
> ```
> 
> I'm not sure I'm creating the right autocommand please help

Try adding to that `:set syntax=`
To also stop the built in highlight

**Comment by qvieth** [comment]
added but the issue still happens

**Comment by ruimgoncalves** [comment]
This slowdown happens whenever I open a large file.

I was trying to view a 120m SQL file and even without syntax highlight and TSBuffDisable, its unworkable.

Previously I was using CodeArt, and was able to edit large files without any problem, even with log syntax highlight.

**Comment by kobzar** [comment]
Do you use Colorizer plugin? (Disable it for test)
Try open files with clear(default) lvim config.

**Comment by qvieth** [comment]
I tried with a lunarvim default config and the issue still happens(even after a fresh install) (pure neovim doesn't have this issue)

**Comment by opalmay** [comment]
hmm, it's probably some plugin or setting being expensive in large files.
I might play around with it later and see if I can pinpoint the cause

**Comment by LostNeophyte** [comment]
```
:TSBufDisable highlight
:IlluminatePauseBuf
:NoMatchParen
:syntax off
```
These commands work for me

**Comment by LostNeophyte** [comment]
Autocommand:
```lua
lvim.autocommands = {
  {
    { "BufEnter" },
    {
      pattern = "*",
      desc = "Disable syntax highlighting in files larger than 1MB",
      callback = function(args)
        local highlighter = require "vim.treesitter.highlighter"
        local ts_was_active = highlighter.active[args.buf]
        local file_size = vim.fn.getfsize(args.file)
        if (file_size > 1024 * 1024) then
          vim.cmd("TSBufDisable highlight")
          vim.cmd("syntax off")
          vim.cmd("syntax clear")
          vim.cmd("IlluminatePauseBuf")
          vim.cmd("IndentBlanklineDisable")
          vim.cmd("NoMatchParen")
          if (ts_was_active) then
            vim.notify("File larger than 1MB, turned off syntax highlighting")
          end
        end

      end
    }
  }
}
```

**Comment by ruimgoncalves** [comment]
Sorry, this does little to the performance of sql files >100 megs

I'm windows.

**Comment by LostNeophyte** [comment]
> Sorry, this does little to the performance of sql files >100 megs
> 
> I'm windows.

Can you provide a link to a sample SQL file that big?

**Comment by ruimgoncalves** [comment]
[test.7z.txt](https://github.com/LunarVim/LunarVim/files/9792378/test.7z.txt)

Here you go a 7zip file disguised as txt

This is just some sample data from [sql-test-data-generator](https://www.coderstool.com/sql-test-data-generator) repeated several times.

**Comment by opalmay** [comment]
> [test.7z.txt](https://github.com/LunarVim/LunarVim/files/9792378/test.7z.txt)
> 
> Here you go a 7zip file disguised as txt
> 
> This is just some sample data from [sql-test-data-generator](https://www.coderstool.com/sql-test-data-generator) repeated several times.

Using the same autocommand by @LostNeophyte works for me in that file too.

**Comment by LostNeophyte** [comment]
> Using the same autocommand by @LostNeophyte works for me in that file too.

On my end opening the file takes a minute but then it works as normal.

**Comment by opalmay** [comment]
> > Using the same autocommand by @LostNeophyte works for me in that file too.
> 
> On my end opening the file takes a minute but then it works as normal.

Takes around 20 seconds for me. I'm guessing it does some processing on the file before `BufEnter`

**Comment by gj86** [comment]
Takes about couple seconds to load the file but then it works as normal using the autocommand by @LostNeophyte.
I also tried with 3.1 MB JSON file and it also works.
Then I tried with this,
```lua
if file_size > 1024 * 1024 then
	-- vim.cmd('TSBufDisable highlight')
	-- vim.cmd('syntax off')
	-- vim.cmd('syntax clear')
	vim.cmd('IlluminatePauseBuf')
	vim.cmd('IndentBlanklineDisable')
	vim.cmd('NoMatchParen')
	if ts_was_active then
		vim.notify('File larger than 1MB, turned off syntax highlighting')
	end
end
```
And it still works as normal in both files. I've also tried with `syntax on` (for default regex highlighting) with `vim.cmd('TSBufDisable highlight')`, it also works as normal.

For me the biggest hit was with `MatchParen`, `Illuminate`, `IndentBlankline`.

Note: I'm using **Neovem 0.9-dev** with my own config generated from @ChristianChiarulli  Neovim from Scratch tutorials.

My Treesitter config,
```lua
require('nvim-treesitter.configs').setup({
	-- one of 'all', 'maintained' (parsers with maintainers), or a list of languages
	auto_install = true,
	ensure_installed = { 'lua', 'php', 'html', 'css', 'typescript', 'javascript' },
	ignore_install = {},
	parser_install_dir = vim.fn.stdpath('data') .. '/parsers',
	matchup = {
		enable = true, -- mandatory, false will disable the whole extension
		disable_virtual_text = true,
		-- disable = { 'c', 'ruby' },  -- optional, list of language that will be disabled
	},
	autopairs = {
		enable = true,
	},
	highlight = {
		enable = true, -- false will disable the whole extension
		use_languagetree = true,
		-- additional_vim_regex_highlighting = { 'php' },
		additional_vim_regex_highlighting = false,
		disable = { 'latex' },
	},
	indent = { enable = false, disable = { 'yaml', 'python' } },
	endwise = { enable = true },
	autotag = { enable = true },
	refactor = {
		smart_rename = {
			enable = true,--[[ , keymaps = { smart_rename = 'gR' } ]]
		},
		highlight_definitions = { enable = false, clear_on_cursor_move = false },
		highlight_current_scope = { enable = false },
		navigation = {
			enable = false,
			keymaps = {
				goto_definition = 'gnd',
				list_definitions = 'gnD',
				list_definitions_toc = 'gO',
				goto_next_usage = '<a-*>',
				goto_previous_usage = '<a-#>',
			},
		},
	},
	context_commentstring = { enable = true, enable_autocmd = false },
	rainbow = {
		enable = true,
		extended_mode = false, -- Highlight also non-parentheses delimiters, boolean or table: lang -> boolean
		max_file_lines = 1000, -- Do not enable for files with more than 1000 lines, int
	},
})

local keymap = require('user.utilities').keymap
keymap('n', 'gR', [[<cmd>lua require('nvim-treesitter-refactor.smart_rename').smart_rename()<CR>]], 'Smart rename')
```

**Comment by LostNeophyte** [comment]
> Takes about couple seconds to load the file but then it works as normal using the autocommand by @LostNeophyte. I also tried with 3.1 MB JSON file and it also works. Then I tried with this,
> 
> ```lua
> if file_size > 1024 * 1024 then
> 	-- vim.cmd('TSBufDisable highlight')
> 	-- vim.cmd('syntax off')
> 	-- vim.cmd('syntax clear')
> 	vim.cmd('IlluminatePauseBuf')
> 	vim.cmd('IndentBlanklineDisable')
> 	vim.cmd('NoMatchParen')
> 	if ts_was_active then
> 		vim.notify('File larger than 1MB, turned off syntax highlighting')
> 	end
> end
> ```
> 
> And it still works as normal in both files. I've also tried with `syntax on` (for default regex highlighting) with `vim.cmd('TSBufDisable highlight')`, it also works as normal.
> 
> For me the biggest hit was with `MatchParen`, `Illuminate`, `IndentBlankline`.

If I comment `vim.cmd('TSBufDisable highlight')` and leave just regex highlighting then in canada.json I get an error: `pattern uses more memory than 'maxmempattern'`. If I don't disable treesitter highlighting then moving the cursor takes something like 200ms.

**Comment by opalmay** [comment]
This works well for me, including much faster load (without the autocmd):
```
local function isLongBuf(_, bufnr)
    return vim.api.nvim_buf_line_count(bufnr) > 5000
end
lvim.builtin.treesitter.highlight.disable = isLongBuf
-- lvim.builtin.treesitter.matchup.disable = isLongBuf
-- Other TS modules...

lvim.builtin.illuminate.options.large_file_cutoff = 5000
```
Let me know how that goes, trying to figure out the best way to deal with this in source.

**Comment by LostNeophyte** [comment]
> This works well for me, including much faster load (without the autocmd):
> 
> ```lua
> vim.opt.redrawtime = 500
> local function isLongBuf(_, bufnr)
>     return vim.api.nvim_buf_line_count(bufnr) > 5000
> end
> lvim.builtin.treesitter.highlight.disable = isLongBuf
> -- lvim.builtin.treesitter.matchup.disable = isLongBuf
> -- Other TS modules...
> 
> lvim.builtin.illuminate.options.large_file_cutoff = 5000
> ```
> 
> Let me know how that goes, trying to figure out the best way to deal with this in source.

This doesn't work with `canada.json` because it only has 9 lines and also if you have `lvim.builtin.indentlines.options.show_current_context/use_treesitter` enabled then indent-blankline calls treesitter.

**Comment by LostNeophyte** [comment]
This seems to work everywhere
```lua
lvim.builtin.indentlines.options.use_treesitter = true
lvim.builtin.indentlines.options.show_current_context = true
lvim.builtin.indentlines.on_config_done = function()
  vim.g.indent_blankline_use_treesitter = false
  vim.g.indent_blankline_show_current_context = false
end

lvim.builtin.treesitter.highlight.disable = function(lang, buf)
  local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(buf))
  if ok and stats and stats.size > 1024 * 1024 then
    if lvim.builtin.illuminate.active then
      vim.cmd("IlluminatePauseBuf")
    end

    if lang == "json" then
      vim.cmd("syntax off")
      vim.cmd("syntax clear")
      vim.cmd("NoMatchParen")
    end

    vim.notify("File larger than 1MB, turned off syntax highlighting")

    return true
  else
    vim.b.indent_blankline_use_treesitter = true
    vim.b.indent_blankline_show_current_context = true

    ---@diagnostic disable-next-line: assign-type-mismatch
    vim.opt_local.foldmethod = "expr"
    ---@diagnostic disable-next-line: assign-type-mismatch
    vim.opt_local.foldexpr = "nvim_treesitter#foldexpr()"
  end
end
```

**Comment by opalmay** [comment]
```lua
vim.opt.redrawtime = 500
local chunginess = {} -- Caching is hard
function isChungusBuf(_, bufnr)
	if chunginess[bufnr] ~= nil then
		return chunginess[bufnr]
	end
	local file = vim.api.nvim_buf_get_name(bufnr)
	if not file or #file == 0 then
		chunginess[bufnr] = false
		return false
	end

	local max_filesize = 1024 * 1024
	local ok, stats = pcall(vim.loop.fs_stat, file)
	if ok and stats and stats.size > max_filesize then
		chunginess[bufnr] = true
		return true
	end

	chunginess[bufnr] = false
	return false
end
-- Can either do this...
lvim.builtin.treesitter.highlight.disable = isChungusBuf
lvim.builtin.treesitter.matchup.disable = isChungusBuf
lvim.builtin.treesitter.indent.disable = isChungusBuf
lvim.builtin.illuminate.options.large_file_cutoff = 5000

lvim.autocommands = {
	{
		{ "BufReadPre" },
		{
			pattern = "*",
			callback = function(args)
				if isChungusBuf(_, args.buf) then
					-- Or handle TS here:
					-- vim.cmd("TSBufDisable highlight")
					-- vim.cmd("TSBufDisable matchup")
					-- vim.cmd("TSBufDisable indent")

					-- vim.cmd("syntax off") -- Not needed, handled by redrawtime
					vim.cmd("IlluminatePauseBuf") -- Still needed for many columns few rows buffs
					vim.cmd("IndentBlanklineDisable")
					vim.cmd("NoMatchParen") -- I think this is the matchup TS module?

					vim.notify("Chungus buf: " .. args.buf)
				end
			end,
		},
	},
}


```

**Comment by LostNeophyte** [comment]
```lua
local function isFileBig(_, bufnr)
  -- Is caching necessary?
  if vim.b.big_file ~= nil then
    return vim.b.big_file
  end

  local file = vim.api.nvim_buf_get_name(bufnr)
  if not file or #file == 0 then
    vim.b.big_file = false
    return false
  end

  local max_filesize = 1024 * 1024
  local ok, stats = pcall(vim.loop.fs_stat, file)
  if ok and stats and stats.size > max_filesize then
    vim.b.big_file = true
    return true
  end

  vim.b.big_file = false
  return false
end

-- Putting it in the autocommand didn't work for me
lvim.builtin.treesitter.highlight.disable = isFileBig
lvim.builtin.treesitter.matchup.disable = isFileBig
lvim.builtin.treesitter.indent.disable = isFileBig
lvim.builtin.illuminate.options.large_file_cutoff = 5000

lvim.autocommands = {
  {
    { "BufReadPre" },
    {
      pattern = "*",
      callback = function(args)
        if isFileBig(_, args.buf) then
          ---@diagnostic disable-next-line: assign-type-mismatch
          vim.opt_local.redrawtime = 500
          vim.cmd("IlluminatePauseBuf")

          vim.b.indent_blankline_use_treesitter = false
          vim.b.indent_blankline_show_current_context = false

          -- sql file works fine with DoMatchParen
          if vim.endswith(args.file, ".json") then
            vim.cmd("NoMatchParen") -- otherwise cursor movement is slowed down
            -- vim.cmd("syntax off") -- For me in canada.json it hits maxmempattern and disables itsels anyway

            vim.api.nvim_create_autocmd({ "BufUnload" }, {
              command = "DoMatchParen",
              buffer = args.buf
            })
          end


          vim.notify("File larger than 1MB, turned off treesitter")
        else
          -- I had these set using vim.opt and it slowed down the opening a lot
          -- TODO: Make these overridable (if this is planned to be merged into lvim)
          ---@diagnostic disable-next-line: assign-type-mismatch
          vim.opt_local.foldmethod = "expr"
          ---@diagnostic disable-next-line: assign-type-mismatch
          vim.opt_local.foldexpr = "nvim_treesitter#foldexpr()"
        end
      end,
    }
  }
}
```

**Comment by kylo252** [comment]
@LostNeophyte, please re-write your hook to use `nvim_treesitter.config.highlight.disable` instead, see https://github.com/nvim-treesitter/nvim-treesitter/pull/3570, and open a PR so we can add it :)

**Comment by LostNeophyte** [comment]
> @LostNeophyte, please re-write your hook to use `nvim_treesitter.config.highlight.disable` instead, see [nvim-treesitter/nvim-treesitter#3570](https://github.com/nvim-treesitter/nvim-treesitter/pull/3570), and open a PR so we can add it :)

Will do but I have exams in the beginning of this week so it may wake a while

**Comment by jalemann** [comment]
I see a solution was merged already some time ago.
However, I just started using lvim and still ran into this problem.
Do I need to enable this behavior somewhere or was it removed again by now?
