### ISSUE TITLE
How to install plugin fzf? 

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3150]
How to install fzf plugin which install command given is 
```
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
```

I dont know how to deal with the first line code. 

What I write in my config.lua is
```lua
-- Additional Plugins
lvim.plugins = {
  { "junegunn/fzf.vim" },
}
```

And then after install I try the command `Files` which comes from **fzf** plugin. I get error like this. how to fix this? 

![image](https://user-images.githubusercontent.com/11295355/194034402-1143bc03-2215-4add-b183-cbd9c229903a.png)

**Comment by kobzar** [comment]
Try this one "ibhagwan/fzf-lua"

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/194102120-eeebae0f-6866-4700-8cb4-539fc84b030b.png)

you would need an equivalent command in packer, install fzf yourself, or use what @kobzar suggested.
