### ISSUE TITLE
Add support for alpha-nvim terminal banner

### ISSUE THREAD

**Issue by Pytness** [LunarVim/LunarVim#3151]
### Feature Description

Alpha-nvim added support for command output as the header in a terminal (goolord/alpha-nvim/pull/124).
There should be a way of accessing this feature.

### Describe the alternatives you have considered

I have tried executing the command and setting the output directly to header.val, but lacks any colors of the output.

### Support information

I have managed to replicate the behaviour with the following changes:

_lua/lvim/core/alpha.lua_
```lua
function M.setup()
   local alpha = require "alpha"
+  require "alpha.term"
   local mode = lvim.builtin.alpha.mode
   local config = lvim.builtin.alpha[mode].config
```

And in my config:
```lua
local dashboard = lvim.builtin.alpha.dashboard;
local alphadash = require("alpha.themes.dashboard")

local terminal = {
    type = "terminal",
    command = "<command>",
    width = image_width,
    height = image_height,

    opts = {
        redraw = true,
        window_config = {},
    },
}

-- Had to redefine buttons or it would not work
alphadash.section.buttons.val = {
    button("SPC f", "  Find File", "<CMD>Telescope find_files<CR>"),
    button("SPC n", "  New File", "<CMD>ene!<CR>"),
    button("SPC P", "  Recent Projects ", "<CMD>Telescope projects<CR>"),
    button("SPC s r", "  Recently Used Files", "<CMD>Telescope oldfiles<CR>"),
    button("SPC s t", "  Find Word", "<CMD>Telescope live_grep<CR>"),
    button("SPC L c", "  Configuration", "<CMD>edit " .. require("lvim.config"):get_user_config_path() .. " <CR>"),
}

-- ...

dashboard.config.layout = {
    terminal,
    { type = "padding", val = buttons_padding },
    alphadash.section.buttons,
    -- ...
}
```

**Comment by cpea2506** [comment]
You need to set the `lvim` table directly, not through its variable reference.

```diff
- dashboard.config.layout = {
+ lvim.builtin.alpha.dashboard.config.layout = {
    terminal,
    { type = "padding", val = buttons_padding },
    alphadash.section.buttons,
    -- ...
}
```

**Comment by Pytness** [comment]
Hi, thanks for reopening the issue.

Quoting from a [comment from that pr](https://github.com/goolord/alpha-nvim/pull/124#issuecomment-1183651560):
> pros:
> - people who don't use the terminal type don't have to load the code. i try to be pretty performance-considerate since this plugin does load every time you start neovim
>
> cons:
> - you have to first require alpha and then require term for the term thing to work.

Since `alpha` is required after loading the config, I dont see a way of requiring `alpha.term` after `alpha` (unless there is a way i dont know of)

I'll be happy to make a pr if necessary.

**Comment by cpea2506** [comment]
> Since alpha is required after loading the config, I dont see a way of requiring alpha.term after alpha (unless there is a way i dont know of)

You can put it anywhere since I see `alpha.term` has called `require ("alpha") for you.

**Comment by Pytness** [comment]
You are right. I must have missed it while tinkering.
I'll close the issue since there has been 140 commits since I opened the issue and some of them changed `dashboard.lua`, eg 8aab0f7 (probably) fixes the problem of redefining the button section.

I will catch up my config to the changes and if there is anything I see off, I'will open an issue/pr.

Thanks.
