### ISSUE TITLE
How to close the current tab and switch between tabs with config.lua open? 

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3158]
I edit a file named `test.lua` and then open config file, by press `leaderkey Lc`. It seems I get two tabs, but seems lvim take it as one tab.

1. I get two tabs here. When I type `:q`, the entire lunarvim exit not just exit the current tab. 

![image](https://user-images.githubusercontent.com/11295355/194212055-1768b389-1b6d-4c09-8de2-f4d14b14c99b.png)

2. I . And how to switch between tabs? I tried `:tabnext` and `:tabprevious` but it doesn’t work.

So my question is how to switch between tabs? And how to exit the current tab? (both with config.lua file) Thanks.

**Comment by rebuilt** [comment]
1. `:q` in vim operates on a window.  What you want is `:bd` which stands for `buffer delete`; `:h bd`.   `<Space>c` is mapped by default for this operation.   
2. To switch tabs you can run `:bnext` or `:bprev`.  Or you can click the tab name you want to switch to with your mouse.  You can also navigate next and previous position in the jump list with `<C-o>` (Control + o) and `<C-i>`.  `<Space>bn` is the default keybinding for next and `<Space>bp` is the binding for previous.   You can also set your own keybindings.  We used to bind <S-h> and <S-l> but that conflicts with basic vim movement keys.  I personally use <A-h> and <A-l>

**Comment by woshichuanqilz** [comment]
> 1. `:q` in vim operates on a window.  What you want is `:bd` which stands for `buffer delete`; `:h bd`.   `<Space>c` is mapped by default for this operation.
> 2. To switch tabs you can run `:bnext` or `:bprev`.  Or you can click the tab name you want to switch to with your mouse.  You can also navigate next and previous position in the jump list with `<C-o>` (Control + o) and `<C-i>`.  `<Space>bn` is the default keybinding for next and `<Space>bp` is the binding for previous.   You can also set your own keybindings.  We used to bind `<S-h>` and `<S-l>` but that conflicts with basic vim movement keys.  I personally use `<A-h>` and `<A-l>`

Why the buffer show like tabs? So `tab` is not used in Lvim?

**Comment by joe733** [comment]
I'm want to bind

```lua
lvim.keys.normal_mode = {
    ["<C-Tab>"] = ":bnext<cr>",
    ["<C-S-Tab>"] = ":bprev<cr>",
}
```

But that does not seem to work, what am I doing wrong?

**Comment by woshichuanqilz** [comment]
> I'm want to bind
> 
> ```lua
> lvim.keys.normal_mode = {
>     ["<C-Tab>"] = ":bnext<cr>",
>     ["<C-S-Tab>"] = ":bprev<cr>",
> }
> ```
> 
> But that does not seem to work, what am I doing wrong?
> 
> Oh wait, I think it's eaten by the terminal confounded
> 
> Nope, not working on Kitty, or Gnome-Terminal.

Yes I check the `:map <C-Tab>` found that the keymap is success. But <C-Tab> not work.

**Comment by joe733** [comment]
This works:

```lua
lvim.keys.normal_mode = {
    ["<M-t>"] = ":bnext<cr>",
    ["<M-S-t>"] = ":bprevious<cr>>",
}
```

But I would still prefer `C-Tab` over `M-t`.

**Comment by dylan-chong** [comment]
considering that the tabs/buffers are quite fundamental to an ide, and they dont work as you'd expect, wouldnt we want to document how to use tabs/buffers?
