### ISSUE TITLE
Several plugins are getting values they don't care in their configurations

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#3164]
### Problem description

I noticed that several plugins are being called their setup functions with a lot of values they don't care about.
This is the result of too general programming and the lack of type checking on Lua.
Two good examples are Telescope and nvim-cmp:
https://github.com/LunarVim/LunarVim/blob/rolling/lua/lvim/core/telescope.lua#L54-L169
https://github.com/LunarVim/LunarVim/blob/rolling/lua/lvim/lsp/null-ls/init.lua#L12-L13

Note how Telescope is getting the values of on_config_done and disabled, and a lot of options that do not apply to nvim-cmp are being passed because there is a generic function to build the options

I propose to create an specific interface for plugin configurations, where the plugin specific configs are in a defined place (eg telescope.config) and the lvim related things in a separate one.

### LunarVim version

rolling

### Neovim version (>= 0.8.0)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@HMBRW-A-001-M1-004.local  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.0/share/nvim"  Run :checkhealth for more info

### Operating system/version

macOS 12.4

### Steps to reproduce

There is nothing to reproduce

### support info

This is not a user problem, just code to be fixed

**Comment by danielo515** [comment]
Bump

**Comment by LostNeophyte** [comment]
that would introduce a breaking change with no benefit (currently) and there were too many of these recently so I think that's something we'll have to deal with when it starts giving us issues

**Comment by danielo515** [comment]
> that would introduce a breaking change with no benefit (currently) and there were too many of these recently so I think that's something we'll have to deal with when it starts giving us issues

Ok then, that's fair.
Let's wait for the next round of breaking changes 😂

**Comment by LostNeophyte** [comment]
> Ok then, that's fair. Let's wait for the next round of breaking changes joy

well, here they come https://github.com/LunarVim/LunarVim/pull/3776

this issue will be fixed by https://github.com/LunarVim/LunarVim/pull/3776/commits/75b653cc623a8cd6de397e42f21b838a065eb0e0, [the pr](https://github.com/LunarVim/LunarVim/pull/3776) also includes more breaking changes, what do you think about this it?
