### ISSUE TITLE
How to merge tabnine completion to lvim default completion popup panel? 

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3166]
### Problem description

![image](https://user-images.githubusercontent.com/11295355/194368851-81789942-0163-47b4-9383-9f028cb2d7d6.png)

Like in this case, I can just select the first item, I can not select on the coc panel.

### LunarVim version

master-e45afe9

### Neovim version (>= 0.8.0)

NVIM v0.7.2

### Operating system/version

OS: Ubuntu 22.04 jammy

### support info

same with this issue I ask days before? 
https://github.com/LunarVim/LunarVim/issues/3153

**Comment by kylo252** [comment]
the source is already configured

https://github.com/LunarVim/LunarVim/blob/16a8b92f40805f285822e24494fb7e6b6e19c1a3/lua/lvim/core/cmp.lua#L266

 just follow the same instructions as #3153

**Comment by woshichuanqilz** [comment]
> the source is already configured
> 
> https://github.com/LunarVim/LunarVim/blob/16a8b92f40805f285822e24494fb7e6b6e19c1a3/lua/lvim/core/cmp.lua#L266
> 
> just follow the same instructions as #3153


Sorry can you tell me what exaclty I need to do. The issue you post end with a 1h38m video which is too long for me. 

With other posts in that issue, 
I add `table.insert(lvim.builtin.cmp.sources, 1, { name = "cmp_tabnine" })` into my `init.lua` but not work.

**Comment by kylo252** [comment]
> I add `table.insert(lvim.builtin.cmp.sources, 1, { name = "cmp_tabnine" })` into my `init.lua` but not work.

did you install the `tabnine` plugin itself?

```lua
lvim.plugins = {
  --- ...
  { "tzachar/cmp-tabnine", run = "./install.sh", requires = "hrsh7th/nvim-cmp" },
}
```

you should follow the instructions here to make sure the account is activated: https://github.com/tzachar/cmp-tabnine#configure-tabnine-or-log-in-to-your-account
