### ISSUE TITLE
Scala metals fail to go to definition.

### ISSUE THREAD

**Issue by Readon** [LunarVim/LunarVim#3167]
### Problem description

I have installed a clean LunarVim and setup metals following the instruction on LunarVim's website.
Now metals seems works, which can help to format the code.

However, when I push down 'g' there is no 'Goto definition' on the menu.
In addition, when I push down 'gd', it will jump to the wrong position, which is only the "import" sentence in the same file.

If I run ':lua vim.lsp.buf.definition()' it will jump to the correct definition position.

There are some [sentences](https://github.com/scalameta/nvim-metals#installation) on nvim-metals, which states that nvim-lspconfig could not be used at the same time with nvim-metals. 
Wish that helps.

### LunarVim version

master-e4a5fa9

### Neovim version (>= 0.8.0)

NVIM v0.8.0-dev-1059-g2d6735d8c

### Operating system/version

Ubuntu 20.04

### Affected language servers

metals

### Steps to reproduce

Follow the steps on LunarVim Docs -> Languages -> [Scala](https://www.lunarvim.org/languages/scala.html#configure-lunarvim).

### Actual behavior

However, when I push down 'g' there is no 'Goto definition' on the menu.
In addition, when I push down 'gd', it will jump to the wrong position, which is only the "import" sentence in the same file.

If I run ':lua vim.lsp.buf.definition()' it will jump to the correct definition position.

### Expected behavior

There are "Goto definition/Goto declaration" on "g" menu.
Jump to definition works.

### support info

For LspInfo:
![image](https://user-images.githubusercontent.com/3614708/194369806-f288e818-b3ff-411a-94e8-3124aabfe791.png)
For LvimInfo:
![image](https://user-images.githubusercontent.com/3614708/194369959-107826f3-b5bf-4ade-ab53-4949a733aaf2.png)

**Comment by nwaywood** [comment]
Have you tried the scala config from [starter.lvim](https://github.com/LunarVim/starter.lvim/tree/scala-ide)

Because go to definition works for me in Scala

**Comment by Readon** [comment]
It works, thanks.
