### ISSUE TITLE
vim.opt.spell = false wont stop the spell check

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3169]
### Problem description

I want disable word spell check.
![image](https://user-images.githubusercontent.com/11295355/194462888-ffcb6697-5e7f-4065-9cf3-871d2e9a5c74.png)

* Add `vim.opt.spell = false` to init.lua file. not work.
* I type `:setlocal nospell` in command line work.
* I write `vim.cmd([[setlocal nospell]])` in init lua file not work.

So how to disable word spell check in init.lua file?

### LunarVim version

master-e45afe9

### Neovim version (>= 0.8.0)

NVIM v0.7.2

### Operating system/version

OS: Ubuntu 22.04 jammy

### support info

same with this. https://github.com/LunarVim/LunarVim/issues/3153

**Comment by tamton-aquib** [comment]
The lines responsible: https://github.com/LunarVim/LunarVim/blob/9509cadf402fd85f8a184fe334f870d701fdc48a/lua/lvim/core/autocmds.lua#L71-L78

Probable workaround: 
```lua
-- inside configlua
vim.api.nvim_create_autocmd("FileType", {
  pattern = { "markdown" },
  command = "setlocal nospell",
})
```

**Comment by pradhyu** [comment]
Thanks @tamton-aquib works like charm when added to
Had been struggling with this while using neovim in vscode as neovim won't stop spell check. 
this hack works. tan q appreciates it, but not sure why neovim doesn't have proper way to disable spell check by default and then turn it on for some. 

 config/options.lua-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
-- -- inside configlua
vim.api.nvim_create_autocmd("FileType", {
  pattern = { "drools", "java", "python", "json", "xml" },
  command = "setlocal nospell",
})
