### ISSUE TITLE
What is the approperaite way to copy the LvimVersion?

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3172]
I want to get the version of the it by command `LvimVersion`.

I read this link: 
https://unix.stackexchange.com/questions/141661/redirect-vi-command-output-to-a-file

I tried this command:
`:redir > vim.output | LvimVersion | redir END`

But I get error messages: 
`E488: Trailing characters` how to fix this?

**Comment by LostNeophyte** [comment]
In some terminals you can hold shift and select it with the mouse and then copy with the terminal's shortcut.
