### ISSUE TITLE
How to diable lsp in certain file type?

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3174]
In markdown file, I always get this lsp message box, how to disable it?
I do some google work but cant solve it.
![image](https://user-images.githubusercontent.com/11295355/194516259-65febe09-2896-4b54-aeea-a68f338a7332.png)

**Comment by LostNeophyte** [comment]
That's probably format on save. You can disable it like this: `lvim.format_on_save = false`

**Comment by woshichuanqilz** [comment]
> That's probably format on save. You can disable it like this: `lvim.format_on_save = false`

Thank you. It works as expected. Can you tell me the exactly steps you do to solve this issue? 
I get so many questions like this, and I know this is not a good question to ask here. So I want to solve it by myself.

**Comment by LostNeophyte** [comment]
> Thank you. It works as expected. Can you tell me the exactly steps you do to solve this issue? I get so many questions like this, and I know this is not a good question to ask here. So I want to solve it by myself.

I learned mostly from watching videos and live streams on Chris' channel and then just by using lvim and reading some of its code to understand how it works

**Comment by dapc11** [comment]
One can also do something like:

```lua
lvim.format_on_save = {
  pattern = { "*.lua", "*.py", "*.go" },
}
```
