### ISSUE TITLE
lvimtree loses transparency when focus changes

### ISSUE THREAD

**Issue by kajdo** [LunarVim/LunarVim#3182]
### Problem description

1. set transparent_window = true in lunarvim config
2. open nvim tree 
3. navigate to file you want to open
4. press 'l' to open a buffer
5. lvimtree loses transparency

expected:
5. lvimtree keeps transparency ;)

colorscheme: tokyonight

![image](https://user-images.githubusercontent.com/8735942/194711444-714bf955-63db-4ba3-870b-c5c71715156c.png)

### LunarVim version

rolling-099b967

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Linux mint 5.4.0-126-generic

### support info

![image](https://user-images.githubusercontent.com/8735942/194711553-1e09bf98-c235-4309-a8f5-1ce87aa81442.png)

### Screenshots

when opening lvimtree (leeder e)
![image](https://user-images.githubusercontent.com/8735942/194711468-793a8881-8f54-4359-ad9c-b7616849a553.png)

after pressing 'l' to open file
![image](https://user-images.githubusercontent.com/8735942/194711488-6555d0fb-b7a2-41c0-a9b3-6e518858e027.png)

**Comment by cpea2506** [comment]
Currently, `NvimTreeNormalNC` is not considered a part of transparency from `lvim`. So please refer to your colorscheme documentation to find if there is any setup that relates to transparency or put to your `config.lua` file an autocmd:

```lua
lvim.autocommands = {
  -- .. other cmd
  {
    "ColorScheme",
    {
      desc="Transparent NvimTree on unfocused",
      command = "hi link NvimTreeNormalNC NormalNC"
    }
  }
}
```

**Comment by opalmay** [comment]
I can't replicate this with tokyonight but looks like their transparency support is a bit meh in general. You would probably be better off switching to something like catppuccin.

**Comment by kajdo** [comment]
got a tip from a matrix user which closes nvimtree immediately after a file is chosen -- this works great with my workflow and I don't really want to mess around with individual changes on the colorschemes itself.

since my problem is fixed - i close the issue to keep the tracker clean - thx for the great tool and the support here and in discord/matrix
