### ISSUE TITLE
Navigating windows causes the status bar to flicker

### ISSUE THREAD

**Issue by nwaywood** [LunarVim/LunarVim#3188]
### Problem description

I brought up this issue on @ChristianChiarulli 's stream. He thinks that it may be an issue with the `laststatus` autocmd.

### LunarVim version

Latest rolling

### Neovim version (>= 0.8.0)

v0.8.0 stable release

### Operating system/version

macOS

### Steps to reproduce

1. Open a file in lvim
2. Open a split, `:vsplit`
3. Navigate between the two windows (C-h, C-l)
4. Observe the flickering of the status bar

**Comment by ChristianChiarulli** [comment]
https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine.lua#L508 << this line
https://github.com/LunarVim/LunarVim/blob/rolling/lua/lvim/core/autocmds.lua#L132 << is why I need this autocmd

which makes the statusline blink, with this removed only the first element (the mode with the little orbit icon it) will blink

**Comment by ChristianChiarulli** [comment]
Also in out builtin we had globalstatus explicitly set to false which was triggering the above line. It should be fixed on rolling now.

**Comment by nwaywood** [comment]
@ChristianChiarulli I just pulled the latest rolling. Yeah it seems a lot better now!

> with this removed only the first element (the mode with the little orbit icon it) will blink

Yeah it seems like this element as well as the last element (the position in the file) still blink, aside from that the rest of the flickering seems to be gone

**Comment by nwaywood** [comment]
Closing this, the blinking seems to be gone now too 🎉
