### ISSUE TITLE
failed to add cspell code action

### ISSUE THREAD

**Issue by lhiamgeek** [LunarVim/LunarVim#3194]
### Problem description

1. config cspell in null-ls code action, an error popup:
failed to load build in cspell for method code actions.

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

centos7

### Steps to reproduce

1. update config.lua with the following code:
`local code_actions = require "lvim.lsp.null-ls.code_actions"
code_actions.setup {
  {
    command = "cspell",
  },
}`
2. save config.lua
3. failed to load build in cspell for method code actions

### support info

```
2022-10-10 02:47:52 [ERROR] lvim: "Not a valid source: cspell"   file="lvim/lsp/null-ls/services.lua", line=77
   14 2022-10-10 02:50:48 [ERROR] lvim: "Not a valid source: cspell"   file="lvim/lsp/null-ls/services.lua", line=77
   15 2022-10-10 02:52:32 [ERROR] lvim: "Not a valid source: cspell"   file="lvim/lsp/null-ls/services.lua", line=77
   16 2022-10-10 02:53:51 [ERROR] lvim: "Not a valid source: cspell"   file="lvim/lsp/null-ls/services.lua", line=77
   17 2022-10-10 02:55:07 [ERROR] lvim: "Not a valid source: cspell"   file="lvim/lsp/null-ls/services.lua", line=77
   18 2022-10-10 02:55:19 [ERROR] lvim: "Not a valid source: cspell"   file="lvim/lsp/null-ls/services.lua", line=77
```

### Screenshots

<img width="769" alt="image" src="https://user-images.githubusercontent.com/26346086/194793388-e9f4003c-4cc1-4646-a33a-d0a2cdab29fc.png">

**Comment by cpea2506** [comment]
`cspell` code action was added in the recently null-ls [commit](https://github.com/jose-elias-alvarez/null-ls.nvim/commit/da0359adceedab05a898471b160983fd0a92554b) which is not available until a next plugin version bump coming in `master` branch.

**Comment by lhiamgeek** [comment]
@cpea2506 thanks, then there is no problem.
