### ISSUE TITLE
Design critique: functionality of keyboard arrows in file explorer

### ISSUE THREAD

**Issue by thisismygitrepo** [LunarVim/LunarVim#3195]
### Feature Description

In the explorer `Space + e`, when I use arrows, all I get is a meaningless and useless rectangle highlighting individual letters of file name as seen here:

<img width="216" alt="image" src="https://user-images.githubusercontent.com/46288868/194843201-c4a8ef9a-64bb-450b-82bb-93bd47b9465b.png">

Can I please ask developers to change the default binding of keys such that arrows are used to expand and collapse folders?  This is the case indeed in `Spacevim` and I found it particularly sane design choice. Additionally, `Enter` **changes the current working directory to that folder**, so they seem to have immense flexibility. I loved this behaviour of `spacevim`, otherwise I found `lunarvim` superior.

**Comment by abzcoding** [comment]
you can already customize that:

by adding this to your `~/.config/lvim/config.lua`
```lua
lvim.builtin.nvimtree.setup.view.mappings.list = {
  { key = { "<CR>", "<Right>" }, action = "edit", mode = "n" },
  { key = "<Up>", action = "dir_up" },
  { key = "<Left>", action = "close_node" },
  { key = "v", action = "vsplit" },
}
```
for more mappings checkout nvim-tree help
using
```vim
:help nvim-tree-default-mappings
```
or
```vim
:help nvim-tree-mappings
```

**Comment by kobzar** [comment]
I think we can close this issue.
