### ISSUE TITLE
Config Treesitter Query Injections

### ISSUE THREAD

**Issue by LeviticusNelson** [LunarVim/LunarVim#3197]
### Feature Description

I want to inject sql syntax highlighting into my .go files but it seems that I cannot easily add `queries/go/injections.scm` into my `.config/lvim` path. I know my query that I wrote is correct because I was able to test it using `TSPlaygroundToggle`.

**Comment by abzcoding** [comment]
you can add them in `~/.config/lvim/after/queries` (e.g [my config](https://github.com/abzcoding/lvim/tree/main/after/queries))

**Comment by LeviticusNelson** [comment]
> you can add them in `~/.config/lvim/after/queries` (e.g [my config](https://github.com/abzcoding/lvim/tree/main/after/queries))

@abzcoding I forgot to mention that I have also tried that as well. This is what I have in my injections.scm: 
```{query}
(call_expression
  (selector_expression
    operand: (identifier) @operand 
    field: (field_identifier) @field (#eq? @field "Exec"))
  (argument_list
    (raw_string_literal) @sql
)
) 
```

**Comment by abzcoding** [comment]
> > you can add them in `~/.config/lvim/after/queries` (e.g [my config](https://github.com/abzcoding/lvim/tree/main/after/queries))
> 
> @abzcoding I forgot to mention that I have also tried that as well. This is what I have in my injections.scm:
> 
> ```
> (call_expression
>   (selector_expression
>     operand: (identifier) @operand 
>     field: (field_identifier) @field (#eq? @field "Exec"))
>   (argument_list
>     (raw_string_literal) @sql
> )
> ) 
> ```

and do you also have `; extends`
at the top of that file?

**Comment by LeviticusNelson** [comment]
@abzcoding yes I do

**Comment by abzcoding** [comment]
> @abzcoding yes I do

can confirm that the issue exists, I'll work on it asap

**Comment by LeviticusNelson** [comment]
@abzcoding I figured out the issue, it seems that I need to add an underscore for each identifier: 
```{query}
; extends
(call_expression
  (selector_expression
    operand: (identifier) @_operand 
    field: (field_identifier) @_field (#eq? @_field "Exec"))
  (argument_list
    (raw_string_literal) @sql
    (#offset! @sql 1 0 -1 0)) ;; The offset was extra but wasn't necessary for this to work
) 
```

**Comment by abzcoding** [comment]
oh ok 😅
