### ISSUE TITLE
fzf history gets refreshed when using floating terminal in lunarVim

### ISSUE THREAD

**Issue by kanishkaverma** [LunarVim/LunarVim#3198]
hey, 
Hope you are having a good day. I just had a problem. whenever I use the inbuilt terminal in lunarvim and press ctrl-r to view my history. it's always empty. My history gets refreshed every time I close and open lunarvim. do you know how I can solve this problem? 
Thank you so much for your time. 
warmest regards, 
kanishka

**Comment by kylo252** [comment]
- what shell do you use outside of lunarvim?
- what operating system are you on?
- what's the output of `:echo &shell`?
- do you have the same issue if you start the terminal with `:term`?
