### ISSUE TITLE
How to unmap a which_key map false not work?

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3204]
As the title said, 
If I put this code `lvim.builtin.which_key.mappings["w"] = false` into my config file. I will get this error.

![image](https://user-images.githubusercontent.com/11295355/195118382-9acd102f-a56e-4985-9c67-a0c5c055ea04.png)

I check this link, https://www.lunarvim.org/docs/configuration/keybindings, 
seem no direct answer to this question. How to unmap this which_key keymap?

**Comment by LostNeophyte** [comment]
Use `nil` instead of `false`.

**Comment by abzcoding** [comment]
you can either use 
```lua
lvim.builtin.which_key.mappings["w"] = {}
```
or 
```lua
lvim.builtin.which_key.mappings["w"] = nil
```
