### ISSUE TITLE
Why plug keymap in vim.cmd not work util reload the config lua manually

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3205]
I get two lines of map here:
```
map  <Leader>w <Plug>(easymotion-bd-w)
nmap <Leader>w <Plug>(easymotion-overwin-w)
```

Since I don't know how to remap `<Plug>` functions in lua.
So I write these code into `vim.cmd`. 

But these keymap not work when you start lvim, utill you reload the lua file manually. 

So I get two question here:
1. How to auto load these two keymap?
2. How to may `map  <Leader>w <Plug>(easymotion-bd-w)` in lua?

**Comment by abzcoding** [comment]
you can either use our syntax:

```lua
lvim.builtin.which_key.mappings["w"] = { "<Plug>(easymotion-bd-w)", "doing sth"}
```

or just disable it and use your own
```lua
lvim.builtin.which_key.mappings["w"] = {}
vim.cmd [[
map  <Leader>w <Plug>(easymotion-bd-w)
nmap <Leader>w <Plug>(easymotion-overwin-w)
]]
```
or even use the neovim way 
```vim
:h vim.keymap.set()
```
