### ISSUE TITLE
Lunar vim display bug

### ISSUE THREAD

**Issue by paspielka** [LunarVim/LunarVim#3209]
### Problem description

Lunar ui is completely blank doesn't have collars ect.

### LunarVim version

c6fd52b

### Neovim version (>= 0.8.0)

0.8.0

### Operating system/version

macOS BigSur 11.4

### Steps to reproduce

![Uploading Screenshot 2022-10-12 at 13.36.17.png…]()

### support info

Can't even read it there's no text.

### Screenshots

<img width="1439" alt="Screenshot 2022-10-12 at 13 36 03" src="https://user-images.githubusercontent.com/111129697/195321522-2a99cf05-ac96-4690-accc-0ae578ef6627.
<img width="1419" alt="Screenshot 2022-10-12 at 13 37 56" src="https://user-images.githubusercontent.com/111129697/195321560-8f104bdd-db68-462f-aefc-50577495e9e2.png">
png">
![Uploading Screenshot 2022-10-12 at 13.36.03.png…]()
<img width="1440" alt="Screenshot 2022-10-12 at 13 36 17" src="https://user-images.githubusercontent.com/111129697/195321554-fc9d2b9a-b9ae-4091-b31b-4460835d10e5.png">

**Comment by kobzar** [comment]
Disable Transparency mode in terminal first

**Comment by abzcoding** [comment]
also please don't use `Terminal.app` 😅 
use kitty,wezterm,iterm,alacrity, ...
