### ISSUE TITLE
Mouse settings is wrong

### ISSUE THREAD

**Issue by kobzar** [LunarVim/LunarVim#3210]
### Problem description

I don't use mouse in my work (only in rare cares).
So, i disable it in my configs.  But sometime i'm need copy/paste text from floating terminal window to other place. 
The long time all was fine. But after the last updates, mouse seting is broken. 
If i try use any setting for mouse unless:
```
vim.opt.mouse = "a"
```
for example:
```
vim.opt.mouse = ""
vim.opt.mouse = "n"
vim.opt.mouse = "nv"
```
When i try select some thing from Terminal - the select area cath Editor field too. 
Its look next:
![2022-10-11_11-26_1](https://user-images.githubusercontent.com/1912842/195327054-8eb37bcc-d3b0-4b4f-970a-96d2606c25a4.png)

The user CPea make retest it with his configuration with the same result. 

### LunarVim version

Last

### Neovim version (>= 0.8.0)

NVIM v0.8.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"

### Operating system/version

Arch

### support info

```

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                lua
* bufnr:                   6
* treesitter status:       active

Active client(s)
* name:                      pyright
* id:                        1
* supported filetype(s):     python
* attached buffers:          1
* root_dir pattern:          1
* capabilities:              callHierarchyProvider
* name:                      sumneko_lua
* id:                        3
* supported filetype(s):     lua
* attached buffers:          6
* root_dir pattern:          6
* capabilities:              documentFormattingProvider      | workspaceSymbolProvider | definitionProvider
                             documentRangeFormattingProvider | typeDefinitionProvider  | documentSymbolProvider
                             colorProvider                   | referencesProvider      | documentHighlightProvider
                             hoverProvider                   | foldingRangeProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels, rust_analyzer]

Formatters info
* Active: stylua  
* Supported: [lua_format, stylua]

Linters info
* Active: luacheck  
* Supported: [luacheck, selene]

Code actions info
* Active: 

```

**Comment by cpea2506** [comment]
I just think it's not an issue with `LunarVim`. When you disable `mouse` in `neovim`, the mouse will see the whole neovim instance just like a normal terminal interface. That's when you can select all things available in your terminal. 

<img width="1296" alt="Screenshot 2022-10-14 at 20 32 18" src="https://user-images.githubusercontent.com/42694704/195859476-ec071818-f8d8-41a2-a0ac-04ed9e71c3a7.png">

**Comment by kobzar** [comment]
Yes. But i am interesting in 
```
vim.opt.mouse = ""
```

**Comment by opalmay** [comment]
Disabling mouse means selection is handled by the terminal emulator, not the application. In Alacritty by default holding ctrl you can do a block selection.

**Comment by techsk8** [comment]
> Yes. But i am interesting in
> 
> ```
> vim.opt.mouse = ""
> ```

This worked for me perfectly to completely disable the mouse inside lunarvim.
