### ISSUE TITLE
[spike][neotest] should we add neotest?

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#3215]
LunarVim would like to provide a simple and standard interface for testing. Neotest seems to be blazing that trail.

- find out if neotest is a good addition to lunarvim
- implement as core plugin if so

**Comment by JBSK8NC** [comment]
I can take it.

**Comment by kylo252** [comment]
## Considerations

#### what are the benefits of adding this to core?

so far, this is only setting up keybinds, which are typically opinionated anyway and are probably better configured by the end-user

#### how does this play with dap?

is there any conflict? is there an integration

#### how to enable extra runners? 

we can **not** add 20 plugins just for test-runner, so this might be better added in `lvim.plugins` where one can add the test-runners they care about

**Comment by kylo252** [comment]
as discussed in https://github.com/LunarVim/LunarVim/pull/3227#issuecomment-1279223228, this will be moved into starter.lvim
