### ISSUE TITLE
[WSL] Installation doesn't go through

### ISSUE THREAD

**Issue by jeeeem** [LunarVim/LunarVim#3216]
### Problem description

First installation of nightly version of Lunarvim in WSL encountering an error in creation of desktop file causing the LunarVim installation not proceeding to install everything including the necessary plugins.

### LunarVim version

rolling-ea1ebda

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-77-gf175ca9f7

### Operating system/version

WSL

### support info

Nan

### Screenshots

![image](https://user-images.githubusercontent.com/51053482/195469070-6bf98857-4a19-4f41-8c4a-0c0be3dabdd7.png)

After creating `.local/share/applications` folder
![image](https://user-images.githubusercontent.com/51053482/195469531-03666ff3-27b6-402b-b75a-c551285e3581.png)

**Comment by jeeeem** [comment]
I could solve this by installing `xdg-utils`  but there should be a way to proceed with installation if I will not gonna be using DE in my WSL

**Comment by kobzar** [comment]
This is bad idea - because we are can use it on the servers

**Comment by thismat** [comment]
This could be solved pretty easily by just checking for `xdg-desktop-menu` and just bypassing the DE file installation where it is already checking for a valid Linux OS.

I'd be happy to make the change.

**Comment by ChristianChiarulli** [comment]
@opalmay you might have more context for this, @thismat if you have fix I'll gladly accept it.

**Comment by thismat** [comment]
Looks like it was handled, I had not worked on it yet. 👍🏻

**Comment by opalmay** [comment]
Sorry, a bit of an oversight on my part when adding this. had to get it fixed myself
