### ISSUE TITLE
`smartindent` causes some lines unable to be indented

### ISSUE THREAD

**Issue by yifeikong** [LunarVim/LunarVim#3219]
### Problem description

Any lines starting with a `#` is unable to be indented with `>>`.

There are articles[1][2] saying that `smartindent` is deprecated and should not be set.

1. https://stackoverflow.com/questions/7281107/vim-cant-indent-lines-if-first-character-starts-with-a
2. https://vim.fandom.com/wiki/Restoring_indent_after_typing_hash

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

macOS 12.0

### Steps to reproduce

1. Open any file with lines like `# this is a title`
2. Use `>>` on that line
3. This line is not indented

### support info

not applicable

**Comment by opalmay** [comment]
@kylo252 Any concerns removing that setting?

**Comment by kylo252** [comment]
> @kylo252 Any concerns removing that setting?

sure, please create a new PR for that.

we should probably follow the choices made in:
https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L62-L100
