### ISSUE TITLE
Python: pyright can't find import directories

### ISSUE THREAD

**Issue by eliavo** [LunarVim/LunarVim#3220]
### Problem description

when initiating pyright in my python project, pyright can't seem to find import paths and produces:
"Import {} can't be resolved".
I have opened a project at "root" directory, and I am on a subdirectory "root/foo/bar/baz/blah.py",
pyright can't resolve: `from foo.bar.baz.help import example`, `import bar.database` exc.
it seems pyright automatically sets the root directory to the python directory and not to the open project directory.
seems like a weird behavior and I don't know how to fix it...
when using `:LspLog` I get:
`"stubPath /home/user/root/foo/bar/baz/typings is not a valid directory."`
and:
`"server_request: no handler found for" "workspace/diagnostics/refresh`

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

ubuntu 20.04

### Affected language servers

pyright

### Actual behavior

pyright can't retrieve import directories

### support info

![Screen Shot 2022-10-13 at 11 04 21](https://user-images.githubusercontent.com/76263733/195538571-2492c9c1-753a-4da9-8618-ca7c95cda76f.png)
![Screen Shot 2022-10-13 at 11 04 54](https://user-images.githubusercontent.com/76263733/195538581-d5ddd368-2b4d-4a01-8de9-5aa858ccaa6a.png)

**Comment by ChristianChiarulli** [comment]
try adding a pyrightconfig.json

**Comment by eliavo** [comment]
> try adding a pyrightconfig.json

I have this file in the project root but pyright doesn't seem to read the file since it seems to read only from the root/bar/baz directory...

**Comment by eliavo** [comment]
**UPDATE**
I've tried switching to Jedi-language-server, still the same problem there.
I do not know where the problem might be, since root dir detection is ok in clangd.
I've tried configuring the :LspSettings pyright, configuring a pyright.json file in the project root and passing through the:
require("lvim.lsp.manager").setup(name, opts), opts = { root_dir = require("lspconfig").util.root_pattern('.git') }, and:
`opts = {
settings = {
[name] = {
root_dir = ...
}
}
}`
none work...

**Comment by LostNeophyte** [comment]
Default root dir is [this](https://github.com/neovim/nvim-lspconfig/blob/67f0d0025b118e7e328396d7732d97415a9afda4/lua/lspconfig/server_configurations/pyright.lua#L10-L17)
You can try this:

lvim/config.lua:
```lua
vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "pyright" })
```
lvim/ftplugin/python.lua
```lua
require("lvim.lsp.manager").setup("pyright", { root_dir = require("lspconfig").util.root_pattern(".git") })
```
And then run `:LvimCacheReset`

**Comment by LostNeophyte** [comment]
> thanks for the comment! it still doesn't recognize my root directory...

Do you have a git repo there?

**Comment by eliavo** [comment]
> Do you have a git repo there?

No its internal.
Ill try to replicate.

**Comment by LostNeophyte** [comment]
> Default root dir is [this](https://github.com/neovim/nvim-lspconfig/blob/67f0d0025b118e7e328396d7732d97415a9afda4/lua/lspconfig/server_configurations/pyright.lua#L10-L17) You can try this:
> 
> lvim/config.lua:
> 
> ```lua
> vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "pyright" })
> ```
> 
> lvim/ftplugin/python.lua
> 
> ```lua
> require("lvim.lsp.manager").setup("pyright", { root_dir = require("lspconfig").util.root_pattern(".git") })
> ```
> 
> And then run `:LvimCacheReset`

With this config it needs a git repo to recognize a root dir

**Comment by eliavo** [comment]
> > Default root dir is [this](https://github.com/neovim/nvim-lspconfig/blob/67f0d0025b118e7e328396d7732d97415a9afda4/lua/lspconfig/server_configurations/pyright.lua#L10-L17) You can try this:
> > 
> > lvim/config.lua:
> > 
> > ```lua
> > vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "pyright" })
> > ```
> > 
> > lvim/ftplugin/python.lua
> > 
> > ```lua
> > require("lvim.lsp.manager").setup("pyright", { root_dir = require("lspconfig").util.root_pattern(".git") })
> > ```
> > 
> > And then run `:LvimCacheReset`
> 
> With this config it needs a git repo to recognize a root dir

I know, I have a .git folder and the repo is initialized.
I guess I misunderstood, I thought you wanted to clone the repo for replication

**Comment by LostNeophyte** [comment]
What do last lines of LSP log say `leader L l L` and :LspInfo

**Comment by eliavo** [comment]
The last couple thousands of lines say this:
`[ERROR][2022-10-31 15:04:28] .../vim/lsp/rpc.lua:733	"rpc"	"jedi-language-server"	"stderr"	'WARNING:pygls.protocol:Cancel notification for unknown message id "5241"\n'`

:LspInfo shows this:
![Screen Shot 2022-10-31 at 21 14 29](https://user-images.githubusercontent.com/76263733/199091147-f73b5bcf-e200-4d5f-82d5-5edf5a00f26d.png)

note this is Jedi-ls but I have tried with pyright your suggestion and it works the same

**Comment by LostNeophyte** [comment]
What if you use my pyright suggestion but substitute pyright with Jedi?

**Comment by LostNeophyte** [comment]
The problem is that root should be core systems and  not suites right?

**Comment by eliavo** [comment]
> What if you use my pyright suggestion but substitute pyright with Jedi?

I did do that

**Comment by eliavo** [comment]
> What if you use my pyright suggestion but substitute pyright with Jedi?

yeah

**Comment by LostNeophyte** [comment]
What are all the files and folders in suites?

**Comment by eliavo** [comment]
> What are all the files and folders in suites?

the structure is like that:
core-system/
    modules/
        module_to_include.py
    nas/
         tests/
                {...}/
                        my_python_file.py     /* this file includes module_to_include by saying:  "import modules.module_to_include"

**Comment by LostNeophyte** [comment]
I don't really know what more we could do, you can try running LvimCacheReset once more but it probably  won't fix it

**Comment by LostNeophyte** [comment]
I would need a simple python project where you have this issue to troubleshoot this more

**Comment by eliavo** [comment]
> I would need a simple(not necessary simple, but one you don't mind sharing) python project where you have this issue to troubleshoot this more

I agree. I'll reproduce and continue this thread.
