### ISSUE TITLE
Line Diagnostics too long, any better way to display?

### ISSUE THREAD

**Issue by felixpohlmann** [LunarVim/LunarVim#3228]
### Problem description

The diagnostics text can't be read in many cases, especially when vertical split screen is in use.

Is there any possibility to visualise the diagnostics in a more convenient way (e.g. floating window with line breaks or something like that)?

Steps to reproduce:

1. Make sure there is a diagnostics entry in an open file
2. Crop down so the text gets cut off 

### LunarVim version

master-1468aea

### Neovim version (>= 0.8.0)

v0.7.2

### Operating system/version

macOS 12.3.1

### support info

![Screenshot 2022-10-14 at 00 03 10](https://user-images.githubusercontent.com/68960775/195719341-cd861136-99e0-41af-87be-512761283962.png)

### Screenshots

![Screenshot 2022-10-13 at 23 56 31](https://user-images.githubusercontent.com/68960775/195719209-2974ca4a-18c7-428e-ac9d-3f0850ef3339.png)

**Comment by kobzar** [comment]
try to use lsp_lines or disable virtual_text by default and use SPS + g + l to show error for selected line.

**Comment by felixpohlmann** [comment]
Thanks for the tip @kobzar! 🎉  I've just installed lsp_lines and it does what i wanted! But now i get duplicate diagnostics, the old ones and the 'new', better ones from lsp_lines.

On page i found it says:
[Source](https://git.sr.ht/~whynothugo/lsp_lines.nvim)

"
It's recommended to also remove the regular virtual text diagnostics to avoid pointless duplication:

-- Disable virtual_text since it's redundant due to lsp_lines.
vim.diagnostic.config({
  virtual_text = false,
})
"

Any tip where to place this statement? Return an invalid config when placing it within config.lua...

Thanks in advance!

**Comment by kobzar** [comment]
https://github.com/LunarVim/LunarVim/issues/2843#issuecomment-1195118661

**Comment by ksajan** [comment]
I am getting depreciated error and saying to use `vim.diagnostic.config({
  virtual_text = false,
})`

I am on nvim version `NVIM v0.9.1`
and lunarvim version `master-15dc5292`
<img width="1800" alt="Screenshot 2023-09-05 at 9 49 25 PM" src="https://github.com/LunarVim/LunarVim/assets/31013555/c6cebaed-e428-4599-b80c-3234d0ce0ba3">
<img width="1800" alt="Screenshot 2023-09-05 at 9 49 38 PM" src="https://github.com/LunarVim/LunarVim/assets/31013555/d31b27cc-48f8-4398-91b1-325639cecb88">
