### ISSUE TITLE
TreeResize

### ISSUE THREAD

**Issue by rafabiela** [LunarVim/LunarVim#3231]
is it possible to adjust the NvimTreeResize property in the settings?

**Comment by LostNeophyte** [comment]
You can change the width like this:
`lvim.builtin.nvimtree.setup.view.width = 50`

**Comment by rafabiela** [comment]
didn't work, the width still remains 50% of the terminal

**Comment by cpea2506** [comment]
> didn't work, the width still remains 50% of the terminal

```lua
lvim.builtin.nvimtree.setup.actions.open_file.resize_window = true
```

**Comment by rafabiela** [comment]
Nice! Thank you for your help!!!
