### ISSUE TITLE
Lunarvim should by default find the current installed M1 rust-analyzer

### ISSUE THREAD

**Issue by ksandvik** [LunarVim/LunarVim#3239]
### Problem description

Rust analyzer installed via brew and the path to open it works:
14:45|ksandvik@GQCGJ3G4WN| ~> rust-analyzer --version
rust-analyzer 0.0.0 (61504c8d9 2022-10-08)

Opening .rs file with lunarvim:

LSP[rust_analyzer] rust-analyzer field to load workspace: could not find lib core in sysroot path '...../.rustup/toolchains/stable-x86_64-apple-darwin/lib'

Note this is an M1 arm arch device, not intel x86_64, so there's maybe some assumption in lunarvim setup (or then a default brew upgrade is totally wrong)./

### LunarVim version

master-e45fe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

MacOSX 12.6

### Affected language servers

rust

### Steps to reproduce

1. Install rust-analyzer with brew
2. Install lvim
3. open .rs file with lvim

### Actual behavior

See report above

### Expected behavior

LSP works as expected.

### support info

I assumed LSP clients were installed automatically when opening rs file?

**Comment by cpea2506** [comment]
I try with `brew` and everything looks good. Maybe you need to check your rust-toolchain

<img width="541" alt="Screenshot 2022-10-15 at 11 51 45" src="https://user-images.githubusercontent.com/42694704/195969333-ace90dfb-67c2-4997-89b9-99def6a3baa7.png">

**Comment by kobzar** [comment]
try change shell for lvim to bash  or sh
```
vim.opt.shell = "/bin/sh"
```

**Comment by ChristianChiarulli** [comment]
this is more of an issue for mason

**Comment by ksandvik** [comment]
rustup toolchain list
stable-aarch64-apple-darwin (default)

**Comment by ksandvik** [comment]
vim.opt.shell = "/bin/sh"
didn't help. Suspect something strange with the local setup, what it is I don't know as the brew install was brand new for an M1 system.

**Comment by brohamgoham** [comment]
why was this issue closed, when not resolved ? I am having same issue with Lvim not loading Rust-analyzer

**Comment by kobzar** [comment]
Please, open new issue. 
show your version of lvim, nvim e.t.c
Now we have 3 releases 1.3 1.2 and master. 
read it on lunarvim.org
