### ISSUE TITLE
Undefined global 'lvim' with sumneko_lua

### ISSUE THREAD

**Issue by sgoudham** [LunarVim/LunarVim#3240]
### Problem description

When opening my `config.lua`, the sumneko_lua language server shows the warning `Undefined global: lvim` and `Undefined global: vim`

It looks like a similar issue was resolved before:
- https://github.com/LunarVim/LunarVim/issues/2076

### LunarVim version

rolling-1fbdcab

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

WSL2 / Ubuntu 20.04

### Affected language servers

sumneko_lua

### Steps to reproduce

1. Open config.lua
2. Wait for LSP to load
3. Observe the warnings as specified above

### Actual behavior

Warnings such as `Undefined global: lvim` and `Undefined global: vim` appear after the LSP loads

### Expected behavior

The LSP should recognise globals `lvim` and `vim`

### support info

`LvimInfo`
```
    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                lua
* bufnr:                   3
* treesitter status:       active

Active client(s)
* name:                      sumneko_lua
* id:                        1
* supported filetype(s):     lua
* attached buffers:          3
* root_dir pattern:          3
* capabilities:              definitionProvider      | foldingRangeProvider            | documentHighlightProvider
                             workspaceSymbolProvider | typeDefinitionProvider          | documentSymbolProvider
                             colorProvider           | documentRangeFormattingProvider | referencesProvider
                             hoverProvider           | documentFormattingProvider
* name:                      gopls
* id:                        2
* supported filetype(s):     [go, gomod, gowork, gotmpl]
* attached buffers:          14
* root_dir pattern:          14
* capabilities:              definitionProvider      | hoverProvider              | documentHighlightProvider
                             implementationProvider  | foldingRangeProvider       | documentSymbolProvider
                             workspaceSymbolProvider | typeDefinitionProvider     | referencesProvider
                             callHierarchyProvider   | documentFormattingProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels, hls]

Formatters info
* Active: 
* Supported: [lua_format, stylua]

Linters info
* Active: 
* Supported: [luacheck, selene]

Code actions info
* Active: 
```

`LspInfo`
```
 Use [q] or [Esc] to quit the window
 
 Language client log: /home/sgoudham/.local/state/nvim/lsp.log
 Detected filetype:   lua
 
 1 client(s) attached to this buffer: 
 
 Client: sumneko_lua (id: 1, pid: nil, bufnr: [3])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /home/sgoudham/.config/lvim
 	cmd:             lua-language-server
 
 Configured servers list: sumneko_lua, hls
```

### Screenshots

![image](https://user-images.githubusercontent.com/58985301/195955626-2a29cdfd-697a-4df2-9195-cca6890d5b64.png)

**Comment by abzcoding** [comment]
resolved via https://github.com/LunarVim/LunarVim/commits/rolling
this should be fixed in the latest `rolling` release

if not, please remove the `~/.config/lvim/plugin` folder
and run `:PackerCompile`
that should fix it

**Comment by sgoudham** [comment]
That fixed it for me, thanks!

**Comment by JeremiahCheatham** [comment]
After and update i am now receiving this. My love2d code is filled with undefined globals now. lua-language-server is not loading any of the required modules. I have since reinstalled lvim and also tried whats posted above. It is also not recognizing it as a love2d project anymore giving even more errors.
