### ISSUE TITLE
LSP issue with jdtls

### ISSUE THREAD

**Issue by JonathanGDiaz** [LunarVim/LunarVim#3243]
### Problem description

Up to about 2 weeks ago everything was working fine, then when I started opening a java file LSP would throw "Client 1 quit with exit code 13 and signal 0" in the notification and LS would remain inactive.

### LunarVim version

rolling-e5bcf01

### Neovim version (>= 0.8.0)

nvim v0.8.0

### Operating system/version

Arch Linux

### Affected language servers

jdtls

### Actual behavior

LSP gives the next notification and LS is inactive.
![image](https://user-images.githubusercontent.com/94073304/195966315-9c8e80a7-2071-40a5-8bd7-de8c829f0d04.png)

### support info

![image](https://user-images.githubusercontent.com/94073304/195966282-9f40a9ac-1529-49fe-80ff-85e7e5af309e.png)

### logs

```console
[ERROR][2022-10-04 20:30:39] .../vim/lsp/rpc.lua:733	"rpc"	"jdtls"	"stderr"	"WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector\n"
[WARN][2022-10-04 20:30:42] ...lsp/handlers.lua:113	"The language server jdtls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2022-10-04 20:30:53] LSP logging initiated
[ERROR][2022-10-04 20:30:53] .../vim/lsp/rpc.lua:733	"rpc"	"jdtls"	"stderr"	"WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector\n"
[WARN][2022-10-04 20:30:55] ...lsp/handlers.lua:113	"The language server jdtls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2022-10-08 15:24:52] LSP logging initiated
[WARN][2022-10-08 15:24:52] .../lua/vim/lsp.lua:1072	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-10-08 15:26:29] LSP logging initiated
[WARN][2022-10-08 15:26:29] .../lua/vim/lsp.lua:1072	"server_request: no handler found for"	"workspace/diagnostic/refresh"
```

**Comment by ChristianChiarulli** [comment]
need to know java version

**Comment by JonathanGDiaz** [comment]
It is the JDK 19.0.1

**Comment by LostNeophyte** [comment]
Try renaming/deleting ~/.cache/jdtls. And if that doesn't work switch to 17 and delete cache again

**Comment by JonathanGDiaz** [comment]
> Try renaming/deleting ~/.cache/jdtls. And if that doesn't work switch to 17 and delete cache again

Installing and changing jdk17 to be the default seems to fix the issue of LSP not working. Now LSP works how it is supposed to, However every time I open a file the next error appears:

![image](https://user-images.githubusercontent.com/94073304/198859649-3e9d28fe-a7d9-47d4-892e-7542dfe8c889.png)

I check the LSP config and the jdk was pointing to jdk18, which I do not have installed so I thought that was the reason and I manually changed the path, however this doesn't fix the error.

**Comment by LostNeophyte** [comment]
The one with end and begin is not really a problem I sometimes get it too. Will look into the second one
You might want to switch to master btw (it's the new nightly now), rolling won't be updated anymore
How to do it:
cd ~/.local/share/lunarvim/lvim && git checkout master Then update lvim normally

**Comment by LostNeophyte** [comment]
What does the lsp log say? `<leader> L l L` copy and paste a few relevant lines here

**Comment by JonathanGDiaz** [comment]
> What does the lsp log say? `<leader> L l L` copy and paste a few relevant lines here

Here are the logs

![image](https://user-images.githubusercontent.com/94073304/198905304-9862a843-725e-46bf-9733-719813a9191c.png)

These are the relevant ones:

[ERROR][2022-10-30 16:39:02] .../vim/lsp/rpc.lua:733	"rpc"	"jdtls"	"stderr"	"WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign\n"

[ERROR][2022-10-30 16:39:06] ...lsp/handlers.lua:485	"Oct 30, 2022, 4:39:06 PM org.eclipse.lsp4j.jsonrpc.ResponseErrorException: MethodNotFound\norg.eclipse.lsp4j.jsonrpc.ResponseErrorException: MethodNotFound\njava.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: MethodNotFound\n\tat java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)\n\tat java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)\n\tat org.eclipse.jdt.ls.core.internal.JavaClientConnection.executeClientCommand(JavaClientConnection.java:101)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.synchronizeBundles(JDTLanguageServer.java:391)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$2.run(JDTLanguageServer.java:288)\n\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)\nCaused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: MethodNotFound\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)\n\tat org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:131)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)\n\tat org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\n"
 
Reading the second error I thought it was related to the program I was working on, because it is related to Threads and ExecutorService. However this same error appeared  when opening an empty java file.

Also I forgot to mention this; Thank you all for your time.

**Comment by LostNeophyte** [comment]
Does the same happen in a single file (not a project)?

**Comment by LostNeophyte** [comment]
> Also I forgot to mention this; Thank you all for your time.

No problem

**Comment by LostNeophyte** [comment]
You may need nvim 0.9, but I'm not sure. Or you can try reinstalling/updating jdtls.

**Comment by LostNeophyte** [comment]
I've just realized that I get `org.eclipse.lsp4j.jsonrpc.ResponseErrorException: MethodNotFound` too, but the lsp is working anyway

**Comment by LostNeophyte** [comment]
I don't have the vim.schedule one though, Is there anything more in `:messages` when that error happens?

**Comment by LostNeophyte** [comment]
the mention is not relevant to the issue, just a link to the rolling>master instructions

**Comment by JonathanGDiaz** [comment]
> I don't have the vim.schedule one though, Is there anything more in `:messages` when that error happens?

No, that is the only message

**Comment by LostNeophyte** [comment]
You can try the config from java-ide branch in lunarvim/starter.lvim or updating nvim to 0.9. I've got no more ideas

**Comment by JonathanGDiaz** [comment]
> 

I might try that, but LSP is working now, as long as it works it doesn't really matter.
I also need to mention that I ended up uninstalling Java17. Before removing the package I changed the default back to java19 with the archlinux-java utility. Even though I don't have Java17 now; LSP seems to keep working even after I erased the cache.

**Comment by LostNeophyte** [comment]
> I might try that, but LSP is working now, as long as it works it doesn't really matter.

If it's working then you can leave it as is, unless you want debugging then you need that java-ide config.
