### ISSUE TITLE
feat: easier override for plugins sha1

### ISSUE THREAD

**Issue by kylo252** [LunarVim/LunarVim#3246]
I tried the `packer.snapshot`, but it is not what I expected. because it is an A/B question, if I choose A(my snapshot), then I will never get B(lunarvim snapshot), that's why I prefer do "patch" via lunarvim itself.

_Originally posted by @2nthony in https://github.com/LunarVim/LunarVim/issues/3212#issuecomment-1279745591_

**Comment by kylo252** [comment]
There's actually a relatively easy way to do this by making `get_default_sha1` global, that makes it overridable

```lua
require("lvim.plugins").get_default_sha1 = function(spec)
  local short_name, _ = require("packer.util").get_plugin_short_name(spec)
  local default_sha1 = vim.fn.json_decode(content) or {}
  if short_name == "mason.nvim" then -- let mason.nvim always use HEAD
    return nil
  end
  return default_sha1[short_name] and default_sha1[short_name].commit
end.
```

cc: @2nthony, @abzcoding

**Comment by kylo252** [comment]
Another alternative, which I like less, but is probably more performant is making the `default_sha1` table global. Though, I'm worried that it will make it harder to track state (maybe it could work if we only ever set it once in the init phase)

**Comment by 2nthony** [comment]
> Though, I'm worried that it will make it harder to track state

that is correct!

**Comment by kylo252** [comment]
> > Though, I'm worried that it will make it harder to track state
> 
> that is correct!

closing this for now since the CI for plugins bump should hopefully be fixed now.

feel free to let me know if you come up with some better solution for this otherwise!
