### ISSUE TITLE
Vertical window split is killing me

### ISSUE THREAD

**Issue by eliavo** [LunarVim/LunarVim#3249]
### Problem description

installed lunar vim and neovim and the vertical split line is weirdly different. the lunar vim split line is similar to the vim split line...
a picture will do better to explain:
![Screen Shot 2022-10-15 at 22 29 51](https://user-images.githubusercontent.com/76263733/196004629-30d3f5eb-1b66-473a-b694-f7bb4f878302.png)
![Screen Shot 2022-10-15 at 22 30 09](https://user-images.githubusercontent.com/76263733/196004631-cadc4577-54dd-485a-8ee2-ea31ee10919e.png)

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

ubuntu 20.04

### Steps to reproduce

installed vim 0.8.0
installed stable lunar vim via:
`bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`

### support info

![Screen Shot 2022-10-15 at 22 34 56](https://user-images.githubusercontent.com/76263733/196004787-d2c89c02-84b9-42cf-aa89-96972d7c8031.png)
![Screen Shot 2022-10-15 at 22 35 27](https://user-images.githubusercontent.com/76263733/196004792-6e475996-ea3b-4ac8-bb03-532d9cb5030c.png)

**Comment by opalmay** [comment]
Please don't die
The `rolling` branch has it the way you want.
So either get the rolling version or wait for next release this weekend

**Comment by eliavo** [comment]
Cancelled my plans! tnx
