### ISSUE TITLE
No LSP client found that supports vscode.java.resolveMainClass

### ISSUE THREAD

**Issue by fithurriague** [LunarVim/LunarVim#3252]
### Problem description

I'm trying to set up java debugging.
So I skipped the ls  `vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "jdtls" })
` and configure it myself under `.config/lvim/lua/ftplugin/java.lua` based on the [java-ide config example](https://github.com/LunarVim/starter.lvim/tree/java-ide) and @ChristianChiarulli lvim configs.

All good so far, lsp working on java projects, code formatting, code actions, everything. But i can't get debug working.

Every time I start a debug session i get the following: No configuration found for `java`. You need to add configs to `dap.configurations.java` (See `:h dap-configuration`)

My intuition says i'm missing `vscode.java` bundles (see **support info** down below) but at the same time i don't know why i'm missing them if i have every dependency installed.

(All being tested in a minimal maven generated project)

*edit: Another things i have noticed:
1. Only JdtShowLogs and JdtWipeDataAndRestart command are available
2. No more single file lsp support, only work on projects now (but i thing that's normal)

### LunarVim version

rolling-48d1c38

### Neovim version (>= 0.8.0)

NVIM v0.8.0 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

Arch Linux x86_64 kernel 5.19.13-arch1-1

### Affected language servers

jdtls

### Actual behavior

Instead of starting the debug session it prints the following: No configuration found for `java`. You need to add configs to `dap.configurations.java` (See `:h dap-configuration`)

### support info

![2022-10-15-180758_1600x900_scrot](https://user-images.githubusercontent.com/71849483/196007635-603f4a90-5e91-4c0e-b7d1-cc44e565cfe3.png)
![2022-10-15-181000_1600x900_scrot](https://user-images.githubusercontent.com/71849483/196007685-020e2e0c-8e7b-4f1f-a06a-7f06e8d2854d.png)
![2022-10-15-184112_1600x900_scrot](https://user-images.githubusercontent.com/71849483/196008621-4f4db25d-648b-432d-ad79-68f0ed5fe50c.png)

**Command:** `require("jdtls").setup_dap({ hotcodereplace = "auto" })`
**Output:** none

**Command:** `:lua require("jdtls.dap").setup_dap_main_class_configs() `
**Output:** `No LSP client found that supports vscode.java.resolveMainClass`

**Command:** `:lua =vim.lsp.get_active_clients()[1].server_capabilities.executeCommandProvider.commands`
**Output:** `{
"java.edit.organizeImports", "java.project.refreshDiagnostics", "java.proje
ct.import", "java.navigate.openTypeHierarchy", "java.project.removeFromSource
Path", "java.project.listSourcePaths", "java.project.resolveStackTraceLocatio
n", "java.project.getAll", "java.project.isTestFile", "java.project.getClassp
aths", "java.navigate.resolveTypeHierarchy", "java.edit.stringFormatting", "j
ava.project.getSettings", "java.project.updateSourceAttachment", "java.projec
t.resolveWorkspaceSymbol", "java.project.upgradeGradle", "java.project.create
ModuleInfo", "java.protobuf.generateSources", "java.project.resolveSourceAtta
chment", "java.project.addToSourcePath"
 }`

### logs

```console
[START][2022-10-15 17:47:15] LSP logging initiated
[ERROR][2022-10-15 17:47:15] .../vim/lsp/rpc.lua:733	"rpc"	"jdtls"	"stderr"	"WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign\n"
[WARN][2022-10-15 17:47:30] ...lsp/handlers.lua:113	"The language server jdtls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2022-10-15 18:00:45] LSP logging initiated
[ERROR][2022-10-15 18:00:45] .../vim/lsp/rpc.lua:733	"rpc"	"jdtls"	"stderr"	"WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign\n"
[WARN][2022-10-15 18:00:52] ...lsp/handlers.lua:113	"The language server jdtls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2022-10-15 18:06:29] LSP logging initiated
[ERROR][2022-10-15 18:06:29] .../vim/lsp/rpc.lua:733	"rpc"	"jdtls"	"stderr"	"WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector\n"
[WARN][2022-10-15 18:06:36] ...lsp/handlers.lua:113	"The language server jdtls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

**Comment by ChristianChiarulli** [comment]
make sure you mason install the java debug and java test packages under dap

**Comment by ITHDevelopment** [comment]
> make sure you mason install the java debug and java test packages under dap

What do you mean by that? Isn't mason already configured by lunarvim? Can you elaborate?  Besides fixing the bug I would love to understand :)

**Comment by LostNeophyte** [comment]
Did you run `:LvimCacheReset` after adding ldtls to skipped list?

**Comment by LostNeophyte** [comment]
From your support info it looks like cmd is the default one and not from ftplugin/java.lua

**Comment by fithurriague** [comment]
Yes I did run `:LvimCacheReset`
If you wanna check the config for yourself I have just uploaded it [here](https://github.com/fithurriague/dotfiles.lvim). Hope it's useful :smile:

**Comment by LostNeophyte** [comment]
Will check the config
You might want to switch to master btw, rolling won't be updated anymore
How to do it:
`cd ~/.local/share/lunarvim/lvim && git checkout master` Then update lvim normally

**Comment by LostNeophyte** [comment]
We don't use lv-settings since quite some time. Now there's a config.lua as you can see [here](https://github.com/LunarVim/starter.lvim/tree/java-ide)

**Comment by LostNeophyte** [comment]
The problem is that you have the ftplugin folder in a wrong place, move it from lua to lvim(parent directory)

**Comment by fithurriague** [comment]
Okey I have moved to master, deleted lv-settings, and changed the location of ftplugin dir. Everything works, even debugging in other languages, jdtls works but I still got errors when trying to debug. I don't have time now to provide more information but I will update this comment later today.
(as mentioned before you can follow everything I do due to the fact that I push the changes to the repo)

**Comment by fithurriague** [comment]
It works now, don't ask me why. I just turned on the pc, **maybe** after changing the config lunarvim needed a cache reset which i didn't try. The **right placing of the ftplugin dir** seems to have fixed the problem so I'm closing the issue. I hope for a consistent behaviour.
Thank you @LostNeophyte for taking the time to help me with this :smile: :+1:
