### ISSUE TITLE
Change Git Workflow

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#3253]
We should adopt a more standard way of managing branches and releases, as well as nightly builds

AC:
- rolling is merged into master
- all new PRs will be merged to master
- master is the "nightly" build
- releases will be frozen to their own branches titled release-vX-neovim-0.Y (where X is the current LunarVim version and Y is the compatible neovim version)

**Comment by Aniketmishra0** [comment]
Hello please
Assign me to work on this
