### ISSUE TITLE
Docs: simplify readme

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#3256]
AC:

- no duplication of docs
- readme should link to website
- similar to how https://github.com/hyprwm/Hyprland does it

**Comment by OkelleyDevelopment** [comment]
I'll get a start on this issue :raised_hands:  @ChristianChiarulli

**Comment by umop3plsdn** [comment]
crap i already made one i didnt see it was assigned

**Comment by umop3plsdn** [comment]
#3282

**Comment by OkelleyDevelopment** [comment]
It's all good, left a review on your PR 😎

**Comment by umop3plsdn** [comment]
merged. Sorry again =(
