### ISSUE TITLE
not able to access yanked content outside the file

### ISSUE THREAD

**Issue by nairobi02** [LunarVim/LunarVim#3263]
### Problem description

Steps to reproduce this behavior 
1. open file in lvim
2. enter visual block mode (ctrl+v)
3. select text 
4. yank(y)
5. try to paste in another application 

I have set vim.opt.clipboard = "unnamedplus" in /home/demo/.config/lvim/config.lua
This behavior occurs whether I set unnamedplus or not. 

for example, if the last thing i yanked was "public class"
![checking registers](https://user-images.githubusercontent.com/109964994/196025801-90674aa0-ad41-4b73-8430-eb048cc00571.png)

when i go to another application and try to paste, 
it doesn't show up in my clipboard 

my system info:
Windows 10 WSL ubuntu 22.04
NVIM v0.8.0-v0.8.0

the clipboard otherwise works well across windows and ubuntu, havent faced issues, 
everything was fine on nvim too(before i installed lvim)

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0-v0.8.0

### Operating system/version

Windows 10 WSL ubuntu 22.004

### Steps to reproduce

1. open file in lvim
2. enter visual block mode (ctrl+v)
3. select text 
4. yank(y)
5. try to paste in another application 

### Screenshots

![image](https://user-images.githubusercontent.com/109964994/196026116-cf6181cc-e198-4f28-9052-944e07f69eb1.png)

**Comment by abzcoding** [comment]
check this for more info -> https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl

**Comment by nairobi02** [comment]
> check this for more info -> https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl

I do not think its an issue between wsl and windows, because it worked fine on nvim before i installed lvim

**Comment by abzcoding** [comment]
cc: @kylo252

**Comment by nairobi02** [comment]
Use 

> > check this for more info -> https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl
> 
> I do not think its an issue between wsl and windows, because it worked fine on nvim before i installed lvim

this was in fact the issue, my bad. it works now, all i had to do was use win32yank instead of xclip
