### ISSUE TITLE
LSP progression of DB load

### ISSUE THREAD

**Issue by lauccode** [LunarVim/LunarVim#3269]
### Feature Description

Maybe it already exist. Or there is a good way to be aware of that. I didn't find.
It is above all for big project.
With LSP for cpp using clangd, when the DB(compile_commands.json) is loaded we don't see the progression and if it is well done.
It is available on vscode and Doom Emacs.

### Describe the alternatives you have considered

I look at vscode first. I can see the clangd progression.
Generally I just see the errors, so I know the DB is not loaded. Sometimes, I restart LSP server and it works.
Also erase the .cache at root. And restart server to be sure the DB is well loaded.

**Comment by ChristianChiarulli** [comment]
I wonder if fidget.nvim would work here @kylo252
