### ISSUE TITLE
how to config auto trigger suggestion?

### ISSUE THREAD

**Issue by kaneruan** [LunarVim/LunarVim#3271]
### Problem description

noop

### LunarVim version

3abb0a7

### Neovim version (>= 0.8.0)

NVIM v0.7.0

### Operating system/version

macos 11.6.7

### Steps to reproduce

no

### support info

noop

### Screenshots

<img width="802" alt="image" src="https://user-images.githubusercontent.com/13065289/196324541-62a896c6-42bf-4180-827e-560cce74b45e.png">

**Comment by abzcoding** [comment]
note: i really don't recomment it but 

add this to your `~/.config/lvim/config.lua`
```lua
lvim.builtin.cmp.completion.completeopt = "menu,menuone"
lvim.builtin.cmp.completion.keyword_length = 0
```
