### ISSUE TITLE
Tabs are looking weird

### ISSUE THREAD

**Issue by AlonHor** [LunarVim/LunarVim#3275]
### Problem description

My tabs are looking very weird.

Expected: 
Something like
![image](https://user-images.githubusercontent.com/57628667/196415656-91331297-86f8-41e1-9967-878d3886a876.png)

Recieved:
![image](https://user-images.githubusercontent.com/57628667/196415756-4a426de8-664b-4b4b-8eb1-5a3a7b76e3a7.png)

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.8.0)

NVIM v0.7.2

### Operating system/version

PopOS 22.04 LTS

### Steps to reproduce

Install LunarVim
Open a new tab

### support info

```console
:LspInfo
Configured servers list: tailwindcss, cssls, sumneko_lua, tsserver
```
```console
:LvimInfo
No important information
```

### Screenshots

![image](https://user-images.githubusercontent.com/57628667/196416723-e0830148-bfca-4d85-92bd-08cae66e3133.png)

**Comment by AlonHor** [comment]
Just realized I'm using NVIM v0.7.2...
Is it because of that?

**Comment by AlonHor** [comment]
Just updated Neovim to v0.8.0, and reinstalled LunarVim, didn't fix the issue.

**Comment by kobzar** [comment]
Try different terminal app like alacritty, kitty....

**Comment by AlonHor** [comment]
Just found out that tmux is causing the issue.
Alacritty without tmux:
![image](https://user-images.githubusercontent.com/57628667/196681855-15089df4-5638-48ca-a6a4-80091e710196.png)

Alacritty with tmux:
![image](https://user-images.githubusercontent.com/57628667/196682004-9188adc9-2f93-4f80-97ea-a72ce52bd69e.png)

This probably needs to be fixed right?

**Comment by AlonHor** [comment]
Thanks so much I'll try that right now.

**Comment by AlonHor** [comment]
I did all of that and it didn't work for some reason.
tmux.conf:
![image](https://user-images.githubusercontent.com/57628667/196686388-84eadce3-821f-4132-8e69-b772470b72df.png)

alacritty.yml:
![image](https://user-images.githubusercontent.com/57628667/196686450-c25d3ced-ab84-4602-aa5a-3196e8ff3235.png)

Did I do something wrong? (*I also started tmux with -2*)
Thanks for the patience.

**Comment by kobzar** [comment]
I try it just now on my system
```
╰─  uname -a                                                                                                                            0 (2.883s)
Linux dLin 5.15.74-1-lts #1 SMP Sat, 15 Oct 2022 06:43:47 +0000 x86_64 GNU/Linux
╭─kobzar[dLin] /home/kobzar/Develop/Python/z (master ●1✚1…1)
╰─  alacritty --version                                                                                                                 0 (0.015s)
alacritty 0.11.0 (8dbaa0bb)
╭─kobzar[dLin] /home/kobzar/Develop/Python/z (master ●1✚1…1)
╰─  nvim --version                                                                                                                      0 (0.013s)
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
╭─kobzar[dLin] /home/kobzar/Develop/Python/z (master ●1✚1…1)
╰─  pacman -Q tmux                                                                                                                      0 (0.024s)
tmux 3.3_a-2
╭─kobzar[dLin] /home/kobzar/Develop/Python/z (master ●1✚1…1)
```
And all looking fine. 
Try to use tmux without your (use clear) configuration

**Comment by AlonHor** [comment]
Alright I'll try that right now thanks so much for helping.

**Comment by AlonHor** [comment]
That works! Thanks, it was probably something in my huge config. I'll try to slowly un-comment stuff and see what's causing the issue.

**Comment by AlonHor** [comment]
For people who might have this problem, turns out I restarted tmux without closing ALL my sessions, so my config didn't reload, so @kobzar's solution fixed it.
