### ISSUE TITLE
LunarVim dashboard start screen glitch

### ISSUE THREAD

**Issue by denesbeck** [LunarVim/LunarVim#3279]
### Problem description

LunarVim start screen (dashboard) looks like as it is positioned too much to the top (the full logo is not visible).

### LunarVim version

master-c015d0f

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Ubuntu 22.04.1 LTS

### Steps to reproduce

1. Install NeoVim.
1. Install LunarVim.
2. Start LunarVim.

### support info

```
    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                alpha
* bufnr:                   1
* treesitter status:       inactive

Active client(s)
* name:                      copilot
* id:                        1
* supported filetype(s):     []
* attached buffers:          []
* root_dir pattern:          []

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

### Screenshots

![lvim](https://user-images.githubusercontent.com/85183401/196500169-f77cd3d0-0692-44d1-a6be-23a58663e28f.png)

**Comment by Joachim-42he** [comment]
Same problem here with Lunavim  rolling-7715900 and neovim 0.803 on Arch (EndeavourOS) under I3. It happens with a fullscreen window (3840x1600) and in smaller windows.

**Comment by LostNeophyte** [comment]
What else should it do? On the screenshots the font is too big for everything to fit, something has to be off screen

**Comment by LostNeophyte** [comment]
Alright so I know now that it happens even when there's lots of space

**Comment by LostNeophyte** [comment]
Will try to reproduce, what's your terminal?

**Comment by kobzar** [comment]
My term is alacritty
Hack Nerd Font Mono size 9

**Comment by jakkan** [comment]
I also have this problem, with a same terminal but different font.

**Comment by denesbeck** [comment]
I use the gnome terminal in Ubuntu, however, I also experienced this issue on Mac using iTerm2. In both cases I use MesloLGM Nerd Font Mono 12. I also tried to reduce the font size or to change the font type without any luck.

**Comment by LostNeophyte** [comment]
looks normal for me on kitty, will try alacritty, don't know what to do to reproduce it
![image](https://user-images.githubusercontent.com/110467150/199431691-2b659161-1f16-42f6-b17d-58a2d4089e08.png)

**Comment by hdecoudr** [comment]
Same problem as @denesbeck here with latest stable release only when the terminal is reduced.
I am using gnome terminal JetBrains Nerd Font Mono 12.

**Comment by LostNeophyte** [comment]
> Same problem as @denesbeck here with the latest stable release only when the terminal is reduced. I am using gnome terminal JetBrainsMono Nerd Font Mono 12.

Can you send a screenshot of the full window wjen that happens?

**Comment by hdecoudr** [comment]
Here it is. 

- Reduced terminal size (80 columns by 24 rows):

![lvim-bug-1](https://user-images.githubusercontent.com/89706873/200110455-dd8eca83-4a32-45a4-8de6-d3614a0b5e73.png)

- Full screen mode (it is ok):

![lvim-bug-2](https://user-images.githubusercontent.com/89706873/200110502-b773b9a6-08ae-4123-97ac-7ed6bfa9597a.png)

**Comment by LostNeophyte** [comment]
> Here it is.
In the top picture it can't fit so I don't know what else it's supposed to do, that doesn't look like a bug to me

**Comment by hdecoudr** [comment]
> > Here it is.
> 
> In the top picture it can't fit so I don't know what else it's supposed to do, that doesn't look like a bug to me

Okay, forgive me, I was a little bit confused. I have not experienced the same behaviour with previous versions.

**Comment by LostNeophyte** [comment]
What did it do back then?

**Comment by hdecoudr** [comment]
> What did it do back then?

The whole logo was correctly displayed even with a smaller terminal size (80 columns x 24 rows).

**Comment by LostNeophyte** [comment]
> > What did it do back then?
> 
> The whole logo was correctly displayed even with a smaller terminal size (80 columns x 24 rows).

and the bottom was cut off then?

**Comment by hdecoudr** [comment]
> > > What did it do back then?
> > 
> > 
> > The whole logo was correctly displayed even with a smaller terminal size (80 columns x 24 rows).
> 
> and the bottom was cut off then?

No, everything was shown (same as full screen).

**Comment by LostNeophyte** [comment]
> No, everything was shown (same as full screen).

How? It looks like it wouldn't physically fit there

**Comment by LostNeophyte** [comment]
this is how it looks for me when it barely fits ![image](https://user-images.githubusercontent.com/110467150/200121887-c5ed8280-78e6-4be4-ac0f-b0d33cc0f1e8.png)

**Comment by MonoPelirrojo** [comment]
> > No, everything was shown (same as full screen).
> 
> How? It looks like it wouldn't physically fit there. The logo takes up 22 lines, the buttons 8 and then 3 for the footer, so at least 33 rows are needed for it to fit

Same problem.
Solution minimum: +36 rows.

-35 Rows is problem, no font size can fix it.

Decent configuration: 41 rows and font size 10. Less rows and the logo doesn't fit.

**Comment by LostNeophyte** [comment]
> -35 Rows is problem, no font size can fix it.

Yes, font size makes no difference, the dashboard takes up 33 rows + padding, so it can't physically fit in a smaller terminal window

Does it happen to someone with a window higher than 35 rows? If so please send a screenshot.

I'll add a more compact version of the logo that will be displayed if the height is less than 35, are you all ok with that solution?
demo:

https://user-images.githubusercontent.com/110467150/202906363-98627f53-7fe2-4d23-bb11-f8e40d6c6c97.mp4

**Comment by rasivasu** [comment]
> Here it is.
> 
> * Reduced terminal size (80 columns by 24 rows):
> 
> ![lvim-bug-1](https://user-images.githubusercontent.com/89706873/200110455-dd8eca83-4a32-45a4-8de6-d3614a0b5e73.png)
> 
> * Full screen mode (it is ok):
> 
> ![lvim-bug-2](https://user-images.githubusercontent.com/89706873/200110502-b773b9a6-08ae-4123-97ac-7ed6bfa9597a.png)

The rendering is not okay for Reduced terminal size as well as for the Full Screen mode.  There is one pixel size gap after every 4 rows of displayed pixels.  This happens only in Alacritty and not in Kitty.  

I came here to report this exact issue.  

![image](https://user-images.githubusercontent.com/1153582/210608356-765570e0-b8e3-48ea-b5ff-2755f09170f0.png)

Thanks

**Comment by rasivasu** [comment]
This is what I get when I reduce the application size.  Not sure if this is an Alacritty issue or if Lunarvim is not working well with Alacritty.

![image](https://user-images.githubusercontent.com/1153582/210608682-7fe4b5dd-051c-433f-a92c-6122b5f5edc1.png)

**Comment by LostNeophyte** [comment]
> The rendering is not okay for Reduced terminal size as well as for the Full Screen mode. There is one pixel size gap after every 4 rows of displayed pixels. This happens only in Alacritty and not in Kitty.

That's noting wrong with lunarvim, there's is no empty line in between - it's your terminal/font

**Comment by rasivasu** [comment]
> > The rendering is not okay for Reduced terminal size as well as for the Full Screen mode. There is one pixel size gap after every 4 rows of displayed pixels. This happens only in Alacritty and not in Kitty.
> 
> That's noting wrong with lunarvim, there's is no empty line in between - it's your terminal/font

Just to be sure, I uninstalled Alacritty and reinstalled it.  I downloaded https://github.com/alacritty/alacritty/blob/master/alacritty.yml to `~/.config/alacritty/alacritty.yml` and configured only the following lines.  I have also installed DroidSansMono Nerd Font.  Is there anything else I need to do to make Lunar Vim work well with Alacritty? ( As I said, LunarVim is working well with Kitty.app )

`
font:
  normal:
    family: DroidSansMono Nerd Font
    style: Book
`

**Comment by LostNeophyte** [comment]
> > > The rendering is not okay for Reduced terminal size as well as for the Full Screen mode. There is one pixel size gap after every 4 rows of displayed pixels. This happens only in Alacritty and not in Kitty.
> > 
> > 
> > That's noting wrong with lunarvim, there's is no empty line in between - it's your terminal/font
> 
> Just to be sure, I uninstalled Alacritty and reinstalled it. I downloaded https://github.com/alacritty/alacritty/blob/master/alacritty.yml to `~/.config/alacritty/alacritty.yml` and configured only the following lines. I have also installed DroidSansMono Nerd Font. Is there anything else I need to do to make Lunar Vim work well with Alacritty? ( As I said, LunarVim is working well with Kitty.app )
> 
> `font: normal: family: DroidSansMono Nerd Font style: Book`

looks like kitty is using a different font to render the braille characters than alacritty
