### ISSUE TITLE
Unable to use the find word feature on dashboard (default leader+s+t)

### ISSUE THREAD

**Issue by nairobi02** [LunarVim/LunarVim#3287]
### Problem description

Every time i use try to use this feature i get with this error 
![image](https://user-images.githubusercontent.com/109964994/196655670-9ea9f102-0686-4b20-910c-5a2ee2af3338.png)

i haven't changed any configs for telescope or any other related plugin
i have been getting this error from the time i cloned this repo.

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0-v0.8.0

### Operating system/version

ubuntu 22.04 on WSL2 windows 10

### Steps to reproduce

1. type lvim to open dashboard
2. go to find word option (spc s t)
3. type a word to find

### support info

![LspInfo](https://user-images.githubusercontent.com/109964994/196656629-d0d6c451-7446-4be2-8651-ace6ed09bfb9.png)
![LvimInfo](https://user-images.githubusercontent.com/109964994/196656819-efff7784-21bd-4181-952d-209fb67357d1.png)

### Screenshots

![LspInfo](https://user-images.githubusercontent.com/109964994/196656629-d0d6c451-7446-4be2-8651-ace6ed09bfb9.png)
![LspInfo](https://user-images.githubusercontent.com/109964994/196657849-3be27be4-eda0-4f8b-a743-de4d4c23b8f7.png)

**Comment by kobzar** [comment]
Try to run
```
:PackerClean
:PackerSync
:PackerCompile
```
And ReRun lvim
fzf is installed?

**Comment by nairobi02** [comment]
> Try to run
> 
> ```
> :PackerClean
> :PackerSync
> :PackerCompile
> ```
> 
> And ReRun lvim fzf is installed?

I ran those three commands, still facing the same error.
Also, yes, like you mentioned in another post, I have 
lvim.plugins = {
  { "ibhagwan/fzf-lua" },
} in my config.lua

**Comment by kobzar** [comment]
Try to disable it just for the test. Some time external plugins got the problems

**Comment by nairobi02** [comment]
> Try to disable it just for the test. Some time external plugins got the problems
Tried with the fzf plugin commented out as well as not. No difference, same error.

Is this a error because of ripgrep or fd? because i just checked and i dont have anything related to either of those in config.lua 
also, :checkhealth says no-info under fzf 
![checkhealth](https://user-images.githubusercontent.com/109964994/196679023-e5634eae-228f-4532-95b9-653816a8c8b1.png)

**Comment by kobzar** [comment]
This was my first things. Install both of them, and inform about results please.

**Comment by nairobi02** [comment]
> This was my first things. Install both of them, and inform about results please.

Thank you so much for following up on this and providing support, 
I followed chris's video and did sudo install ripgrep, 
this is currently what i've appended to my config.lua
lvim.plugins = {
  {
    "ibhagwan/fzf-lua",
    "airblade/vim-rooter"
  },
}
even though i did sudo install ripgrep I can not do :Rg, it says, "not an editor command"
the video didn't say anything about adding config for Ripgrep or fd in config.lua, 
is there anything i need to add in config.lua with respect to Ripgrep or fd?

**Comment by kobzar** [comment]
```sudo apt install fzf fd ripgrep```
not 
```sudo install```
Don`t forget to update you user profile by
source ~/.profile (from bash ) or just relogin
```
╭─kobzar[dLin] /home/kobzar
╰─  rg --version                                                                                                                     130 (44.914s)
ripgrep 13.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
╭─kobzar[dLin] /home/kobzar
╰─  fd --version                                                                                                                        0 (0.007s)
fd 8.4.0
╭─kobzar[dLin] /home/kobzar
╰─  fzf --version                                                                                                                       0 (0.040s)
0.34.0 (04d0b02)
```

**Comment by nairobi02** [comment]
> `sudo apt install fzf fd ripgrep` not `sudo install` Don`t forget to update you user profile by source ~/.profile (from bash ) or just relogin
> 
> ```
> ╭─kobzar[dLin] /home/kobzar
> ╰─  rg --version                                                                                                                     130 (44.914s)
> ripgrep 13.0.0
> -SIMD -AVX (compiled)
> +SIMD +AVX (runtime)
> ╭─kobzar[dLin] /home/kobzar
> ╰─  fd --version                                                                                                                        0 (0.007s)
> fd 8.4.0
> ╭─kobzar[dLin] /home/kobzar
> ╰─  fzf --version                                                                                                                       0 (0.040s)
> 0.34.0 (04d0b02)
> ```

I did exactly as you mentioned and it seems the plugins are installed on my system, but Rg is still not a recognized command in lvim, is there something i need to add to my config.lua file with respect to ripgrep?

![Rg](https://user-images.githubusercontent.com/109964994/196695410-3e90442f-d4d4-401d-ab50-49f78cb9c885.png)
![versions](https://user-images.githubusercontent.com/109964994/196695459-61424e82-d6ec-4960-9373-342e41246055.png)

**Comment by nairobi02** [comment]
> This was my first things. Install both of them, and inform about results please.

In [chris's aritcle](https://www.chrisatmachine.com/blog/category/neovim/08-fzf) he has a section called configuration, this section is in VimL, so obviously i cant paste this into my config.lua, is there a lua alternative that i can use?

**Comment by LostNeophyte** [comment]
@nairobi02 please run `:messages` after you get the error and copy it in full here
