### ISSUE TITLE
Remove " -->" from navic location, there is already a chevron

### ISSUE THREAD

**Issue by gj86** [LunarVim/LunarVim#3289]
This is just for the sake of aesthetic.

https://github.com/LunarVim/LunarVim/blob/c015d0feeed35b34d84558a8e4a49549b3b67781/lua/lvim/core/breadcrumbs.lua#L158

```lua
return ">" .. " " .. gps_location:gsub("% -->", "")
```

**Comment by LostNeophyte** [comment]
Do you have two arrows in breadcrumbs? mine look like this: `  config.lua >    >  entry_filter >  if `

**Comment by gj86** [comment]
> Do you have two arrows in breadcrumbs? mine look like this: ` config.lua >  >  entry_filter >  if`

No, I don't have arrows like that in navic location data. Mine appears like below,
![image](https://user-images.githubusercontent.com/29265467/198927772-b85ab100-d1c9-405c-8d62-082bf3737bfd.png)

**Comment by LostNeophyte** [comment]
> > Do you have two arrows in breadcrumbs? mine look like this: ` config.lua >  >  entry_filter >  if`
> 
> No, I don't have arrows like that in navic location data. Mine appears like below, ![image](https://user-images.githubusercontent.com/29265467/198927772-b85ab100-d1c9-405c-8d62-082bf3737bfd.png)

Then why would we need to gsub --> if it's not there?

**Comment by gj86** [comment]
> > > Do you have two arrows in breadcrumbs? mine look like this: ` config.lua >  >  entry_filter >  if`
> > 
> > 
> > No, I don't have arrows like that in navic location data. Mine appears like below, ![image](https://user-images.githubusercontent.com/29265467/198927772-b85ab100-d1c9-405c-8d62-082bf3737bfd.png)
> 
> Then why would we need to gsub --> if it's not there?

It's not there because I'm `gsub` ing it ;). See the below snapshot for without `gsub`
![image](https://user-images.githubusercontent.com/29265467/198941657-aafacdd4-75a9-4194-9dda-627cb5030c00.png)

**Comment by LostNeophyte** [comment]
It's only the last arrow?

**Comment by LostNeophyte** [comment]
Mine doesn't have --> I think, maybe it's only sometimes visible and I didn't notice jt

**Comment by LostNeophyte** [comment]
Relevant pr: #3380

**Comment by wren** [comment]
The arrow mentioned in this PR comes up when a cursor is in one of the args for a function call. It's part of what navic returns though, so to me it seems like a bug that should be filed with navic, so it can be fixed for everyone.

**Comment by LostNeophyte** [comment]
> The arrow mentioned in this PR comes up when a cursor is in one of the args for a function call. It's part of what navic returns though, so to me it seems like a bug that should be filed with navic, so it can be fixed for everyone.

Please do open an issue in navic then, I don't known much about it
