### ISSUE TITLE
Cant install lunarvim "attempt to index field 'window' (a nil value) "

### ISSUE THREAD

**Issue by indieman** [LunarVim/LunarVim#3290]
### Problem description

Install it:
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh) -y

the error:
Cloning LunarVim configuration
Cloning into '/Users/indie/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 15044, done.
remote: Counting objects: 100% (100/100), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 15044 (delta 37), reused 72 (delta 20), pack-reused 14944
Receiving objects: 100% (15044/15044), 13.40 MiB | 611.00 KiB/s, done.
Resolving deltas: 100% (9389/9389), done.
--------------------------------------------------------------------------------
Installing LunarVim shim
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: /Users/indie/.local/bin/lvim
Preparing Packer setup
Error detected while processing /Users/indie/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: ...s/indie/.local/share/lunarvim/lvim/lua/lvim/core/cmp.lua:217: attempt to index field 'window' (a nil value)
stack traceback:
	...s/indie/.local/share/lunarvim/lvim/lua/lvim/core/cmp.lua:217: in function 'config'
	...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:31: in function 'config'
	...ndie/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:21: in function 'init'
	.../indie/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:105: in function 'init'
	/Users/indie/.local/share/lunarvim/lvim/init.lua:11: in main chunkError detected while processing command line:
E492: Not an editor command: PackerSync

I tried uninstall and install again. But it didn't help.

nvim -v
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info

### LunarVim version

could not get that far

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

macOS 12.3.1

### support info

could not get that far

**Comment by kobzar** [comment]
Do you run install from bash or another shell like fish?
Try to run install from bash
(bash + Enter and next insert installation line)

**Comment by indieman** [comment]
Thank you. I run install from zsh.

I tried to install from bash, but i got the same result

Installing LunarVim shim
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: /Users/indie/.local/bin/lvim
Preparing Packer setup
Error detected while processing /Users/indie/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: ...s/indie/.local/share/lunarvim/lvim/lua/lvim/core/cmp.lua:217: attempt to index field 'window' (a nil value)
stack traceback:
	...s/indie/.local/share/lunarvim/lvim/lua/lvim/core/cmp.lua:217: in function 'config'
	...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:31: in function 'config'
	...ndie/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:21: in function 'init'
	.../indie/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:105: in function 'init'
	/Users/indie/.local/share/lunarvim/lvim/init.lua:11: in main chunkError detected while processing command line:
E492: Not an editor command: PackerSync^C
bash-3.2$

**Comment by s094392** [comment]
Same issue here.

**Comment by umop3plsdn** [comment]
just want to make sure you are entering bash shell first and it changed from zsh. So "bash" enter.. *new shell* then try running this command  without the -y:
       bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
did it ask all 3 questions? it will hang on "Unable to set logger's level to warn" DO NOT ctrl+c out of that stage just wait for it to compile and you should get "Thank you for installing Lunarvim!!"

**Comment by kylo252** [comment]
isn't this a duplicate of these?
- https://github.com/LunarVim/LunarVim/issues/2479
- https://github.com/LunarVim/LunarVim/issues/2498

**Comment by indieman** [comment]
Hello.
Did i it right?
https://pastebin.com/qvGHQRBc

1. change to bash
2. run curl command
3. type three y
But i got the same result.
Thank you.

**Comment by kobzarchekg** [comment]
Run it before
bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh
# or
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/uninstall.sh)

**Comment by kylo252** [comment]
please try this installer from #3338 instead 

https://github.com/LunarVim/LunarVim/blob/810b7d478ba383ad480c38d0dfcf1820a4dc615e/utils/installer/install.sh

**Comment by everte** [comment]
I was facing the same issue and the new installer did work flawless for me.

One small change, you need to use the raw link:
[](https://raw.githubusercontent.com/LunarVim/LunarVim/810b7d478ba383ad480c38d0dfcf1820a4dc615e/utils/installer/install.sh)

**Comment by LostNeophyte** [comment]
@indieman Is the issue fixed in the newest master now?
