### ISSUE TITLE
Lunarvim not loading config on startup

### ISSUE THREAD

**Issue by alexcg1** [LunarVim/LunarVim#3291]
## Beforehand

1. Open Lunarvim
2. Add this line to `/.config/lvim/config.lua`:

```lua
lvim.keys.normal_mode["<leader>c"] = false  -- mapped to "close buffer"
```

3: Save
4. Quit

## Then

1. Open Lunarvim
2. Create a new file
3. Input text
4. Input key combination `\c` (`\` is my leader)
5. Lunarvim asks me if I want to save before closing buffer

It seems `config.lua` isn't being loaded on startup

## Expected behavior

1. Config gets loaded on startup
2. Nothing, or load up whichkey to show subsequent keys in combination when I use `\c`

### LunarVim version

master-c015d0f

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

Manjaro Linux

### Steps to reproduce

See above

### support info

Oddly, *some* of config.lua gets noticed, since it recognizes my custom leader key.

When editing config.lua and saving with `:w`, the config loads properly, and keys work as expected from then on.

## Relevant `config.lua` snippet

```lua
-- keymappings [view all the defaults by pressing <leader>Lk]
lvim.leader = "\\"
-- add your own keymapping
lvim.keys.normal_mode["<leader>f"] = false
lvim.keys.normal_mode["<leader>c"] = false
lvim.keys.normal_mode["<leader>ff"] = ":Telescope oldfiles<CR>"
lvim.keys.normal_mode["<leader>fg"] = ":Telescope live_grep<CR>"
lvim.keys.normal_mode["<S-l>"] = ":BufferLineCycleNext<CR>"
lvim.keys.normal_mode["]b"] = ":BufferLineCycleNext<CR>"
lvim.keys.normal_mode["<S-h>"] = ":BufferLineCyclePrev<CR>"
lvim.keys.normal_mode["[b"] = ":BufferLineCyclePrev<CR>"
-- unmap a default keymapping
-- vim.keymap.del("n", "<C-Up>")
-- override a default keymapping
-- lvim.keys.normal_mode["<C-q>"] = ":q<cr>" -- or vim.keymap.set("n", "<C-q>", ":q<cr>" )
```

**Comment by kobzar** [comment]
try to run :PackerCompile
If not help try to change code like from examples
vim.keymap.del("n", "<leader>f")

**Comment by alexcg1** [comment]
@kobzar I tried both of those and no luck :(

Looking at the problem, I don't think it's a bug with my config file per se. But rather that Lunarvim doesn't load the config file on startup

**Comment by kobzar** [comment]
try this
```
lvim.builtin.which_key.mappings["f"] = { }
```
Its working but i think its wrong method

**Comment by Uzaaft** [comment]
I see that you wrote `/.config/lvim/config.lua`.
Just to be sure, you're editing the  file found at  `~/.config/lvim/config.lua `, right?

**Comment by alexcg1** [comment]
@Uzaaft yup, I made a typo before :sweat_smile:

**Comment by kobzar** [comment]
> @Uzaaft yup, I made a typo before sweat_smile

So, issue is resolved?
