### ISSUE TITLE
Is there still use tag in LunarVim or neovim? 

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3293]
Recently I learn vim from scratch, and I find a very useful concept named 'tag', which can save the position of function name or file name. 
But I check the LunarVim manual and youtube video of neovim tutorial https://www.youtube.com/watch?v=ctH-a-1eUME&list=PLhoH5vyxr6Qq41NFL4GvhFp-WLd5xzIzZ, seem not found related topic. Is the `tag` still use or not? If not how to locate a function name quickly in Lvim?

**Comment by kobzar** [comment]
Try this one 
https://github.com/simrat39/symbols-outline.nvim
```
{
  "simrat39/symbols-outline.nvim",
  config = function()
    require('symbols-outline').setup()
  end
},
```

**Comment by kobzar** [comment]
Is there taht you find?

**Comment by chase** [comment]
@woshichuanqilz Tags can still be used, but using [language server-based](https://www.lunarvim.org/docs/quick-start#language-server) stuff is probably more useful for finding functions.

By default the bindings to access the symbols (function names, variables, etc.) are `<leader>ls` for Document Symbols and `<leader>lS` for Workspace Symbols. A workspace is whatever the server decides the project is, so for Javascript it's something like whatever contains a `package.json`, for C++ it whatever contains a Makefile, etc.

**Comment by kobzarchekg** [comment]
I see full answer for this issue. So TMP closed. 
Please @woshichuanqilz reopen it if something wrong.
