### ISSUE TITLE
[c015d0f] Rebinding Flating Terminal <M-3> to <C-t> does not work

### ISSUE THREAD

**Issue by websorz** [LunarVim/LunarVim#3295]
### Problem description

Using the rebind ```lvim.keys.normal_mode["<C-t>"] = "<M-3>"``` does not work to remap the terminal from ALT+3 on my keyboard to CTRL + t.  (I really miss the old default keybinding for the terminal..)

Update:
i found where the exec command is being run in the lvim terminal config file and that did the trick.. 

### LunarVim version

master-c015d0f

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-123-gbe43cf16c

### Operating system/version

Ubuntu 21.04

### Steps to reproduce

enter lvim.keys.normal_mode["<C-t>"] = "<M-3>" in config and try ALT + t

### support info

none really

**Comment by kobzar** [comment]
```
lvim.keys.normal_mode["<KEY_BIND>"] = "ACTION"
lvim.keys.normal_mode["<C-t>"] = "<cmd>ToggleTerminal<cr>"
```

**Comment by websorz** [comment]
Thank you for the help! :D 

I tried out your keybind, but I'm getting the error "Not and editor command: ToggleTerminal

**Comment by dastein1** [comment]
Isn't it a simple `lvim.keys.normal_mode["<C-t>"] = ":ToggleTerm<cr>"`?

**Comment by DanInSpace104** [comment]
> Isn't it a simple `lvim.keys.normal_mode["<C-t>"] = ":ToggleTerm<cr>"`?

it can only open floating terminal, but then cannot close it while you in insert mode. is it possible to set insert_mode keymap only inside floating term ?

**Comment by kobzar** [comment]
lvim.keys.normal_mode["<C-t>"] = "<cmd>ToggleTerm<cr>"

**Comment by DanInSpace104** [comment]
> ```
> vim.keymap.set("n", "<C-t>", "<cmd>ToggleTerm<cr>")
> vim.keymap.set("t", "<C-t>", "<cmd>ToggleTerm<cr>")
> ```
Thanks! With your help i wrote it like that (more "lunar" i guess :smile_cat:)
```
lvim.keys.term_mode["<C-t"] = "<cmd>ToggleTerm<cr>"
lvim.keys.normal_mode["<C-t"] = "<cmd>ToggleTerm<cr>"
```
