### ISSUE TITLE
[spike] determine if fidget.nvim is a good addition to lunarvim core plugins

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#3297]

**Comment by izzy-el** [comment]
Hey! This seems like an interesting plugin. I would like to do some research on this plugin and test it. What should be taken in consideration for this to be (or not) added to lunarvim core plugins?

**Comment by kobzar** [comment]
I was use it at last week and remove it now. 
Look this one 
https://github.com/arkav/lualine-lsp-progress
![image](https://user-images.githubusercontent.com/1912842/196771622-b759597c-9bed-4885-a1fb-648ad300cf5f.png)

**Comment by cpea2506** [comment]
Notifier could be consider too: <https://github.com/vigoux/notifier.nvim>

**Comment by mhuggins7278** [comment]
[noice.nvim](https://github.com/folke/noice.nvim) seems to have the best of both fidgit and nvim-notify it might be a good fit

**Comment by kobzarchekg** [comment]
> [noice.nvim](https://github.com/folke/noice.nvim) seems to have the best of both fidgit and nvim-notify it might be a good fit

This is awesome plugin. But we are try to going up from notifier 
But i think we can configure it to write message to standard vim/nvim area
But a long time i am look on it...

**Comment by mhuggins7278** [comment]
> > [noice.nvim](https://github.com/folke/noice.nvim) seems to have the best of both fidgit and nvim-notify it might be a good fit
> 
> This is awesome plugin. But we are try to going up from notifier But i think we can configure it to write message to standard vim/nvim area But a long time i am look on it...

I totally missed this was using nvm-notify under the hood :(

**Comment by folke** [comment]
nvim-notify is optional in Noice. There's a bunch of internal views you can use. The mini view is like notifier/fidget.
