### ISSUE TITLE
docs: make badges look like catpuccin (use tokyonight colors), and link socials like them as well

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#3299]
![image](https://user-images.githubusercontent.com/29136904/196823195-8acea135-0988-406d-9992-1bbfb77ef55d.png)

**Comment by umop3plsdn** [comment]
Just linking this for project document purposes #3302 . Also, I quickly put a small tagline in before but thought it looked a little naked being a small sentence and thought your tagline of "An IDE layer for Neovim with sane defaults. Completely free and community driven." might look better?

**Comment by umop3plsdn** [comment]
#3303 merged
