### ISSUE TITLE
Easier to see indicator for modified / dirty buffers

### ISSUE THREAD

**Issue by Isti115** [LunarVim/LunarVim#3307]
### Feature Description

Currently the only indication that a buffer has been modified, but not yet saved seems to be the green dot instead of the X on `bufferline.nvim`.
I'm used to having my entire statusline change color when the buffer becomes dirty, which is a lot more visible, especially since the "tabs" of bufferline can get scrolled off the screen even if the window in which they are shown is still present.
I would really like to be able to have some kind of more prominent indication of unsaved buffer contents, as since switching to LunarVim I have confused myself by trying to test code which was not yet saved several times, and I don't remember that happening to me at all before I made the switch from my own config.

### Describe the alternatives you have considered

I have searched the documentation and issues of `bufferline.nvim`, `lualine.nvim` and `nvim-navic` as well (which is by the way missing from the Core Plugin List in the LunarVim docs) to see if they provide some way to make changed buffers more visible, but none of them seem to be designed to do this. (`lualine.nvim` has some extension that's supposed to change the color of the filename, but it didn't really work properly for me in `neovide`, on the other hand in my regular terminal the entire statusline has been a bit messed up in LunarVim.)

I might try switching back to the default neovim statusline with `laststatus` set to 2.
_(Edit: Instead of that I just restored the `[+]` modified indicator in `lualine.nvim`, hopefully having one indicator on the bottom and one at the top if the tab is visible will be better.)_

**Comment by cpea2506** [comment]
https://github.com/LunarVim/LunarVim/blob/36c8bdee9ff59a0a63c1edfc445b5eb2886cf246/lua/lvim/core/bufferline.lua#L70

I'm not sure if this is the option that you want. This will default put a circle at the end of tab when there is a modified change.

**Comment by Isti115** [comment]
Thanks for the reply, but if I understand correctly, that is just the default behavior, which I already have and find to be way too easy to go unnoticed.

**Comment by cpea2506** [comment]
> Thanks for the reply, but if I understand correctly, that is just the default behavior, which I already have and find to be way too easy to go unnoticed.

The option is in `lvim.builtin.bufferline` table, so you can easily change it to some icon that you want to:
```lua
lvim.builtin.bufferline.options.modified_icon = "X"
```
You can also change the highlight:
```lua
lvim.builtin.bufferline.highlights.modified = { fg = , bg = }
lvim.builtin.bufferline.highlights.modified_visible = { fg = , bg = }             
lvim.builtin.bufferline.highlights.modified_selected = { fg = , bg = }
```

**Comment by nairobi02** [comment]
> https://github.com/LunarVim/LunarVim/blob/36c8bdee9ff59a0a63c1edfc445b5eb2886cf246/lua/lvim/core/bufferline.lua#L70
> 
> I'm not sure if this is the option that you want. This will default put a circle at the end of tab when there are modifications.

How do i decrease the size of this circle? since the last update, its become HUGE
![image](https://user-images.githubusercontent.com/109964994/197266718-41235905-edb6-4879-a298-4dad5647f76e.png)

**Comment by cpea2506** [comment]
> > https://github.com/LunarVim/LunarVim/blob/36c8bdee9ff59a0a63c1edfc445b5eb2886cf246/lua/lvim/core/bufferline.lua#L70
> > 
> > I'm not sure if this is the option that you want. This will default put a circle at the end of tab when there are modifications.
> 
> How do i decrease the size of this circle? since the last update, its become HUGE ![image](https://user-images.githubusercontent.com/109964994/197266718-41235905-edb6-4879-a298-4dad5647f76e.png)

You can get it from here (search for circle): <https://www.nerdfonts.com/cheat-sheet>

**Comment by nairobi02** [comment]
> > > https://github.com/LunarVim/LunarVim/blob/36c8bdee9ff59a0a63c1edfc445b5eb2886cf246/lua/lvim/core/bufferline.lua#L70
> > > 
> > > I'm not sure if this is the option that you want. This will default put a circle at the end of tab when there are modifications.
> > 
> > 
> > How do i decrease the size of this circle? since the last update, its become HUGE.
> 
> You can get it from here (search for circle): https://www.nerdfonts.com/cheat-sheet

hey, im not sure i understand. I already have a nerd font running in windows terminal. 
What do i do with the circle i copy from here? where do i paste it?

**Comment by cpea2506** [comment]
> hey, im not sure i understand. I already have a nerd font running in windows terminal. What do i do with the circle i copy from here? where do i paste it? and which of the three do i copy, hex icon or class? also i think i should mention, it started looking like this only after the last update on master. It was fine until then

lvim.icons.ui.Circle = "put your here"

**Comment by kobzarchekg** [comment]
The issue is resoved for you @Isti115 ?

**Comment by Isti115** [comment]
@kobzarchekg Thanks for asking, but sadly not yet, as I wasn't able to make the following work (not even with single characters):
`lvim.builtin.bufferline.options.modified_icon = '[+]'`
Actually, the only config for `bufferline` that takes effect for me seems to be completely disabling it:
`lvim.builtin.bufferline.active = false`
For example, switching to `tab` mode isn't working either:
`lvim.builtin.bufferline.options.mode = 'tabs'`
But it might be something trivial that I'm overlooking, I wasn't able to spend much time troubleshooting this yet.

**Comment by Isti115** [comment]
I don't know what changed since then, it might've been caused by an update, which for a change fixed something this time instead of breaking stuff, but setting the `bufferline` to `tabs` mode works now and there is also an indicator on the breadcrumbs section (`nvim-navic` I guess) which is constantly visible, so I don't really face this issue anymore, thus I close it.
