### ISSUE TITLE
Copy/Paste registry preview don't show anymore

### ISSUE THREAD

**Issue by ftaiolivista** [LunarVim/LunarVim#3308]
### Problem description

Pressing "  the registry preview don't show up anymore.

### LunarVim version

master-36c8bde

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

Linux 64

### Steps to reproduce

Press "

### support info

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 

Buffer info
* filetype:                javascript
* bufnr:                   6
* treesitter status:       active

Active client(s)
* name:                      tsserver
* id:                        1
* supported filetype(s):     [javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx]
* attached buffers:          6
* root_dir pattern:          6
* capabilities:              callsProvider                   | referencesProvider      | inlayHintProvider
                             documentRangeFormattingProvider | definitionProvider      | foldingRangeProvider
                             documentFormattingProvider      | implementationProvider  | renameProvider
                             documentHighlightProvider       | workspaceSymbolProvider | typeDefinitionProvider
                             documentSymbolProvider          | hoverProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels, html, cssls, tailwindcss]

Formatters info
* Active: prettier_eslint  
* Supported: [deno_fmt, dprint, eslint, eslint_d, prettier, prettier_d_slim, prettier_standard, prettierd, rome, rustywind, semistandardjs, standardjs]

Linters info
* Active: eslint  
* Supported: [eslint, eslint_d, jshint, semistandardjs, standardjs, xo]

Code actions info
* Active:

**Comment by cpea2506** [comment]
https://github.com/LunarVim/LunarVim/blob/36c8bdee9ff59a0a63c1edfc445b5eb2886cf246/lua/lvim/core/which-key.lua#L10

It is disabled by default, turn it on by
```lua
lvim.builtin.which_key.setup.plugins.registers = true
```

**Comment by ftaiolivista** [comment]
Thanks @cpea2506 . Works good!!!
