### ISSUE TITLE
Problem with using Rnvimr as picker and explorer

### ISSUE THREAD

**Issue by Joachim-42he** [LunarVim/LunarVim#3310]
### Problem description

After adding Rnvimr to `init.lua`  
```lua
{
    "kevinhwang91/rnvimr",
    cmd = "RnvimrToggle",
    setup = function()
      vim.g.rnvimr_enable_ex = 1       -- replace netrw
      vim.g.rnvimr_enable_picker = 1  -- use Ranger as a picker
     end,
  },
```
I can manually start Rnvimr/Ranger fine, but when I start Lunarvim with a folder argument like `lvim ~/.config`, Lunarvim starts and inŧead of opening Rnvimr/Ranger, it opens Lir.   
If I disable lir like this in `init.lua`
```lua
lvim.builtin.lir.active = false
```
and again start Lunarvim like above, it still opens without Rnvimr, in fact without any explorer at all and I get an error from Packer about it not being able to configure Lir.  
I could, of course start Lunarvim with the `-c` attribute `lvim -c Rnvimr ~/.config` to get Ranger to open on start as a picker but would like to do it the right way and get rid of Packer's error message.

### LunarVim version

rolling-7715900

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

EndeavourOS (Arch)

### support info

```console

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                
* bufnr:                   4
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

**Comment by Joachim-42he** [comment]
BTW: The configuration example for Rnvimr in the [Lunarvim documentation](https://www.lunarvim.org/docs/plugins/extra-plugins#rnvimr) did not work for me and does not correspond to the variable names listed in [Rnvimr's documentation](https://github.com/kevinhwang91/rnvimr/blob/main/doc/rnvimr.txt).

**Comment by umop3plsdn** [comment]
it worked for me just fine. Did PackerSync pick it up for you? What happens when you :RnvimrToggle

**Comment by umop3plsdn** [comment]
Also you'll want to start it like "lvim -c Rnvimr" should pop right up

**Comment by kobzarchekg** [comment]
Try the next
```
{
    "kevinhwang91/rnvimr",
    cmd = "RnvimrToggle",
    config = function()
    require("rnvimr").setup({
      vim.g.rnvimr_enable_ex = 1       -- replace netrw
      vim.g.rnvimr_enable_picker = 1  -- use Ranger as a picker
    })
    end,
  },
```

**Comment by umop3plsdn** [comment]
if you use the exact code from the documentation
{
    "kevinhwang91/rnvimr",
    cmd = "RnvimrToggle",
    setup = function()
      vim.g.rnvimr_enable_ex = 1       -- replace netrw
      vim.g.rnvimr_enable_picker = 1  -- use Ranger as a picker
     end,
  },

then comment out vim.cmd("normal ! 0") on line 130 in scheduler .local/share/lunarvim/site/pack/packer/start/lir.nvim/lua/lir.lua

**Comment by Joachim-42he** [comment]
Thank you for your reply, but I already knew about the "-c" flag as I wrote above. I switched to n³ instead, which is working as intended.
