### ISSUE TITLE
Keybind/command to open website in the docs section

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#3312]
AC:
- there is a keybind/command that opens to this link: https://www.lunarvim.org/docs/installation
- command should be `:LvimDocs`

**Comment by javamultiplex** [comment]
@ChristianChiarulli  - I would like to work on this, can you pleas assign to me?

**Comment by umop3plsdn** [comment]
This is a simple one liner
 vim.cmd [[command! LvimDocs execute 'silent !open "https://www.lunarvim.org/docs/installation"']]

**Comment by javamultiplex** [comment]
@ChristianChiarulli  - Can you please give more details on requirement? Where to add command?

**Comment by LostNeophyte** [comment]
> @ChristianChiarulli - Can you please give more details on requirement? Where to add command?

commands are [here](https://github.com/LunarVim/LunarVim/blob/master/lua/lvim/core/commands.lua), and bind it in which key under something like `L d(for docs)`
