### ISSUE TITLE
In the latest rolling there is a call to a nil function in theme.lua

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#3315]
### Problem description

Just pulled the latest from rolling, and when I try to open lunarvim I get a fatal error on `lua/lvim/core/theme.lua:84`, which prevents the rest of configs and plugins to load.

### LunarVim version

rolling

### Neovim version (>= 0.8.0)

0.9.0

### Operating system/version

macos 12

### Steps to reproduce

If you try to run the installer this problem also exists.
And then the installer fails to run packersync because the core was not properly loaded.

### support info

```
Preparing Packer setup
Error detected while processing /Users/danielo/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: ...nielo/.local/share/lunarvim/lvim/lua/lvim/core/theme.lua:84: attempt to call field 'setup' (a nil value)
stack traceback:
        ...nielo/.local/share/lunarvim/lvim/lua/lvim/core/theme.lua:84: in function 'config'
        ...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:30: in function 'config'
        ...ielo/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:21: in function 'init'
        ...anielo/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:105: in function 'init'
        /Users/danielo/.local/share/lunarvim/lvim/init.lua:11: in main chunk
Error detected while processing command line:
E492: Not an editor command: PackerSync
```

**Comment by GwiZZLe** [comment]
I have the exact same error when attempting to run lunarvim with neovide using:
`neovide -- -u ~/.local/share/lunarvim/lvim/init.lua`
![image](https://user-images.githubusercontent.com/38036474/197337108-6f918b1b-728f-4d8f-ba4c-f02b1b89727e.png)

**Comment by Israr** [comment]
I have same issue

`Error detected while processing /Users/ikhan/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: ...ikhan/.local/share/lunarvim/lvim/lua/lvim/core/theme.lua:84: attempt to call field 'setup' (a nil value)
stack traceback:
        ...ikhan/.local/share/lunarvim/lvim/lua/lvim/core/theme.lua:84: in function 'config'
        ...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:30: in function 'config'
        ...khan/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:21: in function 'init'
        .../ikhan/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:102: in function 'init'
        /Users/ikhan/.local/share/lunarvim/lvim/init.lua:11: in main chunk`

**Comment by rednaks** [comment]
same issue but on the release 
neovim --version: 
```
NVIM v0.8.0-1210-gd367ed9b2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az505-656

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by Israr** [comment]
+1. I also tried release branch, with neovim 0.8 and got same issue.

**Comment by cataglyphis** [comment]
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3

+1.

**Comment by umop3plsdn** [comment]
A new commit has been merged that should have fixed this if you start over from scratch.

**Comment by Israr** [comment]
> A new commit has been merged that should have fixed this if you start over from scratch.

verified that it works now. 

However I tried uninstalling lunarvim via uninstalls script, that did not work. I had to manually delete `rm -rf` lvim directory and re-run the install script.

Verified with nvim 0.8 and rolling branch.

**Comment by Black-Sirius69** [comment]
Did you do a packer sync to try and fix this as this error usually comes whenever the plugin is not present

**Comment by danielo515** [comment]
After a full re-install (manually removing the folder) this issue disappeared.

**Comment by umop3plsdn** [comment]
pr #3327 fixed issue
