### ISSUE TITLE
Would you consider including hlargs.nvim?

### ISSUE THREAD

**Issue by btegs** [LunarVim/LunarVim#3321]
### Feature Description

Matches the color of the argument with the reference in the function

### Support information

I noticed this after submitting a request for Catppuccin at https://github.com/catppuccin/nvim/issues/314 where the developer mentioned the hlargs.nvim plugin: https://github.com/m-demare/hlargs.nvim

I do realize that I can install this manually in my LunarVim setup, but would it be worthy of being included in the main LunarVim setup?

**Comment by kobzar** [comment]
Yes. You can add it in your config like any of external plugins
Just add this to your config
```
  -- Hlargs
  {"m-demare/hlargs.nvim",
    config = function()
    require("hlargs").setup()
    end,
  },
```
If you need some changes in futures you can just add it in setup() like
```
require("hlargs").setup({...})
```

**Comment by kobzarchekg** [comment]
This is resove you question?

**Comment by btegs** [comment]
@kobzarchekg - I dunno if its an issue with the way the plugin is handling it or the Catppuccin theme, but not seeing any highlights hmm

![hlargs](https://user-images.githubusercontent.com/5166649/197406049-2edafabc-1c77-4c22-b131-9a7614cecc1a.png)

**Comment by btegs** [comment]
After working with the developer, it seemed that Packer Update option didn't just work. I had to do a Packer Sync then a Packer Re-Compile in LunarVim.
