### ISSUE TITLE
/.local/share/lunarvim/lvim/init.lua 时发生错误: E5113: Error while calling lua chunk: ...an/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:46: Vim(packadd):E919: Directory not found in 'packpath': "pack/*/opt/packer.nvim" stack traceback: 	[C]: in function 'cmd' 	...an/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:46: in function 'init'

### ISSUE THREAD

**Issue by jinfagang** [LunarVim/LunarVim#3322]
### Problem description

/.local/share/lunarvim/lvim/init.lua 时发生错误:
E5113: Error while calling lua chunk: ...an/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:46: Vim(packadd):E919: Directory not found in 'packpath': "pack/*/opt/packer.nvim"
stack traceback:
	[C]: in function 'cmd'
	...an/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:46: in function 'init'

### LunarVim version

0.8

### Neovim version (>= 0.8.0)

0.8

### Operating system/version

macOS 11.5

### Steps to reproduce

/.local/share/lunarvim/lvim/init.lua 时发生错误:
E5113: Error while calling lua chunk: ...an/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:46: Vim(packadd):E919: Directory not found in 'packpath': "pack/*/opt/packer.nvim"
stack traceback:
	[C]: in function 'cmd'
	...an/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:46: in function 'init'

### support info

/.local/share/lunarvim/lvim/init.lua 时发生错误:
E5113: Error while calling lua chunk: ...an/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:46: Vim(packadd):E919: Directory not found in 'packpath': "pack/*/opt/packer.nvim"
stack traceback:
	[C]: in function 'cmd'
	...an/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:46: in function 'init'

### Screenshots

/.local/share/lunarvim/lvim/init.lua 时发生错误:
E5113: Error while calling lua chunk: ...an/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:46: Vim(packadd):E919: Directory not found in 'packpath': "pack/*/opt/packer.nvim"
stack traceback:
	[C]: in function 'cmd'
	...an/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:46: in function 'init'

**Comment by kobzar** [comment]
Check that your shell is bash and git is installed.
Next, attach full log after you run installation script please

**Comment by umop3plsdn** [comment]
A new commit has been merged that should have fixed this if you start over from scratch.

**Comment by kobzar** [comment]
@jinfagang What about situation with your issue?

**Comment by umop3plsdn** [comment]
pr #3327 fixed this issue
