### ISSUE TITLE
Customizing cmp sorting function

### ISSUE THREAD

**Issue by Glyphack** [LunarVim/LunarVim#3326]
### Feature Description

It would be nice to be able to customize `cmp.sorting` function.
This will help me to customize the sorting for my copilot suggestions([ref](https://github.com/zbirenbaum/copilot-cmp#comparators).

### Describe the alternatives you have considered

We can try to come up with a sorting that works for the majority of users.

**Comment by kobzarchekg** [comment]
Add more description please. 
For wich languadge you need sorting. 
What custimuzed options are you mean?

**Comment by cpea2506** [comment]
I'm not sure this is want you want. But if the `sorting` setting is in `setup` function, we can make use of `lvim.builtin.cmp.<option>`
```lua
local cmp = require "cmp"
lvim.builtin.cmp.sorting = {
    priority_weight = 2,
    comparators = {
        cmp.config.compare.offset,
        cmp.config.compare.exact,
        cmp.config.compare.score,
        cmp.config.compare.recently_used,
        cmp.config.compare.locality,
        cmp.config.compare.kind,
        cmp.config.compare.sort_text,
        cmp.config.compare.length,
        cmp.config.compare.order,
    },
}
```

**Comment by chase** [comment]
This can already be done, you can see my lvim config for an example: https://github.com/chase/lvim/blob/main/config.lua#L94-L128

**Comment by Glyphack** [comment]
Thanks for the helpful answers. I'm closing this now.
