### ISSUE TITLE
Kubernetes completion's | yaml not support kubernetes scheme

### ISSUE THREAD

**Issue by komildeveloper** [LunarVim/LunarVim#3331]
### Problem description

https://user-images.githubusercontent.com/64638545/197571274-6a2fcd1e-ff2b-42d0-8c20-efae7c39fc6b.mp4

### LunarVim version

rolling-42e410c

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-89-geb123b565

### Operating system/version

Linux - Arch Linux

### Affected language servers

yamls

### Actual behavior

kubernetes completion's doesn't work in yamlls, but other schemes working, docker-compose, skaffold, github-actions

### support info

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels, rust_analyzer, gopls, tsserver, yamlls, jdtls]

**Comment by kdamaski** [comment]
i am also interested in this fix

**Comment by gsalvatella** [comment]
Same problem. Any ideas?
