### ISSUE TITLE
Cargo not reloading after changing Cargo.toml [Rust]

### ISSUE THREAD

**Issue by davebrouwer1** [LunarVim/LunarVim#3333]
### Problem description

I am trying to load in a rust dependency, I added it in my cargo.toml, then when I do "RustRun" I get a unresolved import error, so I do "CargoReload" however, that gives me the error: "Method not found: rust-analyzer/reloadWorkspace" 

### LunarVim version

master-25c4241

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Ubuntu in WSL

### support info

```console
 Language client log: /home/dave/.local/state/nvim/lsp.log
 Detected filetype:   rust
 
 2 client(s) attached to this buffer: 
 
 Client: copilot (id: 1, pid: nil, bufnr: [4])
 	filetypes:       
 	autostart:       true
 	root directory:  /home/dave/helpsimone
 	cmd:             node /home/dave/.local/share/lunarvim/site/pack/packer/opt/copilot.lua/copilot/index.js
 
 Client: rust_analyzer (id: 2, pid: nil, bufnr: [4])
 	filetypes:       rust
 	autostart:       true
 	root directory:  /home/dave/helpsimone
 	cmd:             rust-analyzer
 
 Configured servers list: rust_analyzer
```

```console

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                rust
* bufnr:                   4
* treesitter status:       active

Active client(s)
* name:                      copilot
* id:                        1
* supported filetype(s):     []
* attached buffers:          4
* root_dir pattern:          4
* name:                      rust_analyzer
* id:                        2
* supported filetype(s):     rust
* attached buffers:          4
* root_dir pattern:          4
* capabilities:              selectionRangeProvider | referencesProvider      | callHierarchyProvider
                             foldingRangeProvider   | definitionProvider      | documentFormattingProvider
                             hoverProvider          | typeDefinitionProvider  | documentHighlightProvider
                             declarationProvider    | implementationProvider
                             documentSymbolProvider | workspaceSymbolProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: [dprint, rustfmt]

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

### Screenshots

![WindowsTerminal_Hm2Ke2jxsr](https://user-images.githubusercontent.com/43647034/197601306-2501f99b-15e7-4a6d-b134-14be453e9329.png)
![WindowsTerminal_sZxy5JFxQj](https://user-images.githubusercontent.com/43647034/197601387-82a3851b-2e19-4451-8210-4a49665fa0d6.png)

![WindowsTerminal_ch3dplLODS](https://user-images.githubusercontent.com/43647034/197601440-9fbf7ca3-e5a4-4f48-9322-6906f8e5b474.png)

**Comment by umop3plsdn** [comment]
Are you using from the rust-ide starter? You should be running via Space+l+l from your codelens function

**Comment by davebrouwer1** [comment]
I'm sorry, I'm still pretty new to this, so a bit confused as to what you mean, I'm not sure what "using from rust-ide starter" means, running space + l + l gives me: "no executable codelens found at current line"

**Comment by umop3plsdn** [comment]
No worries.. https://github.com/LunarVim/starter.lvim the rust-ide branch. Also you want to be on the function line of what you are testing where it says play and debug

**Comment by umop3plsdn** [comment]
You can also toggle break points in your code to pull up in the debugger. Space+d+t sets breaks and space+d+U opens dapui

**Comment by davebrouwer1** [comment]
Thanks both of you, it works now, mixed and matched some of the rust-ide branch, which included crates.nvim with my personal config.
