### ISSUE TITLE
It seems that the configuration of colorscheme did not work

### ISSUE THREAD

**Issue by MenMensAa** [LunarVim/LunarVim#3336]
### Problem description

````lua
lvim.colorscheme = "onedark"

-- Additional Plugins
lvim.plugins = {
    {
        'navarasu/onedark.nvim',
        config = function()
            require("onedark").setup({
                style = "dark",
                -- transparent = true,
                code_style = {
                    comments = "italic",
                    keywords = "italic,bold",
                    functions = "italic"
                }
            })
            vim.cmd("colorscheme onedark")
        end
    }
}
````

If I modify colorscheme in command line mode, it works. But when I restart lvim it fails again

### LunarVim version

master-30c65cf

### Neovim version (>= 0.8.0)

Nvim v0.8.0 LuaJIT 2.1.0-beta3

### Operating system/version

macOS 11.5.1

### support info

No

### Screenshots

changing colorscheme in the command line.
![image](https://user-images.githubusercontent.com/51371004/197695798-1cdfb13b-db6d-4a1c-a952-957fb55b1c8a.png)

restart lvim it goes back
![image](https://user-images.githubusercontent.com/51371004/197696091-e0c33e0b-549f-4339-8252-6afd75722ee3.png)

**Comment by cpea2506** [comment]
You might have to run `:PackerCompile` after changing plugin's config

**Comment by MenMensAa** [comment]
> You might have to run `:PackerCompile` after changing plugin's config

my fail.thanks guys!
