### ISSUE TITLE
Where can i define g:python3_host_prog

### ISSUE THREAD

**Issue by kisuke95** [LunarVim/LunarVim#3339]
### Problem description

Can someone tell me where to set `g:python3_host_prog` ? For neovim, i can set it in ~/.config/nvim/init.vim, but where and how to set it in LunarVim ?

### LunarVim version

1.1.4

### Neovim version (>= 0.8.0)

0.8.0

### Operating system/version

macOS 11.5

### support info

none

**Comment by cpea2506** [comment]
Of course, in `~/.config/lvim/config.lua`. You can go to that file by entering `lvim` and choose last option in `Dashboard`.

**Comment by kisuke95** [comment]
Thanks, it workes.

> Of course, in `~/.config/lvim/config.lua`. You can go to that file by entering `lvim` and choose the last option in `Dashboard`.
