### ISSUE TITLE
Add my own banner(logo)

### ISSUE THREAD

**Issue by AjayShanker-geek** [LunarVim/LunarVim#3341]
### Problem description

I would to switch LunarVim logo to my own custom logo

### LunarVim version

master-9e27509

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

MacOS 13.0

### support info

                                                                                                         │ │
             │    __                          _    ___                                                                  │ │
             │   / /   __  ______  ____ _____| |  / (_)___ ___                                                          │ │
             │  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \                                                         │ │
             │ / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /                                                         │ │
             │/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/                                                          │ │
             │                                                                                                          │ │
             │                                                                                                          │ │
             │Buffer info                                                                                               │ │
             │* filetype:                alpha                                                                          │ │
             │* bufnr:                   1                                                                              │ │
             │* treesitter status:       inactive                                                                       │ │
             │                                                                                                          │ │
             │Active client(s)                                                                                          │ │
             │                                                                                                          │ │
             │Automatic LSP info                                                                                        │ │
             │* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golan│ │
             │                                                                                                          │ │
             │Formatters info                                                                                           │ │
             │* Active:                                                                                                 │ │
             │* Supported: []                                                                                           │ │
             │                                                                                                          │ │
             │Linters info                                                                                              │ │
             │* Active:                                                                                                 │ │
             │* Supported: []                                                                                           │ │
             │                                                                                                          │ │
             │Code actions info                                                                                         │ │
             │* Active:

**Comment by LostNeophyte** [comment]
You can change the logo in the dashboard like this:
```lua
lvim.builtin.alpha.dashboard.section.header.val = {
  "                ⢀⣀⣤⣤⣤⣶⣶⣶⣶⣶⣶⣤⣤⣤⣀⡀                ",
  "             ⣀⣤⣶⣿⠿⠟⠛⠉⠉⠉⠁⠈⠉⠉⠉⠛⠛⠿⣿⣷⣦⣀             ",
  "          ⢀⣤⣾⡿⠛⠉                ⠉⠛⢿⣷⣤⡀          ",
  "         ⣴⣿⡿⠃ change these lines   ⠙⠻⣿⣦         ",
  " ⢀⣠⣤⣤⣤⣤⣤⣾⣿⣉⣀⡀                        ⠙⢻⣷⡄       ",
  "⣼⠋⠁   ⢠⣿⡟ ⠉⠉⠉⠛⠛⠶⠶⣤⣄⣀    ⣀⣀      ⢠⣤⣤⡄   ⢻⣿⣆      ",
  "⢻⡄   ⢰⣿⡟        ⢠⣿⣿⣿⠉⠛⠲⣾⣿⣿⣷    ⢀⣾⣿⣿⠁    ⢻⣿⡆     ",
  " ⠹⣦⡀ ⣿⣿⠁        ⢸⣿⣿⡇   ⠻⣿⣿⠟⠳⠶⣤⣀⣸⣿⣿⠇      ⣿⣷     ",
  "   ⠙⢷⣿⡇         ⣸⣿⣿⠃          ⢸⣿⣿⢷⣤⡀     ⢸⣿⡆    ",
  "    ⢸⣿⠇         ⣿⣿⣿     ⣿⣿⣷  ⢠⣿⣿⡏ ⠈⠙⠳⢦⣄  ⠈⣿⡇    ",
  "    ⢸⣿⡆        ⢸⣿⣿⡇     ⣿⣿⣿ ⢀⣿⣿⡟      ⠈⠙⠷⣤⣿⡇    ",
  "    ⠘⣿⡇        ⣼⣿⣿⠁     ⣿⣿⣿ ⣼⣿⣿⠃         ⢸⣿⠷⣄⡀  ",
  "     ⣿⣿        ⣿⣿⡿      ⣿⣿⣿⢸⣿⣿⠃          ⣾⡿ ⠈⠻⣆ ",
  "     ⠸⣿⣧      ⢸⣿⣿⣇⣀⣀⣀⣀⣀⣀⣸⣿⣿⣿⣿⠇          ⣼⣿⠇   ⠘⣧",
  "      ⠹⣿⣧     ⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏          ⣼⣿⠏    ⣠⡿",
  "       ⠘⢿⣷⣄   ⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉         ⢠⣼⡿⠛⠛⠛⠛⠛⠛⠉ ",
  "         ⠻⣿⣦⣄                      ⣀⣴⣿⠟         ",
  "          ⠈⠛⢿⣶⣤⣀                ⣀⣤⣶⡿⠛⠁          ",
  "             ⠉⠻⢿⣿⣶⣤⣤⣀⣀⡀  ⢀⣀⣀⣠⣤⣶⣿⡿⠟⠋             ",
  "                ⠈⠉⠙⠛⠻⠿⠿⠿⠿⠿⠿⠟⠛⠋⠉⠁                ",
}
```

**Comment by lmckiwo** [comment]
This really isn't a bug.  This is a feature request.

**Comment by AjayShanker-geek** [comment]
Thanks
