### ISSUE TITLE
<CR> completion confirmation deletes indentation for copilot

### ISSUE THREAD

**Issue by dmvinson** [LunarVim/LunarVim#3343]
### Problem description

Steps to reproduce:
1. setup Github Copilot according to Lunarvim documentation
2. Begin typing in a file, wait for Copilot completion to appear
3. Use enter (`<CR>`) to accept completion

Expected behavior:
Completion executes and inputs suggestion beginning at current pointer location

Actual behavior: 
Completion inputs suggestion at current pointer location, but deletes prior indentation

Another interesting finding is that this does not happen when using C-y to accept completions, as was added in #2913, and it only happens with the copilot-cmp source.

This seems to occur in all languages, although I've mainly noticed it with Python and Nix.

### LunarVim version

rolling-b6dd175

### Neovim version (>= 0.8.0)

NVIM v.0.8.0

### Operating system/version

macOS 12.3.1

### support info

```console
:LvimInfo
Buffer info
* filetype:                nix
* bufnr:                   57
* treesitter status:       active

Active client(s)
* name:                      copilot
* id:                        1
* supported filetype(s):     []
* attached buffers:          [23, 52, 66, 7, 16, 22, 57]
* root_dir pattern:          [23, 52, 66, 7, 16, 22, 57]
* name:                      pyright
* id:                        2
* supported filetype(s):     python
* attached buffers:          [7, 16, 23, 22]
* root_dir pattern:          [7, 16, 23, 22]
* capabilities:              callHierarchyProvider
* name:                      rnix
* id:                        4
* supported filetype(s):     nix
* attached buffers:          [66, 52, 57]
* root_dir pattern:          [66, 52, 57]
* capabilities:              renameProvider         | definitionProvider
                             selectionRangeProvider | documentFormattingProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels, pyright, rust_analyzer]

Formatters info
* Active: nixpkgs_fmt  
* Supported: [alejandra, nixfmt, nixpkgs_fmt]

Linters info
* Active: 
* Supported: [deadnix, statix]

Code actions info
* Active: 
```

```
:LspInfo
 Language client log: $HOME/.local/state/nvim/lsp.log
 Detected filetype:   nix
 
 3 client(s) attached to this buffer: 
 
 Client: copilot (id: 1, pid: nil, bufnr: [23, 52, 66, 7, 16, 22, 57])
 	filetypes:       
 	autostart:       true
 	root directory:  $HOME/project
 	cmd:             node $HOME/.local/share/lunarvim/site/pack/packer/opt/copilot.lua/copilot/index.js
 
 Client: null-ls (id: 3, pid: 5001, bufnr: [23, 52, 66, 7, 16, 22, 57])
 	filetypes:       python, nix, go
 	autostart:       false
 	root directory:  $HOME/project
 	cmd:             <function>
 
 Client: rnix (id: 4, pid: nil, bufnr: [66, 52, 57])
 	filetypes:       nix
 	autostart:       true
 	root directory:  $HOME/project
 	cmd:             rnix-lsp
 
 1 active client(s) not attached to this buffer: 
 
 Client: pyright (id: 2, pid: nil, bufnr: [7, 16, 23, 22])
 	filetypes:       python
 	autostart:       true
 	root directory:  $HOME/project/factory/agents
 	cmd:             pyright-langserver --stdio
 
 Configured servers list: rnix, pyright
```

**Comment by wstewarttennes** [comment]
I still have this issue today

**Comment by wstewarttennes** [comment]
I was able to fix this by changing
`      ["<CR>"] = cmp.mapping(function(fallback)
        if cmp.visible() then
          local confirm_opts = vim.deepcopy(lvim.builtin.cmp.confirm_opts) -- avoid mutating the original opts below
          local is_insert_mode = function()
            return vim.api.nvim_get_mode().mode:sub(1, 1) == "i"
          end
          if is_insert_mode() then -- prevent overwriting brackets
            confirm_opts.behavior = cmp.ConfirmBehavior.Insert
          end
          if cmp.confirm(confirm_opts) then
            return -- success, exit early
          end
        end

        fallback() -- if not exited early, always fallback
      end),
`

to

`      ["<CR>"] = cmp.mapping(function(fallback)
        if cmp.visible() then
          local confirm_opts = vim.deepcopy(lvim.builtin.cmp.confirm_opts) -- avoid mutating the original opts below
          local is_insert_mode = function()
            return vim.api.nvim_get_mode().mode:sub(1, 1) == "i"
          end
          if is_insert_mode() then -- prevent overwriting brackets
            confirm_opts.behavior = cmp.ConfirmBehavior.Replace
          end
          if cmp.confirm(confirm_opts) then
            return -- success, exit early
          end
        end

        fallback() -- if not exited early, always fallback
      end),
`
