### ISSUE TITLE
Unable to Start Lunarvim

### ISSUE THREAD

**Issue by mdevac** [LunarVim/LunarVim#3345]
### Problem description

log after running /home/mohammad/.local/bin/lvim :

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x55b980a501d5]

goroutine 1 [running]:
main.main.func1()
	/build/snapd/parts/snapd-deb/build/cmd/snap/main.go:492 +0x95
panic(0x55b9810f40c0, 0x55b98176c8f0)
	/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b6
main.run(0xc000405db8, 0xe)
	/build/snapd/parts/snapd-deb/build/cmd/snap/main.go:559 +0x375
main.main()
	/build/snapd/parts/snapd-deb/build/cmd/snap/main.go:497 +0x371

### LunarVim version

latest (LTS)

### Neovim version (>= 0.8.0)

0.9.0

### Operating system/version

Ubuntu 22.04

### support info

not able to install lvim

**Comment by Black-Sirius69** [comment]
Try building neovim from scratch instead of using the snap I think this is a snap error and not a LunarVim error as LunarVim is nothing but a custom config over neovim

**Comment by DARKBOW923** [comment]
I have the error "Command 'lvim' not found, but there are 26 similar ones."

I need some help ty

**Comment by Black-Sirius69** [comment]
lvim is most probably an alias that u have to set for yourselves I have not use lunarvim so I do not know for sure. I will check and tell you. Till then try typing nvim in terminal

**Comment by Black-Sirius69** [comment]
Check this page

https://www.lunarvim.org/docs/quick-start

**Comment by mdevac** [comment]
thanks, manual cloning solves the problem.

**Comment by mdevac** [comment]
hi, i  decided to re-open this issue because this is happening on another new installing client.

~/.local/bin$ ./lvim
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x56488b6501d5]

goroutine 1 [running]:
main.main.func1()
        /build/snapd/parts/snapd-deb/build/cmd/snap/main.go:492 +0x95
panic(0x56488bcf40c0, 0x56488c36c8f0)
        /usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b6
main.run(0xc0003b9db8, 0xe)
        /build/snapd/parts/snapd-deb/build/cmd/snap/main.go:559 +0x375
main.main()
        /build/snapd/parts/snapd-deb/build/cmd/snap/main.go:497 +0x371

**Comment by LostNeophyte** [comment]
Does normal nvim work?

**Comment by chase** [comment]
That error looks like snapd failing, so I doubt this is a LunarVim issue.

I highly recommend using the `.deb` to install instead of the unsupported snap: https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.deb

**Comment by mdevac** [comment]
it worked, thanks.

**Comment by mdevac** [comment]
> Does normal nvim work?

thanks for concerning :)

**Comment by fractalspace** [comment]
It's Dec 26. I am seeing this same issue. (raspberrypi ubuntu:22.04 vim:9.0.242 nvim:0.8.1)
nvim installed using deb package. nvim by itself works.

**Comment by TerrniT** [comment]
After trying re-install multi times  I just `source /.profile` in bash shell and this solves issue
