### ISSUE TITLE
install script didnt work with font bug

### ISSUE THREAD

**Issue by hiimnooob** [LunarVim/LunarVim#3349]
### Problem description

i install with `Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression`
error:
<img width="577" alt="a" src="https://user-images.githubusercontent.com/104507477/198071634-bc9dc67b-32ce-43ec-af5f-38956cc583eb.png">

### LunarVim version

idk but latest

### Neovim version (>= 0.8.0)

0.9.0

### Operating system/version

win11

**Comment by LostNeophyte** [comment]
I am not familiar with powershell but:
`??` is a [null-coalescing operator](https://learn.microsoft.com/en-gb/powershell/scripting/whats-new/what-s-new-in-powershell-70?view=powershell-7#null-coalescing-assignment-and-conditional-operators). It requires powershell 7. Did you run it in powershell 7+ ?

**Comment by hiimnooob** [comment]
yes version:7.2.7

**Comment by LostNeophyte** [comment]
Does it still happen?


7 lis 2022, 11:11 od ***@***.***:

**Comment by hiimnooob** [comment]
yes and i run script then powershell is gone

**Comment by LostNeophyte** [comment]
Does it say the same error or does it just close PowerShell?

**Comment by LostNeophyte** [comment]
> yes and i run script then powershell is gone

that's a different issue, if you're still experiencing it, please open a new issue

**Comment by LostNeophyte** [comment]
I have a pr for the second issue on the website repo
