### ISSUE TITLE
Telescope layout and display issue with transparent background

### ISSUE THREAD

**Issue by AlexBeauchemin** [LunarVim/LunarVim#3350]
### Problem description

* Sorry if this is not a lunarvim issue. It might be a telescope issue, another plugin issue or a problem with my config, will close if it doesn't belong here

When opening telescope (`<leader>f`),
1 - ~the transparent background becomes opaque~ edit: seems to be related to the material colorscheme update, so not related to lunarvim
2-  the layout is now vertical without preview instead of horizontal with preview (which was the default behavior before I assume?)

(see screenshot 1 and 2)

I've been able to kind of fix it by adding this to my config
```lua
local telescope = require('telescope')
telescope.setup {
  defaults = {
    layout_strategy = "horizontal",
  },
  pickers = {
    git_files = {
      hidden = true,
    },
    live_grep = {
      hidden = true,
    },
  },
}
```
which results in the screenshot #3 , but even when opening lunarvim it doesn't goes into effect, I need to modify/reload the config for the changes to take effect (this is probably a config issue on my end, there might be a better way to apply those telescope configs to lunarvim on initialization?). But it doesn't fix the transparent background issue, but that might be a telescope issue?

Any help would be appreciated 🙏

### LunarVim version

master-9e27509

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

macOS 12.2.1

### support info

Link to my actual config
[https://gist.github.com/AlexBeauchemin/281f5b70681bad5eeddb3f88381ca160](https://gist.github.com/AlexBeauchemin/281f5b70681bad5eeddb3f88381ca160)

### Screenshots

Normal state
![image](https://user-images.githubusercontent.com/1663993/198070364-29ed9584-3c90-49e3-b917-ced2aae21b9a.png)

On first telescope open 
![image](https://user-images.githubusercontent.com/1663993/198070575-08c9ad47-d315-4288-81a1-e03265dd21f1.png)

After fix and config change+reload
![image](https://user-images.githubusercontent.com/1663993/198070783-2e12fd6a-a6b3-475e-86b4-bda59ccadf9f.png)

**Comment by AlexBeauchemin** [comment]
Also, might not be related, but I often get a bunch of `Too many open files` error on assert when saving the config
![image](https://user-images.githubusercontent.com/1663993/198116667-ca2965f3-95a9-4718-8230-93c9c67bcf83.png)

**Comment by AlexBeauchemin** [comment]
https://github.com/LunarVim/LunarVim/issues/3351 Seems related

**Comment by AlexBeauchemin** [comment]
For the transparent background after opening telescope it seems to be related to the material colorscheme. I tried switching to onedark for the colorscheme and background transparency works fine

**Comment by kie4280** [comment]
@AlexBeauchemin I fixed the layout by commenting out the pickers passed to the `telescope.setup()` config. The file is at lua/lvim/core/telescope.lua. I believe the `pickers` config in the table overrides the layout setting in the `defaults` entry. See attached screenshot.
![image](https://user-images.githubusercontent.com/6897898/198300085-93ec9e67-e6a1-4e81-9c50-88a3640e3b26.png)

**Comment by AlexBeauchemin** [comment]
@kie4280 I guess that works, but I'm assuming we would have to redo that process on every lvim release. Plus I don't think modifying the core code is a good idea in general.
There should be an easy way to revert to telescope default layout from our local user config, not sure why they changed the default telescope values in lunarvim recently, I'm curious about the reasoning here, there might be a good reason

**Comment by LostNeophyte** [comment]
This has the same effect as commenting out the pickers:
```lua
lvim.builtin.telescope.pickers = nil
```

**Comment by LostNeophyte** [comment]
You can override more of the config like this:
```lua
lvim.builtin.telescope = {
  active = true,
  defaults = {
    layout_strategy = "horizontal",
  },
  pickers = {
    git_files = {
      hidden = true,
    },
    live_grep = {
      hidden = true,
    },
  },
}
```

**Comment by AlexBeauchemin** [comment]
@LostNeophyte that works, thanks!
I might reopen a new issue for the `Too many open files` as it happens a lot when I make changes to Lunarvim's config, will try to detect a pattern or find the cause first

**Comment by LostNeophyte** [comment]
> @LostNeophyte that works, thanks! I might reopen a new issue for the `Too many open files` as it happens a lot when I make changes to Lunarvim's config, will try to detect a pattern or find the cause first

There are 2 issues with this error now #3391 and #3392
