### ISSUE TITLE
Allow customization of the debug-related maps

### ISSUE THREAD

**Issue by Eryx5502** [LunarVim/LunarVim#3352]
### Feature Description

It might be useful to be able to add custom keymaps to the debug group on `which_key`. However, the usual `lvim.builtin.which_key.mappings` mechanism is not working since, if I understood correctly, it gets overridden when dap is set up:
https://github.com/LunarVim/LunarVim/blob/77640e8064208400f6d00da7b6ebae7684d4d486/lua/lvim/core/dap.lua#L43-L59

### Describe the alternatives you have considered

It should be possible to make lunarvim preserve previous mappings if there are any.

**Comment by cpea2506** [comment]
Your custom `lvim.builtin.which_key.mappings` can be put in `on_config_done` function.

https://github.com/LunarVim/LunarVim/blob/77640e8064208400f6d00da7b6ebae7684d4d486/lua/lvim/core/dap.lua#L61-L63

**Comment by Eryx5502** [comment]
Thanks for pointing this out to me! It will do nicely as a work around. However I think it would be easier for users if `dap.lua` wouldn't override pre-existing mappings
