### ISSUE TITLE
`E15: invalid expression` in Elixir files

### ISSUE THREAD

**Issue by digzom** [LunarVim/LunarVim#3360]
### Problem description

Steps to reproduce:

1. Follow the oficial installation guide
2. (y) to all prompts
3. Open any Elixir file

After a few seconds with the file open, an error similar to this appears: 

```bash
Error executing vim.schedule lua callback: ...te/pack/packer/opt/bufferline.nvim/lua/bufferline/ui.lua:158: Vim(redraw):E15: Expressão inválida: "credentials" => %{"email" => email, "password" => password
stack traceback:
        [C]: in function 'cmd'
        ...te/pack/packer/opt/bufferline.nvim/lua/bufferline/ui.lua:158: in function 'refresh'
        ...k/packer/opt/bufferline.nvim/lua/bufferline/commands.lua:76: in function <...k/packer/opt/bufferline.nvim/lua/bufferline/commands.lua:74>
```

I said similar because the above exact error appears in one specific file, but in another files the same error (`E15: Invalid expression...`) appears with another piece of my own code.

### LunarVim version

master-f1b2c5f

### Neovim version (>= 0.8.0)

0.8.0-1210-gd367ed9b2

### Operating system/version

Pop_OS! 22.04

## LvimInfo
```console

Buffer info
* filetype:                
* bufnr:                   9
* treesitter status:       inactive

Active client(s)
* name:                      elixirls
* id:                        1
* supported filetype(s):     [elixir, eelixir, heex, surface]
* attached buffers:          [5, 6, 7]
* root_dir pattern:          [5, 6, 7]
* capabilities:              documentFormattingProvider | workspaceSymbolProvider | implementationProvider
                             hoverProvider              | foldingRangeProvider    | definitionProvider
                             documentSymbolProvider     | macroExpansion          | referencesProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

## LspInfo
```console
 Language client log: /home/lambda3/.local/state/nvim/lsp.log
 Detected filetype:   
 
 0 client(s) attached to this buffer: 
 
 1 active client(s) not attached to this buffer: 
 
 Client: elixirls (id: 1, pid: nil, bufnr: [5, 6, 7])
 	filetypes:       elixir, eelixir, heex, surface
 	autostart:       true
 	root directory:  /home/lambda3/Repositories/dm_bank
 	cmd:             elixir-ls
 
 Configured servers list: tailwindcss, elixirls
```

### Screenshots

![image](https://user-images.githubusercontent.com/62157839/198746259-0b75841a-b5b5-45d4-89a2-17ee3faaa7c0.png)

**Comment by LostNeophyte** [comment]
#3305 looks related. Does disabling breadcrumbs fix it?
`lvim.builtin.breadcrumbs.active = false`

**Comment by digzom** [comment]
> #3305 looks related. Does disabling breadcrumbs fix it? `lvim.builtin.breadcrumbs.active = false`

Yes, thank you. I saw this issue, but I didn't understand that it's the same thing. Sorry for that.

Should I close the issue?

**Comment by LostNeophyte** [comment]
> Yes, thank you. I saw this issue, but I didn't understand that it's the same thing. Sorry for that.
> 
> Should I close the issue?

I'm not quite sure if they are the same but they may be so don't close it for now unless `lvim.builtin.breadcrumbs.active = false` fixes it

**Comment by digzom** [comment]
It worked! Thank you. I will close the issue.

**Comment by LostNeophyte** [comment]
@digzom You will be able to enable breadcrumbs again when #3364 is merged
