### ISSUE TITLE
Telescope and terminal always open in home directory

### ISSUE THREAD

**Issue by Heroiu-Justinian** [LunarVim/LunarVim#3362]
Everytime I try to use the file finder or the terminal, they both open in the home directory of my computer.

I have "solved" the problem by commenting 3 lines in ~/.config/lvim/plugin/packer_compiled.lua :

```
-- Config for: project.nvim
time([[Config for project.nvim]], true)
try_loadstring("\27LJ\2\n?\0\0\3\0\3\0\0066\0\0\0'\2\1\0B\0\2\0029\0\2\0B\0\1\1K\0\1\0\nsetup\22lvim.core.project\frequire\0", "config", "project.nvim")
time([[Config for project.nvim]], false)
```

I suppose project.nvim is either misconfigured or I don't know how to use it.

**Comment by kobzar** [comment]
I am use stable branch - terminal is opened with working dir path
Maybe you have some presets in your shell config?

**Comment by LostNeophyte** [comment]
Does setting `lvim.builtin.project.manual_mode = true` fix it?

**Comment by Heroiu-Justinian** [comment]
apparently it does make the problem go away ( and I don't have to deal with
the weird behavior I get when I comment out the configuration for
projectt.nvim in packer_compiled.lua.
Thanks a lot.
Why does it do this, though?

**Comment by LostNeophyte** [comment]
> apparently it does make the problem go away ( and I don't have to deal with the weird behavior I get when I comment out the configuration for projectt.nvim in packer_compiled.lua. Thanks a lot. Why does it do this, though?

maybe you have one of these files in your home `{ ".git", "_darcs", ".hg", ".bzr", ".svn", "Makefile", "package.json", "pom.xml" }`

**Comment by mcmoodoo** [comment]
> > apparently it does make the problem go away ( and I don't have to deal with the weird behavior I get when I comment out the configuration for projectt.nvim in packer_compiled.lua. Thanks a lot. Why does it do this, though?
> 
> maybe you have one of these files in your home `{ ".git", "_darcs", ".hg", ".bzr", ".svn", "Makefile", "package.json", "pom.xml" }`

I had `package.json` yeah for some reason ...

But I still can't wrap my head around it: what does package.json in my home dir have to do with this??))

Thanks BTW. Fixed my issue
