### ISSUE TITLE
ltex-ls LPS installed but not starting

### ISSUE THREAD

**Issue by alex-schulster** [LunarVim/LunarVim#3365]
### Problem description

I want to use the `ltex-ls` for grammar / spell checking on latex, markdown and text files.
I successfully installed the server as shown below :
![image](https://user-images.githubusercontent.com/40316586/198846546-f5f9f427-19fb-4405-a8f9-4c0fe0c2d1c7.png)

The problem now is that the server does not start when opening a `.md` or `.tex` file in a buffer. Only the `texlab` server gets attached :
![image](https://user-images.githubusercontent.com/40316586/198846582-58c5edbf-89e0-4b16-8e9b-cac63d3eb625.png)

I can't seem to find how to get it working. Any idea ?

### LunarVim version

master-b190f04

### Neovim version (>= 0.8.0)

NVIM 0.8.0

### Operating system/version

macOS Ventura 13.0 (22A380)

### Affected language servers

ltex-ls

### Steps to reproduce

1. Install `ltex-ls` server from the LSP info pane ;
2. Open a `.tex` or `.md` file ;

### Actual behavior

The `ltex-ls` server is not started.

### Expected behavior

The `ltex-ls` server should be running.

### support info

```console
:LspInfo
 Language client log: /Users/alex/.local/state/nvim/lsp.log
 Detected filetype:   tex
 
 1 client(s) attached to this buffer: 
 
 Client: texlab (id: 1, pid: nil, bufnr: [7])
 	filetypes:       tex, plaintex, bib
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             texlab
 
 Configured servers list: texlab
```

```console
:Lviminfo
Buffer info
* filetype:                tex
* bufnr:                   7
* treesitter status:       inactive

Active client(s)
* name:                      texlab
* id:                        1
* supported filetype(s):     [tex, plaintex, bib]
* attached buffers:          7
* root_dir pattern:          7
* capabilities:              foldingRangeProvider | documentSymbolProvider     | definitionProvider
                             inlayHintProvider    | workspaceSymbolProvider    | hoverProvider
                             referencesProvider   | documentFormattingProvider | documentHighlightProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: latexindent

Linters info
* Active: 
* Supported: [chktex, proselint, vale]

Code actions info
* Active: 
```

**Comment by LostNeophyte** [comment]
Itex is in the default skipped list as you can see in Lviminfo.
To remove it from the skipped list: [link](https://github.com/LunarVim/LunarVim/blob/b190f045e896fe5f1646e0807ab0bea008ee8950/utils/installer/config.example.lua#L115-L119)

**Comment by alex-schulster** [comment]
Thanks! Indeed `ltex` is now activated.
However I get an error when loading a file that uses the `ltex` server.
A message saying `Client 1 quit with exit code 1 and signal 0` is displayed under the command line and the server does not work.
![image](https://user-images.githubusercontent.com/40316586/198926211-d08f1c56-cff4-4c8e-8a2c-3932a86f590f.png)
I can' t seem to find the logs for LSP to see what is actually happening, the `~/.cache/lvim/` directory does not contain such a file. Any idea where I can find the file to share its content?

**Comment by LostNeophyte** [comment]
You can view the logs by pressing `Leader L l L` (not sure about the capitalization and I'm currently on my phone

**Comment by LostNeophyte** [comment]
For the root detection by default it needs a git repo

**Comment by LostNeophyte** [comment]
> this version of the Java Runtime only recognizes class file versions up to 52

you may need to update java

**Comment by alex-schulster** [comment]
> you may need to update java

Indeed I should have paid more attention to this. I used the first Java download link available on Google which is for JRE version 8... **[Downloading JDK version 17](https://www.oracle.com/ca-en/java/technologies/downloads/#java17) (current LTS version) solved the problem**.

It is now enabled and working. Thank you so much for your help!
![image](https://user-images.githubusercontent.com/40316586/198998762-b9b86742-4237-4999-ac8f-7cce05948598.png)

**Comment by tusharhero** [comment]
I am still having this issue.
```
-- ---configure a server manually. IMPORTANT: Requires `:LvimCacheReset` to take effect
-- ---see the full default list `:lua =lvim.lsp.automatic_configuration.skipped_servers`
vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "ltex-ls" })
local opts = {} -- check the lspconfig documentation for a list of all possible options
require("lvim.lsp.manager").setup("marksman", opts)
require("lvim.lsp.manager").setup("ltex-ls", opts)
```
But its still not getting activated
