### ISSUE TITLE
bufferline.options.mode = "tabs" throws an error

### ISSUE THREAD

**Issue by NoamMuallem** [LunarVim/LunarVim#3367]
### Problem description

I get an error when settings up bufferline for tabs

### LunarVim version

:LvimVersion does not works

### Neovim version (>= 0.8.0)

v0.8.0-29-g47454d001

### Operating system/version

macos 12.3.1

### Steps to reproduce

in the config, add: lvim.builtin.bufferline.options.mode = "tabs"
then close and every time you open lvim, there is an error

### support info

none

### Screenshots

![Screen Shot 2022-10-30 at 12 08 22](https://user-images.githubusercontent.com/40291455/198863526-9be22825-200e-43ff-b98b-221987c49ff9.png)

**Comment by LostNeophyte** [comment]
Are you sure this is the line that causes the error? I can't reproduce. Are you on rolling or master?

**Comment by kobzar** [comment]
the same for me (master) working without errors.

**Comment by kobzar** [comment]
Closed as inactive.
Please reopen the issue if trouble is still present

**Comment by chalop** [comment]
I am having this error as well. Please let me know how can I help to troubleshoot the issue.

**Comment by LostNeophyte** [comment]
and it is caused by `bufferline.options.mode = "tabs"` ?


Nov 14, 2022, 18:47 by ***@***.***:

**Comment by chalop** [comment]
Yes, setting it back to "buffers" works without issues.

**Comment by chalop** [comment]
Just in case, I edited my original comment with more info.

**Comment by LostNeophyte** [comment]
what's your `:LvimVersion`?


Nov 14, 2022, 18:50 by ***@***.***:

**Comment by chalop** [comment]
Lvimversion is ```release-1.2/neovim-0.8-c1d4f5e```

**Comment by LostNeophyte** [comment]
alright, reproduced

**Comment by LostNeophyte** [comment]
@chalop does this fix it? if so I'll make a PR
```lua
local function is_ft(b, ft)
  return vim.bo[b].filetype == ft
end

lvim.builtin.bufferline.options.mode = "tabs"
local function custom_filter(buf, buf_nums)
  local logs = vim.tbl_filter(function(b)
    return is_ft(b, "log")
  end, buf_nums or {})
  if vim.tbl_isempty(logs) then
    return true
  end
  local tab_num = vim.fn.tabpagenr()
  local last_tab = vim.fn.tabpagenr "$"
  local is_log = is_ft(buf, "log")
  if last_tab == 1 then
    return true
  end
  -- only show log buffers in secondary tabs
  return (tab_num == last_tab and is_log) or (tab_num ~= last_tab and not is_log)
end

lvim.builtin.bufferline.options.custom_filter = custom_filter
```

**Comment by chalop** [comment]
It works! Thank you very much

**Comment by aemonge** [comment]
Works for me too :heart: !!!!

**Comment by aemonge** [comment]
Though this is now working, the sorting of the tabs isn't right. It would be wonderful to have this fixed too, since it's a bit confusing.

:bow: thanks in advance

**Comment by LostNeophyte** [comment]
can you show an example of the actual and expected order? (and a screenshot would be useful)

**Comment by aemonge** [comment]
![image](https://user-images.githubusercontent.com/1322348/206178342-e2cecb9e-ccd6-4a68-881e-b293e93489a2.png)

**Comment by LostNeophyte** [comment]
try `lvim.builtin.bufferline.options.sort_by = "tabs"`

**Comment by aemonge** [comment]
:champagne: That did the trick !
