### ISSUE TITLE
Feat: add borders to LSP hover

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#3382]
I can't seem to figure out how to add them

**Comment by cpea2506** [comment]
We've already had it 

https://github.com/LunarVim/LunarVim/blob/eabf6c6990cb7ac9416b1733cf59c36c85f50777/lua/lvim/lsp/handlers.lua#L15

**Comment by ChristianChiarulli** [comment]
I have no idea why this doesn't work for me, not matter what colorscheme I try

**Comment by ChristianChiarulli** [comment]
ok it was noice and nui
