### ISSUE TITLE
Feature: Segregate buffers with tabs

### ISSUE THREAD

**Issue by riza-khan** [LunarVim/LunarVim#3387]
### Feature Description

I really like the project feature in LunarVim where I can bounce between projects within the same instance. 

I really like the idea of using this with tabs. So on one tab it's Project A related buffers, and on tab B it's Project B related buffers.

The issue is, switching between tabs doesn't hide buffers (and you can still switch to them). Is it possible to have tabs be the 'owners' of buffers?

**Comment by LostNeophyte** [comment]
If you mean buffers in bufferline then you can probably override the filter function to do that

**Comment by LostNeophyte** [comment]
https://github.com/akinsho/bufferline.nvim/issues/494

**Comment by riza-khan** [comment]
Thank you @LostNeophyte .
