### ISSUE TITLE
docs for how to customize color scheme?

### ISSUE THREAD

**Issue by ipsod** [LunarVim/LunarVim#3388]
### Feature Description

I just want to change the window separator color, but I've been messing with it for 30+ minutes and I still don't have a solution that works consistently.

**Comment by LostNeophyte** [comment]
example:
```lua
lvim.autocommands = {
  {
    { "ColorScheme" },
    {
      pattern = "*",
      callback = function()
        vim.api.nvim_set_hl(0, "hlgroup", { bg = "#ffffff", underline = false, bold = true })
      end,
    },
  },
}
```

**Comment by ChristianChiarulli** [comment]
We should document this on the site we could also write a wrapper API around it

**Comment by LostNeophyte** [comment]
> We should document this on the site we could also write a wrapper API around it

something like `lvim.builtin.theme.on_done` callback or  
```lua
lvim.builtin.theme.<name>.highlight_overrides = { 
  <group_name> = { bg = "#ffffff", underline = false, ... },
 ... 
}
 ```

**Comment by danielo515** [comment]
Why it needs to be set on an auto command?

**Comment by LostNeophyte** [comment]
> Why it needs to be set on an auto command?

the colorcheme is loaded after the config is loaded, so the highlights set in the config are discarded

**Comment by danielo515** [comment]
That explains why I was never able to set certain colors of the UI in the
past :P
Is that autocommand lvim specific? Or is general neovim?

**Comment by LostNeophyte** [comment]
> That explains why I was never able to set certain colors of the UI in the past :P Is that autocommand lvim specific? Or is general neovim? 

it's from neovim `:help ColorScheme`

**Comment by danielo515** [comment]
All this years using neovim and still don't know if full yet. Thanks
