### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by Vagab** [LunarVim/LunarVim#3391]
### Problem description

MacPro 2020 M1 Monterey 12.0.1

Steps to reproduce:
1. Install fresh lunarvim
2. Go to configuration
3. Press `:w` swiftly about 10 times
4. See the unrecoverable error
> Error executing vim.schedule lua callback: ...seek/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:172: attempt to call field 'setup' (a nil value)

I would expect that didn't happen.

### LunarVim version

master-375232c

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

macOS Monterey 12.0.1

### support info

`LspInfo`
```console
Language client log: /Users/barseek/.local/state/nvim/lsp.log
Detected filetype:   lua
1 client(s) attached to this buffer:
Client: sumneko_lua (id: 1, pid: nil, bufnr: [3])
filetypes:       lua
autostart:       true
root directory:  Running in single file mode.

cmd:             lua-language-server
Configured servers list: sumneko_lua
```

`LvimInfo`
```console
Error executing Lua callback: ...arseek/.local/share/lunarvim/lvim/lua/lvim/impatient.lua:297: cannot open /Users/barseek/.local/share/lunarvim/lvim/lua/lvim/core/info.lua: Too m
any open files
stack traceback:
        [C]: in function 'error'
        ...arseek/.local/share/lunarvim/lvim/lua/lvim/impatient.lua:297: in function <...arseek/.local/share/lunarvim/lvim/lua/lvim/impatient.lua:288>
        [C]: in function 'require'
        ...ek/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:29: in function <...ek/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:
```

**Comment by LostNeophyte** [comment]
actually if I do `:w` a couple times fast I do get the error. But no in `normal` speed

**Comment by Vagab** [comment]
@LostNeophyte ye, normal speed doesn't do much damage. But my OCD made me press `:w` about 4 times in a second which broke stuff.
About corrupting, yes, that is what I meant by unrecoverable, but that's a poor wording on my end, sorry.

**Comment by LostNeophyte** [comment]
> @LostNeophyte ye, normal speed doesn't do much damage. But my OCD made me press `:w` about 4 times in a second which broke stuff. About corrupting, yes, that is what I meant by unrecoverable, but that's a poor wording on my end, sorry.

In that case case, I recommend disabling automatic reload on save like this: `lua lvim.reload_config_on_save = false`
