### ISSUE TITLE
Dashboard missing

### ISSUE THREAD

**Issue by Asthestarsfalll** [LunarVim/LunarVim#3404]
### Problem description

After I set transparent window， the dashboard disappeared when I enter lvim again
![image](https://user-images.githubusercontent.com/72954905/199648855-1eb17e76-4666-44fb-87cd-5f7da12559d0.png)
I try to set transparent window back, but it doesn't work.
![image](https://user-images.githubusercontent.com/72954905/199649323-7e91ce0e-8f25-47ab-9a89-09abed8d6bed.png)

### LunarVim version

lateset

### Neovim version (>= 0.8.0)

0.8.0

### Operating system/version

5.9.16-1-MANJARO

### Steps to reproduce
1. set transparent_window=true
2. quit vim
3. lvim

### support info

![image](https://user-images.githubusercontent.com/72954905/199649520-3759b020-4d65-441d-a3ed-c65c210221fd.png)

**Comment by ChristianChiarulli** [comment]
Can you try updating and making sure to `:LvimCacheReset`

**Comment by Asthestarsfalll** [comment]
@ChristianChiarulli 
That works! Thank you!
