### ISSUE TITLE
Please don't change my workflow

### ISSUE THREAD

**Issue by sefricke** [LunarVim/LunarVim#3405]
### Feature Description

I have been using LunarVim for quite a while now and recently I did an update, after the update I noticed that certain keymappings were changed, my file finder had no preview anymore, and in the buffer finder, I couldn't type anymore.
And so at that point, I had to start exploring how the plugins are actually called that I opened with previous key mappings, figure out how to change them, figure out how to get my preview window back ... but now the layout is different. etc.

I can understand that you want to evolve the tool, but just pulling the carpet under my feet and letting me recollect my setup afterward doesn't feel nice :(.
For example for the file finder with or without a preview window, I would rather like it if you provide an option to disable it or ask during a setup/update whether I want to use this new proposed change.
I started to use LunarVim because I didn't like the hassle of keeping track of each little plugin configuration and setting, if you break my setup you kind of force me to spend time with that again, which defeats the purpose of this tool me.

So, I would love it if you are a bit more careful when it comes to changes that can break user workflows.

Thanks for your work and sorry for the rant.
Sebastian

**Comment by jakeperry** [comment]
@sefricke I had the same problem and found this commit to be the one that broke telescope for me.  If you remove the previewer = false, lines and relaunch with a PickerCompile the previews are back.

**Comment by LostNeophyte** [comment]
related: https://github.com/LunarVim/LunarVim/discussions/3328

**Comment by LostNeophyte** [comment]
https://github.com/LunarVim/LunarVim/issues/3351#issuecomment-1295331841 to show the preview in telescope

**Comment by danielo515** [comment]
I recommend you give this feedback in the linked discussion

**Comment by meicale** [comment]
Stick to some pined version may help, and do not need to update at all if you do not want change anything.

**Comment by danielo515** [comment]
Except for bug fixes and new features. Lunar vim is very extensible, and
you may not need to change anything and just extend it, but there are
certain core things that need to be changed from the core.
Also, I don't understand why is not possible to just add new things without
doing breaking changes, specially those that are not adding nor fixing
anything, just changing default configurations to something else.

**Comment by LostNeophyte** [comment]
Closing to keep everything in one place(the discussion linked above)
