### ISSUE TITLE
Telescope make pickers more easily configurable

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#3406]

**Comment by LostNeophyte** [comment]
If someone finds this issue and wants to enable the preview, you can do this:
`lvim.builtin.telescope.pickers.find_files.previewer = nil `
If you want to configure more options, do this:
```lua
lvim.builtin.telescope = {
  active = true,
  defaults = {
    layout_strategy = "horizontal",
  },
  pickers = {
    git_files = {
      hidden = true,
    },
    live_grep = {
      hidden = true,
    },
  },
}
```

**Comment by sjzh-null** [comment]
I was going through the documentation the other day and found out that you can actually edit pretty much all the telescope layouts individually by making object calls. Funnily enough I found the documentation for the layout objects using telescope live_grep XD

In my config file I have put the following and everyone is welcomed to copy and paste or pick and choose as they see fit. 
For a more detailed explanation on how to edit the layout_* objects you can **consult** the **telescope.txt** file which can be found in your local installation of lunarvim, which in my case is located in: 
~/.local/share/lunarvim/site/pack/packer/start/telescope.nvim/doc/telescope.txt

in my config.lua (~/.config/lvim/config.lua) I have the following: 
`
lvim.builtin.telescope.pickers.find_files = {
     layout_strategy = "center",
     layout_config = { width = 0.80, height = 0.80, preview_width = nil, prompt_position = "top" }
}

lvim.builtin.telescope.pickers.live_grep = {
    layout_config = { height = 0.99, width = 0.99, preview_cutoff = 120, preview_width = 0.6, prompt_position = "top" },
    layout_strategy = "horizontal"
}

lvim.builtin.telescope.pickers.git_commits = {
    layout_strategy = "horizontal",
    layout_config = { height = 0.88, width = 0.88, preview_cutoff = 20, preview_width = 0.70, prompt_position = "bottom" }
}

lvim.builtin.telescope.pickers.man_pages = {
    layout_strategy = "horizontal",
    layout_config = { height = 0.99, width = 0.99, preview_cutoff = nil, preview_width = 0.80, prompt_position = "bottom" }
}

lvim.builtin.telescope.pickers.vim_options = { layout_config = { height = 0.66, width = 0.66 } }

lvim.builtin.telescope.pickers.colorscheme = { layout_strategy = "cursor", layout_config = { width = 0.19 } }

`

**Comment by khezerberg** [comment]
how does someone do this layout config with ivy please? 
sorry, I noob.

**Comment by LostNeophyte** [comment]
> how does someone do this layout config with ivy please? sorry, I noob.

what do you want do change? and what are you using to open a picker with ivy theme?

**Comment by LostNeophyte** [comment]
@ChristianChiarulli I think the pickers aren't that hard to configure, maybe what we need is some documentation, unless you have an idea of what can be done to make it easier, I couldn't come up with anything other than this:

https://github.com/LunarVim/LunarVim/blob/6132a30dff8808d4c9f0dc046daf2991f58adf1e/lua/lvim/core/telescope.lua#L125 ^this^ line is unnecessary(it literally does nothing) and makes the config harder to understand. If we remove it then we can get rid of the `get_pickers` function and put the pickers config directly [here](https://github.com/LunarVim/LunarVim/blob/6132a30dff8808d4c9f0dc046daf2991f58adf1e/lua/lvim/core/telescope.lua#L134)

if we also merge
https://github.com/LunarVim/LunarVim/blob/19b6e8742f33304999a92275d4f6163810fce528/lua/lvim/core/telescope.lua#L64-L68 with
https://github.com/LunarVim/LunarVim/blob/19b6e8742f33304999a92275d4f6163810fce528/lua/lvim/core/telescope.lua#L74 

then we'll be able to get rid of tbl_extend and completion will work with `lvim.builtin.telescope.pickers` which will make configuring easier in my opinon. 

to change and configure `flex` layout for all pickers all I had to do was this:
```lua
lvim.builtin.telescope.defaults.layout_strategy = "flex"
lvim.builtin.telescope.defaults.layout_config = {
  height = 0.8,
  width = 0.8,
  horizontal = {
    preview_cutoff = 120,
    preview_width = 0.6,
  },
  vertical = {
    preview_cutoff = 40,
  },
  flex = {
    flip_columns = 150,
  },
}

for key, _ in pairs(lvim.builtin.telescope.pickers) do
  lvim.builtin.telescope.pickers[key].previewer = nil
  lvim.builtin.telescope.pickers[key].theme = nil
end
``` 

It maybe isn't easy, but it isn't hard either. I think the hard part comes from telescope itself (for example to enable preview you need to set `previewer` to nil and not true, it's not intuitive)

Let me know what you think

If anyone has any ideas/suggestions please let me know. And if you disagree please tell me why and what is the hard part in the configuration

**Comment by khezerberg** [comment]
> > how does someone do this layout config with ivy please? sorry, I noob.
> 
> what do you want do change? and what are you using to open a picker with ivy theme?

I configured it by reading the telescope documentation. xd sorry. I forgot rule #1 of open source. RTFM.

**Comment by hawkinchina** [comment]
very nice. make picker more easily configurable.
