### ISSUE TITLE
Invalid configuration: vim/keymap.lua

### ISSUE THREAD

**Issue by Asthestarsfalll** [LunarVim/LunarVim#3407]
### Problem description

Everytime when I saving the config.lua file, it will warn that no such file "init.lua'.
I have tryed to update lvim and reset cache, but they don't work.
I am a rookie with vim and lua, so I have no idea where is vim/keymap.lua and how to sovle this.
Thank you in advance for you help!
```bash
[WARN ] lvim: "Invalid configuration: vim/keymap.lua:0: E31: No such mapping" file="init.lua", line=129
```

### LunarVim version

lateset

### Neovim version (>= 0.8.0)

0.8.0

### Operating system/version

5.9.16-1-MANJARO

### support info

None

**Comment by Asthestarsfalll** [comment]
I found that this issue caused by the following config:
```lua
vim.keymap.del("n", "<C-Up>")
```

btw, how can I copy codes from lvim to system clipboard? I found that I can only paste to lvim.I have set config:
```lua
vim.opt.clipboard = "unnamedplus"
```

**Comment by LostNeophyte** [comment]
On Linux if you're using xorg leave the clipboard setting at default and install xclip

**Comment by LostNeophyte** [comment]
To delete a keymap set by lunarvim use the lvim way from [the docs](https://www.lunarvim.org/docs/configuration/keybindings) and set it to nil

**Comment by Asthestarsfalll** [comment]
Thank you!
