### ISSUE TITLE
How to add prettier in lunarvim

### ISSUE THREAD

**Issue by PratamaRizki22** [LunarVim/LunarVim#3410]
### Problem description

I add prettier but file can't to formatted

### LunarVim version

master-c477b9f

### Neovim version (>= 0.8.0)

0.8.0

### Operating system/version

Wsl ubuntu

### support info

![image](https://user-images.githubusercontent.com/96802430/199838517-08d1e75a-f12a-4c28-b848-7babea68aade.png)

### Screenshots

![image](https://user-images.githubusercontent.com/96802430/199838263-e14627ee-bdd0-462f-ad70-542fab5d81fe.png)
![image](https://user-images.githubusercontent.com/96802430/199838303-95cbb32a-dfce-4957-819a-f49571b22b6f.png)

**Comment by ChristianChiarulli** [comment]
you don't need the plugin prettier, also did you install prettier with mason?

**Comment by PratamaRizki22** [comment]
when i add this, masson auto download

**Comment by LostNeophyte** [comment]
> when i add this, masson auto download

If you mean the plugin, then it's not mason but packer

**Comment by morpheuslord** [comment]
where can i add additional plugins in lunarvim can you share the filename and location

**Comment by LostNeophyte** [comment]
> where can i add additional plugins in lunarvim can you share the filename and location

[it's in the docs](https://www.lunarvim.org/docs/plugins#user-plugins)

**Comment by morpheuslord** [comment]
> > where can i add additional plugins in lunarvim can you share the filename and location
> 
> [it's in the docs](https://www.lunarvim.org/docs/plugins#user-plugins)

thanks man
