### ISSUE TITLE
how to open a Vertical Terminal ? what <M-2> mean?

### ISSUE THREAD

**Issue by DeyunLuo** [LunarVim/LunarVim#3412]
<img width="912" alt="WeChatWorkScreenshot_74ab02d8-f446-44b9-95b0-d7a393928456" src="https://user-images.githubusercontent.com/32233191/199878855-c7e3ae6e-3aef-4888-bd45-c98bad5aaf9a.png">

**Comment by DeyunLuo** [comment]
sorry, I use Mac, only fn+option+1 to open the terminal....

**Comment by ErlanRG** [comment]
The equivalent in Linux is <Alt-2>. In think it would be <Option-2> on Mac if I am not mistaken.

**Comment by LostNeophyte** [comment]
On Mac it will be option-2
