### ISSUE TITLE
Spawning language server with cmd: rust-analyzer failed in Windows

### ISSUE THREAD

**Issue by longguzzz** [LunarVim/LunarVim#3413]
### Problem description

I have installed the server. But lvim still prompts "Spawning language server with cmd: rust-analyzer failed. The language server is either not installed, missing from PATH, or not executable."
More details are here: https://github.com/LunarVim/LunarVim/discussions/3396

### LunarVim version

rolling-7d57046

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Windows11 22622.290

### Affected language servers

rust-analyzer

### Steps to reproduce

More details are here: https://github.com/LunarVim/LunarVim/discussions/3396

### Actual behavior

When opening *.rs file, lvim prompts "Spawning language server with cmd: rust-analyzer failed. The language server is either not installed, missing from PATH, or not executable."

### support info

```console
:LspInfo
 Language client log: C:\Users\longguzzz\AppData\Local\nvim-data\lsp.log
 Detected filetype:   rust
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: rust
 
 Config: rust_analyzer
 	filetypes:         rust
 	root directory:    D:\hello
 	cmd:               rust-analyzer
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   experimental/serverStatus
 
 Configured servers list: rust_analyzer
```
```console
:LvimInfo
Buffer info
* filetype:                rust
* bufnr:                   10
* treesitter status:       active

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels, rust_analyzer]

Formatters info
* Active: 
* Supported: [dprint, rustfmt]

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

**Comment by LostNeophyte** [comment]
You can try the latest installer, it should install master now

**Comment by longguzzz** [comment]
It still doesn't work in Windows.
`:lua print(vim.fn.executable("rust-analyzer"))` print 1
![image](https://user-images.githubusercontent.com/96779663/207181606-29f70784-2bca-400e-b7b7-edfdd48947df.png)
![image](https://user-images.githubusercontent.com/96779663/207181662-df5e9e6c-1200-4309-8b92-f98e394ff92e.png)
![image](https://user-images.githubusercontent.com/96779663/207181714-945f422c-7ad9-4e32-aea2-f2336233fa0f.png)
![image](https://user-images.githubusercontent.com/96779663/207182256-f74c5661-9bba-4b47-a684-f49a17c8383e.png)

**Comment by LostNeophyte** [comment]
Paste here last retirement lines from the log `leader L l L`

**Comment by fgimian** [comment]
I sadly have this issue too and it is 100% reproducible here (I've tried multiple times with fresh setups and even with a setup where I just clone this repo into the regular `nvim` directory).

I can definitely see the `rust-analyzer` binary has been installed as shown below:

```
~\AppData\Local\nvim-data
🕙 [ 08:09:59 PM ] ❯ dir -r rust-analyzer.exe

    Directory: C:\Users\Fots\AppData\Local\nvim-data\mason\packages\rust-analyzer

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           3/01/2023  7:52 PM       28832768 rust-analyzer.exe


~\AppData\Local\nvim-data
🕙 [ 08:10:05 PM ] ❯ dir -r rust-analyzer.cmd

    Directory: C:\Users\Fots\AppData\Local\nvim-data\mason\bin

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           3/01/2023  7:52 PM            196 rust-analyzer.cmd

```

Unfortunately the LSP log is completely empty.

Any help would be greatly appreciated!
Fotis

**Comment by LostNeophyte** [comment]
> I sadly have this issue too and it is 100% reproducible here (I've tried multiple times with fresh setups and even with a setup where I just clone this repo into the regular `nvim` directory).
> 
> I can definitely see the `rust-analyzer` binary has been installed as shown below:
> 
> ```
> ~\AppData\Local\nvim-data
> 🕙 [ 08:09:59 PM ] ❯ dir -r rust-analyzer.exe
> 
>     Directory: C:\Users\Fots\AppData\Local\nvim-data\mason\packages\rust-analyzer
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> -a---           3/01/2023  7:52 PM       28832768 rust-analyzer.exe
> 
> 
> ~\AppData\Local\nvim-data
> 🕙 [ 08:10:05 PM ] ❯ dir -r rust-analyzer.cmd
> 
>     Directory: C:\Users\Fots\AppData\Local\nvim-data\mason\bin
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> -a---           3/01/2023  7:52 PM            196 rust-analyzer.cmd
> ```
> 
> Unfortunately the LSP log is completely empty.
> 
> Any help would be greatly appreciated! Fotis

What's the output of :LspInfo in a rust file?

**Comment by fgimian** [comment]
> What's the output of :LspInfo in a rust file?

Thanks for the reply, here's what I'm seeing:

```
 Use [q] or [Esc] to quit the window
 
 Language client log: C:\Users\Fots\AppData\Local\nvim-data\lsp.log
 Detected filetype:   rust
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: rust
 
 Config: rust_analyzer
 	filetypes:         rust
 	root directory:    C:/Users/Fots/source/rust/native-instruments-downloads.rs
 	cmd:               rust-analyzer
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: rust_analyzer
```

**Comment by fgimian** [comment]
> > I sadly have this issue too and it is 100% reproducible here (I've tried multiple times with fresh setups and even with a setup where I just clone this repo into the regular `nvim` directory).
> > I can definitely see the `rust-analyzer` binary has been installed as shown below:
> > ```
> > ~\AppData\Local\nvim-data
> > 🕙 [ 08:09:59 PM ] ❯ dir -r rust-analyzer.exe
> > 
> >     Directory: C:\Users\Fots\AppData\Local\nvim-data\mason\packages\rust-analyzer
> > 
> > Mode                 LastWriteTime         Length Name
> > ----                 -------------         ------ ----
> > -a---           3/01/2023  7:52 PM       28832768 rust-analyzer.exe
> > 
> > 
> > ~\AppData\Local\nvim-data
> > 🕙 [ 08:10:05 PM ] ❯ dir -r rust-analyzer.cmd
> > 
> >     Directory: C:\Users\Fots\AppData\Local\nvim-data\mason\bin
> > 
> > Mode                 LastWriteTime         Length Name
> > ----                 -------------         ------ ----
> > -a---           3/01/2023  7:52 PM            196 rust-analyzer.cmd
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Unfortunately the LSP log is completely empty.
> > Any help would be greatly appreciated! Fotis
> 
> What's the output of :LspInfo in a rust file?



> > What's the output of :LspInfo in a rust file?
> 
> Thanks for the reply, here's what I'm seeing:
> 
> ```
>  Use [q] or [Esc] to quit the window
>  
>  Language client log: C:\Users\Fots\AppData\Local\nvim-data\lsp.log
>  Detected filetype:   rust
>  
>  0 client(s) attached to this buffer: 
>  
>  Other clients that match the filetype: rust
>  
>  Config: rust_analyzer
>  	filetypes:         rust
>  	root directory:    C:/Users/Fots/source/rust/native-instruments-downloads.rs
>  	cmd:               rust-analyzer
>  	cmd is executable: true
>  	autostart:         true
>  	custom handlers:   
>  
>  Configured servers list: rust_analyzer
> ```

P.S.: The exact instructions work correctly inside WSL so it definitely seems to be a Windows-specific issue.

**Comment by LostNeophyte** [comment]
any errors in `:messages`? also see the lsp log using `leader L l L`

**Comment by fgimian** [comment]
> any errors in `:messages`? also see the lsp log using `leader L l L`

`:messages` shows the same error about not finding the binary:

```
Spawning language server with cmd: `rust-analyzer` failed. The language server is either not installed, missing from PATH, or not executable.
```

Using `<leader> L l L` just shows an empty **lsp.log** file I'm afraid (that's the empty log I was referring to above).

I honestly am finding it a bit hard to understand the LunarVim codebase to troubleshoot this.

**Comment by LostNeophyte** [comment]
I might know that's the cause, what's your `:LvimVersion` ?

**Comment by fgimian** [comment]
> I might know that's the cause, what's your `:LvimVersion` ?

Oh cool, I'm on `master-9bc82e4` right now (i.e. the latest commit), although I did have the same issue with stable too.

**Comment by LostNeophyte** [comment]
if you delete these lines, will it work? https://github.com/LunarVim/LunarVim/blob/9bc82e4e684aa548eb0765734ec4e83f16c78b4c/lua/lvim/lsp/manager.lua#L75-L84

**Comment by fgimian** [comment]
> if you delete these lines, will it work?
> 
> https://github.com/LunarVim/LunarVim/blob/9bc82e4e684aa548eb0765734ec4e83f16c78b4c/lua/lvim/lsp/manager.lua#L75-L84

I'm afraid that didn't solve the problem, it is definitely happening during the setup line at https://github.com/LunarVim/LunarVim/blob/9bc82e4e684aa548eb0765734ec4e83f16c78b4c/lua/lvim/lsp/manager.lua#L85 based on my testing just now.

**Comment by LostNeophyte** [comment]
In that case it may be our mason bootstrap (but then other servers wouldn't work either I think), I'll troubleshoot this when I have free time / I'll finish the [lazy refactor](https://github.com/LunarVim/LunarVim/pull/3647)

**Comment by fgimian** [comment]
> In that case it may be our mason bootstrap (but then other servers wouldn't work either I think), I'll troubleshoot this when I have free time / I'll finish the [lazy refactor](https://github.com/LunarVim/LunarVim/pull/3647)

Thanks heaps, I haven't tested any other LSP servers as I'm only currently developing Rust apps, but I'll continue troubleshooting here too.

Really appreciate all your help with this!! 😄

**Comment by fgimian** [comment]
I wonder if the issue is actually related to this https://github.com/neovim/nvim-lspconfig/issues/2032#issuecomment-1200413852

I experienced the same problem with NvChad and an issue on their GitHub page links to this comment which seems to make sense.

Hope this helps
Fotis

**Comment by sozyGithub** [comment]
Don't forget to add the executable on the system env variables.
