### ISSUE TITLE
Calling lsp setup no longer works from within config.lua

### ISSUE THREAD

**Issue by dzonatan** [LunarVim/LunarVim#3415]
### Problem description

```lua
require("lvim.lsp.manager").setup('...')
```
has no effect inside `config.lua`, does not even matter which language server (e.g. `emmet_ls`, `angularls`).
Calling the same setup through command `:lua ...` works normally.
No errors in the logs.

Seems like #3390 somehow broke this. Before this change everything works.

### LunarVim version

master-1eb4188

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

macOS 12.6

### support info

probably irrellevant

**Comment by LostNeophyte** [comment]
does `:lua print(vim.fn.executable("server_excecutalbe_name"))` print 1?

**Comment by LostNeophyte** [comment]
can you share the full code snippet, will check it on my machine, and you did add the servers you configure manually to the skipped list and run `:LvimCacheReset` afterwards?

**Comment by dzonatan** [comment]
> does :lua print(vim.fn.executable("server_excecutalbe_name")) print 1?

it prints `0`

> can you share the full code snippet, will check it on my machine

This is all that's needed to reproduce:
```lua
require('lvim.lsp.manager').setup('emmet_ls')
```

> and you did add the servers you configure manually to the skipped list and run `:LvimCacheReset` afterwards?

seems like it does not make any difference if I add it or not to the skipped list w/ running `:LvimCacheReset`.

**Comment by LostNeophyte** [comment]
It looks like the server is not installed then

**Comment by tiberiuc** [comment]
I'm having the same problem, example snippet:

```
vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "tailwindcss" })
local tailwindcss_lsp_opts = {
  root_dir = function(fname)
    require("lspconfig.util").root_pattern("assets/tailwind.config.js", "tailwind.config.js",
      "tailwind.config.cjs", "tailwind.js",
      "tailwind.cjs")(fname)
  end,
  init_options = {
     userLanguages = { heex = "html", elixir = "html" }
  },
}

require("lvim.lsp.manager").setup("tailwindcss", tailwindcss_lsp_opts)
```

:lua print(vim.fn.executable("server_excecutalbe_name")) print 0

the server is installed but it is loaded with default config not the custom one

output of `:LspInfo`

```
 Config: tailwindcss
 	Refer to :h lspconfig-root-detection for help.
 	filetypes:         aspnetcorerazor, astro, astro-markdown, blade, django-html, htmldjango, edge, eelixir, elixir, ejs, erb, eruby, gohtml, haml, handlebars, hbs, html, html-eex, heex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte
 	root directory:    Not found. Searched for: root_pattern('tailwind.config.js', 'tailwind.config.ts', 'postcss.config.js', 'postcss.config.ts', 'package.json', 'node_modules', '.git').
 	cmd:               tailwindcss-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
```
you can see the root_pattern is not the one configured ( it should contain `assets/tailwind.conf.js` )

I did run `:LvimCacheReset`

**Comment by dzonatan** [comment]
it is installed 

![image](https://user-images.githubusercontent.com/5166666/200117215-20804e47-1e0d-45cc-976a-7034c2464316.png)

strangely, `0` gets printed in the "working" version (before this a6f0e2967d3b1c010401651c626c9bd1c537cdb4 chage).

![image](https://user-images.githubusercontent.com/5166666/200117177-24342bba-5a81-4d64-aa34-538c8b940861.png)

you can see `0` in the messeges, and `emmet_ls` being alive.

**Comment by LostNeophyte** [comment]
you run `:lua print(vim.fn.executable("emmet-ls"))`?

**Comment by LostNeophyte** [comment]
> I'm having the same problem, example snippet:
> :lua print(vim.fn.executable("server_excecutalbe_name")) print 0

Substitute server_excecutalbe_name for the actual name of the executable

**Comment by dzonatan** [comment]
ahhgr, I was using `emmet_ls` for the name. `emmet-ls` prints `1` in both versions (working and not).

**Comment by LostNeophyte** [comment]
it was working before that commit?

**Comment by tiberiuc** [comment]
@LostNeophyte btw I just had it on another computer with older version of Lvim ( rolling-ccd6d36) and it is working fine

**Comment by LostNeophyte** [comment]
Is at least one of you on discord?

**Comment by dzonatan** [comment]
> it was working before that commit?
 yup. the last screenshot is at `master-325bf72f` (just before the change).

**Comment by tiberiuc** [comment]
> Is at least one of you on discord?

I am

**Comment by LostNeophyte** [comment]
> > Is at least one of you on discord?
> 
> I am

ping me on lunarvim channel if you have time now, @dzonatan I'll troubleshoot it with @tiberiuc and get back to you

**Comment by LostNeophyte** [comment]
For anyone who finds this isssue: 
if you put `vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers...` in config.lua and `require("lvim.lsp.manager").setup...` in ftplugin/[filetype].lua it will work, or you can wrap `require("lvim.lsp.manager").setup` in a vim.schedule as a workaround. example:
```lua
vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "tailwindcss" })

vim.schedule(function ()
local tailwindcss_lsp_opts = {
  root_dir = function(fname)
    return require("lspconfig.util").root_pattern("assets/tailwind.config.js", "tailwind.config.js",
      "tailwind.config.cjs", "tailwind.js",
      "tailwind.cjs")(fname)
  end,
  init_options = {
     userLanguages = { heex = "html", elixir = "html" }
  },
}
require("lvim.lsp.manager").setup("tailwindcss", tailwindcss_lsp_opts)
end)
```

**Comment by LostNeophyte** [comment]
Fixed in https://github.com/LunarVim/LunarVim/commit/222a872dccea6c56783a3e3728d5bb4f5ab3447c

**Comment by ChristianChiarulli** [comment]
if there's a new way of doing this we should document it on the site, or just leave it here and I'll add it at some point

**Comment by LostNeophyte** [comment]
> if there's a new way of doing this we should document it on the site, or just leave it here and I'll add it at some point

The old one works now, no need to update the docs
