### ISSUE TITLE
No Line indentation on big amount of html attributes

### ISSUE THREAD

**Issue by felixpohlmann** [LunarVim/LunarVim#3417]
### Problem description

When having lots of attributes in an html tag, the line becomes pretty long. Is there any possibility to auto-indent (see picture) like vs-code does it?

Please have a look at the screenshots for better understanding.

Thanks for any help in advance!

### LunarVim version

master-1468aea

### Neovim version (>= 0.8.0)

v0.7.2

### Operating system/version

macOS 13.0

### Steps to reproduce

1. Either create a .tsx/.jsx or .html file
2. Create a tag with a big amount of attributes and values 
3. No indentation on formatting

### support info

![Screenshot 2022-11-04 at 14 49 05](https://user-images.githubusercontent.com/68960775/199988654-fbb705c7-0cf3-41bd-9f65-f358555dd7ca.png)
![Screenshot 2022-11-04 at 14 50 28](https://user-images.githubusercontent.com/68960775/199988666-82d9f044-dc87-4b26-8406-c6e6aa83244c.png)

### Screenshots

**For example, please have a look at the upper Pane-Tag!**

**FROM THIS:**
![from](https://user-images.githubusercontent.com/68960775/199988709-07853930-a8d9-4bd3-914d-b4da91f36e2b.png)

**TO THIS:**
![to](https://user-images.githubusercontent.com/68960775/199988738-4a26e4db-1110-470f-b975-fbb809195456.png)

**Comment by LostNeophyte** [comment]
that's formatting, there's probably an option in the formatter to do that

**Comment by felixpohlmann** [comment]
@LostNeophyte yea thought so, but I'm not sure which formatter is the actual active one....

**Comment by LostNeophyte** [comment]
> @LostNeophyte yea thought so, but I'm not sure which formatter is the actual active one....

does the html in ts actually get formatted btw?

**Comment by LostNeophyte** [comment]
also you should update your neovim

**Comment by LostNeophyte** [comment]
this:
![image](https://user-images.githubusercontent.com/110467150/200006946-c09740b9-c994-4661-97d5-5dc1817e4236.png)
does format to this:
![image](https://user-images.githubusercontent.com/110467150/200007113-c12bdf84-2d3b-4777-936d-7e13cd0e10b4.png)

in a html file with html ls

**Comment by felixpohlmann** [comment]
> > @LostNeophyte yea thought so, but I'm not sure which formatter is the actual active one....
> 
> does the html in ts actually get formatted btw?

Thats it probably, i think the HTML formatting does not even get triggered within a .jxs/.tsx file, at least that would be my best guess...

**Comment by LostNeophyte** [comment]
does `:lua vim.lsp.buf.format()` format both ts and html?
