### ISSUE TITLE
can't LvimUpdate, get stuck at commit 7d57046

### ISSUE THREAD

**Issue by qvieth** [LunarVim/LunarVim#3420]
### Problem description

can't do `LvimUpdate`, get stuck at commit 7d57046

### LunarVim version

rolling-7d57046

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev+198-g75ec1b720

### Operating system/version

fedora 36

### Steps to reproduce

after do lvim update nothing happens, tried to uninstall and reintstall but the lvim version still stuck at commit `7d5706`

### support info

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 

Buffer info
* filetype:                alpha
* bufnr:                   1
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 

### Screenshots

![image](https://user-images.githubusercontent.com/71810726/199885776-e39101e2-aa66-46ee-a792-80d9beb08a1d.png)

**Comment by LostNeophyte** [comment]
that is the last commit
