### ISSUE TITLE
Lualine looks different and is hard to read

### ISSUE THREAD

**Issue by Andrioshe** [LunarVim/LunarVim#3423]
### Problem description

The lualine colors are looking different compared to my Installation 2 days ago. Does anybody have the same problem?

I only made one configuration for my colorscheme:
```
lvim.colorscheme = "slate"
```

before:
![Screenshot from 2022-11-05 03-00-15](https://user-images.githubusercontent.com/20594633/200096650-c8a47d72-efc6-434d-bbb8-4d4bf1a6062f.png)

now:
![Screenshot from 2022-11-05 03-01-57](https://user-images.githubusercontent.com/20594633/200096655-5b55caa3-ea99-4ef9-a8d6-14b7ac56cbfc.png)

### LunarVim version

master-08d3c05

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-e87dcc9

### Operating system/version

Arch 6.0.6-arch1-1

### support info

/

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/200110105-8105c062-3905-4bd1-bf12-2374cf0096f4.png)

It looks like these just are the colors for the statusline for slate, not sure what we can do about this, can you show me a commit where it looked differently?

**Comment by ChristianChiarulli** [comment]
```
" Name:         slate
" Description:  Remake of slate
" Author:       Original maintainer Ralph Amissah <ralph@amissah.com>
" Maintainer:   Original maintainer Ralph Amissah <ralph@amissah.com>
" Website:      https://github.com/vim/colorschemes
" License:      Same as Vim
" Last Updated: Fri 02 Sep 2022 09:52:25 MSK

" Generated by Colortemplate v2.2.0

set background=dark

hi clear
let g:colors_name = 'slate'

let s:t_Co = &t_Co

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#cd0000', '#00cd00', '#cdcd00', '#0000ee', '#cd00cd', '#00cdcd', '#e5e5e5', '#7f7f7f', '#ff0000', '#00ff00', '#ffff00', '#5c5cff', '#ff00ff', '#00ffff', '#ffffff']
endif
hi! link Terminal Normal
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link CurSearch Search
hi! link CursorLineFold CursorLine
hi! link CursorLineSign CursorLine
hi! link MessageWindow Pmenu
hi! link PopupNotification Todo
hi Normal guifg=#ffffff guibg=#262626 gui=NONE cterm=NONE
hi EndOfBuffer guifg=#5f87d7 guibg=NONE gui=NONE cterm=NONE
hi StatusLine guifg=#000000 guibg=#afaf87 gui=NONE cterm=NONE
hi StatusLineNC guifg=#666666 guibg=#afaf87 gui=NONE cterm=NONE
hi StatusLineTerm guifg=#000000 guibg=#afaf87 gui=NONE cterm=NONE
hi StatusLineTermNC guifg=#666666 guibg=#afaf87 gui=NONE cterm=NONE
```

From the actual colorscheme

**Comment by Andrioshe** [comment]
hmh after using some other applications like btop and neofetch it seems to be a problem on my terminal emulator. I will check that out.

The issue can be closed! I am sorry for all thetrouble and thank you very much for your answer.
