### ISSUE TITLE
Problem When Installing v1.2 or Master  

### ISSUE THREAD

**Issue by RuddraNickBiswas** [LunarVim/LunarVim#3424]
### Problem description

*Sorry for bad English *
I have this problem I dont know what is it when I first time install Lunar-vim after I setup my OS (arch) then It Install perfectly then If i uninstall lunar-vim and then I tried install or update lvim I face error......
It happen to me every time.... even the other day I reinstall my OS for lvim and it work but I see there is update for new version 1.2 so i uninstall lvim and when I tryed to Install the new version I am facing same error....btw I tried master branch but same error .... 

SO do I need to again reinstall My OS for using Lunar-Vim 😨😨

**this is the error when i tried to install lvim** 
***********************************************
All Rust dependencies are successfully installed
--------------------------------------------------------------------------------
Removing old packer cache file
--------------------------------------------------------------------------------
Backing up old /home/rnb/.config/lvim to /home/rnb/.config/lvim.old
--------------------------------------------------------------------------------
Backing up old /home/rnb/.local/share/lunarvim to /home/rnb/.local/share/lunarvim.old
--------------------------------------------------------------------------------
Backing up old /home/rnb/.cache/lvim to /home/rnb/.cache/lvim.old
--------------------------------------------------------------------------------
Cloning LunarVim configuration
Cloning into '/home/rnb/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 15453, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 15453 (delta 1), reused 2 (delta 0), pack-reused 15441
Receiving objects: 100% (15453/15453), 13.49 MiB | 225.00 KiB/s, done.
Resolving deltas: 100% (9653/9653), done.
--------------------------------------------------------------------------------
Installing LunarVim shim
make: Entering directory '/home/rnb/.local/share/lunarvim/lvim'
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: /home/rnb/.local/bin/lvim
make: Leaving directory '/home/rnb/.local/share/lunarvim/lvim'
Creating desktop file
Preparing Packer setup
Initializing first time setup
Installing packer
Cloning into '/home/rnb/.local/share/lunarvim/site/pack/packer/start/packer.nvim'...
[packer.nvim] [WARN  15:16:20] jobs.lua:87: Killing git due to timeout!
packer.nvim: Error running config for telescope.nvim: ...pack/packer/start/telescope.nvim/lua/telescope/utils.lua:8: module 'plenary.path' not found:
^Ino field package.preload['plenary.path']
^Ino file './plenary/path.lua'
^Ino file '/usr/share/luajit-2.1.0-beta3/plenary/path.lua'
^Ino file '/usr/local/share/lua/5.1/plenary/path.lua'
^Ino file '/usr/local/share/lua/5.1/plenary/path/init.lua'
^Ino file '/usr/share/lua/5.1/plenary/path.lua'
^Ino file '/usr/share/lua/5.1/plenary/path/init.lua'
^Ino file '/home/rnb/.cache/lvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/plenary/path.lua'
^Ino file '/home/rnb/.cache/lvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/plenary/path/init.lua'
^Ino file '/home/rnb/.cache/lvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/plenary/path.lua'
^Ino file '/home/rnb/.cache/lvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/plenary/path/init.lua'
^Ino file './plenary/path.so'
^Ino file '/usr/local/lib/lua/5.1/plenary/path.so'
^Ino file '/usr/lib/lua/5.1/plenary/path.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/home/rnb/.cache/lvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/plenary/path.so'
^Ino file './plenary.so'
^Ino file '/usr/local/lib/lua/5.1/plenary.so'
^Ino file '/usr/lib/lua/5.1/plenary.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/home/rnb/.cache/lvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/plenary.so'
packer.nvim: Error running config for lir.nvim: /home/rnb/.local/share/lunarvim/lvim/lua/lvim/core/lir.lua:111: attempt to call field 'setup' (a nil value)Packer setup complete
--------------------------------------------------------------------------------
Verifying core plugins
Error detected while processing BufWinEnter Autocommands for "*":
E5108: Error executing lua ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:171: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:110: Vim(lua):E5108: Error executing lua ...rvim/site/pack/packer/start/lir.nvim/lua/lir/actions.lua:1: loop or previous error loading module 'lir.history'
stack traceback:
        [C]: in function 'cmd'
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:171: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:167>
        [string ":lua"]:1: in main chunk
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'lir.float'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'lir'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
Error detected while processing command line:
packer.nvim: Error running config for telescope.nvim: ...b/.local/share/lunarvim/lvim/lua/lvim/core/telescope.lua:147: loop or previous error loading module 'telescope.previewers'
packer.nvim: Error running config for lir.nvim: /home/rnb/.local/share/lunarvim/lvim/lua/lvim/core/lir.lua:111: attempt to index local 'lir' (a number value)Verification complete!
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Thank you for installing LunarVim!!
You can start it by running: /home/rnb/.local/bin/lvim
Do not forget to use a font with glyphs (icons) support [https://github.com/ryanoasis/nerd-fonts]

### LunarVim version

1.2 stable and master

### Neovim version (>= 0.8.0)

8

### Operating system/version

6.0.6-arch1-1 

### support info

Error executing Lua callback: .../.local/share/lunarvim/lvim/lua/lvim/interface/popup.lua:45: Vim(lua):E5108: Erro
r executing lua [string ":lua"]:1: loop or previous error loading module 'lir'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_open_win'
        .../.local/share/lunarvim/lvim/lua/lvim/interface/popup.lua:45: in function 'display'
        /home/rnb/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:217: in function 'toggle_popup'
        ...nb/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:29: in function <...nb/.local/share/lunarvim/l
vim/lua/lvim/core/commands.lua:28>
stack traceback:
        [C]: in function 'nvim_open_win'
        .../.local/share/lunarvim/lvim/lua/lvim/interface/popup.lua:45: in function 'display'
        /home/rnb/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:217: in function 'toggle_popup'
        ...nb/.local/share/lunarvim/lvim/lua/lvim/core/commands.lua:29: in function <...nb/.local/share/lunarvim/l
vim/lua/lvim/core/commands.lua:28>

**Comment by LostNeophyte** [comment]
`Killing git due to timeout!` seems like the problem here, do you have slow internet maybe?

**Comment by LostNeophyte** [comment]
@kylo252 did you say where was a bug in git on arch? maybe that's related

**Comment by RuddraNickBiswas** [comment]
Solved I dont know how it solved I just use  cellular data and now everything is ok.....
