### ISSUE TITLE
Is there is any way to  focus on the script while opening horizontal terminal ??

### ISSUE THREAD

**Issue by akashdiphazra** [LunarVim/LunarVim#3429]
### Problem description

shortcut key to focus on the file while opening the horizontal terminal.
![Screenshot from 2022-11-06 13-40-32](https://user-images.githubusercontent.com/61003681/200160744-18f16c37-9e58-4eb1-87fd-0fc83bd22664.png)

### LunarVim version

release-1.2/neovim-0.8-222a872

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-220+g234b8c5f3

### Operating system/version

Ubuntu 22.04.01

### support info

None

**Comment by cpea2506** [comment]
Horizontal can be treated as a split window so you can move between them by `Ctrl + [h,j,k,l]

**Comment by akashdiphazra** [comment]
@cpea2506  It seemed to worked, Ok !!!!
