### ISSUE TITLE
showing error message when I name a folder starting with $ example $xxxxx

### ISSUE THREAD

**Issue by RuddraNickBiswas** [LunarVim/LunarVim#3432]
### Problem description

showing error message when I name a folder starting with $ example $xxxxx

btw If I open lvim other then $named folder everything work fine......... 

### LunarVim version

1.2 

### Neovim version (>= 0.8.0)

8

### Operating system/version

6.0.6-arch1-1

### support info

Error executing vim.schedule lua callback: ...m/site/pack/packer/start/nvim-tree.lua/
lua/nvim-tree.lua:234: Vim(cd):E344: Can't find directory "/run/media/rnb/chaos//Proj
ects/PhP/php_l__alpha" in cdpath
stack traceback:
        [C]: in function 'cmd'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:234: in function 
'on_enter'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:790: in function 
<...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:789>
Press ENTER or type command to continue

this is the error I get when I start Lvim....

**Comment by LostNeophyte** [comment]
It's a bug in nvimtree https://github.com/nvim-tree/nvim-tree.lua/issues/1728

**Comment by LostNeophyte** [comment]
nvimtree merged a fix, it will be available in the master branch of lunarvim and maybe in the release later
