### ISSUE TITLE
ctrl+L not working on floating terminals

### ISSUE THREAD

**Issue by Livb-VRC** [LunarVim/LunarVim#3433]
### Problem description

Steps to reproduce:
1. Open a floating terminal with alt+1
2. Type some commands (for example ls)
3. Try to unsucessfully clear with ctrl+L

![image](https://user-images.githubusercontent.com/57561786/200192355-850e9237-9de8-4fb5-b8b0-270037e4bd64.png)

I believe it's caused because ctrl+L is mapped to switching windows. Perhaphs this could be disabled only for floating terminals? Or change the shortcut to switch windows

### LunarVim version

release-1.2/neovim-0.8-222a872

### Neovim version (>= 0.8.0)

nvim v0.8.0-1210-gd367ed9b2

### Operating system/version

wsl2

### Steps to reproduce

1. Open a floating terminal with alt+1
2. Type some commands (for example ls)
3. Try to unsucessfully clear with ctrl+L

### support info

not needed

### Screenshots

![image](https://user-images.githubusercontent.com/57561786/200192453-7c8bebe2-54ab-4348-aed3-6c3ea99180cd.png)

**Comment by opalmay** [comment]
PR open for this https://github.com/LunarVim/LunarVim/pull/3298
