### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by IceTap** [LunarVim/LunarVim#3440]
### Problem description

1. Just using the install script (goes well)
2. running lunarvim through command "C:\Users\samcf\.local\bin\lvim.ps1"
3. boots up but looks wrong, something wrong with package manager I think?

### LunarVim version

0.8.0, release version from website

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Windows 11

### Steps to reproduce

1. As said before, run powershell install script from website
2. start lvim

### support info

Error executing Lua callback: vim/shared.lua:224: t: expected table, got string
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:699: in function 'validate'
        vim/shared.lua:224: in function 'func'
        vim/shared.lua:211: in function 'tbl_filter'
        ...mcf\AppData\Roaming\lunarvim\lvim/lua\lvim\core\info.lua:115: in function 'make_auto_lsp_info'
        ...mcf\AppData\Roaming\lunarvim\lvim/lua\lvim\core\info.lua:159: in function 'toggle_popup'
        ...AppData\Roaming\lunarvim\lvim/lua\lvim\core\commands.lua:29: in function <...AppData\Roaming\lunarvim\lvim/lua\lvim\core\commands.lua:28>

### Screenshots

![Screenshot_20221107_065343](https://user-images.githubusercontent.com/89491881/200471401-a2fc738d-99a2-4c59-a22e-04321c35bdb6.png)
![Screenshot_20221107_065402](https://user-images.githubusercontent.com/89491881/200471402-734e4db7-1686-424e-8c86-35bcd21bfc50.png)

**Comment by LostNeophyte** [comment]
Try running :LvimCacheReswt and then :PackerSync

**Comment by kobzar** [comment]
:PackerCompile at and

**Comment by Patrick-web** [comment]
None of the above solutions work. Am guessing it's a problem with packer since am having the same issue when installing nvchad. Maybe a commit to packer broke something?

**Comment by Patrick-web** [comment]
> there were no errors during installation (of lunarvim)?

There are.  Here's what am getting
![image](https://user-images.githubusercontent.com/56973177/201212435-9e6ea7c2-affa-401b-ba4e-16466b0e41aa.png)

**Comment by LostNeophyte** [comment]
> > there were no errors during installation (of lunarvim)?
> 
> There are. Here's what am getting ![image](https://user-images.githubusercontent.com/56973177/201212435-9e6ea7c2-affa-401b-ba4e-16466b0e41aa.png)

I mean errors during the first installation of lunarvim using the install scriot

**Comment by LostNeophyte** [comment]
You can try deleting plugins directory from .config/lvim and then opening lvim and running :PackerSync

**Comment by Patrick-web** [comment]
I've retried the installation and am getting this 
![image](https://user-images.githubusercontent.com/56973177/201214537-4059adc2-78d8-4211-ac60-15a212128a11.png)

After deleting the config directory  am getting this 
![image](https://user-images.githubusercontent.com/56973177/201214930-b0f50dd0-f2b0-457e-a232-3b0cee270edf.png)
And all packer commands are failing

**Comment by LostNeophyte** [comment]
Something's completely wrong with that installation, run the install script, say no to the dependencies and attach it's full output here

**Comment by Patrick-web** [comment]
No am on linux, its @IceTap who is on linux

**Comment by LostNeophyte** [comment]
> No am on linux, its @IceTap who is on linux

Oh sorry, it's late here, I'm not thinking straight. In that case run the install script, you can say no to the dependencies, and attach the full output here. I'll look into it tomorrow it's too late for thinking

**Comment by Patrick-web** [comment]
Cool

> > No am on linux, its @IceTap who is on linux
> 
> Oh sorry, it's late here, I'm not thinking straight. In that case run the install script, you can say no to the dependencies, and attach the full output here. I'll look into it tomorrow it's too late for thinking

Ok. Let me get to it. Thank you. Tomorrow then

**Comment by IceTap** [comment]
> You can try deleting plugins directory from .config/lvim and then opening lvim and running :PackerSync

running :PackerSync completely fixed my problem

**Comment by aniketgm** [comment]
> running :PackerSync completely fixed my problem

You see, usually just having a look around first, and updating and syncing everything, solves the problem.
I think we should add this point into the "create new issue/bug" template.
@LostNeophyte, @vonPB, What do you guys think ?

Meaning, we can add a question something like:
\## Is the issue still reproducible after `:PackerSync` OR `LvimSyncCorePlugins` OR any other sync that we have in lunarvim ?

**Comment by LostNeophyte** [comment]
> > running :PackerSync completely fixed my problem
> 
> You see, usually just having a look around first, and updating and syncing everything, solves the problem. I think we should add this point into the "create new issue/bug" template. @LostNeophyte, @vonPB, What do you guys think ?
> 
> Meaning, we can add a question something like: ## Is the issue still reproducible after `:PackerSync` OR `LvimSyncCorePlugins` OR any other sync that we have in lunarvim ?

Maybe we could add some stuff to the [troubleshooting page](https://www.lunarvim.org/docs/troubleshooting) and link it in the template
