### ISSUE TITLE
How to 'set background=light' in config.lua

### ISSUE THREAD

**Issue by lucabol** [LunarVim/LunarVim#3441]
### Problem description

Install nvim-solarized-lua with:
```
lvim.plugins = {
    { "ishan9299/nvim-solarized-lua" },
}
```
Attempt to put the following line anywhere in the config.lua file

```
vim.cmd("set background=light")
```

The background doesn't turn light. Running `:set background=light` interactively turns it light.

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

0.8-222a872

### Operating system/version

Linux Ubuntu under wsl

### support info

```console
Language client log: /home/lucabol/.local/state/nvim/lsp.log
 Detected filetype:   lua
 
 1 client(s) attached to this buffer: 
 
 Client: sumneko_lua (id: 1, pid: nil, bufnr: [3])
 	filetypes:       lua
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             lua-language-server
 
 Configured servers list: sumneko_lua
```

**Comment by abzcoding** [comment]
add this to your `~/.config/lvim/config.lua`
```lua
vim.opt.background="light"
```

**Comment by lucabol** [comment]
No luck. Background stays dark.

**Comment by abzcoding** [comment]
> No luck. Background stays dark.

can you share your entire config.lua somewhere?
because we are not setting background anywhere in lunarvim
and unless you have a type inside your config
setting `vim.o.bg="light"` should suffice

**Comment by lucabol** [comment]
[config.lua.txt](https://github.com/LunarVim/LunarVim/files/9960685/config.lua.txt)

Here it is. Apologies in advance if it is something obvious.

**Comment by abzcoding** [comment]
this is an actual bug that comes from here

https://github.com/LunarVim/lunar.nvim/blob/29eedf78c430ad9acebdcba814d77619edbe2bac/lua/lunar/init.lua#L7

@ChristianChiarulli is there a reason we are forcing everyone to use the dark background?


@lucabol temporary fix would be to add this to your config
```lua
lvim.builtin.theme.name="tokyonight"
```

**Comment by lucabol** [comment]
Amazing quick reply and it works. Many thanks. Closing it.

**Comment by abzcoding** [comment]
you are welcome, i'll create the issue inside https://github.com/LunarVim/lunar.nvim
