### ISSUE TITLE
Highlighting changed unexpectedly in OneDarker Theme

### ISSUE THREAD

**Issue by felixpohlmann** [LunarVim/LunarVim#3448]
### Problem description

After updating neovim as well as lunarvim, the highlighting style changed. (I'm using the same theme ("onedarker") and did not change any settings regarding lsp or treesitter)

For example, the highlighting when accessing objects attributes like "data.value" is missing completely… :(

Also please see issue #3417 for my previous lspInfo und LvimInfo screenshots and settings!

**When trying out other themes, this does not happen. So maybe the issue is related to the OneDarker theme?**

Thanks for any help in advance!

### LunarVim version

release-1.2/neovim-0.8-222a872

### Neovim version (>= 0.8.0)

v0.8.0

### Operating system/version

macOS 13.0

### Steps to reproduce

I updated lunarvim as well as neovim itself.
(LunarVim master-1468aea --> release-1.2)
(neovim v0.7.2 --> v0.8.0)

### support info

![Screenshot 2022-11-08 at 19 10 14](https://user-images.githubusercontent.com/68960775/200642550-9d5f0f4c-5d56-4948-b5bb-21d2e9b1529f.png)

![Screenshot 2022-11-08 at 19 10 03](https://user-images.githubusercontent.com/68960775/200642744-08e320cd-258c-410c-a452-bb2bf28db00e.png)

### Screenshots

**BEFORE**

![199988709-07853930-a8d9-4bd3-914d-b4da91f36e2b](https://user-images.githubusercontent.com/68960775/200642631-452b956c-39d6-4e67-a88d-1f5fe60291e1.png)

**NOW**
![Screenshot 2022-11-08 at 19 00 55](https://user-images.githubusercontent.com/68960775/200642667-257b67fb-8c26-4d4e-a397-4695cb49480d.png)

**Comment by ChristianChiarulli** [comment]
this was because treesitter changed, not really a lunarvim problem

**Comment by LostNeophyte** [comment]
> Yea, lots of highlighting issue on treesitter in latest version Which is holding me to upgrade to the latest version of lvim
> 
> Ref: [nvim-treesitter/nvim-treesitter#3092](https://github.com/nvim-treesitter/nvim-treesitter/issues/3092)

To get rid of the errors in the linked issue just run `:TSUpdate`
