### ISSUE TITLE
Add Ansible as language

### ISSUE THREAD

**Issue by bartheerman** [LunarVim/LunarVim#3451]
Is it possible to add Ansible as supported language?

Languange server:
https://github.com/ansible/ansible-language-server

Linter:
https://github.com/ansible/ansible-lint

TS can use YAML:
https://github.com/ikatyang/tree-sitter-yaml

**Comment by LostNeophyte** [comment]
Looks like it's already supported https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ansiblels.
And it's not really an issue with lunarvim

**Comment by bartheerman** [comment]
Maybe it can be added to the docs under languages?

**Comment by LostNeophyte** [comment]
that's an issue for [the website](https://github.com/LunarVim/lunarvim.org) in that case. I don't have permissions to move it though
