### ISSUE TITLE
Unwanted autocmds enabling spelling

### ISSUE THREAD

**Issue by jototland** [LunarVim/LunarVim#3455]
### Problem description

When editing markdown files, random words were underlined. Eventually I found out it was the spell checker started by an autocmd in `lua/lvim/core/autocmds.lua`. (In group `_filetype_settings`, the filetypes gitcommit and markdown had an autocmd `setlocal wrap spell`). 

I often edit markdown files (or gitcommits) in more than one language. It is much harder to remove an autocmd than to add it yourself in a configuration file. I believe these two autocmds should be removed from standard settings, or there should be an easy and documented way to disable them. 

### LunarVim version

master-431ddb4

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev

### Operating system/version

Linux 5.10.16.3-microsoft-standard-WSL2

### Steps to reproduce

: test.md
iRanndom w0rds aree undrlined.<esc>

### support info

Not relevant

### Screenshots

![image](https://user-images.githubusercontent.com/13568702/201159304-de84dd10-20af-4f17-abda-d3137f6453cd.png)

**Comment by abzcoding** [comment]
you can add this to your config,
but I do agree that we should not force this on users

cc: @kylo252 

```lua
vim.api.nvim_clear_autocmds { pattern = { "gitcommit", "markdown" }, group = "_filetype_settings" }
```
