### ISSUE TITLE
Which Key +Debug keeps appearing

### ISSUE THREAD

**Issue by mpas** [LunarVim/LunarVim#3456]
### Problem description

Having the following config.lua the `+Debug` menu keeps appearing..

```lua
lvim.builtin.which_key.mappings['d'] = {}
lvim.builtin.which_key.mappings = {
    ["c"] = { "<cmd>BufferClose!<CR>", "Close Buffer" },
    ["e"] = { "<cmd>lua require'core.nvimtree'.toggle_tree()<CR>", "Explorer" },
    ["h"] = { '<cmd>let @/=""<CR>', "No Highlight" },

    p = {
        name = "Packer",
        c = { "<cmd>PackerCompile<cr>", "Compile" },
        i = { "<cmd>PackerInstall<cr>", "Install" },
        r = { "<cmd>lua require('lv-utils').reload_lv_config()<cr>", "Reload" },
        s = { "<cmd>PackerSync<cr>", "Sync" },
        u = { "<cmd>PackerUpdate<cr>", "Update" },
    },
}
```

<img width="344" alt="image" src="https://user-images.githubusercontent.com/139094/201182395-c7746c7f-5e06-447d-9625-6697a319db5f.png">

### LunarVim version

master-5e051af

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

macos 12.6.1

### support info

```console
Buffer info
* filetype:                alpha
* bufnr:                   1
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 

```

**Comment by abzcoding** [comment]
try this:

```lua
lvim.builtin.dap.on_config_done = function()
  lvim.builtin.which_key.mappings['d'] = {}
end
```

because of this:
https://github.com/LunarVim/LunarVim/blob/87cde2f6a7c1358ba327096c3f802dbe100a64ae/lua/lvim/core/dap.lua#L90

**Comment by mpas** [comment]
That indeed works, I had the idea that overriding the default keybinding as mentioned in the docs would also wipeout the "debug" keys. That is why is tried to also clear the "d" binding with `lvim.builtin.which_key.mappings['d'] = {}` but as you pointed out this is coming from somewhere else in the codebase. 

Would it not be better to keep the bindings in one place instead then also have it in de dap config?

**Comment by abzcoding** [comment]
> Would it not be better to keep the bindings in one place instead then also have it in de dap config?

yep I agree, we would appreciate a PR :)

**Comment by mpas** [comment]
Added a pr see #3459
