### ISSUE TITLE
Allow to customise nvim-cmp sources

### ISSUE THREAD

**Issue by danielo515** [LunarVim/LunarVim#3458]
Here is where nvim-cmp sources are defined:

https://github.com/LunarVim/LunarVim/blob/87cde2f6a7c1358ba327096c3f802dbe100a64ae/lua/lvim/core/cmp.lua#L223-L277

While it is convenient to have them all listed, and all the end user needs to do is install the required plugins, there is no way for the user to configure them.
Imagine that I want to setup the order, or group them, or add little details like keyword_length: there is no way.
The only options is, to completely overwrite the entire list, or get duplicates if you add to the list manually. Neither of those is convenient.

Because this is just a list, there is no easy way to reach for a particular source config either, because order may change anytime.

**Comment by danielo515** [comment]
> as you can see a bit further up in the file
I read the entire file. Not sure why do you think I would take the time to open an issue if the solution was that simple. I deserve a little bit more credit 😉 

The problem with that list is... well, that it is a list, right? The only possible customisations that can be reliable done are:
- completely replace it
- Append to it, at the beginning or at the end

Any other attempt to customise it is unreliable and will result in problems. To give you an idea of what kind of things I want to do, here is how I currently have it customised:

```lua
local sources = {
  {
    name = "nvim_lsp",
    entry_filter = function(entry, ctx)
      local kind = require("cmp.types").lsp.CompletionItemKind[entry:get_kind()]
      if kind == "Snippet" and ctx.prev_context.filetype == "java" then
        return false
      end
      if kind == "Text" then
        return false
      end
      return true
    end,
  },

  { name = "cmp_tabnine" },
  { name = "calc" },
  { name = "emoji" },
  { name = "crates" },
  { name = "npm", keyword_length = 4 },
  --#region Copied from someone
  { name = "path", priority_weight = 110 },
  { name = "git", priority_weight = 110 },
  { name = "nvim_lsp", max_item_count = 20, priority_weight = 100 },
  { name = "nvim_lua", priority_weight = 90 },
  { name = "luasnip", priority_weight = 80 },
  { name = "buffer", max_item_count = 5, priority_weight = 70 },
  {
    name = "rg",
    keyword_length = 4,
    max_item_count = 5,
    priority_weight = 60,
    option = {
      additional_arguments = "--smart-case --hidden",
    },
  },
  { name = "tmux", max_item_count = 5, option = { all_panes = true, label = "[tmux]" }, priority_weight = 50 },
  {
    name = "look",
    keyword_length = 5,
    max_item_count = 5,
    option = { convert_case = true, loud = true },
    priority_weight = 40,
  },
  { name = "treesitter" },
}

lvim.builtin.cmp.sources = sources

```

As you can see, it is a copy paste of the original one in the core with the addition of some extras AND modifications of existing ones. So if you want to customise one of the items on the list, let's say you want to just give a different weight to the crates one, you are out of luck, you have to replace the entire list, either by filtering and then appending, or just copy paste as I did.

Hope the request is a bit more clear now

**Comment by LostNeophyte** [comment]
> I read the entire file. Not sure why do you think I would take the time to open an issue if the solution was that simple. I deserve a little bit more credit :wink:

Many people don't do that, so props to you for that. I didn't mean it in that way, it's just that not everyone knows how much of the defaults you can change in lvim. But here it's completely my fault, It looks like I haven't read the whole issue and just stopped at `there is no way for the user to configure them` to look at the file and didn't read the rest, sorry

As for the issue, I think the easiest way to do what you want is to use `vim.tbl_filter` on the list to delete the items you don't want or want to modify and then append the custom ones

**Comment by LostNeophyte** [comment]
```lua
local sources_to_delete = {
  "copilot",
  "path",--[[ ... ]]
}
local new_sources = vim.tbl_filter(function(source)
  return vim.tbl_contains(sources_to_delete, source.name)
end, lvim.builtin.cmp.sources)

vim.list_extend(new_sources, {
  { name = "path", priority_weight = 110 },
  { name = "git", priority_weight = 110 },
  -- ...
})

lvim.builtin.cmp.sources = new_sources
```

**Comment by danielo515** [comment]
Yes, that is one way of doing it. I'm not saying it's impossible, I'm just saying it is not easy for the average user. LunarVim is already making a lot of decisions for the user by selecting which sources are available, in which order and with which settings. I think it will be good to have one easy way to customise the existing sources, (maybe doing the merge you suggested in the core

Thanks for taking the time to put some code that shows a possible solution.

**Comment by LostNeophyte** [comment]
The problem with putting it in the core is that we would need to know if the user wants to modify it or  completely change the sources. We could change the structure of the list to a table where the have is the key but that's a breaking change and it would be a bit weird as the rest of the config is the same as cmp's.

**Comment by danielo515** [comment]
I was thinking more about a function, like lvim.cmp.addSources and perform
a merge there. But in any case, it is probably not worth the effort if
nobody else has this problem, and I already have it sorted out.

**Comment by JoannesJ** [comment]
I do think this could use some documentation though.
Because the expectation is that something like this would be customizable.
But to me, `cmp.sources` being a list, is API speak for "don't edit these items, only add new ones".

**Comment by danielo515** [comment]
> I do think this could use some documentation though. Because the expectation is that something like this would be customizable. But to me, `cmp.sources` being a list, is API speak for "don't edit these items, only add new ones".

That was my reasoning too, and that is why I completely overwritten it. But having to dig into lunarvim source code for that is not very user friendly.

**Comment by LostNeophyte** [comment]
What could we do without it being a breaking change though, i think it's only documentation. it is a list because cmp needs it to be a list. Cmp documentation will be quite useful, we could put stuff like copilot amd tabnine there, if you want that please open an issue on the lunarvim.org repo

**Comment by danielo515** [comment]
I will open a pull request instead
