### ISSUE TITLE
[Windows] Treesitter issue

### ISSUE THREAD

**Issue by jeeeem** [LunarVim/LunarVim#3466]
### Problem description

I tried changing my LunarVersion from rolling to latest release 1.2 but I am encountering this issue whenever I do, I already tried to `:LvimCacheReset` then `:PackerSync`, removed the plugins then do it again but still the same. 

### LunarVim version

release-1.2/neovim-0.8-c1d4f5ef

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Windows

### Steps to reproduce

Nan

### support info

Nan

### Screenshots

![image](https://user-images.githubusercontent.com/51053482/201504504-51c6bd07-498e-4d6f-bc03-40396256fa50.png)

**Comment by LostNeophyte** [comment]
Duplicate of https://github.com/LunarVim/LunarVim/issues/3460. There have been 3 issues about it already in the past day, @kylo252 what do you think about adding `TSUpdate lua` to the installer to run after packer

**Comment by jeeeem** [comment]
> Duplicate of #3460. There have been 3 issues about it already in the past day, @kylo252 what do you think about adding `TSUpdate lua` to the installer to run after packer

Running `:TSUpdate` fixes this issue
