### ISSUE TITLE
How to enable the popup complete window when search ?

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3468]
### Problem description

I remember that, before I reinstall the lvim, I get a popup window when searching. But now it disappear, how to get them back. 
I do some google work but not found related. 
![image](https://user-images.githubusercontent.com/11295355/201505918-d4b5547a-43c5-40d3-9e83-614682e923c0.png)

### LunarVim version

master-e45afe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0-dev-914-gd4d27c41b

### Operating system/version

OS: Ubuntu 22.04 jammy

### support info

se [q] or [Esc] to quit the window                            │
│                                                                       │
│        Language client log: /home/lizhe/.local/state/nvim/lsp.        │
│                                 log                                   │
│        Detected filetype:   alpha                                     │
│                                                                       │
│        0 client(s) attached to this buffer:                           │
│                                                                       │
│        Configured servers list: 
  │Buffer info                                             │      │
│       │* filetype:                alpha                        │      │
│       │* bufnr:                   1                            │      │
│       │* treesitter status:       inactive                     │      │
│       │                                                        │      │
│       │Active client(s)                                        │      │
│       │                                                        │      │
│       │Automatic LSP info                                      │      │
│       │* Skipped servers: [angularls, ansiblels, csharp_ls, css│      │
│       │                                                        │      │
│       │Formatters info                                         │      │
│       │* Active:                                               │      │
│       │* Supported: []                                         │      │
│       │                                                        │      │
│       │Linters info                                            │      │
│       │* Active:                                               │      │
│       │* Supported: []                                         │      │
│       │                                                        │      │
│~      │Code actions info                                       │      │
│~      │* Active:

**Comment by LostNeophyte** [comment]
lvim.builtin.cmp.cmdline.enable = true
