### ISSUE TITLE
Executing macro gives wrong results

### ISSUE THREAD

**Issue by PhosCity** [LunarVim/LunarVim#3469]
### Problem description

When executing a macro in lunarvim, the execution is different than how it's supposed to be.

For simplicity, let's take the following file:

```
line 1
line 2
line 3
line 4
line 5
```

I go to the first line and record a macro using `qqA, test<ESC>jq` (adding `,test` to the end of all lines, going to next line and stop recording). Then in second line I do `5@q` to execute the macro and I expect the following to happen (and it happens in `vim` or `nvim --clean`. 

```
line 1, test
line 2, test
line 3, test
line 4, test
line 5, test
```

But in Lunarvim, following happens:

```
line 1, test
line 2, test, test, test, test, test
line 3
line 4
line 5
```

### LunarVim version

master-5e051af

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

Arch Linux

### support info

```console
# :LvimInfo

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                
* bufnr:                   3
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```
```console
# :LspInfo
 Use [q] or [Esc] to quit the window
 
 Language client log: /home/phoscity/.local/state/nvim/lsp.log
 Detected filetype:   
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: marksman
```

**Comment by LostNeophyte** [comment]
Maybe you have something in your config, It's working for me.

https://user-images.githubusercontent.com/110467150/201513144-d48879f1-209f-410c-b80d-5f2aa761d8d3.mp4

Try this: move your config, restart lvim run `:PackerSync`, and restart lvim

**Comment by PhosCity** [comment]
You're right. I should've done my due diligence before creating an issue.

It was apparently caused by a plugin I was trying out: https://github.com/ja-ford/delaytrain.nvim

It was stopping macros from using hjkl successively in short period of time. Thanks for your assistance.
