### ISSUE TITLE
When some error in the config file, the error messages keep pop out make me cant edit the config file, how to warn sliently?

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3474]
### Problem description

When I leave a error in the config file. The lvim become like this, I press esc or enter or q, wont stop it how to fix it? 

![image](https://user-images.githubusercontent.com/11295355/201843443-ebc2dd03-79cb-45a8-a961-bdb7e08f8321.png)

### LunarVim version

master-e45afe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0-dev-914-gd4d27c41b

### Operating system/version

OS: Ubuntu 22.04 jammy

### support info

Use [q] or [Esc] to quit the window                            │
│                                                                       │
│        Language client log: /home/lizhe/.local/state/nvim/lsp.        │
│                                 log                                   │
│        Detected filetype:   alpha                                     │
│                                                                       │
│        0 client(s) attached to this buffer:                           │
│                                                                       │
│        Configured servers list: 
  │Buffer info                                             │      │
│       │* filetype:                alpha                        │      │
│       │* bufnr:                   1                            │      │
│       │* treesitter status:       inactive                     │      │
│       │                                                        │      │
│       │Active client(s)                                        │      │
│       │                                                        │      │
│       │Automatic LSP info                                      │      │
│       │* Skipped servers: [angularls, ansiblels, csharp_ls, css│      │
│       │                                                        │      │
│       │Formatters info                                         │      │
│       │* Active:                                               │      │
│       │* Supported: []                                         │      │
│       │                                                        │      │
│       │Linters info                                            │      │
│       │* Active:                                               │      │
│       │* Supported: []                                         │      │
│       │                                                        │      │
│~      │Code actions info                                       │      │
│~      │* Active:

**Comment by LostNeophyte** [comment]
what's the output of `:lua vim.cmd("!cd " .. get_lvim_base_dir() .. " && git log -1")`?

**Comment by woshichuanqilz** [comment]
The result of the command you mentioned is:

```
│:!cd /home/lizhe/.local/share/lunarvim/lvim && git log -1              │
│commit c1d4f5ef59dd1843ba6f69198a6753867a33e3f1                        │
│Author: kylo252 <59826753+kylo252@users.noreply.github.com>            │
│Date:   Thu Nov 10 16:11:55 2022 +0100                                 │
│                                                                       │
│    feat: configure dap logging (#3454)
```

But now the lvim is ok, I kill the process and correct the init file by another editor. 

I mean that when I occasionally leave an error in the init file. The error messages keep pop up from command line, so I cant do anything except kill the lvim.  For example,  Here I leave a meaning  line "xx" in the init file, the error message wont stop

![image](https://user-images.githubusercontent.com/11295355/201891130-d0b293d7-717e-488a-8c52-9a5b374c1e50.png)

When I hit some keys turn to this

![image](https://user-images.githubusercontent.com/11295355/201891833-0b07e62c-824b-4650-88c8-c6ab39b123c2.png)

**Comment by LostNeophyte** [comment]
> The result of the command you mentioned is:
> 
> ```
> │:!cd /home/lizhe/.local/share/lunarvim/lvim && git log -1              │
> │commit c1d4f5ef59dd1843ba6f69198a6753867a33e3f1                        │
> │Author: kylo252 <59826753+kylo252@users.noreply.github.com>            │
> │Date:   Thu Nov 10 16:11:55 2022 +0100                                 │
> │                                                                       │
> │    feat: configure dap logging (#3454)

In that case the LvimVersion in your issue is wrong

The errors don't happen for me though, it only shows one time. Maybe you're saving the config multiple times?

**Comment by SomeBoolShit** [comment]
Is this issue related to your vim.cmd() configurations in your config.lua in one of your earlier posts?

**Comment by woshichuanqilz** [comment]
> Is this issue related to your vim.cmd() configurations in your config.lua in one of your earlier posts?

Yeah, seems one bug already fixed. 
I use nightly version : │master-ae89f07 seems ok now.
