### ISSUE TITLE
Key Mapping changed a lot for version 1.2, how to get the diff?

### ISSUE THREAD

**Issue by RenliangShi** [LunarVim/LunarVim#3476]
After upgraded to version 1.2, jj never jump from insert mode to normal mode, also I can not figure out how to navigate between buffer windows.

**Comment by LostNeophyte** [comment]
for window navigation : [link](https://gitlab.com/lostneophyte/dotfiles/-/blob/655e43decdbd4b76df985c7b45b345bdda551bee/lvim/.config/lvim/lua/user/bindings.lua#L30-27)
bufferline navigation: [link](https://gitlab.com/lostneophyte/dotfiles/-/blob/655e43decdbd4b76df985c7b45b345bdda551bee/lvim/.config/lvim/lua/user/bindings.lua#L44-45)
jk: [link](https://gitlab.com/lostneophyte/dotfiles/-/blob/655e43decdbd4b76df985c7b45b345bdda551bee/lvim/.config/lvim/lua/user/bindings.lua#L14)
you can get the changes in the [changelog](https://github.com/LunarVim/LunarVim/blob/master/CHANGELOG.md)

**Comment by RenliangShi** [comment]
> for window navigation : [link](https://gitlab.com/lostneophyte/dotfiles/-/blob/655e43decdbd4b76df985c7b45b345bdda551bee/lvim/.config/lvim/lua/user/bindings.lua#L30-27) bufferline navigation: [link](https://gitlab.com/lostneophyte/dotfiles/-/blob/655e43decdbd4b76df985c7b45b345bdda551bee/lvim/.config/lvim/lua/user/bindings.lua#L44-45) jk: [link](https://gitlab.com/lostneophyte/dotfiles/-/blob/655e43decdbd4b76df985c7b45b345bdda551bee/lvim/.config/lvim/lua/user/bindings.lua#L14) you can get the changes in the [changelog](https://github.com/LunarVim/LunarVim/blob/master/CHANGELOG.md)

thank you for your reply, but it does not work for me both on ubuntu 20.04 and mac os 12.6.

**Comment by LostNeophyte** [comment]
All of them don't work? Change the jk to jj. Maybe I misunderstood what you meant, can you tell me exactly which keybinding you want? (You can just tell me the old shortcuts)
