### ISSUE TITLE
Sometime diagnostics displays other languages.

### ISSUE THREAD

**Issue by akashdiphazra** [LunarVim/LunarVim#3477]
### Problem description

Why this is displaying in chinese

![Ubuntu-2022-11-15-20-07-36](https://user-images.githubusercontent.com/61003681/201947248-d46f81ec-bca7-43f6-8272-8f77961a987b.png)

### LunarVim version

release-1.2/neovim-0.8-d668598

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-323+g211c568e6

### Operating system/version

Ubuntu 22.10

### support info

None

**Comment by LostNeophyte** [comment]
It's a nerdfont icon
