### ISSUE TITLE
Install issue with powershell script

### ISSUE THREAD

**Issue by zinsss** [LunarVim/LunarVim#3480]
### Problem description

Installing with powershell script error.

#2875 related? 

### LunarVim version

can't provide it, since I couldn't install

### Neovim version (>= 0.8.0)

0.8.0

### Operating system/version

windows 10, powershell 7.3.0

### Steps to reproduce

simple copy paste from official homepage to powershell v7.3.0

### support info

I can't provide it since I didn't install it.

### Screenshots

![image](https://user-images.githubusercontent.com/87020914/202066808-7bd90c97-dd62-4523-a9fd-b49647b2eeb8.png)

**Comment by LostNeophyte** [comment]
Does it work if you download the installer, change line 234 to `$verify_version_cmd='if v:errmsg != "" | cquit | else | quit | endif'` and run it?

**Comment by LostNeophyte** [comment]
that PR fixed #3467 though, so I don't know what's going on, powershell is doing something weird

**Comment by zinsss** [comment]
Will try tommorow and comment when I am back to work... where the machine with the issue is. Thnks!

**Comment by brneor** [comment]
> Does it work if you download the installer, change line 234 to `$verify_version_cmd='if v:errmsg != "" | cquit | else | quit | endif'` and run it?

Can confirm this works.

**Comment by LostNeophyte** [comment]
> > Does it work if you download the installer, change line 234 to `$verify_version_cmd='if v:errmsg != "" | cquit | else | quit | endif'` and run it?
> 
> Can confirm this works.

Interesting, the pr fixed it for some and broke for others it seems. I don't know anything about powershell so I won't try to fix it though
