### ISSUE TITLE
visual glitches: `file.txt (~) - NVIM` `[No Name] - NVIM`

### ISSUE THREAD

**Issue by whot** [LunarVim/LunarVim#3481]
## maintainer edit

add `vim.opt.title = false` to your config.lua as a workaround, the issue is not in lunarvim

examples of this bug:
- near the cursor
  ![image](https://user-images.githubusercontent.com/110467150/208630717-289864d5-bef2-45ee-8d1a-b33b0a3ab9c9.png)
  ![image](https://user-images.githubusercontent.com/110467150/208631585-f290a3c9-51fe-4f50-ac57-70f2f4587991.png)
  ![image](https://user-images.githubusercontent.com/110467150/208631959-43f37a43-6647-48a0-8243-780e7254325b.png)

- near the statusline
  ![image](https://user-images.githubusercontent.com/110467150/208630789-c247b105-101c-4972-8bc9-89ef235b6c5c.png)
  ![image](https://user-images.githubusercontent.com/110467150/208630950-04f0551d-70ea-4c47-9280-4d13fe8efb67.png)

### Problem description

In any document (new file, email, code, ...) i get the document title inserted at the current line, sometimes at the cursor position. Reproducible by simply editing any file and starting to type. Example screenshot after simply typing `t` in a new file:

![Screenshot from 2022-11-16 15-49-06](https://user-images.githubusercontent.com/1487352/202094614-15ab06c1-60a4-4ce6-8ccf-2d795fe938af.png)

The `[[No name] ...` bit is inserted either at a fixed column or sometimes at the cursor position. It's the file name, so editing real files get that inserted.

This started happening after the Fedora 36 -> Fedora 37 update but I can reproduce after reinstalling lvim and in a `podman` container (see below). I don't think it's lvim itself, it happens with the release-1.2/neovim-0.8 branch and master. My config is the default one after reinstalling, I can **not** reproduce it with the `minimal_lsp.lua`. 

My main problem is: How do I even start debugging this? F36 and F37 have the same neovim version afaict, so it's ... somewhere else?

### LunarVim version

release-1.2/neovim-0.8-d668598

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

Fedora 37

### Steps to reproduce

This is reproducible in a podman container 

Start a container with `podman run --rm -it fedora:37`

And in the container:
1. `dnf install -y neovim git make`
1. `LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`
1. `lvim`
1. new file, type `t` to get the result from the screenshot above

This does *not* happen with a `fedora:36`.

### support info

lviminfo
```
Buffer info
* filetype:                
* bufnr:                   6
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```
lspinfo
```
 Use [q] or [Esc] to quit the window
 
 Language client log: /home/whot/.local/state/nvim/lsp.log
 Detected filetype:   alpha
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: 
```

**Comment by LostNeophyte** [comment]
I use fedora, but I use the neovim nightly copr, you can try that.

**Comment by MichalMazurek** [comment]
I just installed the latest neovim, 0.9.0-dev-326+gfa7e1e260, and still have the same under fedora 37

**Comment by LostNeophyte** [comment]
my gpu didn't like the new driver and I had to rollback the update, thanks nvidia. I'll try podman I guess

**Comment by LostNeophyte** [comment]
does `vim.opt.title = false` fix it?

**Comment by vastray** [comment]
@LostNeophyte Yes it fixes the bug.

**Comment by LostNeophyte** [comment]
it's a bug in neovim it seems, if you `:set title` weird things happen as well

**Comment by whot** [comment]
Confirming too, `vim.opt.title = false` fixes the issue. Thank you!

A quick look at the Fedora rpm spec files shows no differences between the F36 and the F37 packages, so it's likely in one of the dependencies then.

**Comment by kobzar** [comment]
Closed as resolved

**Comment by LostNeophyte** [comment]
issue in neovim: https://github.com/neovim/neovim/issues/18573

**Comment by LostNeophyte** [comment]
opened the issue, so it's easier to find, there are many duplicates
