### ISSUE TITLE
null-ls not falling back to proper bin directory in yarn pnp enabled projects

### ISSUE THREAD

**Issue by wizardlink** [LunarVim/LunarVim#3482]
### Problem description

After some digging I got to know that `null-ls` has had since February proper Yarn `pnp` handling, however in _LunarVim_ this behavior seems to be overwritten as seen in `lua/lvim/lsp/null-ls/services.lua` line 28, where it default to always looking in node modules.

So my questions boil down to:
- Is this overwrite needed?
- What can I do in the short term to work around this? I need it ASAP for work.
- In the long term, what would be the route to fixing this?

I made a [post yesterday](https://github.com/LunarVim/LunarVim/discussions/3478) in the discussions concerning `tsserver` which I had the same issue, I was able to work around that but in the case of `eslint` it will not allow me to change the command no matter what, that's because it needs to be the exact name or it throws me the error `Not a valid source`.

### LunarVim version

master-ae89f07

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

Fedora 37 (Silverblue)

### Affected language servers

eslint

### Steps to reproduce

1. Initialize a project using Yarn 2+
2. Install eslint - `yarn add -D eslint`
3. Install the sdk - `yarn dlx @yarnpkg/sdks base`
  _This will add all the binaries based off of what you have in your project, namely, `eslint`._

### Actual behavior

ESLint is silently ignored as `node_modules` does not exists.

### Expected behavior

ESLint to lint my file and give me the same errors that `yarn eslint` gives me.

### support info

![image](https://user-images.githubusercontent.com/26727907/202182895-cd8d19f6-e6d9-4a62-8a74-eb645df4abfd.png)
![image](https://user-images.githubusercontent.com/26727907/202183182-93da3a76-09ea-43fd-afae-f7079042d210.png)

_Sorry, for some reason I can't `"+y` into my copy buffer anymore, so I have to resort to screenshots._

**Comment by LostNeophyte** [comment]
if it doesn't find it in node_modules it will see if it's executable, so you can add it to $PATH as a workaround

**Comment by LostNeophyte** [comment]
you can also use this to bypass lvim
```lua
null_ls.register({
  sources = {
    null_ls.builtins.diagnostics.eslint.with({
      dynamic_command = command_resolver.from_yarn_pnp(),
    }),
  },
})
```
I'm not sure why do we have such a complicated wrapper

**Comment by LostNeophyte** [comment]
just do 
```lua
local command_resolver = require("null-ls.helpers.command_resolver")
require("null-ls").register({
  sources = {
    null_ls.builtins.diagnostics.eslint.with({
      dynamic_command = command_resolver.from_yarn_pnp(),
    }),
  },
})

**Comment by wizardlink** [comment]
That worked out great, just had to do some adjustments and also added a condition to it:
```lua
local command_resolver = require("null-ls.helpers.command_resolver")
require("null-ls").register({
  sources = {
    require("null-ls").builtins.diagnostics.eslint.with({
      dynamic_command = command_resolver.from_yarn_pnp(),
      conditions = function(utils)
        return utils.root_has_file({ ".pnp.cjs" })
      end
    }),
  },
})
```
Now I've hit a different roadblock because it seems that the bundled `eslint` with Yarn 3's sdk cannot find the proper path to deps (in workspaces) so I have to append the command that's called with `yarn pnpify` to essentially route the deps properly. From what I see in the [docs](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md) I'd assume `command` is the way to go but it wants an executable specifically.

Talking to a contributor though, they said that running `yarn eslint` by itself it finds dependencies so I'm not sure whether this is an environment issue or maybe it's my branch with different dep versions.

**Comment by wizardlink** [comment]
Alright, after a lot of tinkering... Ended up that I had local issues, removing all Yarn related files in the root of my user fixed all my issues, in this meantime I moved my containers to Fedora 37 to rule out potential issues there... Well, after installing all dependencies [listed in the prerequisites](https://www.lunarvim.org/docs/installation#prerequisites) I re-installed _LunarVim_ and now I'm having visual issues as seen here:
![image](https://user-images.githubusercontent.com/26727907/202335234-afde702e-fcc7-4655-95cf-99782479b8f5.png)
![image](https://user-images.githubusercontent.com/26727907/202335255-c01fcf1a-3b88-44fe-ab43-e27369b0c615.png)

Since this new issue is unrelated to the ESLint issues which was fixed with the snippet above, I'll close the issue here. But I'd like to know if it's worth the trouble opening a new issue here related to the screenshots above. For reference, if I save the file and it re-draws it looks fine, but the second I type and the floating windows are rendered, everything goes crazy again.

**Comment by peter-subsplash** [comment]
@wizardlink , after hours of struggling with eslint in a pnp project, your snippet fixed it like magic.

**Comment by LostNeophyte** [comment]
> Also, maybe a rewrite of such wrapper is due then?

I'd love to do it but it would be a breaking change, so maybe later (but it is on my todo list), the current one is quite limited. The next version will detect binaries from `yarn pnp` by default if it will be easy to implement
