### ISSUE TITLE
Overlaping inline information

### ISSUE THREAD

**Issue by brneor** [LunarVim/LunarVim#3490]
### Problem description

Lunarvim started showing some strange inline information that overlaps with what I'm typing. I don't know how explain any better what is going on so I'll drop a small screencast that shows the issue:

https://user-images.githubusercontent.com/5962898/202547447-af085a37-b41b-4d02-86c9-cc81cda689ed.mp4

Started happening today. I also tested on a virtual machine with a fresh Lunarvim install and see it happening too.

### LunarVim version

rolling-7d57046

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-336+g1f6d36c2c-dirty

### Operating system/version

Win 11; Fedora 37

### Steps to reproduce

1. Open any file
2. Start typing.

### support info

```console
# :LspInfo
Language client log: /home/brenoperes/.local/state/nvim/lsp.log
Detected filetype:   lua

1 client(s) attached to this buffer: 

Client: sumneko_lua (id: 1, pid: nil, bufnr: [3])
	filetypes:       lua
	autostart:       true
	root directory:  /home/brenoperes/.config/lvim
	cmd:             lua-language-server

Configured servers list: emmet_ls, eslint, sumneko_lua
```

```console
# :LvimInfo
    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                lua
* bufnr:                   3
* treesitter status:       active

Active client(s)
* name:                      sumneko_lua
* id:                        1
* supported filetype(s):     lua
* attached buffers:          3
* root_dir pattern:          3
* capabilities:              foldingRangeProvider      | documentSymbolProvider          | typeDefinitionProvider
                             documentHighlightProvider | documentRangeFormattingProvider | colorProvider
                             referencesProvider        | workspaceSymbolProvider         | documentFormattingProvider
                             definitionProvider        | hoverProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, spectral, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: [lua_format, stylua]

Linters info
* Active: 
* Supported: [luacheck, selene]

Code actions info
* Active: 
```

**Comment by LostNeophyte** [comment]
It's not an issue with lunarvim, it's somewhere else

**Comment by brneor** [comment]
Thks and sorry for the inconvenience, didn't saw the first issue.

**Comment by LostNeophyte** [comment]
No problem, a different person asked about the same thing on discord at the same time btw. I've got no idea what to do with the issue, doesn't seem like a neovim issue, it doesn't happen in an terminals. It's very weird

**Comment by LostNeophyte** [comment]
Wait, you also said windows 11 is the issue template, does it happen on windows as well?

**Comment by LostNeophyte** [comment]
I'll probably open an issue in neovim if one doesn't already exist

**Comment by brneor** [comment]
> Wait, you also said windows 11 is the issue template, does it happen on windows as well? Or is it a fedora vm in windows

My bad. It's a Fedora 37 WSL inside Windows 11, so still a Fedora 37... Doesn't happen in Lunarvim natively on Windows.
