### ISSUE TITLE
Encountered an error while updating lunarvim

### ISSUE THREAD

**Issue by akashdiphazra** [LunarVim/LunarVim#3495]
### Problem description

![Screenshot from 2022-11-18 11-10-01](https://user-images.githubusercontent.com/61003681/202631413-2760db9b-d1d1-4029-9dbf-1ef403a49139.png)

### LunarVim version

release-1.2/neovim-0.8-222a872

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-220+g234b8c5f3

### Operating system/version

Ubuntu 22.10

### support info

None

**Comment by LostNeophyte** [comment]
That's a timeout, you can go to ~/.local/share/lunarvim/lvim and run `git fetch`, then go back to lunarvim and update

**Comment by LostNeophyte** [comment]
I'll open a pr to increase the timeout to 10 seconds

**Comment by akashdiphazra** [comment]
Closing this  issue for now.
