### ISSUE TITLE
Troubletoggle generates Error while opening.

### ISSUE THREAD

**Issue by akashdiphazra** [LunarVim/LunarVim#3497]
### Problem description

Trouble toggle generates erros when press it's default keys are pressed
```lua
lvim.builtin.which_key.mappings["t"] = {
  name = "Diagnostics",
  t = { "<cmd>TroubleToggle<cr>", "trouble" },
  w = { "<cmd>TroubleToggle workspace_diagnostics<cr>", "workspace" },
  d = { "<cmd>TroubleToggle document_diagnostics<cr>", "document" },
  q = { "<cmd>TroubleToggle quickfix<cr>", "quickfix" },
  l = { "<cmd>TroubleToggle loclist<cr>", "loclist" },
  r = { "<cmd>TroubleToggle lsp_references<cr>", "references" },
}
```

![Screenshot from 2022-11-18 15-00-17](https://user-images.githubusercontent.com/61003681/202668811-dd8e06b0-b886-4ed5-ab5f-c496c0f0c3c6.png)

### LunarVim version

release-1.2/neovim-0.8-222a872

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-342+g282cbc235

### Operating system/version

Ubuntu 22.10

### support info

None

### Screenshots

[Screencast from 2022-11-18 14-55-05.webm](https://user-images.githubusercontent.com/61003681/202669726-99ae744b-539d-4d0d-a68b-c2a31abadb19.webm)

**Comment by cpea2506** [comment]
I'm not sure it was caused by `lvim`. You should try to create an issue in `Trouble` repo

**Comment by akashdiphazra** [comment]
I have raised an issue #https://github.com/folke/trouble.nvim/issues/236#issue-1460252817 , then closing this issue for now
