### ISSUE TITLE
Plugin error message is not easy to see on start up

### ISSUE THREAD

**Issue by shth** [LunarVim/LunarVim#3502]
### Problem description

1. install lvim normally
2. ensure you don't have python 3 module installed
3. include `{ "puremourning/vimspector" }` in the packer config
4. run :PackerSync
5. restart lvim

### Expected behaviour:
statusline shown error message `vimspector unavailable: Requires Vim compiled with +python3`

### Actual behaviour:
statusline flash the message very briefly or sometimes doesn't show it at all

### Comments
I was reinstalling it multiple time, but only after I tried installing vimspector in vanilla neovim I saw the message and figured it out. 

I also looked at the default log, neovim log and the packer log but the error wasn't found there.

This makes it very hard to debug what's gone wrong with the plugin. Would be nice if the message stayed like vanilla neovim. Or at least be logged in the log files.

Thanks!

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.8.0)

v0.8.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@HMBRW-A-001-M1-004.local  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"  Run :checkhealth for more info

### Operating system/version

macOS 12.5

### support info

N/A

### Screenshots

(Look very closely at bottom left corner, on the statusline)

https://user-images.githubusercontent.com/15711961/202884925-b0bb05e5-f969-43a8-9440-dd6521a09c7d.mov

**Comment by LostNeophyte** [comment]
does adding this to the your config.lua make the messages appear?
```lua
vim.schedule(function()
  vim.cmd "messages"
end)
```

**Comment by ChristianChiarulli** [comment]
I would test this on the new master branch since rolling is deprecated.

**Comment by LostNeophyte** [comment]
You can test by having a syntax error in your config, the error will be visible only for a short time,

 https://github.com/neovim/neovim/issues/17832 might be the cause. [this](https://github.com/LostNeophyte/LunarVim/commit/ccddba87363d9f4e8c0ac9199223d810a48f535e) should do as a workaround
