### ISSUE TITLE
How do I rebind keys for toggling ToggleTerm?

### ISSUE THREAD

**Issue by Lorryntz** [LunarVim/LunarVim#3503]
I want to map \<Ctrl\>+t to toggle float ToggleTerm, which is originally mapped to `<M-3>`. Here is what I did:
in `~/.config/lvim/config.lua` :
```
lvim.keys.normal_mode["<C-t>"] = ":ToggleTerm direction=float<CR>"
```
Now I can open it with \<Ctrl\>+t, but I can't close it by pressing \<Ctrl\>+t again. Where did I get wrong?

**Comment by LostNeophyte** [comment]
Use this: `lvim.builtin.terminal.open_mapping = [[<c-t>]]`
