### ISSUE TITLE
How do I map <Shift>+<Enter>?

### ISSUE THREAD

**Issue by Lorryntz** [LunarVim/LunarVim#3509]
I'm trying to map \<Shift\>+\<Enter\> to insert a blank line before, and what I did is add
```
lvim.keys.normal_mode["<S-CR>"] = "O<Esc>"
```
in `~/.config/lvim/config.lua`.
But lvim seems to keep recognizing \<Shift\>+\<Enter\> as \<Enter\>. What should I do?

**Comment by LostNeophyte** [comment]
Your terminal may not support that mapping

**Comment by LostNeophyte** [comment]
open lvim, go to insert mode and press `<C-v><S-CR>` and see what it prints, then try the same for just <CR>

**Comment by Lorryntz** [comment]
I got `^M` printed by `<C-v><S-CR>`. Does this mean I should try `lvim.keys.normal_mode["^M"] = "O<Esc>"` instead?

**Comment by LostNeophyte** [comment]
It means that your terminal doesn't support it, kitty prints '<S-CR>'
