### ISSUE TITLE
I want custom  formatter for c, c++ etc

### ISSUE THREAD

**Issue by kdamaski** [LunarVim/LunarVim#3513]
Greetings to the contributors of my favorite editor and the community! It seems that lunarvim has default formatter attached to some filetypes including c, c++. The problem is that i want format on save but i don't want the formatter to indent with shiftwidth = 2. And when i configure it like so 
![image](https://user-images.githubusercontent.com/64901487/203380860-e66e288a-0df1-486e-92e1-f67bf54db3dc.png)

(refering to the clang-format formatter)
i get : "warning: multiple different client offset_encodings detected for buffer, this is not supported yet" and doesn't work.

**Comment by LostNeophyte** [comment]
clang-format is the default with clangd, no need to add it to formatters

**Comment by LostNeophyte** [comment]
to configure indent width in clang-format use this file: https://gitlab.com/lostneophyte/smart-plug/-/blob/main/.clang-format

**Comment by LostNeophyte** [comment]
for the offset_encodings error: https://github.com/LunarVim/LunarVim/issues/2597#issuecomment-1254764973 and then run `:LvimCacheReset`

**Comment by kdamaski** [comment]
Thanks for replying! I am not  sure where to place the .clang-format config file though. i found this file :  <~/.local/share/lunarvim/site/pack/packer/start/telescope-fzf-native.nvim/.clang-format > which looked promising that it would affect the outcome but it doesn't. What i have done at the moment is installing the clang-format through mason and the binary is located in ~/.local/share/nvim/mason/bin/clang-format which is also in the Path. Should i place the .clang-format there?

**Comment by LostNeophyte** [comment]
You should place the file in your project

23 Nov 2022, 13:11 by ***@***.***:

**Comment by kdamaski** [comment]
That works! Thanks for the help <3 !

**Comment by LostNeophyte** [comment]
np :)

23 Nov 2022, 13:27 by ***@***.***:
