### ISSUE TITLE
bug: treesitter issue when saving my config

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#3515]
![image](https://user-images.githubusercontent.com/29136904/203504997-59ac32e4-9669-49a6-b8d9-f0736920a2dc.png)

**Comment by LostNeophyte** [comment]
Looks related: https://github.com/nvim-treesitter/nvim-treesitter/issues/3515

**Comment by jduhamel** [comment]
Same message for me on osx Neovim/HEAD-d7d3934

**Comment by ChristianChiarulli** [comment]
I just uninstalled markdown for now and turned off auto install @jduhamel

**Comment by jduhamel** [comment]
Failed to load parser: uv_dlsym: dlsym(0x9e007f00, tree_sitter_Markdown): symbol not found
What I don't understand is why it fails in lunar vim and not neovim. I've gone into neovim and tried to re-create it using a minimal config doing the TSInstall markdown and then opening the markdown but it works. 

More to learn I guess.
