### ISSUE TITLE
multi line cursor 

### ISSUE THREAD

**Issue by 0xMrR0b0t** [LunarVim/LunarVim#3516]
### Feature Description

please add multi line cursor like vs code vscode

**Comment by LostNeophyte** [comment]
you can use [this plugin](https://github.com/mg979/vim-visual-multi) in your config.  I haven't tested if it works in lvim, but it should. I think this feature is outside the scope of this project and it probably wouldn't be used by most people

**Comment by 0xMrR0b0t** [comment]
> you can use [this plugin](https://github.com/mg979/vim-visual-multi) in your config. I haven't tested if it works in lvim, but it should. I think this feature is outside the scope of this project and it probably wouldn't be used by most people

can you tell me how to add plugin in config

**Comment by LostNeophyte** [comment]
lvim.plugins = {
{"mg979/vim-visual-multi"},
}
