### ISSUE TITLE
Should the default config be empty?

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#3520]
Or at least slimmed down?

**Comment by LostNeophyte** [comment]
I'd cut it in half

**Comment by LostNeophyte** [comment]
something like [this](https://github.com/LostNeophyte/LunarVim/blob/simplify-default-config/utils/installer/config.example.lua)

**Comment by brneor** [comment]
When I first started using Lunarvim I was new to vim also. The current config file helped me a lot to understand Lunarvim's behavior and functionality and also vim's. I think this is something to consider.

**Comment by LostNeophyte** [comment]
> When I first started using Lunarvim I was new to vim also. The current config file helped me a lot to understand Lunarvim's behavior and functionality and also vim's. I think this is something to consider.

Would the linked one be good or is it too stripped down?

**Comment by brneor** [comment]
> > When I first started using Lunarvim I was new to vim also. The current config file helped me a lot to understand Lunarvim's behavior and functionality and also vim's. I think this is something to consider.
> 
> Would the linked one be good or is it too stripped down?

Had a look at it (and diff with previous version) and I think it looks good. Linking to docs was great.
