### ISSUE TITLE
Underscore width can't exceed hor20

### ISSUE THREAD

**Issue by nairobi02** [LunarVim/LunarVim#3522]
### Problem description

I've set

``` vim.opt.guicursor = "v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20,n:hor40-Cursor" ```

but there's no difference between hor20 and hor40

ie, when i switch from normal mode to replace mode, the cursor stays the same.

### LunarVim version

master-4d03f65

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

windows 10 wsl2 ubuntu 22.04

### Steps to reproduce

1. add ``` vim.opt.guicursor = "v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20,n:hor40-Cursor" ``` to config.lua

### support info

![lspinfo](https://user-images.githubusercontent.com/109964994/203789457-0a96fd1f-d42b-419a-9d24-39d2cf13f774.png)

### Screenshots

![replace mode](https://user-images.githubusercontent.com/109964994/203789582-cb808017-8a82-4fbb-ab11-c9f9ae7d1ef4.png)
![normal mode](https://user-images.githubusercontent.com/109964994/203789629-a46f167f-be61-4b38-bb2f-aa21ab1be9e0.png)

**Comment by LostNeophyte** [comment]
does the same happen in neovim?

**Comment by nairobi02** [comment]
> does the same happen in neovim?

No it does not

**Comment by LostNeophyte** [comment]
For me all the hor-x cursors have the same size in lvim and neovim

**Comment by zephaniahong** [comment]
hey @nairobi02! I am unable to replicate this issue as well. all hor(x) cursors have the same size for me too.
1. Could you show some screenshots of how your cursor looks like in neovim?
2. What terminal are you using?

Thanks!
