### ISSUE TITLE
support  golang  c/cpp  rust debug

### ISSUE THREAD

**Issue by fastfading** [LunarVim/LunarVim#3524]
### Feature Description

support  golang  c/cpp  rust debug
right now lvim did not support debug,
when I  click  debug button 
it always shows  
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/8351732/203932979-4f663444-af39-40d6-8cb2-fcd338e7458d.png">
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/8351732/203933114-c1ae103a-876a-4657-9904-67dfc93b2a28.png">

**Comment by LostNeophyte** [comment]
debugging is not supported out of the box, you need to configure it

cpp config: https://github.com/LunarVim/starter.lvim/tree/c-ide
rust config: https://github.com/LunarVim/starter.lvim/tree/rust-ide
