### ISSUE TITLE
Libcrypt not found on installation

### ISSUE THREAD

**Issue by SimonChaumet** [LunarVim/LunarVim#3527]
### Problem description

Install script fails with:

`rsync: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

0.8.1

### Operating system/version

archlinux

### Steps to reproduce

Steps to reproduce :

- run install script

### support info

not installed

### Screenshots

![image](https://user-images.githubusercontent.com/7894362/204030669-26955268-5392-43e6-aa06-80714fa3d252.png)

**Comment by LostNeophyte** [comment]
install `openssl`

**Comment by SimonChaumet** [comment]
openssl is installed and the lib is in /usr/lib

**Comment by LostNeophyte** [comment]
maybe try a system update

**Comment by LostNeophyte** [comment]
or if you don't want the backups, you can run the installer with the `--overwrite` flag

**Comment by SimonChaumet** [comment]
I tried the system update, with openssl, it didn't change anything.

With overwrite it works, but no backup

**Comment by LostNeophyte** [comment]
It's not really a lunarvim issue, it seems as rsync doesn't work on your system

**Comment by SimonChaumet** [comment]
rsync is not listed as a dependency

**Comment by LostNeophyte** [comment]
it's not required, since you can install it with `--overwrite`, but I agree that we need to list optional dependencies in the docs as well

**Comment by LostNeophyte** [comment]
Ideally, we shouldn't even need an installer, it should be a job of the package manager
