### ISSUE TITLE
Packer failed to update.

### ISSUE THREAD

**Issue by akashdiphazra** [LunarVim/LunarVim#3534]
### Problem description

Packer failed to update when i ran PackerUpdate 
![Ubuntu-2022-11-27-13-06-35](https://user-images.githubusercontent.com/61003681/204124364-1166a78b-a245-4a70-a31f-882645eaefaa.png)

### LunarVim version

release-1.2/neovim-0.8-222a872

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-342+g282cbc235

### Operating system/version

22.10

### support info

None

**Comment by LostNeophyte** [comment]
Try things from here https://www.lunarvim.org/docs/troubleshooting#plugin-issue

**Comment by akashdiphazra** [comment]
@LostNeophyte  Issue sloved!! 
This error arises when i tried update the lvim plugins in root mode inside terminal.
![Ubuntu-2022-11-27-14-33-41](https://user-images.githubusercontent.com/61003681/204127184-4b67a9a5-8843-4a66-a0f8-5a69a342f2f3.png)
