### ISSUE TITLE
Pywal.nvim doesn't quite work in the new update

### ISSUE THREAD

**Issue by nimaaskarian** [LunarVim/LunarVim#3536]
### Problem description

I reinstalled lunarvim v1.20 release (update didn't work somehow, so i reinstalled it using the bash script method on the [website](https://www.lunarvim.org/docs/installation#release)) and copied my `~/.config/lvim.old/config.lua` to `~/.config/lvim/config.lua`. then `PackerSync`ed and re-launched the program. 
Now [pywal.nvim]'s color doesn't apply on WhichKey, and some certain type of syntax highlighted text (like text between backtics in .md files) and the default (lunar theme) is applied instead.
I even tried this using nvim-nightly + lunarvim nightly. same results.
In the last version I had, I believe it was the version before v1.20 (in my shell history I see no `LV_BRANCH=`)
Even using the new configuration with just the pywal.nvim setup, same result.

### LunarVim version

1.20 and master-1fbcaf8

### Neovim version (>= 0.8.0)

NVIM v0.8.1 and NVIM v0.9.0-dev-e87dcc9

### Operating system/version

Arch Linux with 5.15.79-1-lts kernel

### Steps to reproduce

Reinstall lunarvim.
Copy old config.lua to default config.lua (old config.lua had AlphaTechnolog's pywal.nvim with its setup, and lvim.colorscheme set to 'pywal').
:PackerSync
Restart lunarvim

### support info

```console
# :LspInfo
 
 Language client log: /home/nima/.local/state/nvim/lsp.log
 Detected filetype:   lua
 
 1 client(s) attached to this buffer: 
 
 Client: sumneko_lua (id: 1, pid: nil, bufnr: [1])
 	filetypes:       lua
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             lua-language-server
 
 Configured servers list: sumneko_lua

# :LvimInfo

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                lua
* bufnr:                   1
* treesitter status:       active

Active client(s)
* name:                      sumneko_lua
* id:                        1
* supported filetype(s):     lua
* attached buffers:          1
* root_dir pattern:          1
* capabilities:              colorProvider             | documentFormattingProvider | workspaceSymbolProvider
                             hoverProvider             | typeDefinitionProvider     | documentSymbolProvider
                             foldingRangeProvider      | referencesProvider         | documentRangeFormattingProvider
                             documentHighlightProvider | definitionProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: [lua_format, stylua]

Linters info
* Active: 
* Supported: [luacheck, selene]

Code actions info
* Active: 

### Screenshots

![lvimbug](https://user-images.githubusercontent.com/88832088/204149185-27e99de5-36be-4e8b-8c8d-d553f022bc57.png)
![lvimbug2](https://user-images.githubusercontent.com/88832088/204149204-318b17ef-7fe1-4cd5-954c-2da9a8e9c3d3.png)

**Comment by LostNeophyte** [comment]
set both `lvim.colorscheme` and `lvim.bultin.theme.name` to the name of the colorscheme

**Comment by nimaaskarian** [comment]
> set both `lvim.colorscheme` and `lvim.bultin.theme.name` to the name of the colorscheme

Worked. Thanks
