### ISSUE TITLE
add a color schema 

### ISSUE THREAD

**Issue by fastfading** [LunarVim/LunarVim#3539]
### Feature Description

how to add a color schema in luanr vim

https://github.com/sainnhe/gruvbox-material/blob/master/doc/gruvbox-material.txt#L83
this color is very beatiful. 
how can I add this color in lunar vim, 
could it be integrated into the lunar vim by default ?

**Comment by LostNeophyte** [comment]
You can add it like any other plugin in lvim.plugins, then set lvim.colorsheme to the desired colorsheme's name

**Comment by fastfading** [comment]
> You can add it like any other plugin in lvim.plugins, then set lvim.colorsheme to the desired colorsheme's name

sorry ,  I am quite new to neovim and vim .   
that is why I use lunarvim which is the best and simplest neovim configure.
can you tell me how to add this plugin in detail ?

**Comment by LostNeophyte** [comment]
it's explained in the docs [here](https://www.lunarvim.org/docs/plugins#user-plugins)

**Comment by fastfading** [comment]
> it's explained in the docs [here](https://www.lunarvim.org/docs/plugins#user-plugins)

there is no nvim file in https://github.com/sainnhe/gruvbox-material
still no idea how to do that

**Comment by LostNeophyte** [comment]
There doesn't need to be a nvim file there


Nov 28, 2022, 09:32 by ***@***.***:

**Comment by fastfading** [comment]
sorry ,  I am  not an expert on vim or nvim 
any quick solution ?

**Comment by LostNeophyte** [comment]
```lua
lvim.plugins = {
  {sainnhe/gruvbox-material"},
}
lvim.colorscheme = "..."

**Comment by fastfading** [comment]
thank you , it works. 
your configuration is awesome.    
this is the simplest neovim configure,   I have ever seen 

star  fork   and watched

**Comment by fastfading** [comment]
" For dark version.
set background=dark
" Set contrast.
" This configuration option should be placed before `colorscheme gruvbox-material`.
" Available values: 'hard', 'medium'(default), 'soft'
let g:gruvbox_material_background = 'hard'
" For better performance
let g:gruvbox_material_better_performance = 1

let g:gruvbox_material_diagnostic_text_highlight = 1
" let g:gruvbox_material_diagnostic_line_highlight = 1
let g:gruvbox_material_diagnostic_virtual_text = "colored"
let g:gruvbox_material_sign_column_background = 'none'

colorscheme gruvbox-material


how to do this configurations in lua ?

**Comment by LostNeophyte** [comment]
`set background=dark` unfortunately won't currently work, we have a bug

for the rest you can change `let g:option = x` to `vim.g.option = x` and put it in config.lua

**Comment by fastfading** [comment]
> `set background=dark` unfortunately won't currently work, we have a bug

so there is no way to "set tabstop=4" in vim  neither.
anywork around ?

**Comment by LostNeophyte** [comment]
There is it's just background that doesn't work https://gitlab.com/lostneophyte/dotfiles/-/blob/43535c8903d849db31836d5aa605d3c1d5bb5281/lvim/.config/lvim/lua/user/options.lua#L3-4


29 Nov 2022, 07:06 by ***@***.***:

**Comment by fastfading** [comment]
https://github.com/907th/vim-auto-save

let g:auto_save_events = ["InsertLeave", "TextChanged"]

how to configure this array  in  lua    ?
