### ISSUE TITLE
plenary logs are written to .cache/nvim and not .cache/lvim

### ISSUE THREAD

**Issue by LostNeophyte** [LunarVim/LunarVim#3541]
`:lua print(vim.api.nvim_call_function("stdpath", { "cache" }))` (that's what plenary is using) returns `.cache/nvim`
for this reason :NullLsLog opens the wrong file which is empty

**Comment by carlosflorencio** [comment]
@LostNeophyte Newbie in neovim here, but the other locations `state`, `data` and `config` are also pointing to an `nvim` folder instead of `lvim`, is it expected?
