### ISSUE TITLE
lvim  indent by language

### ISSUE THREAD

**Issue by fastfading** [LunarVim/LunarVim#3552]
### Feature Description

I found my lvim always ident by 2 space .

I  set  
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4

it works in golang now,  since golang use tab instead of space 

but c lang always format it as 2 space,  
there is chaos in c/cpp,  but normally people use 4 space instead of tab. 
how can we change that ?

**Comment by LostNeophyte** [comment]
you can create an autocommand to do that like this: https://gitlab.com/lostneophyte/dotfiles/-/blob/39e11d4b56cd603064b446dbd1c84b318fd21ae1/lvim/.config/lvim/config.lua#L64-71

**Comment by pplmx** [comment]
how to configure it? Is there any instruction?
