### ISSUE TITLE
Parity with vim on `gq` for formatting to textwidth

### ISSUE THREAD

**Issue by nettrino** [LunarVim/LunarVim#3553]
### Problem description

Hello, 

I recently switched to lunarvim from vim and have [this single file config](https://github.com/nettrino/dotfiles/blob/master/config.lua). Everything is working fine but I haven't been able to get simple wrapping on 80 columns to work as it used to do with vim. Essentially I want the autoformatters to do their thing as they do, but If I press gq I would want lunarvim to just wrap whatever text to textwidth settings. Actually, if there is no LSP or formatter, I just want this to be the default. What is the easiest way to do this? 

### LunarVim version

master-40ec8a0

### Neovim version (>= 0.8.0)

v0.9.0-dev-327+gc404f9b4b-dirty

### Operating system/version

mac os x 12.5.1

### Steps to reproduce

Please see [this config](https://github.com/nettrino/dotfiles/blob/master/config.lua)

**Comment by nettrino** [comment]
Probably this is not a bug - more of a question / request on config, however documenting it here instead of discord for reference for other users

**Comment by LostNeophyte** [comment]
resolved on discord, if someone finds this: you can use `gw` to format using textwidth

**Comment by zztczcx** [comment]
do we know why it was changed to `gw` ?

**Comment by LostNeophyte** [comment]
> do we know why it was changed to `gw` ?

it was not changed, that's how neovim works, 
`gq` will use `formatexpr` which we set to lsp formatting to allow easy range formatting
`gw` uses vim internal formatting only

**Comment by pillmuncher** [comment]
> you can use `gw` to format using textwidth

That only works in visual mode. It should also work in normal mode for the paragraph under the cursor.

**Comment by LostNeophyte** [comment]
> > you can use `gw` to format using textwidth
> 
> That only works in visual mode. It should also work in normal mode on the paragraph under the cursor.

it does work in normal mode
e.g.
`gww` format current line (same as gqq)
`gwip` format current paragraph (same as gqip)
