### ISSUE TITLE
Pasting a outside-lunarvim-workspace file into a folder opened inside LunarVim's File Explorer

### ISSUE THREAD

**Issue by rootex-** [LunarVim/LunarVim#3554]
### Feature Description

Trying to get a full IDE experience out of LunarVim and often find myself struggling with a series of use typical cases.
Let me describe one of such typical use cases.

As a user, I want to be able to copy a file from any doesn't-matter-what-random place to a Lunarvim File Explorer:
1. Copy file (e.g. from IntelliJ IDEA or a system file manager).
2. Enter Lunarvim. 
3. Open Lunarvim's File Explorer.
4. Put a cursor at a folder where I'd like to paste this file.
5. Press P to paste this file
6. Nothing happens. 

Are there any preconfigured ways to accomplish this? 

PS: 
It would be great to create some sort of a CookBook with receipts that would help to turn LunarVim into an IDE for easier migration to LunarVim. Since many obvious use cases for a regular IDE like IntelliJ IDEA require a solid amount of googling and digging into the docs. That slows down overall efficiency and comfort of switching to LunarVim.

**Comment by LostNeophyte** [comment]
the file explorer plugin is [nvim-tree](https://github.com/nvim-tree/nvim-tree.lua), I'm not sure if they support that, you can ask on their github, I'll let you know if I find something
