### ISSUE TITLE
How to configure lvim make dot directory visiable

### ISSUE THREAD

**Issue by baoyachi** [LunarVim/LunarVim#3556]
### Feature Description

my real directory:
```bash
➜  tree -a -d -L 2
.
├── .git
│   ├── hooks
│   ├── info
│   ├── logs
│   ├── objects
│   └── refs
├── .github
│   └── workflows
├── .idea
├── dm-helper
│   ├── src
├── docker
│   └── driver
➜
```

But livm file directory structure invisiable `.git`,`.idea`,`.github` ... dot files.

So how to set configure make dot files visiable

**Comment by LostNeophyte** [comment]
where do you want hidden files to be visible? in lir(explorer opened with `lvim directory`) or nvimtree(side explorer opened by `leader e`)

**Comment by LostNeophyte** [comment]
in lir it's `lvim.builtin.lir.show_hidden_files = true`

**Comment by baoyachi** [comment]
> show_hidden_files

Thx, I configured it in `/Users/baoyachi/. config/lvim/config.lua`. Now it takes effect and hidden files can be seen.

**Comment by baoyachi** [comment]
> show_hidden_files

Thx, I configured it in `/Users/baoyachi/. config/lvim/config.lua`. Now it takes effect and hidden files can be seen.
