### ISSUE TITLE
live_grep support previous search  and  glob

### ISSUE THREAD

**Issue by fastfading** [LunarVim/LunarVim#3560]
### Feature Description

<leader>st
1. support  find previous/next search  text
2. support glob found ,  set a sub folder  or  a  pattern   for example :       search_txt   -g   subfoler/*.go

**Comment by LostNeophyte** [comment]
live grep is a feature of telescope, a separate plugin, you can use <c-j/k> for history

**Comment by fastfading** [comment]
telescope   live grep has a bug , 
the first time you use it , it will search files under work path. then press enter to enter that file
the second time you use it ,  it will search up level path,  and get more result that you don't need.

I try to use  live_grep_args  to set  grep file folder and file pattern
 lvim.keys.normal_mode["<leader>sg"] = ":lua require('telescope').extensions.live_grep_args.live_grep_args()<CR>"
but the get the same issue above

another issues ,  is that  the  live grep  only show parts of the result
<img width="806" alt="image" src="https://user-images.githubusercontent.com/8351732/205224395-602854db-bd26-4c9c-8979-a442332b825a.png">
how to make the window bigger and show more info
