### ISSUE TITLE
Error detected while processing BufEnter Autocommands for "*"

### ISSUE THREAD

**Issue by Jc-Meet** [LunarVim/LunarVim#3561]
### Problem description

![image](https://user-images.githubusercontent.com/109884231/204964318-52431ed6-bacb-42af-8eb2-1aafcf8f71d4.png)

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

neovim-0.8-8f4a7bd

### Operating system/version

windows 11

### Screenshots

![image](https://user-images.githubusercontent.com/109884231/204964293-2623ee8a-ce6b-48b7-ac5f-ecd62e359681.png)

**Comment by LostNeophyte** [comment]
Does that happen with an empty config?

**Comment by ionutvmi** [comment]
I also have this issue with a fresh install on windows 10

```
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua ...ing\lunarvim\site\pack\packer\start\lir.nvim/lua\lir.lua:235: Vim(lua):E5108: Error executing lua ...ck\packer\start\lir.nvim/lua\lir\float\curdir_window.lua:117: attempt to index field 'float' (a nil value)
stack traceback:
        ...ck\packer\start\lir.nvim/lua\lir\float\curdir_window.lua:117: in function '_LirFloatSetCurdirText'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_buf_set_option'
        ...ing\lunarvim\site\pack\packer\start\lir.nvim/lua\lir.lua:235: in function 'init'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'nvim_buf_set_option'
        ...ing\lunarvim\site\pack\packer\start\lir.nvim/lua\lir.lua:235: in function 'init'
        [string ":lua"]:1: in main chunk
```

It happens when i attempt to open a folder.

```
# no error
lvim
lvim config.lua

# error
lvim .
lvim some-folder
```

**Comment by LostNeophyte** [comment]
try running `:PackerSync`

**Comment by ionutvmi** [comment]
After experimenting a bit I found that the installation of the plugins was not completed successfully because the C compiler was not in the path.

On this computer I had Visual studio installed so what I did is the following:

1. Started the developer command prompt
<img width="265" alt="image" src="https://user-images.githubusercontent.com/3531898/205025808-50aaddad-561f-4a87-8c68-0c42cf09353e.png">

2. Started pwsh from there and then started lvim
```
pwsh
lvim
:PackerSynch
```

After the initial install it doesn't look like we need the C compiler anymore.

**Comment by LostNeophyte** [comment]
the compiler is a dependency of treesitter

**Comment by ionutvmi** [comment]
one idea would be to check for it in the install.ps1 script and if it's missing show a helpful error/warning message

**Comment by Jc-Meet** [comment]
Thank you for your enthusiastic help. I am just a beginner in programming. Maybe vim is not suitable for me. I think I will return to the embrace of vscode

**Comment by aaronArinder** [comment]
@JChaooo: hopefully you returned to vim!
