### ISSUE TITLE
FreeBSD and clangd

### ISSUE THREAD

**Issue by mekanix** [LunarVim/LunarVim#3564]
When I try `LspInstall clangd` I get the message that the OS or architecture is not supported. I do have `clangd` executable on the system, so I'm not sure what is reporting the error. Can you help me find the cause of error so I can try and fix it, please?

**Comment by LostNeophyte** [comment]
if you have it installed and it's in your $PATH, then you don't need to run LspInstall

**Comment by jimkoen** [comment]
> if you have it installed and it's in your $PATH, then you don't need to run LspInstall

Note that on FreeBSD, clangd is not part of the system clang installation and needs to be installed from ports via PKG. In this case, the clangd binary will be named after the major version of llvm installed, which as of today would be clangd16.

So regardless of whether clangd is in PATH, FreeBSD naming prohibits LunarVim from picking up the binary. It would be cool if we could set either a path to the binary ourselves, or have LunarVim detect the naming scheme.
