### ISSUE TITLE
Inconsistent indent-blankline.nvim when `show_current_context = false`

### ISSUE THREAD

**Issue by subhajit-halder** [LunarVim/LunarVim#3565]
### Problem description

Steps to reproduce : 
1. Try out the below configs separately.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.1, Build type: Release, LuaJIT 2.1.0-beta3 

### Operating system/version

Pop!_OS 22.04 LTS

### Screenshots

Below config ...
```
lvim.builtin.indentlines.options = {
  show_current_context = true,
}
```
Does this
 
![image](https://user-images.githubusercontent.com/54535412/205338522-30211b3b-dff8-4ab8-b796-2c4c5caa0b74.png)

While ...

```
lvim.builtin.indentlines.options.show_current_context = true
```
Does this

![image](https://user-images.githubusercontent.com/54535412/205338677-372b5c52-d5fe-4a47-a0a2-5c847196d6a2.png)

**Comment by LostNeophyte** [comment]
I'm the first config you're deleting the rest of the options. In the second you're only changing one
