### ISSUE TITLE
Rsync Error

### ISSUE THREAD

**Issue by MarioAvolio** [LunarVim/LunarVim#3566]
### Problem description

1. $ LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
2.  Choose dependencies
3.  Error: 
```
--------------------------------------------------------------------------------
Backing up old /home/mario/.config/lvim to /home/mario/.config/lvim.old
--------------------------------------------------------------------------------
Backing up old /home/mario/.local/share/lunarvim to /home/mario/.local/share/lunarvim.old
--------------------------------------------------------------------------------
Backing up old /home/mario/.cache/lvim to /home/mario/.cache/lvim.old
rsync: [sender] change_dir "/home/mario/.cache/lvim" failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1336) [sender=3.2.7]
```

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

0.8.1

### Operating system/version

Kernel: 6.0.10-zen2-1-zen -- OS: EndeavourOS Linux x86_64

### Screenshots

![2022-12-03T10:51:21,426790919+01:00](https://user-images.githubusercontent.com/64833154/205434948-0b63221d-0376-4553-a7c0-b2a2b3276b31.png)

**Comment by LostNeophyte** [comment]
you can run the installer with the --overwrite flag as a workaround, it will delete your lvim config, so back it up somewhere
