### ISSUE TITLE
Lunarvim not installing

### ISSUE THREAD

**Issue by Pyrole-2002** [LunarVim/LunarVim#3567]
### Problem description

I checked the lunarvim website and copy pasted the install command on my terminal:

OS: Manjaro
Terminal: Kitty
Command Ran: `LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`

I see no output on the terminal and the command simply ends running after exactly 2 min 9 sec.
`lvim` is not installed and i see no change overall.

### LunarVim version

NA

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

Manjaro Linux x86_64

**Comment by lordirah** [comment]
Am also facing same issue on fedora. Installation script runs forever

**Comment by LostNeophyte** [comment]
It doesn't even show the logo, no output at all?

**Comment by LostNeophyte** [comment]
And do you have the [prerequisites](https://www.lunarvim.org/docs/installation#prerequisites) installed?

**Comment by Pyrole-2002** [comment]
@LostNeophyte absolutely nothing, i run it it waits (or does something) for 2 min 9 sec and then ends without any output and its as if nothing happened
![image](https://user-images.githubusercontent.com/78760369/205485783-55b6b59e-0c6f-4cbc-b394-c16aa41ca00a.png)

I did check if the mentioned prerequisites were there.
![image](https://user-images.githubusercontent.com/78760369/205485844-5c3a049d-e247-47c0-a853-57f92d83bea9.png)

**Comment by LostNeophyte** [comment]
What if you download the installer script and run it `LV_BRANCH='release-1.2/neovim-0.8' ~/Downloads/installer.sh` (don't forget to make it executable)

**Comment by Pyrole-2002** [comment]
Can you tell me where the installer script is?

**Comment by LostNeophyte** [comment]
download this https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh

**Comment by Pyrole-2002** [comment]
Should i just download the installer script or clone the entire repo?

**Comment by LostNeophyte** [comment]
just the script

**Comment by Pyrole-2002** [comment]
Ok something really weird happened:

I manually downloaded the installer script and it did work and showed the logo.....
Then just for curiosity I tried running the original installer command and it also started working.

**Comment by LostNeophyte** [comment]
> Ok something really weird happened:
> 
> I manually downloaded the installer script and it did work and showed the logo..... Then just for curiosity I tried running the original installer command and it also started working.

Yup, that's quite weird, I don't know what could cause that

**Comment by Pyrole-2002** [comment]
Undefined behavious i swear XD
