### ISSUE TITLE
Is it possible to pass clangd arguments to lvim.

### ISSUE THREAD

**Issue by akashdiphazra** [LunarVim/LunarVim#3568]
### Problem description

make clangd use c++17 version for every c/c++ files.

### LunarVim version

release-1.2/neovim-0.8-222a872

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-220+g234b8c5f3

### Operating system/version

Ubuntu 22.10

### Affected language servers

clangd

### Steps to reproduce

None

### Actual behavior

None

### support info

None

**Comment by LostNeophyte** [comment]
nlspsettings (:LspSettings plugin) unfortunately doesn't support clangd https://github.com/tamago324/nlsp-settings.nvim/issues/7

currently the only way do do that is to override the settings completely https://www.lunarvim.org/docs/languages#server-override

**Comment by akashdiphazra** [comment]
@LostNeophyte  another way is to use compile_flags.txt file in every project. It worked after had to spend 1 hour by going through clangd docs and issues on github.

**Comment by LostNeophyte** [comment]
oh, I though you wanted it for every project, in that case you can also use compile_commands and 

[.clangd:](https://gitlab.com/lostneophyte/esponoff/-/blob/main/.clangd)
```
CompileFlags:
  Add: [-std=c++17, -Wall, -Wextra, -pedantic, -Wshadow, -Wnon-virtual-dtor, -Wimplicit-fallthrough, -Wlifetime ]
```
