### ISSUE TITLE
Tailwindcss intellisense not working

### ISSUE THREAD

**Issue by imsumoregn** [LunarVim/LunarVim#3570]
### Problem description

No hover docs, no auto-completion. Everything is gone after a night. Tested on both stable release and nightly version. Also, attempt to grab hover docs returned `tailwindcss: -32601: Unhandled method textDocument/hover`.

On a lighter note, I have a suspicion that something is wrong with the intellisense itself, since it's failing not only in Neovim, but also in JetBrains IDEs. Haven't tested on VSCode, though.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

`NVIM v0.9.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-jfFJbo/neovim-0.9.0~ubuntu1+git202211230021-cd386b2c7-333b5866f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-jfFJbo/neovim-0.9.0~ubuntu1+git202211230021-cd386b2c7-333b5866f/build/cmake.config -I/build/neovim-jfFJbo/neovim-0.9.0~ubuntu1+git202211230021-cd386b2c7-333b5866f/src -I/build/neovim-jfFJbo/neovim-0.9.0~ubuntu1+git202211230021-cd386b2c7-333b5866f/.deps/usr/include -I/usr/include -I/build/neovim-jfFJbo/neovim-0.9.0~ubuntu1+git202211230021-cd386b2c7-333b5866f/build/src/nvim/auto -I/build/neovim-jfFJbo/neovim-0.9.0~ubuntu1+git202211230021-cd386b2c7-333b5866f/build/include Compiled by buildd@lcy02-amd64-027`

### Operating system/version

Ubuntu 20.04.

**Comment by LostNeophyte** [comment]
you chose the wrong issue template it should be LSP, send screenshots of `:LspInfo` `:LvimInfo` after opening a file where tailwincss should be working, and the last lines of the log from `leader L l L`

**Comment by LostNeophyte** [comment]
What could I change in the name/description of the issue templates to make that more clear btw,?

**Comment by imsumoregn** [comment]
My bad, here are the screenshots.

![image](https://user-images.githubusercontent.com/87747324/205571169-ec0f0164-90f3-4df2-812d-a20674a9a1bc.png)
![image](https://user-images.githubusercontent.com/87747324/205571176-2dfa3112-e768-474b-9d34-8b00df543891.png)
![image](https://user-images.githubusercontent.com/87747324/205571184-9b95d91f-f4e8-49f6-885f-6990fe73a662.png)

About the issue template, I don't think it could be any clearer, it just that for a person who is not too familiar with the business like me, Tailwindcss intellisense didn't seem to have anything to do with LSP, because Tailwindcss itself is not a language, so yeah, everyday you learn a new thing, thanks in advanced for the quick support. Besides, adding a few examples to the issue template's description may help if the misunderstanding happens too often.

**Comment by LostNeophyte** [comment]
Yea, from the screenshots everything looks ok, clear the log(`ggVGd:w<cr>`), restart lvim, open the file and send the full log here in code blocks

as for the issue template, will adding intelisense to the parenthesis do?

**Comment by imsumoregn** [comment]
There're only 2 lines in the log, one saying LSP logging initiated, and the other one is exactly the same as above.

And yes, adding that definitely help for situations like mine.

**Comment by LostNeophyte** [comment]
does it work in a different project?

**Comment by imsumoregn** [comment]
I was about to reply no immediately, because I've tested on other projects already, but my guts told me something and I create a new Next app, and it works. So what do suggest?

**Comment by LostNeophyte** [comment]
maybe try chanigng the tailwindcss config, clearing project local cache, I've never used tailwind so unfortunately can't help further

**Comment by imsumoregn** [comment]
Oh it's alright, I'll try something, thank you for your time.
