### ISSUE TITLE
Using C-h, j, k, or l to change vim windows does not work out of the box, nor does setting it manually.

### ISSUE THREAD

**Issue by sbcowan** [LunarVim/LunarVim#3572]
### Problem description

1. Install and make neovim from source following [these steps](https://github.com/neovim/neovim/wiki/Building-Neovim).
2. install lunarvim with `bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)` as given on the installation page
3. Open lunarvim with `lvim`, then make a split, and attempt using C-h, j, k, or l

My config.lua:
```
--[[
 THESE ARE EXAMPLE CONFIGS FEEL FREE TO CHANGE TO WHATEVER YOU WANT
 `lvim` is the global options object
]]

-- vim options
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.relativenumber = true

-- general
lvim.log.level = "info"
lvim.format_on_save = {
  enabled = true,
  pattern = "*.lua",
  timeout = 1000,
}
-- to disable icons and use a minimalist setup, uncomment the following
-- lvim.use_icons = false

-- keymappings <https://www.lunarvim.org/docs/configuration/keybindings>
lvim.leader = "space"
-- add your own keymapping
lvim.keys.normal_mode["<C-s>"] = ":w<cr>"
lvim.keys.normal_mode["C-l"] = "<C-w>l" -- Added manually
lvim.keys.normal_mode["C-h"] = "<C-w>h" -- Added manually

-- lvim.keys.normal_mode["<S-l>"] = ":BufferLineCycleNext<CR>"
-- lvim.keys.normal_mode["<S-h>"] = ":BufferLineCyclePrev<CR>"

-- -- Use which-key to add extra bindings with the leader-key prefix
-- lvim.builtin.which_key.mappings["W"] = { "<cmd>noautocmd w<cr>", "Save without formatting" }
-- lvim.builtin.which_key.mappings["P"] = { "<cmd>Telescope projects<CR>", "Projects" }

-- -- Change theme settings
-- lvim.colorscheme = "lunar"

-- After changing plugin config exit and reopen LunarVim, Run :PackerSync
lvim.builtin.alpha.active = true
lvim.builtin.alpha.mode = "dashboard"
lvim.builtin.terminal.active = true
lvim.builtin.nvimtree.setup.view.side = "left"
lvim.builtin.nvimtree.setup.renderer.icons.show.git = false

-- Automatically install missing parsers when entering buffer
lvim.builtin.treesitter.auto_install = true

-- lvim.builtin.treesitter.ignore_install = { "haskell" }

-- -- generic LSP settings <https://www.lunarvim.org/docs/languages#lsp-support>

-- --- disable automatic installation of servers
-- lvim.lsp.installer.setup.automatic_installation = false

-- ---configure a server manually. IMPORTANT: Requires `:LvimCacheReset` to take effect
-- ---see the full default list `:lua =lvim.lsp.automatic_configuration.skipped_servers`
-- vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "pyright" })
-- local opts = {} -- check the lspconfig documentation for a list of all possible options
-- require("lvim.lsp.manager").setup("pyright", opts)

-- ---remove a server from the skipped list, e.g. eslint, or emmet_ls. IMPORTANT: Requires `:LvimCacheReset` to take effect
-- ---`:LvimInfo` lists which server(s) are skipped for the current filetype
-- lvim.lsp.automatic_configuration.skipped_servers = vim.tbl_filter(function(server)
--   return server ~= "emmet_ls"
-- end, lvim.lsp.automatic_configuration.skipped_servers)

-- -- you can set a custom on_attach function that will be used for all the language servers
-- -- See <https://github.com/neovim/nvim-lspconfig#keybindings-and-completion>
-- lvim.lsp.on_attach_callback = function(client, bufnr)
--   local function buf_set_option(...)
--     vim.api.nvim_buf_set_option(bufnr, ...)
--   end
--   --Enable completion triggered by <c-x><c-o>
--   buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")
-- end

-- -- linters and formatters <https://www.lunarvim.org/docs/languages#lintingformatting>
-- local formatters = require "lvim.lsp.null-ls.formatters"
-- formatters.setup {
--   { command = "stylua" },
--   {
--     command = "prettier",
--     extra_args = { "--print-with", "100" },
--     filetypes = { "typescript", "typescriptreact" },
--   },
-- }
-- local linters = require "lvim.lsp.null-ls.linters"
-- linters.setup {
--   { command = "flake8", filetypes = { "python" } },
--   {
--     command = "shellcheck",
--     args = { "--severity", "warning" },
--   },
-- }

-- -- Additional Plugins <https://www.lunarvim.org/docs/plugins#user-plugins>
-- lvim.plugins = {
--     {
--       "folke/trouble.nvim",
--       cmd = "TroubleToggle",
--     },
-- }

-- -- Autocommands (`:help autocmd`) <https://neovim.io/doc/user/autocmd.html>
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = "zsh",
--   callback = function()
--     -- let treesitter use bash highlight for zsh files as well
--     require("nvim-treesitter.highlight").attach(0, "bash")
--   end,
-- })

```

### LunarVim version

master-33e0960

### Neovim version (>= 0.8.0)

NVIM v0.8.1

### Operating system/version

macOS 13.0

**Comment by k4-100** [comment]
I suffer from similar issue.
even though I installed it today (linux mint).

**Comment by LostNeophyte** [comment]
```lua
lvim.keys.normal_mode = {
  -- Better window movement
  ["<C-h>"] = "<C-w>h",
  ["<C-j>"] = "<C-w>j",
  ["<C-k>"] = "<C-w>k",
  ["<C-l>"] = "<C-w>l",
}
```

```diff
-lvim.keys.normal_mode["C-l"] = "<C-w>l" -- Added manually
+lvim.keys.normal_mode["<C-l>"] = "<C-w>l" -- Added manually
```

**Comment by sbcowan** [comment]
> It is bound by default though, and does work with an empty config for me
Precisely, that's why it is odd. Do you have any ideas as to what it could be?

**Comment by LostNeophyte** [comment]
what does `:map <C-l>` print, and does `<C-w>l` work? (you can change `l` to h/j/k)

**Comment by sbcowan** [comment]
`:map <C-l>` prints: `n <C-l>  <C-W>l`

<C-w>h, j, k, l does work

**Comment by LostNeophyte** [comment]
> h, j, k, l does work

and if you use h after pressing <C-w>, will it go the the left split?

**Comment by sbcowan** [comment]
Sorry, I meant `<C-w> h, j, k, l `. So `<C-w> h`, does let me go to the left split

**Comment by LostNeophyte** [comment]
does it work after this command `:lua vim.keymap.set("n", "<C-h>","<C-w>h")` ?

**Comment by sbcowan** [comment]
No it does not. (I tried using it immediately after executing the command, and also after sourcing the config file and after restarting my kernel)

**Comment by LostNeophyte** [comment]
`:noremap <C-h> <C-w>h` maybe this?

**Comment by sbcowan** [comment]
I think it might have to do with another program, or Neovim installation maybe that is overriding this command. It is strange, because earlier in the day, I had a different neovim config (not Lunarvim), and this command did work, which makes it more frustrating.

**Comment by sbcowan** [comment]
> :noremap <C-h> <C-w>h maybe this?

Nope :(

**Comment by LostNeophyte** [comment]
check if any of there commands work in `nivm --clean`

**Comment by sbcowan** [comment]
In `nvim --clean`, when adding `:noremap <C-h> <C-w>h`, it does work! I guess I could try reinstalling lunarvim or something?

**Comment by LostNeophyte** [comment]
yea, you can try that, I've got no idea what could cause it to not work in lvim

**Comment by sbcowan** [comment]
Thanks for your help. I might return if that doesn't work.

**Comment by NurdinDev** [comment]
I have the same issue, did you solve it @sbcowan ?

**Comment by TonyK922** [comment]
Well, I am not the only one running into this issue.

**Comment by Derek-Xiang** [comment]
I have the issue as well. I just started to move my own config from nvim to lvim and what I found is all the bindings with <C-h> or with jkl, just doesn't work, so I also can't use <C-hjkl> on telescope neither. Anyone have some solutions?

**Comment by nathanjcollins** [comment]
I'm having the same issue here, new install of LunarVim on Windows 11. Ctrl+h/l not working to navigate between buffers.

**Comment by webdavis** [comment]
> I have the issue as well. I just started to move my own config from nvim to lvim and what I found is all the bindings with or with jkl, just doesn't work, so I also can't use on telescope neither. Anyone have some solutions?

I'm having the same issue.

**Comment by nikisix** [comment]
Same issue.

**Comment by nikisix** [comment]
> ```lua
> lvim.keys.normal_mode = {
>   -- Better window movement
>   ["<C-h>"] = "<C-w>h",
>   ["<C-j>"] = "<C-w>j",
>   ["<C-k>"] = "<C-w>k",
>   ["<C-l>"] = "<C-w>l",
> }
> ```
> 
>  ```diff
> -lvim.keys.normal_mode["C-l"] = "<C-w>l" -- Added manually
> +lvim.keys.normal_mode["<C-l>"] = "<C-w>l" -- Added manually
> ```

not working for me
