### ISSUE TITLE
lsp_signature  did  not run well in lunarvim

### ISSUE THREAD

**Issue by fastfading** [LunarVim/LunarVim#3581]
### Problem description

https://github.com/ray-x/lsp_signature.nvim

I use default configure

it does not run well 
when I enter parameter ,  the input curser quit automatically .

-- recommended:
require'lsp_signature'.setup(cfg) -- no need to specify bufnr if you don't use toggle_key

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

nvim 0.8

### Operating system/version

macos 13

### Affected language servers

golang 

### Actual behavior

it does not run well 
when I enter parameter ,  the input curser quit automatically .

### support info

no

**Comment by fastfading** [comment]
may be we should consider  
https://github.com/hrsh7th/cmp-nvim-lsp-signature-help
but how to integrate this in   lunarvim  since lunar already has   lvim.builtin.cmp

**Comment by LostNeophyte** [comment]
I use this plugin, and there are no lunarvim specific problems

**Comment by fastfading** [comment]
I used  https://github.com/hrsh7th/cmp-nvim-lsp-signature-help
It work perfect

**Comment by young03600** [comment]
> I used https://github.com/hrsh7th/cmp-nvim-lsp-signature-help It work perfect

Hi, I'm new to use LunarVim as my editor.
I also want to use the signature help plugin.
But it seems not work for me after I add the plugin to my config
how can I setup cmp-nvim-lsp-signature-help for my editor?
