### ISSUE TITLE
java DevTools not reload my spring-boot app

### ISSUE THREAD

**Issue by IBugraGezer** [LunarVim/LunarVim#3590]
### Problem description

I installed DevTools to my spring boot project. It reloads the project when using eclipse but not when using lunarvim.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

v0.8.1

### Operating system/version

fedora 36

### Steps to reproduce

1. Create a spring boot project
2. Add DevTools dependency
3. Change anything and refresh the page

**Comment by Lcarv20** [comment]
I am having the same problem, what I know so far is that, after adding the devtools as dep, you run the project on a separate terminal, and then whenever you make a change you have to compile on another separate terminal the runing terminal will capture the changes. I know it's annoying but that's what I've found so far.

also according to [spring docs](https://docs.spring.io/spring-boot/docs/2.0.x/reference/html/using-boot-devtools.html):

> As DevTools monitors classpath resources, the only way to trigger a restart is to update the classpath. The way in which you cause the classpath to be updated depends on the IDE that you are using. In Eclipse, saving a modified file causes the classpath to be updated and triggers a restart. In IntelliJ IDEA, building the project (Build -> Build Project) has the same effect.

**Comment by iburgos72** [comment]
hey, I just find a way to have hot reload
```lua
-- ~/.config/nvim/ftplugin/java.lua
function SearchFileBackwards(fn)
  local fp = vim.fn.expand('%:p')
  local pos = #fp
  local pom = ""
  while pos > 0 do
    if fp:sub(pos, pos) == '/' then
      pom = fp:sub(1, pos) .. fn
      if vim.fn.filereadable(pom) == 1 then
        break
      end
    end
    pos = pos - 1
  end
  return pom
end

function BuildMavenProject()
    local pom = SearchFileBackwards("pom.xml")
    if pom ~= "" then
        vim.fn.system('mvn -f ' .. pom .. ' compile')
    else
        vim.api.nvim_echo({{ "No pom.xml found.", "WarningMsg" }}, true, {})
    end
end

-- Press <F8> to build current maven project.
vim.api.nvim_buf_set_keymap(0, "n", "<F8>", ":lua BuildMavenProject()<CR>", { silent = true })

-- comment out below line to enable automatic build on maven project.
-- vim.api.nvim_command('autocmd BufWritePost *.java lua BuildMavenProject()')
```

and the equivalent functionality in vim
```vim
" Add below into your ~/.vim/ftplugin/java.vim
function! SearchFileBackwards(fn)
    let fp = expand('%:p')
    let pos = len(fp) - 1
    while pos > 0
        let pom = ""
        if fp[pos] == '/'
            let pom = strpart(fp, 0, pos + 1) . a:fn
            if filereadable(pom)
                break
            endif
        endif
        let pos = pos - 1
    endwhile
    return pom
endfunction

function! BuildMavenProject()
    let pom = SearchFileBackwards("pom.xml")
    if pom != ""
        exec '!mvn -f '.SearchFileBackwards("pom.xml").' compile'
    else
        echohl WarningMsg | echo "No pom.xml found." | echohl None
    endif
endfunction

" comment out below line to enable automatic build on maven project.
" autocmd BufWritePost *.java :call BuildMavenProject()

" Press <F8> to build current maven project.
nnoremap <buffer> <silent> <F8> :call BuildMavenProject()<CR>
```
