### ISSUE TITLE
Lunarvim throws an error if "lir" and "nvim-tree" are disabled

### ISSUE THREAD

**Issue by KonnorRogers** [LunarVim/LunarVim#3593]
### Problem description

1.) have the following config:

```lua
lvim.builtin.lir.active = false
lvim.builtin.nvimtree.active = false
```

2.) Receive the following error:

```
Error running config for "lir.nvim": .local/share/lunarvim/lvim/lua/lvim/core/lir.lua:111 attempt to call field: 'setup' (a nil value)
```

### LunarVim version

master-b6ebc2f

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Mac OS 12.5

### Steps to reproduce

```lua
lvim.builtin.lir.active = false
lvim.builtin.nvimtree.active = false
```

### Screenshots

<img width="1512" alt="Screen Shot 2022-12-11 at 4 29 56 PM" src="https://user-images.githubusercontent.com/26425882/206929876-fab00113-ba8c-4337-a8db-0622ea73ce35.png">

**Comment by LostNeophyte** [comment]
Did you run `:PackerSync` after the changes?

**Comment by KonnorRogers** [comment]
@LostNeophyte I thought I had, but apparently not. Fixed. Thank you!
