### ISSUE TITLE
Conda Package

### ISSUE THREAD

**Issue by ZhiyuanChen** [LunarVim/LunarVim#3594]
### Feature Description

LunarVim is great but it is not easy to install on cluster. 

Is it possible to create a LunarVim package on Conda, like [NeoVIM](https://anaconda.org/conda-forge/neovim)?

**Comment by LostNeophyte** [comment]
that conda package is not neovim, it's just a python client

**Comment by ZhiyuanChen** [comment]
> that conda package is not neovim, it's just a python client

Sorry, I meant zsh

**Comment by LostNeophyte** [comment]
Would they accept an lunarvim as a package though? it seems like it's for python related packages

is there any other package managers you can use on the cluster? would appimage work?

**Comment by ZhiyuanChen** [comment]
> Would they accept an lunarvim as a package though? it seems like it's for python related packages

Actually they have a lot of other packages, zsh, tmux, make, cmake... 
[conda-forge](https://conda-forge.org) has a lot of packages available and you can literally upload anything. 

> is there any other package managers you can use on the cluster? would appimage work?

Unfortunately not.... I'm working at a startup and the maintenance is not perfect

**Comment by LostNeophyte** [comment]
I'll consider it when they'll have an nvim package

**Comment by eunos-1128** [comment]
Now conda-forge has [nvim](https://anaconda.org/conda-forge/nvim).

We can install lunarvim using [default installaion procedure] (https://www.lunarvim.org/docs/installation#release) after installing nvim.
