### ISSUE TITLE
Keeps breaking after updates.

### ISSUE THREAD

**Issue by Chris-Leeworthy** [LunarVim/LunarVim#3595]
### Problem description

Updating Lunarvim seems to have become a bit of a game of chance for me.

Quite often I get errors after the upgrade and I wind up having to re-install from scratch to get stuff working.

I suspect this may be due to my tweaks to the config file.  Nothing complicated, a couple of themes, treesitter based code folding and fuGITive (because I still prefer it to lazygit).

Is it possible to put my tweaks in a separate file that is called from the main config so I can easily re-instate them if I have to do an install from scratch?

### LunarVim version

rolling-5057861

### Neovim version (>= 0.8.0)

NVIM 0.8.1

### Operating system/version

macOS Ventura 13.0.1 and Fedora 36

**Comment by Chris-Leeworthy** [comment]
Sorry if this is in the wrong category, it's not really a bug or an enhancement request so I wasn't sure how to label it.

**Comment by LostNeophyte** [comment]
are you actually on rolling? it's abandoned switch to master (the new nightly) or to 1.2 (stable)

**Comment by LostNeophyte** [comment]
> Is it possible to put my tweaks in a separate file that is called from the main config so I can easily re-instate them if I have to do an install from scratch?

.config/lvim/config.lua is that file, you can ditch the example one it generates and overwrite it with your config

**Comment by Chris-Leeworthy** [comment]
Thanks 🙂

**Comment by LostNeophyte** [comment]
If there anything more or is the issue fixed?

**Comment by Chris-Leeworthy** [comment]
I’m happy this issue is resolved

**Comment by hawkinchina** [comment]
@LostNeophyte @Chris-Leeworthy 
I met  the same problem. 
my version: rolling-16a8b92.
neovim: 0.8.0
if i switch to to 1.2 (stable).   Can i use 'lvimUpdate' command for this Updating.
or  save  my configuration (~/.config/lvim/config.lua),  and then I need reintall 1.2 (stable).
and overwrite it with my config file.
