### ISSUE TITLE
Unable to remove terminal mode keymapping

### ISSUE THREAD

**Issue by decaffjoe** [LunarVim/LunarVim#3598]
### Problem description

I want to be able to use `<C-L>` to clear my terminal (the equivalent of the `clear` command), but the default behavior of `<C-L>` in terminal mode is to close the terminal.

Previously, I was able to include this in my `config.lua` to remove the default behavior so that I could clear the terminal:

```lua
vim.keymap.del("t", "<C-L>")
```

But this now throws a config error ([issue 3407](https://github.com/LunarVim/LunarVim/issues/3407)) when lunarvim is launched.

Unfortunately it does not appear that there is a way to assign keymappings in terminal mode other than the open mapping:

```lua
lvim.builtin.terminal.open_mapping = "<C-T>"
```

And there is no `terminal_mode` object for `lvim.keys` either

### LunarVim version

master-3166cc0

### Neovim version (>= 0.8.0)

v0.8.1

### Operating system/version

EndeavourOS Linux, kernel v6.0.12-arch1-1

### Steps to reproduce

1. Open lunarvim
2. Open the builtin terminal
3. Press `<C-L>` and observe that the terminal is closed

**Comment by LostNeophyte** [comment]
`vim.keymap.del("t", "<C-L>")` should still work, it doesn't give me any errors

**Comment by LostNeophyte** [comment]
> And there is no terminal_mode object for lvim.keys either

there is `lvim.keys.term_mode`

**Comment by rochacbruno** [comment]
I just tried and works well

```lua
-- Remove the Ctrl-\ for terminal toggling, allowing `C-\ C-n` as esc on term mode
lvim.builtin.terminal.open_mapping = "<c-t>"
-- Enable the use of C-l to clean the terminal
lvim.keys.term_mode = { ["<C-l>"] = false }
```
