### ISSUE TITLE
unable to remap move line keyboard shortcut

### ISSUE THREAD

**Issue by 99Percent** [LunarVim/LunarVim#3599]
### Problem description

1. Edit the config.lua file
2. Add the following lines:
```
lvim.keys.normal_mode["<M-p>"] = "<M-k>" -- move line down
lvim.keys.normal_mode["<M-k>"] = "<M-j>" -- move line up
```
save file, exit and start lvim again

Alt k navigates line down instead of moving line down
Alt p does nothing, expected to move line up
Alt j still moves te line down, 

Also, how can I check the log files? where are they located?

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.1

### Operating system/version

Ubuntu 20.04

### Steps to reproduce

(I Don't know how to edit the config.lua in minimal config.)

**Comment by LostNeophyte** [comment]
`lvim.keys.normal_mode["<M-p>"] = {"<A-k>", {remap = true}}` 
M-p doesn't work for me though, vim doesn't recognize it in my terminal (to check go to insert mode and type `<C-v><M-p>`, it should type `<M-p>`

you can see various log files under `leader L l`
