### ISSUE TITLE
Weird Error While modifying Config file

### ISSUE THREAD

**Issue by Pyrole-2002** [LunarVim/LunarVim#3600]
### Problem description

I just installed fresh lunarvim and just added this one line to the config
`vim.opt.autoindent = true`
After this I started getting this error in the terminal when I exit:
` [WARN ] lvim: "Invalid configuration: vim/_meta.lua:0: E545: Missing colon" file="init.lua", line=49% `
I have no idea what this means.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

0.8.1

### Operating system/version

Manjaro Linux x86_64

**Comment by LostNeophyte** [comment]
Is that fixed by the discord conversation?

**Comment by Pyrole-2002** [comment]
> Is that fixed by the discord conversation?

Yes
