### ISSUE TITLE
install.ps1 error on Windows

### ISSUE THREAD

**Issue by ato2** [LunarVim/LunarVim#3601]
### Problem description

Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression
Invoke-Expression: The variable '$LV_BRANCH' cannot be retrieved because it has not been set.

~ > .\install.ps1
InvalidOperation: C:\Users\ato\install.ps1:5
Line |
   5 |  $LV_BRANCH = $LV_BRANCH ?? "master"
     |               ~~~~~~~~~~
     | The variable '$LV_BRANCH' cannot be retrieved because it has not been set.

PSVersion     7.3.0

### LunarVim version

none

### Neovim version (>= 0.8.0)

none

### Operating system/version

Windows 10

**Comment by LostNeophyte** [comment]
maybe you have strict mode enabled, try `$LV_BRANCH='master'; Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression`

**Comment by ato2** [comment]
Install script should be environment independent.
I have no Set-Strictmode in my PS config so it seems that this is default in 7.3
I added "Set-StrictMode -Off" at the beginning of install.ps1 and now is OK.
