### ISSUE TITLE
Moving line up and down doesn't work on Mac

### ISSUE THREAD

**Issue by kwiat1990** [LunarVim/LunarVim#3602]
### Problem description

According to the official docs (https://www.lunarvim.org/docs/keybind-overview#editing) with the following key binding `<M-k>` it should be possible to move the current line up and with `<M-j>` to down. I use LunarVim in the `iTerm 2` terminal and it doesn't seem to work there. I have tried in normal and in visual mode but it does nothing. As mentioned in docs the `<M>` key should be mapped to the `option` key on Mac.

Oddly enough, if I go to docs for key mappings using `<leader> L k` and then find and click a mapping for one of mentioned action, the current line will be moved. 

I can't either use `M-1` to toggle integrated terminal.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

1.2

### Operating system/version

macOS 13.0.1

**Comment by LostNeophyte** [comment]
in the iTerm settings you need to tell it to use option as meta

**Comment by kwiat1990** [comment]
> in the iTerm settings you need to tell it to use option as meta

Thanks a lot for this tip - it helped! I didn't know that `iTerm2` don't map `option` by default.
