### ISSUE TITLE
Noting happens on pasting installation cmd in terminal (linux). 

### ISSUE THREAD

**Issue by priyaan99** [LunarVim/LunarVim#3608]
### Problem description

On pasting this line in my linux machine terminal nothing happens.
= LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

### LunarVim version

0

### Neovim version (>= 0.8.0)

0.8.0

### Operating system/version

Linux Popos

### Steps to reproduce

LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

**Comment by LostNeophyte** [comment]
if you're not able, then use `LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://pastebin.com/raw/yntZw7wK | sed --expression 's/\r$//' )`

**Comment by priyaan99** [comment]
It Works.

**Comment by priyaan99** [comment]
Thank you

**Comment by huntswyj** [comment]
Thank you
