### ISSUE TITLE
How to configure nvim-tree keybindings?

### ISSUE THREAD

**Issue by 99Percent** [LunarVim/LunarVim#3610]
### Problem description

I want to clear the <C-e> binding of my nvim-tree

Apparently the lvim.builtin.nvimtree.mappings is not an object as I get this error:
 ```
attempt to index field 'mappings' (a nil value)
```
Also lvim does not handle such errors gracefully as it prints hundreds of lines in the log, and even crashes sometimes.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by runner@fv-az178-366

### Operating system/version

Ubuntu 20.04

### Steps to reproduce

1. Edit config.lua
2. add the following line (for example):
```
lvim.builtin.nvimtree.mappings["<C-e>"] = nil
```
3. Save the file.

**Comment by LostNeophyte** [comment]
that's not where nvimtree mappings go

**Comment by LostNeophyte** [comment]
`:help nvim-tree-mappings`
https://github.com/LunarVim/LunarVim/blob/f50e49a3cc359cde4dc0132e682c0ae11b20da05/lua/lvim/core/nvimtree.lua#L47
