### ISSUE TITLE
Error while lunarvim installation `unknown flag 'u'` (read workaround at the top of the issue)

### ISSUE THREAD

**Issue by hamzamohdzubair** [LunarVim/LunarVim#3612]
## **how to fix this issue (maintainer edit**)
https://github.com/LunarVim/LunarVim/issues/3612#issuecomment-1379895972
Remove `exec -a "$NVIM_APPNAME"` from ~/.local/bin/lvim as a workaround

### Problem description

I get the following error as the last line of the installation process (see screenshots)
And i get the same error when i try to run lunarvim later using `lvim`
```
error: unknown flag `u'
```

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

NVIM v0.8.1

### Operating system/version

CentOS Linux 7 (Core)

### Steps to reproduce

1. Install neovim

### Screenshots
![image](https://user-images.githubusercontent.com/13695228/207779006-c935374d-1e75-4e04-8d62-bb719007cc09.png)
![image](https://user-images.githubusercontent.com/13695228/207777515-f35d391a-f341-409e-a1f9-7b3513dbbe38.png)
![image](https://user-images.githubusercontent.com/13695228/207779214-e638c721-f42e-4e28-aa2f-fca9530afa52.png)

**Comment by LostNeophyte** [comment]
Send the output of `nvim --help`

**Comment by hamzamohdzubair** [comment]
> Send the output of `nvim --help`

![image](https://user-images.githubusercontent.com/13695228/207793235-25ca3340-0f4c-4d9b-949c-a82ce0ed7722.png)

**Comment by LostNeophyte** [comment]
interesting, `-u` is in the list. Create a `file.lua` and run `nvim -u file.lua`, will it work?

**Comment by hamzamohdzubair** [comment]
> interesting, `-u` is in the list. Create a `file.lua` and run `nvim -u file.lua`, will it work?

yes it worked

**Comment by hamzamohdzubair** [comment]
> does `lvim -u file.lua` work?

![image](https://user-images.githubusercontent.com/13695228/207808747-e25178d0-9351-4fe0-80bb-4da2fad000b7.png)

**Comment by LostNeophyte** [comment]
send the output of `cat ~/.local/bin/lvim`

**Comment by hamzamohdzubair** [comment]
> send the output of `cat ~/.local/bin/lvim`

![image](https://user-images.githubusercontent.com/13695228/207813558-2359ab3a-f80c-43a1-b19d-625fc50d7161.png)

**Comment by LostNeophyte** [comment]
what about `nvim --headless -u NONE`

**Comment by LostNeophyte** [comment]
and if you have nvim in `~/.local/bin/nvim`, test it too

**Comment by hamzamohdzubair** [comment]
> what about `nvim --headless -u NONE`

just freezes
![image](https://user-images.githubusercontent.com/13695228/207817033-7b55cd20-d3b9-4791-970a-62bb8830bf1c.png)

**Comment by hamzamohdzubair** [comment]
> and if you have nvim in `~/.local/bin/nvim`, test it too

no nvim in `~/.local/bin/`

**Comment by LostNeophyte** [comment]
> > what about `nvim --headless -u NONE`
> 
> just freezes ![image](https://user-images.githubusercontent.com/13695228/207817033-7b55cd20-d3b9-4791-970a-62bb8830bf1c.png)

that's expected, idk what's wrong tbh since `nvim -u` works

**Comment by hamzamohdzubair** [comment]
> > > what about `nvim --headless -u NONE`
> > 
> > 
> > just freezes ![image](https://user-images.githubusercontent.com/13695228/207817033-7b55cd20-d3b9-4791-970a-62bb8830bf1c.png)
> 
> that's expected, idk what's wrong tbh since `nvim -u` works

i have been using nvim since last one year without any problems, recently i reinstalled nvim from snap, earlier i was using appimage

**Comment by LostNeophyte** [comment]
we have an experimental lunarvim appimage with bundled nvim btw https://github.com/LostNeophyte/LunarVim/releases/tag/stable

**Comment by hamzamohdzubair** [comment]
> we have an experimental lunarvim appimage with bundled nvim btw https://github.com/LostNeophyte/LunarVim/releases/tag/stable

this is pretty smooth, i like it thanks. But the original issue remains.

**Comment by LostNeophyte** [comment]
does `bash -c "exec nvim -u NONE"` or bash -c "nvim -u NONE" trigger the same error?

**Comment by George-Spanos** [comment]
Hello!! I'm continuing this thread since I have the same **exact** issue up until this point of the convo. Unfortunately I get the same error even by using the .deb (I'm on Ubuntu).
`bash -c "exec nvim -u NONE"` just opens a nvim normally.

**Comment by Philipp0205** [comment]
I just got the exact same problem. 

Removinb `exec -a lvim` from `~/.local/bin/nvim` changes the error to `error: unknown flag `u'` 

```
You can start LunarVim by running: /home/philipp/.local/bin/lvim
make: Leaving directory '/home/philipp/.local/share/lunarvim/lvim'
Creating desktop file
Preparing Packer setup
error: unknown flag `u'

```

**Comment by Philipp0205** [comment]
For me lvim starts now,  but not with the usual start screen and theme. Something seems to be broken.

**Comment by LostNeophyte** [comment]
> For me lvim starts now, but not with the usual start screen and theme. Something seems to be broken.

Run `:PackerSync` for 1.2 / `:Lazy sync` for master

**Comment by LostNeophyte** [comment]
@George-Spanos @Philipp0205 what shell are you using? what's its version and the version of bash?

**Comment by Philipp0205** [comment]
@LostNeophyte Okay `PackerSync` helped. It's my first time using lvim so I was a bit confused :) 

```
➜  ~ neofetch
            .-/+oossssoo+/-.               philipp@x1 
        `:+ssssssssssssssssss+:`           ---------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.10 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 20UAS6FH00 ThinkPad X1 Carbon Gen 8 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.19.0-28-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 18 hours, 13 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 3682 (dpkg), 43 (flatpak), 29 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.9 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1680x1050 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Regolith 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: i3 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Dracula [GTK3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Dracula [GTK3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel i7-10610U (8) @ 4.900GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: Intel CometLake-U GT2 [UHD Graphics] 
    .ossssssssssssssssssdMMMNysssso.       Memory: 6240MiB / 15633MiB 

```

**Comment by LostNeophyte** [comment]
thanks, I'll try to reproduce it in an ubuntu container

**Comment by jagblad** [comment]
I've a similar problem. I think for me it may be due to having nvim installed via "snap", then it seems the lvim script tries to launch /snap/bin/nvim which is a symlink for /usr/bin/snap, so it launches snap instead of nvim. Snap doesn't have a "-u" option.

**Comment by George-Spanos** [comment]
> I've a similar problem. I think for me it may be due to having nvim installed via "snap", then it seems the lvim script tries to launch /snap/bin/nvim which is a symlink for /usr/bin/snap, so it launches snap instead of nvim. Snap doesn't have a "-u" option.
> 

Sounds reasonable, I will test if this is valid as well.

**Comment by LostNeophyte** [comment]
> I've a similar problem. I think for me it may be due to having nvim installed via "snap", then it seems the lvim script tries to launch /snap/bin/nvim which is a symlink for /usr/bin/snap, so it launches snap instead of nvim. Snap doesn't have a "-u" option.

so does `nvim -u` not work with snap installed nvim?

**Comment by jagblad** [comment]
It does for me.

**Comment by George-Spanos** [comment]
I can verify, there is an ussue with the snap version. Installing from tar also worked.

**Comment by LostNeophyte** [comment]
I created a lunarvim snap today https://github.com/LunarVim/LunarVim-mono/blob/master/snap/snapcraft.yaml, it worked, but I didn't test it on a clean system

**Comment by LostNeophyte** [comment]
I can't reproduce it on fedora with a snap, will try ubuntu

**Comment by hardyrafael17** [comment]
Same issue here, removed snap package and installed the deb package and worked nicely!

**Comment by szamanr** [comment]
exact same issue. i'm on ubuntu 20.04 and installed nvim via snap. cannot use apt version because it's outdated (0.4 instead of 0.8)

**Comment by George-Spanos** [comment]
@szamanr I suggest you install nvim from the [releases page on github](https://github.com/neovim/neovim/releases/tag/stable). This way you will safely install the latest stable version that works with lvim.

**Comment by hamzamohdzubair** [comment]
> we have an experimental lunarvim appimage with bundled nvim btw https://github.com/LostNeophyte/LunarVim/releases/tag/stable

Can we please get this on the official install page, because i love this way of working with lunarvim, and i am sure many others will too

**Comment by LostNeophyte** [comment]
> > we have an experimental lunarvim appimage with bundled nvim btw https://github.com/LostNeophyte/LunarVim/releases/tag/stable
> 
> Can we please get this on the official install page, because i love this way of working with lunarvim, and i am sure many others will too

That's my plan, that link is outdated btw, here's the nightly ci build: https://github.com/LunarVim/LunarVim-mono/releases/tag/master

**Comment by obayit** [comment]
I can confirm this issue too,
The same error is given after installing with the ubuntu/debian package too.

**Comment by h-peysepar** [comment]
I have the same issue on ubuntu :(

**Comment by vasilNnikolov** [comment]
Had the same issue. For me, installing nvim from the official website as an appimage and not with `sudo apt` solved it.

**Comment by mancini0** [comment]
Same issue

**Comment by james1236** [comment]
> I've a similar problem. I think for me it may be due to having nvim installed via "snap", then it seems the lvim script tries to launch /snap/bin/nvim which is a symlink for /usr/bin/snap, so it launches snap instead of nvim. Snap doesn't have a "-u" option.

Same issue on raspberry pi 2B, to fix I removed the snap version of nvim, and built and installed nvim [from source](https://github.com/neovim/neovim/wiki/Building-Neovim)

**Comment by bernardogontijo** [comment]
Same issue. Neovim from snap.
$ bash -c "exec -a lvim nvim -u NONE"
erro: unknown flag `u'

**Comment by ArobyR** [comment]
> I've a similar problem. I think for me it may be due to having nvim installed via "snap", then it seems the lvim script tries to launch /snap/bin/nvim which is a symlink for /usr/bin/snap, so it launches snap instead of nvim. Snap doesn't have a "-u" option.

Exactly. I had the same issue on ubuntu with Neovim from snap, so I uninstalled and reinstalled it but using apt instead of snap.

**Comment by caiohenrique12** [comment]
> > What if you remove `exec -a lvim` from ~/.local/bin/lvim and then run lvim?
> 
> For me, removing fixed the issue!

I use ubuntu 22.04, and this work for me, but, i have another install in manjaro using lunarvim, i don't got this error.

**Comment by daniilraptanov** [comment]
I had this problem, but I updated nvim to 0.8.3 and its working
(kubuntu 20.04)

**Comment by DragonDmoney** [comment]
After updating to 0.8.3 it was fixed as well
(Fedora 37)

**Comment by LostNeophyte** [comment]
> After updating to 0.8.3 it was fixed as well
> (Fedora 37)

Awesome, I'll close the issue in that case

**Comment by medeirosjoaquim** [comment]
While neovim 0.8 is not available on repositories of some linux distros (debia, ubuntu). What I did was to download neovim
latest version (0.9) appImage and change the `install.sh` and lvim `.local/bin/lvim`
to use ./nvim.appimage

**Comment by Trotsz** [comment]
I'm having the same problem and none of the suggestions in here worked for me.
I installed NeoVim 0.9.0 and LunarVim just doesn't work because of "unknown flag 'u'"

**Comment by tejaswankalluri** [comment]
Not Worked For me I have the same problem
Nvim version: 0.9.0
Error: unknown flag u

**Comment by LostNeophyte** [comment]
> I'm having the same problem and none of the suggestions in here worked for me.
I installed NeoVim 0.9.0 and LunarVim just doesn't work because of "unknown flag 'u'"

> Not Worked For me I have the same problem
Nvim version: 0.9.0
Error: unknown flag u

did you try this? https://github.com/LunarVim/LunarVim/issues/3612#issuecomment-1379895972

**Comment by hamzamohdzubair** [comment]
> > > we have an experimental lunarvim appimage with bundled nvim btw https://github.com/LostNeophyte/LunarVim/releases/tag/stable
> > 
> > 
> > Can we please get this on the official install page, because i love this way of working with lunarvim, and i am sure many others will too
> 
> That's my plan, that link is outdated btw, here's the nightly ci build: https://github.com/LunarVim/LunarVim-mono/releases/tag/master

Even After 4.5 months of opening this issue, everytime i have to setup lunarvim on a new system, or I excitedly share the awesomeness of lunarvim with my friends, family or colleague, this is the page i have to come to, to share the easiest and best way of installing lunarvim. I really wish this could be the first thing on the install page.

**Comment by LostNeophyte** [comment]
> > > > we have an experimental lunarvim appimage with bundled nvim btw https://github.com/LostNeophyte/LunarVim/releases/tag/stable
> > > 
> > > 
> > > Can we please get this on the official install page, because i love this way of working with lunarvim, and i am sure many others will too
> > 
> > 
> > That's my plan, that link is outdated btw, here's the nightly ci build: https://github.com/LunarVim/LunarVim-mono/releases/tag/master
> 
> I really wish this could be the first thing on the install page.

That was my plan initially, but I don't have enough motivation to work on the project right now, it's not well tested and maintained and I've got no idea if it works with 1.3. I might work on this soon since we have a national holiday on the 1st of May in Poland and the whole week will be off from school so I'll have more time. But I have other projects I want to work on and the last weeks were rough so no promises

**Comment by hamzamohdzubair** [comment]
> > > > > we have an experimental lunarvim appimage with bundled nvim btw https://github.com/LostNeophyte/LunarVim/releases/tag/stable
> > > > 
> > > > 
> > > > Can we please get this on the official install page, because i love this way of working with lunarvim, and i am sure many others will too
> > > 
> > > 
> > > That's my plan, that link is outdated btw, here's the nightly ci build: https://github.com/LunarVim/LunarVim-mono/releases/tag/master
> > 
> > 
> > I really wish this could be the first thing on the install page.
> 
> That was my plan initially, but I don't have enough motivation to work on the project right now, it's not well tested and maintained and I've got no idea if it works with 1.3. I might work on this soon since we have a national holiday on the 1st of May in Poland and the whole week will be off from school so I'll have more time. But I have other projects I want to work on and the last weeks were rough so no promises

Thanks alot for the efforts you have put in uptil now, can't thank you enough. Also want to thank you on behalf of everyone using and enjoying lunarvim.

**Comment by danielo515** [comment]
I am here to report the same issue. My intuition made me test removing the `exec -a lvim` part, and indeed it worked. But I guess that has some other consequences, since `exec` makes lvim take the pid of it's parent and therefore it appears as a separate command in the process list, correctly named lvim, but without that part it just appears as nvim.

I was previously using nvim from brew, and I decided to give `bob-nvim`, a version manager a go, and since then I have those problems.

**Comment by LostNeophyte** [comment]
I'm out of ideas here, no idea what to do

**Comment by thalha-dev** [comment]
I had the same problem. Then I choose to install this way.

```bash
#!/bin/bash

url="https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz"
extract_dir="$HOME/source-installed/nvim/stable"
nvim_bin="$HOME/.local/bin/nvim"

# Remove existing files in the extract directory
if [[ -d "$extract_dir" ]]; then
	echo "Removing existing files in $extract_dir..."
	rm -rf "$extract_dir"
fi

# Remove symlink if it already exists
if [ -L "$nvim_bin" ]; then
	rm "$nvim_bin"
fi

mkdir -p "$extract_dir"

curl -L "$url" | tar -xz -C "$extract_dir" --strip-components=1

# Create symlink to nvim executable
ln -s "$extract_dir/bin/nvim" "$nvim_bin"

```

**Comment by ufo5260987423** [comment]
> does `bash -c "exec -a lvim nvim -u NONE"` trigger the error for all of you?

For me, it didi.

**Comment by AkioKiyota** [comment]
> What if you remove `exec -a lvim` from ~/.local/bin/lvim and then run lvim?

it kinda broke things i guess,
it doesnt responde at all now
i might deleted a bit more than exec -a lvim :D

exec -a "$NVIM_APPNAME" nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"

i have deleted this line

**Comment by LostNeophyte** [comment]
only remove `-a "$NVIM_APPNAME"`, nothing more

**Comment by AkioKiyota** [comment]
> only remove `-a "$NVIM_APPNAME"`, nothing more

it works thx :D

**Comment by MheniMerz** [comment]
this is what worked for me 
i modified the first line of `~/.local/bin/lvim` script to basically change the value of the `NVIM_APPNAME` variable

from
```bash
export NVIM_APPNAME="${NVIM_APPNAME:-"lvim"}"
```

to
```bash
export NVIM_APPNAME="${NVIM_APPNAME:-"nvim"}"
```

**Comment by LostNeophyte** [comment]
> this is what worked for me i modified the first line of `~/.local/bin/lvim` script to basically change the value of the `NVIM_APPNAME` variable
> 
> from
> 
> ```shell
> export NVIM_APPNAME="${NVIM_APPNAME:-"lvim"}"
> ```
> 
> to
> 
> ```shell
> export NVIM_APPNAME="${NVIM_APPNAME:-"nvim"}"
> ```

don't do that, it will use different directories if you do that, use the workaround I edited in at the top of the issue

**Comment by Qwer-TeX** [comment]
@hamzamohdzubair 

Did you download nvim from snap?
`sudo snap install --beta nvim --classic`    ?

**Comment by lackovic** [comment]
I am also getting the same error, right after installation:

```
$ lvim
error: unknown flag `u'
``` 
I installed Neovim through `snap` in order to get the last version.

> What if you remove `exec -a lvim` from ~/.local/bin/lvim and then run lvim?

The last line of my `~/.local/bin/lvim` is:
```
exec -a "$NVIM_APPNAME" nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
``` 
If I remove it then nothing happens when I run `lvim`.

**Comment by Qwer-TeX** [comment]
@lackovic 

I think that you shouldn't install Neovim through snap because the ubuntu developer strip down the binary to save space. 
I suggest that you either download the binaries from their website of [build it](https://github.com/neovim/neovim/wiki/Building-Neovim) yourself.

**Comment by LostNeophyte** [comment]
@lackovic did you remove only the mentioned part of that line?

**Comment by lackovic** [comment]
> @lackovic did you remove only the mentioned part of that line?

The mentioned part `exec -a lvim` is not present on the last line of my `~/.local/bin/lvim`:

```
exec -a "$NVIM_APPNAME" nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
```

I first tried to remove just `exec -a`, without that a warning is printed indefinitely:

```
$ lvim
bash: warning: shell level (1000) too high, resetting to 1
bash: warning: shell level (1000) too high, resetting to 1
bash: warning: shell level (1000) too high, resetting to 1
``` 

When I removed `exec -a "$NVIM_APPNAME"` then the application started and successfully started 43 plugins.

Why is `exec -a "$NVIM_APPNAME"` part of the last line of  `~/.local/bin/lvim` if with that it does not work?

**Comment by LostNeophyte** [comment]
`exec -a "$NVIM_APPNAME"` used to be `exec -a lvim`
> Why is exec -a "$NVIM_APPNAME" part of the last line of ~/.local/bin/lvim if with that it does not work?

for some reason exec's -a flag breaks the nvim executable (or maybe its wrapper) from snap, the same happens with bob (nvim version manager)

**Comment by Peelz** [comment]
OS: Ubuntu 22.04

I'm not sure about root cause, but for me i was install neovim from snap.
After removed nvim from snap store, and use Applmage It's working now.

**Comment by obayit** [comment]
@hamzamohdzubair 
I remove the line mentioned in the workaround, but it gets readded after running the installation script again. Can you please show a detailed steps of how to install?

**Comment by bilenkonito** [comment]
The reason is that snap's shims work by symlinking each binary name to `/usr/bin/snap`, which then grabs the binary name from the 0th argument and executes the actual binary found inside the snap image.
The `exec -a` command is effectively setting to `lvim` the 0th argument passed to `nvim`. Since snapd cannot find any exported binary named `lvim` in any of the installed snaps, the execution of `/snap/bin/nvim` instead behaves as if `/usr/bin/snap` was being executed:
`# /usr/bin/snap -u
error: unknown flag `u'`

**Comment by estrac** [comment]
The workaround at the top of did not resolve this issue for me -- the installation of LunarVim still failed.

As @bilenkonito explained above, this is an issue with snap. I was able to successfully install LunarVim by first removing my neovim installation with:

    sudo snap remove nvim

Then I installed neovim from source (which was surprisingly easy following [neovim "Install from Source" instructions](https://github.com/neovim/neovim/blob/master/INSTALL.md)) and re-ran the LunarVim installation script.

**Comment by nb5p** [comment]
I encountered the same problem with bob-nivm. Modifying the last line as follows solved it.
```bash
exec nivm -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
```

**Comment by WayneBuckhanan** [comment]
FYI, snap has the ability to "alias" executable names so it resolves to the correct packaged executable when using another name to call it.

`sudo snap alias nvim lvim`

As long as your `~/.local/bin` is before snap in your path, it will run the lvim script, then when the script calls the snap managed nvim, it has no issues with the `exec -a` renaming it lvim.

**Comment by Aegox** [comment]
Thats great, delete exec -a and run path of lvim

**Comment by ivandez** [comment]
as jagblad said, I had neovim installed via snap and it did not work, so I delete neovim with snap remove and then install it again with curl from neovim official doc and now it works https://github.com/neovim/neovim/blob/master/INSTALL.md#install-from-package

**Comment by jgollenz** [comment]
> snap's shims work by symlinking each binary name to `/usr/bin/snap`, which then grabs the binary name from the 0th argument and executes the actual binary found inside the snap image.
> 
> The `exec -a` command is effectively passing `lvim` as the 0th argument to `nvim` but since snapd cannot find any snap declared binary called `lvim`, the execution of `/snap/bin/nvim` instead behaves as if `/usr/bin/snap` was being executed directly.

This seems to be the case for `bob` as well. The error message gives this away: 

```
$ lvim
error: unexpected argument '-u' found
$ bob -u
error: unexpected argument '-u' found
$ nvim -x
nvim: Unknown option argument: "-x"
```

(I'm using `-x` for nvim since `-u` exists)

The [bob repo](https://github.com/MordechaiHadad/bob) also mentions this in it's README:

```
2023-02-13: Bob has recently switched to using a proxy executable for running Neovim executables
```

As for the workaround of removing `-a "$NVIM_APPNAME"` from the `exec` command: what are the implications of this? I assume there's a reason for it being there in the first place.


edit: @MordechaiHadad do you think this is something that bob should take into account? Could be as easy as allowing both `nvim` and `lvim` for the 0th argument, if I'm not mistaken.

**Comment by MordechaiHadad** [comment]
> > snap's shims work by symlinking each binary name to `/usr/bin/snap`, which then grabs the binary name from the 0th argument and executes the actual binary found inside the snap image.
> > The `exec -a` command is effectively passing `lvim` as the 0th argument to `nvim` but since snapd cannot find any snap declared binary called `lvim`, the execution of `/snap/bin/nvim` instead behaves as if `/usr/bin/snap` was being executed directly.
> 
> This seems to be the case for `bob` as well. The error message gives this away:
> 
> ```
> $ lvim
> error: unexpected argument '-u' found
> $ bob -u
> error: unexpected argument '-u' found
> $ nvim -x
> nvim: Unknown option argument: "-x"
> ```
> 
> (I'm using `-x` for nvim since `-u` exists)
> 
> The [bob repo](https://github.com/MordechaiHadad/bob?rgh-link-date=2025-04-03T10%3A11%3A59.000Z) also mentions this in it's README:
> 
> ```
> 2023-02-13: Bob has recently switched to using a proxy executable for running Neovim executables
> ```
> 
> As for the workaround of removing `-a "$NVIM_APPNAME"` from the `exec` command: what are the implications of this? I assume there's a reason for it being there in the first place.
> 
> edit: [@MordechaiHadad](https://github.com/MordechaiHadad?rgh-link-date=2025-04-03T10%3A11%3A59.000Z) do you think this is something that bob should take into account? Could be as easy as allowing both `nvim` and `lvim` for the 0th argument, if I'm not mistaken.

You want to allow setting bob's binary to `lvim` so it will work just like how when you rename it basically?

**Comment by jgollenz** [comment]
> You want to allow setting bob's binary to lvim so it will work just like how when you rename it basically?

Let's go one step back first. Can you confirm that [this line](https://github.com/MordechaiHadad/bob/blob/3f0adc0ea987e3aa1858f2dcf9bc09646125bf90/src/main.rs#L39) is the reason why the call `exec -a lvim nvim -u $CONFIG` will fail, because `exe_name` will be "lvim" and thus the `-u $CONFIG` will be forwarded to `bob` instead, where no `-u` exists? Just to be sure this is the actual issue.

But yes, in this case my suggestion would be to either allow both "nvim" and "lvim" as valid values for `exe_name`, since lvim is popular project and ideally bob works out-of-the-box with it, or give users a way to enable support for lvim via the bob config, e.g. by adding a `executable_alias[es]` config-key. This way users can enable support for other projects similar to lvim by themselves and won't file issues regarding their support.

In the latter solution you could also default the value of the key to `[ "lvim" ]` and have it work out-of-the-box as well.

**Comment by MordechaiHadad** [comment]
> > You want to allow setting bob's binary to lvim so it will work just like how when you rename it basically?
> 
> Let's go one step back first. Can you confirm that [this line](https://github.com/MordechaiHadad/bob/blob/3f0adc0ea987e3aa1858f2dcf9bc09646125bf90/src/main.rs#L39) is the reason why the call `exec -a lvim nvim -u $CONFIG` will fail, because `exe_name` will be "lvim" and thus the `-u $CONFIG` will be forwarded to `bob` instead, where no `-u` exists? Just to be sure this is the actual issue.
> 
> But yes, in this case my suggestion would be to either allow both "nvim" and "lvim" as valid values for `exe_name`, since lvim is popular project and ideally bob works out-of-the-box with it, or give users a way to enable support for lvim via the bob config, e.g. by adding a `executable_alias[es]` config-key. This way users can enable support for other projects similar to lvim by themselves and won't file issues regarding their support.
> 
> In the latter solution you could also default the value of the key to `[ "lvim" ]` and have it work out-of-the-box as well.

Yes, if the binary name or the 0th argument is anything besides "nvim" it will forward everything to bob's clap rather than neovim.

**Comment by badbabykosh** [comment]
I used the edit as suggested at top by OP.  I am installing for the first time. Removing exec -a "$NVIM_APPNAME" from ~/.local/bin/lvim as a workaround does not work.

**Comment by liamleeproduction-cloud** [comment]
Open the lvim configuration file
Edit the lvim script located at /home/<user>/.local/bin/lvim, replacing <user> with your username. Run:

nvim /home/<user>/.local/bin/lvim

Locate the execution line
Find the following line in the file:

exec -a "$NVIM_APPNAME" nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"

Update the execution line
Replace it with the following to use the Snap-installed Neovim:

exec -a "$NVIM_APPNAME" snap run nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"

Save and exit
Save the file and exit Neovim (e.g., type :wq and press Enter).

run
./.local/bin/lvim

member add to your path
