### ISSUE TITLE
unable to disable treesitter for vim

### ISSUE THREAD

**Issue by hamzamohdzubair** [LunarVim/LunarVim#3613]
### Problem description

every time i open lunarvim i am greeted with an error message (see screenshots), which basically says unable to install treesitter parser for vim. I am on Centos 7, i have checked, the error stems from old gcc or something.

So, i just want to disable vim for treesitter

I have tried disabling vim for treesitter in many ways, but nothing worked.
1. remove from the list
2. add to ignore list

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

0.8.1

### Operating system/version

CentOS Linux 7 (Core)

### Steps to reproduce

1. download lunarvim appimage
2. run it

### Screenshots

![image](https://user-images.githubusercontent.com/13695228/207863841-115f0a5f-aac3-481b-a993-4ed42c99c457.png)

**Comment by LostNeophyte** [comment]
> 
    remove from the list
    add to ignore list

which lists are you talking about exactly?

**Comment by LostNeophyte** [comment]
@kylo252 can that be because of https://github.com/LunarVim/LunarVim/pull/3475? it doesn't seem to respect ignore_install

**Comment by hamzamohdzubair** [comment]
> @kylo252 can that be because of #3475? it doesn't seem to respect ignore_install

I don't know, even if it is, i don't understand how do i solve my problem

**Comment by LostNeophyte** [comment]
> I don't know, even if it is, i don't understand how do i solve my problem


That wasn't a question for you, we might have a bug in lunarvim where ignore_install doesn't work

**Comment by hamzamohdzubair** [comment]
> > I don't know, even if it is, i don't understand how do i solve my problem
> 
> That wasn't a question for you, we might have a bug in lunarvim where ignore_install doesn't work

i guess ignore_install works for other languages i have tried, but not for `"vim"`

**Comment by kylo252** [comment]
the vim parser is shipped by default with neovim itself, so you should keep it up-to-date if you want to avoid problems with using nvim-treesitter.
