### ISSUE TITLE
Error when checking and downloading spellcheck files.

### ISSUE THREAD

**Issue by altwazar** [LunarVim/LunarVim#3619]
### Problem description

If set in `.config/lvim/config.lua` option:
```
vim.opt.spelllang = { "en", "ru" }
```
i get errors when opening lvim about:
```
spellfile#LoadFile(): No (writable) spell directory found.
then
Failed to create: /home/USER/.local/share/nvim/site/spell
(directory created and writable)
then
Warning: Cannot find word list "ru.utf-8.spl" or "ru.ascii.spl"
```
Workaround:
```
ln -s /home/USER/.local/share/nvim/site/spell/ ~/.local/share/lunarvim/site/spell
```

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.1

### Operating system/version

Gentoo

**Comment by LostNeophyte** [comment]
create a spell directory in ~/.config/lvim

**Comment by cyga** [comment]
It still doesn't work with the main version:
master-4b77c9c
Nvim version:
v0.8.2
OS version:
Ubuntu 22.04.01

I have exactly the same error whenever I enable spelling `set spell`.
However, it works in `nvim`.
Files are loaded already (by `nvim` automatically).
Creating symbolic link doesn't work:
`ln -s ~/.local/share/nvim/site/spell/ ~/.local/share/lunarvim/site/spell`
