### ISSUE TITLE
Pocco81/auto-save  conflict with lvim.format_on_save.enabled = true

### ISSUE THREAD

**Issue by fastfading** [LunarVim/LunarVim#3621]
### Problem description

 {
        "Pocco81/auto-save.nvim",
        config = function()
            require("auto-save").setup()
        end
 },

lvim.format_on_save.enabled = true

in some situation ,
when you save somthing , it will autoformat,  if you undo it ,it will autofomat again , that cause you stuck in this undo step

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

nvim 0.8

### Operating system/version

macos 13

**Comment by LostNeophyte** [comment]
that's expected

**Comment by LostNeophyte** [comment]
remove `TextChanged` from trigger_events
