### ISSUE TITLE
Got an blank box when :LvimSyncCorePlugins

### ISSUE THREAD

**Issue by LiaoZiw** [LunarVim/LunarVim#3624]
### Problem description

Here are warnings for :LvimSyncCorePlugins
![warnings](https://user-images.githubusercontent.com/100927897/208088870-4e5cd4ed-2de3-493d-b479-bb380d7d5608.png)

Here are the blank box. It kept this state for half an hour and I exit. I repeated LvimSyncCorePlugins for many times and got the same situation.
![blankpic](https://user-images.githubusercontent.com/100927897/208088861-04127f12-a16e-4ab1-af85-0b2b9dc5d1cb.png)

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

0.9.0-dev-505+ga6b05cb75

### Operating system/version

Windows 11

### Steps to reproduce

I use PowerShell 7.3.1
Simply :LvimSyncCorePlugins inside lvim and this happened again.

**Comment by LostNeophyte** [comment]
does `:PakerSync` work?

**Comment by LiaoZiw** [comment]
> does `:PakerSync` work?

No. :PackerSync got exactly the same situation.

**Comment by LostNeophyte** [comment]
remove all folders form `APPDATA/lunarvim/site` and the autogenerated `plugin` folder in your config, then restart lvim and run `:PackerSync`
