### ISSUE TITLE
dap-ui setup

### ISSUE THREAD

**Issue by amit-ug** [LunarVim/LunarVim#3630]
### Feature Description

dap-ui is currently builtin in LunarVim, I would like to configure it so that I could change the displayed dap windows and their layout.

### Describe the alternatives you have considered

I assume I can override the default settings, not clear about how to do that and would rather lvim expose the layout part (so I don't break the current setup).

**Comment by LostNeophyte** [comment]
dap-ui is configurable using `lvim.builtin.dap.ui` 
https://github.com/LunarVim/LunarVim/blob/b661efb3179e9ee7c44c5b2f885f5a7e837ea19d/lua/lvim/core/dap.lua#L28

**Comment by amitkot** [comment]
@LostNeophyte thanks! 🙏
