### ISSUE TITLE
i am getting error in asm-lsp installation 

### ISSUE THREAD

**Issue by 0xMrR0b0t** [LunarVim/LunarVim#3631]
### Problem description

i am getting error in asm-lsp installation 
![image](https://user-images.githubusercontent.com/53564887/208422084-6e8de49d-e3e5-45d3-9ab7-be62d21de771.png)

### LunarVim version

master-b661efb

### Neovim version (>= 0.8.0)

0.8.1

### Operating system/version

kali linux

### Affected language servers

asm-lsp

### Actual behavior

getting error in installation 

### support info

![image](https://user-images.githubusercontent.com/53564887/208422432-af42a097-f257-4fdc-ae51-a66d24e3f722.png)

**Comment by LostNeophyte** [comment]
looks like cargo can't compile it, not a lunarvim problem

**Comment by 0xMrR0b0t** [comment]
> looks like cargo can't compile it, not a lunarvim problem

can you tell me how to fix it

**Comment by LostNeophyte** [comment]
I don't know

**Comment by 0xMrR0b0t** [comment]
ohk bro

**Comment by LostNeophyte** [comment]
you can try manually installing it
