### ISSUE TITLE
feat: Switch plugin management system to `lazy.nvim`

### ISSUE THREAD

**Issue by BlueFalconHD** [LunarVim/LunarVim#3645]
### Feature Description

I recently found [`lazy.nvim`](https://github.com/folke/lazy.nvim). I tried it out, and it works great! Though `packer.nvim` is great, I feel `lazy.nvim` would be a better fit. Here are some reasons why:

- Mason-like install menu: `lazy.nvim` provides easy install and update overviews, which can be very helpful in some cases, but `packer.nvim` lacks this feature.	
- Replacement for `packer.nvim`: Packer is a great package manager, and provides many useful tools. The thing is, with the abstractions LunarVim provides, it could be a simple change for the more friendly `lazy.nvim` to replace it.

-----

- **Some features that would make LunarVim even better:** (from https://github.com/folke/lazy.nvim/blob/main/README.md)

	- 🔒 Lockfile lazy-lock.json to keep track of installed plugins: This could be helpful for automatically adding core plugins.
	- 📁 Configurable in multiple files: This might make it easier to integrate into the abstractions that LunarVim provides.
	- 💻 Dev options and patterns for using local plugins: This could be helpful for loading core plugins.
	- 🚀 Fast startup times thanks to automatic caching and bytecode compilation of lua modules: This could improve LunarVim's performance.
	- 🔌 Automatic lazy-loading of lua modules and lazy-loading on events, commands, filetypes, and key mappings: This could improve LunarVim's performance.
	- ⏳ Automatically install missing plugins before starting up Neovim, allowing you to start using it right away: This could make sure there are no errors on startup due to missing or deleted plugins
	- 💪 Async execution for improved performance: This could improve LunarVim's performance.

### Describe the alternatives you have considered

- Keep `packer.nvim`
- Writing a custom plugin manager (unlikely)

### Support information

- link to `lazy.nvim`: https://github.com/folke/lazy.nvim
- screenshot of interface:
![image](https://user-images.githubusercontent.com/72631767/208965540-e5e80ee0-b709-4cfa-9c46-1b599c3e5991.png)

**Comment by LostNeophyte** [comment]
The change would be breaking (lazy uses different names for things than packer) and packer is quite deep in our core and even ci, switching wouldn't be that easy, but we are thinking about it

**Comment by BlueFalconHD** [comment]
> The change would be breaking (lazy uses different names for things than packer) and packer is quite deep in our core and even ci, switching wouldn't be that easy, but we are thinking about it

In the readme, there is a migration guide from packer.

**Comment by LostNeophyte** [comment]
> > The change would be breaking (lazy uses different names for things than packer) and packer is quite deep in our core and even ci, switching wouldn't be that easy, but we are thinking about it
> 
> In the readme, there is a migration guide from packer.

It's not that easy unfortunately, lazy completely disables neovim's plugin loading which we used

**Comment by Uzaaft** [comment]
I'm available for testing if you need anyone @LostNeophyte

**Comment by LostNeophyte** [comment]
> I'm available for testing if you need anyone @LostNeophyte 

Thanks, not yet but testing help will be needed

**Comment by Uzaaft** [comment]
@abzcoding  Be aware, huge changes are happening 👀

**Comment by LostNeophyte** [comment]
@Uzaaft, if you want to test, you can grab an appimage from [here](https://github.com/LunarVim/LunarVim-mono/releases/tag/nightly), (it's probably the easiest) when you run it the first time plugins should get copied and when it's done the dashboard should open. If you encounted any errors, report them - they are bugs, the refactor should be backwards compatible

**Comment by Uzaaft** [comment]
On it 🫡

**Comment by Uzaaft** [comment]
@LostNeophyte Shouldn't we remove impatient? Ref Performance section in the lazy.nvim readme. 

<img width="564" alt="image" src="https://user-images.githubusercontent.com/48220549/209860220-c4629aa6-8e3a-47f0-be6c-a944ed311ed7.png">

**Comment by LostNeophyte** [comment]
> @LostNeophyte Shouldn't we remove impatient? Ref Performance section in the lazy.nvim readme. 
> 
> <img width="564" alt="image" src="https://user-images.githubusercontent.com/48220549/209860220-c4629aa6-8e3a-47f0-be6c-a944ed311ed7.png">

It is removed in the pr

**Comment by Uzaaft** [comment]
> @Uzaaft (or anyone), if you want to test, you can grab an appimage from [here](https://github.com/LunarVim/LunarVim-mono/releases/tag/nightly), (it's probably the easiest) when you run it the first time plugins should get copied and when it's done the dashboard should open. If you encounted any errors, report them - they are bugs, the refactor should be backwards compatible

Initial testing went fine. I'll be coding a bit the next 2-3 hours in different codebases and languages, so something might come up.

@LostNeophyte  Great work! It's impressive how fast you were!

**Comment by Uzaaft** [comment]
I've got some issues with a dependency:
git.sr.ht/~whynothugo/lsp_lines.nvim

Seems like using it like this:

```lua

{url = "git.sr.ht/~whynothugo/lsp_lines.nvim"
}
```lua
breaks my whole config, while:
{"git.sr.ht/~whynothugo/lsp_lines.nvim"
}
``` 
works fine.

**Comment by folke** [comment]
The url should be `https://git.sr.ht/~whynothugo/lsp_lines.nvim`

**Comment by Uzaaft** [comment]
> The url should be `{url = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"}`

Doesn't work for me. Config is still broken for some reason

**Comment by LostNeophyte** [comment]
> {url = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"}

see if `{ "https://git.sr.ht/~whynothugo/lsp_lines.nvim"}` works, there might be a bug in my deprecation handler

**Comment by Uzaaft** [comment]
Issue seems to be with line 147 in `lua/lvim/config/_deprecated.lua`.
Deactivating it and everything works as expected. Besides the UI things mentioning in abzcoding/lvim

**Comment by Uzaaft** [comment]
> > {url = "[https://git.sr.ht/~whynothugo/lsp_lines.nvim"}](https://git.sr.ht/~whynothugo/lsp_lines.nvim%22%7D)
> 
> see if `{ "https://git.sr.ht/~whynothugo/lsp_lines.nvim"}` works, there ~might be~ is a bug in my deprecation handler

This works.

**Comment by LostNeophyte** [comment]
> Besides the UI specific things mentioning in abzcoding/lvim.

Which things?

**Comment by Uzaaft** [comment]
The UI doesn't seem to be the same. See the below screenshots.
I've a hunch that it might be due to how we've set up the loading of the configs.  Config is at:
https://github.com/Uzaaft/lvim-abz

<img width="1770" alt="image" src="https://user-images.githubusercontent.com/48220549/209937114-47a8fef0-8612-40a4-8e73-6d690d7965e7.png">
<img width="1787" alt="image" src="https://user-images.githubusercontent.com/48220549/209937152-d94a0f41-29ec-4fb4-9f78-e08366484ee1.png">

**Comment by LostNeophyte** [comment]
> The UI doesn't seem to be the same. See the below screenshots. I've a hunch that it might be due to how we've set up the loading of the configs. Left is packer, right is lazy Config is at: https://github.com/Uzaaft/lvim-abz
> 

see if this helps
```lua
vim.api.nvim_create_autocmd("ColorScheme", {
  pattern = "*",
  callback = function()
    require("user.theme").telescope_theme()
  end,
})
````

**Comment by LostNeophyte** [comment]
> Issue seems to be with line 147 in `lua/lvim/config/_deprecated.lua`. Deactivating it and everything works as expected. Besides the UI specific things mentioning in abzcoding/lvim. Edit: Posted this before I saw your comment

should be fixed now, (you need to redownload the appimage, it can't be updated)

**Comment by Uzaaft** [comment]
I appreciate the help! Everything seems to work now!
