### ISSUE TITLE
Packer tries to remove nvim-web-devicons when i add a plugin

### ISSUE THREAD

**Issue by alyxeo2k** [LunarVim/LunarVim#3650]
### Problem description

To reproduce
Just install any plugin

i just reinstalled lunarvim and when i add a new plugin packer asks to delete nvim-web-devicons
it does this every time i add or remove or update my packages

### LunarVim version

master-3262e50

### Neovim version (>= 0.8.0)

NVIM v0.9.0

### Operating system/version

Windows 10 21H2

### Steps to reproduce

1. Try to delete or install or update any plugins using packersync

### Screenshots

![image](https://user-images.githubusercontent.com/71589762/209274037-96660623-c52e-4156-a78a-9fa8b99fdf56.png)

**Comment by alyxeo2k** [comment]
if you say yes it breaks lunarvim, so thats why i reinstalled

**Comment by BlueFalconHD** [comment]
I get this too. Maybe we can wait for #3647 from #3645 to resolve this. I have a feeling this is Packer being weird.

**Comment by LostNeophyte** [comment]
I can't reproduce with empty config, or with my config, or with the default config

**Comment by ksajan** [comment]
I also get this issue whenever I try to add new plugin or enable new plugins.

**Comment by LostNeophyte** [comment]
> I also get this issue whenever I try to add new plugin or enable new plugins. 

Is there anything in :messages? How did you add the plugin?

**Comment by ksajan** [comment]
added in config.lua. I am using MacOS Ventura 13.1.

**Comment by BlueFalconHD** [comment]
Try switching to Nightly. This fixed it for me.
