### ISSUE TITLE
[Windows] Install suceess but no changes

### ISSUE THREAD

**Issue by Asthestarsfalll** [LunarVim/LunarVim#3651]
### Problem description

1. I have installed neovim of version 0.8.0 via msi file
2. set alias 'nvim'
3. install lunarvim 
```bash
$LV_BRANCH='release-1.2/neovim-0.8'; Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression
```
4. But when I type lvim, it doesn't have any changes

### LunarVim version

release-1.2/neovim-0.8

### Neovim version (>= 0.8.0)

0.8.0

### Operating system/version

Windows 11

### Screenshots

There is no changes between nvim and lvim
![image](https://user-images.githubusercontent.com/72954905/209286334-eacaa8e2-a7a0-469f-a8ee-798ff89caa82.png)

**Comment by LostNeophyte** [comment]
Run :PackerSync

**Comment by LostNeophyte** [comment]
The msi file is not a supported way of installation

**Comment by LostNeophyte** [comment]
Only the official installer is

**Comment by Asthestarsfalll** [comment]
@LostNeophyte 
Thanks for your help.
![image](https://user-images.githubusercontent.com/72954905/209290137-bb28afb6-6c07-4606-be4d-eef63f1c6cae.png)
So I need to install neovim from source?

**Comment by LostNeophyte** [comment]
Use the install method from the website

**Comment by Asthestarsfalll** [comment]
![image](https://user-images.githubusercontent.com/72954905/209290984-1bff0e73-3229-4ab9-b0e2-f6413316700f.png)
![image](https://user-images.githubusercontent.com/72954905/209290882-89fdcc44-0ccc-4c1f-9b6a-10a49136f945.png)
It still use the msi file

**Comment by LostNeophyte** [comment]
Thats neovim instructions, you can use msi to install neovim

**Comment by LostNeophyte** [comment]
Oh man, my bad i completely misunderstood

**Comment by Asthestarsfalll** [comment]
I remove the alias of 'nvim' and it now works well.
Thank you very much! 
![image](https://user-images.githubusercontent.com/72954905/209291908-622c2e18-8121-4a61-a800-3a6a210b3669.png)
