### ISSUE TITLE
huge lag after space.

### ISSUE THREAD

**Issue by littleblack111** [LunarVim/LunarVim#3653]
### Problem description

after a keyword/word, when I pressed the space bar, it took nearly 3-7secound to respond (for only the space which added only a space(gap))

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Operating system/version

ArchCraft 2021.10

### Affected language servers

all

### Steps to reproduce

just type space/press space bar when you are in lvim

### Actual behavior

after a keyword/word, when I pressed the space bar, it took nearly 3-7secound to respond (for only the space which added only a space(gap))

### Expected behavior

just type space like typing other charactors

### support info

```console
#:LspInfo
 Language client log: /home/system/.local/state/nvim/lsp.log
 Detected filetype:   zsh
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: 
#LvimInfo

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                zsh
* bufnr:                   1
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: beautysh

Linters info
* Active: 
* Supported: zsh

Code actions info
* Active: 

### logs

_No response_

### Screenshots

_No response_

**Comment by LostNeophyte** [comment]
1. does the same happen with an empty config?
2. does the same happen with an empty config and a txt file?

**Comment by littleblack111** [comment]
> 1. does the same happen with an empty config?
> 2. does the same happen with an empty config and a txt file?


do you mean by the init.lua? or in the ~/.config/lvim, if I remove ~/.config/lvim/config.lua, it does happen as well, but if i remove ~/.local/share/lunarvim/lvim/init.lua, it will just have a tone of error and it will act like neovim and it is very strange, but it won't happen again.

**Comment by littleblack111** [comment]
do you mean by the init.lua? or in the ~/.config/lvim, if I remove ~/.config/lvim/config.lua, it does happen as well, but if i remove ~/.local/share/lunarvim/lvim/init.lua, it will just have a tone of error and it will act like neovim and it is very strange, but it won't happen again.
I pretty much believe it doesn't really meter with the config files, since I only added a plugin and I already have this issue once I installed it.

**Comment by LostNeophyte** [comment]
> do you mean by the init.lua? or in the ~/.config/lvim, if I remove ~/.config/lvim/config.lua, it does happen as well, but if i remove ~/.local/share/lunarvim/lvim/init.lua, it will just have a tone of error and it will act like neovim and it is very strange, but it won't happen again. I pretty much believe it doesn't really meter with the config files, since I only added a plugin and I already have this issue once I installed it.

I meant config.lua, does it happen no matter the filetype (test .txt and .lua)

**Comment by littleblack111** [comment]
i still happens even i change the file type, it will generate a new config.lua

**Comment by LostNeophyte** [comment]
> i still happens even i change the file type, it will generate a new config.lua. added: sometimes when I press space too fast, it will automatically write in the file, and most of the keys after pressing space have some special things, like pressing p right after pressing space, will make lvim write PeepOpen

I've got no idea what that can be, does neovim work normally?

**Comment by littleblack111** [comment]
yes, neovim work fine.

**Comment by littleblack111** [comment]
I think I installed a wrong lunarvim version(it might be the nightly build one) and I reinstalled the release/stable one, and now it works fine.
