### ISSUE TITLE
Explorer pane expands to take up half of screen when active file tab is closed

### ISSUE THREAD

**Issue by eedrxs** [LunarVim/LunarVim#3654]
### Problem description

Whenever the explorer pane is open and you close the current active file tab, the explorer pane will then take up the whole screen and obscure any remaining open file tab. If you then click on any of the other file tabs that weren't closed or open a new file from the explorer pane, the screen will then be split into two equal halves: the explorer pane on the left half and the rest of the file tabs on the right half.

When this happens, you would now have to manually resize and reduce the explorer pane width. The explorer pane should stay the exact same size it was before you closed the active file tab.

### LunarVim version

master-30c65cf

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Ubuntu 22.04.1 LTS

### Screenshots

1. Closing active file tab
![Screenshot from 2022-12-25 03-16-00](https://user-images.githubusercontent.com/76642653/209455128-8860a8d1-a3c5-4ad6-8c80-ef7340048f9d.png)

2. Explorer pane expanding to take up all screen and obscuring remaining file tabs
![Screenshot from 2022-12-25 03-16-25](https://user-images.githubusercontent.com/76642653/209455137-af5c141b-8a87-4281-9ee8-d49e9f5e0174.png)

3. Screen splitting into two equal halves when you click on any of the remaining file tabs, with explorer pane on the left and the file tabs on the right
![Screenshot from 2022-12-25 03-16-42](https://user-images.githubusercontent.com/76642653/209455158-3326114d-4658-4dc2-ae52-0500a369d0d8.png)

**Comment by LostNeophyte** [comment]
nvimtree does not take up the whole screen if you close any tab, unless you do it with `:q` or `leader q`, then it's expected (you should use `leader c` or `:BufferKill` or the x button)

**Comment by eedrxs** [comment]
I close tabs using the 'x' button and nvimtree does take up the whole screen if you close the active tab currently in view while it is open.

With that said however, I just updated my LunarVim and I notice that quirk is no longer there.

**Comment by LostNeophyte** [comment]
> With that said however, I just updated my LunarVim and I notice that quirk is no longer there.

Can the issue be closed in that case?
