### ISSUE TITLE
annoying line annotations

### ISSUE THREAD

**Issue by jacek-kurlit** [LunarVim/LunarVim#3655]
### Problem description

When I try to edit line, auto completion is getting masked by line annotation (in green, config.lua + (~/.config/lvim) - NVIM)
![image](https://user-images.githubusercontent.com/6184283/209480491-c2e78a04-a76c-4911-8edc-d9ae28325817.png)

This is my fresh installation of lvim, I haven't chanced anything except relative lines.
How Can I get rid of these line annotations?

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.1

### Operating system/version

fedora 37

### Steps to reproduce

1. Edit config.lua after fresh installation
2. Line is getting masked by line annotation when auto completion popup is shown.

### Screenshots

![image](https://user-images.githubusercontent.com/6184283/209480614-1d206521-52ba-4180-95c6-665118cb0cb4.png)

**Comment by LostNeophyte** [comment]
duplicate: see the second pinned issue
