### ISSUE TITLE
Add support for ruff in Python settings

### ISSUE THREAD

**Issue by danielvelara** [LunarVim/LunarVim#3659]
### Feature Description

Add support for [ruff- An extremely fast Python linter, written in Rust](https://github.com/charliermarsh/ruff)

### Describe the alternatives you have considered

ruff has become one of the most popular linters in the Python ecosystem, gaining a lot of followers in 2022.

It would be nice if LunarVim added support for it in the near future.

**Comment by LostNeophyte** [comment]
it's already supported on master :) (https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1290)
for the future, feature requests for linters/fromatters should go to [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) not lunarvim

**Comment by amitkot** [comment]
@danielvelara @LostNeophyte how can I turn it on in LunarVim using null-ls? 🙏
