### ISSUE TITLE
"dim_inactive" option for tokyonight theme does not seem to work

### ISSUE THREAD

**Issue by Juniar-Rakhman** [LunarVim/LunarVim#3660]
### Problem description

I have the following user configuration 
```lua
lvim.colorscheme = "tokyonight"
lvim.builtin.theme.tokyonight.options.style = "storm"
lvim.builtin.theme.tokyonight.options.dim_inactive = true
```
I set dim_inactive to true, but when I split the window and move from 1 split to another, the background for the inactive window is not dimmed. I don't notice any difference between the inactive and active window. Am I missing something?

### LunarVim version

release-1.2/neovim-0.8

### Neovim version (>= 0.8.0)

NVIM v0.8.0-v0.8.0

### Operating system/version

Pop OS 22.04

### Steps to reproduce

1. Use the following configuration : 
```lua
lvim.colorscheme = "tokyonight"
lvim.builtin.theme.tokyonight.options.style = "storm"
lvim.builtin.theme.tokyonight.options.dim_inactive = true
```
2. Open file in LunarVim
3. Split the window
4. Move cursor from 1 window to another
5. Inactive window is not dimmed

**Comment by LostNeophyte** [comment]
set `lvim.builtin.theme` to "tokyonight" as well

**Comment by Juniar-Rakhman** [comment]
Thanks! it works now.
