### ISSUE TITLE
Can't disable document highlight

### ISSUE THREAD

**Issue by kbrah** [LunarVim/LunarVim#3664]
### Problem description

Despite following settings document highlight is still on.

```
lvim.lsp.document_highlight = false
lvim.builtin.treesitter.highlight.enable = false
```

### LunarVim version

master-9bc82e4

### Neovim version (>= 0.8.0)

0.8.1

### Operating system/version

Linux

**Comment by LostNeophyte** [comment]
if you want no highlighting at all add `vim.cmd("syntax off")` to your config

also, does `lvim.lsp.document_highlight` option exist?

**Comment by kbrah** [comment]
I want to disable the reference highlighting under cursor

**Comment by LostNeophyte** [comment]
`lvim.builtin.illuminate.active = false` in that case
