### ISSUE TITLE
LSP[sumneko_lua] Your workspace is set to $HOME. 

### ISSUE THREAD

**Issue by JxJxxJxJ** [LunarVim/LunarVim#3667]
### Problem description

When I try to configure my `~/.config/lvim/config.lua` this happens. The settings I set there still get applied, so I'm not sure how severe is this. 

![image](https://user-images.githubusercontent.com/103049321/210024154-81edc8cb-48cf-4d72-96ac-27291863dcce.png)

### LunarVim version

master-9bc82e4

### Neovim version (>= 0.8.0)

NVIM v0.8.2

### Operating system/version

GNU/Linux - Arch

### Affected language servers

sumneko_lua

### Actual behavior

Error appears but isn't problematic. Reloading config works fine.

### support info

`:LspInfo`

>  Language client log: /home/Jx/.local/state/nvim/lsp.log
>  Detected filetype:   lua
>  
>  1 client(s) attached to this buffer: 
>  
>  Client: sumneko_lua (id: 1, bufnr: [3])
>  	filetypes:       lua
>  	autostart:       true
>  	root directory:  /home/Jx
>  	cmd:             lua-language-server
>  
>  Configured servers list: sumneko_lua

`lvim.info`

>     __                          _    ___         
>    / /   __  ______  ____ _____| |  / (_)___ ___ 
>   / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
>  / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
> /_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 
> 
> 
> Buffer info
> * filetype:                lua
> * bufnr:                   3
> * treesitter status:       active
> 
> Active client(s)
> * name:                      sumneko_lua
> * id:                        1
> * supported filetype(s):     lua
> * attached buffers:          3
> * root_dir pattern:          3
> * capabilities:              documentRangeFormattingProvider | definitionProvider      | typeDefinitionProvider
>                              documentHighlightProvider       | workspaceSymbolProvider | colorProvider
>                              documentFormattingProvider      | foldingRangeProvider    | hoverProvider
>                              referencesProvider              | documentSymbolProvider
> 
> Automatic LSP info
> * Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, neocmake, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rnix, rome, ruby_ls, solang, solc, sorbet, sourcery, spectral, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]
> 
> Formatters info
> * Active: 
> * Supported: [lua_format, stylua]
> 
> Linters info
> * Active: 
> * Supported: [luacheck, selene]
> 
> Code actions info
> * Active: 

### logs

```console
[START][2022-12-29 09:43:01] LSP logging initiated
[WARN][2022-12-29 09:43:01] ...lsp/handlers.lua:487	"Environment variable configuration is being deprecated, please use workspace configuration. The following environment variables were used: globPattern"
[WARN][2022-12-29 09:43:01] ...lsp/handlers.lua:113	"The language server bashls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2022-12-29 09:43:01] ...lsp/handlers.lua:487	'updateConfiguration: failed with [\n  {\n    "code": "invalid_type",\n    "expected": "object",\n    "received": "null",\n    "path": [],\n    "message": "Expected object, received null"\n  }\n]'
[WARN][2022-12-29 09:43:01] ...lsp/handlers.lua:487	"ShellCheck: disabling linting as no executable was found at path 'shellcheck'"
[START][2022-12-29 10:29:49] LSP logging initiated
[WARN][2022-12-29 10:29:49] ...lsp/handlers.lua:487	"Environment variable configuration is being deprecated, please use workspace configuration. The following environment variables were used: globPattern"
[WARN][2022-12-29 10:29:49] ...lsp/handlers.lua:113	"The language server bashls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2022-12-29 10:29:49] ...lsp/handlers.lua:487	'updateConfiguration: failed with [\n  {\n    "code": "invalid_type",\n    "expected": "object",\n    "received": "null",\n    "path": [],\n    "message": "Expected object, received null"\n  }\n]'
[WARN][2022-12-29 10:29:49] ...lsp/handlers.lua:487	"ShellCheck: disabling linting as no executable was found at path 'shellcheck'"
[START][2022-12-29 21:29:13] LSP logging initiated
[ERROR][2022-12-29 21:29:13] ...lsp/handlers.lua:485	"Your workspace is set to `/home/Jx`. Lua language server refused to load this directory. Please check your configuration.[learn more here](https://github.com/sumneko/lua-language-server/wiki/FAQ#why-is-the-server-scanning-the-wrong-folder)"
[WARN][2022-12-29 21:29:16] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2022-12-29 21:29:16] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-12-29 21:29:59] LSP logging initiated
[ERROR][2022-12-29 21:29:59] ...lsp/handlers.lua:485	"Your workspace is set to `/home/Jx`. Lua language server refused to load this directory. Please check your configuration.[learn more here](https://github.com/sumneko/lua-language-server/wiki/FAQ#why-is-the-server-scanning-the-wrong-folder)"
[WARN][2022-12-29 21:30:02] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2022-12-29 21:30:02] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-12-29 21:39:01] LSP logging initiated
[ERROR][2022-12-29 21:39:01] ...lsp/handlers.lua:485	"Your workspace is set to `/home/Jx`. Lua language server refused to load this directory. Please check your configuration.[learn more here](https://github.com/sumneko/lua-language-server/wiki/FAQ#why-is-the-server-scanning-the-wrong-folder)"
[WARN][2022-12-29 21:39:04] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2022-12-29 21:39:04] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-12-29 21:39:50] LSP logging initiated
[ERROR][2022-12-29 21:39:50] ...lsp/handlers.lua:485	"Your workspace is set to `/home/Jx`. Lua language server refused to load this directory. Please check your configuration.[learn more here](https://github.com/sumneko/lua-language-server/wiki/FAQ#why-is-the-server-scanning-the-wrong-folder)"
[WARN][2022-12-29 21:39:53] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2022-12-29 21:39:53] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-12-29 21:42:44] LSP logging initiated
[ERROR][2022-12-29 21:42:44] ...lsp/handlers.lua:485	"Your workspace is set to `/home/Jx`. Lua language server refused to load this directory. Please check your configuration.[learn more here](https://github.com/sumneko/lua-language-server/wiki/FAQ#why-is-the-server-scanning-the-wrong-folder)"
[WARN][2022-12-29 21:42:47] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2022-12-29 21:42:47] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-12-29 21:43:50] LSP logging initiated
[WARN][2022-12-29 21:43:50] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2022-12-29 21:43:51] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-12-29 21:44:02] LSP logging initiated
[ERROR][2022-12-29 21:44:02] ...lsp/handlers.lua:485	"Your workspace is set to `/home/Jx`. Lua language server refused to load this directory. Please check your configuration.[learn more here](https://github.com/sumneko/lua-language-server/wiki/FAQ#why-is-the-server-scanning-the-wrong-folder)"
[START][2022-12-29 21:46:20] LSP logging initiated
[ERROR][2022-12-29 21:46:20] ...lsp/handlers.lua:485	"Your workspace is set to `/home/Jx`. Lua language server refused to load this directory. Please check your configuration.[learn more here](https://github.com/sumneko/lua-language-server/wiki/FAQ#why-is-the-server-scanning-the-wrong-folder)"
[WARN][2022-12-29 21:46:23] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2022-12-29 21:46:24] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
```

**Comment by LostNeophyte** [comment]
Have one of there files in .config/lvim and make sure you don't have any if these in HOME
`root_pattern(".luarc.json", ".luarc.jsonc", ".luacheckrc", ".stylua.toml", "stylua.toml", "selene.toml", "selene.yml", ".git")`

**Comment by JxJxxJxJ** [comment]
Sorry for the late response, 

> Have one of there files in .config/lvim and make sure you don't have any if these in HOME `root_pattern(".luarc.json", ".luarc.jsonc", ".luacheckrc", ".stylua.toml", "stylua.toml", "selene.toml", "selene.yml", ".git")`

I don't quite understand, am I looking for those files in `$HOME`? I don't have any of them.

**Comment by LostNeophyte** [comment]
create a `stylua.toml` in .config/lvim and see it that helps

**Comment by JxJxxJxJ** [comment]
Hey, thanks for the quick response. In In `~/.config/lvim` I only have these, which differ from my desktop installation. Might this be the issue? 

`~/.config/lvim`
> ├── config.lua
> └── plugin
>     └── packer_compiled.lua

**Comment by JxJxxJxJ** [comment]
> create a `stylua.toml` in .config/lvim and see it that helps

`touch ~/.config/lvim/stylua.toml` fixed the issue, thank you. May I know if anything is wrong with my installation?

**Comment by LostNeophyte** [comment]
> May I know if anything is wrong with my installation?

it's all good, lspconfig needs one of these files, otherwise it doesn't know where the root of the project is
