### ISSUE TITLE
tea.xyz support (pantry)

### ISSUE THREAD

**Issue by hinogi** [LunarVim/LunarVim#3668]
### Feature Description

https://www.lunarvim.org/
tea +python.org +rust-lang.org +neovim.io +gnu.org/make
LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

Installation of Rust dependencies: fd::fd-find, rg::ripgrep doesn't seem to work due to some unknown dependencies but the rest should work.

**Comment by LostNeophyte** [comment]
https://github.com/teaxyz/pantry.extra/issues/94 (just wanted to link the two issues)
