### ISSUE TITLE
How to make the completion case smart?

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3671]
### Problem description

![image](https://user-images.githubusercontent.com/11295355/210160928-43c5fe1c-bbb4-4827-8d7a-8736111960c8.png)

Here is the case. When I type "Comple" with capital "C" the completion become "completion" with lowercase, how to fix it?

### LunarVim version

master-e45afe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0-dev-914-gd4d27c41b

### Operating system/version

OS: Ubuntu 22.04 jammy

**Comment by LostNeophyte** [comment]
the case is smart, but here a longer match takes precedence, if you just type `Co` then `Compiled` will be first

**Comment by LostNeophyte** [comment]
you can customize it yourself using `lvim.builtin.cmp.sorting` if you want different behavious, see https://github.com/hrsh7th/nvim-cmp/issues/381 for examples
