### ISSUE TITLE
Keep a dedicated (frozen ?) 0.7 branch

### ISSUE THREAD

**Issue by bestouff** [LunarVim/LunarVim#3673]
### Feature Description

Some people don't have easy access to Neovim 0.8. For example if you install Debian on a non-x86 arch (think an M1 mac):
- the official repos don't have 0.8 (and being Debian, maybe won't have them soon, even in "experimental")
- the optional Ubuntu PPA don't have 0.8
- Neovim official releases exist only for x86
- ... and then even if you build your own, updating individual packages via source is a long-term pain

So how about keeping a branch/label (with associated installation instructions) for those stuck with 0.7, even if it's prominently marked as "not supported" ?

### Describe the alternatives you have considered

Manually recompiling Neovim

**Comment by LostNeophyte** [comment]
There are older tags, you can try these

**Comment by bestouff** [comment]
I tried a few, none of them install correctly.
Do you have an idea which one, and how I should invoke the installation (maybe I do it wrong) ?

**Comment by LostNeophyte** [comment]
try this ```bash
LV_BRANCH='1.1.4' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/1.1.4/utils/installer/install.sh)
```

**Comment by bestouff** [comment]
This fails; here's then end of the output:
```
[packer.nvim] [INFO  19:14:42] (tail call):-1: Finished compiling lazy-loaders!
[packer.nvim] [DEBUG 19:14:42] (tail call):-1: packer.compile: CompletePacker setup complete
--------------------------------------------------------------------------------
Verifying core plugins
Error detected while processing BufWinEnter Autocommands for "*":
E5108: Error executing lua Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...te/pack/packer/start/packer.nvim/lua/packer/load.lua:110: Vim(lua):E5108: Error executing lua ...arvim/site/pack/packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:21: '=' expected near 'continue'
stack traceback:
	[C]: in function 'nvim_exec'
	?: in function 'cmd'
	...te/pack/packer/start/packer.nvim/lua/packer/load.lua:165: in function <...te/pack/packer/start/packer.nvim/lua/packer/load.lua:161>
	[string ":lua"]:1: in main chunk
E5108: Error executing lua ...arvim/site/pack/packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:21: '=' expected near 'continue'
stack traceback:
	[C]: in function 'error'
	?: in function <?:18>
	[C]: in function 'require'
	[string ":lua"]:1: in main chunk
Error detected while processing command line:
packer.nvim: Error running config for LuaSnip: ...arvim/site/pack/packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:21: '=' expected near 'continue'mismatch at [nvim-treesitter]: expected [07b7221], got [07b72215]
[ERROR]: Unable to verify plugins, make sure to manually run ':PackerSync' when starting lvim for the first time.
```

**Comment by LostNeophyte** [comment]
What if you open lvim, ignore the errors and run PackerSync?

**Comment by bestouff** [comment]
PackerSync opens an empty window and shows this error:
```
[packer.nvim] ^I...e/pack/packer/start/packer.nvim/lua/packer/async.lua:12: in function <...e/pack/packer/start/packer.nvim/lua/packer/async.lua:11>
```
... and then nothing.

**Comment by gonviegas** [comment]
Just compile neovim. That's usually how you handle those types of problems in debian anyway. Doesn't make much sense to have a dedicated branch when you just need to compile neovim.

**Comment by bestouff** [comment]
Ok right.
