### ISSUE TITLE
Iskeyword set failed.

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3675]
### Problem description

Here is my settings you can see there is a `/` in it.
![image](https://user-images.githubusercontent.com/11295355/210705259-1b9fd81d-2efd-420d-b538-c6b3dea56e0d.png)

but on the word `/a/b/c{cursor here}` i press `b` it jumps to the head of the whole word

`{cursor here}/a/b/c`

Why and how to fix it?

### LunarVim version

master-e45afe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0-dev-914-gd4d27c41b

### Operating system/version

OS: Ubuntu 22.04 jammy

**Comment by LostNeophyte** [comment]
> but on the word /a/b/c{cursor here} i press b it jumps to the head of the whole word

that's because you added `/` to iskeyword,

it will go to `b` and then to `a` by default

**Comment by woshichuanqilz** [comment]
> > but on the word /a/b/c{cursor here} i press b it jumps to the head of the whole word
> 
> that's because you added `/` to iskeyword,
> 
> it will go to `b` and then to `a` by default

Ok sorry I misunderstand the concept of iskeyword. Sorry for the bad issue
