### ISSUE TITLE
:help error: treesitter/query.lua:219: query: invalid node type at position 14 for language help

### ISSUE THREAD

**Issue by hjoukl** [LunarVim/LunarVim#3680]
### Problem description

Thanks for providing LunarVim!

On Kubuntu 20.04 LTS:
 
1. Install neovim stable from https://github.com/neovim/neovim/releases/tag/stable (at the time of writing: NVIM v0.8.2, Build type: Release, LuaJIT 2.1.0-beta3)
2. Install LunarVim with `LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh`
3. Invoke vim help with `:help` ==> Error:
```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:22: Error executing lua: /usr/share/nvim/runtime/filetype.lua:23
: Vim(append):Error executing lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at p
osition 14 for language help
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: in function 'get_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:52: in function 'new'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:45: in function '_create_parser'
        /usr/share/nvim/runtime/lua/vim/treesitter.lua:96: in function 'get_parser'
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:34: in function 'start'
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:42: in function 'attach'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:505: in function 'attach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function 'reattach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...er/start/nvim-treesitter/lua/nvim-treesitt
er/configs.lua:130>
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
```

After pressing a key the help shows and lvim seems to work. 

https://github.com/nvim-treesitter/nvim-treesitter/issues/3092 sounds related but `TSUpdate` incantations do not make the problem go away, i.e. after restarting lvim the error shows again for `:help`.

IIRC this implies potential inconsistency for treesitter Lua query/parser setup - the output of `:echo nvim_get_runtime_file('*/lua.so', v:true)` yields `['/home/holger/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/parser/lua.so', '/usr/lib/nvim/parser/lua.so']`, fwiw.

This is a fresh install, no previous lvim/nvim config/settings.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.2

### Operating system/version

Linux (Kubuntu 20.04)

### Steps to reproduce

Error is *not* reproducible with `nvim -u .local/share/lunarvim/lvim/tests/minimal_lsp.lua`.

### Screenshots

```
# :checkhealth nvim-treesitter output

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v10.19.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - vim            ✓ ✓ ✓ . ✓
  - tsx            ✓ ✓ ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - css            ✓ . ✓ ✓ ✓
  - java           ✓ ✓ . ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . x

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: help(injections): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 14 for language help
    help(injections) is concatenated from the following files:
    | [ERROR]:"/usr/share/nvim/runtime/queries/help/injections.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 14 for language help
```

**Comment by LostNeophyte** [comment]
run `:TSUpdate`

**Comment by hjoukl** [comment]
> run `:TSUpdate`

Thanks for the quick reaction + suggestion but quoting myself:

"https://github.com/nvim-treesitter/nvim-treesitter/issues/3092 sounds related but **TSUpdate incantations** do not make the problem go away, i.e. after restarting lvim the error shows again for :help."

So I already tried that but it didn't help. Output is "nvim-treesitter: All parsers are up-to-date!" but error message persists.

FWIW I'm also taking a look at https://github.com/AstroNvim/AstroNvim. Running `:help` doesn't trigger an error there but `:checkhealth nvim-treesitter` also outputs lua treesitter problems.

So my guess is this is some nvim-treesitter issue. IIUC it's bundled with neovim so maybe I'll try and downgrade to neovim < 0.8.2.

**Comment by hjoukl** [comment]
> my bad, I read the issue too quickly, try `TSInstall help` and say yes to reinstall, if that won't help then remove the bundled parsers

Downgrading neovim to 0.8.1 didn't change anything so I'm back on 0.8.2. 

After a fresh lunarvim install:

`:TSInstall help` results in
```
Failed to execute the following command:               
{
  cmd = <function 1>
}
```

Running `:TSInstall all` doesn't cure the issue for LunarVim (in contrast to AstroNvim where this seemingly removed its lua highlighting problems).

When I do `:TSUninstall all` I see messages like
```
Tried to uninstall parser for lua! But the parser is still installed (not by nvim-treesitter). Please delete the following files manually: /usr/lib/nvim/parser/lua.so
[nvim-treesitter] [1/4] Treesitter parser for lua has been uninstalled
```
These are the neovim deb package-installed parsers:

```
$ dpkg --search /usr/lib/nvim/parser/lua.so
neovim: /usr/lib/nvim/parser/lua.so
```

However, a restart of `lvim` immediately installs the c, help, lua, vim parsers. Afterwards, the error message for `:help` is still there.

Strange: I tried setting
```
lvim.builtin.treesitter.ensure_installed = {}
```
but installation of above treesitter parsers still happens. Same if I manually delete the parsers I find here in the `nvim-treesitter/parser` dir:

```
$ find .local/share/lunarvim/ -name "*.so"
.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/parser/help.so
.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/parser/vim.so
.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/parser/c.so
.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/parser/lua.so
.local/share/lunarvim/site/pack/packer/start/telescope-fzf-native.nvim/build/libfzf.so
```

Start of lvim triggers immediate reinstallation after nuking the `*.so` files.
So I don't know where installation of these parsers is actually enforced.

Parser runtime file paths look ok to me:
```
:echo nvim_get_runtime_file('*/help.so', v:true)
['/home/holger/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/parser/help.so', '/usr/lib/nvim/parser/help.so']

:echo nvim_get_runtime_file('*/lua.so', v:true)
['/home/holger/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/parser/lua.so', '/usr/lib/nvim/parser/lua.so']

```

Thanks for your help! I'm giving up for today. :-)

**Comment by LostNeophyte** [comment]
Delete usr/lib/nvim/parser/help.so and /usr/share/nvim/runtime/queries/help,  parsers from 0.8 are incompatible with newer nvim-treesitter the ones from packer should be used though, it's weird. You could also update neovim to nightly

**Comment by hjoukl** [comment]
Can confirm that deleting `/usr/lib/nvim/parser/help.so` and `/usr/lib/nvim/parser/lua.so` fix the issue at hand. 
These come from the neovim deb package (and need sudo/root privileges for removal) so this is a bit inconvenient.

As is to be expected the `nvim_get_runtime_file()` output then changes to:
```
:echo nvim_get_runtime_file('*/lua.so', v:true)
['/home/holger/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/parser/lua.so']
```
Why removal of the neovim system package files is necessary remains unclear to me. I suspect that s.th. going wrong with parser `.so` files search paths(?).

**Comment by LostNeophyte** [comment]
> Why removal of the neovim system package files is necessary remains unclear to me. I suspect that s.th. going wrong with parser .so files search paths(?).

there was a breaking change in treesitter and parsers bundled with older neovim versions are incompatible, there's no system in place to check for compatibility so it runs them and errors appear

it's fixed is a newer version of nvim-treesitter

**Comment by hjoukl** [comment]
Aha, just found this in the nvim-treesitter README.md: https://github.com/nvim-treesitter/nvim-treesitter#i-get-query-error-invalid-node-type-at-position

So this is exactly what's happening here:
```
:echo nvim_get_runtime_file('parser', v:true)
['/home/holger/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/parser', '/usr/lib/nvim/parser']
```

The recommendation is "If you get more than one path, remove the ones that are outside this plugin (nvim-treesitter directory), so the correct version of the parser is used.". 

Maybe there's a better way than deleting files from the neovim deb package? Gotta find out how to control the parser runtime directory...

(Note that it is possible to cure AstroNvim's similar treesitter problems by an explicit `TSInstall c help lua vim`, without removing the `/usr/share/nvim/parser/*.so` files. AstroNvim seems to not automatically install any treesitter language parsers out-of-the box. While the same approach did not work for me with LunarVim there must obviously be some way to keep the (outdated) deb package parser files but make nvim-treesitter use the new, freshly installed ones. AstroNvim does not separate its installation in separate directories like LunarVim does, it simply lives in the main nvim dirs.)

Again, thanks for your help - valuable insights! Great work on LunarVim.

**Comment by LostNeophyte** [comment]
`TSInstall c help lua vim` would work in lunarvim master, but it won't in 1.2 (it has an older version of nvim-treesitter)

**Comment by hjoukl** [comment]
I'll leave it at that so here's just for the record, some learnings for me.

- From the neovim builtin help via `:help treesitter`:

  "[...] Parsers are the heart of tree-sitter. They are libraries that tree-sitter will search for in the `parser` runtime directory.
  By default, Nvim bundles only parsers for C, Lua, and Vimscript, but parsers can be installed manually or
  via a plugin like https://github.com/nvim-treesitter/nvim-treesitter.
  Parsers are searched for as `parser/{lang}.*` in any 'runtimepath' directory.
  If multiple parsers for the same language are found, the first one is used.
  (This typically implies the priority "user config > plugins > bundled. [...]"

-  To me, the distinction between treesitter (nvim builtin) and nvim-treesitter (plugin) wasn't really clear, understood now.
-  I haven't found a way to show the nvim-treesitter plugin version in neovim but the commits recorded in the AstroNvim and LunarVim  packer snapshot files differ, for the versions I've tried (AstroNvim 2.11.6, LunarVim release-1.2/neovim-0.8-8f4a7bd) . I take it these are lockfiles for plugin installation so there's a version difference for nvim-treesitter.

**Comment by hjoukl** [comment]
Ok, I said I'll leave it but I just found out how to upgrade nvim-treesitter plugin (all plugins are pinned to specific commits in the LunarVim release, to keep a stable working ground):
```
# Start lvim in dev mode (this "unpins" plugin versions i.e. allows PackerUpdate to fetch newer versions)
$ LVIM_DEV_MODE=1 lvim

# Update nvim-treesitter plugin
:PackerUpdate nvim-treesitter

# Reinstall parsers  (just a selection; to make :checkhealth show no more errors you should
# probably reinstall all of LunarVims predefined parser, e.g. also typescript, tsx, ...)                                                                                          
:TSInstall c help lua vim 

# quit lvim & restart without dev mode ==> :help works without errors
```

For the curious see https://github.com/LunarVim/LunarVim/blob/796ee8e14c38bbedcf79dce40f5a52117d96f74a/lua/lvim/plugins.lua#L305 for `LVIM_DEV_MODE`.

Of course, this is also propery documented here: https://www.lunarvim.org/docs/plugins#pinning-strategy - I just didn't see it. :-)

**Comment by SunHuawei** [comment]
`:TSUninstall all` works for me

**Comment by aungthihaaung** [comment]
If ":TSUninstall sql" is not working, delete the sql.so file from the following path.
C:\Users\<<user_name>>\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\parser\sql.so
The install sql ":TSInstall sql" again.

**Comment by aungthihaaung** [comment]
If ":TSUninstall sql" is not working, delete the sql.so file from the following path.
C:\Users<<user_name>>\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\parser\sql.so
Then, install sql ":TSInstall sql" again.

**Comment by aungthihaaung** [comment]
If ":TSUninstall sql" is not working, delete the sql.so file from the following path.
C:\Users<<user_name>>\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\parser\sql.so
Then, install sql ":TSInstall sql" again.

And, "help" is now called "vimdoc".

**Comment by youguanxinqing** [comment]
I also encountered it, but the error I received is: `treesitter/query.lua:273: Query error at 9:4. Invalid node type "heredoc_end".`  I tried `:TSInstall vim vimdoc,` and it still broke. `TSInstall help` is not supported. Finally, `:TSInstall all` worked for me."

**Additionally**, my problem is with NVChad.

**Comment by stevenhay** [comment]
> I also encountered it, but the error I received is: `treesitter/query.lua:273: Query error at 9:4. Invalid node type "heredoc_end".` I tried `:TSInstall vim vimdoc,` and it still broke. `TSInstall help` is not supported. Finally, `:TSInstall all` worked for me."
> 
> **Additionally**, my problem is with NVChad.

I also got this cryptic error but using Noice and nui with my own config, for me installing `bash` and `fish` solved it instead of installing all parsers.

**Comment by DavidePatria** [comment]
for me it was somehow related to still having rainbow active

**Comment by DinkyTrady** [comment]
@stevenhay really, i should install fish to fix the problems?😧

**Comment by Alohaoh** [comment]
> TSInstall all

Brilliant

**Comment by stevenhay** [comment]
> @stevenhay really, i should install fish to fix the problems?😧. haahhh still doesn't fix maybe `:TSInstall all` is the way

No, install the parser for the environment you're using. I was using fish so I did :TSInstall fish and :TSInstall bash as I didn't want to install every single parser.

**Comment by DinkyTrady** [comment]
> > @stevenhay really, i should install fish to fix the problems?😧. haahhh still doesn't fix maybe `:TSInstall all` is the way
> 
> No, I didn't mean install the fish environment, I meant install the parser for the environment you're using. I was using fish so I did :TSInstall fish and :TSInstall bash as I didn't want to install every single parser.

oh man, I misunderstand xD. but yeah I think installing all parsers is the only way to fix this bug

**Comment by Chethan-L701** [comment]
> > @stevenhay really, i should install fish to fix the problems?😧. haahhh still doesn't fix maybe `:TSInstall all` is the way
> 
> No, I didn't mean install the fish environment, I meant install the parser for the environment you're using. I was using fish so I did :TSInstall fish and :TSInstall bash as I didn't want to install every single parser.

Thanks dude, it solved my issuse installing the fish parser, but i still dont get how it is related.

Here what i did in the following order.
`:Lazy sync` to update tree-sitter.
`:TSUpdateSync`
`:TSInstall markdown markdown_inline vim vimdoc`
after this the issue still existed.
then installing the `fish` parser (my shell) solved the issue.

**Comment by ricardodiasc** [comment]
For those who do not want to install :TSInstall all, you can simply do :TSInstall vimdocs. This is how I got it working.

**Comment by hubertlepicki** [comment]
`:TSInstall all` worked for me

**Comment by convers39** [comment]
for nvchad users

I have tried `:TSUpdate <lang>`, `:TSInstall all`, remove or delete the parser in neovim lib([here](https://github.com/nvim-treesitter/nvim-treesitter#i-get-query-error-invalid-node-type-at-position)), nothing worked.

Finnaly I run `:NvChadUpdate` and in the pannel I run `Restore`, then the problem disappeared.

**Comment by zhengduoru** [comment]
I found the same problem. And I figured it out by this way:
firstly, I install lunarvim with command: LV_BRANCH='master' INSTALL_PREFIX='/usr' XDG_DATA_HOME='/usr/share' ./lunarvim-install.sh  --no-install-dependencies.
so it was installed in /usr/share  path.

then, I install lunarvim with command: LV_BRANCH='master' ./lunarvim-install.sh  --no-install-dependencies.
it was installed in /usr/.local/share. and I found the error is gone. and I found the key folder is /root/.local/share/lvim, without which the error is reproducable
