### ISSUE TITLE
shift-h and shift-l to switch buffers stop working after reinstall lunarVim

### ISSUE THREAD

**Issue by gleydson404** [LunarVim/LunarVim#3690]
### Problem description

I cant switch between buffers using shift-h and shift-l. Instead of switch tabs, the cursor is jumping some lines up (shift-h) and down(shift-l)

1 - Open two different buffers from nvim-tree
2 - Try to navigate between then using shift-h and shift-l

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Operating system/version

archlinux under wsl2

### Steps to reproduce

1 - Open two different buffers from nvim-tree
2 - Try to navigate between then using shift-h and shift-l

**Comment by LostNeophyte** [comment]
there keybinds have been removed, use this https://github.com/LunarVim/LunarVim/blob/796ee8e14c38bbedcf79dce40f5a52117d96f74a/utils/installer/config.example.lua#L26-L27

**Comment by gleydson404** [comment]
Thanks @LostNeophyte solved!
