### ISSUE TITLE
How to reload plugin ?

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3698]
### Problem description

I am writing my own plugin. After make some changes. I have to restart the whole lunarvim can make the 
change take effect. I try to run command `LvimReload` but not work. 

How to make it?

### LunarVim version

master-e45afe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0-dev-914-gd4d27c41b

### Operating system/version

OS: Ubuntu 22.04 jammy

**Comment by LostNeophyte** [comment]
you can unload lua modules with `package.loaded["module"] = nil` , but reloading plugins isn't really possible in (neo)vim
