### ISSUE TITLE
Move line(s) up and down key binding not working

### ISSUE THREAD

**Issue by Nunatic02** [LunarVim/LunarVim#3702]
### Problem description

keybindings to move line(s) up and down described in https://www.lunarvim.org/docs/keybind-overview are not working.
Tested both on iTerm2 and kitty on MacOS 13.0.

---

Keybindings described under Editing section.

`<M-k>` | move line(s) up | normal, visual
`<M-j>` | move line(s) down | normal, visual

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.2

### Operating system/version

macOS 13.0

### Steps to reproduce

1. Use lvim to open any file
2. Press `<M-k>` or `<M-j>`

Expected: line under cursor move up or down.

Reality: line not moved.

### Screenshots

https://user-images.githubusercontent.com/58194485/211427322-edb3eb7f-f18c-4369-a40d-c3db5337a217.mp4

**Comment by LostNeophyte** [comment]
In your terminal settings set it to use option as meta

**Comment by rscircus** [comment]
Please have a look at the docs as you might need to modify your terminal settings:

- https://www.lunarvim.org/docs/beginners-guide/keybinds-overview#editing
  - e.g. alacritty: https://github.com/alacritty/alacritty/issues/62
