### ISSUE TITLE
Firenvim installation does not work for LunarVim in Ubuntu

### ISSUE THREAD

**Issue by albertas** [LunarVim/LunarVim#3704]
### Problem description

I tried installing Firenvim in LunarVim using:
```
lvim.plugins = {
    { "glacambre/firenvim",
        run = function() vim.fn['firenvim#install'](0) end
    }
}
```
Firenvim was installed, but it looks that incorrectly, because I get an error `"Your plugin manager did not load the Firenvim plugin for neovim."` error when troublshooting. Raised the issue for Firenvim, but they tell that LunvarVim is not supported, see: https://github.com/glacambre/firenvim/issues/1488

### LunarVim version

master-375232c

### Neovim version (>= 0.8.0)

v0.8.0-1210-gd367ed9b2

### Operating system/version

Ubuntu 20.04

### Steps to reproduce

1. Add this to `lvim.plugins` map:
```     
   { "glacambre/firenvim",
        run = function() vim.fn['firenvim#install'](0) end
    },
```
2. Install Firenvim plugin for Firefox: https://addons.mozilla.org/en-US/firefox/addon/firenvim/
3. Enter any Textarea in browser and Firenvim does not start (just a blink appears, instead of vim window appearing).

**Comment by glacambre** [comment]
Somebody also opened a discussion about this: https://github.com/LunarVim/LunarVim/discussions/3689

To the lunarvim maintainers: I can answer direct questions if needed, but I won't investigate the problem myself.

**Comment by LostNeophyte** [comment]
> There also are discussions about this: https://github.com/LunarVim/LunarVim/discussions/3689 , https://github.com/LunarVim/LunarVim/discussions/2689 . It also looks like somebody managed to get firenvim to work with lunarvim in the past: https://github.com/LunarVim/LunarVim/discussions/3178 .

wow, I really should look at discussions more

> To the lunarvim maintainers: I can answer direct questions if needed, but I won't investigate the problem myself.

I believe [this](https://github.com/glacambre/firenvim/blob/b6be2e074b8f62815a45e31eb0966b4dd5e57810/autoload/firenvim.vim#L640) will mean that firenvim will start `nvim`, while lunarvim is started using an `lvim` script, so `firenvim#run` will be an unknown function, since the plugin was only added in lvim and not nvim

If the above is true then I think the easiest way to fix it would be a config option in firenvim that would allow overriding the binary that firenvim uses so it would be used instead of `get_progpath`

If that solution isn't something you'd add I can think of a different way

**Comment by albertas** [comment]
> I believe [this](https://github.com/glacambre/firenvim/blob/b6be2e074b8f62815a45e31eb0966b4dd5e57810/autoload/firenvim.vim#L640) will mean that firenvim will start nvim, while lunarvim is started using an lvim script

I would love if LunarVim had an option to override `nvim` instead of adding additional `lvim` script. I would definitely use it.

**Comment by LostNeophyte** [comment]
> > I believe [this](https://github.com/glacambre/firenvim/blob/b6be2e074b8f62815a45e31eb0966b4dd5e57810/autoload/firenvim.vim#L640) will mean that firenvim will start nvim, while lunarvim is started using an lvim script
> 
> I would love if LunarVim had an option to override `nvim` instead of adding additional `lvim` script. I would definitely use it.

that's possible, just clone the lunarvim repo to .config/lvim and put your user config in the same place it was before

**Comment by albertas** [comment]
I will try using bash `alias nvim='lvim'` later today to see if it solves the issue.

**Comment by glacambre** [comment]
@albertas
>I will try using bash alias nvim='lvim' later today to see if it solves the issue.

This will not solve your issue. Replacing `/path/to/nvim` with `/path/to/lvim` in `~/.local/share/firenvim/firenvim` should help you make progress though.

@LostNeophyte
>while lunarvim is started using an lvim script, so firenvim#run will be an unknown function, since the plugin was only added in lvim and not nvim

What does this `lvim` script do on top of starting neovim? Is there a way to figure out an absolute path to that script from neovim?

**Comment by LostNeophyte** [comment]
> What does this `lvim` script do on top of starting neovim? 

it sets env variables and runs `nvim -u`

```bash
#!/usr/bin/env bash

export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"/home/adam/.local/share/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"/home/adam/.config/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"/home/adam/.cache/lvim"}"

export LUNARVIM_BASE_DIR="${LUNARVIM_BASE_DIR:-"/home/adam/.local/share/lunarvim/lvim"}"

exec -a lvim nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
```

> Is there a way to figure out an absolute path to that script from neovim?

no, but I saw that the firenvim script has the PATH variable copied over, so just `lvim` should work

if you want to make it automatic, i'd check if `$LUNARVIM_RUNTIME_DIR` is set to detect lunarvim, `lvim` table exists in installations to .config/nvim, in these installations the lvim script does not exist and is not needed

**Comment by glacambre** [comment]
>I saw that the firenvim script has the PATH variable copied over, so just lvim should work

That's a fallback to work around some binaries not being found due to $PATH not being the same when running neovim from the terminal and when running neovim from a browser that was started through a graphical interface. I'd prefer to avoid relying on it (otherwise there's a risk that an ancient `nvim` living in /usr/bin could be selected instead of the `nvim` that was used to run `firenvim#install`).

I think implementing [NVIM_APPNAME](https://github.com/neovim/neovim/issues/21691) in neovim, having the lunarvim script set it to `lvim` and having the firenvim script capture and re-export it might be an optimal solution though.

I'll try to open a PR for NVIM_APPNAME in neovim.

**Comment by glacambre** [comment]
@LostNeophyte support for [$NVIM_APPNAME](https://neovim.io/doc/user/starting.html#$NVIM_APPNAME) has been [merged in Neovim](https://github.com/neovim/neovim/pull/22128) and [in Firenvim](https://github.com/glacambre/firenvim/pull/1500).

**Comment by LostNeophyte** [comment]
> @LostNeophyte support for [$NVIM_APPNAME](https://neovim.io/doc/user/starting.html#$NVIM_APPNAME) has been [merged in Neovim](https://github.com/neovim/neovim/pull/22128) and [in Firenvim](https://github.com/glacambre/firenvim/pull/1500).

Thank you, it will be quite useful

- https://github.com/LunarVim/LunarVim/pull/3856

**Comment by kobzar** [comment]
@albertas wich situation at this moment?

**Comment by albertas** [comment]
> @albertas wich situation at this moment?

Its still under active implementation, see https://github.com/LunarVim/LunarVim/pull/3896

**Comment by rafaelliu** [comment]
Following the discussion, it seems @glacambre added the [support needed](https://github.com/LunarVim/LunarVim/issues/3704#issuecomment-1434194330) to firenvim, and @kylo252 merged [changes needed to lunarvim](https://github.com/LunarVim/LunarVim/pull/3896). Could someone point me to how to set this up?

I tried setting up `NVIM_APPNAME` in a few places, changing the firenvim's exec command, can't make it work. When I select the textarea it flashes and nothing happens. Reverting back to nvim works

**Comment by glacambre** [comment]
@rafaelliu In theory, the only things you need to do are:
- Add the `firenvim` plugin to your lunarvim config
- In a shell, run `unset NVIM_APPNAME ; lvim`
- Then, run `:call firenvim#install()`
Firenvim should then be installed and working in your browser, assuming you've installed the firenvim browser add-on.

Is this what you tried? If yes, could you paste the content of `~/.local/share/firenvim/firenvim` here?

**Comment by rafaelliu** [comment]
Below is my firenvim file[1].

I tested some more, and setting the NVIM_APPNAME directly into firenvim script works with LazyVim distro. Also using `NVIM_APPNAME=lvim nvim` does not work like it does for LazyVim.

The problem seems lvim entry point is not in `.config/lvim` as nvim expects. Looking carefully at the script @LostNeophyte shared[2], lvim is started using that custom script from another directory, and as it comes up, it requires a `config.lua` in the `.config/lvim` directory. I'm not sure the LunarVim merge adding support NVIM_APPNAME does what it intends to.

If what I said makes sense, I guess the NVIM_APPNAME support needs to be revisited. As in: lvim should be able to start with `NVIM_APPNAME=lvim nvim`, and likely the lvim script itself should use that instead of `nvim -u`

```bash
#!/bin/sh
mkdir -p /var/folders/m9/sdyvq8bs1pxgmjjbnsb929wrj75qvf/T//firenvim
chmod 700 /var/folders/m9/sdyvq8bs1pxgmjjbnsb929wrj75qvf/T//firenvim
cd /var/folders/m9/sdyvq8bs1pxgmjjbnsb929wrj75qvf/T//firenvim
export PATH="$PATH:/Users/rafael/.wasmtime/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/coreutils/libexec/gnubin:/Users/rafas/.local/bin:/usr/local/opt/coreutils/libexec/gnubin:/Users/rafael/bin:/Users/rafael/.cache/zsh4humans/v5/zsh4humans/zb:/Users/rafael/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/rafael/.cache/zsh4humans/v5/fzf/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/rafael/.cargo/bin"
unset NVIM_LISTEN_ADDRESS
if [ -n "$VIM" ] && [ ! -d "$VIM" ]; then
  unset VIM
fi
if [ -n "$VIMRUNTIME" ] && [ ! -d "$VIMRUNTIME" ]; then
  unset VIMRUNTIME
fi
if [ ! -n "$NVIM_APPNAME" ]; then
  NVIM_APPNAME='lvim'
  export NVIM_APPNAME
fi

exec '/opt/homebrew/Cellar/neovim/0.9.5/bin/nvim' --headless --cmd "let g:firenvim_config={'globalSettings':{},'localSettings':{'.*':{}}}|let g:firenvim_i=[]|let g:firenvim_o=[]|let g:Firenvim_oi={i,d,e->add(g:firenvim_i,d)}|let g:Firenvim_oo={t->[chansend(2,t)]+add(g:firenvim_o,t)}|let g:firenvim_c=stdioopen({'on_stdin':{i,d,e->g:Firenvim_oi(i,d,e)},'on_print':{t->g:Firenvim_oo(t)}})" --cmd 'let g:started_by_firenvim = v:true' -c 'try|call firenvim#run()|catch /Unknown function/|call chansend(g:firenvim_c,["f\n\n\n"..json_encode({"messages":["Your plugin manager did not load the Firenvim plugin for neovim."],"version":"0.0.0"})])|call chansend(2,["Firenvim not in runtime path. &rtp="..&rtp])|qall!|catch|call chansend(g:firenvim_c,["l\n\n\n"..json_encode({"messages": ["Something went wrong when running firenvim. See troubleshooting guide."],"version":"0.0.0"})])|call chansend(2,[v:exception])|qall!|endtry'
```


[2] From https://github.com/LunarVim/LunarVim/issues/3704#issuecomment-1376911733

``` bash
[...]
export LUNARVIM_BASE_DIR="${LUNARVIM_BASE_DIR:-"/home/adam/.local/share/lunarvim/lvim"}"

exec -a lvim nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
```

**Comment by rafaelliu** [comment]
Curious, @LostNeophyte, any chance LunarVim migrates to the NVIM_APPNAME standard? Should I open a new issue for that?
