### ISSUE TITLE
During fresh install, cause of the vim.diagnostic error (for me)

### ISSUE THREAD

**Issue by jasonsydes** [LunarVim/LunarVim#3705]
### Problem description

Hi all, I was getting the dreaded vim.diagnostic error (see #2811 and #2590, and my pasted errors below), but I was getting them despite performing fresh installs of both Neovim and LunarVim. I believe I found the cause of the error (for me at least), and in retrospect the solution seems obvious, but since it didn't seem obvious to me at the time, I'm leaving this here in case it helps others.

In short, I believe the error (for me at least) was caused because I had moved the nvim executable to ~/.local/bin and had pointed my $PATH to ~/.local/bin. When I did this either for a) the stable nightly neovim build (v0.8.2) or b) when I had built from source (make CMAKE_BUILD_TYPE=RelWithDebInfo) (no make install at this point), I received errors that looked like the ones below (for MacOS and Ubuntu).

The above being the cause of the error I was seeing wasn't obvious to me, because moving the executable to ~/.local/bin and invoking it from there seems to start up Neovim just fine (I've been lightly using Neovim in that fashion for the last month or so in the hopes of switching from Vim to Neovim permanently). Yes, I technically didn't follow the directions (e.g., [this](https://github.com/neovim/neovim/releases/tag/v0.8.2) says to invoke nvim directly from the untarball-ed dir), but again I hadn't encountered any errors using nvim until I tried to bootstrap Neovim/LunarVim this week.

It does seem like it's trying to use the "system" nvim during bootstrap (because "/usr/local/share/..." and "/share/..." are system folder, not user folders:
On Ubuntu I get:
```E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim```
On MacOS I get:
```E484: Can't open file /share/nvim/syntax/syntax.vimError detected while processing command line:```

The solution for me was to either:
1. When using the [binary NeoVim release](https://github.com/neovim/neovim/releases/) to point PATH at where I had untar'ed the release, i.e., like so: ```export PATH=$PATH:$HOME/path/to/un-tarballed-neovim/bin```, or: 
2. When building from source, build with ```make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=~/opt```, followed by the install with ```make install```, and the point PATH there with ```export PATH=~/opt/bin:$PATH```

Again, sorry if this is obvious to everyone else, but it wasn't obvious to me, so putting this here in case it helps someone else. 

Feel free to close this ticket. Looking forward to playing with LunarVim!

The error on MacOS:
```...
Preparing Packer setup
Error detected while processing /Users/sydes/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: vim/_init_packages.lua:0: module 'vim.diagnostic' not found:
	no field package.preload['vim.diagnostic']
	no file './vim/diagnostic.lua'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/diagnostic.lua'
	no file '/usr/local/share/lua/5.1/vim/diagnostic.lua'
	no file '/usr/local/share/lua/5.1/vim/diagnostic/init.lua'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/diagnostic.lua'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/diagnostic/init.lua'
	no file './vim/diagnostic.so'
	no file '/usr/local/lib/lua/5.1/vim/diagnostic.so'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim/diagnostic.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './vim.so'
	no file '/usr/local/lib/lua/5.1/vim.so'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	vim/_init_packages.lua: in function '__index'
	...s/.local/share/lunarvim/lvim/lua/lvim/core/which-key.lua:183: in function 'config'
	...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:30: in function 'config'
	...ydes/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:21: in function 'init'
	.../sydes/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:102: in function 'init'
	/Users/sydes/.local/share/lunarvim/lvim/init.lua:11: in main chunk
E484: Can't open file /share/nvim/syntax/syntax.vimError detected while processing command line:
E492: Not an editor command: PackerSync
```
The error on Ubuntu:
```...
Error detected while processing /home/sydes/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: vim/_init_packages.lua:0: module 'vim.diagnostic' not found:
        no field package.preload['vim.diagnostic']
        no file './vim/diagnostic.lua'
        no file '/home/sydes/src/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/diagnostic.lua'
        no file '/usr/local/share/lua/5.1/vim/diagnostic.lua'
        no file '/usr/local/share/lua/5.1/vim/diagnostic/init.lua'
        no file '/home/sydes/src/neovim/.deps/usr/share/lua/5.1/vim/diagnostic.lua'
        no file '/home/sydes/src/neovim/.deps/usr/share/lua/5.1/vim/diagnostic/init.lua'
        no file './vim/diagnostic.so'
        no file '/usr/local/lib/lua/5.1/vim/diagnostic.so'
        no file '/home/sydes/src/neovim/.deps/usr/lib/lua/5.1/vim/diagnostic.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './vim.so'
        no file '/usr/local/lib/lua/5.1/vim.so'
        no file '/home/sydes/src/neovim/.deps/usr/lib/lua/5.1/vim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        vim/_init_packages.lua: in function '__index'
        ...s/.local/share/lunarvim/lvim/lua/lvim/core/which-key.lua:183: in function 'config'
        ...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:30: in function 'config'
        ...ydes/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:21: in function 'init'
        .../sydes/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:102: in function 'init'
        /home/sydes/.local/share/lunarvim/lvim/init.lua:11: in main chunk
E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim
Error detected while processing command line:
E492: Not an editor command: PackerSync
```

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by runner@Mac-1672330205276.local  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/share/nvim"  Run :checkhealth for more info

### Operating system/version

macOS 12.6

### Steps to reproduce

See problem description above.
Feel free to close this issue.

**Comment by LostNeophyte** [comment]
neovim needs runtime files to function correctly so you can't move the executable independently, you also need to move the runtime files (so just move the whole uncompressed folder) so that nvim can find them using the original relative path

**Comment by prestonvanloon** [comment]
I have this exact issue. I have tried uninstalling and reinstalling lunarvim and neovim without success. How Is this issue resolved?

```
Error detected while processing /home/preston/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: vim/_init_packages.lua:64: module 'vim.diagnostic' not found:
        no field package.preload['vim.diagnostic']
        no file './vim/diagnostic.lua'
        no file '/usr/share/luajit-2.1/vim/diagnostic.lua'
        no file '/usr/local/share/lua/5.1/vim/diagnostic.lua'
        no file '/usr/local/share/lua/5.1/vim/diagnostic/init.lua'
        no file '/usr/share/lua/5.1/vim/diagnostic.lua'
        no file '/usr/share/lua/5.1/vim/diagnostic/init.lua'
        no file './vim/diagnostic.so'
        no file '/usr/local/lib/lua/5.1/vim/diagnostic.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/vim/diagnostic.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './vim.so'
        no file '/usr/local/lib/lua/5.1/vim.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/vim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        vim/_init_packages.lua:64: in function '__index'
        ...on/.local/share/lunarvim/lvim/lua/lvim/core/nvimtree.lua:149: in function 'config'
        ...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:30: in function 'config'
        ...ston/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:21: in function 'init'
        ...reston/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:102: in function 'init'
        /home/preston/.local/share/lunarvim/lvim/init.lua:11: in main chunk
E484: Can't open file /usr/share/nvim/syntax/syntax.vim
```

**Comment by prestonvanloon** [comment]
Update: [This was my problem](https://stackoverflow.com/a/77845990)

Resolved with restoring the neovim runtime files.

```
git clone https://github.com/neovim/neovim.git
cd neovim
git checkout v0.9.5
sudo cp -r runtime /usr/share/nvim/
```
