### ISSUE TITLE
fatal error when installing vim-fish with lazy

### ISSUE THREAD

**Issue by UgurcanAkkok** [LunarVim/LunarVim#3706]
### Problem description

Can not install vim-fish as additional plugin. See error for for steps.

### LunarVim version

master-ccb80e4

### Neovim version (>= 0.8.0)

neovim-0.9.0~ubuntu1+git202301100019-364b131f4-333b5866f

### Operating system/version

ubuntu focal

### Steps to reproduce

In lvim config.lua, as additional plugins, add vim-fish
```
lvim.plugins = {
  {
    "antoniomayk/vim-fish"
  },
}
```
As you save the config, lazy tries to install the plugin and gets the error:
```
Cloning into '/home/<USERNAME>/.local/share/lunarvim/site/pack/lazy/opt/vim-fish'...   
fatal: could not read Username for 'https://github.com': terminal prompts disabled 
```

**Comment by LostNeophyte** [comment]
Is this repo public? https://github.com/antoniomayk/vim-fish returns 404

**Comment by UgurcanAkkok** [comment]
Hmm i used to use that repo, i don't know why it returns 404 now. I guess i will use some other fish plugin.

**Comment by LostNeophyte** [comment]
I also get an error with packer 
![image](https://user-images.githubusercontent.com/110467150/211748032-da90a4a1-b9c8-45dd-8fe4-c7122f6ff6fa.png)

**Comment by kylo252** [comment]
what's the output of `git --version`?

**Comment by folke** [comment]
The repo just doesn't exist, so that can't work ;)

In case this is a private repo, then use the git url instead and make sure Github has your public ssh key.

**Comment by UgurcanAkkok** [comment]
> what's the output of `git --version`?

git version 2.25.1

I am guessing the author of the package just deleted the repositories, because it used to work and when you search "antoniomayk/vim-fish" on duckduckgo, there are results showing up with 404 pages.

 So this doesn't appear to be a bug. As far as i am concerned, you can close the issue.
