### ISSUE TITLE
Unable to move lines in MacOS

### ISSUE THREAD

**Issue by ksajan** [LunarVim/LunarVim#3709]
### Problem description

After installing lunarvim on macos tried moving lines using option + j/k but it didn't work. On the other hand, it perfectly works on my other machine with linux as os. tried remapping as well but it didn't work. 
```
lvim.keys.normal_mode["<M-j>"] = ":m .+1<CR>==" -- move line down
lvim.keys.normal_mode["<M-k>"] = ":m .-2<CR>==" -- move line up
lvim.keys.insert_mode["<M-j>"] = "<Esc>:m .+1<CR>==gi" -- move line down
lvim.keys.insert_mode["<M-k>"] = "<Esc>:m .-2<CR>==gi" -- move line up
```
Can you please point me in the right direction to use this feature. 

### LunarVim version

master

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-659+g3d49d39cd-dirty

### Operating system/version

macOS 13.1

### Steps to reproduce

installed lunar vim and started using it on macos. 

### Screenshots

<img width="223" alt="Screenshot 2023-01-12 at 2 57 18 AM" src="https://user-images.githubusercontent.com/31013555/211921935-123c0bdf-ca52-4564-bff3-9d3c15329d20.png">
when I type the mentioned command it type like this on my editor.

**Comment by yesmeck** [comment]
See #3702 #3602

**Comment by ksajan** [comment]
Thank you @yesmeck ! Couldn't find this while searching for issues here. Sorry for bugging you!
