### ISSUE TITLE
Since the `lazy.nvim` version, some user config seems not working

### ISSUE THREAD

**Issue by 2nthony** [LunarVim/LunarVim#3712]
### Problem description

plugins are active, and my plugin configs in `.config/lvim/plugin/*.lua`

### bufferline

![image](https://user-images.githubusercontent.com/19513289/212078441-0ce03bf3-0a30-4198-81b8-5637fe76523d.png)

message from `print(vim.inspect(lvim.builtin.bufferline))`

![image](https://user-images.githubusercontent.com/19513289/212081292-69d386d3-9886-4150-9997-6909029cb00b.png)

### nvim-tree

> key mappings is the most important to me

![image](https://user-images.githubusercontent.com/19513289/212078685-7d2eba5a-9c10-4b5e-96e8-a4483f2935c8.png)

### LunarVim version

master-f4ec3fc

### Neovim version (>= 0.8.0)

NVIM v0.8.2

### Operating system/version

macOS 13.1

**Comment by 2nthony** [comment]
## update

if i move these TWO configs to `.config/lvim/config.lua` will work.

**Comment by LostNeophyte** [comment]
you should require these files in your config, if you put them in /plugin then they won't be loaded at the right time

**Comment by 2nthony** [comment]
I am reading the lazy.nvim docs for detail, it works in packer before, thanks anyway

**Comment by LostNeophyte** [comment]
with lazy files in plugin/ will be loaded too late
