### ISSUE TITLE
Bug: Octo comment throws error on breadcrumbs file

### ISSUE THREAD

**Issue by RizaHKhan** [LunarVim/LunarVim#3713]
### Problem description

Install and configure Octo and proceed to creating a comment via review:

1. `:Octo review start`
2. Find a hunk and add a comment: `:Octo comment add`
3. It will throw the following error:
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/51720003/212111470-bc1e0dcb-1273-4d95-b36d-414bd25015d7.png">

The reason it seems is that the `extension` of the file comes back in this format:

<img width="189" alt="image" src="https://user-images.githubusercontent.com/51720003/212111628-ca6dba9f-5134-4c14-8367-ecc19da9ffb7.png">

`php:507` where is should just be `php`. 

### LunarVim version

8f4a7bde

### Neovim version (>= 0.8.0)

8.2

### Operating system/version

MacOs

**Comment by LostNeophyte** [comment]
this is fixed in master
