### ISSUE TITLE
Cant input chinese by using fcitx tool into Lvim

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3714]
### Problem description

Cant input Chinese in lvim. But pure neovim can. 

> fcitx version: 4.2.9.8
> I use rime to input Chinese.

Situation is:
When I switch to **rime** for input Chinese in lvim. I can see the tray icon of Rime. 
  But when I type first letter, I can see the rime input panel flash immediately and disappear.
Then the tray icon change back to normal(not Rime). And I cant input any Chinese char at the beginning.

I clear all the config in `config.lua` wont work. 

And if I type in pure neovim, I can type Chinese char normally.

And not always cant input Chinese, I can type Chinese in Lvim just like in pure neovim about once for one day . 
Very rarely, I use vim hundreds times a day just one time work. 

So How to solve it? 

### LunarVim version

master-5ae42b0

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

OS: Ubuntu 22.04 jammy

**Comment by LostNeophyte** [comment]
can you paste Chinese characters? or does the issue only occur when using fcitx?

**Comment by woshichuanqilz** [comment]
> can you paste Chinese characters? or does the issue only occur when using fcitx?

Paste is fine. 

![image](https://user-images.githubusercontent.com/11295355/212127001-abfdaa29-38a8-499a-bca5-bbb257621ea7.png)

**Comment by LostNeophyte** [comment]
you can try commenting out options in `~/.local/share/lunarvim/lvim/lua/lvim/config/settings.lua`

**Comment by woshichuanqilz** [comment]
> you can try commenting out options in `~/.local/share/lunarvim/lvim/lua/lvim/config/settings.lua`

After change the file if it need re-compile or something? I found that the change not take effect after restart.
