### ISSUE TITLE
Do we have a LvimSync command ? 

### ISSUE THREAD

**Issue by luong-komorebi** [LunarVim/LunarVim#3717]
### Problem description

I could not search for this command in the command pallete or the code. It was not sugggested when you type `:LvimSyn` 

However, there seem to be such a command in action, because when I mistype it yesterday, here is what it did:

1. Reset everything, every plugin seems uninstalled and reinstalled again (that's what happened on the master branch)
2. The latest code from the master branch is pulled 

I want to confirm with maintainers whether we have this command. 

### LunarVim version

master-f4ec3fc

### Neovim version (>= 0.8.0)

NVIM v0.8.2

### Operating system/version

macOS 13.1

### Steps to reproduce

Go to lunarvim and call the command `:LvimSync`

**Comment by LostNeophyte** [comment]
We don't have LvimSync, but we do have LvimSyncCorePlugins, maybe that got autocompleted though the result looks like from LvimUpdate
