### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Ralghs** [LunarVim/LunarVim#3720]
### Problem description

At first, I had some problems running the installing script on GitHub, so I downloaded the install.ps1 file. After I ran the install.ps1 file, some errors showed on my PowerShell. I don't know where the errors are coming from, so I could not debug this myself.

I've tried googling and have looked everywhere in the existing issues and could not find any answers.
Sorry if anything is unclear, I am very new to the GitHub community.

### LunarVim version

typing :LvimVersion in lvim doesn't give me any output

### Neovim version (>= 0.8.0)

0.8.2

### Operating system/version

Windows 11

### Screenshots
```
.\install.ps1


                88\                                                   88\
                88 |                                                  \__|
                88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
                88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
                88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
                88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
                88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
                \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|


Backup operation complete
--------------------------------------------------------------------------------

Checking dependencies..
--------------------------------------------------------------------------------

Would you like to check lunarvim's NodeJS dependencies? [y]es or [n]o (default: no) : y

changed 35 packages, and audited 36 packages in 2m

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Would you like to check lunarvim's Python dependencies? [y]es or [n]o (default: no) : y
Requirement already satisfied: pynvim in c:\users\peter\appdata\roaming\python\python311\site-packages (0.4.3)
Requirement already satisfied: msgpack>=0.5.0 in c:\users\peter\appdata\roaming\python\python311\site-packages (from pynvim) (1.0.4)
Requirement already satisfied: greenlet in c:\users\peter\appdata\roaming\python\python311\site-packages (from pynvim) (2.0.1)
Updating LunarVim
--------------------------------------------------------------------------------

Error detected while processing BufWinEnter Autocommands for "*":
E5108: Error executing lua ...m\site\pack\packer\start\packer.nvim/lua\packer\load.lua:179: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...m\site\pack\packer\start\packer.nvim/lua\packer\load.lua:118: Vim(lua):E5108: Error executing lua ...rvim\site\pack\packer\start\lir.nvim/lua\lir\actions.lua:1: loop or previous error loading module 'lir.history'
stack traceback:
        [C]: in function 'cmd'
        ...m\site\pack\packer\start\packer.nvim/lua\packer\load.lua:179: in function <...m\site\pack\packer\start\packer.nvim/lua\packer\load.lua:175>
        [string ":lua"]:1: in main chunk
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'lir.float'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'lir'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
Error detected while processing command line:
packer.nvim: Error running config for lir.nvim: ...eter\AppData\Roaming\lunarvim\lvim/lua\lvim\core\lir.lua:111: attempt to index local 'lir' (a number value)
packer.nvim: Error running config for telescope.nvim: ...ppData\Roaming\lunarvim\lvim/lua\lvim\core\telescope.lua:147: loop or previous error loading module 'telescope.previewers'
packer.nvim: Error running config for indent-blankline.nvim: ...Data\Roaming\lunarvim\lvim/lua\lvim\core\indentlines.lua:35: attempt to call field 'setup' (a nil value)Your LunarVim installation is now up to date!
```

**Comment by LostNeophyte** [comment]
try running the uninstaller first

**Comment by Ralghs** [comment]
I tried to uninstall then run the install script again and ran into a new error

Updating LunarVim
--------------------------------------------------------------------------------

Error detected while processing C:\Users\Peter\AppData\Roaming\lunarvim\lvim\init.lua:
E5113: Error while calling lua chunk: ...AppData\Roaming\lunarvim\lvim/lua/lvim/plugin-loader.lua:47: module 'lazy.core.cache' not found:
        no field package.preload['lazy.core.cache']
        no file '.\lazy\core\cache.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\lazy\core\cache.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\lazy\core\cache\init.lua'
        no file '.\lazy\core\cache.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\lazy\core\cache.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'
        no file '.\lazy.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\lazy.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'
stack traceback:
        [C]: in function 'require'
        ...AppData\Roaming\lunarvim\lvim/lua/lvim/plugin-loader.lua:47: in function 'init'
        ...ter\AppData\Roaming\lunarvim\lvim/lua/lvim/bootstrap.lua:97: in function 'init'
        C:\Users\Peter\AppData\Roaming\lunarvim\lvim\init.lua:11: in main chunkError detected while processing command line:
E492: Not an editor command: LvimUpdateYour LunarVim installation is now up to date!

**Comment by LostNeophyte** [comment]
try running the uninstaller and deleting the whole `AppData\Roaming\lunarvim` directory, I'm not sure if the uninstaller does it, If that won't help I'll need to boot up a windows vm
