### ISSUE TITLE
Pyright Utilizes High Cpu on Python Files Causing editor lag

### ISSUE THREAD

**Issue by sktzofrenic** [LunarVim/LunarVim#3726]
### Problem description

When editing any python file, the Pyright LSP server immediately jumps to 100% CPU usage while in insert mode and returns to normal in any other mode. 

This is causing editor lag while typing. 

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

0.8.0

### Operating system/version

Ubuntu 20

### Affected language servers

pright

### Actual behavior

High CPU while in any python file in insert mode. 

### Expected behavior

CPU shouldn't be that high and certainly editor lag is not great :) 

### support info

![image](https://user-images.githubusercontent.com/11902047/212351497-992c7133-b1cb-4e6d-8a90-a30b3655a0c0.png)

### logs

```console
lidation.js:34:60)\n    at _callee$ (/home/dans/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/lib/html-language-server/modes/cssMode.js:53:69)\n    at tryCatch (/home/dans/.
local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:64:40)\n    at Generator.invoke (/home/dans/.local/share/nvim/mason/packages/html-ls
p/node_modules/vscode-langservers-extracted/node_modules/regenerator-runtime/runtime.js:299:22)\n    at Generator.next (/home/dans/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extrac
ted/node_modules/regenerator-runtime/runtime.js:124:21)\n    at asyncGeneratorStep (/home/dans/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/lib/html-language-server/modes/c
ssMode.js:17:103)\n    at _next (/home/dans/.local/share/nvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/lib/html-language-server/modes/cssMode.js:19:194)"
[START][2023-01-12 17:19:49] LSP logging initiated
[WARN][2023-01-12 17:19:49] ...lsp/handlers.lua:113     "The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2023-01-12 17:19:50] ...lsp/handlers.lua:485    "Notification handler 'textDocument/didChange' failed with message: Cannot read properties of undefined (reading 'offsetAt')"
[ERROR][2023-01-13 07:03:25] ...lsp/handlers.lua:485    "Notification handler 'textDocument/didChange' failed with message: Cannot read properties of undefined (reading 'offsetAt')"
[ERROR][2023-01-13 07:03:28] ...lsp/handlers.lua:485    "Notification handler 'textDocument/didChange' failed with message: Cannot read properties of undefined (reading 'offsetAt')"
[ERROR][2023-01-13 07:03:28] ...lsp/handlers.lua:485    "Notification handler 'textDocument/didChange' failed with message: Cannot read properties of undefined (reading 'offsetAt')"
[ERROR][2023-01-13 07:03:30] ...lsp/handlers.lua:485    "Notification handler 'textDocument/didChange' failed with message: Cannot read properties of undefined (reading 'offsetAt')"
[ERROR][2023-01-13 07:03:31] ...lsp/handlers.lua:485    "Notification handler 'textDocument/didChange' failed with message: Cannot read properties of undefined (reading 'offsetAt')"
[WARN][2023-01-13 07:04:24] ...lsp/handlers.lua:113     "The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-01-13 07:04:24] ...lsp/handlers.lua:487     "stubPath /home/dans/Documents/danwinsrx/typings is not a valid directory."
[WARN][2023-01-13 07:04:25] ...lsp/handlers.lua:487     "stubPath /home/dans/Documents/danwinsrx/typings is not a valid directory."
[WARN][2023-01-13 09:29:09] ...lsp/handlers.lua:113     "The language server volar triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2023-01-13 09:57:21] .../vim/lsp/rpc.lua:733    "rpc"   "node"  "stderr"        "(node:1470828) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added to [Even
tEmitter]. Use emitter.setMaxListeners() to increase limit\n(Use `node --trace-warnings ...` to show where the warning was created)\n"
```

**Comment by sktzofrenic** [comment]
Does anyone know how to switch language servers so I can see if this occurs with other servers?

![image](https://user-images.githubusercontent.com/11902047/212351737-7b1623f1-1c77-44b0-8542-b80625cc5d33.png)

**Comment by LostNeophyte** [comment]
see if this happens if you `:LspStop <tab>` pyright, does neovim or pyright use most of the cpu?

**Comment by sktzofrenic** [comment]
Thanks @LostNeophyte. If I turn pyright off, the CPU problem goes away. 

I'd like to 

a) Adjust pyright settings to eliminate the CPU usage issue
or
b) Switch to another LSP server. 

The repository is quite large, has 100's of files and probably about 70k lines of python. I'm wondering if that is the culprit or maybe the pyright settings should be adjusted to handle larger repositories. 

I also don't know how to tell Lunarvim to switch to another LSP server.

**Comment by LostNeophyte** [comment]
> a) Adjust pyright settings to eliminate the CPU usage issue

You can do that with `:LspSettings pyright`

>  b) Switch to another LSP server.

https://www.lunarvim.org/docs/languages#server-override

**Comment by sktzofrenic** [comment]
To follow up and resolve this issue, pyright was including my entire home directory which was causing the lag. 

The settings that resolved it for me were to put the specific folders I wanted in the pyright config and the issue resolved. 

![image](https://user-images.githubusercontent.com/11902047/212474140-cc894bcc-f670-4abe-a000-736f0e57370b.png)


There is probably a more nuanced way to do this too, but it worked for me. 

Thank you to @LostNeophyte for pointing me in the right direction.
