### ISSUE TITLE
[ERROR]: LunarVim requires at least Neovim v0.8 or higher

### ISSUE THREAD

**Issue by rsrajput** [LunarVim/LunarVim#3729]
My nvim version is 0.8.1 on MacBook air. However when I am trying to install lvim stable branch, following error appears:
`[ERROR]: LunarVim requires at least Neovim v0.8 or higher`
The output of nvim -v is:
```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```
Therefore I am not able to install lunarvim on nvim 0.8.1 (stable)

**Comment by im6chen** [comment]
I had the same problem.
I installed Neovim 0.8.2 by Homebrew on Macbook Pro intel.
```
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
编译者 brew@Ventura

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/0.8.2/share/nvim"

Run :checkhealth for more info
```

**Comment by LostNeophyte** [comment]
Make sure you don't have an older binary somewhere, for example ~/.local/bin

**Comment by im6chen** [comment]
> Make sure you don't have an older binary somewhere, for example ~/.local/bin

Thanks Bro~

**Comment by lu-maca** [comment]
Same problem here, on Ubuntu 20.04. Any solution?

**Comment by LostNeophyte** [comment]
check if all these print 1, if something prints 0 you need to fix it
1. `nvim --headless +'echo has("nvim-0.8")' +q`
2. `bash -c "nvim --headless +'echo has(\"nvim-0.8\")' +q"`
3. `~/.local/bin/nvim --headless +'echo has("nvim-0.8")' +q` this one can also be `no such file or directory`

**Comment by rsrajput** [comment]
> Make sure you don't have an older binary somewhere, for example ~/.local/bin

Thank you so much! This solves the problem.

**Comment by the404dev** [comment]
I solved the problem by installing Neovim through Homebrew on Pop!_Os 22.04 LTS
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilado por team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM/sysinit.vim"
            padrão para $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
