### ISSUE TITLE
How to use lvim in self-write plugins

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3735]
### Problem description

I have some settings in my-own plugin which need to change the value of 
telescope like this:
```lua
lvim.builtin.telescope.defaults.mappings.i['#'] = actions.close
lvim.builtin.telescope.defaults.mappings.i[' '] = actions.close
```

But seems I cant use `lvim` directly in my plug. I check the code of lvim. 
I found that the lvim is defined in `lvim/config/init.lua`. 

I try to use lvim like this
```lua
package.path = '/home/lizhe/.local/share/lunarvim/lvim/lua/lvim/config/init.lua;' .. package.path
lvim = require("config")
```

But I get a lot of error.  So How to make it. 

### LunarVim version

master-e45afe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0-dev-914-gd4d27c41b

### Operating system/version

OS: Ubuntu 22.04 jammy

**Comment by LostNeophyte** [comment]
Here's a plugin that does it https://github.com/LunarVim/lvim-themes
