### ISSUE TITLE
Can't disable quickfix popup.

### ISSUE THREAD

**Issue by JxJxxJxJ** [LunarVim/LunarVim#3736]
### Problem description

I use `lunarvim` to edit LaTeX files, there are many times where LaTeX compilation gives warnings that are ok to ignore, but the quickfix buffer gets opened and focused in the center of the frame every time I compile, interrupting the editing. 

I'm trying to disable the "open and focus" behavior and be able if I want to just `:copen` and see the warnings.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.2

### Operating system/version

GNU / Linux - Arch

### Steps to reproduce

--

### Screenshots

--

**Comment by LostNeophyte** [comment]
the quickfix windows does not open by itself, maybe you have a plugin that does it

**Comment by JxJxxJxJ** [comment]
Thanks. I'm using vimtex. I failed trying to disable it from their side so was thinking it could be done from lunarvim side. Will keep trying then, thanks.
