### ISSUE TITLE
Spell checking doesn't work for languages other than default en

### ISSUE THREAD

**Issue by cyga** [LunarVim/LunarVim#3742]
### Problem description

1. Write minimal file test-spell-check-ru.txt:
```
фыва слово в предложении
```
2. Open it using lvim.
3. Set spell checking:
```
set spell
```
It underlines all words.
4. Set language for spelling:
```
setlocal spell spelllang=ru
```
Output:
```
spellfile#LoadFile(): No (writable) spell directory found.
Failed to create: /home/cyga/.local/share/nvim/site/spell
Warning: Cannot find word list "ru.utf-8.spl" or "ru.ascii.spl"
Press ENTER or type command to continue
```

Expected:
only the first word is highlighted as not correctly spelled.
In neovim the same functionality already works.

I found a closed issue on the topic:
https://github.com/LunarVim/LunarVim/issues/3619
but it looks like this wasn't fixed since I'm using the latest version from the git (and I can't reopen that issue).

### LunarVim version

master-4b77c9c

### Neovim version (>= 0.8.0)

v0.8.2

### Operating system/version

Ubuntu 22.04.01

**Comment by LostNeophyte** [comment]
Do you have this directory? ~/.config/lvim/spell

**Comment by cyga** [comment]
> Do you have this directory? ~/.config/lvim/spell

No, I didn't.

I created it manually and then repeated my actions above.
I was asked if I want to download the corresponding language files.
I answered yes.
Now check speller looks good.
Also, I checked files after the operation above:
```
ls ~/.config/lvim/spell
ru.utf-8.spl  ru.utf-8.sug
```
Thus,  I guess directory creation was missing somewhere on the way.

**Comment by antonkesy** [comment]
This is still an issue
I had to manually create the spell directory before being asked to download missing language files

**Comment by selmison** [comment]
The same error here. As workaround I need to create the `~/.config/lvim/spell` folder suggested by @LostNeophyte

**Comment by JVAQUEROM** [comment]
I had the same issue and I had to create the  `~/.config/lvim/spell` folder and that solved it.
