### ISSUE TITLE
Treesitter parsers are deleted after every update to LunarVim

### ISSUE THREAD

**Issue by LeviticusNelson** [LunarVim/LunarVim#3744]
### Problem description

After migrating to lazy.nvim, there seems to be a deletion of all of the Treesitter parsers after an update has been ran on LunarVim.

### LunarVim version

master-1162b72

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-731+g20b7be2d1-dirty

### Operating system/version

macOS 13.2 Beta (22D5038i)

### Steps to reproduce

```:LvimUpdate```

**Comment by LostNeophyte** [comment]
I know the reason. Lazy.sync cleans plugins, i'll fix it
