### ISSUE TITLE
LSP-Config UI customization quality of life improvement

### ISSUE THREAD

**Issue by ecthelionvi** [LunarVim/LunarVim#3752]
### Feature Description

Frequently when writing code it can be quite cumbersome to view lsp info as sometimes it extends past the viewable window. In referring to lsp config docs I came upon: https://github.com/neovim/nvim-lspconfig/wiki/UI-customization, specifically the ability to view diagnostic info in a pop upon holding your cursor on the error in question. I found it to be supremely useful and a major quality of life enhancement. There are other alternatives to this solution such as whynothugo/lsp_lines.nvim, but think implementing the code in the lsp config wiki:

`lvim.lsp.on_attach_callback = function(client, bufnr)
  vim.api.nvim_create_autocmd("CursorHold", {
    buffer = bufnr,
    callback = function()
      local opts = {
        focusable = false,
        close_events = { "BufLeave", "CursorMoved", "InsertEnter", "FocusLost" },
        border = 'rounded',
        source = 'always',
        prefix = ' ',
        scope = 'cursor',
      }
      vim.diagnostic.open_float(nil, opts)
    end
  })
end`

Is simpler and does not require an additional plugin. I would recommend you try it yourself and see how useful it might be. I think many user would appreciate it. 

### Describe the alternatives you have considered

whynothugo/lsp_lines.nvim

**Comment by LostNeophyte** [comment]
you can use `gl` to view the currently focused error in a popup,

you can create that autocommand in your config if you want

**Comment by ecthelionvi** [comment]
I did not realize you can do gl, I should I have looked more a the docs. Thank you for the info. Closing now.
