### ISSUE TITLE
~/.local/share/lunarvim/lvim/lua/lvim/config/_deprecated.lua:155: `requires` in `lvim.plugins` is deprecated.  Use `dependencies` instead See https://github.com/folke/lazy.nvim#-migration-guide.

### ISSUE THREAD

**Issue by rjs520** [LunarVim/LunarVim#3760]
### Problem description

Using nightly lunarvim, it will automatically open with an error and no changes have been made

### LunarVim version

master-98ef4a1

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

Ubuntu 22

### Screenshots

![image](https://user-images.githubusercontent.com/87847751/213648087-8b130358-6305-4f51-82c6-b36aa07e1fa5.png)

**Comment by rjs520** [comment]
But I don't know how to modify it, because this is lunarvim's configuration file

**Comment by LostNeophyte** [comment]
the problem is your config.lua, the path is where the message was printed

**Comment by LostNeophyte** [comment]
here's an example of what I had to do https://gitlab.com/lostneophyte/dotfiles/-/commit/ec2a68e57053867bacca276eead1c6ba75e92e5f
