### ISSUE TITLE
Error while updating through commandline

### ISSUE THREAD

**Issue by ksajan** [LunarVim/LunarVim#3766]
### Problem description

After running the command `lvim +LvimUpdate +LvimCacheReset +q` it produces this error

```
Error detected while processing command line:
Error executing vim.schedule lua callback: ...rvim/site/pack/lazy/opt/lazy.nvim/lua/lazy/view/text.lua:72: Vim:E315: ml_get: invalid lnum: 2
stack traceback:
	[C]: in function 'nvim_buf_set_lines'
	...rvim/site/pack/lazy/opt/lazy.nvim/lua/lazy/view/text.lua:72: in function 'render'
	...im/site/pack/lazy/opt/lazy.nvim/lua/lazy/view/render.lua:77: in function 'update'
	...rvim/site/pack/lazy/opt/lazy.nvim/lua/lazy/view/init.lua:133: in function 'fn'
	.../lunarvim/site/pack/lazy/opt/lazy.nvim/lua/lazy/util.lua:70: in function <.../lunarvim/site/pack/lazy/opt/lazy.nvim/lua/lazy/util.lua:69>%
```

### LunarVim version

master-2d3140f0

### Neovim version (>= 0.8.0)

NVIM v0.8.2

### Operating system/version

macOS 13.1 ( m1 )

### Steps to reproduce

- Install lunarvim
 - if any custom configuration add in config.lua
 - Updating lunarvim using command line argument `lvim +LvimUpdate +LvimCacheReset +q`

### Screenshots

<img width="1107" alt="Screenshot 2023-01-22 at 6 06 22 PM" src="https://user-images.githubusercontent.com/31013555/213916183-70615f5a-8bf2-4425-9972-7e7b17b86afb.png">

**Comment by LostNeophyte** [comment]
I can't reproduce

**Comment by rebuilt** [comment]
I also can't reproduce

**Comment by ca11ado** [comment]
Have the same issue. Trying to update by LunarVim keymap: "<leader>Lu"
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/3800764/229257254-9c4aa965-aaab-47da-a4e9-6d32501c9d7a.png">
