### ISSUE TITLE
Unable to use `pnpm` to install Node dependancies

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [LunarVim/LunarVim#3768]
### Problem description

while trying to install it and accepting the `install node dependancies` prompt the installation uses `npm` and fails

### LunarVim version

latest stable

### Neovim version (>= 0.8.0)

0.8.2

### Operating system/version

macOS 13.1

### Steps to reproduce

1. try installing
2. accept node dependancies

### Screenshots

<img width="1449" alt="Screenshot 2023-01-22 at 11 46 42" src="https://user-images.githubusercontent.com/74371045/213927944-81d2e28d-1b4f-4eea-86a2-101724577ff3.png">

already uninstalled npm global dependancies, `neovim` installed through Homebrew

unable to use pnpm instead of npm

**Comment by LostNeophyte** [comment]
it's fixed on master, you can just skip installing npm deps
