### ISSUE TITLE
Cannot override LSP server using lvim.lsp.manager

### ISSUE THREAD

**Issue by zane131** [LunarVim/LunarVim#3771]
### Problem description

Using the instructions here: https://www.lunarvim.org/docs/languages#server-setup

I have the following in `~/.config/lvim/after/ftplugin/cpp.lua`:

```lua
vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "clangd" })

-- Disabling the fallback style to ensure formatting is only applied if a
-- project has defined a `.clang-format` file.
local opts = { cmd = { "clangd", "--fallback-style=none" } }

require("lvim.lsp.manager").setup("clangd", opts)  -- does not work
--require("lspconfig")["clangd"].setup(opts)       -- works
```

Using `lvim.lsp.manager`, the target command argument is not used, which causes `clangd` to apply the default formatting (llvm) on files that should not be formatted at all. At least, by using `lspconfig` I am able to get the desired behavior to work, but I don't get the lvim `on_attach` and `capabilities` support that all the other servers have.

### LunarVim version

release-1.2

### Neovim version (>= 0.8.0)

neovim-0.8-8f4a7bd (v.0.8.2)

### Operating system/version

macOS 13.1

### Affected language servers

clangd

### Steps to reproduce

1. Define FTPlugin as shown in problem description.
2. Open poorly formatted C++ file in a project that does not have a `.clang-format` file defined in the current working directory or any parent directories.
3. Format the file with `<leader>lf` or by saving the file (if "format on save" is enabled).

### Actual behavior

Clang-format will apply default formatting (llvm) to the file.

### Expected behavior

The file should remain unchanged.

### support info

 Using `lvim.lsp.manager`, `:LspInfo` shows:
 
 ```console
 Client: clangd (id: 3, pid: nil, bufnr: [1])
 	filetypes:       c, cpp, objc, objcpp, cuda, proto
 	autostart:       true
 	root directory:  /Users/zshelle/sandbox/prd
 	cmd:             clangd
 
 Configured servers list: clangd
 ```

 Using `lspconfig`, `:LspInfo` shows:

  ```console
 Client: clangd (id: 3, pid: nil, bufnr: [1])
 	filetypes:       c, cpp, objc, objcpp, cuda, proto
 	autostart:       true
 	root directory:  /Users/zshelle/sandbox/prd
 	cmd:             clangd --fallback-style=none
 
 Configured servers list: clangd
 ```

**Comment by LostNeophyte** [comment]
did you do `:LvimCacheReset` ?

**Comment by LostNeophyte** [comment]
does `:LspInfo` show the changed cmd?

it does work for me on master
![image](https://user-images.githubusercontent.com/110467150/214320746-3e92e965-21ce-47a2-9b08-9fc3b9013e28.png)

**Comment by zane131** [comment]
I'm still not seeing the correct command when I use `lvim.lsp.manager`. Maybe the cache reset isn't working as expect? I don't get any feedback when I run the command. Is there a way to manually clear the cache?

**Comment by LostNeophyte** [comment]
> I'm still not seeing the correct command when I use `lvim.lsp.manager`. Maybe the cache reset isn't working as expect? I don't get any feedback when I run the command. Is there a way to manually clear the cache?

move `vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "clangd" })` to config.lua (so it runs always and not only in cpp files), restart lvim, run LvimCacheReset, restart lvim, and to check if it was cleaned correctly do `leader L f` and search for cpp.lua, there should be no such file

**Comment by zane131** [comment]
I moved that line and reset as requested, but the cpp.lua file still exists:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/1259185/214333293-e13e2e01-50fe-4098-8c99-3287e9e1f227.png">

When I run `:lua print(vim.inspect(lvim.lsp.automatic_configuration.skipped_servers))`, `clangd` is in the list:
```
{ "angularls", "ansiblels", "ccls", "csharp_ls", "cssmodules_ls", "denols", "ember", "emmet_ls", "eslint", "eslintls", "glint", "golangci_lint_ls", "gradle_ls", "graphql", "jedi_language_server", "ltex", "o
camlls", "phpactor", "psalm", "pylsp", "quick_lint_js", "reason_ls", "rome", "ruby_ls", "scry", "solang", "solc", "solidity_ls", "sorbet", "sourcekit", "sourcery", "spectral", "sqlls", "sqls", "stylelint_ls
p", "svlangserver", "tflint", "verible", "vuels", "clangd" }
Press ENTER or type command to continue
```

I manually deleted that file, reset cache, restarted, etc. Still no results. Then, I moved the rest of my `cpp.lua` file to `config.lua` and it works.

**Comment by zane131** [comment]
Ah, I think I figured it out. In `config.lua', I added `clangd` to `lvim.lsp.installer.setup.ensure_installed`. After removing it everything works with `vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "clangd" })` in `config.lua` and the following in `~/.config/lvim/after/ftplugin/cpp.lua`:

```
-- Disabling the fallback style to ensure formatting is only applied if a
-- project has defined a `.clang-format` file.
local opts = { cmd = { "clangd", "--fallback-style=none" } }

require("lvim.lsp.manager").setup("clangd", opts)
```
