### ISSUE TITLE
[ERROR]: Unable to verify plugins, make sure to manually run ':Lazy sync' when starting lvim for the first time.

### ISSUE THREAD

**Issue by parraletz** [LunarVim/LunarVim#3773]
### Problem description

Steps to reproduce:

1.- I tried to install lunarvim, but I got an error 

```
mismatch at [packer.nvim]: expected [6afb674], got [1d0cf98]
[ERROR]: Unable to verify plugins, make sure to manually run ':Lazy sync' when starting lvim for the first time.
```

2.- Open lvim , 
<img width="473" alt="Screenshot 2023-01-24 at 6 46 35" src="https://user-images.githubusercontent.com/1150748/214295301-c6027bc7-7a46-4d7d-99c2-b73638386dbc.png">

-----
Nvim
 
<img width="587" alt="Screenshot 2023-01-24 at 6 47 12" src="https://user-images.githubusercontent.com/1150748/214295390-41491d38-2b59-41b5-b2b0-d7a931757620.png">

MacOS Ventura 13.1

### LunarVim version

release-1.2/neovim-0.8

### Neovim version (>= 0.8.0)

neovim-0.8

### Operating system/version

macOS 13.1

**Comment by LostNeophyte** [comment]
what's the exact command you used to install lunarvim? I think it's now the updated (a couple days ago) one on the website

**Comment by brneor** [comment]
Looks similar to https://github.com/LunarVim/LunarVim/discussions/3707

**Comment by parraletz** [comment]
@LostNeophyte ` LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)  `

**Comment by LostNeophyte** [comment]
> @LostNeophyte `LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh) `

yup, that's not the one that's on the website now, use `LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh)`

**Comment by userrand** [comment]
The website says that one should install using `LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)` according to https://www.lunarvim.org/docs/installation#uninstall. That did not work for me. According to this conversation it seems like the command should be updated to the one given by @brneor .
