### ISSUE TITLE
Error when opening Makefile with file extension

### ISSUE THREAD

**Issue by paulgrove** [LunarVim/LunarVim#3777]
I have a project that has several Makefiles named like:

- Makefile.linux-amd64
- Makefile.windows-amd64
- Makefile.freebsd-amd64

Opening these files in lunarvim causes errors in `local/share/lunarvim/lvim/lua/lvim/core/breadcrumbs.lua:108`:

```
Error detected while processing CursorHold Autocommands for "*":
E5248: Invalid character in group name
Press ENTER or type command to continue
Error detected while processing CursorHold Autocommands for "*":
Error executing lua callback: ....local/share/lunarvim/lvim/lua/lvim/core/breadcrumbs.lua:108: Invalid highlight name: FileIconColorfreebsd-amd64
stack traceback:
        [C]: in function 'nvim_set_hl'
        ....local/share/lunarvim/lvim/lua/lvim/core/breadcrumbs.lua:108 in function 'get_filename'
        ....local/share/lunarvim/lvim/lua/lvim/core/breadcrumbs.lua:173: in function 'get_winbar'
        ....local/share/lunarvim/lvim/lua/lvim/core/breadcrumbs.lua:219: in function <....local/share/lunarvim/lvim/lua/lvim/core/breadcrumbs.lua:216>
Press ENTER or type command to continue
```

The errors continue with interaction with the editor and make using the editor impossible.

As a workaround, I have added the following code. However, I do not know Lua nor what the ideal fix would be:

```
    if extension ~= "linux-amd64" and extension ~= "freebsd-amd64" and extension ~= "windows-amd64" then
      hl_group = hl_group .. extension
    end
```

There is probably a simple fix to catch the error here or to check that the highlight name exists or some other sanity check.  But I do not know the correct course of action.

Many thanks for the great project!

**Comment by LostNeophyte** [comment]
please use the issue template next time, there's a field there for your lvim version and you didn't provide it, I assume you use 1.2

this issue is fixed on master
