### ISSUE TITLE
rust file can't be run with lunarvim,but it's ok in vscode or intellij Rust 

### ISSUE THREAD

**Issue by Leviathans** [LunarVim/LunarVim#3778]
### Problem description

1.excute commond RustRun
2.get error 
error[E0432]: unresolved import `log`
 --> src/main.rs:1:5
  |
1 | use log::info;
  |     ^^^ maybe a missing crate `log`?
  |
  = help: consider adding `extern crate log` to use the `log` crate

error: cannot determine resolution for the macro `info`
  --> src/main.rs:10:5
   |
10 |     info!(
   |     ^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports
but it's work for vscode ,and source is

use log::info;

fn main() {
    log4rs::init_file("log4rs.yaml", Default::default()).unwrap();
    let person = Person {
        name: String::from("aaa"),
        age: 18,
        address: String::from("hello world"),
    };
    info!(
        "the person name is {},age is {},address is {}",
        person.name, person.age, person.address
    );
    person.say();
    Person::talk();
    let mut v = vec![1, 2, 3];
    v.push(5);
    for value in v {
        info!("vec element is {}", value);
    }
}

struct Person {
    name: String,
    age: u8,
    address: String,
}

impl Person {
    fn say(&self) -> u8 {
        1
    }

    fn talk() -> i32 {
        2
    }
}
 Cargo.toml
[package]
name = "order"
version = "0.1.0"
edition = "2021"
[dependencies]
log4rs = "1.2.0"
log = "0.4.17"

### LunarVim version

release-1.2

### Neovim version (>= 0.8.0)

neovim-0.8-8f4a7bd

### Operating system/version

macos 13.1

**Comment by LostNeophyte** [comment]
does the same happen in neovim?

**Comment by Leviathans** [comment]
> 

yes

**Comment by LostNeophyte** [comment]
the problem is somewhere else than lunarvim in that case
