### ISSUE TITLE
Latexmk causes the cursor to flicker.

### ISSUE THREAD

**Issue by afaikiac** [LunarVim/LunarVim#3779]
### Problem description

I compared `LunarVim` and `nvim` with empty `config.lua` and minimal `init.lua` respectively.

When I run `latexmk` in `:terminal` or in `:TermExec` and the cursor is in another buffer, it flickers.

In `nvim` all ok. I use `alacritty 0.11.0 (8dbaa0bb)` terminal emulator.

It's a very annoying bug.

### LunarVim version

master-fab66b0

### Neovim version (>= 0.8.0)

NVIM v0.8.2

### Operating system/version

6.1.7-arch1-1

### Steps to reproduce

1. Run `latexmk` build in `LunarVim`.
2. Place cursor in another buffer.

### Screenshots

`LunarVim`: 0 - 37 sec.
`nvim`: 38 - ... sec.

https://user-images.githubusercontent.com/45965330/214674896-e4596f27-0294-4d52-8d2f-62d1a613d50c.mp4

**Comment by LostNeophyte** [comment]
I can't reproduce using `timeout 5s yes` in :term, does that cause the cursor to flicker for you?

**Comment by afaikiac** [comment]
Sorry @LostNeophyte, my bad. I can only reproduce it when I run `latexmk` with `-outdir='build'` option. I've tried creating new files or log into new files in subdir in a loop, but no luck. This is a very specific issue, I'll close it.
