### ISSUE TITLE
Error when deleting more than 5-6 characters with 'x' 

### ISSUE THREAD

**Issue by nairobi02** [LunarVim/LunarVim#3781]
### Problem description

Expected behavior: deleting characters, error shouldn't occur. 
Actual behavior: characters are deleted as usual and sent to correct buffers. But error still shows.

### LunarVim version

master—2d3140f

### Neovim version (>= 0.8.0)

NVIM v0.8.0-v0.8.0

### Operating system/version

windows 10 wsl2

### Steps to reproduce

1.Have win32yank as clipboard 
2.Open any file in lunarvim
3. lone press x to delete multiple characters

### Screenshots

![image](https://user-images.githubusercontent.com/109964994/214762000-4cae93da-e9b2-4e0d-95a5-c07ad867e391.png)

**Comment by rebuilt** [comment]
Can you try the troubleshooting steps listed here: https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl

**Comment by kobzar** [comment]
Closed as long inactive time.  (Solution is present)
