### ISSUE TITLE
Is there any meson build support on lvim ?

### ISSUE THREAD

**Issue by MyraBaba** [LunarVim/LunarVim#3782]
### Feature Description

meson build system 

Is there any plugin for meson build system for Lunarvim ?

**Comment by mjour** [comment]
I'm not aware of any specific plugin for the LunarVim text editor that adds support for the Meson build system. LunarVim is a distribution of the Vim text editor that includes a number of plugins and customizations for enhanced functionality, but I couldn't find any information about it having built-in support for Meson.
However, LunarVim is built on top of Vim and it doesn't have to be limited to the plugins they include, you can use any plugin that works with regular Vim, so you could use a Meson plugin for Vim in LunarVim.

**Comment by LostNeophyte** [comment]
we don't have anything built in

**Comment by MyraBaba** [comment]
@LostNeophyte  is there any third party party meson system ?

**Comment by LostNeophyte** [comment]
I've never used any
