### ISSUE TITLE
plugin colorizer wont show color preview after save any file

### ISSUE THREAD

**Issue by shgvrxysic38821** [LunarVim/LunarVim#3786]
### Problem description

install plugin https://github.com/NvChad/nvim-colorizer.lua

Then save any file, the color preview will gone. 

I clear my config file and only leave the plugin. The issue still there. How to solve it?

### LunarVim version

master-e45afe9

### Neovim version (>= 0.8.0)

NVIM v0.8.0-dev-914-gd4d27c41b

### Operating system/version

OS: Ubuntu 22.04 jammy

**Comment by opalmay** [comment]
I can't reproduce.
You're using a development version of 0.8.0, meaning lower than 0.8.0. Start with upgrading that.

**Comment by woshichuanqilz** [comment]
> I can't reproduce. You're using a development version of 0.8.0, meaning lower than 0.8.0. Start with upgrading that.

Same issue. After I upgrade nvim to 

```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az183-550

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by kobzar** [comment]
Don't use Colorizer plugin from Nvchad
try this one with sample of settings
https://www.lunarvim.org/docs/plugins/extra-plugins#nvim-colorizer

**Comment by kobzar** [comment]
Working normaly with 
https://www.lunarvim.org/docs/plugins/extra-plugins#nvim-colorizer
Lvim 1.2 stable
nvim 8.3++
