### ISSUE TITLE
PackerSync error related to Telescope during fresh Windows install

### ISSUE THREAD

**Issue by Nowaha** [LunarVim/LunarVim#3788]
### Problem description

I'm trying to install LunarVim on a Windows 11 machine using these steps:
https://www.lunarvim.org/docs/installation

- I run the script in Powershell 7.3, say yes to all dependency checks which pass. No errors show. 
- I then launch the bare installation LunarVim (lvim).
- Then I run `:PackerSync`.
- It goes fine until at some point I get an error telling me "Failed spawning command: pwsh.exe -NoLogo because NOENT: no such file or directory"
- - pwsh.exe is certainly a registered command in my path, see screenshot.

The error seems to appear while installing `nvim-telescope\telescope-fzf-native.nvim` inside of the Packer Sync.
If I press enter to continue I am thereafter left with a permanent [nvim-treesitter] [0/2] Compiling... error at the bottom of my screen, and if I go to the lvim dashboard and select "Find File" I get Telescope related errors.

### LunarVim version

release-1.2/neovim-0.8-7f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.2

### Operating system/version

Windows 11

### Screenshots

![image](https://user-images.githubusercontent.com/5718297/215222233-e82b36e0-ae9f-4db9-b27c-e9bb9bfdd1b5.png)

**Comment by carlosonrails** [comment]
It wasn't a bug probably. It happens cause telescope need some dependencies with gcc. I tried out here and get same behavior. Here solved it installing Mingw. 
The easiest way to install: 

`choco install mingw`

After reinstall lunarvim then :PackerSync

**Comment by Nowaha** [comment]
> It wasn't a bug probably. It happens cause telescope need some dependencies with gcc. I tried out here and get same behavior. Here solved it installing Mingw. The easiest way to install:
> 
> `choco install mingw`
> 
> After reinstall lunarvim then :PackerSync

That, unfortunately, makes no difference 😔
I installed mingw but I have gcc working regardless

**Comment by Nowaha** [comment]
Okay, I have resolved the issue! For anyone with the same issue, make sure you have ripgrep installed (you can run "rg") - `choco install ripgrep`. This was at least the issue for me.

Do check your dependencies with `:checkhealth` to see what you're missing for Telescope (if that's the issue)

Thanks :)
