### ISSUE TITLE
Fail to install on Fedora 37

### ISSUE THREAD

**Issue by acv-98** [LunarVim/LunarVim#3791]
### Problem description

Hi, I installed all dependencies and said yes during installation to all using the bash script for latest release from the official page and I'm getting this installation error.

```
Installing LunarVim shim
make: Entering directory '/home/acv/.local/share/lunarvim/lvim'
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
mkdir: cannot create directory ‘/home/acv/.local/bin’: File exists
make: *** [Makefile:9: install-bin] Error 1
make: Leaving directory '/home/acv/.local/share/lunarvim/lvim'
```

I'm on Fedora 37 workstation edition and from what I can see my `/.local/bin` is not usable, but instead I've been using `/usr/local/bin` for other installations

`cd: /home/acv/.local/bin: Not a directory`

Is there any way to change the default installation path ?

### LunarVim version

1.2.0

### Neovim version (>= 0.8.0)

0.8.2

### Operating system/version

Fedora Workstation 37

### Steps to reproduce

Install all dependencies then run bash script  `LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh)`

**Comment by LostNeophyte** [comment]
> from what I can see my /.local/bin is not usable

make it usable. do you have a `bin` file there? if so then remove it

**Comment by acv-98** [comment]
> > from what I can see my /.local/bin is not usable
> 
> make it usable. do you have a `bin` file there? if so then remove it

Made a copy of it just in case, but yeah it was safe to delete it seems. Thank you, all good now
