### ISSUE TITLE
When I open a buffer in nvimtree, the root dir of nvimtree expands to become $home

### ISSUE THREAD

**Issue by dnxxymcj** [LunarVim/LunarVim#3792]
### Problem description

When I open a buffer in nvimtree, the root dir of nvimtree expands to become $home

### LunarVim version

master-fab66b0

### nvim-tree version
branch master commit https://github.com/nvim-tree/nvim-tree.lua/commit/e8a89db1bbc06510a76fc935754b4e99a3e5e8a7

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-756+g0481f04ec-dirty

### Operating system/version

macOS 13.1 

### Steps to reproduce

1.  `lvim .` in $HOME/.config/lvim 
2.  `<leader> e`  open the nvimtree
3. select a file and open it 
4. nvimtree is expanded

### Screenshots

https://user-images.githubusercontent.com/7660888/215328139-738c226b-8192-4a45-ba5f-d37ff3b725bc.mov

**Comment by LostNeophyte** [comment]
project.nvim does that, you probably have one of these files in your home https://github.com/LunarVim/LunarVim/blob/c18cd3f0a89443d4265f6df8ce12fb89d627f09e/lua/lvim/core/project.lua#L26
