### ISSUE TITLE
Some settings don't persist after closing LunarVim

### ISSUE THREAD

**Issue by Shock9616** [LunarVim/LunarVim#3800]
### Problem description

Some of my settings/plugins aren't persisting after closing LunarVim. The things I've specifically noticed are bracket colour matching with `aklk1ng/nvim-ts-rainbow` and setting ToggleTerm to open in the horizontal direction instead of floating. Both of these settings refuse to work until I open and re-save the config file. 

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.2-release

### Operating system/version

macOS 13.1

### Steps to reproduce

1. in `~/.config/lvim/config.lua`
```lua 
lvim.plugins = {
    -- Some plugins
    { "aklk1ng/nvim-ts-rainbow" },
    -- Some more plugins
}

...

require("nvim-treesitter.configs").setup {
    rainbow = {
        enable = true,
        extended_mode = true,
        max_file_lines = nil,
    }
}

require("toggleterm").setup {
    size = 15,
    direction = "horizontal",
}
```
2. Close lvim
3. Open a file in lvim and notice that the parentheses, brackets, etc. aren't coloured, and that if the terminal is opened with `<C-\>` it still floats instead of being at the bottom (make sure to close the terminal with `exit` not just hide it)
4. Open config file and `:w`, and notice that the brackets immediately become highlighted and the terminal opens in the horizontal direction.

### Screenshots

Screen Recording of the problem https://drive.google.com/file/d/1JWlqKDKLS0z5yRhi2vl6I0TC4KPrBpQW/view?usp=share_link

**Comment by LostNeophyte** [comment]
that's because you're not configuring them using the intended way of editing lvim.builtin.<builtin>.option = value
