### ISSUE TITLE
Icons are not appearing when using the Master branch build

### ISSUE THREAD

**Issue by kingedward35** [LunarVim/LunarVim#3802]
### Problem description

Recently upgraded LunarVim to use the latest master branch version and as a result, many of the icons that previously showed up no longer do. Since the font and the terminal emulator have not changed, it was surprising that upgrading to the newest version seemed to affect the appearance of the icons. I would have assumed since nothing changed on my end as far as the terminal and the font, that there should be no change in the display of the icons.

### LunarVim version

master-c18cd3f0

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-771+g18fb669b9

### Operating system/version

MacOs v12.4 Monterey

### Steps to reproduce

1. Update the LunarVim version from v1.2 to latest.
2. Run the `lvim` command and open a file.

### Screenshots

<img width="318" alt="image" src="https://user-images.githubusercontent.com/12418717/216209964-cc14d7a8-6e98-47d6-af5e-3600c4cf92b3.png">

<img width="279" alt="image" src="https://user-images.githubusercontent.com/12418717/216210021-da0c850a-f6e5-4da0-a268-a64352f8ce72.png">

<img width="505" alt="image" src="https://user-images.githubusercontent.com/12418717/216210063-eeda3068-ce04-4a46-b2f5-a2b8eda3262c.png">

**Comment by LostNeophyte** [comment]
update your nerd font
