### ISSUE TITLE
W18: Invalid character in group name after install 

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3818]
### Problem description

I install the lunarvim. And get a lot of W18 errors when enter lvim. 
How to fix it. 

Error message : 
error when processing /home/lizhe/.local/share/lunarvim/lvim/init.lua

![image](https://user-images.githubusercontent.com/11295355/216871750-be301385-7601-46a9-9bd2-26cdec2bf057.png)

### LunarVim version

LvimVersion Command not recognized

### Neovim version (>= 0.8.0)

NVIM v0.8.0-dev-914-gd4d27c41b

### Operating system/version

OS: Ubuntu 22.04 jammy

### Steps to reproduce

Content of /home/lizhe/.local/share/lunarvim/lvim/init.lua

```
local base_dir = vim.env.LUNARVIM_BASE_DIR
  or (function()
    local init_path = debug.getinfo(1, "S").source
    return init_path:sub(2):match("(.*[/\\])"):sub(1, -2)
  end)()

if not vim.tbl_contains(vim.opt.rtp:get(), base_dir) then
  vim.opt.rtp:append(base_dir)
end

require("lvim.bootstrap"):init(base_dir)

require("lvim.config"):load()

local plugins = require "lvim.plugins"

require("lvim.plugin-loader").load { plugins, lvim.plugins }

require("lvim.core.theme").setup()

local Log = require "lvim.core.log"
Log:debug "Starting LunarVim"

local commands = require "lvim.core.commands"
commands.load(commands.defaults)

require("lvim.lsp").setup()

```

**Comment by LostNeophyte** [comment]
Update neovim
