### ISSUE TITLE
Which Key panel not opening up if `<` gets mapped

### ISSUE THREAD

**Issue by Artem-Schander** [LunarVim/LunarVim#3821]
### Problem description

Steps to reproduce:
1. Go to `config.lua`
2. Add the following line
```lua
lvim.builtin.which_key.mappings["<"] = { ":echo 'foo'<CR>", "Foo" }
```
3. Load config
4. Hit space (or your leader key)
5. Realize that Which Key panel does not open

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.

### Operating system/version

macOS Ventura 13.1

**Comment by brneor** [comment]
Can reproduce on Lunarvim `master-24d8780d` with neovim `v0.9.0-dev-869+g964ae205a-dirty`.

**Comment by LostNeophyte** [comment]
can't reproduce on lvim `master-4d8780d` nvim v0.9.0-dev+701-g34b973b1d

**Comment by LostNeophyte** [comment]
Can you reproduce in neovim? I don't think it's a bug in lunarvim

**Comment by opalmay** [comment]
In lua `["<"]` is not a valid index.
Idk what is the right way to map these with whichkey

**Comment by kobzar** [comment]
Working fine in last stable version of lvim (check on  nvim 8.3++ lvim stable)

**Comment by Artem-Schander** [comment]
can confirm. works with nvim 9
