### ISSUE TITLE
The meaning of red triangle icon.

### ISSUE THREAD

**Issue by ez4lionky** [LunarVim/LunarVim#3822]
### Problem description

I'm confused and don't know why a red triangle occurred before the line number.
It's sometimes annoying because it looks like there is some error.
Although I just opened a pure text file, as shown in the picture below.

### LunarVim version

release-1.2

### Neovim version (>= 0.8.0)

neovim-0.8-8f4a7bd

### Operating system/version

Ubuntu 20.04

### Screenshots

![image](https://user-images.githubusercontent.com/23551503/217262097-2f3070e4-217b-4f7c-bdcc-99e38f12a354.png)

**Comment by brneor** [comment]
Git line removed

**Comment by ez4lionky** [comment]
> Git sign for line removed

Got it!
Thanks for your reply!
