### ISSUE TITLE
Transparent window setting is not working properly in nvim-tree

### ISSUE THREAD

**Issue by cmdctl** [LunarVim/LunarVim#3839]
### Problem description
I've been struggling for a couple of days with this issue and I can't seem to get it working. I tried different themes with the same result. I tried with other terminal emulators ( currently using Iterm2) still no effect. I have no idea how to fix this. I can't find a setting in the nvim-tree for controlling this (to set the background manually somehow). I would really appreciate some help on this :( 

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

v0.8.1

### Operating system/version

macOS Ventura / 13.0.1 

### Steps to reproduce
1. Open `config.lua`
2. Add `lvim.transparent_window = true` to your settings using any theme (Example uses `lunar`)
3. Focus on the nvim-tree buffer (cursor to be in the file tree) and the transparent window is applied
4. Focus out on the nvim-tree (cursor on any open buffer - `config.lua` in this example) and the background of nvim-tree is no longer transparent
_No response_

### Screenshots

<img width="1920" alt="Screenshot 2023-02-12 at 16 50 09" src="https://user-images.githubusercontent.com/10723474/218318619-53df9f8c-c30f-4288-8ff3-636fb901adac.png">
<img width="1920" alt="Screenshot 2023-02-12 at 16 50 17" src="https://user-images.githubusercontent.com/10723474/218318629-6507036f-af33-41c4-aeb9-2bd28c59aa44.png">

**Comment by cpea2506** [comment]
Some color schemes hard-coded the value of the `NvimTreeNormalNC` group. So you need to set it manually with autocommands.

```lua
lvim.autocommands = {
   -- other commands,
   {
     "ColorScheme",
     { command = "hi NvimTreeNormalNC guibg=NONE" }
   }
}
```

**Comment by LostNeophyte** [comment]
Should we add it to [our autocommand](https://github.com/LunarVim/LunarVim/blob/f590770a17770f5cb74186e15204a9ffe1b96beb/lua/lvim/core/autocmds.lua#L102)?

**Comment by cpea2506** [comment]
> Should we add it to [our autocommand](https://github.com/LunarVim/LunarVim/blob/f590770a17770f5cb74186e15204a9ffe1b96beb/lua/lvim/core/autocmds.lua#L102)?

If then, we should add it to [this](https://github.com/LunarVim/LunarVim/blob/f590770a17770f5cb74186e15204a9ffe1b96beb/lua/lvim/core/autocmds.lua#L197)

**Comment by LostNeophyte** [comment]
> > Should we add it to [our autocommand](https://github.com/LunarVim/LunarVim/blob/f590770a17770f5cb74186e15204a9ffe1b96beb/lua/lvim/core/autocmds.lua#L102)?
> 
> There are so many questions about this problem so I think we should. If then, we should add it to [this](https://github.com/LunarVim/LunarVim/blob/f590770a17770f5cb74186e15204a9ffe1b96beb/lua/lvim/core/autocmds.lua#L197)

yup, do you want to do that or I?

**Comment by cpea2506** [comment]
> > > Should we add it to [our autocommand](https://github.com/LunarVim/LunarVim/blob/f590770a17770f5cb74186e15204a9ffe1b96beb/lua/lvim/core/autocmds.lua#L102)?
> > 
> > 
> > There are so many questions about this problem so I think we should. If then, we should add it to [this](https://github.com/LunarVim/LunarVim/blob/f590770a17770f5cb74186e15204a9ffe1b96beb/lua/lvim/core/autocmds.lua#L197)
> 
> yup, do you want to do that or I?

I have some works to do in these moment. So you can do it if you have free time. 😅
