### ISSUE TITLE
Stop using `$XDG_STATE_HOME/nvim`

### ISSUE THREAD

**Issue by REmerald** [LunarVim/LunarVim#3840]
### Feature Description

Logs and stuff must be separated from nvim and written to e.g. `$HOME/.local/state/lunarvim/` and NOT `$HOME/.local/state/nvim/`.

### Describe the alternatives you have considered

Use `$LUNARVIM_CACHE_DIR` instead?

### Support information

I also use my own neovim config in addition to lunarvim, and when I was trying to debug a lsp server in lunarvim, I realized that files like `lsp.log`, `mason.log` are written to the nvim's dir, not lunarvim's!

**Comment by LostNeophyte** [comment]
related https://github.com/LunarVim/LunarVim/issues/3541

**Comment by jeeeem** [comment]
maybe this can be useful - https://github.com/neovim/neovim/pull/22128
