### ISSUE TITLE
Lunarvim doesn't complete macros in C (clangd)

### ISSUE THREAD

**Issue by REmerald** [LunarVim/LunarVim#3842]
### Problem description

Macros for the C language don't show up in the nvim-cmp: `EIO`, `EXIT_FAILURE`, etc. and user-defined macros:
![image](https://user-images.githubusercontent.com/55359236/218329667-018910b5-9065-4cec-8f53-4510f7101ff9.png)

As opposed to my basic neovim config (also `nvim-lspconfig`, `nvim-cmp` and `clangd` but without `mason`):
![image](https://user-images.githubusercontent.com/55359236/218329573-1b83651d-a052-4e9c-8ab1-68e499514f4b.png)

### LunarVim version

master-fde46c4b

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev

### Operating system/version

Arch Linux

### Affected language servers

clangd

### Steps to reproduce

1. Open lvim with installed clangd.
2. Open `.c` file.
3. Add `#include <stdlib.h>`.
4. Add `main()` function.
5. Type `return ` `;`.
6. Try to complete `E` -> `EXIT_SUCCESS`.
7. The lsp completion doesn't show up inside nvim-cmp.

### Actual behavior

The lsp completion doesn't show up inside nvim-cmp.

### support info

lvim: [lvim-lsp.log](https://github.com/LunarVim/LunarVim/files/10716901/lvim-lsp.log)

nvim: [nvim-lsp.log](https://github.com/LunarVim/LunarVim/files/10716903/nvim-lsp.log)

**Comment by LostNeophyte** [comment]
use this, we filter out text from lsp suggestions by default 
```lua
  lvim.builtin.cmp.sources[2].entry_filter = nil
```

**Comment by tomkark** [comment]
> ```lua
> lvim.builtin.cmp.sources
> ```

Did not fix it.
