### ISSUE TITLE
"x" does not work on visual selection

### ISSUE THREAD

**Issue by cnshsliu** [LunarVim/LunarVim#3843]
### Problem description

1.  V to select several lines
2. press 'x'

the visual selected lines should be deleted, but nothing happens

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Operating system/version

Ventura 13.1 (22C65)

### Steps to reproduce

1. lvim anyfile
2. press V, then select several lines
3. press x

### Screenshots

<img width="842" alt="image" src="https://user-images.githubusercontent.com/2124836/218363970-c6a64c66-de6e-4acd-87af-660e8a63b6bf.png">

**Comment by LostNeophyte** [comment]
can't reproduce, check if the same happens with an empty config

**Comment by cnshsliu** [comment]
It turns out that is caused by leap.nvim plugin‘s default setting which take x as a mode key.
Sorry for being bothering.
