### ISSUE TITLE
Remove DAP and LSP

### ISSUE THREAD

**Issue by 1ofseven** [LunarVim/LunarVim#3845]
### Feature Description

Remove hooks to proprietary DAP and LSP protocol dependencies from lvim in favor of FOSS plugins and parsers.

### Describe the alternatives you have considered

It takes more effort but gdb and ycm paradigms are more removed from proprietary protocols and parsers.

### Support information

The license requirements found on the proprietary sites can conflict with FOSS in they can lead to "what's mine is mine, what's yours is mine" agreements.

**Comment by LostNeophyte** [comment]
what hooks to proprietary dependencies are you talking about?

Personally I don't think it's worth doing, it's a breaking change and most users probably wouldn't like it, LSP is a core feature of lvim and I wouldn't use it if it didn't support it

**Comment by 1ofseven** [comment]
Why make a faux ide based on proprietary code. Just pay for and use the proprietary IDE. Don't set coders up to freely offer code to a very rich company.

**Comment by LostNeophyte** [comment]
> Why make a faux ide based on proprietary code. Just pay for and use the proprietary IDE. Don't set coders up to freely offer code to a very rich company

what proprietary code do we depend on?

We don't force you to use lsp/dap (and they licensed under Creative Commons and MIT)
