### ISSUE TITLE
Error when hitting <Enter> to jump to a location in quickfix/location list window

### ISSUE THREAD

**Issue by Lorryntz** [LunarVim/LunarVim#3849]
### Problem description

In a quickfix list window opened by `:copen` or a location list window opened by `:lopen`, hitting \<Enter\> on any item gets the following error:
```
E21: Cannot make changes, 'modifiable' is off
```
I'm expecting to move the cursor to the corresponding location as I type \<Enter\> with my cursor on any item in the list.

### LunarVim version

master-87cde2f

### Neovim version (>= 0.8.0)

NVIM v0.8.0-release

### Operating system/version

macOS 12.3

### Steps to reproduce

1. Search for anything using `:lvim` command
2. Open the location list window using `:lopen`
3. Move the cursor to any result item and hit \<Enter\>

### Screenshots

![图片](https://user-images.githubusercontent.com/52034192/218970116-a7d31f90-f25b-4d3b-883a-750bc18cba1b.png)

**Comment by LostNeophyte** [comment]
can't reproduce on master-9b4c4ab6, does it happen with an empty config

**Comment by Lorryntz** [comment]
I've just tested it with an empty config and the config from `~/.local/share/lunarvim/lvim/utils/installer/config.example.lua`, and the issue doesn't exist. It's probably caused by my own config or one of the plugins I've installed but I have no idea how to locate it. Is there any way I can fix it by adding some new config?

**Comment by LostNeophyte** [comment]
> I've just tested it with an empty config and the config from `~/.local/share/lunarvim/lvim/utils/installer/config.example.lua`, and the issue doesn't exist. It's probably caused by my own config or one of the plugins I've installed but I have no idea how to locate it. Is there any way I can fix it by adding some new config?

Remove parts of the config and see what causes it

**Comment by Lorryntz** [comment]
Okay I found it. A rookie mistake. It's caused by an unnoticed remap for the <cr> key in normal mode.
