### ISSUE TITLE
Where to put java.lua file

### ISSUE THREAD

**Issue by Ralghs** [LunarVim/LunarVim#3857]
I am trying to set up jdtls and I see most tutorials tell me to put my java.lua file under ~/.config/nvim(in this case lvim)/ftplugin but I see a ftplugin file already in ~/.local/share/lunarvim/lvim. Does it matter where I put my java.lua file? Can I just choose any? What is the difference

**Comment by LostNeophyte** [comment]
don't edit files in `~/.local/share/lunarvim/*`, put it in .cofing/lvim/ftplugin/java.lua
