### ISSUE TITLE
LSP started twice?

### ISSUE THREAD

**Issue by Ralghs** [LunarVim/LunarVim#3862]
### Problem description

Every time I open a java file, the same errors get reported twice. I think this is maybe because the java.lua file got executed twice? Is there a way for me to find the location of these java.lua files?

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Operating system/version

macOS 13.2.1

### Affected language servers

jdtls

### Actual behavior

![32115CE1-EA82-4A48-942C-C013A9DCE0BD](https://user-images.githubusercontent.com/36202998/219719362-a6130d13-5509-41eb-b6a9-d30a81adbcb1.png)

### support info

![lspInfo](https://user-images.githubusercontent.com/36202998/219719590-384c9a84-7fcb-4228-9831-bdbfe5cbac46.png)

**Comment by Ralghs** [comment]
>

**Comment by Ralghs** [comment]
> did you set up jdtls yourself?

I opened a Java file and I think Mason installed jdtls automatically. Then I followed some tutorials and setup a java.lua file in ~/.config/Lvim/ftplugin/. Then I required jdtls again in config.lua and ran :PackerInstall. These are the only setups regarding jdtls I can recall

**Comment by LostNeophyte** [comment]
in that case you need to add jdtls to skipped_servers https://www.lunarvim.org/docs/master/configuration/language-features/language-servers#by-overriding-the-setup

**Comment by LostNeophyte** [comment]
also `Any changes to lvim.lsp.automatic_configuration.skipped_servers must be followed by :LvimCacheReset to take effect.`
