### ISSUE TITLE
auto save plugin conflict with  auto_format 

### ISSUE THREAD

**Issue by fastfading** [LunarVim/LunarVim#3868]
### Problem description

{
  "Pocco81/auto-save.nvim",
  config = function()
    require("auto-save").setup()
  end,
},

this plugin conflict with  auto_format 
lvim.format_on_save.enabled = true
lvim.format_on_save.timeout = 3000

when you change some thing , it auto saved ,  and auto formated
but when there is a indent space change ,  you press  u(undo)
it auto saved again and auto formated again .     so your undo does not work.

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

nvim 0.8

### Operating system/version

macos 13

**Comment by LostNeophyte** [comment]
that's expected, what else is it supposed to do?

**Comment by LostNeophyte** [comment]
duplicate of https://github.com/LunarVim/LunarVim/issues/3621

**Comment by fastfading** [comment]
try it ，  you will find the undo  won't work in this case ,  is there any way to fix it ?

**Comment by LostNeophyte** [comment]
I know it won't work, because it will auto save, what else did you expect it to do?
