### ISSUE TITLE
Error after updating through Lunarvim Dashboard 

### ISSUE THREAD

**Issue by carlosonrails** [LunarVim/LunarVim#3870]
### Problem description

I update as alwals with: Leader+L then u.
I get a lot errors and telescope broke. 

### LunarVim version

Can't use the command :LvimVersion, but in dashboard it says: master-f43cc8e2

### Neovim version (>= 0.8.0)

0.8.3

### Operating system/version

Arch Linux

### Steps to reproduce

Update Lunarvim from dashboard shortcut - Leader+L then u.

### Screenshots

![image](https://user-images.githubusercontent.com/69637662/219940659-8a7d9cb2-4d4e-42ca-84c7-365b91cda280.png)

**Comment by LostNeophyte** [comment]
the error has something to do with the rainbow plugin, maybe you're using p00f's unmaintained repo?

**Comment by carlosonrails** [comment]
I uninstalled it already and didn't stop to show the problem. But I'll try update again after it.

**Comment by carlosonrails** [comment]
> the error has something to do with the rainbow plugin, maybe you're using p00f's unmaintained repo?

It did solve the problem. I'll later to install the other version of this plugin.

**Comment by brneor** [comment]
@LostNeophyte  I'm getting (not exactly the same) errors using the maintained fork `mrjones2014/nvim-ts-rainbow`.
