### ISSUE TITLE
Git branch symbol not visible in all colorschemes except Lunar

### ISSUE THREAD

**Issue by antoineco** [LunarVim/LunarVim#3871]
### Problem description

Since 57c159fe3c4aec49aeb5a4df78275e7092fc21fa, the statusline icon for `lvim.core.lunaline.components.branch` blends with the background in all colorschemes except `lunar`.

This could probably be avoided by applying a highlight group by default. I'm not sure I understand why `SLGitIcon` was "reserved" for the `lunar` colorscheme, with its color enforced [outside of the colorscheme](https://github.com/LunarVim/LunarVim/blob/732fd6fc2b840eb5ecb5f7ba5931363d3c3dafab/lua/lvim/core/autocmds.lua#L100-L121). It feels like something that colorschemes could easily override, but instead users now need to [apply that change manually](https://github.com/ChristianChiarulli/lvim/blob/b0f587fe3115a6a8a190ffdf6dac65dce24b5297/lua/user/lualine.lua#L1-L19).

Is somebody able to provide some context?

---

colorscheme everforest
<img width="114" alt="Screenshot 2023-02-19 at 11 55 11" src="https://user-images.githubusercontent.com/3299086/219943968-48aa41f9-4289-4cac-a961-a0a56da68725.png">

colorscheme lunar (default)
<img width="113" alt="Screenshot 2023-02-19 at 11 55 31" src="https://user-images.githubusercontent.com/3299086/219943969-93f2e0cd-37c7-4baa-9799-134e8c894705.png">

Cross-referencing https://github.com/sainnhe/everforest/issues/115

### LunarVim version

master-f43cc8e2

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-1001+gcbd4480f9

### Operating system/version

macOS 13.1

### Steps to reproduce

```lua
lvim.colorscheme = 'tokyonight
```

### Screenshots

<img width="1038" alt="Screenshot 2023-02-19 at 12 21 22" src="https://user-images.githubusercontent.com/3299086/219944775-398a3f4a-4b63-4540-9a73-954182297f4a.png">

**Comment by LostNeophyte** [comment]
![image](https://user-images.githubusercontent.com/110467150/219946762-31791951-5eec-4cd3-9763-976f608125a5.png)
can't reproduce

**Comment by antoineco** [comment]
OK let's try this one more time:

```console
$ rm -rfv ~/.local/share/lunarvim ~/.local/share/nvim ~/.cache/lvim ~/.cache/nvim ~/.local/bin/lvim ~/.config/lvim
```

```console
$ bash <(curl https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
y
y
y
--------------------------------------------------------------------------------
Cloning LunarVim configuration
Cloning into '~/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 16913, done.
remote: Counting objects: 100% (803/803), done.
remote: Compressing objects: 100% (312/312), done.
remote: Total 16913 (delta 516), reused 638 (delta 398), pack-reused 16110
Receiving objects: 100% (16913/16913), 13.80 MiB | 17.34 MiB/s, done.
Resolving deltas: 100% (10622/10622), done.
--------------------------------------------------------------------------------
Installing LunarVim shim
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: ~/.local/bin/lvim
Preparing Lazy setup
Initializing first time setupLazy setup complete
--------------------------------------------------------------------------------
Verifying core plugins
Verification complete!
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Thank you for installing LunarVim!!
You can start it by running: ~/.local/bin/lvim
Do not forget to use a font with glyphs (icons) support [https://github.com/ryanoasis/nerd-fonts]
```

```console
$ echo 'lvim.colorscheme = "tokyonight"' >~/.config/lvim/config.lua 
```

```console
$ git init ~/.config/lvim
Initialized empty Git repository in ~/.config/lvim/.git/
```

```console
$ cd ~/.config/lvim && git add config.lua && git commit -m test && cd -
 1 file changed, 1 insertion(+)
 create mode 100644 config.lua
```

```console
$ lvim
```

<img width="1350" alt="Screenshot 2023-02-19 at 13 40 50" src="https://user-images.githubusercontent.com/3299086/219948576-70f04473-3ca9-48d3-853c-9f1145848fcf.png">

<img width="1350" alt="Screenshot 2023-02-19 at 13 44 29" src="https://user-images.githubusercontent.com/3299086/219948771-4664d1b8-48ca-4b7b-86ab-83177ab02884.png">

**Comment by antoineco** [comment]
> can't reproduce
> -- https://github.com/LunarVim/LunarVim/issues/3871#issuecomment-1435970671

On a different system I can't reproduce either:

- Ubuntu 22.04.2 (in WSL2)
- Neovim 0.9.0~ubuntu1+git202302191603-bfe6b4944-333b5866f
- Windows Terminal 1.16.10262.0

![image](https://user-images.githubusercontent.com/3299086/219970684-a957a5d8-ff89-4a7a-a3c9-5397e186ec76.png)

![image](https://user-images.githubusercontent.com/3299086/219970958-ac4be43f-0f93-4e26-a3bb-15552fd68800.png)

It's unlikely to be a Neovim bug because both versions I tried are just [a couple of commits apart](https://github.com/neovim/neovim/compare/bfe6b4944..cbd4480f9).

---

Next, I'm going to investigate whether the issue could be related to:

- The terminal emulator: kitty 0.27.1 vs. Windows Terminal
- The font: Cascadia Code + NerdFont Symbols (fallback) vs. Cascadia Code NerdFont (patched)

**Comment by antoineco** [comment]
Confirmed to be a glitch with the kitty terminal emulator and its font fallback mechanism.

kitty, with font fallback
![image](https://user-images.githubusercontent.com/3299086/220051062-ef8fcb61-9d58-45a6-87b3-b9dcf2d2cead.png)

kitty, with patched font
![image](https://user-images.githubusercontent.com/3299086/220057288-34b97b65-ba85-485b-ba3d-40794c095dec.png)

Terminal.app, with patched font
![image](https://user-images.githubusercontent.com/3299086/220052561-95cf949f-8d44-468b-8e19-f4628253ac4d.png)

Thanks for double checking @LostNeophyte! Closing.
