### ISSUE TITLE
Lazy git won't open when a Terminal instance is also opened

### ISSUE THREAD

**Issue by RizaHKhan** [LunarVim/LunarVim#3872]
### Problem description

From within Lunarvim:

1. Open lazy git (`<leader>gg`) Opens fine
2. Open Toggleterm (`<ctrl+t`) Opens fine
3. Open lazy git... opens Toggleterm instead

### LunarVim version

master-732fd6fc

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev793+g7126d9b8c

### Operating system/version

Pop!_OS 22.04 LTS

**Comment by cpea2506** [comment]
Sorry for the inconvenience. The problem comes from `ToggleTerm` plugin itself. There was a fix in its [latest commit](<https://github.com/akinsho/toggleterm.nvim/commit/a5638b2206c3930a16a24e5c184dddd572f8cd34>). Please wait for next `plugin version bump` PR.

**Comment by cpea2506** [comment]
Fixed in https://github.com/LunarVim/LunarVim/commit/d682ae0657a287be05e167ca367de4121ae666b2
