### ISSUE TITLE
Splits equalize doesn't work all the time

### ISSUE THREAD

**Issue by xbladesub** [LunarVim/LunarVim#3878]
I have an issue with splits equalizing with `<C-w>=`. It works randomly and I can't figure out why does it happen. So sometimes it works and sometimes it doesn't (most of the time it doesn't work)

**Comment by LostNeophyte** [comment]
Does it happen with an empty config?
Do you know how to reproduce it?

**Comment by xbladesub** [comment]
the problem was in `set winfixwidth`
