### ISSUE TITLE
Astrojs LSP is not working

### ISSUE THREAD

**Issue by Burnsedia** [LunarVim/LunarVim#3883]
### Problem description

I am unable to get astrojs lsp to load

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

0.8.8

### Operating system/version

Linux

### Affected language servers

astro

### Actual behavior

LSP is not detected

### Expected behavior

Syntax highligint for astro componets

### support info

Language client log: /home/overlord/.local/state/nvim/lsp.log
 Detected filetype:   lir
 
 0 client(s) attached to this buffer: 
 
 Configured servers list:

**Comment by LostNeophyte** [comment]
it works on master 
![image](https://user-images.githubusercontent.com/110467150/220841342-a4205498-2d2d-4844-a7d4-4da83f03e778.png)

**Comment by Burnsedia** [comment]
I fixed it, most have been a runtime error, just did the hole reinstall

**Comment by Burnsedia** [comment]
but the Syntax highlighting is not working though but it now is working.

**Comment by LostNeophyte** [comment]
:TSInstall astro

**Comment by Burnsedia** [comment]
I will do that again, Treesiter is detecting the lsp not sytax highlighting  though

**Comment by Burnsedia** [comment]
Ok, it is working now, Just needed a full system update, reinstall neovim,  and Reinstall Lunarvim,  then install all my LSPs.
