### ISSUE TITLE
Copilot gives an error on lvim launch

### ISSUE THREAD

**Issue by mbledkowski** [LunarVim/LunarVim#3884]
### Problem description

I have installed the Copilot, as in LunarVim documentation, but when I am launching lvim i get the following error:
```
Error executing vim.schedule lua callback: .../site/pack/packer/opt/copilot.lua/lua/copilot/client.lua:125: attempt to concatenate a nil value
stack traceback:
        .../site/pack/packer/opt/copilot.lua/lua/copilot/client.lua:125: in function <.../site/pack/packer/opt/copilot.lua/lua/copilot/client.lua:120>
```

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Operating system/version

NixOS 23.05pre456418.d0d55259081 (Stoat) x86_64

**Comment by LostNeophyte** [comment]
copilot is not a core plugin, it should work if you configure it correctly

**Comment by mbledkowski** [comment]
> copilot is not a core plugin, it should work if you configure it correctly

I used the configuration from documentation https://www.lunarvim.org/docs/plugins/extra-plugins#copilotlua-and-copilot-cmp

**Comment by LostNeophyte** [comment]
try the config from master docs, but you'll need to change `dependencies` to `requires` and remove `event`

**Comment by mbledkowski** [comment]
Still getting an error :/
```
Error executing vim.schedule lua callback: ...ite/pack/packer/start/copilot.lua/lua/copilot/client.lua:125: attempt to concatenate a nil value
stack traceback:
        ...ite/pack/packer/start/copilot.lua/lua/copilot/client.lua:125: in function <...ite/pack/packer/start/copilot.lua/lua/copilot/client.lua:120>
```
