### ISSUE TITLE
Which key `z` shows only `=`

### ISSUE THREAD

**Issue by sizhky** [LunarVim/LunarVim#3885]
### Problem description

Press `z` in normal mode and see only `=`

### LunarVim version

master-732fd6fc

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-1001+gcbd4480f9

### Operating system/version

Ubuntu

### Steps to reproduce

Error occuring with default config

### Screenshots

<img width="308" alt="image" src="https://user-images.githubusercontent.com/3656100/220831718-294f1cda-14ea-4cdf-b3ef-d97122213b51.png">

**Comment by LostNeophyte** [comment]
it's not a bug, if you want more options enable plugins in `lvim.builtin.which_key.setup.plugins`, see whichkey's docs for available options
