### ISSUE TITLE
lazygit shortcut keys conflict with terminal shortcut keys

### ISSUE THREAD

**Issue by yjhtry** [LunarVim/LunarVim#3886]
### Problem description

lazygit shortcut keys conflict with terminal shortcut keys
Watch the video below

https://user-images.githubusercontent.com/39440537/220831167-ea7b03ac-9279-43a0-b488-9d666d35d7f5.mp4

lazygit can only be opened using the shortcut key after killing the Suspension terminal

### LunarVim version

732fd6f

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-678+g922075530-dirty

### Operating system/version

MacOs Big Sur 11.1

### Steps to reproduce

1. open Suspension terminal
2. hidden terminal
3. <leader> gg  will open terminal
4. <Ctrl+D> kill terminal
5. <leader> gg can open lazygit

**Comment by cpea2506** [comment]
related #3872

**Comment by yjhtry** [comment]
> 相关#3872

thank you😀

**Comment by cpea2506** [comment]
Hi, the new plugin version bump is now available. Please update `lvim` and let me know if there is any problem. 😄

**Comment by yjhtry** [comment]
> Hi, the new plugin version bump is now available. Please update `lvim` and let me know if there is any problem. 😄

Yes, It's working fine!    Thank you very much
