### ISSUE TITLE
clangd not starting after following instructions to manually register

### ISSUE THREAD

**Issue by NachoPonisio** [LunarVim/LunarVim#3891]
### Problem description

After generating a **clangd.lua** file as stated in the documentation for manually installing the LS, I am not able to get it running.

![image](https://user-images.githubusercontent.com/14790476/221052204-5f125e0e-58a1-4941-ae46-a444b3abd29e.png)

 I checked that the LS is not part of the servers listed to skip automatic configuration. Nevertheless, the **:LspInstall clangd** command fails the same.

![image](https://user-images.githubusercontent.com/14790476/221052716-d35cdcfc-82fb-402e-a6c4-78d7cadfbef3.png)

### LunarVim version

master-d682ae06

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Operating system/version

Ubuntu 22.04.2LTS

### Affected language servers

clangd

### Steps to reproduce

1. Install nvim from deb package, as per these [instructions](https://github.com/neovim/neovim/releases/tag/stable)
2. Install LunarVim
3. Attempt to install clangd throug **:LspInstall clangd**. Notice its failure.
4. Install clangd according to these [instructions](https://clangd.llvm.org/installation) for the latest stable version (15)
5. Create a symlink to clangd
6. Create a ftpfile for clangd.lua with the attached configuration.
7. Open a .cpp file and observe the LSP not starting. 

### Actual behavior

LSP does not start

### Expected behavior

LSP should start

### support info

**:LspInfo**

>  Language client log: /home/nacho/.local/state/nvim/lsp.log
>  Detected filetype:   cpp
>  
>  0 client(s) attached to this buffer: 
>  
>  Other clients that match the filetype: cpp
>  
>  Config: clangd
>  	filetypes:         c, cpp, objc, objcpp, cuda, proto
>  	root directory:    /home/nacho/Documents/dev/cpp/coursera-cs400
>  	cmd:               clangd
>  	cmd is executable: true
>  	autostart:         true
>  	custom handlers:   
>  
>  Configured servers list: clangd

**:LspLog***

> 
> [START][2023-02-23 17:33:29] LSP logging initiated
> [WARN][2023-02-23 17:33:29] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
> [START][2023-02-23 17:46:03] LSP logging initiated
> [WARN][2023-02-23 17:46:03] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
> [WARN][2023-02-23 17:49:36] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
> [WARN][2023-02-23 17:52:44] .../lua/vim/lsp.lua:1602	"buf_attach_client called on unloaded buffer (id: 4): "
> [START][2023-02-23 19:58:47] LSP logging initiated
> [WARN][2023-02-23 19:58:47] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
> [START][2023-02-23 19:59:55] LSP logging initiated
> [WARN][2023-02-23 19:59:55] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
> [START][2023-02-23 20:05:33] LSP logging initiated
> [WARN][2023-02-23 20:05:33] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
> [START][2023-02-23 20:05:48] LSP logging initiated
> [WARN][2023-02-23 20:05:48] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"

**Comment by LostNeophyte** [comment]
Where in the documentation does it say to make a clangd.lua file?

**Comment by LostNeophyte** [comment]
Where in the documentation does it say to make a clangd.lua file? (It should be ~/.config/lvim/ftplugin/c.lua), but since you're using the defaults you don't need to configure anything, it should just work

**Comment by NachoPonisio** [comment]
Thank you for your response. Yes, I made a mistake and created that clangd.lua file. Like you said, there's already a c.lua file with the exact same config under ftpplugin, but still, the LSP is not being connected to any buffer. 

![image](https://user-images.githubusercontent.com/14790476/221170583-bc6a7d00-6561-4c78-921a-5a2bd885342e.png)

I do see clangd being recognized by, for instance, VSCode, for the same projects, working as intended.

![image](https://user-images.githubusercontent.com/14790476/221171510-ed67601b-80da-4aa2-9ab7-30819fa29f2e.png)

**Comment by LostNeophyte** [comment]
are you on the discord? it would be easier to help you there 

lunarvim channel of https://discord.gg/Xb9B4Ny
