### ISSUE TITLE
Error while installing LunarVim on Windows

### ISSUE THREAD

**Issue by WavingCatDevs** [LunarVim/LunarVim#3894]
### Problem description

I got this issue by trying the windows release install script on the website.

### LunarVim version

N/A

### Neovim version (>= 0.8.0)

0.8.2

### Operating system/version

Windows 10

### Steps to reproduce

$LV_BRANCH='release-1.2/neovim-0.8'; Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression

### Screenshots

![Capture](https://user-images.githubusercontent.com/69034430/221215367-558738dc-8b1f-4e16-9382-121137017aa5.PNG)

**Comment by LostNeophyte** [comment]
![image](https://user-images.githubusercontent.com/110467150/221217488-6a8502e6-03ec-45da-b171-af340b3b94e5.png)
