### ISSUE TITLE
Remap requiring I source my config.lua

### ISSUE THREAD

**Issue by rpmeira** [LunarVim/LunarVim#3895]
### Problem description

Recently, I discovered a little tool that helps parse bibtex files.
In their github repo they have instructions on how to integrate the tool with neovim:

https://github.com/msprev/fzf-bibtex#vimneovim-integration

I've just copied the code and paste it inside a `vim.cmd( [[ ]] )` in my `~/.config/lvim/config.lua`.
The remap works fine and I get the desired result, but only after I source my config.lua every time I enter LunaVim.
Is there a way to make this remap load without having to source my config.lua file?

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev

### Operating system/version

wsl2 (Ubuntu 22.04) on Windows 10

**Comment by LostNeophyte** [comment]
leader c is bound to closing the buffer by default, unmap it or just do the mappings with whichkey

**Comment by rpmeira** [comment]
Thanks for the reply.

But I don't know if that is the problem here. I've tried with different keys, and regardless of the key I choose for the remapping, I still need to source my config.lua every time I open LunarVim. 

I've tried to do the mapping with whichkey:

````
lvim.builtin.which_key.mappings["M"] = {
  ":call fzf#run({'source': 'bibtex-ls', 'sink*': function('<sid>bibtex_markdown_sink'), 'down': '40%', 'options': '--ansi --layout=reverse-list --multi'})<CR>",
  "Cite Markdown"
}
````

 but it throws an error about the `<sid>` part inside `fzf#run()`:

![image](https://user-images.githubusercontent.com/64609486/221375819-f8c51aa6-02b7-4aa2-a692-1343f4810427.png)

I've also tried without the `<sid>` part:
````
lvim.builtin.which_key.mappings["M"] = {
  ":call fzf#run({'source': 'bibtex-ls', 'sink*': bibtex_markdown_sink(), 'down': '40%', 'options': '--ansi --layout=reverse-list --multi'})<CR>",
  "Cite Markdown"
}
````

But it doesn't recognise the `bibtex_markdown_sink()` function defined before.

![image](https://user-images.githubusercontent.com/64609486/221375861-8996eb6c-e99a-4a14-bfe7-10273541b5fb.png)

How can I translate this to use with whichkey?

````
nnoremap <silent> <leader>c :call fzf#run({
                        \ 'source': 'bibtex-ls',
                        \ 'sink*': function('<sid>bibtex_cite_sink'),
                        \ 'up': '40%',
                        \ 'options': '--ansi --layout=reverse-list --multi --prompt "Cite> "'})<CR>
````
