### ISSUE TITLE
start lvim failed with error module 'cmp.config.window' not found

### ISSUE THREAD

**Issue by OgawaMuko** [LunarVim/LunarVim#3899]
### Problem description

failed to open lvim with error:
Error detected while processing C:\Users\OgawaMuko\AppData\Roaming\lunarvim\lvim\init.lua:
E5113: Error while calling lua chunk: ...Muko\AppData\Roaming\lunarvim\lvim/lua/lvim/core/cmp.lua:130: module 'cmp.config.window' not found:

        no field package.preload['cmp.config.window']
        no file '.\cmp\config\window.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\cmp\config\window.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\cmp\config\window\init.lua'
        no file '.\cmp\config\window.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\cmp\config\window.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'
        no file '.\cmp.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\cmp.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'

### LunarVim version

master

### Neovim version (>= 0.8.0)

v0.8.3

### Operating system/version

windows 10

**Comment by LostNeophyte** [comment]
make sure you're on latest master

**Comment by OgawaMuko** [comment]
I'm on the latest master

**Comment by LostNeophyte** [comment]
what if you ignore the errors (press enter) and run `:Lazy sync`

**Comment by OgawaMuko** [comment]
I cannot run it with error: Not an editor command: Lazy sync

**Comment by LostNeophyte** [comment]
remove `C:\Users\OgawaMuko\AppData\Roaming\lunarvim\site` and restart lvim

**Comment by LostNeophyte** [comment]
@kobzar the github action will automatically close inactive issues after 50 days, no need to do it manually https://github.com/LunarVim/LunarVim/blob/master/.github/workflows/close-inactive-bot.yml

**Comment by kobzar** [comment]
![image](https://user-images.githubusercontent.com/1912842/234900351-b5fb3187-a185-4e72-a82d-58bf0f10712d.png)

but post wasn't closed.

**Comment by LostNeophyte** [comment]
it will be stale first and after being stale for 14 days it will be closed, my bad

**Comment by little-yzp** [comment]
So how to solve this problem in the end.
