### ISSUE TITLE
`<leader>` or `<g>` Previewer shows too slow

### ISSUE THREAD

**Issue by devgony** [LunarVim/LunarVim#3900]
## Steps to reproduce
1. Right after upgrading LunarVim from `1.1.0` to `1.2.0`
2. Whenever pressing `<leader>` or `<g>`, the shortcut previewer shows too slow. it takes like 3 seconds

## How to solve?
Is there any way to speed this up with minimizing design option?

### LunarVim version

1.2.0

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Operating system/version

Ubuntu 22.04

**Comment by GuangDai** [comment]
This is not a bug probably. But I don't find an option to configure it, because I am new to lvim :).

In doom-emacs, it also requires 3s to show which-key menu.

**Comment by devgony** [comment]
@GuangDai But i took like 0.1s before upgrading to lvim 1.2.0

**Comment by devgony** [comment]
@GuangDai Thank you so much! it became blazingly fast!

**Comment by vito-chl** [comment]
I found the last version can not see previewer when i press <g>

**Comment by poloxue** [comment]
This can be set by `vim.opt.timeoutlen = 500`. I guess it's to avoid displaying the menu when you type very fast.
