### ISSUE TITLE
Allow choosing default formatter per file type

### ISSUE THREAD

**Issue by gipo355** [LunarVim/LunarVim#3901]
### Feature Description

- First example: Typescript.
Having both eslint, prettier and tsserver active, i'd like to specify which default formatter is used on save and `<leader>lf`.

- Second example: Astro files.
Similar to the above, eslint + astro lsp i'd like to choose eslint as default.

- third example: markdown files.
Multiple formatters are available like prettier, grammarly etc...

Is there a way to introduce a config options akin to `lvim.builtin.lsp.default_formatters = { javascript = 'eslint' }` or something similar, preserving current behavior as default if not used?

In Vscode it's possible to specify which server performs the format on save per filetype.

Eslint in particular is messy, as per their documentation at [eslint](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#eslint) it's a completely different command `:EslintFixAll`

this could be useful for things like markdown too where the language servers can become numerous

### Describe the alternatives you have considered

At the moment, I implemented it with my own function (and disabling format on save globally):
```lua
vim.api.nvim_create_autocmd("BufWritePre", {
    pattern = "*",
    callback = function()
        if vim.bo.filetype == "typescript" or vim.bo.filetype == "javascript" or vim.bo.filetype == "javascriptreact" or
            vim.bo.filetype == "typescriptreact"
        then
            vim.cmd("EslintFixAll")
            return
        else
            require("lvim.lsp.utils").format { timeout_ms = 2000, filter = require("lvim.lsp.utils").format_filter }
            return
        end
    end,
})
```

## what is currently used
grepping the default keybindings, it seems like the default command for autoformat is:
```lua
function M.enable_format_on_save()
  local opts = get_format_on_save_opts()
  vim.api.nvim_create_augroup("lsp_format_on_save", {})
  vim.api.nvim_create_autocmd("BufWritePre", {
    group = "lsp_format_on_save",
    pattern = opts.pattern,
    callback = function()
      require("lvim.lsp.utils").format { timeout_ms = opts.timeout, filter = opts.filter }
    end,
  })
  Log:debug "enabled format-on-save"
end
```
and for the which key
```lua
      l = {
        name = "LSP",
        f = { "<cmd>lua require('lvim.lsp.utils').format()<cr>", "Format" },
```

**Comment by cpea2506** [comment]
The formatter was decided by using `null-ls`. There is a section on Lunarvim docs that's helpful
https://www.lunarvim.org/docs/languages#lintingformatting

**Comment by kobzar** [comment]
@gipo355 the question is resolved?

**Comment by kobzar** [comment]
Closed as long time without author activity.
