### ISSUE TITLE
Issue with colorsceme plugin

### ISSUE THREAD

**Issue by palandovalex** [LunarVim/LunarVim#3902]
### Problem description

I installed plugin https://github.com/Abstract-IDE/Abstract-cs
I try add to config:
`lvim.colorscheme = "abscs"`
When i open lvim to edit file, theme is not active. But i can change it manualy.

But when i open dashboard - theme changes to "default", and when dashboard is active - using abscs theme is imposable.

### LunarVim version

a7e7f286

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wno-unused-result -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=auto -fstack-protector-strong -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -DNVIM_UNIBI_HAS_VAR_FROM -I/usr/include/luajit-2.1 -I/usr/include -I/build/neovim-jFZHAM/neovim-0.9.0~ubuntu1+git202302251603-f0f27e9ae-333b5866f/.deps/usr/include -I/build/neovim-jFZHAM/neovim-0.9.0~ubuntu1+git202302251603-f0f27e9ae-333b5866f/.deps/usr/include -I/build/neovim-jFZHAM/neovim-0.9.0~ubuntu1+git202302251603-f0f27e9ae-333b5866f/.deps/usr/include -I/build/neovim-jFZHAM/neovim-0.9.0~ubuntu1+git202302251603-f0f27e9ae-333b5866f/.deps/usr/include -I/build/neovim-jFZHAM/neovim-0.9.0~ubuntu1+git202302251603-f0f27e9ae-333b5866f/build/src/nvim/auto -I/build/neovim-jFZHAM/neovim-0.9.0~ubuntu1+git202302251603-f0f27e9ae-333b5866f/build/include -I/build/neovim-jFZHAM/neovim-0.9.0~ubuntu1+git202302251603-f0f27e9ae-333b5866f/build/cmake.config -I/build/neovim-jFZHAM/neovim-0.9.0~ubuntu1+git202302251603-f0f27e9ae-333b5866f/src -I/build/neovim-jFZHAM/neovim-0.9.0~ubuntu1+git202302251603-f0f27e9ae-333b5866f/.deps/usr/include -I/build/neovim-jFZHAM/neovim-0.9.0~ubuntu1+git202302251603-f0f27e9ae-333b5866f/.deps/usr/include -I/build/neovim-jFZHAM/neovim-0.9.0~ubuntu1+git202302251603-f0f27e9ae-333b5866f/.deps/usr/include              общесистемный файл vimrc: "$VIM/sysinit.vim"           значение $VIM по умолчанию: "/usr/share/nvim"  Run :checkhealth for more info

### Operating system/version

ubuntu22.04.1

### Steps to reproduce

add string "Abstract-IDE/Abstract-cs" to plugins list:
```
lvim.plugins = {
  {
    "Abstract-IDE/Abstract-cs",
  },
}
```
Then set this theme as default:

`lvim.colorscheme = "abscs"`

open lvim by commands "lvim <filename>"  or  "lvim"

**Comment by cpea2506** [comment]
I can't reproduce your situation

<img width="1296" alt="Screenshot 2023-02-28 at 08 01 05" src="https://user-images.githubusercontent.com/42694704/221724914-07676264-dff2-4038-8de0-e8f74a531847.png">
<img width="1296" alt="Screenshot 2023-02-28 at 08 01 14" src="https://user-images.githubusercontent.com/42694704/221724935-4baa6dd1-b04e-44fc-a79f-3816b8abe38b.png">

**Comment by palandovalex** [comment]
Hm... im sorry, colorscheme works, but when ir set, and i check current colorscheme whith command 
:colo 
it shows default. It is definatly problem with plugin, not with lvim.
