### ISSUE TITLE
Terminal Display Issue.

### ISSUE THREAD

**Issue by akashdiphazra** [LunarVim/LunarVim#3905]
### Problem description

Terminal text shifts or disappears after opening the file explorer.

![Screencast from 2023-02-28 21-00-54](https://user-images.githubusercontent.com/61003681/221902009-4da2e06a-6bc4-4c99-ab08-dd8445b24a9f.gif)

### LunarVim version

release-1.2

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-1059+g2c9fbe34b

### Operating system/version

Ubuntu 22.10

**Comment by kobzar** [comment]
I can confirm this one. But problem not in terminal. 
Problem with file explorer. Some time when i close the last buffer the explorer take half of screen size.

**Comment by akashdiphazra** [comment]
@kobzar  issue might be in the toggle terminal because Lunarvim uses toggleterm by default.

**Comment by akashdiphazra** [comment]
This issue is now ported to https://github.com/akinsho/toggleterm.nvim/issues/417

**Comment by akashdiphazra** [comment]
I have tried with by closing the last buffer but text doesn't shift. Issue might be in toggleterm because lunarvim uses toggleterm by default. check issue --> https://github.com/akinsho/toggleterm.nvim/issues/417
