### ISSUE TITLE
perlnavigator not giving any lsp completion

### ISSUE THREAD

**Issue by amonull** [LunarVim/LunarVim#3907]
### Problem description

perlnavigator which was installed through Mason does not give any lsp completions.
checking `:LspInfo` i can see perlnavigator is loaded but i am not getting any lsp completion
![image](https://user-images.githubusercontent.com/90932550/221913077-bb9baece-5464-4c3f-8232-e1fb47f84e04.png)
this is only an issue with perlnavigator and not any other lsps 

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

v0.8.3

### Operating system/version

void linux

### Affected language servers

perlnavigator

### Steps to reproduce

1. open perl file using `lvim perlFIle.pl`
2. receive no lsp completion when starting to write

### Actual behavior

when starting to write in perl theres no lsp completion being given but errors are reported from perlnavigator.

Errors:
![image](https://user-images.githubusercontent.com/90932550/221914747-630bb0bc-3dd8-48d5-b7c7-7e6d453caca5.png)

no lsp completion:
![image](https://user-images.githubusercontent.com/90932550/221914845-3fc45528-710f-4b36-b0d3-c19c4c700279.png)

### Expected behavior

when starting to write perl lsp giving completion like in other languages with configured lsps

example language python:
![image](https://user-images.githubusercontent.com/90932550/221915135-c7608cd3-29b7-4f29-b123-14cbc2919f54.png)

### support info

# :LspInfo
![image](https://user-images.githubusercontent.com/90932550/221915373-afa0e1b8-36f0-4e70-939c-ec28e5cc9322.png)

# :LvimInfo
![image](https://user-images.githubusercontent.com/90932550/221915504-e2f418a6-7660-4d8f-b2e1-2ed09ca310c0.png)

### logs

```console
[START][2023-02-28 15:32:04] LSP logging initiated
[WARN][2023-02-28 15:32:04] ...lsp/handlers.lua:113	"The language server perlnavigator triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2023-02-28 15:35:16] LSP logging initiated
[WARN][2023-02-28 15:35:16] ...lsp/handlers.lua:113	"The language server perlnavigator triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2023-02-28 15:37:13] LSP logging initiated
[WARN][2023-02-28 15:37:13] ...lsp/handlers.lua:113	"The language server perlnavigator triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-02-28 15:40:46] ...lsp/handlers.lua:113	"The language server perlnavigator triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2023-02-28 15:44:49] LSP logging initiated
[WARN][2023-02-28 15:44:49] ...lsp/handlers.lua:113	"The language server perlnavigator triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2023-02-28 15:53:12] LSP logging initiated
[WARN][2023-02-28 15:53:12] ...lsp/handlers.lua:113	"The language server perlnavigator triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2023-02-28 15:55:54] LSP logging initiated
[WARN][2023-02-28 15:55:54] ...lsp/handlers.lua:113	"The language server perlnavigator triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2023-02-28 15:56:39] LSP logging initiated
[WARN][2023-02-28 15:56:39] ...lsp/handlers.lua:113	"The language server perlnavigator triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2023-02-28 16:07:28] LSP logging initiated
[WARN][2023-02-28 16:07:28] ...lsp/handlers.lua:113	"The language server perlnavigator triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2023-02-28 16:08:36] LSP logging initiated
[WARN][2023-02-28 16:08:36] ...lsp/handlers.lua:113	"The language server perlnavigator triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

**Comment by brneor** [comment]
Oh! Finally a perl buddy! Do you have your Perl installation on an unorthodox path? I had a similar issue before and creating a `perlnavigator.json` file inside `~/.config/lvim/lsp-settings/` solved the issue for me.

I'm currently using
```json
{
  "perlnavigator": {
    "perlPath": "/home/brenoperes/development/perl/languageserver.sh",
    "perlcriticProfile": "/cfg/perlcriticrc"
  }
}
```

Where `languageserver.sh` is just a shell script to run a container, but it could be the path to your Perl binary.

**Comment by amonull** [comment]
thanks for the reply
my choice of os is void linux which uses xbps as its package manager and my perl was installed through that with the path to perl being `/usr/bin/perl`
i tried putting `perlnavigator.json` inside `~/.config/lvim/lsp-settings` with perl path changed to my perl path and the issue is still there.

changed `perlnavigator.json`
```
{
  "perlnavigator": {
    "perlPath": "/usr/bin/perl",
    "perlcriticProfile": "/cfg/perlcriticrc"
  }
}
```

**Comment by amonull** [comment]
[perl navigator was working fine all along it was just my understanding that caused issues.](https://github.com/bscan/PerlNavigator/issues/66)
