### ISSUE TITLE
LspInstall terraformls fails due to missing file

### ISSUE THREAD

**Issue by jinnko** [LunarVim/LunarVim#3908]
### Problem description

Not sure whether filing here is correct.  If not please point me in the right direction.

When attempting to install terraform with `:LspInstall terraformls` the following error occurs:

```
Failed (1)               
  ◍ terraform-ls
  Downloading file "https://github.com/hashicorp/terraform-ls/releases/download/v0.30.3/terraform-ls_0.30.3_linux_amd64.zip"...
    ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:121: ...er/start/mason.nvim/lua/mason-core/managers/std/init.lua:52: Failed to download file "https://github.com/hashicorp/terraform-ls/releases/download/v0.30.3/terraform-ls_0.30.3_linux_amd64.zip".
  spawn: wget failed with exit code 8 and signal 0.
```

A couple of weeks ago upstream [changed their release policy](https://github.com/hashicorp/terraform-ls/releases/tag/v0.30.2) with the v0.30.2 release.

> v0.30.2
@[hc-github-team-es-release-engineering](https://github.com/hc-github-team-es-release-engineering) hc-github-team-es-release-engineering released this 15 Feb 17:13
v0.30.2
14251ad
>
> NOTES / BREAKING CHANGES:
>
>    We have changed our release process: all assets continue to be available from the [HashiCorp Releases site](https://releases.hashicorp.com/terraform-ls) and/or via the [Releases API](https://releases.hashicorp.com/docs/api/v1/), not as GitHub Release assets anymore.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Operating system/version

ArchLinux

### Affected language servers

terraformls

### Steps to reproduce

1. `:LspInstall terraformls`

### Actual behavior

Fails to download because releases are no longer published to Github.

### Expected behavior

Successful installation of terraformls

### support info

```console
# :LspInfo
se [q] or [Esc] to quit the window                                                                                                                                                     

Language client log: /home/jinn/.local/state/nvim/lsp.log
Detected filetype:   alpha

0 client(s) attached to this buffer:

Configured servers list:
```

```console
# :LvimInfo
    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                alpha
* bufnr:                   1
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

**Comment by LostNeophyte** [comment]
it will work on master, not sure what to do with 1.2

**Comment by 0xAlighieri** [comment]
Seeing the same issue on MacOS Ventura, but was able to install on EndeavourOS (Arch).

**Comment by Gabryel8818** [comment]
same issue on EndeavourOS (Arch)

**Comment by jmborsani** [comment]
From what I understand, releases are now available for download through the website https://releases.hashicorp.com/terraform-ls, no longer through Github Releases.

Please see the breaking change notes:
https://github.com/hashicorp/terraform-ls/releases/tag/v0.30.2

How do I point to fetch from this new address?

**Comment by djcurill** [comment]
@jmborsani Thanks for sharing that link. I had a look, and applied a `:LvimSyncCorePlugins` to fetch any updates. That did not seem to resolve the issue.

**Comment by mkarbo** [comment]
@djcurill did you fix it?

**Comment by LostNeophyte** [comment]
@mkarbo it should work if you're using lvim 1.3
