### ISSUE TITLE
install lvim in windown 11

### ISSUE THREAD

**Issue by srayleighdk** [LunarVim/LunarVim#3917]
### Problem description

error when i install lvim

### LunarVim version

Neovim 0.8.0 

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-912+gfe1w6b82f

### Operating system/version

window 11

### Screenshots

![image](https://user-images.githubusercontent.com/40032226/222761416-7b4a6ad9-2589-40fc-b907-7220fb597d78.png)

**Comment by brneor** [comment]
Is this a Powershell v7+? Doesn't look like a Powershell v7+. It is a requirement for LunarVim.
