### ISSUE TITLE
feat: Dart lsp integration

### ISSUE THREAD

**Issue by jarrodcolburn** [LunarVim/LunarVim#3919]
### Feature Description

Add language support for the Dart language https://dart.dev/

### Describe the alternatives you have considered

Adding the following line to the `config.lua` enables dart support.*
```lua
require('lspconfig').dartls.setup{}
```
*assuming `dart` is installed/available in path

### Support information

Dart provides it's own language server.

**Comment by tom-010** [comment]
Worked out the box. Thank you. Had to search a lot to find that!

**Comment by jarrodcolburn** [comment]
@tom-010 seems like a satisfied dart+lunarvim customer. 
If I create a PR is it as simple as hoisting `lspconfig` into the `lvim.lsp` object?

**Comment by tomiokadasilva** [comment]
Thanks! I spen't the last hour searching for this.
