### ISSUE TITLE
Live grep can't show non utf-8 content correctly

### ISSUE THREAD

**Issue by brneor** [LunarVim/LunarVim#3920]
### Problem description

1. Open a file with some accented characters with `latin1` encoding.
2. Press `<leader> s t`
3. Search for a term in this file
4. Preview can't show accented characters correctly

Not sure if this is LunarVim's or Telescope's problem, but reporting here first because I couldn't test with Telescope on nvim directly.

### LunarVim version

master-7c3849ee

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-869+g964ae205a-dirty

### Operating system/version

Fedora 37

### Screenshots

![image](https://user-images.githubusercontent.com/5962898/222821559-755b4f3b-6c65-448c-b0d8-94b745849e92.png)

**Comment by LostNeophyte** [comment]
I can reproduce using the default telescope config, seems like a telescope issue
![image](https://user-images.githubusercontent.com/110467150/222982529-c7900d7b-fc9f-4b15-90ab-9cd6aeda0a8f.png)
contents of the file: `hello this is a test ÀÀÀØØØ©©©`

**Comment by brneor** [comment]
@LostNeophyte thanks, I'll report it in Telescope's project.
