### ISSUE TITLE
Cannot get copilot-lua working

### ISSUE THREAD

**Issue by Jacfger** [LunarVim/LunarVim#3928]
### Problem description

After installing Copilot.lua I do not see any suggestion from Copilot. Also, :cmpstatus shows copilot as unknown sources.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

PopOS 22.04LTS

### Steps to reproduce

1. fresh install ( But I do have previous installed LunarVim and uninstalled it, couldn't get copilot to work as well )
2. Install copilot.lua by appending `core_plugins` in `lua/lvim/plugins.lua`.

```lua
lvim.builtin.cmp.formatting.source_names["copilot"] = "(Copilot)"
table.insert(lvim.builtin.cmp.sources, 1, { name = "copilot" })
```

**Comment by Jacfger** [comment]
> > Install copilot.lua by appending core_plugins in lua/lvim/plugins.lua.
> 
> don't edit files in ~/.local/share/lunarvim

Then what does it means by
```
-- Can not be placed into the config method of the plugins.
lvim.builtin.cmp.formatting.source_names["copilot"] = "(Copilot)"
table.insert(lvim.builtin.cmp.sources, 1, { name = "copilot" })
```
This is in the documentation page of Copilot

**Comment by Yumshot** [comment]
as far as I was aware, you just drop a folder called pack within your nvim directory. and call :Copilot from the line to setup.

**Comment by Jacfger** [comment]
> as far as I was aware, you just drop a folder called pack within your nvim directory. and call :Copilot from the line to setup.

what's teh pack folder

**Comment by Jacfger** [comment]
Putting all the configuration in the configuration files actually works. Apparently `-- Can not be placed into the config method of the plugins.` means don't put the following lines to the list of the plugins. It doesn't mean to not put those line in the configuration file.

**Comment by LostNeophyte** [comment]
yes,  "-- Can not be placed into the config method of the plugins" means that it can't be placed in the `config` function in the lvim.plugins table

**Comment by Jacfger** [comment]
> yes, "-- Can not be placed into the config method of the plugins" means that it can't be placed in the `config` function in the lvim.plugins table

Right... Maybe it's just me, I found the sentence confuses me more than if it didn't say anything at all. It could be me not familiar with lua and the terminology.
