### ISSUE TITLE
wrong bash highlighting

### ISSUE THREAD

**Issue by palandovalex** [LunarVim/LunarVim#3929]
### Problem description

Just see this code fragment:

![Снимок экрана от 2023-03-07 18-31-10](https://user-images.githubusercontent.com/75374436/223469536-c6797d7b-cefd-496d-8422-cdb27f69e261.png)

### LunarVim version

master-9f1f9831

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev  

### Operating system/version

Linux mint  21.04.1, kernel - 5.19.0-35-generic

### Affected language servers

bash

### Steps to reproduce

use such bash code fragment, and you will see it

```bash
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
```

### Actual behavior

syntax highlighting breaks down on the case language construct

### Expected behavior

normal highlighting, NOT WORSE THAN WITH pure neovim!

### support info

 Language client log: /home/lexsilentium/.local/state/nvim/lsp.log
 Detected filetype:   sh
 
 1 client(s) attached to this buffer: 
 
 Client: bashls (id: 1, bufnr: [1])
 	filetypes:       sh
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             bash-language-server start
 
 Configured servers list: bashls

**Comment by LostNeophyte** [comment]
that's a nvim-treesitter's or bash treesitter parser's bug, open an issue there instead
it doesn't like something on line three
![image](https://user-images.githubusercontent.com/110467150/223484068-e3d791ed-e21a-4900-a913-a8c43eae7029.png)
