### ISSUE TITLE
Can't install plugin vim-tmux-navigator

### ISSUE THREAD

**Issue by morenohernan** [LunarVim/LunarVim#3931]
Hi, taking Lunravim latest build and tmux.  

% lvim --version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3

I want to install and use https://github.com/christoomey/vim-tmux-navigator in Lunarvim. 

After installing the plugin in config.lua
<img width="566" alt="image" src="https://user-images.githubusercontent.com/700619/223558578-b5814518-7678-4c60-9680-70a3e12b3421.png">

Then when installing <leader>  + p + install  , it looks like installed but .. it is not working
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/700619/223559488-acee9404-c5b8-4469-ab70-ca36baccabdd.png">

The plugin is not working with LunarVim, but it works with nvim. Is there anything that I am missing?

**Comment by kobzar** [comment]
Did you run after install the plugin
```
:PackerCompile
```
?
Check Lvim configuration for the same hotkeys. And try to disable it if you need
```
lvim.keys.normal_mode["<C-h>"] = false
  lvim.keys.normal_mode["<C-j>"] = false
  lvim.keys.normal_mode["<C-k>"] = false
  lvim.keys.normal_mode["<C-l>"] = false
```

**Comment by kobzar** [comment]
Close as long inactive time by author.
Please reopen it if problem is still actual.
