### ISSUE TITLE
Most Color Schemes Don't Work

### ISSUE THREAD

**Issue by LSleutsky** [LunarVim/LunarVim#3932]
### Problem description

I'm using LunarVim on Arch Linux (_latest zen kernel_), and like 90% of the different color scheme packages I install, simply do not work. They install properly, without error, and I can run a reload and/or sync and/or clean also with no errors, when I add the colorscheme name to the `lvim.colorscheme` option, and go through the reloading/syncing steps, I'll go and reload LunarVim, and I see a color scheme loading, and after a couple seconds, it auto-reverts back to some kind of default scheme, but it's not always the `lunar` theme (_which seems to be the default on my end_).

It's almost like its loading the scheme, but then reverting back to some kind of default scheme, of which the colors are all essentially the same.

I'm adding the different schemes this way:

```lua
lvim.colorscheme = "onedark"

...

lvim.plugins = {
  {
    'navarasu/onedark.nvim',
    config = function()
      require('onedark').setup({
        style = 'deep'
      })
      require('onedark').load()
    end
  },
}
```

I don't really know how else to describe the issue, as there are no error logs to add or anything. The color schemes I am installing just do not persist. The only ones that work seem to be the only ones that come pre-installed with LunarVim.

Is there something I'm doing wrong...?

**EDIT**: The color scheme can be previewed correctly when using the `Change Colorscheme` option by cycling through them all, but in an actual file, it does not work.

### LunarVim version

master-9f1f9831

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-1166+g06aed7c17

### Operating system/version

Arch Linux x86_64 | 6.2.2-zen1-1-zen

### Steps to reproduce

1. Install a color scheme of choice.
2. Try to load and use color scheme.

### Screenshots

The color scheme shows the correct output in the preview window, but in an actual live file, it craps out.

![color-schemes](https://user-images.githubusercontent.com/7631797/223712519-26785f6e-cec5-4d51-8965-fba9af945beb.png)

**Comment by cpea2506** [comment]
I can't reproduce your issue. From what I have seen, you do not have `lua tree-sitter` installed, which most theme recommended.
```vim
:TSInstall lua
```

**Comment by LSleutsky** [comment]
> I can't reproduce your issue. From what I have seen, you do not have `lua tree-sitter` installed, which most theme recommended.
> 
> ```viml
> :TSInstall lua
> ```

Sorry, not sure where you're able to see that from in the screenshot I posted, but I do indeed have `lua` treesitter highlighting installed.

I'm facing this issue with 95% of color schemes, if not more. The ones I can confirm working are `onedarker` and `tokyonight`. The rest show the color scheme highlights for a second or 2, then revert to some default, which isn't even an actual default LunarVim color scheme.

Very odd stuff.

**Comment by LSleutsky** [comment]
What's even weirder than the above, is when I save a file, like let's say the main `config.lua` file, either with the pre-installed `Control - S`, or just by `:w`, after the file saves (_whether or not their were edits or not_), the color scheme becomes enabled.

After restarting LunarVim, same issue again - color scheme shows for a couple seconds, then goes rogue. What the hell...!?

**Comment by pieroluha** [comment]
This happens to me as well. PopOS. Lvim Nightly. Gruvbox plug.

With Rust it's fine for the first few seconds but then the colorscheme gets borked when the LSP kicks in.

I even used LspStop before it runs and the colorscheme stays working. Then I use LspStart, wait a few seconds, when the virtual text shows up it gets borked again.

**Comment by LSleutsky** [comment]
> This happens to me as well. PopOS. Lvim Nightly. Gruvbox plug.
> 
> With Rust it's fine for the first few seconds but then the colorscheme gets borked when the LSP kicks in.
> 
> I even used LspStop before it runs and the colorscheme stays working. Then I use LspStart, wait a few seconds, when the virtual text shows up it gets borked again.

Yep, exactly! This happens on the stable version of LunarVim as well for me, not just the nightly. On MacOS, however, there are no issues, and everything seems to work just fine.....

**Comment by cpea2506** [comment]
Sorry for the late response. I think I found out what happened but need someone to test it.

On Neovim nighly, `semantic_token` was enabled by default, which was returned from the language server. Read more [here](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) and `:h lsp-semantic-highlight`.

Some color schemes have not yet implemented their own color for them, so you can simply disable them to return to the default one.
```lua
-- Hide all semantic highlights
    for _, group in ipairs(vim.fn.getcompletion("@lsp", "highlight")) do
      vim.api.nvim_set_hl(0, group, {})
    end
```
or
```lua
lvim.lsp.on_attach_callback = function(client, _)
    client.server_capabilities.semanticTokensProvider = nil
end
```

**Comment by pieroluha** [comment]
It worked.
```lua
lvim.lsp.on_attach_callback = function(client, _)
    client.server_capabilities.semanticTokensProvider = nil
end
```
Tested on NVIM v0.9.0-dev-1222+gf01f18cdf with LunarVim stable and LunarVim nightly (d559dfc)
Tested two coloschemes: lunarvim and gruvbox
Tested on Rust and lua (just LunarVim config). But for Rust I had to remove the plugin simrat39/rust-tools.nvim for it to work 🤷

**Comment by cpea2506** [comment]
> It worked.
> 
> ```lua
> lvim.lsp.on_attach_callback = function(client, _)
>     client.server_capabilities.semanticTokensProvider = nil
> end
> ```
> 
> Tested on NVIM v0.9.0-dev-1222+gf01f18cdf with LunarVim stable and LunarVim nightly ([d559dfc](https://github.com/LunarVim/LunarVim/commit/d559dfc1cd9d2622393135ad23101e3e73930f30)) Tested two coloschemes: lunarvim and gruvbox Tested on Rust and lua (just LunarVim config). But for Rust I had to remove the plugin simrat39/rust-tools.nvim for it to work 🤷

Maybe your `rust-tools` automatically setup the server and it runs after `lvim.lsp.on_attach_callback`. There is an option you can try with:

```lua
require("rust-tools").setup({
  server = {
    on_attach = function(client, _)
		client.server_capabilities.semanticTokensProvider = nil
	end   
})
```

**Comment by pieroluha** [comment]
Thanks, that fixed it.

**Comment by LSleutsky** [comment]
Sorry for the late reply, but yes, can confirm it's working on my end as well! Thanks for solving this!!

Will close the issue now...
