### ISSUE TITLE
TroubleToggle not loading until Config Reload

### ISSUE THREAD

**Issue by iworkinpixels** [LunarVim/LunarVim#3933]
### Problem description

Keybindings and certain other configs seem to be not loading on LunarVim startup, and don't show up until I manually reload the config using &lt;leader&gt;Lr

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>gt;= 0.8.0)

NVIM v0.8.3

### Operating system/version

macOS 13.2.1

### Steps to reproduce

1: Install folke/trouble.nvim
2: Set a custom keybinding for TroubleToggle, like &lt;leader&gt;Z
3: Save your config and reload.
4: Press your leader key. Notice that &lt;leader&gt;Z is listed as expected in WhichKey.
5: Close out of LunarVim and go back in to LunarVim to edit any file.
6: Press your leader key. Notice that &lt;leader&gt;Z is not listed as expected in WhichKey. However, you can still :TroubleToggle in command mode.
7: Press &lt;leader&gt;Lr to reload the configuration file.
8: Press your leader key. Notice that &lt;leader&gt;Z is listed as expected in WhichKey.

**Comment by LostNeophyte** [comment]
can you send the piece of your config where you add the plugin and the keybind?

**Comment by LostNeophyte** [comment]
can't reproduce 
![image](https://user-images.githubusercontent.com/110467150/227134468-c2e1d15e-faed-4182-9a9d-e8725b7285e3.png)

**Comment by kobzar** [comment]
Lvim 1.3 neovim 0.9
The bug isn’t confirmed. 
@iworkinpixels i think you try to choose preselected (non free) key combination. Some external plugins have keybindings in default configs to. 
So, i advice You get clean config add keybindings and check again.
