### ISSUE TITLE
Code in c++ gives error that doesnt exist

### ISSUE THREAD

**Issue by Plasgianp** [LunarVim/LunarVim#3939]
### Problem description

This is my code(it gives me error only until the end of the main:
#include <iostream>       Too many error emitted, stopping now
#include "LibreriaMia.h"
/*1) Inserire i dati dei partecipanti e dei tempi realizzati
2) Stampare la classifica di tutti i concorrenti
3) Stampare i primi tre classificati con l’indicazione del vincitore della gara
4) Dato un numero di pettorina stampare il nome del concorrente e la posizione finale
in classifica
5) Dato un tempo in secondi, stampare tutti gli atleti che hanno realizzato un tempo
inferiore*/

using namespace std;
int N = 100;

struct Atleta
{
    string nome;         Unknow type name 'string'
    string cognome;      Unknow type name 'string'
    int numeroPettorina;
    int tempo;
};

int getAtleta(Atleta atleti[],int n,int pettorina);
void toString(Atleta atleta);
void findAtleta(Atleta atleti[],int n);
void stampaClassificaGenerale(Atleta atleta[],int n);
int schermoMenu();
void leggiInput(Atleta atleti[],int &n);
void stampaArray(Atleta atleti[],int n);
void bubbleSortAtleti(Atleta atleti[],int n);
void stampaPodio(Atleta atleti[],int n);
void copiaAtleti(Atleta array[],Atleta arrayCopiato[],int n);
void menoTempo(Atleta atleti[],int n);

int main(){

    Atleta atleti[N];
    int n;  //numero atleti in input
    int scelta;
    bool flag = false;

    while(true)
    {
        fflush(stdin);       use of undeclared identifier 'stdin'
        system("cls || clear");       use of undeclared identifier 'system'
        scelta = schermoMenu();
        switch (scelta)
        {
        case 1:
            leggiInput(atleti,n);
            flag = true;
            break;
        case 2:
            if (flag == false)
            {
                cout<<"Inserire prima gli atleti"<<endl;     use of undeclared identifier 'cout'
                getchar();       use of undeclared identifier 'getchar'
                break;
            }
            stampaClassificaGenerale(atleti,n);
            getchar();       use of undeclared identifier 'getcha'
            break;
        case 3:
            if (flag == false)
            {
                cout<<"Inserire prima gli atleti"<<endl;         use of undeclared identifier 'endl'
                getchar();
                break;
            }
            stampaPodio(atleti,n);
            getchar();
            break;
        case 4:
            if (flag == false)
            {
                cout<<"Inserire prima gli atleti"<<endl;
                getchar();
                break;
            }
            findAtleta(atleti,n);
            getchar();
            break;
        case 5:
            if (flag == false)
            {
                cout<<"Inserire prima gli atleti"<<endl;
                getchar();
                break;
            }
            menoTempo(atleti,n);
        default:
            break;
        }
    }
}

void menoTempo(Atleta atleti[],int n){
    
}

Atleta* calcolaClassifica(Atleta atleti[], int n) {
    Atleta* classificaAtleti = new Atleta[n];
    copiaAtleti(classificaAtleti, atleti, n);
    bubbleSortAtleti(classificaAtleti, n);
    return classificaAtleti;
}

void stampaClassificaGenerale(Atleta atleta[],int n){
    Atleta* classificaAtleti = calcolaClassifica(atleta,n);
    stampaArray(classificaAtleti,n);
}

void leggiInput(Atleta atleti[],int &n){
    cout<<"Inserire quanti atleti parteciperanno alla gara: "<<endl;
    n = leggiInteroLimitato(1,N);
    for (int i = 0; i < n; i++)
    {
        cout<<"Inserire il nome dell'atleta numero "<<i+1<<endl;
        atleti[i].nome = leggiStringaNonVuota();
        cout<<"Inserire il conome dell'atleta :"<<endl;
        atleti[i].cognome = leggiStringaNonVuota();
        cout<<"Inserire il numero pettorina dell'atleta :"<<endl;
        atleti[i].numeroPettorina = leggiInteroLimitato(1,n);
        cout<<"Inserire il tempo dell'atleta :"<<endl;
        atleti[i].tempo= leggiIntero();
    }
}

int getAtleta(Atleta atleti[],int n,int pettorina){
    for (int  i = 0; i < n; i++)
    {
        if (atleti[i].numeroPettorina == pettorina)
        {
            return i;
        }
    }
    return -1;
}

void findAtleta(Atleta atleti[],int n){
    int pettorina;
    cout<<"Inserire numero pettorina dell'atleta: "<<endl;
    pettorina = leggiInteroLimitato(1,n);
    int posizioneAtleta;
    Atleta* posto = new Atleta[n];
    posto = calcolaClassifica(atleti,n);
    posizioneAtleta = getAtleta(posto,n,pettorina);
    if (posizioneAtleta == -1)
    {
        cout<<"Atleta non trovato"<<endl;
        return;
    }else{
        Atleta atleta = posto[posizioneAtleta];
        toString(atleta);
        cout<<"La posizione in classifica dell'atleta e' : "<<posizioneAtleta+1<<endl;
    }
}

void toString(Atleta atleta){
    cout<<"Il nome dell'atleta e': "<<atleta.nome<<endl;
    cout<<"Il conome dell'atleta e': "<<atleta.cognome<<endl;
    cout<<"Il numero dell'atleta e': "<<atleta.numeroPettorina<<endl;
    cout<<"Il tempo dell'atleta e': "<<atleta.tempo<<endl;
}

void copiaAtleti(Atleta array[],Atleta arrayCopiato[],int n){
    for (int i = 0; i < n; i++)
    {
        array[i] = arrayCopiato[i];
    }
}

void stampaPodio(Atleta atleti[],int n){
    Atleta* podio = new Atleta[n];
    podio = calcolaClassifica(atleti,n);
    stampaArray(podio,3);
}

void bubbleSortAtleti(Atleta atleti[], int n) {
    bool flag;
    Atleta temp;
    for(int i = 0; i < n; i++) {
        flag = false;
        for(int j = 1; j < (n-i); j++) {
            if(atleti[j-1].tempo > atleti[j].tempo) { 
                temp = atleti[j-1];
                atleti[j-1] = atleti[j];  
                atleti[j] = temp;  
                flag = true;
            }
        }
        if(!flag) break;
    }
}

void stampaArray(Atleta atleti[],int n){
    for (int i = 0; i < n; i++)
    {
        cout<<i+1<<"."<<atleti[i].nome<<endl;
    }
}

int schermoMenu(){
	cout<<"1) Inserire i dati dei partecipanti e dei tempi realizzati\n\
    2) Stampare la classifica di tutti i concorrenti\n\
    3) Stampare i primi tre classificati con l’indicazione del vincitore della gara\n\
    4) Dato un numero di pettorina stampare il nome del concorrente e la posizione finale in classifica\n\
    5) Dato un tempo in secondi, stampare tutti gli atleti che hanno realizzato un tempo inferiore\n"<<endl;	
	int x = leggiInteroLimitato(1,5);
	return x;
}

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

0.8.3

### Operating system/version

PopOS

**Comment by PLASGIANP** [comment]
I wanto to specify that i made:
g++  GARA.cpp on my terminal and it worked

**Comment by WenXiaoDev** [comment]
If your LSP reports too many incorrect diagnostic messages (unable to find the Header File that already exists inside the project, unable to find a certain symbol, etc.), it may be because clangd does not know how to compile some files in the project, so it cannot parse them.
If your project is built with cmake, you can execute cmake at this time to generate `compile_commands.json` to help clangd parse the code:
`cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1`

this worked for me : )

reference: https://clangd.llvm.org/installation

**Comment by cauliyang** [comment]
https://github.com/rizsotto/Bear is a great tool if you use `Makefile` to manage your project. It can help you generate `compile_commands.json` that clangd can use.
