### ISSUE TITLE
Invalid default ui.Target icon

### ISSUE THREAD

**Issue by alealv** [LunarVim/LunarVim#3946]
### Problem description

The default lunar vim `ui.Target` icon seems to be invalid.

I opened `lua/lvim/icons.lua` with a hexfile viewer
```hex
00000a20: 3d20 22ee aeb7 222c 0a20 2020 2054 6172  = "...",.    Tar
00000a30: 6765 7420 3d20 22f3 b080 9822 2c0a 2020  get = "....",.
```
 and symbol hex code is `f3b08098` which isn't valid

https://unicode.scarfboy.com/?s=%5Cxf3%5Cxb0%5Cx80%5Cx98

Am I correct? What was the intended symbol?

### LunarVim version

master-d559dfc1

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Operating system/version

MacOS 13.2.1 (22D68)

### Screenshots

<img width="186" alt="image" src="https://user-images.githubusercontent.com/9395091/224376293-122698ce-e4bf-4063-ad54-167cabcb59a0.png">

**Comment by LostNeophyte** [comment]
It's a nerd font icon, update your font

**Comment by alealv** [comment]
I have a nerd font, I use `FiraCode Nerd Font Mono`
All the other symbols work

![image](https://user-images.githubusercontent.com/9395091/224653689-4ded1bda-5f29-4135-a4b6-5da97d18d1e4.png)

**Comment by LostNeophyte** [comment]
it's a new icon https://github.com/LunarVim/LunarVim/pull/3880
