### ISSUE TITLE
Not seeing any output after putting in the install script 

### ISSUE THREAD

**Issue by Chilly-169-table** [LunarVim/LunarVim#3954]
### Problem description

Copied the Install script from the website and already got the prequisites installed ,but after pressing enter to execute the script nothing is happening 

### LunarVim version

NA

### Neovim version (>= 0.8.0)

NVIM v0.8.1

### Operating system/version

macOs 13.2.1

**Comment by LostNeophyte** [comment]
can you access this file with your browser?
https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh

**Comment by LostNeophyte** [comment]
well, you can use a vpn or something or call your isp

**Comment by Chilly-169-table** [comment]
Alright checking with vpn

**Comment by Chilly-169-table** [comment]
Working Now, Closing.
