### ISSUE TITLE
Error while calling lua chunk

### ISSUE THREAD

**Issue by RoPedro** [LunarVim/LunarVim#3955]
### Problem description

Trying to install Lunarvim, there's an error that freezes the installation in the error "E492: Not an editor command: PackerSync"

I installed Neovim 0.8.3 via Tarball.

### LunarVim version

Release

### Neovim version (>= 0.8.0)

0.8.3

### Operating system/version

Ubuntu 22.04 LTS (WSL)

### Steps to reproduce

Installing LunarVim shim
make: Entering directory '/home/pedro/.local/share/lunarvim/lvim'
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: /home/pedro/.local/bin/lvim
make: Leaving directory '/home/pedro/.local/share/lunarvim/lvim'
Preparing Packer setup
Error detected while processing /home/pedro/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: vim/_init_packages.lua:0: module 'vim.diagnostic' not found:
        no field package.preload['vim.diagnostic']
        no file './vim/diagnostic.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/diagnostic.lua'
        no file '/usr/local/share/lua/5.1/vim/diagnostic.lua'
        no file '/usr/local/share/lua/5.1/vim/diagnostic/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/diagnostic.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/diagnostic/init.lua'
        no file './vim/diagnostic.so'
        no file '/usr/local/lib/lua/5.1/vim/diagnostic.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim/diagnostic.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './vim.so'
        no file '/usr/local/lib/lua/5.1/vim.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        vim/_init_packages.lua: in function '__index'
        ...o/.local/share/lunarvim/lvim/lua/lvim/core/which-key.lua:183: in function 'config'
        ...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:30: in function 'config'
        ...edro/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:21: in function 'init'
        .../pedro/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:102: in function 'init'
        /home/pedro/.local/share/lunarvim/lvim/init.lua:11: in main chunk
E484: Can't open file /share/nvim/syntax/syntax.vimError detected while processing command line:
E492: Not an editor command: PackerSync^C

**Comment by LostNeophyte** [comment]
Can you :lua require "vim.diagnostic" in nvim --clean? If not then you didn't install nvim correctly

**Comment by RoPedro** [comment]
> Can you :lua require "vim.diagnostic" in nvim --clean? If not then you didn't install nvim correctly

Thanks, i kinda solved my issue reinstalling Neovim Nightly using PPA, but one thing that i don't understand, is why the stable release of Neovim PPA didn't installed the 0.8 version, instead it installed the 0.7.

But huge thanks anyway :)
