### ISSUE TITLE
[Bug] Cannot remove default keymapping (<leader>f)

### ISSUE THREAD

**Issue by tinwritescode** [LunarVim/LunarVim#3961]
### Problem description

Step to preproduce:
1. Install lunarvim
2. In `config.lua`, add (notice that last line): 

```
-- general
lvim.log.level = "warn"
lvim.format_on_save.enabled = false
lvim.colorscheme = "lunar"
-- to disable icons and use a minimalist setup, uncomment the following
-- lvim.use_icons = false

-- keymappings [view all the defaults by pressing <leader>Lk]
lvim.leader = "space"
-- add your own keymapping
lvim.keys.normal_mode["<C-s>"] = ":w<cr>"
lvim.keys.normal_mode["<M-s>"] = ":w<cr>"
lvim.keys.normal_mode["<C-p>"] = ":Telescope<cr>"
lvim.keys.normal_mode["<leader>fw"] = ":Telescope current_buffer_fuzzy_find<cr>"
-- lvim.keys.normal_mode["<S-l>"] = ":BufferLineCycleNext<CR>"
-- lvim.keys.normal_mode["<S-h>"] = ":BufferLineCyclePrev<CR>"
-- unmap a default keymapping
lvim.keys.normal_mode["<leader>f"] = false

```

3. The result is `<leader>f` is not removed

Expect: `<leader>f` is removed, so I can use `<leader>fw` as one of the line above. 

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Operating system/version

macOS 11.5

**Comment by cpea2506** [comment]
Try with
```lua
lvim.builtin.which_key.mappings["f"] = nil
```

**Comment by nikisix** [comment]
Thanks, this has been recking my Jukit (leader-c) workflow for half a year.
Anyway to harmonize leader-x settings with these new builtin ones perhaps to reduce confusion?

Example:

```
lvim.lsp.buffer_mappings.normal_mode['<LEADER>c'] = nil
lvim.keys.normal_mode['<LEADER>c'] = nil

lvim.builtin.which_key.mappings["c"] = nil
```
Allow the first two to implicitly switch the third.
