### ISSUE TITLE
Why not use singature help and command prompt?

### ISSUE THREAD

**Issue by TomQunChao** [LunarVim/LunarVim#3962]
### Feature Description

noticing that there is no function signature prompt and command prompt in lunar vim, so suggest to use https://github.com/hrsh7th/cmp-nvim-lsp-signature-help to provide function signature help, use https://github.com/gelguy/wilder.nvim to provide command prompt

### Support information

![image](https://user-images.githubusercontent.com/46163583/226148918-f6ecaeba-4242-43f7-b2a4-491bcfd8a523.png)
![image](https://user-images.githubusercontent.com/46163583/226148923-0daf7cb7-904e-41fb-88d6-64e9dd9a95e8.png)

**Comment by rebuilt** [comment]
We should at least list the plugin here:  https://www.lunarvim.org/docs/plugins/extra-plugins

The reason we don't have the plugin included as default is we were trying to keep the list of plugins slim.  

https://github.com/LunarVim/LunarVim/pull/726#issuecomment-879673881

And if we had included a signature plugin, it would have been the only plugin available at the time: ray-x/lsp_signature.nvim .  That one doesn't work as well with lunarvim as the one you linked in this issue.

https://github.com/LunarVim/LunarVim/issues/3581

**Comment by TomQunChao** [comment]
@rebuilt  I'm sorry for not reviewing issue these days, this is my wilder setup
```lua
require("wilder").setup({ modes = { ':', '/', '?' } })
```
Maybe `set_option` should be called before setup?
