### ISSUE TITLE
request for ruff and ruff-lsp server integration in by default supported servers

### ISSUE THREAD

**Issue by Aneeqasif** [LunarVim/LunarVim#3964]
### Feature Description

ruff is blazing fast rust based python lineter,formater and lsp also it will cool to have it in lvim

### Describe the alternatives you have considered

pyright , available already

**Comment by kylo252** [comment]
`ruff` is ignored by default in favor of using the more popular [`pyright`](https://github.com/microsoft/pyright).

You can simply call the setup `ruff` manually [^1]

```lua
-- ~/.config/lvim/after/ftplugin/python.lua
require("lvim.lsp.manager").setup("ruff_lsp")
```

[^1]: https://www.lunarvim.org/docs/languages#server-setup

**Comment by Aneeqasif** [comment]
> `ruff` is ignored by default in favor of using the more popular [`pyright`](https://github.com/microsoft/pyright).
> 
> You can simply call the setup `ruff` manually [1](#user-content-fn-1-376dc0b97b0bee572cfdc6e1d5323b6e)
> 
> ```lua
> -- ~/.config/lvim/after/ftplugin/python.lua
> require("lvim.lsp.manager").setup("ruff_lsp")
> ```
> 
> ## Footnotes
> 
>     1. https://www.lunarvim.org/docs/languages#server-setup [leftwards_arrow_with_hook](#user-content-fnref-1-376dc0b97b0bee572cfdc6e1d5323b6e)

how can i

```lua
local on_attach = function(client, bufnr)
  -- Disable hover in favor of Pyright
  client.server_capabilities.hoverProvider = false
end

require('lspconfig').ruff_lsp.setup {
  on_attach = on_attach,
}

```

https://github.com/astral-sh/ruff-lsp
