### ISSUE TITLE
Big file takes time to open 

### ISSUE THREAD

**Issue by niksingh710** [LunarVim/LunarVim#3967]
### Problem description

I am using a custom hosts file from [here](https://github.com/StevenBlack/hosts)
the exact file I am using is [this](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts)

if I try to open this file in lvim it takes 4.5-5 secs to open the file. 

### LunarVim version

master-2e42dddb

### Neovim version (>= 0.8.0)

NVIM v0.8.3
Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  
Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Operating system/version

Arch Linux

### Steps to reproduce

Save the hosts file to local system.
then `lvim path/to/file`

**Comment by niksingh710** [comment]
@LostNeophyte 
I have added the file url there.

**Comment by LostNeophyte** [comment]
for me hosts file takes 150ms with clean config, empty file takes 120ms

**Comment by niksingh710** [comment]
> for me hosts file takes 150ms with clean config, empty file takes 120ms

It seems like my [config](https://github.com/niksingh710/cli/blob/master/lvim/config.lua) is the culprit

How can i narrow down what exactly is slowing this down?

**Comment by LostNeophyte** [comment]
> > for me hosts file takes 150ms with clean config, empty file takes 120ms
> 
> It seems like my [config](https://github.com/niksingh710/cli/blob/master/lvim/config.lua) is the culprit
> 
> How can i narrow down what exactly is slowing this down?

binary search is the way to go, comment out lvim.plugins first, if that fixes it uncomment the half of it, ...

**Comment by niksingh710** [comment]
> > > for me hosts file takes 150ms with clean config, empty file takes 120ms
> > 
> > 
> > It seems like my [config](https://github.com/niksingh710/cli/blob/master/lvim/config.lua?rgh-link-date=2023-03-21T13%3A25%3A34Z) is the culprit
> > How can i narrow down what exactly is slowing this down?
> 
> binary search is the way to go, comment out lvim.plugins first, if that fixes it uncomment the half of it, ...

Thanks for the idea.

```lua
-- Colorizer{{{
	{
		"norcalli/nvim-colorizer.lua",
		config = function()
			require("colorizer").setup({ "css" }, {
				RGB = true, -- #RGB hex codes
				RRGGBB = true, -- #RRGGBB hex codes
				RRGGBBAA = true, -- #RRGGBBAA hex codes
				rgb_fn = true, -- CSS rgb() and rgba() functions
				hsl_fn = true, -- CSS hsl() and hsla() functions
				css = true, -- Enable all CSS features: rgb_fn, hsl_fn, names, RGB, RRGGBB
				css_fn = true, -- Enable all CSS *functions*: rgb_fn, hsl_fn
			})
		end,
	},
	```
using `*` in the setup makes it load slower.
i guess have to specify specific files.
