### ISSUE TITLE
There is a problem with the color theme

### ISSUE THREAD

**Issue by guonaihong** [LunarVim/LunarVim#3974]
### Problem description

vim config.lua

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

macOS 12.5

### Steps to reproduce

vim 
space L c

### Screenshots

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/5006959/227485578-a176b20c-ec67-4ca0-9db8-14daa92d4458.png">

Default configuration

**Comment by rrrix** [comment]
@guonaihong Make sure you're using `lvim` .. not `vim` (or `nvim`). Unless you explicitly alias or override the command names `vim` and/or `nvim`, you will not be running `lvim`.

It looks like that's the default vim color theme - as in you're not _actually using LunarVim_.

**Comment by guonaihong** [comment]
@rrrix 'm pretty sure I'm using lvim. There is no problem with the shortcut keys. Sometimes this problem can be solved by restarting the computer. I am now using an external screen through the mac. I will update the review when I find a way to reproduce it stably
