### ISSUE TITLE
Structlog version too old... even though it's not

### ISSUE THREAD

**Issue by riotrah** [LunarVim/LunarVim#3976]
### Problem description

I had been on `rolling` since it was deprecated without realizing that it was. I tried to find any guides or suggestions about changes required, especially since we changed to `lazy`. I eventually my config working after making various changes, except for _excessive_ spamming by `structlog`, or rather, lunarvim's check added [here](https://github.com/LunarVim/LunarVim/pull/3755/files#diff-5986487111cdff165004dbd035a83275f7646155d77e7cd1310a90d1e8ee4f16R29).

Even trying to get the version in headless (via `+ 'LvimVersion'`) causes the attached screenshot.

I've synced/updated/cleaned `lazy` (redundantly), and checking `git status` in the `structlog` installation folder shows that I'm up to date.

I've also looked through my config for references to terms like `log`, `notify`, `notif`, `message`, but nothing came up.

If I could get any pointers to config options that might be causing this, or any suggestions at all, that would be great.

Let me know if I should attach my config

### LunarVim version

master-2e42dddbstructlog

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-1265+g410dc3349

### Operating system/version

Win 11 Pro 

### Screenshots

![image](https://user-images.githubusercontent.com/22646419/227697670-4dc07e04-026e-4b2d-8a6d-a4400f74bfff.png)

**Comment by LostNeophyte** [comment]
does the same happen with an empty config?, if the errors persist remove the pcall check in the lvim source code and send the errors here

> and checking git status in the structlog installation folder shows that I'm up to date.

so the structlog version is `45b26a2b1036bb93c0e83f4225e85ab3cee8f476` ?

**Comment by riotrah** [comment]
0. Wow, thanks for mega rapid response
1. Will try against empty config, sorry that I didn't do that before posting - was wondering if there was a known gotchaa
2. Will try removing that call
3. And yes, that commit
