### ISSUE TITLE
Document DAP configuration

### ISSUE THREAD

**Issue by toytown** [LunarVim/LunarVim#3979]
### Feature Description

Configuring DAP for different language server is a pain. Would be great if someone could share the way to configure DAP as described in the demo video https://www.youtube.com/watch?v=5KQK2id3JtI

### Describe the alternatives you have considered

tried official doc and still struggling to configure debugging properly

**Comment by toytown** [comment]
Here is the customization I added in options.lua

lvim.plugins = {
  {
    "folke/trouble.nvim",
    cmd = "TroubleToggle",
  },
  {
    "github/copilot.vim",
  },
  { "mxsdev/nvim-dap-vscode-js"},
  {
      "microsoft/vscode-js-debug",
      opt = true,
      run = "npm install --legacy-peer-deps && npx gulp vsDebugServerBundle && mv dist out",
  },
}


for _, language in ipairs { "typescript", "javascript" } do
  require("dap").configurations[language] = {
    {
      type = "pwa-node",
      request = "launch",
      name = "Launch file",
      program = "${file}",
      cwd = "${workspaceFolder}",
    },
    {
      type = "pwa-node",
      request = "attach",
      name = "Attach",
      processId = require("dap.utils").pick_process,
      cwd = "${workspaceFolder}",
    },
    {
      type = "pwa-node",
      request = "launch",
      name = "Debug Jest Tests",
      -- trace = true, -- include debugger info
      runtimeExecutable = "node",
      runtimeArgs = {
        "./node_modules/jest/bin/jest.js",
        "--runInBand",
      },
      rootPath = "${workspaceFolder}",
      cwd = "${workspaceFolder}",
      console = "integratedTerminal",
      internalConsoleOptions = "neverOpen",
    },
  }
end

**Comment by eagle-tex** [comment]
Has someone been able to build a working DAP configuration at all?
For Python, Typescript, Javascript, Java, C/C++? Anything?
