### ISSUE TITLE
Deprecated setup in lvim.plugins

### ISSUE THREAD

**Issue by KevenGoncalves** [LunarVim/LunarVim#3982]
### Problem description

Steps to reproduce the bug:
1. Try to install a plugin 
2. Close and open the lvim

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

nvim 0.8.0

### Operating system/version

macOS 12.4

### Screenshots

<img width="1440" alt="Captura de Tela 2023-03-27 às 15 19 03" src="https://user-images.githubusercontent.com/80492657/227948850-f1d2a7c5-16c8-464e-ba9d-c0427f738b35.png">

**Comment by KevenGoncalves** [comment]
This is how I call the plugins in lvim
<img width="619" alt="Captura de Tela 2023-03-27 às 19 55 47" src="https://user-images.githubusercontent.com/80492657/228027049-5940c184-1488-4f55-a38c-b908b17bb2bb.png">

**Comment by brneor** [comment]
That's weird, v1.2 it's not supposed to use `lazy`, it should be using `packer`.

**Comment by KevenGoncalves** [comment]
I thought the same, I even uninstalled and installed again

**Comment by LostNeophyte** [comment]
what's your :LvimVersion

**Comment by KevenGoncalves** [comment]
I manage to fixed I thought  I was using the v1.2 but it was the master. Thanks for the help 😁

**Comment by captjay98** [comment]
How did you fix it please?

**Comment by LostNeophyte** [comment]
> How did you fix it please?

By doing what the warning says, you have `setup = ...` somewhere in your `lvim.plugins` table, change it to `init = ...`
