### ISSUE TITLE
Terminal is not usable 

### ISSUE THREAD

**Issue by geohuz** [LunarVim/LunarVim#3983]
### Problem description

On macos 13.2.1, fresh installed Lvim, open the terminal inside lvim, get this output:
```
/etc/zshrc: 7 command not found: locale
````
and even command like `ls` showing command not found. I' wondering if the shell doesn't read .zshrc or .zshenv?

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Operating system/version

macos 13.2.1

**Comment by LostNeophyte** [comment]
it's probably a bug in toggleterm

**Comment by geohuz** [comment]
I found the issure in my .zshrc, now I fixed it.
