### ISSUE TITLE
vim.treesitter.query.get_query() is deprecated

### ISSUE THREAD

**Issue by changchichung** [LunarVim/LunarVim#3993]
### Problem description

everytime open files using lunarvim , error message will be generated
```
vim.treesitter.query.get_query() is deprecated, use vim.treesitter.query.get() instead. :help deprecated
This feature will be removed in Nvim version 0.10
```
after press enter , there are more
```
stack traceback:
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:200: in function 'get_query'
        ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:104: in function 'get_query'
        ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:196: in function 'prepare_query'
        ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:378: in function 'iter_group_results'
        ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:390: in function 'collect_group_results'
        ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:48: in function 'update_cached_matches'
        ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:56: in function 'get_locals'
        ...ker/start/nvim-treesitter/lua/nvim-treesitter/locals.lua:38: in function 'get_definitions'
        ...ker/start/nvim-treesitter/lua/nvim-treesitter/locals.lua:158: in function 'fn'
        ...r/start/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:356: in function 'get_definitions_lookup_table'
        ...ker/start/nvim-treesitter/lua/nvim-treesitter/locals.lua:213: in function 'find_definition'
        ...t/vim-illuminate/lua/illuminate/providers/treesitter.lua:16: in function 'get_references'
        ...ck/packer/start/vim-illuminate/lua/illuminate/engine.lua:140: in function <...ck/packer/start/vim-illuminate/lua/illuminate/engine.lua:118>
        [C]: in function 'pcall'
        ...ck/packer/start/vim-illuminate/lua/illuminate/engine.lua:118: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
...
...
...
```

any suggestions ??

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM V0.9.0-dev

### Operating system/version

ubuntu 22.04

**Comment by fdelacruz** [comment]
yeah, but who runs 0.8??

**Comment by LostNeophyte** [comment]
> yeah, but who runs 0.8??

a commit before the deprecation will probably work as well

**Comment by gravis** [comment]
Nvim 0.9 is now the default on Mac OS with Homebrew

**Comment by fdelacruz** [comment]
Some of us compile from src even on a Mac OS X.

**Comment by fdelacruz** [comment]
Some of us compile src even on Mac OS X.

**Comment by FlippingBinary** [comment]
This issue describes exactly what happened to me today after my OS (Manjaro Linux) updated NeoVim to the latest stable release of NeoVim, which is [0.9](https://software.manjaro.org/package/neovim).

Should this issue be reopened? The release notes describe [several breaking changes](https://github.com/neovim/neovim/releases/tag/v0.9.0)...

**Comment by zydou** [comment]
Downgrade neovim to `v0.8.3` fixed the warning.

**Comment by FlippingBinary** [comment]
> Downgrade neovim to `v0.8.3` fixed the warning.

Downgrading NeoVim to any version prior to 0.9 will eliminate the warning because the deprecation was introduced in 0.9. It is an adequate work-around, but not a permanent solution unless LunarVim is planning on forking NeoVim to eliminate the dependency.

**Comment by LostNeophyte** [comment]
> It is an adequate work-around, but not a permanent solution unless LunarVim is planning on forking NeoVim to eliminate the dependency
lunarvim 1.2 is made for nvim 0.8, and it won't be updated, there will be a new release soon for nvim 0.9

**Comment by FlippingBinary** [comment]
> lunarvim 1.2 is made for nvim 0.8, and it won't be updated, there will be a new release soon for nvim 0.9

Thank you for that information. That's a relief. I see #3858 from February, but I couldn't find any other place that mentioned or tracked this issue. I don't think anybody in this thread would need a specific version of LunarVim to support NeoVim 0.9 as long as there is a version that does.

Is there anything I can do to help? I'm not sure I understand the workflow of the migration to the new version, so I don't want to just search and replace the deprecated functions with new ones and submit it as a pull request unless that would help.

**Comment by FlippingBinary** [comment]
I just tried `:PackerUpdate` and that seems to have resolved the problem. In my case, I think it was a plugin that had already fixed the problem in their repository and I just needed to pull the update. I got the idea after searching LunarVim's source for `get_query` and coming up empty.

**Comment by cristobalgvera** [comment]
@LostNeophyte when do you think it will be released? I don't see any workaround in MacOS other than install Neovim not from Homebrew.

**Comment by LostNeophyte** [comment]
> @LostNeophyte when do you think it will be released? I don't see any workaround in MacOS other than install Neovim not from Homebrew.

within a week most likely

**Comment by MajorZiploc** [comment]
@changchichung 
Given how annoying this warning message is, it basically makes lunar vim unusable.
I have a work around for it.
CAUTION: This will silence basically any deprecated warning or stack trace. So I would recommend only using this until the next release of lunar vim

```lua
-- PATCH: in order to address the message:
-- vim.treesitter.query.get_query() is deprecated, use vim.treesitter.query.get() instead. :help deprecated
--   This feature will be removed in Nvim version 0.10
local orig_notify = vim.notify
local filter_notify = function(text, level, opts)
  if type(text) == "string" and (string.find(text, ":help deprecated", 1, true) or string.find(text, "stack trace", 1, true)) then
    return
  end
  orig_notify(text, level, opts)
end
vim.notify = filter_notify
```

**Comment by LostNeophyte** [comment]
> Given how annoying this warning message is, it basically makes lunar vim unusable.
I have a work around for it.
CAUTION: This has the potential to remove other messages not related to this specific issue. So I would recommend only using this until the next release of lunar vim
Put this into your config.lua

use a supported version of neovim, no need for a workaround.

**Comment by FlippingBinary** [comment]
> @changchichung Given how annoying this warning message is, it basically makes lunar vim unusable. I have a work around for it. CAUTION: This has the potential to remove other messages not related to this specific issue. So I would recommend only using this until the next release of lunar vim Put this into your config.lua
> 
> ```lua
> -- PATCH: in order to address the message:
> -- vim.treesitter.query.get_query() is deprecated, use vim.treesitter.query.get() instead. :help deprecated
> --   This feature will be removed in Nvim version 0.10
> local orig_notify = vim.notify
> local filter_notify = function(text, level, opts)
>   -- more specific to this case
>   if type(text) == "string" and (string.find(text, "get_query", 1, true) or string.find(text, "get_node_text", 1, true)) then
>   -- for all deprecated and stack trace warnings
>   -- if type(text) == "string" and (string.find(text, ":help deprecated", 1, true) or string.find(text, "stack trace", 1, true)) then
>     return
>   end
>   orig_notify(text, level, opts)
> end
> vim.notify = filter_notify
> ```

This will work for me, thank you! If I forget to remove a workaround, I'd rather it be this filter function than a version lock to an old version of NeoVim. 

If there was a way to only activate the filter when LunarVim 1.2 is used with NeoVim 0.9+, that would be even better, but I didn't see an obvious way to detect the LunarVim version.

**Comment by MajorZiploc** [comment]
@LostNeophyte I use multiple flavors of nvim configs. Other configs work for 0.9
  but your comment does make me think of looking into a nvim version manager
  found this one: https://github.com/MordechaiHadad/bob
  Thanks for that!

@FlippingBinary 
Glad this could help. shouldnt this file only be used by LunarVim? ~/.config/lvim/config.lua
If you put the filter_notify code above there, then it would only affect LunarVim

**Comment by FlippingBinary** [comment]
> @LostNeophyte I use multiple flavors of nvim configs. Other configs work for 0.9 but your comment does make me think of looking into a nvim version manager found this one: https://github.com/MordechaiHadad/bob Thanks for that!
> 
> @FlippingBinary Glad this could help. shouldnt this file only be used by LunarVim? ~/.config/lvim/config.lua If you put the filter_notify code above there, then it would only affect LunarVim

Yes, that's where I put it, but I wouldn't want to suppress warnings that I haven't seen yet, so I will want to remove it after the LunarVim update in anticipation of future warnings that I should review before suppressing.

**Comment by MajorZiploc** [comment]
@FlippingBinary i see. right, i miss read what you said before.
I just plan on removing it manually from my dotfiles once i update lunarvim

**Comment by Lotfree618** [comment]
you could install again,and evething will be right
make sure backups!
LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)

**Comment by PeterPasdzierny** [comment]
> still get the same error using nvim v0.9.0

Likewise with current nightly v0.10.0

**Comment by LostNeophyte** [comment]
@kamalkech @PeterPasdzierny 

what's your lunarvim version?

**Comment by PeterPasdzierny** [comment]
> @kamalkech @PeterPasdzierny
> 
> what's your lunarvim version?

Oh, I use a custom config, not LunarVim and was redirected here while tracking down the Treesiter problem only. Didn't realise this is an LunarVim thread! 

I haven't yet find anything helpful elsewhere though

**Comment by Scribler** [comment]
I used`:checkhealth nvim-treesitter` and it'll show you which languages aren't parsing

then I used `TSInstall <languageThatIsn'tParsing>`

that solved the conflicts

**Comment by Jarrod-Angove** [comment]
Have there been any updates on this? I'm still getting this error message on nvim v0.9.4.

**Comment by FlippingBinary** [comment]
@Jarrod-Angove This issue occurred when using LunarVim 1.2 with NeoVim 0.9. LunarVim releases are locked to specific NeoVim releases, so NeoVim 0.9 users should be using LunarVim 1.2 (as I understand it). I wound up getting frustrated with how brittle that arrangement was, so I switched to LazyVim.
 
Are you sure you're using the correct version of LunarVim?
