### ISSUE TITLE
Trouble Toggle isn't working

### ISSUE THREAD

**Issue by esciafardini** [LunarVim/LunarVim#3995]
### Problem description

When I try to use <Leader>tt to toggle diagnostics, I am getting an error message:

<img width="770" alt="Screenshot 2023-03-30 at 9 05 10 AM" src="https://user-images.githubusercontent.com/51748017/228845342-d535218f-750c-4a96-a180-0456c42685a9.png">

### LunarVim version

release-1.2

### Neovim version (>= 0.8.0)

1.2.0

### Operating system/version

macOS

### Affected language servers

all

### Steps to reproduce

1. Enable TroubleToggle
2. Use <leader>tt to toggle diagnostics

### Actual behavior

lua error message

### Expected behavior

toggling lsp diagnostics off and on

### support info

<leader>tt

### logs

```console
[WARN][2023-03-29 15:04:40] ...lsp/handlers.lua:113	"The language server clojure_lsp triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

### Screenshots

<img width="770" alt="Screenshot 2023-03-30 at 9 05 10 AM" src="https://user-images.githubusercontent.com/51748017/228845979-778432a5-bf88-4c05-ad9f-ad68ed1e2184.png">
s

**Comment by cpea2506** [comment]
For now, 
1. Please upgrade to version [1.3](https://www.lunarvim.org/docs/installation).
2. After upgrading, run `Lazy update trouble.nvim` to get the latest version/fixes
3. Response back to this if the problem solved. Thank you 😉
