### ISSUE TITLE
windows installation using powershell script remote server unreachable

### ISSUE THREAD

**Issue by beautifulnature** [LunarVim/LunarVim#3997]
### Problem description

$LV_BRANCH='release-1.2/neovim-0.8'; Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

Neovim 0.8.0

### Operating system/version

Windows 10

### Steps to reproduce

1.  $LV_BRANCH='release-1.2/neovim-0.8'; Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression

### Screenshots

Error: Invoke-WebRequest : Unable to connect to the remote server

**Comment by LostNeophyte** [comment]
can you open the link from the command in your browser?

**Comment by beautifulnature** [comment]
No I can't

**Comment by LostNeophyte** [comment]
use a vpn or something then
