### ISSUE TITLE
Support for launch.json DAP config

### ISSUE THREAD

**Issue by WillianFuks** [LunarVim/LunarVim#4000]
### Feature Description

Would it be possible to add the support for loading extra DAP configurations from a specific "launch.json" file, as it is in vscode?

Here's an example that I set up in my lvim:

```lua
{
    { "BufWinEnter", "BufNewFile" },
    {
      group = group_dap_settings,
      pattern = { "*" },
      desc = [[
        Looks for the file "launch.json" either at `cwd` or
        at `cwd .. ".vscode"`. If if finds, loads its dap
        config for the given buffer
      ]],
      callback = function()
        local lvim_utils = require("lvim.utils")
        local cwd = vim.fn.getcwd()
        local ok, _ = pcall(function()
          local dap = require("dap")
          local dap_ext_vscode = require "dap.ext.vscode"
          local json_path = nil
          if lvim_utils.is_file(cwd .. "launch.json") then
            json_path = cwd .. "launch.json"
          elseif lvim_utils.is_file(cwd .. "/.vscode/launch.json") then
            json_path = cwd .. "/.vscode/launch.json"
          end
          if (json_path ~= nil and dap.configurations[vim.bo.filetype] ~= nil) then
                dap_ext_vscode.load_launchjs(json_path)
          end
        end)
        if not ok then
          Log:error("Failed loading DAP configuration from launch.json")
        end
      end
    }
  }
```

It looks for launch.json either at `cwd` or at `cwd ../.vscode` and if it finds one and there's already a DAP setup found then it adds the extra configs. For supporting windows OSes then the separator would have to be considered. Also, it might make more sense (maybe) to allow the users choose on their config a default list of folders to look for the files. Something like:

```lua
local dap_config = {
  launch_json_default_folders = {
     "folder_path_1_from_cwd",
     "folder_path_2",
     ...
   }
}
```

**Comment by mbrav** [comment]
This would be a very welcoming feature. I am currently forcing myself to transition from VSCode to nvim (NvChad > kickstart.nvim > LunarVim), not having `launch.json` support for DAP out of the box is such a brain breaker. I have so many project that rely on `launch.json`. Thanks for sharing your config @WillianFuks.
