### ISSUE TITLE
lsp cannot figure out dunder methods in classes

### ISSUE THREAD

**Issue by tomkark** [LunarVim/LunarVim#4001]
### Problem description

Hey,

i'm setting up my lvim as a python IDE right now, and i thought i had finished but i've noticed that a lot of auto completions are missing.

for example i've written a sample class that was supposed to be a context manager, and if i try to type 
`def __enter` it won't autocomplete, same for exit.

I've also noticed other dunder methods are missing when compared to pycharm's auto completion.

Tried using pyright, jedi-language-server and pylsp. So probably isn't a specific lsp problem.
  

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde 

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Operating system/version

Ubuntu 22.04

### Affected language servers

all

### Actual behavior

auto-complete should work for all dunder methods in classes

### Expected behavior

Missing methods....

### support info
```
 Language client log: /home/tom/.local/state/nvim/lsp.log
 Detected filetype:   python
 
 2 client(s) attached to this buffer: 
 
 Client: pyright (id: 1, pid: nil, bufnr: [1])
 	filetypes:       python
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             pyright-langserver --stdio
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [1])
 	filetypes:       python
 	autostart:       false
 	root directory:  /home/tom/stuff/python
 	cmd:             <function>
 
 Configured servers list: pyright

```

```
    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                python
* bufnr:                   1
* treesitter status:       active

Active client(s)
* name:                      pyright
* id:                        1
* supported filetype(s):     python
* attached buffers:          1
* root_dir pattern:          1
* capabilities:              callHierarchyProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: black  
* Supported: [autopep8, black, blue, isort, reorder_python_imports, usort, yapf]

Linters info
* Active: flake8  
* Supported: [flake8, mypy, pycodestyle, pydocstyle, pylama, pylint, pyproject_flake8, semgrep, vulture]

Code actions info
* Active: 
```

### Screenshots

Example of init:
![image](https://user-images.githubusercontent.com/27143723/229295776-cc67fb56-f5d4-4625-9388-8c2a209c4461.png)

__enter__ not working
![image](https://user-images.githubusercontent.com/27143723/229295785-64efeeaf-ad1d-4e70-b205-99cec910d9fe.png)

**Comment by LostNeophyte** [comment]
try this https://github.com/LunarVim/LunarVim/issues/3842#issuecomment-1441408397

**Comment by tomkark** [comment]
> try this [#3842 (comment)](https://github.com/LunarVim/LunarVim/issues/3842#issuecomment-1441408397)

Did not fix it...

**Comment by LostNeophyte** [comment]
the lsp server is most likely the issue in that case

**Comment by tomkark** [comment]
Though i tried using 3 different lsp servers

**Comment by LostNeophyte** [comment]
try in something else than lunarvim

**Comment by LostNeophyte** [comment]
i don't get any completion after __enin my nvim config with pyright

**Comment by tomkark** [comment]
So what do you suggest? because it's pretty critical for me

**Comment by LostNeophyte** [comment]
see if you get the completion in different neovim configs, if you don't then it's not a lunarvim issue

**Comment by kobzar** [comment]
I was check this moment on the VSC with python plugings with the same results. 
So, this is no LV problem.  I think autocomplete for this method working only in PyCharm by Intelleji instruments. 
So, you can add personal snipets for quick fix.
