### ISSUE TITLE
nvim-tresitter warns about adding new parsers.

### ISSUE THREAD

**Issue by akashdiphazra** [LunarVim/LunarVim#4003]
### Problem description

<pre><span style="background-color:#FF0000"><font color="#FFFFFF">Error detected while processing VimEnter Autocommands for &quot;*&quot;:</font></span>
<span style="background-color:#FF0000"><font color="#FFFFFF">Error executing lua callback: .../.local/share/lunarvim/lvim/lua/lvim/core/treesitter.lua:185:</font></span>
<span style="background-color:#FF0000"><font color="#FFFFFF"> VimEnter Autocommands for &quot;*&quot;: Vim(lua):Installation not possible: ...er/start/nvim-treesitte</font></span>
<span style="background-color:#FF0000"><font color="#FFFFFF">r/lua/nvim-treesitter/install.lua:52: Parser not available for language &quot;vimdoc&quot;</font></span>
<span style="background-color:#FF0000"><font color="#FFFFFF">stack traceback:</font></span>
<span style="background-color:#FF0000"><font color="#FFFFFF">        [C]: in function &apos;cmd&apos;</font></span>
<span style="background-color:#FF0000"><font color="#FFFFFF">        .../.local/share/lunarvim/lvim/lua/lvim/core/treesitter.lua:185: in function &lt;.../.loc</font></span>
<span style="background-color:#FF0000"><font color="#FFFFFF">al/share/lunarvim/lvim/lua/lvim/core/treesitter.lua:179&gt;</font></span>
</pre>

### LunarVim version

1.2.0

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-1322+gbc96bda5a

### Operating system/version

Ubuntu 22.04

### Screenshots

![Screenshot from 2023-04-03 18-00-45](https://user-images.githubusercontent.com/61003681/229511965-fac963dc-bdb7-48bd-ac5e-706b8a9b6972.png)

**Comment by ctarx** [comment]
I can confirm that I am also experiencing the same issue as the original poster:

```Error detected while processing VimEnter Autocommands for "*":
Error executing lua callback: .../.local/share/lunarvim/lvim/lua/lvim/core/treesitter.lua:185: VimEnter Autocommands for "*":
 Vim(lua):Installation not possible: ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:52: Parser not available for
 language "vimdoc"
stack traceback:
        [C]: in function 'cmd'
        .../.local/share/lunarvim/lvim/lua/lvim/core/treesitter.lua:185: in function <.../.local/share/lunarvim/lvim/lua/lvim
/core/treesitter.lua:179>
```
### Steps to reproduce
Simply launch nvim.

**Comment by ctarx** [comment]
Using a Neovim version higher than 0.8.0+ is causing this issue.
https://github.com/LunarVim/LunarVim/issues/4015#issuecomment-1501467793

**Comment by LostNeophyte** [comment]
closing in favor of #4015 (it has more comments)
