### ISSUE TITLE
Treesitter puppat parser

### ISSUE THREAD

**Issue by HerveMARTIN** [LunarVim/LunarVim#4006]
### Problem description

In Neovim, i'm able to add an extra treesitter parser for puppet with this snippet : 
```
local status_parsers_ok, parsers = pcall(require, "nvim-treesitter.parsers")
if not status_parsers_ok then
  vim.notify("Error loading parsers")
  return
end

local parser_config = parsers.get_parser_configs()
parser_config.puppet = {
  install_info = {
    url = "https://github.com/neovim-puppet/tree-sitter-puppet.git",
    files = {"src/parser.c", "src/scanner.cc"},
    branch = "main",
  },
  filetype = "puppet",
}
```

But I can't get it work in LunarVim...
Is there any documentation for this case elsewhere?

Regards

### LunarVim version

release-1.2

### Neovim version (>= 0.8.0)

neovim-0.8-8f4a7bde

### Operating system/version

Manjaro Linux

**Comment by techsk8** [comment]
I was looking around on how to do this and I bumped into this.
Where do I need to add that snippet to make it work with `neovim`?
And where you able to make it work with `Lunarvim`?

**Comment by HerveMARTIN** [comment]
For NeoVim you have to put this snippet into your init.lua file.
I'm still waiting for help to make it work on LunarVim.

**Comment by techsk8** [comment]
I have done it and it still doesn't work.

I need to make this work on `Lunarvim`

**Comment by techsk8** [comment]
They have added puppet the nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter/pull/4715#event-9108714827

**Comment by LostNeophyte** [comment]
that code will probably work if you put it in on_config_done in treesitter config

**Comment by techsk8** [comment]
Well, we don't need to anymore.

It's already integrated into `nvim-treesiter` by default~

**Comment by techsk8** [comment]
@HerveMARTIN can you please correct the typo from title?
`puppat --> puppet`
