### ISSUE TITLE
Add keybinding to exit insert mode in terminal

### ISSUE THREAD

**Issue by brokoli18** [LunarVim/LunarVim#4007]
### Problem description

I would like to add a custom mapping to exit the terminal insert mode. Something like:
`tnoremap <Esc> <C-\><C-n>`

However I see no way to do this in the keybindings section of the doc. There is an `lvim.keys.normal_mode` section but as far as I know this doesnt apply to the terminal. I would just like to know how I can add the above setting to the neovim config.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd 

### Neovim version (>= 0.8.0)

NVIM v0.8.1

### Operating system/version

Ubuntu 22.04.2 LTS

**Comment by kobzar** [comment]
Just add this line in your config file
'''
-- Exit from insert mode by Esc in Terminal
vim.keymap.set('t', '<esc>', [[<C-\><C-n>]])
'''

**Comment by LostNeophyte** [comment]
you can use `lvim.keys.term_mode`

**Comment by brokoli18** [comment]
I tried @kobzar suggestion first and that worked perfectly. Thank you very much. I am not sure if this should be kept open for the doc enhansements but my issue is resolved so feel free to close.

**Comment by kobzar** [comment]
You can use both of them for your choice
```
lvim.keys.term_mode["<esc>"] = "<C-\\><C-n>"
```
