### ISSUE TITLE
Lag when editing a 12MB CSV file

### ISSUE THREAD

**Issue by xis19** [LunarVim/LunarVim#4009]
### Problem description

I am editing a 12MB CSV file. The file itself contains very long lines (up to 10k characters) and corrupted by some non-ascii characters. It is very slow to move around, even I set `syntax off`.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Operating system/version

macOS 13.3 (22E252)

### Steps to reproduce

1. `vim somewhat_large_csv_file.csv`
2. Experience the slowness

**Comment by LostNeophyte** [comment]
probably fixed on master

**Comment by kobzar** [comment]
Just for interest - did you use Colorizer plugin? Try to disable it for test.

**Comment by xis19** [comment]
> Just for interest - did you use Colorizer plugin? Try to disable it for test.

How do I disable it? I am pretty new to lunarvim.

**Comment by xis19** [comment]
> probably fixed on master

Yes, after upgrade to nightly, the issue gets disappeared
