### ISSUE TITLE
Questioning the "sane defaults" claim.

### ISSUE THREAD

**Issue by thisismygitrepo** [LunarVim/LunarVim#4011]
### Feature Description

When I open the explorer side bar and use my right and left arrows, that results in a useless movement of cursor over the letters of files and folders. I'm not sure if this is a sane default.

Can we please have it such that right and left arrows do expansion and contraction of directories? This is the case in `spacevim` and I believe it makes explorer more convenient in navigation of the tree.

Thank you.

**Comment by riotrah** [comment]
I'm not a contributor but I'm quite taken aback by how self-unaware this post is. I hope I'm not misreading your tone or something, and I don't know if you were just having a particularly frustrating day, but I feel compelled to answer, if only just for others reading this.

`h` & `l`, as part of the primary navigation keys in vim, do **exactly** that, which many, if not most, users will discover without issue. 

The arrow keys, which are not typically "primary" nav keys in vim, offer an _added convenience_ in lvim to let you override those folding bindings in case you _want_ to do "useless" cursor movement - which btw, I use often for selecting or copying substrings of filenames. I'd have a hard time concluding that either of having the arrow keys as cursor movement overrides or as dups of homerow keys are significantly more or less intuitive/sane.

Though I'd encourage you to try to communicate more constructively for your own sake in the future - if you'd phrased this issue as a discussion of "Proposing using arrow keys vs/in addition to classic nav keys for primary or default actions in certain UIs", or "How can I change the sidebar nav keybindings", etc, I suspect you'd get more than 4 downvotes in over a week in such an active repo.

**Comment by thisismygitrepo** [comment]
@riotrah thanks for taking time to explain instead of a dislike. 

Not sure why people get offended if I described something as useless. I mean, if that happened on my repo, it wouldn't even cross my mind, I'll be focusing on the argument itself.

I'm closing this though as I'm no convinced with substring copy, cause the filename should not be that long, let a long a substring.
