### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by ryannewcomer** [LunarVim/LunarVim#4014]
### Problem description

1. paste the command from website
2. run the command
3. ans yes for both python and node
4. see error

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.2 

### Terminal name

powerShell 7.3.3

### Operating system/version

window 11

### Screenshots

![image](https://user-images.githubusercontent.com/88273136/230735388-5ae27f03-066e-47eb-badc-bf3db4411687.png)

**Comment by LostNeophyte** [comment]
fixed on master
