### ISSUE TITLE
Deprecate treesitter query

### ISSUE THREAD

**Issue by kobzar** [LunarVim/LunarVim#4017]
### Problem description

Deprecated options for treesitter
```
vim.treesitter.query.get_query() is deprecated, use vim.treesitter.query.get() instead. 
:help deprecated
This feature will be removed in Nvim version 0.10
```

### LunarVim version

last stable

### Neovim version (>= 0.8.0)

0.9.0_1

### Terminal name

Alacritty

### Operating system/version

Void Linux

### Steps to reproduce

any

**Comment by LostNeophyte** [comment]
don't use lvim 1.2 with neovim nightly

**Comment by kobzar** [comment]
I dont use it. My lvim version is 

release-1.2/neovim-0.8-8f4a7bde
And neovim version is 0.9.0-1
And this is STABLE version for ArchLinux, Void Linux for this moment

And on the official neovim site we can see the same info
https://github.com/neovim/neovim/releases/tag/stable
0.9 version is stable. 

There a lot of function that wasr renamed
https://github.com/neovim/neovim/pull/22761

**Comment by LostNeophyte** [comment]
lvim 1.2 is made for nvim 0.8, I forgot that 0.9 is no longer nightly
