### ISSUE TITLE
How to make word completion for normal word? 

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#4018]
### Problem description

lvim.colorscheme = "lunar"
-- require("bluloco").setup({
--   style = "auto",               -- "auto" | "dark" | "light"
--   transparent = false,
--   italics = false,
--   terminal = vim.fn.has("gui_running") == 1 -- bluoco colors are enabled in gui terminals per default.
-- })
-- lvim.colorscheme = 'bluloco'

-- to disable icons and use a minimalist setup, uncomment the following
lvim.use_icons = true

-- keymappings [view all the defaults by pressing <leader>Lk]
lvim.leader = ";"
lvim.keys.normal_mode["<C-s>"] = ":w<cr>"
lvim.keys.normal_mode["<C-Tab>"] = ":BufferLineCyclePrev<CR>"
lvim.keys.normal_mode["<C-S-Tab>"] = ":BufferLineCyclePrev<CR>"
vim.opt.clipboard = ""
lvim.keys.visual_mode["<"] = "<gv"
lvim.keys.visual_mode[">"] = ">gv"
lvim.keys.visual_mode["p"] = '"_dP'
lvim.keys.normal_mode["gm"] = "<cmd>lua require('telescope.builtin').marks()<CR>"
lvim.keys.normal_mode["gbb"] = "<cmd>Telescope buffers<CR>"
lvim.keys.normal_mode["<A-o>"] = ":Telescope oldfiles<CR>"
lvim.keys.normal_mode["<C-o>"] = ":Telescope oldfiles<CR>"
lvim.keys.normal_mode["<A-o>"] = ":lua require('telescope.builtin').find_files { shorten_path = true, cwd = '" .. note_path .. "' }<CR>"
-- lvim.keys.normal_mode["<A-n>"] = "<cmd>lua require('telescope.builtin').find_files { shorten_path = true, cwd = '" .. note_path .. "' }<CR>"
-- lvim.keys.normal_mode["<A-f>"] = "<cmd>lua require('telescope.builtin').live_grep({cwd='.'})<CR>"
-- cant change this lvim mapping is later than this, will overwrite it.
--

-- remove map for close buffer
lvim.builtin.which_key.mappings["c"] = {}
lvim.builtin.which_key.mappings["sl"] = {'<cmd>lua require("luapad").attach()<CR>', "Show Luapad", silent=true }
lvim.builtin.which_key.vmappings["c"] = { "\"+y", "Copy to clipboard" }
lvim.builtin.which_key.mappings["f"] = {}
lvim.builtin.which_key.mappings["f"] = { "<cmd>lua require('telescope.builtin').oldfiles{ previewer = false }<CR>", "old files", silent=true }
lvim.builtin.which_key.mappings["vs"] = { "<cmd>vs<CR><cmd>lua require('telescope.builtin').oldfiles{ previewer = false }<CR>", "vsplit window and oldfiles", silent=true }
lvim.builtin.which_key.mappings["ve"] = { "<C-w>=", "Even Split", silent=true }
lvim.builtin.which_key.mappings["u"] = {"mzb~`z", "Capitalized First letter"}
lvim.builtin.which_key.mappings["cb"] = {"<cmd>BufferKill<CR>", "Close buffer"}
lvim.builtin.which_key.mappings["sc"] = { "<cmd>Telescope command_history<CR>", "Search history", silent = true }
lvim.builtin.which_key.mappings["h"] = { "q:", "Check history" }
lvim.builtin.which_key.mappings["bx"] = { ":BufferKill<CR>", "Close Current Buffer", silent = true }
lvim.builtin.which_key.mappings["bs"] = { "<C-w><C-r>", "Close Current Buffer", silent = true }
lvim.builtin.which_key.mappings["w"] = nil
lvim.builtin.which_key.mappings["n"] = { ":lua require('telescope.builtin').find_files { shorten_path = true, cwd = '" .. note_path .. "' }<CR>", "Run current script", silent = true }
lvim.builtin.which_key.mappings["rr"] = { "<cmd>edit " .. get_config_dir() .. "/config.lua<cr>", "edit config" }
lvim.builtin.which_key.mappings["rc"] = { "<cmd>@:<cr>", "Repeat last command" }
lvim.builtin.which_key.mappings['cf'] =  {"<cmd>let @\"=expand('%:p') . ':' . line('.')<CR><cmd>let @+=@\"<CR>", "Copy file and line number", silent = true}
lvim.builtin.which_key.mappings['ct'] =  {"<cmd>lua toggleTheme()<CR>", "Toggle Theme", silent = true}
lvim.builtin.which_key.mappings.s['b'] =  {"<cmd>Telescope buffers<CR>", "Search buffers"}
lvim.builtin.which_key.mappings.s['r'] =  {"<cmd>Telescope registers<CR>", "Search buffers"}
lvim.lsp.buffer_mappings.normal_mode["gl"] = { "$", "Go to line end" }
lvim.builtin.which_key.mappings["w"] = { "<cmd>HopWord<CR>", "Hop Word" }
-- vim.keymap.set({'x', 'o', 'n'}, '<leader>sb', '<cmd>Telescope buffers<CR>')

-- buffer process
-- lvim.keys.normal_mode["<A-]>"] = "<cmd>vertical resize +5<CR>"
-- lvim.keys.normal_mode["<A-[>"] = "<cmd>vertical resize -5<CR>"
lvim.keys.normal_mode["<A-S-=>"] = "<cmd>resize +5<CR>"
lvim.keys.normal_mode["<A-S-->"] = "<cmd>resize -5<CR>"
-- be care about the zellij commands
keymap({'n'}, '<A-]>', '<cmd>vertical resize -5<CR>')
keymap({'n'}, '<A-[>', '<cmd>vertical resize +5<CR>')
lvim.builtin.which_key.mappings["on"] = { "<cmd>only | noh<CR>", "Close other split window", silent=true }
lvim.builtin.which_key.mappings["oo"] = { "<cmd>edit /home/lizhe/.local/share/lunarvim/site/pack/packer/start/orivim/lua/orivim.lua<CR>", "Open Orivim", silent=true }
lvim.builtin.which_key.mappings["bo"] = { "<cmd>BufferLineCloseLeft<CR><cmd>BufferLineCloseRight<CR>", "Close other split window", silent=true }
lvim.builtin.which_key.mappings["co"] = { "<cmd>exe 'bd '.join(filter(range(0, bufnr('$')), 'bufwinnr(v:val)<0'), ' ') | noh<CR>", "Close other split window", silent=true }
lvim.keys.normal_mode["<S-x>"] = ":BufferKill<CR>"
lvim.keys.normal_mode["<A-S-l>"] = ":BufferLineCycleNext<CR>"
lvim.keys.normal_mode["<A-S-h>"] = ":BufferLineCyclePrev<CR>"

-- TODO: User Config for predefined plugins
-- After changing plugin config exit and reopen LunarVim, Run :PackerInstall :PackerCompile
lvim.builtin.alpha.active = true
lvim.builtin.alpha.mode = "dashboard"
lvim.builtin.terminal.active = true
lvim.builtin.nvimtree.setup.view.side = "left"
lvim.builtin.nvimtree.setup.renderer.icons.show.git = false
lvim.builtin.nvimtree.setup.actions.open_file.quit_on_open = true
lvim.builtin.nvimtree.setup.actions.open_file.quit_on_open = true

-- if you don't want all the parsers change this to a table of the ones you want
lvim.builtin.treesitter.ensure_installed = {
  "bash",
  "c",
  "javascript",
  "json",
  "lua",
  "python",
  "typescript",
  "tsx",
  "css",
  "rust",
  "java",
  "yaml",
}

lvim.builtin.treesitter.ignore_install = { "haskell" }
lvim.builtin.treesitter.highlight.enable = true

-- plug install pluginstall
lvim.plugins = {
  -- {
  --     'uloco/bluloco.nvim',
  --     requires = { 'rktjmp/lush.nvim' }
  -- },
  {'skywind3000/asyncrun.vim'},
  {'NvChad/nvim-colorizer.lua'},
  {'rafcamlet/nvim-luapad'},
  {
    'phaazon/hop.nvim',
    branch = 'v2', -- optional but strongly recommended
    config = function()
      -- you can configure Hop the way you like here; see :h hop-config
      require'hop'.setup { keys = 'etovxqpdygfblzhckisuran' }
    end
  },
  {'rcarriga/nvim-notify'},
  -- {"mickael-menu/zk-nvim"},
  { "woshichuanqilz/orivim",
    config = function ()
      require("orivim").setup()
    end
  },
  { "Shatur/neovim-session-manager" },
  {
    'phaazon/mind.nvim',
    branch = 'v2.2',
    requires = { 'nvim-lua/plenary.nvim' },
    config = function()
      require'mind'.setup()
    end
  },
  { "preservim/vim-markdown", commit='df4be8626e2c5b2a42eb60e1f100fce469b81f7d' },
  { "rlue/vim-barbaric" },
  {'raghur/vim-ghost', run=':GhostInstall'},
  { "dag/vim-fish" },
  { "ggandor/leap.nvim" },
  { "tpope/vim-repeat" },
  { "gcmt/wildfire.vim" },
  { "tpope/vim-surround" },
  { "rafcamlet/nvim-whid" },
  { 'michaelb/sniprun', run = 'bash ./install.sh' },
  { "github/copilot.vim" , run = ':Copilot setup'},
  {
    "folke/trouble.nvim",
    cmd = "TroubleToggle",
  },
  {
    "iamcco/markdown-preview.nvim", run = "cd app && npm install", setup = function() vim.g.mkdp_filetypes = { "markdown" } end, ft = { "markdown" }, 
  },
  { "uga-rosa/cmp-dictionary" },
  { "ggandor/flit.nvim" },
  -- { "tzachar/cmp-tabnine", run = "./install.sh", requires = "hrsh7th/nvim-cmp" },
  -- { 'neoclide/coc.nvim', branch = 'release' },
}

lvim.format_on_save = {
  pattern = { "*.lua", "*.py", "*.go" },
}

require 'sniprun'.setup({ display = { "Terminal" }, })

table.insert(lvim.builtin.cmp.sources, 1, { name = "dictionary", keyword_length = 2, })

-- leap config
require('leap').add_default_mappings()
-- Disable auto jump first match
-- local ok, actions = pcall(require, "telescope.actions")
_, _ = pcall(vim.api.nvim_del_keymap, 'n', 's')
_, _ = pcall(vim.api.nvim_del_keymap, 'v', 's')
_, _ = pcall(vim.api.nvim_del_keymap, 'n', 'S')
_, _ = pcall(vim.api.nvim_del_keymap, 'n', 'S')
_, _ = pcall(vim.api.nvim_del_keymap, 'v', 'x')

local leap_trigger_key = 'r'
vim.keymap.set({'x', 'o', 'n'}, leap_trigger_key, '<Plug>(leap-forward-to)')
vim.keymap.set({'x', 'o', 'n'}, string.upper(leap_trigger_key), '<Plug>(leap-backward-to)')

require('leap').opts.safe_labels = {'f', 'n', 'u', 't', 'r', 'm', 'j'}
require("leap").opts.equivalence_classes = { ' \t\r\n=-_+', }
vim.api.nvim_set_hl(0, 'LeapBackdrop', { link = 'Comment' })
vim.api.nvim_set_hl(0, 'LeapMatch', {
  fg = 'white',  -- for light themes, set to 'black' or similar
  bold = true,
  nocombine = true,
})
require('leap').opts.highlight_unlabeled_phase_one_targets = true
-- vim.keymap.set({'x', 'o', 'n'}, 'f', 'f')
-- vim.keymap.set({'x', 'o', 'n'}, 'F', 'F')

-- cmp-dictionary
require("cmp_dictionary").setup({
	dic = {
		["markdown"] = { "/home/lizhe/OriNote/notes/Data/google-10000-english-no-swears.txt" },
		["text"] = { "/home/lizhe/OriNote/notes/Data/google-10000-english-no-swears.txt" },
	},
	-- The following are default values.
	exact = 2,
	first_case_insensitive = true,
	document = false,
	document_command = "wn %s -over",
	async = false,
	max_items = -1,
	capacity = 5,
	debug = false,
})

require('flit').setup {
  keys = { f = 'f', F = 'F', t = 't', T = 'T' },
  -- A string like "nv", "nvo", "o", etc.
  labeled_modes = "v",
  -- multiline = true,
  opts = {}
}

vim.cmd([=[
    autocmd! InsertEnter * call feedkeys("\<Cmd>noh\<cr>" , 'n')
    autocmd! BufWritePost * noh | redraw
    nnoremap gf gF
    cnoremap cc ccl
    nnoremap <S-A-K> viwy:he <C-r>"
    nnoremap 'r 'R
    nnoremap 'k 'K
    nnoremap <A-S-d> :e /home/lizhe/OriNote/notes/Ori/OriTask🏃.md<CR>
    setlocal nospell
    set iskeyword+=-
    set relativenumber
    nnoremap < <<
    nnoremap > >>
    cnoremap ww w \| noh
    nnoremap }  }b
    nnoremap {  {w
    nnoremap gw {w
    vnoremap gw {w
    nnoremap ge }be
    vnoremap ge }be
    vnoremap gh ^
    vnoremap gl $
    nnoremap gh ^
    nnoremap gl $
    nnoremap <A-a> <C-o>
    nnoremap <A-d> <C-i>
    nnoremap <S-l> <C-w>l
    nnoremap <S-h> <C-w>h
    nnoremap <ESC> <ESC>:w<CR>
    imap <C-v> <ESC>"+p<ESC>a
    cmap <C-v> <ESC>"+p<ESC>a
    vmap <c-v> <ESC>"+p
    nnoremap p p`]
    vnoremap y y`]
    nnoremap Y y$
    nmap <A-m> viW<Plug>VSurround]viW<Plug>VSurround]
    nmap g` viW<Plug>VSurround`
    vmap g` <Plug>VSurround`
    nmap g( viW<Plug>VSurround)
    vmap g( <Plug>VSurround)
    vmap <A-m> <Plug>VSurround]gv<Plug>VSurround]
    " nmap <A-y> viW<Plug>VSurround]%a()<ESC>h"+pF(<CR>l
    " vmap <A-y> <Plug>VSurround]%a()<ESC>h"+pF(<CR>l
    nnoremap <A-y> viW<Esc>a](<C-r>+)<Esc>gvo<Esc>i[<Esc>
    vnoremap <A-y> <Esc>a](<C-r>+)<Esc>gvo<Esc>i[<Esc>
    nnoremap <A-s> :lua require('alpha').start()<CR>
    nnoremap <A-r> :Telescope oldfiles<CR>
    vnoremap <A-r> :Telescope oldfiles<CR>
    nnoremap <A-c> :Telescope command_history<CR>
    " nnoremap gT :bp<CR>
    nnoremap gn :bn<CR>
    cnoremap %s %s/\v
    imap jj <esc>
    imap jk <esc>
    nnoremap <leader>a <ESC>mzggVG"+y`z
    " inoremap <A-i> [[]]<ESC>hi
    inoremap <A-t> [Todo]
    inoremap <A-d> [Done]
    let g:copilot_filetypes = {
        \ 'markdown': v:true,
    \ }
    " Open file
    " nnoremap <leader>t :e $HOME/OriNote/notes/Ori/OriTaskKanban.md<CR>
    function! Lv()
      let @+=trim(execute("LvimVersion"))
    endfunction
    " nnoremap <Leader>v :LvimVersion<CR>
    onoremap p ip`]
    nnoremap <silent> <Leader>pwd :silent !pwd<Bar>tr -d '\n'<Bar>xclip<CR>
    command! Cpwd let @+=trim(execute('pwd'))
    command! Pwd echo expand('%:p')
    " This selects the next closest text object.
    map <SPACE> <Plug>(wildfire-fuel)
    " This selects the previous closest text object.
    vmap <C-SPACE> <Plug>(wildfire-water)
    nnoremap j gj
    nnoremap k gk
    com! -nargs=1 -range Sbak call MoveSelectedLinesToFile()
    fun! MoveSelectedLinesToFile(filename)
        exec "'<,'>w! >>" . a:filename
        norm gvd
    endfunc
    " match SpellCap /\[Todo\]/
    " 2match SpellCap /\[Done\]/
    " you should make n, v, o map"
    "nnoremap <A-l> :s/\[ \]/[x]/g<CR>:noh<CR>
    ]=])
-- vimcmd

-- markdown setting
vim.g.vim_markdown_folding_disabled = 1

-- Load snippet
require("luasnip/loaders/from_vscode").load { paths = { "~/.config/lvim/snippets/my-snippets" } }

-- use autocmd group
vim.api.nvim_create_augroup("ori_write_note", {})
vim.api.nvim_clear_autocmds({group = 'ori_write_note'})
vim.api.nvim_create_autocmd("FileType", {
  group = 'ori_write_note',
  pattern = { "*.md" },
  callback = function()
    vim.cmd('setlocal nospell')
  end,
})

-- Autocommands (https://neovim.io/doc/user/autocmd.html)
vim.api.nvim_create_autocmd("BufEnter", {
  group = 'ori_write_note',
  pattern = { "*.md" },
  callback = function()
    keymap({'n'}, '<C-b>', 'mzlbi**<ESC>ea**<ESC>`z')
    keymap({'v'}, '<C-b>', '<ESC>mz`>a**<ESC>`<i**<ESC>`z')
  end,
})

-- vim.api.nvim_create_augroup("oriColorSchemeChangeEvent", {})
-- vim.api.nvim_create_autocmd("ColorScheme", {
--   group = "oriColorSchemeChangeEvent",
--   pattern = "*",
--   desc = "ColorScheme Event",
--   callback = function()
--     require('leap').init_highlight(true)
--     vim.cmd([[ hi! VertSplit guifg=white guibg=white ctermbg=white ctermfg=white ]])
--   end,
-- })

-- session manager
local Path = require('plenary.path')
require('session_manager').setup({
  sessions_dir = Path:new(vim.fn.stdpath('data'), 'sessions'), -- The directory where the session files will be saved.
  path_replacer = '__', -- The character to which the path separator will be replaced for session files.
  colon_replacer = '++', -- The character to which the colon symbol will be replaced for session files.
  autoload_mode = require('session_manager.config').AutoloadMode.LastSession, -- Define what to do when Neovim is started without arguments. Possible values: Disabled, CurrentDir, LastSession
  autosave_last_session = true, -- Automatically save last session on exit and on session switch.
  autosave_ignore_not_normal = true, -- Plugin will not save a session when no buffers are opened, or all of them aren't writable or listed.
  autosave_ignore_dirs = {}, -- A list of directories where the session will not be autosaved.
  autosave_ignore_filetypes = { -- All buffers of these file types will be closed before the session is saved.
    'gitcommit',
  },
  autosave_ignore_buftypes = {}, -- All buffers of these bufer types will be closed before the session is saved.
  autosave_only_in_session = false, -- Always autosaves session. If true, only autosaves after a session is active.
  max_path_length = 80,  -- Shorten the display path if length exceeds this threshold. Use 0 if don't want to shorten the path at all.
})

function toggleTheme()
  if lvim.colorscheme == "tokyonight" then
    vim.cmd('colorscheme lunar')
  else
    vim.cmd('colorscheme tokyonight')
  end
end

-- parse string in snippets
function parse_snippets_string()
 vim.cmd(':\'<,\'>s/"/\\\\"/g')
 vim.cmd(':\'<,\'>s/^/"/g')
 vim.cmd(':\'<,\'>s/$/",/g')
 vim.cmd(':noh')
end

-- seems got a conflict here
vim.api.nvim_create_augroup("ori_all_files", {})
vim.api.nvim_create_autocmd("BufWritePost", {
  group = "ori_all_files",
  pattern = { "*" },
  desc = 'Autocmd for all files',
  callback = function()
    vim.cmd('noh')
    -- vim.cmd('echo "lizhe1"')
  end,
})

-- Open in neovim: alacritty -e nvim {path} "+normal {line}G{col}l"
function open_in_neovim()
  local row = vim.api.nvim_exec('echo line(".")', true)
  local col = vim.api.nvim_exec('echo col(".")', true)
  local path = vim.api.nvim_exec('echo expand("%:p")', true)
  -- how to run async command in lvim
  vim.cmd(string.format('AsyncRun alacritty -e nvim %s "+normal %sG%sl"', path, row, col - 1))
end

-- color css
require("colorizer").setup {
    filetypes = { "*" },
    user_default_options = {
      RGB = true, -- #RGB hex codes
      RRGGBB = true, -- #RRGGBB hex codes
      names = true, -- "Name" codes like Blue or blue
      RRGGBBAA = false, -- #RRGGBBAA hex codes
      AARRGGBB = false, -- 0xAARRGGBB hex codes
      rgb_fn = true, -- CSS rgb() and rgba() functions
      hsl_fn = false, -- CSS hsl() and hsla() functions
      css = true, -- Enable all CSS features: rgb_fn, hsl_fn, names, RGB, RRGGBB
      css_fn = false, -- Enable all CSS *functions*: rgb_fn, hsl_fn
      -- Available modes for `mode`: foreground, background,  virtualtext
      mode = "background", -- Set the display mode.
      -- Available methods are false / true / "normal" / "lsp" / "both"
      -- True is same as normal
      tailwind = false, -- Enable tailwind colors
      -- parsers can contain values used in |user_default_options|
      sass = { enable = false, parsers = { css }, }, -- Enable sass colors
      virtualtext = "■",
    },
    -- all the sub-options of filetypes apply to buftypes
    buftypes = {},
}

function searchCurrentWord()
  vim.cmd('normal mzviw"ay')
  local kw = vim.fn.getreg('a')
  vim.cmd(string.format('AsyncRun google-chrome "https://www.google.com.hk/search?q=%s"', kw))
  vim.cmd('normal `z')
end

```


### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Terminal name

alacritty

### Operating system/version

OS: Ubuntu 22.04 jammy

### Steps to reproduce

_No response_

### Screenshots

_No response_

**Comment by LostNeophyte** [comment]
please fill out the issue form correctly next time and if it's a question, use github discussions instead
