### ISSUE TITLE
installation failed silently

### ISSUE THREAD

**Issue by zzzgit** [LunarVim/LunarVim#4020]
### Problem description

I executed the installation scripts on the terminal on MacOS Monterrey. It failed silently, and no error was shown.

### LunarVim version

newest

### Neovim version (>= 0.8.0)

0.8.2

### Terminal name

macOS monterey termianl

### Operating system/version

macOS 12

**Comment by LostNeophyte** [comment]
how do you know it failed?

**Comment by zzzgit** [comment]
> 

<img width="568" alt="image" src="https://user-images.githubusercontent.com/1060733/230958149-19938830-9a73-421a-bf41-71c942878780.png">

Without a wait for curl, it immediately showed me the second line.

**Comment by LostNeophyte** [comment]
can you access the url in your browser?
