### ISSUE TITLE
Error complaining when install nightly version 

### ISSUE THREAD

**Issue by YinAqu** [LunarVim/LunarVim#4024]
### Problem description

An error occurs when installing nightly version, but it just seems to be an insignificant issue, which does not affect the use after installation.

### LunarVim version

Master 2d373036493b3a61ef24d98efdeecbe8e74467be

### Neovim version (>= 0.8.0)

NVIM  v0.9.0

### Terminal name

suckless st

### Operating system/version

Arch linux

### Steps to reproduce

1. Just execute `bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`

### Screenshots

![image](https://user-images.githubusercontent.com/16650765/231111653-1a749bc6-96a7-4d2c-98d6-aa8a1ae8afee.png)

**Comment by YinAqu** [comment]
@kobzar actually I've tried to reinstall many times after clean all old files, every time this error occurs

**Comment by YinAqu** [comment]
After some investigation, I figure out that when `build` giving,  `config` will be executed even `lazy = true`,  but in this `config` callback, `mason` has not loaded yet as  [lazy plugin doc](https://github.com/folke/lazy.nvim#-plugin-spec) says on a first fresh installing.
```
  {
    "williamboman/mason.nvim",
    config = function()
      require("lvim.core.mason").setup()
    end,
    cmd = { "Mason", "MasonInstall", "MasonUninstall", "MasonUninstallAll", "MasonLog" },
    build = function()
      pcall(function()
        require("mason-registry").refresh()
      end)
    end,
    enabled = true,
    lazy = true,
  },

```

**Comment by YinAqu** [comment]
After some investigation, I figure out that when `build` giving,  `config` will be executed even `lazy = true` on a first fresh installing,  but in this `config` callback, `mason` has not been loaded yet as  [lazy plugin doc](https://github.com/folke/lazy.nvim#-plugin-spec) says .
```
  {
    "williamboman/mason.nvim",
    config = function()
      require("lvim.core.mason").setup()
    end,
    cmd = { "Mason", "MasonInstall", "MasonUninstall", "MasonUninstallAll", "MasonLog" },
    build = function()
      pcall(function()
        require("mason-registry").refresh()
      end)
    end,
    enabled = true,
    lazy = true,
  },

```

**Comment by LostNeophyte** [comment]
> but in this config callback, mason has not been loaded yet, which violates [lazy plugin doc](https://github.com/folke/lazy.nvim#-plugin-spec)'s guarantee

requiring it loads it automatically
