### ISSUE TITLE
Additional plugin is not being added

### ISSUE THREAD

**Issue by restagner** [LunarVim/LunarVim#4034]
### Problem description

Trying to add [vimwiki](https://github.com/vimwiki/vimwiki) plugin

1. open lunar vim's config file (confg.lua)
2. add the following 
```
lvim.plugins = {
    {
        {"vimwiki/vimwiki"}
    }
}
```
4. save and exit 
5. re-open lunar vim
6. run `:PackerStatus`

I don't see that the `vimwiki` plugin was added.  Am I missing a step?

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.2

### Terminal name

iTerm2

### Operating system/version

macOS 10.15.7

### Steps to reproduce

see above description

**Comment by brneor** [comment]
You should run `:PackerSync` or `<leader> p s`.

**Comment by restagner** [comment]
Thanks @brneor .   I tried this, but it does not seem to work, either.  The plugin remains uninstalled

**Comment by restagner** [comment]
Ok, I figured this out -- problem solved.  It looks like the syntax I used
```
lvim.plugins = {
    {
        {"vimwiki/vimwiki"}
    }
}
```

was incorrect.  It should be

```
lvim.plugins = {
    {"vimwiki/vimwiki"}
}
```

I included too many curly braces `}`
