### ISSUE TITLE
Change install instructions on Linux/MacOS to not directly run script from curl

### ISSUE THREAD

**Issue by meepcode** [LunarVim/LunarVim#4035]
It's generally regarded as a bad practice in the Linux world to not directly run a script that was curled or wgeted from the internet directly in bash with bash<(curl ...), to avoid the user from installing or running malware/a poorly written script. The install instructions should be changed to instruct the user to curl the install script before checking it over and _then_ running it.

**Comment by LostNeophyte** [comment]
I personally believe that 99% of people would just run the script without reading it anyway and it would be just more commands to copy paste

**Comment by ChristianChiarulli** [comment]
For users who have this concern I'm sure they have the ability to decompose the command. It's not worth it for the inconvenience for 99% of users.
