### ISSUE TITLE
NvimTree update_focused_file option are not working

### ISSUE THREAD

**Issue by KevenGoncalves** [LunarVim/LunarVim#4039]
### Problem description

I need the cwd not update when I update a file 
Expect
<img width="334" alt="Captura de Tela 2023-04-14 às 10 32 21" src="https://user-images.githubusercontent.com/80492657/231990127-24d94d28-6275-4b58-a90e-0b43350a9b6f.png">

What really happen:
<img width="334" alt="Captura de Tela 2023-04-14 às 10 32 37" src="https://user-images.githubusercontent.com/80492657/231990191-3604095f-a7df-449e-a9e6-0ebf5a689fdc.png">

### LunarVim version

1.2

### Neovim version (>= 0.8.0)

nvim 0.8.0

### Terminal name

kitty

### Operating system/version

macOS 12.4

**Comment by YinAqu** [comment]
it's not because of nvimtree, but 'project.nvim'

**Comment by KevenGoncalves** [comment]
How I can disable this behavior

**Comment by YinAqu** [comment]
Just take a loot at [project configuration](https://github.com/ahmedkhalf/project.nvim#%EF%B8%8F-configuration), and [project.lua](https://github.com/LunarVim/LunarVim/blob/master/lua/lvim/core/project.lua). `lvim.builtin.project.manual_mode = true` may satisfy your needs if you dont need automatically root change.

**Comment by KevenGoncalves** [comment]
It's working, thanks!
