### ISSUE TITLE
html lsp issues 

### ISSUE THREAD

**Issue by timepassforfun** [LunarVim/LunarVim#4044]
### Problem description

every time i close terminal and enter again html lsp is uninstalled and i have to install it again it started happening recently and how do i add auto brackets plugin it also shows error and emitter does not work 

### LunarVim version

10

### Neovim version (>= 0.8.0)

NVIM v0.10.0-dev-46+ge23c6ebed

### Terminal name

Windows terminal app,cmd

### Operating system/version

windows 10

### Steps to reproduce

indent-blankline: Failed to load parser for language 'html': uv_dlopen: C:\Users\LENOVO\AppData\Local\nvim-data\site\pack\lazy\opt\nvim-treesitter\parser\html.so is not a valid Win32 application.
Press ENTER or type command to continue

**Comment by LostNeophyte** [comment]
> LunarVim version
10

that's not a valid lunarvim version

> html lsp issues

i see no mention of anything related to lsp in the issue, do you mean treesitter?

**Comment by LostNeophyte** [comment]
What's your lunarvim version?

**Comment by timepassforfun** [comment]
master-7@ce6b7d-dirty

NVIM vo.9.@ sorry for earlier typo

**Comment by timepassforfun** [comment]
![2](https://user-images.githubusercontent.com/127202592/232434889-458ad16d-c639-47d6-9069-93a3834e29fe.jpg)
![1](https://user-images.githubusercontent.com/127202592/232434904-c06c1169-9f43-4d49-a2aa-0f04d2251725.jpg)

**Comment by LostNeophyte** [comment]
> 

you edited the lunarvim core files, revert these edits, also I can't find the `ce6b7d` commit on our repo
