### ISSUE TITLE
Telescope FZF Native build failed.

### ISSUE THREAD

**Issue by armada45-pixel** [LunarVim/LunarVim#4045]
### Problem description

1. Install lunarvim ( Invoke-WebRequest https://raw.githubusercontent.com/LunarVim/LunarVim/master/utils/installer/install.ps1 -UseBasicParsing | Invoke-Expression )
2. open lunarvim ( lvim )
3. Wait for setup or :Lazy build telescope-fzf-native.nvim
4. Then telescope-fzf-native.nvim error

### LunarVim version

master

### Neovim version (>= 0.8.0)

0.9.0

### Terminal name

PowerShell 7.3.3 on Windows Terminal

### Operating system/version

Windows 11 V.22H2 22621.1555

### Steps to reproduce

:Lazy build telescope-fzf-native.nvim

### Screenshots

![image](https://user-images.githubusercontent.com/59261678/232336479-a4540334-0a18-4925-9757-493b2d304d90.png)

**Comment by LostNeophyte** [comment]
Do you have make installed?

**Comment by armada45-pixel** [comment]
> Do you have make installed?

Sure.
![image](https://user-images.githubusercontent.com/59261678/232455306-82d8e2b6-063a-44ff-bf7e-22b4c70099c4.png)

**Comment by kobzar** [comment]
@armada45-pixel does the @LostNeophyte link help you?

**Comment by satyamjay-iitd** [comment]
I  am facing the same issue

**Comment by Woutjeee** [comment]
Yea, I am having the same issue..

**Comment by LostNeophyte** [comment]
please upvote the issue instead of writing "I have the same issue" comments

**Comment by armada45-pixel** [comment]
I fix this issue with this.

C:\Users\`armada`\AppData\Local\nvim\lua\plugins\configs\nvim-treesitter.lua

```lua
return function(_, opts)
  require 'nvim-treesitter.install'.compilers = { "clang", "gcc" }
  require("nvim-treesitter.configs").setup(opts)
end
```

**Comment by fcFn** [comment]
Had this issue. To fix (step 2 may be optional for you):

1. Open `%localappdata%\lvim\config.lua` and remove `-NoLogo` (there was a fix a couple of hours ago for that, so might not be necessary after the stable updates).
2. Make sure you have `gcc` in your path. I downloaded [MinGW-w64](https://www.mingw-w64.org/downloads/#w64devkit).
3. Build `telescope-fzf-native.nvim` in Lazy (`:Lazy`, select it and press `gb`) or just uninstall and reinstall LunarVim so it will run the setup again.

**Comment by tahir-hassan** [comment]
This is still an issue as of today (20 Feb 2024).  

I fixed it using @fcFn 's comment.  What I did: 

- installed `gcc` using scoop. 
- Ran the uninstallation pwsh code from the LunarVim website
- Re-installed LunarVim using the installation pwsh code
- Before running `lvim`, I edited `%localappdata%\lvim\config.lua` and removed `-NoLogo`.
- Ran `lvim` and things worked as expected.
