### ISSUE TITLE
Switching between tabs, cant figure out how to do this without the mouse

### ISSUE THREAD

**Issue by sigboe** [LunarVim/LunarVim#4047]
### Problem description

In LunarVim everything I do in the explorer opens a new tab... Fine but the only way I have found to switch between tabs is to click on them with the mouse. 

Okay so then I take to googling, and also checking `:help tabs` in neovim and vim I can easily change tabs using `gt` and `gT`  as well as the following commands `:tabn` `:tabnext` `:tabp` `:tabprevious` and `:tabN`

I might have misunderstood what to expect from using LunarVim as opposed to (neo)vim, but why doesn't any of these ways to cycle between tabs work? I have not edited any settings files (at least not manually), I have just installed things via `:Mason` . (this is not a rhetorical question, its a genuine question) am I not supposed to be able to use a normal (neo)vim workflow in LunarVim? 

### LunarVim version

master-40e48574

### Neovim version (>= 0.8.0)

NVIM v0.9.0

### Terminal name

Kitty

### Operating system/version

6.2.11-arch1-1

**Comment by brneor** [comment]
You can use `<leader> b` to see the options to navigate between open buffers. `<leader> b b/n`, for example, move to previous/next buffer respectively. You can also use `<leader> b j` to jump to any open buffer.

You can also have a look at [this commit](https://github.com/LunarVim/LunarVim/commit/45f9825d1e666890ed37baf15a14707ae4) to bring back a mapping to directly move to next and previous buffers.

**Comment by sigboe** [comment]
@brneor  thank you, I was able to restore my prefered way of switching tabs using by reading the commit you linked

```lua
lvim.keys.normal_mode["gt"] = ":BufferLineCycleNext<CR>"
lvim.keys.normal_mode["gT"] = ":BufferLineCyclePrev<CR>"
```

And I agree with the commit you linked, to avoid Highjacking H and L, but I don't understand removing gt and gT ??

**Comment by cpea2506** [comment]
> @brneor thank you, I was able to restore my prefered way of switching tabs using by reading the commit you linked
> 
> ```lua
> lvim.keys.normal_mode["gt"] = ":BufferLineCycleNext<CR>"
> lvim.keys.normal_mode["gT"] = ":BufferLineCyclePrev<CR>"
> ```
> 
> And I agree with the commit you linked, to avoid Highjacking H and L, but I don't understand removing gt and gT ?? (which the commit didn't do but its still missing)

The buffer comes from `bufferline.nvim` plugins and it's not a native vim tab. Read more here <https://github.com/akinsho/bufferline.nvim#faq>

**Comment by Xbz-24** [comment]
thank you for the info I added these two lines and now my setup is great, tysm
