### ISSUE TITLE
Do you need to configure your work environment as `luv`

### ISSUE THREAD

**Issue by Chris-Leeworthy** [LunarVim/LunarVim#4049]
### Problem description

Whenever I open the `config.lua` I get the following prompt.
```
Do you need to configure your work environment as `luv`?:
1: Apply and modify settings
2: Apply but do not modify settings
3: Don't show again
Type number and <Enter> or click with the mouse (q or empty cancels):
```
It doesn't matter which of the options I choose, I get the prompt again the next time I open the file.

I have tried `:LvimUpdate` and `:LvimCacheReset` but the problem is still happening. 

***Update***
Happens for any lua file.

### LunarVim version

master-40e48574

### Neovim version (>= 0.8.0)

NVIM v0.9.0

### Terminal name

iTerm2

### Operating system/version

macOS 13.3.1

### Steps to reproduce

The prompt doesn't happen using the minimal config.

**Comment by NivekNK** [comment]
For what i have seen, there is two solutions to this problem, one is to modify the lua_ls default_workspace, adding **checkThirdParty = false**:

```lua
local default_workspace = {
  checkThirdParty = false,

  library = {
    vim.fn.expand "$VIMRUNTIME",
    get_lvim_base_dir(),
    require("neodev.config").types(),
    "${3rd}/busted/library",
    "${3rd}/luassert/library",
  },

  maxPreload = 5000,
  preloadFileSize = 10000,
}
```

Another way is to modify the **.luarc.json** like:
```json
{
    "Lua": {
        "workspace.checkThirdParty": false
    }
}
```

But these solutions feel more like a workaround.

More info: https://github.com/LuaLS/lua-language-server/issues/679

**Comment by embeddedpenguin** [comment]
> For what i have seen, there is two solutions to this problem, one is to modify the lua_ls default_workspace, adding **checkThirdParty = false**:
> 
> ```lua
> local default_workspace = {
>   checkThirdParty = false,
> 
>   library = {
>     vim.fn.expand "$VIMRUNTIME",
>     get_lvim_base_dir(),
>     require("neodev.config").types(),
>     "${3rd}/busted/library",
>     "${3rd}/luassert/library",
>   },
> 
>   maxPreload = 5000,
>   preloadFileSize = 10000,
> }
> ```
> 
> Another way is to modify the **.luarc.json** like:
> 
> ```json
> {
>     "Lua": {
>         "workspace.checkThirdParty": false
>     }
> }
> ```
> 
> But these solutions feel more like a workaround.
> 
> More info: [LuaLS/lua-language-server#679](https://github.com/LuaLS/lua-language-server/issues/679)

This solution only fixes the issue for projects afaik. For example, every time I open my lua config in `~/.config/lvim/config.lua`, I get hit with 
```
Do you need to configure your work environment as `luv`?:
1: Apply and modify settings
2: Apply but do not modify settings
3: Don't show again
Type number and <Enter> or click with the mouse (q or empty cancels):
```

Is the proposed solution to add a .luarc.json file next to every lua file I want to edit?

**Comment by nfwyst** [comment]
its 
```lua
require('lspconfig').lua_ls.setup {
  settings = {
    Lua = {
      ...
      workspace = {
        ...
        checkThirdParty = "Disabled",
      },
    },
  },
}
```

**Comment by 9mm** [comment]
@nfwyst awesome was bout to lose my mind
