### ISSUE TITLE
instalation error

### ISSUE THREAD

**Issue by MiladHossein** [LunarVim/LunarVim#4050]
### Problem description

I got this error when I want install LunarVim's Python dependencies

`Verifying that pip is available..
Installing with pip..
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
`

### LunarVim version

master

### Neovim version (>= 0.8.0)

v0.10.0

### Terminal name

konsole

### Operating system/version

debian testing

**Comment by YanaiKlugman** [comment]
I have the same error while using Ubuntu 23.04 beta. ppa:deadsnakes doesn't support 23.04 until April 20th from what I understand.

**Comment by YanaiKlugman** [comment]
sudo apt install python3-pip 
( even python3- )

Doesn't seem to solve the issue. I've also set up pip to run in a virtual environment, same result.

**Comment by LostNeophyte** [comment]
The Python dependencies are unused, you don't need them

If you want them then install them any ash you want and in the installer skip this step

**Comment by Roctic** [comment]
> The Python dependencies are unused, you don't need them
> 
> If you want them then install them any ash you want and in the installer skip this step

I thought I'd do just that (laughs)

**Comment by elivanse** [comment]
sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED
this worked for me!

**Comment by Corybyte** [comment]
> sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED this worked for me!

I solved the problem. Thank you.

**Comment by LostNeophyte** [comment]
> sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED this worked for me!

don't do that, that file is there for a [reason](https://packaging.python.org/en/latest/specifications/externally-managed-environments/#externally-managed-environments) 

if you really need it, just install pynvim using apt `sudo apt install python3-pynvim`. No plugins from lunarvim require it as far as I'm aware, idk why it's in the list of dependencies

**Comment by vaibhav3027** [comment]
how do i do it in macos ?

**Comment by grievercr** [comment]
> > how do i do it in macos ?
> > since it still shows the same error after `brew install python3-pynvim` and `python-ply`
> 
> creating `~/.config/pip/pip.conf` and adding
> 
> ```
> [global]
> break-system-packages = true
> user = true
> ```
> 
> fixed it for me.

This fix worked for me!
