### ISSUE TITLE
changing my lualine theme

### ISSUE THREAD

**Issue by thivox** [LunarVim/LunarVim#4051]
### Problem description

hey guys, i wanted to change to lualine theme to a custom one, but it always loaded the default one
i craeted a file called lualine.lua in C:\Users\BIBOP\AppData\Local\lvim\lua\user\plugins , and rquired it in config.lua file in C:\Users\BIBOP\AppData\Local\lvim 
 i added this line in my config.lua  "lvim.builtin.lualine.sections = true" 
i got the theme i wanted but i got an error message each time i lauch lvim, my question is how can i fix that, or if you have a more efficient way to change my lualine config

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Terminal name

Powershell

### Operating system/version

windows 10

### Steps to reproduce

lvim config.lua
add lvim.builtin.lualine.sections = true
require("user.plugins.lualine")
save and relaunch lvim

### Screenshots

![added acode](https://user-images.githubusercontent.com/89551173/232644385-e4a5adb5-941d-4fa4-9edd-73159f6bc407.png)
![lualine issue one](https://user-images.githubusercontent.com/89551173/232644404-7e43cfcd-0d42-45c3-9e80-4b719b0610a7.png)

**Comment by kobzar** [comment]
You dont need add last two rows just use it like this
```
lvim.builtin.lualine.options.theme = "material"
lvim.builtin.lualine.sections.lualine_b = { "lsp_progress" }
```
You can find more info here
https://github.com/nvim-lualine/lualine.nvim

**Comment by thivox** [comment]
hey man, thanx for taking the time to answer me. here is how my lualine looks after adding the two lines
![after change one](https://user-images.githubusercontent.com/89551173/233158864-cadaac02-01d6-4f20-a480-3e55a6403335.png)
 and here is the wanted look. as you can see there are no triangles in mine
![wanetd look](https://user-images.githubusercontent.com/89551173/233158989-35b6cc05-e4e8-4a65-be12-f7489a6f7ebc.png)

**Comment by kobzar** [comment]
You can play with separators 
```
lvim.builtin.lualine.options.section_separators = { left = "", right = "" }
lvim.builtin.lualine.options.component_separators = { left = "", right = "" }
```
But directly, the author of Pauline say:
All available themes are only best effort ports by myself/ other users. If you find a theme to be weird/ wrong please open an issue/ pr.

The default values as I see is 
```
options = {
  section_separators = { left = '', right = '' },
  component_separators = { left = '', right = '' }
}
```

**Comment by pedrosmmc** [comment]
Hey @thivox!
Liked very much your lualine design. I would like to adopt it.
Can you share it?
Thanks.
Regards.
