### ISSUE TITLE
Cannot split the content of `config.lua` file into multiple subfile

### ISSUE THREAD

**Issue by aap01** [LunarVim/LunarVim#4056]
### Problem description

if I separate the content of the `config.lua` file into multiple files and refer them in the `config.lua` file following problems occur

1. every time I launch LunarVim, my configuration does not load

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/19292809/232905442-93c6f5d3-e55d-4852-9bb6-0c1bffbed390.png">

Probably, it has nothing to do with LunarVim but programming with lua.
Whichever the case is, a helpful clue would be nice.
Please note that I have almost zero knowledge in lua programming language.

### LunarVim version

rolling-50578617

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-945+gd359f7a53-dirty Build type: Release LuaJIT 2.1.0-beta3

### Terminal name

alacritty

### Operating system/version

macOS 13.3.1

### Steps to reproduce

Move the content of `config.lua` file to separate files

<img width="822" alt="Screenshot 2023-04-19 at 2 55 58 AM" src="https://user-images.githubusercontent.com/19292809/232906115-ac59abb1-5c1f-4ead-97c8-1d48780fba2c.png">

**Comment by LostNeophyte** [comment]
put the files in /lua/user subfolder and require them like this `user.file`
