### ISSUE TITLE
Ftplugin files reset after LvimUpdate

### ISSUE THREAD

**Issue by nochzato** [LunarVim/LunarVim#4062]
### Problem description

So I had my typescript.lua file populated with the following content:

```
require("lvim.lsp.manager").setup("tailwindcss")
require("lvim.lsp.manager").setup("tsserver")

local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup {
  { name = "eslint_d" },
  { name = "prettierd" },
}

local linters = require "lvim.lsp.null-ls.linters"
linters.setup {
  { name = "eslint_d" },
}
```
After running :LvimUpdate, all content, except top two lines, gets deleted. 

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.9.0

### Terminal name

Default Pop!_OS terminal

### Operating system/version

Pop!_OS 22.04

### Steps to reproduce

1, Populate ../ftplugin/typescript.lua
2. Run :LvimUpdate

**Comment by LostNeophyte** [comment]
What's the full path of the file? It's supposed to be in .config, don't edit files in .local

**Comment by nochzato** [comment]
> What's the full path of the file? It's supposed to be in .config, don't edit files in .local

oh, i see. so i have to create .config/lvim/ftplugin/typescript.lua?

**Comment by LostNeophyte** [comment]
yes
