### ISSUE TITLE
Cannot disable automatic installation of pylyzer

### ISSUE THREAD

**Issue by dycw** [LunarVim/LunarVim#4063]
### Problem description

I've just switched from 1.2 to nightly, so I noticed as I write Python the new `pylyzer` LSP.

Admittedly I am unclear on how to configure it (specifically how to have it plug into my virtual environment), but out-of-the-box it's not helpful, and I want to disable it.

There appear to be two things I can use:

https://github.com/LunarVim/LunarVim/blob/9ecad22dbb6ad4bbe1c02bf654ca92be59a56808/utils/installer/config.example.lua#L53-L57

I've tried `vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "pylyzer" })` but this doesn't seem to work. I'll have to disable all LSP installations for now, but that won't be helpful in the long run. Any help?

### LunarVim version

master-9ecad22d

### Neovim version (>= 0.8.0)

0.9.0

### Operating system/version

Ubuntu 22.04

### Affected language servers

pylyzer

### Steps to reproduce

My config is [here](https://github.com/dycw/dotfiles/blob/eb82b347f5ccb60ea622531f276d0a8bd375ce3e/lvim/config.lua).

### Actual behavior

Still installs `pylyzer` when I open a Python file.

### support info

![image](https://user-images.githubusercontent.com/10572122/233222012-f366ce1d-ee99-44bc-b610-a9e7a7195c2c.png)

![image](https://user-images.githubusercontent.com/10572122/233222081-bc7b6c18-c7de-4663-96d5-805708071322.png)

**Comment by salimp2009** [comment]
> ### Problem description
> I've just switched from 1.2 to nightly, so I noticed as I write Python the new `pylyzer` LSP.
> 
> Admittedly I am unclear on how to configure it (specifically how to have it plug into my virtual environment), but out-of-the-box it's not helpful, and I want to disable it.
> 
> There appear to be two things I can use:
> 
> https://github.com/LunarVim/LunarVim/blob/9ecad22dbb6ad4bbe1c02bf654ca92be59a56808/utils/installer/config.example.lua#L53-L57
> 
> I've tried `vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "pylyzer" })` but this doesn't seem to work. I'll have to disable all LSP installations for now, but that won't be helpful in the long run. Any help?
> 
> ### LunarVim version
> master-9ecad22d
> 
> ### Neovim version (>= 0.8.0)
> 0.9.0
> 
> ### Operating system/version
> Ubuntu 22.04
> 
> ### Affected language servers
> pylyzer
> 
> ### Steps to reproduce
> My config is [here](https://github.com/dycw/dotfiles/blob/eb82b347f5ccb60ea622531f276d0a8bd375ce3e/lvim/config.lua).
> 
> ### Actual behavior
> Still installs `pylyzer` when I open a Python file.
> 
> ### Expected behavior
> _No response_
> 
> ### support info
> ![image](https://user-images.githubusercontent.com/10572122/233222012-f366ce1d-ee99-44bc-b610-a9e7a7195c2c.png)
> 
> ![image](https://user-images.githubusercontent.com/10572122/233222081-bc7b6c18-c7de-4663-96d5-805708071322.png)
> 
> ### logs
> _No response_
> 
> ### Screenshots
> _No response_

I had the same problem and added this to my config to disable pylyzer
`vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "pylyzer" })`
it worked. I got pyright, black, isort, flake8 all attached and highligting works too

**Comment by dycw** [comment]
Hi @salimp2009 , unfortunately I've not been able to disable `pylyzer`, it still keeps getting installed.

Can you tell me a bit about the `:Mason` menu method (this is installed despite me having the same `skipped_servers` line that we both use)? What do I do?

<img width="701" alt="image" src="https://user-images.githubusercontent.com/10572122/233769534-e22f1b79-cd9c-47f5-985b-d0df3009bc36.png">

**Comment by salimp2009** [comment]
> Hi @salimp2009 , I can indeed get `pylyzer` to be disabled; my mistake was to miss the `:LvimCacheReset` directive in the comment! Thanks!

After that I learned pylyzer is better a static analyzer, lsp and linter than pyright. Now I am trying to put it pack for python but somehow I could not manage that :)

**Comment by dycw** [comment]
Is it not just `:LspInstall pylyzer`?

I personally am excited to use it, but it I'll need to configure it a fair bit as I've done `pyright` for a while in order to get value (and more importantly: no unnecessary noise) out of it.

**Comment by salimp2009** [comment]
> Is it not just `:LspInstall pylyzer`?
> 
> I personally am excited to use it, but it I'll need to configure it a fair bit as I've done `pyright` for a while in order to get value (and more importantly: no unnecessary noise) out of it.

ok. I did install pyright with :Mason and  tried with adding
require("lspconfig").pylyzer.setup{}
but did not work. so i will go with pyright right now until I figure that out. no big deal
