### ISSUE TITLE
Support for coc-pyright

### ISSUE THREAD

**Issue by Zundrium** [LunarVim/LunarVim#4065]
### Feature Description

At the moment, LunarVim's standard Python LSP [pyright](https://github.com/microsoft/pyright) has [no intentions](https://github.com/microsoft/pyright/issues/4263#issuecomment-1335585261) to add code actions to the solution.

However, in that same response from one of pyright's maintainers, they suggest to use [coc-pyright](https://github.com/fannheyward/coc-pyright) for code actions in Python.

Me, enjoying LunarVim's godlike out-of-the-box experience, would love to see a way to support this plugin or how to implement this, as my config skills are limited. 

This also concerns these closed issues:
- https://github.com/LunarVim/LunarVim/issues/407
- https://github.com/LunarVim/LunarVim/issues/3220

Any help appreciated :)

**Comment by LostNeophyte** [comment]
we don't use coc.nvim and currently don't plan to switch, you can use a different lsp that supports this feature

**Comment by chaozwn** [comment]
> we don't use coc.nvim and currently don't plan to switch, you can use a different lsp that supports this feature

It is necessary for him to have this demand. pyright is so bad. it with out code action.
