### ISSUE TITLE
Low priority suggestion: `mini.nvim`

### ISSUE THREAD

**Issue by riotrah** [LunarVim/LunarVim#4068]
### Feature Description

Hello.

I believe - in line with Lunarvim's aim of a rich, IDE-like, out-of-the-box nvim experience - incorporating [mini.nvim](https://github.com/echasnovski/mini.nvim) might be an interesting choice for one of the default plugins available. 

I'm not saying that it's hard to incorporate as a user plugin, or that this is a must-have/"big deal" by any means, nor that it would be easy to incorporate as a core plugin either (not idea really tbh), but I thought I'd at least put it on y'all's radar if not already familiar.

Anyways, aside from that, thank you for everything. I would have seriously never touched vim if it weren't for this project, and I use vim _literally **every single day**_ now, across OSes (win, mac, wsl ubuntu, android/termux!)

**Comment by kobzar** [comment]
The MIni.nvim is perfect and powerful plugin. But really I don't see any important properties to add it in core plugin. 
There many other plugin must be added as core like code runner. But anyway what are from mini you are need?

**Comment by kobzar** [comment]
I think the best idea to move this topic to vote. But i think no one will add this to core plugins list.

**Comment by kobzar** [comment]
Closed as don't interest for anyone. 
But You can add it by yourself in any time.
