### ISSUE TITLE
Suggestions: Return to last edit position when opening files

### ISSUE THREAD

**Issue by simonfontana** [LunarVim/LunarVim#4071]
### Feature Description

I've used this vimrc script for ages and it's served me well: https://stackoverflow.com/a/14449484/1516699

I think it should be a "sane default" in LunarVim considering most IDEs have this preset.

**Comment by simonfontana** [comment]
@kobzar it works great, I'll switch to that. 

But my main point was that this should be part of the default configuration.

**Comment by kobzar** [comment]
Some time ago i was used some plugins, but this variant is best for me. 
But make it default is wrong. Some one want to open project and last tabs etc.

**Comment by juniway** [comment]
This doesn't work on my machine, I wonder why? I add a print statement in the event "BufReadPost", and it wasn't triggerred when I open a file.
