### ISSUE TITLE
Suggestions: use ALT-h, ALT-l to change buffer

### ISSUE THREAD

**Issue by simonfontana** [LunarVim/LunarVim#4072]
### Feature Description

Since CTRL-h/j/k/l moves between windows I think a similar keybinding should be used to move between buffers (open files). I know \<Leader\>-b-b and \<Leader\>-b-n is the current keybinding but I find it a bit awkward to use.  It requires 3 key-presses. 

I suggest using ALT-h, ALT-l instead and from what I see they don't have a keybinding currently. The advantages are:
1. Jumping windows and changing buffers are closely related and should have similar keybindings. 
2. Requires 1 + n key-presses, where n is the number of buffers to jump. This compares to the current binding which requires 3*n key-presses to jump n buffers. 
3. Much faster switching between buffers since \<L\>-b-b doesn't support repetitive action, e.g. 3\<L\>-b-b only jumps to previous buffer. Using \<L\>-b-j is not as fast (for me) because I have to look at the screen before I can jump. I just can't get used to it, remembering the relative position of my buffer is easier for me than remembering the buffer alias.

Disadvantage:
1. ALT-j and ALT-k are bound to move line(s) up/down, so it may be confusing to bind ALT-h, ALT-l to something completely different.

I feel this would be a great improvement (which I'm already using). But it is opinionated so I understand if you don't want to change it.

### Describe the alternatives you have considered

Supporting repeating action for \<L\>-b-b and \<L\>-b-n would also be an improvement.

_Edit: Fixed all \<tags\> that were removed in my first post. Sorry about that._

**Comment by kobzar** [comment]
By default keys Shift + H  and Shift + L   is for  buffer select.
But you can remap your keys to Alt +H  Alt + L for yourself.

**Comment by brneor** [comment]
`S-l` and `S-h` [has long been removed as default for selecting buffers](https://github.com/LunarVim/LunarVim/commit/45f9825d1e666890ed37baf15a14707ae40e5cff).
