### ISSUE TITLE
Change dapui layout to avoid text overflow cluttering the code

### ISSUE THREAD

**Issue by WillianFuks** [LunarVim/LunarVim#4073]
### Feature Description

This is more of an idea for discussion. What I've been realizing here is that using the dapui layout where the `DAP Scopes` element is at the right side of the window doesn't seem to lead to a very friendly UX/UI. I took these pictures in the hopes to better explain this:

Here's a picture of a normal debugging and I've positioned the cursor at a text that doesn't cause text overflow:

![lvim_dapui_before](https://user-images.githubusercontent.com/4665485/233805226-f8027521-87f7-48e5-bb15-22da99abb803.png)

But now if I move the cursor to the `results` object this happens:

![lvim_dapui_after](https://user-images.githubusercontent.com/4665485/233805250-2ea64ef7-929e-462b-9888-dfab5465b84e.png)

As I was debugging and reading through the classes parameters and methods the text kept moving around and the experience was not that great.

I'm opening this issue more as an opinion of mine being expressed and if the community may think the same maybe leaving those at the left side as default would lead to a better debugging experience as we'd be able to cycle through the options without losing track of the text to read (still the overflow happens but to the right side which doesn't seem to be too invasive. Don't know if this overflowing options is "togglable" as well).

**Comment by WillianFuks** [comment]
Turns out I just found that the option:

`lvim.builtin.dap.ui.config.expand_lines = false`

that avoids the line expansion. I wonder if leaving that as default would be a better approach to the UI.

**Comment by kobzar** [comment]
Some one like the default options was true, else one - false.
Thats why VIM is the best for all. Everyone can setup it for himself.
