### ISSUE TITLE
Error running lldb-vscode: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by morenohernan** [LunarVim/LunarVim#4074]
### Problem description

Getting error when trying to debug in rust. See the error:
Error executing vim.schedule lua callback: ...l/share/lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap.lua:493: ...lunarvim/site/pack/lazy/opt/nvim-dap/lua
/dap/session.lua:1321: Error running lldb-vscode: ENOENT: no such file or directory
stack traceback:
        [C]: in function 'trigger_run'
        ...l/share/lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap.lua:493: in function 'run'
        ...ite/pack/lazy/opt/rust-tools.nvim/lua/rust-tools/dap.lua:151: in function <...ite/pack/lazy/opt/rust-tools.nvim/lua/rust-tools/dap.lua:85>
Press ENTER or type command to continue

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/700619/233808593-40e3b347-8a65-4a2b-861b-b14fd66fdad9.png">

### LunarVim version

master-15c1f79b

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-1355+gb2d10aa01

### Terminal name

iTerm2

### Operating system/version

macOS Ventura 13.3.1

### Steps to reproduce

1- Fresh install of lunarvim + config of rust-ide starter (according to this link: https://github.com/LunarVim/LunarVim/issues/3320) 

2- Here my config.lua

--[[
 THESE ARE EXAMPLE CONFIGS FEEL FREE TO CHANGE TO WHATEVER YOU WANT
 `lvim` is the global options object
]]

-- vim options
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.relativenumber = true

-- general
lvim.log.level = "info"
lvim.format_on_save = {
  enabled = true,
  pattern = "*.lua",
  timeout = 1000,
}
lvim.leader = "space"

-- add your own keymapping
lvim.keys.normal_mode["<C-s>"] = ":w<cr>"

lvim.builtin.alpha.active = true
lvim.builtin.alpha.mode = "dashboard"
lvim.builtin.terminal.active = true
lvim.builtin.nvimtree.setup.view.side = "left"
lvim.builtin.nvimtree.setup.renderer.icons.show.git = false

-- Automatically install missing parsers when entering buffer
lvim.builtin.treesitter.auto_install = true

local formatters = require("lvim.lsp.null-ls.formatters")
formatters.setup({
  { command = "rustfmt", filetypes = { "rust" } },
})

lvim.builtin.treesitter.ensure_installed = {
  "lua",
  "rust",
  "toml",
}

vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "rust_analyzer" })

local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup {
  { command = "stylua", filetypes = { "lua" } },
}

local mason_path = vim.fn.glob(vim.fn.stdpath "data" .. "/mason/")
local codelldb_adapter = {
  type = "server",
  port = "${port}",
  executable = {
    command = mason_path .. "bin/codelldb",
    args = { "--port", "${port}" },
    -- On windows you may have to uncomment this:
    -- detached = false,
  },
}
local extension_path = vim.env.HOME .. '/.vscode/extensions/vadimcn.vscode-lldb-1.9.0/'
local codelldb_path = extension_path .. 'adapter/codelldb'
local liblldb_path = extension_path .. 'lldb/lib/liblldb.dylib'  

pcall(function()
  require("rust-tools").setup {
    tools = {
      executor = require("rust-tools/executors").termopen, -- can be quickfix or termopen
      reload_workspace_from_cargo_toml = true,
      runnables = {
        use_telescope = true,
      },
      inlay_hints = {
        auto = true,
        only_current_line = false,
        show_parameter_hints = false,
        parameter_hints_prefix = "<-",
        other_hints_prefix = "=>",
        max_len_align = false,
        max_len_align_padding = 1,
        right_align = false,
        right_align_padding = 7,
        highlight = "Comment",
      },
      hover_actions = {
        border = "rounded",
      },
      on_initialized = function()
        vim.api.nvim_create_autocmd({ "BufWritePost", "BufEnter", "CursorHold", "InsertLeave" }, {
          pattern = { "*.rs" },
          callback = function()
            local _, _ = pcall(vim.lsp.codelens.refresh)
          end,
        })
      end,
    },
 
    dap = {
      adapter = require('rust-tools.dap').get_codelldb_adapter(
            codelldb_path, liblldb_path)     
    },
    server = {
      on_attach = function(client, bufnr)
        require("lvim.lsp").common_on_attach(client, bufnr)
        local rt = require "rust-tools"
        vim.keymap.set("n", "K", rt.hover_actions.hover_actions, { buffer = bufnr })
      end,

      capabilities = require("lvim.lsp").common_capabilities(),
      settings = {
        ["rust-analyzer"] = {
          lens = {
            enable = true,
          },
          checkOnSave = {
            enable = true,
            command = "clippy",
          },
        },
      },
    },
  }
end)

lvim.builtin.dap.on_config_done = function(dap)
  dap.adapters.codelldb = codelldb_adapter
  dap.configurations.rust = {
    {
      name = "Launch file",
      type = "codelldb",
      request = "launch",
      program = function()
        return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
      end,
      cwd = "${workspaceFolder}",
      stopOnEntry = false,
    },
  }
end

vim.api.nvim_set_keymap("n", "<m-d>", "<cmd>RustOpenExternalDocs<Cr>", { noremap = true, silent = true })

lvim.builtin.which_key.mappings["C"] = {
  name = "Rust",
  r = { "<cmd>RustRunnables<Cr>", "Runnables" },
  t = { "<cmd>lua _CARGO_TEST()<cr>", "Cargo Test" },
  m = { "<cmd>RustExpandMacro<Cr>", "Expand Macro" },
  c = { "<cmd>RustOpenCargo<Cr>", "Open Cargo" },
  p = { "<cmd>RustParentModule<Cr>", "Parent Module" },
  d = { "<cmd>RustDebuggables<Cr>", "Debuggables" },
  v = { "<cmd>RustViewCrateGraph<Cr>", "View Crate Graph" },
  R = {
    "<cmd>lua require('rust-tools/workspace_refresh')._reload_workspace_from_cargo_toml()<Cr>",
    "Reload Workspace",
  },
  o = { "<cmd>RustOpenExternalDocs<Cr>", "Open External Docs" },
  y = { "<cmd>lua require'crates'.open_repository()<cr>", "[crates] open repository" },
  P = { "<cmd>lua require'crates'.show_popup()<cr>", "[crates] show popup" },
  i = { "<cmd>lua require'crates'.show_crate_popup()<cr>", "[crates] show info" },
  f = { "<cmd>lua require'crates'.show_features_popup()<cr>", "[crates] show features" },
  D = { "<cmd>lua require'crates'.show_dependencies_popup()<cr>", "[crates] show dependencies" },
}

lvim.plugins = {
  -- RUST
  {
    "simrat39/rust-tools.nvim",
    config = function()
      -- local lsp_installer_servers = require("nvim-lsp-installer.servers")
      -- local _, requested_server = lsp_installer_servers.get_server("rust_analyzer")
      require("rust-tools").setup({
        tools = {
          autoSetHints = true,
          -- hover_with_actions = true,
          -- options same as lsp hover / vim.lsp.util.open_floating_preview()
          hover_actions = {

            -- the border that is used for the hover window
            -- see vim.api.nvim_open_win()
            border = {
              { "╭", "FloatBorder" },
              { "─", "FloatBorder" },
              { "╮", "FloatBorder" },
              { "│", "FloatBorder" },
              { "╯", "FloatBorder" },
              { "─", "FloatBorder" },
              { "╰", "FloatBorder" },
              { "│", "FloatBorder" },
            },

            -- whether the hover action window gets automatically focused
            -- default: false
            auto_focus = true,
          },
          runnables = {
            use_telescope = true,
          },
        },
        server = {
          on_init = require("lvim.lsp").common_on_init,
          on_attach = function(client, bufnr)
            require("lvim.lsp").common_on_attach(client, bufnr)
            local rt = require("rust-tools")
            -- Hover actions
            vim.keymap.set("n", "<C-space>", rt.hover_actions.hover_actions, { buffer = bufnr })
            -- Code action groups
            vim.keymap.set("n", "<leader>lA", rt.code_action_group.code_action_group, { buffer = bufnr })
          end,
        },
      })
    end,
    ft = { "rust", "rs" },
  },
}

**Comment by kobzar** [comment]
You are try to join differents settings. 
Get clear config and add all from this to rust support 
https://github.com/LunarVim/starter.lvim/blob/rust-ide/config.lua

**Comment by morenohernan** [comment]
Hi @kobzar , I just did that. But the error is the same.  My configuration is the same as https://github.com/LunarVim/starter.lvim/blob/rust-ide/config.lua

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/700619/234128061-1f5c4792-2a92-4cc4-abd8-98cc046fa2eb.png">

**Comment by ljtpetersen** [comment]
I had this same issue. My fix was the following. First, download and install and make sure it works the `codelldb` extension from their github, https://github.com/vadimcn/codelldb/releases.
The .vsix files are just zip files, so you can use `unzip` or rename it to a `.zip` file and open it. Inside, there is a directory called `extension`. I recommend keeping it whole, ie not moving things around inside that directory. I just copied it to `~/.local/codelldb` myself, though anywhere else works. Then, in the `lvim` configuration, replace

```
local mason_path = vim.fn.glob(vim.fn.stdpath "data" .. "/mason/")
local codelldb_adapter = {
  type = "server",
  port = "${port}",
  executable = {
    command = mason_path .. "bin/codelldb",
    args = { "--port", "${port}" },
    -- On windows you may have to uncomment this:
    -- detached = false,
  },
}
```

in the config with

```
local codelldb_adapter = {
  type = "server",
  port = "${port}",
  executable = {
    command = "{PATH TO THE extension FOLDER}/adapter/codelldb",
    args = { "--port", "${port}" },
    -- On windows you may have to uncomment this:
    -- detached = false,
  },
}
```

Thus, in my case, I had

```
local codelldb_adapter = {
  type = "server",
  port = "${port}",
  executable = {
    command = "/home/jpetersen/.local/codelldb/adapter/codelldb",
    args = { "--port", "${port}" },
    -- On windows you may have to uncomment this:
    -- detached = false,
  },
}
```

**Comment by daibertdiego** [comment]
Same issue here. Changing the path to downloaded codelldb didn't work.

**Comment by d3-dmitriy-onypko** [comment]
I can confirm changing the path fixes this issue. 
Make sure to use absolute path for codelldb

**Comment by daibertdiego** [comment]
Still not working. 
I tried different versions of the codelldb. I also tried pointing to codelldb from .vscode extensions, but I'm always getting the same issue. 
I'm only using the absolute path. 

Here are my configuration and healtcheck. I appreciate any help. Thanks in advance. 

```

==============================================================================
crates: require("crates.health").check()

Checking for required plugins ~
- OK plenary.nvim installed
- OK null-ls.nvim installed

Checking for external dependencies ~
- OK curl installed
- OK open installed

==============================================================================
hop: require("hop.health").check()

Ensuring keys are unique ~
- OK Keys are unique

Checking for deprecated features ~
- OK All good

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.0.1
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `require("mason-registry.index")` is installed.
- OK Registry `github.com/mason-org/mason-registry version: 2023-05-09-annual-chard` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.21.3 built on darwin21.3.0.`
- OK curl: `curl 7.87.0 (x86_64-apple-darwin22.0) libcurl/7.87.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0`
- OK gzip: `Apple gzip 403.100.6`
- OK tar: `bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
- OK bash: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- OK Ruby: `ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22]`
- WARNING node: unsupported version `v10.19.0`
  - ADVICE:
    - Node version must be >= 14
- OK cargo: `cargo 1.66.0 (d65d197ad 2022-11-15)`
- OK RubyGem: `3.0.3.1`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK npm: `6.13.4`
- OK python3: `Python 3.10.9`
- OK Go: `go version go1.19.4 darwin/amd64`
- OK java: `openjdk version "19.0.1" 2022-10-18`
- OK javac: `javac 19.0.1`
- OK pip3: `pip 22.3.1 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Tue May  9 11:52:40 2023.
  Install and authenticate via gh-cli to increase rate limit.

==============================================================================
null-ls: require("null-ls.health").check()

- crates.nvim: cannot verify if the command is an executable.

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- WARNING Missing user config file: /Users/diegodaibert/.config/lvim/init.vim
  - ADVICE:
    - :help |nvim-from-vim|

Runtime ~
- OK $VIMRUNTIME: /usr/local/Cellar/neovim/0.9.0/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=^H`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $TERM_PROGRAM="tmux"
- $COLORTERM="truecolor"

tmux ~
- OK escape-time: 10
- OK focus-events: on
- $TERM: screen-256color

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v10.19.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "22.4.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- OK Clipboard tool found: pbcopy

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set.  Searching for python3 in the environment.
- Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
- Executable: /usr/local/bin/python3
- Other python executable: /usr/bin/python3
- Python version: 3.10.9
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

Node.js provider (optional) ~
- Node.js: v10.19.0
- WARNING Missing "neovim" npm (or yarn, pnpm) package.
  - ADVICE:
    - Run in shell: npm install -g neovim
    - Run in shell (if you use yarn): yarn global add neovim
    - Run in shell (if you use pnpm): pnpm install -g neovim
    - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /Users/diegodaibert/.local/state/lvim/lsp.log
- Log size: 201 KB

vim.lsp: Active Clients ~
- No active clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: comment    ABI: 13, path: /Users/diegodaibert/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/parser/comment.so
- OK Parser: go         ABI: 14, path: /Users/diegodaibert/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/parser/go.so
- OK Parser: java       ABI: 14, path: /Users/diegodaibert/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/parser/java.so
- OK Parser: json       ABI: 14, path: /Users/diegodaibert/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/parser/json.so
- OK Parser: lua        ABI: 13, path: /Users/diegodaibert/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/parser/lua.so
- OK Parser: markdown_inline ABI: 13, path: /Users/diegodaibert/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/parser/markdown_inline.so
- OK Parser: query      ABI: 14, path: /Users/diegodaibert/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/parser/query.so
- OK Parser: regex      ABI: 13, path: /Users/diegodaibert/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/parser/regex.so
- OK Parser: rust       ABI: 14, path: /Users/diegodaibert/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/parser/rust.so
- OK Parser: vim        ABI: 14, path: /Users/diegodaibert/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/parser/vim.so
- OK Parser: c          ABI: 13, path: /usr/local/Cellar/neovim/0.9.0/lib/nvim/parser/c.so
- OK Parser: lua        ABI: 13, path: /usr/local/Cellar/neovim/0.9.0/lib/nvim/parser/lua.so
- OK Parser: query      ABI: 14, path: /usr/local/Cellar/neovim/0.9.0/lib/nvim/parser/query.so
- OK Parser: vim        ABI: 14, path: /usr/local/Cellar/neovim/0.9.0/lib/nvim/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /usr/local/Cellar/neovim/0.9.0/lib/nvim/parser/vimdoc.so

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"ys"**
- rhs: `<Plug>(nvim-surround-normal)`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"yS"**
- rhs: `<Plug>(nvim-surround-normal-line)`
- WARNING buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"c"**
- old rhs: `<CMD>edit /Users/diegodaibert/.config/lvim/config.lua <CR>`
- new rhs: `<cmd>lua require("which-key").show("c", {mode = "n", auto = true})<cr>`
- WARNING buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>dr"**
- old rhs: `<cmd>lua require'dap'.continue()<cr>`
- new rhs: `<cmd>lua require'dap'.repl.toggle()<cr>`
- WARNING buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>db"**
- old rhs: `<cmd>lua require'dap'.toggle_breakpoint()<cr>`
- new rhs: `<cmd>lua require'dap'.step_back()<cr>`
- WARNING buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>dt"**
- old rhs: `<cmd>lua require'dap'.repl.toggle()<cr>`
- new rhs: `<cmd>lua require'dap'.toggle_breakpoint()<cr>`
- WARNING buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>du"**
- old rhs: `<cmd>lua require('dapui').toggle()<cr>`
- new rhs: `<cmd>lua require'dap'.step_out()<cr>`
- WARNING buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>do"**
- old rhs: `<cmd>lua require'dap'.step_over()<cr>`
- new rhs: `<cmd>lua require'dap'.step_out()<cr>`
```

My rust_tools.lua file

```

local M = {}

M.config = function()
  local status_ok, rust_tools = pcall(require, "rust-tools")
  if not status_ok then
    return
  end

  local opts = {
    tools = {
      executor = require("rust-tools/executors").termopen, -- can be quickfix or termopen
      reload_workspace_from_cargo_toml = true,
      inlay_hints = {
        auto = true,
        only_current_line = false,
        show_parameter_hints = true,
        parameter_hints_prefix = "<-",
        other_hints_prefix = "=>",
        max_len_align = false,
        max_len_align_padding = 1,
        right_align = false,
        right_align_padding = 7,
        highlight = "Comment",
      },
      hover_actions = {
        border = {
          { "╭", "FloatBorder" },
          { "─", "FloatBorder" },
          { "╮", "FloatBorder" },
          { "│", "FloatBorder" },
          { "╯", "FloatBorder" },
          { "─", "FloatBorder" },
          { "╰", "FloatBorder" },
          { "│", "FloatBorder" },
        },
        auto_focus = true,
      },
    },
    server = {
      on_attach = require("lvim.lsp").common_on_attach,
      on_init = require("lvim.lsp").common_on_init,
      settings = {
        ["rust-analyzer"] = {
          inlayHints = { locationLinks = false },
        },
      },
    },
  }
  -- local mason_path = vim.fn.glob(vim.fn.stdpath "data" .. "/mason/packages/codelldb/extension/")
  local mason_path = "/Users/diegodaibert/.local/codelldb/extension/"
  -- local mason_path = "/Users/diegodaibert/.local/lvim/mason/packages/codelldb/extension"
  local vscode_path = "/Users/diegodaibert/.vscode/extensions/vadimcn.vscode-lldb-1.9.1/"

  local path = ""
  local debugger_found = true
  if M.dir_exists(mason_path) then
    path = mason_path
  elseif M.dir_exists(vscode_path) then
    path = vscode_path
  else
    debugger_found = false
    vim.notify("please install codelldb using :Mason or via vscode", vim.log.levels.WARN)
  end

  if debugger_found then
    local codelldb_path = path .. "adapter/codelldb"
    local liblldb_path = path .. "lldb/lib/liblldb.so"

    if vim.fn.has "mac" == 1 then
      liblldb_path = path .. "lldb/lib/liblldb.dylib"
    end

    if vim.fn.filereadable(codelldb_path) and vim.fn.filereadable(liblldb_path) then
      print(codelldb_path)
      print(liblldb_path)
      opts.dap = {
        adapter = require("rust-tools.dap").get_codelldb_adapter(codelldb_path, liblldb_path),
      }
    else
      vim.notify("please reinstall codellb, i cannot find liblldb or codelldb itself", vim.log.levels.WARN)
    end
  end
  rust_tools.setup(opts)
end

M.dir_exists = function(file)
  local ok, _, code = os.rename(file, file)
  if not ok then
    if code == 13 then
      -- Permission denied, but it exists
      return true
    end
  end
  return ok
end

return M
```

![image](https://github.com/LunarVim/LunarVim/assets/25724941/f4444ad2-7079-47e7-9554-ae83f0b9a82e)

**Comment by sin1111yi** [comment]
I am using LazyVim on manjaro, and the same issue happened.
here's my dap-config.lua
```lua
return {
  {
    "mfussenegger/nvim-dap",

    config = function()
      local dap = require("dap")

      dap.adapters.codelldb = {
        type = "server",
        port = "${port}",
        executable = {
          command = "~/Tools/codelldb/adapter/codelldb",
          args = { "--port", "${port}" },
        },
      }

      dap.configurations.cpp = {
        {
          name = "Launch file",
          type = "codelldb",
          request = "launch",
          program = function()
            return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
          end,
          cwd = "${workspaceFolder}",
          stopOnEntry = false,
        },
      }

      dap.configurations.c = dap.configurations.cpp
    end,
  },
}
```

I made this all accroding to [C/C++/Rust(via codelldb)](https://github.com/mfussenegger/nvim-dap/wiki/C-C---Rust-(via--codelldb)), the only difference is that after unzip the *.visx* file, I moved all files in *codelldb/extension/* to *codelldb/*, just like the configuration in the lua code above. 
Here are some feather information:
1. codelldb path
```bash
>ls -l
-rwxr-xr-x 1 sin1111yi sin1111yi  1107328  4月30日 03:48 codelldb
-rwxr-xr-x 1 sin1111yi sin1111yi 10647568  4月30日 03:48 libcodelldb.so
drwxr-xr-x 3 sin1111yi sin1111yi     4096  5月13日 03:09 scripts
>pwd
/home/sin1111yi/Tools/codelldb/adapter
```
2. error infomation
```
E5108: Error executing lua: /home/sin1111yi/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:493: ...11yi/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1158: ENOENT: no such file or directory
stack traceback:
	[C]: in function 'trigger_run'
	/home/sin1111yi/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:493: in function 'run'
	/home/sin1111yi/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:406: in function 'cb'
	...sin1111yi/.local/share/nvim/lazy/nvim-dap/lua/dap/ui.lua:34: in function 'pick_if_many'
	/home/sin1111yi/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:400: in function 'select_config_and_run'
	/home/sin1111yi/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:871: in function 'continue'
	...vim/lazy/LazyVim/lua/lazyvim/plugins/extras/dap/core.lua:75: in function <...vim/lazy/LazyVim/lua/lazyvim/plugins/extras/dap/core.lua:75>
```

I had tried the same configuration on LunarVim too, and it stiil work un-normally. Maybe this issue is occured by nvim-dap or some other things?

**Comment by morenohernan** [comment]
I've switched to AstroNvim with its community pack for rust (https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/pack/rust) and it works there.

**Comment by sin1111yi** [comment]
> I had this same issue. My fix was the following. First, download and install and make sure it works the `codelldb` extension from their github, https://github.com/vadimcn/codelldb/releases. The .vsix files are just zip files, so you can use `unzip` or rename it to a `.zip` file and open it. Inside, there is a directory called `extension`. I recommend keeping it whole, ie not moving things around inside that directory. I just copied it to `~/.local/codelldb` myself, though anywhere else works. Then, in the `lvim` configuration, replace
> 
> ```
> local mason_path = vim.fn.glob(vim.fn.stdpath "data" .. "/mason/")
> local codelldb_adapter = {
>   type = "server",
>   port = "${port}",
>   executable = {
>     command = mason_path .. "bin/codelldb",
>     args = { "--port", "${port}" },
>     -- On windows you may have to uncomment this:
>     -- detached = false,
>   },
> }
> ```
> 
> in the config with
> 
> ```
> local codelldb_adapter = {
>   type = "server",
>   port = "${port}",
>   executable = {
>     command = "{PATH TO THE extension FOLDER}/adapter/codelldb",
>     args = { "--port", "${port}" },
>     -- On windows you may have to uncomment this:
>     -- detached = false,
>   },
> }
> ```
> 
> Thus, in my case, I had
> 
> ```
> local codelldb_adapter = {
>   type = "server",
>   port = "${port}",
>   executable = {
>     command = "/home/jpetersen/.local/codelldb/adapter/codelldb",
>     args = { "--port", "${port}" },
>     -- On windows you may have to uncomment this:
>     -- detached = false,
>   },
> }
> ```

I tried this configurations, and it works! But this phenomenon is wried. When I using the path point to the codelldb I download by myself, this issue still exist.

**Comment by OkieOth** [comment]
Under Ubuntu lldb-vscode was installed with `apt-get install lldb`, but the binary wasn't in the search path. After I created a related sym link it worked for me. (Ubuntu 22.04 LTS)

`cd /usr/bin; sudo ln -s ../lib/llvm-14/bin/lldb-vscode`

**Comment by JoseCarlosGlez** [comment]
@OkieOth Man you saved my life

**Comment by CodeConnoisseur74** [comment]
worked for me. Thanks @OkieOth !

**Comment by bkp5190** [comment]
I ran into this same issue on MacOS using NvChad, the fix is this: 

brew install llvm
Add $(brew --prefix)/opt/llvm/bin your PATH, usually in your ~/.bashrc or .zshrc file
