### ISSUE TITLE
lvim is not recognized as an internal or external command

### ISSUE THREAD

**Issue by cuarangme123** [LunarVim/LunarVim#4076]
### Problem description

when I finish install after following step on the website and  type the lvim command 
It's show me an error 
lvim : The term 'lvim' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ lvim
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (lvim:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

### LunarVim version

1.3

### Neovim version (>= 0.8.0)

NVIM 0.8.0

### Terminal name

window terminal

### Operating system/version

window 11

### Screenshots

![image](https://user-images.githubusercontent.com/96458601/233820340-874c44eb-1eac-49bd-a8cb-a77036be020c.png)

**Comment by kobzar** [comment]
Release 1.3 of lvim must be used with neovim 0.9+ version. Update it, reinstall the LunarVim and check again.

**Comment by cpea2506** [comment]
Make sure you choose to create alias option when installing. Or:

```pwsh
Add-Content -Path $PROFILE -Value $("`r`nSet-Alias lvim '$INSTALL_PREFIX\bin\lvim.ps1'")
```

**Comment by cuarangme123** [comment]
> Release 1.3 of lvim must be used with neovim 0.9+ version. Update it, reinstall the LunarVim and check again.

tks for notice me <3

**Comment by kobzar** [comment]
This is help you?

**Comment by kobzar** [comment]
Close as fixed.
