### ISSUE TITLE
Lualine displays garbled characters

### ISSUE THREAD

**Issue by wutianjun5858** [LunarVim/LunarVim#4077]
### Problem description

1. install lunarvim
2. lvim open one file
3. view lualine

### LunarVim version

master-15c1f79b

### Neovim version (>= 0.8.0)

NVIM v0.9.0 Release and NVIM v0.10.0-dev

### Terminal name

terminator

### Operating system/version

manjaro22/ubuntu18.04

### Screenshots

![image](https://user-images.githubusercontent.com/25163353/233823558-f7515ae4-7535-4d0a-9438-738ce7a82945.png)

**Comment by kobzar** [comment]
This is not lvim issue. Install Nerd Fonts and choose it for your terminal
https://www.lunarvim.org/docs/installation/post-install#install-a-nerd-font

**Comment by wutianjun5858** [comment]
> This is not lvim issue. Install Nerd Fonts and choose it for your terminal https://www.lunarvim.org/docs/installation/post-install#install-a-nerd-font

I have install Nerd Fonts, so you can see some icons are normal.

**Comment by kobzar** [comment]
Some - is not all. Try another font
For example Hack Nerd Font Mono
Also try to use another terminal app like litty, alacritty....

**Comment by brneor** [comment]
@wutianjun5858 try just updating the font you're using. There was a lot of changes recently in both Lunarvim and NerdFonts regarding some glyphs.

**Comment by wutianjun5858** [comment]
> @wutianjun5858 try just updating the font you're using. There was a lot of changes recently in both Lunarvim and NerdFonts regarding some glyphs.

Yes, you are right.
