### ISSUE TITLE
Some broken symbols after upgrading to v1.3

### ISSUE THREAD

**Issue by Napam** [LunarVim/LunarVim#4086]
### Problem description

After upgrading to lvim v1.3 (from v1.2) some of the symbols became squares or japanese (or maybe chinese). Everything worked fine before upgrading. I have gotten this problem both on my mac and windows machines. I have not touched anything related to my font settings.

Here are my relevant kitty settings:
```conf
font_family Hack Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

# font_size 11.0
font_size 11.0
```

### LunarVim version

master-eaa33768

### Neovim version (>= 0.8.0)

NVIM v0.9.0

### Terminal name

kitty, Windows Terminal

### Operating system/version

macOS 13.3.1, Windows 11 (WSL2)

### Screenshots

<img width="618" alt="Screenshot 2023-04-26 at 18 03 22" src="https://user-images.githubusercontent.com/47104226/234636005-4cfdce0c-8bee-4d71-a2b7-94e91a9e2617.png">

**Comment by brneor** [comment]
Try updating your NerdFont. There was changes regarding some glyphs in both Lunarvim and NerdFonts.

**Comment by Napam** [comment]
Well, unsurprisingly that fixed the problem :P

I really didn't think that such things would change that much
