### ISSUE TITLE
Telescope Code actions config error

### ISSUE THREAD

**Issue by Lcarv20** [LunarVim/LunarVim#4089]
### Problem description

When using code actions (vim.lsp.buf.code_action()) an error message pops up with the folloing:
`_Unsupported layout_config key for the center strategy: preview_width_`

### LunarVim version

master-eaa33768

### Neovim version (>= 0.8.0)

NVIM v0.9.0

### Terminal name

Kitty

### Operating system/version

macOS 13.3.1

### Steps to reproduce

Steps to reproduce:
1. Open your code;
2. Introduce a bug;
3. open code actions.

### Screenshots

<img width="670" alt="Screenshot 2023-04-27 at 22 50 25" src="https://user-images.githubusercontent.com/42584819/234989696-e6ab129f-0d88-4d53-a24f-918ad6db0500.png">

**Comment by LostNeophyte** [comment]
I can't reproduce with empty config 
![image](https://user-images.githubusercontent.com/110467150/235306655-7d017f1d-4742-4125-9320-f619c7a8da2d.png)

**Comment by Lcarv20** [comment]
Hi there @LostNeophyte, I believe I was wrong and I think I have found the issue and it is in my config. This is where it happens:
```lua
lvim.builtin.telescope.defaults = {
  winblend = 15,
  layout_strategy = "horizontal",
  show_line = false,
  layout_config = {
    height = 0.50,
    width = 0.85,
    prompt_position = "top",
    preview_width = 0.6,
  },
  prompt_prefix = " " .. require("lcarv.icons").ui.Search .. " ",
}
```
The error seems to be with the option layout_config.preview_width, if I remove it it doesn't the error doesn't pop up again. I don't know if I am doing something wrong but I tried to follow some examples from the telescope wiki recipes section. If you would like to inspect here is my [config](https://github.com/Lcarv20/lvim).

**Comment by Lcarv20** [comment]
I will close the issue since it is not a problem with lunarvim but rather my config.

**Comment by Nullarity** [comment]
Well, I have the same issue:
```
layout_config = {
  -- preview_height = 0.7
},
```
As soon as I uncomment the 'preview_height' property, I start experiencing the same errors.

**Comment by Jaxx497** [comment]
This seems to be a Telescope related problem. I've never used LunarVim, but this thread was what helped me figure out why my code-action call was throwing an error. Removing any configuration for telescope's preview pane seems to solve the problem.
