### ISSUE TITLE
Rscript files in directory ruin the nvim-tree layout

### ISSUE THREAD

**Issue by hamzamohdzubair** [LunarVim/LunarVim#4091]
### Problem description

The nvim tree layout is distorted on lines where `.R` filenames are written.
The problem happens with only `.R` filenames. In below screenshot the tree structure as follows:
```
-- library
    | -- workarea/
    | -- CommonFunctions.R
    | -- DailyFeaturizer.R
    | -- mCore.R
    | -- PrefVecFeaturizer.cpp
```

### LunarVim version

master/fde46c4b

### Neovim version (>= 0.8.0)

part of appimage

### Terminal name

mobaxterm

### Operating system/version

centOS 7

### Steps to reproduce

1. Install using: `wget https://github.com/LunarVim/LunarVim-mono/releases/tag/master` (source: #3612 )
2. `chmod +x lvim`
3. copy it to bin directory.
4. launch a project with Rscript files (`.R`)
5. open nvimtree
6. The layout will be distorted at lines that mention the R Filenames

### Screenshots

![image](https://user-images.githubusercontent.com/13695228/235074521-02476e92-0bfd-4c68-b6c0-563aa75b26c4.png)
![image](https://user-images.githubusercontent.com/13695228/235076519-773f9f37-b66c-4812-93a4-574db32b643a.png)

**Comment by kobzar** [comment]
Check you neovim version - it must be 0.9.0+
Check Prerequisites
Use installation script 
https://www.lunarvim.org/docs/installation

**Comment by LostNeophyte** [comment]
I can't reproduce with my install on current latest master 
![image](https://user-images.githubusercontent.com/110467150/235300810-142f1dc1-f399-400f-88e3-b5259f105177.png)
 try adding `vim.opt.title=false` to your config

**Comment by hamzamohdzubair** [comment]
> Check you neovim version - it must be 0.9.0+ Check Prerequisites Use installation script https://www.lunarvim.org/docs/installation

This solved the problem for me
