### ISSUE TITLE
mason registry is unavailable

### ISSUE THREAD

**Issue by nathan22x3** [LunarVim/LunarVim#4092]
### Problem description

Open mason with `:Mason`, then the error show up (screenshot beblow)

### LunarVim version

master-4cefc895

### Neovim version (>= 0.8.0)

0.9.0

### Terminal name

Alacritty

### Operating system/version

macOS 13.1

### Screenshots

![mason registry is unavailable](https://user-images.githubusercontent.com/67423224/235081379-0846970e-2db7-4e24-bdbb-71e4418ef607.png)

**Comment by LostNeophyte** [comment]
Can you create that directory?

**Comment by nathan22x3** [comment]
Yes, i can create it manually (with `sudo`), but another error occur
![Screenshot 2023-04-28 at 14 51 12](https://user-images.githubusercontent.com/67423224/235088372-20175a24-ba5f-4fe6-b8f8-b58fa29d31f9.png)

**Comment by nathan22x3** [comment]
It's works as normal. Thanks!
