### ISSUE TITLE
are there some ways to configure the lsp_dynamic_workspace_symbols listed entry field width?

### ISSUE THREAD

**Issue by hansen6878** [LunarVim/LunarVim#4093]
### Feature Description

some symbols' path or name may be too long,  they can't be full dispalyed at lsp_dynamic_workspace_symbols list result.
For example as following picture:
![image](https://user-images.githubusercontent.com/63840235/235103496-e0369a1d-0a29-424f-b7ea-aa6ba92aba0f.png)

And the lunarvim not provide API for user config to configure the width .

However,  the telescope plugin provides setup option to configure the width for symbol path or name. The following option was copied from telescope plugin  (telescope.nvim/lua/telescope/builtin/init.lua)。
```lua
--- Lists LSP document symbols in the current workspace
--- - Default keymaps:
---   - `<C-l>`: show autocompletion menu to prefilter your query by type of symbol you want to see (i.e. `:variable:`)
---@param opts table: options to pass to the picker
---@field query string: for what to query the workspace (default: "")
---@field fname_width number: defines the width of the filename section (default: 30)
---@field symbol_width number: defines the width of the symbol section (default: 25)
---@field symbol_type_width number: defines the width of the symbol type section (default: 8)
---@field show_line boolean: if true, shows the content of the line the tag is found on (default: false)
---@field symbols string|table: filter results by symbol kind(s)
---@field ignore_symbols string|table: list of symbols to ignore
---@field symbol_highlights table: string -> string. Matches symbol with hl_group
builtin.lsp_workspace_symbols = require_on_exported_call("telescope.builtin.__lsp").workspace_symbols
```

### Support information
There is an tracked [issue  ](https://github.com/nvim-telescope/telescope.nvim/issues/2041) that i found at telescope repo
_No response_

**Comment by kobzar** [comment]
```
lvim.builtin.telescope.theme = "center"
lvim.builtin.telescope.defaults.layout_config.width = 180
```

**Comment by hansen6878** [comment]
thanks for your reply, i have tried the center theme style. and the symbol name still does not fully  display.

![image](https://user-images.githubusercontent.com/63840235/235161930-21a6f00c-dd35-4dfb-8328-8845d8a41980.png)

> ```
> lvim.builtin.telescope.theme = "center"
> lvim.builtin.telescope.defaults.layout_config.width = 180
> ```

**Comment by hansen6878** [comment]
use this method will take work:
```lua
 :lua require('telescope.builtin').lsp_workspace_symbols({fname_width = 0.5,symbol_width=0.3, symbol_type_width = 0.2})
```

**Comment by kobzar** [comment]
```
:h telescope.defaults.path_display
and play with it 
For example:
lvim.builtin.telescope.defaults.path_display = {shorten=2} 

```

**Comment by hansen6878** [comment]
> ```
> :h telescope.defaults.path_display
> 
>                                           *telescope.defaults.path_display*
>     path_display:  
>         Determines how file paths are displayed.
> 
>         path_display can be set to an array with a combination of:
>         - "hidden"    hide file names
>         - "tail"      only display the file name, and not the path
>         - "absolute"  display absolute paths
>         - "smart"     remove as much from the path as possible to only show
>                       the difference between the displayed paths.
>                       Warning: The nature of the algorithm might have a negative
>                       performance impact!
>         - "shorten"   only display the first character of each directory in
>                       the path
>         - "truncate"  truncates the start of the path when the whole path will
>                       not fit. To increase the gap between the path and the edge,
>                       set truncate to number `truncate = 3`
> 
>         You can also specify the number of characters of each directory name
>         to keep by setting `path_display.shorten = num`.
>           e.g. for a path like
>             `alpha/beta/gamma/delta.txt`
>           setting `path_display.shorten = 1` will give a path like:
>             `a/b/g/delta.txt`
>           Similarly, `path_display.shorten = 2` will give a path like:
>             `al/be/ga/delta.txt`
> ```
> 
> and play with it For example:
> 
> ```
> lvim.builtin.telescope.defaults.path_display = {shorten=2} 
> ```

it's an way to only resolve the path display problem, the symbol truncated  problem is still unresolved.
I have used the telescope builtin method， thanks for your help！
···
:lua require('telescope.builtin').lsp_workspace_symbols({fname_width = 0.5,symbol_width=0.3, symbol_type_width = 0.2})
···

![image](https://user-images.githubusercontent.com/63840235/235274252-f0243d53-6c31-4909-8f7f-c09b7592e8a6.png)

**Comment by zalegrala** [comment]
Is there a way to set `symbol_width` in config defaults?  I see it defaults to 25 in the config in several places, which seems narrow for some use cases.
