### ISSUE TITLE
Issues when trying to update (nothing happens/shows up)

### ISSUE THREAD

**Issue by DominickVale** [LunarVim/LunarVim#4094]
### Problem description

I've been using lunarvim for some time now, I used it on 2 different fresh OS installs (2 times arch linux of course).
Every time I tried updating lunarvim I had some sorts of issues. I thought I did something wrong or my setup was broken but now I'm starting to believe there's actually something wrong in lunarvim.
To put it simply: every time I tried updating, nothing ever happened.
If I updated via \<leader\>Lu inside lvim, nothing shows up and no warnings or error messages show up.
If I did it via cli with lvim +LvimUpdate +q same thing, the program just returns with no error.
So I always had to reinstall it and each time something broke even more.
This time when reinstalling I also got this error:
![image](https://user-images.githubusercontent.com/52491108/235123384-bc68a013-663c-423f-8b9e-a3f33e535f1d.png)
which made no sense to me, but since I was in a hurry I just rm -rf ~/.cache/lvim and that solved it. I was able to reinstall it.

### LunarVim version

release-1.3/neovim-0.9-e823ccb9

### Neovim version (>= 0.8.0)

NVIM v0.9.0

### Terminal name

foot

### Operating system/version

endeavourOS 6.2.12-arch1-1 

### Steps to reproduce

1. Use lvim
2. Try to update in any way
3. Won't work
4. Reinstalling causes issues (need to clear .cache/lvim to reinstall)

**Comment by brneor** [comment]
And you're sure there's a update available when you run `<leader> L u`?

**Comment by DominickVale** [comment]
I hadn't updated in a while so I'm guessing there was an update... In any case, i think it should return with a message saying that there's no update instead of total silence

**Comment by brneor** [comment]
I agree with you about a message "Lunarvim is up to date" vs total silence.

**Comment by LostNeophyte** [comment]
> I agree with you about a message "Lunarvim is up to date" vs total silence.

it does print a message if you didn't change your log level at least on 1.3, i don't remember if that happens with 1.2
![image](https://user-images.githubusercontent.com/110467150/235299821-f8cc9ded-1ccd-4df9-b15a-915ea5183509.png)

**Comment by kobzar** [comment]
> > I agree with you about a message "Lunarvim is up to date" vs total silence.
> 
> it does print a message if you didn't change your log level at least on 1.3, i don't remember if that happens with 1.2 ![image](https://user-images.githubusercontent.com/110467150/235299821-f8cc9ded-1ccd-4df9-b15a-915ea5183509.png)

On 1.2 release loglevel was “warn”.  On 1.3 release log settings is changed to “info”

**Comment by brneor** [comment]
My log level was set to warn, changed to info. Thank you all!

**Comment by kobzar** [comment]
@DominickVale does loglevel info help you?

**Comment by djotaku** [comment]
Is it not possible to update from 1.2 to 1.3?
