### ISSUE TITLE
not able to search for or within .env file

### ISSUE THREAD

**Issue by knnmran** [LunarVim/LunarVim#4096]
### Problem description

there are no search results when using "Leader + f " to search for .env file or using "Leader + s + t" to search for anything within .env file.

the .env file is visible in the left hand side explorer and it is usable upon opening.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-1023+g649742821

### Terminal name

Alacritty

### Operating system/version

macOS, Monterey, 12.6.3

**Comment by kobzar** [comment]
Lvim 1.3 neovim 0.9.0_1

```

╰─  ls -a                                                                                                                              
./  ../  .env  .git/  lancet.py  test.py
╭─kobzar[vDell] /home/kobzar/Develop/Python/(master ✚1…1)
╰─  cat .env                                                                                                                          
────────────────────────────────────────────────────────────────────
   1   │ This is my file
   2   │ Log settings there
   3   │ Just for text
───────┴────────────────────────────────────────────────────────────
```

SPS +s +t and SPS +s +f  - both is worked
![image](https://user-images.githubusercontent.com/1912842/235185179-93cbcb25-9f5b-45c4-a2ce-fac28bed4557.png)

**Comment by brneor** [comment]
@kobzar TIL about `<leader> s f`, I always struggle trying to find a file that is being ignored on git. Ty :)

Is there a way to make `<leader> s t` search for terms inside ignores files too?

**Comment by knnmran** [comment]
@kobzar, i am really new to VIM world. 

what is SPS? i tried looking it up but no luck.

**Comment by kobzar** [comment]
Hmm SPS = Space = Leader Key

**Comment by knnmran** [comment]
thanks @kobzar but this did not work for me. i will come back with an update after switching to newer versions.

**Comment by knnmran** [comment]
<img width="1509" alt="Screenshot 2023-04-29 at 12 44 31 AM" src="https://user-images.githubusercontent.com/50757957/235284012-5032753c-2fcb-4c0a-8956-d6677828993b.png">
<img width="1512" alt="Screenshot 2023-04-29 at 12 43 43 AM" src="https://user-images.githubusercontent.com/50757957/235284013-0fa357a4-2b20-4b6e-9942-e9d385ab3bb6.png">
<img width="1512" alt="Screenshot 2023-04-29 at 12 42 53 AM" src="https://user-images.githubusercontent.com/50757957/235284014-62033137-befb-4efa-99a9-52c1fcce3183.png">
<img width="1512" alt="Screenshot 2023-04-29 at 12 42 35 AM" src="https://user-images.githubusercontent.com/50757957/235284015-ac12e7ce-73db-4911-9ed6-394eaa01e8d5.png">

using LVIM release-1.3/neovim-0.9-e823ccb9

**Comment by brneor** [comment]
> As i say - the same variant, but in SPS + s + t you must input some from file data, not file name. And add git init in your project.

Yep, I know. But the search that opens with `<leader> s t` **does not search inside ignored files** by default. I was wondering if I can change this behaviour.

**Comment by kobzar** [comment]
This is not LunarVim problem. This is Telescope plugin logic.
https://github.com/nvim-telescope/telescope.nvim/issues?q=gitignore

**Comment by knnmran** [comment]
here is a maybe helpful thread on this topic:  
https://github.com/nvim-telescope/telescope.nvim/issues/2105

i can live with it but would be nice to have.
