### ISSUE TITLE
pip install failed on Ubuntu 23.04 with Python 3.11

### ISSUE THREAD

**Issue by Zheaoli** [LunarVim/LunarVim#4101]
### Problem description

In the [PEP 668](https://peps.python.org/pep-0668/), Python import a new concept named "externally managed". This is means that if some distro marked the base python environment, the `pip3 install --user pynvim` would be failed.

This thing is already happed in Ubuntu 23.04 with Python 3.11.

So. maybe is a good choice to support virtualenv support for lunarvim installation?

### LunarVim version

mater

### Neovim version (>= 0.8.0)

master

### Terminal name

Wezterm

### Operating system/version

Ubuntu 23.04

**Comment by kobzar** [comment]
This is not LunarVim problem. 
try apt-get install python3-pynvim

**Comment by Zheaoli** [comment]
https://github.com/LunarVim/LunarVim/blob/master/utils/installer/install.sh#L325-L337
@kobzar But the lunarvim installer script would install the pynvim by using pip3

**Comment by kobzar** [comment]
As i say before this is not LunarVim problem. 
For example on the neovim offical page you can find inforation about pynvim
![image](https://user-images.githubusercontent.com/1912842/235355724-cce7f0bc-b717-47b4-b6bc-e57a1a057f8d.png)

But yes , in last ubuntu LTS the people have some troubles with pip.
You every time can fix it easy by
```
mkdir -p ~/.config/pip && nano ~/.config/pip/pip.conf
```
and add nex one 
```
[global]
break-system-packages=true
```
This is it.
