### ISSUE TITLE
No LSP keymappings when editing dart

### ISSUE THREAD

**Issue by FlippingBinary** [LunarVim/LunarVim#4103]
### Problem description

I apologize in advance if this is not the proper forum to discuss this problem. I would be happy to write a pull request that contributes to the documentation's example plugin configurations once I get this figured out. 

I'm working with a flutter project now, so I installed `akinsho/flutter-tools.nvim` to bring in support for hot reloading and such. Unfortunately, LSP keyboard shortcuts such as `K`, or `gd` do not function as expected when I'm editing dart files. I strongly suspect that I haven't configured it correctly, but I tried to use an example configuration provided in [another issue](https://github.com/LunarVim/LunarVim/issues/439#issuecomment-923320127) which is no longer compatible with v1.3. Their configuration that I based my configuration on is copied here for reference:

```lua
lvim.lsp.override = { "dart" }
lvim.plugins = {
    {
      "akinsho/flutter-tools.nvim",
      requires = "nvim-lua/plenary.nvim",
      config = function()
        require("flutter-tools").setup {
          lsp = {
            on_attach = require("lsp").common_on_attach,
          },
        }
      end,
      ft = "dart",
    },
}
```
`lvim.lsp.override` is deprecated, so I used the newer method described in the warning message. I couldn't detect a difference with or without `ft = "dart"` so I left it off. Finally, `require("lsp").common_on_attach` results in an error that the `lsp` file can't be found, and I couldn't figure out what to use instead. I think that last one probably is what would attach the `lvim.lsp.buffer_mappings.normal_mode` key mappings that I need, but I'm not sure.

As a workaround, I'm able to configure keybindings by creating an autocommand:

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "dart",
  callback = function()
    -- Show hover
    vim.api.nvim_set_keymap("n", "K", "<Cmd>lua vim.lsp.buf.hover()<CR>", { noremap = true, silent = true })
    -- Jump to definition
    vim.api.nvim_set_keymap("n", "gd", "<Cmd>lua vim.lsp.buf.definition()<CR>", { noremap = true, silent = true })
    -- .....
  end,
})
```

This, of course, loses the friendly titles of the commands like "Goto Declaration" or "Show line diagnostics" that `which_key` can display in other files. These are particularly useful because I don't have the commands memorized, so I would prefer to discover the proper way to configure flutter support in LunarVim.

### LunarVim version

release-1.3/neovim-0.9-e823ccb9

### Neovim version (>= 0.8.0)

NVIM v0.9.0

### Operating system/version

Windows 10, WSL 2, Debian 11

### Affected language servers

dartls

### Steps to reproduce

1. Edit LunarVim's config to include `flutter-tools`:
    ```lua
    {
      "akinsho/flutter-tools.nvim",
      dependencies = {
        "nvim-lua/plenary.nvim",
        "stevearc/dressing.nvim",
      },
      config = function()
        require("flutter-tools").setup {
          settings = {
            enableSnippets = true,
          }
        }
      end,
    },
    ```
2. Disable automatic configuration of `dartls` per the warning in the `flutter-tools` [readme file](https://github.com/akinsho/flutter-tools.nvim#warning).
    ```lua
    vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "dartls" })
    ```
3. Save the config, close LunarVim, and open a dart file in LunarVim.
4. Locate a variable or classname and press `K`

### Actual behavior

`man.lua: "no manual entry for ExampleClassObject"`

### Expected behavior

LSP should display information about the type of object under the cursor.

### support info

```console
# :LspInfo
 Language client log: /home/jon/.local/state/lvim/lsp.log
 Detected filetype:   dart
 
 2 client(s) attached to this buffer: 
 
 Client: dartls (id: 1, bufnr: [1])
 	filetypes:       dart
 	autostart:       false
 	root directory:  /home/jon/projects/invulnerable_iot
 	cmd:             /home/jon/.local/share/flutter/bin/dart /home/jon/.local/share/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp
 
 Client: copilot (id: 2, bufnr: [1])
 	filetypes:       
 	autostart:       false
 	root directory:  Running in single file mode.
 	cmd:             node /home/jon/.local/share/lunarvim/site/pack/lazy/opt/copilot.vim/copilot/dist/agent.js
 
 Configured servers list: 
```
```console
# :LvimInfo

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                dart
* bufnr:                   1
* treesitter status:       active

Active client(s)
* name:                      dartls
* id:                        1
* supported filetype(s):     dart
* attached buffers:          1
* root_dir pattern:          1
* capabilities:              implementationProvider     | referencesProvider              | typeHierarchyProvider
                             foldingRangeProvider       | documentRangeFormattingProvider | callHierarchyProvider
                             selectionRangeProvider     | definitionProvider              | hoverProvider
                             documentHighlightProvider  | workspaceSymbolProvider
                             documentFormattingProvider | documentSymbolProvider
* name:                      copilot
* id:                        2
* supported filetype(s):     []
* attached buffers:          1
* root_dir pattern:          1

Automatic LSP info
* Skipped servers: [angularls, ansiblels, antlersls, csharp_ls, cssmodules_ls, denols, docker_compose_language_service, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, neocmake, phpactor, psalm, pylsp, pyre, quick_lint_js, reason_ls, rnix, rome, ruby_ls, ruff_lsp, solang, solc, sorbet, sourcery, spectral, sqlls, sqls, stylelint_lsp, svlangserver, tflint, unocss, verible, vtsls, vuels]

Formatters info
* Active: 
* Supported: dart_format

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

### logs

```console
[START][2023-04-29 23:15:17] LSP logging initiated
[WARN][2023-04-29 23:15:17] ...lsp/handlers.lua:137	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

**Comment by cpea2506** [comment]
Every file inside `lvim` must be prefix with `lvim`. So the right path would be `require("lvim.lsp")`
