### ISSUE TITLE
[Lvim1.3] Dapui - Attempt to index local 'element' (a nil value)

### ISSUE THREAD

**Issue by WillianFuks** [LunarVim/LunarVim#4105]
### Problem description

I just updated my lvim to tag 1.3 running on Ubuntu, fresh installed all plugins and when trying to run dap got the error:

```
Error executing vim.schedule lua callback: ...im/site/pack/lazy/opt/nvim-dap-ui/lua/dapui/controls.lua:15: attempt to index local 'element' (a nil value)
stack traceback:
        ...im/site/pack/lazy/opt/nvim-dap-ui/lua/dapui/controls.lua:15: in function 'enable_controls'
        ...narvim/site/pack/lazy/opt/nvim-dap-ui/lua/dapui/init.lua:304: in function 'open'
        /home/will/.config/lvim/lua/user/plugins/dap.lua:7: in function 'c'
        ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:982: in function <...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:970>
Press ENTER or type command to continue
```

I tried running `dapui.setup({})` and then it worked but then if pressing `<C+W>l` then all windows close.

Maybe it's a conflict between newer versions not contemplated by lvim's default config.

### LunarVim version

release-1.3/neovim-0.9-e823ccb9

### Neovim version (>= 0.8.0)

NVIM v0.9.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Terminal name

Terminator

### Operating system/version

ubuntu 20.04

### Steps to reproduce

1. Set dap toggle
2. Run `<F5>`

### Screenshots

![image](https://user-images.githubusercontent.com/4665485/235361537-e95eb3b2-5b07-4135-9580-002ca773ef77.png)

**Comment by kobzar** [comment]
My lvim 1.3
My python dap presets i get here
https://github.com/LunarVim/starter.lvim/tree/python-ide
all working fine. 
Try to full uninstall/install lvim

**Comment by WillianFuks** [comment]
Hi @kobzar , thanks for the reply.

I just tried what you suggested and after a complete fresh install I still get the same error.

Could you please share which commits your dap and dapui are currently in?

For nim-dap mine is:
```
    ● nvim-dap 1.33ms
        dir     ~/.local/share/lunarvim/site/pack/lazy/opt/nvim-dap
        url     https://github.com/mfussenegger/nvim-dap
        version 0.6.0
        tag     0.6.0
        branch  master
        commit  debd7c2
        readme  README.md
        help    |dap.txt|
```

And for dapui:
```
    ○ nvim-dap-ui 
        dir    ~/.local/share/lunarvim/site/pack/lazy/opt/nvim-dap-ui
        url    https://github.com/rcarriga/nvim-dap-ui
        branch master
        commit 286f682
        readme README.md
        help   |nvim-dap-ui|
```

Thanks in advance,

**Comment by WillianFuks** [comment]
Hi @kobzar ,

I just got it working. I had to change the plugins definition and set dapui to not be lazy loaded, like so:

```
  -- lvim/plugins.lua
  -- Debugger user interface
  {
    "rcarriga/nvim-dap-ui",
    config = function()
      require("lvim.core.dap").setup_ui()
    end,
    lazy = false,
    enabled = lvim.builtin.dap.active,
  },
```

Don't know why this is the case. What I could see here though is that when entering the debug session the event `dap.listeners.after.event_initalized` was still equal to `{}` which hinted me that maybe dapui was not loaded yet and so the [code](https://github.com/LunarVim/LunarVim/blob/1.3.0/lua/lvim/core/dap.lua#L128-L129) executed for its initalization didn't process through, which didn't trigger the dapui layout view.

When I forced this value on my own config, the code was executing before dap was set up so config was just `{}`, that's why I saw the error as described in this issue (saying that element was `nil`, which it was as dap hand't run `dap.setup()` yet).

I tried adding the `dependencies` element for dapui forcing it to first load dap but it still didn't work. Only thing that worked indeed was to set its lazy loading to `false`.

**Comment by WillianFuks** [comment]
Just as I wrote the previous message I found the reference from Folke himself on his suggestion for [loading dap](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/dap/core.lua) through Lazy:

```
{
  "mfussenegger/nvim-dap",

  dependencies = {

    -- fancy UI for the debugger
    {
      "rcarriga/nvim-dap-ui"
   }
}
```

So the correct way to still have the plugins as lazy evaluated is to set dapui as dependency of dap, not the other way around as mistakenly presumed by me. 

Testing his approach worked just fine.

**Comment by ChristianChiarulli** [comment]
This should be working now thanks @WillianFuks.

**Comment by hadishahpuri** [comment]
Hi, I  just got this error
![Screenshot from 2023-08-21 09-04-31](https://github.com/LunarVim/LunarVim/assets/54359470/f79e1db0-21a1-4814-b6b7-519531833e63)
NVIM v0.9.1

**Comment by GrimalDev** [comment]
Hello, same here...
```lua
  {
    "rcarriga/nvim-dap-ui",
    dependencies = {
      {
        "mfussenegger/nvim-dap",
      },
      "nvim-neotest/nvim-nio",
    },
    init = function()
      local dap = require "dap"
      local dapui = require "dapui"

      -- PHP --
      dap.adapters.php = {
        id = "php",
        type = "executable",
        command = vim.fn.exepath "php-debug-adapter",
        localSourceRoot = vim.fn.expand "%:p:h" .. "/",
        serverSourceRoot = vim.fn.expand "%:p:h" .. "/",
      }
      dap.configurations.php = {
        {
          type = "php",
          request = "launch",
          name = "Listen for Xdebug",
          port = 9003,
        },
      }

      vim.fn.sign_define("DapBreakpoint", { text = "", texthl = "ErrorMsg", linehl = "", numhl = "ErrorMsg" })
      vim.fn.sign_define(
        "DapBreakpointCondition",
        { text = "⬤", texthl = "ErrorMsg", linehl = "", numhl = "SpellBad" }
      )
      vim.fn.sign_define("DapStopped", { text = "", texthl = "ErrorMsg", linehl = "", numhl = "ErrorMsg" })

      dap.listeners.after.event_initialized["dapui_config"] = function()
        dapui.open()
      end
      dap.listeners.before.event_terminated["dapui_config"] = function()
        dapui.close()
      end
      dap.listeners.before.event_exited["dapui_config"] = function()
        dapui.close()
      end
    end,
  },
```
I also tried the dependencies in the other way around with dap first depending on ui.

I don't know what I am doing wrong...

**Comment by GrimalDev** [comment]
SOOOOO, turns out I just needed to add a dapui.config() call in my init function. Which is PRETTY obvious. Hope this helps anyone...
