### ISSUE TITLE
syntax isn't detected automatically when editing dosini files

### ISSUE THREAD

**Issue by singh-gagandeep** [LunarVim/LunarVim#4106]
### Problem description

Hi, I've noticed this strange behavior in Lvim 1.3 when editing dosini files syntax isn't automatically detected unlike previous release Lvim (1.2)

Issues
- :set syntax? is empty when editing .ini(dosini) files
- commentstring is "# %s" instead of "; %s"

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.9.0

### Operating system/version

linux

### Affected language servers

NA

### Steps to reproduce

- edit existing .ini file
- try to comment any line with <leader>/ ( In normal behaviour it should start with ; not #)

### Actual behavior

Issues
- :set syntax? is empty when editing .ini(dosini) files
- commentstring is "; %s" instead of "# %s"

### Expected behavior

- syntax should be detected as type dosini
- commentstring should be "; %s" instead of "# %s"

### support info

:LspInfo
Use [q] or [Esc] to quit the window

             Language client log: /home/archie/.local/state/nvim/lsp.log
             Detected filetype:   dosini

             0 client(s) attached to this buffer:

             Configured servers list:

----------------------------------------------------------------------------------------------------------------------------------------
:LvimInfo

Buffer info
               * filetype:                dosini
               * bufnr:                   1
               * treesitter status:       active

               Active client(s)

               Automatic LSP info
               * Skipped servers: [angularls, ansiblels, antlersls, csharp_ls, cssmodules_ls, denols, docker_compose_language_service, embe

               Formatters info
               * Active:
               * Supported: []

               Linters info
               * Active:
               * Supported: []

               Code actions info
               * Active: %

**Comment by kobzar** [comment]
I am confirmed this issue. The same problem.

**Comment by LostNeophyte** [comment]
commentstring is "; %s", but Comment.nvim is using its internal mapping first https://github.com/numToStr/Comment.nvim/blob/e1fe53117aab24c378d5e6deaad786789c360123/lua/Comment/ft.lua#L83

**Comment by singh-gagandeep** [comment]
Thank you for looking into it.
