### ISSUE TITLE
Custom .prettierrc

### ISSUE THREAD

**Issue by dmasley-hyfen** [LunarVim/LunarVim#4108]
### Problem description

I have a custom .prettierrc rule which is not being picked up by the formatter, thus all my formatting is different from my organization. How can I get my formatting settings to read the `.prettierrc` file config?

### LunarVim version

master-91bdb7cd

### Neovim version (>= 0.8.0)

NVIM 0.8

### Operating system/version

Ubuntu 18.x

### Affected language servers

tsserver

### Steps to reproduce

1. have a .prettierrc file
2. try to format a document

### Actual behavior

uses default prettier options

### Expected behavior

uses .prettierrc options

### support info

``` 
    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                lua
* bufnr:                   4
* treesitter status:       active

Active client(s)
* name:                      lua_ls
* id:                        1
* supported filetype(s):     lua
* attached buffers:          4
* root_dir pattern:          4
* capabilities:              definitionProvider      | documentRangeFormattingProvider | documentFormattingProvider
                             foldingRangeProvider    | colorProvider                   | hoverProvider
                             referencesProvider      | typeDefinitionProvider          | documentSymbolProvider
                             workspaceSymbolProvider | documentHighlightProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, antlersls, azure_pipelines_ls, omnisharp, cssmodules_ls, denols, docker_compose_language_service, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, neocmake, phpactor, psalm, pylsp, pylyzer, pyre, quick_lint_js, reason_ls, rnix, rome, ruby_ls, ruff_lsp, solang, solc, sorbet, sourcery, spectral, sqlls, sqls, standardrb, stylelint_lsp, svlangserver, tflint, unocss, verible, vtsls, vuels]

Formatters info
* Active: 
* Supported: [lua_format, stylua]

Linters info
* Active: 
* Supported: [luacheck, selene]

Code actions info
* Active: 
```

**Comment by kobzar** [comment]
You can add prettier parameters in your config file 
https://www.lunarvim.org/docs/configuration/language-features/linting-and-formatting

**Comment by ChristianChiarulli** [comment]
I'm surprised the formatter isn't picking up the config file

**Comment by benediktms** [comment]
are you working in a monorepo with multiple prettier config files a different roots?

**Comment by imsumoregn** [comment]
> I'm surprised the formatter isn't picking up the config file

I remember you could do something like this with `null-ls`

```lua
require("null-ls").setup {
    on_attach = require("lvim.lsp").common_on_attach,
    sources = {
      nls.builtins.formatting.prettier.with {
        condition = function(utils)
          return utils.root_has_file { ".prettierrc" }
        end,
        prefer_local = "node_modules/.bin",
    }
}
```

--but not quite sure how to make the formatter use the config file found.

Is there anything similar in LunarVim core, or some options we could add to pull this off?

**Comment by sroertgen** [comment]
I think I have the same problem. Local `.prettierrc` does not seem to have any effect. When I run `prettier` from the command line the `.prettierrc` gets picked up

**Comment by kobzar** [comment]
Did the project folders contains .git init?

**Comment by dmasley-hyfen** [comment]
> You can add prettier parameters in your config file https://www.lunarvim.org/docs/configuration/language-features/linting-and-formatting

Thank you Koz, this is what I ended up doing. Just manually hardcoding the settings in my global lunarvim config.

@benediktms yes it is a monorepo, although the .prettierrc is only on root

@sroertgen I had the same behavior of it working but just not working within lunarvim automatically

@kobzar yes the project folders contain .git folders
