### ISSUE TITLE
Strange Chinese Icons shoing up

### ISSUE THREAD

**Issue by codingluke** [LunarVim/LunarVim#4112]
### Problem description

Since some time I can see icons on the title and sidebar which look very chinese to me. Am I the only one or did something change lately? It is not a problem, I am just wondering. The file icons are still ok. I is somehow an additional icon.

### LunarVim version

91bdb7cd5131bdeeb0fd68ad58aaf69adb510983

### Neovim version (>= 0.8.0)

v0.10.0-dev-174+ga4b240080

### Terminal name

kitty

### Operating system/version

macos 13.3.1

### Steps to reproduce

1. brew install --cask font-fira-code-nerd-font
2. start lvim
3. open mutiple files

### Screenshots

![image](https://user-images.githubusercontent.com/643436/235660738-ed4f361c-6a58-41a8-bf7a-22b3e8614bc7.png)
![image](https://user-images.githubusercontent.com/643436/235660790-f4eff9a1-0f42-4038-b30a-6a23202fee50.png)

**Comment by Flygrounder** [comment]
See https://github.com/nvim-tree/nvim-web-devicons/pull/264

**Comment by brneor** [comment]
If you're not using a NerdFont 3.0 font, try updating to the latest 2.X version.

**Comment by kobzar** [comment]
Moved to main thread
https://github.com/nvim-tree/nvim-web-devicons/pull/264

**Comment by codingluke** [comment]
Ok, I will investigate in this. I have the latest version from **brew --cask** maybe they are behind V3.

**Comment by codingluke** [comment]
For everybody which installed fira-code via homebrew and updated it to version 3, which will be automatically done by `brew upgrade`. `brew install --cask font-fira-code-nerd-font@2.3.3` is not working. Here the easiest way to go back: 

```shell
brew install --cask https://raw.githubusercontent.com/Homebrew/homebrew-cask-fonts/e759a655cb287ec8fad47b9c85edd2ef283039a9/Casks/font-fira-code-nerd-font.rb
```

1. In general, go to the Homebrew cask formula
2. find the version you like with "history"
3. copy the raw file url
4. `brew install --cask [url-to-the-version-file]`
