### ISSUE TITLE
TreeSitter gitcommit parser weirdness

### ISSUE THREAD

**Issue by gonzus** [LunarVim/LunarVim#4113]
This is likely not a problem exclusive to `lunarvim`, I have seen it happening on other installations of `neovim`. I am running on an M1 Mac laptop.

I have configured `git` to use `lunarvim` as the editor. The first time I commit something, I see correct colors for all areas of the commit message:

* The commit summary
* The commit detailed message
* Each of the lines starting with `diff --git ...` that separate each file being committed.
* The diff themselves for each file changed.

However, after a few seconds I get this error message:
```
Could not load parser for gitcommit: "Failed to load parser for language 'gitcommit': '.../.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/parser/gitcommit.so' (mach-o file
, but is an incompatible architecture (have 'x86_64', need 'arm64'))"
```
After this happens, every time I try to commit something I get a large `neovim` error message, but colors still work OK while editing the commit buffer.

If I look at the parsers built so far for my `lunarvim` installation, I do see that `gitcommit` has the wrong architecture -- I guess how this came to happen is mystery number 1 here:
```sh
$ file parser/*    
parser/c.so:         Mach-O 64-bit bundle arm64
parser/cpp.so:       Mach-O 64-bit bundle arm64
parser/gitcommit.so: Mach-O 64-bit bundle x86_64
parser/lua.so:       Mach-O 64-bit bundle arm64
parser/perl.so:      Mach-O 64-bit bundle arm64
```
Now, if I manually open `lunarvim` and run `:TSInstall gitcommit`, it correctly installs the parser for my architecture:
```sh
$ file parser/*
parser/c.so:         Mach-O 64-bit bundle arm64
parser/cpp.so:       Mach-O 64-bit bundle arm64
parser/gitcommit.so: Mach-O 64-bit bundle arm64
parser/lua.so:       Mach-O 64-bit bundle arm64
parser/perl.so:      Mach-O 64-bit bundle arm64
```
But mystery number 2 now shows up: if after doing that I do a `git commit`, the `lunarvim` buffer only shows correct colors for the summary and detail messages, but does NOT show anymore the correct colors for each of the `diff --git` lines, or for the actual diffs; they simply appear as grey text.

Flabbergasted.

**Comment by LostNeophyte** [comment]
> But mystery number 2 now shows up: if after doing that I do a git commit, the lunarvim buffer only shows correct colors for the summary and detail messages, but does NOT show anymore the correct colors for each of the diff --git lines, or for the actual diffs; they simply appear as grey text.

`:TSInstall diff`

**Comment by gonzus** [comment]
Wow, easy and brief solution, thanks @LostNeophyte! Weird how the `diff` highlight works to begin with, then it stops working, then it works again by installding the `diff` parser. Will close the issue.
