### ISSUE TITLE
Add nvim-surround to LunarVim

### ISSUE THREAD

**Issue by mbledkowski** [LunarVim/LunarVim#4118]
### Feature Description

Hello,
I feel like [nvim-surround](https://github.com/kylechui/nvim-surround) would be very beneficial to LunarVim users, especially when editing and fixing the code.
Best regards

**Comment by kobzar** [comment]
For me https://github.com/echasnovski/mini.surround mutch better. 
Some one uses https://github.com/machakann/vim-sandwich

So, wich we must add by default?
(The true answer is no one. Every one choose it by himself)

**Comment by ChristianChiarulli** [comment]
I don't think this should be a core plugin tbh. It's easy enough to include as a plugin.

**Comment by kobzar** [comment]
I think we can close this post. The personal plugin list must be personal.
