### ISSUE TITLE
Filetype autocommads not working with whichkey

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#4120]
### Problem description

filetype autocommands are not working with whichkey

### LunarVim version

master

### Neovim version (>= 0.8.0)

NVIM v0.9.0

### Terminal name

kitty

### Operating system/version

macOS, Linux

### Steps to reproduce

Add this to your config.lua and notice when you press space d the options are not available

```lua
vim.api.nvim_create_autocmd({ "FileType" }, {
  pattern = { "python" },
  callback = function()
    lvim.builtin.which_key.mappings["dm"] = { "<cmd>lua require('neotest').run.run()<cr>",
      "Test Method" }
    lvim.builtin.which_key.mappings["dM"] = { "<cmd>lua require('neotest').run.run({strategy = 'dap'})<cr>",
      "Test Method DAP" }
    lvim.builtin.which_key.mappings["df"] = {
      "<cmd>lua require('neotest').run.run({vim.fn.expand('%')})<cr>", "Test Class" }
    lvim.builtin.which_key.mappings["dF"] = {
      "<cmd>lua require('neotest').run.run({vim.fn.expand('%'), strategy = 'dap'})<cr>", "Test Class DAP" }
    lvim.builtin.which_key.mappings["dS"] = { "<cmd>lua require('neotest').summary.toggle()<cr>", "Test Summary" }
  end,
})
```

**Comment by LostNeophyte** [comment]
`lvim.builtin.which_key.mappings` is only evaluated one time on startup, in autocommands users should the vim api to add mappings, unless we want to change that? idk if it's possible

**Comment by ChristianChiarulli** [comment]
@LostNeophyte I'm pretty sure this used to work not that long ago, not sure what a good solution to this is.
