### ISSUE TITLE
How to make autocompletion gives lsp results?

### ISSUE THREAD

**Issue by ufo5260987423** [LunarVim/LunarVim#4123]
### Problem description

Manual configuration for autocomletion can't give lsp's response result, and I've checked my lsp server is working well.

It seems I need follow **some instructions** and do some further configuration. However, I can't find related information in LunarVim's issues and nvim-lspconfig. 

>NOTE: Yes, I know my nvim version is not 0.9, but…… lunarvim 1.2 have many bugs and I can't figure out them. And Lunarvim 1.3 seems now perform well for goto-definition, document symbols and many other functions.

### LunarVim version

latest version

### Neovim version (>= 0.8.0)

NVIM v0.8.3 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/nvim/parts/nvim/build/build/cmake.config -I/build/nvim/parts/nvim/build/src -I/build/nvim/parts/nvim/build/.deps/usr/include -I/usr/include -I/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build/build/include Compiled by root@lcy02-amd64-037  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Operating system/version

Ubuntu16.04

### Affected language servers

scheme-langserver

### Actual behavior

I'm manually configuring [scheme-langserver](https://github.com/ufo5260987423/scheme-langserver), and here's my configure:

`~/.local/share/lunarvim/site/pack/lazy/opt/nvim-lspconfig/lua/lspconfig/server_configurations/scheme_langserver.lua` as follows:
```lua
local util = require 'lspconfig.util'
local bin_name = '{path-to-run}'
local cmd = { bin_name }

return {
  default_config = {
    cmd = cmd,
    filetypes = { 'scheme' },
    root_dir = util.find_git_ancestor,
    single_file_support = true,
  },
  docs = {
    description = [[
https://github.com/ufo5260987423/scheme-langserver
`scheme-langserver`, a language server protocol implementation for scheme
]]   ,
  },
}
```

Then configure your `~/.config/lvim/config.lua` and add following codes like:
```lua
vim.cmd [[ au BufRead,BufNewFile *.sld set filetype=scheme ]]
vim.cmd [[ au BufRead,BufNewFile *.sls set filetype=scheme ]]

require 'lspconfig'.scheme_langserver.setup {
vim.api.nvim_create_autocmd('LspAttach', {
  group = vim.api.nvim_create_augroup('UserLspConfig', {}),
  callback = function(ev)
    -- Enable completion triggered by <c-x><c-o>
    vim.bo[ev.buf].omnifunc = 'v:lua.vim.lsp.omnifunc'

    -- Buffer local mappings.
    -- See `:help vim.lsp.*` for documentation on any of the below functions
    local opts = { buffer = ev.buf }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
  end,
})
}
```
However, auto-completion can't give lsp response result:
![2023-05-03 23-27-40屏幕截图](https://user-images.githubusercontent.com/3020270/236131859-6cf175e7-b2aa-4975-b0d7-9b419fb35654.png)

### Expected behavior

Last year, lunarvim had worked perfectly. And in my previous experience, it should be like:
![auto-completion](https://user-images.githubusercontent.com/3020270/236132769-c13d7255-0ef1-495d-b043-573aafe37592.png)

### support info

LspInfo:
![2023-05-04 15-01-00屏幕截图](https://user-images.githubusercontent.com/3020270/236133031-12b824b0-1b9c-4346-984e-7a7d92385277.png)
LvimInfo:
![2023-05-04 15-02-20屏幕截图](https://user-images.githubusercontent.com/3020270/236133240-88deaeea-23ea-4807-89b2-548b2d867a38.png)

**Comment by LostNeophyte** [comment]
> NOTE: Yes, I know my nvim version is not 0.9, but…… lunarvim 1.2 have many bugs and I can't figure out them. And Lunarvim 1.3 seems now perform well for goto-definition, document symbols and many other functions.

i won't spend time troubleshooting this issue as the problem might be caused by you using 0.8, there are also some lsp fixes on lvim master, you can try that

```lua
require 'lspconfig'.scheme_langserver.setup {
vim.api.nvim_create_autocmd('LspAttach', {
  group = vim.api.nvim_create_augroup('UserLspConfig', {}),
  callback = function(ev)
    -- Enable completion triggered by <c-x><c-o>
    vim.bo[ev.buf].omnifunc = 'v:lua.vim.lsp.omnifunc'

    -- Buffer local mappings.
    -- See `:help vim.lsp.*` for documentation on any of the below functions
    local opts = { buffer = ev.buf }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
  end,
})
}
```
this code seems incorrect, why would you pass an autocommand to the setup function?

**Comment by ufo5260987423** [comment]
I've just upgrade my neovim to 0.10, the problem is still existed.

NVIM v0.10.0-dev-265+gfe7cdc7cc
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -fdiagnostics-color=auto -fstack-protector-strong -DNVIM_LOG_DEBUG -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/ufo/Documents/workspace/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/ufo/Documents/workspace/neovim/.deps/usr/include -I/home/ufo/Documents/workspace/neovim/build/src/nvim/auto -I/home/ufo/Documents/workspace/neovim/build/include -I/home/ufo/Documents/workspace/neovim/build/cmake.config -I/home/ufo/Documents/workspace/neovim/src -I/usr/include -I/home/ufo/Documents/workspace/neovim/.deps/usr/include -I/home/ufo/Documents/workspace/neovim/.deps/usr/include -I/home/ufo/Documents/workspace/neovim/.deps/usr/include -I/home/ufo/Documents/workspace/neovim/.deps/usr/include -I/home/ufo/Documents/workspace/neovim/.deps/usr/include -I/home/ufo/Documents/workspace/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

**Comment by LostNeophyte** [comment]
> -- nvim-cmp setup
local cmp = require 'cmp'
cmp.setup {

don't call setup of builtin plugins

**Comment by ufo5260987423** [comment]
> > -- nvim-cmp setup
> > local cmp = require 'cmp'
> > cmp.setup {
> 
> don't call setup of builtin plugins

Thank you very much! I now can understand what lunarvim did!

And my current code is like 

```lua
vim.cmd [[ au BufRead,BufNewFile *.sld set filetype=scheme ]]
vim.cmd [[ au BufRead,BufNewFile *.sls set filetype=scheme ]]

vim.api.nvim_create_autocmd('LspAttach', {
  group = vim.api.nvim_create_augroup('UserLspConfig', {}),
  callback = function(ev)
    -- Enable completion triggered by <c-x><c-o>
    vim.bo[ev.buf].omnifunc = 'v:lua.vim.lsp.omnifunc'

    -- Buffer local mappings.
    -- See `:help vim.lsp.*` for documentation on any of the below functions
    local opts = { buffer = ev.buf }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
  end,
})

-- local capabilities = vim.lsp.protocol.make_client_capabilities()
-- capabilities = require("cmp_nvim_lsp").default_capabilities(capabilities)
local lspconfig = require('lspconfig')
lspconfig.scheme_langserver.setup {}
lvim.builtin.cmp.enabled()
lvim.builtin.cmp.sources = {
  { name = 'nvim_lsp' },
  { name = 'luasnip' },
}
```
