### ISSUE TITLE
Should we integrate neotest?

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#4133]
Or maybe write a plugin layer that abstracts aways some of the complicated bits.

**Comment by nieomylnieja** [comment]
neotest runners offer debug capabilities, which is often a reimplementation of existing solutions (like nvim-dap-python or nvim-dap-go). Moreover not all runners offer a complete set of these functionalities (neotest-go for one does not support DAP yet). I like neotest, but I feel like they over extended with DAP support and started reinventing the wheel.
Nevertheless It does fill the gap for first class test workflows with visual hints and the summary.
In my own workflow I just don't use it for debugging and use it specifically for testing, and as I said, having discovered it a couple of weeks ago, it has filled a big tests workflow gap for me between Neovim and GoLand for Go development quiet nicely.
