### ISSUE TITLE
Some icons can't display

### ISSUE THREAD

**Issue by liuyangzys** [LunarVim/LunarVim#4138]
### Problem description

Some icons can't distplay. Such as "FindFile", "Folder"

On alacritty or windows terminal 
![image](https://user-images.githubusercontent.com/19203871/236680883-f29a24b9-2733-4aeb-8847-4c296e0b5f09.png)

When using neovide 
![image](https://user-images.githubusercontent.com/19203871/236680792-51c56766-3654-4e22-859a-47a6d94c2aa8.png)

### LunarVim version

master-55f048a

### Neovim version (>= 0.8.0)

0.9.0

### Terminal name

Windows Terminal, A

### Operating system/version

Windows 11

**Comment by LostNeophyte** [comment]
update your nerd font to v3
