### ISSUE TITLE
Set indentation to a tab character rather than whitespaces

### ISSUE THREAD

**Issue by sandczn** [LunarVim/LunarVim#4142]
### Problem description

I want my indentation to be a tab character everytime

I tried using ```vim.opt.noexpandtab = true``` but that didnt work.

### LunarVim version

release-1.3/neovim-0.9-e399a08d

### Neovim version (>= 0.8.0)

NVIM v0.9.0 Release

### Terminal name

Konsole

### Operating system/version

Endeavour OS Kernel 6.1.27-1-lts (64-bit)

### Steps to reproduce

*

**Comment by lunacd** [comment]
Try `vim.o.expandtab = false`.

**Comment by ChristianChiarulli** [comment]
I don't think noexpandtab is an available option. Btw lunarvim has support for showing you all of the options available just do `vim.o.` and a completion menu should show up with all of the options available.

![image](https://user-images.githubusercontent.com/29136904/236741497-670edd00-f52c-4509-9a6d-de14fc4a0697.png)

**Comment by LostNeophyte** [comment]
`vim.opt.expandtab = false` will do it
