### ISSUE TITLE
Html LSP not working

### ISSUE THREAD

**Issue by daibertdiego** [LunarVim/LunarVim#4151]
### Problem description

I used Mason to install HTML and tailwind LSP but they are not connecting when I open a HTML file.
I tried to uninstall and reinstall but without success.

### LunarVim version

release-1.3/neovim-0.9-fcb65eaa

### Neovim version (>= 0.8.0)

NVIM v0.9.0 Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.0/share/nvim"

### Operating system/version

macOS Ventura 13.3.1

### Affected language servers

html-lsp and tailwindcss-laguage-server

### Steps to reproduce

1 - Install html-lsp and taiwwindcss-language-server using Mason. 
2 - Open a html file. 

### Actual behavior

LSP Server is not connecting. 

### Expected behavior

Get HTML and Tailwind LSP features working. 

### support info

Language client log: /Users/diegodaibert/.local/state/lvim/lsp.log
 Detected filetype:   html
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: html
 
 Config: tailwindcss
 	filetypes:         aspnetcorerazor, astro, astro-markdown, blade, clojure, django-html, htmldjango, edge, eelixir, elixir, ejs, erb, eruby, gohtml, haml, handlebars, hbs, html, html-eex, heex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte
 	root directory:    /Users/diegodaibert/tailwindcss-course
 	cmd:               tailwindcss-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 Config: html
 	filetypes:         html
 	root directory:    /Users/diegodaibert/tailwindcss-course
 	cmd:               vscode-html-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: tailwindcss, html, rust_analyzer

### logs

```console
[START][2023-05-09 14:44:09] LSP logging initiated
[ERROR][2023-05-09 14:44:09] .../vim/lsp/rpc.lua:734	"rpc"	"tailwindcss-language-server"	"stderr"	'/Users/diegodaibert/.local/share/lvim/mason/packages/tailwindcss-language-server/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server:137\n`,fF=class{constructor(e="utf-8"){this._encoding=e,this._chunks=[],this._totalLength=0}get encoding(){return this._encoding}append(e){let r=typeof e=="string"?this.fromString(e,this._encoding):e;this._chunks.push(r),this._totalLength+=r.byteLength}tryReadHeaders(){if(this._chunks.length===0)return;let e=0,r=0,n=0,s=0;e:for(;r<this._chunks.length;){let p=this._chunks[r];n=0;t:for(;n<p.length;){switch(p[n]){case Rfe:switch(e){case 0:e=1;break;case 2:e=3;break;default:e=0}break;case Ffe:switch(e){case 1:e=2;break;case 3:e=4,n++;break e;default:e=0}break;default:e=0}n++}s+=p.byteLength,r++}if(e!==4)return;let i=this._read(s+n),o=new Map,a=this.toString(i,"ascii").split(Bfe);if(a.length<2)return o;for(let p=0;p<a.length-2;p++){let u=a[p],H=u.indexOf(":");if(H===-1)throw new Error("Message header must separate key and value using :");let l=u.substr(0,H),c=u\n\nSyntaxError: Unexpected token .\n    at Module._compile (internal/modules/cjs/loader.js:723:23)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)\n'
[ERROR][2023-05-09 14:44:09] .../vim/lsp/rpc.lua:734	"rpc"	"vscode-html-language-server"	"stderr"	"/Users/diegodaibert/.local/share/lvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40\n        return this._head?.value;\n                          ^\n\nSyntaxError: Unexpected token .\n    at Module._compile (internal/modules/cjs/loader.js:723:23)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/Users/diegodaibert/.local/share/lvim/mason/packages/html-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n"
```

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/25724941/140fc2ac-39d0-428f-a7e2-fdd8a447ffd4)
![image](https://github.com/LunarVim/LunarVim/assets/25724941/2eb99c75-d402-4bf6-9f20-aa5950b0cbcf)

**Comment by LostNeophyte** [comment]
try using a different nodejs version

**Comment by hawkinchina** [comment]
I met the same question.

**Comment by spithash** [comment]
try updating those:

spithash@shire:~$ node --version
v20.3.1
spithash@shire:~$ npm --version
9.6.7

It'll work,
