### ISSUE TITLE
Floating Text Artifacts

### ISSUE THREAD

**Issue by JustinStitt** [LunarVim/LunarVim#4152]
### Problem description

Open Lvim
- `$ lvim`

Notice `f`, `t`, and `q` are slightly offset (not caused by font, tried dozens of nerd fonts, all same offset).
![Screenshot_3](https://github.com/LunarVim/LunarVim/assets/24460581/d080d006-1b57-4fd1-818d-8457b3a69403)

Now, if we open the config (`c`) we see some floating text
![Screenshot_4](https://github.com/LunarVim/LunarVim/assets/24460581/cd4c85ef-6d8e-4ba5-bf53-3362c4f12f65)

There are other cases where some weird floating text appears too. Especially when interacting with NvimTree or when the LSP detects an error/warning it may sometimes leave some random characters from my buffer splattered around.

### LunarVim version

release-1.3/neovim-0.9-fcb65eaa

### Neovim version (>= 0.8.0)

NVIM v0.9.0

### Terminal name

Windows Terminal

### Operating system/version

Windows 10 w/ WSL 2

### Steps to reproduce

1) open lvim

2) press c

3) look at the floating text

**Comment by JustinStitt** [comment]
Here's an example if the issue when LSP diagnostics pop up and leave some leading spaces in front of the line:
![Screenshot_5](https://github.com/LunarVim/LunarVim/assets/24460581/23c665ef-887d-4e4d-b5e6-9e4cb414e861)

*If I were to navigate to those lines, the **magic** floating spaces immediately disappear*

**Comment by LostNeophyte** [comment]
most likely vim.opt.title = false will fix it

**Comment by JustinStitt** [comment]
> most likely vim.opt.title = false will fix it

Did not fix my issue. However, disabling LSP signs in the sign column solved some of the random leading text. The floating letters from the title screen still remain.

**Comment by LostNeophyte** [comment]
your terminal doesn't like the new nerdfont icons, idk what you can do with that

**Comment by JustinStitt** [comment]
> your terminal doesn't like the new nerdfont icons, idk what you can do with that

New as of when? I just recently hit :LvimUpdate whereas before I was on some pre v1.2 release with Nvim v0.9 nightly (idk what SHA)

**Comment by LostNeophyte** [comment]
nerd fonts 1.3

**Comment by JustinStitt** [comment]
Do you suggest I repatch my existing fonts?

**Comment by LostNeophyte** [comment]
It looks like you already have v3, otherwise you wouldn't be able to see the icons, you can try repatching / try downloading a font from their website

**Comment by JustinStitt** [comment]
> nerdfont

Gotcha, my font is definitely patched pre-v3 but will try a font from source. Thanks.

I will go radio silent if it ends up working.

**Comment by JustinStitt** [comment]
Reporting back.

I tried 10+ fonts from v3 and had no luck. I also noticed this behavior where text gets left behind from previous buffers but only on lines with LSP diagnostics (virtual text + signs).

Not sure wtf is happening. I tried fresh installs of LVIM on both the stable and nightly releases (with their relative NVIM releases)

![show1](https://github.com/LunarVim/LunarVim/assets/24460581/8cbff2f2-177d-4dc3-aeca-6ec34e6d6388)

**Comment by JustinStitt** [comment]
> It looks like you already have v3, otherwise you wouldn't be able to see the icons, you can try repatching / try downloading a font from their website

I think I found it's only for "Not Accessed" warnings due to the Lightbulb icon. This text glitch doesn't seem to happen with the warning or error icon. 

Interesting stuff.

**Comment by LostNeophyte** [comment]
> I think I found it's only for "Not Accessed" warnings due to the Lightbulb icon. This text glitch doesn't seem to happen with the warning or error icon.

not all icons were updated

I've got no idea, can't help you, sorry
you can try a different terminal

**Comment by LostNeophyte** [comment]
Someone had the same issue on discord and using preview version of the terminal fixed it

**Comment by JustinStitt** [comment]
> Someone had the same issue on discord and using preview version of the terminal fixed it

My quick fix was just reverting LunarVim back a few months. Didn't really want to bisect the issue so I just chose a SHA that seemed far enough back where I did not have the issue.

I may try the preview Windows Terminal, if that's what you're referring to.

**Comment by andrewwong1221** [comment]
I'm currently using `release-1.3/neovim-0.9-0aea5a68` and I also ran into the same issue with the exact same "artifact" issue only when using lvim inside of tmux. The incorrect `f`, `t`, and `q`  alignment on the start screen is the exact same issue I ran into after updating Lunarvim.

The current preview version of Microsoft windows terminal fixes the issue for me but I will note that Alacritty also displays these  offset issues.

**Comment by JustinStitt** [comment]
Using the preview version of Microsoft Terminal fixed it for me as well. I wonder if this issue should be re-opened now that there's another reported case as per @andrewwong1221

**Comment by LostNeophyte** [comment]
This but has little to do with lunarvim, the bug is in the terminals

**Comment by ccbiozhaw** [comment]
i have the issue in wezterm and ms terminal. It only happens with icons enabled + tmux.
