### ISSUE TITLE
Nerd Font v3 Compatability

### ISSUE THREAD

**Issue by quaxlyqueen** [LunarVim/LunarVim#4154]
### Problem description

After updating nerd fonts, certain icons were no longer visible in LunarVim. Specifically, in my install under lua/lvim/icons.lua, the icons missing were:

- Folder (line 14),
- Watches (line 72),
- Close (line 82),
- FindFile (line 96),
- FindText (line 97),
- Folder (line 99),
- Tab (line 119), and
- Hint (line 141)

I figured this was an issue with the hex codes changing for these icons, so I cloned the LunarVim repo and opened lua/lvim/icons.lua. All icons were present. I copied over everything from this cloned icons.lua file to my installed icons.lua, and it fixed it. I saw some Reddit posts indicating others had this issue. I don't know why this fixed it or why the issue occurred in the first place, or if this is something to be corrected in LunarVim or in Nerd Fonts.

Note: This is the first issue I've ever done, please let me know if there's anything I should change going forward.

### LunarVim version

release-1.3/neovim-0.9-e823ccb9

### Neovim version (>= 0.8.0)

NVIM v0.9.0

### Terminal name

iTerm2

### Operating system/version

macOS 13.3.1 (a)

### Screenshots

<img width="1440" alt="Screenshot 2023-05-10 at 5 55 41 PM" src="https://github.com/LunarVim/LunarVim/assets/55456786/c1b775c9-9c16-4407-8fa6-91e964002c5c">

**Comment by lunacd** [comment]
Fixed by #4111. Please update by running `:LvimUpdate`.

**Comment by quaxlyqueen** [comment]
Thank you!
