### ISSUE TITLE
nvim-cmp sometimes auto-select the first entry and sometimes does not

### ISSUE THREAD

**Issue by lunacd** [LunarVim/LunarVim#4155]
### Problem description

nvim-cmp sometimes auto-select the first entry and sometimes does not. See example:

[Screencast from 2023-05-10 17-58-11.webm](https://github.com/LunarVim/LunarVim/assets/35328328/ed7f518d-897d-4815-89e3-b30f96663225)

In the example, `rect` is not automatically selected (I need to press `TAB` to complete), but its members are auto-selected (I need to press `ENTER` to complete). I don't mind it behaving either way (preferably it never auto-selects), but I want it to be consistent. How would I configure this behavior?

Btw, I don't see a clear criterion by which `nvim-cmp` is selecting between the two behaviors. So I think the default LunarVim config should enforce consistency, no matter which of the two it chooses.

### What I Tried

I tried setting `lvim.builtin.cmp.preselects = require('cmp').PreselectMode.None` (which I think is the default?). But that didn't affect this behavior.

### LunarVim version

release-1.3/neovim-0.9-fcb65eaa

### Neovim version (>= 0.8.0)

0.9.0

### Terminal name

kitty

### Operating system/version

Debian 12

**Comment by YinAqu** [comment]
Try `lvim.builtin.cmp.preselect = require "cmp.types.cmp".PreselectMode.None` for not selecting `height` by default in your example.
