### ISSUE TITLE
Add Haskell support?

### ISSUE THREAD

**Issue by v0d1ch** [LunarVim/LunarVim#4156]
### Feature Description

I would like to see Haskell included in the list of supported languages.

**Comment by kobzar** [comment]
Just try to use this one 
https://github.com/mrcjkb/haskell-tools.nvim

**Comment by v0d1ch** [comment]
I already do :) Just thought using LunarVim for haskell would give me some nice defaults and less configuration. Feel free to close this issue if there are no plans to _support_ Haskell right now.

**Comment by kobzar** [comment]
Lvim don't have a presets for any languages by default
Users must make presets for each of them
https://github.com/LunarVim/starter.lvim
