### ISSUE TITLE
nvimtree mapping setting invalid

### ISSUE THREAD

**Issue by bigzhu** [LunarVim/LunarVim#4157]
### Problem description

NvimTree mapping setting invalid when lvim upgrade:

```
lvim.builtin.nvimtree.setup.view.mappings = {
	list = {
		{ key = "l", action = "tabnew" },
		{ key = "h", action = "tabnew" },
		{ key = "t", action = "tabnew" },
	},
}
```

### LunarVim version

 master-b1c72541

### Neovim version (>= 0.8.0)

NVIM v0.10.0-dev

### Terminal name

Alacritty

### Operating system/version

Ubuntu 23.04"

**Comment by cpea2506** [comment]
Yep. Because this way of setting keymapping has been deprecated. Please use `on_attach` and `vim.keymap.set` instead.

https://github.com/nvim-tree/nvim-tree.lua/wiki/Migrating-To-on_attach

**Comment by kobzar** [comment]
@bigzhu this is help you?

**Comment by ChristianChiarulli** [comment]
@bigzhu here is an example of how to do it: https://github.com/ChristianChiarulli/lvim/blob/master/lua/user/nvimtree.lua

```
local function my_on_attach(bufnr)
  local api = require "nvim-tree.api"

  local function opts(desc)
    return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
  end

  api.config.mappings.default_on_attach(bufnr)

  vim.keymap.set("n", "l", api.node.open.edit, opts "Open")
  vim.keymap.set("n", "h", api.node.navigate.parent_close, opts "Close Directory")
  vim.keymap.set("n", "v", api.node.open.vertical, opts "Open: Vertical Split")
  vim.keymap.del("n", "<C-k>", { buffer = bufnr })
end

lvim.builtin.nvimtree.setup.on_attach = my_on_attach
```

**Comment by bigzhu** [comment]
@ChristianChiarulli thanks, this setting works well
