### ISSUE TITLE
Ability to extract user settings and configuration out of lvim main git repo

### ISSUE THREAD

**Issue by przbadu** [LunarVim/LunarVim#4159]
### Feature Description

I was checking AstroNVim and one feature that I really like on it is user has an ability to extract all user config into their own git repo:

https://github.com/AstroNvim/user_example.

I think this is very helpful because, I can keep all of my work specific settings in my own git repo and if I have to setup new system, I can quickly install LunarVim, clone my settings, and everything is good to go.

**Comment by LostNeophyte** [comment]
you can make a git repo in .config/lvim, here's an example https://github.com/abzcoding/lvim
