### ISSUE TITLE
linter staticcheck warning level

### ISSUE THREAD

**Issue by gczgcz2015** [LunarVim/LunarVim#4164]
### Problem description

i want to use "wraning" level but now it is "error" level, when using staticcheck linter
![image](https://github.com/LunarVim/LunarVim/assets/15188637/2bc8534b-249d-41d2-81de-df947d4c5534)

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.9.0)

NVIM v0.9.0

### Operating system/version

Linux

### Affected language servers

gopls

### Actual behavior

![image](https://github.com/LunarVim/LunarVim/assets/15188637/6956783e-9852-42ee-8e15-42322cc01067)

### support info

```console
 Language client log: /home/paul/.local/state/nvim/lsp.log
 Detected filetype:   go
 
 2 client(s) attached to this buffer: 
 
 Client: gopls (id: 1, pid: nil, bufnr: [3])
 	filetypes:       go, gomod, gowork, gotmpl
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             gopls
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [3])
 	filetypes:       go
 	autostart:       false
 	root directory:  Running in single file mode.
 	cmd:             <function>
 
 Configured servers list: gopls
```

```LvimInfo
    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                lir
* bufnr:                   1
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

**Comment by gczgcz2015** [comment]
what should i do to config it to a warning level

**Comment by kobzar** [comment]
Try this one

```lua
local linters = require("lvim.lsp.null-ls.linters")
linters.setup({
	{ command = "staticcheck", extra_args = { "--ignore", "112" }, filetypes = { "go" } },
})

```

Replace this for needed params.
```
extra_args = { "--ignore", "112" },
```

**Comment by gczgcz2015** [comment]
> Try this one
> 
> (statickcheck must be installed)
> 
> ```lua
> local linters = require("lvim.lsp.null-ls.linters")
> linters.setup({
> 	{ command = "staticcheck", extra_args = { "--ignore", "112" }, filetypes = { "go" } },
> })
> ```
> 
> Replace this for needed params.
> 
> ```
> extra_args = { "--ignore", "112" },
> ```

thanks for reply but i dont find a flag to ignore some rule or change error level to warn level.
![image](https://github.com/LunarVim/LunarVim/assets/15188637/b8f63855-a928-4ca8-9573-bf60d196a087)

**Comment by gczgcz2015** [comment]
> Try this one
> 
> (statickcheck must be installed)
> 
> ```lua
> local linters = require("lvim.lsp.null-ls.linters")
> linters.setup({
> 	{ command = "staticcheck", extra_args = { "--ignore", "112" }, filetypes = { "go" } },
> })
> ```
> 
> Replace this for needed params.
> 
> ```
> extra_args = { "--ignore", "112" },
> ```

thanks for reply and it worked，but it is ignored this rule. i want to change level （from error to warn）.

**Comment by kobzar** [comment]
MAybe something like {"severity", "warn"} ?

**Comment by LostNeophyte** [comment]
something like this https://gitlab.com/lostneophyte/dotfiles/-/blob/2953a13f9765e245229d8af0e50eb4352ab44f5f/lvim/.config/lvim/lua/user/lsp.lua#L24-32
```lua
local null_ls = require("null-ls")
null_ls.register({
  null_ls.builtins.diagnostics.cspell.with({
    diagnostics_postprocess = function(diagnostic)
      diagnostic.severity = vim.diagnostic.severity.INFO
    end,
    filetypes = { "markdown" },
  }),
})
```
modify to your needs

**Comment by gczgcz2015** [comment]
> something like this https://gitlab.com/lostneophyte/dotfiles/-/blob/2953a13f9765e245229d8af0e50eb4352ab44f5f/lvim/.config/lvim/lua/user/lsp.lua#L24-32
> 
> ```lua
> local null_ls = require("null-ls")
> null_ls.register({
>   null_ls.builtins.diagnostics.cspell.with({
>     diagnostics_postprocess = function(diagnostic)
>       diagnostic.severity = vim.diagnostic.severity.INFO
>     end,
>     filetypes = { "markdown" },
>   }),
> })
> ```
> 
> modify to your needs

tanks a lot. it worked！after config：
```lua
local null_ls = require("null-ls")
null_ls.register({
  null_ls.builtins.diagnostics.staticcheck.with({
    diagnostics_postprocess = function(diagnostic)
      diagnostic.severity = vim.diagnostic.severity.WARN
    end,
    filetypes = { "go" },
  }),
})
```

![image](https://github.com/LunarVim/LunarVim/assets/15188637/4a0eb4d5-0845-4ec6-9977-c22f2b709fa1)
