### ISSUE TITLE
Installation fails 

### ISSUE THREAD

**Issue by nelson777** [LunarVim/LunarVim#4165]
### Problem description

I got the exact same error of this issue: 

https://github.com/LunarVim/LunarVim/discussions/3707

Only now is a different version so that command doesn't work anymore.

When I try to install lunarvim I get the following error:

```
(...)
Initializing first time setup
Lazy setup complete--------------------------------------------------------------------------------
Verifying core plugins
mismatch at [schemastore.nvim]: expected [0b396f5], got [b8e6c7d]
[ERROR]: Unable to verify plugins, make sure to manually run ':Lazy sync' when starting lvim for the first time.

```
The command I'm using is the following (copied from lunarvim's site):

`LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)
`

There's a correct install command besides that one as in the other issue ? How can I check what's causing this ? 

I'm using Nvim 0.9 build from source, after many problems trying to install it. If you guys think it's relevant I can write my whole ordeal trying to install it. But it's long and I guess it's solved. At least the health checks pass.

I want to use the NVim's stable version.

### LunarVim version

1.3

### Neovim version (>= 0.9.0)

0.9.0

### Terminal name

Terminator

### Operating system/version

Linux Mint 21 Vanessa

### Steps to reproduce

Just run the command I mentioned above

**Comment by kobzar** [comment]
run uninstall.sh script and install again

**Comment by nelson777** [comment]
done that several times

**Comment by nelson777** [comment]
@kobzar same thing

@LostNeophyte how do I start it ? lvim in the command line doesn't work

**Comment by nelson777** [comment]
It worked... thanks :)

**Comment by LostNeophyte** [comment]
>  But the problem still remains in installation. Do you think I close this issue or do we investigate a bit further to solve the installation also.

leave it open, but I currently can't fix it as I can't reproduce it on my machine

**Comment by nelson777** [comment]
Can I provide any useful info ?

**Comment by kobzar** [comment]
I was try to reinstall lvim and dont have this error. 
@nelson777 could you provide full log from start command to install for end? 

Did you change your env to bash before run install script?( i mean bash, and next input command)

**Comment by nelson777** [comment]
Well I tried several times the installation. The first installed the dependencies, then the following ones just used what was already installled. The log I saw in the last one was this:

```
❯ LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)

      88\                                                   88\
      88 |                                                  \__|
      88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
      88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
      88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
      88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
      88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
      \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|

--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies: neovim, tree-sitter-cli?
[y]es or [n]o (default: no) : y
Installing node modules with yarn..
yarn global v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "neovim@4.10.1" with binaries:
      - neovim-node-host
success Installed "tree-sitter-cli@0.20.8" with binaries:
      - tree-sitter
Done in 2.98s.
All NodeJS dependencies are successfully installed
--------------------------------------------------------------------------------
Would you like to install LunarVim's Python dependencies: pynvim?
[y]es or [n]o (default: no) : y
Verifying that pip is available..
/usr/bin/python3: No module named ensurepip
Installing with pip..
Requirement already satisfied: pynvim in /home/nelson/.local/lib/python3.10/site-packages (0.4.3)
Requirement already satisfied: greenlet in /usr/lib/python3/dist-packages (from pynvim) (1.1.2)
Requirement already satisfied: msgpack>=0.5.0 in /usr/lib/python3/dist-packages (from pynvim) (1.0.3)
All Python dependencies are successfully installed
--------------------------------------------------------------------------------
Would you like to install LunarVim's Rust dependencies: fd::fd-find, rg::ripgrep?
[y]es or [n]o (default: no) : y
Installing missing Rust dependency with cargo
    Updating crates.io index
     Ignored package `fd-find v8.7.0` is already installed, use --force to override
warning: be sure to add `/home/nelson/.cargo/bin` to your PATH to be able to run the installed binaries
All Rust dependencies are successfully installed
--------------------------------------------------------------------------------
Backing up old /home/nelson/.local/share/lunarvim to /home/nelson/.local/share/lunarvim.old
--------------------------------------------------------------------------------
Backing up old /home/nelson/.cache/lvim to /home/nelson/.cache/lvim.old
--------------------------------------------------------------------------------
Cloning LunarVim configuration
Cloning into '/home/nelson/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 17286, done.
remote: Counting objects: 100% (2564/2564), done.
remote: Compressing objects: 100% (284/284), done.
remote: Total 17286 (delta 2352), reused 2350 (delta 2240), pack-reused 14722
Receiving objects: 100% (17286/17286), 13.90 MiB | 15.37 MiB/s, done.
Resolving deltas: 100% (10919/10919), done.
--------------------------------------------------------------------------------
Installing LunarVim shim
make: Entrando no diretório '/home/nelson/.local/share/lunarvim/lvim'
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: /home/nelson/.local/bin/lvim
make: Saindo do diretório '/home/nelson/.local/share/lunarvim/lvim'
Creating desktop file
Preparing Lazy setup
Initializing first time setup
Lazy setup complete--------------------------------------------------------------------------------
Verifying core plugins
mismatch at [schemastore.nvim]: expected [0b396f5], got [b8e6c7d]
[ERROR]: Unable to verify plugins, make sure to manually run ':Lazy sync' when starting lvim for the first time.

```
Is there another log file ?

Also I just started to see the tutorial video and found that I don't have a config.lua installed. At least not with all that configurations. My file just have some links in the top. Is this normal ?

**Comment by kobzar** [comment]
@LostNeophyte why the default config is clean?
https://github.com/LunarVim/LunarVim/blob/master/utils/installer/config.example.lua

**Comment by johnatandias** [comment]
I had the same problem, to solve it I did the following steps:
- I uninstalled using the script `bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/uninstall.sh)`
- Confirmed the neovim version, using the command `neovim --version`
  - I have version 0.9.0
- I commented out my configuration file `~/.config/lvim/config.lua`
- I installed using the install script for neovim in version 0.9.0
  - `LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)`
- I redid the [post install](https://www.lunarvim.org/docs/installation/post-install) steps
- I run the `Lazy sync` command
- I uncommented my config file
- Done 🤩

**Comment by nelson777** [comment]
@johnatandias That's also what I did, except for the fact that I got the example config from Github's history.  It worked. But I guess the best would be for the installer to end properly don't you agree ? It would be better if we could find why it's not finishing.
