### ISSUE TITLE
XML file icons not being rendered correctly

### ISSUE THREAD

**Issue by ubmit** [LunarVim/LunarVim#4166]
### Problem description

Steps to reproduce:

1. Start LunarVim
2. Press <leader>f to search files or <leader>e to open explorer
3. XML file icons will be rendered like a "box"

By the way, I'm using `font-jetbrains-mono-nerd-font` from the `homebrew/cask-fonts` tap (https://github.com/ryanoasis/nerd-fonts#option-4-homebrew-fonts)

### LunarVim version

release-1.3/neovim-0.9-27987368

### Neovim version (>= 0.9.0)

NVIM v0.9.0

### Terminal name

Kitty

### Operating system/version

macOS 13.3.1 (a)

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/8797405/112b0794-ef33-4e2d-9eba-0616c84a3906)
![image](https://github.com/LunarVim/LunarVim/assets/8797405/e6dc8547-b91c-47b9-869d-5607a085d813)

**Comment by kobzar** [comment]
Read this one
https://github.com/LunarVim/LunarVim/issues/4107

try to run **brew update**
Check your fonts version

And try another font for test like 
brew install font-hack-nerd-font

**Comment by LostNeophyte** [comment]
make sure your nerd font version is 3 and run `:Lazy sync`

**Comment by LostNeophyte** [comment]
nvm, It's a bug, I can reproduce

**Comment by ubmit** [comment]
thank you @LostNeophyte 🙌
