### ISSUE TITLE
null-ls not setup in certain configurations

### ISSUE THREAD

**Issue by ben-ce** [LunarVim/LunarVim#4170]
### Problem description

Hi!

I experienced some behavior changes with null-ls invocation on different setup scenarios.
Could you please clarify if this is the expected behavior or not?

### LunarVim version

master-af2db622

### Neovim version (>= 0.9.0)

NVIM v0.9.0

### Operating system/version

Arch Linux 6.3.2-arch1-1

### Affected language servers

null-ls

### Actual behavior

Null-ls formatters and linters are not setup when it's user defined configuration occurs after the use of any `require("lvim.lsp.manager").setup()` call.
Originally I had all the LSP related configs in the `user/lsp/init.lua` like this (no lazy loading on filetype):
```
require("user.lsp.languages.rust")
require("user.lsp.languages.python")
require("user.lsp.languages.go")
require("lvim.lsp.manager").setup("marksman")

local formatters = require("lvim.lsp.null-ls.formatters")
formatters.setup({
	{ command = "stylua", filetypes = { "lua" } },
	{ command = "prettier", filetypes = { "markdown" } },
	{
		command = "prettier",
		args = { "--print-width", "100" },
		filetypes = { "typescript", "typescriptreact" },
	},
	{ command = "goimports", filetypes = { "go" } },
	{ command = "gofumpt", filetypes = { "go" } },
	{ command = "rubocop", filetypes = { "ruby" } },
	{ command = "black", filetypes = { "python" } },
})

local linters = require("lvim.lsp.null-ls.linters")
linters.setup({
	{ command = "flake8", filetypes = { "python" } },
})

```

The files `user/lsp/languages/rust.lua` and `user/lsp/languages/python.lua` don't contain any LSP manager stuff, but `user/lsp/languages/go.lua` does and `require("lvim.lsp.manager").setup("marksman")` does it also.
Given this order of configuration with the content above the null-ls client did not attach to any buffer.
Python file:
![image](https://github.com/LunarVim/LunarVim/assets/60733449/c950ea7d-c030-483a-a602-fe0a5eb86c6e)
Markdown file:
![image](https://github.com/LunarVim/LunarVim/assets/60733449/64cd1dc1-9379-4d73-9086-40b1892dc972)

After removing the go and marksman require lines the null-ls client attach with the configured formatters and linters.
Python file:
![image](https://github.com/LunarVim/LunarVim/assets/60733449/cc41b4aa-5743-44b8-8fb2-6b8d5eeed446)
Markdown file:
![image](https://github.com/LunarVim/LunarVim/assets/60733449/4ef4403c-411e-48e4-ae83-a1aeb49897fe)

The same thing happens when I reorder the config. Also the order of the LSP manager function invocation matters: `marksman` language server can only be attached if the `require("lvim.lsp.manager").setup("marksman")` is before the `require("user.lsp.languages.go")`
And for the go LSP the reverse is true.

If these are configured in lazy loading ftplugin style obviously the behavior disappears.

### support info

See actual behavior

**Comment by LostNeophyte** [comment]
currently `lvim.lsp.manager` shouldn't be used directly in config.lua, it breaks lazy loading

**Comment by ben-ce** [comment]
Thanks for the help!
ftplugin it is then.
