### ISSUE TITLE
Weird characters appear in LunarVim when running within tmux.

### ISSUE THREAD

**Issue by jackblackevo** [LunarVim/LunarVim#4175]
### Problem description

When opening LunarVim within tmux, strange characters are displayed in both the Command Line and the editing area.

### LunarVim version

release-1.3/neovim-0.9-0aea5a68

### Neovim version (>= 0.9.0)

NVIM v0.9.0

### Terminal name

Windows Terminal

### Operating system/version

Ubuntu 22.10 (WSL2) @ Windows 11 Pro 22H2 Build 22621.1702

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/15699333/d98c4299-a55f-482b-879a-9e3ae753f062)

The left screen displays a strange "4" appearing in the Neovim Command Line, along with the letters "f", "t", "q", and so on appearing in the editing screen when LunarVim is launched within tmux. On the right screen, LunarVim is opened without tmux, and everything appears to be normal.

**Comment by LostNeophyte** [comment]
the letters are leftovers from the dashboard 
![image](https://github.com/LunarVim/LunarVim/assets/110467150/fc593c84-610b-41fe-9e08-8fc765b33a06)
the issue is not in lunarvim, try updating tmux, new nerdfont icons are the cause of this

**Comment by jackblackevo** [comment]
When I changed the [lualine style](https://www.lunarvim.org/docs/configuration/appearance/statusline#style) to `default`, the "4" in the Neovim Command Line disappeared.

`lvim.builtin.lualine.style = "default"`

![image](https://github.com/LunarVim/LunarVim/assets/15699333/37438a44-7cd7-4e6a-9ab2-bd7d0693cf3c)

**Comment by jackblackevo** [comment]
On [Windows Terminal Preview 1.17](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-17-release/), everything is working fine.
