### ISSUE TITLE
support  the feature of  code complete for  Xmake Lua api

### ISSUE THREAD

**Issue by hawkinchina** [LunarVim/LunarVim#4176]
### Feature Description

When lvim edit Xmake Lua script , it cannot  support api code complete.

xmake  is easier  than cmake.

**Comment by LostNeophyte** [comment]
I don't know Chinese, but I google translated https://github.com/xmake-io/xmake/issues/2656 and it looks like xmake doesn't have type annotations, can vscode complete xmake scripts?

**Comment by hawkinchina** [comment]
maybe , it is ok now , please check

https://github.com/LuaLS/lua-language-server/wiki/Addons
https://github.com/LuaLS/LLS-Addons/tree/main/addons/xmake

and modify the config.lua of lvim and you should copy the Addon for xmake to the directory as the following configuration.
```lua
-- lsp for xmake
require("lspconfig").sumneko_lua.setup({
	settings = {
		-- Settings go here!
		Lua = {
			workspace = {
				userThirdParty = {
					"/Users/jack/.config/lvim/LuaAddons",
				},
			},
		},
	},
})
```
