### ISSUE TITLE
Python Auto Indent on a statement with parentheses incorrect

### ISSUE THREAD

**Issue by Fish1** [LunarVim/LunarVim#4178]
### Problem description

Python auto indentation gets pushed to a parentheses, even if the parentheses is a character in a string.

![image](https://github.com/LunarVim/LunarVim/assets/13600696/9b717102-899e-496e-a66e-08569cc40463)

### LunarVim version

release-1.3/neovim-0.9-e823ccb9

### Neovim version (>= 0.9.0)

NVIM v0.9.0

### Terminal name

Windows Terminal

### Operating system/version

WSL 2

### Steps to reproduce

1) use python in lunar vim
2) indent an if statement that has parentheses inside a string

**Comment by LostNeophyte** [comment]
use `lvim.builtin.treesitter.indent.disable = {"yaml"}`
