### ISSUE TITLE
Toggleterm/lazygit not working

### ISSUE THREAD

**Issue by lunacd** [LunarVim/LunarVim#4182]
### Problem description

1. Invoke lazygit/toggleterm using either the shortcut or command.
2. On first invocation, I see a window very briefly (like 0.2s). The following invocations have no effect at all.

### LunarVim version

release-1.3/neovim-0.9-0aea5a68 

### Neovim version (>= 0.9.0)

0.9.0

### Terminal name

kitty

### Operating system/version

Debian 12

### Steps to reproduce

I'm on default config.

Also I'm using zsh if that might be the cause.

**Comment by sanbids** [comment]
toggle terminal <M-1/2/3> not working ,, only <C-\> this work . anyone had solution

**Comment by LostNeophyte** [comment]
do you have lazygit installed?

**Comment by LostNeophyte** [comment]
> toggle terminal <M-1/2/3> not working ,, only <C-> this work . anyone had solution

what's your OS and terminal?

**Comment by lunacd** [comment]
> do you have lazygit installed?

Yes. Invoking lazygit directly works. Also, toggleterm doesn’t work either, so I’m guessing something with lvim.terminal module is causing this (or something with my setup).

**Comment by LostNeophyte** [comment]
does toggleterm work if you add `if true then return end` at the top of your config.lua?

**Comment by lunacd** [comment]
> does toggleterm work if you add `if true then return end` at the top of your config.

It works! I found out what in my config that messed it up. Thank you! And I learned a new debug trick.

My issue is resolved but I'll keep this open for @sanbids. Feel free to close it once his issue is resolved.

**Comment by kobzar** [comment]
@sanbids must open new issue with show his info about os, neovim e.t.c

**Comment by sanbids** [comment]
problem solve .. problem was happen due to zellij .
