### ISSUE TITLE
Python's black formatter isn't using provided args

### ISSUE THREAD

**Issue by huberemanuel** [LunarVim/LunarVim#4183]
### Problem description

I've setup my config.lua to use black formatter with custom args:
```lua
local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup {
  {
    name = "black",
    args = { "-l", 100, "--preview" }
  },
}
```

The `--preview` uses a feature to break lines longer than specified (100 in this case). When I run the command in the shell all works, but when I save or manually execute ``:! black %` it executes black without the custom args. 

### LunarVim version

release-1.3

### Neovim version (>= 0.9.0)

neovim-0.9-e399a08d

### Operating system/version

Arch Linux on Windows 10 x86_64 Kernel: 5.15.90.1-microsoft-standard-WSL2

### Affected language servers

null-ls

### Steps to reproduce

Configure black with the following parameters in the config.lua file:
```lua
local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup {
  {
    name = "black",
    args = { "-l", 100, "--preview" }
  },
}
```

Try to format a python file with line length greater than 100.

### Actual behavior

Black isn't executed with specified `args`

### Expected behavior

Black execute with specified `args`

### support info

```console
 Language client log: /home/ehs/.local/state/lvim/lsp.log
 Detected filetype:   alpha
 
 0 client(s) attached to this buffer: 
 
 1 active client(s) not attached to this buffer: 
 
 Client: lua_ls (id: 1, bufnr: [5])
 	filetypes:       lua
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             lua-language-server
 
 Configured servers list: lua_ls
```

```console

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                lspinfo
* bufnr:                   8
* treesitter status:       inactive

Active client(s)
* name:                      lua_ls
* id:                        1
* supported filetype(s):     lua
* attached buffers:          5
* root_dir pattern:          5
* capabilities:              documentRangeFormattingProvider | hoverProvider          | referencesProvider
                             colorProvider                   | definitionProvider     | documentFormattingProvider
                             documentHighlightProvider       | typeDefinitionProvider | workspaceSymbolProvider
                             foldingRangeProvider            | documentSymbolProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, antlersls, azure_pipelines_ls, omnisharp, cssmodules_ls, denols, docker_compose_language_service, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, neocmake, phpactor, psalm, pylsp, pylyzer, pyre, quick_lint_js, reason_ls, rnix, rome, ruby_ls, ruff_lsp, solang, solc, sorbet, sourcery, spectral, sqlls, sqls, standardrb, stylelint_lsp, svlangserver, tflint, unocss, verible, vtsls, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

**Comment by kobzar** [comment]
```lua
    vim.opt.colorcolumn = "120" -- vertical line for line length
	
    { command = "black", extra_args = { "--line-length", "120" }, filetypes = { "python" } },
```

**Comment by huberemanuel** [comment]
@kobzar I tried your suggestion, but the long strings aren't automatically split into multiple lines. To achieve that, the [--preview](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#preview-style) option must be passed to black. Although I didn't know the `colorcolumn` options, thanks :).

I tried the following config with extra_args and with args, and neither worked:
```lua
formatters.setup {
  { name = "isort" },
  {
    name = "black",
    extra_args = { "--line-length", 100, "--preview" },
    filetypes = { "python" }
  },
}
```

Btw, I'm using black==23.1.0

**Comment by kobzar** [comment]
maybe you need something like this ``` vim.opt.wrap = true -- wrap lines```

**Comment by huberemanuel** [comment]
That actually does the job! It isn't the black executing the formatting and I still think it should take custom args, but I'm happy with the solution. Thanks, kobzar!

**Comment by kobzar** [comment]
Black can’t show wraps on n live mode. Only when you run formatter like SPS l f 

but you can play with this params 
https://vim.works/2019/03/16/wrapping-text-in-vim/
