### ISSUE TITLE
Error Sourcing Nvim-Treesitter

### ISSUE THREAD

**Issue by Qwer-TeX** [LunarVim/LunarVim#4191]
### Problem description

When I open lvim I get this message for every file 
![Screenshot 2023-05-16 8 30 55 PM](https://github.com/LunarVim/LunarVim/assets/128016252/38645f6c-74ce-48a0-bd47-1120504205eb)

Please Help 

### LunarVim version

release-1.3/neovim-0.9-0aea5a68

### Neovim version (>= 0.9.0)

NVIM v0.10.0-dev-347+g6b19170d4

### Terminal name

"Chromebook Developer's Terminal" in debian 11 container

### Operating system/version

ChromeOs 114.0.5735.12

### Steps to reproduce

1. lvim
2. lvim ~/.config/lvim/config.lua

### Screenshots

![Screenshot 2023-05-16 8 30 55 PM](https://github.com/LunarVim/LunarVim/assets/128016252/38645f6c-74ce-48a0-bd47-1120504205eb)

**Comment by kobzar** [comment]
Try to isntall stable neovim version from binary (dont compile)
https://github.com/neovim/neovim/releases/tag/stable

**Comment by LostNeophyte** [comment]
`release-1.3/neovim-0.9` is made for neovim 0.9, don't use it with nightly
