### ISSUE TITLE
Lvim + Tmux + Windows Terminal

### ISSUE THREAD

**Issue by and-rose** [LunarVim/LunarVim#4195]
### Problem description

Since updating to LunarVim 1.3 I've noticed some weird rendering behaviour in tmux. I didn't have any issues with 1.2 but it's started rendering characters in slightly incorrect places and wrapping text to the next line unexpectedly. It behaves perfectly fine outside of tmux though.

I've tried tweaking my $TERM var and launching tmux with a default config but can't seem to resolve it. Any ideas? Maybe this isn't a Lvim issue, but it has definitely changed since updating from 1.2 > 1.3

### LunarVim version

Release-1.3/neovim-0.9-0ae5a68

### Neovim version (>= 0.9.0)

NVIM v0.9.0

### Terminal name

Windows Terminal + Tmux

### Operating system/version

Windows 11

### Steps to reproduce

Tmux Version: 3.3a

1. Uninstall lvim 1.2 using `bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh`
2. Install lvim 1.3 using `LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)`
3. Open a Tmux session
4. Open lvim

### Screenshots

Weird printing of splash screen characters.
![image](https://github.com/LunarVim/LunarVim/assets/84128724/301d56f3-1228-479e-bdfd-858cfff88a32)
Notice the line wrap on the line count:
![image](https://github.com/LunarVim/LunarVim/assets/84128724/0bbb28c3-349b-4b31-bddf-6e9f22b0652f)
Lvim splash with default tmux config:
![image](https://github.com/LunarVim/LunarVim/assets/84128724/e0ef6f90-2074-4036-9ef2-025ae391c1ad)

**Comment by LostNeophyte** [comment]
Update the terminal to the preview version

**Comment by jackblackevo** [comment]
Hi @and-rose,
I am encountering a similar issue: #4175.
