### ISSUE TITLE
cant correctly quit in some cases

### ISSUE THREAD

**Issue by palandovalex** [LunarVim/LunarVim#4198]
### Problem description

Open some files
use command
:q
after that, the terminal freezes, does not react to anything, and it has to be cut down from the outside

### LunarVim version

release-1.3/neovim-9.0-0aea5a68

### Neovim version (>= 0.9.0)

NVIM v0.10.0-dev Build type: RelWithDebInfo

### Terminal name

Terminator

### Operating system/version

DISTRIB_DESCRIPTION="Linux Mint 21.1 Vera"

### Steps to reproduce

Open file

```python
#!/bin/python3
import asyncio
import datetime
import json
from pathlib import Path


STAT_DIR = Path(__file__).resolve().parent.parent.joinpath('stat')

class DaylyStat:
    def __init__(self) -> None:
        self.stat = {}

    def add_action(self, action_name):
        if self.stat.get(action_name):
            self.stat[action_name] +=1
        else:
            self.stat[action_name] =1
            

async def periodic():
    STAT = DaylyStat()
    prev_day = str(datetime.date.today())
    prev_mongth = str(datetime.datetime.now().month)

    print(prev_mongth, prev_day)
    exit

    for file in STAT_DIR.iterdir():
        name = file.name
        with open(file, 'r') as f:
            data: dict = json.load(f)
        day_count = data.get(prev_day, 0)
        


    while True:
        new_day = datetime.date.today()
        new_mongth = datetime.datetime.now().month

        if prev_day != new_day:
            #action
            


            prev_day = new_day
            if prev_mongth != new_mongth:
                #action
                prev_mongth = new_mongth



loop = asyncio.get_event_loop()
loop.run_until_complete(periodic())
```

try to quit with :q  or :wq

**Comment by LostNeophyte** [comment]
don't use lvim 1.3 with neovim nightly, use neovim 0.9, if the problem persists ping me / reopen the issue

**Comment by palandovalex** [comment]
previously, I used a "night" lvim with a night nvim. This problem was just there. 
Tryed reinstall nvim and lvim - nightly

it sticks on:
Initializing first time setup
If i force to stop process on this moment - then in his bug with :q

**Comment by LostNeophyte** [comment]
Initializing first time setup will take some time, it's downloading plugins, let it finish
 
 can you reproduce the issue with clean neovim?

**Comment by palandovalex** [comment]
clean neovim? what you meen

**Comment by palandovalex** [comment]
my nvim without any configs - hasnt this problem

**Comment by palandovalex** [comment]
Lvim with cleen config - also

**Comment by LostNeophyte** [comment]
>Lvim with cleen config - also

I assume by also you mean that it doesn't' have the problem, in that case the problem is with your config

**Comment by palandovalex** [comment]
I meend that lvim without config - has problem

**Comment by palandovalex** [comment]
Using quit on dashboard - correct quit
using files - problems

**Comment by LostNeophyte** [comment]
I have no problems with :q


https://github.com/LunarVim/LunarVim/assets/110467150/66fa253b-4a62-4116-9825-9b82d57b3a30

**Comment by palandovalex** [comment]
https://github.com/LunarVim/LunarVim/assets/75374436/4a9b000d-e87a-4720-b8ba-9b55d0b9a65f


So, what i should do, to find causes of problem?

**Comment by LostNeophyte** [comment]
you can try disabling core plugins, uninstalling lsp, installing lsp, try without internet connection

**Comment by punknroll** [comment]
same problem here!

**Comment by kobzar** [comment]
@palandovalex could you provide the video with problem?

**Comment by LostNeophyte** [comment]
> same problem here!

what's your OS, terminal, nvim and lvim version?

**Comment by LostNeophyte** [comment]
@punknroll do you experience the same problem with nvim 0.9?

**Comment by punknroll** [comment]
> 

no, the problem is gone in 0.9

**Comment by LostNeophyte** [comment]
Lvim 1.3 is made only for nvim 0.9, but according to @palandovalex the issue occurs with lvim master + nvim nightly which makes me think that it's a nvim issue

**Comment by fredrik-hansen** [comment]
FWIW I had the same issue with nvim v0.10.0-dev but gone after changing nvim version, so it seems plausible to think lvim master+nvim nightly combination is the culprit here.
