### ISSUE TITLE
Illegal character in group name

### ISSUE THREAD

**Issue by edvn0** [LunarVim/LunarVim#4199]
### Problem description

I'm editing c# files and Omnisharp seems to generate incorrect semantic tokens for syntax analysis (?). I've read several other posts on how to fix this for neovim, see for instance [this post](https://github.com/LunarVim/LunarVim/issues/3716#issuecomment-1464766484).

I'm just very unsure of how to fix this in a vanilla installation of LunarVim. Do you have any help moving forward for me?

Where do I put this new file? How do I incorporate it with config.lua?

### LunarVim version

master-23ace671

### Neovim version (>= 0.9.0)

 v0.9.0-dev-1339+g9d5cbd1b1

### Operating system/version

Windows 11

### Affected language servers

omnisharp

### Steps to reproduce

1. lvim ~/test.cs
2. :LspInstall omnisharp
3. Write some code
4. Receive several errors of "Invalid character in group name"

### Actual behavior

Several error messages with message "Invalid character in group name"

### Expected behavior

No errors at all

### support info

LspInfo

Language client log: /home/<username>/.local/state/nvim/lsp.log
 Detected filetype:   mason
 
 0 client(s) attached to this buffer: 
 
 1 active client(s) not attached to this buffer: 
 
 Client: omnisharp (id: 1, bufnr: [11])
 	filetypes:       cs, vb
 	autostart:       true
 	root directory:  /home/<username>/MyProject
 	cmd:             omnisharp -z -s /home/<username>/MyProject --hostPID 14797 DotNet:enablePackageRestore=false --encoding utf-8 --languageserver FormattingOptions:EnableEditorConfigSupport=true Sdk:IncludePrereleases=true
 
 Configured servers list: omnisharp

-----------------------------------------------------
LvimInfo
    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 

Buffer info
* filetype:                lspinfo
* bufnr:                   23
* treesitter status:       inactive

Active client(s)
* name:                      omnisharp
* id:                        1
* supported filetype(s):     [cs, vb]
* attached buffers:          11
* root_dir pattern:          11

Automatic LSP info
* Skipped servers: [angularls, ansiblels, antlersls, csharp_ls, cssmodules_ls, denols, docker_compose_language_service, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, neocmake, phpactor, psalm, pylsp, pyre, quick_lint_js, reason_ls, rnix, rome, ruby_ls, ruff_lsp, solang, solc, sorbet, sourcery, spectral, sqlls, sqls, stylelint_lsp, svlangserver, tflint, unocss, verible, vtsls, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active:

**Comment by brneor** [comment]
If you just want to implement the solution you linked in Lunarvim, putting the following code in your `config.lua` must be enough:

```lua
lvim.lsp.on_attach_callback = function(client, bufnr)
  if client.name == "omnisharp" then
    client.server_capabilities.semanticTokensProvider = {
      full = vim.empty_dict(),
      legend = {
        tokenModifiers = { "static_symbol" },
        tokenTypes = {
          "comment",
          "excluded_code",
          "identifier",
          "keyword",
          "keyword_control",
          "number",
          "operator",
          "operator_overloaded",
          "preprocessor_keyword",
          "string",
          "whitespace",
          "text",
          "static_symbol",
          "preprocessor_text",
          "punctuation",
          "string_verbatim",
          "string_escape_character",
          "class_name",
          "delegate_name",
          "enum_name",
          "interface_name",
          "module_name",
          "struct_name",
          "type_parameter_name",
          "field_name",
          "enum_member_name",
          "constant_name",
          "local_name",
          "parameter_name",
          "method_name",
          "extension_method_name",
          "property_name",
          "event_name",
          "namespace_name",
          "label_name",
          "xml_doc_comment_attribute_name",
          "xml_doc_comment_attribute_quotes",
          "xml_doc_comment_attribute_value",
          "xml_doc_comment_cdata_section",
          "xml_doc_comment_comment",
          "xml_doc_comment_delimiter",
          "xml_doc_comment_entity_reference",
          "xml_doc_comment_name",
          "xml_doc_comment_processing_instruction",
          "xml_doc_comment_text",
          "xml_literal_attribute_name",
          "xml_literal_attribute_quotes",
          "xml_literal_attribute_value",
          "xml_literal_cdata_section",
          "xml_literal_comment",
          "xml_literal_delimiter",
          "xml_literal_embedded_expression",
          "xml_literal_entity_reference",
          "xml_literal_name",
          "xml_literal_processing_instruction",
          "xml_literal_text",
          "regex_comment",
          "regex_character_class",
          "regex_anchor",
          "regex_quantifier",
          "regex_grouping",
          "regex_alternation",
          "regex_text",
          "regex_self_escaped_character",
          "regex_other_escape",
        },
      },
      range = true,
    }
  end
end
```

That's how I use.

**Comment by LostNeophyte** [comment]
Run :LvimCacheReset, we switched to csharpls https://github.com/LunarVim/LunarVim/pull/4079

**Comment by edvn0** [comment]
@LostNeophyte I hear you. Still, everytime I run :LspUninstall omnisharp and reopen a C# file, it automatically installs itself.

**Comment by LostNeophyte** [comment]
Update lunarvim and it will use csharpls instead
