### ISSUE TITLE
set lvim.use_icons to false doesn't work

### ISSUE THREAD

**Issue by 5ilvers** [LunarVim/LunarVim#4209]
### Problem description

When i try to set lvim.use_icons = false in config.lua in ~/.config/lvim/

I still get icons everywhere

I tried to reset Lvim Cache, and reinstall as well

### LunarVim version

1.3

### Neovim version (>= 0.9.0)

NVIM v0.9.0

### Terminal name

kitty

### Operating system/version

Ubuntu 20.04

### Steps to reproduce

lvim.use_icons = false in config.lua in ~/.config/lvim/
re-open lvim, still sees icons everywhere

**Comment by kobzar** [comment]
This is working. But a lot of plugins use personal icons settings 
So, you must disable it to. 
run this command to generate full options file for lvim
```lua
lvim --headless +'lua require("lvim.utils").generate_settings()' +qa && sort -o lv-settings.lua{,}
```
use search and you found a lot of settings icons for different places.

**Comment by kobzar** [comment]
Tmp close as inactive state

**Comment by nickdesaulniers** [comment]
Bump; seeing this as well.

**Comment by stevenroose** [comment]
This bugs me too, I can't get the icons configured so I see rectangles everywhere even with `lvim.use_icons = false`.

**Comment by dunkOnIT** [comment]
Also struggling with this.
* Icons not displaying even after installing a NerdFont and setting it in my terminal 
* `lvim.use_icons = false` doesn't work either - still seeing boxes everywhere
