### ISSUE TITLE
Find files seems to be searching my entire home dir

### ISSUE THREAD

**Issue by gammons** [LunarVim/LunarVim#4211]
### Problem description

I am noticing that find files is searching all files in my home dir and not my cwd.   This is on a fresh install of lvim with no custom configuration.

### LunarVim version

release-1.3

### Neovim version (>= 0.9.0)

NVIM v0.9.0

### Terminal name

kitty

### Operating system/version

Arch Linux / up-to-date

### Steps to reproduce

To reproduce:

1. Head to any directory
2. `<Leader>f`
3. Notice that it's not searching files within the directory you're in.  It's searching all files in your home dir

### Screenshots

Example when I am in my `~/.config/lvim` dir:
![image](https://github.com/LunarVim/LunarVim/assets/38560/c003062b-e665-43de-aa6a-565d0b64eee4)

**Comment by gammons** [comment]
huh, so `:pwd` is returning my home dir!  that's interesting.

**Comment by gammons** [comment]
ok, so it turns out that something in my existing neovim setup was messing with this.   I removed my `~/.config/nvim` folder and now it acts as expected.  Thanks for the help!

**Comment by gammons** [comment]
Actually, I think that was a red herring.  The actual issue was that I was testing things in the `~/.config` dir.  Any time you are in a directory within `~/.config` (or probably any directory with a dot in front), the cwd will default to the home dir, and not the actual cwd.

If you test in any directory without a dot in front, it works as expected.

**Comment by gammons** [comment]
I can replicate this behavior by going into a directory that starts with a dot (`~/.config`, for instance).

**Comment by kobzar** [comment]
can't confirm
try to add in your config 
```
vim.opt.shell = "/bin/sh"
```

**Comment by gammons** [comment]
the `vim.opt.shell` did not fix the issue ;-(

@LostNeophyte - when I am in my `~/.config/lvim` folder:

1. start lvim with `lvim` and then use `leader f` (without doing anything else in between)
- I actually see the files in the cwd!  It's only when I open up a file and then `leader f` again that I see files in the home dir.  
- `:pwd` still reports the directory being `/home/grant`.

2. start lvim with `lvim .` and then use `leader f` (without doing anything else in between)
- Same behavior as above.  
- `:pwd` reports the correct dir, but once I open a file, `pwd` reverts to my home dir.

**Comment by LostNeophyte** [comment]
In that case you have a root marker in your home directory, configure project.nvim differently

**Comment by gammons** [comment]
I haven't configured project.nvim at all.  

One other data point - if the folder is a git repo, fzf behaves normally.

**Comment by LostNeophyte** [comment]
It's configured by default, change its configuration

**Comment by gammons** [comment]
Ahh, yep, this is some sort of bug with `project.nvim`.  I added `lvim.builtin.project.active = false` and now find files behaves normally.

Thank you @LostNeophyte for your help!

**Comment by LostNeophyte** [comment]
Duplicate of #3362, #2222

**Comment by gammons** [comment]
Thanks, that makes sense.  I'm wondering if this default should be part of the documentation.  It definitely caused a lot of head scratching for me, and it definitely felt like a bug.

**Comment by JayAndJef** [comment]
I agree with this, it should be either clearer in the documentation or not a default option. Still love lvim though.
