### ISSUE TITLE
LunarVim slows to a crawl on Elixir file with many pipes

### ISSUE THREAD

**Issue by Hermanverschooten** [LunarVim/LunarVim#4213]
### Problem description

Take a default lunarvim install (eg Docker version), with treesitter for elixir installed.
Open a file called `test.ex`
insert the line: `|> IO.inspect()`
Now yank that line and paste it say 80 times.
LunarVim becomes almost non-responsive.

### LunarVim version

master-7b413c42

### Neovim version (>= 0.9.0)

NVIM v0.9.1

### Terminal name

iTerm2

### Operating system/version

macOS 13.3.1 (a)

### Steps to reproduce

1. Take a default lunarvim install (eg Docker version).
2. :TSInstall elixir (just to be sure)
3. Create a file called `test.ex`
4. insert the line: `|> IO.inspect()`
5. Now yank that line and paste it say 80 times.

**Comment by Hermanverschooten** [comment]
Some more info. It only seems to happen if the line starts with the pipe operator.
So If you change the line to read `1 |> IO.inspect()` it does not happen.

**Comment by LostNeophyte** [comment]
does `:TSBufDisable illuminate` fix the slowness?

**Comment by Hermanverschooten** [comment]
Yes it does
