### ISSUE TITLE
Hover information is too narrow sometimes with a `.` prefixing the info

### ISSUE THREAD

**Issue by benediktms** [LunarVim/LunarVim#4219]
### Problem description

Sometimes the hover information displayed by the LSP hover is too narrow and not all the type information is displayed. This seems to happen for primitive types or simple types that do not have multi line definitions, e.g. `string` rather than
```ts
type Foo = {
	bar: string
	baz: boolean
}
```

This is especially jarring if you have types that are actually array but that information is  obscured, i.e. the hover only shows `string` rather than `string[]`

### LunarVim version

release-1.3/neovim-0.9-0aea5a68

### Neovim version (>= 0.9.0)

NVIM v0.9.1

### Terminal name

kitty

### Operating system/version

Arch Linux

### Steps to reproduce

1. Open a file that has LSP support
2. create a variable with a simple type, e.g.
![image](https://github.com/LunarVim/LunarVim/assets/48836135/6fc4835d-40f5-4c28-b758-ffbcf545c395)
3. hover over the variable. Part of the type information will be obscured and only accessible if you enter the hover (even then you will never see the full type): 
![image](https://github.com/LunarVim/LunarVim/assets/48836135/235392b0-31f7-446e-aab1-d1423933afe3) 
![image](https://github.com/LunarVim/LunarVim/assets/48836135/ac9d7b8b-03de-4155-a55f-dbf13d6877d4)

**Comment by LostNeophyte** [comment]
I can't reproduce with lua ls
![image](https://github.com/LunarVim/LunarVim/assets/110467150/ec38d364-605a-4e62-8706-487fa2a653ec)

**Comment by benediktms** [comment]
This was caused by the [marks.nvim](https://github.com/chentoast/marks.nvim) plugin I was using and is related to https://github.com/chentoast/marks.nvim/issues/79
