### ISSUE TITLE
null-ls can't format code based on .prettierrc configuration for a specific project

### ISSUE THREAD

**Issue by minhman2501** [LunarVim/LunarVim#4221]
### Problem description

Hi!

I experienced some formatting errors with null-ls on prettierrc configuration.
Can you give me the solution to fix it ?

### LunarVim version

release-1.3/neovim-0.9-0aea5a68

### Neovim version (>= 0.9.0)

NVIM v0.9.0

### Operating system/version

Window 11

### Affected language servers

tsserver

### Actual behavior

Null-ls formatter can't format my code based on the prettierrc configuration
I have installed the prettier formatter with Mason and here are my configuration
![image](https://github.com/LunarVim/LunarVim/assets/90081072/9cf33e5d-59c4-41ec-8dbb-92233d82ca41)

![image](https://github.com/LunarVim/LunarVim/assets/90081072/26e8c0c0-97f2-4b5d-bac0-2182ed32f1da)

I have also installed the prettier library into my Next project:
![image](https://github.com/LunarVim/LunarVim/assets/90081072/24bd9b8f-ac77-4620-a4aa-8adb7c7cb12e)

And here is my .prettierrc configuration for my Next project:
![image](https://github.com/LunarVim/LunarVim/assets/90081072/c6276aec-ba9c-4725-8e4d-9dc851d890e8)

This is my codes before formating:
![image](https://github.com/LunarVim/LunarVim/assets/90081072/363cf76f-37c6-4a4c-ae13-d73204c88e6a)

But after I did a little bit of coding and save the file, null-ls can't format my codes based on the prettierrc file 
![image](https://github.com/LunarVim/LunarVim/assets/90081072/3c636af9-6cf9-428f-8548-86408fdfb3fc)

### Expected behavior

This is my codes after being formatted by VSCode editor
![image](https://github.com/LunarVim/LunarVim/assets/90081072/f032b569-5b2b-4400-bbdd-6d73a09c3770)

As you can see, it works perfectly

### support info

See the actual behavior and compare it with the expected one

**Comment by kobzar** [comment]
Did you read this?
https://www.lunarvim.org/docs/configuration/language-features/linting-and-formatting

```lua
local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup {
  { name = "black" },
  {
    name = "prettier",
    ---@usage arguments to pass to the formatter
    -- these cannot contain whitespace
    -- options such as `--line-width 80` become either `{"--line-width", "80"}` or `{"--line-width=80"}`
    args = { "--print-width", "100" },
    ---@usage only start in these filetypes, by default it will attach to all filetypes it supports
    filetypes = { "typescript", "typescriptreact" },
  },
}
```

Save file and try SPS + l + f also

**Comment by minhman2501** [comment]
> ```lua
> co
> ```

I think this configuration is meant for the whole editor. What I want is the null-ls formatters stick to the .prettierrc configuration for a specific project only. 
Example: although my args in my config.lua would be: args = { "--print-width", "100" }, but the prettierrc configured the print-width for the project is 80, null-ls would format the print-width to 80

**Comment by minhman2501** [comment]
> Did you read this? [lunarvim.org/docs/configuration/language-features/linting-and-formatting](https://www.lunarvim.org/docs/configuration/language-features/linting-and-formatting)
> 
> ```lua
> local formatters = require "lvim.lsp.null-ls.formatters"
> formatters.setup {
>   { name = "black" },
>   {
>     name = "prettier",
>     ---@usage arguments to pass to the formatter
>     -- these cannot contain whitespace
>     -- options such as `--line-width 80` become either `{"--line-width", "80"}` or `{"--line-width=80"}`
>     args = { "--print-width", "100" },
>     ---@usage only start in these filetypes, by default it will attach to all filetypes it supports
>     filetypes = { "typescript", "typescriptreact" },
>   },
> }
> ```
> 
> Save file and try SPS + l + f also

I think this configuration is meant for the whole editor. What I want is the null-ls formatters stick to the .prettierrc configuration for a specific project only.
Example: although my args in my config.lua would be: args = { "--print-width", "100" }, but the prettierrc configured the print-width for the project is 80, null-ls would format the print-width to 80

**Comment by kobzar** [comment]
Try something like this
```lua
require("null-ls").setup {
    on_attach = require("lvim.lsp").common_on_attach,
    sources = {
      nls.builtins.formatting.prettier.with {
        condition = function(utils)
          return utils.root_has_file { ".prettierrc" }
        end,
        prefer_local = "node_modules/.bin",
    }
}
```

**Comment by minhman2501** [comment]
> Try something like this
> 
> ```lua
> require("null-ls").setup {
>     on_attach = require("lvim.lsp").common_on_attach,
>     sources = {
>       nls.builtins.formatting.prettier.with {
>         condition = function(utils)
>           return utils.root_has_file { ".prettierrc" }
>         end,
>         prefer_local = "node_modules/.bin",
>     }
> }
> ```

I did but nothing happens.

**Comment by LostNeophyte** [comment]
>Try something like this
require("null-ls").setup {
...

calling setup of builtin plugins is not allowed, in all cases it breaks lazy loading (a current bug), in most cases it does nothing

**Comment by minhman2501** [comment]
My friend @cpea2506 tried to recreate the problem on his Mac, but it worked perfectly. Right now, we still don't know what caused the problem

**Comment by kobzar** [comment]
I am using mac to. 
i was create new folder, init git, add formatters rule in config to ue prettier with python files. Add .prettierrc file in my project folder - but this dont work.

**Comment by kylo252** [comment]
This would be an upstream configuration issue. 

Try enforcing `condition` to make sure that the `CWD` matches what you're expecting, see: 
https://github.com/kylo252/lvim/blob/eb9a7e2e68690a392362d9ab1c59be5e54063739/lua/user/lsp.lua#L62-L73
