### ISSUE TITLE
add a way to start lvim without loading user config

### ISSUE THREAD

**Issue by LostNeophyte** [LunarVim/LunarVim#4222]
### Feature Description

something like nvim --clean
it would be useful for troubleshooting

**Comment by kobzar** [comment]
The best variant will be to select configuration
like
``` lvim --config config_test.lua```

In this case you can use default/working config but always can try \nother one to test plugins or default conf to find issue.

**Comment by ChristianChiarulli** [comment]
I think clean is doing something different here since it doesn't necessitate any config argument, making it easier to load the defaults. @kobzar

**Comment by kylo252** [comment]
You can change `$LUNARVIM_CONFIG_DIR` and that will do the same thing.

Let me know if you had something else in mind.

**Comment by LostNeophyte** [comment]
> You can change `$LUNARVIM_CONFIG_DIR` and that will do the same thing.
> 
> Let me know if you had something else in mind.

oh, that will work, I didn't think of that
