### ISSUE TITLE
terraformls - format fails

### ISSUE THREAD

**Issue by Chris-Leeworthy** [LunarVim/LunarVim#4223]
### Problem description

Using Lunarvim with terraform-ls, when I try to format my code with `<leader>lf` I get an error message
```[LSP][terraformls] timeout```

I have tried uninstalling and re-installing terraform-ls via Mason but the outcome is the same.

### LunarVim version

master-804e08cb-dirty

### Neovim version (>= 0.9.0)

NVIM 0.9.1

### Operating system/version

macOS 13.4

### Affected language servers

terraformls

### Steps to reproduce

1. Open any terraform source file with Lunarvim
2. try to format the code with `<leader>lf`

### Actual behavior

Error message

`[LSP][terraformls] timeout`

### Expected behavior

Expected the terraform code to be reformatted.  I think this has worked in previous versions.

### support info

```console
:LspInfo
 Language client log: /Users/leewoc/.local/state/nvim/lsp.log
 Detected filetype:   terraform
 
 1 client(s) attached to this buffer: 
 
 Client: terraformls (id: 1, bufnr: [1])
 	filetypes:       terraform, terraform-vars
 	autostart:       true
 	root directory:  /Users/leewoc/Documents/XXXXXXXXXXXXXXXXXXXXXX
 	cmd:             /Users/leewoc/.local/share/nvim/mason/bin/terraform-ls serve
 
 Configured servers list: terraformls
```
```console
:LvimInfo
Buffer info
* filetype:                terraform
* bufnr:                   1
* treesitter status:       active

Active client(s)
* name:                      terraformls
* id:                        1
* supported filetype(s):     [terraform, terraform-vars]
* attached buffers:          1
* root_dir pattern:          1
* capabilities:              workspaceSymbolProvider    | hoverProvider       | documentSymbolProvider
                             referencesProvider         | definitionProvider
                             documentFormattingProvider | declarationProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, antlersls, azure_pipelines_ls, omnisharp, cssmodules_ls, denols, docker_compose_language_service, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, java_language_server, jedi_language_server, ltex, neocmake, phpactor, psalm, pylsp, pylyzer, pyre, quick_lint_js, reason_ls, rnix, rome, ruby_ls, ruff_lsp, solang, solc, sorbet, sourcery, spectral, sqlls, sqls, standardrb, stylelint_lsp, svlangserver, tflint, unocss, verible, vtsls, vuels]

Formatters info
* Active: 
* Supported: terraform_fmt

Linters info
* Active: 
* Supported: [terraform_validate, tfsec]

Code actions info
* Active: 
```

**Comment by LostNeophyte** [comment]
your lvim version is dirty, what modifications did you make to the core? (send the output of `git -C ~/.local/share/lunarvim/lvim diff`)

**Comment by Chris-Leeworthy** [comment]
Thanks, I've obviously managed to modify something I was only supposed to be looking at. Is there an easy way to revert to the 'proper' code? 

```
index b701f7e4..aedd8db9 100644
--- a/lua/lvim/core/telescope.lua
+++ b/lua/lvim/core/telescope.lua
@@ -100,10 +100,10 @@ function M.config()
     },
     extensions = {
       fzf = {
-        fuzzy = true, -- false will only do exact matching
+        fuzzy = true,                   -- false will only do exact matching
         override_generic_sorter = true, -- override the generic sorter
-        override_file_sorter = true, -- override the file sorter
-        case_mode = "smart_case", -- or "ignore_case" or "respect_case"
+        override_file_sorter = true,    -- override the file sorter
+        case_mode = "smart_case",       -- or "ignore_case" or "respect_case"
       },
     },
   }
(END)
```

**Comment by LostNeophyte** [comment]
is that "/Users/leewoc/Documents/XXXXXXXXXXXXXXXXXXXXXX" the correct root dir of the project?
does `<cmd>lua require('lvim.lsp.utils').format({timeout_ms=5000})<cr>` work?

**Comment by LostNeophyte** [comment]
> The lua require statement you posted returned without error.

did it format the code?

**Comment by Chris-Leeworthy** [comment]
Yes it did.

Is there some way for me to tell Lunarvim to override the project root?

**Comment by LostNeophyte** [comment]
> Yes it did.

lvim.builtin.which_key.mappings.l.f[1] = "<cmd>lua require('lvim.lsp.utils').format({timeout_ms=5000})<cr>"

> Does this mean the formatter is running on the entire git repo?

the lsp is running on the entire repo, it should have an impact on the format speed though

> Is there some way for me to tell Lunarvim to override the project root?

manually configuring terraformls

**Comment by Chris-Leeworthy** [comment]
Thank you so much for your help @LostNeophyte 🥇
