### ISSUE TITLE
Haven't found a way to customize Telescope and seeing Preview pane in find_files

### ISSUE THREAD

**Issue by alduro** [LunarVim/LunarVim#4224]
### Problem description

`<leader> f`

### LunarVim version

master-5c7d7124

### Neovim version (>= 0.9.0)

NVIM v0.10.0-dev-1401+gf4136c9d4-Homebrew

### Terminal name

iTerm2

### Operating system/version

macOS 13.4

### Steps to reproduce

`<leader> f`

### Screenshots

<img width="1396" alt="Screenshot 2023-06-06 at 16 31 23" src="https://github.com/LunarVim/LunarVim/assets/183364/6cf6d792-014d-4a34-a8ad-64336a58dbf3">

**Comment by brneor** [comment]
What exactly do you want to achieve?

**Comment by LostNeophyte** [comment]
bind the key to `:Telescope find_files` to enable preview
