### ISSUE TITLE
Setting autochdir to true doesn't work

### ISSUE THREAD

**Issue by joajfreitas** [LunarVim/LunarVim#4225]
### Problem description

1. Add `vim.o.autochdir = true` to config.lua 
2. Open a file in a subdirectory of project
3. Write `vs` into the command prompt
4. Expected completions are the files in the subfolder. The actual completions are the files in the project root. 

### LunarVim version

804e08c

### Neovim version (>= 0.9.0)

0.9.1

### Terminal name

wezterm

### Operating system/version

Archlinux

### Steps to reproduce

1. Add `vim.o.autochdir = true` to config.lua 
2. Open a file in a subdirectory of project
3. Write `vs` into the command prompt
4. Expected completions are the files in the subfolder. The actual completions are the files in the project root.

**Comment by LostNeophyte** [comment]
if you want to use autochdir then disable project.nvim (core plugin)
