### ISSUE TITLE
Error sometimes when close a buffer (BufferKill)

### ISSUE THREAD

**Issue by KevenGoncalves** [LunarVim/LunarVim#4227]
### Problem description

1. Open many buffers
2. Try to close them, one of them will give a error

### LunarVim version

release-1.3/neovim-0.9-0aea5a68

### Neovim version (>= 0.9.0)

v0.9.1

### Terminal name

kitty

### Operating system/version

macOS 13.4

### Steps to reproduce

1. Open many buffers
2. Try to close them, one of them will give a error

### Screenshots

<img width="1440" alt="Captura de Tela 2023-06-07 às 13 06 04" src="https://github.com/LunarVim/LunarVim/assets/80492657/3135d37a-27cb-491b-b20e-85dcb4e3150b">
<img width="1440" alt="Captura de Tela 2023-06-07 às 13 06 25" src="https://github.com/LunarVim/LunarVim/assets/80492657/eeaeeda6-41c6-4e7c-8cfc-3652ae5106df">

**Comment by KevenGoncalves** [comment]
I read the error and searching for something I found out that maybe the treesitter and bufferline are doing this behavior,
link to my dotfiles configs: https://github.com/KevenGoncalves/lunarvim-dotfiles

**Comment by KevenGoncalves** [comment]
@LostNeophyte I discovery that when the option lvim.builtin.treesitter.rainbow.enable = true it's activated cause that bug

**Comment by KevenGoncalves** [comment]
I solved my bug changing my old nvim-ts-rainbow for HiPhish/nvim-ts-rainbow2

**Comment by dang309** [comment]
It worked! Thank you so much!
