### ISSUE TITLE
Astro-lsp is not working after Mason updated (lvim1.3, nvim 0.9)

### ISSUE THREAD

**Issue by salimp2009** [LunarVim/LunarVim#4229]
### Problem description

 after updating astro-lsp; it started giving this error . it was working before the Mason updated it. (lvim1.3 , nvim 0.9) I tested with default lvim config on 2 different computers and there are other people effected as well
 
![image](https://github.com/LunarVim/LunarVim/assets/46407603/64f2319d-1d81-4b12-8d2f-b185aed387fa)

### LunarVim version

release-1.3/neovim-0.9-0aea5a68  

### Neovim version (>= 0.9.0)

Nvim 0.9.0

### Operating system/version

Linux; Arch

### Affected language servers

astro-ls

### Steps to reproduce

1. mkdir astro_test & cd astro_test
2. git clone git@github.com:nodetec/notebin.git
3. cd notebin 
4. npm i
5. lvim .
6. open any .astro file
7. you will see the error msg posted above
8. also Space Li and astro lsp is not attached / no language server features

### Actual behavior

 you will see the error msg posted above
 also press ` Space Li` and astro lsp is not attached / no language server features

### Expected behavior

expected astro-ls to attach and no error ; it was working before Mason update astro-language-server

### support info

![image](https://github.com/LunarVim/LunarVim/assets/46407603/7314b58a-0a77-4328-90a4-7e5d41bc187c)

![image](https://github.com/LunarVim/LunarVim/assets/46407603/bb70ec70-f2a9-4870-9486-7d626e377c3e)

### logs

```console
[WARN][2023-06-08 23:43:09] ...lsp/handlers.lua:137	"The language server emmet_ls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-06-08 23:43:09] ...lsp/handlers.lua:137	"The language server emmet_ls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-06-08 23:43:18] ...lsp/handlers.lua:137	"The language server tailwindcss triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2023-06-09 12:14:37] LSP logging initiated
[WARN][2023-06-09 12:14:37] ...lsp/handlers.lua:137	"The language server emmet_ls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-06-09 12:14:37] ...lsp/handlers.lua:137	"The language server emmet_ls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2023-06-09 12:20:10] LSP logging initiated
[WARN][2023-06-09 12:20:10] ...lsp/handlers.lua:137	"The language server emmet_ls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-06-09 12:20:10] ...lsp/handlers.lua:137	"The language server emmet_ls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2023-06-09 12:29:28] LSP logging initiated
[WARN][2023-06-09 12:29:28] ...lsp/handlers.lua:137	"The language server emmet_ls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-06-09 12:29:28] ...lsp/handlers.lua:137	"The language server emmet_ls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

### Screenshots

see above LspInfo and actual error message

**Comment by salimp2009** [comment]
![image](https://github.com/LunarVim/LunarVim/assets/46407603/85d1fa02-57a7-4dea-b314-559d5e67870e)

**Comment by salimp2009** [comment]
I managed to install previous version of astro-language-server by doing ;
`:MasonInstall astro-language-server@1.0.8`
and after that it worked again.
Apparently there is something not compatible with the latest update with LunarVim handling it or neovim. If someone has a language server installed in neovim can try if latest version works there to see if it is lvim specific or not. That might help

**Comment by salimp2009** [comment]
apparently this is a neovim issue and it is fixed in the new versions but it is not available in lvim1.3 release version. until then either use the old version of astro-ls (1.0.8) or switch to lvim master are the 2 options;

https://github.com/withastro/language-tools/issues/559

**Comment by salimp2009** [comment]
since it is nvim-lsp issue. I am closing although would be nice if we can get an nvim-lsp update for lvim 1.3

**Comment by seanaye** [comment]
Nevermind, needed to run `:LvimSyncCorePlugins`
