### ISSUE TITLE
Error installing lunarvim

### ISSUE THREAD

**Issue by jordisantamaria** [LunarVim/LunarVim#4231]
### Problem description

Hi, I installed lvim Nightly (Neovim 0.9.0) and It's giving this error the instalation:

_Initializing first time setupyError detected while processing command line..VimLeavePre Autocommands for "*"..function CleanupStuff:
line    1:
E492: Not an editor command:         NvimTreeClose
Lazy setup complete--------------------------------------------------------------------------------
Verifying core plugins
mismatch at [schemastore.nvim]: expected [6c580be], got [0b396f5]
[ERROR]: Unable to verify plugins, make sure to manually run ':Lazy sync' when starting lvim for the first time._

So I run command :Lazy sync.

I can run lvim, but the problem is LSP is not working, I'm entering in a react file with format tsx and when I check with LSP is running I see It:
![image](https://github.com/LunarVim/LunarVim/assets/6263700/d10bb8e2-6c0b-42a1-b398-5c928e9b0034)

As you can see, only null-ls server is running.
But tslint server is already installed by default.
It also happens of course with ts file, js files and any kind of file, server don't works so I don't have autocomplete.

### LunarVim version

master-f24df08

### Neovim version (>= 0.9.0)

NVIM v0.9.0

### Operating system/version

linux mint

### Affected language servers

all, tested with tsx, ts, js, html, css

### Steps to reproduce

bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

Then open lvim and check If lsp works

### Actual behavior

LSP not working, only running null-ls server

### Expected behavior

Lsp working, be able to run tsserver  and others servers as need, to check errors and be able to use autocomplete, etc...

### support info

```console
 Language client log: /home/jordi/.local/state/lvim/lsp.log
 Detected filetype:   json
 
 0 client(s) attached to this buffer: 
 
 1 active client(s) not attached to this buffer: 
 
 Client: null-ls (id: 1, bufnr: [8])
 	filetypes:       python, typescript, typescriptreact
 	autostart:       false
 	root directory:  /home/jordi/projects/courses/test-admin
 	cmd:             <function>
 
 Configured servers list: 
```

**Comment by LostNeophyte** [comment]
did you already have lunarvim installed when you run the installer? 
do you recognize the CleanupStuff function?
does :LvimCacheReset fix the lsp issue?

**Comment by jordisantamaria** [comment]
Seems I tried to uninstall and reinstall It again, pressing enter to skip optional installing libraries and now finally lunarvim had beein installed without errors and lsp is working.
