### ISSUE TITLE
"tag" is not deprecated in lazy.nvim

### ISSUE THREAD

**Issue by fdelacruz** [LunarVim/LunarVim#4237]
### Problem description

tried to pin fidget.nvim (j-hui/fidget.nvim) to a tagged branch:
 `"j-hui/fidget.nvim", tag = "legacy"`
I got the deprecation warning in the screenshot
still:
`"j-hui/fidget.nvim", version = "legacy"` doesn't register.

### LunarVim version

master

### Neovim version (>= 0.9.0)

NVIM 0.9.0

### Terminal name

iTerm2

### Operating system/version

macOS 10.15.7

### Screenshots

<img width="572" alt="Screen Shot 2023-06-13 at 7 56 22 PM" src="https://github.com/LunarVim/LunarVim/assets/148098/9173d3f4-6a9a-4173-8182-e2aa6c9966f9">

**Comment by LostNeophyte** [comment]
you're right, I missed that, in this case you can also use `branch`, i'll fix that later

**Comment by brneor** [comment]
For reference, even though `lazy.nvim`'s [plugin spec](https://github.com/folke/lazy.nvim#-plugin-spec) describes both _tag_ and _version_, the [migration guide](https://github.com/folke/lazy.nvim#-migration-guide) suggests `tag -> version`. 

So maybe not entirely Lunarvim's fault for this confusion, unless I'm missing something.

**Comment by LostNeophyte** [comment]
> For reference, even though `lazy.nvim`'s [plugin spec](https://github.com/folke/lazy.nvim#-plugin-spec) describes both _tag_ and _version_, the [migration guide](https://github.com/folke/lazy.nvim#-migration-guide) suggests `tag -> version`.
> 
> So maybe not entirely Lunarvim's fault for this confusion, unless I'm missing something.

version is only suggested for the case when the value of tag is "*", i missed that. other bullet points don't have an equal sign 
- `run` ➡️ `build`
- `tag='*'` ➡️ `version="*"`

**Comment by fdelacruz** [comment]
Thanks in advance for looking into this. 
I thought i was going crazy then I tried pinning **fidget** in my nvim with _tag = "legacy"_ and it worked.

**Comment by fdelacruz** [comment]
Thanks for looking into this.

**Comment by fdelacruz** [comment]
Any updates?

**Comment by ducker0010** [comment]
I got the same issue. Hope you can fix this @LostNeophyte

**Comment by fdelacruz** [comment]
@ducker0010 just use `branch = "legacy"` for now

**Comment by ducker0010** [comment]
@fdelacruz  thanks for your help. But it's still not working
  {
    "j-hui/fidget.nvim",
    branch ="legacy",
    config = function()
      require("fidget").setup()
    end,
  },
above is my config.lua

**Comment by LostNeophyte** [comment]
> Any updates?

I'll get around to it today/tomorrow
