### ISSUE TITLE
Expected memory consumption

### ISSUE THREAD

**Issue by mbenencase** [LunarVim/LunarVim#4244]
### Problem description

First of all, I love LunarVim.

It's not a bug, is more a general question. I have been using LunarVim for some weeks, but I haven't monitored its memory consumption. Currently, it's consuming 800Mb of memory according to System Monitor.

I wasn't expected that for such light-weight editor. However, I believe that the usage of the PyTest environment: I configured it according to [Chris@Machine Video](https://www.youtube.com/watch?v=onu_upaLKo4&t=158s). Currently, I use this a lot.

Besides that, I'm using the default configurations of LunarVim.

So my question is if this memory consumption is related to the usage of the PyTest environment. Or if other persons faces something similar on different languages and etc..

### LunarVim version

release-1.3/neovim-0.9-0aea5a68-dirty

### Neovim version (>= 0.9.0)

NVIM v-0.9.0 Builded from source

### Terminal name

zsh

### Operating system/version

Ubuntu 20.04

### Steps to reproduce

1. Install the configurations according to this [video](https://www.youtube.com/watch?v=onu_upaLKo4&t=158s)
2. Create some tests in a test_something.py file. The test functions must have the following name `test_{something_to_test}`.
3. Execute the tests using `<leader>df`.

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/18446963/3c2e19d8-d172-41fa-bc4c-9667a0db5ef3)

**Comment by quantumfate** [comment]
This might be affected by #4301  if you do any lazyload on filetype
