### ISSUE TITLE
jump from v1.2 to v1.3 init issue

### ISSUE THREAD

**Issue by etlagnese** [LunarVim/LunarVim#4245]
### Problem description

I had originally installed lunarvim 1.2 and decided to update to v1.3. I went to my lunarvim where I have this repository cloned and pulled v1.3 which caused some issues with lunarvim's init process.

I get this error: 
```
lvim/lua/lvim/config/_deprecated.lua:176: `module` in `lvim.plugins` is deprecated.
 Use `lazy = true` instead. See https://github.com/folke/lazy.nvim#-migration-guide.
```

As per the documentation for packer.nvim -> lazy.nvim migration found here: https://github.com/folke/lazy.nvim#packernvim
I made the following edit which resolved the issue for me.
```lua
--- a/lua/lvim/config/_deprecated.lua
+++ b/lua/lvim/config/_deprecated.lua
@@ -139,11 +139,6 @@ function M.post_load()
     end
     alternatives.needs = alternatives.wants
 
-    alternatives.module = function()
-      spec.lazy = true
-      return "Use `lazy = true` instead."
-    end
-
     for old_key, alternative in pairs(alternatives) do
       if spec[old_key] ~= nil then
         local message
```

### LunarVim version

release-1.3/neovim-0.9-0aea5a68-dirty

### Neovim version (>= 0.9.0)

v0.9.1

### Terminal name

Gnome default terminal

### Operating system/version

Arch

**Comment by cpea2506** [comment]
Instead of removing the source code why wouldn't you follow the suggestion to use `lazy=true`?

**Comment by etlagnese** [comment]
Because in the migration guide it said "`module` is auto-loaded. No need to specify".

**Comment by LostNeophyte** [comment]
> Because in the migration guide it said "`module` is auto-loaded. No need to specify".

yup, so remove the `module = ...` line from your config

**Comment by etlagnese** [comment]
Okay thank you, missed my `module` call out in my config.
