### ISSUE TITLE
Support for MinGW

### ISSUE THREAD

**Issue by nathan22x3** [LunarVim/LunarVim#4249]
### Feature Description

Hope you guys can support Lunar installation to MinGW ASAP!

**Comment by nathan22x3** [comment]
> I think it's already supported

I don't know, but when I run the installation script, this message appears.

![image](https://github.com/LunarVim/LunarVim/assets/67423224/34186a28-aa76-49a8-8df8-8dd13aaef225)

**Comment by LostNeophyte** [comment]
does the installer stop there? we just don't have install commands for dependencies on that platform

**Comment by nathan22x3** [comment]
> does the installer stop there? we just don't have install commands for dependencies on that platform

yup it just stopped right there

**Comment by LostNeophyte** [comment]
I'll fix that then, is MINGW64_NT just windows with mingw?

**Comment by nathan22x3** [comment]
actually, it's a [QMK MSYS](https://msys.qmk.fm)
