### ISSUE TITLE
Error when closing html buffer

### ISSUE THREAD

**Issue by mandaputtra** [LunarVim/LunarVim#4250]
### Problem description

1. Download latest release of lunarvim
2. open up 2 html file
3. close one
4. Error happen
<img width="1440" alt="Screenshot 2023-06-21 at 14 54 48" src="https://github.com/LunarVim/LunarVim/assets/23342943/d382bfff-4cff-4aa8-90c1-b189562e5be2">
<img width="1440" alt="Screenshot 2023-06-21 at 14 55 02" src="https://github.com/LunarVim/LunarVim/assets/23342943/f2edb76d-a520-4a8d-aad3-f9dd959e5ab9">

```

```

### LunarVim version

release-1.3/neovim-0.9-0aea5a68

### Neovim version (>= 0.9.0)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### Terminal name

Kitty

### Operating system/version

macOS 13.4

### Steps to reproduce

Default config

**Comment by LostNeophyte** [comment]
do you use p00f/nvim-ts-rainbow?

**Comment by mandaputtra** [comment]
Yes!, Its not required as for now?

**Comment by mandaputtra** [comment]
Fixed by deleting p00f/nvim-ts-rainbow, Thanks! havent look at the error for detail. I'll make sure of it next time

**Comment by LostNeophyte** [comment]
That plugin is no longer maintained, there is a maintained fork
