### ISSUE TITLE
Lunar vim setup themes to have a problem and it doesn't load the neovim plugins and causing multiple problems

### ISSUE THREAD

**Issue by AhmedLilah** [LunarVim/LunarVim#4251]
### Problem description

I recently updated/installed lunar vim on my Windows/WSL2 Ubuntu and almost immediately I started having problems with packer.nvim is being loaded correctly on Neovim but it doesn't show anymore on lunar vim also the Dracula color scheme that I installed for both is also working on Neovim but not lunar vim and overall it seems to be a problem.

I tried multiple steps to make a clean reinstall on both platforms to the point that I deleted my WSL2 Ubuntu and installed a new one.
I checked that pathes containing packer.nvim for neovim and it's available and tried adding this to my config.lua :
>vim.cmd[[packadd packer.nvim]]

it didn't work so I tried this 

>local packer = require('packer')
local use = packer.use
packer.startup(function()
  -- Add your packages here
end)
vim.cmd[[packadd packer.nvim]]

can someone help me I have been enjoying the development on lunar vim and it's frustrating not knowing why it broke on me.

### LunarVim version

master-407e7b0

### Neovim version (>= 0.9.0)

NVIM v0.9.1

### Terminal name

Windows terminal

### Operating system/version

Windows / Ubuntu WSL2

**Comment by AhmedLilah** [comment]
I also tried to use use the lv-settings.lua config in my config.lua by copying it or adding a require() to the file and it shows errors with almost every line when I try to launch lvim so I ended up removing it.

**Comment by LostNeophyte** [comment]
we don't use packer on master

**Comment by AhmedLilah** [comment]
> we don't use packer on master

I am not very informed on that but when i installed lunarvim about 3 months ago it was installed and i remember installing the normal release and nightly to try both.


also regarding the supplied `lv-settings.lua` configuration not working when i copy it in my config.lua is that a problem or something wrong on my behalf

**Comment by LostNeophyte** [comment]
the very long generated lv-settings.lua? it just shows all available options, it's not supposed to be used as a config

**Comment by AhmedLilah** [comment]
> the very long generated lv-settings.lua? it just shows all available options, it's not supposed to be used as a config

ok, I see where I went wrong here, thanks for the clarification. I hope I didn't take much of your time.

just one last question: is there any release that of lunar vim that used packer as I the source of this was that it was working on lunar vim the first time I installed it and it showed when I searched on google before that lunar vim uses packer as it's plugin manager and I have been trying to get it back running since the update.

**Comment by LostNeophyte** [comment]
> ok, I see where I went wrong here, thanks for the clarification. I hope I didn't take much of your time.

you didn't, i have a lot of it

> just one last question: is there any release that of lunar vim that used packer as I the source of this was that it was working on lunar vim the first time I installed it and it showed when I searched on google before that lunar vim uses packer as it's plugin manager and I have been trying to get it back running since the update.

lvim 1.2 uses packer

**Comment by AhmedLilah** [comment]
> > ok, I see where I went wrong here, thanks for the clarification. I hope I didn't take much of your time.
> 
> you didn't, i have a lot of it
> 
> > just one last question: is there any release that of lunar vim that used packer as I the source of this was that it was working on lunar vim the first time I installed it and it showed when I searched on google before that lunar vim uses packer as it's plugin manager and I have been trying to get it back running since the update.
> 
> lvim 1.2 uses packer

thank you ver much.

**Comment by AhmedLilah** [comment]
,
