### ISSUE TITLE
Icons not rendering in dashboard

### ISSUE THREAD

**Issue by InnocentZero** [LunarVim/LunarVim#4256]
### Problem description

Kitty [FAQ](https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font) says that it automatically pics up nerd fonts from the system. It works because binaries like exa are able to use the nerd fonts. However, lunarvim dashboard isn't able to render some icons. 

### LunarVim version

release-1.3/neovim-0.9-0aea5a68

### Neovim version (>= 0.9.0)

NVIM v0.9.1

### Terminal name

kitty 0.28.1

### Operating system/version

fedora linux 6.3.8

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/106757172/926a048d-2b98-4583-9a9d-9bcf94dff803)

**Comment by cpea2506** [comment]
You need to update your font to version 3.
