### ISSUE TITLE
breadcrumbs boolean icon needs a space 

### ISSUE THREAD

**Issue by Aneeqasif** [LunarVim/LunarVim#4260]
### Problem description

![Screenshot_20230627_234120](https://github.com/LunarVim/LunarVim/assets/78728701/98d75538-3c33-496c-878c-4736c7d1ff1f)

### LunarVim version

release—1 .3/neovim-0.9-0aea5a68-dirty

### Neovim version (>= 0.9.0)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Terminal name

wezterm

### Operating system/version

arco linux / linux

### Steps to reproduce

just go to sum boolean and the breadcrummp icon is mushed with the text

**Comment by LostNeophyte** [comment]
fixed on master
