### ISSUE TITLE
Lazyvim's move commit keybinding not working from LunarVim (ctrl j and ctrl k)

### ISSUE THREAD

**Issue by 1-800-jono** [LunarVim/LunarVim#4261]
### Problem description

1. Open `LazyGit` with `space gg`
2. Navigate to commits tab
3. Try to move a commit up/down. In `LazyGit` this is `ctrl-j/ctrl-k`
4. When you use `ctrl-j/ctrl-k` the `LazyGit` window closes.
5. Tried opening `lazygit` directly from the terminal and this works correctly
6. Tried in `iTerm` and `kitty`. (MacBook) 

### LunarVim version

release-1.3/neovim-0.9-0aea5a68

### Neovim version (>= 0.9.0)

NVIM v0.9.1

### Terminal name

iTerm, Kitty

### Operating system/version

macOs 12.6.6

**Comment by LostNeophyte** [comment]
that's because we have ctrl h/j/k/l bound to moving between windows in both normal and term mode, you can unbind them with lvim.keys.term_mode["<C-j>"] = false

**Comment by VladimirBeliakov** [comment]
Unfortunately, this doesn't work. To make it work I had to comment out `term_mode` in
`~/.local/share/lunarvim/lvim/lua/lvim/keymappings.lua`

I also tried adding 
```
lvim.keys.term_mode["<C-h>"] = nil
lvim.keys.term_mode["<C-j>"] = nil
lvim.keys.term_mode["<C-k>"] = nil
lvim.keys.term_mode["<C-l>"] = nil
```
to my config, but to no avail.
