### ISSUE TITLE
completion of scss variables not working

### ISSUE THREAD

**Issue by mmolhoek** [LunarVim/LunarVim#4275]
### Problem description

I have an test.scss file containing:
@use "@dnr-ui/tokens/css/core/color" as *;

.sidebar {
  width: 368px;
  background-color: $dnr-color-neutrals-100;
}

I would expect to get autocompletion on the variables defined in @dnr-ui/tokens/css/core/color, so when I change the background-color I can type $dnr-color<tab tab> and get all colors defined in color.scss

example contents of color.scss:

$dnr-color-neutrals-50: #ffffff;
$dnr-color-neutrals-100: #f5f5f5;
$dnr-color-neutrals-200: #f0f0f0;
$dnr-color-neutrals-300: #e9e9e9;

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.0)

NVIM v0.9.0

### Operating system/version

macOS 13.4.1

### Affected language servers

cssls

### Steps to reproduce

* create node_modules/@dnr-ui/tokens/css/core/color.scss and add 

$dnr-color-neutrals-50: #ffffff;
$dnr-color-neutrals-100: #f5f5f5;
$dnr-color-neutrals-200: #f0f0f0;
$dnr-color-neutrals-300: #e9e9e9;

create test.scss and add:

@use "~@dnr-ui/tokens/css/core/color" as *;

.sidebar {
  width: 368px;
  background-color: $dnr-color-neutrals-100;
}

change $dnr-color- and press tab tab or the autocomplete command
 

### Actual behavior

nothing

### Expected behavior

show variables of the @dnr-ui/tokens/css/core/color.scss file

### support info

```console
Buffer info
* filetype:                alpha
* bufnr:                   1
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, antlersls, azure_pipelines_ls, omnisharp, cssmodules_ls, denols, docker_compose_language_service, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, neocmake, phpactor, psalm, pylsp, pylyzer, pyre, quick_lint_js, reason_ls, rnix, rome, ruby_ls, ruff_lsp, solang, solc, sorbet, sourcery, spectral, sqlls, sqls, standardrb, stylelint_lsp, svlangserver, tflint, unocss, verible, vtsls, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

### logs

```console
not needed
```

### Screenshots

not needed

**Comment by mmolhoek** [comment]
I have now written a [cmp plugin](https://github.com/mmolhoek/cmp-scss) to deal with this, so no hurry in fixing this one :)

**Comment by brneor** [comment]
@mmolhoek how did you set up your plugin in Lunarvim? I'm curious on how did you add your plugin to cmp's sources.
