### ISSUE TITLE
Keymay override not working

### ISSUE THREAD

**Issue by hrai** [LunarVim/LunarVim#4276]
### Problem description

I'm mapping `pl`. 

I'm not mapping `p`. lvim automatically maps `p` to `which key`. 

I'm trying to reset the `which key` to `{}` or `nil` but that doesn't seem to work.

`lvim.builtin.which_key.mappings['p'] = {}`

I don't explicitly want to map `p` as that has custom mapping with my clipboard and want to leave it as is.

The question is how do i get rid of which key mapping for `p` as the method stated by docs isnt working.

`lua =lvim.builtin.which_key.mappings['p']` returns `{}` but `nmap p` returns below:
![image](https://github.com/LunarVim/LunarVim/assets/4055444/70b8806a-d186-453a-adf7-382f7a99e43f)

### LunarVim version

Master-af2db622

### Neovim version (>= 0.9.0)

0.9.1

### Terminal name

Windows Terminal

### Operating system/version

Windows 11

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/4055444/15c4ceca-7285-4c59-a5f1-285ea397f11c)

I've been having conversations here but with no success.

**Comment by LostNeophyte** [comment]
`:nmap p` with an empty config return no mappings on latest master(01acdde7)
if you map pl with whichkey it will automatically create a mapping for p with a menu, use `lvim.keys` if you don't want that to happen

**Comment by hrai** [comment]
@LostNeophyte 
My mapping is not with which key, it is with a different command.
`nnoremap pl :Telescope neoclip<cr>`

**Comment by hrai** [comment]
I tried below as per your instructions but no cigar.

`lvim.keys.normal_mode["pl"] = ":Telescope neoclip<CR>"`

![image](https://github.com/LunarVim/LunarVim/assets/4055444/b999d483-b6a5-4e4b-8614-36c2a95affdc)

**Comment by LostNeophyte** [comment]
in that case use `lvim.builtin.which_key.setup.triggers_blacklist.n = {"p"}`
