### ISSUE TITLE
treesitter/highlighter error executing lua

### ISSUE THREAD

**Issue by sjakk** [LunarVim/LunarVim#4279]
### Problem description

After updating kernel to rc mainline lunarvim get me this error idk what to do i already did everything that checkhealth shows and  searched for related problems but all possible solutions didnt work

What i did  - remove all user plugins (just colorscheme)  - TSUpdate - MasonUpdate - LvimUpdate - none of theses possible solutions work

### LunarVim version

release-1.3/neovim-0.9-0aea5a68

### Neovim version (>= 0.9.0)

NVIM v0.9.1

### Terminal name

Alacritty

### Operating system/version

Linux 6.4.1-arch2-1

### Screenshots

![Screenshot from 2023-07-07 01-54-56](https://github.com/LunarVim/LunarVim/assets/87045222/b47ff9c7-caab-4f68-acdc-5ce45c6f65e6)
![Screenshot from 2023-07-07 01-59-02](https://github.com/LunarVim/LunarVim/assets/87045222/2ec2b598-cb3f-4fbe-bd14-81cfd8eb0ea1)

**Comment by cpea2506** [comment]
Try `TSUninstall comment` and then `TSInstall comment`

**Comment by sjakk** [comment]
Thanks!
