### ISSUE TITLE
my lunar vim icons wont work

### ISSUE THREAD

**Issue by ariDevelops** [LunarVim/LunarVim#4280]
### Problem description

hello, I've installed lunar vim on my ubuntu, following the installation manual on lunarvim page, but  whenever I try to run it, some icons don't seem to work right..

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.0)

NVIM v0.9.1

### Terminal name

bash5.1.16 (In default ubuntu term emulator)

### Operating system/version

Ubuntu 22.04.2 LTS x86_64 

### Screenshots

![Captura de tela de 2023-07-07 14-16-33](https://github.com/LunarVim/LunarVim/assets/101485612/2445d455-6dc8-46d3-b4e1-6de4a36b0981)

**Comment by brneor** [comment]
Check if your Nerd Fonts are up to date (v3+) and properly set.

**Comment by ariDevelops** [comment]
> Check if your Nerd Fonts are up to date (v3+) and properly set in your terminal emulator.

okay thanks very much, I'm gonna try it !

**Comment by kobzar** [comment]
Close as resolved.
Write new message to reopen it.
