### ISSUE TITLE
null-ls will be archived

### ISSUE THREAD

**Issue by takomitsu** [LunarVim/LunarVim#4289]
https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621

**Comment by ajames14-chwy** [comment]
any alternatives to null-ls?

**Comment by benediktms** [comment]
Many people seem to be switching to [efm](https://github.com/mattn/efm-langserver) but I'm not sure how much feature overlap it has with null-ls

**Comment by mamaraddio** [comment]
Just now discovered [guard.nvim](https://github.com/nvimdev/guard.nvim)

**Comment by mamaraddio** [comment]
Also [none-ls](https://github.com/nvimtools/none-ls.nvim).
- It aims to be null-ls but maintained by the community.
- The API shouldn't change.
- Configuration scheme shouldn't change

**Comment by crisidev** [comment]
I have posted PR #4392 to migrate from null-ls to none-ls.
