### ISSUE TITLE
When opening a file, the nvim-tree plugin and terminal do not automatically enter the file path.

### ISSUE THREAD

**Issue by GEJXD** [LunarVim/LunarVim#4290]
### Problem description

Neither nvim-tree nor the built-in terminal automatically goes to the directory where the file is opened, but always the home directory, need me to type :cd %:p:h or in the terminal cd。
I haven't used lvim in about a week and everything was fine before, but today I opened it and all of a sudden it did this!

### LunarVim version

master-c626fe1-dirty

### Neovim version (>= 0.9.0)

NVIM v0.10.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Terminal name

gnome-terminal

### Operating system/version

Ubuntu 22.04.2 LTS

### Steps to reproduce

1.Go to any directory and open a file with lvim
2.Then open the nvim-tree interface or open one of the built-in terminals
3.The working directory is still the home directory, not the directory of the current file

### Screenshots

For example, if I open a file like this：
![Open_Lvim](https://github.com/LunarVim/LunarVim/assets/99662189/752bcce4-db70-4131-85a5-c182eb33e0ae)
Then I open nvim-tree and his working directory is always the home directory：
![nvim-tree](https://github.com/LunarVim/LunarVim/assets/99662189/07055ee8-605c-4cea-b833-24db4abe3fec)
Use ctrl+\ to open the terminal, the directory of the terminal is also the home directory：
![terna](https://github.com/LunarVim/LunarVim/assets/99662189/bdd25564-0185-4fdf-b9bd-8d3f32eedeaa)

**Comment by LostNeophyte** [comment]
feels like a duplicate, try this https://github.com/LunarVim/LunarVim/issues/3362
