### ISSUE TITLE
Integrating typescript-tools.nvim example

### ISSUE THREAD

**Issue by sativ01** [LunarVim/LunarVim#4292]
### Feature Description

Hey guys, 
I was trying to integrate [typescript-tools.nvim](https://github.com/pmizio/typescript-tools.nvim) into my LunarVim config, using this guide [Changing the default server](https://www.lunarvim.org/docs/configuration/language-features/language-servers#changing-the-default-server).

What I've done so far:

1. added the plugin to `lvim.plugins` in `.config/lvim/config.lua`:
```lua
  {
    "pmizio/typescript-tools.nvim",
    dependency = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
    config = function()
      require("typescript-tools").setup {}
    end,
  }
```

2. removed the default server by adding this in `config.lua`
`vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "tsserver" })`

3. did a cache reset `:LvimCacheReset`

The result is that after the restart when I try to `gd` I get an error `No language server attached`.

Please advise me what can I do here to get this thing working, thanks!

**Comment by LostNeophyte** [comment]
That config works for me, do you have any errors in `:messages`? make sure you have typescript installed globally or locally
