### ISSUE TITLE
custom configurations with more than two key bindings are ineffective

### ISSUE THREAD

**Issue by everdom** [LunarVim/LunarVim#4298]
### Problem description
custom configurations with more than two key bindings ineffective.
For example, the configuration:
`lvim.keys.normal_mode["gn"] = ":Lspsaga rename<cr>"`
defined in config.lua will become ineffective!
But when I change the configuration to
`lvim.keys.normal_mode["gn"] = {":lssaga rename<cr>","Rename"}`
There will be an error when loading

https://github.com/LunarVim/LunarVim/commit/ef3f25fd1d496c3822af9536d224270c48f12fff#commitcomment-121949648

### LunarVim version

master-e7ce9522d7cbc6639a3d31046c515739e929bfdd

### Neovim version (>= 0.9.0)

NVIM v0.9.0-dev

### Terminal name

alacritty

### Operating system/version

ubuntu 20.04

**Comment by LostNeophyte** [comment]
you can set `ignore_missing` in your config: `lvim.builtin.which_key.setup.ignore_missing = false`
if you want to add a description: `lvim.keys.normal_mode["gn"] = { ":Lspsaga rename<cr>", { desc = "hi" } }`
the keybind is effective (it works) even if whichkey doesn't show up

---
@kylo252 
I feel like `g` should open whichkey by default, we probably should add a label or set ingore_missing to false by default, what do you think?

**Comment by kylo252** [comment]
> @kylo252
> I feel like `g` should open whichkey by default, we probably should add a label or set ingore_missing to false by default, what do you think?

I have `g` enabled personally, here's what I use: https://github.com/kylo252/lvim/blob/1878330f1f76ceaa676c5d95eedc462202cb1624/lua/user/whichkey.lua#L297-L320

_P.s. I haven't tested how well `triggers_nowait` works_

**Comment by everdom** [comment]
> you can set `ignore_missing` in your config: `lvim.builtin.which_key.setup.ignore_missing = false` if you want to add a description: `lvim.keys.normal_mode["gn"] = { ":Lspsaga rename<cr>", { desc = "hi" } }` the keybind is effective (it works) even if whichkey doesn't show up
> 
> @kylo252 I feel like `g` should open whichkey by default, we probably should add a label or set ingore_missing to false by default, what do you think?

Okay, thank you very much. It worked, but during this period, I found another issue, which is that the configuration for the 'nvim-treesitter-textobjects' plugin is not taking effect, even though I added the 'lvim.builtin.which_key.setup.ignore_missing = false' configuration. I don't know if it is related to this issue. For example, the which-key doesn't appear when I type "vaf" in a function body when I want to select a whole function, my config is below：
  {
    "nvim-treesitter/nvim-treesitter-textobjects",
    after = "nvim-treesitter",
    config = function()
      require 'nvim-treesitter.configs'.setup {
        textobjects = {
          select = {
            enable = true,
            -- Automatically jump forward to textobj, similar to targets.vim
            lookahead = true,
            keymaps = {
              -- You can use the capture groups defined in textobjects.scm
              ["af"] = "@function.outer",
              ["if"] = "@function.inner",
              ["ac"] = "@class.outer",
              -- You can optionally set descriptions to the mappings (used in the desc parameter of
              -- nvim_buf_set_keymap) which plugins like which-key display
              ["ic"] = { query = "@class.inner", desc = "Select inner part of a class region" },
              -- You can also use captures from other query groups like `locals.scm`
              ["as"] = { query = "@scope", query_group = "locals", desc = "Select language scope" },
            },
            selection_modes = {
              ['@parameter.outer'] = 'v', -- charwise
              ['@function.outer'] = 'V',  -- linewise
              ['@class.outer'] = '<c-v>', -- blockwise
            },
            include_surrounding_whitespace = true,
          },
          move = {
            enable = true,
            set_jumps = false, -- whether to set jumps in the jumplist
            goto_next_start = {
              ["]]"] = "@function.outer",
              -- ["]["] = "@function.outer",
              ["]o"] = "@loop.outer",
              -- ["]o"] = { query = { "@loop.inner", "@loop.outer" } }
            },
            goto_next_end = {
              ["]["] = "@function.outer",
              -- ["]["] = "@class.outer",
            },
            goto_previous_start = {
              ["[["] = "@function.outer",
              -- ["[]"] = "@function.outer",
            },
            goto_previous_end = {
              ["[]"] = "@function.outer",
              -- ["[]"] = "@class.outer",
            },
            goto_next = {
              ["]d"] = "@conditional.outer",
            },
            goto_previous = {
              ["[d"] = "@conditional.outer",
            },
          },
          lsp_interop = {
            enable = true,
            border = 'none',
            peek_definition_code = {
              ["<leader>pf"] = "@function.outer",
              ["<leader>pF"] = "@class.outer",
            },
          },
        },
      }
    end,
    dependencies = "nvim-treesitter/nvim-treesitter",
  },

**Comment by everdom** [comment]
I solved this problem using a customized keymap method. Although it may not be the most elegant solution, it became apparent that in the Treesitter-TextObjects plug-in configuration, if two or more keys are unable to take effect, the following is how I addressed the issue:
```lua
lvim.keys.normal_mode["vaf"] = {":TSTextobjectSelect @function.outer<cr>", {desc="Function Outer"}}
lvim.keys.normal_mode["vif"] = {":TSTextobjectSelect @function.inner<cr>", {desc="Function Inner"}}
lvim.keys.normal_mode["vac"] = {":TSTextobjectSelect @class.outer<cr>", {desc="Class Outer"}}
lvim.keys.normal_mode["vic"] = {":TSTextobjectSelect @class.inner<cr>", {desc = "Class Outer" }}
lvim.keys.normal_mode["vas"] = {":TSTextobjectSelect @scope<cr>",  {desc = "Select language scope" }}

```

**Comment by everdom** [comment]
> > @kylo252
> > I feel like `g` should open whichkey by default, we probably should add a label or set ingore_missing to false by default, what do you think?
> 
> I have `g` enabled personally, here's what I use: https://github.com/kylo252/lvim/blob/1878330f1f76ceaa676c5d95eedc462202cb1624/lua/user/whichkey.lua#L297-L320
> 
> _P.s. I haven't tested how well `triggers_nowait` works_

Today, looking back at your response, I found that by using your configuration, the keymap for nvim-treesitter-textobjects is now effective. Your configruation is better, thank you very much! I'm posting it here for people who encounter this issue:
```lua
local setup_opts                                    = {
  plugins = {
    marks = true,     -- shows a list of your marks on ' and `
    registers = true, -- shows your registers on " in NORMAL or <C-r> in INSERT mode
    -- the presets plugin, adds help for a bunch of default keybindings in Neovim
    -- No actual key bindings are created
    presets = { -- adds help for operators like d, y, ...
      operators = {
        v = false,
        d = false,
      },
      motions = false,      -- adds help for motions
      text_objects = false, -- help for text objects triggered after entering an operator
      windows = false,      -- default bindings on <c-w>
      nav = true,           -- misc bindings to work with windows
      z = true,             -- bindings for folds, spelling and others prefixed with z
      g = true,             -- bindings for prefixed with g
    },
  },
  hidden = { "<silent>", "<cmd>", "<Cmd>", "<CR>", "call", "lua", "^:", "^ " }, -- hide mapping boilerplate
  show_help = true,                                                             -- show help message on the command line when the popup is visible
}

lvim.builtin.which_key.setup                        = setup_opts

```
