### ISSUE TITLE
Fails to install on Windows

### ISSUE THREAD

**Issue by super-tomcat** [LunarVim/LunarVim#4299]
### Problem description

After entering the PSWH command for windows i immediately see this on the command line in red....

$LV_BRANCH=release-1.3/neovim-0.9: The term '$LV_BRANCH=release-1.3/neovim-0.9' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Install continues asking for NodeJS dependencies and Python dependencies.

But then when i try to launch with: lvim, i get:

'lvim' is not recognized as an internal or external command,
operable program or batch file.

### LunarVim version

----

### Neovim version (>= 0.9.0)

NVIM v0.9.1 Build type: RelWithDebInfo

### Terminal name

Command Prompt

### Operating system/version

Windows 11 Pro

**Comment by LostNeophyte** [comment]
what's the powershell version, what command exactly did you use?

**Comment by super-tomcat** [comment]
Ahhh, fixed, i was issuing the windows PSWH command from in the Command Prompt rather than from in Powershell (version 7.3.6)... the windows PSWH ran without problems in the Command Prompt but failed to install.

Installed now. thanks
