### ISSUE TITLE
Super slow and/or skipping lines on Dart files

### ISSUE THREAD

**Issue by kmlopez-hhl** [LunarVim/LunarVim#4305]
### Problem description

It's skipping lines and supper laggy when working with Flutter or Dart

### LunarVim version

master-d6639290

### Neovim version (>= 0.9.0)

0.9.1

### Terminal name

WezTerm

### Operating system/version

MacOS 13.4.1

### Steps to reproduce

1. Install Lvim using the master branch
2. Open a fresh Flutter project
3. Open any '.dart` file, hold `j` or `k`
4. You will notice it's dropping frames or skipping lines

**Comment by harish2704** [comment]
Same Experience
## Neovim
NVIM v0.9.0

Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

## Lunarvim version
commit d663929036e23bd54427cf3e78dedf5b34ab97fc (HEAD -> master, origin/master, origin/HEAD)
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Tue Jul 18 23:59:59 2023 +0300

    chore: bump plugins version (#4272)

## Terminal
alacritty 0.12.0

## Lunarvim info
```
Buffer info
* filetype:                dart
* bufnr:                   14
* treesitter status:       active

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, antlersls, azure_pipelines_ls, custom_elements_ls, omnisharp, cssmodules_ls, denols, docker_compose_language_service, ember, emmet_language_server, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, java_language_server, jedi_language_server, ltex, neocmake, phpactor, psalm, pylsp, pylyzer, pyre, quick_lint_js, reason_ls, rnix, rome, ruby_ls, rubocop, ruff_lsp, solang, solc, solidity_ls_nomicfoundation, sorbet, sourcery, spectral, sqlls, sqls, standardrb, stylelint_lsp, svlangserver, tflint, unocss, verible, vtsls, vuels]

Formatters info
* Active: 
* Supported: dart_format

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

**Comment by tabarnouche** [comment]
This is apparently because of nvim-treesitter bug.
https://github.com/nvim-treesitter/nvim-treesitter/issues/4945

For me, 
```
:TSUninstall dart
```
```
lvim.builtin.treesitter.ignore_install = {"dart"}
```
and installing

https://github.com/akinsho/flutter-tools.nvim

work file.
