### ISSUE TITLE
andymass/vim-matchup and nvim-treesitter seems to be incompatible

### ISSUE THREAD

**Issue by cova-fe** [LunarVim/LunarVim#4313]
### Problem description

andymass/vim-matchup (current version) is not compatible with nvim-treesitter version installed as core plugin, at least for LUA files.
Short description: installing vim-matchup causes troubles, with an error starting with 
`Error detected while processing CursorMoved Autocommands for "*"..function`
See here for full details:
https://github.com/andymass/vim-matchup/issues/307#issuecomment-1662308872
I updated nvim-treesitter to latest commit (upstream) by manually changing default.json, run TSUpdate and the issue disappeared

### LunarVim version

release-1.3/neovim-0.9-d1c1bace-dirty

### Neovim version (>= 0.9.0)

NVIM v0.9.1

### Terminal name

alacritty

### Operating system/version

Gentoo Linux 2.14

### Steps to reproduce

Just add andymass/vim-matchup and try to edit config.lua

**Comment by LostNeophyte** [comment]
we pin the versions of core plugins, the core plugin specs aren't configurable yet, your options are:
- use older version of matchup
- use lunarvim master
- unpin all core plugins by setting LVIM_DEV_MODE env variable
