### ISSUE TITLE
switch to new nvimtree organization plugin

### ISSUE THREAD

**Issue by gipo355** [LunarVim/LunarVim#4317]
### Problem description

kyazdani42/nvim-tree.lua has moved to nvim-tree/nvim-tree.lua

when installing plugins that set it as dependency, you get a conflict reporting same plugins, different urls

### LunarVim version

master-420817e6-dirty

### Neovim version (>= 0.9.0)

v0.10.0-dev-766+gef44e59729

### Terminal name

wezterm

### Operating system/version

arch

### Steps to reproduce

add plugin
```lua
{
  'antosha417/nvim-lsp-file-operations',
  dependencies = {
    "nvim-lua/plenary.nvim",
    "nvim-tree/nvim-tree.lua",
  }
```

**Comment by LostNeophyte** [comment]
for now don't add it to the dependencies or add just "nvim-tree.lua" without the author
