### ISSUE TITLE
Default config

### ISSUE THREAD

**Issue by kobzar** [LunarVim/LunarVim#4321]
### Feature Description

As you known after https://github.com/LunarVim/LunarVim/commit/72e55a729015130b68afdbf433ed349ece491909
the default config is empty. In this is worse for my opinion.
This is hard for begginers and new users.

So we can do something like another Neovim packs.
On installation script just add new punct 

"Do You want to install sample config (Y/n)"

So, new customers can try Lvim with simple settings to play with it. The old users can just add their config after clear install.

**Comment by LostNeophyte** [comment]
In https://github.com/LunarVim/LunarVim/issues/4314 I said I'll add some examples to the config, will that resolve this issue? (I'd like to close one of the issues)
