### ISSUE TITLE
Installer doesn't work on Termux. Again.

### ISSUE THREAD

**Issue by TheGamer1002** [LunarVim/LunarVim#4329]
### Problem description

I expect it to install.
```
Installing LunarVim shim
make: Entering directory '/data/data/com.termux/files/home/.local/share/lunarvim/lvim'
make: /usr/bin/env: No such file or directory
make: *** [Makefile:8: install-bin] Error 127
make: Leaving directory '/data/data/com.termux/files/home/.local/share/lunarvim/lvim'
```

### LunarVim version

commit 420817e

### Neovim version (>= 0.9.0)

0.9.0 (latest)

### Terminal name

Termux

### Operating system/version

Android 14

### Steps to reproduce

1. Use Termux
2. `bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh) --overwrite`
3. Go through installer

**Comment by laaledesiempre** [comment]
Hi, it works for me, make sure you have installed dependencies and luajit and tell me the output

**Comment by gmankab** [comment]
have luajit, git, make, pip, python, npm, node, cargo installed

same error

**Comment by laaledesiempre** [comment]
HI, can you tell me the output? or error message? what do you see?

**Comment by gmankab** [comment]
@laaledesiempre, same error message as @TheGamer1002

```text
Installing LunarVim shim
make: Entering directory '/data/data/com.termux/files/home/.local/share/lunarvim/lvim'
make: /usr/bin/env: No such file or directory
make: *** [Makefile:8: install-bin] Error 127
make: Leaving directory '/data/data/com.termux/files/home/.local/share/lunarvim/lvim'
```

**Comment by laaledesiempre** [comment]
try to do this:

-```$ bash```
-```$ LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)```

try that and tell me the output

**Comment by gmankab** [comment]
@laaledesiempre, same

```text
~ $ LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

      88\                                                   88\
      88 |                                                  \__|
      88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
      88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
      88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
      88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
      88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
      \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|

--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies: neovim?
[y]es or [n]o (default: no) :
--------------------------------------------------------------------------------
Would you like to install LunarVim's Python dependencies: pynvim?
[y]es or [n]o (default: no) :
--------------------------------------------------------------------------------
Would you like to install LunarVim's Rust dependencies: fd::fd-find, rg::ripgrep?
[y]es or [n]o (default: no) :
--------------------------------------------------------------------------------
Backing up old /data/data/com.termux/files/home/.cache/lvim to /data/data/com.termux/files/home/.cache/lvim.old
--------------------------------------------------------------------------------
Cloning LunarVim configuration
Cloning into '/data/data/com.termux/files/home/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 171, done.
remote: Counting objects: 100% (171/171), done.
remote: Compressing objects: 100% (155/155), done.
remote: Total 171 (delta 4), reused 66 (delta 3), pack-reused 0
Receiving objects: 100% (171/171), 151.83 KiB | 678.00 KiB/s, done.
Resolving deltas: 100% (4/4), done.
--------------------------------------------------------------------------------
Installing LunarVim shim
make: Entering directory '/data/data/com.termux/files/home/.local/share/lunarvim/lvim'
make: /usr/bin/env: No such file or directory
make: *** [Makefile:8: install-bin] Error 127
make: Leaving directory '/data/data/com.termux/files/home/.local/share/lunarvim/lvim'
```

**Comment by laaledesiempre** [comment]
maybe i'm saying something obvious but, do you have installed nvim? you didnt mentioned it on the dependencies you have installed.

**Comment by laaledesiempre** [comment]
the problem seems to be that cant find /usr/bin/env that is where bash is located on the make file(look ar /Makefile in this repo). maybe is that is looking on your root directory, do you have a rooted device? 
also you can try run that commands by yourself and see what happens.

**Comment by gmankab** [comment]
my device is not rooted

/usr/bin/var works in bash

**Comment by TheGamer1002** [comment]
Should we get someone to reopen this? I'm surprised it's still getting comments.

**Comment by kyzsuukii** [comment]
> the problem seems to be that cant find /usr/bin/env that is where bash is located on the make file(look ar /Makefile in this repo). maybe is that is looking on your root directory, do you have a rooted device? 
> also you can try run that commands by yourself and see what happens. 
> 

In Termux, the path to the environment file is `/data/data/com.termux/files/usr/bin/env`. I tried editing it to the correct path, but it backs up the edited folder and creates a new one, making my changes ineffective. I think I need to disable the backup of old folders and simply run `make` to compile with the correct path without any backups.

**Comment by gecko-ganlu** [comment]
1. download install file
```shell
wget https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh
```

2.  modify `install.sh`
modify line 1: `#!/usr/bin/env bash` -> `#!/data/data/com.termux/files/usr/bin/env bash`

line 400, modiry function clone_lvim,  add a line like:
```shell
function clone_lvim() {
  msg "Cloning LunarVim configuration"
  if ! git clone --branch "$LV_BRANCH" \
    "https://github.com/${LV_REMOTE}" "$LUNARVIM_BASE_DIR"; then                                                                                                   echo "Failed to clone repository. Installation failed."
    exit 1
  fi

  sed -i 's/\/usr\/bin/\/data\/data\/com.termux\/files\/usr\/bin/g' "${LUNARVIM_BASE_DIR}"/Makefile                                                            

}
```

4. run `bash install.sh ` .

**Comment by Suletta-Majo** [comment]
termux has sheban change command :0
https://wiki.termux.com/wiki/Termux-fix-shebang
so gecko-ganlu's post 1. & 2. part can fix this way too. yes 3. Makefile is not fix :(
`termux-fix-shebang install.sh`

**Comment by rafaelportomoura** [comment]
> 1. download install file
> ```shell
> wget https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh
> ```
> 
> 2.  modify `install.sh`
> modify line 1: `#!/usr/bin/env bash` -> `#!/data/data/com.termux/files/usr/bin/env bash`
> 
> line 400, modify function clone_lvim,  add a line (sed -i ...) like this:
> ```shell
> function clone_lvim() {
>   msg "Cloning LunarVim configuration"
>   if ! git clone --branch "$LV_BRANCH" \
>     "https://github.com/${LV_REMOTE}" "$LUNARVIM_BASE_DIR"; then                                                                                                   
>     echo "Failed to clone repository. Installation failed."
>     exit 1
>   fi
> 
>   sed -i 's/\/usr\/bin/\/data\/data\/com.termux\/files\/usr\/bin/g' "${LUNARVIM_BASE_DIR}"/Makefile                                                            
> 
> }
> ```
> 
> 4. run `bash install.sh ` .

this works for me

**Comment by JiangWan-sleeping** [comment]
@gecko-ganlu Thank you!

**Comment by ayueryi** [comment]
> 1. download install file
> 
> ```shell
> wget https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh
> ```
> 
> 2. modify `install.sh`
>    modify line 1: `#!/usr/bin/env bash` -> `#!/data/data/com.termux/files/usr/bin/env bash`
> 
> line 400, modify function clone_lvim, add a line (sed -i ...) like this:
> 
> ```shell
> function clone_lvim() {
>   msg "Cloning LunarVim configuration"
>   if ! git clone --branch "$LV_BRANCH" \
>     "https://github.com/${LV_REMOTE}" "$LUNARVIM_BASE_DIR"; then                                                                                                   
>     echo "Failed to clone repository. Installation failed."
>     exit 1
>   fi
> 
>   sed -i 's/\/usr\/bin/\/data\/data\/com.termux\/files\/usr\/bin/g' "${LUNARVIM_BASE_DIR}"/Makefile                                                            
> 
> }
> ```
> 
> 4. run `bash install.sh ` .

Thanks, @gecko-ganlu 🧡
it works

**Comment by swomf** [comment]
Alternatively, you can simply run `install.sh` directly, but within a `termux-chroot` so that directories just under `/` are temporarily respected.

However, you'll need to change the lvim environment variables defined within `~/.local/bin/lvim` to use `$HOME/blah` rather than a `termux-chroot`-style `/home/blah`. For example:

```bash
# Make /usr directly accessible at /usr
termux-chroot

# run the installer
#   removing lunarvim.old will bypass
#   some cp errors
rm -rf ~/.local/share/lunarvim.old
git clone https://github.com/lunarvim/lunarvim
cd lunarvim
./utils/installer/install.sh

# Exit the temporary chroot
# with <CTRL+D>

# Fix env vars in ~/.local/bin/lvim
sed -i 's/\/home/\$HOME/g' $(command -v lvim)
```

**Comment by op30mmd** [comment]
> Alternatively, you can simply run `install.sh` directly, but within a `termux-chroot` so that directories just under `/` are temporarily respected.
> 
> However, you'll need to change the lvim environment variables defined within `~/.local/bin/lvim` to use `$HOME/blah` rather than a `termux-chroot`-style `/home/blah`. For example:
> 
> ```bash
> # Make /usr directly accessible at /usr
> termux-chroot
> 
> # run the installer
> #   removing lunarvim.old will bypass
> #   some cp errors
> rm -rf ~/.local/share/lunarvim.old
> git clone https://github.com/lunarvim/lunarvim
> cd lunarvim
> ./utils/installer/install.sh
> 
> # Exit the temporary chroot
> # with <CTRL+D>
> 
> # Fix env vars in ~/.local/bin/lvim
> sed -i 's/\/home/\$HOME/g' $(command -v lvim)
> ```

`~ $ sed -i 's/\/home/\$HOME/g' $(command -v lvim)                                       sed: no input files` @swomf
