### ISSUE TITLE
No autocompletion for lvim builtin config

### ISSUE THREAD

**Issue by imroc** [LunarVim/LunarVim#4332]
### Problem description

The [Doc](https://www.lunarvim.org/docs/configuration/plugins/core-plugins) says:
```txt
To configure a builtin plugin, edit options in lvim.builtin.<builtin>. You can press <TAB> to get autocomplete suggestions to explore these settings.
```
But there is no valid auto completion for lvim builtin config:

![image](https://github.com/LunarVim/LunarVim/assets/7448852/628b74bf-fa30-4ad7-84f2-5d189bae4ecb)

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.0)

NVIM v0.9.1

### Terminal name

iTerm2

### Operating system/version

macOS 13.5

**Comment by anshiq** [comment]
I have also same problem

**Comment by anshiq** [comment]
I fix the Lsp, first I uninstalled lvim and copied my .config/lvim/config.lua as backup 
now make sure .config/lvim directory should be empyt, and now you can install lvim from official website after installation you can again add your backup config.lua file to .config/lvim/
