### ISSUE TITLE
fzf nil value

### ISSUE THREAD

**Issue by mikowhyHUB** [LunarVim/LunarVim#4333]
### Problem description

Trying to call :Telescope fzf and got this error:
![Screenshot from 2023-08-17 08-59-54](https://github.com/LunarVim/LunarVim/assets/111461945/286921c5-dc15-4141-a806-c680c3be6c32)

Any ideas how to solve this problem?

### LunarVim version

release-1.3/neovim-0.9-d1c1bace-dirty

### Neovim version (>= 0.9.0)

NVIM v0.9.1

### Terminal name

Kitty

### Operating system/version

Linux Mint 21 x86_64

**Comment by mrPuckk** [comment]
Installing fzf in your shell will help you out.
