### ISSUE TITLE
Layout Disorder Issue in Lazygit

### ISSUE THREAD

**Issue by timlee1128** [LunarVim/LunarVim#4337]
### Problem description

\<Leader>gg to active lazygit:
<img width="1672" alt="image" src="https://github.com/LunarVim/LunarVim/assets/16740193/f65889d4-b22f-4900-a37c-3c80e2e9d52a">

However, when running Lazygit directly in the terminal, the interface is normal.
<img width="1122" alt="image" src="https://github.com/LunarVim/LunarVim/assets/16740193/5f5ae024-c8d3-4bce-80d9-657380036892">

Here is my configration about shell:
`
   -- Enable powershell as your default shell
    vim.opt.shell = "pwsh.exe -NoLogo"
    vim.opt.shellcmdflag =
    "-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;"
    vim.cmd [[
      let &shellredir = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
      let &shellpipe = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
      set shellquote= shellxquote=
    ]]

`

### LunarVim version

release-1.3

### Neovim version (>= 0.9.0)

neovim-0.9

### Terminal name

windows terminal

### Operating system/version

windows 11

**Comment by yongnianliu** [comment]
Same issue!
LunarVim version
release-1.3

Neovim version (>= 0.9.0)
neovim-0.9

Terminal name
windows terminal pwsh 7.3.4

Operating system/version
windows 11

![image](https://github.com/LunarVim/LunarVim/assets/6042007/da04f9e8-5092-42c5-ae8e-8b3addd17d37)
