### ISSUE TITLE
PEP 668

### ISSUE THREAD

**Issue by ideveCore** [LunarVim/LunarVim#4349]
### Problem description

Hello, it would be nice if you added this line of code "--break-system-packages" to the pip installation command, because my Manjaro GNOME system blocked pip based on the PEP 668 rule.

### LunarVim version

release-1.3

### Neovim version (>= 0.9.1)

neovim-0.9

### Terminal name

Tilix

### Operating system/version

Manjaro GNOME (latest)

### Steps to reproduce

LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)

### Screenshots

![Captura de tela de 2023-08-28 11-49-47](https://github.com/LunarVim/LunarVim/assets/120337844/c0a3c5f4-4a59-44dd-9d2e-745dec27ac77)
## Part of script edited to work ignoring PEP rule 668
![Captura de tela de 2023-08-28 11-50-48](https://github.com/LunarVim/LunarVim/assets/120337844/aa3daf79-9e87-4c49-b8dc-02b89555e739)

**Comment by b-** [comment]
With all due respect, I think that adding this flag to the LunarVim is _not_ the solution to PEP668. There's a reason the flag is called `--break-system-packages`.

A better solution would be to either install LunarVim's python dependencies using the system package manager (e.g., [`sudo apt install python3-pynvim`](https://packages.debian.org/bookworm/python3-pynvim) on Debian), and/or to install into a venv/virtualenv.

**Comment by ideveCore** [comment]
Hi, you're right.

**Comment by ideveCore** [comment]
I haven't checked its full documentation before, but if there is nothing related to PEP 668, it would be nice to include it, maybe some users don't know what it is and how to get around it safely.

**Comment by b-** [comment]
If this wasn’t fixed, it shouldn’t have been closed?

**Comment by ideveCore** [comment]
As you said, "installing LunarVim's python dependencies using the system's package manager (e.g. sudo apt install python3-pynvim on Debian), and/or installing in a venv/virtualen", solves the problem, but I leave the tip to add this In the documentation, several Linux systems are applying PEP668 by default this can confuse novice users.

**Comment by ideveCore** [comment]
I rushed to mark this question as an "error", but in reality it's just a warning, which is why I closed it. Thanks for the explanation about PEP668.

**Comment by elivanse** [comment]
sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED
this worked foe me!

**Comment by pdostal** [comment]
Similar to: #4403, #4050, #4372
