### ISSUE TITLE
Can not attach lsp clients to buffers

### ISSUE THREAD

**Issue by xyegithub** [LunarVim/LunarVim#4350]
### Problem description

The command `require("lvim.lsp.manager").setup("xxxx")` does not work. Can not attach the lsp clients to buffers, even the clients is installed.

### LunarVim version

023fb27b322ca8d0e3c02b4bbe88118b8d131c4e

### Neovim version (>= 0.9.1)

NVIM v0.10.0-dev-739+g42333ea98

### Operating system/version

Arch Linux/6.4.11

### Affected language servers

all

### Steps to reproduce

install the newst lunarvim for  Neovim 0.10.0

### Actual behavior

Can not attach the lsp servers.

### support info

LspInfo

```
 Language client log: /home/Eric/.local/state/lvim/lsp.log
 Detected filetype:   tex
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: tex
 
 Config: texlab
 	filetypes:         tex, plaintex, bib
 	root directory:    Not found.
 	cmd:               /home/Eric/.local/share/lvim/mason/bin/texlab
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: texlab

```

LvimInfo

```

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                tex
* bufnr:                   1
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, antlersls, azure_pipelines_ls, custom_elements_ls, omnisharp, cssmodules_ls, denols, docker_compose_language_service, ember, emmet_language_server, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, java_language_server, jedi_language_server, ltex, neocmake, phpactor, psalm, pylsp, pylyzer, pyre, quick_lint_js, reason_ls, rnix, rome, ruby_ls, rubocop, ruff_lsp, solang, solc, solidity_ls_nomicfoundation, sorbet, sourcery, spectral, sqlls, sqls, standardrb, stylelint_lsp, svlangserver, tflint, unocss, verible, vtsls, vuels]

Formatters info
* Active: 
* Supported: latexindent

Linters info
* Active: 
* Supported: [chktex, proselint, textidote, vale]

Code actions info
* Active: 

```

### Screenshots

![2023-08-29_19-52](https://github.com/LunarVim/LunarVim/assets/46625185/f6b67165-df2b-45ba-8033-0091f43c2dba)
![2023-08-29_19-52_1](https://github.com/LunarVim/LunarVim/assets/46625185/9bef1a81-ac22-470c-924e-45dd26e36a73)

**Comment by nwiizo** [comment]
I also have a similar problem

**Comment by stratumforce** [comment]
Here's a PR for it waiting to be merged: https://github.com/LunarVim/LunarVim/pull/4348

**Comment by nwiizo** [comment]
I solved it by changing the file and reinstalling the binary
```
cd <lunarvim-repo> # this will be in `~/.local/share/lunarvim/lvim` by default
bash utils/installer/install_bin.sh
```

https://www.lunarvim.org/docs/troubleshooting

**Comment by cpea2506** [comment]
Close by https://github.com/LunarVim/LunarVim/pull/4348
