### ISSUE TITLE
incorrect indentation when opening new line in insert mode

### ISSUE THREAD

**Issue by nickdesaulniers** [LunarVim/LunarVim#4353]
### Problem description

I use `o` and `O` to open new lines in insert mode often.  It seems that for some files (this is a c++ header), `o` and `O` open a new line with the wrong indentation.

This doesn't happen if I just use `nvim`. It does happen even if I delete my lvim config file.

i.e.

```c++
if (foo) // cursor anywhere on this line
  return 1;
```
hit `o`

expected:
```c++
if (foo)
    
//^ cursor here
  return 1;
```

actual:
```c++
if (foo)
    
  //^ cursor here
  return 1;
```

Smells like:
1. https://github.com/LunarVim/LunarVim/issues/1364
2. https://www.reddit.com/r/lunarvim/comments/sgcptg/lunarvim_keeps_indenting_4_spaces_no_matter_my/
3. https://github.com/LunarVim/LunarVim/issues/1364
4. https://github.com/LunarVim/LunarVim/issues/563

### LunarVim version

release-1.3/neovim-0.9-d1c1bace2218

### Neovim version (>= 0.9.1)

NVIM v0.9.1

### Terminal name

terminator

### Operating system/version

linux 6.3.11 (debian fork)

### Steps to reproduce

vim llvm/include/llvm/CodeGen/MachineInstr.h +1047

**Comment by nickdesaulniers** [comment]
another note: since this in llvm/llvm-project/ I wonder if a .clang-format file is getting read somewhere, and overriding shiftwidth or something?

**Comment by nickdesaulniers** [comment]
I think this is a minimal repro (thanks @justinstitt):
```c++
class foo {};
class bar :
  public foo {
  void hello () {}
                     //^ put cursor in the curly braces then hit enter
};
```
expected:
```c++
class foo {};
class bar :
  public foo {
  void hello () {
    
  // ^ cursor here
  }
};
```
actual:
```c++
class foo {};
class bar :
  public foo {
  void hello () {
        ^ cursor here
    }
};
```
seems somehow related to the inheritance being wrapped in the class defintion?

**Comment by TheBearodactyl** [comment]
having the same problem now
indentation doesn't increase the level if i'm using namespace indentation in C++ files

**Comment by JustinStitt** [comment]
> having the same problem now indentation doesn't increase the level if i'm using namespace indentation in C++ files

Move on from LunarVim. It is dead.

Try out [LazyVim](https://www.lazyvim.org/).

**Comment by TheBearodactyl** [comment]
> having the same problem now indentation doesn't increase the level if i'm using namespace indentation in C++ files
> 
> Move on from LunarVim. It is dead.
> 
> Try out [LazyVim](https://www.lazyvim.org/).

<img width="1889" height="927" alt="Image" src="https://github.com/user-attachments/assets/0f22bc03-bcaf-4fe9-989e-dfe10bfb04ee" />

<img width="483" height="239" alt="Image" src="https://github.com/user-attachments/assets/b844865f-5434-4274-a1b6-1700c0e73e4a" />
