### ISSUE TITLE
Automatically changes first line of code across different languages

### ISSUE THREAD

**Issue by ksajan** [LunarVim/LunarVim#4363]
### Problem description

Whenever i am editing a file randomly at some point in time it will change the first line of the code to some line number I was that time or randomly starting writing spaced numbers and closing bracket. I have seen this in typescript, golang and python language project till now. 
I was finally able to capture live on video recording as this is quite random

### LunarVim version

master-15dc5

### Neovim version (>= 0.9.1)

NVIM v0.9.1

### Operating system/version

Version 13.5.1 (22G90)

### Affected language servers

tsserver, python, golang, jsonls or may be more

### Steps to reproduce

My config is based on [abzcoding](https://github.com/abzcoding/lvim) and is present [here](https://github.com/ksajan/lvim) 
then open any project in typescript or json file and edit something go to first/last and press j/k till you see error shown by diagnostics.
Its not fool proof as sometimes it happens and sometimes it don't.

### Actual behavior

It is adding certain characters/line when I editing/saving the file in the starting of the file.

### Expected behavior

It should just save and should not add line automatically in the starting of the file when I am editing the file.

### support info

:LspIndo 
```
 
 Language client log: /Users/sajan.kumar/.local/state/lvim/lsp.log
 Detected filetype:   json
 
 1 client(s) attached to this buffer: 
 
 Client: jsonls (id: 2, bufnr: [46])
 	filetypes:       json, jsonc
 	autostart:       true
 	root directory:  /Users/sajan.kumar/Documents/CoinDCX/okto-token-price-service
 	cmd:             /Users/sajan.kumar/.local/share/lvim/mason/bin/vscode-json-language-server --stdio
 
 1 active client(s) not attached to this buffer: 
 
 Client: copilot (id: 1, bufnr: [])
 	filetypes:       
 	autostart:       false
 	root directory:  Running in single file mode.
 	cmd:             node /Users/sajan.kumar/.local/share/lunarvim/site/pack/lazy/opt/copilot.vim/dist/agent.js
 
 Configured servers list: jsonls
 ```
 

### Screenshots

<img width="1800" alt="Screenshot 2023-09-11 at 2 06 30 PM" src="https://github.com/LunarVim/LunarVim/assets/31013555/47b491cb-bef1-4cb2-8074-17fa64029bed">
<img width="1800" alt="Screenshot 2023-09-11 at 1 45 19 PM" src="https://github.com/LunarVim/LunarVim/assets/31013555/372f0c91-0921-48fe-aa71-754f1261b54e">
<img width="1800" alt="Screenshot 2023-09-11 at 1 45 15 PM" src="https://github.com/LunarVim/LunarVim/assets/31013555/bc264f72-9956-4a3d-9e89-0ff889680f69">

https://github.com/LunarVim/LunarVim/assets/31013555/c78a9c55-b4d6-4550-b916-c4467235190b

Sorry for the bad quality I couldn't do much about the size of the file.

**Comment by williamgoulois** [comment]
Hi @ksajan I got the same issue it was coming from the plugin https://github.com/andymass/vim-matchup
I removed it from my user plugins and also disabled the treesitter integration and no more problem :
`lvim.builtin.treesitter.matchup.enable = false`

Hope that it helps !
