### ISSUE TITLE
Installation instructions  did not work 

### ISSUE THREAD

**Issue by userrand** [LunarVim/LunarVim#4364]
### Problem description

Maybe similarly to https://github.com/LunarVim/LunarVim/issues/3773 , following the instruction on the website https://www.lunarvim.org/docs/installation did not work and i received the error 

`line 9: lvim: command not found
[ERROR]: Unable to verify plugins, make sure to manually run ':Lazy sync' when starting lvim for the first time.`

I tried following the instructions in that thread and used 

`LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh)`

which seems to have worked for this reddit user that posted a day ago https://www.reddit.com/r/lunarvim/comments/11hqzic/comment/jzxtcfq/?utm_source=share&utm_medium=web2x&context=3

but after saying yes to loading node js dependencies, the installer seemingly got stuck installing and i canceled it (i migth have done it too early see below).

Trying again with the answer from the linked thread after using the uninstall script, the installer seemingly gets stuck at reify tree sitter cli or something but after a while it installs. However, at the end, I got an error

`line 9: lvim: command not found
[ERROR]: Unable to verify plugins, make sure to manually run ':PackerSync' when starting lvim for the first time.`
 
which is different than the first in that it now asks to use PackerSync rather than lazy sync

### LunarVim version

stable release-1.3

### Neovim version (>= 0.9.1)

0.9.1

### Terminal name

yakuake then after getting the error a few times I tried konsole with the answer from thread and it failed again

### Operating system/version

linux fedora with kde

### Steps to reproduce

`LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)`

**Comment by cpea2506** [comment]
It maybe late to response. But for your confusion, `lvim 1.3` have changed from [Packer](https://github.com/wbthomason/packer.nvim) to [Lazy](https://github.com/folke/lazy.nvim) for better packages managing.

On Linux, lvim is installed in `~/.local/bin` so make sure you have that folder in PATH, so your shell can lookup the command.

> [ERROR]: Unable to verify plugins, make sure to manually run ':Lazy sync' when starting lvim for the first time

For this error, just do what it said, open lvim and run `:Lazy sync` to installed necessary builtin packages.

**Comment by userrand** [comment]
> It maybe late to response. But for your confusion, `lvim 1.3` have changed from [Packer](https://github.com/wbthomason/packer.nvim) to [Lazy](https://github.com/folke/lazy.nvim) for better packages managing.
> 
> On Linux, lvim is installed in `~/.local/bin` so make sure you have that folder in PATH, so your shell can lookup the command.
> 
> > [ERROR]: Unable to verify plugins, make sure to manually run ':Lazy sync' when starting lvim for the first time
> 
> For this error, just do what it said, open lvim and run `:Lazy sync` to installed necessary builtin packages.
> 
> After all of these, you can use lvim as normal.

Thank you. I installed astronvim since but I might come back to your messages later if I try lunarvim in the futur.
