### ISSUE TITLE
lvim.lsp.automatic_servers_installation is ignored

### ISSUE THREAD

**Issue by RickStanley** [LunarVim/LunarVim#4366]
### Problem description

I want to configure my servers manually and use already installed LSP in my machine.

To achieve that, the first step is to disable automatic installation of LSPs.

After a fresh install, without any modifications, I opened ` ~/.config/lvim/config.lua` and added:

```lua
lvim.lsp.automatic_servers_installation = false
```

Ref: https://www.lunarvim.org/docs/configuration/language-features/language-servers#manual-installation

I did not work as expected. I opened a JavaScript file and it warned me that installation of tsserver and tailwindcss were in progress. Like so:

![grafik](https://github.com/LunarVim/LunarVim/assets/142456149/d406f026-0703-4a25-a2e7-cc5aee0b7dd0)

and it really did install:
![grafik](https://github.com/LunarVim/LunarVim/assets/142456149/3a434dcd-d2bb-42d1-9102-4e24c89c89ee)

I removed the LSPs and executed `:LvimCacheReset`, but it wasn't effective either.

I'm not sure if it matters, but I skipped pynvim installation, because of this:
![grafik](https://github.com/LunarVim/LunarVim/assets/142456149/d31cd141-71f3-47bf-96f7-b2e765106942)

------

Anyways, I just want to disable the automatic installation of LSP and configure myself.

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NIM v0.9.2

### Operating system/version

Arch Linux 6.4.12-arch1-1

### Affected language servers

all

### Actual behavior

Language servers are installed for supported file types.

### Expected behavior

Disabled LSP automatic installation after setting `lvim.lsp.automatic_servers_installation` to `false`.

### support info

![grafik](https://github.com/LunarVim/LunarVim/assets/142456149/83f9111b-6689-408a-bb66-ae2b4ca5d927)

![grafik](https://github.com/LunarVim/LunarVim/assets/142456149/29ad678f-604e-4dc9-81c7-b0e65a94720d)

**Comment by RickStanley** [comment]
After making a copy of the same setting (`lvim.lsp.automatic_servers_installation = false`) in the next line, a warning showed up stating that `lvim.lsp.automatic_servers_installation` was deprecated and that I should use `lvim.lsp.installer.automatic_servers_installation = false` instead.

I did that and ran `:LvimCacheReset`, but it installed, for instance for JS file, `tailwindcss` yet again.

**Comment by LostNeophyte** [comment]
it should be `lvim.lsp.installer.setup.automatic_installation = false`

**Comment by AjBreidenbach** [comment]
This isn't completed, the documentation still refers to the deprecated setting https://www.lunarvim.org/docs/configuration/language-features/language-servers#manual-installation
