### ISSUE TITLE
Installation instructions did not work [2]

### ISSUE THREAD

**Issue by vsly-ru** [LunarVim/LunarVim#4371]
### Problem description

When following instructions at https://www.lunarvim.org/docs/installation 
It says "fish: Invalid redirection target:" (see screenshots)
```bash
❯ uname -a
Darwin M13.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64
❯ fish -v
fish, version 3.6.1
```

Using zsh, it runs fine.

### LunarVim version

1.3

### Neovim version (>= 0.9.1)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.0-beta3

### Terminal name

iTerm2, fish

### Operating system/version

macOS 13.13.1 (M1)

### Steps to reproduce

1. using fish `LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)`

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/39321074/f8af6146-7c84-417e-86c7-b77906a3755d)

**Comment by vsly-ru** [comment]
Using zsh it also failed with `mkdir: /Users/admin/.cache/lvim: Permission denied` after finished installing rust dependencies.

![image](https://github.com/LunarVim/LunarVim/assets/39321074/f8614b84-a549-4f5c-919a-1afeb830c3ee)

**Comment by vsly-ru** [comment]
@brneor Well, all other install scripts to copy-paste were working fine. It's the first time I encountered something that doesn't work in fish. So maybe change the install script to exclude the bash specific syntax? 
Or add a comment on your website about compatible shell for the script. 
Or remove `No alarms and No surprises:` line, because what I've encountered may count as a surprise :)

**Comment by brneor** [comment]
> It's the first time I encountered something that doesn't work in fish.

It's okay, you'll encounter more as you keep using fish.

@vsly-ru from the [Fish docs](https://fishshell.com/docs/current/fish_for_bash_users.html#fish-for-bash-users):

_"Fish is intentionally not POSIX-compatible and as such some of the things you are used to work differently."_
