### ISSUE TITLE
How to add cmp-dictionary in lunarvim

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#4376]
### Problem description

I want to use cmp-dictionary in lunarvim to add english word for normal writting. (Like add some words like apple and dog)
If I install cmp-dictionary in `config.lua` the other cmp feature like cmp-buffer or cmp-path which already built in lunarvim will be disabled. 
So I check the file `.local/share/lunarvim/lvim/lua/lvim/plugins.lua` to add the cmp-dictionary. 
Related settings is here
```
  {
    "hrsh7th/nvim-cmp",
    config = function()
      if lvim.builtin.cmp then
        require("lvim.core.cmp").setup()
      end
    end,
    event = { "InsertEnter", "CmdlineEnter" },
    dependencies = {
      "cmp-nvim-lsp",
      "cmp_luasnip",
      "cmp-buffer",
      "cmp-path",
      "cmp-dictionary",
      "cmp-cmdline",
    },
  },
  { "hrsh7th/cmp-nvim-lsp", lazy = true },
  { "saadparwaiz1/cmp_luasnip", lazy = true },
  { "hrsh7th/cmp-buffer", lazy = true },
  { "hrsh7th/cmp-path", lazy = true },
  { "uga-rosa/cmp-dictionary", lazy = true },
```

Then I came back to the `config.lua` file do some setting follow the steps here: 
[cmp-dictionary](https://github.com/uga-rosa/cmp-dictionary#setting)

After I add the  switcher code: 
```
dict.switcher({
 filetype = {
    markdown = "/home/lizhe/OriNote/notes/Data/google-10000-english-no-swears.txt",
    text = "/home/lizhe/OriNote/notes/Data/google-10000-english-no-swears.txt",
  }
})
```

I get error like this. 
```
Error executing luv callback:
...mp-dictionary/lua/cmp_dictionary/kit/Async/AsyncTask.lua:223: ...
/cmp-dictionary/lua/cmp_dictionary/kit/Thread/Worker.lua:35: module
'cmp_dictionary.kit.Async.AsyncTask' not found:
        no field package.preload['cmp_dictionary.kit.Async.AsyncTask
']
        no file './cmp_dictionary/kit/Async/AsyncTask.lua'
        no file '/usr/share/luajit-2.1/cmp_dictionary/kit/Async/Asyn
cTask.lua'
        no file '/usr/local/share/lua/5.1/cmp_dictionary/kit/Async/A
syncTask.lua'
        no file '/usr/local/share/lua/5.1/cmp_dictionary/kit/Async/A
syncTask/init.lua'
        no file '/usr/share/lua/5.1/cmp_dictionary/kit/Async/AsyncTa
sk.lua'
        no file '/usr/share/lua/5.1/cmp_dictionary/kit/Async/AsyncTa
sk/init.lua'
        no file './cmp_dictionary/kit/Async/AsyncTask.so'
        no file '/usr/local/lib/lua/5.1/cmp_dictionary/kit/Async/Asy
ncTask.so'
        no file '/usr/lib/lua/5.1/cmp_dictionary/kit/Async/AsyncTask
.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

So how to fix this issue? 

### LunarVim version

release-1.3/neovim-0.9-d1c1bace-dirty

### Neovim version (>= 0.9.1)

NVIM v0.9.2

### Terminal name

alacritty

### Operating system/version

6.5.3-1-MANJARO

**Comment by brneor** [comment]
You shouldn't edit the files in `.local/share/lunarvim/` file directly, add your custom settings only to `config.lua`.

You can try adding `cmp-dictionary` to Lunarvim's cmp sources (`lvim.builtin.cmp.sources`), although I don't know how to *add* items to this list, only override it entirely. As a quickfix/test you can grab the source list from [here](https://github.com/LunarVim/LunarVim/blob/15dc5292922b8b6009db645225bfee1f26796a68/lua/lvim/core/cmp.lua#L227) and try setting `lvim.builtin.cmp.sources` to its value + cmp-dictionary until someone can give you a better solution than this.

**Comment by woshichuanqilz** [comment]
> You shouldn't edit the files in `.local/share/lunarvim/` file directly, add your custom settings only to `config.lua`.
> 
> You can try adding `cmp-dictionary` to Lunarvim's cmp sources (`lvim.builtin.cmp.sources`), although I don't know how to _add_ items to this list, only override it entirely. As a quickfix/test you can grab the source list from [here](https://github.com/LunarVim/LunarVim/blob/15dc5292922b8b6009db645225bfee1f26796a68/lua/lvim/core/cmp.lua#L227) and try setting `lvim.builtin.cmp.sources` to its value + cmp-dictionary until someone can give you a better solution than this.

Is this code same as you said? 

`table.insert(lvim.builtin.cmp.sources, 1, { name = "dictionary", keyword_length = 2, })`
But how to install `cmp-dictionary` if set in config.lua. 

I add the  code `  -- { "uga-rosa/cmp-dictionary" },` to lazy nvim. The lvim built-in nvim-cmp will be disabled.

**Comment by cpea2506** [comment]
> table.insert(lvim.builtin.cmp.sources, 1, { name = "dictionary", keyword_length = 2, })
Lua index start at `1` instead of `0` like other languages. So this line of you will override the first entry. The better way to do this is:
```lua
local sources_table = lvim.builtin.cmp.sources
sources_table[#sources_table + 1] = { 
      name = "dictionary",
      keyword_length = 2,
}
```

Also, the completion issue maybe relate to [this](https://github.com/uga-rosa/cmp-dictionary/issues/42)

**Comment by PuppyGirlBelly** [comment]
Hi, I am experiencing similar issues; I'm trying to use [cmp-nvim-lsp-signature-help](https://github.com/hrsh7th/cmp-nvim-lsp-signature-help). And it seems that cmp can't source any other source when I try to add a plugin via Lazy. 

Here is a screenshot output of `:CmpStatus`
![2023-11-12T16:14:46,974066689-07:00](https://github.com/LunarVim/LunarVim/assets/40257903/787d53e7-3001-44f2-a844-294c3a9f22e1)
