### ISSUE TITLE
mason ensure_installed not supported ?

### ISSUE THREAD

**Issue by nicolas-g** [LunarVim/LunarVim#4378]
### Problem description

I'm trying to have all the plugins I use defined in a configuration file so I don't need to run manual commands to install them but it doesn't seem to be working.

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.0-beta3

### Terminal name

Alacritty

### Operating system/version

macOS 13.6

### Steps to reproduce

This is how my Lunar VIM config looks like ( ~/.config/lvim/config.lua):

```
{
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "black",
      },
    },
  },
```

After restarting lvim, I don't see the `black` plugin has been installed...

**Comment by cpea2506** [comment]
You don't need to add plugin your self. Lvim has already do that:

```lua
lvim.lsp.installer.setup.ensure_installed = {}
```

**Comment by nicolas-g** [comment]
thanks for the reply @cpea2506  but what do you mean?

I'v added the bellow into my  ~/.config/lvim/config.lua file:
```
lvim.lsp.installer.setup.ensure_installed = { black, debugpy }
```

when I type `:Mason` I don't see either black or debugpy installed ...

**Comment by cpea2506** [comment]
Oh! I see. They are not language server. The `ensure_installed` only receive list of lsp server.
You would need this one: https://github.com/jay-babu/mason-null-ls.nvim

**Comment by chase** [comment]
See https://github.com/LunarVim/LunarVim/issues/4409#issuecomment-1802230065
