### ISSUE TITLE
Provide documentation for DAP

### ISSUE THREAD

**Issue by eagle-tex** [LunarVim/LunarVim#4379]
### Feature Description

Provide a detailed setup for DAP with DAP-UI.

Can you please provide a proper/detailed documentation on how to setup the Debug Adapter Protocol?
I've been searching for a few days and so far, nothing seems to work.

My languages of interest are Typescript, Javascript, Python
But if you have something that works and explanations on how to adapt it to other languages, I'll happily take that.

Thanks

### Describe the alternatives you have considered

Nothing found on the internet seems to be working so far.
Plus there are kind of conflicting informations.

**Comment by kobzar** [comment]
https://github.com/LunarVim/starter.lvim

**Comment by eagle-tex** [comment]
@kobzar 
I don't understand. How does your reply answer my request/question?
