### ISSUE TITLE
header files not found: cpp

### ISSUE THREAD

**Issue by yashwardhan-gautam** [LunarVim/LunarVim#4381]
### Problem description

Hello, 
I'm using pop os, i want to setup lunarvim for competitive programming.
But I think it's not including header files from designated place. 
How to update my config (`clangd.json` or inside config.lua) file to remove these errors?
![image](https://github.com/LunarVim/LunarVim/assets/33232174/4889987d-65a9-4eb2-bcae-94b75d786805)

In my system, these header files are located in 
`/usr/include/x86_64-linux-gnu/c++/11/`

### LunarVim version

release-1.3

### Neovim version (>= 0.9.1)

neovim-0.9-d1c1bace

### Operating system/version

Pop!_OS 22.04 LTS

### Affected language servers

CPP

### Actual behavior

![image](https://github.com/LunarVim/LunarVim/assets/33232174/905a0e74-b2d2-4c69-aeb8-052d868761c2)

### support info

# :LspInfo
```

 Language client log: /home/unlaome/.local/state/lvim/lsp.log
 Detected filetype:   cpp
 
 1 client(s) attached to this buffer: 
 
 Client: clangd (id: 1, bufnr: [1])
 	filetypes:       c, cpp, objc, objcpp, cuda, proto
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             clangd
 
 Configured servers list: clangd
 ```

**Comment by quil-hon-fwd** [comment]
Do you export the CXXFLAGS= correctly in your current terminal session?

**Comment by quil-hon** [comment]
Do you export the CXXFLAGS= correctly in your current terminal session?

**Comment by yashwardhan-gautam** [comment]
No, I haven't done that. Can you explain a bit more on that?

**Comment by yashwardhan-gautam** [comment]
```~ via 🐍 v3.10.9
➜ echo $CXXFLAGS


~ via 🐍 v3.10.9
➜ echo $CXX


```

**Comment by salimp2009** [comment]
you can have a look at how to configure .clangd file . As far as I can see, this is not a lvim issue. I use C++ and Cmake
https://clangd.llvm.org/config#compileflags
you add this in your  .clangd file
```sh
CompileFlags:                     
  Add: [-I/usr/include/x86_64-linux-gnu/c++/11/,  --include-directory=/usr/include] 
  ```

**Comment by Alexis12119** [comment]
I just used `cmake` to generate `compile_commands.json` which helps the `clangd` server to recognized header files.

Here's my example repo:

https://github.com/Alexis12119/sfml

**Comment by salimp2009** [comment]
this is not an lvim issue. this is learning C++ issue. you can use CMake as a build system and and add 
```
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
```
on top your project after project name like this 
```
cmake_minimum_required(VERSION 3.21 FATAL_ERROR)
project(
  message-package_project
  VERSION 1.2.1
  LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED True)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
```
So this can be closed. This is not lvim related.
