### ISSUE TITLE
assembly file not recognized as asm and asm-lsp is inactive for  C++

### ISSUE THREAD

**Issue by salimp2009** [LunarVim/LunarVim#4382]
### Problem description

Hi,
I generated an assembly file for C++ project, which I use lvim without any problem.
However when I open the assembly file which has an extension of .a , lsp gives error and the file is also not recognized as asm .
I tried manually setting the filetype as asm by
```lua
set filetype=asm
```
then file type is recognized but asm-lsp does not work.
If i open the same file with my neovim config then everythng works. I have the same clangd setup for lvim and neovim.
If i manually create a file test.a then everythng works
I first tough this is an issue related to asm-lsp and open an issue there and I attached the file and the developer also responded that it works for him. 
https://github.com/bergercookie/asm-lsp/issues/10
Here are some related output from lvim
![image](https://github.com/LunarVim/LunarVim/assets/46407603/e7829323-0e74-4037-af16-9fc1672bb3c8)

Here is the lsp info
![image](https://github.com/LunarVim/LunarVim/assets/46407603/85f546d0-ca07-417b-b42f-5e94fe532a11)
I also attached the file but I had to add .txt extension since github did not allow the .a extension.

Please if you download the file remove .txt and try to open in lvim
[libalgoFunLib.a.txt](https://github.com/LunarVim/LunarVim/files/12838501/libalgoFunLib.a.txt)

my lvim cpp config is also here
https://github.com/salimp2009/deskmach_config/blob/main/lvim/.config/lvim/llua/user/lsp/languages/cpp.lua

and I use this plugin in addition to clangd 
```lua
{ "p00f/clangd_extensions.nvim" },
```

### LunarVim version

release-1.3/neovim-0.9-0aea5a68  

### Neovim version (>= 0.9.1)

Nvim 0.9.0

### Operating system/version

Linux; Arch

### Affected language servers

asm-lsp

### Steps to reproduce

download the file remove .txt and try to open in lvim

### Actual behavior

the file type is not recognized. and lsp not working

### Expected behavior

file type is recognized and asm-lsp working

### support info

LspLog
```
  [ERROR][2023-08-20 19:02:48] .../vim/lsp/rpc.lua:734	"rpc"	"asm-lsp"	"stderr"	"INFO [asm_lsp] Populating instruction set -> x86...\n"
    [ERROR][2023-08-20 19:02:48] .../vim/lsp/rpc.lua:734	"rpc"	"asm-lsp"	"stderr"	"thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/salim/.cargo/registry/src/github.com-1ecc6299db9ec823/asm-lsp-0.3.2/src/x86_parser.rs:236:38\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

**Comment by LostNeophyte** [comment]
you can try disabling bigfile in that case

**Comment by salimp2009** [comment]
> you can try disabling bigfile in that case

I will try let you know. I was just guessing.

**Comment by salimp2009** [comment]
I guess no one has time to look at it so i will close but this needs to be looked up ;
- Why is lvim is behaving so heavy ? similar neovim setup with similar plugins runs more smoothly & with no problems at all
