### ISSUE TITLE
Add Dart/Flutter Support Please!!!

### ISSUE THREAD

**Issue by ankanroy-code** [LunarVim/LunarVim#439]
the LspInstall dose not provide any option for dart. Cant really understand what to do.

**Comment by rebuilt** [comment]
Since the LspInstall plugin doesn’t support dart, you’ll need to create a configuration yourself with lspconfig.   https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md

create a new file with your darts configs.  Source those configs in initial.lua. Manually install darts.

**Comment by ChristianChiarulli** [comment]
add the plugin and make sure to add the ft option for whoever picks this up (even if its me)

**Comment by andremeireles** [comment]
The Lsp will work out of the box after you had setup the server's snapshot file.

In lv-config.lua, after go and rust configs, add a line for dart, like this:

O.lang.dart.sdk_path = "dart/sdk/folder/until/snapshots/analysis_server.dart.snapshot"

Tested today with stable release.

**Comment by barun108** [comment]
Yes it does, 
Code actions are also working 
And snippets too
I am also using flutter tool plugin 
'akinsho/flutter-tools.nvim'

**Comment by pxsanghyo** [comment]
I'm not sure what my problem is.

Here are the steps I took:

1. Installed using the one line command
2. LspInstall lua
3. Install `flutter-tools` plugin:

```lua
-- lua/plugins.lua:
    use {'akinsho/flutter-tools.nvim', requires = 'nvim-lua/plenary.nvim'}

-- lua/lv-flutter-tools/init.lua:
    require("flutter-tools").setup{}

-- init.lua
    require('lv-flutter-tools')
```

4. PackerCompile && PackerInstall

-----------------------------------------------------

Open a dart file in Flutter project it says:
`Client # quit with exit code 64 and signal 0` where the # increases on subsequent opens (including a json file)
The Active LSP is `dartls`
However, all the Flutter commands works so far.

If this is not a flutter problem, how do I check?
I'm pretty new at this...

**Comment by pxsanghyo** [comment]
Also, auto format on save? How do I activate it?

**Comment by pxsanghyo** [comment]
I figured out how to get rid of the `Client # quit...` error for dart when using `flutter-tools` was to add this line:
`O.lang.dart.sdk_path = nil` in `lv-config.lua`

For json files, I forgot to install Lsp for it.

Now if I can get auto-format to work on save... any help would be appreciated.

**Comment by pxsanghyo** [comment]
Added the following to the `ftplugin/dart.lua` for auto-completion on save.

```lua

if O.lang.python.autoformat then
    require('lv-utils').define_augroups({
        _python_autoformat = {
            {
                'BufWritePre', '*.dart',
                'lua vim.lsp.buf.formatting_sync(nil, 1000)'
            }
        }
    })
end
```

**Comment by pxsanghyo** [comment]
Created PR flutter-tools #658

**Comment by andremeireles** [comment]
> Created PR flutter-tools #658

Thanks for add flutter support @pxsanghyo.
I am using the stable branch and applied your changes. At opening dart files, it show me two dartls servers. Saving files always ask me wich server to choose.
It's needed to type `:LspRestart` to get rid of one them.

**Comment by IndianBoy42** [comment]
> At opening dart files, it show me two dartls servers. Saving files always ask me wich server to choose.
> It's needed to type `:LspRestart` to get rid of one them.

Quoting from the page of flutter-tools.nvim

- flutter tools does not depend on nvim-lspconfig. The two can co-exist but please ensure you do NOT configure dartls using lspconfig. It will be automatically set up by this plugin instead.

it seems LunarVim initializes a dart ls and so does flutter-tools

Try to remove lines 1:11 in `ftplugin/dart.lua`. or move them to the correct place in `lua/lv-flutter-tools/init.lua`, I can't find the analogous configs from skimming the flutter-tools repo, I don't know if they are important either

**Comment by pxsanghyo** [comment]
support flutter-tools #681
old one was a mess with conflicts... git newbie

@andremeireles check out the new pr. it adds active flag for flutter-tools so that dartlsp is only configured by flutter-tools. here is my lv-config:

```lua
O.lang.dart.sdk_path = '/Users/pxsanghyo/.flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot'
O.lang.dart.flutter_tools.active = true
O.lang.dart.autoformat = true
```

ie. dart.sdk_path is not required if flutter_tools is active.

**Comment by pxsanghyo** [comment]
Hmm... It used to work but now it doesn't connect to dartls.
It's weird because it connects 1/10 tries... w t f

**Comment by andremeireles** [comment]
> Hmm... It used to work but now it doesn't connect to dartls.
> It's weird because it connects 1/10 tries... w t f
> 
> Any ideas?

Guys, take a look at Pull request #799.
I think most issues are fixed there.

**Comment by iapicca** [comment]
> Since the LspInstall plugin doesn’t support dart, you’ll need to create a configuration yourself with lspconfig. https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md
> 
> create a new file with your darts configs. Source those configs in initial.lua. Manually install darts.

@rebuilt 
https://github.com/akinsho/flutter-tools.nvim

**Comment by abzcoding** [comment]
you can use this in rolling
```lua
lvim.lsp.override = { "dart" }
lvim.plugins = {
    {
      "akinsho/flutter-tools.nvim",
      requires = "nvim-lua/plenary.nvim",
      config = function()
        require("flutter-tools").setup {
          lsp = {
            on_attach = require("lsp").common_on_attach,
          },
        }
      end,
      ft = "dart",
    },
}
```

**Comment by iapicca** [comment]
@abzcoding 
I didn't mean [this](https://github.com/LunarVim/LunarVim/issues/439#issuecomment-884388217) as a solution,
but as a workaround until dart and flutter aren't added in the available languages

would you please consider reopening this issue?

**Comment by kylo252** [comment]
Added supported in #1584
