### ISSUE TITLE
[Comment.nvim] Invalid commentstring for llvm! Read `:h commentstring` for help.

### ISSUE THREAD

**Issue by nickdesaulniers** [LunarVim/LunarVim#4394]
### Problem description

The llvm syntax highlighting file seems to not work for me when I try to comment out lines using `gcc` (oh, the irony) command.

https://github.com/llvm/llvm-project/blob/main/llvm/utils/vim/syntax/llvm.vim

in my config:
```
vim.cmd [[
  source /android0/llvm-project/llvm/utils/vim/syntax/llvm.vim
  au BufNewFile,BufRead *.ll setf llvm
]]
```

### LunarVim version

release-1.3/neovim-0.9-d1c1bace2218

### Neovim version (>= 0.9.1)

NVIM v0.9.4

### Terminal name

terminator

### Operating system/version

linux 6.5.3 (debian fork)

### Steps to reproduce

open .ll file with the above config set

`gcc` to comment out line

nothing happens, instead I observe the warning from the title.

Do I need to update the llvm syntax file or something?

**Comment by chase** [comment]
Setting the syntax file won't have any effect. `:h commentstring` has exactly the answer you need.

`setlocal commentstring=;\ %s`

**Comment by nickdesaulniers** [comment]
Thanks for the suggestion @chase , I've sent a patch to update LLVM's syntax file in https://github.com/llvm/llvm-project/pull/71838.  Does that look right to you (it works for me, dunno if that's the best way to set that var).

**Comment by chase** [comment]
@nickdesaulniers `vim/ftplugin/llvm.vim` is probably a better place for this than the syntax file

**Comment by nickdesaulniers** [comment]
done in https://github.com/llvm/llvm-project/pull/71838/commits/4e231b774127af3a9501e02177b28e7eb57db33f, thanks for the suggestion!
