### ISSUE TITLE
lvim: "Invalid configuration: /home/user/.config/lvim/config.lua:3" attempt to index field '1' (a nil value)" - default config doesn't load

### ISSUE THREAD

**Issue by ProgrammingLife** [LunarVim/LunarVim#4396]
### Problem description

I just generate default config file and ran my lvim again.

### LunarVim version

1.3

### Neovim version (>= 0.9.1)

v0.9.4

### Terminal name

xfce4-terminal

### Operating system/version

Arch Linux

### Steps to reproduce

```
$ cd ~/.config/lvim/
$ mv config.lua config.lua.bak0
$ lvim --headless +'lua require("lvim.utils").generate_settings()' +qa && sort -o lv-settings.lua{,}
$ mv lv-settings.lua config.lua

$ head -5 config.lua                                                            
lvim.builtin.alpha.active = true
lvim.builtin.alpha.dashboard.opts.autostart = true
lvim.builtin.alpha.dashboard.section.buttons.entries["1"]["1"] = "f"
lvim.builtin.alpha.dashboard.section.buttons.entries["1"]["2"] = "󰈞  Find File"
lvim.builtin.alpha.dashboard.section.buttons.entries["1"]["3"] = "<CMD>Telescope find_files<CR>"

# Run it:
$ lvim config.lua
```

**Comment by cpea2506** [comment]
What you do is to search for key `"1"` not for index `1`
```lua?
lvim.builtin.alpha.dashboard.section.buttons.entries[1][1] = "f"
```

**Comment by cpea2506** [comment]
> > What you do is to search for key `"1"` not for index `1`
> > ```lua
> > lvim.builtin.alpha.dashboard.section.buttons.entries[1][1] = "f"
> > ```
> 
> Ok, but that's what `generate_settings()` returned to me. Should I manually edit all those indexes to make it work? Or I suppose I can use lv-settings.lua just for a reference and use only those lines I need. After it fixing, of course.

I think you shoud take `lv-settings` as a reference only. And I think that way to genenate config is from old version of Lunarvim that should not be used anymore.

**Comment by cpea2506** [comment]
> > I think you should take `lv-settings` as a reference only.
> 
> Got it!
> 
> > And I think that way to genenate config is from old version of Lunarvim that should not be used anymore.
> 
> Ok, but I took that from the official documentation: [lunarvim.org/docs/configuration](https://www.lunarvim.org/docs/configuration) It says absolutely nothing about the fact that these settings are from the previous version of the LunarVim and it should no longer be used for actual version.
