### ISSUE TITLE
Android Emulator and IOS Simulatro Support

### ISSUE THREAD

**Issue by Burnsedia** [LunarVim/LunarVim#4397]
### Feature Description

Add a official plugin to support android and ios development. I am using [telescope-simulators.nvim](https://github.com/dimaportenko/telescope-simulators.nvim) for my LunarVim Setup and I also think this should be a optional configuration at install like the rust and nodejs options in the install.sh

### Describe the alternatives you have considered

There are soveral other plugins and you can use the commandline tools with a bash script but a full intergration would be better.

**Comment by kenkoro** [comment]
I love nvim and that's great, but I think it's more efficient and convenient to use Android Studio (or something for IOS development). I mean, just use IDE and sometimes nvim for small changes. imho

**Comment by kobzar** [comment]
Sorry man, but this is very specify plugin. And i think you just one who needed it.

**Comment by chase** [comment]
@Burnsedia the right place for this is [LunarVim/starter.lvim](https://github.com/LunarVim/starter.lvim). You can make a LunarVim starter for others to use!

**Comment by Burnsedia** [comment]
Sounds good
