### ISSUE TITLE
Why the color is so strange in macos terminal.

### ISSUE THREAD

**Issue by Gowa2017** [LunarVim/LunarVim#4400]
<img width="746" alt="image" src="https://github.com/LunarVim/LunarVim/assets/33367355/5a501f60-e56b-4663-b61c-a2552b156231">

Open direct in nvim is OK:

<img width="710" alt="image" src="https://github.com/LunarVim/LunarVim/assets/33367355/4159fc11-b0c8-42f0-9d43-0c658d770a74">

**Comment by cpea2506** [comment]
```lua
vim.opt.termguicolors = false
```

**Comment by Gowa2017** [comment]
> ```lua
> vim.opt.termguicolors = false
> ```
> 
> macOS's Terminal doesn't support 24 bit color
> 
> See: `:h termguicolors`
> 
> ```viml
> 		*'termguicolors'* *'tgc'* *'notermguicolors'* *'notgc'*
> 'termguicolors' 'tgc'	boolean	(default off)
> 			global
> 	Enables 24-bit RGB color in the |TUI|.  Uses "gui" |:highlight|
> 	attributes instead of "cterm" attributes. |guifg|
> 	Requires an ISO-8613-3 compatible terminal.
> ```
> 
> In case you want to use different colorscheme that requires 24-bit color to function properly. I suggest to use another terminal like: Alacritty, Kitty, Wezterm,...
> 
> Note: Please re-open this issue if this problem keep happening. Thank you!
Thanks very.If I close the `Show ANIS color` option os terminal, it do not get the strange color, but other color also do not show.

Ok, now I use iTerm2 instead.
