### ISSUE TITLE
2 file explorers are showing up on a fresh install of lunarvim

### ISSUE THREAD

**Issue by diningPhilosopher64** [LunarVim/LunarVim#4402]
### Problem description

Make a fresh install of lunarvim ( I did it in a new ubuntu docker container)

After adding fonts and launching lunarvim then press: <leader> + e (to launch the file explorer):

As there is a file explorer already open, it would open another one as shown:

![image](https://github.com/LunarVim/LunarVim/assets/12293878/c7234536-6ba6-49be-beaa-95f62d25f533)

I'm able to close the second one and work as usual without issues. 

This happens only on startup.

This issue is not specific to docker containers. It happens on regular desktop linux.

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1692716794

### Terminal name

bash

### Operating system/version

ubuntu 20.04 

### Steps to reproduce

1. Fresh install of lunarvim
2. Install fonts (optional I think)
3. launch lunarvim
4. You should have file explorer open already. 
5. Now press <leader> + e : This will open another file explorer next to the previous one.

**Comment by brneor** [comment]
Which exact command and parameters are you using to open lunarvim?

**Comment by diningPhilosopher64** [comment]
Thanks for responding @brneor. 

I use no extra commands, just `lvim`. Was able to confirm with another colleague that this issue exists.

One additional point I forgot to add:

The file explorer that is visible when lvim is launched seems to be the `netrw` file explorer(as it behaves the same way).

When I press `<leader> + e`, the file explorer that gets added (to the left) is nvim-tree file explorer as I can run shortcuts available for it such as `Shift + r` to refresh, `r` to rename etc.

**Comment by LostNeophyte** [comment]
the explorer on the right is lir and the one on the left it nvimtree, this is not a bug. leader e is for nvimtree so it opens it

**Comment by diningPhilosopher64** [comment]
@LostNeophyte okay. But wouldn't it make sense to disable the explorer on the right ( what does lir mean ?) when nvim-tree is enabled by default ?

Or if this is how it is, do you know the command to hide the one on the right ? 

Thanks.

**Comment by LostNeophyte** [comment]
> @LostNeophyte okay. But wouldn't it make sense to disable the explorer on the right ( what does lir mean ?) when nvim-tree is enabled by default ?

I agree, I have it disabled in my config

> ( what does lir mean ?)

it's a different file explorer plugin lir.nvim

> Or if this is how it is, do you know the command to hide the one on the right ?

if you open anything in the right one it will close, or close its buffer, it's a netrw replacement

**Comment by diningPhilosopher64** [comment]
> I agree, I have it disabled in my config

@LostNeophyte  could you share the link to it please ?

**Comment by LostNeophyte** [comment]
https://gitlab.com/lostneophyte/dotfiles/-/blob/a14a8370dabfa32e3a475033a1dfeb8d1d6d8057/lvim/.config/lvim/lua/user/nvimtree.lua#L1

**Comment by diningPhilosopher64** [comment]
@LostNeophyte  thank you!
