### ISSUE TITLE
Unable to generate lv-settings.lua in Windows Powershell.

### ISSUE THREAD

**Issue by yliu-fe** [LunarVim/LunarVim#4404]
### Problem description

Referring to the document, I want to generate the file `lv-settings.lua` and configure my editor. 
The only command I used was:
```shell
cd ~/AppData/Local/lvim
lvim --headless +'lua require("lvim.utils").generate_settings()' +qa && sort -o lv-settings.lua{,}
```
Then Powershell raised ParserError:

>ParserError:
>Line |
>    1 |  … ("lvim.utils").generate_settings()' +qa && sort -o lv-settings.lua{,}
>       |                                                                        ~
>       | Missing expression after unary operator ','.

and no file was generated.

### LunarVim version

release-1.3/neovim-0.9-d1c1bac

### Neovim version (>= 0.9.1)

NVIM v0.9.4

### Terminal name

Powershell 7.3.9

### Operating system/version

Windows 11

### Steps to reproduce

1. change directory to `~/AppData/Local/lvim`, where the `config.lua` located.
2. execute the command `lvim --headless +'lua require("lvim.utils").generate_settings()' +qa && sort -o lv-settings.lua{,}`

**Comment by cpea2506** [comment]
I'm not sure if there is `sort` command on Powershell. It's just used to sort the file content. You can remove it and run

```lua
lvim --headless +'lua require("lvim.utils").generate_settings()' +qa
```

**Comment by yliu-fe** [comment]
@cpea2506 It works, thank you!
