### ISSUE TITLE
[Question] How can make some dependencies (flake8) always be installed by mason?

### ISSUE THREAD

**Issue by docwhite** [LunarVim/LunarVim#4409]
I am following [chris@machine's LunarVim as a Python IDE | Pyright | Black Formatting | Flake8 Linting | Virtual ENV Switching](https://www.youtube.com/watch?v=lUssfjNzGNg) video and it sets up flake8.

I needed to do `:MasonInstall flake8` otherwise it would complain about not finding it.

Is there a place in the configs where you can specify that you want flake8 always to be instaleld?

Something along the lines of:

```
lvim.builtin.treesitter.ensure_installed = {
  "python",
}
```

But for specific packages that the previous snippet might miss installing?

**Comment by programB** [comment]
1. Once you've installed flake8 through Mason is should stay installed as long as you have not uninstalled it (or Lunarvim) - so it's a one time effort
2. I'm not not sure what you mean by "specific packages" but note that treesitters parsers are not the same as external tools installed by Mason
3. Lunarvim comes with the mason-lspconfig plugin (https://github.com/williamboman/mason-lspconfig.nvim) installed which can be used to automatically install LSPs, eg. adding this to Lunarvim's config.lua
```
require("mason-lspconfig").setup {
    ensure_installed = { "lua_ls", "pyright" },
}
```
will ensure those 2 LSPs get installed through Mason on Lunarvim startup. Unfortunately  it doesn't seem to be able to do it for formatters or linters (like flake8), at least for now, but....
4. ...you can use mason-tool-installer plugin (https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim). In your case, to get started try adding this plugin like so:
```
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    config = function()
      require('mason-tool-installer').setup {
      ensure_installed = {
         { 'flake8', auto_update = true },
        },
        auto_update = false,
        run_on_start = true,
        start_delay = 3000, -- 3 second delay
        debounce_hours = 5, -- at least 5 hours between attempts to install/update
      }
    end
  },
```
You may need to comment out the debounce_hours option if you don't see any installation happening.

**Comment by docwhite** [comment]
Thank you very much @programB ! I am now using `mason-tool-installer` so that if I install LunarVim elsewhere, only with my config file it will install all the packages I need.
