### ISSUE TITLE
How can I list all errors instead of having them inline?

### ISSUE THREAD

**Issue by docwhite** [LunarVim/LunarVim#4413]
### Problem description

Errors and code warnings are displayed inline.

It is difficult to read the full stacktrace or message.

Is there a chance I can view them listed in a panel or window? What plugin is used under the hood?

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

0.9.2

### Terminal name

Alacritty

### Operating system/version

macOS 13.5

### Steps to reproduce

Write some code that upsets the linter.

### Screenshots

<img width="1627" alt="Screenshot 2023-11-07 at 12 01 58" src="https://github.com/LunarVim/LunarVim/assets/6486812/dfcc891f-a962-4f42-8e86-02dd3400f632">

**Comment by chase** [comment]
@docwhite These errors and warnings are called diagnostics.

You can disable the per-line diagnostics by adding this to your `config.lua`:
```
vim.diagnostic.config({ virtual_text = false })
```

You can view the diagnostic at the cursor with `gl` or `<Leader>le`.
List of all diagnostics in the current buffer/file: `<Leader>ld`.
List of all diagnostics in the LSP's workspace/project `<Leader>lw`.

For more information, including what `<Leader>` is, refer to 
https://www.lunarvim.org/docs/beginners-guide/keybinds-overview

**Comment by docwhite** [comment]
Thanks so much @chase that's what I needed to know 🙇
