### ISSUE TITLE
使用lunarvim编辑c或cpp文件时，不停的警告

### ISSUE THREAD

**Issue by rjs520** [LunarVim/LunarVim#4414]
### Problem description

# 使用lunarvim编辑c或cpp文件时，不停的警告

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1692716794

### Terminal name

Windows terminal

### Operating system/version

Ubuntu 22.04

### Steps to reproduce

# 这是我的配置

--[[
 THESE ARE EXAMPLE CONFIGS FEEL FREE TO CHANGE TO WHATEVER YOU WANT
 `lvim` is the global options object
]]
-- vim options
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.relativenumber = true
vim.keymap.set("i", "jk", "<ESC>")

-- vim.cmd([[source $HOME/.config/lvim/wsl.vim]])
-- general
lvim.log.level = "info"
lvim.format_on_save = {
	enabled = true,
	pattern = "*.lua",
	timeout = 1000,
}
-- to disable icons and use a minimalist setup, uncomment the following
-- lvim.use_icons = false
-- lvim.transparent_window = true

-- keymappings <https://www.lunarvim.org/docs/configuration/keybindings>
lvim.leader = "space"
-- add your own keymapping
lvim.keys.normal_mode["<C-s>"] = ":w<cr>"
-- lvim.keys.normal_mode["<A-m>"] = ":NvimTreeToggle<CR>"
lvim.keys.normal_mode["<C-q>"] = ":BufferLineCyclePrev<CR>"
lvim.keys.normal_mode["<C-e>"] = ":BufferLineCycleNext<CR>"
-- lvim.keys.normal_mode["<C-tab>"] = ":BufferLineCycleNext<CR>"
lvim.keys.normal_mode["<C-w>"] = ":BufferKill<CR>"
lvim.keys.normal_mode["<C-t>"] = ":terminal<CR>"
--lvim.keys.normal_mode["<A-f>"] = ":lua require('jdtls.setup').add_commands()<CR>"
lvim.keys.normal_mode["<C-m>"] = ":MarkdownPreviewToggle<CR>"

-- -- Change theme settings
lvim.colorscheme = "onedark"

lvim.builtin.alpha.active = true
lvim.builtin.alpha.mode = "dashboard"
lvim.builtin.terminal.active = true
lvim.builtin.nvimtree.setup.view.side = "left"
lvim.builtin.nvimtree.setup.renderer.icons.show.git = false
lvim.builtin.dap.active = true -- (default: false)

-- Automatically install missing parsers when entering buffer
lvim.builtin.treesitter.auto_install = true

-- lvim.builtin.treesitter.ignore_install = { "haskell" }
local _, actions = pcall(require, "telescope.actions")
lvim.builtin.telescope.defaults.mappings = {
	--   -- for input mode
	i = {
		["<C-j>"] = actions.move_selection_next,
		["<C-k>"] = actions.move_selection_previous,
		["<C-n>"] = actions.cycle_history_next,
		["<C-p>"] = actions.cycle_history_prev,
	},
	-- for normal mode
	n = {
		["<C-j>"] = actions.move_selection_next,
		["<C-k>"] = actions.move_selection_previous,
	},
}

local components = require("lvim.core.lualine.components")

lvim.builtin.lualine.sections.lualine_a = {
	{ "mode", separator = { left = "" }, right_padding = 2 },
}
lvim.builtin.lualine.sections.lualine_b = {
	components.branch,
	components.diff,
	components.diagnostics,
}
lvim.builtin.lualine.sections.lualine_c = {
	components.filename,
}
lvim.builtin.lualine.sections.lualine_x = {
	components.encoding,
	components.filetype,
	components.lsp,
	{
		require("lazy.status").updates,
		cond = require("lazy.status").has_updates,
		color = { fg = "#ff9e64" },
	},
}
lvim.builtin.lualine.sections.lualine_y = {
	components.spaces,
	components.treesitter,
}
lvim.builtin.lualine.sections.lualine_z = {
	components.location,
	{ "progress", separator = { right = "" }, left_padding = 2 },
}
-- lualine themes
lvim.builtin.lualine.options.theme = "auto"
lvim.builtin.lualine.style = "default" -- or "none"
-- Use which-key to add extra bindings with the leader-key prefix
lvim.builtin.which_key.mappings["P"] = { "<cmd>Telescope projects<CR>", "Projects" }
lvim.builtin.which_key.mappings["X"] = { name = "nvim-jdtls" }
lvim.builtin.which_key.mappings["t"] = {
	name = "Trouble",
	r = { "<cmd>Trouble lsp_references<cr>", "References" },
	f = { "<cmd>Trouble lsp_definitions<cr>", "Definitions" },
	d = { "<cmd>Trouble document_diagnostics<cr>", "Diagnostics" },
	q = { "<cmd>Trouble quickfix<cr>", "QuickFix" },
	l = { "<cmd>Trouble loclist<cr>", "LocationList" },
	w = { "<cmd>Trouble workspace_diagnostics<cr>", "Workspace Diagnostics" },
}
lvim.builtin.which_key.mappings["x"] = {
	name = "jdtls",
	r = { "<cmd>JdtUpdateConfig<cr>", "JdtUpdateConfig" },
	b = { "<cmd>JdtBytecode<cr>", "JdtBytecode" },
	c = { "<cmd>JdtCompile<cr>", "JdtCompile" },
	j = { "<cmd>JdtJol<cr>", "JdtJol" },
	x = { "cmd>JdtJshell<cr>", "JdtJshell" },
	w = { "<cmd>JdtRestart<cr>", "JdtRestart" },
	s = { "<cmd>JdtSetRuntime<cr>", "JdtSetRuntime" },
	u = { "<cmd>JdtShowLogs<cr>", "JdtShowLogs" },
	t = { "<cmd>JdtWipeDataAndRestart<cr>", "jdtWipeDataAndRestart" },
}
lvim.builtin.which_key.mappings["r"] = {
	name = "code_runner",
	r = { "<cmd>RunCode<cr>", "RunCode" },
	f = { "<cmd>Runfile<cr>", "RunFile" },
	p = { "<cmd>RunProject<cr>", "RunProject" },
	y = { "<cmd>RunFile tab<cr>", "RunFileTab" },
	c = { "<cmd>RunClose<cr>", "RunClose" },
	v = { "<cmd>CRFiletype<cr>", "CRFiletype" },
	z = { "<cmd>CRProjects<cr>", "CRProjects" },
}
lvim.builtin.which_key.mappings["a"] = {
	name = "lspsaga",
	r = { "<cmd>Lspsaga rename<cr>", "Rename" },
	c = { "<cmd>Lspsaga code_action<cr>", "code_action" },
	t = { "<cmd>Lspsaga term_toggle<cr>", "term_toggle" },
	s = { "<cmd>Lspsaga symbols in winbar<cr>", "symbols in winbar" },
	o = { "<cmd>Lspsaga outline<cr>", "outline" },
	d = { "<cmd>Lspsaga diagnostic_jump_next<cr>", "diagnostic_jump_next" },
	w = { "<cmd>Lspasga hover_doc<cr>", "hover_doc" },
	i = { "<cmd>Lspsaga Lightbulb<cr>", "Lightbulb" },
	g = { "<cmd>Lspsaga goto_definition<cr>", "goto_definition" },
	p = { "<cmd>Lspsaga peek_definition<cr>", "peek_definition" },
	f = { "<cmd>Lspsaga lsp_finder<cr>", "lsp_finder" },
	q = { "<cmd>Lspsaga show_diagnostics<cr>", "show_diagnostics" },
	e = { "<cmd>Lspsaga incoming_calls / outgoing_calls<cr>", "incoming_calls / outgoing_calls" },
}

-- -- generic LSP settings <https://www.lunarvim.org/docs/languages#lsp-support>

-- --- disable automatic installation of servers
-- lvim.lsp.installer.setup.automatic_installation = false
lvim.builtin.treesitter.ignore_install = { "haskell" }
lvim.builtin.treesitter.highlight.enable = true

-- -- linters and formatters <https://www.lunarvim.org/docs/languages#lintingformatting>
local formatters = require("lvim.lsp.null-ls.formatters")
formatters.setup({
	{ command = "black",         filetypes = { "python" } },
	{ command = "clang-format",  filetypes = { "java" } },
	{ command = "clang-format",  filetypes = { "c", "cpp" } },
	{ command = "markdownlint",  filetypes = { "markdown" } },
	{ command = "rustfmt",       filetypes = { "rust" } },
	{ command = "stylua",        filetypes = { "lua" } },
	{ command = "sql-formatter", filetypes = { "sql" } },
	{ command = "fixjson",       filetypes = { "json" } },
})

-- -- set additional linters
local linters = require("lvim.lsp.null-ls.linters")
linters.setup({
	{ command = "flake8", filetypes = { "python" } },
	{
		--     -- each formatter accepts a list of options identical to https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#Configuration
		command = "eslint_d",
		--     ---@usage arguments to pass to the formatter
		--     -- these cannot contain whitespaces, options such as `--line-width 80` become either `{'--line-width', '80'}` or `{'--line-width=80'}`
		extra_args = { "--print-with", "100" },
		--     ---@usage specify which filetypes to enable. By default a providers will attach to all the filetypes it supports.
		filetypes = { "typescript", "typescriptreact", "vue", "javascript" },
	},
	{
		--     -- each linter accepts a list of options identical to https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#Configuration
		command = "shellcheck",
		--     ---@usage arguments to pass to the formatter
		--     -- these cannot contain whitespaces, options such as `--line-width 80` become either `{'--line-width', '80'}` or `{'--line-width=80'}`
		extra_args = { "--severity", "warning" },
	},
	{
		command = "codespell",
		--     ---@usage specify which filetypes to enable. By default a providers will attach to all the filetypes it supports.
		filetypes = { "javascript", "python" },
	},
})
-- -- set additional code_actions
local code_actions = require("lvim.lsp.null-ls.code_actions")
code_actions.setup({
	{
		command = "proselint",
		args = { "--json" },
		filetypes = { "markdown", "tex" },
	},
	{
		exe = "eslint_d",
		filetypes = { "typescript", "typescriptreact", "javascript", "javascriptreact", "vue" },
	},
})
-- -- Additional Plugins <https://www.lunarvim.org/docs/plugins#user-plugins>
lvim.plugins = {
	{
		"folke/trouble.nvim",
		cmd = "TroubleToggle",
	},
	{ "mfussenegger/nvim-jdtls", lazy = true },
	{ "stevearc/dressing.nvim" },
	{
		"glepnir/lspsaga.nvim",
		event = "BufRead",
		config = function()
			require("lspsaga").setup({
				symbol_in_winbar = {
					enable = false,
					separator = " ",
					hide_keyword = true,
					show_file = true,
					folder_level = 2,
					respect_root = false,
					color_mode = true,
				},
			})
		end,
		dependencies = { { "nvim-tree/nvim-web-devicons" } },
	},
	{ "weilbith/nvim-code-action-menu", cmd = "CodeActionMenu" },
	{ "navarasu/onedark.nvim" },
	{
		"Kasama/nvim-custom-diagnostic-highlight",
		config = function()
			require("nvim-custom-diagnostic-highlight").setup({})
		end,
	},
	{
		"klen/nvim-test",
		config = function()
			require("nvim-test").setup()
		end,
	},
	{ "mfussenegger/nvim-dap-python" },
	{ "nvim-telescope/telescope-ui-select.nvim" },
	{ "ggandor/leap.nvim" },
	{ "mfussenegger/nvim-lint" },
	{
		"windwp/nvim-ts-autotag",
		config = function()
			require("nvim-ts-autotag").setup()
		end,
	},
	{ "mhartington/formatter.nvim" },
	{
		"ethanholz/nvim-lastplace",
		event = "BufRead",
		config = function()
			require("nvim-lastplace").setup({
				lastplace_ignore_buftype = { "quickfix", "nofile", "help" },
				lastplace_ignore_filetype = {
					"gitcommit",
					"gitrebase",
					"svn",
					"hgcommit",
				},
				lastplace_open_folds = true,
			})
		end,
	},
	{ "wakatime/vim-wakatime" },
	{
		"zbirenbaum/copilot.lua",
		cmd = "Copilot",
		event = "InsertEnter",
	},
	{
		"zbirenbaum/copilot-cmp",
		after = { "copilot.lua" },
		config = function()
			require("copilot_cmp").setup()
		end,
	},
	{ "kdheepak/lazygit.nvim" },
	{
		"folke/noice.nvim",
		config = function()
			require("noice").setup({
				-- add any options here
				-- background_color = "#000000",
				lsp = {
					-- override markdown rendering so that **cmp** and other plugins use **Treesitter**
					override = {
						["vim.lsp.util.convert_input_to_markdown_lines"] = true,
						["vim.lsp.util.stylize_markdown"] = true,
						["cmp.entry.get_documentation"] = true,
					},
					hover = {
						enabled = false,
						view = nil, -- when nil, use defaults from documentation
						opts = {}, -- merged with defaults from documentation
					},
					signature = {
						enabled = false,
						auto_open = {
							enabled = true,
							trigger = true, -- Automatically show signature help when typing a trigger character from the LSP
							luasnip = true, -- Will open signature help when jumping to Luasnip insert nodes
							throttle = 50, -- Debounce lsp signature help request by 50ms
						},
						view = nil, -- when nil, use defaults from documentation
						opts = {}, -- merged with defaults from documentation
					},
				},
			})
		end,
		dependencies = {
			-- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
			"MunifTanjim/nui.nvim",
			-- OPTIONAL:
			--   `nvim-notify` is only needed, if you want to use the notification view.
			--   If not available, we use `mini` as the fallback
			"rcarriga/nvim-notify",
		},
	},
	{
		"jinzhongjia/LspUI.nvim",
		config = function()
			require("LspUI").setup()
		end,
	},
	{ "MunifTanjim/prettier.nvim" },
	{ "CRAG666/code_runner.nvim", dependencies = "nvim-lua/plenary.nvim" },
}

require("onedark").setup({
	style = "darker",
})
require("onedark").load()
require("nvim-treesitter.configs").setup({
	context_commentstring = {
		enable = true,
		config = {
			css = "// %s",
		},
		javascript = {
			__default = "// %s",
			jsx_element = "{/* %s */}",
			jsx_fragment = "{/* %s */}",
			jsx_attribute = "// %s",
			comment = "// %s",
		},
	},
})
local dap = require("dap")
dap.adapters.cppdbg = {
	id = "cppdbg",
	type = "executable",
	command = "/home/rjs/.local/share/nvim/mason/bin/OpenDebugAD7",
}
dap.configurations.cpp = {
	{
		name = "Launch file",
		type = "cppdbg",
		request = "launch",
		program = function()
			return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
		end,
		cwd = "${workspaceFolder}",
		stopAtEntry = true,
	},
	{
		name = "Attach to gdbserver :1234",
		type = "cppdbg",
		request = "launch",
		MIMode = "gdb",
		miDebuggerServerAddress = "localhost:1234",
		miDebuggerPath = "/usr/bin/gdb",
		cwd = "${workspaceFolder}",
		program = function()
			return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
		end,
	},
}
dap.configurations.c = dap.configurations.cpp
dap.configurations.rust = dap.configurations.cpp
require("telescope").load_extension("lazygit")

require("nvim-test").setup({
	run = true,            -- run tests (using for debug)
	commands_create = true, -- create commands (TestFile, TestLast, ...)
	filename_modifier = ":.", -- modify filenames before tests run(:h filename-modifiers)
	silent = false,        -- less notifications
	term = "terminal",     -- a terminal to run ("terminal"|"toggleterm")
	termOpts = {
		direction = "vertical", -- terminal's direction ("horizontal"|"vertical"|"float")
		width = 96,        -- terminal's width (for vertical|float)
		height = 24,       -- terminal's height (for horizontal|float)
		go_back = false,   -- return focus to original window after executing
		stopinsert = "auto", -- exit from insert mode (true|false|"auto")
		keep_one = true,   -- keep only one terminal for testing
	},
	runners = {            -- setup tests runners
		cs = "nvim-test.runners.dotnet",
		go = "nvim-test.runners.go-test",
		haskell = "nvim-test.runners.hspec",
		javascriptreact = "nvim-test.runners.jest",
		javascript = "nvim-test.runners.jest",
		lua = "nvim-test.runners.busted",
		python = "nvim-test.runners.pytest",
		ruby = "nvim-test.runners.rspec",
		rust = "nvim-test.runners.cargo-test",
		typescript = "nvim-test.runners.jest",
		typescriptreact = "nvim-test.runners.jest",
	},
})
require("telescope").load_extension("noice")
-- -- Autocommands (`:help autocmd`) <https://neovim.io/doc/user/autocmd.html>
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = "zsh",
--   callback = function()
--     -- let treesitter use bash highlight for zsh files as well
--     require("nvim-treesitter.highlight").attach(0, "bash")
--   end,
-- })
require("code_runner").setup({
	-- put here the commands by filetype
	filetype = {
		java = "cd $dir && javac $fileName && java $fileNameWithoutExt",
		python = "python3 -u",
		typescript = "deno run",
		rust = "cd $dir && rustc $fileName && $dir/$fileNameWithoutExt",
		c = "cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt",
		cpp = "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt",
		sh = "bash",
	},
})
local ok, copilot = pcall(require, "copilot")
if not ok then
	return
end

copilot.setup({
	suggestion = {
		keymap = {
			accept = "<C-l>",
			next = "<C-j>",
			prev = "<C-k>",
			dismiss = "<C-h>",
		},
	},
})

local opts = { noremap = true, silent = true }
vim.api.nvim_set_keymap("n", "<c-s>", "<cmd>lua require('copilot.suggestion').toggle_auto_trigger()<CR>", opts)

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/87847751/7682cccb-ee02-43e8-b915-f54890b012a6)

**Comment by cauliyang** [comment]
@rjs520, you need to launch clangd with `--offset-encoding=utf-16`, the issue should be fixe.

**Comment by rjs520** [comment]
> @rjs520, you need to launch clangd with `--offset-encoding=utf-16`, the issue should be fixe.

So how should I modify it? Can you tell me the detailed process? Thank you.

**Comment by cauliyang** [comment]
```lua

local clangd_flags = {
    "--fallback-style=Google",
    "--background-index",
    "-j=8",
    "--all-scopes-completion",
    "--pch-storage=memory",
    "--clang-tidy",
    "--log=error",
    "--completion-style=detailed",
    "--header-insertion=iwyu",
    "--header-insertion-decorators",
    "--enable-config", -- clangd 11+ supports reading from .clangd configuration file
    "--offset-encoding=utf-16", --temporary fix for null-ls
    "--ranking-model=heuristics",
    "--function-arg-placeholders",
}


local opts = {
    cmd = { "clangd", unpack(clangd_flags) },
}

require("lvim.lsp.manager").setup("clangd", opts)
```

**Comment by rjs520** [comment]
> ```lua
> vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "clangd" })
> 
> local clangd_flags = {
>     "--fallback-style=Google",
>     "--background-index",
>     "-j=8",
>     "--all-scopes-completion",
>     "--pch-storage=memory",
>     "--clang-tidy",
>     "--log=error",
>     "--completion-style=detailed",
>     "--header-insertion=iwyu",
>     "--header-insertion-decorators",
>     "--enable-config", -- clangd 11+ supports reading from .clangd configuration file
>     "--offset-encoding=utf-16", --temporary fix for null-ls
>     "--ranking-model=heuristics",
>     "--function-arg-placeholders",
> }
> 
> 
> local opts = {
>     cmd = { "clangd", unpack(clangd_flags) },
> }
> 
> require("lvim.lsp.manager").setup("clangd", opts)
> ```
> 
> you can modify other parameters according to your requirements.

Successfully solved, you are really great, really thank you very much, play very admire you

**Comment by rjs520** [comment]
@cauliyang Successfully solved, you are really great, really thank you very much, play very admire you
