### ISSUE TITLE
How to reload config.lua without exiting lunarvim?

### ISSUE THREAD

**Issue by mohamadiarch** [LunarVim/LunarVim#4439]
### Problem description

I am changing my config inside `config.lua`, Is there a way to reload Lunarvim without exiting that?
I changed relativenumber with `vim.opt.relativenumber = true  ` and tried `:source %` when my current buffer in `config.lua` but it does not work. How can I do that?

### LunarVim version

start-a16bd7e3-dirty

### Neovim version (>= 0.9.1)

0.9.4

### Terminal name

powershell 

### Operating system/version

windows/11

**Comment by LostNeophyte** [comment]
`:LvimReload`, but it doesn't work for everything

**Comment by mohamadiarch** [comment]
@LostNeophyte  but why `source %` does not work?

**Comment by LostNeophyte** [comment]
if you had just that in your config it probably would've worked, but editing the lvim global does nothing, and if you're calling setup of different plugins that can break stuff, hot reloading isn't supported in neovim
