### ISSUE TITLE
Broken Installation

### ISSUE THREAD

**Issue by Lcarv20** [LunarVim/LunarVim#4445]
### Problem description

Hello there 
I have tried to run the install command as per the website instructions, but I am prompted with `unexpected argument '-u' found`.
I have tried to install both the stable and nightly version

### LunarVim version

1.3

### Neovim version (>= 0.9.1)

0.9.4

### Terminal name

Kitty, rio

### Operating system/version

MacOS Sonoma 14.2.1 (23C71)

### Steps to reproduce

1. run `LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)`

### Screenshots

<img width="1257" alt="Screenshot 2023-12-21 at 21 57 31" src="https://github.com/LunarVim/LunarVim/assets/42584819/818b3ddb-675f-40e8-8ab2-348b1a6a9e95">

**Comment by brneor** [comment]
Duplicate of #3612. You can find a workaround there.
