### ISSUE TITLE
Where is the `lvim` bin located on Windows 10?

### ISSUE THREAD

**Issue by Trotsz** [LunarVim/LunarVim#4453]
### Problem description

I installed it on Windows 10, but I cannot run lunarvim by typing "lvim" on Console.
I must add it to the Path in order to do that.
The problem is, I do not have any idea about its root directory location. And I didn't find anything related to that on the main website,

Can someone help me?

### LunarVim version

I don't know, because I don't know how to start lvim

### Neovim version (>= 0.9.1)

0.9.0

### Terminal name

Windows Powershell

### Operating system/version

Windows 10

**Comment by LostNeophyte** [comment]
the lvim script is here '$HOME\.local\bin\lvim.ps1'

**Comment by Trotsz** [comment]
@LostNeophyte Thank you so much dude. God bless
