### ISSUE TITLE
git bash installation on windows

### ISSUE THREAD

**Issue by verajosemanuel** [LunarVim/LunarVim#4454]
### Feature Description

allow installation in Git bash. For many of us it's the only available cli-tool in windows.
I have all dependencies installed but the install script discards this environent right at the beginning

Detecting platform for managing any additional neovim dependencies
OS MINGW64_NT-10.0-19042 is not currently supported.

### Describe the alternatives you have considered

WSL2 not available due to organizational restrictions.

**Comment by kylo252** [comment]
I'm not sure it's a good idea to try to support this, but feel free to comment this line in the installer to skip that check

https://github.com/LunarVim/LunarVim/blob/e85637c2408264f2591b9c9bca073cd58d314a97/utils/installer/install.sh#L132
