### ISSUE TITLE
Getting error: unknown flag `u' after installation

### ISSUE THREAD

**Issue by devholland** [LunarVim/LunarVim#4456]
### Problem description

I've installed `lvim` for the first time today using curl as described at https://www.lunarvim.org/docs/installation#release. After running the script, I'm getting `error: unknown flag 'u'` if I try to execute `~/.local/bin/lvim`.

Something doesn't work with the command `exec -a "$NVIM_APPNAME" nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"`, even though `nvim --help` lists the `-u` option as available for me.

```
$ bash -x lvim
+ export NVIM_APPNAME=lvim
+ NVIM_APPNAME=lvim
+ export LUNARVIM_RUNTIME_DIR=/home/userx/.local/share/lunarvim
+ LUNARVIM_RUNTIME_DIR=/home/userx/.local/share/lunarvim
+ export LUNARVIM_CONFIG_DIR=/home/userx/.config/lvim
+ LUNARVIM_CONFIG_DIR=/home/userx/.config/lvim
+ export LUNARVIM_CACHE_DIR=/home/userx/.cache/lvim
+ LUNARVIM_CACHE_DIR=/home/userx/.cache/lvim
+ export LUNARVIM_BASE_DIR=/home/userx/.local/share/lunarvim/lvim
+ LUNARVIM_BASE_DIR=/home/userx/.local/share/lunarvim/lvim
+ exec -a lvim nvim -u /home/userx/.local/share/lunarvim/lvim/init.lua
error: unknown flag `u'

$ nvim --version
NVIM v0.9.4
Build type: RelWithDebInfo
LuaJIT 2.1.1692716794

$ nvim -u
nvim: Argument missing after: "-u"
More info with "nvim -h"
```

### LunarVim version

release-1.3

### Neovim version (>= 0.9.1)

NVIM v0.9.4

### Terminal name

Windows Terminal

### Operating system/version

Ubuntu 23.04 (WSL2)

**Comment by DavidHoenisch** [comment]
Same on MacOS Sonoma 14.2.1. with nvim v0.9.5.

**Comment by DavidHoenisch** [comment]
> ### Problem description
> I've installed `lvim` for the first time today using curl as described at https://www.lunarvim.org/docs/installation#release. After running the script, I'm getting `error: unknown flag 'u'` if I try to execute `~/.local/bin/lvim`.
> 
> Something doesn't work with the command `exec -a "$NVIM_APPNAME" nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"`, even though `nvim --help` lists the `-u` option as available for me.
> 
> ```
> $ bash -x lvim
> + export NVIM_APPNAME=lvim
> + NVIM_APPNAME=lvim
> + export LUNARVIM_RUNTIME_DIR=/home/userx/.local/share/lunarvim
> + LUNARVIM_RUNTIME_DIR=/home/userx/.local/share/lunarvim
> + export LUNARVIM_CONFIG_DIR=/home/userx/.config/lvim
> + LUNARVIM_CONFIG_DIR=/home/userx/.config/lvim
> + export LUNARVIM_CACHE_DIR=/home/userx/.cache/lvim
> + LUNARVIM_CACHE_DIR=/home/userx/.cache/lvim
> + export LUNARVIM_BASE_DIR=/home/userx/.local/share/lunarvim/lvim
> + LUNARVIM_BASE_DIR=/home/userx/.local/share/lunarvim/lvim
> + exec -a lvim nvim -u /home/userx/.local/share/lunarvim/lvim/init.lua
> error: unknown flag `u'
> 
> $ nvim --version
> NVIM v0.9.4
> Build type: RelWithDebInfo
> LuaJIT 2.1.1692716794
> 
> $ nvim -u
> nvim: Argument missing after: "-u"
> More info with "nvim -h"
> ```
> 
> ### LunarVim version
> release-1.3
> 
> ### Neovim version (>= 0.9.1)
> NVIM v0.9.4
> 
> ### Terminal name
> Windows Terminal
> 
> ### Operating system/version
> Ubuntu 23.04 (WSL2)
> 
> ### Steps to reproduce
> _No response_
> 
> ### Screenshots
> _No response_

Looks like there is a workaround here https://github.com/LunarVim/LunarVim/issues/3612

**Comment by devholland** [comment]
> Looks like there is a workaround here #3612

Yes, thank you. That workaround solved my problem. 

I don't understand why that issue is closed though, since the problem still exists. I've used `bob` and `snap` to install nvim and both resulted in this error.

**Comment by harryhanYuhao** [comment]
> > Looks like there is a workaround here #3612
> 
> Yes, thank you. That workaround solved my problem.
> 
> I don't understand why that issue is closed though, since the problem still exists. I've used `bob` and `snap` to install nvim and both resulted in this error.

Please see this comment https://github.com/LunarVim/LunarVim/issues/3612#issuecomment-1780953183
which states it is probably a snap problem instead of lvim problem.

**Comment by devholland** [comment]
> > > Looks like there is a workaround here #3612
> > 
> > 
> > Yes, thank you. That workaround solved my problem.
> > I don't understand why that issue is closed though, since the problem still exists. I've used `bob` and `snap` to install nvim and both resulted in this error.
> 
> Please see this comment [#3612 (comment)](https://github.com/LunarVim/LunarVim/issues/3612#issuecomment-1780953183) which states it is probably a snap problem instead of lvim problem.

It definitively also happens when installing nvim via [bob](https://github.com/MordechaiHadad/bob), not only just snap. It seems like `exec` has problems with the `-a` option when using shims/softlinks.

**Comment by kylo252** [comment]
> It definitively also happens when installing nvim via [bob](https://github.com/MordechaiHadad/bob), not only just snap. It seems like exec has problems with the -a option when using shims/softlinks.

@devholland, not really sure how to fix this then (other than outright refusing to install if detecting such an installation path)

ideas are welcome!

**Comment by isaldarriaga** [comment]
neovim ppa for ubuntu does not look correct to me (outdated):
version `0.7.2-3`

See https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable

To double check use `lsb_release -a` to see the os version in wsl and manually add the sources that matches your os. Then sudo apt update + sudo apt install nvim (or neovim)

As alternative try installing latest nvim from sources.

**Comment by tf42src** [comment]
Same issue.

```
...
Creating desktop file
Preparing Lazy setup
error: unknown flag `u'
```

tried the "unstable" version from ubuntu 

```
NVIM v0.10.0
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```
