### ISSUE TITLE
Lunarvim crashing errors on the screen

### ISSUE THREAD

**Issue by juninhopo** [LunarVim/LunarVim#4458]
### Discussed in https://github.com/LunarVim/LunarVim/discussions/4457

<div type='discussions-op-text'>

<sup>Originally posted by **juninhopo** January  4, 2024</sup>
I came across a problem where it simply keeps blocking the errors, so I have to restart LUNARVIM for it to fix or change the errors.

![Screenshot 2024-01-04 at 16 54 11](https://github.com/LunarVim/LunarVim/assets/26558998/e01433db-b22f-4734-8c3e-6bc4a6bf0bd9)

Do you know anything about this, how can I fix this?</div>

**Comment by juninhopo** [comment]
I also saw that when you change the file name through explorer the file stays with the same name, then you need to close and open lvim.

**Comment by harryhanYuhao** [comment]
I am not sure what do you mean. pls provide more info.

The red warning came from lsp (language server protocol), stating that your code may have syntactic errors.

As to your second question, this is actually how vim works. In vim all the files are stored as vim buffers. When you delete the file the buffer still exists, and therefore will not be renamed.

**Comment by juninhopo** [comment]
@harryhanYuhao 

Got it, great to know about buffers. I will study more about this.

Regarding the error, after a while with Vim open, it stops the error, even though I resolve the error it remains there. Then I need to close and open Vim for the error to come out.
