### ISSUE TITLE
telescope vertical layout strategy breaks telescope header

### ISSUE THREAD

**Issue by dylan-chong** [LunarVim/LunarVim#4464]
### Problem description

with `lvim.builtin.telescope.defaults.layout_strategy = 'vertical'`

You can't see the top and bottom properly
![image](https://github.com/LunarVim/LunarVim/assets/17482349/817856eb-7984-4bf1-b239-8c6344d25d1c)

for contrast, this is without setting it
![image](https://github.com/LunarVim/LunarVim/assets/17482349/bdb3d94f-cf37-431b-bbe8-a3d578de3cd6)

### LunarVim version

master-e85637c2

### Neovim version (>= 0.9.1)

NVIM v0.10.0-dev-1495+g3d8f0cb69

### Terminal name

windows 11 wsl terminal

### Operating system/version

windows 11

### Steps to reproduce

1. set`lvim.builtin.telescope.defaults.layout_strategy = 'vertical'` in lua config
2. press `space f`

**Comment by lgeralds** [comment]
I had this problem. It went away with defined borderchars.

```
lvim.builtin.telescope.defaults.borderchars = {
  preview = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
  prompt = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
  results = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
}

```

**Comment by kylo252** [comment]
That's because you need to change the entire theme for this to work properly, and you should avoid that unless you want to change the default one.

Try this instead `:Telescope git_files theme=get_dropdown`

semi related: https://github.com/LunarVim/LunarVim/issues/2286

**Comment by dylan-chong** [comment]
thanks.
i put  `lvim.builtin.telescope.theme = nil` in my config and now the border chars work
