### ISSUE TITLE
File system ex command ( :Ex  [ explorer ] ) not working in Lvim.

### ISSUE THREAD

**Issue by KhodeNima** [LunarVim/LunarVim#4466]
### Problem description

**Greetings**
<br>

The `:Ex` ex command which stands for ( `Explorer` ) works without any branch of problems in `Nvim`, `Vim`, `Vi`, but it does not actually return to the file explorer tree in `Lvim`.

Is that command actually removed, or there are different commands and plugins for managing files in `LunarVim`?

### LunarVim version

master-b124e8c

### Neovim version (>= 0.9.1)

v0.9.5

### Terminal name

ZSH ( The Z shell )

### Operating system/version

debian_kali_linux_2023

### Steps to reproduce

1. `lvim [ directory_name ].
<br>

2. `Enter` on a file name.
<br>

3. `:Ex`.

**Comment by kylo252** [comment]
Try  `:NvimTreeOpen` (also mapped `<leader>e`)

There's an option in `nvim-tree` to disable Netrw, so double-check that as well in case you want to have both
https://github.com/LunarVim/LunarVim/blob/e85637c2408264f2591b9c9bca073cd58d314a97/lua/lvim/core/nvimtree.lua#L10
