### ISSUE TITLE
error: context_commentstring nvim-treesitter module is deprecated

### ISSUE THREAD

**Issue by harryhanYuhao** [LunarVim/LunarVim#4468]
### Problem description

Upon opening certain files and not others, this error is shown
```
context_commentstring nvim-treesitter module is deprecated, use require('ts_context_commentstring').setup {} and set vim.g.skip_ts_context_commen
tstring_module = true to speed up loading instead.
``` 

### LunarVim version

master-b124e8c

### Neovim version (>= 0.9.1)

v0.9.4

### Terminal name

alacritty

### Operating system/version

Fedora 

### Steps to reproduce

This error message does not seem to be consistent: sometimes it appears after I open a file sometimes not even if I open the same file.

**Comment by salimp2009** [comment]
Did some research and nvim-treesitter module is  depreceated and the link is here explaining how to mitigate
https://github.com/JoosepAlviste/nvim-ts-context-commentstring/issues/82#issuecomment-1817659634
