### ISSUE TITLE
Failed to execute child process "lvim": Failed to execve: No such file or directory

### ISSUE THREAD

**Issue by Android789515** [LunarVim/LunarVim#4469]
### Problem description

When I start lvim with the desktop file it is erroring.

I have no issues starting lvim with the desktop file using Xterm.

I have no issues starting lvim by running it in xfce4-terminal.

nvim -v

```
~ $: nvim -v
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
~ $: 

```

Finding it:
```
~ $: which lvim
/home/untitled1/.local/bin/lvim
~ $: stat "$(which lvim)"
  File: /home/untitled1/.local/bin/lvim
  Size: 491       	Blocks: 8          IO Block: 4096   regular file
Device: 259,5	Inode: 6840206     Links: 1
Access: (0744/-rwxr--r--)  Uid: ( 1000/untitled1)   Gid: ( 1000/untitled1)
Access: 2024-01-16 19:38:44.703775358 -0600
Modify: 2024-01-16 19:38:44.707775327 -0600
Change: 2024-01-16 19:38:44.708775320 -0600
 Birth: 2024-01-16 19:38:44.703775358 -0600
~ $: cat "$(which lvim)"
#!/usr/bin/env bash

export NVIM_APPNAME="${NVIM_APPNAME:-"lvim"}"

export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"/home/untitled1/.local/share/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"/home/untitled1/.config/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"/home/untitled1/.cache/lvim"}"

export LUNARVIM_BASE_DIR="${LUNARVIM_BASE_DIR:-"/home/untitled1/.local/share/lunarvim/lvim"}"

exec -a "$NVIM_APPNAME" nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
~ $: 

```

.profile
```
export PATH="~/.local/bin:$PATH"

export TERMINAL="xfce4-terminal"
export EDITOR="lvim"

```

### LunarVim version

master-e85637c

### Neovim version (>= 0.9.1)

NVIM v0.9.5

### Terminal name

xfce4-terminal

### Operating system/version

EndeavourOS

### Steps to reproduce

Unsure how reproducible this is.

1. Clone the repo.
2. Run the install script.
3. Opt in to missing dependencies.
4. Add the install folder to path.
5. Set default terminal in i3wm in .profile.
6. Reboot.
7. Comment TryExec line in the .desktop file to have it show in Rofi.
8. Run lvim from Rofi.

### Screenshots

![lvim Fail to start](https://github.com/LunarVim/LunarVim/assets/90219092/21286056-367a-40a5-9ba6-af350055fe6b)

**Comment by kylo252** [comment]
when did you last install the desktop file? it might be worth it re-executing `create_desktop_file()` from the installer, or at least [checking that `xdg-desktop-menu` works fine](https://wiki.archlinux.org/title/xdg-menu) for you.

https://github.com/LunarVim/LunarVim/blob/e85637c2408264f2591b9c9bca073cd58d314a97/utils/installer/install.sh#L455-L467

**Comment by Android789515** [comment]
I installed it on Tuesday and it did not show up in Rofi, so I had to comment out the TryExec line.

**Comment by Android789515** [comment]
> when did you last install the desktop file? it might be worth it re-executing `create_desktop_file()` from the installer, or at least [checking that `xdg-desktop-menu` works fine](https://wiki.archlinux.org/title/xdg-menu) for you.
> 
> https://github.com/LunarVim/LunarVim/blob/e85637c2408264f2591b9c9bca073cd58d314a97/utils/installer/install.sh#L455-L467

Looks like `xdg-desktop-menu` is working fine for me:

```
~ $: xdg-desktop-menu
   xdg-desktop-menu -- command line tool for (un)installing
   desktop menu items

Synopsis

   xdg-desktop-menu install [--noupdate] [--novendor] [--mode
   mode] directory-file(s) desktop-file(s)

   xdg-desktop-menu uninstall [--noupdate] [--mode mode]
   directory-file(s) desktop-file(s)

   xdg-desktop-menu forceupdate [--mode mode]

   xdg-desktop-menu { --help | --manual | --version }

Use 'man xdg-desktop-menu' or 'xdg-desktop-menu --manual' for additional info.
~ $: 

```

**Comment by Android789515** [comment]
👎

**Comment by kylo252** [comment]
did you resolve this? otherwise, it might a problem with your rofi'e config/environment.

**Comment by Android789515** [comment]
> did you resolve this? otherwise, it might a problem with your rofi'e config/environment.

I haven't been able to resolve this.
