### ISSUE TITLE
:tabmove commands do not work

### ISSUE THREAD

**Issue by benibilme** [LunarVim/LunarVim#4471]
### Problem description

I  would like to sort the tabs by myself. There are two options, sort by language and sort by directory for sorting tabs in `<leader>b`  menu which does not suit to me. I wanted to use the native `:tabmove` command.  

However `:+tabmove, :-tabmove, :3tabmove`  commads gives invalid range errors. `:tabmove` command does not give anything. 

The lunarvim does not comply with the documentation of [neovim documentation](https://neovim.io/doc/user/tabpage.html)

### LunarVim version

master-a45cfa59

### Neovim version (>= 0.9.1)

NVIM v0.9.4 

### Terminal name

kitty

### Operating system/version

arch linux 

### Steps to reproduce

1. create several tabs.
2. try to sort the tabs via `:+tabmove, :-tabmove` commands  as described at [neovim documentation](https://neovim.io/doc/user/tabpage.html)

**Comment by kylo252** [comment]
These are controlled by [bufferline.nvim](https://github.com/akinsho/bufferline.nvim),  try `:BufferLineMovePrev`.

**Comment by benibilme** [comment]
I have noticed closed issue #4047. I looked at the documentation of bufferline.vim. For sorting I have found section. Unfortunately I am just a user recently switched from vim to nvim, I do not think that I can handle this I do not know lua enough. Is there way to use native `:tabmove` commands?  


> SORTING					               *bufferline-sorting*

> Bufferline allows you to sort the visible buffers by `extension` or `directory`: >vim

>    " Using vim commands
````
    :BufferLineSortByExtension
    :BufferLineSortByDirectory
    :BufferLineSortByTabs
````
>    -- Or using lua functions
````
    :lua require'bufferline'.sort_by('extension')`
    :lua require'bufferline'.sort_by('directory')`
    :lua require'bufferline'.sort_by('tabs')`
````

>By default bufferline will sort by buffer number which is an integer value
provided by vim to identify a buffer that increases as new buffers are opened
this means that new buffers are placed at the end of the bufferline.

> For more advanced usage you can provide a custom compare function which will receive two buffers to compare. You can see what fields are available to use using lua

````
    sort_by = function(buffer_a, buffer_b)
        print(vim.inspect(buffer_a))
        -- add custom logic
        return buffer_a.modified > buffer_b.modified
    end
````
> When using a sorted bufferline it's advisable that you use the `BufferLineCycleNext` and `BufferLineCyclePrev` commands since these will traverse the bufferline bufferlist in order whereas `bnext` and `bprev` will cycle buffers according to the buffer numbers given by vim.

**Comment by benibilme** [comment]
> These are controlled by [bufferline.nvim](https://github.com/akinsho/bufferline.nvim), try `:BufferLineMovePrev`.

Sorry, possibly a race condition happened since I did not see your response while I was writing. Thanks.

**Comment by kylo252** [comment]
> Sorry, possibly a race condition happened since I did not see your response while I was writing. Thanks.

no worries, you can map them with neovim directly

```lua
  local opts = { noremap = true, silent = true }
  vim.keymap.set("n", "<leader>bJ", "<cmd>BufferLineMovePrev<cr>", opts)
  vim.keymap.set("n", "<leader>bK", require'bufferline'.move_to(1), opts) -- if you want to use the lua API
```

you can also add them to the default mappings table: `lvim.builtin.which_key.mappings["b"]`
