### ISSUE TITLE
ufo not working with LunarVim

### ISSUE THREAD

**Issue by lobneroO** [LunarVim/LunarVim#4476]
### Problem description

I have a somewhat fresh install of LunarVim and wanted to add some capabilities I need. One of them being (decent) code folding. 
For the [ufo plugin](https://github.com/kevinhwang91/nvim-ufo), I added the following to the bottom of my config.lua, which had worked for me when using [kickstarter](https://github.com/nvim-lua/kickstart.nvim/):
```
-- install plugin for code folding

return {
  "kevinhwang91/nvim-ufo",
  event = "BufRead",
  dependencies = { "kevinhwang91/promise-async" },
  config = function()
    -- default settings to enable
    vim.o.foldcolumn = "1"
    vim.o.foldlevel = 99
    vim.o.foldlevelstart = 99
    vim.o.foldenable = true

    -- setup folding source: first lsp, then indent as fallback
    require("ufo").setup({
	    provider_selector = function(bufnr, filetype, buftype)
  	    return { 'lsp', 'indent' }
     	end
   	})

     -- remap keys for "fold all" and "unfold all"
   	vim.keymap.set('n', 'zR', require('ufo').openAllFolds, { desc = "Open all folds" })
   	vim.keymap.set('n', 'zM', require('ufo').closeAllFolds, { desc = "Close all folds" })
  end,
}
```

Whenever I try coding fold, it tells me "No fold found". I have LSPs for lua, python, rust and c++ installed.

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.5

### Operating system/version

Arch Linux

### Affected language servers

all

### Steps to reproduce

1. Add the given ufo setup to your config.lua
2. Install language server for lua
3. open your config.lua in lvim
4. go to a folding line, press "z" then "a" for folding at the cursor
5. Note the error output

### Actual behavior

Error about no fold found

### Expected behavior

Code at cursor folds

:LspInfo
:LvimInfo

### support info

:LspInfo

```
Language client log: /home/tare/.local/state/lvim/lsp.log
Detected filetype: lua

1 client(s) attached to this buffer:

Client: lua_ls (id: 1, bufnr: [1])
  filetypes: lua
  autostart: true
  root directory: /home/tare/.config/nvim_kickstarter
  cmd: lua-language-server

Configured servers list: lua_ls
```

:LvimInfo

Copy paste doesn't work, I won't type all of this...

![image](https://github.com/LunarVim/LunarVim/assets/17877050/77161b94-625e-4f90-9629-be03cad3e795)

### logs

```console
log is empty
```

**Comment by rajesh-1252** [comment]
> ### Problem description
> 
> I have a somewhat fresh install of LunarVim and wanted to add some capabilities I need. One of them being (decent) code folding. For the [ufo plugin](https://github.com/kevinhwang91/nvim-ufo), I added the following to the bottom of my config.lua, which had worked for me when using [kickstarter](https://github.com/nvim-lua/kickstart.nvim/):
> 
> ```
> -- install plugin for code folding
> 
> return {
>   "kevinhwang91/nvim-ufo",
>   event = "BufRead",
>   dependencies = { "kevinhwang91/promise-async" },
>   config = function()
>     -- default settings to enable
>     vim.o.foldcolumn = "1"
>     vim.o.foldlevel = 99
>     vim.o.foldlevelstart = 99
>     vim.o.foldenable = true
> 
>     -- setup folding source: first lsp, then indent as fallback
>     require("ufo").setup({
> 	    provider_selector = function(bufnr, filetype, buftype)
>   	    return { 'lsp', 'indent' }
>      	end
>    	})
> 
>      -- remap keys for "fold all" and "unfold all"
>    	vim.keymap.set('n', 'zR', require('ufo').openAllFolds, { desc = "Open all folds" })
>    	vim.keymap.set('n', 'zM', require('ufo').closeAllFolds, { desc = "Close all folds" })
>   end,
> }
> ```
> 
> Whenever I try coding fold, it tells me "No fold found". I have LSPs for lua, python, rust and c++ installed.
> ### LunarVim version
> 
> release-1.3/neovim-0.9-d1c1bace
> ### Neovim version (>= 0.9.1)
> 
> NVIM v0.9.5
> ### Operating system/version
> 
> Arch Linux
> ### Affected language servers
> 
> all
> ### Steps to reproduce
> 
>     1. Add the given ufo setup to your config.lua
> 
>     2. Install language server for lua
> 
>     3. open your config.lua in lvim
> 
>     4. go to a folding line, press "z" then "a" for folding at the cursor
> 
>     5. Note the error output
> 
> 
> ### Actual behavior
> 
> Error about no fold found
> ### Expected behavior
> 
> Code at cursor folds
> 
> :LspInfo :LvimInfo
> ### support info
> 
> :LspInfo
> 
> ```
> Language client log: /home/tare/.local/state/lvim/lsp.log
> Detected filetype: lua
> 
> 1 client(s) attached to this buffer:
> 
> Client: lua_ls (id: 1, bufnr: [1])
>   filetypes: lua
>   autostart: true
>   root directory: /home/tare/.config/nvim_kickstarter
>   cmd: lua-language-server
> 
> Configured servers list: lua_ls
> ```
> 
> :LvimInfo
> 
> Copy paste doesn't work, I won't type all of this...
> 
> ![image](https://private-user-images.githubusercontent.com/17877050/298382066-77161b94-625e-4f90-9629-be03cad3e795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNjE2NjksIm5iZiI6MTcwOTM2MTM2OSwicGF0aCI6Ii8xNzg3NzA1MC8yOTgzODIwNjYtNzcxNjFiOTQtNjI1ZS00ZjkwLTk2MjktYmUwM2NhZDNlNzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDA2MzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjN2E5ZGM0NWI0MjA4OTIwOWY2NGYwYzBjZjU2MzNmYTBmYzM5MGNmNmUwMTgyYTQ1NWMzMTVlYmFlYTRjNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PrQ9G7XkUkpf2kkbt8DgrMj7zJqqbGuMHmcoNY0YJPA)
> ### logs
> 
> ```
> log is empty
> ```
> 
> ### Screenshots
> 
> _No response_


Did you Find any solution?

**Comment by lobneroO** [comment]
No sorry. I gave up on LunarVim and started NeoVim from scratch. I had opened a [bug report ](https://github.com/kevinhwang91/nvim-ufo/issues/186#event-11446219305) with the ufo creator about a different problem with kickstart nvim and eventually got a bug fix. Perhaps you will have better luck there.
