### ISSUE TITLE
Installing problem in arch

### ISSUE THREAD

**Issue by MRParag95** [LunarVim/LunarVim#4477]
### Problem description

unable to install getting this log:

`
Would you like to install LunarVim's Python dependencies: pynvim?
[y]es or [n]o (default: no) : Y
Verifying that pip is available..
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ensurepip/__init__.py", line 286, in _main
    return _bootstrap(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/ensurepip/__init__.py", line 202, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ensurepip/__init__.py", line 103, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmp0ricibn9/setuptools-65.5.0-py3-none-any.whl\', \'/tmp/tmp0ricibn9/pip-23.2.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmp0ricibn9\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
Installing with pip..
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

`

python installed: 3.11.6

### LunarVim version

nightly

### Neovim version (>= 0.9.1)

master

### Terminal name

kitty

### Operating system/version

Arch

**Comment by weiss-d** [comment]
Same on Manjaro with `Release` branch.
Installed `python-pynvim` with pacman, but the script still prompts to install it by itself.

**Comment by mfouesneau** [comment]
Alpine also throws the same error.

**Comment by romulomf** [comment]
Exactly the same issue here reported by @MRParag95 also on arch linux.

**Comment by 0xhenrique** [comment]
A workaround for this is to manually install the (so far only) python dependency, 'pynvim'. You can do so on Arch with the following command;
`sudo pacman -S python-pynvim`

Then install LunarVim again, selecting "no" for installing python dependencies.

**Comment by kylo252** [comment]
Yeah, we should probably remove that `pynvim` dependency, and tell the users they can install it themselves if they need it.
For now, you can select "no" when prompted by the installer.

**Comment by Sundhar22** [comment]
> ### Problem description
> 
> unable to install getting this log:
> 
> ` Would you like to install LunarVim's Python dependencies: pynvim? [y]es or [n]o (default: no) : Y Verifying that pip is available.. error: externally-managed-environment
> 
> × This environment is externally managed ╰─> To install Python packages system-wide, try 'pacman -S python-xyz', where xyz is the package you are trying to install.
> 
> ```
> If you wish to install a non-Arch-packaged Python package,
> create a virtual environment using 'python -m venv path/to/venv'.
> Then use path/to/venv/bin/python and path/to/venv/bin/pip.
> 
> If you wish to install a non-Arch packaged Python application,
> it may be easiest to use 'pipx install xyz', which will manage a
> virtual environment for you. Make sure you have python-pipx
> installed via pacman.
> ```
> 
> note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages. hint: See PEP 668 for the detailed specification. Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "/usr/lib/python3.11/ensurepip/**main**.py", line 5, in sys.exit(ensurepip._main()) ^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/ensurepip/**init**.py", line 286, in _main return _bootstrap( ^^^^^^^^^^^ File "/usr/lib/python3.11/ensurepip/**init**.py", line 202, in _bootstrap return _run_pip([*args, *_PACKAGE_NAMES], additional_paths) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/ensurepip/**init**.py", line 103, in _run_pip return subprocess.run(cmd, check=True).returncode ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/subprocess.py", line 571, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['/usr/bin/python3', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = ['/tmp/tmp0ricibn9/setuptools-65.5.0-py3-none-any.whl', '/tmp/tmp0ricibn9/pip-23.2.1-py3-none-any.whl'] + sys.path\nsys.argv[1:] = ['install', '--no-cache-dir', '--no-index', '--find-links', '/tmp/tmp0ricibn9', 'setuptools', 'pip']\nrunpy.run_module("pip", run_name="**main**", alter_sys=True)\n']' returned non-zero exit status 1. Installing with pip.. error: externally-managed-environment
> 
> × This environment is externally managed ╰─> To install Python packages system-wide, try 'pacman -S python-xyz', where xyz is the package you are trying to install.
> 
> ```
> If you wish to install a non-Arch-packaged Python package,
> create a virtual environment using 'python -m venv path/to/venv'.
> Then use path/to/venv/bin/python and path/to/venv/bin/pip.
> 
> If you wish to install a non-Arch packaged Python application,
> it may be easiest to use 'pipx install xyz', which will manage a
> virtual environment for you. Make sure you have python-pipx
> installed via pacman.
> ```
> 
> note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages. hint: See PEP 668 for the detailed specification.
> 
> `
> 
> python installed: 3.11.6
> ### LunarVim version
> 
> nightly
> ### Neovim version (>= 0.9.1)
> 
> master
> ### Terminal name
> 
> kitty
> ### Operating system/version
> 
> Arch
> ### Steps to reproduce
> 
> _No response_
> ### Screenshots
> 
> _No response_

yes i am facing this now
