### ISSUE TITLE
lunarvim cannot be used for java 11 project

### ISSUE THREAD

**Issue by yimingwangdell** [LunarVim/LunarVim#4479]
### Problem description

working company java project use this version bundle: java11 -> gradle **5**. which is very normal for a big project more than 5 years.
lunarvim default gradle version is **8** and not compatible with gradle 5 in my project.  latest jdtls requires java 17, java 17 is only compatible with gradle version >7.

finally java 11 project cannot be loaded by LSP in lunarvim. which it claimed it could.

### LunarVim version

any

### Neovim version (>= 0.9.1)

any

### Operating system/version

any

### Affected language servers

any

### Steps to reproduce

any

### Actual behavior

java 11 is claimed supported but actually not.

### Expected behavior

make java 11 project is supported in lunarvim.

### support info

//

**Comment by yimingwangdell** [comment]
it alway download wrong gradle version even if the gradle version in my project is clearly version 5.

**Comment by brneor** [comment]
As you correctly stated, [jdtls](https://github.com/mfussenegger/nvim-jdtls) only requires Java > 17. Looks like it's not a Lunarvim's issue.
