### ISSUE TITLE
emmet-ls not working on php files

### ISSUE THREAD

**Issue by Tyson453** [LunarVim/LunarVim#4480]
### Problem description

I'm having trouble getting emmet-ls to run on my php files. I made an [issue](https://github.com/aca/emmet-ls/issues/73) on emmet-ls's github but it looks like they don't respond to issues often so I'm posting here to see if I can get help or redirection. Please go to the issue linked for more information

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.4

### Operating system/version

macOS Sonoma 14.3

### Affected language servers

emmet-ls

### Steps to reproduce

1. Open a php file
2. Run :LspInfo
3. emmet_ls is under "active client(s) not attached to this buffer"

### Actual behavior

emmet_ls is not attached to the buffer and I'm not getting any LSP suggestions for emmet_ls

### Expected behavior

I expect to have the same LSP suggestions that I would have in an html file

### support info

:LspInfo
![Screenshot 2024-01-24 at 9 23 42 AM](https://github.com/LunarVim/LunarVim/assets/95186148/276eb827-da69-43d9-81c6-4ee7688d1898)

:LvimInfo
![Screenshot 2024-01-24 at 9 24 03 AM](https://github.com/LunarVim/LunarVim/assets/95186148/21c82363-c24e-4379-a34b-b52c16339ac0)

**Comment by olrtg** [comment]
It seems like you were able to solve this (https://github.com/aca/emmet-ls/issues/73). Can we close this?
