### ISSUE TITLE
Document translation errors

### ISSUE THREAD

**Issue by edte** [LunarVim/LunarVim#4481]
### Problem description

raw

<img width="1340" alt="截屏2024-01-26 17 19 11" src="https://github.com/LunarVim/LunarVim/assets/50194671/4bc4a0a4-7a44-4c60-89a7-05829e8b1788">

translate

<img width="1400" alt="截屏2024-01-26 17 20 41" src="https://github.com/LunarVim/LunarVim/assets/50194671/55b5ac5c-a9bd-4865-afdb-854f18071e4b">

### LunarVim version

null

### Neovim version (>= 0.9.1)

null

### Terminal name

null

### Operating system/version

null

**Comment by lopezac** [comment]
This is solved in [master version](https://www.lunarvim.org/zh-Hans/docs/master/configuration/language-features/custom-snippets#lua%E7%89%88%E6%9C%AC), so in the next docs release 1.4 this will be solved.
It was solved in this [pull request](https://github.com/LunarVim/lunarvim.org/commit/5ead242a1ae4440f862964d11c9648c130e3d59e).
So I think this issue should be closed.
