### ISSUE TITLE
Lunarvim can't find a c++ include that is created within the project

### ISSUE THREAD

**Issue by stefanaerospace** [LunarVim/LunarVim#4484]
### Problem description

Trying to make a "portable" code base that leverages CMake's FetchContent so dependencies are built within the project. Code builds and runs, but Lunarvim highlights an include that it should be able to easily find.

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.4

### Terminal name

bash

### Operating system/version

Pop!_OS 22.04 LTS

### Steps to reproduce

Issues that I have already looked at for help:
https://github.com/LunarVim/LunarVim/issues/2896
https://github.com/LunarVim/LunarVim/issues/4381

CMake version 3.22.1

My config.lua:
lvim.keys.normal_mode["<C-s>"] = ":w<cr>" -- faster than :w , the <cr> is probably carriage return, basically "Enter", override doesn't work w/o it
lvim.keys.normal_mode["<C-[>"] = ":bprev<cr>" -- Effectively C-( to go to left tab
lvim.keys.normal_mode["<C-]>"] = ":bnext<cr>" -- Effectively C-( to go to left tab
lvim.keys.insert_mode["jj"] = "<Esc>" -- I don't like reaching
lvim.builtin.treesitter.ensure_installed = {"python", "cpp", "c", "bash"} -- languages to check
lvim.builtin.treesitter.highlight.enable = true -- syntax check (I think)
vim.opt.clipboard = "unnamedplus" -- system clipboard access

To reproduce the problem: 
Clone my Git project:
https://gitlab.com/Saero/scientific-coding.git

Commit hash:
273cd7967d08b2b3f953107acde231a524244613

Navigate to project root in the terminal: 
Run ./compile.sh
This will build successfully.
You will find a compile_commands.json in CMake/
However when you open src/fastImageProcessing.cpp you will see the following:
   3 #include <matplot/matplot.h>     ■ 'matplot/matplot.h' file not found

How do I get lunarvim to find this header file in CMake/_deps/matplotplusplus-src/source/matplot/matplot.h ?

**Comment by kristiansordal** [comment]
Shot in the dark, but have you tried `ln -s CmakeFiles/compile_commands.json compile_commands.json` from the root directory? In my experience `compile_commands.json` should be linked to the root of the project.

**Comment by stefanaerospace** [comment]
Good question. Let me try this weekend.

**Comment by hitoyaCute** [comment]
@stefanaerospace hello there, furture developer here :D

have you fixed the issue can you share how you managed to fix it

**Comment by stefanaerospace** [comment]
It's been so long I can't recall.

But looking at it, it seems like the solution is to update the PATH environment variables in my Linux environment.

**Comment by hitoyaCute** [comment]
i managed to fixed mine by using older cmake not sure how it works but it works.... ill not touch it again lol
