### ISSUE TITLE
Install without user prompt.

### ISSUE THREAD

**Issue by thisismygitrepo** [LunarVim/LunarVim#4489]
### Problem description

I'm building a docker image and I need to install without user prompts.

Currently following this `LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)
`
Thanks,

### LunarVim version

latest

### Neovim version (>= 0.9.1)

0.95

### Terminal name

wezterm

### Operating system/version

all

**Comment by gyanantaran** [comment]
Interesting...
