### ISSUE TITLE
git blame popup remain the same and won't quit

### ISSUE THREAD

**Issue by arglin** [LunarVim/LunarVim#4491]
### Problem description

git blame popup remain the same and won't quit

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1703358377

### Terminal name

iTerm2

### Operating system/version

macOS 14.2.1 (23C71)

### Steps to reproduce

1. <leader>gl to check the git blame
2. the git blame popup wont close even I close the file

**Comment by MDSADABWASIM** [comment]
@arglin I have the same terminal and OS as you.

To see git blame the keybinding is: <leader>gl

And git blame popup hides as soon as I press any navigation key (h,j,k,l)

**Comment by MDSADABWASIM** [comment]
for me <leader>gl opens the git blame popup and C-j doesn't focus on the git blame popup.
