### ISSUE TITLE
Support path for lldb-vscode executable from PATH variable

### ISSUE THREAD

**Issue by gracicot** [LunarVim/LunarVim#4492]
### Problem description

When I try to debug my C++ project (using `<leader>ds`), I get this error:

    ...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:1420: Error running /usr/bin/lldb-vscode: ENOENT: no such file or directory
    stack traceback:
    ^I[C]: in function 'error'
    ^I...lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/session.lua:1420: in function 'spawn'
    ^I...l/share/lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap.lua:1041: in function 'launch'
    ^I...l/share/lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap.lua:373: in function 'run_adapter'
    ^I...l/share/lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap.lua:408: in function 'maybe_enrich_config_and_run'
    ^I...l/share/lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap.lua:504: in function <...l/share/lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap.lua:488>
    ^I[C]: in function 'xpcall'
    ^I...e/lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/async.lua:12: in function <...e/lunarvim/site/pack/lazy/opt/nvim-dap/lua/dap/async.lua:11>
    Press ENTER or type command to continue

I don't have an executable `/usr/bin/lldb-vscode`, but I do have `lldb-vscode` in my path:

    ❯ lldb-vscode
    Content-Length: 205

    {"body":{"category":"stderr","output":"Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nModuleNotFoundError: No module named 'lldb'\n"},"event":"output","seq":0,"type":"event"}

### LunarVim version

master-e85637c2

### Neovim version (>= 0.9.1)

NVIM v0.9.4

### Terminal name

iTerm2

### Operating system/version

macOS 14.2 (23C64)

### Steps to reproduce

1. Install lldb-vscode using a package manager like brew, nix, macports etc with the llvm distribution. The problem arise if the package manager don't copy/link to `/usr/bin`
2. Run the debugger in vim, default binding is `<leader>ds`
3. Observe vim trying to call a fixes absolute path `/usr/bin/lldb-vscode` instead of the `lldb-vscode` in `PATH`

**Comment by gracicot** [comment]
Well, I'm still affected by the issue. No one addressed it yet and I'm still looking for workarounds.

**Comment by juicy-g** [comment]
Can you post your DAP config? You may need to provide the path of the debugger to your adapter since it's installed externally (not through Mason).

**Comment by gracicot** [comment]
@juicy-g I'm just using the default lunarvim config. I haven't seen documentation how to change lunarvim's config for DAP.

**Comment by juicy-g** [comment]
Lunarvim doesn't configure the debug adapter for you. I have never used C++, but this is what I would try in my `config.lua`:

```lua
lvim.builtin.dap.on_config_done = function(dap)
 dap.adapters.lldb = {
    type = 'executable',
    command = 'lldb-vscode', -- absolute path to lldb-vscode here
    name = 'lldb'
  }

  dap.configurations.cpp = {
    {
      name = 'Launch',
      type = 'lldb',
      request = 'launch',
      program = function()
        return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
      args = {},
    },
  }
end
```
See this page for more information on how to configure DAP and the adapter: [https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#ccrust-via-lldb-vscode](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#ccrust-via-lldb-vscode)

**Comment by relief-melone** [comment]
same issue. I am using nixos and I remember my setup to have been working in the past (still not counting out I messed up something unnoticed along the way). My config looks more or less exactly the same ;) guess we found it in the same spot

**Comment by juicy-g** [comment]
I found that `lldb-vscode` was renamed to `lldb-dap` a few months ago: [https://discourse.llvm.org/t/rfc-rename-lldb-vscode-to-lldb-dap/74075](https://discourse.llvm.org/t/rfc-rename-lldb-vscode-to-lldb-dap/74075).
