### ISSUE TITLE
nvim-treesitter-context error

### ISSUE THREAD

**Issue by AhmedLilah** [LunarVim/LunarVim#4496]
### Problem description

I added these lines to my lunar vim config.lua file

```lua
lvim.plugins = {
        {
                "nvim-treesitter/nvim-treesitter-context",
        },
}
```

and I got this error that when i open a file and start to move in it
```
Error detected while processing CursorMoved Autocommands for "*":
Unable to load context query for cpp:
...s/Neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 301 for language cpp
```

### LunarVim version

release-1.3/neovim-0.9-d1c1bac

### Neovim version (>= 0.9.1)

NVIM v0.9.5

### Terminal name

Windows Terminal, powershell

### Operating system/version

windows 10

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/67424460/1503c10b-c606-4a75-b1cf-1497c2cc5be7)

**Comment by CrazyCatZhang** [comment]
<img width="1690" alt="image" src="https://github.com/LunarVim/LunarVim/assets/67346540/58fd27b7-ca7a-48dc-9d82-4327bfa41850">

**Comment by kylo252** [comment]
works fine for me on master with Neovim v0.10.0, let me know if you still encounter any issues.
