### ISSUE TITLE
Some LSP clients (markdownlint, mdx-analyzer) are not attached to the buffer

### ISSUE THREAD

**Issue by lightbluepoppy** [LunarVim/LunarVim#4503]
## Summary

markdownlint and mdx-analyzer, both LSPs and installed via Mason, does not start. Whereas gopls and tailwindcss lsp does start without configuration, and emmet_ls needed `require("lvim.lsp.manager").setup("emmet_ls")` in the config file to start.

Therefore,
- How can I make the LSP clients in the title detect the filetype of the file in the current buffer and start automatically without any configuration? 

I have some questions too that possibly be helpful to debug this.
- Why emmet_ls does not start without setup() function?
- Why gopls and tailwindcss lsp does start without configs, and some don't?

### LunarVim version

release-1.3

### Neovim version (>= 0.9.1)

neovim-0.9-d1c1bace-dirty

### Operating system/version

macOS 14.1.1

### Affected language servers

markdownlint, mdx-analyzer, emmet_ls

### Steps to reproduce

1. Install gopls, emmet_ls, and mdx-analyzer.
2. `touch test.go test.ts test.mdx` 
3. As for `test.mdx`, run `:setfiletype mdx` and `:LspRestart`
4. See only gopls is running in `test.go`, now add the following to the config

```lua
require("lvim.lsp.manager").setup("emmet_ls")
require("lvim.lsp.manager").setup("mdx-analyzer")
```

5. See emmet_ls is listed in "Configured servers list" in LspInfo now but mdx-analyzer isn't

### Actual behavior

markdownlint and mdx-analyzer does not start.

### Expected behavior

All the LSP clients detect the filetype of the file in the current buffer, attached to the buffer, and activated without any configuration.

### support info

There is not a single `mdx` string in lsp.log

### logs

```console
[WARN][2024-02-17 02:40:46] ...lsp/handlers.lua:137	"The language server emmet_ls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

**Comment by lightbluepoppy** [comment]
There was a bug for Lazy.nvim where the version of nvim-lspconfig was fixed to the one from April last year, therefore it did not have the latest server_configurations that included mdx_analyzer. I forcefully deleted and cloned nvim-lspconfig (or `git checkout master` might have been valid as well). This is a bug of Lazy.nvim I guess.

**Comment by Nosterx** [comment]
@lightbluepoppy Many thanks for sharing this! Saved me alot of time debugging problem with typos-lsp.
