### ISSUE TITLE
Adding inlay_hints since neovim 0.10+ supports it 

### ISSUE THREAD

**Issue by salimp2009** [LunarVim/LunarVim#4509]
### Feature Description

Hi 
Since inlay_hints is supported by neovim 0.10.+ there should be inlay_hints, toogle and enable/disable inlay_hints .
maybe something like this can be added to on_attach function
```lua
if client.supports_method "textDocument/inlayHint" then
    vim.lsp.inlay_hint.enable(bufnr, true)
  end
 ```
 Also a custom function to toogle it can be added to which_key lsp menu and a way to enable/disable using lvim builtins or lvim.lsp.inlay_hints.enable = true/false for users to easily set it
 ```lua
 M.toggle_inlay_hints = function()
  local bufnr = vim.api.nvim_get_current_buf()
  vim.lsp.inlay_hint.enable(bufnr, not vim.lsp.inlay_hint.is_enabled(bufnr))
end
```

**Comment by VincentVonPark** [comment]
Sorry to ask of you, could you guide me full content you wrote into where / what files in detail?
Because I added these in config.lua in Lunarvim, but failed to start...

**Comment by salimp2009** [comment]
I believe it should be in common_on_attach function on line 63 some where within that function. 
https://github.com/LunarVim/LunarVim/blob/9ee3b7b8846d7ed2fa79f03d67083f8b95c897f2/lua/lvim/lsp/init.lua#L63

Similar what is in Launch.nvim
https://github.com/LunarVim/Launch.nvim/blob/master/lua/user/lspconfig.lua#L22

**Comment by salimp2009** [comment]
just keeping it alive :)

**Comment by kylo252** [comment]
We can take a vote whether this should be opt-in or not, since not all the servers have useful info to display, but it's definitely a nice feature!

**Comment by salimp2009** [comment]
> We can take a vote whether this should be opt-in or not, since not all the servers have useful info to display, but it's definitely a nice feature!

at least we need to give an option to user to enable or disable. But if we dont have it in lvim source , the user will not have that option unless they tweak the lvim code.

**Comment by salimp2009** [comment]
it is very sad this is closed. Because that means we will be lacking a feature that neovim provides.

**Comment by hadnet** [comment]
Why can’t we have this feature??

**Comment by peterwilli** [comment]
Just for those that came here after a simple search. I just added `vim.lsp.inlay_hint.enable(true)` to ~/.config/lvim/config.lua and it worked flawlessly!

In addition, make sure that your LSP enables it too.

For example, for Rust, type `:LspSettings rust_analyzer` then add and save the appropiate JSON:

```json
{
    "rust-analyzer.diagnostics.enable": true
    "rust-analyzer.inlayHints.typeHints.enable": true
    "rust-analyzer.inlayHints.expressionAdjustmentHints.enable": "always"
    "rust-analyzer.inlayHints.renderColons": true
}
```

Having no inlay hints is a deal-breaker for me, and I was about to actually move to another distro after finding zero ways to do it, then I thought "f*** it i have nothing to lose now" and Occams Razor'ed it, and well, it worked!

<img width="783" height="257" alt="Image" src="https://github.com/user-attachments/assets/7ebb82f1-314b-422a-b634-50894259b234" />
