### ISSUE TITLE
Importing in config.lua

### ISSUE THREAD

**Issue by palandovalex** [LunarVim/LunarVim#4513]
### Problem description

config dir
`/home/user/.config/lvim/`

inside

```
config.lua

plug-configs/dap.lua

```
e.t.c.
In config.lua i try to require module by

`require 'plug-configs.dap'`

- lvim cant find module.

### LunarVim version

master-9ee3b7b8

### Neovim version (>= 0.9.1)

NVIM v0.10.0-dev

### Terminal name

Terminator

### Operating system/version

Linux mint  21.04.1, kernel - 6.5

**Comment by palandovalex** [comment]
some thing strange is hapening - 

when i use require inside my config.lua

Relative path will try to use cwd, or other modules path.
To forse use  path, that relatives to config.lua - i used this:

local function script_path()
   local str = debug.getinfo(2, "S").source:sub(2)
   return str:match("(.*/)")
end
local file_root = script_path() ---lib.abspath(".")

package.path = package.path .. ";" .. file_root .. "/?.lua"

this solution is realy, REALY weard. Byt i dont now, how do it RIGHTLY.

If you now - please give me feedback

**Comment by palandovalex** [comment]
Also i forsed to remove my custom modification of package.path, to prevent breaking plugins, or all other lua scripts, that runs in this project.

**Comment by LostNeophyte** [comment]
the path should be `lua/plug-configs/dap.lua`, see  `:h lua-package-path`
