### ISSUE TITLE
Failed to source nvim-treesitter

### ISSUE THREAD

**Issue by xeluior** [LunarVim/LunarVim#4515]
### Problem description

Unsure the cause, but running lunarvim always presents this error (https://pastebin.com/ZniNRfwX) at startup and treesitter is unavailable.

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

v0.10.0-dev-1770+gf64e4b43e

### Terminal name

alacritty

### Operating system/version

OpenSUSE Leap 15.5

### Steps to reproduce

Unsure. The error appears on all files I open (as in `lvim <filename>`). Running without a filename does not cause the error immediately, but it does open a scratch buffer in place of the dashboard and the error appears on entering insert or trying to run any of the `:TS` commands.

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/44057501/d4d2a441-b8a3-4f93-8493-c99dbc6ae30a)

**Comment by salimp2009** [comment]
your neovim version 0.10+ is too new for lvim 1.3
you should use neovim 0.9.+ for lvim 1.3
for neovim 0.10+ you should use lvim nightly.
This issue can be closed.
