### ISSUE TITLE
Change vue default lsp

### ISSUE THREAD

**Issue by haug1** [LunarVim/LunarVim#4517]
If I'm not mistaken, `volar` is now the preferred LSP to use. It changed with major version 3.
https://github.com/LunarVim/LunarVim/blob/9ee3b7b8846d7ed2fa79f03d67083f8b95c897f2/lua/lvim/lsp/config.lua#L64

**Comment by olrtg** [comment]
I think that table is used to say "I don't want you to configure these LSPs automatically using the defaults, let the user set it up by himself". But I'm not a maintainer of the project so take it with a grain of salt.

**Comment by Noxdor** [comment]
According to the [LunarVim Docs](https://www.lunarvim.org/docs/features/supported-frameworks/vue) `vuels` is indeed the default and @haug1 is correct that `volar` is the recommended LSP to use since vue 3. I would also appreciate the suggested change.

**Comment by Noxdor** [comment]
@olrtg Actually true, I just realised that too, but the documentation is not up to date then.
