### ISSUE TITLE
Can we document the tab/buffer thing?

### ISSUE THREAD

**Issue by githorse** [LunarVim/LunarVim#4519]
### Problem description

<img width="372" alt="image" src="https://github.com/LunarVim/LunarVim/assets/8271372/a2e33acb-74cc-4a3c-86f6-2332c96471c8">

These look a lot like tabs. But -- surprise! -- [they are buffers](https://github.com/LunarVim/LunarVim/discussions/3529). As a Vim veteran, I don't even know what's going on here ... ok, looks like it's the [bufferline](https://github.com/akinsho/bufferline.nvim) plugin, which I hadn't previously heard of. But whether veteran or newbie, I would expect the tab navigation commands (`gt`, `gT`) to work on these, but they don't seem to do anything.

I won't open up here the debate/confusion about Vim [buffers vs. tabs](https://stackoverflow.com/questions/26708822/why-do-vim-experts-prefer-buffers-over-tabs), or whether bufferline is a good idea or not. (I'll be turning it off, myself.) But having read through all the docs, I don't see anything about this. Could we add some documentation to make it clear what's going on here, and how I should switch tabs/buffers? (And maybe add some default keyboard shortcuts for it?)

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

0.9.5

### Terminal name

Terminal (macOS)

### Operating system/version

macOS 14.2 (23C64)

**Comment by chase** [comment]
The docs are largely unmaintained, but you can contribute here: https://github.com/LunarVim/lunarvim.org/blob/master/docs/beginners-guide/keybinds-overview.md

**Comment by erichlf** [comment]
I was surprised by this too. In the end use BufferLine* commands and then whatever they are, (they can be tabs or be m buffers as it is configurable) won't matter.
