### ISSUE TITLE
Can't overwrite a `whichkey` subkey

### ISSUE THREAD

**Issue by githorse** [LunarVim/LunarVim#4520]
### Problem description

I want to change just one value in a submenu from the default `whichkey` menu (`<leader>gl`). Is there any way to do that? I can add a new submenu binding [like this](https://www.lunarvim.org/docs/configuration/keybindings#removing-a-single-mapping):

```
lvim.builtin.which_key.mappings["tP"] = {
  "<cmd>lua require'telescope'.extensions.project.project{}<CR>", "Projects"
}
```
 
But that doesn't work when the binding already exists. (It *does* work as expected when adding a root-level binding, just not for a nested one). Ideally, I would expect bindings I specify explicitly in my config to overwrite the default ones.

Is there a way to overwrite a submenu binding without [specifying the entire submenu](https://www.lunarvim.org/docs/configuration/keybindings#submenu-mapping)?

See [docs](https://www.lunarvim.org/docs/configuration/keybindings#removing-a-single-mapping).

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

0.9.5

### Terminal name

Terminal (macOS)

### Operating system/version

macOS 14.2 (23C64)

**Comment by ziraqyoung** [comment]
Have you tried?

```
lvim.builtin.which_key.mappings["t"]["P"] = {
  "<cmd>lua require'telescope'.extensions.project.project{}<CR>", "Projects"
}
```

As an example,  I have this in my config and seems to work for me

```
lvim.builtin.which_key.mappings["l"]["f"] = {
  "<cmd>lua require('conform').format({ async = true, lsp_fallback = true })<CR>",
  "LSP format",
}
```

**Comment by githorse** [comment]
Ok, I'm unable to reproduce whatever problem I was having before. It seems both `["tP"]` syntax and `["t"]["P"]` work fine here and successfully overwrite or add a subkey. Closing the issue.
