### ISSUE TITLE
Opening the dl_malloc. c file with lunarvim is very slow

### ISSUE THREAD

**Issue by starifly** [LunarVim/LunarVim#4525]
### Problem description

Opening the https://github.com/kamailio/kamailio/blob/5.3/src/core/mem/dl_malloc.c file with lunarvim is very slow, and moving the cursor after opening is also very slow.

### LunarVim version

release-1.3

### Neovim version (>= 0.9.1)

NVIM v0.9.5

### Terminal name

Wezterm

### Operating system/version

Ubuntu22.04

**Comment by chase** [comment]
This is more than likely caused by bad defaults for clangd.

You can potentially fix it by referencing https://github.com/abzcoding/lvim

**Comment by starifly** [comment]
> This is more than likely caused by bad defaults for clangd.
> 
> You can potentially fix it by referencing https://github.com/abzcoding/lvim

I use this configuration, but after moving the cursor a certain distance, it still gets very slow and gets stuck

**Comment by starifly** [comment]
I found that it is affected by this configuration:
https://github.com/LunarVim/LunarVim/blob/master/lua/lvim/config/settings.lua#L48
