### ISSUE TITLE
Could someone please update the list of core plugins ?  

### ISSUE THREAD

**Issue by samuel-cavalcanti** [LunarVim/LunarVim#4528]
### Problem description

null-ls was deprecated #4289  and now LunarVim uses none-ls.
However, [the core plugins list](https://www.lunarvim.org/docs/features/core-plugins-list ) haven't been updated.
Please change  [jose-elias-alvarez/null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim) to [nvimtools/none-ls.nvim/](https://github.com/nvimtools/none-ls.nvim/)

### LunarVim version

1.3 and master

### Neovim version (>= 0.9.1)

whatever 

### Terminal name

any

### Operating system/version

any

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/24573157/29d7c912-3bb8-4e6b-a65b-5f1f3231760e)

**Comment by vonPB** [comment]
Closed in https://github.com/LunarVim/lunarvim.org/pull/453, thank you
