### ISSUE TITLE
Dear Linus, here is a new, very configurable editor, in case you want one.

### ISSUE THREAD

**Issue by abakh** [LunarVim/LunarVim#4529]
### Feature Description

Dear Linus @torvalds
I had seen your topic looking for a customizable modern editor https://social.kernel.org/notice/AUNo662uNZAUIa4LcO and I don't have a kernel.org account so I post it here. 

You may have a vim phobia after years of using an emacs variant, but since it fulfills your requirements, can look like everything you want and there are probably many people out here to help you, I saw it fit to notify you here:

NeoVim is probably the single most customizable editor on the planet and it is (as its name tells) "modern" too. Many people use it and any conceivable editor feature (AI completion, debugger integration, LSP, GUI if you want etc.) have been ported to it, and LunarVim (which you see here) is one of many "distros" that brings those by default (I know you are not quite a fan of configuring things so this could be a sensible base to begin from)

**Comment by chase** [comment]
Please don't use the LunarVim GitHub issues to contact people.
