### ISSUE TITLE
line moving when enteringnormal mode 

### ISSUE THREAD

**Issue by amirreza8002** [LunarVim/LunarVim#4531]
### Problem description

when i hit Esc and enter normal mode
if i hit `j` excatly after that
if there is a line below the current one
the two lines switch places
but if i do anything before pressing `j` this won't happen

### LunarVim version

1.3

### Neovim version (>= 0.9.1)

0.9.5

### Terminal name

gnome terminal

### Operating system/version

linux openSUSE tumbleweed

### Steps to reproduce

```py
def this(x):
    print(2 + 2)
    print(3 + 3)
```

be on insert mode
go to line two
hit Esc
immediately hit j

**Comment by chase** [comment]
It's probably this default binding (which I don't like either): https://github.com/LunarVim/LunarVim/blob/master/lua/lvim/keymappings.lua#L62-L63

I accidentally hit it pretty frequently. You can see my keymap configuration for how to disable it if you'd like to try: https://github.com/chase/lvim/blob/main/lua/user/keymap.lua

**Comment by amirreza8002** [comment]
hi @chase, yes i had seen that before
the problem is i don't hit alt
this happens when you hit esc and hit j very fast, before the cursor turns to the block looking thin in normal mode

but once the cursor turns this doesn't happen
might not seem like a very big problem but kinda reduces my productivity

**Comment by chase** [comment]
If that's not the case, you can try `:nmap j` to view the keybindings that are set to `j` in Normal mode. If there's anything there that mentions lines, that's probably the culprit that you should unset.

**Comment by ladieman217** [comment]
same question here

**Comment by chase** [comment]
> same question here

LunarVim is no longer actively maintained

**Comment by amirreza-sf80** [comment]
> > same question here
> 
> LunarVim is no longer actively maintained

that's sad
even tho it breaks sometimes I really like it
