### ISSUE TITLE
LunarVim as MANPAGER -

### ISSUE THREAD

**Issue by JxJxxJxJ** [LunarVim/LunarVim#4532]
### Feature Description

I would like to use lunarvim as my MANPAGER in my shell config.

Currently, I've tried this with neovim and it works fine 
```shell
export MANPAGER='nvim +Man!+"set nocul" +"set noshowcmd" +"set noruler" +"set noshowmode" +"set laststatus=0" +"set showtabline=0" +"set nonumber"'
```
But if I replace `nvim` with `lvim` everything breaks.
```shell
man: exit status 1: sed -e '/^[[:space:]]*$/{ N; /^[[:space:]]*\n[[:space:]]*$/D; }' | LESS=-ix8RmPm Manual page man(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$PM Manual page man(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$ MAN_PN=man(1) lvim +Man!
```
An alternative would be just using Nvim, but I really like Lvim, the main point is to be able to have your own theme and plugins in the manpages

**Comment by juicy-g** [comment]
The first command with `lvim` works for me. What shell and terminal are you using?
