### ISSUE TITLE
Telescope theme / layouts are broken

### ISSUE THREAD

**Issue by githorse** [LunarVim/LunarVim#4534]
### Problem description

When I try to modify anything about the Telescope layout, the boxes are no longer correctly rendered. For instance, if I do this

```
lvim.builtin.telescope.pickers.find_files = {
  layout_strategy = "horizontal",
  layout_config = {
    width = 0.8
  }
}
```
 
I get this:

<img width="1440" alt="image" src="https://github.com/LunarVim/LunarVim/assets/8271372/de970322-1da3-43e7-bbad-08effc710c0a">

I can resolve the issue with:

```
lvim.builtin.telescope.theme = nil
```

as suggested in https://github.com/LunarVim/LunarVim/issues/4464, but I'm opening this new issue because that existing issue 1) specifies vertical layouts, when the problem is more general; and 2) is closed, even though the bug is not resolved in the latest Lvim.

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

0.9.5

### Terminal name

MacOS Terminal

### Operating system/version

MacOS

**Comment by Tobshub** [comment]
Hi, I got this same issue. I was able to fix it by adding the following to my config:
```lua
lvim.builtin.telescope.defaults.borderchars = {
	prompt = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
	results = { "─", "│", "─", "│", "╭", "╮", "┤", "├" },
	preview = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
}
```

**Comment by kylo252** [comment]
you should supply the entire theme instead

```lua
lvim.builtin.telescope.theme = "center" -- or any other supported theme like "ivy"
```
