### ISSUE TITLE
lsp.log grows insanely

### ISSUE THREAD

**Issue by stevenroose** [LunarVim/LunarVim#4537]
### Problem description

I just realize that my `~/.local/state/lvim/lsp.log` has grown to 250GiB as it was taking up over half of my `/home` partition.. This is definitely not good..

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.5

### Terminal name

alacritty

### Operating system/version

GuixSD

### Screenshots

![Uploading screenshot-2024-03-31--20-14-38.png…]()

**Comment by kylo252** [comment]
could you check which server is spamming the info? are you sure you're not running on debug by mistake?

```lua
vim.lsp.set_log_level("WARN") -- set :h set_log_level
```

**Comment by bgmonroe** [comment]
I've seen this happed with some language servers that act "odd."  Namely terraform-ls where it would, by default, send it's logs to stderr which would get captured as errors in the lsp.log file.  I had to change the lspconfig for terraform-ls to send its logs to its own file:
```
require("lspconfig").terraformls.setup {
    filetypes = { "terraform", },
    cmd = { 'terraform-ls', 'serve', '-log-file', vim.fs.dirname(require('vim.lsp.log').get_filename()) .. "/terraform-ls.log" },
}
```

Saying that, I think it would be a great feature request to add rolling the lsp.log file into LunarVim.

**Comment by kylo252** [comment]
>  I had to change the lspconfig for terraform-ls to send its logs to its own file

please consider upstreaming these changes to https://github.com/neovim/nvim-lspconfig/blob/b124ef3bd4435a6db7ff03ea2f5a23e1e0487552/lua/lspconfig/server_configurations/terraformls.lua

> Saying that, I think it would be a great feature request to add rolling the lsp.log file into LunarVim.

I was planning on adding that to neovim core at some point, but got sidetracked with something else.
