### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by fabioluciano** [LunarVim/LunarVim#4540]
This project is dead? 

There is any recommendation to orher "neovim distro"?

**Comment by LostNeophyte** [comment]
https://github.com/LunarVim/LunarVim/discussions/4518#discussioncomment-8963843

**Comment by fabioluciano** [comment]
Sooooo... Yes! Thank you!

**Comment by kylo252** [comment]
I'm working on updating all the plugins, starting with #4552 :)
