### ISSUE TITLE
Unable to guarantee data integrity while updating. Please run :LvimUpdate manually instead.

### ISSUE THREAD

**Issue by ajyxwDean** [LunarVim/LunarVim#4542]
### Feature Description

When I Install LunarVim, It Error.
![image](https://github.com/LunarVim/LunarVim/assets/110725838/64ca68f7-f044-4993-9f53-c4f8ab730ff5)

**Comment by kylo252** [comment]
Please run a clean install manually instead, it seems that you have modified your local repo at some point.
