### ISSUE TITLE
Icons are Broken

### ISSUE THREAD

**Issue by deedeedev** [LunarVim/LunarVim#4546]
### Problem description

Icons are broken. This is what I see:

![lunarvim-broken-icons](https://github.com/LunarVim/LunarVim/assets/4921463/432245ea-76d0-4c2d-9425-4ee6d2da20ab)

I installed various nerd fonts (JetBrains Mono, Sauce Code Pro, RobotoMono, Inconsoloata etc.), they are being displayed correctly by the terminal but icons in lunarvim are still missing. Nerd Fonts seem to be installed correctly, they show up both with `fc-list` and `kitty +list-fonts` commands and are displayed in the terminal. My shell is zsh. Any idea how to fix this?

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.5

### Terminal name

kitty 0.32.0

### Operating system/version

Ubuntu 22.04.4

### Steps to reproduce

1. install lunarvim with `LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)`
2. download NerdFonts from [here](https://www.nerdfonts.com/font-downloads) and extract them in `~/.fonts`
3. rebuild font cache with `fc-cache -f -v`
4. check that fonts are installed correctly with `fc-list | grep <font_name>`
5. set font in terminal config file: `~/.config/kitty/kitty.conf` and reload terminal configuration
6. open LunarVim

### Screenshots

![lunarvim-broken-icons-file](https://github.com/LunarVim/LunarVim/assets/4921463/fcc94c6e-c221-4288-83e4-c71b972f9dc5)

**Comment by deedeedev** [comment]
Ok I managed to solve the problem, it was just a kitty configuration issue. I just installed the standalone nerdfonts symbols font from [here](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/NerdFontsSymbolsOnly.zip) and added the following to the `kitty.conf` file:

```
symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d4,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b1,U+e700-U+e7c5,U+f000-U+f2e0,U+f300-U+f372,U+f400-U+f532,U+f0001-U+f1af0 Symbols Nerd Font Mono
```

[Here](https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font) is a detailed guide from the kitty docs.

**Comment by thederpykrafter** [comment]
I have a similar issue with the font of the dashboard header, but with the amount of missing symbols I just live with it for now
