### ISSUE TITLE
Using LunarVim as git editor on Windows

### ISSUE THREAD

**Issue by jkoehlerrelativity** [LunarVim/LunarVim#4550]
### Problem description

Is there a way to use LunarVim as the git commit-message editor in Windows/Powershell? I've tried:

- Setting core.editor to `lvim` (unable to start editor 'lvim')
- Setting core.editor to the full path to lvim.ps1 (lvim starts very slowly, gives E282: Cannot read from ":LUNARVIM_BASE_DIR\init.lua", does not load git commit template)
- Setting core.editor to the expanded-out nvim command found in lvim.ps1 (lvim starts very slowly, fails because other lvim environment variables aren't set)

### LunarVim version

release-1.3/neovim-0.9-d1c1bac

### Neovim version (>= 0.9.1)

NVIM v0.9.5

### Terminal name

Windows Terminal (Powershell 7.4.1)

### Operating system/version

Windows 11 23H2

**Comment by kylo252** [comment]
It is a bit finicky, but this should work most of the time

```powershell
git config --global core.editor "powershell.exe c:\\Users\\$env:USERNAME\\.local\\bin\\lvim.ps1"
```

check https://github.com/LunarVim/LunarVim/pull/1893#pullrequestreview-797458609 for other solutions
