### ISSUE TITLE
Crystalline (Crystal LSP) isn't doing anything

### ISSUE THREAD

**Issue by BigBoyBarney** [LunarVim/LunarVim#4553]
### Problem description

Hey guys!
I installed Crystalline with `:LspInstall crystal`, this part works.
`:LspInfo`
![image](https://github.com/LunarVim/LunarVim/assets/86712892/5e553e30-eeb6-48ba-aa01-21f19ae358a8)
`:LvimInfo`
![image](https://github.com/LunarVim/LunarVim/assets/86712892/8e1af86a-ffae-413d-8176-f97b43842543)
However, nothing really happens. I don't get highlighting or other LSP features like autocomplete etc.
![image](https://github.com/LunarVim/LunarVim/assets/86712892/d0c189dd-8987-4c1c-a6a9-66d86f32ca71)

Thanks a lot!!

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.5

### Operating system/version

Linux / Fedora 39

### Affected language servers

Crystalline

### Steps to reproduce

Install Crystalline with `:LspInstall crystal`.
Create a `test.cr` file. 
Write Crystal code.

### Actual behavior

Nothing happens

### Expected behavior

LSP works as intended, including code highlighting and auto-completion

### support info

See screenshots from the OP.

**Comment by juicy-g** [comment]
In LunarVim syntax highlighting is handled by `nvim-treesitter` which does not yet support the `crystal` filetype. The Crystalline README suggests to use the `vim-crystal` plugin.  

It looks like the server is configured and launched correctly, but autocompletion does not work with `nvim-lspconfig`. This might be an issue with Crystalline itself: elbywan/crystalline#89

**Comment by juicy-g** [comment]
Do you have a `shard.yml` or `.git` in your project root folder? If not, please try and comment if it changes anything or not.

**Comment by gptlang** [comment]
> Do you have a shard.yml or .git in your project root folder? If not, please try and comment if it changes anything or not.

Yes to both. Still doesn't work. I'll try `vim-crystal`
