### ISSUE TITLE
nvim tree fails to remove files from explorer when deleting

### ISSUE THREAD

**Issue by johnend** [LunarVim/LunarVim#4557]
### Problem description

When deleting a file from the nvim-tree with `d` the explorer window does not refresh, making it appear as the file still exists.

Short discussion on Discord with additional context: https://discord.com/channels/701530051140780102/704077577920446636/1237490293947760650

In most projects this works as expected. However, in a the node project I am working on the behaviour is as above.

I have made some changes to my config which you can see (here)[https://github.com/johnend/lunarvim] but I _think_ that nothing there should be affecting this.

The project I am working on is not public at this time, so I can't share it, but it's a node CLI tool. It is not installed, it's linked at the moment while I'm building it out (using `npm link`).

This is not the case with a minimal nvim setup (using suggested steps from nvim-tree's github docs), not does it fail to update with my basic WIP nvim config.

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.5

### Terminal name

Kitty

### Operating system/version

Linux 6.8.9-arch1-1

### Steps to reproduce

Unsure how to best provide steps outside of what I've outlined above.

1. LunarVim in nodejs project that is linked to global npm modules using `npm link`
2. Open LunarVim in project directory,
3. Create file in explorer using `a`,
4. Attempt to delete with `d`,
5. File is deleted on system,
6. Explorer window in nvim-tree inside LunarVim does not update.

**Comment by kylo252** [comment]
Please try switching to master branch instead while we create another release.

**Comment by starifly** [comment]
> Please try switching to master branch instead while we create another release.

When will the new version be released
