### ISSUE TITLE
dotfiles in a directory hidden

### ISSUE THREAD

**Issue by tylerthehaas** [LunarVim/LunarVim#4562]
### Problem description

do to any directory that contains files beginning in `.` and run `lvim .` that window will hide all dotfiles from the list of files to select.

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.5-release-2.1.1692716794

### Terminal name

kitty

### Operating system/version

MacOS 14.3

### Screenshots

<img width="360" alt="image" src="https://github.com/LunarVim/LunarVim/assets/11150235/e00a85e9-00cd-4dba-8a1c-bacfedce7bc3">

**Comment by juicy-g** [comment]
This is not a bug. What you're seeing is the [lir](https://github.com/tamago324/lir.nvim) file explorer. I assume you are doing `lvim .` to open lvim in the current directory. You can set the option to show hidden files by `lvim.builtin.lir.show_hidden_files = true` in your `config.lua`.
