### ISSUE TITLE
README Pandoc install

### ISSUE THREAD

**Issue by smikeblog** [LunarVim/LunarVim#541]
To avoid compilation install current binaries from github 
```  cd ~/Downloads
  mkdir pandot && cd pandot
  wget -A "gz" $((curl -s https://api.github.com/repos/jgm/pandoc/releases/latest | grep "browser_download_url" | grep "amd64.tar") | cut -d\: -f2,3 | jq -r )
  sudo tar xvzf *.gz --strip-components 1 -C /usr/local/bin
  cd 
  rm -rf ~/Downloads/pandot
```
Note: This is my cli procedure tio install on /usr/local/bin which can be local dir in the PATH var as example ~/.local/bin

**Comment by kylo252** [comment]
Closing since it's outdated. Please let me know if you still need help with this.
