### ISSUE TITLE
Freeze plugin state for stable releases

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#576]
For stable releases we should create a branch, freeze required plugins to a specific commit, then create a stable release.

**Comment by rebuilt** [comment]
This means requiring a specific version of neovim as well.

**Comment by ChristianChiarulli** [comment]
@rebuilt good point

**Comment by ChristianChiarulli** [comment]
there will forever be bugs if we don't pin these. I don't think neovim version will be that big of a deal.

**Comment by ChristianChiarulli** [comment]
I have an example in for nvimtree now.

**Comment by abzcoding** [comment]
duplicate of #1265
