### ISSUE TITLE
Lightning Network to accept donations

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#734]

**Comment by matthiasdebernardini** [comment]
Theres two main ways you could implement; 
1) custodial
2) non-custodial

My recommendation would be to start custodial, then if its working out move up to non custodial.

Best custodial option is IMO https://twitter.com/lntxbot?lang=en

You can use LNURL to receive donations to your telegram wallet, then upgrade to https://github.com/lightningnetwork/lnd

**Comment by abzcoding** [comment]
closed due to inactivity, feel free to reopen
