### ISSUE TITLE
[Feature]: Windows setup  

### ISSUE THREAD

**Issue by morphykuffour** [LunarVim/LunarVim#804]
### Feature motivation

Installing in windows would be nice

### Describe the expected solution

Can an installation for windows be added

**Comment by midnightexigent** [comment]
could be helpful to rewrite the installer in [batsh](https://github.com/batsh-dev-team/Batsh) ?

**Comment by TeoDev1611** [comment]
Could be install with Powershell script for example

**Comment by Dulanjala007** [comment]
Yeah, that would super helpful..
manual install is a cumbersome, most difficult part is to setup the binaries like Fzf, rg on windows
got it working on windows now, it's awesome..

**Comment by MarcSchaetz** [comment]
Hi guys,
I nailed a powershell script together for a windows installation. On my test setup it worked, but it is only tested with powershell (no good old cmd). 

I can create a merge request if you want

**Comment by jmahlik** [comment]
In this setup, have you considered lsp installs at all? Just came to find out `nvim-lspinstall` is quite broken on windows as it stands. Trying to hack something together to enable manual installs into `data/lspinstall` but still have `lspinstall` pick them up. Should just be a matter of changing some `/` and `\\` based on os. 

Still doesn't get around having to manual install though but it would be something.

**Comment by abzcoding** [comment]
> In this setup, have you considered lsp installs at all? Just came to find out `nvim-lspinstall` is quite broken on windows as it stands. Trying to hack something together to enable manual installs into `data/lspinstall` but still have `lspinstall` pick them up. Should just be a matter of changing some `/` and `\\` based on os.
> 
> Still doesn't get around having to manual install though but it would be something.
we might consider migrating to this ->
<img width="952" alt="Screen Shot 2021-09-10 at 12 10 53 PM" src="https://user-images.githubusercontent.com/10992695/132818295-67648f9a-3bbd-4632-8b64-99ec8fee3d12.png">

**Comment by TeoDev1611** [comment]
@abzcoding  yeah this plugin is amazing have a ui and some tools for support lsp

**Comment by LeonardoDaLuz** [comment]
> Could be install with Powershell script for example

not work.

**Comment by aniketgm** [comment]
@MarcSchaetz If possible can you please share the powershell script. A repo at your end would be fine I guess. If I or anyone who wishes to try it out can pick it up from there, untill we have some conclusion to this discussion on what and how to do it.

**Comment by kylo252** [comment]
@aniketgm, https://github.com/LunarVim/LunarVim/blob/9def60f1dd09ac2244672b8570092229977b43b4/utils/installer/install.ps1 already exists 😄
