### ISSUE TITLE
Add plugin_install.sh utility to install an individual plugin to lv-user-CONFIG

### ISSUE THREAD

**Issue by rebuilt** [LunarVim/LunarVim#857]
Easily add a plugin to your configuration files by choosing a plugin from a list.  This would have the same user interface as mode.sh.  Modify the lua files directly to add require statements for a chosen plugin.

**Comment by luxus** [comment]
thats a good idea.. still not sure if it is really necessary.
the issue with the wiki is that it its not easy just to copy paste the configs and with the wiki there is no option to PR plugins

**Comment by kylo252** [comment]
Closing since it's outdated and probably unnecessary anymore 😄
