### ISSUE TITLE
[Bug]: Color-scheme switching doesn't work when switching back to nvcode-color-schemes options

### ISSUE THREAD

**Issue by mattcoker** [LunarVim/LunarVim#942]
### Problem description

This happens on a fresh install of the rolling branch at this time. Not sure if I'm just dumb here but this seems like it should work.

1. Open a file with the default color scheme
2. Run `:colorscheme blue` or any color scheme you want
3. Run `:colorscheme spacegray`
4. Observe the color scheme DID NOT change
5. Run `:colorscheme default` or any built-in color scheme
6. Observe the color scheme DID change

Seems that built-in color schemes can be switched to, but the ones provided by `nvcode-color-schemes.vim` can't be switched to on-demand.

I encountered this bug while trying to set up a custom user config for [this github theme](https://github.com/projekt0n/github-nvim-theme). This bug occurs even without any of the config for that theme.

### LunarVim version

98430bd1082ebeaaabd7d01eb487be7580dcb939 (commit)

### Neovim version (>= 0.5)

0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by dfontana** [comment]
Experiencing a similar issue. I just updated to release [`0.4.8`](https://github.com/ChristianChiarulli/LunarVim/releases/tag/0.4.8) (so master branch) and found the `gruvbox` theme I was using bad broke :( I can no longer see those color schemes either in the `:Telescope colorscheme` selector. It looks like these themes were removed: https://github.com/ChristianChiarulli/nvcode-color-schemes.vim leaving the built-in or `spacegray` as the only options

**Comment by ChristianChiarulli** [comment]
This should be fixed now.
