### ISSUE TITLE
[Feature]: Add R support

### ISSUE THREAD

**Issue by JulianTao** [LunarVim/LunarVim#953]
I was following the updates and just want to thank all for the great project!

Would love to see language support for R. I got it partially work following the suggestions from Nvim-lspconfig but there are many details that I could not figure out (newbie in lua and programming in general). 
Thanks in advance.

**Comment by arxra** [comment]
Seems very similar to #328, Would that resolve this one as well?

**Comment by JulianTao** [comment]
Interesting it seems it was merged originally,   but somehow it was deleted in later updates?

**Comment by Uzaaft** [comment]
How do you get that #328 was merged originally? 
It says right there that Christian would merge it only if someone could confirm that it works. 
@JulianTao Could you go ahead and the fork, to see  if it works? If so, tag Christian, and inform him if it works. If it doesn't work, tag fanmih

**Comment by abzcoding** [comment]
@JulianTao can you test #965 to make sure it works for you?

after installing dependencies, use `<leader>lf` for formatting, or `:Format` for verbose formatting

**Comment by JulianTao** [comment]
> How do you get that #328 was merged originally?
> It says right there that Christian would merge it only if someone could confirm that it works.
> @JulianTao Could you go ahead and the fork, to see if it works? If so, tag Christian, and inform him if it works. If it doesn't work, tag fanmih

My bad. Github workflow is still fairly new to me. 
@abzcoding helped solved the problem. Thank you!

**Comment by lf-araujo** [comment]
Hi all,

What is needed in order to install the R lsp support? It is not listed in :LspInstall

**Comment by abzcoding** [comment]
@lf-araujo add this to your `~/.config/lvim/config.lua`
```lua

**Comment by lf-araujo** [comment]
Thanks so much, this is working pretty nicely!

Sorry if this is the wrong place, but if I try to add Nvim-R using the following:

```
-- Additional Plugins
lvim.plugins = {
    {"jalvesaq/Nvim-R"}
}
```

Nothing really happens, and lunar vim does not pick up the package's new keybindings. What are the steps to get a vimscript module working on lunarVim?

Thanks
