### ISSUE TITLE
Contest: Propose a Default Colorscheme

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#957]
LunarVim needs a good default colorscheme, spacegray is ok but it's nothing special. 

I will leave this thread up until maybe end of August mid September and choose the best theme proposed. 

The theme should be a good **default** theme so while nord and synthwave are cool I don't think they have what it takes to be the default. Think darkplus, oceanic and onedark.

**Comment by UltimateOmega** [comment]
I would suggest github-nvim-theme:
https://github.com/projekt0n/github-nvim-theme

**Comment by GlennLeo** [comment]
That would be great if it's "cobalt2"

**Comment by icupken** [comment]
I really like darkplus from vscode, it perfectly highlights most languages and comfortable enough for the eyes.

**Comment by gnmearacaun** [comment]
An extra challenge is to have a theme with comments clearly visible on a variety of backgrounds when transparency is enabled. There is an opportunity to solve that programatically ([issue #911](https://github.com/ChristianChiarulli/LunarVim/issues/911)) with spacegray for lunarvim.

**Comment by gnmearacaun** [comment]
> It's an added challenge to have one with bright enough comments when transparency is enabled. Otherwise I find I have to tweak the the grays (it helps with colorizer.nvim)

This is a transparent spin on `glepnir/zephyr-nvim` written in lua and works with treesitter. The background is set to 'none' but this can be changed. https://github.com/gnmearacaun/zephyr-clear.nvim

**Comment by gnmearacaun** [comment]
> It's an added challenge to have one with bright enough comments when transparency is enabled. Otherwise I find I have to tweak the the grays (it helps with colorizer.nvim)

This is a transparent spin on `glepnir/zephyr-nvim` written in lua and works with treesitter. The background is set to 'none' but this can be changed. https://github.com/gnmearacaun/zephyr-clear.nvim

**Comment by VDuchauffour** [comment]
Those variants of Onedark are cool too IMO (+1 for Cool and Warm styles)
https://github.com/navarasu/onedark.nvim/

**Comment by edward-mb** [comment]
I like Night-Owl
https://github.com/haishanh/night-owl.vim

**Comment by qvieth** [comment]
https://github.com/pbrisbin/vim-colors-off + ZenMode enable for default

**Comment by jp707049** [comment]
https://github.com/srcery-colors/srcery-vim
Official link - https://srcery-colors.github.io/
It has theme color for alaritty as well.

**Comment by zahin-muhaimeen** [comment]
In my opinion, I think One Dark should be the default colorscheme. Not only do I love it, there is proof out there of the amount of people that do ranging from themes for text editors, ide, browsers, terminals, tiling window managers and a lot more. But, this could be biased!

**Comment by MichaelSasser** [comment]
I really like [projekt0n/github-nvim-theme](https://github.com/projekt0n/github-nvim-theme) with `themeStyle = "dark"` or `themeStyle = "dimmed"`.

**Comment by lavixta** [comment]
I suggest gruvbox-flat. It is nice 
https://github.com/eddyekofo94/gruvbox-flat.nvim
<img width="786" alt="Screen Shot 2021-07-23 at 3 40 35 PM" src="https://user-images.githubusercontent.com/36840462/126757678-27aa084d-7df1-4b98-885c-34a7f7a28df1.png">

**Comment by luxus** [comment]
https://github.com/navarasu/onedark.nvim/
one more vote for one dark,  if I could only select one.
but GitHub, tokyo nights and srcery are really great themes too

**Comment by qvieth** [comment]
https://github.com/marko-cerovac/material.nvim +1 vote

**Comment by dimas-cyriaco** [comment]
https://github.com/arcticicestudio/nord-vim

**Comment by vontman** [comment]
I suggest `Neon`, https://github.com/rafamadriz/neon.

Looks similar to spacemacs which a lot of people are used to.

![image](https://user-images.githubusercontent.com/4175383/126899666-335b1527-5b9f-421b-a7f5-01c007935644.png)

**Comment by reedobrien** [comment]
PaperColor

**Comment by abzcoding** [comment]
i suggest this lazy loading multiple themes based on the time of the day
example
```lua
  {
    "folke/tokyonight.nvim",
    config = function()
      vim.g.tokyonight_hide_inactive_statusline = true
      local _time = os.date "*t"
      if _time.hour < 9 then
        vim.g.tokyonight_style = "night"
      end
      vim.cmd [[
      colorscheme tokyonight
      ]]
    end,
    cond = function()
      local _time = os.date "*t"
      return (_time.hour >= 0 and _time.hour < 16)
    end,
  },
  {
    "NTBBloodbath/doom-one.nvim",
    config = function()
      vim.g.doom_one_italic_comments = true
      vim.cmd [[
      colorscheme doom-one
      ]]
      -- vim.g.doom_one_terminal_colors = true
    end,
    cond = function()
      local _time = os.date "*t"
      return (_time.hour >= 16 and _time.hour < 20)
    end,
  },
  {
    "glepnir/zephyr-nvim",
    config = function()
      vim.cmd [[
      colorscheme zephyr
      ]]
    end,
    cond = function()
      local _time = os.date "*t"
      return (_time.hour >= 20 and _time.hour <= 24)
    end,
  },
```

**Comment by UltimateOmega** [comment]
> I'd suggest **lazy loading** multiple themes based on the time of the day

This is a great idea!

**Comment by pxsanghyo** [comment]
@abzcoding Thanks for that awesome config.
I have a question about setting colors for galaxyline.

Before changing config global from O to lvim, I had this which worked:
```lua
O.plugin.galaxyline.colors = require("tokyonight.colors").setup()
```

But changing it to this below, does nothing...
```lua
lvim.builtin.galaxyline.colors = require("tokyonight.colors").setup()
```

This is my full code (not working...)
```lua
lvim.builtin.galaxyline.colors = require("tokyonight.colors").setup()
lvim.plugins = {
  {
    "folke/tokyonight.nvim",
    config = function()
      vim.g.tokyonight_hide_inactive_statusline = true
      vim.g.tokyonight_style = "night"
      vim.cmd [[
      colorscheme tokyonight
      ]]
    end,
  },
}
```

**Comment by rebuilt** [comment]
Change the colorscheme declaration to

`lvim.colorscheme = "tokyonight"`

**Comment by qvieth** [comment]
onedark from https://github.com/ChristianChiarulli/nvcode-color-schemes.vim

![image](https://user-images.githubusercontent.com/71810726/128362540-e7a59270-f1c8-4475-a9d1-de7b767e2f9c.png)

**Comment by ashincoder** [comment]
So is the colorscheme decided yet.
I like a dark kinda material colorscheme

**Comment by SlippyJimmy** [comment]
zephyr-nvim
`A dark neovim colorscheme written in lua and syntax based on nvim-treesitter`

**Comment by ahmedkhalf** [comment]
I really like spacegray it's very nice theme

**Comment by ashincoder** [comment]
space gray should be a little darker. Then it would be better

**Comment by alexUplevel** [comment]
Base16-Ocean: Nord but everything is not blue!

**Comment by genesis-algorithms** [comment]
NvChat theme is pretty 🔥 IMO https://github.com/siduck76/NvChad

**Comment by 3301n** [comment]
Needs gruvbox colorscheme also needs a setting to change the default colorscheme, or does it aldready havee?

**Comment by genesis-algorithms** [comment]
+1 for the gruvbox scheme. I think it should be one of the default themes IMO.

**Comment by yudhiesh** [comment]
How do you change the colorscheme for the statusline?

**Comment by jimcornmell** [comment]
I use zenburn with LunarVim, because it looks nice and its available for loads of other tools, so you get consistent syntax highlighting, e.g:

- bat
- beyond compare
- eclipse
- vscode
- ranger
- Loads more..........

**Comment by Iron-E** [comment]
I would propose my own colorscheme, [`nvim-highlite`](https://github.com/Iron-E/nvim-highlite). I am biased, obviously, although its design is specifically based around readability rather than looking fancy.

Many users use blue-light filters at nighttime, and in most of the colorschemes I had used before developing `highlite` became unreadable after 5:00pm. This was a big issue for me, especially during late-night coding sessions when I would have to set my own colors for many shades of blue and green that had become synonymous to the background.

Further, the colorscheme consistently uses semantic highlights. You can tell what something is just by looking at it, allowing you to hunt around the page for specific types of tokens very easily. Duplicate highlight groups are rare, so you won't see an italic green for both `Identifier` and `Debug`.

Lastly, it has a long list of supported filetypes and plugins, and I'm updating it often. People are free to submit their own patches or request them.

I think I recall you used to have a colorscheme based on it called NvCode, though it eventually moved to something else. Could be misremembering.

**Comment by rebuilt** [comment]
Chris has chosen and implemented onedarker.  https://github.com/LunarVim/LunarVim/tree/rolling/lua/onedarker

**Comment by siduck76** [comment]
> Needs gruvbox colorscheme also needs a setting to change the default colorscheme, or does it aldready havee?

yes , we have like 3+ variants of gruvbox

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/135595417-8e2eb1b1-13b8-4e4a-bf9c-753b939bb658.png)

gruvchad
